### ISSUE TITLE
Cannot create project with `--style=styl` option

### ISSUE THREAD

**Issue by januwA** [angular/angular-cli#21364] opened 2021-07-18 12:15 UTC
# 🐞 Bug report

I am creating a single project, But the following error appeared

```
$ ng new ng-app --routing --skip-install --style=styl --directory=./ng-app --strict
Cannot parse arguments. See below for the reasons.
    Argument --style could not be parsed using value "styl". Valid values are: "css", "scss", "sass", "less".
```

This command worked before, but there is an error in the current version

```
λ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.1.2
Node: 14.17.3
Package Manager: npm 7.19.1
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1201.2 (cli-only)
@angular-devkit/core         12.1.2 (cli-only)
@angular-devkit/schematics   12.1.2 (cli-only)
@schematics/angular          12.1.2 (cli-only)
```

I am a user of stylus ❤️

**Comment by alan-agius4** [comment] 2021-07-18 12:23
Duplicate of https://github.com/angular/angular-cli/issues/21237

**Closed by alan-agius4** 2021-07-18 12:23 UTC

**Comment by januwA** [comment] 2021-07-18 14:19
Okay, I am a sass user now
