### ISSUE TITLE
100% in branching is not achieved in istanbul code coverage

### ISSUE THREAD

**Issue by RoopanV** [angular/angular-cli#7048] opened 2017-07-19 11:21 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
"@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "ng2-datetime": "^1.4.0",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"

### Repro steps.

When i am running ng test --code-coverage i am not getting branches covered 100% because of not covering constructor fully.

**Comment by devoto13** [comment] 2017-07-19 12:43
Possible duplicate of #5526.

**Comment by filipesilva** [comment] 2017-07-28 14:20
Closing as per @devoto13's comment.

**Closed by filipesilva** 2017-07-28 14:20 UTC
