### ISSUE TITLE
After upgraded Angular to v12, ng build production converting keywords inside angular brackets <> to lowercase 

### ISSUE THREAD

**Issue by JagdishWagh** [angular/angular-cli#23034] opened 2022-04-25 07:22 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After upgraded Angular to v12, ng build production converting keywords inside angular brackets <> to lowercase.

We are using index.jsp instead of index.html as index file, where java camelCase variables/methods are getting converted to lowercase with v12, and v11 it used to work fine. 

Is there any configuration we need add to resolve this?

Is there any package we need to update?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.15
Node: 14.15.0
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 12.2.15

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.17
@angular-devkit/build-angular   12.2.16
@angular-devkit/core            12.2.17
@angular-devkit/schematics      12.2.15
@angular/cdk                    12.2.13
@angular/language-service       12.1.3
@angular/upgrade                12.2.16
@schematics/angular             12.2.15
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by alan-agius4** [comment] 2022-04-25 11:34
Duplicate of https://github.com/angular/angular-cli/issues/20276#issuecomment-800053465

**Closed by alan-agius4** 2022-04-25 11:34 UTC
