### ISSUE TITLE
Warning: *.worker.ts is part of the TypeScript compilation but it's unused. Add only entry points to the 'files' or 'include' properties in your tsconfig.

### ISSUE THREAD

**Issue by HyperLife1119** [angular/angular-cli#20519] opened 2021-04-14 05:21 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 10.2.4

### Description

After upgrading from v10.2.4 to v11.2.8, warn when running the `ng build --prod` command: 
```
Warning: *.worker.ts is part of the TypeScript compilation but it's unused. Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

## 🔥 Exception or Error
<pre><code>
Warning: *.worker.ts is part of the TypeScript compilation but it's unused. Add only entry points to the 'files' or 'include' properties in your tsconfig.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.8
Node: 14.15.0
OS: win32 x64

Angular: 11.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8
@angular-devkit/build-angular   0.1102.8
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.4
@angular/cdk                    11.2.8
@angular/cli                    11.2.8
@schematics/angular             10.1.4
@schematics/update              0.1102.8
rxjs                            6.6.7
typescript                      4.0.7
</code></pre>

tsconfig.json:
```json
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true
  }
}
```

tsconfig.app.json:
```json
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

tsconfig.worker.json:
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/worker",
    "lib": [
      "es2018",
      "webworker"
    ],
    "types": []
  },
  "include": [
    "src/**/*.worker.ts"
  ]
}

```

**Anything else relevant?**

**Comment by HyperLife1119** [comment] 2021-04-14 05:24
package.json:
```json
"dependencies": {
    "@angular/animations": "^11.2.9",
    "@angular/cdk": "^11.2.8",
    "@angular/common": "^11.2.9",
    "@angular/core": "^11.2.9",
    "@angular/forms": "^11.2.9",
    "@angular/platform-browser": "^11.2.9",
    "@angular/platform-browser-dynamic": "^11.2.9",
    "@angular/router": "^11.2.9",
    "@angular/service-worker": "^11.2.9",
    "@capacitor/android": "^2.4.7",
    "@capacitor/core": "2.4.7",
    "@ionic/angular": "^5.6.4",
    "core-js": "^3.10.1",
    "hammerjs": "^2.0.8",
    "ngx-cookie-service": "^10.1.1",
    "ngx-image-cropper": "^3.3.5",
    "ngx-quill": "^12.0.1",
    "ngx-socket-io": "^3.3.1",
    "quill": "^1.3.7",
    "rxjs": "^6.6.7",
    "swiper": "^6.5.6",
    "tslib": "^2.0.0",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1102.8",
    "@angular/cli": "^11.2.8",
    "@angular/compiler": "^11.2.9",
    "@angular/compiler-cli": "^11.2.9",
    "@angular/language-service": "^11.2.9",
    "@capacitor/cli": "2.4.7",
    "@ionic/angular-toolkit": "^2.3.3",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^14.14.37",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "^5.2.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "^7.0.0",
    "ts-node": "~9.0.0",
    "tslint": "~6.1.3",
    "typescript": "~4.0.2",
    "webpack-bundle-analyzer": "^4.4.1"
  }
```

**Comment by alan-agius4** [comment] 2021-04-14 05:37
Do you have multiple web workers ?

**Comment by HyperLife1119** [comment] 2021-04-14 05:39
Yes, I have two web workers.

**Comment by alan-agius4** [comment] 2021-04-14 05:39
Duplicate of #19938

**Closed by alan-agius4** 2021-04-14 05:39 UTC
