### ISSUE TITLE
`outDir` in `angular-cli.json` is not working

### ISSUE THREAD

**Issue by Meligy** [angular/angular-cli#2230] opened 2016-09-19 20:40 UTC
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

  OSX Yosemite

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

  ```
angular-cli: 1.0.0-beta.14
node: 6.3.1
os: darwin x64
  ```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

  ```
ng new sample-app
cd sample-app
  ```

  Then open `angular-cli.json` and change `outDir` from `"dist"` to `"dist2"`

  ```
ng build
  ```

4. The log given by the failure. Normally this include a stack trace and some
   more information.

  No tool failure, but wrong outcome.

  The output would still go to `dist` (actual) instead of `dist2` (expected).

5. Mention any other details that might be useful.

  I first tried this with `../external-folder` and thought the `../` was the problem, but even just changing the folder name doesn't work.

**Comment by Meligy** [comment] 2016-09-20 04:49
Note:

Changing the output directory from the `ng build` command itself works just fine.

Both `ng build -o dist2` and `ng build -o ../external-folder` will output to `dist2` and `../external-folder` respectively, even on Windows (so, it's not OS seems irrelevant here).

It's changing `outDir` in `angular-cli.json` that seems to do nothing though.

**Comment by osnoser1** [comment] 2016-09-21 04:39
Same issue in Windows 10, angular-cli: 1.0.0-beta.15, node: 6.5.0.

**Comment by filipesilva** [comment] 2016-09-22 04:26
Dupe of https://github.com/angular/angular-cli/issues/2006

**Closed by filipesilva** 2016-09-22 04:26 UTC

**Comment by notresponding2u** [comment] 2018-03-21 11:32
Try something like "./dist2". For me that worked even when I want it to build outside the project root.
