### ISSUE TITLE
MergeStrategy seems to be completely broken (mergeWith failure)

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12118] opened 2018-09-04 23:18 UTC
_From @kevin-anidjar on April 19, 2018 21:45_

### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ x ] schematics
```

### Versions

Node v8.11.1
NPM 5.8.0
Mac OS High Sierra

### Repro steps

Use the following schematic

```javascript
import { Rule, url, apply, mergeWith, chain, MergeStrategy } from '@angular-devkit/schematics';

export function index(): Rule {
  return chain([
    simpleMerge(),
  ])
}

function simpleMerge(): Rule {
    
    const source = url('./files');

    return mergeWith(source, MergeStrategy.Overwrite);
}

```
### The log given by the failure

```

schematics .:boilerplate

ERROR! /src/app/app.component.html already exists.
ERROR! /src/app/app.component.spec.ts already exists.
ERROR! /src/app/app.component.ts already exists.
ERROR! /src/app/app.module.ts already exists.
ERROR! /src/assets/.gitkeep already exists.
ERROR! /src/environments/environment.prod.ts already exists.
ERROR! /src/environments/environment.ts already exists.
ERROR! /src/index.html already exists.
```
### Desired functionality

All files should be overwritten.

### Mention any other details that might be useful

I tried every MergeStrategy possible (AllowOverwriteConflict, etc.), same result.

_Copied from original issue: angular/devkit#745_

**Comment by alan-agius4** [comment] 2018-10-11 13:43
Duplicate of https://github.com/angular/angular-cli/issues/11337

**Closed by alan-agius4** 2018-10-11 13:43 UTC
