### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by doovers** [angular/angular-cli#8245] opened 2017-10-29 22:37 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.9
node: 6.10.3
os: darwin x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4

### Repro steps.
Not sure how to reproduce. The issue shows up intermittently.

### The log given by the failure.
[Error] ReferenceError: Can't find variable: webpackJsonp
	Global Code (polyfills.bundle.js:1)
[Error] ReferenceError: Can't find variable: webpackJsonp
	Global Code (styles.bundle.js:1)
[Error] ReferenceError: Can't find variable: webpackJsonp
	Global Code (vendor.bundle.js:1)

**Comment by avbentem** [comment] 2017-11-08 19:26
That's not a lot of detail to go on.

Any chance you're **not** using the default `index.html` in which the required JavaScript bundles are inserted automatically, but instead are using some other means to insert the bundles?

(If yes, then see https://stackoverflow.com/a/41829100.)

**Comment by doovers** [comment] 2017-11-13 02:43
@avbentem Yes, apologies for the lack of detail I was in a bit of a rush posting and was hoping it might be an obvious fix for someone! To elaborate a little it occurs in one of 2 almost identical components. It renders the page the first time around but if I hit refresh, it will give me those errors. If I go back a page and navigate to it again it will render properly again. The same error occurs if I make a change to a file and it reloads. Hopefully, that clarifies things a little? Oh and I'm using the default index.html. No customisations there...

**Comment by filipesilva** [comment] 2017-11-24 10:08
I think this issue is a duplicate of #8026. Can you add a repro and details there please? With just the information here there isn't much we can do to address it.

**Closed by filipesilva** 2017-11-24 10:08 UTC
