### ISSUE TITLE
ng build --watch does not work when building a library

### ISSUE THREAD

**Issue by jrista** [angular/angular-cli#11617] opened 2018-07-20 21:19 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

➜ node -v 
v8.11.2

➜ npm -v
5.6.0

➜ npx ng -v

         _                      _                 ____ _     ___
        / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
       / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
      / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
     /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                    |___/
    

Angular CLI: 6.0.8
Node: 8.11.2
OS: darwin x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cdk                       6.4.0
@angular/cli                       6.0.8
@angular/flex-layout               6.0.0-beta.16
@angular/material                  6.4.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
ng-packagr                         3.0.3
rxjs                               6.2.2
typescript                         2.7.2
webpack                            4.8.3

### Repro steps

In any CLI library project:

`npx ng build [your-project-name] --watch`

### The log given by the failure

➜ npx ng build my-lib-project --watch 
Unknown option: '--watch'

### Desired functionality

Library project will build automatically whenever any of it's files change.

**Comment by alan-agius4** [comment] 2018-07-21 07:20
Duplicate of 
https://github.com/angular/angular-cli/issues/11100

**Comment by filipesilva** [comment] 2018-07-23 10:30
Closing as per @alan-agius4's comment 👍

**Closed by filipesilva** 2018-07-23 10:30 UTC
