### ISSUE TITLE
Cannot read property 'glob' of null

### ISSUE THREAD

**Issue by manoz2000** [angular/angular-cli#5580] opened 2017-03-23 07:48 UTC
C:\xampp\htdocs\hello-angular>ng serve
**Cannot read property 'glob' of null**
TypeError: Cannot read property 'glob' of null
    at ObjectSchemaTreeNode._set (C:\xampp\htdocs\hello-angular\node_modules\@ng
tools\json-schema\src\schema-tree.js:224:131)
    at new ObjectSchemaTreeNode (C:\xampp\htdocs\hello-angular\node_modules\@ngt
ools\json-schema\src\schema-tree.js:209:14)
    at OneOfSchemaTreeNode._createChildProperty (C:\xampp\htdocs\hello-angular\n
ode_modules\@ngtools\json-schema\src\schema-tree.js:148:26)
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (C:\xampp\htdocs\hel
lo-angular\node_modules\@ngtools\json-schema\src\schema-tree.js:161:25)
    at Array.map (native)
    at OneOfSchemaTreeNode (C:\xampp\htdocs\hello-angular\node_modules\@ngtools\
json-schema\src\schema-tree.js:160:48)
    at ArraySchemaTreeNode._createChildProperty (C:\xampp\htdocs\hello-angular\n
ode_modules\@ngtools\json-schema\src\schema-tree.js:148:26)
    at ArraySchemaTreeNode._set (C:\xampp\htdocs\hello-angular\node_modules\@ngt
ools\json-schema\src\schema-tree.js:286:39)
    at new ArraySchemaTreeNode (C:\xampp\htdocs\hello-angular\node_modules\@ngto
ols\json-schema\src\schema-tree.js:267:14)
    at ObjectSchemaTreeNode._createChildProperty (C:\xampp\htdocs\hello-angular\
node_modules\@ngtools\json-schema\src\schema-tree.js:148:26)

Its duplicate of 
#5231
#4919
#4889
#4207

still not solve the issue

**Comment by filipesilva** [comment] 2017-03-23 21:26
Dupe of https://github.com/angular/angular-cli/issues/4207, fixed in https://github.com/angular/angular-cli/pull/5523, out next release.

**Closed by filipesilva** 2017-03-23 21:26 UTC

**Comment by balr404** [comment] 2017-05-09 23:01
I have tried the following option to resolve the issue
Steps to resolve the issue

$ pwd
it shows —> /Users/YourName /*** That is your Home path***/
Execute the below command to display the hidden files

$ defaults write com.apple.Finder AppleShowAllFiles true
$ killall Finder
After executing the above command you will see the hidden files.
if “.angular-cli.json” file exist under “/Users/yourname” (i.e Home Path) then remove “.angular-cli.json” file.

then navigate to your application path and try execute ‘ng’ command.

**Comment by kirillgroshkov** [comment] 2017-08-30 21:21
Still doesn't work for me!
