### ISSUE TITLE
Specify default port

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular-cli#4173] opened 2017-01-23 08:40 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.25.5
node: 6.2.0
os: win32 x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

### Mention any other details that might be useful.

The default port (4200) should be configurable in angular-cli.json. 

Scenario: We are working on several projects which all use a single open id connect server. This server needs to register all the frontend apps with their urls for security reasons. So every developer must launch the frontend apps on the correct port. This would be a lot easier to manage if the default port was configured in json file and so synchronized via git.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2017-01-24 13:51
Dupe of https://github.com/angular/angular-cli/issues/1156

**Closed by filipesilva** 2017-01-24 13:51 UTC
Labels: command: build, priority: 3 (nice to have), type: enhancement
