### ISSUE TITLE
Can't find stylesheet to import with v17

### ISSUE THREAD

**Issue by lgpage** [angular/angular-cli#26702] opened 2023-12-18 20:12 UTC
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.12

### Description

I just migrated an existing Angular project on a Windows PC from 15.2.9 to 16.2.12, then to 17.0.4 and got an error 

### Minimal Reproduction

Take any ng v16.2x project with a global style sheet and upgrade it to v17

### Exception or Error

```text
./src/styles.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
  ╷
3 │ @import "@angular/material/theming";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\styles\theme.scss 3:9  @import
  src\styles.scss 1:9        root stylesheet

./src/styles.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
  ╷
3 │ @import "@angular/material/theming";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\styles\theme.scss 3:9  @import
  src\styles.scss 1:9        root stylesheet
```

### Your Environment

```text
Angular CLI: 17.0.7
Node: 18.17.1
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 17.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.7
@angular-devkit/build-angular   17.0.7
@angular-devkit/core            17.0.7
@angular-devkit/schematics      17.0.7
@angular/cdk                    17.0.4
@angular/material               17.0.4
@schematics/angular             17.0.7
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

Also see

- https://github.com/angular/angular-cli/issues/26088
- https://github.com/angular/angular-cli/issues/25660

**Comment by clydin** [comment] 2023-12-18 23:25
The referenced issues are from projects that are using the new build system available within v17. However, from the error shown above your project is using the existing build system (Webpack-based).

Please provide a minimal reproduction demonstrating the problem so that we can further investigated.

**Comment by tortuc** [comment] 2023-12-19 15:07
I think it's Angular material issue, After checking node_mdoules, I found that there is no file /@angular/material/_theming.scss in Angular Material 17, But it is exist when you install Angular material 16.

**Comment by JoostK** [comment] 2023-12-19 15:45
Closing as duplicate of https://github.com/angular/components/issues/28204

**Closed by JoostK** 2023-12-19 15:45 UTC
Labels: needs: repro steps

**Comment by Bullsized** [comment] 2024-01-11 09:50
> I think it's Angular material issue, After checking node_mdoules, I found that there is no file /@angular/material/_theming.scss in Angular Material 17, But it is exist when you install Angular material 16.

This is true, since the `` version has NO theming SCSS file in it, the whole structure has changed and no one warned about it:
![image](https://github.com/angular/angular-cli/assets/26943431/4da7b10f-a803-4f81-8548-612f18b4045f)

@lgpage I am also getting the same error as you, have you managed to fix it?
![image](https://github.com/angular/angular-cli/assets/26943431/293c14ad-55eb-43ce-953f-07456159ad8f)

**Comment by meganmuirhead** [comment] 2024-01-19 18:56
I am having a similar issue. i am trying to use the cli to upgrade and when running ng build, i am getting this error.
![image](https://github.com/angular/angular-cli/assets/16979732/0d230601-e8c4-414e-a550-d98d83733db6)
I tried to update to what was in the node modules but that path also isn't working, does anyone have any fixes/suggestions?

**Comment by nishanc** [comment] 2024-02-13 20:53
Was able fix this by adding `stylePreprocessorOptions` like this on CLI version 17.1.3

```
"styles": [
  ....
]
"scripts": [
  ....
],
"stylePreprocessorOptions": {
  "includePaths": ["node_modules/"]
}
```
