### ISSUE TITLE
ng generate doesn't initialize component stylesheets with specified styles type

### ISSUE THREAD

**Issue by avatsaev** [angular/angular-cli#7721] opened 2017-09-17 13:28 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.2
node: 8.5.0
os: linux x64
@angular/animations: 4.4.1
@angular/common: 4.4.1
@angular/compiler: 4.4.1
@angular/core: 4.4.1
@angular/forms: 4.4.1
@angular/http: 4.4.1
@angular/platform-browser: 4.4.1
@angular/platform-browser-dynamic: 4.4.1
@angular/router: 4.4.1
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.1
@angular/language-service: 4.4.1
typescript: 2.5.2

### Repro steps.

- Create a new project with --style=sass

OR

- Specify in .angular-cli.json

```

  "defaults": {
    "styleExt": "sass",
    "component": {}
  }

```

- Generate a new components with `ng g c home`

It will generate a component with css stylesheet instead of sass

**Comment by AhsanAyaz** [comment] 2017-09-19 00:19
Duplicate of #7624, #7644, #7647, #7708, #7715, #7719 & #7522

**Comment by Brocco** [comment] 2017-09-22 16:59
Closing as a duplicate.

**Closed by Brocco** 2017-09-22 16:59 UTC
