### ISSUE TITLE
ngtools with nested lazy modules routing

### ISSUE THREAD

**Issue by jmpmscorp** [angular/angular-cli#3593] opened 2016-12-16 06:42 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> angular-cli: 1.0.0-beta.22-1
node: 6.7.0
os: win32 x64

### Repro steps.
Suppose there are two nested lazy modules routes like this:

**Module A: app-routing.module**

`export const routes: Routes = [
  { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
  { path: 'login', loadChildren: './login/login.module#LoginModule' },
  { path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardModule'}
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule {}`

**Module B (lazy module with another lazy module) dashboard-routing.module:**

`const routes: Routes = [
  { path: '', component: DashboardComponent, pathMatch: 'full' },
  { path: 'explotaciones', component: DashboardComponent,
    children: [
        { path: '', loadChildren: './explotaciones/explotaciones.module#ExplotacionesModule'}
      ]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class DashboardRoutingModule {}`

### The log given by the failure.
Error: Could not resolve route "./explotaciones/explotaciones.module#ExplotacionesModule" from file "D:\Code\DL-GEST\src\client\app\dashboard\dashboard.module".
    at D:\Code\DL-GEST\node_modules\@ngtools\webpack\src\plugin.js:280:23
    at Array.map (native)
    at AotPlugin._processNgModule (D:\Code\DL-GEST\node_modules\@ngtools\webpack\src\plugin.js:275:14)
    at _loop_1 (D:\Code\DL-GEST\node_modules\@ngtools\webpack\src\plugin.js:309:35)
    at AotPlugin._processNgModule (D:\Code\DL-GEST\node_modules\@ngtools\webpack\src\plugin.js:328:13)
    at D:\Code\DL-GEST\node_modules\@ngtools\webpack\src\plugin.js:242:39
    at process._tickCallback (internal/process/next_tick.js:103:7)
 70% building modules 716/716 modules 0 active

### Mention any other details that might be useful.
I have been looking for the error and I find a problem in plugin.js. At line 274, this.extractLoading function use a variable called 'relativeModulePath'. With module A, this variable use '/' on paths (D:/Code/DL-GEST/src/client/app/app.module) and there is no problem with it, but with module B, this variable use '\\' on path and then, emit error I wrote lines before.

I have changed function `var relativeModulePath = this._resolveModulePath(module, containingFile)` to
`var relativeModulePath = this._resolveModulePath(module, containingFile).replace(/\\/g,'/')` and it solves my problems.

Is there a better approach to solve it??

Thanks and excuse my english :). 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Destreyf** [comment] 2016-12-17 00:16
@jmpmscorp I can confirm this behavior, and that your fix resolves the issue.

**Comment by filipesilva** [comment] 2016-12-30 16:24
Marking as dupe of https://github.com/angular/angular-cli/issues/3663 since it has a bit more discussion.

**Closed by filipesilva** 2016-12-30 16:24 UTC
Labels: package: @ngtools/webpack, priority: 1 (urgent), type: bug

**Comment by Destreyf** [comment] 2016-12-30 17:11
@filipesilva This was an issue in beta.22 (more specifically the @ngtools for that release so going back to 21 still had the same issue) this does not affect beta.24, and the fix does not work for beta.24 either. #3663 is a newly introduced problem that prevents nested lazy loading beyond a certain depth.

**Comment by filipesilva** [comment] 2016-12-30 17:17
Hm, I see. I guess then it's closed as fixed, since it doesn't affect beta.24 and we can't fix the old one anyway.

**Comment by chrillewoodz** [comment] 2017-01-04 06:48
@Destreyf What is this fix that you mention? ;s
