### ISSUE TITLE
angular-devkit failing on calling other rules that returns a Tree

### ISSUE THREAD

**Issue by cenk1cenk2** [angular/angular-cli#24014] opened 2022-10-05 11:09 UTC
### Command

other

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.1.3

### Description

Hello dear maintainers,

With the recent refactoring on the @angular-devkit/schematics [here](https://github.com/angular/angular-cli/commit/398d66af4fd7fe5bcb0161428d832de1c228d16c), calling an external schematic that works by itself without problems where it returns a Tree as Rule fails with searching with the in operator inside a Symbol.

### Minimal Reproduction

Unfortunately, this is not really CLI related but related to a custom schematic that our company uses.

### Exception or Error

```text
TypeError: Cannot use 'in' operator to search for 'Symbol(schematic-tree)' in null
    at callRuleAsync (/home/cenk/development/work/nx-test/node_modules/@angular-devkit/schematics/src/rules/call.js:89:32)


 >  NX   Cannot use 'in' operator to search for 'Symbol(schematic-tree)' in null


TypeError: Cannot use 'in' operator to search for 'Symbol(schematic-tree)' in null
    at callRuleAsync (/home/cenk/development/work/nx-test/node_modules/@angular-devkit/schematics/src/rules/call.js:89:32)
```
```


### Your Environment

```text
"@angular-devkit/architect": "^0.1402.4",
    "@angular-devkit/core": "^14.2.4",
    "@angular-devkit/schematics": "^14.2.4",
```

**Comment by alan-agius4** [comment] 2022-10-05 12:32
@cenk1cenk2, based on the above errors it seems that the problem is when a rule returns `null` not when it returns a `Tree`.

**Comment by alan-agius4** [comment] 2022-10-06 07:05
Closing via https://github.com/angular/angular-cli/pull/24016 which now displays a more actionable error when a rule returns `null`.

**Closed by alan-agius4** 2022-10-06 07:05 UTC

**Comment by cenk1cenk2** [comment] 2022-10-06 09:19
Hey @alan-agius4,

Thank you for this and sorry for missing the obvious!
