### ISSUE TITLE
Schematic "ng-new" not found in collection "@schematics/angular".

### ISSUE THREAD

**Issue by ukaaa** [angular/angular-cli#11074] opened 2018-05-31 15:00 UTC
### Versions
```
Angular CLI: 6.0.7
Node: 10.3.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    <error>
@angular-devkit/core         0.6.7
@angular-devkit/schematics   0.6.7
@schematics/angular          0.6.7
@schematics/update           <error>
rxjs                         6.2.0

npm: 6.1.0
OS: macOS High Sierra 10.13.4
```

### Repro steps
`npm i -g @angular/cli`
`ng new`

### Observed behavior
```
Schematic "ng-new" not found in collection "@schematics/angular".
Error: Schematic "ng-new" not found in collection "@schematics/angular".
    at SchematicEngine.createSchematic (/Users/nicholas/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:155:23)
    at CollectionImpl.createSchematic (/Users/nicholas/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/collection.js:12:29)
    at Object.getSchematic (/Users/nicholas/node_modules/@angular/cli/utilities/schematics.js:36:23)
    at NewCommand.getOptions (/Users/nicholas/node_modules/@angular/cli/models/schematic-command.js:194:40)
    at NewCommand.initialize (/Users/nicholas/node_modules/@angular/cli/commands/new.js:48:21)
    at Object.<anonymous> (/Users/nicholas/node_modules/@angular/cli/models/command-runner.js:87:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nicholas/node_modules/@angular/cli/models/command-runner.js:4:58)
```

### Desired behavior
No error.

**Comment by clydin** [comment] 2018-05-31 19:08
Duplicate of #10691

**Closed by clydin** 2018-05-31 19:08 UTC
