### ISSUE TITLE
ng build fails to properly export styles from styles.bundle.js when referenced styles are in symlinked node_modules directory

### ISSUE THREAD

**Issue by scottseeker** [angular/angular-cli#7265] opened 2017-08-03 18:14 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.9.4
os: win32 x64
npm: 4.1.2

### Repro steps.
1.) in angular-cli.json, under the 'styles' section, reference a css file that is in node_modules, where node_modules is a symlink to a node_modules folder in another directory

2.) ng build and run web application on a server

3.) styles will show up in the styles.bundle.js, but they will never be injected into a head tag and you will not see them working on your site

### Desired functionality.
Works the same whether the node_modules directory is a symlink or not.  Working with node on Windows can be painful because of file path length restrictions and simply moving the directory (not using a symlink) is not always a viable option.

**Comment by filipesilva** [comment] 2017-08-21 11:46
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/3500. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-08-21 11:46 UTC
Labels: priority: 2 (required), severity3: broken
