### ISSUE TITLE
Broken links in Readme.md

### ISSUE THREAD

**Issue by sergiator** [angular/angular-cli#4449] opened 2017-02-06 08:46 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS + Web Browsers
>Linux (Ubuntu 14.04 LTS), Firefox 49.0, Chrome 53.0.2785.143 (64-bit)

### Mention any other details that might be useful.

This links are broken:

[![Dependency Status][david-badge]][david-badge-url]
[![devDependency Status][david-dev-badge]][david-dev-badge-url]
[![npm][npm-badge]][npm-badge-url]

[david-badge]: https://david-dm.org/angular/angular-cli.svg
[david-badge-url]: https://david-dm.org/angular/angular-cli
[david-dev-badge]: https://david-dm.org/angular/angular-cli/dev-status.svg
[david-dev-badge-url]: https://david-dm.org/angular/angular-cli?type=dev
[npm-badge]: https://img.shields.io/npm/v/@angular/cli.svg
[npm-badge-url]: https://www.npmjs.com/package/@angular/cli

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment] 2017-02-06 10:10
Most likely dupe of #4443

**Comment by filipesilva** [comment] 2017-03-09 11:30
We've fixed this since, thanks for the report!

**Closed by filipesilva** 2017-03-09 11:30 UTC
