### ISSUE TITLE
When building services with a broad browser target, why not use core-js within angular/cli?

### ISSUE THREAD

**Issue by jiho9505** [angular/angular-cli#27768] opened 2024-06-04 01:56 UTC
### Command

build

### Description

hello.
I have a question regarding polyfill injection using core-js.

The current browser target for our service is ES5, and we are considering upgrading to ES6.

In other words, when upgrading to ES6, all users with Chrome version 61 or higher should be able to use the service.

However, there is something confusing during the review.
Differential loading has disappeared from Angular since version 13, 
and the latest Angular seems to target those versions as shown in the document below.
ㄴ https://angular.dev/reference/versions#browser-support
<img width="741" src="https://github.com/angular/angular-cli/assets/50862052/806ec83d-2140-4377-8157-fc93d74c648e">

Additionally, looking at the angular/cli code, 
it seems that transpiling to the target will work fine when Chrome >= 61, but there is no part to inject core-js.
In other words, we felt that a separate polyfill for ECMAScript was needed in order for the users we were targeting to use the service properly.
<img width="318" src="https://github.com/angular/angular-cli/assets/50862052/371e53db-aaa1-41db-b168-18ccd0e96b62">
<img width="585"  src="https://github.com/angular/angular-cli/assets/50862052/7c51e619-2273-4200-a6ae-5546949a382c">

I have two questions.

1. I am curious as to whether Angular did not use core-js because it was intended to target the latest browsers as shown in the document above. Also, there may be services that support a wide browser target like ours, but I am wondering if there are any plans to include core-js.

2. If there are no plans to modify, In order to inject polyfills for ECMAScript functions, 
should services that use Angular go in the direction of specifying core-js separately in polyfills.ts?

Thank you for reading. I know that you always put a lot of effort into creating a good framework, and I am grateful.

### Describe the solution you'd like

Inserting core-js when building

### Describe alternatives you've considered

I can't think of any additional alternatives. I think it would be a good idea to tell us whether each service needs to import it separately.

**Comment by alan-agius4** [comment] 2024-06-04 06:10
Duplicate of https://github.com/angular/angular-cli/issues/27510

**Closed by alan-agius4** 2024-06-04 06:10 UTC
