### ISSUE TITLE
inter library dependency inside a workspace: Cannot find module 'library1'

### ISSUE THREAD

**Issue by gbharathkumar** [angular/angular-cli#10780] opened 2018-05-10 10:23 UTC
### Versions
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / ? \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0
@angular-devkit/core         0.6.0
@angular-devkit/schematics   0.6.0
@schematics/angular          0.6.0
@schematics/update           0.6.0
rxjs                         6.1.0
typescript                   2.7.2


```

### Repro steps
* create a new angular 6 workspace with an application
* add two libraries named library1, library2
* refer library1 in library2 package.
* compile library1 using ng build --project=library1
* compile library2 using ng build --project=library2

### Observed behavior
```
* getting exception projects/library2/src/lib/library2.module.ts(3,36): error TS2307: Cannot find module 'library1'.

```

### Mention any other details that might be useful (optional)

1) setting the output of library1 to node_modules doesn't work as ng_packagr is not generating the public_api.ts file if the dest path is node_modules. 
2) even adding paths to tsconfig.lib.json doesn't get reflected, neither does the paths in the root tsconfig.json

**Comment by wulfsberg** [comment] 2018-05-10 12:32
Duplicate of #10665?
While it would be nice to have it working out of the box, I got my project working the same way @aitboudad suggests in https://github.com/angular/angular-cli/issues/10665#issuecomment-387494405, i.e. adding `paths` to the other library's dist output.

You'd need something like
```
"paths": {
  "library1": [
	"../../../dist/library1"
  ]
}
```
in the `compilerOptions` of library2's `tsconfig.lib.json`

**Comment by gmfun** [comment] 2018-05-10 12:35
I have created a stackoverflow qoestion with a solution for this. Doesn't look like cli issue.

**Comment by clydin** [comment] 2018-05-10 15:56
Duplicate of #10665

**Closed by clydin** 2018-05-10 15:56 UTC

**Comment by playground** [comment] 2018-05-13 21:11
I have the same issue with using npm @scope.
```
@scope/library1
@scope/library2

ng build @scope/library1
in library2, import {} from '@scope/library1', vscode cannot find it.

This maybe a separate issue when I tried to build @scope/library2 anyway
ng build @scope/library2
Building Angular Package

BUILD ERROR
Cannot read property 'isSkipSelf' of null
TypeError: Cannot read property 'isSkipSelf' of null
    at ProviderElementContext._getDependency (/git_repo/sandbox/node_modules/@angular/compiler/bundles/compiler.umd.js:11389:18)
    at /git_repo/sandbox/node_modules/@angular/compiler/bundles/compiler.umd.js:11334:60
    at Array.map (<anonymous>)
    at /git_repo/sandbox/node_modules/@angular/compiler/bundles/compiler.umd.js:11334:26
    at Array.map (<anonymous>)
    at ProviderElementContext._getOrCreateLocalProvider (/git_repo/sandbox/node_modules/@angular/compiler/bundles/compiler.umd.js:11312:63)
    at /git_repo/sandbox/node_modules/@angular/compiler/bundles/compiler.umd.js:11210:23
    at Array.forEach (<anonymous>)
    at new ProviderElementContext (/git_repo/sandbox/node_modules/@angular/compiler/bundles/compiler.umd.js:11207:49)
    at TemplateParseVisitor.visitElement (/git_repo/sandbox/node_modules/@angular/compiler/bundles/compiler.umd.js:14961:31)

**Comment by playground** [comment] 2018-05-14 14:30
It's working now after npm install @scope/library1 in project library1.

**Comment by wulfsberg** [comment] 2018-05-14 14:40
Likely due to https://github.com/dherges/ng-packagr/pull/862, which obsoletes the workaround with paths in `tsconfig.lib.json`.
