### ISSUE TITLE
Could not read Angular module file: /src/@app/app.module.ts

### ISSUE THREAD

**Issue by kasir-barati** [angular/angular-cli#23407] opened 2022-06-20 19:41 UTC
Oh hi there! 😄

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [:negative_squared_cross_mark:] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
IDK but I guess it won't be working at all

## 🔬 Minimal Reproduction & Description

Add this in `tsconfig.json`: `"paths":{ "@app/*": ["src/app/*"] }` and then [in the `main.ts` I imported like this](https://github.com/kasir-barati/task-tracker-traversy-media/blob/d90eb32581d8a908d6dea805f8d2758d24011a52/src/main.ts#L4).

## 🔥 Exception or Error

<pre><code>
[kasir@kasir task-tracker-traversy-media]$ ng add @angular/material
Skipping installation: Package already installed
? Choose a prebuilt theme name, or "custom" for a custom theme: Purple/Green       [ Preview: 
https://material.angular.io?theme=purple-green ]
? Set up global Angular Material typography styles? Yes
? Include the Angular animations module? Include and enable animations
UPDATE package.json (1905 bytes)
✔ Packages installed successfully.
Could not read Angular module file: /src/@app/app.module.ts
</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.2
Node: 18.2.0 (Unsupported)
Package Manager: pnpm 7.2.1 
OS: linux x64

Angular: 14.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.1
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.1
@angular-devkit/schematics      14.0.1
@schematics/angular             14.0.1
rxjs                            7.5.5
typescript                      4.7.4
    
Warning: The current version of Node (18.2.0) is not supported by Angular.
</code></pre>

**Anything else relevant?**

https://github.com/angular/angular-cli/issues/11499

# Temporary nutty as a fruitcake solution

Remove the config from `tsconfig.json`
![image](https://user-images.githubusercontent.com/73785723/174668824-76e1d927-c064-4b4d-888b-731108dcfb11.png)

**Comment by alan-agius4** [comment] 2022-06-20 20:41
Duplicate of https://github.com/angular/angular-cli/issues/12740

**Closed by alan-agius4** 2022-06-20 20:41 UTC
