### ISSUE TITLE
After upgrading to Angular v12, hashes (#) were added to the RGB color format 

### ISSUE THREAD

**Issue by yumadilovtimur** [angular/angular-cli#20869] opened 2021-05-20 11:15 UTC
After upgrading to Angular v12, hashes (#) were added to the RGB color format
It was:
![image](https://user-images.githubusercontent.com/40427062/118969462-8733b080-b986-11eb-87e3-9ce4dfb7554f.png)

Become:
![image](https://user-images.githubusercontent.com/40427062/118969511-90248200-b986-11eb-8369-e11c722f82cc.png)

My **angular.json**:
```
              "optimization": {
                "scripts": true,
                "styles": {
                  "inlineCritical": true,
                  "minify": true
                },
                "fonts": {
                  "inline": true
                }
              }
```
If you set **false** for the **minify** property, there is no problem

**package.json**:
```
{
  "name": "front-end",
  "version": "0.0.0",
  "scripts": {
  ...
  },
  "lint-staged": {
    "*.{ts,html}": "eslint --fix",
    "*.scss": "stylelint --fix --syntax scss"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged --relative"
    }
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.0.0",
    "@angular/cdk": "^12.0.0",
    "@angular/common": "~12.0.0",
    "@angular/compiler": "~12.0.0",
    "@angular/core": "~12.0.0",
    "@angular/forms": "~12.0.0",
    "@angular/platform-browser": "~12.0.0",
    "@angular/platform-browser-dynamic": "~12.0.0",
    "@angular/platform-server": "~12.0.0",
    "@angular/router": "~12.0.0",
    "@angular/service-worker": "~12.0.0",
    "@nguniversal/express-engine": "^12.0.0",
    "@sentry/angular": "^6.3.6",
    "@sentry/tracing": "^6.3.6",
    "angular-google-tag-manager": "^1.3.2",
    "atms": "file:atms-0.0.1.tgz",
    "classlist.js": "^1.1.20150312",
    "css-vars-ponyfill": "^2.4.5",
    "express": "^4.15.2",
    "guid-typescript": "^1.0.9",
    "intl": "^1.2.5",
    "jwt-decode": "^3.1.2",
    "localstorage-polyfill": "^1.0.1",
    "lottie-web": "^5.7.8",
    "ngx-cookie-service": "^11.0.2",
    "ngx-device-detector": "^2.0.10",
    "ngx-infinite-scroll": "^10.0.1",
    "ngx-mask": "^11.1.5",
    "plural-ru": "^2.0.2",
    "preboot": "^8.0.0",
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primeng": "^11.4.1",
    "registration": "file:registration-0.0.1.tgz",
    "rxjs": "~6.6.6",
    "shared": "file:shared-0.0.1.tgz",
    "svg4everybody": "^2.1.9",
    "tslib": "^2.1.0",
    "tslint": "^6.1.3",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.0.0",
    "@angular-eslint/builder": "12.0.0",
    "@angular-eslint/eslint-plugin": "12.0.0",
    "@angular-eslint/eslint-plugin-template": "12.0.0",
    "@angular-eslint/schematics": "^12.0.0",
    "@angular-eslint/template-parser": "12.0.0",
    "@angular/cli": "^12.0.0",
    "@angular/compiler-cli": "~12.0.0",
    "@babel/core": "^7.14.2",
    "@compodoc/compodoc": "^1.1.11",
    "@nguniversal/builders": "^12.0.0",
    "@storybook/addon-a11y": "^6.1.21",
    "@storybook/addon-actions": "^6.1.21",
    "@storybook/addon-contexts": "^5.3.21",
    "@storybook/addon-essentials": "^6.1.21",
    "@storybook/addon-links": "^6.1.21",
    "@storybook/addon-storysource": "^6.1.21",
    "@storybook/angular": "^6.1.21",
    "@storybook/storybook-deployer": "^2.8.7",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.7.4",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "4.23.0",
    "@typescript-eslint/parser": "4.23.0",
    "babel-loader": "^8.2.2",
    "codelyzer": "^6.0.2",
    "copy-webpack-plugin": "^8.1.1",
    "eslint": "^7.26.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "34.2.1",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "globby": "^11.0.3",
    "husky": "^4.3.0",
    "imagemin-keep-folder": "^5.3.2",
    "imagemin-mozjpeg": "^9.0.0",
    "imagemin-pngquant": "^9.0.2",
    "imagemin-svgo": "^8.0.0",
    "imagemin-webp": "^6.0.0",
    "jasmine-core": "~3.7.1",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "lint-staged": "^11.0.0",
    "ng-packagr": "^12.0.0",
    "protractor": "~7.0.0",
    "stylelint": "^13.13.1",
    "stylelint-order": "^4.1.0",
    "stylelint-scss": "^3.18.0",
    "svg-sprite": "^1.5.0",
    "svgo": "^1.3.2",
    "ts-node": "~9.1.1",
    "typescript": "~4.2.3",
    "webpack-cli": "^4.7.0"
  }
}

```

**Comment by JoostK** [comment] 2021-05-20 11:27
Moving to the CLI as this is probably done by a css minifier.

Is this really valid CSS? I'd have expected the syntax to be `rgb(R,G,B)` instead of just comma-separated values.

**Comment by yumadilovtimur** [comment] 2021-05-20 11:36
> Moving to the CLI as this is probably done by a css minifier.
> 
> Is this really valid CSS? I'd have expected the syntax to be `rgb(R,G,B)` instead of just comma-separated values.

it's just a string here. then there are separate variables, where rgb is added, etc.

**Comment by alan-agius4** [comment] 2021-05-20 11:38
@yumadilovtimur, can you please provide the exact values you are setting?

**Comment by yumadilovtimur** [comment] 2021-05-20 11:49
> @yumadilovtimur, can you please provide the exact values you are setting?

@alan-agius4 I set the values as in the first screenshot and expect to get them in the output.
We need such values so that we can further process them, for example, add transparency, like this: rgba(var(--gray-10), 0.3);
If it is just a variable with rgb(), then it will not work.
P.S. we also found a problem in cssnano

**Comment by alan-agius4** [comment] 2021-05-20 11:57
I can confirm that the below yields the incorrect output.

**Input** 
```css
:root {
    --white: 255,255,255
}

* {
    color: rgba(var(--white), 0.3)
}
```

**Ouput**
```css
:root{--white:#255,#255,#255}*{color:rgba(var(--white),.3)}
```

There is no much we can do for this case but redirect you to file an issue with CSS Nano as this is not caused by the Angular CLI.

**Closed by alan-agius4** 2021-05-20 11:57 UTC
