### ISSUE TITLE
Update component schematic to 'export default class' by default

### ISSUE THREAD

**Issue by geromegrignon** [angular/angular-cli#28187] opened 2024-08-10 08:52 UTC
### Command

generate

### Description

The DX has been improved in Angular lazy loading route generation by allowing the removal of the requirement to use `.then(c => c.HomeComponent)` syntax by adding the **default** keyword on the route provider (route file/component/module).

But it comes at the cost of manually opening another file to add this keyword while writing the route definition, making the DX improvment quite limited.

### Describe the solution you'd like

Is there any possible negative impact at making `ng generate component` includes the **default** keyword by default?

**Comment by alan-agius4** [comment] 2024-08-10 09:14
Duplicate of https://github.com/angular/angular-cli/issues/25023

**Closed by alan-agius4** 2024-08-10 09:14 UTC
