### ISSUE TITLE
ng build --base-href or -bh generates incorrect base href in the index.html 

### ISSUE THREAD

**Issue by JoA-MoS** [angular/angular-cli#7876] opened 2017-09-29 06:48 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Output from: `ng --version`.
```
$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.4
node: 8.1.2
os: win32 x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4
```
```
$ npm -v
5.0.3
$ node -v
v8.1.2
```
OS: WIndows 10

### Repro steps.
1. ng new repro-app
2. ng build -bh /testing/
3. look at your /dist/index.html and see that the base tag looks as follows
    ```html
    <base href="C:/Program Files/Git/testing/">
    ```
notice it has added the local directory to Git for some reason.

### Desired functionality.
when using --base-href the value specified in the base element of index.html should be exactly the text typed in following the --base-href flag.

**Comment by paul-thomas0** [comment] 2017-09-29 09:00
Try something like: ng build -bh="testing"

**Comment by ajit-jain** [comment] 2017-09-29 09:34
i have issue #7879 not #7876

**Comment by filipesilva** [comment] 2017-09-29 13:19
Duplicate of https://github.com/angular/angular-cli/issues/5606

**Closed by filipesilva** 2017-09-29 13:19 UTC
Labels: priority: 2 (required), severity3: broken

**Comment by JoA-MoS** [comment] 2017-09-29 14:50
It seems to be an issue when running the command in git bash the same command works properly in powershell.

**Comment by tolgabalci** [comment] 2018-05-30 23:53
It's not an issue, its a feature of git bash on Windows.  It's trying to help you out by converting Linux paths to Windows paths.

You can tell git bash to avoid the conversion for the -bh parameter by setting the MSYS2_ARG_CONV_EXCL environment variable while calling ng like this:
`MSYS2_ARG_CONV_EXCL="-bh=" ng build --prod -bh="/en/"`

Note that to use the exclusion you must use -bh parameter with an =, not space since MSYS2_ARG_CONV_EXCL will think the value after the space is a different parameter.
