### ISSUE TITLE
Compile problem with  @angular-devkit/build-angular 0.800.4

### ISSUE THREAD

**Issue by abadakhshan** [angular/angular-cli#14883] opened 2019-06-25 07:26 UTC
# 🐞 Bug report

### Description

I have a problem with **@angular-devkit/build-angular 0.800.4** while I did not it with previous version of **@angular-devkit/build-angular**

When I want to compile my project with ng serve I got this error

> ERROR in ./src/app/modules/main/change-password/change-password.component.ts 56:12-21
> "export 'DialogRef' was not found in 'narik-infrastructure'

and this is related to this line of code:

>  @Inject(DIALOG_REF) public dialog: DialogRef<any>

**DIALOG_REF** is an **injectionToken** and DialogRef is a **interface** in external angular package.

I get this error only when I use DialogRef in constructor. If I use it as an usual declaration like
dialog: DialogRef i get no error.

You can see error on this repo: https://github.com/NarikMe/narik-material-demo
_if you change @angular-devkit/build-angular version to "0.800.4"_

**Comment by alan-agius4** [comment] 2019-06-25 07:33
Duplicate of https://github.com/angular/angular-cli/issues/14876

**Closed by alan-agius4** 2019-06-25 07:33 UTC
