### ISSUE TITLE
Problem with latest RxJS version in generation command-line process

### ISSUE THREAD

**Issue by njl07** [angular/angular-cli#10351] opened 2018-04-16 09:39 UTC
### Versions
```
Angular CLI: 6.0.0-rc.4
Node: 9.11.1
OS: darwin x64
Angular: 6.0.0-rc.5
... animations, common, compiler, compiler-cli, core, elements
... forms, http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.5.6
@angular-devkit/build-angular      0.5.6
@angular-devkit/build-ng-packagr   0.5.6
@angular-devkit/build-optimizer    0.5.6
@angular-devkit/core               0.5.6
@angular-devkit/schematics         0.5.6
@angular/cli                       6.0.0-rc.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.0-rc.4
@schematics/angular                0.5.6
@schematics/update                 0.5.6
rxjs                               6.0.0-uncanny-rc.7
typescript                         2.7.2
webpack                            4.5.0
```

### Repro steps

* Install `angular-cli`
* Create new project => `ng new my-project`
* Generate a new library `ng g library my-library` or a service `ng g s my-service`

### Observed behavior
For library generation :
```
CREATE projects/my-library/karma.conf.js (1012 bytes)
CREATE projects/my-library/ng-package.json (191 bytes)
CREATE projects/my-library/ng-package.prod.json (152 bytes)
CREATE projects/my-library/package.json (175 bytes)
CREATE projects/my-library/src/public_api.ts (191 bytes)
CREATE projects/my-library/src/test.ts (700 bytes)
CREATE projects/my-library/tsconfig.lint.json (201 bytes)
CREATE projects/my-library/tsconfig.spec.json (246 bytes)
CREATE projects/my-library/tslint.json (317 bytes)
CREATE projects/my-library/src/lib/my-library.module.ts (265 bytes)
CREATE projects/my-library/src/lib/my-library.component.spec.ts (685 bytes)
CREATE projects/my-library/src/lib/my-library.component.ts (282 bytes)
CREATE projects/my-library/src/lib/my-library.service.spec.ts (423 bytes)
CREATE projects/my-library/src/lib/my-library.service.ts (143 bytes)
UPDATE angular.json (9731 bytes)
UPDATE package.json (1622 bytes)
UPDATE tsconfig.json (727 bytes)
/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/util/subscribeTo.js:42
        throw new TypeError(msg);
        ^

TypeError: You provided 'function reduceOperatorFunction(source) {
        return pipe_1.pipe(scan_1.scan(function (acc, value, index) {
            return accumulator(acc, value, index + 1);
        }), takeLast_1.takeLast(1))(source);
    }' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.exports.subscribeTo (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/util/subscribeTo.js:42:15)
    at Object.subscribeToResult (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:26)
    at MergeMapSubscriber._innerSub (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.notifyComplete (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/operators/mergeMap.js:148:18)
    at InnerSubscriber._complete (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/InnerSubscriber.js:37:21)
    at InnerSubscriber.Subscriber.complete (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/Subscriber.js:128:18)
    at Observable.rxjs_1.concat.rxjs_1.concat.rxjs_1.Observable.obs [as _subscribe] (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/@angular-devkit/schematics/tools/workflow/node-workflow.js:113:17)
    at Observable.subscribe (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/Observable.js:162:69)
```

For service :
```
CREATE src/app/my-service.service.spec.ts (362 bytes)
CREATE src/app/my-service.service.ts (133 bytes)
/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/util/hostReportError.js:9
    setTimeout(function () { throw err; });
                             ^

TypeError: You provided 'function reduceOperatorFunction(source) {
        return pipe_1.pipe(scan_1.scan(function (acc, value, index) {
            return accumulator(acc, value, index + 1);
        }), takeLast_1.takeLast(1))(source);
    }' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.exports.subscribeTo (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/util/subscribeTo.js:42:15)
    at Object.subscribeToResult (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:26)
    at MergeMapSubscriber._innerSub (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.notifyComplete (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/operators/mergeMap.js:148:18)
    at InnerSubscriber._complete (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/InnerSubscriber.js:37:21)
    at InnerSubscriber.Subscriber.complete (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/Subscriber.js:128:18)
    at Observable.rxjs_1.concat.rxjs_1.concat.rxjs_1.Observable.obs [as _subscribe] (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/@angular-devkit/schematics/tools/workflow/node-workflow.js:113:17)
    at Observable.subscribe (/Users/akanass/Programmation/Angular/webcomponents-cli/node_modules/rxjs/internal/Observable.js:162:69)
```

All elements are created but `cli` throw errors.

### Desired behavior
No errors provided by `cli` process

**Comment by cyrilletuzi** [comment] 2018-04-16 10:00
I confirm this issue. It happens in several other places (like `ng add @angular/elements`), so I think it's a RxJS issue with last RC.

**Comment by cyrilletuzi** [comment] 2018-04-16 10:02
ReactiveX/rxjs#3573 : last comment is suggesting the error is on CLI side, not RxJS.

**Comment by filipesilva** [comment] 2018-04-16 11:01
Heya, we are tracking this issue in https://github.com/angular/angular-cli/issues/10335.

Closing as duplicate of https://github.com/angular/angular-cli/issues/10335.

**Closed by filipesilva** 2018-04-16 11:01 UTC
