### ISSUE TITLE
Invalid project build when project path includes symlink

### ISSUE THREAD

**Issue by pohybel** [angular/angular-cli#3797] opened 2016-12-30 23:20 UTC
### OS?
Windows 7

### Versions.
```
angular-cli: 1.0.0-beta.24
node: 6.5.0
os: win32 ia32
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

npm: 3.10.3
```

### Repro steps.
- create symbolic link to folder using `mklink` command, eg. 
`mklink D:\workspace-link R:\workspace /J`
where
`R:\workspace` is a phisical folder
`D:\workspace-link` is a symbolic link which pointing to `R:\workspace`
`/J` is a switch indicating that it has to be folder link
- navigate to `R:\workspace`
- execute `ng new test-project`
- `cd test-project`
- set some global styles (eg. `body {	background-color: #99ff99; }` ) in `src/styles.css`
- `ng serve`

project run perfectly fine, global styles are applied in application. Now run the project through symlink folder:

- navigate to `D:\workspace-link\test-project`
- `ng serve`

project seems to be build successfully and even runs in the browser but in some different way, eg no `vendor.bundle.js` is emitted, no `styles.bundle.css` etc. But the more important thing is that **global styles have not been applied in the application!**

### Output:

![Image of Yaktocat](https://s24.postimg.org/wfd9ynioz/angular_cli_symlink_issue.png?dl=1)

```
R:\workspace\GIT\iot-config>ng serve
** NG Live Development Server is running on http://localhost:4200. **
Hash: e998220d54d5437f33c0
Time: 10934ms
chunk    {0} main.bundle.js, main.bundle.map (main) 4.59 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 1.73 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.83 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: bundle is now VALID.

R:\workspace\GIT\iot-config>D:

D:\workspace\GIT\iot-config>ng serve
** NG Live Development Server is running on http://localhost:4200. **
Hash: 7bf8c693f9546528f93a
Time: 25323ms
chunk    {0} styles.bundle.map (styles) 87 bytes {2} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.map (main) 2.82 MB [initial] [rendered]
chunk    {2} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: bundle is now VALID.
```

**Comment by memboc** [comment] 2017-01-12 07:22
same problem without symlink

**Comment by filipesilva** [comment] 2017-01-24 12:32
I can verify this happens. It's due to the way we resolve the `node_modules` path, which is used for detection of what should go into the vendor bundle.

**Comment by filipesilva** [comment] 2017-05-22 09:45
Dupe of https://github.com/angular/angular-cli/issues/2726, addressed by https://github.com/angular/angular-cli/pull/6403.

**Closed by filipesilva** 2017-05-22 09:45 UTC
Labels: command: build, effort2: medium (days), priority: 2 (required), severity2: inconvenient, type: bug

**Comment by Wim-van-der-Veen** [comment] 2017-07-07 10:00
In addition to this, if i have a running and producable project with root-folder f.i. D:\bla\bla\bla\project, then create a soft symlink to this f.i. D:\prj, and try to run 'ng serve' from there, i get all sorts of trouble
Also, if i share the project folder, then create (on the same machine) a network-connection to it thus having a drive f.i. Q: which is the root of my valid project (containing node-modules, src, etc) 'ng serve' says 'you have to be inside an angular-cli project ... etc'. Well, i am, am i?
(both Win10, btw; i tried this because my project is rather deep in the directory tree and i wanted to shorten all ng-produced messages in order to keep it readable :( )

**Comment by filipesilva** [comment] 2017-07-17 09:00
@Wim-van-der-Veen this should be fixed in the new versions, are you sure you've updated?

**Comment by minuz** [comment] 2017-08-28 09:52
@filipesilva I just update my project to angular-cli 1.3.2 and I'm getting the same issue. Are you sure this has been fixed? :)
