### ISSUE TITLE
Node#moveTo was deprecated. Use Container#append

### ISSUE THREAD

**Issue by dilotec-2015** [angular/angular-cli#8727] opened 2017-12-02 21:33 UTC
Installed Versions:
Angular CLI: 1.5.5
Node: 8.9.0
OS: win32 x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.5.5
@angular/material: 5.0.0-rc.2
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript: 2.4.2
webpack: 3.8.1

### Repro steps

ng build --prod --aot=false --sourcemap=false

### Observed behavior

after update to cli 1.55 i get this error:
 10% building modules 8/10 modules 2 active ...\bootstrap\dist\css\bootstrap.min.cssNode#moveTo was deprecated. Use Container#append

### Desired behavior
compiled production version

**Comment by Bretto** [comment] 2017-12-03 04:53
I have the same issue my project stoped building...
```
Angular CLI: 1.6.0-rc.1
Node: 8.9.0
OS: win32 x64
Angular: 5.1.0-rc.1
`
``

**Comment by devoto13** [comment] 2017-12-03 19:07
This is from one of the PostCSS plugins, which uses method deprecated in [6.0.0 release](https://github.com/postcss/postcss/releases/tag/6.0.0). 

> Now, `moveTo`, `moveAfter` & `moveBefore` are deprecated because regular insert methods have this move behavior.

**Comment by clydin** [comment] 2017-12-04 14:00
Thanks for reporting this issue. However, this issue is appears to be a duplicate of an existing issue #8598. Please subscribe to that issue for future updates.

**Closed by clydin** 2017-12-04 14:00 UTC
