### ISSUE TITLE
Using baseUrl and paths from tsconfig causes crash for wildcard paths

### ISSUE THREAD

**Issue by karptonite** [angular/angular-cli#5459] opened 2017-03-16 22:07 UTC
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9

### Repro steps.
1. create a new clean project with `ng new`.
2. Add the following to tsconfig.app.json. 
(this is exactly analogous to what is suggested here https://www.typescriptlang.org/docs/handbook/module-resolution.html, and worked fine when I was using the angular-class starter)
```
    "baseUrl": ".",
    "paths": {
      "*": [
        "*",
        "app/*"
      ]
    },
```
3. `ng serve`

### The log given by the failure.
<--- Last few GCs --->

[99409:0x104800000]     6888 ms: Mark-sweep 1399.2 (1459.4) -> 1399.2 (1459.9) MB, 133.5 / 0.0 ms  allocation failure GC in old space requested
[99409:0x104800000]     7072 ms: Mark-sweep 1399.2 (1459.9) -> 1399.0 (1427.9) MB, 184.2 / 0.0 ms  last resort
[99409:0x104800000]     7242 ms: Mark-sweep 1399.0 (1427.9) -> 1399.0 (1427.9) MB, 169.6 / 0.0 ms  last resort

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1a53eaca66a1 <JS Object>
    1: DoJoin(aka DoJoin) [native array.js:~97] [pc=0x116f6a33f02a](this=0x30cf1cf02311 <undefined>,q=0x39cc9548d809 <JS Array[1613]>,r=1613,F=0x30cf1cf023b1 <true>,B=0x8c9e081dcb9 <String[3]\: \n  >,A=0x30cf1cf02421 <false>)
    2: Join(aka Join) [native array.js:~122] [pc=0x116f6a6bbfa2](this=0x30cf1cf02311 <undefined>,q=0x39cc9548d809 <JS Array[1613]>,r=1613,B=0x8c9e081dcb9 <String[3]\: \n  ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::Runtime_StringBuilderJoin(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x116f697843a7
 8: 0x116f6a33f02a
 9: 0x116f6a6bbfa2
10: 0x116f6a650171
[1]    99409 abort      ng serve

### Desired functionality.
Adding that setting to tsconfig.app.json should allow all directories in `src/app/` to be accessed absolutely.

**Comment by filipesilva** [comment] 2017-05-23 12:24
Dupe of https://github.com/angular/angular-cli/issues/3441

**Closed by filipesilva** 2017-05-23 12:24 UTC
Labels: freq1: low, package4: @angular-sdk/webpack, severity2: inconvenient, type: bug
