### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by nelashj** [angular/angular-cli#7251] opened 2017-08-03 04:35 UTC
I am getting below error:-

**Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null**

ng --version is 
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / ? \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.6
node: 7.8.0
os: win32 x64
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 3.0.0-rc.1
@angular/router-deprecated: 2.0.0-rc.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.3

 I just checked **node_modules\@angular\cli\tasksbuild.js** file where it's calling **CliConfig.fromProject()** but there is no such method in **@angular\cli\models\config\config.js**.. Not sure if it's bug or what?

**Comment by jiverson** [comment] 2017-08-03 06:48
I just tested with the following and was not able to reproduce may need more info possible os issue?

```
@angular/cli: 1.2.6
node: 7.8.0
os: darwin x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3
```

**Comment by nelashj** [comment] 2017-08-03 08:07
Not sure what is wrong with my code. Coould you please share your package.json and tsconfig.json.

Here is what I am getting:-
C:\Official\UI\testAngular>C:\Official\Software\node-v7.8.0-win-x64\ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / ? \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
```
@angular/cli: 1.2.6
node: 7.8.0
os: win32 x64
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/router-deprecated: 2.0.0-rc.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.3
```

```
C:\Official\UI\testAngular>C:\Official\Software\node-v7.8.0-win-x64\ng build
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (C:\Official\UI\testAngular\node_modules\@angular\cli\tasks\build.js:14:56)
    at Class.run (C:\Official\UI\testAngular\node_modules\@angular\cli\commands\build.js:162:26)
    at resolve (C:\Official\UI\testAngular\node_modules\@angular\cli\ember-cli\lib\models\command.js:273:20)
    at Class.validateAndRun (C:\Official\UI\testAngular\node_modules\@angular\cli\ember-cli\lib\models\command.js:251:12)
    at Promise.resolve.then.then (C:\Official\UI\testAngular\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:157:24)
    at tryCatch (C:\Official\UI\testAngular\node_modules\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (C:\Official\UI\testAngular\node_modules\rsvp\dist\rsvp.js:538:13)
    at publish (C:\Official\UI\testAngular\node_modules\rsvp\dist\rsvp.js:508:7)
    at flush (C:\Official\UI\testAngular\node_modules\rsvp\dist\rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by alanhg** [comment] 2017-08-12 04:41
I met the same error!

**Comment by Philip-Sultanescu** [comment] 2017-08-13 23:10
I also get the same error

Darwin 16.7.0
node v6.11.2
npm  v3.10.10
@angular/cli: 1.2.6,
@angular/compiler-cli: 4.3.2,

**Comment by nelashj** [comment] 2017-08-16 02:58
does anybody have any solution to this?

**Comment by clydin** [comment] 2018-09-25 17:59
Closing as version `1.2.6`/`1.3.0` is no longer supported. If the problem persists within the latest stable version (currently `6.2.3`), please open a new issue detailing the problem.

**Closed by clydin** 2018-09-25 17:59 UTC
Labels: priority: 2 (required), severity5: regression
