### ISSUE TITLE
FESM bundles: Could not resolve entry module

### ISSUE THREAD

**Issue by burner-account** [angular/angular-cli#25773] opened 2023-09-03 10:25 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15

### Description

**Problem**:  
After using `ng build @namespace/library-name --watch`  and CTRL-C'ing the process, subsequent calls of  `ng build @namespace/library-name --watch` as well as calls to `ng build @namespace/library-name` (non-watching) **might** fail.

In case of failure,  this is shown:
```
------------------------------------------------------------------------------
Building entry point '@namespace/library-name'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy full compilation mode.
✖ Generating FESM bundles
Could not resolve entry module "dist/namespace/library-name/esm2022/namespace-library-name.mjs".
```
*may also happen with partial Ivy mode

**Workaround**: 
Simply restarting the failed build process does the trick.

### Minimal Reproduction

Sorry, cannot provide that.  It's too random.

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.1
Node: 18.10.0
Package Manager: npm 9.6.2
OS: linux x64

Angular: 16.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1602.1
@angular-devkit/build-angular        16.2.1
@angular-devkit/core                 16.2.1
@angular-devkit/schematics           16.2.1
@angular/cdk                         16.2.2
@angular/cli                         16.2.1
@angular/material                    16.2.2
@angular/material-date-fns-adapter   16.2.2
@schematics/angular                  16.2.1
ng-packagr                           16.2.0
rxjs                                 7.8.1
typescript                           5.1.6
zone.js                              0.13.1
```

**Comment by burner-account** [comment] 2023-09-03 10:31
Additional trials seems to indicate that the error does not occur, if the .angular/cache/<version> directory incl children is removed before building libraries.

**Comment by alan-agius4** [comment] 2023-09-03 11:59
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/2666

**Closed by alan-agius4** 2023-09-03 11:59 UTC
