### ISSUE TITLE
[1.5.0-rc.5] Failing to Load the Page when doing an Ng Serve

### ISSUE THREAD

**Issue by sameel** [angular/angular-cli#8232] opened 2017-10-28 01:40 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report 
- [ ] feature request
```

### Versions.
@angular/cli: 1.5.0-rc.5
node: 6.9.4
os: darwin x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
typescript: 2.4.2

### Issue
I am currently trying to build my project which is using ES6. I had trouble using angular-cli/1.4.9 when attempting to run a prod build due to Uglify-Es so I upgraded to the beta version but now ng serve seems to fail with error: 

`Unhandled Promise rejection: Cannot convert undefined or null to object ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at getParentCtor (reflection_capabilities.ts:324)
    at ReflectionCapabilities.parameters (reflection_capabilities.ts:115)
    at Reflector.parameters (reflector.ts:42)
    at CompileMetadataResolver._getDependenciesMetadata (metadata_resolver.js:794)
    at CompileMetadataResolver._getFactoryMetadata (metadata_resolver.js:729)
    at CompileMetadataResolver.getProviderMetadata (metadata_resolver.js:1001)
    at JitCompiler._compileModule (compiler.js:172)
    at createResult (compiler.js:116)
    at ZoneDelegate.invoke (zone.js:334)
    at Zone.run (zone.js:126)
    at zone.js:713
    at ZoneDelegate.invokeTask (zone.js:367)
    at Zone.runTask (zone.js:166)
    at drainMicroTaskQueue (zone.js:546) TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at getParentCtor (http://localhost:4200/vendor.bundle.js:2414:49)
    at ReflectionCapabilities.parameters (http://localhost:4200/vendor.bundle.js:2234:45)
    at Reflector.parameters (http://localhost:4200/vendor.bundle.js:2496:44)
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:40117:73)
    at CompileMetadataResolver._getFactoryMetadata (http://localhost:4200/vendor.bundle.js:40056:51)
    at CompileMetadataResolver.getProviderMetadata (http://localhost:4200/vendor.bundle.js:40324:43)
    at JitCompiler._compileModule (http://localhost:4200/vendor.bundle.js:50248:77)
    at createResult (http://localhost:4200/vendor.bundle.js:50192:25)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2970:26)
    at Zone.run (http://localhost:4200/polyfills.bundle.js:2762:43)
    at http://localhost:4200/polyfills.bundle.js:3349:57
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:3003:31)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:2802:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:3182:35)`

Running the ng serve with AOT seems to make it successful but I am unable to develop in AOT due to JavaScript Heap Memory errors which is another unrelated issue.

It seems to be only with JIT Compilation. Going back to 1.4.9 makes my project's ng serve work perfectly but the production build fail (due to the Uglify-es).

**Comment by filipesilva** [comment] 2017-10-28 09:35
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/7797. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-10-28 09:35 UTC
