### ISSUE TITLE
ng build --watch and ng serve does not work in sync

### ISSUE THREAD

**Issue by vinothbabu** [angular/angular-cli#19125] opened 2020-10-19 15:23 UTC
We have an angular library project and when we try to build the project, we use the following command. 

`ng build library --watch`

Now I have a separate SPA which is consuming this library through `npm link`, when we try to do `ng serve` and make changes to the library, the changes are not reflected in the primary application. I get the below warning and there is no changes reflected. 

```
Date: 2020-10-19T15:16:37.896Z - Hash: 7806cdf5aebeb072fe94
8 unchanged chunks
chunk {lib-module-ngfactory} lib-module-ngfactory.js, lib-module-ngfactory.js.map (lib-module-ngfactory) 34.3 kB 
 [rendered]
Time: 1064ms

WARNING in Emitted no files.

i ｢wdm｣: Compiled with warnings.
```

When I try to stop the ng serve and start again, it works! 

**Reference for similar issue**: 
https://github.com/angular/angular-cli/issues/6195

**Details on the machine and Angular:** 

Angular CLI: 8.3.24
Node: 12.10.0
OS: win32 x64 (Windows 10)
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.24
@angular-devkit/core         8.3.24
@angular-devkit/schematics   8.3.24
@schematics/angular          8.3.24
@schematics/update           0.803.24
rxjs                         6.4.0

**Comment by alan-agius4** [comment] 2020-10-19 15:34
Are you updating an HTML or CSS file by any change?

Looks to me like a duplicate of https://github.com/angular/angular-cli/issues/13588

**Comment by vinothbabu** [comment] 2020-10-19 15:38
I am trying to update the HTML, i am looking at the the thread you have pointed too. Is there a specific CLI and Angular version this issue is resolved which we can migrate?

**Comment by alan-agius4** [comment] 2020-10-19 15:42
Yeah, this should no longer be an with Angular and Angular CLI version 9+ with Ivy.

**Closed by alan-agius4** 2020-10-19 15:42 UTC
Labels: need: more info

**Comment by vinothbabu** [comment] 2020-10-19 17:05
> Yeah, this should no longer be an issue with Angular and Angular CLI version 9+ with Ivy.

Can this be resolved by enabling ivy in Angular 8 or we need to migrate to Angular 9?

**Comment by alan-agius4** [comment] 2020-10-19 17:21
You can try, although Ivy in version 8 was still in it’s early stages and was not as stable as in version 9.

My recommendation would be to update to the latest stable version which as the moment is 10.1.x, please be aware that Angular version 8 is currently in LTS which support will end in 28th November 2020. See: https://angular.io/guide/releases
