### ISSUE TITLE
Found: postcss@8.2.14  Could not resolve dependency:  peer postcss@"^8.2.15" from cssnano-preset-default@5.1.1

### ISSUE THREAD

**Issue by billpeace** [angular/angular-cli#20915] opened 2021-05-24 01:20 UTC
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: postcss@8.2.14
npm ERR! node_modules/postcss
npm ERR!   postcss@"8.2.14" from @angular-devkit/build-angular@0.1102.13
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"^0.1102.13" from the root project
npm ERR!   postcss@"^8.2.4" from ng-packagr@11.2.4
npm ERR!   node_modules/ng-packagr
npm ERR!     dev ng-packagr@"^11.2.4" from the root project
npm ERR!     peerOptional ng-packagr@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.13
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       dev @angular-devkit/build-angular@"^0.1102.13" from the root project
npm ERR!   10 more (autoprefixer, css-loader, cssnano, postcss-import, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer postcss@"^8.2.15" from cssnano-preset-default@5.1.1
npm ERR! node_modules/cssnano/node_modules/cssnano-preset-default
npm ERR!   cssnano-preset-default@"^5.0.1" from cssnano@5.0.2
npm ERR!   node_modules/cssnano
npm ERR!     cssnano@"5.0.2" from @angular-devkit/build-angular@0.1102.13
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       dev @angular-devkit/build-angular@"^0.1102.13" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by alan-agius4** [comment] 2021-05-24 05:06
Duplicate of https://github.com/angular/angular-cli/issues/20888

**Closed by alan-agius4** 2021-05-24 05:06 UTC
