### ISSUE TITLE
ng-add doesn't install the latest version correctly x2

### ISSUE THREAD

**Issue by luillyfe** [angular/angular-cli#18203] opened 2020-07-09 09:37 UTC
# 🐞 Bug report
### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ X] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
Is happening again, I tried to reopen the issue but it was impossible to me.

All details here: https://github.com/angular/angular-cli/issues/17024

## 🔬 Minimal Reproduction

Just try:
ng add @ngrx/store
## 🔥 Exception or Error
<pre><code>

**Comment by alan-agius4** [comment] 2020-07-09 10:05
Duplicate of https://github.com/angular/angular-cli/issues/17983

**Closed by alan-agius4** 2020-07-09 10:05 UTC
