### ISSUE TITLE
file-replacements not work in scss

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#18585] opened 2020-08-20 06:15 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

## 🔬 Minimal Reproduction
https://github.com/xiaoxiangmoe/angular-file-replacements-scss-error
 

### Description

run `yarn start -c serve`
```
"serve":{
  "fileReplacements": [
    {
      "replace": "src/app/app-color.ts",
      "with": "src/app/app-color-replace.ts"
    },
    {
      "replace": "src/app/_app-color.scss",
      "with": "src/app/_app-color-replace.scss"
    }
  ]
}
```
fileReplacements in ts works, but fileReplacements in scss don't work.

![image](https://user-images.githubusercontent.com/8111351/90723697-d06bac80-e2ef-11ea-8683-638744716cb8.png)

If it works, the color should be green.

**Comment by alan-agius4** [comment] 2020-08-20 09:57
Duplicate of https://github.com/angular/angular-cli/issues/11451

**Closed by alan-agius4** 2020-08-20 09:57 UTC
