### ISSUE TITLE
ng build --prod --base-href includes absolute path of building cwd

### ISSUE THREAD

**Issue by athlan** [angular/angular-cli#12501] opened 2018-10-06 10:04 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Windows 10, GIt Bash

```
$ ng --version

Angular CLI: 6.2.3
Node: 8.12.0
OS: win32 x64
Angular: 6.1.8
```

### Repro steps

Build project by the following command:
```
ng build --prod --base-href /client1-app
```

### The log given by the failure

n/a

### Desired functionality

Application need to be deployed under http://example.com/client1-app. The base path for it should be `/client1-app` then.

However in index.html wrong base path is included:
```
$ grep base dist/election-barometer/index.html
  <base href="E:/Programs/Git/client1-app">
```

The git installation path (absolute path of installation dir) is included when `--base-href` starts with slash character.

Base href cannot be just `client1-app` (without slash at the beggining), because of routing. User can start application from:
/client1-app/some/path/started
Then, `client1-app` will point to example.com/some/path/client1-app
Which is not intended, so slash at the beggining is required.

### Mention any other details that might be useful

The following repository could be useful during investigation: https://github.com/athlan/election-barometer
However, nothing special on it, was generated by ng cli.

**Comment by simjes** [comment] 2018-10-07 08:32
Noticed this as well, but only happened when using bash. Seems to work as expected in PowerShell.

**Comment by athlan** [comment] 2018-10-08 16:47
Hello,

Checked that and `ng build --prod --base-href '/client1-app'` and `ng build --prod --base-href "/client1-app"` results with the same issue.

By the way, where this fragment of code is actually generated?
https://github.com/search?p=1&q=org%3Aangular+base-href&type=Code

**Comment by filipesilva** [comment] 2018-10-09 15:21
I'm sorry to say but this is a duplicate of https://github.com/angular/angular-cli/issues/5606 and https://github.com/angular/angular-cli/issues/6060. 

This isn't the thing we can truly fix on our side. Git Bash converts the commands and what is actually passed into the node executable is already the full path you see. You can read more about this problem and some possible workarounds in the issues I mentioned.

**Closed by filipesilva** 2018-10-09 15:21 UTC
Labels: comp: devkit/build-angular, freq1: low, severity3: broken
