### ISSUE TITLE
Missing directive suffix when generating directive

### ISSUE THREAD

**Issue by daretodave** [angular/angular-cli#1687] opened 2016-08-14 12:54 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10, build 14393

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.2.2
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
`ng g directive highlight`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
n/a

5. Mention any other details that might be useful.
The non-issue is with the generated directive class. In the above example, here's what will be generated (highlight.directive.ts) -

```
import {Directive} from '@angular/core';

@Directive({
  selector: '[highlight]'
})
export class Highlight {

  constructor() { }

}
```

Shouldn't the class decoration instead be -

`export class HighlightDirective {`

All the provided examples on angular.io uphold this convention. 

It may also be important to note that when generating a Pipe, Component, or Service that the classes are in fact suffixed with the keyword (e.g UppercasePipe, AppComponent, UserService).

Any way, great tool guys! Enjoying the webpack'd version of the cli.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-08-19 02:33
Dupe of https://github.com/angular/angular-cli/issues/1217

**Closed by filipesilva** 2016-08-19 02:33 UTC
