### ISSUE TITLE
Upgrade Angular 12 to 13 failing with peer dependency conflict

### ISSUE THREAD

**Issue by uweDuesing** [angular/angular-cli#22826] opened 2022-03-09 22:09 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I am trying to upgrade an Angular 12 project to version 13.
I created a brand new project with cli version 12.2.16

I am following the guidance from the Angular Update Website https://update.angular.io/?v=12.0-13.0

Running this command 
**npx @angular/cli@13 update @angular/core@13 @angular/cli@13**
the upgrade starts, but then fails with a peer dependency error

### Please provide a link to a minimal reproduction of the bug

https://github.com/uweDuesing/angularApp12

### Please provide the exception or error you saw

```true
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: test-app12@0.0.0
npm ERR! Found: @angular-devkit/build-angular@12.2.16
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~13.2.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~13.2.5" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/compiler-cli@13.2.6
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^13.0.0" from @angular-devkit/build-angular@13.2.5
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~13.2.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.2.16
Node: 14.19.0
Package Manager: npm 8.5.3
OS: win32 x64

Angular: <error>
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.16 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            12.2.16 (cli-only)
@angular-devkit/schematics      12.2.16 (cli-only)
@angular/cli                    12.2.16 (cli-only)
@schematics/angular             12.2.16 (cli-only)
rxjs                            6.6.7 (cli-only)
```

**Comment by alan-agius4** [comment] 2022-03-10 07:50
Duplicate of https://github.com/angular/angular-cli/issues/21204

**Closed by alan-agius4** 2022-03-10 07:50 UTC

**Comment by mrsegen** [comment] 2022-03-10 14:16
In my understanding, this seems to be a new issue related to the 13.2.6 release - distinct from #21204. I'm seeing a similar issue when I attempt to run `ng update @angular/core` while currently having 13.2.2 installed in our app.

```
ng update @angular/core @angular/cdk -C
Using package manager: 'npm'
Collecting installed dependencies...
Found 89 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/compiler-cli @ "13.2.6" (was "13.2.2")...
    Updating package.json with dependency @angular/language-service @ "13.2.6" (was "13.2.2")...
    Updating package.json with dependency @angular/animations @ "13.2.6" (was "13.2.2")...
    Updating package.json with dependency @angular/cdk @ "13.2.6" (was "13.2.2")...
    Updating package.json with dependency @angular/common @ "13.2.6" (was "13.2.2")...
    Updating package.json with dependency @angular/compiler @ "13.2.6" (was "13.2.2")...
    Updating package.json with dependency @angular/core @ "13.2.6" (was "13.2.2")...
    Updating package.json with dependency @angular/forms @ "13.2.6" (was "13.2.2")...
    Updating package.json with dependency @angular/localize @ "13.2.6" (was "13.2.2")...
    Updating package.json with dependency @angular/platform-browser @ "13.2.6" (was "13.2.2")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "13.2.6" (was "13.2.2")...
    Updating package.json with dependency @angular/router @ "13.2.6" (was "13.2.2")...
  UPDATE package.json (4395 bytes)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: pfasolutions.firm-view.client@0.0.0
npm ERR! Found: @angular/animations@13.2.2
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"13.2.6" from the root project
npm ERR!   peerOptional @angular/animations@"13.2.2" from @angular/platform-browser@13.2.2
npm ERR!   node_modules/@angular/platform-browser
npm ERR!     @angular/platform-browser@"13.2.6" from the root project
npm ERR!     peer @angular/platform-browser@"13.2.2" from @angular/forms@13.2.2
npm ERR!     node_modules/@angular/forms
npm ERR!       @angular/forms@"13.2.6" from the root project
npm ERR!       3 more (@ng-bootstrap/ng-bootstrap, @ng-select/ng-select, primeng)
npm ERR!     4 more (@angular/platform-browser-dynamic, @angular/router, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @angular/animations@"13.2.6" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/core@13.2.6
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"13.2.6" from @angular/animations@13.2.6
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"13.2.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by mrsegen** [comment] 2022-03-10 14:19
Would this have anything to do with @angular/animations being held at a 12 version? https://github.com/angular/angular/blob/6f1c941dfec8cf0ea0ccbb0fda76f3d960fd843b/package.json#L45

**Comment by alan-agius4** [comment] 2022-03-10 14:23
@mrsegen, the package.json shown there is used by the angular repo and it's not the package.json of the distributable. 

The problem you are experiencing is a known NPM issue https://github.com/npm/cli/issues/3666. As a workaround you can  use the `--force` option.

**Comment by uweDuesing** [comment] 2022-03-10 19:55
Thanks for your help, Uwe
