### ISSUE TITLE
Avoid creating component with unicode naming, instead of throwing error after finishing creation.

### ISSUE THREAD

**Issue by nobodxbodon** [angular/angular-cli#8397] opened 2017-11-08 08:17 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Angular CLI: 1.5.0
Node: 8.7.0
OS: darwin x64

### Repro steps.

Using unicode naming when creating component succeeds:
```
$ ng generate component 英雄
  create src/app/英雄/英雄.component.css (0 bytes)
  create src/app/英雄/英雄.component.html (25 bytes)
  create src/app/英雄/英雄.component.spec.ts (628 bytes)
  create src/app/英雄/英雄.component.ts (310 bytes)
  update src/app/app.module.ts (398 bytes)
```
But it results in error.

### The log given by the failure.

As @clydin kindly pointed out [below](https://github.com/angular/angular-cli/issues/8397#issuecomment-342840475), error below is the same as https://github.com/angular/angular-cli/issues/8386, thus most likely not related with the unicode naming.
```
英雄.component.ts:7 Uncaught ReferenceError: ViewEncapsulation is not defined
    at eval (英雄.component.ts:7)
    at eval (英雄.component.ts:18)
    at Object.../../../../../src/app/英雄/英雄.component.ts (main.bundle.js:58)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (app.module.ts:5)
    at Object.../../../../../src/app/app.module.ts (main.bundle.js:36)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (main.ts:4)
    at Object.../../../../../src/main.ts (main.bundle.js:74)
    at __webpack_require__ (inline.bundle.js:55)
```

### Desired functionality.

Error out when creating component in such way, similar as creating a project with unicode naming:
```
$ ng new 英雄榜
Project name "英雄榜" is not valid. New project names must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter.
英雄榜
^
```

**Comment by adityaparab** [comment] 2017-11-08 09:50
If this is not being worked on by anyone, I'd like to work on this.

**Comment by clydin** [comment] 2017-11-08 14:51
The error shown above is a known issue (https://github.com/angular/angular-cli/issues/8386)  and is not related to unicode filenames.

**Comment by nobodxbodon** [comment] 2017-11-08 15:05
Thanks for the heads up, and It does result in the same error. But as far as I know, Angular doesn't support unicode naming in component. If that's the case, the issue still holds, right?

**Comment by Brocco** [comment] 2017-11-14 03:14
This issue has been reported several times and is currently being tracked via #8398 closing this issue.
Duplicate of #8398

**Closed by Brocco** 2017-11-14 03:14 UTC

**Comment by nobodxbodon** [comment] 2017-11-14 03:21
@Brocco like I mentioned above, the error was a side effect of the issue, but the focus of this issue is to avoid creating component with unicde naming through cli tool. In other words, for current implementation, `ng generate component foo` is legit, but `ng generate component 英雄` should not be considered as legit, as component with unicode naming isn't supported. So IMO the issue isn't duplicate.
