### ISSUE TITLE
"ng new" does not handle project name properly

### ISSUE THREAD

**Issue by pmerlo** [angular/angular-cli#12718] opened 2018-10-23 16:56 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### Command (mark with an `x`)
```
- [x] new
```

### Versions

node
```
v8.11.4
```
npm
```
6.4.1
```
ng
```
Angular CLI: 7.0.2
Node: 8.11.4
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3
```
OS
```
Ubuntu 16.04.5 LTS
Linux 4.15.0-36-generic x86_64
```

### Repro steps
Run `ng new` and enter and invalid name like `example-01` when you are asked to. You will be asked to enter the project name again and again...

### The log given by the failure
Nothing.

### Desired functionality
Immediately inform the user that the project name is invalid and why and/or exit immediately.

### Mention any other details that might be useful
Running `ng new example-01` does print something but it is not very helpful either:
```
Schematic input does not validate against the Schema: {"name":"example-01","version":"7.0.2","routing":true,"style":"scss"}
Errors:

  Data path ".name" should match format "html-selector".
```
I have seen this issue already been reported and the ouput seems to be more descriptive if run on Windows. It would be great if it were so for Ubuntu too.

**Comment by alan-agius4** [comment] 2020-12-01 09:49
Duplicate of https://github.com/angular/angular-cli/issues/11051

**Closed by alan-agius4** 2020-12-01 09:49 UTC
Labels: comp: schematics/angular, freq1: low, severity2: inconvenient
