### ISSUE TITLE
Cannot assign to read only property '_showWarnings' of object '#<Object>'

### ISSUE THREAD

**Issue by harsh7510** [angular/angular-cli#18002] opened 2020-06-24 05:49 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [x]build:ssr

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
"@angular-devkit/build-angular": "0.803.28"
"@angular/cli": "8.0.2",

### Description

 A clear and concise description of the problem...
I tried to add server-side rendering in my existing angular 8 project.
when I do "npm run build:ssr" this error is coming. 

## 🔥 Exception or Error
<pre><code>

<code>
TypeError: Cannot assign to read only property '_showWarnings' of object '#<Object>'
    at TapSubscriber._visitJsonRecursive.pipe.operators_1.tap.x [as _tapNext] (F:\pro\rk\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\json\schema\visitor.js:56:210)
    at TapSubscriber._next (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\operators\tap.js:59:27)
    at TapSubscriber.Subscriber.next (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:66:18)
    at F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeTo.js:17:28
    at Object.subscribeToResult (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:76:14)
    at MergeMapSubscriber._next (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\observable\scalar.js:6:20)
    at Observable._trySubscribe (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:30:22)
    at MergeMapOperator.call (F:\pro\ang8\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:39:23)
</code>
</pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-06-24 07:10
Duplicate of https://github.com/angular/angular-cli/issues/16087

**Closed by alan-agius4** 2020-06-24 07:11 UTC

**Comment by harsh7510** [comment] 2020-06-24 08:31
@alan-agius4  thanks, bro. this helps me a lot. It fixed the error.
