### ISSUE TITLE
Conflicts occur when the `host` and `open` parameters are used at the same time

### ISSUE THREAD

**Issue by asnowwolf** [angular/angular-cli#5729] opened 2017-03-29 06:31 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.10.0
os: darwin x64

### Repro steps.

1. run `ng serve --host 0.0.0.0 --open`
2. try to open `http://0.0.0.0:4200` (Can't open)

### Desired functionality.

open `http://127.0.0.1:4200` in the browser

**Comment by RicardoVaranda** [comment] 2017-03-29 23:09
Hey @asnowwolf ,

This sounds like a local issue, what OS are you using? 
I'm on OSX Sierra and the command you posted works as intended and does open the application correctly.

**Comment by filipesilva** [comment] 2017-05-22 10:01
Fixed by https://github.com/angular/angular-cli/pull/5743

**Closed by filipesilva** 2017-05-22 10:01 UTC
Labels: effort1: easy (hours), freq1: low, priority: 2 (required), severity1: confusing
