### ISSUE TITLE
After adding other projects like ag-grid of ng2-bootstrap the basic webpack build process stops and 20% 

### ISSUE THREAD

**Issue by SteveStrongBAH** [angular/angular-cli#3556] opened 2016-12-14 13:32 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 7 and win 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
![image](https://cloud.githubusercontent.com/assets/19686538/21183792/929ce334-c1d7-11e6-8ac3-1f6f5da84584.png)

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

![image](https://cloud.githubusercontent.com/assets/19686538/21183711/28a68eda-c1d7-11e6-8827-e5d63aa76358.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ipassynk** [comment] 2016-12-14 17:14
The same for me after upgrade to 1.0.0-beta.22-1:

> promo-client@0.0.0 start xxxxx/promo-client
> ng serve --host 0.0.0.0 --port 5555 --proxy-config proxy.conf.json

** NG Live Development Server is running on http://0.0.0.0:5555. **                                                  10% building modules 3/3 modules 0 active[HPM] Proxy created: /api  ->  http://localhost:8080
[HPM] Proxy created: /oauth  ->  http://localhost:8080           25% building modules 125/125 modules 0 activewebpack: wait until bundle finished: /                                                

and no any message after at all.

**Comment by ipassynk** [comment] 2016-12-14 17:49
I narrowed down the issue - if I remove provideAuth from angular2-jwt from the list of providers in the app.module, angular-cli doesn't get stuck on 25%.

```
import {provideAuth} from 'angular2-jwt';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [
    // if  provideAuth is not there - angular-cli can build
    provideAuth({
      headerPrefix: 'Bearer',
      tokenName: 'test',
      globalHeaders: [{'Content-Type': 'application/json'}],
      noJwtError: false,
      noTokenScheme: true,
      tokenGetter: (() => localStorage.getItem('test'))
    })
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by SteveStrongBAH** [comment] 2016-12-14 19:19
What I see above has nothing to do what I am doing, yet I have the same problem.   I thought is was about webpack trying to 'join' two different versions of NgModule together, my own and what ag-grid  provides, but we do not get enough info from the build step to know what is going wrong.

**Comment by hansl** [comment] 2016-12-14 22:27
What does `provideAuth` look like? That seems to be a function that cannot be statically analyzable.

**Comment by ipassynk** [comment] 2016-12-14 22:33
Here is a link to https://github.com/auth0/angular2-jwt that defines provideAuth. We use the same provideAuth with angular-cli 1.0.0-beta.20-4 and it works.

**Comment by hansl** [comment] 2016-12-15 01:37
Seems like they already have an issue for AOT compatibility: https://github.com/auth0/angular2-jwt/pull/202

Even though we're not compiling using AOT we still use the same analysis to figure out routes. We're coming with better ways to display errors, but basically this means that `provideAuth` is not statically analyzable. You'll have to wait for a fix from their library, or not use that function.

Closing this as it's intended behaviour, although we have a tracking issue for the error messaging.

**Closed by hansl** 2016-12-15 01:37 UTC
