### ISSUE TITLE
race condition due to async beforeEach and normal beforeEach?

### ISSUE THREAD

**Issue by MeMeMax** [angular/angular-cli#12032] opened 2018-08-29 10:45 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 6.1.1
Node: 10.8.0
OS: linux x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.1
@angular-devkit/core         0.7.1
@angular-devkit/schematics   0.7.1
@schematics/angular          0.7.1
@schematics/update           0.7.1
rxjs                         6.2.2
typescript                   2.7.2

npm: 6.3.0
Linux Ubuntu 18.04

### Repro steps
Can´t be reproduced. Occurs occasionally.

### The log given by the failure
HeadlessChrome 0.0.0 (Ubuntu 0.0.0) ERROR
  {
    "message": "An error was thrown in afterAll\n[object ErrorEvent] thrown",
    "str": "An error was thrown in afterAll\n[object ErrorEvent] thrown"
  }
[1A[2KHeadlessChrome 0.0.0 (Ubuntu 0.0.0) ERROR
  {
    "message": "An error was thrown in afterAll\n[object ErrorEvent] thrown",
    "str": "An error was thrown in afterAll\n[object ErrorEvent] thrown"
  }
HeadlessChrome 0.0.0 (Ubuntu 0.0.0): Executed 239 of 239 ERROR (0 secs / 1 min 7.031 secs)
HeadlessChrome 0.0.0 (Ubuntu 0.0.0) ERROR
  {
    "message": "An error was thrown in afterAll\n[object ErrorEvent] thrown",
    "str": "An error was thrown in afterAll\n[object ErrorEvent] thrown"
  }
HeadlessChrome 0.0.0 (Ubuntu 0.0.0) ERROR
  {
    "message": "An error was thrown in afterAll\n[object ErrorEvent] thrown",
    "str": "An error was thrown in afterAll\n[object ErrorEvent] thrown"
  }

### Desired functionality
No such error message.

### Mention any other details that might be useful
This error occurs after all the tests have been completed successfull on our build server. It is not reproduceable and occurs occasionally. Therefore I wonder if this could be a race condition of the async and the normal beforeEach. I do not have any afterAll in my project.

**Comment by filipesilva** [comment] 2018-09-03 07:54
Is this using `ng test` or `ng e2e`?

The description doesn't ring any bells to me. I can leave the issue open to see if someone else is running into it, but as is there isn't much to go on with.

Even though it happens only occasionally it should be possible for a repro to be created though. The repro might not be consistent, but should be able to show the problem once it runs enough times.

**Comment by filipesilva** [comment] 2018-09-03 08:42
Yeah this seems like a duplicate of https://github.com/angular/angular-cli/issues/11968 from the stack errors. Will followup up there.

**Closed by filipesilva** 2018-09-03 08:42 UTC
Labels: comp: devkit/build-angular, need: repro steps
