### ISSUE TITLE
Always uses dev environment config after eject

### ISSUE THREAD

**Issue by sodper** [angular/angular-cli#5433] opened 2017-03-15 10:47 UTC
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report
- [ ] feature request

### Versions.
```@angular/cli: 1.0.0-rc.2 (e)
node: 6.9.5
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9
```
Windows 7

### Repro steps.
1. Generate new app
2. Edit `environment.ts` with a new property with a unique string value
```
uniqueProp: "my-dev-prop"
```
3. [_Not really necessary since it's already included in main.ts_] Import the environment config in any `.ts` file, for example in `app.module.ts`
```
import {environment} from '../environments/environment';
```
4. run `ng eject --prod --e prod`
5. run `npm run build`
6. run a search through files in `dist/` looking for unique value specified in step 2

### Desired functionality.
To have production environment configuration used when building.
(or given above mentioned repro steps to not find the specified string value)

### Mention any other details that might be useful.
I'm running the commands from Git Bash.

**Comment by alvaro450** [comment] 2017-03-17 03:39
@sodper I believe the arguments you are using are incorrect, try using: 
ng eject -e prod 
or 
ng eject --environment prod

it worked for me.

**Comment by sodper** [comment] 2017-03-17 09:16
I just tried the repro steps with both `ng eject -e prod` and `ng eject --environment prod` and I still get the same results. Are you running the same versions as I am?

**Comment by filipesilva** [comment] 2017-03-18 13:15
Dupe of https://github.com/angular/angular-cli/issues/4907

**Comment by sodper** [comment] 2017-03-18 19:50
@filipesilva I don't agree with you that this is a duplicate of #4907. The issue I'm having is that the webpack config generated by `ng eject --environment=prod` doesn't use the `environment.prod.ts`, even though it's declared in the AOT plugin like so:

```
hostReplacementPaths: {
  'environments/environment.ts': 'environments/environment.prod.ts'
}
```

Have you tried to reproduce the issue with the above stated repro steps?

**Comment by filipesilva** [comment] 2017-03-18 20:21
Apologies, I misunderstood. Reopening.

**Comment by alvaro450** [comment] 2017-03-18 20:35
My cli version is rc2. The only difference is that I'm on a mac.

**Comment by berhir** [comment] 2017-04-10 12:09
I am facing the same problem. Is there a workaround?

**Comment by dominique-mueller** [comment] 2017-04-12 20:04
Same issue here. Seems that the AoT Plugin is broken. Or do we miss something in the Webpack configuration?

**Comment by TheLegion** [comment] 2017-04-20 03:00
Error is in WebpackCompilerHost used by AoT Plugin. While replacing 'environments\\environment.ts' with 'environments\\environment.prod.ts' in writeFile, file path is normalizing to Windows-style by utilite path, e. g. 'environments\\environment.ts' transforms to something like 'C:\git\test-app\src\environments\environment.ts'. But later, when compiler is looking for environment file, it is looking for unix-style path, e. g. 'C:/git/test-app/src/environments/environment.ts'. File paths does not match and compiler uses original environment file instead of replacement.

**Comment by harouny** [comment] 2017-04-20 04:58
@TheLegion thanks :) any workaround?

**Comment by carl09** [comment] 2017-04-20 05:20
Hi @harouny 

The workaround i am using is two part, one for dev and one for build, but they work side by side.

first in the webpack config under resolve i add an alias for enviroment like:
`
resolve: {
  extensions: ['.ts', '.js', '.scss'],
  alias: {
    environment: helpers.environment(options.ENV),
  }
}
`
helpers.environment(options.ENV) just returns the path to my enviroment file eg ./src/environments/dev/index.ts

then in the tsconfig.json i update the paths node like:
`
"paths": {
      "environment": [
        "./environments"
      ]
    }
`

lastly i have updated the imports to be: import { environment } from 'environment';
rather then:  import {environment} from '../environments/environment';

i have changed the file name from environment.ts to index.ts for simplisity,
hope this makes sense

**Comment by kotmatpockuh** [comment] 2017-05-17 10:54
any news?

**Comment by kotmatpockuh** [comment] 2017-05-17 11:13
@carl09 what is `helpers.`?

**Comment by sujay1848** [comment] 2017-11-15 09:45
@kotmatpockuh A sample content of `helpers` can be found [here](https://angular.io/guide/webpack#configuring-webpack).

**Comment by odahcam** [comment] 2018-01-30 17:17
My workaround:

```
        // use this before AngularCompilerPlugin in your webpack.prod.js
        new webpack.NormalModuleReplacementPlugin(/\.\.\/environments\/environment/, '../environments/environment.prod')
```

**Comment by clydin** [comment] 2018-09-28 16:34
eject functionality is no longer available in the latest version (6.0+).  For custom webpack configurations the following unofficial add-on is a suggested solution: https://github.com/manfredsteyer/ngx-build-plus

**Closed by clydin** 2018-09-28 16:34 UTC
Labels: comp: angular/cli
