### ISSUE TITLE
ng build --base-href flag not setting correct relative file path

### ISSUE THREAD

**Issue by brookhutchinson** [angular/angular-cli#7746] opened 2017-09-19 16:24 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.2
node: 6.11.3
os: win32 x64
Windows 10

### Repro steps.
If your Angular App files are located in a subfolder under the root folder on your website.
Example root/projects/abc

ng build --prod --base-href /projects/abc/

The Angular CLI creates the static asset files inside the "dist" folder correctly
Open dist/index.html and you will see that the Angular CLI did not set the <base href=""> file path value correctly.  The correct file path value should be <base href="/projects/abc/".  Instead Angular CLI set the file path value as follows <base href="C:\Program Files\Git\...\Websites\projects\abc"> 

Looks like the Angular CLI is using the absolute file path of the "abc" folder location to set the <base href=""> value instead of using the relative file path value "/projects/abc/" that is passed as a parameter to the "ng build" command

**Comment by clydin** [comment] 2017-09-19 16:58
What shell are you using?  I'm guessing that it may be trying to be helpful and is expanding the path for you.  Can you try quoting the argument?

**Comment by brookhutchinson** [comment] 2017-09-20 21:45
I am using Git Bash.  I tried putting the command line argument value for the --base-href flag inside quotes and unfortunately this yielded the same result. Unfortunately the value is not getting set correctly inside the generated dist\index.html file.  If I open the dist/index.html the value that is generated by the ng build command the <base href=""> is set to the value "C:/Program Files/Git/projects/abc"

The goal is to have the value set to <base href="/projects/abc/"> 

Here is the ng build command that I tried from the Git Bash Command Line using quotes
ng build --prod --base-href "/projects/abc/"

**Comment by filipesilva** [comment] 2017-09-21 09:29
Heya, this is a duplicate of https://github.com/angular/angular-cli/issues/7746. There's a tentative workaround there. This is something we can truly fix on the CLI side :/

**Closed by filipesilva** 2017-09-21 09:29 UTC

**Comment by mbukejlovic** [comment] 2018-01-03 13:05
I'm also experiencing this issue. Did anyone find a fix for this or a workaround?
Btw, @filipesilva, this IS the issue 7746 :) what do you mean it's a duplicate of itself? :)

**Comment by arthurspa** [comment] 2018-01-30 20:11
I was with the same problem.

It seems that Git Bash command line was expanding the path. 

After trying running the command with windows cmd, it worked as expected.

**Comment by bownie** [comment] 2018-04-13 14:38
The path is being expanded probably because you need to specify '=' to set the base-href.

Having said that I have also seen problems though - base-href gets updated but when building for prod the asset paths are incorrect.

**Comment by nngo** [comment] 2018-09-26 21:06
I have the same issue on Git Bash Shell v4.4.19 (MINGW64) under Windows with Angular CLI v6.2.3.
I have tried all of the following and none of them worked.
```
ng build  --base-href /foo
ng build  --base-href /foo/
ng build  --base-href "/foo"
ng build  --base-href "/foo/"
ng build  --base-href '/foo'
ng build  --base-href '/foo/'
ng build  --base-href='/foo'
ng build  --base-href="/foo/"
ng build  --base-href=/foo/
```

**Comment by arthurspa** [comment] 2018-10-04 07:42
@nngo in your case, if you want to get `<base href="/foo/">`, try the following:

```
ng build --bash-href //foo/
```

using double forward slashs. I'm using conemu with git bash and it worked for me.

I hope it helps.

**Comment by nngo** [comment] 2018-10-05 17:54
That is still does not produce that I am looking for, e.g. running following in Git Bash terminal
```
ng build --base-href //foo/
```

that produces `<base href="//foo/">`

BTW:  using  "ng build --bas**h**-href //foo/" produces following error:
`Unknown option: '--bashHref'

@arthurspa thanks for the "workaround" using `cmd.exe`. From my Windows 10 command prompt, `ng build --base-href /foo` produces the proper index.html.

**Comment by nngo** [comment] 2018-10-09 18:08
I have found two additional workarounds while working from Git Bash for Windows. Add the `--base-href /foo/` option inside either `package.json` (as parameter to a script under "scripts", e.g. to the "build" script) or to `angular.json` (under "projects" > "architect" > "build" > "options" > add `"baseHref": "/foo/"`

**Comment by developergoutam** [comment] 2019-04-23 22:38
I run this command from unix/linux console and it worked.
ng build --base-href /foo/
output: index.html
<base href="/foo/">
