### ISSUE TITLE
ng serve failed to serve project after upgrade to angular cli beta.32

### ISSUE THREAD

**Issue by zolekm** [angular/angular-cli#4819] opened 2017-02-18 22:12 UTC
### OS?
>Mac OSX Sierra

### Versions.
> @angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.26]
> node v7.5.0

### The log given by the failure.
> Normally this include a stack trace and some more information.

** NG Live Development Server is running on http://localhost:4200. **
 92% chunk asset optimization                                                              
<--- Last few GCs --->

[9033:0x103801600]   280307 ms: Mark-sweep 1451.8 (1580.0) -> 1451.8 (1580.0) MB, 1467.8 / 0.0 ms  allocation failure GC in old space requested
[9033:0x103801600]   281966 ms: Mark-sweep 1451.8 (1580.0) -> 1451.7 (1542.0) MB, 1658.3 / 0.0 ms  last resort gc 
[9033:0x103801600]   283424 ms: Mark-sweep 1451.7 (1542.0) -> 1451.7 (1542.0) MB, 1457.1 / 0.0 ms  last resort gc 

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x32eb04dc0d39 <JS Object>
    2: add(aka MappingList_add) [/Users/x/Projects/node_modules/source-map/lib/mapping-list.js:55] [pc=0xbbe3ce77483](this=0x38f4e9c898e1 <a MappingList with map 0x3c2afbbc1d51>,aMapping=0xa5605898121 <an Object with map 0x32f926a40639>)
    3: addMapping(aka SourceMapGenerator_addMapping) [/Users/x/Projects/node_modules/source-map/lib...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 6: v8::internal::(anonymous namespace)::FastElementsAccessor<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::AddArguments(v8::internal::Handle<v8::internal::JSArray>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::Arguments*, unsigned int, v8::internal::(anonymous namespace)::Where) [/usr/local/bin/node]
 7: v8::internal::(anonymous namespace)::DoArrayPush(v8::internal::Isolate*, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 8: 0xbbe3b008506
 9: 0xbbe3b02aea5
sh: line 1:  9033 Abort trap: 6           ng serve

Command ng serve fail if use npm linked modules

**Comment by Nikki1993** [comment] 2017-02-19 08:51
Check out this issue which seems to be related to your case [#1652](https://github.com/angular/angular-cli/issues/1652) and as a workaround for now try settings bigger `heap size node --max_old_space_size=2048 ./node_modules/.bin/ng serve`

**Comment by zolekm** [comment] 2017-02-20 08:40
@Nikki1993 tnx for help, actually the problem is when i'm using npm link modules if there is no npm link inside node_modules then is everything ok. Currently i'm using beta.26 because in that release npm link modules works.

**Comment by filipesilva** [comment] 2017-03-13 17:45
Dupe of https://github.com/angular/angular-cli/issues/3875

**Closed by filipesilva** 2017-03-13 17:45 UTC
