### ISSUE TITLE
angular cli - install stuck when extract rxjs 

### ISSUE THREAD

**Issue by Nagarajan8194** [angular/angular-cli#9942] opened 2018-03-12 06:05 UTC
when run "npm install -g @angular/cli" it will run for some time and its get struck when extracting rxjs . Please help me. i already set proxy configuration. 
### Versions
```

```
node version : 
8.10.0
NPM version : 
5.6.0
 am using windows 10.

### Repro steps

when installation get stuck:
extract:rxjs: sill pacote rxjs@https://registry.npmjs.org/rxjs/-/rxjs-5.5.6.tgz extracted to C:\Users\p00115856\AppData\Roaming\npm\node_modules

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

### Mention any other details that might be useful (optional)

![image](https://user-images.githubusercontent.com/37285424/37268026-bae928ee-25e9-11e8-91b0-ea4d98e8d1d9.png)

**Comment by ZackKnopp** [comment] 2018-03-12 17:33
Possible duplicate of https://github.com/angular/angular-cli/issues/8367

I followed @avalanchy's solution and it worked for me.

"Ok, it unfreezes after a long time.

From the output grabbed this gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.9.1". After googling this line I found a solution of adding an extra flag "unsafe-perm" (which is not documented in npm install manual) that fixes the problem:

sudo npm i --unsafe-perm --verbose -g @angular/cli  "

**Comment by Brocco** [comment] 2018-03-13 00:10
This appears to be an npm installation issue, which is not something that we're able to assist with, please see the possible duplicate issue above.

**Closed by Brocco** 2018-03-13 00:10 UTC

**Comment by gfaganli** [comment] 2018-07-23 12:43
i also have the same problem while upgrading to angular 6, any solution?

**Comment by jmaFinistereVar** [comment] 2018-08-01 09:41
I have the exact same problem using windows10, node v8.9.3, npm5.5.1
I tried 
`npm install --unsafe-perm 
`
but the command freezes

`extract:rxjs: sill pacote rxjs@https://registry.npmjs.org/rxjs/-/rxjs-6.2.2.tgz`

![image](https://user-images.githubusercontent.com/14360444/43514129-cf83f7f6-957f-11e8-9a50-25c8ed181f74.png)

**Comment by geekyarthurs** [comment] 2018-08-25 16:48
use administrator permission to open cmd :) 💯

**Comment by ashraphs** [comment] 2018-09-24 08:55
hi guys, any fix ?
already open the cmd as admin, but still stuck

**Comment by radhemohan** [comment] 2018-10-02 05:30
By providing write access to node_modules and installing packages by
npm i --unsafe-perm --verbose install
Solved by problem. Thanks to all

**Comment by opit** [comment] 2018-10-29 13:06
@ashraphs its a long shot, but are you running in a vagrant VM? npm install creates a lot of I/O on the virtual machine that might make it crash. I just ran into this issue this morning on ubuntu/bionic64 see error description here: https://www.virtualbox.org/ticket/16417

Only occurs on a shared folder though, so hotfix for me was to copy the package.json in a folder that was not shared between guest and host system, run npm -i there and then cp -r the node_modules folder over afterwards.

Good luck.

**Comment by presidiomep** [comment] 2018-11-03 20:08
I had the SAME issue: installation stalled on rsjx. Closed down the terminal, and restarted the process again, same issue the second time, BUT, I decided to let it sit and came back 30 mins later and it worked! I guess it just took time??

**Comment by Peter1234444** [comment] 2018-11-15 14:59
@radhemohan found your solution worked thanks! I
Instead of "npm i --unsafe-perm --verbose install" I wrote
sudo npm i --unsafe-perm --verbose install

not sure if adding sudo actually did anything or not but the code still worked fine.

**Comment by smartnav** [comment] 2019-07-16 15:50
Install dependency one by one then it will work.

**Comment by RadhakrishnaGitLab** [comment] 2019-08-07 10:07
If you are running behind proxy, Configure proxy for npm and Git by running below commands.
NPM:
$ npm config set https-proxy http://proxy.[Company Name].com:8080
$ npm config set https-proxy http://proxy.[Company Name].com:8080
In case proxy needs credentials, you need to pass credentials like below,
$ npm config set https-proxy http://<username>:<password>@proxy.[Company Name].com:[Port]
$ npm config set https-proxy http://<username>:<password>@proxy.[Company Name].com:[Port]

Git:
$ git config --global http.proxy http://<username>:<password>@<proxy-server-url>:<port>

This Resolved my problem. Hope this info will help you all

**Comment by hypnotic-frog** [comment] 2019-08-29 16:42
This is why I hate Node and all the related sh.... that comes with it. The process of problem solving is so arbitrary you never know what to expect. 
I sincerely hope some day when I hit `npm install`, the floor cracks and I finally may die burned by the flames of hell, so I have not to suffer all of this over again.
