### ISSUE TITLE
error in updating angular 11 to 12

### ISSUE THREAD

**Issue by behroozbc** [angular/angular-cli#22102] opened 2021-11-05 13:40 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes. six month ago I updated this project 10 to 11 and be okay 
### Description
I want update my angular project from version 11 to version 12 
but get error 
## 🔬 Minimal Reproduction
I have angular project with version 11 
Go to update.angular.io 
Select version 11 to 12 
run ```npx @angular/cli@12 update @angular/core@12 @angular/cli@12```
Get Error 

## 🔥 Exception or Error

<pre><code>

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: tracker@1.1.153
npm ERR! Found: @angular-devkit/build-angular@0.1102.3
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~12.2.13" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~12.2.13" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/compiler-cli@12.2.13
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^12.0.0" from @angular-devkit/build-angular@12.2.13
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~12.2.13" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\behro\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\behro\AppData\Local\npm-cache\_logs\2021-11-05T13_14_24_506Z-debug.log
✖ Package install failed, see above.

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.10
Node: 16.13.0 (Unsupported)
Package Manager: npm 8.1.0
OS: win32 x64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core
... flex-layout, forms, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.10 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            12.2.10 (cli-only)
@angular-devkit/schematics      12.2.10 (cli-only)
@angular/cli                    12.2.10 (cli-only)
@schematics/angular             12.2.10 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      <error>

Warning: The current version of Node (16.13.0) is not supported by Angular.
</code></pre>
I attach log file 
[2021-11-05T13_14_24_506Z-debug.log](https://github.com/angular/angular-cli/files/7486378/2021-11-05T13_14_24_506Z-debug.log)

**Comment by alan-agius4** [comment] 2021-11-05 13:51
Duplicate of https://github.com/angular/angular-cli/issues/21204

**Closed by alan-agius4** 2021-11-05 13:51 UTC
Labels: npm 7
