### ISSUE TITLE
Styling cursor with url does not work, second parameter is lost after compilation

### ISSUE THREAD

**Issue by BlindDespair** [angular/angular-cli#9709] opened 2018-02-21 08:35 UTC
### Versions
```
@angular/cli: 1.7.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.3.4
webpack: 3.11.0
```
### Repro steps

Create scss file with styles.
Add class which has cursor style using asset file, e.g.
```scss
cursor: url('../../../assets/cursors/grab.cur'), move;
```

### Observed behavior
It compiles to
```scss
cursor: url(grab.b06c243f534d9c5461d1.cur);
```

### Desired behavior
Should be 
```scss
cursor: url(grab.b06c243f534d9c5461d1.cur), move;
```

### Mention any other details that might be useful (optional)
I tried same on 1.6.8 and it worked fine. Style for cursor provided with url does not work without second parameter.

**Comment by clydin** [comment] 2018-02-22 20:54
Duplicate of #9642

**Closed by clydin** 2018-02-22 20:54 UTC
