### ISSUE TITLE
Bundling into one file

### ISSUE THREAD

**Issue by davidstellini** [angular/angular-cli#4496] opened 2017-02-07 17:31 UTC
After an `ng build --prod`, a directory listing of `dist` looks like this:

```
inline.bundle.js 
main.bundle.js
polyfills.bundle.js
styles.bundle.js 
vendor.bundle.js
index.html
```

I am creating a widget and would like a consumer to include only one file - `widget.js`. Is reverting to webpack the only option I have?

**Comment by jgainfort** [comment] 2017-02-10 23:28
You could create a custom script to concat the files after the `ng build --prod` maybe on a repo pipeline, cd/ci hook, or create a custom script in the package.json
`
"build": "ng build --prod && gulp concat"
`
Just make sure to keep the same order though.

inline -> styles -> scripts -> vendor -> main

**Comment by filipesilva** [comment] 2017-03-09 12:06
Dupe of #3288.

**Closed by filipesilva** 2017-03-09 12:06 UTC
