### ISSUE TITLE
SSR angular cli

### ISSUE THREAD

**Issue by adwaer** [angular/angular-cli#6944] opened 2017-07-11 20:27 UTC
### Desired functionality.
Hello! Will the ssr be added to cli?
If yes: when?
If no: what should we use?

**Comment by intellix** [comment] 2017-07-12 03:21
Duplicate of #1050

**Comment by adwaer** [comment] 2017-07-12 08:42
No, it's not. I'm asking about Angular 4

**Comment by intellix** [comment] 2017-07-12 11:36
SSR = Angular Universal
Which the above issue is discussing in regards to it's added support in CLI. The issue is around a year old so I believe the title mentions 2 but support will only exist for SSR for 4

**Closed** 2017-07-13 09:28 UTC
