### ISSUE TITLE
Please update webpack to 4.29.5 for angular v.7

### ISSUE THREAD

**Issue by AstRonin** [angular/angular-cli#13741] opened 2019-02-22 09:48 UTC
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [X] version
- [ ] doc
```

### Description
Because webpack v.4.29.0 has some bugs like this: https://github.com/webpack/webpack/issues/8656
And I cannot set version of webpack in package.json in devDependencies myself through the error:
`Error: No module factory available for dependency type: ContextElementDependency`

### Describe the solution you'd like
Please update webpack to 4.29.5 for angular v.7

**Comment by alan-agius4** [comment] 2019-02-22 12:37
By the way typically this error `Error: No module factory available for dependency type: ContextElementDependency` means that you have multiple versions of webpack installed.

**Comment by AstRonin** [comment] 2019-02-22 14:10
Yes, I wrote about that, that why I cannot set version of webpack myself...

**Comment by alan-agius4** [comment] 2019-02-22 15:29
Hi, we have looked into this and it seems that the issue is not yet resolved as a matter of fact it’s an npm bug.

However there are some steps here to get around this https://github.com/webpack/webpack/issues/8656#issuecomment-456010969

**Comment by alan-agius4** [comment] 2019-02-25 08:38
Hi, following the above, I am closing the issues, as the issue reported seems to have been caused by npm itself and updating webpack is not the solution to this problem.

**Closed by alan-agius4** 2019-02-25 08:38 UTC
Labels: comp: devkit/build-angular, freq1: low, severity5: regression, type: bug/fix
