### ISSUE TITLE
build aot failed when having lazy load

### ISSUE THREAD

**Issue by jjlgjkkl** [angular/angular-cli#2602] opened 2016-10-09 06:57 UTC
there is a  loadChildren in my project
export const routes: Routes = [ 
    { path: '', redirectTo: 'test01', pathMatch: 'full'},
    { path: 'test01', loadChildren: 'app/testing01/test01.module' },
 when  ng build --aot
exception occurred:

  0% compiling can't resolve module D:/ng2/aotdemo/src/app/testing01/test01.module.ts from D:/ng2/aotdemo/src/app/testing01/test01.module.ts
can't find symbol MainModule exported from module D:/ng2/aotdemo/src/app/testing01/test01.module.ts
Error: can't find symbol MainModule exported from module D:/ng2/aotdemo/src/app/testing01/test01.module.ts
    at ReflectorHost.findDeclaration (D:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\reflector_host.ts:200:15)
    at _loop_1 (D:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\codegen.ts:62:45)
    at CodeGenerator.readFileMetadata (D:\ng2\aotdemo\node_modules\.npminstall\@angular\compiler-cli\0.6.4\@angular\compiler-cli\src\codegen.js:66:13)
    at D:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\codegen.ts:105:56

i am using

"angular-cli": "1.0.0-beta.17",
@angular 2.0.2

**Comment by duxiaofeng-github** [comment] 2016-10-09 11:29
+1

**Comment by hassanasad** [comment] 2016-10-10 09:33
I could never get loadChildren to work so simply as `loadChildren: 'app/testing01/test01.module'` in webpack.

I use something like this:
```
loadChildren: () => new Promise(resolve => {
	(require as any).ensure([], () => {
		resolve(require('./testing01/test01.module').default);
	})
})
```

and then in the test01.module file
```
export default class Test01Module { }
```

But this might not work for `--aot` flag.

**Comment by filipesilva** [comment] 2016-10-10 16:15
Dupe of https://github.com/angular/angular-cli/issues/2452

**Closed by filipesilva** 2016-10-10 16:15 UTC
