### ISSUE TITLE
ng build --prod  JavaScript heap out of memory

### ISSUE THREAD

**Issue by luomu172** [angular/angular-cli#7616] opened 2017-09-07 03:54 UTC
JavaScript heap out of memory

why？ solution?

**Comment by jotatoledo** [comment] 2017-09-07 09:34
It was already mentioned that its duplicated. Why did you still created the issue?

**Comment by filipesilva** [comment] 2017-09-07 13:40
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #5618. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-09-07 13:40 UTC
