### ISSUE TITLE
Add ability to set keepNames for esbuild

### ISSUE THREAD

**Issue by foxel** [angular/angular-cli#26768] opened 2023-12-29 10:33 UTC
### Command

build, serve

### Description

esbuild optimizes TS code with decorators a bit different to tsc. This is not a huge difference but class names are lost if a class is decorated. There is `keepNames` ([keep-names](https://esbuild.github.io/api/#keep-names)) option in esbuild that ensures the name is restored. It would be great if angular cli expose this opton in angular.json

### Describe the solution you'd like

`keepNames` can be exposed in angular.json under AngularDevkitBuildAngularBuildersBrowserEsbuildSchema

getEsBuildCommonOptions in this case should just forward this option to BuildOptions

### Describe alternatives you've considered

Currently, I've patched `getEsBuildCommonOptions` to set `keepNames` as `!optimizationOptions.scripts` within my project. 
Setting the keepNames this way might be an alternative, but explicit exposure is best IMHO

**Comment by alan-agius4** [comment] 2023-12-29 11:04
Duplicate of https://github.com/angular/angular-cli/issues/15761 and #14487

**Closed by alan-agius4** 2023-12-29 11:04 UTC

**Comment by foxel** [comment] 2023-12-29 12:36
@alan-agius4 how is this a duplicate? I don't see common points
