### ISSUE TITLE
Setting the default style on an existing project (bug)

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular-cli#2639] opened 2016-10-11 05:52 UTC
I just created a new project and forgot to add `--style scss` to `ng new newProject`.

I tried to set the default style on that project using `ng set defaults.styleExt scss` and I got this error
`
Cannot read property 'serialize' of undefined
`

**Comment by RicardoVaranda** [comment] 2016-10-11 07:14
This had been fixed by f7bf0aa

**Comment by moniuch** [comment] 2016-10-11 09:21
Same problem and error, but the solution did not work for me

**Comment by RicardoVaranda** [comment] 2016-10-11 09:37
Make sure to uninstall the cli and clear npm cache before installing the updated version.

**Comment by 07Gond** [comment] 2016-10-11 18:04
Or: **Temporaly solution** (If you don't want reinstall.)

You can edit the file: 
"%PROJECT%\node_modules\angular-cli\models\json-schema\schema-tree" 
and replace the line 235 with:
serializer.property(key, function () { return serializer.outputValue(value[key])});

**Comment by harryjubb** [comment] 2016-10-13 15:52
Can we not just edit `angular-cli.json` and change:

```
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false
  }
```

to:

```
  "defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false
  }
```

Or is it more complex than that?

**Comment by harryjubb** [comment] 2016-10-13 16:00
I also noticed a possible newbie gotcha, in that you also need to change `apps.styles` to include `styles.scss`, assuming you're modifying your global `styles.css` to a `styles.scss`.

**Comment by Meligy** [comment] 2016-10-14 09:51
@harryjubb yes. Changing the property in `angular-cli.json` would work. You'd still have existing .css files unchanged and need to change them all yourself.

Another approach is running `ng init` with the correct parameters from `ng new` (for example: `ng init --style=scss`. This will generate all the default files again, and ask you whether you want to override them or not (offers to show a diff too).

This is how I upgrade my CLI project. I make sure all my files are committed in git, upgrade my global CLI, change CLI version in project's `package.json`, and then run `ng init --style=scss`, accept various files, and then run my Git UI commit dialog, undo lines I don't care about, and commit the good ones (usually they are only few files).

You will still have to delete the old .css files, and update all components (other than AppComponent) to point to .scss files.

**Comment by moniuch** [comment] 2016-10-14 16:12
Thanks @Meligy for your explanation - I think it should be quoted in angular-cli docs/wiki one day!

**Comment by filipesilva** [comment] 2016-10-14 18:40
Dupe of https://github.com/angular/angular-cli/pull/2614

**Closed by filipesilva** 2016-10-14 18:40 UTC
