### ISSUE TITLE
npm i -g angular-cli fails on window: installs broccoli plugin 1.0, 1.1, 1.2 (are all 3 necessary) 

### ISSUE THREAD

**Issue by HansS** [angular/angular-cli#391] opened 2016-04-04 05:12 UTC
Hans@HP-HANS C:\Users\Hans\Web\js\angular20\angular-cli\test-cli
> ng new todo
installing ng2
  create .clang-format
  create angular-cli.json
  create config\environment.js
  create e2e\app.e2e.ts
  create e2e\app.po.ts
  create e2e\tsconfig.json
  create e2e\typings.d.ts
  create angular-cli-build.js
  create .gitignore
  create karma-test-shim.js
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create public\.npmignore
  create src\app\todo.html
  create src\app\todo.spec.ts
  create src\app\todo.ts
  create src\app\route-config.ts
  create src\app.ts
  create src\favicon.ico
  create src\index.html
  create src\tsconfig.json
  create src\typings.d.ts
  create tslint.json
  create typings.json
Successfully initialized git.
Installing packages for tooling via npm..broccoli-plugin 1.0.0: Installing
loadDep:promise-map-serie / |############################-------------------------------------------------------------------------------------------------------------| Installing packages for tooling via npmloadDep:rsvp              - |############################------------------------------------------------------------------------C:\Users\Hans\Web\js\angular20\angular-cli\test-cli\todo\node_modules\angular-cli\node_modules\broccoli\test\multidep\broccoli-plugin-1.0.0
broccoli-plugin@1.0.0Installing packages for tooling via npm
  ├─┬ promise-map-series@0.2.2
  │ └── rsvp@3.2.1
  ├─┬ quick-temp@0.1.5
  │ ├── mktemp@0.3.5
  │ ├── rimraf@2.2.8
underscore.string@2.3.3Installing packages for tooling via npm
  ├─┬ .rimraf@2.5.2
  │ └─┬ glob@7.0.3
  │   ├─┬ inflight@1.0.4
  │   │ └── wrappy@1.0.1
  │   ├── inherits@2.0.1
  │   ├─┬ minimatch@3.0.0
  │   │ └─┬ brace-expansion@1.1.3
  │   │   ├── balanced-match@0.3.0
  │   │   └── concat-map@0.0.1
  │   ├── once@1.3.3
  │   └── path-is-absolute@1.0.0
  └─┬ symlink-or-copy@1.0.1
    └── copy-dereference@1.0.0

Installing packages for tooling via npm...broccoli-plugin 1.1.0: Installing
Installing packages for tooling via npmextract -> gunzTarPerm    - |################################################################################################----.extract:once -> gentlyRm  | |#################################################################################################----------------------------------------|C:\Users\Hans\Web\js\angular20\angular-cli\test-cli\todo\node_modules\angular-cli\node_modules\broccoli\test\multidep\broccoli-plugin-1.1.0
└─┬ broccoli-plugin@1.1.0 oling via npm...
  ├─┬ promise-map-series@0.2.2
  │ └── rsvp@3.2.1
  ├─┬ quick-temp@0.1.5
  │ ├── mktemp@0.3.5
  │ ├── rimraf@2.2.8
  │ └── underscore.string@2.3.3
  ├─┬ rimraf@2.5.2
  │ └─┬ glob@7.0.3
  │   ├─┬ inflight@1.0.4
  │   │ └── wrappy@1.0.1
  │   ├── inherits@2.0.1
  │   ├─┬ minimatch@3.0.0
  │   │ └─┬ brace-expansion@1.1.3
  │   │   ├── balanced-match@0.3.0
  │   │   └── concat-map@0.0.1
  │   ├── once@1.3.3
  │   └── path-is-absolute@1.0.0
  └─┬ symlink-or-copy@1.0.1
    └── copy-dereference@1.0.0

Installing packages for tooling via npmbroccoli-plugin 1.2.0: Installing
C:\Users\Hans\Web\js\angular20\angular-cli\test-cli\todo\node_modules\angular-cli\node_modules\broccoli\test\multidep\broccoli-plugin-1.2.0
└─┬ broccoli-plugin@1.2.0 oling via npm
  ├─┬ promise-map-series@0.2.2
  │ └── rsvp@3.2.1
  ├─┬ quick-temp@0.1.5
  │ ├── mktemp@0.3.5
  │ ├── rimraf@2.2.8
  │ └── underscore.string@2.3.3
  ├─┬ rimraf@2.5.2
  │ └─┬ glob@7.0.3
  │   ├─┬ inflight@1.0.4
  │   │ └── wrappy@1.0.1
  │   ├── inherits@2.0.1
  │   ├─┬ minimatch@3.0.0
  │   │ └─┬ brace-expansion@1.1.3
  │   │   ├── balanced-match@0.3.0
  │   │   └── concat-map@0.0.1
  │   ├── once@1.3.3
  │   └── path-is-absolute@1.0.0
  └─┬ symlink-or-copy@1.0.1
    └── copy-dereference@1.0.0

Installing packages for tooling via npm.broccoli-source 1.1.0: Installing
C:\Users\Hans\Web\js\angular20\angular-cli\test-cli\todo\node_modules\angular-cli\node_modules\broccoli\test\multidep\broccoli-source-1.1.0
└── broccoli-source@1.1.0 oling via npm...

├── es6-shim (ambient)
├── angular-protractor (ambient dev)
├── jasmine (ambient dev)
└── selenium-webdriver (ambient dev)

Installed packages for tooling via npm.

**Comment by hansl** [comment] 2016-04-05 22:25
Dupe of #389

**Closed by hansl** 2016-04-05 22:25 UTC
