### ISSUE TITLE
Not able to update to angular 12 build failed with bellow error

### ISSUE THREAD

**Issue by pgsekaran** [angular/angular-cli#22566] opened 2022-01-25 06:32 UTC
# 🐞 Bug report

### Command (mark with an `x`)

Error: Optimization error [main.js]: Error: Transform failed with 1 error:
main.js:219752:5: error: Expected identifier but found "="
    at failureErrorWithLog (C:\Dev 25-1\gehc-edison-ai-workbench-webui\node_modules\@angular-devkit\build-angular\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Dev 25-1\gehc-edison-ai-workbench-webui\node_modules\@angular-devkit\build-angular\node_modules\esbuild\lib\main.js:1282:29
    at C:\Dev 25-1\gehc-edison-ai-workbench-webui\node_modules\@angular-devkit\build-angular\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\Dev 25-1\gehc-edison-ai-workbench-webui\node_modules\@angular-devkit\build-angular\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (C:\Dev 25-1\gehc-edison-ai-workbench-webui\node_modules\@angular-devkit\build-angular\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.2.15
Node: 14.18.3
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 12.2.15
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.15
@angular-devkit/build-angular   12.2.15
@angular-devkit/core            12.2.15
@angular-devkit/schematics      12.2.15
@angular/cdk                    9.2.4
@schematics/angular             12.2.15
rxjs                            7.5.2
typescript                      4.3.5

## 🔬 Minimal Reproduction

Simple steps to reproduce this bug.
After update from angular 11 to 12 build is getting failed.

**Comment by alan-agius4** [comment] 2022-01-25 06:48
Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2022-01-31 10:56
Closing due to the lack of a reproduction. Please feel free to open a new issue with a reproduction if the problem persists.

**Closed by alan-agius4** 2022-01-31 10:56 UTC
Labels: need: repro steps
