### ISSUE TITLE
Unexpected token 'export' with vite dev server

### ISSUE THREAD

**Issue by zip-fa** [angular/angular-cli#26209] opened 2023-11-02 16:23 UTC
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Hi. I am not sure if this related to angular, but vite throws an error and continues to work.
It builds dependency without an issue.

More details, repro: https://github.com/EsotericSoftware/spine-runtimes/issues/2407

### Minimal Reproduction

ng serve

### Exception or Error

```text
Error when evaluating SSR module /main.server.mjs: failed to import "@esotericsoftware/spine-webgl"
|- C:\ng-spine-vite-bug\node_modules\@esotericsoftware\spine-webgl\dist\index.js:1
export * from "./AssetManager";
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

### Your Environment

```text
Angular CLI: 17.0.0-rc.3
Node: 18.18.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.3
@angular-devkit/build-angular   17.0.0-rc.3
@angular-devkit/core            17.0.0-rc.3
@angular-devkit/schematics      17.0.0-rc.1
@angular/cdk                    17.0.0-next.6
@angular/cli                    17.0.0-rc.3
@angular/material               17.0.0-rc.0
@angular/ssr                    17.0.0-next.9
@schematics/angular             16.2.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by alan-agius4** [comment] 2023-11-02 17:21
This problem is caused by the package itself as while it ships ESM modules, it's not fully valid.

The main problems are;
- `"type": "module"` is missing from it's `package.json`
- Files are imported without an extension, example 
```js
export * from "./AssetManager";
```
Instead of 
```js
export * from "./AssetManager.js";
```

Closing as this is not actionable from our end.

**Closed by alan-agius4** 2023-11-02 17:21 UTC
