### ISSUE TITLE
css live-reload not working

### ISSUE THREAD

**Issue by sanlyfang** [angular/angular-cli#878] opened 2016-05-21 07:42 UTC
Mac OSX (El Capitan)

angular-cli: 1.0.0-beta.5
node: 6.2.0
npm: 3.8.9

ng new ng2-demo
cd ng2-demo
ng serve

go to edit generated "ng2-demo.component.css"

browser doesn't reload css changes automatically, has to refresh the page manually to see the change

but live reload works properly for html changes

**Comment by Brocco** [comment] 2016-05-24 01:26
I verified this is occuring

**Comment by tobakk** [comment] 2016-05-25 10:01
same problem on linux mint

**Comment by monojack** [comment] 2016-05-25 11:07
it's the same on any OS, `css` files are not being watched for live reload

**Comment by filipesilva** [comment] 2016-06-02 14:58
Closing as a duplicate of https://github.com/angular/angular-cli/issues/815

**Closed by filipesilva** 2016-06-02 14:58 UTC
Labels: flag: help wanted, priority: 2 (required), type: bug
