### ISSUE TITLE
Component generation schematic is adding additonal comma(,) at the end

### ISSUE THREAD

**Issue by gauravsoni119** [angular/angular-cli#22898] opened 2022-03-27 22:24 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Not sure

### Description

Generating a new component with `--style=none` and `--changeDetection=OnPush` is adding additional comma(`,`) which results into double comma after the `templateUrl`.

## 🔬 Minimal Reproduction
Run the below command in the angular app to reproduce it:-
`npm run ng -- generate c --name=test --style=none --changeDetection=OnPush`

## 🔥 Exception or Error
Below error is thrown when run `ng serve`,
<pre><code>
TS1136: Property assignment expected.

</code></pre>
![ng-cli](https://user-images.githubusercontent.com/8476712/160303470-bad32880-409d-4d30-aa7a-c692af68747b.png)

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.1.4
Node: 14.17.0
Package Manager: npm 6.14.13
OS: linux x64

Angular: 12.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@angular/cli                    12.1.4
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.3.5
    

</code></pre>

**Anything else relevant?**
I think the issue is in [this](https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/component/files/__name%40dasherize%40if-flat__/__name%40dasherize__.__type%40dasherize__.ts.template#L18) line. If the issue is accepted, I would like to create a pull request for this.

**Comment by JoostK** [comment] 2022-03-28 05:53
This is a duplicate of #22857. 

> I think the issue is in [this](https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/component/files/__name%40dasherize%40if-flat__/__name%40dasherize__.__type%40dasherize__.ts.template#L18) line. If the issue is accepted, I would like to create a pull request for this.

I don't think there is a PR already, so go for it!

**Closed by JoostK** 2022-03-28 05:53 UTC
