### ISSUE TITLE
IE9 - `TypeError: Object doesn't support property or method 'apply'`.

### ISSUE THREAD

**Issue by daehongKo** [angular/angular-cli#8625] opened 2017-11-24 13:45 UTC
### Versions
```
@angular/cli: 1.2.0
node: 8.1.2
os: darwin x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.2.0
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
```

### Repro steps

* Step 1. import `HttpClientModule` or `HttpModule` in AppModule
* Step 2. dependency `HttpClientModule` or `HttpModule` in AppComponent
* Step 3. 
```typecript
constructor(private http: HttpClient) { } // or Http

ngOnInit() {
  this.http.get('url').subscribe(data => { });
}
```
* Step 4. run `ng serve`

### The log given by the failure.
* In console of ie9 : 
`TypeError: Object doesn't support property or method 'apply'`
* Why do I get an error when I try to include a module?

#### My `polyfills.ts`
```
/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'core-js/client/shim';

...
```

#### My `tsconfig.json`
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "pretty": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```

**Comment by filipesilva** [comment] 2017-11-27 09:36
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #6110. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-11-27 09:36 UTC
