### ISSUE TITLE
Improper providers update with service generation

### ISSUE THREAD

**Issue by yfain** [angular/angular-cli#7898] opened 2017-10-01 16:27 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

When you use ```ng g s -m app.module```, the ```providers``` property is not properly updated in cases when providers property has an existing ```useValue``` provider. 

### Repro steps.

1. Add a provider to the app.module that looks something like this:

providers: [ {provide: MATERIAL_COMPATIBILITY_MODE, useValue: true}]

2. ng g s search -m app.module

3. Check the providers property in app.module - it's wrong:

```providers: [ {provide: MATERIAL_COMPATIBILITY_MODE, useValue: true, providers: [SearchService]}],```

### Desired functionality.

The updated property providers should look as follows:
```providers: [ {provide: MATERIAL_COMPATIBILITY_MODE, useValue: true},  [SearchService]}],```

**Comment by Brocco** [comment] 2017-10-02 18:37
Closing...
Duplicate of #7061

**Closed by Brocco** 2017-10-02 18:37 UTC
