### ISSUE TITLE
Feature: autoincrement port when default in use

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#18119] opened 2020-07-02 11:25 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

package.json

```
{
 "start": "ng serve"
}
```

```
$ yarn start
An unhandled exception occurred: Port 4200 is already in use. Use '--port' to specify a different port.
See "/private/var/folders/s7/5jlxk11s7bzg4nptht9xr4gw0000gn/T/ng-y1Z3za/angular-errors.log" for further details.

```

### Describe the solution you'd like

package.json

```
{
 "start": "ng serve --port-autoincrement"
}
```

```
$ yarn start
Port 4200 is already in use. 
** Angular Live Development Server is listening on localhost:4201, open your browser on http://localhost:4201/ **
```

**Comment by alan-agius4** [comment] 2020-07-02 12:09
Duplicate of #17464

**Closed by alan-agius4** 2020-07-02 12:09 UTC
