### ISSUE TITLE
Feature: Exclude files from 'watch' mode

### ISSUE THREAD

**Issue by kchojhu** [angular/angular-cli#2425] opened 2016-09-29 17:52 UTC
I think it would be great if you can exclude files to not watch so that it doesn't recompile every time.  As of now, I'm using styles.scss to override the default styles.css.  Yes, I do know that component can include the scss but I rather just have 1 style file for entire application (it's very small app).  Anyways, everytime I change scss files then it gets compiled twice.  Thanks and definitely loving NG2.

**Comment by gelliott181** [comment] 2016-09-30 15:54
Currently Webpack builds the entire project on any change, so excluding a file from being watched isn't going to do much yet. There are plans to allow partial building of projects for this sort of case, but based on responses from the Angular CLI team we should expect them after the new year begins.

**Comment by filipesilva** [comment] 2016-10-08 23:21
It definitely shouldn't be compiled twice, that sounds like a bug.

**Comment by awerlang** [comment] 2017-03-08 17:51
> it watches every dependency of the app plus the stuff we tell it to watch (styles, scripts, assets)

The entire root folder is watched. Repro:

1. Add a new folder inside app's root directory, let's call it `scss`;
2. Add a new file to this folder, let's call it `.gitkeep`;

`ng serve` would trigger a recompile.

I have my scss files inside this source folder, but these are compiled externaly. So every time I save, the app is refreshed but without the latest build from sass.

I believe this is a bug, given that the scope of watched files is wider than expected.

**Comment by samartioli** [comment] 2017-05-31 20:28
@spredemann Did you ever figure out a solution... I am using pug with Angular 4, and using a gulp task to compile pug to html.. problem is ng-build see's the pug changes and recompiles. Wasn't a big deal until I started using `include` pug files... 
I supposed I could `ng eject` and wire up webpack myself... I'd prefer not to.

**Comment by spredemann** [comment] 2017-05-31 20:31
@samartoli no but you probably should avoid includes anyway. Write smaller components.

**Comment by edoloughlin** [comment] 2017-07-07 10:58
Emacs creates a file called `.#<filename>` when you begin editing `<filename>`. This causes angular-cli to rebuild. I could set watchOptions.ignored to avoid this issue but this doesn't seem to be possible with angular-cli, forcing me to `ng eject`

**Comment by dmitrysteblyuk** [comment] 2017-07-10 13:54
```If you don't want any of those to be watched, you can just remove it from angular-cli.json```
@filipesilva the way I see it, everything's is watched. I'm saving my readme file and ng rebuilds. Even changing root in angular-cli.json doesn't help.

**Comment by towc** [comment] 2017-07-14 09:49
yeah, how do I get it not to watch vim files? It's very very annoying

**Comment by filipesilva** [comment] 2017-07-17 10:11
Reopening, I can confirm that everything in `src/` is indeed watched. I don't know if there's a way to configure webpack to not rebuild when random stuff is added to the folder. PR's and suggestions are welcome.

**Comment by dmitrysteblyuk** [comment] 2017-07-17 10:27
I believe everything in project directory is watched (where angular-cli.json is located) not only in src/. I have app root set to "src" in angular-cli.json, but still ng recompiles when any of my project files is saved.

**Comment by simpers** [comment] 2017-07-19 16:03
Is this being worked on? I am just like @edoloughlin using Emacs and right now I get this every time I edit a scss file: 

`webpack: Compiling...
 94% asset optimization(node:6150) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat '/home/simon/arbete/gor-cli/src/assets/scss/.#index.scss'
(node:6150) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by jaimealsilva** [comment] 2017-07-25 18:49
Same issue as https://github.com/angular/angular-cli/issues/4593

**Comment by redbmk** [comment] 2017-08-17 21:16
I'm looking into a fix for this. I'm thinking it would be an option passed in, similar to `poll` (maybe called `ignored`) that lets you set an anymatch string via the command line, or an anymatch string/array of strings via an option in `.angular-cli.json`.

If I `ng eject` and add `ignored: "**/*.swp"` to `devServer.watchOptions` it will ignore writes to any `*.swp` file. However, if I add `ignored: "**/*.swp"` to `watchOptions` [in the dev server config in angular-cli](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/tasks/serve.ts#L171) (after modifying the spec so it accepts the option) it still writes on those files.

Any ideas what could be going wrong here?

**Comment by redbmk** [comment] 2017-08-17 21:44
I take some of it back...it *is* working when I do the steps recommended in `npm link` and run this modified code in another project, but the test I have written is not passing. Something about this triggers a rebuild when it shouldn't. Can anybody see what's wrong with this test? When I run the linked version I'm invoking it the same way (`ng serve --ignored=**/*.swp`). I also have a `console.log` showing me the configuration and it shows the same in the test as it does when using it in practice.

```
import {
  killAllProcesses,
  waitForAnyProcessOutputToMatch,
  execAndWaitForOutputToMatch
} from '../../utils/process';
import {writeFile, appendToFile} from '../../utils/fs';
import {expectToFail} from '../../utils/utils';

const webpackGoodRegEx = /webpack: Compiled successfully./;

export default function() {         
  const ignoreCmd = `--ignored=**/*.swp`;
  
  return execAndWaitForOutputToMatch('ng', ['serve', ignoreCmd], webpackGoodRegEx)
    .then(() => appendToFile('src/main.ts', 'console.log(1);')) 
    .then(() => waitForAnyProcessOutputToMatch(webpackGoodRegEx, 10000))
    
    .then(() => writeFile('src/.main.ts.swp', 'console.log(1);')) //FIXME: this still triggers a rebuild
    .then(() => expectToFail(() => waitForAnyProcessOutputToMatch(webpackGoodRegEx, 10000)))
    
    .then(() => appendToFile('src/main.ts', 'console.log(1);'))
    .then(() => waitForAnyProcessOutputToMatch(webpackGoodRegEx, 10000))
    .then(() => killAllProcesses(), (err: any) => {
      killAllProcesses();
      throw err;
    });
}   
```

**Comment by filipesilva** [comment] 2017-08-21 12:11
Closed via https://github.com/angular/angular-cli/pull/7310, `src/` is no longer watched unconditionally.

**Closed by filipesilva** 2017-08-21 12:11 UTC
Labels: community: help wanted, priority: 2 (required), severity2: inconvenient, type: bug

**Comment by DelphiWorlds** [comment] 2018-07-29 23:38
This feature is closed, however there does not seem to be anything added to allow files/folders to be excluded? Is there something missing from the documentation?

**Comment by jbojcic1** [comment] 2019-03-05 15:26
For library generated with cli it seems to be watching entire library folder. @filipesilva I assume that currently it's not possible to add exception for library?

**Comment by Robert-Baindorov-Mindtree** [comment] 2019-07-10 13:51
I don't have this anular-cli.json file that has been mentioned. Using angular 7. 
Is it serve.json now? 
Can You link to an example of how to setup exclusion? 

robert@pop-os:~/bose_project/Raphael-App-Framework$ sudo find / -iname angular-cli.json
find: ‘/run/user/1000/gvfs’: Permission denied
robert@pop-os:~/bose_project/Raphael-App-Framework$ sudo find / -iname serve.json
find: ‘/run/user/1000/gvfs’: Permission denied
/home/robert/bose_project/Raphael-App-Framework/node_modules/@angular/cli/commands/serve.json
/home/robert/bose_project/angular-electron/node_modules/@angular/cli/commands/serve.json
/home/robert/.nvm/versions/node/v12.4.0/lib/node_modules/@angular/cli/commands/serve.json
/home/robert/Raphael-App-Framework/node_modules/@angular/cli/commands/serve.json
/home/robert/.cache/yarn/v4/npm-@angular-cli-7.3.3-b357000385aa6c75b001cb9fa7982ef3ce02c423/node_modules/@angular/cli/commands/serve.json
/var/backups/backintime/pop-os/robert/1/new_snapshot/backup/home/robert/.nvm/versions/node/v12.4.0/lib/node_modules/@angular/cli/commands/serve.json
