### ISSUE TITLE
Global version vs local version

### ISSUE THREAD

**Issue by kptLucek** [angular/angular-cli#7990] opened 2017-10-10 11:59 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [x] feature request
```

### Versions.

@angular/cli: 1.4.5
node: 8.4.0
os: linux x64

### Repro steps.

1. Create brand new deployment server with current stable (or latest, doesnt matter at all right now) version of `@angular/cli`
2. Start creating brand new application on *same* version of cli as deployment server uses to build application
3. Publish application few days later
4. Wait for `@angular/cli` new version
5. Create brand new application on new version (mostly because you want to keep patch-updates up to date)
6. Try to build your app on deployment server to get an error because of versions missmatch.

### Desired functionality.

I would love to keep an `@angular/cli` inside application itself, without need for global instalation, especially when you're serving many applications created in very different periods of time.

Situation is more or less as described, we've got single "building machine" which got stable configuration. We're also working with team of in-home developers and remote ones too, we're also working on very different versions of `@angular` itself.

In my opinion, the `@angular/cli` should be *global* or *local*, one on time, not both.

**Comment by hansl** [comment] 2017-10-11 00:18
The global one is only used when creating new applications, or when running `ng` without using the local install. The first thing the global installation does is verify if there is a local CLI, and if there is, transfer the process to it. So if you have a global CLI installed at version 1.0 (for example), but your local is 1.2, it will use the newer 1.2 from your project. If you want to upgrade to 1.4, simply upgrade your application's dependency. You don't need to reinstall the CLI globally. Hope this clarifies the behaviour.

Closing this as working as intended.

**Closed by hansl** 2017-10-11 00:18 UTC
