### ISSUE TITLE
Add generated files to git automatically

### ISSUE THREAD

**Issue by vultix** [angular/angular-cli#7144] opened 2017-07-26 05:39 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
When creating files using generate (i.e. `ng generate component|module`) it would be great if the cli would automatically add the new files to the git repository.  Currently it only creates the files.

**Comment by foxjazz** [comment] 2017-07-27 16:25
or type git add .

**Comment by filipesilva** [comment] 2017-07-31 10:53
Duplicate of https://github.com/angular/angular-cli/issues/358. There is an explanation there of why we don't do this.

**Closed by filipesilva** 2017-07-31 10:53 UTC
