### ISSUE TITLE
Question - why it is not buildable what yesterday was?

### ISSUE THREAD

**Issue by onatschirmaj** [angular/angular-cli#9430] opened 2018-01-29 20:46 UTC
### Versions
```_                      _                 ____ _     ___
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
/ △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
|___/

Angular CLI: 1.6.6
Node: 6.9.2
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.1
@angular/cli: 1.6.6
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

* npm install
* ng build // it works
* wait a few days
* rm -rf node_modules
* npm install
* ng build // it doesn`t work 

### My package.json file

```
{
  "name": "",
  "version": "",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {},
  "devDependencies": {
    "@angular-devkit/core": "0.0.28",
    "@angular-devkit/schematics": "0.0.51",
    "@angular/animations": "5.0.0",
    "@angular/cdk": "5.0.1",
    "@angular/cli": "1.6.6",
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/flex-layout": "2.0.0-beta.10-4905443",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/language-service": "5.0.0",
    "@angular/material": "5.0.1",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@angular/router": "5.0.0",
    "@types/jasmine": "2.5.53",
    "@types/jasminewd2": "2.0.2",
    "@types/node": "6.0.60",
    "codelyzer": "4.0.1",
    "core-js": "2.4.1",
    "jasmine-core": "2.6.2",
    "jasmine-spec-reporter": "4.1.0",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.2.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.2",
    "rxjs": "5.5.2",
    "ts-node": "3.2.0",
    "tslint": "5.7.0",
    "typescript": "2.4.2",
    "uglifyjs-webpack-plugin": "1.1.6",
    "zone.js": "0.8.14"
  }
}

```

### Observed behavior

```
 ng serve
Cannot find module 'uglifyjs-webpack-plugin'
Error: Cannot find module 'uglifyjs-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\sample\node_modules\@angular\cli\models\webpack-configs\production.js:13:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\sample\node_modules\@angular\cli\models\webpack-configs\index.js:9:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

### Desired behavior

Bug Is documented on the link I am adding below, but I would like to ask in general:
Sorry for the silly question, but I supposed that when I have dependencies versions whithour carrets and tildas in my package.json, npm install will always install the same versions and I can`t face the situation, that my project will became unbuildable on other plain system using the same configuration. Please, can somebody clarify me, why can angular-cli stop working after "reinstalling" packages? Or am I doing something wrong? I tried to google a lot about this, but I am not sure, how can I keep my project buildable for sure, what can I do for that? Thanks for the answers and again sorry, if it is my bad. 

### Mention any other details that might be useful (optional)

[https://github.com/angular/angular-cli/issues/9428](https://github.com/angular/angular-cli/issues/9428)

**Comment by admosity** [comment] 2018-01-29 20:47
Dupe #9427

**Comment by hansl** [comment] 2018-01-29 20:55
Duplicate of #9427

**Closed by hansl** 2018-01-29 20:55 UTC

**Comment by filipesilva** [comment] 2018-01-29 20:59
@onatschirmaj please have a look at https://github.com/angular/angular-cli/issues/9427#issuecomment-361383935, especially the part about lockfiles. Using lockfiles will ensure that you will have the same dependencies installed as long as the lockfile is the same.

**Comment by onatschirmaj** [comment] 2018-01-29 21:07
Thank you, guys!
