### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by yairtawil** [angular/angular-cli#3000] opened 2016-11-03 11:53 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
> angular-cli: 1.0.0-beta.19-3
node: 4.5.0
os: win32 x64

### Repro steps.
> 
Hi, 
how can I run scripts from angular-cli.json when I using 'ng test'?
Thanks 
Yair 

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ahaan729** [comment] 2016-11-03 13:05
@yairtawil  You can ask the same in the below chat room to get a quick response.
https://gitter.im/angular/angular

**Comment by filipesilva** [comment] 2016-11-04 17:02
Dupe of https://github.com/angular/angular-cli/issues/2897. It's broken at the moment.

**Closed by filipesilva** 2016-11-04 17:02 UTC

**Comment by YonatanKra** [comment] 2016-11-12 16:59
@yairtawil This solved my issue: https://github.com/angular/angular-cli/pull/3120
In order to solve this locally, you can add the relevant files in the `karma.conf.js`:
```
...
files: [
      { pattern: './src/test.ts', watched: false },
      { pattern: './node_modules/cesium/Build/Cesium/*.js'}
],
...
```
