### ISSUE TITLE
Not able to update angular cli and other packages. It is giving error of dependency

### ISSUE THREAD

**Issue by ErVishalM** [angular/angular-cli#15501] opened 2019-09-02 05:23 UTC
Not able to update angular cli and other packages. It is giving error of dependency. Please check. I'm aware of this issue has been already logged in this  [link](https://github.com/angular/angular-cli/issues/14980) but it is solved or not. If it is solved then how can we update the packages can you tell please.
These i need to update 

```
ng update        
Using package manager: 'npm'
Collecting installed dependencies...
Found 43 dependencies.
    We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cdk                       8.1.3 -> 8.1.4           ng update @angular/cdk
      @angular/cli                       8.3.0 -> 8.3.2           ng update @angular/cli
      @angular/material                  8.1.3 -> 8.1.4           ng update @angular/material
```

and when i am updating getting this error.

```
ng update --all 
Using package manager: 'npm'
Collecting installed dependencies...
Found 43 dependencies.
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires ">=3.1 < 3.6", would install "3.6.2")
                  Package "@angular/core" has an incompatible peer dependency to "zone.js" (requires "~0.9.1", would install "0.10.2").
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=3.4 <3.6", would install "3.6.2").
Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
```

and when i updating angular/cli alone then getting this error
```
ng update @angular/cli
Using package manager: 'npm'
Collecting installed dependencies...
Found 43 dependencies.
Fetching dependency metadata from registry...
                  Package "ag-grid-angular" has an incompatible peer dependency to "@angular/core" (requires ">=2.1.x" (extended), 
would install "9.0.0-next.4").
                  Package "ag-grid-angular" has an incompatible peer dependency to "@angular/compiler" (requires ">=2.1.x" (extended), would install "9.0.0-next.4").
Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
```

**Comment by ScottSpittle** [comment] 2019-09-02 06:08
I think you are meant to ng update @angular/cli @angular/core

https://update.angular.io/#7.0:8.0

**Comment by ErVishalM** [comment] 2019-09-02 06:55
@ScottSpittle  I am already in angular 8. Please check in my attached ss.

**Comment by alan-agius4** [comment] 2019-09-02 07:27
This is a duplicate of #14980 which is still open. 

If you're already on version 8.x, updating your package.json to the latest Angular version should be fine. We haven't shipped any changes that require automatic migration.

Thanks and apologies for the inconvience.

**Closed by alan-agius4** 2019-09-02 07:27 UTC

**Comment by ErVishalM** [comment] 2019-09-02 07:28
So what can i do can you tell me i need to manually update my cli version in `package.json` after that i need to run `npm install`?

**Comment by alan-agius4** [comment] 2019-09-02 07:34
Yes, you manually update the packages in your `package.json` and run `npm install`, or you can use `npm outdated`
