### ISSUE TITLE
[6.0.0-beta.4] CSS bundling problem on prod build

### ISSUE THREAD

**Issue by omahjoub** [angular/angular-cli#9902] opened 2018-03-08 15:18 UTC
### Versions
```
Angular CLI: 6.0.0-beta.4
Node: 9.5.0
OS: darwin x64
Angular: 6.0.0-beta.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 6.0.0-beta.4
@angular-devkit/build-optimizer: 0.4.3
@angular-devkit/core: 0.4.3
@angular-devkit/schematics: 0.4.3
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.4
@schematics/angular: 0.4.3
@schematics/package-update: 0.4.3
typescript: 2.6.2
webpack: 4.0.1
```

### Repro steps

* Step 1 

`ng serve`

![image](https://user-images.githubusercontent.com/1083387/37157817-0e7ce2e6-22ea-11e8-9a7e-eb9cb947e1d4.png)

* Step 2

`ng serve --prod`

![image](https://user-images.githubusercontent.com/1083387/37157852-2c9fcd24-22ea-11e8-832b-42e173b82727.png)

### Observed behavior

The rendering is not the same between `ng serve` and `ng serve --prod`

### Desired behavior

We should have the same rendering on normal builds and prod builds.

### Mention any other details that might be useful (optional)

I set up a repro project [here](https://github.com/omahjoub/angular-cli-repro.git).

All is good with angular-cli 6.0.0-beta.3

**Comment by omahjoub** [comment] 2018-03-09 09:35
Hi @clydin thank you for paying attention to this.
May be it would helps, the final bundle with `ng build --prod` presents the same problem.

**Comment by bakasmarius** [comment] 2018-07-28 14:34
I also have a similar issue:
on `ng serve` and `ng build` this css works fine: `border-right: 1px solid rgb(196, 197, 199, 0.3)`
but on `ng serve --prod` the same css looks like this: `border-right: 1px solid ` - so the rgb property is lost for some reason.

```
Angular CLI: 6.1.1
Node: 10.7.0
OS: win32 x64
Angular: 6.1.0
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.1
@angular-devkit/build-angular     0.7.1
@angular-devkit/build-optimizer   0.7.1
@angular-devkit/build-webpack     0.7.1
@angular-devkit/core              0.7.1
@angular-devkit/schematics        0.7.1
@angular/cdk                      6.4.1
@angular/cli                      6.1.1
@angular/flex-layout              6.0.0-beta.17
@angular/material                 6.4.1
@ngtools/webpack                  6.1.1
@schematics/angular               0.7.1
@schematics/update                0.7.1
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.9.2
```

**Comment by bakasmarius** [comment] 2018-07-28 14:37
Might it be related to #9255?

**Comment by alan-agius4** [comment] 2018-10-03 12:06
@bakasmarius, You issue might have been fixed by `clean-css` as I can no longer reproduce it.
@omahjoub.Your reproduction no longer work.


If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Closed by alan-agius4** 2018-10-03 12:06 UTC
Labels: comp: devkit/build-angular
