### ISSUE TITLE
Improve bundling experience for supporting multiple Angular Elements on a page

### ISSUE THREAD

**Issue by dsozzi** [angular/angular-cli#19164] opened 2020-03-11 22:33 UTC
Hi,

I’d like to bring some attention back to this original post

https://github.com/angular/angular/issues/23732

Where it’s stating that in previous Angular version it was not possible to run multiple Angular Elements on a single page and we had to wait for Ivy release. 

Now that we are at version 9 and Ivy is enabled by default, I was wondering if there are any progress regarding this issue. 

Thanks 

##
_**UPDATE** by @gkalpak (for visibility):_

List of related issues (with useful context, info, explanations):
- angular/angular#23732 (in particular https://github.com/angular/angular/issues/23732#issuecomment-388670907)
- angular/angular#30951 
- angular/angular#32726
- angular/angular#35429

**Comment by jelbourn** [comment] 2020-10-21 15:40
Moving this to the CLI repo since it relates to bundling. I believe this would fall under the feature request umbrella for CLI.

**Comment by alan-agius4** [comment] 2021-11-22 08:37
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2021-11-22 08:37 UTC
Labels: type: feature, comp: devkit/build-angular
