### ISSUE TITLE
Unable to run the Jasmine test scripts using Protractor tool using Visual Studio Code IDE

### ISSUE THREAD

**Issue by Vasundhara-vasu** [angular/angular-cli#7915] opened 2017-10-03 11:35 UTC
Hi All,

I am using 
1.Node -- v6.11.3
2.npm -- 3.10.10

When i am running below command ,
ng e2e

 the Visual Studio Code is displaying below error message

Executed 1 of 1 spec (1 FAILED) in 13 secs.
[17:00:20] I/launcher - 0 instance(s) of WebDriver still running
[17:00:20] I/launcher - chrome #01 failed 1 test(s)
[17:00:20] I/launcher - overall: 1 failed spec(s)
[17:00:20] E/launcher - Process exited with error code 1

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm
-cli.js" "run" "e2e" "--" "./protractor.conf.js"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! my-app@0.0.0 e2e: `protractor "./protractor.conf.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.0.0 e2e script 'protractor "./protractor.conf.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor "./protractor.conf.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\agudla\Desktop\Vasundhara\VSCodeWorkspace5\my-app\npm-debug.log

Some end-to-end tests failed, see above.
PS C:\Users\agudla\Desktop\Vasundhara\VSCodeWorkspace5\my-app>

Can any one please help me in solving this issue.

**Comment by Brocco** [comment] 2017-10-03 14:28
This issue is a support issue and not a bug or issue with the CLI itself. I suggest submitting your question where you can can some support/assistance such as [StackOverflow](https://stackoverflow.com).
Closing this issue.

**Closed by Brocco** 2017-10-03 14:28 UTC
