### ISSUE TITLE
jquery and bootstrap not work

### ISSUE THREAD

**Issue by wanghaolu** [angular/angular-cli#3202] opened 2016-11-19 03:38 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 10 x64

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.20-4
node: 7.0.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
1. >ng new ng2-sample
2. >cd ng2-sample
3. >npm install jquery --save
4. > npm install bootstrap --save
5. > change the angular-cli.json like this
`
"styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js"
      ]
`
6. > change src/app/app.component.html like this

![default](https://cloud.githubusercontent.com/assets/9586655/20452748/62b46d52-ae4c-11e6-96eb-a3243e5d5cbe.PNG)

### The log given by the failure.
> Normally this include a stack trace and some more information.

![1](https://cloud.githubusercontent.com/assets/9586655/20452710/c5fa2ee8-ae4b-11e6-8ace-344bfa6538c2.PNG)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by lordmat0** [comment] 2016-11-19 18:17
I followed your exact steps but could not reproduce. Am running on OSX

**Comment by jorgeas80** [comment] 2016-11-20 10:24
Same problem. Bootstrap not found. 

Ubuntu 16.04
Node 6.7.0
angular-cli: 1.0.0-beta.16

**Comment by wanghaolu** [comment] 2016-11-21 13:39
@lordmat0 yes, i'm sure jquery is included in script.bundle.js.
![default](https://cloud.githubusercontent.com/assets/9586655/20484604/e0c9cbaa-b032-11e6-8e71-18b6865bb9ed.PNG)

**Comment by noelmace** [comment] 2016-11-25 10:39
Same issue for me !

## OS?

windows 10 x64

## Versions.

angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64

## Repro steps.

1. ng new angular-todo
2. cd angular-todo
3. npm install jquery@latest --save
4. npm install bootstrap@next --save
5. angular-cli.json

```json
{
  "project": {
    "version": "1.0.0-beta.21",
    "name": "angular-todo"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/tether/dist/js/tether.min.js",
        "../node_modules/bootstrap/dist/js/bootstrap.min.js"
      ],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}
```

## The log given by the failure.

### in Chrome

```
Uncaught Error: Bootstrap's JavaScript requires jQuery(…)364 @ scripts.bundle.js:20__webpack_require__ @ inline.bundle.js:53679 @ scripts.bundle.js:48__webpack_require__ @ inline.bundle.js:53webpackJsonpCallback @ inline.bundle.js:24(anonymous function) @ scripts.bundle.js:1
main.bundle.js:415 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
```

In scripts.bundle.js, jQuery is included : 
```javascript
var __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */
```

## Workaround

The problem is that jQuery create the window.$ var, but not a window.jQuery var (which is expected by bootstrap). Same issue for Tether.

The following workaround seems to work : 

1. install @types/jquery and @types/tether (@types/jquery may need to install jquery@^2.0.34 instead of jquery@3.1.1, which seems to work fine with bootstrap 4)
2. in angular-cli.json, replace apps[0].scripts by : 
```
"scripts": [
        "vendor.ts",
        "../node_modules/bootstrap/dist/js/bootstrap.min.js"
      ],
```
3. create the vendor.ts file as follow :
```
import * as jquery from 'jquery';
window['jQuery'] = window['$'] = jquery;

import * as tether from 'tether';
window['Tether'] = tether;
```

### Remaining issues after the workaround

#### @types/jquery checking

The @types/jquery/index.d.ts give the following tslint errors, and I didn't found how to ignore this file via tslint.json :
```
[default] C:\Documents and Settings\nmace\dev\architecture\angular-todo\node_modules\@types\jquery\index.d.ts:3248:5
    Duplicate identifier 'export='.
[default] C:\Users\nmace\dev\architecture\angular-todo\node_modules\@types\jquery\index.d.ts:625:5
    Duplicate string index signature.
[default] C:\Users\nmace\dev\architecture\angular-todo\node_modules\@types\jquery\index.d.ts:2874:5
    Duplicate string index signature.
[default] C:\Users\nmace\dev\architecture\angular-todo\node_modules\@types\jquery\index.d.ts:2875:5
    Duplicate number index signature.
[default] C:\Users\nmace\dev\architecture\angular-todo\node_modules\@types\jquery\index.d.ts:3248:5
    Duplicate identifier 'export='.
[default] Checking finished with 5 errors
```

#### boostrap css import

The bootstrap's css isn't available in the app.component.js, even if it's included in styles.bundle.js and apparently correctly imported.

**Comment by noelmace** [comment] 2016-11-28 12:56
same issue with 1.0.0-beta.19-3

**Comment by xggaxlc** [comment] 2016-11-29 02:04
same issue with 1.0.0-beta.21

**Comment by noelmace** [comment] 2016-12-07 10:28
The problem seems to be resolved with beta.22-1 ! I replaced my previous workaround with the angular-cli.json scripts configuration shown in the README, and all seems to work fine now. I think we can close the issue.

**Comment by hansl** [comment] 2016-12-08 22:21
Closing thsi as fixed. Please note we have a Bootstrap 3 setup guide in work.

**Closed by hansl** 2016-12-08 22:21 UTC

**Comment by iTrout** [comment] 2016-12-14 06:13
Any timeline available or notification process for when Bootstrap 3 Setup guide completion.  That will be a big help...thanks!

**Comment by wcxaaa** [comment] 2017-01-10 05:11
Same issue on Beta 24 on node v7.4.0 on OS X 10.2.2.

My **angular-cli.json** has been configured as
```
"scripts": [

        "../node_modules/jquery/dist/jquery.slim.js",

        "../node_modules/tether/dist/js/tether.min.js",

        "../node_modules/bootstrap/dist/js/bootstrap.min.js"

      ],
...
```

But I get errors when the page loaded, and neither jquery nor tether work.
Only bootstrap is loaded, because it is bootstrap who report errors.

**Comment by xggaxlc** [comment] 2017-02-22 06:03
**cnpm install** xxx not work!  use **npm install** solved!

**Comment by twltony** [comment] 2017-04-14 00:41
@xggaxlc  Thank you! it works for my case, since we use **cnpm** You save my life!

**Comment by eminoda** [comment] 2017-09-07 01:00
@xggaxlc why cnpm cannot work

**Comment by dyl0807** [comment] 2017-12-13 03:01
Try to install @types/jquery(bootstrap) too.
**npm install @types/jquery --save-dev
npm install @types/bootstrap--save-dev**

To translate jquery and bootstrap in typescript type.

**Comment by dyl0807** [comment] 2017-12-13 03:03
`@`types/jquery --save-dev

**Comment by jasonlazo** [comment] 2018-02-17 16:51
You have to turn off the service completly and turn on it  again apparently the angular-cli.json is not update when you edit it

**Comment by jBC006-learner** [comment] 2018-03-28 17:52
Angular CLI: 1.6.5
Node: 8.9.4
OS: darwin x64
Angular: 
...
problem is:
it worked till last night ..
now all of sudden Terminal of my MaC throws 404 Error..bootstrap@3 not found
now unable to run my angular project generated
guide me if anyone able to resolve this..

thank you
