### ISSUE TITLE
Style minification converts RGB values within CSS variables into hex for values >99 (SCSS)

### ISSUE THREAD

**Issue by Matrix159** [angular/angular-cli#20926] opened 2021-05-24 21:31 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
N/A

### Description

When using `ng build` with `optimization:styles:minify` set to `true`, CSS variables within .scss files containing RGB values are converted to hex values when greater than 99.

## 🔬 Minimal Reproduction

These styles
```
:root {
  --contrast-color-0: white;
  --contrast-color-1: #F4F7FA;
  --contrast-color-1-rgb: 244, 247, 250;
  --contrast-color-2: #DFE6EE;
  --contrast-color-2-rgb: 223, 230, 238;
  --contrast-color-3: #B0BAC5;
  --contrast-color-3-rgb: 176, 186, 197;
  --contrast-color-4: #8091A5;
  --contrast-color-4-rgb: 128, 145, 165;
  --contrast-color-5: #667587;
  --contrast-color-5-rgb: 102, 117, 135;
  --contrast-color-6: #3F4A56;
  --contrast-color-6-rgb: 63, 74, 86;
}
```
are converted to this during minification
```
:root{--contrast-color-0:#fff;--contrast-color-1:#f4f7fa;--contrast-color-1-rgb:#244,#247,#250;--contrast-color-2:#dfe6ee;--contrast-color-2-rgb:#223,#230,#238;--contrast-color-3:#b0bac5;--contrast-color-3-rgb:#176,#186,#197;--contrast-color-4:#8091a5;--contrast-color-4-rgb:#128,#145,#165;--contrast-color-5:#667587;--contrast-color-5-rgb:#102,#117,#135;--contrast-color-6:#3f4a56;--contrast-color-6-rgb:63,74,86;}
```

Notice the added hexadecimal format on RGB values > 99. This causes colors to not be rendered.

## 🌍 Your Environment

<pre><code>

Angular CLI: 11.2.13
Node: 14.15.0
OS: darwin x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.13
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cli                    11.2.13
@schematics/angular             11.2.13
@schematics/update              0.1102.13
rxjs                            6.5.5
typescript                      4.0.7
</code></pre>

**Anything else relevant?**

Using scss schematics
```
"schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
```

**Comment by alan-agius4** [comment] 2021-05-25 07:21
Duplicate of https://github.com/angular/angular-cli/issues/20870 and #20869

**Closed by alan-agius4** 2021-05-25 07:21 UTC
