### ISSUE TITLE
ng update error message: Cannot find module 'tslint'.

### ISSUE THREAD

**Issue by wartab** [angular/angular-cli#14555] opened 2019-05-29 08:15 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
It seems like some part of angular-cli uses tslint to perform some migration step from Angular 7 to Angular 8.
When running `npm update @angular/cli @angular/core @angular/material`, the procedure crashes after static query migration is performed. 
After installing tslint, it does not crash anymore, but our environment does not make use of tslint and it doesn't seem to be a dependency of angular-cli either.

## 🔬 Minimal Reproduction
* Have an Angular 7 project without tslint
* Run `ng update @angular/cli @angular/core @angular/material`

## 🔥 Exception or Error
<pre><code>Cannot find module 'tslint'</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.3.9
Node: 10.14.2
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by devversion** [comment] 2019-05-29 10:21
Problem here is that the `@angular-devkit/schematics` package uses `tslint` to provide the `TslintFix` schematic task. Ideally it would specify `tslint` as a dependency as it is directly used.

https://github.com/angular/angular-cli/blob/3afdab21a0f0307dcd2be1b44a868ea3d7a8938c/packages/angular_devkit/schematics/tasks/tslint-fix/executor.ts#L13-L15

Migrations such as these from `@angular/material` can depend on these to apply fixes.

**Comment by alan-agius4** [comment] 2019-05-29 10:28
The problem is https://github.com/angular/angular-cli/blob/3afdab21a0f0307dcd2be1b44a868ea3d7a8938c/packages/angular_devkit/schematics/tasks/tslint-fix/executor.ts#L96 😛 

As the above mentioned part only imports for types

**Comment by devversion** [comment] 2019-05-29 10:37
ups right :smile: In any way, the `TslintFix` task has a dependency on `tslint`.

**Comment by alan-agius4** [comment] 2019-05-31 12:41
Hi, we discussed this in yesterdays team meeting, and the outcome is that we should print a warning when tslint is not found.

It was also brought up that using tslint for migrations is not the should be discouraged because tslint runs on files which are on disk and not using the schematic host, meaning that it might run on files which have changes not yet committed to disk or if the part of the schematic fails users will need to rollback the changes manually.

**Comment by dgp1130** [comment] 2020-05-27 20:55
It seems like this was fixed in #16433. Please re-open if you are still seeing this issue on any migrations.

**Comment by devversion** [comment] 2020-05-27 21:24
@dgp1130 Thanks for looking. This is still an issue as `tslint` is transitively used by `TslintFixTask`, but `tslint` is not a dependency of `@angular-devkit/schematics`.

https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/schematics/tasks/tslint-fix/executor.ts#L86.

As @alan-agius4 pointed out, it might be best to just provide a good error in those cases? It seems not like a good idea to add `tslint` as actual dependency of `@angular-devkit/schematics`. The PR you linked to is actually a workaround we provided on the Angular Components side. The root cause is not fixed (or improved by better messaging).

I could re-open the issue, but I'm leaving that to you. I could imagine this being reworked in the future. Ideally the tslint task would be specific to the Angular CLI and not to the schematics devkit unless I miss something here.

**Comment by dgp1130** [comment] 2020-05-27 21:33
Thanks for the clarification @devversion. Seems like this can still happen then, so I'm reopening the issue. We'll need to address that usage or add better warnings for this case.

**Comment by alan-agius4** [comment] 2020-10-15 08:05
Closing this that tslint executor is deprecated and will be removed in the future.

**Closed by alan-agius4** 2020-10-15 08:05 UTC
Labels: comp: schematics/update, freq1: low, severity3: broken, triage #1, type: bug/fix
