### ISSUE TITLE
How to override files with merge or branchMerge?

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12088] opened 2018-09-04 22:52 UTC
_From @CarstenLeue on June 5, 2018 13:8_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
0.6.5

### Repro steps

In a custom schematic I use this code to copy files from the schematic library to the target project:

```typescript
  const templateSource = apply(url('./app/files'), [
    template({
      ...strings,
      dataDir: 'data/'
    }),
    move(project.root)
  ]);

  return chain([branchAndMerge(chain([mergeWith(templateSource)]))]);
```

This fails if any of the files already exist in the target location. Adding "MergeStrategy.Override" to either mergeWidth or branchAndMerge does not solve this.

### Desired functionality

I would like to be able to specify what happens if copied files already exists in the target location, without producing an error. Either choose to override these files or to ignore the overrides.

How can I do that?

_Copied from original issue: angular/devkit#1010_

**Comment by Bored-Bohr** [comment] 2018-10-10 17:04
This issue still exists in 0.8.4.

The issue occurs on HostTree merge. The template generates actions with kind 'c' and since there exists no prior actions this._willCreate(path) || this._willOverwrite(path) returns false. this._record.create triggers. This in turn throws the fileDoesNotExistException on execute.

**Comment by alan-agius4** [comment] 2018-10-11 13:19
Duplicate of #11337

**Closed by alan-agius4** 2018-10-11 13:19 UTC
