### ISSUE TITLE
'ng serve' and 'ng build' exit in the middle of compilation with no error

### ISSUE THREAD

**Issue by lehtiniemi** [angular/angular-cli#9950] opened 2018-03-12 17:42 UTC
### Versions
Angular CLI: 1.7.3
Node: 9.4.0
OS: win32 x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/flex-layout: 5.0.0-beta.13
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.4.5
@ngtools/json-schema: 1.2.0
typescript: 2.6.2
webpack: 3.11.0
  Windows (10)

### Repro steps
-run 'ng serve' or 'ng build'

### Observed behavior
-after the command, ang cli starts to compile, but the compilation line stops at something like this:
51% building modules 344/373 modules 29 active ...dules\core-js\modules\_object-keys.js

It returns to command prompt, leaving that line visible. It's usually somewhere around 50+%, but the file is different every time.

I sometimes get it to work by installing the very latest typescript (the one not yet supported by angular) and reinstalling node_modules, but this isn't foolproof.

### Desired behavior
If there's a problem with compilation in serve or build, there should be an error about what it is.

### Mention any other details that might be useful (optional)
This project has worked for months, but suddenly this started.

For example, I just deleted node_modules, ran npm install and then ng serve. It started correctly without errors. I then hit CTRL-C and ran ng serve again. This time it won't run anymore. Some memory issue? Also build succeeds sometimes, but then the second time it doesn't.

In the recent days, I have upgraded to ang-cli 1.7.x (both .0 and current version result the same error). I also upgraded to latest angular recently, but it works sometimes. Installing different versions of typescript makes some change sometimes. Sometimes the build works, then the next time not.

Is there a way to get a more detailed log? Any ideas on how to find out more on this?

Could be related to this - I get the same behaviour from time to time: https://github.com/angular/angular-cli/issues/8422

**Comment by slubowsky** [comment] 2018-03-12 23:03
Seeing same behavior but for me it was only with aot and/or prod and was failing at 14%. Went back down to cli 1.7.2 and it worked, went back up to 1.7.3 and its working so far...

ng serve silently failed but ng build gave me following in log. Perhaps its useful?

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-prod' ]
2 info using npm@5.6.0
3 info using node@v9.7.1
4 verbose run-script [ 'prebuild-prod', 'build-prod', 'postbuild-prod' ]
5 info lifecycle abc@0.0.42~prebuild-prod: abc@0.0.42
6 info lifecycle abc@0.0.42~build-prod: abc@0.0.42
7 verbose lifecycle abc@0.0.42~build-prod: unsafe-perm in lifecycle true
8 verbose lifecycle abc@0.0.42~build-prod: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\dev\abc-app\node_modules\.bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Program Files\TortoiseHg\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\slubo\AppData\Local\Microsoft\WindowsApps;C:\Users\slubo\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;C:\Users\slubo\.dotnet\tools
9 verbose lifecycle abc@0.0.42~build-prod: CWD: D:\dev\abc-app
10 silly lifecycle abc@0.0.42~build-prod: Args: [ '/d /s /c',
10 silly lifecycle   'npm version patch && node ./replace.build.js && ng build --prod' ]
11 silly lifecycle abc@0.0.42~build-prod: Returned: code: 3221226356  signal: null
12 info lifecycle abc@0.0.42~build-prod: Failed to exec build-prod script
13 verbose stack Error: abc@0.0.42 build-prod: `npm version patch && node ./replace.build.js && ng build --prod`
13 verbose stack Exit status 3221226356
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:127:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:127:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid abc@0.0.42
15 verbose cwd D:\dev\abc-app
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-prod"
18 verbose node v9.7.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 3221226356
22 error abc@0.0.42 build-prod: `npm version patch && node ./replace.build.js && ng build --prod`
22 error Exit status 3221226356
23 error Failed at the abc@0.0.42 build-prod script.
```

**Comment by lehtiniemi** [comment] 2018-03-13 08:39
I've been testing around and just now I just hit 'ng serve' repeadetly - first 5 times it exited at around 50% with no error and on 6th attempt it succeeded.

**Comment by krilllind** [comment] 2018-03-21 13:27
Experiencing the same issue, but in both CLI version 1.7.2 and 1.7.3 (downgraded from 1.7.3).
I feel like this should get a higher prio when noone is able to run any applications properly.

Love to see a fix for this in 1.7.4 **soon** and maybe a merge to 6.0.0 (if same error occures).

**Comment by haricodeharan** [comment] 2018-10-02 05:55
Experiencing same error.WOrks on local Mac but fails on server Ubuntu 18.04.

Your global Angular CLI version (7.0.0-rc.1) is greater than your local
version (6.2.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
 92% after chunk asset optimization SourceMapDevToolPlugin vendor.js generate SourceMapKilled

**Comment by haricodeharan** [comment] 2018-10-02 06:34
Probably the issue is with the ram or cpu.
The issue is resolved if the ram and cpu are increased, don't have set up to check whether its ram or cpu. 
Showing an appropriate error msg would be better.

**Comment by filipesilva** [comment] 2019-01-29 12:00
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by filipesilva** 2019-01-29 12:00 UTC
Labels: comp: devkit/build-angular
