### ISSUE TITLE
@angular-devkit/build-angular@0.803.20 - production build not working in IE

### ISSUE THREAD

**Issue by psimonova** [angular/angular-cli#16366] opened 2019-12-05 18:17 UTC
# 🐞 Bug report 

- [ x ] build

### Is this a regression?

Yes, the previous version in which this bug was not present was: @angular-devkit/build-angular@0.803.19

### Description

Service with injected NgZone service
ng build -c production build now not working IE

## 🔬 Minimal Reproduction

tsconfig.json:
 compilerOptions.target = es2015
 compilerOptions.module = esNext

angular.json:
architect.build.configurations.production.aot = true

## 🔥 Exception or Error
<pre><code>

ERROR TypeError: Unable to get property 'runOutsideAngular' of undefined or null reference

</code></pre>

## 🌍 Your Environment
<pre><code>
@angular-devkit/{all}@0.803.20
@angular/{all}@8.03.20
typescript@3.5.3
</code></pre>

**Anything else relevant?**
IE 11

**Comment by clydin** [comment] 2019-12-06 18:29
Can you provide the full output of executing `ng version`?

**Comment by psimonova** [comment] 2019-12-06 18:37
Sure:

@angular-devkit/architect 0.803.20
@angular-devkit/build-angular 0.803.20
@angular-devkit/build-ng-packagr 0.803.20
@angular-devkit/build-optimiser 0.803.20
@angular-devkit/build-webpack 0.803.20
@angular-devkit/core 8.3.20
@angular-devkit/schematics 8.3.20
@angular/cdk 8.2.3
@angular/cli 8.3.20
@angular/material 8.2.3
@angular/pwa 0.803.20
@ngtools/webpack 8.3.20
@schematics/angular 8.3.20
@schematics/update 0.803.20
ng-packagr 5.7.1
rxjs 6.5.3
typescript 3.5.3
webpack 4.39.2

**Comment by kumaresan-subramani** [comment] 2019-12-09 13:55
By default in version 8, angular Team enable `differential loading` for `ng build`. However for ng test and ng serve we only generate a single `ES2015` build which cannot run in `IE 11`


There are a couple of options that you can do if you want to have `ES5` code during serve.

### 1. Disable differential loading completely, (Not recommended)
You can turn differential loading off by changing the target from **es2015** to **es5** in your `tsconfig.json`

### 2. Have multiple configuration for serve.

Create a new tsconfig tsconfig.es5.json next to tsconfig.app.json with the below contents

```
{
 "extends": "./tsconfig.app.json",
 "compilerOptions": {
     "target": "es5" 
  }
}
```

### FYI-

https://github.com/angular/angular-cli/issues/14455#issuecomment-493739768

**Comment by psimonova** [comment] 2019-12-09 14:23
@kumaresan-subramani

**Comment by Trent-Matthias** [comment] 2019-12-09 21:15
IE broke for me as well in my current project, only change was updating the cli from .19 to .20 in the production environment.

**Comment by clydin** [comment] 2019-12-10 15:54
As this appears to be highly correlated to the specifics of a project, a reproduction would be incredibly helpful to troubleshoot the issue.  For anyone with the time and resources, can you provide a reproduction that demonstrates the problem?  I attempted to create one from the information contained in the original issue but was unable to trigger the problem.

Also, if possible can you try your projects with the release candidate for 9.0 (currently 9.0.0-rc.5)?

**Comment by Trent-Matthias** [comment] 2019-12-10 19:53
So this is only a problem with my large project, I have 2 other ones that do not have this issue. All three have a similar bootstrapping process, I use an external config and fetch it using the APP_INITIALIZER token. My large project has many more services to handle things like logging in, but I'm not doing anything with zones explicitly, the config stuff is the most unique things my apps are doing. 

I spent a good chunk of yesterday playing around and trying to get my large project to work with IE. I tried using 9.0.0-rc5 but was unable to get IE to work there as well using es5 as my target in the tsconfig using ng serve. I got the other browsers working though on 9.0.0-rc5, but I'm pretty stumped now and not sure what is causing this bug in my one project.

**Comment by Wisdomb33r** [comment] 2019-12-11 09:44
I tried to reproduce this IE problem but had no success to find a small reproduction project.
I now have a very small project, which is using NgZone injection in service (for an error service being injected in an ErrorHandler). And this small project seems to run absolutely fine under IE with a 8.3.20 compilation.

I agree this issue is project-specific. The sad thing is I have really no clue what in my thousands of lines of code is trigerring the error I have (which is not the same error message than psimonova, see #16405).

Up to now I could only reproduce the crash with a prod deployment using differential loading, never with `ng serve`, and not with a smaller project. So the error is located somewhere in a several-million-long line of minified JS...

@clydin Can CLI 9 compile an Angular 8 project (with anything like a -force optional parameter) ?
Now I have a `This version of CLI is only compatible with Angular versions 0.0.0 || ^9.0.0-beta || >=9.0.0 <10.0.0, but Angular version 8.2.14 was found instead.` error message. And I have no plans to upgrade my entire project before a stable release of Angular 9 (even waiting for the first minor version to avoid early-adopters usual small bugs).

**Comment by matt-senseye** [comment] 2019-12-11 13:06
I'm not sure exactly how to reproduce this in a minimal environment yet and can't share my codebase, but if it helps add any context, we saw a similar problem but with a different error - it is as if some kind of polyfill is missing. For us it only affected production builds in IE, manifesting itself with errors along the lines of:

`Object doesn't support property or method '{....}'`

and, perhaps as a consequence of that,
`Unable to get property 'map' of undefined or null reference`

Reverting build-angular and angular-cli from 0.803.20 one patch version fixes it in our case:
```
"@angular-devkit/build-angular": "0.803.19",
"@angular/cli": "8.3.19"
```

**Comment by RichardMisiak** [comment] 2019-12-11 14:35
My team is having the same issue in both of our applications
I'll try to find a minimal reproduction as a I can't share the real applications

**Comment by RichardMisiak** [comment] 2019-12-11 15:46
I did some more digging by looking through the changes in the last release, thankfully there weren't that many
Undoing this change appears to fix the issue for me
https://github.com/angular/angular-cli/commit/574e76e2dac200146fb4eec41141d3068270d4b2

I don't know what it does or why that fixes it but it's something to do with enabling downlevel iteration

**Comment by NoelLH** [comment] 2019-12-11 15:56
Thanks for finding a likely culprit @RichardMisiak!

I was just about to post our public repo in case it's helpful as an example (though the above is most likely more useful now) - https://github.com/thebiggive/donate-frontend

We also have a dependency on `@angular/flex-layout@8.0.0-beta.27` so based on the previous comment I'm also wondering if flex could be a factor.

I think we had a couple of different crashes depending on which page the SSR'd app was first loaded with. The `/donate/:id` route hit the original issue description one with 'runOutsideAngular' if I remember correctly. [This](https://donate-staging.thebiggivetest.org.uk/donate/a051r00001WoCJPAA3) is a current example of that route on our staging site (now working in IE11 with the libraries reverted to 0.803.19 as others have done).

**Comment by Wisdomb33r** [comment] 2019-12-12 06:16
@RichardMisiak, @NoelLH : No flex-layout lib on my side but crashing on IE. Seems every project has a different error message.

@RichardMisiak Thanks for the digging and finding this commit. It seems related to differential loading, which perfectly explains why the error is only showing after a real production build and never with `ng serve`.

**Comment by pradab-augment** [comment] 2019-12-12 12:15
Even me also faced  same issue when i upgrade to angular 8.3.20 version .
I have fixed by editing ts config file target : "es5"

"compilerOptions": {
    "target": "es5",
   }

**Comment by linjie997** [comment] 2019-12-13 09:55
I can confirm the regression.
While in development, with `ng serve` the issue doesn't happen while running a build, IE throw the error: 
`Object doesn't support property or method 'some' `

I did a downgrade to 8.3.19 and everything is working fine.

**Comment by tbunique** [comment] 2019-12-13 15:58
Thank you for recommending a downgrade, I had NO idea what to do to fix this as I couldn't reproduce in local.

Everything works fine in prod now with version 8.3.19

**Comment by Trent-Matthias** [comment] 2019-12-16 20:23
OK now my other project has the same bug, so 2 out of the 3 have it. The thing these 2 share in common is that they are relatively old and where generated with an older version of the CLI, then upgraded to 8.

**Comment by Trent-Matthias** [comment] 2019-12-17 03:03
I've been tinkering around with this and got one of the 2 broken projects working. The issue with it was a third party community package. This particular one was ngx-quicklink, removing it and upgrading to angular 9 fixes IE. However, if I just remove it and don't upgrade to 9 and stay at 8 I still get the error in IE.

**Comment by alan-agius4** [comment] 2019-12-31 08:16
Closes via https://github.com/angular/angular-cli/pull/16458

**Closed by alan-agius4** 2019-12-31 08:16 UTC
Labels: comp: devkit/build-angular, freq1: low, need: more info, severity5: regression, type: bug/fix

**Comment by zero-1** [comment] 2020-01-13 07:57
I am still able to repro this issue using these ....

@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cli                      8.3.22
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2


Downgrading to ...
@angular-devkit/build-angular": "0.803.19
@angular/cli: 8.3.19
.... is fixing the problem.

Is anyone else facing the same ?

**Comment by johnjosephtigris** [comment] 2020-02-09 03:04
Unable to run npm run build

> node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod

This version of CLI is only compatible with Angular versions 0.0.0 || ^9.0.0-beta || >=9.0.0 <10.0.0,
but Angular version 8.0.0 was found instead.

Please visit the link below to find instructions on how to update Angular.
https://update.angular.io/

npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! fuse@8.0.0 build: `node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the fuse@8.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sreekanthvr/.npm/_logs/2020-02-09T02_58_55_672Z-debug.log

debug log mentioned below.
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.13.4
3 info using node@v12.15.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle fuse@8.0.0~prebuild: fuse@8.0.0
6 info lifecycle fuse@8.0.0~build: fuse@8.0.0
7 verbose lifecycle fuse@8.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle fuse@8.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/sreekanthvr/Downloads/MemberManagement/membershipWeb/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/sreekanthvr/Documents/Development/tools/flutter/bin:/Users/sreekanthvr/Documents/Development/tools/flutter/bin
9 verbose lifecycle fuse@8.0.0~build: CWD: /Users/sreekanthvr/Downloads/MemberManagement/membershipWeb
10 silly lifecycle fuse@8.0.0~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod'
10 silly lifecycle ]
11 silly lifecycle fuse@8.0.0~build: Returned: code: 3  signal: null
12 info lifecycle fuse@8.0.0~build: Failed to exec build script
13 verbose stack Error: fuse@8.0.0 build: `node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod`
13 verbose stack Exit status 3
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid fuse@8.0.0
15 verbose cwd /Users/sreekanthvr/Downloads/MemberManagement/membershipWeb
16 verbose Darwin 19.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v12.15.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 3
22 error fuse@8.0.0 build: `node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod`
22 error Exit status 3
23 error Failed at the fuse@8.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3, true ]
