### ISSUE TITLE
ERROR Initiated Worker with invalid execArgv flags: --use-openssl-ca plugin angular-compiler

### ISSUE THREAD

**Issue by viceice** [angular/angular-cli#29075] opened 2024-12-06 14:36 UTC
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18.2.13

### Description

The `@angular/build` is passing all node args to the `Worker` via `piscina` which is invalid. Angular should filter some args like `--use-openssl-ca`

https://github.com/angular/angular-cli/blob/120f088778fa0023291781afb5199933d4ac69f7/packages/angular/build/src/tools/esbuild/javascript-transformer.ts#L63

### Minimal Reproduction

create a simple shell wrapper for node and add to path, then run nx build for an esbuild enabled project.

```sh
#!/bin/sh

node --use-openssl-ca "$@"
```

### Exception or Error

```text
15:01:04  ✘ [ERROR] Initiated Worker with invalid execArgv flags: --use-openssl-ca [plugin angular-compiler]
15:01:04  
15:01:04      node_modules/.pnpm/piscina@4.7.0/node_modules/piscina/dist/index.js:130:23:
15:01:04        130 │         const worker = new node_worker_threads_1.Worker((0, node_...
15:01:04            ╵                        ^
15:01:04  
15:01:04      at new Worker (node:internal/worker:222:13)
15:01:04      at ThreadPool._addNewWorker (/var/jenkins/workspace/gitea_xfab_sx_main/node_modules/.pnpm/piscina@4.7.0/node_modules/piscina/dist/index.js:130:24)
15:01:04      at ThreadPool._ensureMinimumWorkers (/var/jenkins/workspace/gitea_xfab_sx_main/node_modules/.pnpm/piscina@4.7.0/node_modules/piscina/dist/index.js:125:18)
15:01:04      at new ThreadPool (/var/jenkins/workspace/gitea_xfab_sx_main/node_modules/.pnpm/piscina@4.7.0/node_modules/piscina/dist/index.js:116:14)
15:01:04      at new Piscina (/var/jenkins/workspace/gitea_xfab_sx_main/node_modules/.pnpm/piscina@4.7.0/node_modules/piscina/dist/index.js:566:53)
15:01:04      at new WorkerPool (/var/jenkins/workspace/gitea_xfab_sx_main/node_modules/.pnpm/@angular+build@19.0.2_@angular+compiler-cli@19.0.1_@angular+compiler@19.0.1_@angular+core@19._v7u63jdkqmnm72dubgsrnjhawe/node_modules/@angular/build/src/utils/worker-pool.js:40:9)
15:01:04      at #ensureWorkerPool (/var/jenkins/workspace/gitea_xfab_sx_main/node_modules/.pnpm/@angular+build@19.0.2_@angular+compiler-cli@19.0.1_@angular+compiler@19.0.1_@angular+core@19._v7u63jdkqmnm72dubgsrnjhawe/node_modules/@angular/build/src/tools/esbuild/javascript-transformer.js:42:30)
15:01:04      at JavaScriptTransformer.transformFile (/var/jenkins/workspace/gitea_xfab_sx_main/node_modules/.pnpm/@angular+build@19.0.2_@angular+compiler-cli@19.0.1_@angular+compiler@19.0.1_@angular+core@19._v7u63jdkqmnm72dubgsrnjhawe/node_modules/@angular/build/src/tools/esbuild/javascript-transformer.js:80:51)
15:01:04      at async /var/jenkins/workspace/gitea_xfab_sx_main/node_modules/.pnpm/@angular+build@19.0.2_@angular+compiler-cli@19.0.1_@angular+compiler@19.0.1_@angular+core@19._v7u63jdkqmnm72dubgsrnjhawe/node_modules/@angular/build/src/tools/esbuild/angular/compiler-plugin.js:381:38
15:01:04      at async requestCallbacks.on-load (/var/jenkins/workspace/gitea_xfab_sx_main/node_modules/.pnpm/esbuild@0.24.0/node_modules/esbuild/lib/main.js:1276:22)
15:01:04  
15:01:04    This error came from the "onLoad" callback registered here:
15:01:04  
15:01:04      node_modules/.pnpm/@angular+build@19.0.2_@angular+compiler-cli@19.0.1_@angular+compiler@19.0.1_@angular+core@19._v7u63jdkqmnm72dubgsrnjhawe/node_modules/@angular/build/src/tools/esbuild/angular/compiler-plugin.js:371:18:
```

### Your Environment

```text
Angular CLI: 19.0.2
Node: 22.11.0
Package Manager: pnpm 9.14.4
OS: win32 x64

Angular: 19.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@schematics/angular             19.0.2
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.15.0
```

### Anything else relevant?

I'm using nx but it shouldn't matter as the mentioned code uses `process.execArgv` directly

**Comment by alan-agius4** [comment] 2024-12-06 14:43
Duplicate of https://github.com/angular/angular-cli/issues/28901

**Closed by alan-agius4** 2024-12-06 14:43 UTC
