### ISSUE TITLE
Missing peer deps in CLI beta 31

### ISSUE THREAD

**Issue by AloeDream** [angular/angular-cli#4616] opened 2017-02-11 13:10 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10 x64 latest updates

### Versions.
> C:\Windows\system32>node --version
v7.5.0

### Repro steps.
> 1) Remove all global npm packages, run npm cache clean
2) Install global CLI package
3) See warns after
4) run npm ls -g
5) see errors provided in a log

### The log given by the failure.
> npm ERR! peer dep missing: @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0, required by @ngtools/webpack@1.2.9
npm ERR! peer dep missing: @angular/compiler-cli@^2.3.1 || >=4.0.0-beta <5.0.0, required by @ngtools/webpack@1.2.9
npm ERR! peer dep missing: @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0, required by @ngtools/webpack@1.2.9
npm ERR! peer dep missing: @angular/tsc-wrapped@^0.5.0, required by @ngtools/webpack@1.2.9

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Node-gyp and windows-build-tools also globally installed (not outdated)

**Comment by osnoser1** [comment] 2017-02-11 15:24
#4575

**Comment by hansl** [comment] 2017-02-12 21:50
Dupe of #4575.

**Closed by hansl** 2017-02-12 21:50 UTC
