### ISSUE TITLE
coverage-istanbul-loader cannot find javascript source maps

### ISSUE THREAD

**Issue by Pouja** [angular/angular-cli#16854] opened 2020-02-06 15:56 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ x ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

When enabling the `codeCoverage` for `ng test` the test will not run and crash because it cannot find the source maps of our javascript files. We are in the process of converting our angularjs to angular.

I think the problem will be fixed if we convert all our js files to ts. But that introduces more errors than files. We have over 2000 javascript files.

## 🔥 Exception or Error
<pre><code>

ERROR in ./src/main/javascript/structure/cases/hv-plan/hv-plan.module.js
Module build failed (from ./node_modules/coverage-istanbul-loader/lib/index.js):
Error: An error occurred while trying to read the map file at C:\Users\p289718\Projects\flow\flow-ui\src\main\javascript\structure\cases\hv-plan\hv-plan.module.js.map
Error: ENOENT: no such file or directory, open 'C:\Users\p289718\Projects\flow\flow-ui\src\main\javascript\structure\cases\hv-plan\hv-plan.module.js.map'
    at readFromFileMap (C:\Users\p289718\Projects\flow\flow-ui\node_modules\coverage-istanbul-loader\node_modules\convert-source-map\index.js:40:11)
    at new Converter (C:\Users\p289718\Projects\flow\flow-ui\node_modules\coverage-istanbul-loader\node_modules\convert-source-map\index.js:47:32)
    at Object.exports.fromMapFileComment (C:\Users\p289718\Projects\flow\flow-ui\node_modules\coverage-istanbul-loader\node_modules\convert-source-map\index.js:110:10)
    at Object.exports.fromMapFileSource (C:\Users\p289718\Projects\flow\flow-ui\node_modules\coverage-istanbul-loader\node_modules\convert-source-map\index.js:122:22)
    at Object.default_1 (C:\Users\p289718\Projects\flow\flow-ui\node_modules\coverage-istanbul-loader\lib\index.js:28:45)
 @ ./src/main/javascript/structure/structure.module.ts 228:0-58 230:101-113
 @ ./src/main/javascript/app/app.angularjs.module.ts
 @ ./src/main/javascript/flow-tests.ts
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.14
Node: 12.10.0
OS: win32 x64

Angular: 9.0.0-rc.14
... cli, common, compiler, compiler-cli, core, language-service
... platform-browser, platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.24
@angular-devkit/build-angular     0.803.24
@angular-devkit/build-optimizer   0.803.24
@angular-devkit/build-webpack     0.803.24
@angular-devkit/core              8.3.24
@angular-devkit/schematics        9.0.0-rc.14
@ngtools/webpack                  8.3.24
@schematics/angular               9.0.0-rc.14
@schematics/update                0.900.0-rc.14
rxjs                              6.5.4
typescript                        3.7.3
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

Relevant `angular.json` part
```json
"test": {
          "builder": "ngx-build-plus:karma",
          "options": {
            "main": "src/main/javascript/flow-tests.ts",
            "polyfills": "src/main/javascript/polyfills.ts",
            "reporters": ["progress"],
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "codeCoverage": true,
            "assets": [],
            "styles": [],
            "scripts": [],
            "extraWebpackConfig": "webpack.partial.js"
          }
        },
```

karma.conf
```js
const path = require('path');

module.exports = function(config) {
    config.set({
        basePath : '',
        frameworks : ['jasmine', '@angular-devkit/build-angular'],
        files : [
            'src/main/javascript/flow-tests.ts'
        ],
        exclude : [],
        plugins : [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-coverage-istanbul-reporter'),
            require('@angular-devkit/build-angular/plugins/karma')
        ],
        coverageIstanbulReporter : {
            reports : [ 'html', 'text-summary' ],
            dir : path.join(__dirname, 'target'),
            fixWebpackSourcePaths : true,
            'report-config' : {
                html : { subdir : 'coverage' }
            },
            thresholds : {
                global : {
                    statements : 77.1,
                    branches : 62.7,
                    functions : 76.1,
                    lines : 77.0
                }
            }
        },
        junitReporter : {
            outputDir : 'target/surefire-reports-ui/'
        },
        port : 9876,
        colors : true,
        logLevel : config.LOG_INFO,
        autoWatch : false,
        browsers : ['ChromeHeadless'],
        singleRun : true,
        concurrency : Infinity
    });
};

```

**Comment by alan-agius4** [comment] 2020-02-06 18:35
Can you try to replicate this without custom builders? Also, can you kindly share a reproduction that we can take a look at? 

This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

Thanks.

**Comment by studix** [comment] 2020-02-07 15:04
I'm getting the same error running ng test with code-coverage using build-angular 0.803.x. Same code with build-angular version 0.802.2 works fine.

configuration: 
angular CLI: 8.3.25 
@angular-devkit/build-angular  0.803.25

Cheers,
studix

**Comment by swapnilfarande** [comment] 2020-02-08 15:46
I am also facing the same issue while running `ng test` with code coverage with 
```
@angular/cli:  8.3.25
@angular-devkit/build-angular:  0.803.25
```

But if I downgrade @angular-devkit/build-angular to 0.803.21, it's working as expected. 
As per my understanding, its broken in 0.803.23 while the following change and looks like `coverage-istanbul-loader` is not working properly for hybrid applications (AngularJs + Angular):

https://github.com/angular/angular-cli/commit/d88c5f81c778a84fdf6c90ea886df1bb2ed9b5d0 (@angular-devkit/build-angular): replace istanbul-instrumenter-loader with coverage-istanbul-loader)

**Comment by alan-agius4** [comment] 2020-02-08 15:59
Hi all, unfortunately without a reproduction we are unable to look and address this issue.

Can someone please share a minimal reproduction? Thanks.

**Comment by Pouja** [comment] 2020-02-08 20:53
@alan-agius4 Thanks for the fast reply! 

> Can you try to replicate this without custom builders?

I had to use the custom loader because we use the html-loader for our angularjs components. See #14855 and #16746 

> A good way to make a minimal repro is to create a new app via ng new repro-app and adding the minimum possible code to show the problem.

I tried to use the generated cli starter project with mixed js and ts files. But it still worked. I think the problem lies somewhere in how I bootstrap the angularjs. `serve` Works just fine for the record. I'll (after the weekend) keep trying to create a minimum repo. If I fail I'll just convince my team to invest time in converting all the `js` files to `ts`.

**Comment by danduh** [comment] 2020-02-10 08:40
@Pouja , We had the same issue. 
Not sure if this is fix or workaround but adding `"sourceMap": false` solved the problem
```
"test": {
          "builder": "ngx-build-plus:karma",
          "options": {
            "main": "src/main/javascript/flow-tests.ts",
            "polyfills": "src/main/javascript/polyfills.ts",
            "reporters": ["progress"],
            "tsConfig": "tsconfig.spec.json",
            "sourceMap": false,     // <---
            "karmaConfig": "karma.conf.js",
            "codeCoverage": true,
            "assets": [],
            "styles": [],
            "scripts": [],
            "extraWebpackConfig": "webpack.partial.js"
          }
        },
```

**Comment by Pouja** [comment] 2020-02-10 15:17
@danduh Thanks for the workaround, we can indeed run our coverage again. But I'm not sure if it because of the other coverage tool or because of the sourcemaps. But Instanbul indicates that all our import statements are unused or the import statement is missing a branch (which is silly ofcourse).
So for now we settled with the solution of @studix by downgrading `@angular-devkit/build-angular` to `0.802.2`

@alan-agius4 I wasnt able to reproduce our initial problem (missing sourcemaps) with the generated starter repo of the cli with the newer version of `@angular-devkit/build-angular` and mixed js and ts files.

I want to give it another try tomorrow by adding angularjs to the generated starter repo.

**Comment by Istanful** [comment] 2020-02-17 10:57
Using version `0.802.2` was not an option for me since that includes security warnings for [`serialize-javascript`](https://github.com/angular/angular-cli/issues/16414).

Version `0.803.23` introduces the source maps issue for me. It seems to be introduced in this commit: https://github.com/angular/angular-cli/commit/d88c5f81c778a84fdf6c90ea886df1bb2ed9b5d0

For anyone having the source map issue, I recommend using version `0.803.22` until this issue is fixed.

**Comment by SergeyKons** [comment] 2020-02-27 07:54
Hi, is there someone who was got same issue after update to angular 9?

**Comment by swapnilfarande** [comment] 2020-02-27 16:36
Hi everyone, I was able to crack this issue for my project. We were facing this issue because of importing ts file with js extension in other files.

File` wifi-manager.service.ts` was imported in another file as :
`import { ManagerService } from 'services/manager.service.js';`

Changing this to `import { WiFiManagerService } from 'services/wifi-manager.service';` fixed issue for us and all tests stared working as expected. 

@Pouja, in your case please check if file `hv-plan.module.ts`  is imported correctly in `structure.module.ts`. Try removing extensions while import.

**Comment by Pouja** [comment] 2020-03-02 15:22
@swapnilfarande All our imports are without extensions :/

We still have `sourceMap` set to `false` and everything still works.

**Comment by samuel-gay** [comment] 2020-03-17 05:32
> Hi, is there someone who was got same issue after update to angular 9?

Yeah, I'm getting this issue in angular 9, removed coverage reporting and tests run as normal.

**Comment by coryrylan** [comment] 2020-03-27 15:34
We are running into this issue as well due to the need to import a `.js` extension file. Currently have to disable code coverage. Started after the ng9 update. I'll see if I can get a repo.

**Comment by bogdanconstantinescu** [comment] 2020-04-06 11:26
> Hi everyone, I was able to crack this issue for my project. We were facing this issue because of importing ts file with js extension in other files.
> 
> File`manager.service.ts` was imported in another file as :
> `import { ManagerService } from 'services/manager.service.js';`
> 
> Changing this to `import { ManagerService } from 'services/manager.service';` fixed issue for us and all tests started working as expected.
> 
> @Pouja, in your case please check if file `hv-plan.module.ts` is imported correctly in `structure.module.ts`. Try removing extensions while import.

Thank you @swapnilfarande! In my case, after upgrading to Angular 9 the issue was a wrong import that had `.js` at the end.

**Comment by alan-agius4** [comment] 2020-04-06 11:31
Thanks @swapnilfarande for tracking down the issue and indeed, imports should not have an extensions.

Closing as it seems that the issue is not caused by the CLI.

**Closed by alan-agius4** 2020-04-06 11:31 UTC
Labels: need: repro steps
