### ISSUE TITLE
Can't run ng xi18n with imported local library

### ISSUE THREAD

**Issue by CN91** [angular/angular-cli#18464] opened 2020-08-06 13:37 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2

### Description

When developing a library locally and using the library in the main-application of the project, ng xi18n won't work. 

Building the library or the application work, however 'ng xi18n' doesn't complete and results in an error.

## 🔬 Minimal Reproduction

ng new lib-test
ng build
ng generate library my-temp-lib
ng build my-temp-lib
npm i .\dist\my-temp-lib

import { MyTempLibModule } from 'my-temp-lib';  in app.module.ts
and in 'imports' section add MyTempLibModule 

then try to run 'ng xi18n' 

## 🔥 Exception or Error
<pre><code>
ERROR in Unexpected value 'MyTempLibModule in C:/xxx/xxxx/Workspace/angular-lib-test/lib-test/dist/my-temp-lib/lib/my-temp-lib.module.d.ts' imported by the
module 'AppModule in C:/xxxx/xxxxx/Workspace/angular-lib-test/lib-test/src/app/app.module.ts'. Please add a @NgModule annotation.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.12
Node: 12.13.1
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.12
@angular-devkit/build-angular      0.901.12
@angular-devkit/build-ng-packagr   0.901.12
@angular-devkit/build-optimizer    0.901.12
@angular-devkit/build-webpack      0.901.12
@angular-devkit/core               9.1.12
@angular-devkit/schematics         9.1.12
@ngtools/webpack                   9.1.12
@schematics/angular                9.1.12
@schematics/update                 0.901.12
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Anything else relevant?**

Package json
<code>
{
  "name": "lib-test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.12",
    "@angular/common": "~9.1.12",
    "@angular/compiler": "~9.1.12",
    "@angular/core": "~9.1.12",
    "@angular/forms": "~9.1.12",
    "@angular/platform-browser": "~9.1.12",
    "@angular/platform-browser-dynamic": "~9.1.12",
    "@angular/router": "~9.1.12",
    "my-temp-lib": "file:dist/my-temp-lib",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.12",
    "@angular-devkit/build-ng-packagr": "~0.901.12",
    "@angular/cli": "~9.1.12",
    "@angular/compiler-cli": "~9.1.12",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "ng-packagr": "^9.0.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}

</code>

I have tried setting ivy to false in tsconfig.app.json like below >

 "angularCompilerOptions": {
    "enableIvy": false
  }

However this doesn't resolve the issue.

**Comment by alan-agius4** [comment] 2020-08-06 14:39
Duplicate of https://github.com/angular/angular-cli/issues/16395

**Closed by alan-agius4** 2020-08-06 14:39 UTC
