### ISSUE TITLE
Angular 15, build failing "Cannot read properties of undefined (reading 'file')"

### ISSUE THREAD

**Issue by meraj-markettime** [angular/angular-cli#25497] opened 2023-07-06 11:16 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.10

### Description

Building a new Angular 15.2.9 project via @angular/cli fails.

### Minimal Reproduction

ng build --configuration=production

### Your Environment

```text
Angular CLI: 15.2.8
Node: 16.13.0
Package Manager: npm 8.1.4
OS: win32 x64

Angular: 15.2.9
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.8
@angular-devkit/build-angular   15.2.8
@angular-devkit/core            15.2.8
@angular-devkit/schematics      15.2.8
@angular/cli                    15.2.8
@schematics/angular             15.2.8
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by thaoula** [comment] 2023-07-06 11:17
@meraj-markettime are you using Azure DevOps.

We are getting this issue on Angular 15 and Angular 16 builds.

**Comment by meraj-markettime** [comment] 2023-07-06 11:18
no we are using AWS and Bitbucket pipelines

**Comment by meraj-markettime** [comment] 2023-07-06 11:19
![image](https://github.com/angular/angular-cli/assets/82381740/57a413d5-c144-48e5-8570-8dd9126eb374)

**Comment by arluko** [comment] 2023-07-06 11:25
This seams to be related to https://github.com/angular/angular-cli/issues/25496

**Comment by thaoula** [comment] 2023-07-06 11:44
I just added this to package.json

  "overrides": {
    "@babel/traverse": "7.22.6"
  }

As suggested here -
https://github.com/babel/babel/issues/15752

**Comment by jgterradillos-stratio** [comment] 2023-07-06 11:46
We are having the same problems. The same errors in angular 15 and 14. In new clean projects happends the same.

**Comment by alan-agius4** [comment] 2023-07-06 11:52
Duplicate of https://github.com/angular/angular-cli/issues/25496

**Closed by alan-agius4** 2023-07-06 11:52 UTC
