### ISSUE TITLE
Ability to set global style bundles to be inline into index

### ISSUE THREAD

**Issue by OvidijusStukas** [angular/angular-cli#12968] opened 2018-11-15 17:03 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality
Ability to specify to inline global stylesheet in index.html. Currently there is not option to specificy to inline desired SCSS (CSS) bundle in angular.json.

This would be very helpful since all SCSS files would be processed and optimized and prepared for production and no external tooling would be needed to build Angular applications.

### Mention any other details that might be useful
For angular application preloaders or small static CSS to avoid application flickering and asset refresh while everything is downloading.

**Comment by alan-agius4** [comment] 2018-11-15 18:34
Duplicate of #11395

**Closed by alan-agius4** 2018-11-15 18:34 UTC
