### ISSUE TITLE
ng generate in a sub directory adds a backslash to the app.module import statement

### ISSUE THREAD

**Issue by NiklasTeich** [angular/angular-cli#2388] opened 2016-09-28 10:14 UTC
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.15
node: 6.3.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

"ng generate component" in a sub directory adds a backslash in the app.module.ts import statement.
For example, app/settings component exists, after "ng generate component users" in the settings directory, the app.module has this statement:
"import { UsersComponent } from './settings\users/users.component';"

ng serve crashes, after changing the backslash to a normal slash, ng serve builds everything and the app works like expected!

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Bad character escape sequence (24:44)
You may need an appropriate loader to handle this file type.
| import { DashboardComponent } from './dashboard/dashboard.component';
| import { SettingsComponent } from './settings/settings.component';
| import { UsersComponent } from './settings\users/users.component';
| export var AppModule = (function () {
|     function AppModule() {
 @ ./src/app/index.ts 2:0-29
 @ ./src/main.ts
 @ multi main

**Comment by gelliott181** [comment] 2016-09-29 12:45
Already known, see #2132 and #2357.

Workaround: Use your OSes expected directory separator. Windows users need to write paths using `\` and *Nix users should be using `/`.

**Comment by NiklasTeich** [comment] 2016-09-30 09:30
Thanks, good idea!
Another open (same addressed) issue is here: #2419

**Comment by filipesilva** [comment] 2016-10-05 20:48
Dupe of https://github.com/angular/angular-cli/issues/1719, already fixed.

**Closed by filipesilva** 2016-10-05 20:48 UTC
