### ISSUE TITLE
Build --watch doesn't remove previous files when --output-hashing is used

### ISSUE THREAD

**Issue by kyledevans** [angular/angular-cli#5846] opened 2017-04-05 18:42 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.9.2
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/animations: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.
1. Run `ng build --watch --output-hashing all`
2. Wait for the compiler to perform the first compile
3. Make a change to one of the source files and save

### Desired functionality.
The directory that contains the compiled output will have duplicate bundles, only they will have different hashes in their name.  This is because the initial compile generates the first bundle output with hash 1, and then when it detects a modified source file it creates a new set of bundled output with different hash.  It never deletes the first hashed output file.

This is a pain because it causes the build output directory to fill up with a bunch of garbage files.  In my opinion the compiler should automatically remove older versions of generated bundles.

**Comment by filipesilva** [comment] 2017-05-04 13:37
I think that makes sense. I worry there might be a performance problem but your logic is sound.

**Comment by luckynick** [comment] 2019-05-20 10:44
Any update on this? 

Dist folder grows to 100 mb easily. Manual deletion of content is needed, then ng build --watch again. Makes no sense to use --watch if you need to restart it periodically.

**Comment by mgechev** [comment] 2019-08-19 20:18
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:18 UTC
Labels: effort1: easy (hours), freq1: low, priority: 3 (nice to have), severity1: confusing, type: feature
