### ISSUE TITLE
Options  --ssl, --ssl-key and --ssl-cert have no effect. Serving over HTTPS does not work

### ISSUE THREAD

**Issue by igolfs** [angular/angular-cli#1874] opened 2016-08-29 15:53 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux Mint 17.3

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: local (v1.0.0-beta.11-webpack.2, branch: master)
node: 6.2.2
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Try to launch ng serve with ssl:

ng serve --ssl true --ssl-key ./sslcert/privkey.pem --ssl-cert ./sslcert/fullchain.pem

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

My app needs access to GeoLocation services but chrome will only provide them to pages loaded over HTTPS.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by munsellj** [comment] 2016-09-02 20:07
See also related #1576

**Comment by filipesilva** [comment] 2016-09-21 03:01
Dupe of https://github.com/angular/angular-cli/issues/1576

**Closed by filipesilva** 2016-09-21 03:01 UTC
