### ISSUE TITLE
'ng help generate' returns an error

### ISSUE THREAD

**Issue by yfain** [angular/angular-cli#9595] opened 2018-02-11 12:00 UTC
When you run ```ng help generate```, it returns an error "Cannot read property '0' of undefined".
Other help commands work fine.

I use Angular CLI 1.6.8 on macOS.

**Comment by petarblazevski** [comment] 2018-02-11 17:58
This one is a duplicate of issue #9589

**Comment by Brocco** [comment] 2018-02-12 16:25
Duplicate of #9412

Closing.

**Closed by Brocco** 2018-02-12 16:25 UTC
