### ISSUE TITLE
Can't find stylesheet to import.

### ISSUE THREAD

**Issue by mamjerez** [angular/angular-cli#25156] opened 2023-05-06 16:37 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

 "architect": {
                "build": {
                    "builder": "@angular-devkit/build-angular:browser-esbuild",

### Minimal Reproduction

 "architect": {
                "build": {
                    "builder": "@angular-devkit/build-angular:browser-esbuild",

### Exception or Error

```text
[ERROR] Can't find stylesheet to import.
  ╷
1 │ @import '/src/app/scss/base';
  │         ^^^^^^^^^^^^^^^^^^^^
  ╵
  src\app\home\components\card-info\card-info.component.scss 1:9  root stylesheet [plugin angular-sass]


X [ERROR] Can't find stylesheet to import.
  ╷
1 │ @import '/src/app/scss/base';

X [ERROR] Can't find stylesheet to import.
  ╷
3 │ @import '/src/app/scss/animations';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\styles.scss 3:9  root stylesheet [plugin angular-sass]

    angular:styles/global:styles:1:8:
      1 │ @import 'src/styles.scss';
        ╵         ~~~~~~~~~~~~~~~~~
```

### Your Environment

```text
Angular CLI: 16.0.0
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 16.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      4.9.3
```

**Comment by alan-agius4** [comment] 2023-05-08 07:48
Duplicate of https://github.com/angular/angular-cli/issues/23698

**Closed by alan-agius4** 2023-05-08 07:48 UTC
