### ISSUE TITLE
wrong source map path generated by `ng build`

### ISSUE THREAD

**Issue by UchihaYuki** [angular/angular-cli#22703] opened 2022-02-14 02:41 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I shipped my own angular libraries with typescript source code and source map, then consume it in a regular angular app. after run `ng build`, I observed the following item in vendor.js.map's sources property:
```
./node_modules/@myname/mylib/__ivy_ngcc__/src/lib/alert/alert.service.ts
```
which doesn't exist on my disk at all.

## 🌍 Your Environment

<pre><code>
Angular CLI: 11.2.18
Node: 16.13.1
OS: win32 x64
OS: win32 x64
OS: win32 x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.18
@angular-devkit/build-angular   0.1102.18
@angular-devkit/core            11.2.18
@angular-devkit/schematics      11.2.18
@angular/cli                    11.2.18
@schematics/angular             11.2.18
@schematics/update              0.1102.18
rxjs                            6.6.7
typescript                      4.0.8

</code></pre>

**Comment by alan-agius4** [comment] 2022-02-14 09:34
The is caused by NGCC which is needed for Angular libraries that have been compiled with older versions of Angular. NGCC is no longer needed when compiled with Angular 13+.

That said, in general it is not expected that TypeScript sources are included in `node_modules` See: https://github.com/angular/angular-cli/issues/22701

Closing as NGCC doesn't support such a library setup.

**Closed by alan-agius4** 2022-02-14 09:34 UTC
