### ISSUE TITLE
UNMET PEER DEPENDENCY error.

### ISSUE THREAD

**Issue by magichim** [angular/angular-cli#8512] opened 2017-11-16 13:08 UTC
My angular-cli version is (@angular/cli@1.5.0)

When I make new ng project and input 'npm list --depth=0', I get the npm message.

'UNMET PEER DEPENDENCY'

To fix, have to add  uninstall codelyzer.

or What should I do?

fix please.

**Comment by devoto13** [comment] 2017-11-16 13:58
Duplicate of https://github.com/angular/angular-cli/issues/8463. Subscribe to that issue. In the meantime you can upgrade codelyzer to 4+ yourself.

**Comment by magichim** [comment] 2017-11-16 15:13
@devoto13 Thanks!, but I have a question. Should I npm upgrade or npm install 4+ codelyzer by myself? Whenever I use angular-cli for making project, I need doing that?

**Closed** 2017-11-16 15:32 UTC

**Comment by devoto13** [comment] 2017-11-16 16:20
Yes. For now you'll have to do it manually every time. But it will probably be fixed in the next release.
