### ISSUE TITLE
--base-href option results into wrong base-href in index.html

### ISSUE THREAD

**Issue by MeMeMax** [angular/angular-cli#6060] opened 2017-04-24 13:44 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / â³ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.3
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/compiler-cli: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/platform-server: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0

### Repro steps.
Create a new project and build it with this command:
ng build --env prod --base-href /test/

This results into the following base href:

`<base href="C:/Program Files/Git/test/">`

### The log given by the failure.
- no error

### Desired functionality.
Result should be
`<base href="/test/">`

### Mention any other details that might be useful.
---

**Comment by MeMeMax** [comment] 2017-04-24 14:12
Ok. This seems to be a particular problem with git bash. Any ideas on resolving this?

**Comment by Bulan** [comment] 2017-04-26 06:08
I'm seeing this as well after upgrading to CLI v 1.0, worked before on the beta releases.

**Comment by MeMeMax** [comment] 2017-04-26 06:44
Do you use git bash or anything else?

**Comment by MeMeMax** [comment] 2017-04-26 07:00
Nevertheless I think this is a problem with git bash, not with angular cli since it works in cmd.

**Comment by Bulan** [comment] 2017-04-26 07:11
Nevertheless it worked on CLI beta with the same version of Git bash, so seems something changed on the CLI side. 
Anyone know which files this is setup? 
Did a quick search in source and base-href pops up all over the place.. Hard for a rookie to know where to look 😵

**Comment by filipesilva** [comment] 2017-05-05 16:55
Dupe of https://github.com/angular/angular-cli/issues/5606.

This is, unfortunately, very much a git bash problem. The string that reaches the CLI isn't `/test/` but `C:/Program Files/Git/test/`.

Workarounds are:
- use two slashes so gitbash doesn't replace it: `ng build --base-href //test/`
- setup a npm script: `"build-base-href": "ng build --base-href=/test/"`

**Closed by filipesilva** 2017-05-05 16:55 UTC

**Comment by daherrera40** [comment] 2019-06-11 20:30
> Dupe of #5606.
> 
> This is, unfortunately, very much a git bash problem. The string that reaches the CLI isn't `/test/` but `C:/Program Files/Git/test/`.
> 
> Workarounds are:
> 
> * use two slashes so gitbash doesn't replace it: `ng build --base-href //test/`
> * setup a npm script: `"build-base-href": "ng build --base-href=/test/"`

In my case the two slashes didn't worked but the second option works like a charm, thank you.
