### ISSUE TITLE
Differential loading bundle file names are not suffixed with ES2015 or ES5 causing only one file to output

### ISSUE THREAD

**Issue by jyothi530** [angular/angular-cli#17366] opened 2020-04-02 02:58 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No. Upgrade from Angular 8 to 9.

### Description
I am trying to utilize differential loading feature. I have set my app target to ES2015. ng build --prod shows in the console it is generating ES5 bundles. But in the final output I have only one file for each main, runtime, polyfills without suffix es2015, es5. Please see below screenshot.
![image](https://user-images.githubusercontent.com/19412829/78205933-7450da80-746b-11ea-95e4-781a8d83d69a.png)

 

## 🔬 Minimal Reproduction
It is consistently happening on a app upgraded from Angular 8 to 9. On a app directly created for Angular 9 no issues.

## 🔥 Exception or Error
Nothing

## 🌍 Your Environment
![image](https://user-images.githubusercontent.com/19412829/78205974-93e80300-746b-11ea-89f2-14964479b591.png)

**Anything else relevant?**
No

**Comment by alan-agius4** [comment] 2020-04-02 08:15
Hi @jyothi530, Are you using custom builders? I am unable to reproduce this with a standard CLI project?

**Comment by jyothi530** [comment] 2020-04-02 16:39
@alan-agius4 I use ngx-build-plus to define global variables. I figured out. Thanks for responding. In the build architect when my builder property value is "@angular-devkit/build-angular:build" it was producing files as mentioned above. I compared it with the standard cli project of angular 9. There the value was "@angular-devkit/build-angular:browser". It worked as expected after changing from build to browser. You can close the issue if you think it is working as expected. 
I have one question. A separate bundle is not generated for each lazy loaded modules. Everything is in main.js file. Can you please let know if I am missing something or with Ivy separate file will not be generated for each lazy loaded module.
Thanks

**Comment by alan-agius4** [comment] 2020-04-06 07:47
Duplicate of #16098

**Closed by alan-agius4** 2020-04-06 07:47 UTC
Labels: need: more info
