### ISSUE TITLE
Cannot be used with BSON library

### ISSUE THREAD

**Issue by XhstormR** [angular/angular-cli#27554] opened 2024-04-28 19:09 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I want to integrate the bson library into the app, library repo https://github.com/mongodb/js-bson, but an error occurred during build. 

I have searched those pages, it shows I can switch builder to `@angular-devkit/build-angular:browser-esbuild` to fix this error, but now it doesn't work.

https://github.com/angular/angular-cli/issues/26507
https://stackoverflow.com/questions/77287205/error-upon-importing-bson-library-saying-the-top-level-await-experiment-is-not

### Minimal Reproduction

in the angular project folder and run:
```shell
bun add bson
bun run build
```

### Exception or Error

```text
=> bun run  build
$ ng build 
Application bundle generation failed. [8.210 seconds]

✘ [ERROR] Top-level await is not available in the configured target environment ("chrome120.0", "edge120.0", "firefox115.0", "ios16.0", "safari16.0" + 5 overrides)

    node_modules/bson/lib/bson.mjs:204:26:
      204 │ const nodejsRandomBytes = await (async () => {
          ╵                           ~~~~~


error: script "build" exited with code 1
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.3.0
Node: 22.0.0 (Unsupported)
Package Manager: bun 1.1.5
OS: darwin x64

Angular: 17.3.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.0
@angular-devkit/build-angular   17.3.0
@angular-devkit/core            17.3.0
@angular-devkit/schematics      17.3.0
@schematics/angular             17.3.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4

Warning: The current version of Node (22.0.0) is not supported by Angular.
```

**Comment by alan-agius4** [comment] 2024-04-28 20:09
Duplicate of https://github.com/angular/angular-cli/issues/26507

Top level awaits are not supported and explicitly disabled as these can use a certain optimisations not to work correctly.

**Closed by alan-agius4** 2024-04-28 20:09 UTC

**Comment by XhstormR** [comment] 2024-04-29 09:39
@alan-agius4 is there a way to make bson library work with angular?
