### ISSUE TITLE
Error "An unhandled exception occurred: Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager" updating from angular 11 to Angular 12

### ISSUE THREAD

**Issue by jortiz-belike** [angular/angular-cli#21130] opened 2021-06-14 10:37 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9 10 11

### Description

 I am getting an error when trying to update my project from angular 11 to angular 12

## 🔬 Minimal Reproduction

I share the project dependencies:
```
"dependencies": {
    "@angular/animations": "~11.2.3",
    "@angular/cdk": "^11.2.3",
    "@angular/common": "~11.2.3",
    "@angular/compiler": "~11.2.3",
    "@angular/core": "~11.2.3",
    "@angular/forms": "~11.2.3",
    "@angular/material": "^11.2.3",
    "@angular/platform-browser": "~11.2.3",
    "@angular/platform-browser-dynamic": "~11.2.3",
    "@angular/router": "~11.2.3",
    "@asymmetrik/ngx-leaflet": "^8.1.0",
    "@asymmetrik/ngx-leaflet-draw": "^7.0.0",
    "@ng-bootstrap/ng-bootstrap": "^9.0.2",
    "angular-highcharts": "^11.3.1",
    "highcharts": "^9.0.1",
    "leaflet": "^1.7.1",
    "leaflet-draw": "^1.0.4",
    "leaflet-easybutton": "^2.4.0",
    "leaflet.markercluster": "^1.4.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.2",
    "@angular/cli": "~11.2.2",
    "@angular/compiler-cli": "~11.2.3",
    "@types/jasmine": "~3.6.0",
    "@types/leaflet": "^1.5.23",
    "@types/leaflet-draw": "^1.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.2"
  }
```

The command I have used to update is the following:

`ng update @angular/core@12 @angular/cli@12`

## 🔥 Exception or Error

<pre><code>
An unhandled exception occurred: Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"
See "C:\Users\juanj\AppData\Local\Temp\ng-I727YC\angular-errors.log" for further details.

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 11.2.3
Node: 14.16.0
OS: win32 x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cdk                    11.2.3
@angular/cli                    11.2.3
@angular/material               11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Anything else relevant?**

The most "strange" thing I have in the project are the leaflet dependencies, the same thing has happened to me in 2 projects that have similar dependencies.

**Comment by alan-agius4** [comment] 2021-06-14 10:49
Do you have `always-auth: true` set in your `.npmrc`?

**Comment by jortiz-belike** [comment] 2021-06-14 11:11
I don't have that file, as far as I know it is not generated when creating a new project in Angular.
I've had to use (.npmrc) it in another project, which doesn't have 'always-auth: true', but the credentials of the dependency I'm working with. (In that project the error is also presented)

**Comment by alan-agius4** [comment] 2021-06-14 11:23
Can you use `--verbose` flag when running `ng update` and kindly provide the logs. Thanks.

**Comment by jortiz-belike** [comment] 2021-06-14 11:39
```
Locating potential npmrc files:
Trying 'C:\Program Files\nodejs\etc\npmrc'...not found.
Trying 'C:\Users\juanj\.npmrc'...found.
Trying 'D:\code\.npmrc'...not found.
Trying 'D:\code\linkener-applications\.npmrc'...found.
Trying 'D:\code\linkener-applications\linkener-photovoltaic-calculator\.npmrc'...not found.
An unhandled exception occurred: Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"
See "C:\Users\juanj\AppData\Local\Temp\ng-q7fNtP\angular-errors.log" for further details.
```
I do not understand why this file is looking for me in my project while updating.
I had another local project in version 11 (without dependencies), very basic that I have been able to update

**Comment by alan-agius4** [comment] 2021-06-14 12:52
`ng update` will always try to locale npmrc files.

In this case for this application you have multiple npmrc files which are merged togather.

Likely the other application have not have been in the `D:\code\linkener-applications` directory.

Can you share the settings of all the located npmrc files (mask any sensitive info)

**Comment by jortiz-belike** [comment] 2021-06-14 12:53
For testing I have created the file .npmrc always = true, and it has not worked either
![image](https://user-images.githubusercontent.com/80050520/121894976-0a46ed00-cd20-11eb-91e1-86516ef258d8.png)

**Comment by alan-agius4** [comment] 2021-06-14 13:15
I suppose that the error doesn’t occur when you run `npm i‘ correct?

**Comment by jortiz-belike** [comment] 2021-06-14 14:22
I do not work with npmrc on this project.
I used it in a another project to install the company's own library (the problem also occurs in that project).
This project where the error occurs is a small project with a map.

Yes, the error occurs during update.

I do not know what configuration file you need, I have not configured anything other than leaflet, charts and material for this project.

**Comment by alan-agius4** [comment] 2021-06-14 14:45
@joseph-ortiz, By defining an npmrc in your user directory you are forcing all projects to use that npmrc file.

See: https://docs.npmjs.com/cli/v7/configuring-npm/npmrc

What is strange is that `npm i` works but `ng update ` doesn’t. This would need some work to determine what’s wrong since we don’t have a reproduction.

**Comment by jortiz-belike** [comment] 2021-06-14 15:17
Thanks to your last answer I have managed to solve one of the problems, in the path to the project there was a backup of the .npmrc file
![image](https://user-images.githubusercontent.com/80050520/121915849-e4c3de80-cd33-11eb-97af-42132f69dff5.png)
That solves the update of the smallest project that I have that has no npmrc dependencies.

**Now I have a project that does have npmrc, that I have updated it from version 8 to 11 without problems and that now gives me a problem and I don't know why**

![image](https://user-images.githubusercontent.com/80050520/121916277-4a17cf80-cd34-11eb-95dc-df12d0cab465.png)
I do not know what configuration I should use to update the angular, I think that changing the location of the file, and copying it again would work, but it is not the most optimal

**Comment by alan-agius4** [comment] 2021-06-14 16:20
Can you try the following
```
registry=https://example.com/repository/npm-group/:_auth=XXXXX
```

**Comment by jortiz-belike** [comment] 2021-06-14 16:45
npm 6.14.11
When making the change the error changes to:
![image](https://user-images.githubusercontent.com/80050520/121928580-936e1c00-cd40-11eb-9bc6-9c6cbd7a56a2.png)

**Comment by alan-agius4** [comment] 2021-06-15 06:19
So, I did look into this and using the below should fix the below issue.

Adding the below info in your project NPMC.
```ini
//localhost:4873/:_authToken="XXXX==" # Declare the proxy and it's auth.
registry=http://localhost:4873/ # Configure to use the proxy.
```

Alternatively you can use `npm login  --registry=http://localhost:4873/` so that the proxy and auth are configured globally and in your project just add the an NPMRC which uses the proxy.

```ini
registry=http://localhost:4873/ # Configure to use the proxy.
```

**Comment by jortiz-belike** [comment] 2021-06-15 07:28
I'm not getting what this has to do with the Angular update, with previous versions I had no problem.
If my password is abc123
Would the password be abc123== or just abc123?
Should the port be 4873, or can it be another?

**Comment by alan-agius4** [comment] 2021-06-15 09:45
`ng update` like `npm` has logic to read and parse the NPMRC to request packages via https://github.com/npm/npm-registry-fetch so that it can do network requests to the private/public NPM registries.

- `//localhost:4873/` needs to be replaced by your registry url, and no it doesn't need a port. 
- `XXXX==` needs to be replaced with your encrypted authentication token (Can be obtained when login via `npm login`)

At the point the easilest thing to do in your case would be to do the following

- Update `D:\code\linkener-applications\.npmrc` to the below:
```
registry=https://<registry>
```

- Delete `D:\code\linkener-applications\linkener-photovoltaic-calculator\.npmrc`

- Update `C:\Users\juanj\.npmrc` to contain the below;
```
//<registry>/:_auth="XXXXX"
```
 Alternatively and recommended use `npm login --registry=https://<registry>` instead of the last step.

**Comment by jortiz-belike** [comment] 2021-06-16 07:41
The project is LINKENER-Front
I dont know for what reason Angular search npmrc in Linkener-applications (Other project)

This is the folder structure.
I only want update Linkener-front. Linkener Front have npmrc file.
![image](https://user-images.githubusercontent.com/80050520/122178036-7d6a7380-ce86-11eb-88c3-0385b179fd75.png)


In C:\Users\juanj\.npmrc I Have
//registry.npmjs.org/:_authToken=55a623eb-c26a-XXX-XXXX-XXXXX    (diferent auth that auth in Linkener-front)

My current npmrc file in Linkener-front is
![image](https://user-images.githubusercontent.com/80050520/122178579-fc5fac00-ce86-11eb-9c19-e339826cfc40.png)

**Comment by alan-agius4** [comment] 2021-06-16 09:53
@jortiz-belike, I am confused because of multiple projects being mentioned here. it looks like now you are describing another project and not the one you previously provided the logs for ie `D:\code\linkener-applications\linkener-photovoltaic-calculator`.

Is the error in this project the same ie: `An unhandled exception occurred: Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager`? I noticed that in the last comment you are using `https:/` instead of `https://` as protocol.

If indeed this is the another project please provide the output of `ng update --verbose` and the sanitised contents of all the `.npmrc` ideally text code and not screenshots.

> if I run the XXX command in the terminal inside my project (linkener-front), will it go global, or only inside the project context which is really what I need?
The auth details will be globally saved, but you need to configure to use the registry locally in the project. 

Likely, `npm install` is working because it is fallbacking to using the locale cache, you can view these configures by running `npm config ls`.

> Is this problem Angular or NPM?

It is unclear if this is a bug or a misconfiguration. I am unable to replicate this behaviour on my machine, ie: `npm i` / `ng update` fail if the `_auth` or `_authToken` is not configured. Though, I think there is a small issue that for NPM we are trying to locate `npmrc` files in parent directories, which unlike `yarn` doesn't go up the directory tree to locate a configurations files. NPM rather relies on a number of specific locations https://docs.npmjs.com/cli/v7/configuring-npm/npmrc#comments

- per-project config file (/path/to/my/project/.npmrc)
- per-user config file (~/.npmrc)
- global config file ($PREFIX/etc/npmrc)
- npm builtin config file (/path/to/npm/npmrc)

**Comment by jortiz-belike** [comment] 2021-06-16 10:39
Sorry for the confusion
The initial situation is that I have 2 projects that I want to update.
The error was the same in the 2
This error `An unhandled exception occurred: Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager`

Project 1
`D:\code\linkener-applications\linkener-photovoltaic-calculator`
I had told you that in **the problem was solved**, because in its root it had a backup npmrc file
I deleted the file and updated and it works without problem. 

Project 2
`D:\code\linkener-front`   (app-front)
The problem remains, this project does have an npmrc file that we use for an internal component library.
This project I have updated from angular 8

the initial npmrc file in app-front looked like this
```
registry=https://XXXXXXXkener.com/repository/npm-group/
_auth=dmXXXXXXXXXXX
```

the current npmrc is:
https://XXXXXXX.linkener.com/repository/npm-group/:_auth=dmXXXXXXXXX
registry=https://XXXXXXXX.linkener.com/repository/npm-group/ 
(its Obvious that registry name is linkener)

`ng update --verbose`
```
Trying 'C:\Program Files\nodejs\etc\npmrc'...not found.
Trying 'C:\Users\juanj\.npmrc'...not found.
Trying 'D:\code\.npmrc'...not found.
Trying 'D:\code\linkener-front\.npmrc'...found.
An unhandled exception occurred: Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"
See "C:\Users\juanj\AppData\Local\Temp\ng-wcumcd\angular-errors.log" for further details. 
```


Something extra that I remember, on this same computer, in a test project I uploaded a package to NPM by logging in to NPM from that project's console. It was a webcomponent, but unrelated to this project

**Comment by alan-agius4** [comment] 2021-06-16 11:16
What is the output of `npm info` when you execute in `D:\code\linkener-front`?

**Comment by jortiz-belike** [comment] 2021-06-16 13:36
npm info
```
PS D:\code\linkener-front> npm info
npm ERR! code E401
npm ERR! Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\juanj\AppData\Roaming\npm-cache\_logs\2021-06-16T11_40_23_736Z-debug.log
```
I do not know what I should authenticate myself to


I try this.
//XXXX.linkener.com/repository/npm-group/:_auth=dmliYW5lejp2aWJhbmV6 # Declare the proxy and it's auth.
registry=https://XXXXXX.linkener.com/repository/npm-group/ # Configure to use the proxy.
Apparently it worked but it shows me error messages.
```
PS D:\code\linkener-front> ng update @angular/core@12 @angular/cli@12 --verbose
Locating potential npmrc files:
Trying 'C:\Program Files\nodejs\etc\npmrc'...not found.
Trying 'C:\Users\juanj\.npmrc'...not found.
Trying 'D:\code\.npmrc'...not found.
Trying 'D:\code\linkener-front\.npmrc'...found.
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
⠧ Installing package...

```

I don't know why the path must be relative to the auth, and I don't know why it worked before and I had to change it now.

**Comment by alan-agius4** [comment] 2021-06-17 09:13
Following some further investigation it appears that `npm-registry-fetch` ignores authentication details that are not scoped as part of the registry name. 

https://github.com/npm/npm-registry-fetch/blob/8954f61d8d703e5eb7f3d93c9b40488f8b1b62ac/auth.js#L45-L91

Hence, the below will not work. 
```
registry=https://XXXXXXXkener.com/repository/npm-group/
_auth=dmXXXXXXXXXXX
```

But this does
```
//XXXXXXX.linkener.com/repository/npm-group/:_auth=dmXXXXXXXXX
registry=https://XXXXXXXX.linkener.com/repository/npm-group/ 
```

`npm ls`, was used in this case to verify if you NPM couldsuccessfully authenticated you with `XXXXXXX.linkener.com`. In this case you weren't because the details in the `.npmrc` were invalid due to using the `https` instead of the `//` protocol.

**Comment by alan-agius4** [comment] 2021-06-17 09:17
Closed via https://github.com/angular/angular-cli/pull/21140

**Closed by alan-agius4** 2021-06-17 09:17 UTC
Labels: need: more info
