### ISSUE TITLE
ERROR in TypeError: Cannot read property 'flags' of undefined. When updated to latest angular packages from 9.1.4

### ISSUE THREAD

**Issue by ErVishalM** [angular/angular-cli#17669] opened 2020-05-08 11:08 UTC
Hi,
I'm getting the error
`**ERROR in TypeError: Cannot read property 'flags' of undefined**`
When i updated to latest angular-cli packages
previous version in which everything was working fine-
```
"@angular/animations": "^9.1.4",
"@angular/common": "^9.1.4",
"@angular/compiler": "^9.1.4",
"@angular/core": "^9.1.4",
"@angular/forms": "^9.1.4",
"@angular/platform-browser": "^9.1.4",
"@angular/platform-browser-dynamic": "^9.1.4",
"@angular/router": "^9.1.4",

```
current updated to latest in which error is coming-

```
"@angular/animations": "^9.1.5",
"@angular/common": "^9.1.5",
"@angular/compiler": "^9.1.5",
"@angular/core": "^9.1.5",
"@angular/forms": "^9.1.5",
"@angular/platform-browser": "^9.1.5",
"@angular/platform-browser-dynamic": "^9.1.5",
"@angular/router": "^9.1.5",

```
Can somebody help me please.

**Comment by igorosabel** [comment] 2020-05-08 11:42
I have the same issue, but only on Win10. On macOS 10.15.4 works fine.

**Comment by alan-agius4** [comment] 2020-05-08 12:06
Duplicate of https://github.com/angular/angular/issues/36993

**Closed by alan-agius4** 2020-05-08 12:06 UTC
