### ISSUE TITLE
ng serve fail after third reload error: TypeError: Cannot read property 'jsonData' of undefined

### ISSUE THREAD

**Issue by hajekj14** [angular/angular-cli#21373] opened 2021-07-20 16:12 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11.2.12

### Description

 After third reload (change file in watch mode) ng serve will fail with exception

## 🔥 Exception or Error

<pre><code>

Build at: 2021-07-20T15:58:11.772Z - Hash: ca28e5ce1300d15845e9 - Time: 5041ms

√ Compiled successfully.
⠋ Generating browser application bundles...C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\json\JsonGenerator.js:119
                let data = module.buildInfo.jsonData;
                                            ^

TypeError: Cannot read property 'jsonData' of undefined
    at JsonGenerator.getSize (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\json\JsonGenerator.js:119:31)
    at NormalModule.size (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModule.js:1224:43)
    at NormalModule.cleanupForCache (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModule.js:364:9)
    at NormalModuleFactory.cleanupForCache (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModuleFactory.js:670:11)
    at Compiler._cleanupLastNormalModuleFactory (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:383:34)
    at Compiler.createNormalModuleFactory (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1049:8)
    at Compiler.newCompilationParams (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1071:30)
    at Compiler.compile (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1082:23)
    at C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Watching.js:188:19
    at Hook.eval [as callAsync] (eval at create (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
    at run (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Watching.js:142:33)
    at C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Watching.js:129:6
    at C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Cache.endIdle (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Cache.js:140:22)
    at run (C:\Users\JiriHajek\projects\e2e\ra-web-fe\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Watching.js:126:32)
</code></pre>

## 🌍 Your Environment

<pre><code>

@angular-devkit/architect          0.1201.2
@angular-devkit/build-angular      12.1.2
@angular-devkit/build-ng-packagr   0.1001.7
@angular-devkit/core               12.1.2
@angular-devkit/schematics         12.1.2
@schematics/angular                12.1.2
ng-packagr                         12.1.2
rxjs                               6.6.7
typescript                         4.2.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-07-20 16:33
Duplicate of #21349

**Closed by alan-agius4** 2021-07-20 16:33 UTC
