### ISSUE TITLE
App broken with a --prod build

### ISSUE THREAD

**Issue by umarov** [angular/angular-cli#10910] opened 2018-05-18 02:33 UTC
### Versions
```
Angular CLI: 6.0.3
Node: 10.1.0
OS: linux x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@angular/pwa                      0.6.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3

Target: es2016

```

### Repro steps

[Here is the repo for repro](https://github.com/umarov/basic-angular-app). It's deployed to [github pages here](https://umarov.github.io/basic-angular-app/)

* `ng new --routing -p basic -S -g --style scss basic-angular-app `
* Update `tsconfig.json` to target ES2016. (_Note: Problem happens with ES5 as well, I tried_)
* `ng build --prod --output-path docs --base-href basic-angular-app`
* Git add and push to master branch
* Blank white screen, check console to see error

### Observed behavior
```
Uncaught ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
```

### Desired behavior
App to just work and see the hello world screen with angular logo.

### Mention any other details that might be useful (optional)
This is happening on my [other project](https://github.com/umarov/node-todo-api). It also [lives in Github pages](https://umarov.github.io/node-todo-api/). You can see the same error there as well. It's broken in production.

**Comment by larssn** [comment] 2018-05-18 07:38
Related issue: https://github.com/angular/angular-cli/issues/10658

**Comment by filipesilva** [comment] 2018-05-18 13:43
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/devkit/issues/816. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2018-05-18 13:43 UTC

**Comment by filipesilva** [comment] 2018-05-18 13:45
Note: you mentioned that this happens with ES5 as well but the error message shown (`Must call super constructor`) is something that only happens with Build Optimizer with ES2015. 

If you get a different message with ES5, please let me know. If you get the same message on ES5, then one of the libraries you import must be exporting ES2015 and that is why it breaks on Build Optimizer.

You can disable Build Optimizer meanwhile though.

**Comment by umarov** [comment] 2018-05-18 14:05
@filipesilva I get the exact same message in es5 target. I am just using the default generated app from angular cli, not extra libraries and no modification to the code itself. I will be following it on the devkit repo

**Comment by clydin** [comment] 2018-05-18 14:14
@umarov Can you provide a reproduction?  Classes don't exist in ES5.

**Comment by clydin** [comment] 2018-05-18 14:48
Using the reproduction found above and changing the TS target to `es5`, resulted in the application working as expected with `--prod`.  ES5 does not have classes so the only way to receive the error indicated above in that scenario would be if a third-party ES2015 library containing classes was used within the application.

In the `"target": "es2016",` case, disabling build optimizer results in a working application.

**Comment by umarov** [comment] 2018-05-18 14:52
Only third party library seems to be rxjs.
