### ISSUE TITLE
The `ng serve` command is unusually slow in v12

### ISSUE THREAD

**Issue by hadrien-toma** [angular/angular-cli#21116] opened 2021-06-11 07:45 UTC
# 🐞 Bug report

### Command

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was 11.

### Description

The `ng serve` command is unusually slow and considerably increase with the number of library (especially lazy loaded ones from what I experienced).

## 🔬 Minimal Reproduction

I privately shared a reproduction with @alan-agius4 (link here https://github.com/hadrien-toma/angular-12-perf-troubleshooting) and I am opening this issue here in order to track it properly and to not pollute the one I originally posted in (https://github.com/angular/angular-cli/issues/20713).

## 🔥 Exception or Error

No error.

## 🌍 Your Environment

Here is my `package.json` dependencies (`@angular/core` installed is 12.0.4).

```json

    "@angular/animations": "^12.0.0",
    "@angular/cdk": "^12.0.4",
    "@angular/common": "^12.0.0",
    "@angular/compiler": "^12.0.0",
    "@angular/core": "^12.0.0",
    "@angular/forms": "^12.0.0",
    "@angular/material": "^12.0.4",
    "@angular/platform-browser": "^12.0.0",
    "@angular/platform-browser-dynamic": "^12.0.0",
    "@angular/platform-server": "^12.0.0",
    "@angular/router": "^12.0.0",
```

**Comment by alan-agius4** [comment] 2021-06-11 08:24
@hadrien-toma thanks a lot for sharing the project and all the details, reproductions like these are super helpful and crucial to get to the bottom of issue.

Myself and @JoostK are looking at this and it appears that this performance issue is only manifested during watch mode.

We'll keep you posted.

**Comment by hadrien-toma** [comment] 2021-06-11 15:39
I see, thank you very much for your time and help. So what I plan to do is:

- [ ] to make a public reproduction of this issue in an Nx workspace and raise an issue on Nx side hoping a solution will pop overthere :four_leaf_clover:.
- [ ] to share this reproduction on the TypeScript repo. I think I will not be able to remove all Nx and Ng tooling unfortunately...

As a side note, a workaround I am thinking of at the moment : run `chokidar` on my side with a custom/crafted watch configuration and run `nx:affected` commands when a changes occurs, maybe the incremental build will be more comfortable than the current very slow ng serve :thinking: :crossed_fingers:...

**Comment by alan-agius4** [comment] 2021-06-11 15:55
> to share this reproduction in an issue on the TypeScript repo. I think I will not be able to remove all Nx and Ng tooling unfortunately...

All you need to keep is the `libs` folder and tsconfig files.

**Comment by hadrien-toma** [comment] 2021-06-11 15:59
@alan-agius4 ah, thank you! So I will do that :handshake: !

**Comment by JoostK** [comment] 2021-06-11 16:02
@hadrien-toma FYI, Nx has [buildable libraries](https://nx.dev/latest/angular/structure/buildable-and-publishable-libraries) that result in each library having its own compilation unit.

**Comment by hadrien-toma** [comment] 2021-06-11 16:04
@JoostK Yes, in fact, in the shared reproduction all the libs are already `--buildable` and `--publisbale`, it should have change something? :persevere:

**Comment by JoostK** [comment] 2021-06-11 16:06
Oh I was expecting it to not use that (haven't had a look at the repro yet)

**Comment by alan-agius4** [comment] 2021-06-11 16:11
> @JoostK Yes, in fact, in the shared reproduction all the libs are already `--buildable` and `--publishable`, it should have changed something? 😣

In the monorepo however libraries are consumed using path mappings directly to the sources and not the built versions. Therefore, they become part of the application compilation unit.

**Comment by hadrien-toma** [comment] 2021-06-11 16:13
Yeap, that's why I supposed it was not linked, the fact that they are buildable and publishable is more link to the final delivery process.

**Comment by hadrien-toma** [comment] 2021-06-12 07:46
> @JoostK Yes, in fact, in the shared reproduction all the libs are already --buildable and --publishable, it should have changed something? persevere

I just made another example without specifying that lazy loaded routes are `--buildable` and `--publishable` (by default they are not) but the duration of the `ng serve` remains the same.

**Comment by hadrien-toma** [comment] 2021-06-12 10:03
As a workaround for the moment I am using [`chokidar`](https://github.com/paulmillr/chokidar) to watch specifically inside my libs and apps, a change re-run nx build command (so using its cache) and then re-run [`angular-http-server`](https://github.com/simonh1000/angular-http-server). 

Even if the browser is not updated automatically, the time to get the app working the first time is around 70s, which allows me to work again even if not really comfortable...

**Comment by hadrien-toma** [comment] 2021-06-13 06:03
I have done another example in v11 and the `ng serve` is fine so in a "user" point of view, this slow behavior is likely to be considered as a regression (I am not saying this is linked to Angular, it could be on Nx or TypeScript side).

**Comment by alan-agius4** [comment] 2021-06-13 06:21
@hadrien-toma, as mentioned earlier this appears to be caused by TypeScript incremental API, as it can also be reproduced using `tsc` directly.

I strongly suggest that you share a reproduction with the TypeScript team so that they can investigate from their end.

**Comment by hadrien-toma** [comment] 2021-06-13 12:42
Hey @alan-agius4 yes I will try to do a sharable smaller reproduction asap 😬

**Comment by jonastg** [comment] 2021-06-21 08:26
I'm having the same issue with build and serve times in a new nx monorepo project and the time oscillates between 120s to 380s. My configuration:

```
Dev config:

"development": {
    "aot": true,
    "buildOptimizer": false,
    "optimization": false,
    "vendorChunk": true,
    "extractLicenses": false,
    "sourceMap": true,
    "namedChunks": true
}

---------------------------------------------------------

Angular CLI: 12.0.0
Node: 12.22.1
Package Manager: npm 6.14.12
OS: linux x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
ng-packagr                      12.0.2
rxjs                            6.6.7
typescript                      4.2.4

```

**Comment by hadrien-toma** [comment] 2021-06-21 08:47
Thanks for sharing @jonastg, I will not have time to work on it recently, do you mind to share a reproduction on your side?

**Comment by glebmachine** [comment] 2021-06-23 16:18
I had to migrate the application back to the 11.0.3
This is a disaster(

Does anybody handle it already?

**Comment by alan-agius4** [comment] 2021-06-23 17:25
@glebmachine, you might be experiencing a different issue. Please file a new issue including a reproduction or at the very minimum a CPU profile. You can also share the project privately like @hadrien-toma did for this issue.

Regarding this specific issue, there is not much we can do since this is caused by an issue in TypeScript incremental API, which @hadrien-toma will/will report to TypeScript and provide a minimal reproduction based on his problematic project.

**Comment by alan-agius4** [comment] 2021-06-25 08:37
Closing since for this particular issue is not actionable from our end since it's a bug inside of the TypeScript compiler.

**Closed by alan-agius4** 2021-06-25 08:37 UTC
Labels: severity4: memory/performance
