### ISSUE TITLE
@angular/cli Fails due to Missing pinkie-promise@^2.0.0 dependencies

### ISSUE THREAD

**Issue by patilraviraj2007GitHub** [angular/angular-cli#9116] opened 2018-01-06 21:08 UTC
npm install -g @angular/cli Fails due to dependencies are missing

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: **pinkie-promise@^2.0.0** (node_modules\read-pkg-up\node_modules\find-up\node_modules\pinkie-promise):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No valid versions available for pinkie-promise
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pinkie-promise@^2.0.0 (node_modules\load-json-file\node_modules\pinkie-promise):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No valid versions available for pinkie-promise

npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for pinkie-promise

**Comment by kyen99** [comment] 2018-01-06 21:55
This was a temporary issue caused by pinkie-promise getting unpublished from the npm registry. It probably works now.

**Comment by hansl** [comment] 2018-01-07 20:33
Closing this as fixed.

**Closed by hansl** 2018-01-07 20:33 UTC
