### ISSUE TITLE
angular-builder:browser-esbuild build fails with Bootstrap5 SCSS imports

### ISSUE THREAD

**Issue by alydemah** [angular/angular-cli#24276] opened 2022-11-18 09:55 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

After switching to the new experimental esbuild in Angular 15 the build fails using Bootstrap 5 SCSS imports.

The app imports the bootstrap 5 SCSS in the root angular app.scss located under /assets/scss

### Minimal Reproduction

ng build output

`
$ ng build
The esbuild browser application builder ('browser-esbuild') is currently experimental.
The 'budgets' option is currently unsupported by this experimental builder and will be ignored.
The 'progress' option is currently unsupported by this experimental builder and will be ignored.
The 'inlineStyleLanguage' option is currently unsupported by this experimental builder and will be ignored.
The 'namedChunks' option is currently unsupported by this experimental builder and will be ignored.
▲ [WARNING] Calling "moment" will crash at run-time because it's an import namespace object, not a function [call-import-namespace]

✘ [ERROR] [plugin angular-sass] Expected ".
    ╷
135 │       @if str-index($string, "url(./../node_modules/bootstrap/scss/\") == 1 {
    │                                                                              ^
    ╵
  node_modules\bootstrap\scss\_functions.scss 135:78  @import
  bootstrap\scss\bootstrap.scss 7:9                   @import
  src\styles.scss 2:9                                 root stylesheet

    angular:styles/global:styles:2:8:
      2 │ @import 'src/styles.scss';
        ╵         ~~~~~~~~~~~~~~~~~

✘ [ERROR] [plugin angular-sass] Expected ".
    ╷
135 │       @if str-index($string, "url(./../../../node_modules/bootstrap/scss/\") == 1 {
    │                                                                                    ^
    ╵
  bootstrap\scss\_functions.scss 135:84  @import
  src\assets\scss\bootstrap.scss 2:9     root stylesheet

    angular:styles/global:styles:3:8:
      3 │ @import 'src/assets/scss/bootstrap.scss';
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] [plugin angular-sass] Expected ".
    ╷
135 │       @if str-index($string, "url(./../../../node_modules/bootstrap/scss/\") == 1 {
    │                                                                                    ^
    ╵
  bootstrap\scss\_functions.scss 135:84  @import
  src\assets\scss\app.scss 3:9           root stylesheet

    angular:styles/global:styles:4:8:
      4 │ @import 'src/assets/scss/app.scss';
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~

`

Main app.scss located under assets/scss

`

//Core files
@import 'bootstrap/scss/functions';
@import 'bootstrap/scss/variables';
@import 'variables';
@import 'bootstrap/scss/mixins.scss';

@import "themes/theme-base";
@import "themes/theme-dark";

`

package.json

`
{
  "name": "test-esbuild-ng",
  "version": "1.0.0",
  "scripts": {
    "start": "ng serve",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "serve": "ng serve",
    "build:prod": "ng build --configuration production",
    "build:staging": "ng build --configuration=staging",
    "build:sandbox": "ng build ---prod --build-optimizer"

  },
 
  "dependencies": {
    "@angular-builders/custom-webpack": "^13.1.0",
    "@angular/animations": "^15.0.0",
    "@angular/cdk": "^15.0.0",
    "@angular/common": "^15.0.0",
    "@angular/compiler": "^15.0.0",
    "@angular/core": "^15.0.0",
    "@angular/forms": "^15.0.0",
    "@angular/platform-browser": "^15.0.0",
    "@angular/platform-browser-dynamic": "^15.0.0",
    "@angular/router": "^15.0.0",
    "@auth0/angular-jwt": "^5.0.2",
    "@ckeditor/ckeditor5-angular": "^4.0.0",
    "@ckeditor/ckeditor5-build-classic": "^35.3.0",
    "@ckeditor/ckeditor5-media-embed": "^35.3.0",
    "@ckeditor/ckeditor5-upload": "^35.3.0",
    "@commitlint/cli": "^16.2.1",
    "@commitlint/config-conventional": "^16.2.1",
    "@fortawesome/fontawesome-free": "^6.1.1",
    "@ng-bootstrap/ng-bootstrap": "^13.0.0",
    "@ngxs-labs/dispatch-decorator": "^4.0.2",
    "@ngxs/devtools-plugin": "^3.7.5",
    "@ngxs/form-plugin": "^3.7.5",
    "@ngxs/logger-plugin": "^3.7.5",
    "@ngxs/storage-plugin": "^3.7.5",
    "@ngxs/store": "^3.7.5",
    "@popperjs/core": "^2.11.2",
    "@swimlane/ngx-datatable": "^20.0.0",
    "@types/feather-icons": "^4.7.0",
    "@types/forge-viewer": "^7.69.4",
    "@types/simplebar": "^5.3.3",
    "acorn": "^8.7.0",
    "angular-archwizard": "^7.0.0",
    "angularx-flatpickr": "^6.6.0",
    "apexcharts": "^3.35.0",
    "autolinker": "^3.14.3",
    "bootstrap": "^5.2.0",
    "chartist": "^0.11.4",
    "dayjs": "^1.11.6",
    "dropzone": "^6.0.0-beta.2",
    "feather-icons": "^4.29.0",
    "file-saver": "^2.0.5",
    "git-describe": "^4.1.1",
    "jspdf": "^2.5.1",
    "jspdf-autotable": "^3.5.23",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "lodash-es": "^4.17.21",
    "marked": "^4.0.12",
    "metismenujs": "^1.3.1",
    "moment": "^2.29.2",
    "ng-apexcharts": "^1.7.0",
    "ng-click-outside": "^9.0.1",
    "ngx-color-picker": "^11.0.0",
    "ngx-file-drop": "^13.0.0",
    "ngx-lightbox": "^2.5.2",
    "ngx-mask": "^13.1.1",
    "prettier": "^2.6.2",
    "primeflex": "^3.1.3",
    "primeicons": "^5.0.0",
    "primeng": "^14.1.2",
    "quill": "^1.3.7",
    "rxjs": "~7.5.0",
    "simplebar": "^5.3.9",
    "stream": "0.0.2",
    "tslib": "^2.3.0",
    "url-parse": "^1.5.10",
    "xlsx": "^0.18.5",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.0",
    "@angular/cli": "^15.0.0",
    "@angular/compiler-cli": "^15.0.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.8.4",
    "@angular-eslint/builder": "^13.2.0",
    "@angular-eslint/eslint-plugin": "^13.2.0",
    "@angular-eslint/eslint-plugin-template": "^13.2.0",
    "@angular-eslint/template-parser": "^13.2.0",
    "@angular/localize": "^15.0.0",
    "@semantic-release/changelog": "^6.0.1",
    "@semantic-release/git": "^10.0.1",
    "@types/lodash": "^4.14.178",
    "@types/url-parse": "^1.4.8",
    "@types/file-saver": "^2.0.5",
    "@types/lodash-es": "^4.17.6",
    "@typescript-eslint/eslint-plugin": "^5.18.0",
    "@typescript-eslint/parser": "^5.18.0",
    "eslint": "^8.12.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsdoc": "^38.1.6",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "husky": "^7.0.4",
    "lint-staged": "^12.3.4",
    "postcss-modules": "^4.3.0",
    "posthtml-css-modules": "^0.1.3",
    "posthtml-loader": "^2.0.1",
    "pretty-quick": "^3.1.3",
    "raw-loader": "^4.0.2"
  },
  "lint-staged": {
    "*.js": "eslint --cache --fix"
  }
}

`

Style imports in angular.json

`
 "build": {
          "builder": "@angular-devkit/build-angular:browser-esbuild",
          "options": {
            "outputPath": "dist/app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss",
              "src/assets/scss/app.scss",
              "src/assets/scss/icons.scss"
             
            ],
            "scripts": [],
            "vendorChunk": false,
            "extractLicenses": false,
            "buildOptimizer": true,
            "sourceMap": false,
            "optimization": true,
            "namedChunks": true,
            "outputHashing": "all",
            "crossOrigin": "anonymous",
            "progress": true,
            "stylePreprocessorOptions": {}

`

### Your Environment

```text
Angular CLI: 15.0.0
Node: 14.20.1
Package Manager: npm 8.14.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1500.0 (cli-only)
@angular-devkit/core         15.0.0 (cli-only)
@angular-devkit/schematics   15.0.0 (cli-only)
@schematics/angular          15.0.0 (cli-only)
```

**Comment by clydin** [comment] 2022-11-18 12:02
Duplicate of #24245

**Closed by clydin** 2022-11-18 12:02 UTC
