### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed

### ISSUE THREAD

**Issue by jgenchik** [angular/angular-cli#709] opened 2016-05-10 15:44 UTC
```
ng --version
angular-cli: 1.0.0-beta.1
node: 4.3.1
os: win32 x64
```
npn version: 3.7.3

All I do (these are the steps to reproduce) are these 3 steps:
`ng new try-cli`
`cd try-cli`
`ng serve`

The `ng serve` generates the following error:
```
ng serve

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

Livereload server on http://localhost:49155
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EPERM: operation not permitted, symlink 'C:\development\try-cli\tmp\broccoli_type_script_compiler-cache_path-eQw1jvoS.tmp\src\app\environment.js.map' ->
'C:\development\try-cli\tmp\broccoli_type_script_compiler-output_path-K88yBtUv.tmp\src\app\environment.js.map'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at BroccoliTypeScriptCompiler._outputFile (C:\development\try-cli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:206:8)
    at C:\development\try-cli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:108:18
    at Array.forEach (native)
    at C:\development\try-cli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:107:30
    at Array.forEach (native)
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\development\try-cli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:93:19)
    at BroccoliTypeScriptCompiler.build (C:\development\try-cli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\development\try-cli\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\development\try-cli\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16
)
    at lib$rsvp$$internal$$invokeCallback (C:\development\try-cli\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1
048:17)
    at lib$rsvp$$internal$$publish (C:\development\try-cli\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)

    at lib$rsvp$asap$$flush (C:\development\try-cli\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\development\try-cli\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\inde
x.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\development\try-cli\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:
21:10)
    at BroccoliTypeScriptCompiler (C:\development\try-cli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (C:\development\try-cli\node_modules\angular-cli\lib\broccoli\angular2-app.js:280:18)
    at Angular2App._buildTree (C:\development\try-cli\node_modules\angular-cli\lib\broccoli\angular2-app.js:101:23)
    at new Angular2App (C:\development\try-cli\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
    at module.exports (C:\development\try-cli\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\development\try-cli\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:
19)
    at Class.module.exports.Task.extend.init (C:\development\try-cli\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\development\try-cli\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\development\try-cli\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
    at C:\development\try-cli\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (C:\development\try-cli\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\development\try-cli\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\development\try-cli\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\development\try-cli\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

 
```
npm info angular-cli
{ name: 'angular-cli',
  time:
   { modified: '2016-05-07T16:07:33.383Z',
     created: '2014-10-07T04:34:38.078Z',
     '1.0.0': '2014-10-07T04:34:38.078Z',
     '0.0.0': '2014-10-11T11:38:24.914Z',
     '0.0.1': '2015-08-03T17:12:04.553Z',
     '0.0.2': '2015-10-18T17:46:40.146Z',
     '0.0.3': '2015-10-18T21:42:52.445Z',
     '0.0.4': '2015-10-19T01:14:13.216Z',
     '0.0.5': '2015-10-19T09:14:01.712Z',
     '0.0.6': '2015-10-19T09:36:51.644Z',
     '0.0.7': '2015-10-19T11:48:24.233Z',
     '0.0.8': '2015-10-19T11:51:59.318Z',
     '0.0.9': '2015-10-19T21:18:13.725Z',
     '0.0.10': '2015-10-19T22:18:13.091Z',
     '0.0.11': '2015-11-03T05:03:06.345Z',
     '0.0.12': '2015-11-15T10:10:48.551Z',
     '0.0.13': '2015-12-04T17:16:43.662Z',
     '0.0.14': '2015-12-05T01:40:39.377Z',
     '0.0.15': '2015-12-05T05:50:59.226Z',
     '0.0.16': '2015-12-10T12:23:28.722Z',
     '0.0.17': '2015-12-14T19:37:08.400Z',
     '0.0.18': '2015-12-15T12:51:47.990Z',
     '0.0.19': '2015-12-15T18:23:33.077Z',
     '0.0.20': '2015-12-15T20:39:55.357Z',
     '0.0.22': '2016-02-20T00:36:56.908Z',
     '0.0.23': '2016-02-20T01:44:13.897Z',
     '0.0.24': '2016-02-25T17:41:20.619Z',
     '0.0.25': '2016-03-10T02:10:05.410Z',
     '0.0.26': '2016-03-23T00:39:46.402Z',
     '0.0.27': '2016-03-23T22:05:56.538Z',
     '0.0.28': '2016-03-28T22:39:45.766Z',
     '0.0.29': '2016-03-30T18:10:47.060Z',
     '0.0.30': '2016-04-06T22:27:32.015Z',
     '0.0.31': '2016-04-11T18:20:32.677Z',
     '0.0.33': '2016-04-19T22:31:48.209Z',
     '0.0.34': '2016-04-26T17:56:20.524Z',
     '0.0.37': '2016-05-03T18:49:21.731Z',
     '0.0.39': '2016-05-04T16:29:23.054Z',
     '0.1.0': '2016-05-05T19:41:05.830Z',
     '1.0.0-beta.0': '2016-05-06T18:18:54.950Z',
     '1.0.0-beta.1': '2016-05-07T16:07:33.383Z' },
  maintainers:
   [ 'angularcore <angular-core+npm@google.com>',
     'rodyhaddad <npm@rodyhaddad.com>' ],
  description: 'CLI tool for Angular',
  versions:
   [ '0.0.0',
     '0.0.1',
     '0.0.2',
     '0.0.3',
     '0.0.4',
     '0.0.5',
     '0.0.6',
     '0.0.7',
     '0.0.8',
     '0.0.9',
     '0.0.10',
     '0.0.11',
     '0.0.12',
     '0.0.13',
     '0.0.14',
     '0.0.15',
     '0.0.16',
     '0.0.17',
     '0.0.18',
     '0.0.19',
     '0.0.20',
     '0.0.22',
     '0.0.23',
     '0.0.24',
     '0.0.25',
     '0.0.26',
     '0.0.27',
     '0.0.28',
     '0.0.29',
     '0.0.30',
     '0.0.31',
     '0.0.33',
     '0.0.34',
     '0.0.37',
     '0.0.39',
     '0.1.0',
     '1.0.0-beta.0',
     '1.0.0-beta.1' ],
  'dist-tags': { latest: '1.0.0-beta.1', beta: '1.0.0-beta.1' },
  readmeFilename: 'README.md',
  homepage: 'https://github.com/angular/angular-cli',
  keywords: [],
  repository:
   { type: 'git',
     url: 'git+https://github.com/angular/angular-cli.git' },
  author: 'Angular Authors',
  bugs: { url: 'https://github.com/angular/angular-cli/issues' },
  license: 'MIT',
  contributors:
   [ 'Rody Haddad <npm@rodyhaddad.com> (http://rodyhaddad.com/)',
     'Igor Minar <igor@angularjs.org>' ],
  users: { altrim: true, seachange: true },
  version: '1.0.0-beta.1',
  main: 'lib/cli/index.js',
  trackingCode: 'UA-8594346-19',
  bin: { ng: './bin/ng' },
  scripts: { test: 'node tests/runner', lint: 'eslint .' },
  engines: { node: '>= 4.1.0' },
  dependencies:
   { broccoli: '^1.0.0-beta.7',
     'broccoli-caching-writer': '^2.2.1',
     'broccoli-concat': '^2.2.0',
     'broccoli-funnel': '^1.0.1',
     'broccoli-merge-trees': '^1.1.1',
     'broccoli-source': '^1.1.0',
     'broccoli-writer': '^0.1.1',
     chalk: '^1.1.3',
     'ember-cli': '2.5.0',
     'ember-cli-string-utils': '^1.0.0',
     exit: '^0.1.2',
     'fs-extra': '^0.30.0',
     glob: '^7.0.3',
     leek: '0.0.21',
     lodash: '^4.11.1',
     opn: '4.0.1',
     resolve: '^1.1.7',
     shelljs: '^0.7.0',
     'silent-error': '^1.0.0',
     'symlink-or-copy': '^1.0.3',
     'systemjs-builder': '^0.15.16',
     typescript: '^1.8.10',
     typings: '^0.8.1' },
  'ember-addon': { paths: [ './addon/ng2/' ] },
  devDependencies:
   { chai: '^3.5.0',
     'clang-format': '^1.0.38',
     eslint: '^2.8.0',
     'exists-sync': '0.0.3',
     minimatch: '^3.0.0',
     mocha: '^2.4.5',
     'mock-fs': '^3.8.0',
     'object-assign': '^4.0.1',
     rewire: '^2.5.1',
     sinon: '^1.17.3',
     through: '^2.3.8',
     tslint: '^3.8.1',
     'walk-sync': '^0.2.6' },
  gitHead: '668ecee86bc9acbf5fc41994802eb263b8b9c4aa',
  dist:
   { shasum: '86feceee719d7a14579ab4486ca3077a1a80a840',
     tarball: 'https://registry.npmjs.org/angular-cli/-/angular-cli-1.0.0-beta.1.tgz' },
  directories: {} }
```

**Comment by rido-min** [comment] 2016-05-10 16:24
have you tried: "run as administrator" ?

**Comment by jgenchik** [comment] 2016-05-10 17:52
When I ran `cmd.exe` "as admin":
After installing `angular-cli` from `npm`, it does not recognize `ng` as a command.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd\

C:\>cd development

C:\development>ng --help
'ng' is not recognized as an internal or external command,
operable program or batch file.

C:\development>npm install -g angular-cli
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in fav
or of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\joeadmin\AppData\Roaming\npm\ng -> C:\Users\joeadmin\AppData\Roaming\np
m\node_modules\angular-cli\bin\ng
angular-cli@1.0.0-beta.1 C:\Users\joeadmin\AppData\Roaming\npm\node_modules\angu
lar-cli
├── ember-cli-string-utils@1.0.0
├── broccoli-source@1.1.0
├── symlink-or-copy@1.1.3
├── exit@0.1.2
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2
.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── opn@4.0.1 (object-assign@4.1.0, pinkie-promise@2.0.1)
├── silent-error@1.0.0 (debug@2.2.0)
├── fs-extra@0.30.0 (path-is-absolute@1.0.0, jsonfile@2.3.0, rimraf@2.5.2, klaw@
1.2.0, graceful-fs@4.1.4)
├── glob@7.0.3 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0
.4, minimatch@3.0.0)
├── shelljs@0.7.0 (interpret@1.0.1, rechoir@0.6.2)
├── resolve@1.1.7
├── broccoli-writer@0.1.1 (rsvp@3.2.1, quick-temp@0.1.5)
├── broccoli-caching-writer@2.2.1 (rimraf@2.5.2, debug@2.2.0, lodash.assign@3.2.
0, rsvp@3.2.1, walk-sync@0.2.6, broccoli-kitchen-sink-helpers@0.2.9, broccoli-pl
ugin@1.1.0)
├── broccoli-funnel@1.0.1 (array-equal@1.0.0, blank-object@1.0.1, path-posix@1.0
.0, rimraf@2.5.2, fs-tree-diff@0.3.1, fast-ordered-set@1.0.2, walk-sync@0.2.6, d
ebug@2.2.0, minimatch@2.0.10, mkdirp@0.5.1, broccoli-plugin@1.2.1)
├── broccoli-concat@2.2.0 (lodash.merge@4.3.5, lodash.omit@4.2.1, minimatch@2.0.
10, lodash.uniq@4.2.1, mkdirp@0.5.1, broccoli-kitchen-sink-helpers@0.2.9, fast-s
ourcemap-concat@0.2.7)
├── leek@0.0.21 (debug@2.2.0, rsvp@3.2.1, lodash.assign@3.2.0, request@2.72.0)
├── broccoli-merge-trees@1.1.1 (rimraf@2.5.2, fs-tree-diff@0.4.4, debug@2.2.0, f
ast-ordered-set@1.0.2, can-symlink@1.0.0, broccoli-plugin@1.2.1)
├── typescript@1.8.10
├── typings@0.8.1 (listify@1.0.0, xtend@4.0.1, wordwrap@1.0.0, archy@1.0.0, mini
mist@1.2.0, any-promise@1.3.0, bluebird@3.3.5, columnify@1.5.4, update-notifier@
0.6.3, typings-core@0.3.1)
├── broccoli@1.0.0-beta.7 (broccoli-slow-trees@2.0.0, copy-dereference@1.0.0, ri
mraf@2.5.2, mime@1.3.4, commander@2.9.0, rsvp@3.2.1, tmp@0.0.28, connect@3.4.1,
findup-sync@0.2.1, broccoli-kitchen-sink-helpers@0.3.1, underscore.string@3.3.4,
 handlebars@4.0.5)
├── lodash@4.12.0
├── systemjs-builder@0.15.16 (source-map@0.5.6, mkdirp@0.5.1, bluebird@3.3.5, sy
stemjs@0.19.27, uglify-js@2.6.2, rollup@0.25.8, traceur@0.0.105, es6-template-st
rings@2.0.0, babel-core@6.8.0, babel-plugin-transform-es2015-modules-systemjs@6.
8.0)
└── ember-cli@2.5.0 (ember-cli-path-utils@1.0.0, ember-cli-is-package-missing@1.
0.0, ember-cli-test-info@1.0.0, clean-base-url@1.0.0, ember-cli-normalize-entity
-name@1.0.0, fs-monitor-stack@1.1.0, broccoli-funnel-reducer@1.0.0, ember-cli-va
lid-component-name@1.0.0, ember-cli-get-component-path-option@1.0.0, escape-stri
ng-regexp@1.0.5, is-git-url@0.2.3, isbinaryfile@2.0.4, broccoli-config-loader@1.
0.0, promise-map-series@0.2.2, rimraf@2.5.2, get-caller-file@1.0.1, filesize@3.3
.0, inflection@1.10.0, exists-sync@0.0.3, tree-sync@1.1.1, bower-endpoint-parser
@0.2.2, broccoli-viz@2.0.1, node-modules-path@1.0.1, through@2.3.8, semver@5.1.0
, node-uuid@1.4.7, broccoli-sane-watcher@1.1.4, amd-name-resolver@0.0.5, debug@2
.2.0, nopt@3.0.6, http-proxy@1.13.2, diff@2.2.2, portfinder@1.0.3, findup@0.1.5,
 temp@0.8.3, rsvp@3.2.1, readline2@0.1.1, morgan@1.7.0, minimatch@3.0.0, configs
tore@2.0.0, merge-defaults@0.2.1, mkdirp@0.5.1, ora@0.2.1, quick-temp@0.1.5, fs-
extra@0.26.7, fs-tree-diff@0.4.4, broccoli-kitchen-sink-helpers@0.3.1, compressi
on@1.6.1, yam@0.0.18, walk-sync@0.2.6, broccoli-config-replace@1.1.2, broccoli-p
lugin@1.2.1, sane@1.3.4, cpr@0.4.2, express@4.13.4, findup-sync@0.2.1, inquirer@
0.12.0, git-repo-info@1.1.2, tiny-lr@0.2.1, ember-router-generator@1.2.1, markdo
wn-it@4.3.0, markdown-it-terminal@0.0.3, testem@1.6.0, ember-cli-broccoli@0.16.9
, ember-cli-preprocess-registry@2.0.0, core-object@0.0.2, bower-config@1.4.0, br
occoli-babel-transpiler@5.5.0, npm@2.14.21, bower@1.7.9)

C:\development>ng
'ng' is not recognized as an internal or external command,
operable program or batch file.

C:\development>ng --version
'ng' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by realsaraf** [comment] 2016-05-10 21:39
Running as admin is not a solution

**Comment by hansl** [comment] 2016-05-11 00:22
Dupe of https://github.com/angular/angular-cli/issues/641.

We know, as long as we use Broccoli there won't be an easy solution.

**Closed by hansl** 2016-05-11 00:22 UTC

**Comment by webia1** [comment] 2016-06-20 07:59
Sorry but Brocolli Plugin causes more problems than it helps,.. :/
