### ISSUE TITLE
--standalone option for ng new CLI command

### ISSUE THREAD

**Issue by gouravkajal** [angular/angular-cli#24706] opened 2023-02-13 14:45 UTC
### Command

new

### Description

Since Angular v14, we have had a new feature called Standalone Components. I recently started using them and they are really very helpful. The only problem I faced was setting up the framework to use Standalone components, like removing the root module, and passing required modules (e.g. RouterModule, HttpClientModule, etc) to bootstrapApplication using importProvidersFrom.

I guess that will be really helpful if we can create a new app itself with these configurations. Let's say we use --standalone with ng new, then no root module should be created, the main.ts file should have bootstrapApplication instead of bootstrapModule, and whatever we need by default should be provided in bootstrapApplication.

### Describe the solution you'd like

Suggested command: **ng new <APP_NAME> --standalone**

**Comment by alan-agius4** [comment] 2023-02-13 14:49
Duplicate of  #23976

**Closed by alan-agius4** 2023-02-13 14:49 UTC
