### ISSUE TITLE
Error during prod build in Angular Cli 

### ISSUE THREAD

**Issue by chetanvaja** [angular/angular-cli#7725] opened 2017-09-17 16:12 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### The log given by the failure.
 94% asset optimization(node:11160) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token: operator (>)
(node:11160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Mention any other details that might be useful.
I can do normal build only build in prod fails with above error. 
greatly appreciate help here. 
While I have read the Promise Then and Catch - I have followed the pattern in my source code every where but exact issue is missing and I cant really build anymore.

**Comment by umarkashmiri** [comment] 2017-09-18 18:55
It works fine when i remove --environment variable. from this command, 
`ng build --target=production --environment=prod `

**Comment by umarkashmiri** [comment] 2017-09-19 03:12
I am getting the same here. Here is the version detail 
![image](https://user-images.githubusercontent.com/1515507/30574247-51f95a4e-9d2b-11e7-95b5-2ec5e263e702.png)
and TSCONFIG

![image](https://user-images.githubusercontent.com/1515507/30574281-6f5b5484-9d2b-11e7-8f65-9ebdb9b2d0f5.png)

**Comment by shrekuu** [comment] 2017-09-19 03:29
This is my angular-cli version info:
![image](https://user-images.githubusercontent.com/3136026/30574585-87f33f2c-9cc0-11e7-8047-5d3d37700a73.png)

This is the exception when I run `ng build --prod`:
![image](https://user-images.githubusercontent.com/3136026/30574577-79846a1a-9cc0-11e7-9a46-a537c9851a2e.png)
This project is created to reproduce this error. I can't fix this one. :'(

**Comment by ilianiv** [comment] 2017-09-19 07:15
Same here with @angular/cli@1.4.2

```
94% asset optimization(node:20368) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token: name (f)
```

**Comment by thekhoi** [comment] 2017-09-19 20:31
I got this error when I included a script file inside the angular-cli.json written in es6.  I converted it to es5 by change 'let' back to 'var' and removing arrow functions.

**Comment by mistory** [comment] 2017-09-20 06:13
Im getting this error when i run `ng build --prod`
``` bash
 95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open
'C:\Users\story\pro\ng-app\node_modules\_@angular_core@4.4.3@@angular\packa
ge.json'
```
The version is:
``` bash
@angular/cli: 1.4.2
node: 7.10.0
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4
```

**Comment by ilianiv** [comment] 2017-09-20 06:39
@thekhoi you are right. I've got a custom script included in `.angular-cli.json` written in es6. Transpiling to es5 fixed the issue with SyntaxError: Unexpected token: name (f) when building with `-prod` flag

**Comment by umarkashmiri** [comment] 2017-09-20 18:04
Yes, one thing is confirmed, this is due to external scripts. I am using bootstrap 4  in my project and it has a dependency on popper.min.js and it is based on es6. I changed my "target": "es2016", in my tsconfig file and it's working now besides a few warnings, still figuring out how to get rid of them.

**Comment by umarkashmiri** [comment] 2017-09-20 18:25
updating to es2016 was still messing up with some of my other libraries and it was not suitable. so what I did, I installed popper.js separately via npm and used umd version which is compatible with es5, and changed the target to es5 again in tsconfig and it solved my problem.

**Comment by rodolfojnn** [comment] 2017-09-28 11:49
Same here. I also use Bootstrap 4 and Pooper.js.

.angular-cli.json
```
...
"scripts": [
    "../node_modules/popper.js/dist/esm/popper.min.js",
    "../node_modules/bootstrap/dist/js/bootstrap.min.js",
  ],
...
```

**Comment by DmitriyPotapov** [comment] 2017-10-09 11:00
> I got this error when I included a script file inside the angular-cli.json written in es6. I converted it to es5 by change 'let' back to 'var' and removing arrow functions.
Thanks, it restore production build for me

**Comment by hiepxanh** [comment] 2017-10-19 09:15
@chetanvaja did you resolve this issue sir ? can you close this if you finished ?

**Comment by Justin-wei** [comment] 2017-10-23 07:59
Hello,

It is still not work with version 1.4.9, any workaround? 

Thanks

**Comment by mrahulreddy** [comment] 2017-10-25 15:12
Same here with @angular/cli@1.4.9

` 94% asset optimization(node:235548) UnhandledPromiseRejectionWarning: Unhandled
 promise rejection (rejection id: 1): SyntaxError: Unexpected token: name (Doubl
eQtyHinge)`

**Comment by PendelinP** [comment] 2017-10-31 09:17
Same here -> working with Bootstrap 4 and Popper.js

**Comment by sunny061** [comment] 2017-11-01 09:26
Facing the same issue in @angular/cli@1.4.9 when trying to user Bootstrap with Popper.js in my Angular app.

**Comment by umarkashmiri** [comment] 2017-11-01 11:31
@sunny061 Use the solution i mentioned

**Comment by sunny061** [comment] 2017-11-01 16:13
@umarkashmiri I've temporarily solved the problem by downgrading the angular cli to 1.3.2 as mentioned in this answer. https://stackoverflow.com/a/46330054/1874266

**Comment by filipesilva** [comment] 2017-11-04 18:18
This type of error occurs when you try to use ES2015 vendor code with a ES5 app. It was addressed when we added ES2105 support in https://github.com/angular/angular-cli/pull/7610.

**Closed by filipesilva** 2017-11-04 18:18 UTC
Labels: priority: 2 (required), severity3: broken

**Comment by PendelinP** [comment] 2017-12-05 15:23
I found a solution: https://stackoverflow.com/a/47654981/1820522

**Comment by umarkashmiri** [comment] 2017-12-05 15:51
@PendelinP this is what I mentioned above.
https://github.com/angular/angular-cli/issues/7725#issuecomment-330939271

**Comment by rkkoszewski** [comment] 2017-12-13 08:53
I have the same issue. I'm not using Bootstrap nor popper.js. As this issue post has been closed, I suppose this has been fixed. But where and how? My "target" is "es5" while my "lib" is "es2017". Could this be the issue? Changing es5 to es2017 yields the same result. Any help or fix?

**Comment by darrenjs** [comment] 2017-12-17 00:38
I have similar issue when running "./ng build --prod' for ng version 1.5.2

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token: name (Commented)`

I've tracked the problem to the include of a particular script via the `.angular-cli.json`, I have this :

            "scripts": [
                "../libs/autobahn-js-built-17.5.2/autobahn.js"
            ],

... and further, I suspect the error happens during the minification stage (when uglifyjs would be invoked).  I can't seem to find any way to get further logging / diagnostics from `ng` , (I tried `--verbose` but just gives mainly timing stats, rather information on what sub programs are being invoked etc)
