### ISSUE TITLE
angular-cli-builds

### ISSUE THREAD

**Issue by fxck** [angular/angular-cli#3918] opened 2017-01-09 15:27 UTC
Could you please create per-commit releases similar to the main repo or material2?

**Comment by Meligy** [comment] 2017-01-09 15:29
Related discussion here https://github.com/angular/angular-cli/issues/3127

Quite unlikely in the short term I'm afraid.

**Comment by filipesilva** [comment] 2017-01-09 15:37
Dupe of https://github.com/angular/angular-cli/issues/3127 as meligy mentioned.

**Closed by filipesilva** 2017-01-09 15:37 UTC
