### ISSUE TITLE
Two head tags are created in dist/index.html file.

### ISSUE THREAD

**Issue by vjayanth** [angular/angular-cli#9329] opened 2018-01-23 09:15 UTC
after running ng build --prod --build-optimizer, two head tags are created in dist/index.html.

dist/index.html code

```
<!doctype html>
<html lang="en">

    <head>
        <link href="styles.90ab85c80ca66149196a.bundle.css" rel="stylesheet" />
    </head>

    <head>
        <meta charset="utf-8">
        <title>MobilesiteEcommerce</title>
        <base href="/">
        <meta name="viewport" content="width=device-width,maximum-scale=1,minimum-scale=1,initial-scale=1,user-scalable=no,shrink-to-fit=no">
        <link rel="stylesheet" href="https://use.typekit.net/tws5qsj.css">
        <link rel="icon" type="image/x-icon" href="assets/images/favicon.png">

        <body>
            <app-root>
                <div class="text-center loading-screen position-relative">
                    <figure><img src="assets/images/img-page-loader.gif" alt=""></figure>
                </div>
            </app-root>
            <script type="text/javascript" src="inline.44bffd0334ee9c25f017.bundle.js"></script>
            <script type="text/javascript" src="polyfills.abdf53ca655716e505e0.bundle.js"></script>
            <script type="text/javascript" src="scripts.4aa02c2ef0bfbe906c22.bundle.js"></script>
            <script type="text/javascript" src="main.bb86da637b1fef37c528.bundle.js"></script>
        </body>
    </head>

</html>
```
this was causing error [issue link](https://github.com/angular/angular-cli/issues/9110)

**Comment by mgechev** [comment] 2019-08-19 20:22
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:22 UTC
Labels: comp: devkit/build-angular, freq1: low, severity1: confusing, type: bug/fix
