### ISSUE TITLE
@angular-devkit/build-angular:jest creates invalid test suite

### ISSUE THREAD

**Issue by rafagsiqueira** [angular/angular-cli#25189] opened 2023-05-11 11:56 UTC
### Command

test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Running tests using ng test <project name> with the new @angular-devkit/build-angular:jest builder results always in at least one failed test suite:
 ```
FAIL  dist/test-out/StandardController-QMDYSHA5.mjs
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (../../node_modules/@jest/core/build/TestScheduler.js:133:18)
      at ../../node_modules/@jest/core/build/TestScheduler.js:254:19
      at ../../node_modules/emittery/index.js:363:13
          at Array.map (<anonymous>)
      at Emittery.emit (../../node_modules/emittery/index.js:361:23)
```
Perhaps is just a matter of adding an extra testPathIgnorePattern similar to this one?
https://github.com/angular/angular-cli/blob/35d239e9376277e50cee8c83b2e7a90626ec941d/packages/angular_devkit/build_angular/src/builders/jest/index.ts#L114

### Minimal Reproduction

ng test <project name>

### Your Environment

```text
Angular CLI: 16.0.0
Node: 18.16.0
Package Manager: yarn 3.5.0
OS: darwin x64

Angular: 16.0.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0-rc.1
@angular/cdk                    16.0.0
@angular/cli                    16.0.0
@angular/flex-layout            15.0.0-beta.42
@angular/material               16.0.0
@angular/pwa                    16.0.0
@schematics/angular             16.0.0
ng-packagr                      16.0.1
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by dgp1130** [comment] 2023-05-11 16:32
This is interesting, where does `StandardController` come from? Is that a file name in your application?

I was under the impression ESBuild always generated shared chunks in `chunk-*.mjs` files, but maybe that's not strictly accurate.

**Comment by rafagsiqueira** [comment] 2023-05-11 17:18
It's not. It was generated by the ESBuild.

**Comment by dplarina** [comment] 2023-05-24 16:41
I have this issue as well. It seems to be components that are lazy loaded using the await import('./my-component-dialog.component').then((m) => m.MyComponentDialogComponent);

So the repro for this:
- Create ComponentA
- Create a service that lazy loads ComponentA using import()
- Create ComponentB that injects the service
- In the ComponentB spec, import the service as a provider.
- Include only ComponentB the includes under options for @angular-devkit/build-angular:jest

ESBuild will build the ComponentB spec, and ComponentA. Since the option to provide filtering to jest is not available we cannot tell jest to ignore ComponentA.

I created a repro repository. https://github.com/dplarina/angular-esbuild-jest-repro
When you run `ng test` you will see the problem.

Jest output
```
NOTE: The Jest builder is currently EXPERIMENTAL and not ready for production use.
The esbuild-based browser application builder ('browser-esbuild') is currently in developer preview and is not yet recommended for production use. For additional information, please see https://angular.io/guide/esbuild



Application bundle generation complete. [2.945 seconds]
(node:11504) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  dist/test-out/component-a.component-HN52MMGZ.mjs
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (../../node_modules/@jest/core/build/TestScheduler.js:133:18)
          at Array.map (<anonymous>)

(node:21344) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 PASS  dist/test-out/component-b.component.spec.mjs
  ● Console

    console.log
      ComponentAComponent loaded

      at src/app/component-b/component-b.component.ts:18:13


Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.225 s
Ran all test suites.
```

You can see in the dist/test-out folder that it generated component-a.component-HN52MMGZ.mjs even though it was not included
![image](https://github.com/angular/angular-cli/assets/1740636/170f1ee6-e3f4-4cf4-b556-6f0d89864177)

HTH

**Comment by gultyayev** [comment] 2023-06-12 10:14
> This is interesting, where does StandardController come from? Is that a file name in your application?

I got the exact same issue. By looking at the contents it looks like it's caused by importing of `MsalService` in a test suite to override the provider.

I use `@azure/msal-angular` & `@azure/msal-browser` 3.0.0-alpha.2 if it makes any difference

**Comment by gultyayev** [comment] 2023-06-12 10:17
To me the solution would seem to add a pattern of `.(spec|test).ts` for running tests. This would eliminate any non-tests generated files from running the tests over.

**Comment by gultyayev** [comment] 2023-06-16 18:33
I found the root cause. The bug can be easily fixed by changing the glob (to "<rootDir>/**/*.spec.mjs") for running the tests in packages/angular_devkit/build_angular/src/builders/jest/index.ts.

<img width="900" alt="image" src="https://github.com/angular/angular-cli/assets/22374911/f0bf3b19-3b0c-4958-9a98-1020c796d6a3">

This may in turn cause issues running tests with suffix different from `spec`.

**Comment by dgp1130** [comment] 2023-06-20 20:30
> To me the solution would seem to add a pattern of `.(spec|test).mjs` for running tests. This would eliminate any non-tests generated files from running the tests over.

Users can customize the file filter and I'd rather not transform it to align with `--testMatch` semantics if we can avoid it. I think the problem here is that ESBuild is retaining the file name for dynamic imported chunks, rather than calling them `chunk-*.mjs`, making it hard to exclude those files deterministically. The ideal solution is to make it stop doing that. I suspect the right way of doing this is to set [`--chunk-names`](https://esbuild.github.io/api/#chunk-names) in ESBuild to enforce the `chunk-*.mjs` convention or put them in a subfolder which gets excluded. I'll have to give it a try and see if that fixes the problem here.

**Comment by gultyayev** [comment] 2023-06-21 08:14
Yes. Going to `bundler-context.js` and setting `chunkNames: 'chunk-[hash]'` for esbuild config does fix the issue.

**Closed** 2023-07-14 21:50 UTC
Labels: type: bug/fix, freq1: low, severity3: broken, area: devkit/build-angular, devkit/build-angular: jest
