### ISSUE TITLE
Multiple module directories inside src directory

### ISSUE THREAD

**Issue by charitharumapperuma** [angular/angular-cli#1561] opened 2016-08-05 09:20 UTC
Windows 10
angular-cli: 1.0.0-beta.10
node: 4.4.4
os: win32 x64

Repro steps-
Add a sub directory inside src. 
E.g. if src/core is added directory structure should be,
```
NgProject
    src/
        app/
        core/
```
Run "ng g component ..\core\header" inside project directory (in this case "NgProject")
And I get the error,
Invalid path: "..\core\header" cannot be above the "src\app" directory

I think this happens because Angular CLI supports creating directories, services, etc. only inside `src/app` directory. Check [this line of code](https://github.com/angular/angular-cli/blob/master/addon/ng2/utilities/dynamic-path-parser.js#L7), and hard-coded "app" at the end of the line.

I believe this is mostly a feature request, as it would be a good practice to separate core logic from application logic in large apps.

Also, moving "app" parameter to the configuration file seems appropriate.

**Comment by Vayrex** [comment] 2016-08-09 16:11
They told that they are in need of something similar.
https://github.com/angular/angular-cli/issues/761

**Comment by filipesilva** [comment] 2016-08-16 04:25
Dupe of https://github.com/angular/angular-cli/issues/761. We aim to implement this in the future, but have no details to share now.

**Closed by filipesilva** 2016-08-16 04:25 UTC

**Comment by AbdallahBedir** [comment] 2016-12-07 06:53
It's not a good idea to generate feature module inside "app" folder ?! 
I need to generate a new module in "src" folder but instead it generated in "app" -_-
