### ISSUE TITLE
AOT Build fails

### ISSUE THREAD

**Issue by montella1507** [angular/angular-cli#2734] opened 2016-10-16 22:05 UTC
Windows 10,

Version: beta17 + @ngtools/webpack 1.1.0
ng build --aot=true

Log:
ENOENT: no such file or directory, stat 'v:\mediware\fixrepo\allimp-web\Source\Renewal\src\app\main\main.module'
Error: ENOENT: no such file or directory, stat 'v:\mediware\fixrepo\allimp-web\Source\Renewal\src\app\main\main.module'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at _symbolImportLookup (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\@ngtools\webpack\src\entry_resolver.js:103:28)
    at Object.resolveEntryModuleFromMain (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\@ngtools\webpack\src\entry_resolver.js:148:18)
    at AotPlugin._setupOptions (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\@ngtools\webpack\src\plugin.js:105:77)
    at new AotPlugin (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\@ngtools\webpack\src\plugin.js:34:14)
    at Object.exports.getWebpackAotConfigPartial (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\angular-cli\models\webpack-build-typescript.js:57:13)
    at new NgCliWebpackConfig (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\angular-cli\models\webpack-config.js:18:42)
    at Class.run (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\angular-cli\tasks\build-webpack.js:17:22)
    at Class.run (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\angular-cli\commands\build.js:50:26)
    at Class.<anonymous> (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\angular-cli\lib\models\command.js:152:17)
    at tryCatch (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\rsvp\dist\lib\rsvp\-internal.js:215:12)
    at invokeCallback (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\rsvp\dist\lib\rsvp\-internal.js:230:13)
    at v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\rsvp\dist\lib\rsvp\then.js:29:16
    at flush (v:\mediware\fixrepo\allimp-web\Source\Renewal\node_modules\rsvp\dist\lib\rsvp\asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

All of the mentioned files exist

**Comment by Meligy** [comment] 2016-10-16 23:48
Can you please create a repository that shows the problem?

I have AoT issues shown here:
https://github.com/meligy/routing-angular-cli

But it's browser issues not build issues.

**Comment by montella1507** [comment] 2016-10-17 00:13
Ah i think i have fixed the problem and its super silly....

Not working:
`
//main.ts
import { MainModule } from './app/main/main.module'  //point to main.module.ts;
`

Working:
`
//main.ts
import { MainModule } from './app/main'  //point to index.ts with export * from "./main.module".
`

**Comment by Meligy** [comment] 2016-10-17 00:15
So, did you get AoT to work for you completely?

If so, can you please share how your app routes look like?

Thanks.

**Comment by montella1507** [comment] 2016-10-17 00:27
Well.. it has nothing to do with routing... it is build process. There must be a bug in Path resolution in the build process. 

If i use index.ts (barel file) it works, if i import main module directly:

`
import { MainModule }   from './main/main.module';
`
it doesnt.

**Comment by Meligy** [comment] 2016-10-17 00:34
I get that. I mean. Are you able to serve the app in the browser now with aot?

Something like:

```
ng serve --aot
```

Without errors in browser console?

**Comment by montella1507** [comment] 2016-10-17 00:56
no.

`nhandled Promise rejection: Cannot read property 'replace' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'replace' of undefined
    at Function.StringWrapper.replaceAll (http://localhost:4200/main.bundle.js:5085:17)
    at _flattenStyles (http://localhost:4200/main.bundle.js:19269:89)
    at new DomRenderer (http://localhost:4200/main.bundle.js:19064:24)
    at DomRootRenderer_.DomRootRenderer.renderComponent (http://localhost:4200/main.bundle.js:19035:24)
    at DebugDomRootRenderer.renderComponent (http://localhost:4200/main.bundle.js:38599:52)
    at ViewUtils.renderComponent (http://localhost:4200/main.bundle.js:2747:31)
    at _View_PortalComponent0.AppView (http://localhost:4200/main.bundle.js:2289:39)
    at new _View_PortalComponent0 (http://localhost:4200/main.bundle.js:51792:16)
    at viewFactory_PortalComponent0 (http://localhost:4200/main.bundle.js:51964:12)
    at _View_PortalComponent_Host0.createInternal (http://localhost:4200/main.bundle.js:51758:26) TypeError: Cannot read property 'replace' of undefined
    at Function.StringWrapper.replaceAll (http://localhost:4200/main.bundle.js:5085:17)
    at _flattenStyles (http://localhost:4200/main.bundle.js:19269:89)
    at new DomRenderer (http://localhost:4200/main.bundle.js:19064:24)
    at DomRootRenderer_.DomRootRenderer.renderComponent (http://localhost:4200/main.bundle.js:19035:24)
    at DebugDomRootRenderer.renderComponent (http://localhost:4200/main.bundle.js:38599:52)
    at ViewUtils.renderComponent (http://localhost:4200/main.bundle.js:2747:31)
    at _View_PortalComponent0.AppView (http://localhost:4200/main.bundle.js:2289:39)
    at new _View_PortalComponent0 (http://localhost:4200/main.bundle.js:51792:16)
    at viewFactory_PortalComponent0 (http://localhost:4200/main.bundle.js:51964:12)
    at _View_PortalComponent_Host0.createInternal (http://localhost:4200/main.bundle.js:51758:26)`

**Comment by montella1507** [comment] 2016-10-17 00:57
but thats a known bug:

http://stackoverflow.com/a/40040036

**Comment by montella1507** [comment] 2016-10-17 01:05
Yeah it works. I just had to remove ViewEncapsulation.None, because AOT has problems with that. But it works perfectly.

**Comment by montella1507** [comment] 2016-10-17 01:40
ah it looks i have very similar problem to this #https://github.com/angular/angular-cli/issues/2577
but different way how to simulate

**Comment by filipesilva** [comment] 2016-10-17 21:52
Dupe of https://github.com/angular/angular-cli/issues/2577 I think. The same root cause at least. I'll close this one in favor of that, it here more info on it. I'll add your repro steps there as well.

**Closed by filipesilva** 2016-10-17 21:52 UTC
