### ISSUE TITLE
Scss import error at compilation since Angular 17

### ISSUE THREAD

**Issue by tleveque23** [angular/angular-cli#27177] opened 2024-02-28 18:11 UTC
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.x

### Description

Since upgrading my project to v17.x and migrating to use Vite (using the command ng update @angular/cli --name=use-application-builder), I have the following error(s) when building:
```
[ERROR] Can't find stylesheet to import.
  ╷
1 │ @import "assets/scss/variables";
  │         ^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/app/app.component.scss 1:9  root stylesheet [plugin angular-sass]
```
This is easily reproducible with a brand new project.
You can see the bug with the following project:
https://github.com/tleveque23/testScssImport

I already check all similar bugs but none seem similar to this one.

### Minimal Reproduction

https://github.com/tleveque23/testScssImport

### Exception or Error

```text
[ERROR] Can't find stylesheet to import.
  ╷
1 │ @import "assets/scss/variables";
  │         ^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/app/app.component.scss 1:9  root stylesheet [plugin angular-sass]
```

### Your Environment

```text
Angular CLI: 17.2.1
Node: 20.11.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 17.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.1
@angular-devkit/build-angular   17.2.1
@angular-devkit/core            17.2.1
@angular-devkit/schematics      17.2.1
@angular/cli                    17.2.1
@schematics/angular             17.2.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by clydin** [comment] 2024-02-28 18:24
Duplicate of #26848

**Closed by clydin** 2024-02-28 18:24 UTC
