### ISSUE TITLE
har-validator@5.1.5: this library is no longer supported

### ISSUE THREAD

**Issue by ISMIALKHAN17** [angular/angular-cli#20992] opened 2021-05-29 23:33 UTC
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

getting this error please help

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment] 2021-05-30 06:42
Duplicate of https://github.com/angular/angular-cli/issues/20994

**Closed by alan-agius4** 2021-05-30 06:42 UTC
