### ISSUE TITLE
ng new <projectName> installs non-existent node-sass

### ISSUE THREAD

**Issue by yasinallana** [angular/angular-cli#14332] opened 2019-05-03 10:34 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```
### Description

upon running `ng new <projectName>` the project structure is created and install works up until the point of installing node-sass during post script. the `ng new` command seems to be installing a non-existent version  of node-sass, **v4.11.0/darwin-x64-72_binding.node** to be exact. Upon manually visiting the [url](https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node) via the browser it is indeed a 404 not found error

## 🔥 Exception or Error
<pre><code>
> node-sass@4.11.0 install /Users/devuser/Developement/Web/AngularProjects/tested/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.11.0 postinstall /Users/devuser/Developement/Web/AngularProjects/tested/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/build.js
</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 12.1.0
OS: darwin x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Comment by maheshnathwani** [comment] 2019-05-04 08:47
I'm also getting the same issue

**Comment by maheshnathwani** [comment] 2019-05-04 08:53
I figured out, node-sass@4.11 doesn't support node v12, downgrading it to <=11 would solve the problem

**Comment by yasinallana** [comment] 2019-05-04 09:09
> I figured out, node-sass@4.11 doesn't support node v12, downgrading it to <=11 would solve the problem

Yes agreed , that is one solution

**Comment by alan-agius4** [comment] 2019-05-07 07:08
Duplicate of https://github.com/angular/angular-cli/issues/14339

**Closed by alan-agius4** 2019-05-07 07:08 UTC
