### ISSUE TITLE
Build Timing addition in build logs

### ISSUE THREAD

**Issue by codebriefcase** [angular/angular-cli#18762] opened 2020-09-11 11:56 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...
If we run any Angular project through ng-serve, we see an output log in the console stating the chunk, date, time and status.
But the problem is, when we make too frequent changes and it Angular CLI continues to serve the changes automatically; it becomes difficult to trace if our recent changes have been served or not. Let me explain it through an example -
I am making some changes to my css/html file. Everytime I edit my file and view the changes in my browser. The changes in the code are very few, so it wont take much time for cli to build the app. So as soon as i made the changes, they got reflected. Now if I switch to my terminal to view the status of my build, it will be somewhat inconvenient for me to figure out if my code got build or not, because there are a lot of other build logs too.

Another point here is that the console log contains date field which is too detailed and serves a different purpose.
There should be some easy way to track when this build happened.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
We can add some details like - Served xx seconds/minutes/hours ago either for the most recent build or all builds.
I am attaching a screenshot of current log along with the expected.
![Capture](https://user-images.githubusercontent.com/61384771/92922634-c4d55680-f453-11ea-9ad3-c2f178c8ead3.PNG)

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment] 2020-09-11 13:17
Thanks for the excellent report.

This is however a duplicate of https://github.com/angular/angular-cli/issues/16741 and displaying date in ISO format is preferred and intentional.

**Closed by alan-agius4** 2020-09-11 13:17 UTC
Labels: comp: devkit/build-angular, freq1: low, severity2: inconvenient, type: bug/fix
