### ISSUE TITLE
Unable to install Angular-cli

### ISSUE THREAD

**Issue by kam2001** [angular/angular-cli#3322] opened 2016-11-30 13:02 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and node => v7.2.0
npm => 3.10.9

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
e_modules\.staging\fstream-ignore-4b18af0c\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cookie-signature@1.0.6 (node_mod
ules\angular-cli\node_modules\cookie-signature):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\cookie-signa
ture-c1ef148c\package.json.1216519259' -> 'C:\Users\Matthew\AppData\Roaming\npm\
node_modules\.staging\cookie-signature-c1ef148c\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: assert-plus@1.0.0 (node_modules\
angular-cli\node_modules\sshpk\node_modules\assert-plus):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\assert-plus-
039d73ea\package.json.2746914917' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_
modules\.staging\assert-plus-039d73ea\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@0.0.1 (node_modules\angu
lar-cli\node_modules\duplexer2\node_modules\isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\isarray-d3c1
9c92\package.json.1861600888' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modu
les\.staging\isarray-d3c19c92\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: flatten@1.0.2 (node_modules\angu
lar-cli\node_modules\flatten):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\flatten-5bfb
179c\package.json.3586841460' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modu
les\.staging\flatten-5bfb179c\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: block-stream@0.0.9 (node_modules
\angular-cli\node_modules\block-stream):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\block-stream
-b048db39\package.json.2406798194' -> 'C:\Users\Matthew\AppData\Roaming\npm\node
_modules\.staging\block-stream-b048db39\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: amdefine@1.0.0 (node_modules\ang
ular-cli\node_modules\remap-istanbul\node_modules\amdefine):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\amdefine-4d4
a6635\package.json.3247908622' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_mod
ules\.staging\amdefine-4d4a6635\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uid-number@0.0.6 (node_modules\a
ngular-cli\node_modules\uid-number):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\uid-number-c
0da5560\package.json.54373274' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_mod
ules\.staging\uid-number-c0da5560\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: caseless@0.11.0 (node_modules\an
gular-cli\node_modules\caseless):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\caseless-2ae
231bb\package.json.3735000949' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_mod
ules\.staging\caseless-2ae231bb\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-to-regexp@0.1.7 (node_modul
es\angular-cli\node_modules\path-to-regexp):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\path-to-rege
xp-b95a1286\package.json.3835182277' -> 'C:\Users\Matthew\AppData\Roaming\npm\no
de_modules\.staging\path-to-regexp-b95a1286\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wbuf@1.7.2 (node_modules\angular
-cli\node_modules\wbuf):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\wbuf-2a163f3
3\package.json.3365972470' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modules
\.staging\wbuf-2a163f33\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: jsprim@1.3.1 (node_modules\angul
ar-cli\node_modules\jsprim):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\jsprim-bd205
922\package.json.136474344' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_module
s\.staging\jsprim-bd205922\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mute-stream@0.0.4 (node_modules\
angular-cli\node_modules\readline2\node_modules\mute-stream):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\mute-stream-
b2d36a15\package.json.3973343458' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_
modules\.staging\mute-stream-b2d36a15\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: indexof@0.0.1 (node_modules\angu
lar-cli\node_modules\indexof):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\indexof-3154
01ca\package.json.2384422093' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modu
les\.staging\indexof-315401ca\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: array-equal@1.0.0 (node_modules\
angular-cli\node_modules\array-equal):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\array-equal-
894181ba\package.json.3764219443' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_
modules\.staging\array-equal-894181ba\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: graceful-readlink@1.0.1 (node_mo
dules\angular-cli\node_modules\graceful-readlink):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\graceful-rea
dlink-4cb917fa\package.json.716437058' -> 'C:\Users\Matthew\AppData\Roaming\npm\
node_modules\.staging\graceful-readlink-4cb917fa\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: indexes-of@1.0.1 (node_modules\a
ngular-cli\node_modules\indexes-of):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\indexes-of-2
c59b435\package.json.1191507917' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_m
odules\.staging\indexes-of-2c59b435\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-browserify@0.2.1 (node_module
s\angular-cli\node_modules\os-browserify):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\os-browserif
y-fb413ccb\package.json.3015661050' -> 'C:\Users\Matthew\AppData\Roaming\npm\nod
e_modules\.staging\os-browserify-fb413ccb\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: browserify-rsa@4.0.1 (node_modul
es\angular-cli\node_modules\browserify-rsa):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\browserify-r
sa-72588f2c\package.json.2279921751' -> 'C:\Users\Matthew\AppData\Roaming\npm\no
de_modules\.staging\browserify-rsa-72588f2c\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.1 (node_modules\angular-
cli\node_modules\sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\sax-a9856468
\package.json.3785908420' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\
.staging\sax-a9856468\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.1 (node_modules\ang
ular-cli\node_modules\util\node_modules\inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\inherits-804
ca555\package.json.3271424176' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_mod
ules\.staging\inherits-804ca555\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: broccoli-kitchen-sink-helpers@0.
3.1 (node_modules\angular-cli\node_modules\broccoli-kitchen-sink-helpers):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\broccoli-kit
chen-sink-helpers-59d0dbc2\package.json.836668045' -> 'C:\Users\Matthew\AppData\
Roaming\npm\node_modules\.staging\broccoli-kitchen-sink-helpers-59d0dbc2\package
.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: defaults@1.0.3 (node_modules\ang
ular-cli\node_modules\defaults):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\defaults-11e
be0f8\package.json.4080137306' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_mod
ules\.staging\defaults-11ebe0f8\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@1.0.7 (node
_modules\angular-cli\node_modules\process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\process-next
ick-args-762c423c\package.json.575347761' -> 'C:\Users\Matthew\AppData\Roaming\n
pm\node_modules\.staging\process-nextick-args-762c423c\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@0.7.1 (node_modules\angular-c
li\node_modules\ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\ms-c19b8f78\
package.json.3068959934' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.
staging\ms-c19b8f78\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-posix@1.0.0 (node_modules\a
ngular-cli\node_modules\path-posix):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\path-posix-1
49aa24e\package.json.1324971859' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_m
odules\.staging\path-posix-149aa24e\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npmlog@4.0.1 (node_modules\angul
ar-cli\node_modules\npmlog):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\npmlog-8b143
8c1\package.json.273950345' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_module
s\.staging\npmlog-8b1438c1\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sigmund@1.0.1 (node_modules\angu
lar-cli\node_modules\sigmund):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\sigmund-4105
8215\package.json.3452545886' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modu
les\.staging\sigmund-41058215\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: can-symlink@1.0.0 (node_modules\
angular-cli\node_modules\can-symlink):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\can-symlink-
3fed0e63\package.json.3066682654' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_
modules\.staging\can-symlink-3fed0e63\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: browserslist@1.4.0 (node_modules
\angular-cli\node_modules\browserslist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\browserslist
-bb5620dd\package.json.780592357' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_
modules\.staging\browserslist-bb5620dd\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: regjsparser@0.1.5 (node_modules\
angular-cli\node_modules\regjsparser):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\regjsparser-
16f07919\package.json.691151684' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_m
odules\.staging\regjsparser-16f07919\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: stringstream@0.0.5 (node_modules
\angular-cli\node_modules\stringstream):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\stringstream
-d3b863f9\package.json.383668146' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_
modules\.staging\stringstream-d3b863f9\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: tapable@0.1.10 (node_modules\ang
ular-cli\node_modules\ts-loader\node_modules\tapable):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\tapable-2f8a
5609\package.json.4265711852' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modu
les\.staging\tapable-2f8a5609\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: jsbn@0.1.0 (node_modules\angular
-cli\node_modules\jsbn):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\jsbn-a436ff1
6\package.json.1581474630' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modules
\.staging\jsbn-a436ff16\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: multipipe@0.1.2 (node_modules\an
gular-cli\node_modules\multipipe):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\multipipe-bb
c07720\package.json.366723464' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_mod
ules\.staging\multipipe-bbc07720\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cryptiles@2.0.5 (node_modules\an
gular-cli\node_modules\cryptiles):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\cryptiles-4a
92bd12\package.json.933149204' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_mod
ules\.staging\cryptiles-4a92bd12\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: slide@1.1.6 (node_modules\angula
r-cli\node_modules\slide):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\slide-d31fc1
fe\package.json.442851809' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modules
\.staging\slide-d31fc1fe\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uc.micro@1.0.3 (node_modules\ang
ular-cli\node_modules\uc.micro):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\uc.micro-71c
9d2d5\package.json.3273535437' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_mod
ules\.staging\uc.micro-71c9d2d5\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rimraf@2.2.8 (node_modules\angul
ar-cli\node_modules\quick-temp\node_modules\rimraf):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\rimraf-92b47
c08\package.json.3937087682' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modul
es\.staging\rimraf-92b47c08\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: toposort@1.0.0 (node_modules\ang
ular-cli\node_modules\toposort):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\toposort-ebb
49720\package.json.2907829876' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_mod
ules\.staging\toposort-ebb49720\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimatch@0.3.0 (node_modules\an
gular-cli\node_modules\jasmine\node_modules\minimatch):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\minimatch-96
3a01d5\package.json.2487713659' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_mo
dules\.staging\minimatch-963a01d5\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ipaddr.js@1.1.1 (node_modules\an
gular-cli\node_modules\ipaddr.js):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\ipaddr.js-a7
1a3df8\package.json.2838616911' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_mo
dules\.staging\ipaddr.js-a71a3df8\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: in-publish@2.0.0 (node_modules\a
ngular-cli\node_modules\in-publish):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\in-publish-4
40c173c\package.json.1588191221' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_m
odules\.staging\in-publish-440c173c\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utila@0.4.0 (node_modules\angula
r-cli\node_modules\utila):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\utila-42033f
bd\package.json.1945993431' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_module
s\.staging\utila-42033fbd\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.0.3 (node_modules\angul
ar-cli\node_modules\agent-base\node_modules\semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\semver-4c28c
99b\package.json.1658993363' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modul
es\.staging\semver-4c28c99b\package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uuid@3.0.1 (node_modules\angular
-cli\node_modules\request\node_modules\uuid):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory,
 rename 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\uuid-f3d738f
3\package.json.376814675' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\
.staging\uuid-f3d738f3\package.json'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "-f" "angular-cli"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! path C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\minimal
istic-assert-ec64ef6b\package.json.1281385208
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Matthew\AppD
ata\Roaming\npm\node_modules\.staging\minimalistic-assert-ec64ef6b\package.json.
1281385208' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\minim
alistic-assert-ec64ef6b\package.json'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Matthew\AppD
ata\Roaming\npm\node_modules\.staging\minimalistic-assert-ec64ef6b\package.json.
1281385208' -> 'C:\Users\Matthew\AppData\Roaming\npm\node_modules\.staging\minim
alistic-assert-ec64ef6b\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\System32\npm-debug.log
npm ERR! code 1

C:\WINDOWS\System32>

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gelliott181** [comment] 2016-12-01 20:11
Node >=7.0.0 is currently unsupported due to breaking changes, try it with Node 6.9.1.

**Comment by kam2001** [comment] 2016-12-02 10:16
I tried as you suggested by doing cache clean but still the same issue, even tried with with and without -f flag,  with and without administrator cmd . I can install everything else globally eg Typescript, protractorbut this issue only comes up with angular-cli

**Comment by filipesilva** [comment] 2016-12-30 10:58
Dupe of https://github.com/angular/angular-cli/issues/1190. The lib at which it fails is different, but it's essentially the same problem. We don't know why happens either but it's an NPM issue for sure.

**Closed by filipesilva** 2016-12-30 10:58 UTC

**Comment by mitulparekh90** [comment] 2017-08-20 02:27
I am having the same error with npm 3.8.5, node 8.4.0.

**Comment by stevematdavies** [comment] 2018-03-22 15:01
Same on mac node 7 8 9
