### ISSUE TITLE
Library2project @angular-devkit/build-angular:dev-server 14.1.2 not reloading node_modules within project

### ISSUE THREAD

**Issue by pelord** [angular/angular-cli#23960] opened 2022-09-26 17:46 UTC
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.x

### Description

I'm using @angular-devkit/build-angular:dev-server 14.1.2 . I was told, this is webpack running behind.

Here my setup:
I'm developping a lib, (igo2-lib) and a related sub project (igo2) using the lib components.

In a dev mode, I edit my libs, I build and copy the dist folder from the lib to the igo2/node_modules/https://github.com/igo2 directory.

Previously, my changes were applied to the started instance. Webpack was detecting the changes.

Do you know to allow webpack to reload with the new node_modules applied?

### Minimal Reproduction

Try IGO2-LIB with IGO2 project (on next branch) to test

https://github.com/infra-geo-ouverte/igo2/
https://github.com/infra-geo-ouverte/igo2-lib/

In a dev mode, edit lib, build and copy the dist folder from the lib to the igo2/node_modules/https://github.com/igo2 directory.
On the first start, the content is change.. but if you edit again the node_modules content, the changes do not appear. 

### Your Environment

```text
Angular CLI: 14.1.2
Node: 16.16.0
Package Manager: npm 8.14.0
OS: win32 x64

Angular: 14.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.2
@angular-devkit/build-angular   14.1.2
@angular-devkit/core            13.3.8
@angular-devkit/schematics      13.3.8
@angular/cdk                    14.2.2
@schematics/angular             14.1.2
ng-packagr                      14.1.0
rxjs                            7.5.6
typescript                      4.6.4
webpack                         5.74.0
```

**Comment by alan-agius4** [comment] 2022-09-26 18:00
Duplicate of https://github.com/angular/angular-cli/issues/22104

**Closed by alan-agius4** 2022-09-26 18:00 UTC

**Comment by pelord** [comment] 2022-09-26 18:09
Thanks. Ok it's a duplicate but the issue is still pending.. no solution found ;(

**Comment by pelord** [comment] 2022-09-26 19:49
@mikerentmeister any updates?

**Comment by pelord** [comment] 2022-09-27 13:00
@alan-agius4 The issue https://github.com/angular/angular-cli/issues/22104 is lock and I can't post that your solution do not work on my project ;( What should I do?
