### ISSUE TITLE
Prod build should not contain any comments.

### ISSUE THREAD

**Issue by Anufriev** [angular/angular-cli#6072] opened 2017-04-25 07:59 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64

### Repro steps.
ng build --prod --env=prod --aot=true

### Actual functionality. 
Builded scripts contain a lot of comments. 

### Desired functionality.
I want to get the smallest size of build as possible.

### Mention any other details that might be useful.

![image](https://cloud.githubusercontent.com/assets/1809671/25374491/5051edd0-29a6-11e7-9ea8-7a85e88096df.png)

**Comment by sumitarora** [comment] 2017-04-25 14:27
Closing Duplicate of https://github.com/angular/angular-cli/issues/4413

**Closed by sumitarora** 2017-04-25 14:27 UTC
