### ISSUE TITLE
Unable to find any apps in `.angular-cli.json`

### ISSUE THREAD

**Issue by wasifale** [angular/angular-cli#7604] opened 2017-09-05 17:54 UTC
I've followed these steps
`npm install -g @angular-cli`
`ng new project-name`

then copy that project into a new directory and ran the command
`ng g component cmp-name`
and got the error 

> Unable to find any apps in `.angular-cli.json`.

I have followed #6503 , #5616 and #5661 but didn't get any luck cause it's not working.

**Comment by cedvdb** [comment] 2017-09-06 00:32
works fine for me

**Comment by wasifale** [comment] 2017-09-06 05:43
@cedvdb I've tried it at least 3 times still having the same issue.

**Comment by filipesilva** [comment] 2017-09-06 11:09
Heya, can you check if you have other `package.json` or `.angular-cli.json` in the parent directories? There are cases where this can create problems with the project detection. If that's the case, please let us know of the directory structure so we can try to reproduce.

**Comment by wasifale** [comment] 2017-09-08 22:44
Well yes @filipesilva it was happening due to the reason that parent directory had another `.json` file, I have changed the structure and moved the app in a newly created directory and it is working.

**Comment by ssurajita** [comment] 2017-09-17 19:19
I am also facing the same issue. I just created a sample angular app using np new hello-world.
Next I was trying to create a component inside the project path using ng g c course. 
I am getting the same error **_Unable to find any apps in `.angular-cli.json`_**

**Comment by rberge** [comment] 2017-09-21 21:54
Me too.  I cloned the angular Quickstart from git hub. 
git clone https://github.com/angular/quickstart.git
 I then changed the name of the directory and ran the ng generate class and got an error.  I ran this command from within the project directory (e.g. it would have been "quickstart" but I renamed it)
ng generate class Heroes
Unable to find "@angular/cli" in devDependencies.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest" 

installing class
Unable to find any apps in `.angular-cli.json`.


I tried again. I cloned a new Quickstart from git hub .  (same command above)
cd quickstart
1178477-C1MRF34AG944:quickstart mymainuserdirectory$ ls
CHANGELOG.md			karma.conf.js
LICENSE				non-essential-files.osx.txt
README.md			non-essential-files.txt
bs-config.e2e.json		package.json
bs-config.json			protractor.config.js
e2e				src
karma-test-shim.js		tslint.json
1178477-C1MRF34AG944:quickstart mymainuserdirectory$ ng generate class Hobbes
Unable to find "@angular/cli" in devDependencies.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest" 

node_modules appears empty, you may need to run `npm install`


Now to back up, I had installed angular cli globally a while ago using 
npm install -g @angular/cli

Also here is my directory structure,  The project files are all in one directory called
"Angst"
"Angst" has as its contents 4 project directories and no standalone files.
Angst directory contains Project 1 dir(Called FirstForm), Project 2 dir, Project 3 dir, Project 4 dir
The parent of "angular does not have a .json file.  There is one at a high level and then down into a different directory

I tried the "ng generate class Hobbes" in the FirstForm directory.  Just for reference, I did not create that directory with the git clone command, I used ng install.  In that directory it worked
ng generate class Hobbes
installing class
  create src/app/hobbes.ts


[FirstFormpackage_json.txt](https://github.com/angular/angular-cli/files/1322840/FirstFormpackage_json.txt)
[quickstartpackage_json.txt](https://github.com/angular/angular-cli/files/1322841/quickstartpackage_json.txt)


In case it helps, here is how I created the FirstForm directory/project

1178477-C1MRF34AG944:Angst mymainuserdirectory$ node -v
v6.11.2
1178477-C1MRF34AG944:Angst mymainuserdirectory$ npm -v
3.10.10

1178477-C1MRF34AG944:Angst mymainuserdirectory$ cd Angst
-bash: cd: Angst: No such file or directory
1178477-C1MRF34AG944:Angst mymainuserdirectory$ ls
1178477-C1MRF34AG944:Angst mymainuserdirectory$ ng new FirstForm

Installing packages for tooling via npm.
Installed packages for tooling via npm.
Successfully initialized git.
Project 'FirstForm' successfully created

I attached the package.json from each of these.  I had to give them a txt suffix and renamed them with the project name.  To summarize, in Quickstart, I can't use the generate component and in First Form I can.  
[quickstartpackage_json.txt](https://github.com/angular/angular-cli/files/1322848/quickstartpackage_json.txt)

**Comment by mmamongy** [comment] 2017-10-27 17:07
i found the answer here, and it works now for me 
https://stackoverflow.com/a/45705204/3123228

**Comment by filipesilva** [comment] 2017-11-04 18:03
Closing as the @wasifale says he got it sorted (https://github.com/angular/angular-cli/issues/7604#issuecomment-328230900). @rberge the quickstart that you cloned wasn't actually a CLI app, you should use `ng new` to make CLI apps instead.

**Closed by filipesilva** 2017-11-04 18:03 UTC
Labels: need: investigation, priority: 2 (required), type: bug

**Comment by jplew** [comment] 2017-11-11 09:27
I had this exact error message, and learned that the problem was I was attempting to run my `ng` commands from the wrong directory. All I had to do was `cd` into the directory containing my `.angular-cli.json` and it started working.

**Comment by saldivarl** [comment] 2018-01-16 19:37
Hello everybody , I have the same error but what happens if I have a package.json instead of .angular-cli.json ?

**Comment by cenkozan** [comment] 2018-02-12 12:46
ng new isn't creating .angular-cli.json anymore. What a blessed thing to work with angular cli lately. It is always breaking nowadays.

**Comment by vivatum** [comment] 2018-03-22 13:52
I had a same issue. I can't find `.angular-cli.json` by the Finder.
BUT! When I open my project by Visual Studio Code, I can find this file

**Comment by kingsuk** [comment] 2018-03-23 09:38
I believe most of the cases the problem is happening with DOTNET core angular template.
It doesnot provide .angular-cli.json out of the box because it is not created through ng cli.
What you can do is:
Get one .angular-cli.json from any of your other project create with angular cli.
Paste it in your root directory of application.
Change the root to ClientApp.
Rename the app.shared.module.ts to app.module.ts and change all the references of that.
