### ISSUE TITLE
Dynamic external IP

### ISSUE THREAD

**Issue by Hanfrey** [angular/angular-cli#10723] opened 2018-05-08 10:23 UTC
### Versions
```6.0.0
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.0.6
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps

* Step 1 ng serve  --host=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | cut -d\  -f2)

### Observed behavior
```
Project '10.6.234.202' could not be found in workspace.
Error: Project '10.6.234.202' could not be found in workspace.
```

### Desired behavior
In the other Angular CLIs this worked just fine, if I use the IP directly it also works. 

### Mention any other details that might be useful (optional)

Using Mac OS.

**Comment by clydin** [comment] 2018-05-08 14:38
Does the system have more than one non-localhost IP address?

What does the following output?
```
ifconfig | grep "inet " | grep -v 127.0.0.1 | cut -d\  -f2
```

**Comment by Hanfrey** [comment] 2018-05-08 16:39
Gives back the IP I want., which works. But he thinks the ip is a project

**Comment by hansl** [comment] 2018-05-08 17:29
Hi @Hanfrey,

Is there two IPs? I say this because it seems your shell is replacing this command line with something like `ng serve --host=SOMETHING_HERE 10.6.234.202` which is invalid (we take the first unnamed argument as the project name).

Could you try to do 
```sh
echo "ng serve --host=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | cut -d\ -f2)"
```

and see what the actual executed command line looks like? Thanks!

I'm going to close this as it's not a CLI issue (it's shell script), and it's working as intended.

**Closed by hansl** 2018-05-08 17:29 UTC
Labels: need: more info
