### ISSUE TITLE
Ember-cli blueprints not supported by Angular-CLI still work

### ISSUE THREAD

**Issue by huyph** [angular/angular-cli#1884] opened 2016-08-30 02:09 UTC
If I want to customise "ng build" to, say, add a new task to process a json file and populate correct property in environment.*.ts, as of the moment, I think will need to add a new addon, using "ng addon".

I tried that however, it creates lots a new folder with lots of things inside, and looks like it is a separate node package. If an addon is just a simple task like above, is this the right approach? 

Thanks.

**Comment by hansl** [comment] 2016-08-30 03:52
That's using the `ember-cli` addon blueprints. That seems to be a bug (should tell you it doesn't exist). Will look into it.

**Comment by huyph** [comment] 2016-08-30 04:11
Right thanks. 

With angular-cli@webpack.2, is there any way to create hooks for commands, like `ng build`?

**Comment by hansl** [comment] 2016-08-30 21:32
No.

**Comment by huyph** [comment] 2016-08-30 23:24
Ok. Do you know if there is any plan to make `angular-cli` customisable in the near future? Otherwise, I will still need to use grunt/gulp to achieve extra build steps specifically for my project.

**Comment by Brocco** [comment] 2016-09-10 01:09
@huyph there are discussions surrounding build customizations but that is a lower priority than getting bugs fixed.

**Comment by Brocco** [comment] 2016-09-10 02:11
@huyph in what version of the CLI were you able to run `ng addon`?

**Comment by huyph** [comment] 2016-09-10 11:10
@Brocco: ah ok. Thanks for letting me know 👍 

I ran `ng addon` on webpack.2, and just tried on webpack.8.. I am not able to run it inside a project generated by angular-cli, but outside it though.

**Comment by Brocco** [comment] 2016-09-19 14:14
@huyph I was not able to execute `ng addon` inside or outside a CLI project with the current version (beta 14). Are you still able to do this?

**Comment by huyph** [comment] 2016-09-20 00:13
Yes, apparently

```
$ ng --version
angular-cli: 1.0.0-beta.14
node: 6.4.0
os: darwin x64
$ ng addon toberemoved
installing addon
  create .bowerrc
  create .editorconfig
  create .angular-cli
  create .jshintrc
  create .travis.yml
....
```

**Comment by Brocco** [comment] 2016-09-24 03:31
I still have not been able to reproduce this issue or track down a possible leak in the code.

![image](https://cloud.githubusercontent.com/assets/1565117/18805817/d28214ba-81e5-11e6-9152-c86a7fa2dbab.png)

I am closing this for now, please update to the latest CLI (Currently beta 15) and try this in a newly created application.

**Closed by Brocco** 2016-09-24 03:31 UTC
Labels: priority: 2 (required), type: bug
