### ISSUE TITLE
Jasmine tests stacktrace useless - does not show source .ts files and line numbers

### ISSUE THREAD

**Issue by xnnkmd** [angular/angular-cli#6943] opened 2017-07-11 11:20 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
ng 1.2

### Repro steps.
`ng new tst`

modify generated app.component.spec.ts line 23 to force an error. E.g.
` expect(app.title).toEqual('forcebug');`

`ng test`

Note the useless stacktrace this gives no clue about the source code responible for the bug.

### The log given by the failure.

        Expected 'app' to equal 'forcebug'.
            at Object.<anonymous> (http://localhost:9876/_karma_webpack_/main.bundle.js:89:27)
            at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2801:26)
            at AsyncTestZoneSpec.webpackJsonp.../../../../zone.js/dist/async-test.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:2643:39)
            at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:3406:39)
C

### Desired functionality.

Stacktrace should report app.component.ts:23 as part of the stacktrace (ideally at the top).

**Comment by devoto13** [comment] 2017-07-11 13:09
Possible duplicate of #6583.

**Comment by filipesilva** [comment] 2017-07-28 09:54
Closing as duplicate of https://github.com/angular/angular-cli/issues/6583

**Closed by filipesilva** 2017-07-28 09:54 UTC
