### ISSUE TITLE
Safari: SynthaxError: Left hand side of operaor '=' must be a reference.

### ISSUE THREAD

**Issue by alexfriesen** [angular/angular-cli#21107] opened 2021-06-10 10:08 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I am not sure.

### Description

My Angular Application is crashing only on Safari when three.js is included.
The error message: `SynthaxError: Left hand side of operaor '=' must be a reference.`

Threre is a Stackoverflow Thread about this Issue: 
https://stackoverflow.com/questions/66941849/chunkloaderror-in-angular-threejs-app-only-on-safari

## 🔬 Minimal Reproduction

I created this repo: 
https://github.com/alexfriesen/angular-three-template

Which is deployed on:
https://alexfriesen.github.io/angular-three-template/

The same Code works just fine with Vite:
https://github.com/alexfriesen/retro

## 🔥 Exception or Error

<pre><code>
SynthaxError: Left hand side of operaor '=' must be a reference.
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.3
Node: 14.17.0
Package Manager: npm 6.14.13
OS: linux x64

Angular: 12.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@angular/cli                    12.0.3
@schematics/angular             12.0.3
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

Tested with Safari 14

I looks like it is related to [ES6 Changes in Three.js](https://github.com/mrdoob/three.js/releases/tag/r126)

**Comment by wulfsberg** [comment] 2021-07-15 09:51
I am unsure  whether ThreeJS is doing something crazy with its ES6 classes, but flat out getting a runtime syntax error in the production-built code just can't be right.
I see the "need investigation" tag. Is there anything we can do to help narrow it down?

**Comment by imario42** [comment] 2021-07-22 09:48
I am having the exact same issue. Also something with isSpotlight. When disabling the optimization for scripts in angular.json it started to work. Not an option for prod builds though.

**Comment by petebacondarwin** [comment] 2021-07-22 11:01
Here is another report on StackOverflow: https://stackoverflow.com/questions/68224800/left-hand-side-of-operator-must-be-a-reference-only-in-webkit-safari-in-ang

I also note from the reproduction that it only occurs when the code is minified (i.e. `optimization: true`).
So it seems that combination of how Three.js is generating its classes and how Terser is minifying them creates a syntax that Safari is not able to parse.

**Comment by petebacondarwin** [comment] 2021-07-22 11:35
One last note: setting `buildOptimizer` to false, while leaving `optmization` at true resolves the issue as well.
So it appears to be the combination of the two that is causing the problem on Safari.

**Comment by wulfsberg** [comment] 2021-07-22 11:40
Is this purely a Terser issue, then, and should be logged against that? Or does Angular do some preprocessing which confuses the tool chain?

**Comment by petebacondarwin** [comment] 2021-07-22 11:42
The build optimizer pass is somethat specific to the Angular CLI. So it might be an issue on our side...

**Comment by alan-agius4** [comment] 2021-07-22 12:41
This should no longer be an issue with 12.2 which is currently in pre-release. 

Can someone please try this out using `ng update @angular/cli --next`?

**Comment by petebacondarwin** [comment] 2021-07-22 14:24
The reproduction in the original description of this issue does indeed work with `12.2.0-next.3`. 👍

**Comment by wulfsberg** [comment] 2021-07-22 15:08
Seconded. Angular 12.2.0-next.3 and ThreeJS 0.130.1 plays nicely together again.

**Comment by imario42** [comment] 2021-07-22 15:41
Yep, that works for me too. Thanks alot!

**Comment by alan-agius4** [comment] 2021-07-22 17:33
Closing as per above.

**Closed by alan-agius4** 2021-07-22 17:33 UTC
Labels: comp: devkit/build-angular

**Comment by alexfriesen** [comment] 2021-08-09 07:13
It works now. Thanks!
