### ISSUE TITLE
Package manager binary location to angular.json

### ISSUE THREAD

**Issue by egaga** [angular/angular-cli#11959] opened 2018-08-21 12:19 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Relevant only: Angular CLI: 6.1.4

### Repro steps

```
ng config cli.packageManager yarn
ng update @angular/core`
```

### The log given by the failure
```
yarn not found
```

because yarn is not globally installed.

### Desired functionality
Specify yarn location in `angular.json` (by a relative path). The reason is that yarn version should be project dependent, not globally installed and defined in `PATH`.

**Comment by hansl** [comment] 2018-08-22 03:13
Duplicate of #11694

**Closed by hansl** 2018-08-22 03:13 UTC
