### ISSUE TITLE
ng lint fails on a big file while tslint does not

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular-cli#9605] opened 2018-02-12 14:37 UTC
### Versions
```
Angular CLI: 1.6.8
Node: 8.9.4
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cdk: 5.1.0
@angular/cli: 1.6.8
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0
```

```
$ node -v
v8.9.4
```
```
$ npm -v
5.6.0
```

```
Windows 10 (gitbash)
```

### Repro steps

A autogenerated metadata.ts that has 1.2MB which looks like:

```typescript
export class Foo {
  public static value = {...}
}
```

The value object is a massive "uglified" blob that makes the file to be 1.2MB. If formatted, it is a real 58k lines TypeScript class.

### Observed behavior

`ng lint` is not able to run it, eventually dies with a:

```
$ ng lint                                                                                                                                        
Maximum call stack size exceeded                                                                                                                 
RangeError: Maximum call stack size exceeded                                                                                                     
    at lintConfigs.map.reduce (C:\Users\Jesus\Documents\Programming\foo\node_modules\@angular\cli\tasks\lint.js
:77:45)                                                                                                                                          
    at Array.reduce (<anonymous>)                                                                                                                
    at Class.run (C:\Users\Jesus\Documents\Programming\foo\node_modules\@angular\cli\tasks\lint.js:74:14)      
    at Class.run (C:\Users\Jesus\Documents\Programming\foo\node_modules\@angular\cli\commands\lint.js:46:25)   
    at resolve (C:\Users\Jesus\Documents\Programming\foo\node_modules\@angular\cli\ember-cli\lib\models\command
.js:261:20)                                                                                                                                      
    at new Promise (<anonymous>)                                                                                                                 
    at Class.validateAndRun (C:\Users\Jesus\Documents\Programming\foo\node_modules\@angular\cli\ember-cli\lib\m
odels\command.js:240:12)                                                                                                                         
    at Promise.resolve.then.then (C:\Users\Jesus\Documents\Programming\foo\node_modules\@angular\cli\ember-cli\
lib\cli\cli.js:140:24)                                                                                                                           
    at <anonymous>                                                                                                                               
```

The interesting bit is that `tslint` success while `ng lint` which is a wrapper just fails.

The second interesting bit is that if I allow VSCode to format the file properly (from ugly to the 58k lines) it works with both commands.

### Desired behavior

The wrapper should be able to run what `tslint` itself runs as well.

### Mention any other details that might be useful (optional)

/cc @filipesilva

**Comment by mgechev** [comment] 2019-08-19 20:24
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:24 UTC
Labels: comp: devkit/build-angular, freq1: low, help wanted, severity4: memory/performance, type: bug/fix
