### ISSUE TITLE
CSS Sourcemap is always empty

### ISSUE THREAD

**Issue by changLiuUNSW** [angular/angular-cli#4199] opened 2017-01-24 12:15 UTC
My Angular-Cli version is ```1.0.0-beta.26```
Here is my ```angular-cli.json```:
```
{
  "project": {
    "version": "1.0.0-beta.26",
    "name": "test"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.scss"
      ],
      "scripts": [],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}
```
And Here is my ```styles.scss```

```
h1 {
    font-size: 20px;
}
```

When I type ```ng serve --extract-css=true``` or ```ng build  --extract-css=true```, the ```styles.bundle.map``` is always empty like: 
```
{"version":3,"sources":[],"names":[],"mappings":"","file":"styles.bundle.css","sourceRoot":""}
```

Does anyone have the same issue with me ? Or maybe this is expected behavior ?

**Comment by changLiuUNSW** [comment] 2017-01-24 12:23
I also tried ```ng serve --extract-css=true --sourcemap=true``` or ```ng build --extract-css=true --sourcemap=true```, the result is still the same.

**Comment by filipesilva** [comment] 2017-01-24 12:24
Bug I think. I have known about it for a while, but haven't had time to look at it yet.

**Comment by changLiuUNSW** [comment] 2017-01-24 12:57
I think we should have unit test to cover css sourcemap

**Comment by a5hik** [comment] 2017-01-25 00:57
I'm facing the same issue, the css source map is empty.

**Comment by filipesilva** [comment] 2017-01-27 15:10
Dupe of https://github.com/angular/angular-cli/issues/2020, fixed by https://github.com/angular/angular-cli/pull/4222.

**Closed by filipesilva** 2017-01-27 15:10 UTC
Labels: command: build, priority: 2 (required), type: bug

**Comment by craigcosmo** [comment] 2017-02-15 16:09
Are you sure it's fixed? I still have the issue. My command is like this

`"start": "ng serve --port 1800 --extract-css=true --sourcemap=true",`

And source map still not show up

<img width="1438" alt="screen_shot_2017-02-15_at_11_04_08_pm" src="https://cloud.githubusercontent.com/assets/538657/22983013/5db84b58-f3d3-11e6-840a-975ee4098e7d.png">

demo: https://github.com/craigcosmo/yeahman-angular-cli-app

**Comment by kaynz** [comment] 2017-02-16 09:29
I can confirm: Not working! :(

**Comment by changLiuUNSW** [comment] 2017-02-20 12:43
@filipesilva Maybe we need to reopen this issue

**Comment by filipesilva** [comment] 2017-02-20 12:47
Regarding component styles and sourcemaps, please see @asnowwolf's excelent explanation in https://github.com/angular/angular-cli/issues/3617#issuecomment-279412965.

The gist of it is that component styles atm cannot have style maps.

**Comment by changLiuUNSW** [comment] 2017-02-20 13:22
The sourcemaps for global style seemed broken again

**Comment by filipesilva** [comment] 2017-02-20 13:28
@changLiuUNSW can you show me a repro?

**Comment by changLiuUNSW** [comment] 2017-02-20 13:41
@filipesilva https://github.com/changLiuUNSW/ng2Redux

**Comment by filipesilva** [comment] 2017-02-21 09:40
@changLiuUNSW I tried your repo, serving with `ng serve --extract-css`, and I could see the sourcemaps for scss files:

![image](https://cloud.githubusercontent.com/assets/4172079/23159198/c3f72476-f819-11e6-9566-b8fea4c5d21d.png)

**Comment by changLiuUNSW** [comment] 2017-02-21 09:44
Yes, it works. I forget to put ```--extract-css```
Thanks @filipesilva

**Comment by daddyschmack** [comment] 2017-06-29 02:16
@filipesilva , HI, this is not working for me in v1.04.  What steps do I need to troubleshoot?  Or what do you need from me to troubleshoot?  
I've tried: 
```ng serve -prod```
I've tried :
```ng serve --extract-css -sourcemap=true

My expectation is to see the component scss files mapped to the elements inspected in chrome developer tools.  Please let me know if this is not the correct expectation.
BTW, TS source 

maps are working.

<img width="1434" alt="screen shot 2017-06-28 at 8 11 54 pm" src="https://user-images.githubusercontent.com/2753635/27668498-af6f3456-5c3e-11e7-96f6-57e988b7b565.png">

**Comment by asnowwolf** [comment] 2017-06-29 03:14
@daddyschmack It's a reasonable expectation. But in fact, this issue is blocked by https://github.com/angular/angular/pull/16088 and https://github.com/angular/angular/pull/16090 .
In other words, currently, it's an issue of "angular", not "angular-cli"'s. You can go to push them to be merged. 
I've resolved the part of cli through a pull request to `css-loader` https://github.com/webpack-contrib/css-loader/pull/417 . So, just waiting for the angular repo.
