### ISSUE TITLE
Angular 10 project component is not rendered with target as `es5`

### ISSUE THREAD

**Issue by Indrajith-Sync** [angular/angular-cli#18857] opened 2020-09-22 12:56 UTC
# 🐞 bug report

### Affected Package
**tsconfig.json**

![image](https://user-images.githubusercontent.com/29561170/93885955-77ce6b80-fd02-11ea-994e-28fcaa4de732.png)

### Description

When setting the target as es5 a script error of cannot call class as function is raised. If the target is changed to es2015 it works.

## 🔬 Minimal Reproduction

Run the below sample 
->  npm install
-> ng serve

Sample: 
[Angular_10_RTE.zip](https://github.com/angular/angular/files/5261497/Angular_10_RTE.zip)

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/29561170/93884614-bfec8e80-fd00-11ea-898c-7d8d8094e10a.png)

## 🌍  Your Environment

![image](https://user-images.githubusercontent.com/29561170/93884801-ff1adf80-fd00-11ea-8aad-716310ec519f.png)

Any idea of this issue based on target ?

**Comment by alan-agius4** [comment] 2020-09-23 13:16
I am seeing that you are using @syncfusion packages.

This is a duplicate of https://github.com/angular/angular-cli/issues/18125

**Closed by alan-agius4** 2020-09-23 13:16 UTC
