### ISSUE TITLE
Allow imports with .js extension

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#4591] opened 2017-02-10 11:12 UTC
### Versions.
`@ngtools/webpack` 1.2.9

### Repro steps.
[Since TS 2.0](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#module-identifiers-allow-for-js-extension), it's possible to : 
`import { Something } from './something.js'`;

> Module identifiers allow for .js extension
> 
> Before TypeScript 2.0, a module identifier was always assumed to be extension-less; for instance, given an import as import d from "./moduleA.js", the compiler looked up the definition of "moduleA.js" in ./moduleA.js.ts or ./moduleA.js.d.ts. This made it hard to use bundling/loading tools like SystemJS that expect URI's in their module identifier.
> 
> With TypeScript 2.0, the compiler will look up definition of "moduleA.js" in ./moduleA.ts or ./moduleA.d.ts.

But using this possibility with `@ngtools/webpack` results in error : 
`Module not found: Error: Can't resolve './something.js'`

It's important to be compatible with ES6 modules, which **require** the `.js` extension, as `<script type="module"></script>` is now in test in all browsers, and as for now TS doesn't provide an option to add the `.js` extension in transpiled files (see Microsoft/TypeScript#13422).

It's possible when using `ngc` directly, and also in [rollup/rollup-plugin-typescript](https://github.com/rollup/rollup-plugin-typescript) so I assume it's possible with `@ngtools/webpack` too.

**Comment by Brocco** [comment] 2017-03-17 16:19
I was able to get this to work locally without any changes to the CLI itself.

In your generated project's `tsconfig.json` under `compilerOptions` you will need to add `"allowJs": true`. This will allow `tsc` to resolve the references to `.js` files.

VS Code provided the related warning to discover this flag:
![image](https://cloud.githubusercontent.com/assets/1565117/24052459/f460e868-0b0b-11e7-8ff6-da0ff06c33ac.png)

**Comment by cyrilletuzi** [comment] 2017-03-17 16:37
Do we agree the original file is `tester.ts` ?

It's not about including .js files, it's about loading .ts files (as Angular is in TypeScript) but accordingly to the ES modules loading spec.

**Comment by Brocco** [comment] 2017-03-17 21:11
I see what you're saying now, I am looking through this now.

**Comment by hansl** [comment] 2017-03-21 20:29
Unfortunately, I'm going to close this as Working As Intended right now.

The ESM spec is not finalized yet, and webpack does not support it. We found no problem in the CLI code, but we end up passing `require()` calls pointing to those `.js` files to webpack, and webpack itself fails to resolve them.

We will continue investigate this as ESM is finalized and webpack support is added. We may release a minor update to support it at that time. Cheers.

**Closed by hansl** 2017-03-21 20:29 UTC
Labels: priority: 1 (urgent), type: enhancement
