### ISSUE TITLE
Production bundle error after very small edit from seed app

### ISSUE THREAD

**Issue by tranvansang** [angular/angular-cli#7738] opened 2017-09-19 09:29 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.4.2
node: 8.5.0
os: linux x64
@angular/animations: 4.4.2
@angular/common: 4.4.2
@angular/compiler: 4.4.2
@angular/core: 4.4.2
@angular/forms: 4.4.2
@angular/http: 4.4.2
@angular/platform-browser: 4.4.2
@angular/platform-browser-dynamic: 4.4.2
@angular/router: 4.4.2
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.2
@angular/language-service: 4.4.2
typescript: 2.3.4
```

### Repro steps.

`ng new test-app`

`cd test-app`

`yarn`

`ng serve --environment=prod --host 0.0.0.0 --prod --aot`

Browse `http://localhost:4200`, site works

Edit `src/app/app.module.ts`  to add `ReactiveFormsModule`
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { AppComponent } from './app.component';
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    ReactiveFormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Edit `src/app/app.component.html`
```html
<input [formControl]="helloFC">
```

Edit `src/app/app.component.ts`
```typescript
import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  helloFC = new FormControl('');
}
```

Browse `http://localhost:4200`, site not work

### The log given by the failure.
```
Error: No provider for e!
    at E (vendor.3de0515ca8e2c20f1562.bundle.js:1)
    at O (vendor.3de0515ca8e2c20f1562.bundle.js:1)
    at t._throwOrNull (vendor.3de0515ca8e2c20f1562.bundle.js:1)
    at t._getByKeyDefault (vendor.3de0515ca8e2c20f1562.bundle.js:1)
    at t._getByKey (vendor.3de0515ca8e2c20f1562.bundle.js:1)
    at t.get (vendor.3de0515ca8e2c20f1562.bundle.js:1)
    at je (vendor.3de0515ca8e2c20f1562.bundle.js:1)
    at t.get (vendor.3de0515ca8e2c20f1562.bundle.js:1)
    at fn (vendor.3de0515ca8e2c20f1562.bundle.js:1)
    at cn (vendor.3de0515ca8e2c20f1562.bundle.js:1)
```

### Desired functionality.
Site should work without any error

**Comment by prismsoundzero** [comment] 2017-09-19 12:28
Same issue here with a bigger app. Seems like a compatibility issue with Angular 4.4.X. Switching back to Angular 4.3.6 resolves temporarily the issue.

**Comment by tranvansang** [comment] 2017-09-19 13:47
I worked on an real project, had this issue, `bisect` until very first commit and came up with this smallest edit to make the bug easier to be seen

**Comment by devoto13** [comment] 2017-09-19 15:25
It's Angular [issue](https://github.com/angular/angular/issues/19219#issuecomment-330431900), not CLI.

**Comment by Brocco** [comment] 2017-09-22 19:05
@tranvansang Can you confirm that your app is working after updating to 4.4.3 or greater per @devoto13's comment/link?

**Comment by tranvansang** [comment] 2017-09-24 16:53
@Brocco 
`ng --version` result

```
@angular/cli: 1.4.3
node: 8.5.0
os: linux x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4
```

Now thing works as expected

**Comment by devoto13** [comment] 2017-09-26 09:59
@tranvansang Than close this issue, please.

**Closed** 2017-09-26 12:10 UTC

**Comment by nayanasrirama** [comment] 2017-12-06 14:04
@tranvansang what small change did you do to clear the error could you please help me out

**Comment by tranvansang** [comment] 2017-12-07 04:47
@nayanasrirama upgrade `@angular` and `@angular/cli` only did not fix the problem. What I did was `yarn upgrade` or `npm update` followed by `@angular @angular/cli @angular/compile-cli`... everything appears in `ng --version` result.

Hope this help

**Comment by nayanasrirama** [comment] 2017-12-07 12:16
@tranvansang 
yarn command isn't working so i did npm update and i have the latest angular cli and angular versions but still the error appears can you please help me out

**Comment by tranvansang** [comment] 2017-12-07 14:09
@nayanasrirama can you paste `ng --version` and your `package.json` content. And what is your problem? any terminal error output and how did you reproduce them

**Comment by nayanasrirama** [comment] 2017-12-08 11:52
@tranvansang 
No the problem is fixed thank you for your time
