### ISSUE TITLE
In HMR mode, the whole page goes blank after each change in code

### ISSUE THREAD

**Issue by Parsa-Sedigh** [angular/angular-cli#21095] opened 2021-06-09 10:48 UTC
# 🐞 Bug report
After any little change in my code, the page in dev server goes blank and I need to manually refresh the page to see the changes. Note that this issue was also present in angular v11 with hmr.

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre><code>

-- In console I get:
Uncaught TypeError: Cannot read property 'push' of undefined
    at self.webpackHotUpdatexxx (jsonp chunk loading:48)
    at runtime.4575cdf871eee780f0cb.hot-update.js:1

Uncaught TypeError: Cannot set property '9229' of undefined
    at self.webpackHotUpdateng_xxx (jsonp chunk loading:44)
    at main.4575cdf871eee780f0cb.hot-update.js:1

-- The related source code(jsonp chunk loading) is:
self["webpackHotUpdateng_xxx"] = (chunkId, moreModules, runtime) => {
	for(var moduleId in moreModules) {
		if(__webpack_require__.o(moreModules, moduleId)) {
			currentUpdate[moduleId] = moreModules[moduleId];
			if(currentUpdatedModulesList) currentUpdatedModulesList.push(moduleId);
		}
	}
	if(runtime) currentUpdateRuntime.push(runtime);
	if(waitingUpdateResolves[chunkId]) {
		waitingUpdateResolves[chunkId]();
		waitingUpdateResolves[chunkId] = undefined;
	}
};
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@angular/platform-server        12.0.2
@nguniversal/builders           12.0.1
@nguniversal/express-engine     12.0.0
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-06-09 11:09
Duplicate of https://github.com/angular/angular-cli/issues/20288

Please update to the latest version of `@angular/cli` and `@angular-devkit/build-angular`.

**Closed by alan-agius4** 2021-06-09 11:09 UTC
