### ISSUE TITLE
CSS Module imports stopped working from v10 to v11.

### ISSUE THREAD

**Issue by chrissyast** [angular/angular-cli#19667] opened 2020-12-22 17:32 UTC
### Is this a regression?

Yes. V10 worked.

### Description

Up to and including Angular 10, it was possible to use [CSS Modules](https://github.com/css-modules/css-modules) to import CSS into the script of the component (via the `:export` function on the .scss file and `import styles from "../foo.scss";` within the script of the component). You can see a live example [here](https://scss-import-angular-v10.herokuapp.com/), a minimal reproduction of which is linked below. The variable was imported from the .scss into the .ts and then consequently available within the html too.

This has stopped working in v11 with more details below.

## 🔬 Minimal Reproduction

Working example https://github.com/chrissyast/scss-import-ng-ten
Not working example https://github.com/chrissyast/scss-import-ng-eleven

## 🔥 Exception or Error

`import styles from "../styles.scss"` gives an error   ` "export 'default' (imported as 'styles') was not found in '../styles.scss'`

`const styles = require("../styles.scss")` works but it is not possible to extract the variable from the created map

## 🌍 Your Environment
<pre><code>
Working
======
Angular CLI: 10.0.8
Node: 10.15.3
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

Not working
========
Angular CLI: 11.0.5
Node: 10.15.3
OS: win32 x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

## Additional info
In a discussion on https://stackoverflow.com/a/63429103/8940624, a fellow user stated:

> Css modules configuration changed considerably from ng 10 to ng 11. Now, its not the default. You have to set modules : true on the webpack configuration, which is not enabled on ng 11. I think its the case to create an issue on the @angular/cli repo to ask for expose the configuration of it.

My knowledge is not sufficient to be able to verify or refute whether this is the underlying issue but adding for extra info.

**Comment by alan-agius4** [comment] 2020-12-22 18:00
Duplicate of https://github.com/angular/angular-cli/issues/19622

**Closed by alan-agius4** 2020-12-22 18:00 UTC
