### ISSUE TITLE
ng update for cli@8.1.3 requires Angular 8.2.0-rc.0 dependencies

### ISSUE THREAD

**Issue by tomgruszowski** [angular/angular-cli#15193] opened 2019-07-29 23:18 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, started with angular/cli 8.1.3

### Description

run ng update @angular/cli produces error with incompatible dependencies for 8.2.0.rc-0
## 🔬 Minimal Reproduction

ng update @angular/cli
Using package manager: 'npm'
Collecting installed dependencies...
Found 51 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular/material" has an incompatible peer dependency to "@angular/common" (requires "^8.0.0 || ^9.0.0-0" (extended), would install "8.2.0-rc.0").
                  Package "ngx-quill" has an incompatible peer dependency to "@angular/platform-browser" (requires "^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0" (extended), would install "8.2.0-rc.0").
                  Package "@angular/material" has an incompatible peer dependency to "@angular/forms" (requires "^8.0.0 || ^9.0.0-0" (extended), would install "8.2.0-rc.0").
                  Package "@angular/material" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0 || ^9.0.0-0" (extended), would install "8.2.0-rc.0").
                  Package "@angular/material" has an incompatible peer dependency to "@angular/animations" (requires "^8.0.0 || ^9.0.0-0" (extended), would install "8.2.0-rc.0").
Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.1.2
Node: 12.7.0
OS: win32 x64
Angular: 8.1.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/cdk                      8.1.2
@angular/cli                      8.1.2
@angular/material                 8.1.2
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Comment by just-trey** [comment] 2019-07-30 03:14
I have this same issue as well.

**Comment by topikus** [comment] 2019-07-30 04:53
the same

**Comment by alan-agius4** [comment] 2019-07-30 05:19
Duplicate of https://github.com/angular/angular-cli/issues/14980

**Closed by alan-agius4** 2019-07-30 05:19 UTC
