### ISSUE TITLE
Slow Time when Passing Prod

### ISSUE THREAD

**Issue by jorgelub12** [angular/angular-cli#9714] opened 2018-02-21 15:43 UTC
### Versions
```
Angular CLI: 1.5.5
Node: 8.9.1
OS: win32 x64
```

### Repro steps
* Running the command: ng build --prod --aot --verbose

### Observed behavior Prod 
```
 67% building modules 794/822 modules 28 active ...ontend\node_modules\d3-shape\index.jsNode#moveTo was deprecated. Use Cont59337ms building modules96ms sealing
10ms optimizing
1ms basic module optimization
0ms module optimization
74ms advanced module optimization
16ms basic chunk optimization
0ms chunk optimization
3ms advanced chunk optimization
5318ms building modules
1ms module and chunk tree optimization
362ms chunk modules optimization
0ms advanced chunk modules optimization
0ms module reviving
11ms module order optimization
2ms module id optimization
0ms chunk reviving
14ms chunk order optimization
59ms chunk id optimization
263ms hashing
1ms module assets processing
3900ms chunk assets processing
14ms additional chunk assets processing
10ms recording
1ms additional asset processing
 92% chunk asset optimization
```

### Observed behavior Using Serve
```
PS D:\Projecs\> ng serve --aot
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-02-21T15:53:48.020Z
Hash: 0258219101f60309cd12
Time: 80417ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 9.17 MB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 549 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 1.65 MB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 24.4 MB [initial] [rendered]
webpack: Compiled successfully.
```
### Desired behavior
Its almost 48 minutes and still in 92% without any additional message. My project is a medium projects with more than 40 components.
Is there any way to check in the logs whats going on? Not just see the 92% message.

**Comment by istiti** [comment] 2018-02-22 14:29
this is definitly not normal I have more than 1k files and build in 3mn, can you share your project ?

**Comment by filipesilva** [comment] 2018-02-22 20:57
Hi, this issue is a duplicate of https://github.com/angular/angular-cli/issues/6795. You're using an older version of the CLI that did not have a couple important optimizations for production though. I recommend updating to 1.7.0.

**Closed by filipesilva** 2018-02-22 20:57 UTC
