### ISSUE TITLE
Unable to install angular-cli

### ISSUE THREAD

**Issue by lmahanand** [angular/angular-cli#2514] opened 2016-10-05 03:19 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows   10.

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

Cannot find module 'portfinder'
Error: Cannot find module 'portfinder'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\lingraj mahanand\AppData\Roaming\npm\node_modules\angular-cli\commands\serve.js:6:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Class.module.exports.includedCommands (C:\Users\lingraj ma

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
Just before the installation fails, I am getting the below error

> node-sass@3.10.1 postinstall C:\Users\lingraj mahanand\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
> node scripts/build.js

"C:\Users\lingraj mahanand\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass\vendor\win32-x64-46\binding.node" exists.
 testing binary.
Binary is fine; exiting.
C:\Users\lingraj mahanand\AppData\Roaming\npm\ng -> C:\Users\lingraj mahanand\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli@latest"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer string-replace-loader@1.0.5 wants webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.3 wants webpack@^2.1.0-beta

npm ERR! Please include the following file with any support request:
npm ERR!     E:\softwares\angular-cli\npm-debug.log

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gelliott181** [comment] 2016-10-05 14:21
So when you install the CLI and run node --version you get that portfinder error?

**Comment by JanStureNielsen** [comment] 2016-10-05 15:44
Dup of #1782

**Comment by filipesilva** [comment] 2016-10-06 17:22
Dupe of #1782.

**Closed by filipesilva** 2016-10-06 17:22 UTC
