### ISSUE TITLE
[Bug] - styleUrls fail when using template string's backtick in CLI >= 1.5

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#8731] opened 2017-12-03 19:56 UTC
```
Angular CLI: 1.5.5
Node: 8.9.1
OS: darwin x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.5
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript: 2.4.2
webpack: 3.8.1
```

```  
styleUrls: [`/hero-list.component.scss`],
```

Notice I had the backtick for the string. I was using this because at one point I converted from inline styles to a separate file (because we can’t do SASS inline). So I never bothered changing the template string syntax to single quote strings. This worked in the CLI 1.4.x. I upgraded to 1.5 and *boom*. The error was confusing and long. But it gave me a hint as it was trying to find the scss file with the template strings around it, which is obviously wrong. So I changed to single quotes and I was good.

So … if you ever use template string / backtick for a file reference, then it will go *boom*.

Optimally, this would be supported. If not, it would be nice to have a warning about this in the CLI.

**Comment by filipesilva** [comment] 2017-12-03 20:09
Duplicate of #7945, fixed by https://github.com/angular/angular-cli/pull/8666.

**Closed by filipesilva** 2017-12-03 20:09 UTC

**Comment by johnpapa** [comment] 2017-12-03 20:20
perfect, thanks
