### ISSUE TITLE
Latest code/html changes not visible in browser.

### ISSUE THREAD

**Issue by Ionaru** [angular/angular-cli#14804] opened 2019-06-17 22:07 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.0.2
Ancient issue that described the same problem: #5117

### Description

Auto-reload does not reload latest changes into the browser, instead the one before last change is visible.

## 🔬 Minimal Reproduction

1. `ng new --style=scss --enable-ivy --routing reload-test`
2. `ng g component home`
3. Add `{component: HomeComponent, path: ''}` as route to `app-routing.module.ts`
2. `ng serve`
4. Open webpage on http://localhost:4200
5. Change some HTML or code in `HomeComponent`.
6. Save (Recompile will trigger & webpage will reload).
7. **Change is not visible.**
8. Make another change in `HomeComponent`.
9. Save (Recompile will trigger & webpage will reload).
10. First change is visible, but second change isn't.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.3
Node: 12.3.1
OS: win32 x64
Angular: 8.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

## Additional information
A few things I've noticed:

* Subsequent saves will trigger another recompile, even though nothing was changed. Each new build also has a unique hash, which is strange because nothing changed.
* Changes to `AppComponent` do show up when reloading the webpage. (Problem seems isolated to routes)

**Comment by Ionaru** [comment] 2019-06-17 23:35
`2019-06-17 23:33 UTC`: Updated original comment with better reproduction steps and additional information.

**Comment by alan-agius4** [comment] 2019-06-18 04:40
Duplicate of https://github.com/angular/angular/issues/30947

**Closed by alan-agius4** 2019-06-18 04:40 UTC
