### ISSUE TITLE
ERROR in Cannot read property 'getSourceFile' of undefined

### ISSUE THREAD

**Issue by milenkovic** [angular/angular-cli#5329] opened 2017-03-09 10:48 UTC
Hi, I am trying to configure webpack in order to work with AOT, however I am getting this error. I tried with changing versions but without success, in some cases I even got more errors.

### OS?
Windows 10

### Versions.
Node: v7.6.0
@ngtools/webpack: 1.2.12

### Repro steps.
https://github.com/milenkovic/webpack-angular-aot
npm install
npm run project-aot

### The log given by the failure.
ERROR in Cannot read property 'getSourceFile' of undefined

ERROR in C:/Workspace/webpack-aot/public/javascripts/core/projects/main.aot.ts (3,34): Cannot find module './ngfactory/public/javascripts/core/projects/app.module.ngfactory'.)

ERROR in ./public/javascripts/core/projects/main.aot.ts
Module not found: Error: Can't resolve './ngfactory/public/javascripts/core/projects/app.module.ngfactory' in 'C:\Workspace\webpack-aot\public\javascripts\core\projects'
 @ ./public/javascripts/core/projects/main.aot.ts 3:0-103

**Comment by Dobryvechir** [comment] 2017-03-11 20:24
The error lies in node_modules\@ngtools\webpack\src\compiler_host.js in function _resolve(path), when the operating system is Windows.
In some cases, this function calls to path.join, which returns a normalized path under the current OS, which does not correspond to the idea of _resolve function to replace backslashes with normal slashes.
Until a new version with this fix appears, you can replace manually that function with the code as follows:
    _resolve(path) {
        path = this._normalizePath(path);
        if (path[0] == '.') {
            return this._normalizePath(path_1.join(this.getCurrentDirectory(), path));
        }
        else if (path[0] == '/' || path.match(/^\w:\//)) {
            return path;
        }
        else {
            return this._normalizePath(path_1.join(this._basePath, path));
        }
    }
After this, the problem disappears.

**Comment by PaybackMan** [comment] 2017-03-16 20:42
horrible error message

**Comment by maffelbaffel** [comment] 2017-03-22 12:45
This error literally cost me 5 hours debugging. Replacing with 
````
_resolve(path) {
        path = this._normalizePath(path);
        if (path[0] == '.') {
            return this._normalizePath(path_1.join(this.getCurrentDirectory(), path));
        }
        else if (path[0] == '/' || path.match(/^\w:\//)) {
            return path;
        }
        else {
            return this._normalizePath(path_1.join(this._basePath, path));
        }
    }
````

@Dobryvechir's code was missing a backslash:
````
        else if (path[0] == '/' || path.match(/^\w://)) {
                                                     ^
SyntaxError: Unexpected token )
````

**Comment by arlindonatal** [comment] 2017-03-22 23:55
I have the same problem. After changing this method, the error persists:

ERROR in Cannot read property 'getSourceFile' of undefined

`ERROR in /home/arlindo/git/vendedoronline/frontend/src/app/utils/hmac-http-client.ts (39,63): Cannot find name 'CryptoJS'.)
/home/arlindo/git/vendedoronline/frontend/src/app/utils/hmac-http-client.ts (41,63): Cannot find name 'CryptoJS'.)
/home/arlindo/git/vendedoronline/frontend/src/app/utils/hmac-http-client.ts (43,63): Cannot find name 'CryptoJS'.)

ERROR in /home/arlindo/git/vendedoronline/frontend/src/app/security/securityToken.ts (5,9): Cannot find name '_'.)

ERROR in /home/arlindo/git/vendedoronline/frontend/src/app/account/account.ts (12,13): Cannot find name '_'.)

ERROR in /home/arlindo/git/vendedoronline/frontend/src/app/empresa/empresa.ts (11,13): Cannot find name '_'.)

ERROR in /home/arlindo/git/vendedoronline/frontend/src/app/fabricante/fabricante.ts (10,13): Cannot find name '_'.)

ERROR in /home/arlindo/git/vendedoronline/frontend/src/app/linha/linha.ts (10,13): Cannot find name '_'.)
`

**Comment by tinchou** [comment] 2017-03-25 00:34
I'm on Windows 10 using `@ngtools/webpack:1.3.0`. I can confirm @maffelbaffel's fix works.

You can paste this into your `webpack.config.js` and avoid touching the `node_modules` folder, especially useful for automated deployment scenarios:

```js
// workaround https://github.com/angular/angular-cli/issues/5329
var aotPlugin = new ngToolsWebpack.AotPlugin({
    tsConfigPath: "./tsconfig.aot.json",
    entryModule: path.resolve(__dirname, "./ClientApp/components/main.module#MainModule"),
});
aotPlugin._compilerHost._resolve = function(path_to_resolve) {
    path_1 = require("path");
    path_to_resolve = aotPlugin._compilerHost._normalizePath(path_to_resolve);
    if (path_to_resolve[0] == '.') {
        return aotPlugin._compilerHost._normalizePath(path_1.join(aotPlugin._compilerHost.getCurrentDirectory(), path_to_resolve));
    }
    else if (path_to_resolve[0] == '/' || path_to_resolve.match(/^\w:\//)) {
        return path_to_resolve;
    }
    else {
        return aotPlugin._compilerHost._normalizePath(path_1.join(aotPlugin._compilerHost._basePath, path_to_resolve));
    }
};
```

**Comment by DanWahlin** [comment] 2017-03-26 17:04
Thanks for sharing @tinchou! That fixed it for me. Was having the same problem on Windows 10....wasted more time than I care to admit on this issue. :-)

**Comment by tinchou** [comment] 2017-03-26 18:51
Yeah, that sucks. The problem is not knowing which one is the broken
component after a big update. I was lucky I was glancing over that repo's
issues a couple of hours before updating myself.

On Sun, Mar 26, 2017, 10:04 Dan Wahlin <notifications@github.com> wrote:

Thanks for sharing @tinchou <https://github.com/tinchou>! That fixed it for
me. Was having the same problem on Windows 10....wasted more time than I
care to admit on this issue. :-)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/angular/angular-cli/issues/5329#issuecomment-289298412>,
or mute the thread

**Comment by tavelli** [comment] 2017-04-12 20:44
@tinchou can you share plugins context of your webpack config for this workaround?

**Comment by tinchou** [comment] 2017-04-13 00:49
What do you mean? This?

```js

    plugins: [
        aotPlugin,
        new webpack.optimize.UglifyJsPlugin({
            mangle: { screw_ie8: true },
            compress: {
                screw_ie8: true,
                warnings: false,
            }
        }),
        new webpack.LoaderOptionsPlugin({
            minimize: true,
            debug: false
        }),
    // ....
```

**Comment by tavelli** [comment] 2017-04-13 17:36
@tinchou yea thanks, i had dumb mistake with var aotPlugin = new ngToolsWebpack.AotPlugin({ part defined after webpack config instead of before

**Comment by hheexx** [comment] 2017-04-13 19:48
@tinchou screw_ie8: true, is default. You don't need that.

**Comment by bkdotcom** [comment] 2017-04-14 19:29
where is this `webpack.config.js` file everyone speaks of along with the aotPlugin settings?

**Comment by tinchou** [comment] 2017-04-14 23:11
I'm not using the CLI, but webpack with @ngtools/webpack plugin. I think
you can "eject" your webpack configuration with the CLI if you need to use
this workaround.

**Comment by mariussl** [comment] 2017-04-19 15:00
thx @tinchou for the workaround, works perfectly for me (win7x64)

**Comment by rbarcelos** [comment] 2017-04-24 15:57
Any ETA for a final fix for this? Thanks

**Comment by hheexx** [comment] 2017-04-25 17:05
Deployed in 1.3.1

**Comment by mariussl** [comment] 2017-04-26 09:36
thx @hheexx . bugfix confirmed.

**Comment by filipesilva** [comment] 2017-05-23 11:53
Fixed by https://github.com/angular/angular-cli/pull/6063

**Closed by filipesilva** 2017-05-23 11:53 UTC
Labels: need: investigation

**Comment by uscbsitric** [comment] 2017-11-03 03:00
I solved min by pressing Ctrl + C on the terminal to end the current npm start,
then ran the entire setup with a npm start.

This error occurred to me when I was switching branches.
