### ISSUE TITLE
Application builder grows output folder every change in watch mode

### ISSUE THREAD

**Issue by kyesil** [angular/angular-cli#29137] opened 2024-12-14 18:32 UTC
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

browser builder

### Description

With new application builder,
When compiling with  “ng build --watch”, if “namedChunks” is turned on, new chunk files are add in the output folder with every file change after the output folder gets bigger and bigger.

### Minimal Reproduction

``` 
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath":  "dist",
            "index": "src/index.html",
            "browser": "src/main.ts",
            "polyfills": [
              "zone.js"
            ],
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/assets
            ],
			...
          },
			....
              "outputHashing": "all"
            },
            "development": {
              "optimization": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
```

1. Change  `"development"."namedChunks": true` angular.json  
2. Run ng build --watch.
3. Make a change to the *.ts file in app folder.

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 19.0.5
Node: 22.12.0
Package Manager: npm 10.9.2
OS: win32 x64

Angular: 19.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.5
@angular-devkit/build-angular   19.0.5
@angular-devkit/core            19.0.5
@angular-devkit/schematics      19.0.5
@angular/cdk                    19.0.3
@angular/cli                    19.0.5
@angular/material               19.0.3
@schematics/angular             19.0.5
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by alan-agius4** [comment] 2024-12-14 18:45
Duplicate of https://github.com/angular/angular-cli/issues/26595

**Closed by alan-agius4** 2024-12-14 18:45 UTC
