### ISSUE TITLE
Add ability to specify additional style preprocessor options

### ISSUE THREAD

**Issue by StevenBarnettST** [angular/angular-cli#7733] opened 2017-09-18 20:45 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.4.0
node: 8.4.0
os: win32 x64
@angular/animations: 5.0.0-beta.6
@angular/cdk: 2.0.0-beta.10
@angular/common: 5.0.0-beta.6
@angular/compiler: 5.0.0-beta.6
@angular/core: 5.0.0-beta.6
@angular/forms: 5.0.0-beta.6
@angular/http: 5.0.0-beta.6
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 5.0.0-beta.6
@angular/platform-browser-dynamic: 5.0.0-beta.6
@angular/router: 5.0.0-beta.6
@angular/cli: 1.4.0
@angular/compiler-cli: 5.0.0-beta.6
@angular/language-service: 5.0.0-beta.6
typescript: 2.5.2

### Desired functionality.

Please add the ability to specify additional style preprocessor options to be used during compile.

Specifically, I want to be able to enable strict math (`strictMath: true`) for the Less preprocessor.

### Mention any other details that might be useful.

This option is enabled by adding an additional property to the less-loader options, like the second example in the [less-loader readme](https://github.com/webpack-contrib/less-loader/blob/9ed895fd8bbeb919e42b9137cdf0858a654b6275/README.md):

                loader: "less-loader", options: {
                    strictMath: true,
                    noIeCompat: true
                }

The `stylePreprocessorOptions` setting in the [config schema](https://github.com/angular/angular-cli/wiki/angular-cli) sounds like a great place to add configuration for this. The options [already being configured](https://github.com/angular/angular-cli/blob/260c781642688dcd637bdb340e38375b53911933/packages/%40angular/cli/models/webpack-configs/styles.ts#L137) could be merged with any specified in that config object.

**Comment by AhsanAyaz** [comment] 2017-09-19 00:20
Duplicate of #7624, #7644, #7647, #7708, #7715, #7719, #7721 & #7522

**Comment by StevenBarnettST** [comment] 2017-09-19 18:10
@AhsanAyaz this is a different issue than the other ones addressed by #7648.

**Comment by AhsanAyaz** [comment] 2017-09-19 18:38
@StevenBarnettST you're right. I removed it from the comment there.

**Comment by clydin** [comment] 2017-09-19 20:48
An argument could be made to always enabled the `strictMath` option.  There's really no need to optimize any math expressions in a dev mode.  In production, `cssnano` should already handle this category of optimization.

**Comment by StevenBarnettST** [comment] 2017-09-19 21:58
@clydin While personally I'd be fine with having `strictMath` always enabled, it would be a breaking change for people with code that assumes it is disabled. In addition, [the Less documentation says](http://lesscss.org/usage/#command-line-usage-options) they "originally planned to default this to true in the future, but it has been a controversial option".

**Comment by alan-agius4** [comment] 2021-05-31 11:45
Closing, since this has received little to no activity since it has been open since 2017.

You can use a 3rd party builder to extend the Angular CLI and provide additional style preprocessor options.

**Closed by alan-agius4** 2021-05-31 11:45 UTC
Labels: comp: devkit/build-angular, type: feature
