### ISSUE TITLE
dev-server executor expects certain options, but error message does not give away how to solve

### ISSUE THREAD

**Issue by fhaag** [angular/angular-cli#27935] opened 2024-06-26 15:43 UTC
### Command

run

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Using another target for `dev-server` than `build` results in an unclear error message.

### Minimal Reproduction

In my `project.json` file, I have a `testserve` target that uses the `@angular-devkit/build-angular:dev-server` executor:
```json
"testserve": {
	"executor": "@angular-devkit/build-angular:dev-server",
	"configurations": {
		"development": {
			"buildTarget": "myProject:build:development"
		}
	},
	"defaultConfiguration": "development"
},
```
`build` is another target in the same `project.json` file. When invoking `nx run testserve`, this works flawlessly.

Now, I have declared a new target for testing purposes:
```json
"testoutput": {
	"command": "echo 'TEST'"
}
```
On its own, that target works - `nx run testoutput` results in the text `TEST` to be printed to the console.

Then, I have tried to use that target for `dev-server` instead of `build`:
```json
"testserve": {
	"executor": "@angular-devkit/build-angular:dev-server",
	"configurations": {
		"development": {
			"buildTarget": "myProject:testoutput"
		}
	},
	"defaultConfiguration": "development"
},
```
The expected outcome of invoking `nx run testserve` is that it will output the text `TEST`, and maybe repeat to do so whenever the live reload of `dev-server` strikes.

However, the actual outcome is this error:
> TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined

I suspect only a subset of targets with certain options are eligible to be used here, but unfortunately, the error message does not give away what exactly is required (nor does the project's readme file).

---

It seems when you use `nx init` to initialize NX using the current version, the attribute is called `browserTarget` instead of `buildTarget`. However, the result is exactly the same.

The issue can be observed in this repro with the minimal sample modified as described above: https://github.com/fhaag/angular-cli-bug-repro/tree/buildtarget-issue

### Exception or Error

```text
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:167:9)
    at readTsconfig (C:\...\NX\targets\repro-app\node_modules\@angular-devkit\build-angular\src\utils\read-tsconfig.js:44:51)
    at configureI18nBuild (C:\...\NX\targets\repro-app\node_modules\@angular-devkit\build-angular\src\utils\i18n-options.js:125:61)
    at generateI18nBrowserWebpackConfigFromContext (C:\...\NX\targets\repro-app\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:67:80)
    at setup (C:\...\NX\targets\repro-app\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js:141:126)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Your Environment

```text
Angular CLI: 17.1.3
Node: 18.17.0
Package Manager: npm 8.9.0
OS: win32 x64

Angular: 17.1.3
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1701.3
@angular-devkit/build-angular    17.1.3
@angular-devkit/core             17.1.3
@angular-devkit/schematics       17.1.3
@angular-devkit/schematics-cli   17.1.3
@angular/cdk                     17.1.2
@angular/material                17.1.2
@schematics/angular              17.1.3
rxjs                             7.8.1
typescript                       5.3.3
webpack                          5.90.1
zone.js                          0.14.3
```

**Comment by alan-agius4** [comment] 2024-06-26 15:53
@fhaag, I suspect that this is an NX issue and not an Angular CLI bug. Can you please provide a reproduction using the Angular CLI? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by fhaag** [comment] 2024-06-26 16:12
@alan-agius4 I have uploaded the minimal sample with the described modifications applied and linked to it in the description: https://github.com/fhaag/angular-cli-bug-repro/tree/buildtarget-issue

**Comment by alan-agius4** [comment] 2024-06-26 16:27
Duplicate of https://github.com/angular/angular-cli/issues/27937

**Closed by alan-agius4** 2024-06-26 16:27 UTC
Labels: needs: repro steps
