### ISSUE TITLE
Tests are not rebuilding

### ISSUE THREAD

**Issue by dagi12** [angular/angular-cli#5402] opened 2017-03-13 12:42 UTC
### Versions.
1.0.0-rc1

### Repro steps.

- Create new app with `ng new angular-app`
- Run tests `ng test`
- You will see `Executed 3 of 3 SUCCESS`
- In `app.component.spec.ts` in some test, paste `throw new Error();`
- CLI will print
- `Executed 3 of 3 SUCCESS (0.16 secs / 0.155 secs)` 
- As you see karma prints that every test ends with success despite fact that one them should fail. 
- To rebuild your tests you have to close test CLI with Ctrl+C and launch it again. This finally make CLI to print proper message `Chrome 56.0.2924 (Windows 10 0.0.0) AppComponent should render title in a h1 tag FAILED
        Failed: Error
            at webpack:///~/@angular/core/bundles/core-testing.umd.js:54:0 <- src/test.ts:32879:30 [ProxyZone]
            at webpack:///~/@angular/core/bundles/core-testing.umd.js:105:0 <- src/test.ts:32930:21 [ProxyZone]
            at AsyncTestZoneSpec.onInvoke (webpack:///~/zone.js/dist/async-test.js:49:0 <- src/test.ts:63577:39) [ProxyZone]
            at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:76:0 <- src/test.ts:64279:39) [ProxyZone]
            at Zone.run (webpack:///~/zone.js/dist/zone.js:126:0 <- src/polyfills.ts:1642:43) [ProxyZone => ProxyZone]`
- `Chrome 56.0.2924 (Windows 10 0.0.0): Executed 3 of 3 (1 FAILED) (0.326 secs / 0.173 secs)`

### Info
- Issue is very annoying and slows down development process.
- The problem occurs after switching to 1.0.0-rc1. It works correctly in previous version (I use some beta, don't remember which exactly). 
- I think it's related to [5404](https://github.com/angular/angular-cli/issues/5404)

**Comment by ktriek** [comment] 2017-03-13 20:14
I have the same issue with after updating to rc1, I didn't have this issue before.

**Comment by maddev0** [comment] 2017-03-14 11:10
Experiencing the same issue since switching to 1.0.0-rc1. Sometimes tests are not automatically rebuilt. I put some changes into spec and save the file, `ng test` rebuilds tests but showing the results for unchanged spec. Restarting `ng test` solves the issue.

Sometimes automatic rebuild fails with the following message (actual project directory is replaced with PROJECT_DIR):
```
Chrome 56.0.2924 (Mac OS X 10.9.5) ERROR
  Uncaught Error: Module build failed: Error
      at WebpackCompilerHost.populateWebpackResolver (PROJECT_DIR/node_modules/@ngtools/webpack/src/compiler_host.js:135:51)
      at _donePromise.Promise.resolve.then.then.then.then (PROJECT_DIR/node_modules/@ngtools/webpack/src/plugin.js:327:32)
      at process._tickCallback (internal/process/next_tick.js:103:7)
  at src/test.ts:112583
```

**Comment by markheron91** [comment] 2017-03-14 15:52
Can confirm that I'm also getting this error running v1.0.0-rc.2 - saving files seems to kick off a new build but its as if nothing has been changed until the process is completely killed and restarted again.

**Comment by coryrylan** [comment] 2017-03-16 16:28
@markheron91 I have similar type errors like what you described. Unfortunately the typeRoot patch I mention in #5351 only seems to work part of the time for me. If a save a lingle spec file I get the type errors with Jasmine again.

**Comment by atom-morgan** [comment] 2017-03-16 16:55
@coryrylan @markheron91 My `tsconfig.json` file has `typeRoots` as listed in the issue above and I'm still encountering this problem.

**Comment by filipesilva** [comment] 2017-03-18 12:40
This seems a dupe of https://github.com/angular/angular-cli/issues/5332. It looks like sometimes past builds are served on `ng test` instead.

If someone has a simple repro of what you're experiencing here please post in #5332 to keep it in one place.

**Closed by filipesilva** 2017-03-18 12:40 UTC
