### ISSUE TITLE
"The option '--flat' is not registered with the generate command"

### ISSUE THREAD

**Issue by dtgriscom** [angular/angular-cli#3403] opened 2016-12-05 13:56 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?

    $ cat /proc/version
    Linux version 3.13.0-96-generic (buildd@lcy01-09) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016

Note: running on Vagrant VM under OS X 10.10.5; directory is shared with host OS

### Versions.

    $ ng --version
    Could not start watchman; falling back to NodeWatcher for file system events.
    Visit http://ember-cli.com/user-guide/#watchman for more info.
    angular-cli: 1.0.0-beta.18
    node: 6.9.1
    os: linux x64

### Repro steps.

This is an Angular 2 project generated by the CLI, and worked on extensively by me. In the past, the command:

    ng generate component myComponent --flat

would generate the files for myComponent without embedding it into a `myComponent\` directory. However, today, in the same environment, I got a warning, and the --flat option was ignored:

    $ ng generate module --flat utilities
    The option '--flat' is not registered with the generate command. Run `ng generate --help` for a list of supported options.
    Could not start watchman; falling back to NodeWatcher for file system events.
    Visit http://ember-cli.com/user-guide/#watchman for more info.
    installing module
      create src/app/utilities/utilities.module.ts
    installing component
      create src/app/utilities/utilities.component.css
      create src/app/utilities/utilities.component.html
      create src/app/utilities/utilities.component.spec.ts
      create src/app/utilities/utilities.component.ts

    

### The log given by the failure.

No log was generated.

### Mention any other details that might be useful.

Again, I've successfully done this before on this project (I even checked my history). The problem isn't specific to the module name "utilities"; other names give the same results. I've tried restarting the Vagrant VM: no change. Something must have changed or become broken, but I have no clue what.

Interestingly, if I try using `ng generate class` with the `--flat` flag, I get the same warning, but the class is NOT put into its own directory:

    $ ng generate class --flat anotherClass
    The option '--flat' is not registered with the generate command. Run `ng generate --help` for a list of supported options.
    Could not start watchman; falling back to NodeWatcher for file system events.
    Visit http://ember-cli.com/user-guide/#watchman for more info.
    installing class
      create src/app/another-class.ts

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment] 2016-12-05 23:43
`class` and `module` don't have flat mode. For `module` I don't think it makes sense, and `class` is flat by default.

Closing this as working as intended, but we can keep the conversation going. What was the behaviour you were expecting?

**Comment by hansl** [comment] 2016-12-05 23:44
For reference, see [class](https://github.com/angular/angular-cli/wiki/class) and [module](https://github.com/angular/angular-cli/wiki/module).

**Closed by hansl** 2016-12-05 23:43 UTC

**Comment by dtgriscom** [comment] 2016-12-06 02:27
If this is "working as intended", then that's fine, but the documentation is misleading. The `ng generate <type>` command is documented as having a `--flat` option; there's no hint that `--flat` is type-specific. See https://cli.angular.io/reference.pdf . If only components are ever put into their own directories (is that true?) then the doc should state that, and that `--flat` only works with components (and, in fact, `--flat` shouldn't work with classes, as it's a NOP).

(thanks...)

**Comment by rfvoltolini** [comment] 2017-03-08 17:55
It's also important to notice that the embedded help: `ng help generate` and the [wiki](https://github.com/angular/angular-cli/wiki/generate-module) also suggests that `ng g module` has a `--flat` option, which does not seem to work (option is silently ignored) as for ng version 1.0.0-rc.1.

Whether this option for the `module` generator makes sense or not, I am not sure, but the docs are surely misleading. For instance, if the feature directory gets manually created:
```bash
mkdir my-module
cd my-module
ng g module my-module --flat
    create src/app/my-module/my-module/my-module.module.ts
```
*Notice the doubled directory `my-module`

**Comment by simeyla** [comment] 2018-01-02 07:54
The documentation is misleading in that it says

--flat 
Flag to indicate if a dir is created.

But what it really means is:
Flag to indicate if a dir is NOT created.

**Comment by muhammedjasin** [comment] 2018-01-06 15:09
will this issue get resolved when we update the cli?
