### ISSUE TITLE
wrong style extension used when generating component

### ISSUE THREAD

**Issue by jasedwards** [angular/angular-cli#11045] opened 2018-05-28 21:59 UTC
### Versions
```
Angular CLI: 6.0.1
Node: 8.9.4
OS: win32 x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.5
@angular-devkit/build-angular     0.6.5
@angular-devkit/build-optimizer   0.6.5
@angular-devkit/core              0.6.5
@angular-devkit/schematics        0.6.1
@ngtools/webpack                  6.0.5
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

* ng new testapp --style scss
* ng g application myapp --style scss
* ng g c mycomponent

### Observed behavior
```
when generating the new workspace nothing is added to angular.json to say the default extension should be scss.  When you generate the app you do get the entry in schematics for that app saying styleext is scss.  the app component does have the proper style extension.  However, the component that gets generated is css instead of scss
```

### Desired behavior
the component gets generated with correct extension

### Mention any other details that might be useful (optional)
I should mention that my global cli is version 6.0.5.
Here is my angular.json:
```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "",
  "projects": {
    "myapp": {
      "root": "apps/myapp/",
      "sourceRoot": "apps/myapp/src",
      "projectType": "application",
      "prefix": "styletest",
      "schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/apps/myapp",
            "index": "apps/myapp/src/index.html",
            "main": "apps/myapp/src/main.ts",
            "polyfills": "apps/myapp/src/polyfills.ts",
            "tsConfig": "apps/myapp/tsconfig.app.json",
            "assets": [
              "apps/myapp/src/favicon.ico",
              "apps/myapp/src/assets"
            ],
            "styles": [
              "apps/myapp/src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "apps/myapp/src/environments/environment.ts",
                  "with": "apps/myapp/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "myapp:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "myapp:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "myapp:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "apps/myapp/src/test.ts",
            "polyfills": "apps/myapp/src/polyfills.ts",
            "tsConfig": "apps/myapp/tsconfig.spec.json",
            "karmaConfig": "apps/myapp/karma.conf.js",
            "styles": [
              "apps/myapp/src/styles.scss"
            ],
            "scripts": [],
            "assets": [
              "apps/myapp/src/favicon.ico",
              "apps/myapp/src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "apps/myapp/tsconfig.app.json",
              "apps/myapp/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "myapp-e2e": {
      "root": "apps/myapp-e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "apps/myapp-e2e/protractor.conf.js",
            "devServerTarget": "myapp:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "apps/myapp-e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "cli": {
    "warnings": {
      "typescriptMismatch": false,
      "versionMismatch": false
    },
    "defaultCollection": "@nrwl/schematics"
  },
  "defaultProject": "myapp"
}
```

**Comment by humphrycc** [comment] 2018-05-29 01:15
@jasedwards `--style=scss` works perfectly.

$ ng new web-interface --style=scss --skip-tests --routing -v 
CREATE web-interface/README.md (1029 bytes)
CREATE web-interface/angular.json (4022 bytes)
CREATE web-interface/package.json (1317 bytes)
CREATE web-interface/tsconfig.json (384 bytes)
CREATE web-interface/tslint.json (2805 bytes)
CREATE web-interface/.editorconfig (245 bytes)
CREATE web-interface/.gitignore (503 bytes)
CREATE web-interface/src/environments/environment.prod.ts (51 bytes)
CREATE web-interface/src/environments/environment.ts (631 bytes)
CREATE web-interface/src/favicon.ico (5430 bytes)
CREATE web-interface/src/index.html (299 bytes)
CREATE web-interface/src/main.ts (370 bytes)
CREATE web-interface/src/polyfills.ts (3194 bytes)
CREATE web-interface/src/test.ts (642 bytes)
CREATE web-interface/src/assets/.gitkeep (0 bytes)
**CREATE web-interface/src/styles.scss (80 bytes)**
CREATE web-interface/src/browserslist (375 bytes)
CREATE web-interface/src/karma.conf.js (964 bytes)
CREATE web-interface/src/tsconfig.app.json (194 bytes)
CREATE web-interface/src/tsconfig.spec.json (282 bytes)
CREATE web-interface/src/tslint.json (314 bytes)
CREATE web-interface/src/app/app-routing.module.ts (245 bytes)
CREATE web-interface/src/app/app.module.ts (393 bytes)
CREATE web-interface/src/app/app.component.scss (0 bytes)
CREATE web-interface/src/app/app.component.html (1173 bytes)
CREATE web-interface/src/app/app.component.ts (208 bytes)
CREATE web-interface/e2e/protractor.conf.js (752 bytes)
CREATE web-interface/e2e/src/app.e2e-spec.ts (299 bytes)
CREATE web-interface/e2e/src/app.po.ts (208 bytes)
CREATE web-interface/e2e/tsconfig.e2e.json (213 bytes)

**Comment by jasedwards** [comment] 2018-05-29 11:11
@humphrycc  You are correct that the original styles file has the correct extension.  so does app.component style sheet.  create a component now and it will generate css instead of scss.  Here is a screen shot of my apps file structure.  the last thing I ran was ng g c testcomp.  it created css instead of scss.    

![image](https://user-images.githubusercontent.com/5818023/40655430-f551a114-6306-11e8-9c59-2228d84e15bf.png)

And here is the relevant part of angular.json.  would also have expected scss to be listed somewhere in the global schematics section since I set that when generating the workspace as well but nothing there:

![image](https://user-images.githubusercontent.com/5818023/40655487-187b8f7e-6307-11e8-8092-0c3084ceeda3.png)

**Comment by cvgaviao** [comment] 2018-05-29 15:29
Also, the `ng new ` command is not respecting a global styleext default previous set using the command:

>  ng config -g schematics.@schematics/angular.component '{ styleext: "scss"}'

**Comment by FrozenPandaz** [comment] 2018-05-30 02:35
I did some investigating but ultimate could not decipher what was wrong but my findings might be helpful.

* The project's `root` property might have something to do with it.
  * Changing the Nx project's `root` to `''` allows it to resolve the default schematic options.
  * Changing a fresh Angular CLI v6 project but with the root changed to `apps/app1` makes the default schematic options not resolvable

**Comment by ysfjwd** [comment] 2018-06-01 11:59
i am here to report the same bug.

**Comment by gkamperis** [comment] 2018-06-29 20:02
As a workaround try setting the global default:

`ng config schematics.@schematics/angular:component.styleext scss`

**Comment by Brocco** [comment] 2018-07-20 20:06
I have not been able to reproduce this locally using the latest version of master (which will become version 6.1.0).

![image](https://user-images.githubusercontent.com/1565117/43022856-af055ada-8c36-11e8-8fa0-83246b592639.png)

I know the screenshot doesn't show the whole angular.json but to give it context, the value is inside fo the application project.

**Comment by hansl** [comment] 2018-07-30 16:22
Closing this as fixed. I tested it locally and could not reproduce. If you still have this issue, please file a new issue at https://github.com/angular/angular-cli/issues/new

**Closed by hansl** 2018-07-30 16:22 UTC
Labels: comp: schematics/angular, freq3: high, need: more info, severity5: regression, type: bug, workaround4: none

**Comment by baio** [comment] 2018-08-14 20:06
@Brocco please see here Reproduced in repo https://github.com/baio/ng-holistic

**Comment by gkamperis** [comment] 2018-08-15 06:44
@baio you are using a different schematics collection.

see
https://github.com/nrwl/nx/issues/158
and
https://github.com/nrwl/nx/issues/533
