### ISSUE TITLE
Angular-cli & Webpack & ng test  (msg || "").replace is not a function

### ISSUE THREAD

**Issue by Chabane** [angular/angular-cli#1608] opened 2016-08-09 12:50 UTC
Hi,

I have an error when I execute the command ng test. I tried to add -watch=false -build=false, it doesn't work.

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack
node: 6.3.1
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Migrating from angular-cli@broccoli

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Missing error handler on `socket`.
TypeError: (msg || "").replace is not a function

5. Mention any other details that might be useful.
Nop.

Thanks.

**Comment by deebloo** [comment] 2016-08-09 21:48
I am having the same issue but only since updating to the newest build for rc5

**Comment by vapits** [comment] 2016-08-10 09:10
I'm having the same (and similar) issues after updating to RC5

**Comment by westonpace** [comment] 2016-08-12 17:49
If you upgrade to karma 1.0 or higher you will get a different error message.  The one you are posting is a red-herring message caused by an issue in karma so it doesn't say much about the underlying issue.

**Comment by vapits** [comment] 2016-08-12 20:10
@Chabane I manage to fix it by upgrading to @webpack version and of course RC5,

**Comment by mhamel06** [comment] 2016-08-13 15:43
@Chabane  If it is the same issue I was running into, the actual error message was only clear by checking the karma debugging button in chrome. 
<img width="808" alt="screen shot 2016-08-13 at 11 41 52 am" src="https://cloud.githubusercontent.com/assets/473551/17644075/f9a70b88-614a-11e6-884d-7c50ec473fb5.png">

I think this pull request should fix the issue for new projects and be easy to update in existing projects. https://github.com/angular/angular-cli/pull/1680

**Comment by filipesilva** [comment] 2016-08-19 03:04
Fixed by https://github.com/angular/angular-cli/pull/1680.

**Closed by filipesilva** 2016-08-19 03:04 UTC
