### ISSUE TITLE
how to change package version number for angular cli library using ng command

### ISSUE THREAD

**Issue by aniruddhadas9** [angular/angular-cli#10825] opened 2018-05-12 22:49 UTC
### Versions
```
Angular CLI: 6.0.1
Node: 10.1.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.1
@angular-devkit/core         0.6.1
@angular-devkit/schematics   0.6.1
@schematics/angular          0.6.1
@schematics/update           0.6.1
rxjs                         6.1.0
typescript                   2.7.2

```

### Observed behavior
I have created an angular library using `angular cli` library command `ng g library libname` and published it into npm repository. Now whenever I change something in the library, I have to go to the library folder and run `npm version <version-type>` to update version number before publishing to npm. I did not see a `ng` command to update the version number of the library.

There is no command `ng` command to update the version number of the library? Or is there one?

### Desired behavior
if  a`ng` command to update the library version (similar to `npm version <version-type>`) can be provided, it can be done easily and don't have to do it manually by going inside the library folder.

**Comment by Brocco** [comment] 2018-05-14 15:01
This is a feature request as this functionality does not exist.

**Comment by kieranjohn** [comment] 2019-02-12 03:40
the library folder has its own package json, you could update the version using a script from main project
`"build-patch":"cd ./projects/{your_project} && npm version patch && cd .. && ng build",`

**Comment by clydin** [comment] 2020-05-30 01:59
Duplicate of #11486

**Closed by clydin** 2020-05-30 01:59 UTC
Labels: comp: devkit/build-ng-packagr, type: feature
