### ISSUE TITLE
Build failure within --project but not regular build when using generic classes

### ISSUE THREAD

**Issue by cjonasw** [angular/angular-cli#12444] opened 2018-10-02 16:57 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

I am trying to access <any> properties on a generic class with a library. The build fails when this code is within a project/library (`--project`) but the exact same setup within an Angular app, it compiles with no errors.

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps

So create a  library and a component within that library:

```
ng generate library questions
ng generate component question --project=questions
``` 

this is the content of the `question.component.ts`:

```
import { Component, OnInit, Input } from '@angular/core';
import { QuestionBase } from 'questions/lib/question-base';

@Component({
  selector: 'lib-question',
  templateUrl: './question.component.html',
  styleUrls: ['./question.component.css']
})
export class QuestionComponent implements OnInit {

  @Input() field: QuestionBase<any>;

  constructor() { }

  ngOnInit() {
  }

}
```

this is the content of `question.component.html`:

```
<p>
  test works!

  {{field.type}}
</p>
```

this is the content of `question-base.ts` (from https://angular.io/guide/dynamic-form#question-model)

```
export class QuestionBase<T> {
  value: T;
  key: string;
  label: string;
  required: boolean;
  order: number;
  controlType: string;
 
  constructor(options: {
      value?: T,
      key?: string,
      label?: string,
      required?: boolean,
      order?: number,
      controlType?: string
    } = {}) {
    this.value = options.value;
    this.key = options.key || '';
    this.label = options.label || '';
    this.required = !!options.required;
    this.order = options.order === undefined ? 1 : options.order;
    this.controlType = options.controlType || '';
  }
}
```

This does not compile correct with errors below. However, this exact same component and class code within an angular app rather than "project"/"library"... it compiles fine.

Any help appreciated, please let me know if you need more info.

### The log given by the failure

```
BUILD ERROR
projects/questions/src/lib/question/question.component.ts.QuestionComponent.html(1,4): : Property 'type'does not exist on type 'QuestionBase<any>'.

Error: projects/questions/src/lib/question/question.component.ts.QuestionComponent.html(1,4): : Property'type' does not exist on type 'QuestionBase<any>'.
```

### Desired functionality

To compile with no errors, just like the regular build does.

**Comment by alan-agius4** [comment] 2018-10-02 17:04
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

That said, the error is correct as there is no `type` public member in `QuestionBase`.  That said, I am not sure why you are trying to pass an instance of a class as an `Input` field.

**Comment by alan-agius4** [comment] 2018-10-03 05:35
I had a look at this, when using `ng build - aot` at application level the error is shown correctly. This is due that template checks are only done when using `AOT` and library compilation always use `AOT`. 

Closing as it's working as intended.

**Closed by alan-agius4** 2018-10-03 05:35 UTC
Labels: need: more info

**Comment by cjonasw** [comment] 2018-10-03 12:01
Thanks for looking into this. This code is actually within the Angular docs, not sure where to raise where that should be corrected.

https://angular.io/guide/dynamic-form#question-model

Used in the same way. An instance of a class which extends the `QuestionBase` which does have a `type` property is passed into the `@Input`.

**Comment by alan-agius4** [comment] 2018-10-04 05:47
In yourcase the class that you are proving in the input doesn’t have `type` as a member and hence the error. 

The ones in the Angular docs have a slight different implementation, which are extending the base class and declaring the `type` in the extended class.

**Comment by cjonasw** [comment] 2018-10-04 12:57
Sorry, I've condensed the project to highlight the issue,

I've basically had the same setup as the dynamic forms in Angular docs, but the build fails on that type issue.

**Comment by cjonasw** [comment] 2018-10-04 13:03
I manually made each element, but it's identical pretty much.

**Comment by ghtjiann4321** [comment] 2018-10-08 07:31
Any updates on this? The dynamic form tutorial in the Angular Docs doesn't compile when adding --aot. It says 'type' doesn't exist on type 'QuestionBase<any>'

**Comment by h4t0n** [comment] 2019-01-12 08:32
Any updates on this? I'm following the tutorial and I have implemented (ad a library) a class like QuestionBase and its subclasses. But I can't use subclasses fields.
