### ISSUE TITLE
Add .editorconfig support for CLI generated code

### ISSUE THREAD

**Issue by KBeDeveloper** [angular/angular-cli#16684] opened 2020-01-16 17:41 UTC
I'd like to generate new files (from Angular Schematics) with the [.editorconfig](https://editorconfig.org/) indentation/spaces specifications.

I know, this is a very low priority feature request, but would be comfortable to have.

**Comment by alan-agius4** [comment] 2020-01-16 17:45
@KBeDeveloper thanks for the issue, however I am not understanding the problem here, as we do generate an `.editorconfig` when creating a workspace.

https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/workspace/files/__dot__editorconfig.template

Can you please elaborate on the problem? Thanks.

**Comment by KBeDeveloper** [comment] 2020-01-16 17:54
When I generate a group of files from Angular Schematics with the <code>$ ng g *schematic_name* *new_name*</code> command, the code generated doesn't use specifications declared in the .editorconfig file.

**Comment by filipesilva** [comment] 2020-01-23 10:02
We have a related option;
```
  --lint-fix
    When true, applies lint fixes after generating the component.
```

This doesn't use editor config. Instead it uses tslint and the fix option there. The idea is that you put fixable lint rules (like https://palantir.github.io/tslint/rules/indent/) and tslint will fix the generated files to your style.

**Comment by KBeDeveloper** [comment] 2020-01-23 12:41
> We have a related option;
> 
> ```
>   --lint-fix
>     When true, applies lint fixes after generating the component.
> ```
> 
> This doesn't use editor config. Instead it uses tslint and the fix option there. The idea is that you put fixable lint rules (like https://palantir.github.io/tslint/rules/indent/) and tslint will fix the generated files to your style.

Have I to specify the PATH of my tslint file? I've used this flag but there's no difference between the code generated with or without it.

I added this line to my tslint file:

```
"indent": [true, "tabs", 3]
```

**Comment by filipesilva** [comment] 2020-01-23 13:18
You shouldn't have to, no. It should just work. Maybe there's a bug in there right now.

**Comment by filipesilva** [comment] 2020-01-27 11:15
Brought it up with the time and someone remembered what was happening here. It has to do with the number of spaces and the note in https://palantir.github.io/tslint/rules/indent/:
```
NOTE: auto-fixing will only convert invalid indent whitespace to the desired type, it will not fix invalid whitespace sizes.
```

Support for this fixer was added in https://github.com/palantir/tslint/pull/2723. There's more on this in https://github.com/palantir/tslint/issues/581, and https://github.com/palantir/tslint/issues/2814. It sounds like this won't progress much further on tslint because it's going to be deprecated soon.

**Comment by KBeDeveloper** [comment] 2020-01-29 00:40
Breaking news: https://github.com/palantir/tslint/issues/4534

**Comment by filipesilva** [comment] 2020-01-29 00:48
Yes we are aware of that, and making migration plans.

**Comment by alan-agius4** [comment] 2020-01-30 07:49
Closing as a duplicate of https://github.com/angular/angular-cli/issues/10777

**Closed by alan-agius4** 2020-01-30 07:49 UTC
Labels: comp: schematics/angular, priority: 3 (nice to have), type: feature
