### ISSUE TITLE
Rename a component in Angular CLI

### ISSUE THREAD

**Issue by CodeDroid999** [angular/angular-cli#24489] opened 2023-01-05 17:21 UTC
### Command

generate

### Description

No command exists that can modify the names of any files created by the component create command. Ts, HTML, CSS/SCSS, and.spec.ts files must therefore be manually renamed and changed.

I frequently use the Angular CLI, and I believe that having this option would be useful since sometimes we merely construct angular components and then need to rename them. The produced angular component, directive, etc. must be deleted and the procedure to create the component must be executed again because there is no rename command.

### Describe the solution you'd like

Here is some additional commentary. It has the advantage of adhering to the newly developed style guide when CLI builds new components and other components. Maybe the style guide truly needs to hear this comment. That much duplication and naming is unquestionably produced. We receive N copies of each item's name across various folders and files when we add something using this tools, and we also receive N copies of each item's name in two separate ways. This causes a lot of friction when it's time to rename, which happens frequently in actual applications. There doesn't seem to be anything that can be done about it as it has already been decided that each name will be used twice as an official style (or more).

### Describe alternatives you've considered

In VSCode, for instance, you can see error messages in the files explorer pane on the left when something is wrong (imported file that isn't there, non-existent component, etc.). Therefore, when I wanted to rename a component, I simply changed the names of its folder and internal files. After that, I simply followed all the error cues and changed the component's name appropriately.

**Comment by clydin** [comment] 2023-01-06 14:48
Duplicate of #900
For a overview of that issue please see this comment: https://github.com/angular/angular-cli/issues/900#issuecomment-642889197
As a result of that comment, an feature request issue was filed with the Angular language service to support renaming which can be found here: https://github.com/angular/angular-cli/issues/24489

**Closed by clydin** 2023-01-06 14:48 UTC
