### ISSUE TITLE
Get an error: "Index html generation failed"

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular-cli#21001] opened 2021-05-31 14:06 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ^11.0.0

### Description

 When I add some styles from node_modules to angular.json and then try to build a project I get the error

## 🔬 Minimal Reproduction
1. Clone repo https://github.com/dxvladislavvolkov/ngstyles
2. Run npm i
3. Run ng build

## 🔥 Exception or Error

<pre><code>

✖ Index html generation failed.
undefined:5:111389: property missing ':'
</code></pre>

## 🌍 Your Environment

<pre><code>

angular@12.0.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-05-31 14:12
Duplicate of https://github.com/angular/angular-cli/issues/20760

**Closed by alan-agius4** 2021-05-31 14:12 UTC
