### ISSUE TITLE
prod build with angular material - radio buttons not working

### ISSUE THREAD

**Issue by Enc-EE** [angular/angular-cli#9000] opened 2017-12-26 10:46 UTC
### Versions
1.6.2

### Repro steps
* `ng new some-name`
* run steps 1 - 4 of https://material.angular.io/guide/getting-started
* copy the code of the example on page https://material.angular.io/components/radio/examples in your code
* `ng build --prod`

### Observed behavior
Radio button is not working properly. Cannot check any option.

### Desired behavior
When clicking on an option, it should be selected

### Mention any other details that might be useful (optional)
No, there are no further errors.
There is also a strange behaviour using simple mat-input fields. Maybe the problem comes from [(ngModel)]-bindings.
Using @angular/cli@1.5.5 everything works fine.
Even if I make a normal build `ng build` radio button will work in 1.6.2.
I've already spend some time on this issue but i'm stuck since there is no real error.
I hosted the `ng build --prod` in the simple http-server and an IIS.

Could you please help me?

**Comment by vthinkxie** [comment] 2017-12-26 13:06
duplicated #8997

**Comment by filipesilva** [comment] 2017-12-28 17:14
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/8997. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-12-28 17:14 UTC
