### ISSUE TITLE
ng serve does not work after a fresh installation

### ISSUE THREAD

**Issue by benzid-wael** [angular/angular-cli#3480] opened 2016-12-08 19:36 UTC
After installing my project, I'm able to run **ng test** but not **ng serve**

When I run tests it works with Chrome but not with PhantomJS, I get the following error:
```

PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Functions cannot be declared in a nested block in strict mode
  at http://localhost:9876/_karma_webpack_/0.bundle.js:24476

PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Functions cannot be declared in a nested block in strict mode
  at http://localhost:9876/_karma_webpack_/0.bundle.js:24476
08 12 2016 20:23:16.355:ERROR [PhantomJS 2.1.1 (Linux 0.0.0)]: SyntaxError: Functions cannot be declared in a nested block in strict mode
at http://localhost:9876/_karma_webpack_/0.bundle.js:24476
```

On the other hand, when I run **ng serve**, I get the following error:

```
/home/wael/.nvm/v6.3.1/bin/node /home/wael/.nvm/v6.3.1/lib/node_modules/npm/bin/npm-cli.js start -prod

> webapp@0.0.0 start /home/wael/WebstormProjects/frontend
> ng serve

can't resolve module @angular/core/src/di/opaque_token from /home/wael/WebstormProjects/frontend/src/index.ts
Cannot read property 'parse' of undefined
TypeError: Cannot read property 'parse' of undefined
    at ReflectorHost.normalizeAssetUrl (/home/wael/WebstormProjects/frontend/node_modules/@angular/compiler-cli/src/reflector_host.js:54:43)
    at ReflectorHost.findDeclaration (/home/wael/WebstormProjects/frontend/node_modules/@angular/compiler-cli/src/reflector_host.js:151:33)
    at StaticReflector.initializeConversionMap (/home/wael/WebstormProjects/frontend/node_modules/@angular/compiler-cli/src/static_reflector.js:145:38)
    at new StaticReflector (/home/wael/WebstormProjects/frontend/node_modules/@angular/compiler-cli/src/static_reflector.js:42:14)
    at AotPlugin._setupOptions (/home/wael/WebstormProjects/frontend/node_modules/@ngtools/webpack/src/plugin.js:137:27)
    at new AotPlugin (/home/wael/WebstormProjects/frontend/node_modules/@ngtools/webpack/src/plugin.js:37:14)
    at Object.exports.getWebpackNonAotConfigPartial (/home/wael/WebstormProjects/frontend/node_modules/angular-cli/models/webpack-build-typescript.js:20:13)
    at new NgCliWebpackConfig (/home/wael/WebstormProjects/frontend/node_modules/angular-cli/models/webpack-config.js:23:42)
    at Class.exports.default.Task.extend.run (/home/wael/WebstormProjects/frontend/node_modules/angular-cli/tasks/serve-webpack.js:20:22)
    at /home/wael/WebstormProjects/frontend/node_modules/angular-cli/commands/serve.js:102:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

```

### OS?
> Ubuntu 16.0.4

### Versions.

angular-cli: 1.0.0-beta.22-1
node: 6.3.1
os: linux x64

### Repro steps.
> My app is created with angular-cli. I discovered the error in Jenkins and I don't found any problem with the application on my PC until I deleted node_modules directory and reinstall my app

### The log given by the failure.
Check above

### Mention any other details that might be useful.

> npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/wael/.nvm/v6.3.1/bin/node',
1 verbose cli   '/home/wael/.nvm/v6.3.1/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '-prod' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle webapp@0.0.0~prestart: webapp@0.0.0
6 silly lifecycle webapp@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle webapp@0.0.0~start: webapp@0.0.0
8 verbose lifecycle webapp@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle webapp@0.0.0~start: PATH: /home/wael/.nvm/v6.3.1/lib/node_modules/npm/bin/node-gyp-bin:/home/wael/WebstormProjects/nlg-frontend/node_modules/.bin:/home/wael/.nvm/v6.3.1/bin:/home/wael/bin:/home/wael/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle webapp@0.0.0~start: CWD: /home/wael/WebstormProjects/nlg-frontend
11 silly lifecycle webapp@0.0.0~start: Args: [ '-c', 'ng serve' ]
12 silly lifecycle webapp@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle webapp@0.0.0~start: Failed to exec start script
14 verbose stack Error: webapp@0.0.0 start: `ng serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/wael/.nvm/v6.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/wael/.nvm/v6.3.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid webapp@0.0.0
16 verbose cwd /home/wael/WebstormProjects/nlg-frontend
17 error Linux 4.4.0-53-generic
18 error argv "/home/wael/.nvm/v6.3.1/bin/node" "/home/wael/.nvm/v6.3.1/lib/node_modules/npm/bin/npm-cli.js" "start" "-prod"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error webapp@0.0.0 start: `ng serve`
22 error Exit status 1
23 error Failed at the webapp@0.0.0 start script 'ng serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the webapp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ng serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs webapp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls webapp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

> package.json

```
{
  "name": "webapp",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.2.1",
    "@angular/compiler": "^2.2.1",
    "@angular/core": "^2.2.1",
    "@angular/forms": "^2.2.1",
    "@angular/http": "^2.2.1",
    "@angular/platform-browser": "^2.2.1",
    "@angular/platform-browser-dynamic": "^2.2.1",
    "@angular/router": "^3.2.2",
    "core-js": "^2.4.1",
    "ng2-file-upload": "^1.1.4-2",
    "immutable": "^3.8.1",
    "redux": "^3.6.0",
    "rxjs": "^5.0.0-beta.12",
    "ts-helpers": "^1.1.2",
    "zone.js": "^0.7.1"
  },
  "devDependencies": {
    "@types/jasmine": "^2.5.38",
    "@types/node": "^6.0.50",
    "angular-cli": "^1.0.0-beta.17",
    "codelyzer": "~0.0.26",
    "html5shiv": "^3.7.3",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "^2.7.0",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.0.2",
    "karma-junit-reporter": "^2.0.0",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "karma-verbose-reporter": "0.0.3",
    "protractor": "^4.0.11",
    "ts-node": "^1.7.0",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}

```

**Comment by hansl** [comment] 2016-12-08 20:38
Dupe of https://github.com/angular/angular-cli/issues/3476

**Closed by hansl** 2016-12-08 20:38 UTC
