### ISSUE TITLE
Incorrect path on generating new module in app.module

### ISSUE THREAD

**Issue by psingl** [angular/angular-cli#7380] opened 2017-08-14 09:13 UTC
When we use `ng g component any-component` the path being written in app.module.ts is wrong and it fires an error. The path being written in app.module.ts is './components/src/app/home/home.component'

**Comment by exequiel09** [comment] 2017-08-14 10:06
#7284 and #7090 are related here. Already reported since versions 1.2.x. This is just a duplicate of an existing issue. Fixes and new implementation are already on progress being done by @Brocco

**Comment by filipesilva** [comment] 2017-08-24 12:07
Duplicate of https://github.com/angular/angular-cli/issues/7135, fixed in `1.4.0-rc.0`.

**Closed by filipesilva** 2017-08-24 12:07 UTC
