### ISSUE TITLE
[AOT] @ngtools/webpack throws "Cannot find module './ngfactory/app/app.module.ngfactory'"

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular-cli#2586] opened 2016-10-08 10:24 UTC
### OS?

Windows_NT 10.0.10586
### Description.

I'm trying to integrate `@ngtools/webpack` into my custom webpack build and is getting `Cannot find module './ngfactory/app/app.module.ngfactory'` error. The source of the error is [here](https://github.com/angular/angular-cli/blob/master/packages/webpack/src/loader.ts#L112-L127). I've managed to suppress the error by disabling [this](https://github.com/angular/angular-cli/blob/master/packages/webpack/src/loader.ts#L112) check.
### Repro steps.

Github repo: https://github.com/DzmitryShylovich/ngtools-error

```
npm i
npm start
```
### The log given by the failure.

```
ERROR in ./app/main.aot.ts
Module build failed: Error: D:/Workspace/ngtools-error/app/main.aot.ts (3,34): Cannot find module './ngfactory/app/app.module.ngfactory'.)
    at _transpile (D:\Workspace\ngtools-error\node_modules\@ngtools\webpack\src\loader.js:101:19)
    at D:\Workspace\ngtools-error\node_modules\@ngtools\webpack\src\loader.js:125:26
```

**Comment by david1880** [comment] 2016-10-10 08:10
I tryed to run the starting material2 project and I had a similar problem with ngfactory. In main.ts I finded this comment: 
`/**
 * AoT compile.
 * First run `./node_modules/.bin/ngc -p ./src/`
 */
`
After running that it worked, maybe you can try this.

**Comment by filipesilva** [comment] 2016-10-10 10:33
@DzmitryShylovich what version of `@ngtools/webpack` are you using?

**Comment by DzmitryShylovich** [comment] 2016-10-10 10:34
the latest

**Comment by DzmitryShylovich** [comment] 2016-10-10 11:34
Basically I've just copy pasted [test app](https://github.com/angular/angular-cli/tree/master/tests/e2e/assets/webpack/test-app) so it might be Windows specific issue.

**Comment by Gamblt** [comment] 2016-10-11 10:22
I have the same error. But if a try to go back to the beta16 I've got error: 
`
webpack_1.NgcWebpackPlugin is not a constructor
TypeError: webpack_1.NgcWebpackPlugin is not a constructor
`

**Comment by jtsom** [comment] 2016-10-11 10:25
I saw this same error also, when running `ng serve -aot` However, when I changed a file (added a new `<p> ... </p>` in app.component.html for instance) the error would not show after the project rebuilt. Making any other change would show the error.. and so on, alternately showing and not showing the error.

**Comment by michaelbromley** [comment] 2016-10-11 20:17
I have the same on Windows 10, but also is occurring in my Travis build on mac OS. You can see the full output of that here: https://travis-ci.org/michaelbromley/skqw/jobs/166849701#L466

I just updated to v1.1.0.

**Comment by Delagen** [comment] 2016-10-12 04:43
#2452

**Comment by sdeuvarow** [comment] 2016-10-31 03:45
It's happening again to me. When I run 
`node_modules/.bin/ngc -p ./src/`
I don't get any error, and all ng-factories are created. But when I run 
`ng build`

I get the following error:
`...\AppData\Roaming\npm\node_modules\ng-cli\node_modules\resolve\lib\sync.js:33
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
`

`Error: Cannot find module 'ng-factory' from '...\workspaceFrontend`
`at Function.module.exports [as sync] (..\AppData\Roaming\npm\node_modules\ng-cli\node_modules\resolve\lib\sync.js:33:11)`
`at module.exports (..\AppData\Roaming\npm\node_modules\ng-cli\node_modules\resolve-require\lib\index.js:10:24)`
`at Command.<anonymous> (..\AppData\Roaming\npm\node_modules\ng-cli\lib\index.js:35:5)`
`at Command.listener (..\AppData\Roaming\npm\node_modules\ng-cli\node_modules\commander\index.js:301:8)`
`at emitTwo (events.js:106:13)`
`at Command.emit (events.js:191:7)`
`at Command.parseArgs (..\AppData\Roaming\npm\node_modules\ng-cli\node_modules\commander\index.js:615:12)`
`at Command.parse (..\AppData\Roaming\npm\node_modules\ng-cli\node_modules\commander\index.js:458:21)`
`at Object.<anonymous> (C:\Users\Simon\AppData\Roaming\npm\node_modules\ng-cli\lib\index.js:55:9)`
`at Module._compile (module.js:570:32)`

Two days ago I didn't have any problems to create the distribution of the app. 
Any idea how to fix this?

NODE v6.9.1
NPM v3.10.6
TSC v2.0.0
angular-cli@1.0.0-beta.19-3
ng-cli@0.7.0

I tried in windows and also in linux. In bot OS have the same issue.

**Comment by fcrocce** [comment] 2016-10-31 19:15
Same as @sdeuvarow for me... in my case from ubuntu 16.04

**Comment by sdeuvarow** [comment] 2016-10-31 20:11
I had a conflict with "ng-cli" package. Removing it and reinstall angular-cli fix the issue.

**Comment by Meligy** [comment] 2017-01-16 19:16
Anyone still getting this?

**Comment by zoehneto** [comment] 2017-01-17 17:20
I'm still seeing this issue with ´@ngtools/webpack 1.2.3´. Interestingly enough it works if I have the site open before running ´npm start´ but then it imediatly recompiles and throws the error.

**Comment by hansl** [comment] 2017-02-03 20:19
Closing this as obsolete. Please provide a git repo that we can try to reproduce.

**Closed by hansl** 2017-02-03 20:19 UTC
Labels: command: build, feature: aot, os: Windows, priority: 1 (urgent), type: bug

**Comment by karthikeyanVK** [comment] 2017-03-10 12:42
When you run the ng build in angular 2, latest angular-cli automatically runs with --aot parameter (ahead of time compilation), so it is trying to optimize your code. You are having a package that is not yet compatible for optimizing. So you need update to your packages. Most probably the packages that has forRoot() in your **app.module.ts**

I recommend to update all packages.

Easy way to update your package is to the use package below, which i got it from http://stackoverflow.com/questions/36597780/how-do-i-correctly-upgrade-angular-2-npm-to-the-latest-version


Install

`npm install -g npm-check-updates`

Usage

`ncu `for display

`ncu -u` for re-writing your package.json

and run `npm install `to update your packages

**Comment by 18steps** [comment] 2017-05-25 18:29
Check if your `tsconfig.json` has the following at the root level:

````
  "angularCompilerOptions": {
    "genDir": "src/ngfactory",
    "entryModule": "./src/app#AppModule"
  }
````

I had accidentally left that out and for me it fixed the problem.

**Comment by snewell92** [comment] 2017-06-27 16:34
@18steps that didn't work for me 😿 

I was trying to follow [the docs](https://angular.io/guide/aot-compiler) for aot compilation, and the only difference I have is I want JIT to be the default `main.ts` and AOT be opt in with `main-aot.ts` (so I can bundle scripts just for production, automatically, with a postinstall script or whatever).

My `aot` folder output is also one directory level above my `src` directory -

```
  "angularCompilerOptions": {
    "genDir": "../aot",
    "basePath": "./src/", // this doesn't change anything :c
    "entryModule": "./src/app#AppModule" // this didn't help either :c
  }
```

And inside that `aot` folder it doesn't include the compiled `main-aot.ts` file, it just has `app` folder with broken `.ngfactory.ts` and `.ngsummary.ts` files, all of which have ts errors because they're import urls are wrong.

Can I not have my `aot` output be somewhere else? `genDir` is constrained?

**Comment by snewell92** [comment] 2017-06-27 16:36
Maybe #1465 would help me actually.
