### ISSUE TITLE
"tsconfig.app.json" paths causing errors with "ng build --prod"

### ISSUE THREAD

**Issue by ernestbofill** [angular/angular-cli#6548] opened 2017-06-02 09:32 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.6
node: 6.9.5
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.6
@angular/compiler-cli: 4.1.3

### Repro steps.

 - Create an empty angular-cli project
 - Add `paths` in `tsconfig.app.json` to point to a component library in the local environment. Example:
```
"paths": {
  "my-component-library/*": [
    "../../component.library/src/*"
  ]
}
```
 - Use the component library (import a module and use a component).
 - Attempt a production build `ng build --prod`.
 - It fails to build and shows an error.

### The log given by the failure.

```
ERROR in C:/Users/eby/Downloads/component-library-minimal/angular-cli.app/src/$$_gendir/component.library/src/my-example/example.componen
t.ngfactory.ts (10,26): Cannot find module './example.component'.

ERROR in C:/Users/eby/Downloads/component-library-minimal/angular-cli.app/src/$$_gendir/component.library/src/my-example/example.module.n
gfactory.ts (10,26): Cannot find module './example.module'.

ERROR in C:/Users/eby/Downloads/component-library-minimal/angular-cli.app/src/$$_gendir/app/app.component.ngfactory.ts (11,26): Cannot fi
nd module '../../../../component.library/src/my-example/example.component.ngfactory'.

ERROR in C:/Users/eby/Downloads/component-library-minimal/angular-cli.app/src/$$_gendir/app/app.component.ngfactory.ts (11,26): Cannot fi
nd module '../../../../component.library/src/my-example/example.component.ngfactory'.

ERROR in ./src/$$_gendir/app/app.component.ngfactory.ts
Module not found: Error: Can't resolve '../../../../component.library/src/my-example/example.component.ngfactory' in 'C:\Users\eby\Downlo
ads\component-library-minimal\angular-cli.app\src\$$_gendir\app'
 @ ./src/$$_gendir/app/app.component.ngfactory.ts 9:0-100
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

### Desired functionality.

I would like to be able to use component libraries in my local machine, without using npm link nor having them as dependencies.

### Mention any other details that might be useful.

It does work with ng serve.
I attach a minimal project that can be used to reproduce the issue.
[component-library-minimal.zip](https://github.com/angular/angular-cli/files/1047256/component-library-minimal.zip)

**Comment by filipesilva** [comment] 2017-06-06 13:00
This issue is a duplicate of https://github.com/angular/angular-cli/issues/6387. There is an answer and context in https://github.com/angular/angular-cli/issues/6387#issuecomment-302749300.

**Closed by filipesilva** 2017-06-06 13:00 UTC
