### ISSUE TITLE
changing the index attribute in angular-cli.json breaks app

### ISSUE THREAD

**Issue by jpmyob** [angular/angular-cli#9543] opened 2018-02-08 06:06 UTC
### Versions
cli 1.6.0

* Step 1
create default working app - confirm it works
* Step 2
change the name of file src/index.html to src/default.html
* Step 3
change "index" attribute in angular-cli.json 
    from ..."index": "index.html" 
    to... "index": "default.html"

### Observed behavior
core.js:1448 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'default.html'
Error: Cannot match any routes. URL Segment: 'default.html'
    at ApplyRedirects.webpackJsonp.../../../router/esm5/router.js.ApplyRedirects.noMatchError (router.js:1719)

### Desired behavior
I would expect to be able to browse to index.html (as a static page my express app) normally,
then when i browse to default.html - the angular app would proceed as normal

### Mention any other details that might be useful (optional)
This issue arrises because Im trying to find a way to have HTML and my app co-exist in my build
when I try to change my express default behavior from - 

app.get('*', (req,res) => {
	res.sendFile(path.join(__dirname,'dist/index.html'));
})

to

app.get('*', (req,res) => {
	res.sendFile(path.join(__dirname,'dist/default.html'));
})

The angular index.html gets executed anyway - not my default.html...(as static html)

SO I tried to flip the scenario - and make the angular app "default.html" and make my static HTML "index.html" - but that doesn't work either.

however - in the process, distilling this concept of renaming the 'index' property of the cli.json SHOULD work - otherwise, what's the point of having the angular-cli.json config file?

I hope that makes sense.

**Comment by mmenik** [comment] 2018-04-04 21:45
I have the same problem if change index.html into index.hbs

**Comment by bigteejay** [comment] 2018-04-18 08:07
I have the same problem, I tried changing `.angular-cli.json`'s `apps` `index` property to something other than `index.html` (so I can drop `dist` in a subfolder of overall website and it "just work").

**Error message**
```
ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve [snipped path]\my-awesome-app\src\index.html' in [snipped path]\my-awesome-app':
  Error: Can't resolve '[snipped path]\my-awesome-app\src\index.html' in '[snipped path]\my-awesome-app'
```

**Comment by mgechev** [comment] 2019-08-19 20:24
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:24 UTC
Labels: comp: devkit/build-angular, freq1: low, severity1: confusing, type: bug/fix
