### ISSUE TITLE
Service worker broken when ng build with custom base href

### ISSUE THREAD

**Issue by jscti** [angular/angular-cli#15025] opened 2019-07-09 14:52 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ *] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Don't know

### Description
Service worker isn't registered (ngsw-worker.js never called) when building with a custom --base-href.
Related stackoverflow post : https://stackoverflow.com/questions/53329924/angular-7-service-worker-not-registered
Related closed issue : https://github.com/angular/angular-cli/issues/13351

## 🔬 Minimal Reproduction
On localhost, I have 2 apps :
- 1 with default base-href : service Worker working without problem `ng build --project=projectA`
- 1 with custom base-href (given from the cli `ng build --project=projectB --base-href=/projectB/`

Manifest reflects this with start_url and scope to "/projectB"

## 🔥 Exception or Error

</code></pre>

## 🌍 Your Environment
<pre>Angular CLI: 8.1.0
Node: 10.15.3
OS: darwin x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.0
@angular-devkit/build-angular      0.801.0
@angular-devkit/build-ng-packagr   0.801.0
@angular-devkit/build-optimizer    0.801.0
@angular-devkit/build-webpack      0.801.0
@angular-devkit/core               8.1.0
@angular-devkit/schematics         8.1.0
@angular/cdk                       8.0.2
@angular/fire                      5.2.1
@angular/flex-layout               8.0.0-beta.26
@angular/http                      7.2.15
@angular/material                  8.0.2
@angular/pwa                       0.801.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.1.0
@schematics/angular                8.1.0
@schematics/update                 0.801.0
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2<code>

</code></pre>

Tried to : 
- register it relatively with "./ngsw-worker.js" without success
- manual register in browser console works (after app load)
- deps updated to latests
- Note that the workaround provided in the SO post works totally (= angular.json, ngsw-config, manifest file is well configured)

**Comment by alan-agius4** [comment] 2019-07-10 11:30
@gkalpak, I think this might be some related more to the `service-worker` package.

**Comment by gkalpak** [comment] 2019-07-10 12:21
Hard to tell what this is related with, without a minimal reproduction. (For example, the SO question mentions `http://127.0.0.1` which will of course not work, because SW requires HTTPS or `localhost` (not `127.0.0.1`).)

I would be happy to investigate this, if someone can provide a minimal reproduction (i.e. a ZIP file I can download or a repo I can check out and run a command to see the problem).

**Comment by alan-agius4** [comment] 2019-07-11 17:22
@jscti, it would be great if you can provide a minimal repo to speed up the process in looking into the issue.

Thanks

**Comment by vmagalhaes** [comment] 2019-08-13 14:56
Same thing on Angular CLI 7.3.6, any update?

**Comment by AkshayRaut1321** [comment] 2019-09-28 17:54
This might help:

https://github.com/angular/angular-cli/issues/8515#issuecomment-486017106
OR
https://github.com/angular/angular-cli/issues/13351#issuecomment-516342267

**Comment by alan-agius4** [comment] 2020-01-24 19:05
Closing as a reproduction has not been provided.

If this issue is still present in the latest version of Angular. Please open a new issue with a minimal reproduction. Thanks.

**Closed by alan-agius4** 2020-01-24 19:05 UTC
Labels: need: repro steps
