### ISSUE TITLE
Angular-Cli 1.0.0-beta.22-1 activate --aot by default ?

### ISSUE THREAD

**Issue by maxime1992** [angular/angular-cli#3427] opened 2016-12-06 08:46 UTC
### OS?
Ubuntu 16.10 x64

### Versions.
```
$ ng -v
angular-cli: 1.0.0-beta.22-1
node: 6.8.0
os: linux x64
```

### Repro steps.
I updated this morning to `"angular-cli": "1.0.0-beta.22-1"` and I have a strange behaviour. It seems that `aot` is now activated by default. (I didn't change anything to my code).

### The log given by the failure.
After running as usual `ng serve` I first ran into error like : 

> Error encountered resolving symbol values statically. Reference to a non-exported function

Or

> Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

The big problem here is not even to make my code `aot` compliant (and I did).
The problem is **not** to strip out custom decorators (see https://github.com/angular/angular-cli/issues/2799).

Before that update, the app I'm working on could not be deployed using `--aot` because of that.
And we said at work that it's fine till we can dev and hopefully this feature would come soon.

But now, I do have the same problem in dev, which is really a problem.
(I'll have to go back to beta-21 until it get fixed).

### Mention any other details that might be useful.
To reproduce : 
```
git clone https://gitlab.com/victornoel/petals-cockpit.git
git checkout front/upgrade-angular-cli-beta-22
cd petals-cockpit/frontend
yarn
# or : npm i
ng serve
```

Thanks for your awesome work on angular-cli !

**Comment by elvirdolic** [comment] 2016-12-06 08:52
dupe of #3368

**Comment by montella1507** [comment] 2016-12-06 14:43
It is using AOT=true (cannot be disabled) by default IN EVERY version now, because of benevolent dependencies on ngtools/webpack.. this is the hell of NPM.  

We cannot even build our applications now..

**Comment by maxime1992** [comment] 2016-12-06 15:33
@montella1507 I heard about the ngtools/webpack problem and as it's a problem of `^` on a version number I really think that using `yarn` would be a great idea to avoid this kind of problem.

Anyway until they figure something out, I wiped my node_modules, uninstalled angular-cli globally and reinstalled it in beta21 (same for local).

**Comment by montella1507** [comment] 2016-12-06 15:41
i would try, thanks. I think the entire "allow to install newer- - nonbreaking changes version" in NPM is only road to hell and terrible dead.

**Comment by montella1507** [comment] 2016-12-06 15:57
Error: AppModule is not an NgModule

IS there ANY working version? I dont think so... 

i did:
1) Rimrafed node_modules
2)Changed version in packages to beta21. 
3) yarn
4) yarn ... ng build (because ng server just got frozen without any error).

I am really thinking about switching to React in last weekes, becase with every new version, there are 1000 problems with build proccess and breaking (undocumented) changes. :-(

**Comment by hansl** [comment] 2016-12-06 18:10
Closing this as duplicate of #3368

**Closed by hansl** 2016-12-06 18:10 UTC
