### ISSUE TITLE
Feature Request: Copy assets outside of src folder (e.g. node_modules)

### ISSUE THREAD

**Issue by serhiisol** [angular/angular-cli#3555] opened 2016-12-14 11:14 UTC
So this is a feature request for ability to copy assets from different folders of the project, e.g. ```node_modules``` etc. Currently it doesn't seem to be supported even if you'll specify this:

```angular-cli.json```
```
    "assets": [
      "assets",
      "../logo.png",
      "../node_modules/third-party/cool.svg"
    ],
```

It's actually common use case, when you need to copy assets from third-party modules from ```node_modules```

Below you can see additional information about cli and steps to reproduce:

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
```macOS Sierra 10.12.1```

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.21
node: 7.2.1
os: darwin x64
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
To reproduce this issue just try to copy file one level up of src folder or explicitly from ```node_modules```

### Stack trace
1. If you'll specify asset as 
```
   "assets": [
      "assets",
      "../node_modules/bootstrap-theme/svg/sprite-symbol.svg"
    ]
```
you won't see any stack trace, all good, but file won't be copied

1. If you'll specify asset as 
```
   "assets": [
      "assets",
      "node_modules/bootstrap-theme/svg/sprite-symbol.svg"
    ]
```

```
ENOENT: no such file or directory, stat '/Users/serhiisol/Development/test-app/src/node_modules/bootstrap-theme/svg/sprite-symbol.svg'
Error: ENOENT: no such file or directory, stat  #'/Users/serhiisol/Development/test-app/src/node_modules/bootstrap-theme/svg/sprite-symbol.svg'
    at Object.fs.statSync (fs.js:906:18)
```

### Mention any other details that might be useful.
What if you want to include assets from node_modules, which seems like a fairly common use case

**Comment by hikalkan** [comment] 2016-12-14 12:25
We also need this to copy a file from node_modules to output folder.

**Comment by manuelfink** [comment] 2016-12-28 15:34
Same situation here. It would be awesome if angular-cli could merge several sources into joined the public foulders eg.:

"assets":[
  "source1/css",
  "source1/js",
  "source2/css",
  "source2/js"
] 

output is merged in public folders /css and /js.

It also would be really handy do specify different targets to avoid naming conflicts eg.

```
assets: [
  { "source":"../node_modules/awsomse/style.css", "to":"css/awesome.css"},
  { "source":"../node_modules/other/style.css", "to":"css/other.css"}
]
```

**Comment by filipesilva** [comment] 2016-12-30 15:17
There was something similar to @manuelfink's suggestion added for scripts/styles in https://github.com/angular/angular-cli/pull/3402. 

Something similar could be added for assets.

**Comment by serhiisol** [comment] 2016-12-30 15:20
@filipesilva is it available in beta.24 ? if so I can test

**Comment by filipesilva** [comment] 2016-12-30 15:25
@serhiisol it doesn't exist for assets, just for scripts/styles.

**Comment by serhiisol** [comment] 2016-12-30 15:26
@filipesilva right, ok, I can try to help with it

**Comment by filipesilva** [comment] 2017-01-05 11:19
@serhiisol I'd prefer to take this one myself since it requires a few changes throughout parts of the app that I already had to do for other PRs. I might end up consolidating that mechanism.

**Comment by derekcdaley** [comment] 2017-01-13 23:15
What's the latest on this? This would be an amazing feature.

**Comment by mcgraphix** [comment] 2017-01-23 15:17
Any update on this? It's really unfortunate that you manually have to copy the files from npm deps into your own assets directory. Especially given that there is no way to add any custom scripts into the build that could do this automatically.

**Comment by fleskesvor** [comment] 2017-01-27 10:50
@mcgraphix I agree that it's unfortunate that we can't currently configure external assets in angular.cli.json, but you can easily add a custom script to package.json to copy assets. I have this one added to copy the svg file from [Octicons](https://www.npmjs.com/package/octicons):

`"copy:assets": "cp node_modules/octicons/build/sprite.octicons.svg src/assets",`

(Use a module like eg. [copyfiles](https://www.npmjs.com/package/copyfiles) if you want cross-platform copy.)

If you launch your project with `npm start`, you might want to append `npm run copy:assets &&` in front of whatever is there from before.

I currently only use it for that one file, but you could do the same for all of your external assets until a better solution is implemented.

**Comment by Bnaya** [comment] 2017-02-04 23:44
Looks like you can use explicit file-loader calls!
``
// this will include static files from budgetkey-ng2-components to our dist
const t = '';
console.log(require('file-loader?name=assets/[path]/[name].[ext]!budgetkey-ng2-components/assets/' + t));
``

I'm still hacking on it

**Closed** 2017-02-15 12:53 UTC
Labels: command: build, priority: 2 (required), type: enhancement

**Comment by jeffaxial** [comment] 2017-03-03 15:05
I just wanted to thank @filipesilva for getting this feature in. Thanks man!

**Comment by filipesilva** [comment] 2017-03-03 15:13
@jeffaxial glad you're finding it useful!

**Comment by fleskesvor** [comment] 2017-03-08 14:02
Thanks, @filipesilva!

If I understand the documentation right, I have to configure something like

`{ "glob": "**/*", "input": "../node_modules/octicons/build/svg", "output": ["./assets", "../src/assets/"] }`

for my own use-case if I want to have the Octicons svg files available both during development and in the production build. Is that right?

**Comment by filipesilva** [comment] 2017-03-08 14:07
@fleskesvor that sounds mostly right, except `output` shouldn't be an array. It should be the location where you want them to be on a build.

**Comment by fleskesvor** [comment] 2017-03-08 22:15
@filipesilva Yes, you're absolutely right, of course. The reason why that appeared to be working must have been that I had already built my project using the correct syntax. On a new project with angular-cli up to date (v. 1.0.0-rc.1), this configuration works:

`{ "glob": "**/*", "input": "../node_modules/octicons/build/svg", "output": "./assets/" }`

Both during development and an AoT build.

**Comment by fletchsod-developer** [comment] 2017-05-05 20:30
I tried that option '{ "glob": "**/*", "input": "../../foo", "output": "_artifacts/local"' then ran "ng build" and it doesn't do anything.

**Comment by fleskesvor** [comment] 2017-05-08 09:40
@fletchsod-developer It's working for me in version 1.0.0-rc.1. Which version are you on, and are you 100% sure of that input path?

**Comment by rajramo61** [comment] 2017-06-27 04:14
@filipesilva I am using @angular/cli: 1.0.4
and trying like
"assets": [
        { "glob": "**/*", "input": "../node_modules/styles/lib/modern/assets/images/", "output": "./assets/" },
        { "glob": "**/*", "input": "../node_modules/styles/lib/modern/assets/images/", "output": "../src/assets/" },
        { "glob": "**/*", "input": "../node_modules/styles/lib/modern/assets/fonts/", "output": "./assets/" },
        { "glob": "**/*", "input": "../node_modules/styles/lib/modern/assets/fonts/", "output": "../src/assets/" }
      ]

But it does not copy anything.

**Comment by codedmonkey** [comment] 2017-07-07 12:38
The idea of this feature is great, but it seems that this solution doesn't work for the development environment at all. I would like to use this feature to include CSS from a node_modules directory, but if I'm unable to access the files while developing the app this doesn't seem to be the way to solve that problem. So am I missing something here or is this feature just for show?

**Comment by jeffaxial** [comment] 2017-07-07 14:45
Honestly, it's a little bit rude to assume they've spent time on a feature that only _looks_ like it works.

I'm using it locally while developing my app as well in a production environment, and it works great.

**Here is how I am using it:**
I have a folder with font files in it I want to get from a node_module directory to my assets folder.
Input folder: _node_modules/DIRECTORY/fonts_
Output folder: _assets/fonts_

In .angular-cli.json:
`"assets": [
      "assets",
      { "glob": "**/*", "input": "../node_modules/DIRECTORY/fonts", "output": "./assets/fonts" },
   ]`

Do note that you need to restart _ng serve_ after adding the line. All I can say is that I have this working on several projects, and it works just as advertised.

**Comment by fleskesvor** [comment] 2017-07-07 15:07
Yep, as noted by me just a few comments up, I also have it working both in development and production.

**Comment by rajramo61** [comment] 2017-07-07 15:53
But, I am facing the problem.
I have few external stylesheets which I am pulling from ../node_modules/dir/stylesheet . I am also using stylePreprocessorOptions to include few paths for pre processing otherwise it fails here itself.
These styles use some fonts and images which are available under ../node_modules/dir/stylesheets/fonts and ../node_modules/dir/stylesheets/images . The failure shows it is looking for assets under src/assets . 

Error is like the following:
Module not found: Error: Can't resolve './assets/images/loading-icon.svg' in 'project-path/src' . It is repeated for each image/fonts referenced in stylesheet.

I provided the option using glob to copy assets but it does not copy it. It seems styles processing happens before copy and it tries to reference the fonts and images so it just fails and could not copy (Just a guess).

**Comment by hieunt88** [comment] 2017-08-28 02:28
@filipesilva Work like a charm! Thanks for putting in the work. I almost pull in Gulp to copy a few files from _node_modules_.

@rajramo61 for stylesheets, if you use SASS/LESS, you can use the **import** statement without having to copy them over. Also, can you post your "apps" section in _.angular-cli.json_ for further troubleshooting?

**Comment by rajramo61** [comment] 2017-08-28 03:51
@hieunt88 
Currently, my work around is to run a copy script to copy fonts or images from node styles  folder to src/assets to mitigate this issue as this does not work for me.

Here is the app section. 
{
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        { "glob": "**/*", "input": "../node_modules/styleg/lib/modern/assets/fonts/", "output": "../src/assets/fonts" },
        { "glob": "**/*", "input": "../node_modules/style/lib/modern/assets/images/", "output": "../src/assets/images" }
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.scss"
      ],
      "stylePreprocessorOptions": {
        "includePaths": [
          "../node_modules",
          "../node_modules/bourbon/app/assets/stylesheets",
          "../node_modules/bourbon-neat/app/assets/stylesheets"
        ]
      },
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }

style.scss has
@import "~style/modern"; // this is importing styles from node module.

This modern is again combination of multiple scss files which are pre-build and I need to use them.
It breaks mostly, as in one of the scss file has a variable 
$font-path: 'assets/fonts/';

This variable is utilized in many places for the path for fonts. Like
@at-root {
  @font-face {
    font-family: "demo-icons";
    src: url("#{$font-path}demo-icons.svg");
    url("#{$font-path}demo-icons.woff") format("woff"),
    font-weight: normal;
    font-style: normal;
  }
}
I see errors like following for all the files referred from font or image directories:
ERROR in ./src/assets/fonts/demo-icons.svg
Module build failed: Error: ENOENT: no such file or directory, open '/<project-complete-path>/src/assets/fonts/demo-icons.svg'

I tried to override this variable $font-path but could not make it work.

**Comment by hieunt88** [comment] 2017-09-06 02:19
@rajramo61 this is my script to copy external fonts. `glob` is different and will match all sub file/folder paths. This should work.
```javascript
{ "glob": "**/*", "input": "../node_modules/font-awesome/fonts", "output": "./assets/fonts/" }
```
For `$font-path`, I ran into the same issue. Angular CLI would try to resolve asset paths,  in your case `./src/assets/fonts/demo-icons.svg`, during SCSS compiling process and fail if they don't exist. I have yet to find a way to change this behaviour. My work around is to copy the assets to the `assets` folder using another pre-build script e.g `gulp`.

Also, you need to drop `src` from your `$font-path` like so.
```scss
$font-path: 'assets/fonts/'
```

For SASS, I believe the problem is not with Angular CLI referencing external .scss. The build most likely broke because of the asset path issue above. Try the setting below.

```javascript
"stylePreprocessorOptions": {
   "includePaths": [
     "../node_modules/path/to/modern/scss"
  ]
}
```

Then, in your `styles.scss`.
```scss
$font-path: 'assets/fonts/'
@import 'modern';
````

**Comment by ghiscoding** [comment] 2017-12-14 16:59
That doesn't seem to work with JSON files, I tried multiple ways and it doesn't do anything. This is what I tried so far
```javascript
"assets": [
        "assets",
        "favicon.ico",
        { "glob": "**/*", "input": "../node_modules/angular-slickgrid/i18n", "output": "./assets/i18n/" },
        { "glob": "*", "input": "../node_modules/angular-slickgrid/i18n", "output": "./assets/i18n/" },
        { "glob": "*/", "input": "../node_modules/angular-slickgrid/i18n", "output": "./assets/i18n/" },
        { "glob": "**/*", "input": "../node_modules/angular-slickgrid/i18n", "output": "./assets/i18n" }
      ],
```
Would that work with JSON files or is that a restricted file type?

**Comment by commercialsuicide** [comment] 2018-05-07 15:46
As @ghiscoding mentioned above, looks like it doesn't work with JSON files.
Angular 5.0.3
It will be pretty useful to allow copy of JSON files too, this way we can include different lists and other stuff from external libraries.

**Comment by tnicola** [comment] 2018-07-13 09:05
@ghiscoding Have you tried with:

` { "glob": "**/*.json", "input": "node_modules/angular-slickgrid/i18n", "output": "/assets/i18n/" }`

**Comment by daveerwin** [comment] 2018-10-10 02:19
Angular-cli version: 6.0.8
This worked for me:
`{
                "glob": "**/*",
                "input": "node_modules/<npm-pkg-name>/dist/images",
                "output": "assets/images"
   },`

I did struggle with this until I got it working. A couple important pieces that helped to get it working

1. restarting ng serve is not enough, I needed to use ng build or npm install to get a new dist folder
2. the images do NOT need to be in src for them to work on the site, I thought they did. This will copy from node_modules into dist so don't expect your images to be in src. I have no idea how to get them to copy from node_modules into src, according to this: https://github.com/angular/angular-cli/wiki/stories-asset-configuration it's not possible as it has security implications.

Being new to angular these assumptions I made caused a couple hours of headaches, so hopefully this info helps somebody else.

**Comment by kylietmo** [comment] 2019-08-21 18:50
This does not appear to work with `ng serve` in Angular 8:
```
"assets":[
    {"glob": "jquery/dist/jquery.js", "input": "node_modules", "output": "third_party"}
]
```
It will work fine with `ng build`, but specifically not with `ng serve.`
