### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dignadicedustin261188** [angular/angular-cli#2605] opened 2016-10-09 13:06 UTC
**OS**
Windows 7

**Versions**
Node@latest
NPM@latest

**Repro steps.**
Installation and then it stucked.

**The log given by the failure.**
![screenshot](https://cloud.githubusercontent.com/assets/22390719/19220777/d2d7955a-8e67-11e6-923f-55e95f86b1a4.png)

**Comment by dignadicedustin261188** [comment] 2016-10-09 13:31
**OS**
Windows 7

**Versions**
Node@latest
NPM@latest

**Repro steps.**
Installation

**The log given by the failure.**
![screenshot](https://cloud.githubusercontent.com/assets/22390719/19220769/95b7f2e6-8e67-11e6-9668-30ea8e033967.png)

**Comment by filipesilva** [comment] 2016-10-10 14:32
Looks like a dupe of https://github.com/angular/angular-cli/issues/1932

**Closed by filipesilva** 2016-10-10 14:32 UTC
