### ISSUE TITLE
ng serve. File changed detected but no change in the output to ng serve. File change detected but no change in the output

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular-cli#5507] opened 2017-03-19 14:00 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Window 7
@angular/cli: 1.0.0-rc.2
node: 6.9.4
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.10
@ngtools/webpack: 1.2.13

### Repro steps.
any change in any *.ts file under the src/app/modules/ is refresh the browser 
but the file with the new change is not change when I inpect in the browser (chrome)
for example this path: src/app/modules/header/header.component.ts

it do work for this path for example:
src/app/app.component.ts

### Desired functionality.
on any change *.ts file it should be reflected on the browser.

### Mention any other details that might be useful.
OS win 7
browser chrome
IDE webstorm 2016.3.3

**Comment by ofirrifo** [comment] 2017-03-19 17:35
I found that my problem only happened with webstorm IDE.

and this what help me to solve it

File > Settings... > System Settings > Use "safe write" ([save changes to a temporary file first](https://webpack.github.io/docs/troubleshooting.html#file-saves-in-webstorm-don-t-trigger-the-watcher)).

**Comment by filipesilva** [comment] 2017-03-23 21:28
Dupe of https://github.com/angular/angular-cli/issues/5117

**Closed by filipesilva** 2017-03-23 21:28 UTC
