### ISSUE TITLE
Angular SSR Issue: When attempting to execute npm run start, it appears that Express is not running to enable hot reload.

### ISSUE THREAD

**Issue by julianguerrerop202** [angular/angular-cli#27440] opened 2024-04-10 02:57 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

It was working with Angular Universal

### Description

You’ve encountered an issue where Angular SSR (Server-Side Rendering) isn’t executing your Express code when you run `npm run start`, but it works as expected when you run `npm run build && npm run serve:ssr:<projectname>`

## First option:
The project is in this url: https://github.com/julianguerrerop202/testangularssr1

## Or you could:
# Create a project:
Create a new Angular project with SSR support using the following command 
1. `ng new --ssr testangularssr1` 
2. `cd testangularssr1`
3. Choose Sass (SCSS) as your style format.

# Add code:
To manage Express and its functionalities, we’ll start by adding a simple route and a console.log.
Open the `server.ts` file and add the following code snippet below the line `server.set('views', browserDistFolder);`

```
console.log(' == Express Works Well == ');
server.get('/required-page', (req, res) => {
    res.send('Successful!!');
});

```

# Run serve:
When you run `npm run start`, I didn’t see the ’ == Express Works Well == ’ message. This suggests that Express might not be running. Additionally, attempting to access the route http://localhost:4200/required-page results in an error.

### Exception or Error

```text
ERROR RuntimeError: NG04002: Cannot match any routes. URL Segment: 'required-page'
    at Recognizer.noMatchError (/testangularssr1/node_modules/@angular/router/fesm2022/router.mjs:3694:12)
    at eval (/testangularssr1/node_modules/@angular/router/fesm2022/router.mjs:3727:20)
    at eval (/testangularssr1/node_modules/rxjs/dist/esm/internal/operators/catchError.js:10:39)
    at OperatorSubscriber.OperatorSubscriber._error (/testangularssr1/node_modules/rxjs/dist/esm/internal/operators/OperatorSubscriber.js:23:21)
    at OperatorSubscriber.error (/testangularssr1/node_modules/rxjs/dist/esm/internal/Subscriber.js:40:18)
    at OperatorSubscriber._error (/testangularssr1/node_modules/rxjs/dist/esm/internal/Subscriber.js:64:30)
    at OperatorSubscriber.error (/testangularssr1/node_modules/rxjs/dist/esm/internal/Subscriber.js:40:18)
    at OperatorSubscriber._error (/testangularssr1/node_modules/rxjs/dist/esm/internal/Subscriber.js:64:30)
    at OperatorSubscriber.error (/testangularssr1/node_modules/rxjs/dist/esm/internal/Subscriber.js:40:18)
    at OperatorSubscriber._error (/testangularssr1/node_modules/rxjs/dist/esm/internal/Subscriber.js:64:30) {
  code: 4002
}
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.3
Node: 20.11.1
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 17.3.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@schematics/angular             17.3.3
rxjs                            7.8.1
typescript                      5.4.4
zone.js                         0.14.4
```

**Comment by alan-agius4** [comment] 2024-04-10 06:43
This is expected as the `server.ts` is not used during `ng serve`. 

Duplicate of https://github.com/angular/angular-cli/issues/27144

**Closed by alan-agius4** 2024-04-10 06:43 UTC

**Comment by julianguerrerop202** [comment] 2024-04-10 13:54
@alan-agius4 In some comments like:
https://github.com/angular/angular-cli/issues/26323#issuecomment-1987050082
I read that it will be fixed in future versions, is this true?

**Comment by alan-agius4** [comment] 2024-04-10 13:57
@julianguerrerop202, https://github.com/angular/angular-cli/issues/26323#issuecomment-1987050082 is slightly different from https://github.com/angular/angular-cli/issues/27144. We definitely want to fix this issue though.
