### ISSUE TITLE
Selecting SASS generates SCSS files but angular.json config is set to SASS

### ISSUE THREAD

**Issue by vivek1996** [angular/angular-cli#13600] opened 2019-02-06 06:46 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

 A clear and concise description of the problem...
I have created a new project using the cli by selecting the styles type as SASS but the generated files are SCSS but still the configuration in angular.json is points to SASS file and it returns error while serving.
These are config contains related to SASS
<pre><code>
 "styles": [
              "src/styles.sass"
           ],

 "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.sass"
            ],

 "schematics": {
        "@schematics/angular:component": {
          "style": "sass"
        }
      },

 </code> </pre>

## 🔬 Minimal Reproduction
<code> ng new demo <code>

## 🔥 Exception or Error
<pre>ERROR in multi ./src/styles.sass
Module not found: <code>

</code></pre>

## 🌍 Your Environment
<pre><code>

$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / ? \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.3.0
Node: 11.6.0
OS: win32 x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.0
@angular-devkit/build-angular     0.13.0
@angular-devkit/build-optimizer   0.13.0
@angular-devkit/build-webpack     0.13.0
@angular-devkit/core              7.3.0
@angular-devkit/schematics        7.3.0
@angular/cli                      7.3.0
@ngtools/webpack                  7.3.0
@schematics/angular               7.3.0
@schematics/update                0.13.0
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-02-06 07:22
Duplicate of https://github.com/angular/angular-cli/issues/13550

**Closed by alan-agius4** 2019-02-06 07:22 UTC
