### ISSUE TITLE
ng version take around 3 min to start

### ISSUE THREAD

**Issue by oshri551** [angular/angular-cli#21172] opened 2021-06-21 12:46 UTC
# 🐞 Bug report

### Command `ng version`

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [x] help
- [x] version
- [ ] doc

### Is this a regression? 
started to see this after installing 12.0.4 version but now even when reverting to v11 still see the issue

### Description

 When trying to do `ng version` or `ng new`  it takes almost 3 minutes for the CLI to start

## 🌍 Your Environment

<pre><code>
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.5
Node: 14.17.1
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.5 (cli-only)
@angular-devkit/core         12.0.5 (cli-only)
@angular-devkit/schematics   12.0.5 (cli-only)
@schematics/angular          12.0.5 (cli-only)

</code></pre>

**Anything else relevant?**
Tried to remove node and reinstall the npm packages.
Other npm packages works fine

**Comment by alan-agius4** [comment] 2021-06-22 05:58
Hi @oshri551, 

Can you please provide a CPU profile? 

You can generate one by running the below command inside of an Angular workspace
```
node --cpu-proof node_modules/@angular/cli/lib/init.js version
```

**Comment by oshri551** [comment] 2021-06-22 07:51
don't know what happened but after running  node --cpu-prof node_modules/@angular/cli/lib/init.js version once everything started to work fast.

Thanks for the quick reply

**Comment by oshri551** [comment] 2021-06-23 08:04
After restart the issue continue - I've attached the cpu profile
[CPU.20210623.102607.20096.0.001.zip](https://github.com/angular/angular-cli/files/6700074/CPU.20210623.102607.20096.0.001.zip)

**Comment by alan-agius4** [comment] 2021-06-23 08:53
From the profiler it appears that spawning NPM via `execSync` is taking `3.2mins`.

I suspect this is caused by the NPM updater notifier, which prevents the child process from closing until it times out after 3 minutes.

Can you please try to update `getPackageManager` in `/node_modules/@angular/cli/commands/version-impl.js` and see if the problem persists afterwards. 

```js
    async getPackageManager() {
        try {
            const manager = await package_manager_1.getPackageManager(this.context.root);
            const version = child_process_1.execSync(`${manager} --version`, {
                encoding: 'utf8',
                stdio: ['ignore', 'pipe', 'ignore'],
            }).trim();
            return `${manager} ${version}`;
        }
        catch {
            return '<error>';
        }
    }
```

**Closed** 2021-06-25 05:45 UTC
Labels: comp: angular/cli, freq1: low, severity5: regression, type: bug/fix

**Comment by oshri551** [comment] 2021-07-11 08:10
Version 12.1.1 solved the 3 min wait for ng version but, it also happens in ng new <project_name>
Do we need CPU profile again?

**Comment by alan-agius4** [comment] 2021-07-11 11:04
> Version 12.1.1 solved the 3 min wait for ng version but, it also happens in ng new <project_name>
> Do we need CPU profile again?

Updating the global CLI version should solve the issue.

`npm i -g @angular/cli`

**Comment by oshri551** [comment] 2021-07-11 11:16
I've updated the version today and now  on 12.1.1 and even ng update command on on local project - version (10.0.x) wait 3 min to start:

C:\Users\oifrah>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.1.1
Node: 14.17.1
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1201.1 (cli-only)
@angular-devkit/core         12.1.1 (cli-only)
@angular-devkit/schematics   12.1.1 (cli-only)
@schematics/angular          12.1.1 (cli-only)
