### ISSUE TITLE
ng serve doesn't generate media directory

### ISSUE THREAD

**Issue by arturober** [angular/angular-cli#26216] opened 2023-11-03 08:28 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

It seems that all resources referenced from CSS  using url() are put in media/ directory (in this case, fonts) are put in **media/** directory. This directory (including the fonts) is created inside **dist/** when executing **ng build**, but it's not being generated with **ng serve**.

For example, installing @fortawesome/fontawesome-free, and importing the CSS in angular.json ("node_modules/@fortawesome/fontawesome-free/css/all.css").

When I put an icon in the app (<i class="fa-regular fa-thumbs-up"></i> for example), I get a 404 error -> doens't find http://localhost:4200/media/fa-regular-400.woff2.

Until it's resolved, I have to manually create a media directory inside src and copy the font files there. Then include that directory in the assets section in angular.json.

### Minimal Reproduction

npm i @fortawesome/fontawesome-free

Include "node_modules/@fortawesome/fontawesome-free/css/all.css" in the styles section (angular.json)

Create an icon in any template: <i class="fa-regular fa-thumbs-up"></i>

Execute **ng serve**

Get a 404 error (doesn't find the font file inside the media directory)

### Your Environment

```text
Angular CLI: 17.0.0-rc.3
Node: 18.18.2
Package Manager: npm 10.2.3
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.0-rc.3 (cli-only)
@angular-devkit/core         17.0.0-rc.3 (cli-only)
@angular-devkit/schematics   17.0.0-rc.3 (cli-only)
@schematics/angular          17.0.0-rc.3 (cli-only)
```

**Comment by alan-agius4** [comment] 2023-11-03 09:29
Duplicate of https://github.com/angular/angular-cli/issues/26215

**Closed by alan-agius4** 2023-11-03 09:30 UTC
