### ISSUE TITLE
Unable to serve/build --aot

### ISSUE THREAD

**Issue by ScottSpittle** [angular/angular-cli#8752] opened 2017-12-06 09:28 UTC
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.5
Node: 8.4.0
OS: linux x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.5
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.39
@ngtools/json-schema: 1.1.0
typescript: 2.6.2
webpack: 3.8.1
```

### Repro steps

* npm install
* ng serve/build --aot

### Observed behavior
With --verbose the output ends with the following and if I try to pipe it into a file (> buildinfo.txt) it just hangs at the end before 'webpack: Failed to compile.' so I can never see the output.

Our jenkins build does pass some how (as it doesn't locally), but build time has gone from ~28 mins to 1 hour and 30 minutes
```
[entry] [rendered]
webpack: Failed to compile.
```

![image](https://user-images.githubusercontent.com/1223461/33654376-2cc3ed7a-da70-11e7-8ff0-3aa52cdb1f29.png)

### Desired behavior
For it to work

### Mention any other details that might be useful (optional)
I've tried angular 4.6.x and 5.0.x
I've tried CLI 1.5.x and 1.6.0-rc.x

Tried combinations of toggling:
* sourcemap
* build-optimizer

I'm not sure why but I've recently had to add the following to the tsconfig.json too;
```
  "include": [
    "./src/**/*.ts",
    "./node_modules/humanize-duration-ts/humanize-duration-ts.ts"
  ]
```

Event reverting back to a previous 4.x version and cleraing node_modules npm install and trying to server --aot I just can't get it to work.

**Comment by devoto13** [comment] 2017-12-06 10:43
Possible duplicate of https://github.com/angular/angular-cli/issues/5618.

**Comment by clydin** [comment] 2017-12-06 13:39
Thanks for reporting this issue. However, this issue appears to be a duplicate of an existing issue #5618. Please subscribe to that issue for future updates.

**Closed by clydin** 2017-12-06 13:39 UTC
