### ISSUE TITLE
Branch coverage data is incorrect after upgrading to Angular 13

### ISSUE THREAD

**Issue by acieroid** [angular/angular-cli#22652] opened 2022-02-04 21:17 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [X] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 12

### Description

The coverage produced when running `ng test --code-coverage` is incorrect, it is missing branches that were previously counted. This applies to `if` that do not have an `else`: these used to be counted as two branches, and they are now counted as one. This artificially increases branch coverage.

## 🔬 Minimal Reproduction

Starting from a minimal reproduction repository (`ng new`), make the following changes:
1. Add `src/foo.ts`. Note that this function contains two branches to cover: the if, and the (non-explicitly written) else.
```
export function foo(n: number) {
  if (n % 2 === 0) {
    console.log('hello');
  }
}
```
2. Add `src/foo.spec.ts`:
```
import { foo } from './foo';

describe('test', () => {
  it('test', () => {
    foo(2);
  });
});
```
3. Restrict the test suite to run only `foo.spec.ts` in `src/test.ts`:
```
const context = require.context('./', true, /foo\.spec\.ts$/);
```
4. Launch the tests with code coverage: `npx ng test --code-coverage`
5. The output reports full coverage, of only one branch:
```
=============================== Coverage summary ===============================
Statements   : 100% ( 2/2 )
Branches     : 100% ( 1/1 )
Functions    : 100% ( 1/1 )
Lines        : 100% ( 2/2 )
```

For comparison, downgrading to Angular 12 and to Typescript 4.3.5 results in the correct coverage report, which is:
```
=============================== Coverage summary ===============================
Statements   : 100% ( 5/5 )
Branches     : 50% ( 1/2 )
Functions    : 100% ( 1/1 )
Lines        : 100% ( 5/5 )
```

## 🌍 Your Environment

Everything comes from the default app when running `ng new`
<pre><code>
Angular CLI: 13.2.2
Node: 16.13.2
Package Manager: npm 8.1.2
OS: linux x64

Angular: 13.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.2
@angular-devkit/build-angular   13.2.2
@angular-devkit/core            13.2.2
@angular-devkit/schematics      13.2.2
@angular/cli                    13.2.2
@schematics/angular             13.2.2
rxjs                            7.5.2
typescript                      4.5.5
</code></pre>

**Comment by alan-agius4** [comment] 2022-02-08 09:33
It turned out to be pretty complex to find the root cause of this. After spending most of yesterday afternoon and today's morning I was able to locate the root cause of the issue. It turns out that this is caused by [this change](https://github.com/istanbuljs/istanbuljs/pull/633) in [istanbul-lib-instrument](https://github.com/istanbuljs/istanbuljs) which is causing incorrect branch coverage for implicit else.

I opened an issue in their repo with a [minimal reproduction](https://github.com/istanbuljs/istanbuljs/issues/670). I suggest that you subscribe to that issue. 

I am going to close this issue, as is not actionable from our end since we don't control which version of `istanbul-lib-instrument` is used because this is a transitive dependency.

**Closed by alan-agius4** 2022-02-08 09:33 UTC
Labels: need: investigation, comp: devkit/build-angular, devkit/build-angular: test
