### ISSUE TITLE
Global scss compile takes too long time

### ISSUE THREAD

**Issue by fuitattila** [angular/angular-cli#3964] opened 2017-01-12 09:02 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10.

### Versions.
> angular-cli: 1.0.0-beta.24
node: 5.11.0
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2

### Mention any other details that might be useful.

Problem: we have global scss style - not included in components. There are many scss files (circa 60) and fonts (circa 10) in our project. The preprocessing of style.css from that files takes 14-15 seconds (i5, 8gb).

Are there any ways to disable or speed up the scss compile process?

**Comment by RicardoVaranda** [comment] 2017-01-12 10:11
This issue is already being addressed at #1980

**Comment by filipesilva** [comment] 2017-01-12 15:01
Mostly a dupe of #1980 as @RicardoVaranda said, but https://github.com/angular/angular-cli/pull/3943 should fix this particular issue.

**Closed by filipesilva** 2017-01-12 15:01 UTC
