### ISSUE TITLE
Unable to update from 13.1.0 to the latest point release

### ISSUE THREAD

**Issue by jayhamilton** [angular/angular-cli#22565] opened 2022-01-25 03:03 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

no

### Description

running ng update or ng update @angular/cli@^13 @angular/core@^13  results in a failure

## 🔬 Minimal Reproduction

see above

## 🔥 Exception or Error

<pre><code>

The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 13.1.4 to perform the update.
✔ Package successfully installed.
Using package manager: 'npm'
Collecting installed dependencies...
Found 25 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "13.1.4" (was "13.1.1")...
    Updating package.json with dependency @angular/cli @ "13.1.4" (was "13.1.1")...
    Updating package.json with dependency @angular/compiler-cli @ "13.1.3" (was "13.1.0")...
    Updating package.json with dependency @angular/animations @ "13.1.3" (was "13.1.0")...
    Updating package.json with dependency @angular/common @ "13.1.3" (was "13.1.0")...
    Updating package.json with dependency @angular/compiler @ "13.1.3" (was "13.1.0")...
    Updating package.json with dependency @angular/core @ "13.1.3" (was "13.1.0")...
    Updating package.json with dependency @angular/forms @ "13.1.3" (was "13.1.0")...
    Updating package.json with dependency @angular/platform-browser @ "13.1.3" (was "13.1.0")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "13.1.3" (was "13.1.0")...
    Updating package.json with dependency @angular/router @ "13.1.3" (was "13.1.0")...
  UPDATE package.json (1136 bytes)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: plm-ui@0.0.0
npm ERR! Found: @angular-devkit/build-angular@13.1.1
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~13.1.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~13.1.4" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/core@13.1.3
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"13.1.3" from @angular/service-worker@13.1.3
npm ERR!   node_modules/@angular/service-worker
npm ERR!     peerOptional @angular/service-worker@"^13.0.0 || ^13.1.0-next" from @angular-devkit/build-angular@13.1.4
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       dev @angular-devkit/build-angular@"~13.1.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

</code></pre>

## 🌍 Your Environment

node version 16.13.1
npm version 8.1.2
mac os 10.15.7

**Comment by alan-agius4** [comment] 2022-01-25 12:53
Duplicate of https://github.com/angular/angular-cli/issues/21204

**Closed by alan-agius4** 2022-01-25 12:53 UTC

**Comment by jayhamilton** [comment] 2022-01-25 21:50
@alan-agius4  In that closed issue there is a workaround to use --force, which I did and that just caused more issues. That leaves me with 
Switching to yard or downgrading npm? Is that it?

**Comment by alan-agius4** [comment] 2022-01-26 05:56
Yes, that is right

**Comment by vanessag** [comment] 2022-01-26 18:49
I am having the same issue even updating minor angular 12 versions with same version of node and npm. Are we expected to use the force flag every time we upgrade angular? It seems like there should be a better solution.

It's not a very good user experience to upgrade and then see an error message and have your entire node_modules folder deleted and have to back out and start over.

**Comment by alan-agius4** [comment] 2022-01-26 19:23
@vanessag, unfortunately the error is from NPM 7+ and due to a bug in their peer dependency resolution logic. 

See https://github.com/npm/cli/issues/3666 for more context.

In case you are experiencing the error and want to use NPM 7+, the `-—force` needs to be used. You can also use an alternate package manage such as Yarn which don’t have this bug. You can also downgrade and use NPM 6.

**Comment by vanessag** [comment] 2022-01-26 20:19
@alan-agius4 Thank you for the explanation. I will follow that thread and hopefully npm will have a fix for it at some point.
