### ISSUE TITLE
Imported CSS from linked node packages don't get updated on change

### ISSUE THREAD

**Issue by simeonoff** [angular/angular-cli#9516] opened 2018-02-05 17:49 UTC
### Versions
```
Angular CLI: 1.6.0
Node: 8.9.2
OS: macOS High Sierra 10.13.3
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
* Create a new app using the CLI  `ng new app`
* Link a local node package using npm link `npm link name-of-package`
* Add a CSS file to the styles array in the angular-cli.json file from the linked node package
* Run `ng serve --preserve-symlinks`
* Change the content of the linked CSS file and save it

### Observed behavior
The changes made to the styles from the imported CSS don't get reflected in the injected styles in the head of the app until the ng server is restarted, even when reloading of the entire page.

### Desired behavior
The updated styles should get re-injected in the head upon change.

**Comment by simeonoff** [comment] 2018-02-05 20:24
Can confirm the same behavior in v1.6.6.

**Comment by mgechev** [comment] 2019-08-19 20:24
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:24 UTC
Labels: comp: devkit/build-angular, freq1: low, severity2: inconvenient, type: bug/fix
