### ISSUE TITLE
Generator dosn't work with latest varsion @angular-devkit/schematics

### ISSUE THREAD

**Issue by dean992008** [angular/angular-cli#9012] opened 2017-12-28 08:46 UTC
### Versions
```
Angular CLI: 1.6.3
Node: 8.9.1
OS: linux x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.40
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
If update @angular-devkit/schematics to 0.0.42 and run "ng g c _helpers/alert " get a crash and error: "input.mergeMap is not a function". @angular-devkit/schematics@0.0.40 work is well

### Observed behavior
```
TypeError: input.mergeMap is not a function
    at Object.callRule (/home/dean/work/admin-mo-cash/node_modules/@angular-devkit/schematics/src/rules/call.js:78:18)
    at SchematicImpl.call (/home/dean/work/admin-mo-cash/node_modules/@angular-devkit/schematics/src/engine/schematic.js:35:23)
    at Promise (/home/dean/work/admin-mo-cash/node_modules/@angular/cli/tasks/schematic-run.js:73:23)
    at new Promise (<anonymous>)
    at Class.run (/home/dean/work/admin-mo-cash/node_modules/@angular/cli/tasks/schematic-run.js:72:16)
    at Class.run (/home/dean/work/admin-mo-cash/node_modules/@angular/cli/commands/generate.js:161:33)
    at resolve (/home/dean/work/admin-mo-cash/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (/home/dean/work/admin-mo-cash/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/home/dean/work/admin-mo-cash/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)

**Comment by Brocco** [comment] 2017-12-28 17:33
Duplicate of #8912

**Closed by Brocco** 2017-12-28 17:33 UTC
Labels: priority: 1 (urgent), type: bug
