### ISSUE TITLE
Auto add in git after generated

### ISSUE THREAD

**Issue by WahlbergRu** [angular/angular-cli#6550] opened 2017-06-02 10:01 UTC
### Bug Report or Feature Request (mark with an `x`)
``` 
- [x] feature request
```

### Desired functionality.
I need want to add files to git (manually) after they were generated. Can you add auto-add to git (option)?

**Comment by tytskyi** [comment] 2017-06-02 10:14
https://github.com/angular/angular-cli/wiki/new `--skip-git`

**Comment by filipesilva** [comment] 2017-06-06 13:03
Thanks for reporting this issue. However, this issue is a duplicate of an existing issuehttps://github.com/angular/angular-cli/issues/358. This isn't something we're looking at doing for the reasons stated in that issue.

**Closed by filipesilva** 2017-06-06 13:03 UTC
