### ISSUE TITLE
Production build fails with message "Cannot read property 'input' of null"

### ISSUE THREAD

**Issue by maylukas** [angular/angular-cli#4207] opened 2017-01-24 15:43 UTC
### OS?
node:6.9.4 docker container

### Versions.
node@v6.9.4
angular-cli@1.0.0-beta.26

### Repro steps.

After an upgrade to 1.0.0-beta.26 from 1.0.0-beta.24 the app fails to build.
Build always starts with a clean docker container in which the following steps are run:
FROM node:6.9.4
WORKDIR /root/
RUN npm install angular-cli@1.0.0-beta.26 -g

COPY package.json ./package.json
RUN npm install

COPY src ./src/
COPY e2e ./e2e/
COPY angular-cli.json ./angular-cli.json
COPY protractor.conf.js ./protractor.conf.js
COPY karma.conf.js ./karma.conf.js
COPY tslint.json ./tslint.json

RUN ng build --prod

Prod build works when running on the development machine with Windows 7

### The log given by the failure.
Cannot read property 'input' of null
TypeError: Cannot read property 'input' of null
    at ObjectSchemaTreeNode._set (/root/node_modules/@ngtools/json-schema/src/sc
hema-tree.js:347:132)
    at new ObjectSchemaTreeNode (/root/node_modules/@ngtools/json-schema/src/sch
ema-tree.js:331:14)
    at OneOfSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/root/nod
e_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
    at /root/node_modules/@ngtools/json-schema/src/schema-tree.js:260:26
    at Array.map (native)
    at new OneOfSchemaTreeNode (/root/node_modules/@ngtools/json-schema/src/sche
ma-tree.js:259:48)
    at ArraySchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/root/nod
e_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
    at ArraySchemaTreeNode._set (/root/node_modules/@ngtools/json-schema/src/sch
ema-tree.js:434:39)
    at new ArraySchemaTreeNode (/root/node_modules/@ngtools/json-schema/src/sche
ma-tree.js:414:14)
    at ObjectSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/root/no
de_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
    at ObjectSchemaTreeNode._set (/root/node_modules/@ngtools/json-schema/src/sc
hema-tree.js:347:47)
    at new ObjectSchemaTreeNode (/root/node_modules/@ngtools/json-schema/src/sch
ema-tree.js:331:14)
    at ArraySchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/root/nod
e_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
    at ArraySchemaTreeNode._set (/root/node_modules/@ngtools/json-schema/src/sch
ema-tree.js:434:39)
    at new ArraySchemaTreeNode (/root/node_modules/@ngtools/json-schema/src/sche
ma-tree.js:414:14)
    at RootSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/root/node
_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
    at RootSchemaTreeNode.ObjectSchemaTreeNode._set (/root/node_modules/@ngtools
/json-schema/src/schema-tree.js:347:47)
    at RootSchemaTreeNode.ObjectSchemaTreeNode [as constructor] (/root/node_modu
les/@ngtools/json-schema/src/schema-tree.js:331:14)
    at new RootSchemaTreeNode (/root/node_modules/@ngtools/json-schema/src/schem
a-tree.js:478:16)
    at GeneratedSchemaClass.SchemaClassBase (/root/node_modules/@ngtools/json-sc
hema/src/schema-class-factory.js:66:29)
    at new GeneratedSchemaClass (/root/node_modules/@ngtools/json-schema/src/sch
ema-class-factory.js:165:20)
    at new CliConfig (/root/node_modules/angular-cli/models/config/config.js:24:
24)
    at Function.CliConfig.fromConfigPath (/root/node_modules/angular-cli/models/
config/config.js:99:16)
    at Function.CliConfig.fromProject (/root/node_modules/angular-cli/models/con
fig.js:63:44)
    at Class.run (/root/node_modules/angular-cli/tasks/build-webpack.js:14:73)
    at Class.buildRun (/root/node_modules/angular-cli/commands/build.run.js:39:2
2)
    at Class.run (/root/node_modules/angular-cli/commands/build.js:38:47)
    at Class.<anonymous> (/root/node_modules/angular-cli/ember-cli/lib/models/co
mmand.js:147:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
The command '/bin/sh -c ng build --prod' returned a non-zero code: 1
### Mention any other details that might be useful.
angular-cli.json

{
  "project": {
    "version": "1.0.0-alpha.2",
    "name": "core-ui"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "genDir": "gen",
      "assets": ["assets"],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "scss/style.scss"
      ],
      "scripts": [
        "../node_modules/pace-js/pace.min.js",
        "../node_modules/chart.js/dist/Chart.bundle.min.js",
        "../node_modules/chart.js/dist/Chart.min.js"
      ],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false
  }
}

**Comment by maylukas** [comment] 2017-01-24 16:15
I don't know the cause of the issue as i did not invest enough time to understand the parsing of the configuration but if I change Line 347 in @ngtools/json-schema/src/schema-tree.js from
`
this._children[name_1] = this._createChildProperty(name_1, value ? value[name_1] : null, forward ? forward.children[name_1] : null, propertySchema);
`
to this:
`
this._children[name_1] = this._createChildProperty(name_1, value ? value[name_1] : null, forward  && forward.children ? forward.children[name_1] : null, propertySchema);
`

it works again

**Comment by filipesilva** [comment] 2017-01-24 18:21
Can you show me your `angular-cli.json`? Maybe you have a property there that's not supported anymore or something.

**Comment by maylukas** [comment] 2017-01-25 07:30
I actually provided it in the issue description under "Mention any other details that might be useful.".

**Comment by hoatle** [comment] 2017-01-26 14:28
I'm having the same exact problem.

**Comment by hoatle** [comment] 2017-01-29 06:05
I guess this is the root cause (related to Docker, not sure about other cases).

When I have angular app under $HOME path, I got the same exact problem.

When I move the angular app out of $HOME path, it works as expected, no error.

**Comment by alexweber** [comment] 2017-02-01 22:33
@hoatle Thanks for taking the time to share this, can't say how happy I am to have this working finally! :)

**Comment by giertych97** [comment] 2017-02-02 01:16
Today I've updated angular-cli and now I get this same error.

**Comment by alexweber** [comment] 2017-02-02 01:26
@giertych97 That's unrelated to this particular issue.  See here for a fix: https://github.com/angular/angular-cli/issues/4326#issuecomment-276819350

**Comment by dustintheweb** [comment] 2017-02-02 14:05
@filipesilva I have had the same issue in my production builds to Heroku since Beta 25 (Beta 24 & earlier worked great, however I just updated to Beta 28 & can confirm the issue still exists).

```
2017-02-02T13:23:29.383781+00:00 app[web.1]: TypeError: Cannot read property 'input' of null
2017-02-02T13:23:29.383783+00:00 app[web.1]:     at new ObjectSchemaTreeNode (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:331:14)
```

I believe it may have something to do with the JSON Schema feature added in Beta 25:
```
@ngtools/json-schema: Introduce a separate package for JSON schema. (#3927) (74f7cdd)
```

This does not happen when I ick off a build in my local environment `npm start` - all things are working as expected on localhost:4300. It is only when I deploy & Heroku kicks off the `npm start` that it will fail on the 'ng build' (it breaks before it is able to create a /dist folder)

This type of error message is similar to the ones seen when an npm package is missing a Types declaration file - unfortunately, one does not exist for the JSON Schema package. Maybe this is related to that?

I made a comment on this in another thread a while back but didn't follow up until just now - here's a link for [additional context](https://github.com/angular/angular-cli/issues/4068#issuecomment-274259494)

Hopefully this provides some additional insight to the bug

**Comment by dlimkin** [comment] 2017-02-02 21:20
Maybe this will help. I accidentally called ng init in Нome directory, after the launch of the ng in any other directory caused the error (even when call ng --version). After deleting ng files from the home directory. ng runs without errors

**Comment by juanmcampos** [comment] 2017-02-02 22:16
@dustintheweb did you find any solution?

**Comment by Mattee** [comment] 2017-02-03 08:44
@dlimkin Thank you, it solved my problem! It seems like I had some old Angular files in the root of my home directory causing all Angular projects in there with later Angular-cli versions to fail. So by deleting all files and folders that doesn't belong to the home directory, it solves the problems and the errors disappears.

**Comment by robertorosas** [comment] 2017-02-03 16:46
@dlimkin solution works. Thanks.

**Comment by dustintheweb** [comment] 2017-02-03 17:49
For me, this issue is weirdly specific to a new build, only in my live production environment (Heroku / Ubuntu). Everything gets built fresh from the package.json (no old files), so no possibilities of similar `ng` gremlins for me in that regard.

Can anyone with a similar production env also confirm that this is an issue?

**Comment by alexweber** [comment] 2017-02-03 17:56
@dustintheweb I'm getting it too and only when building in Docker

**Comment by hoatle** [comment] 2017-02-04 04:00
anyone using Docker, I recommend using this Docker image to get started https://hub.docker.com/r/teracy/angular-cli/tags/

or you can use this seed project https://github.com/teracyhq/angular-boilerplate that I'm working on

I do not have any issues so far with these 2 projects.

**Comment by alexweber** [comment] 2017-02-04 14:19
@hoatle Thanks for the tip!  Unfortunately my project's openshift s2i environment doesn't allow me to use docker images (even though OC itself supports it), we're currently using: https://hub.docker.com/r/ryanj/centos7-s2i-nodejs/ which is itself pretty out of date, sigh. :(

**Comment by nurbsurf** [comment] 2017-02-04 14:55
OSX 10.12.3
NPM 4.2.0
[ISSUE]
Encounter the same issue when I updated angular-cli and ran $ng new appname. App wouldn't build. 

[RESOLVED]

1. ran `npm uninstall angular-cli -g`
2. ran ` npm uninstall angular-cli --save`
3. Confirmed angular-cli was not in angular-cli `/usr/local/lib/node_modules` 
4. Confirmed angular-cli was not in `/Users/username/node_modules`
5. Confirmed there was no package.json or angular package files in `/Users/username/`
6. Reinstall angular cli `npm install angular-cli -g`
7. Ran ` ng -v` output `angular-cli: 1.0.0-beta.28.3` `node: 7.3.0` `os: darwin x64`
8. Successfully created new project with ng new project

I think my main issue was having a package.json in my `/Users/username/`

**Comment by mikejpeters** [comment] 2017-02-06 22:50
To add to what others have mentioned, on Ubuntu if you have an `angular-cli.json` file in your home directory, it seems to get read (and maybe merged) whenever running `ng` commands in any folder. If you have a project in your home directory the `json` file seems to get read twice, which screws up parsing if you specify `styles` property.

Simplest way to see this behavior is to create an empty `angular-cli.json` in your home directoy, and then run the `angular-cli` tests, many of which will fail:

```sh
touch ~/angular-cli.json 

git clone https://github.com/angular/angular-cli.git
cd angular-cli
npm install && npm test
```

@filipesilva is this expected behaviour?

**Comment by filipesilva** [comment] 2017-03-13 18:49
Thanks for all the work investigating this issue. @mikejpeters I can confirm this isn't intended and is in fact a bug.

**Comment by sumitarora** [comment] 2017-03-17 15:23
@mikejpeters Which version of CLI are you using? Fallback mechanism has already been changed and fixed https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/models/config.ts#L105 I tried to replicate issue and seems to be working fine.

**Comment by mikejpeters** [comment] 2017-03-17 16:16
I haven't tested with the latest version, but from reading the source code I don't see any reason the issue would be fixed.

The issue is that the global config is merged with the project config _even if they are the exact same path (i.e. project folder = home folder)_.

**Comment by ipassynk** [comment] 2017-04-21 15:39
i just run today to this issue with latest cli and angular-cli.json file in the home. It looks like issue is still there.

**Comment by syscools** [comment] 2017-04-25 18:50
I am having this problem when launching it from within Bluemix shell environment only but not in my docker environment:
```Shell
vcap@af80c6a0-788b-44c6-586d-5423ba47ebde:~$ ng build                                                                                                                     
Cannot read property 'config' of null                                                                                                                                     
TypeError: Cannot read property 'config' of null                                                                                                                          
    at Class.run (/home/vcap/app/node_modules/@angular/cli/tasks/build.js:16:56)                                                                                          
    at Class.run (/home/vcap/app/node_modules/@angular/cli/commands/build.js:143:26)                                                                                      
    at Class.<anonymous> (/home/vcap/app/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)                                                                
    at process._tickCallback (internal/process/next_tick.js:109:7)                                                                                                        

```

In my Bluemix web shell environment settings are:
```Shell
vcap@af80c6a0-788b-44c6-586d-5423ba47ebde:~$ ng --version                                                                                                                 
    _                      _                 ____ _     ___                                                                                                               
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|                                                                                                              
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |                                                                                                               
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |                                                                                                               
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|                                                                                                              
               |___/                                                                                                                                                      
@angular/cli: 1.0.0-rc.2                                                                                                                                                  
node: 7.9.0                                                                                                                                                               
os: linux x64                                                                                                                                                             
@angular/cli: 1.0.0-rc.2                                                                                                                                                  
@angular/common: 4.0.3                                                                                                                                                    
@angular/compiler: 4.0.3                                                                                                                                                  
@angular/core: 4.0.3                                                                                                                                                      
@angular/forms: 4.0.3                                                                                                                                                     
@angular/http: 4.0.3                                                                                                                                                      
@angular/platform-browser: 4.0.3                                                                                                                                          
@angular/platform-browser-dynamic: 4.0.3                                                                                                                                  
@angular/router: 4.0.3                                                                                                                                                    
@angular/compiler-cli: 4.0.3                                                                                                                                              
vcap@af80c6a0-788b-44c6-586d-5423ba47ebde:~$ node --version                                                                                                               
v7.9.0                                                                                                                                                                    
vcap@af80c6a0-788b-44c6-586d-5423ba47ebde:~$                                                                                                                              
                                                       
```
And in my local machine docker settins are:
```Shell
┌─[127|]─[master]─<default2:~/src/mean-app>
└node_modules/\@angular/cli/bin/ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.2
node: 7.9.0
os: linux x64
@angular/cli: 1.0.0-rc.2
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/compiler-cli: 4.0.3
┌─[0|]─[master]─<default2:~/src/mean-app>
└node --version
v7.9.0
┌─[0|]─[master]─<default2:~/src/mean-app>
└
```

**Comment by filipesilva** [comment] 2017-05-10 11:06
@sumitarora can you have another look at this? There's a couple more reports that seem to indicate some problem with the config merging logic:
- heroku seems to need explicit redeclare of the `HOME` var: https://github.com/angular/angular-cli/issues/5808#issuecomment-298309209
- seems to be happening outside of heroku as well: https://github.com/angular/angular-cli/issues/6227

**Comment by vinittcs** [comment] 2017-07-05 17:29
Hi, I am changing the schema.js file manually and it works fine. But
I want to implement : this._children[name_1] = this._createChildProperty(name_1, value ? value[name_1] : null, forward && forward.children ? forward.children[name_1] : null, propertySchema);
in my node modules automatically using ng build through gradle. I am download node v6.9.2 and running npm install and build using gradle task. I get the same error. 
Please suggest. Is it a version issue or something else?

**Comment by sdsanders** [comment] 2017-09-14 21:01
Still running into this (on dokku) with the latest version of the cli.

**Comment by jskrnbindra** [comment] 2017-09-21 14:06
The issue still exists on latest @angular/cli 3.10.10..
Works on my windows machine but throws this error:

> `TypeError: Cannot read property 'glob' of null`

on centos in aws.

All was good until today morning when the error just popped up while running:
`ng build && node server.js`

on CentOS.

Is there a fix?

**Comment by Gpzim98** [comment] 2017-10-08 13:13
Thank you SO much @dlimkin 
Such a stp issue!

**Comment by ysilvestrov** [comment] 2017-12-17 23:00
The same issue for me with dokku today.
Updated @angular/cli to 1.6.1 with no help.

Could we expect a fix?
The non-working repo, if needed, is https://github.com/ysilvestrov/ontap-tv

**Comment by codestation** [comment] 2017-12-19 16:01
@ysilvestrov redefine HOME to any other directory before building, for example i have this in my package.json

```
    "heroku-postbuild": "HOME=/tmp/build ng build --target=production -e ${NODE_ENV:-production} --aot --no-progress"
```

The bug appears when $HOME contains a .angular-cli.json and since dokku puts the project in $HOME then the bug triggers

**Comment by clydin** [comment] 2018-09-25 17:53
Closing as version `1.0.0-beta.26` is a prerelease version and no longer supported.  If the problem persists within the latest stable version (currently 6.2.3), please open a new issue detailing the problem.

**Closed by clydin** 2018-09-25 17:53 UTC
Labels: effort1: easy (hours), priority: 1 (urgent), severity5: regression, type: bug/fix
