### ISSUE TITLE
global variable in js files called in script array in angular-cli.json

### ISSUE THREAD

**Issue by mrbraca15** [angular/angular-cli#3742] opened 2016-12-26 13:49 UTC
Hello people, i'm trying to declarate a global variable in one of my js files and called this variable in other js file, in angular-cli.json I have the following:

{
	"project": {
		"version": "1.0.0-beta.21",
		"name": "xxxx"
	},
	"apps": [{
		"root": "app",
		"outDir": "dist",
		"assets": [
			"assets",
			"favicon.ico",
			"fonts",
			"images",
			"json",
			"styles",
			"vendor",
			"views",
			"404.html"
		],
		"index": "app.html",
		"main": "tsScripts/Main.ts",
		"test": "test.ts",
		"tsconfig": "tsconfig.json",
		"prefix": "app",
		"mobile": false,
		"styles": [],
		"scripts": ["file1.js","file2.js"],
		"environments": {
			"source": "environments/environment.ts",
			"dev": "environments/environment.ts",
			"prod": "environments/environment.prod.ts"
		}
	}],
	"addons": [],
	"packages": [],
	"e2e": {
		"protractor": {
			"config": "./protractor.conf.js"
		}
	},
	"test": {
		"karma": {
			"config": "./karma.conf.js"
		}
	},
	"defaults": {
		"styleExt": "css",
		"prefixInterfaces": false,
		"inline": {
			"style": false,
			"template": false
		},
		"spec": {
			"class": false,
			"component": true,
			"directive": true,
			"module": false,
			"pipe": true,
			"service": true
		}
	}
}

in file1.js i have:

`var title='my title';`

and in file2.js i have:

`console.log(title);`

when i run in console ng serve show this:

`
Uncaught ReferenceError: title is not defined
    at eval (eval at module.exports (addScript.js:9), <anonymous>:62:13)
    at eval (<anonymous>)
    at module.exports (addScript.js:9)
    at Object.<anonymous> (modalDecorator.js?0e5f:1)
    at __webpack_require__ (bootstrap 36a9fd0…:52)
    at Object.<anonymous> (scripts.bundle.js:4950)
    at __webpack_require__ (bootstrap 36a9fd0…:52)
    at webpackJsonpCallback (bootstrap 36a9fd0…:23)
    at scripts.bundle.js:1
`

my node version is 7.2.1, angular-cli version is:  1.0.0-beta.24 in windows 7 64bits.

**Comment by filipesilva** [comment] 2016-12-30 20:45
Dupe of https://github.com/angular/angular-cli/issues/3782 I think.

**Closed by filipesilva** 2016-12-30 20:45 UTC

**Comment by filipesilva** [comment] 2016-12-31 22:03
Heya, I just checked and this works, but I checked in beta.24. Maybe in beta.21 the functionality wasn't fully there, not sure.
![image](https://cloud.githubusercontent.com/assets/4172079/21579398/dd85bd28-cfa4-11e6-9f6f-a7226140fc9e.png)
