### ISSUE TITLE
developer can change uglify options dynamically

### ISSUE THREAD

**Issue by MadfishDT** [angular/angular-cli#12399] opened 2018-09-28 14:50 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node --version = v8.11.4
npm --version = 6.1.0
Angular CLI: 6.2.3
Windows 10, macOS(Sierra, High Sierra)

### Repro steps
when I communicate between each window with pre-defined interface, to distinguish what kind of data, I use pre-defined interface name(constructor name). but uglify broken constructor name. so I can't compare each data after prod build

### The log given by the failure
```
SyntaxError: Unexpected token: name
```

### Desired functionality
.angular-cli.json have uglify options file path in build option(uglify.json) and user can change uglify options. it's very tiny change. 
1. defined options shape 2.common.ts modify.
```
    export interface BuildOptions {
    uglify?: string;
    optimization: boolean;
    environment?: string;
```
in commmon.ts
```
    const uglifyOptions = JSON.parse(fs.readSync(path.resolve(root, buildOptions.uglify));
````

**Comment by alan-agius4** [comment] 2018-11-07 12:59
Duplicate of 
https://github.com/angular/angular-cli/issues/3861 and 
https://github.com/angular/angular-cli/issues/11910

**Closed by alan-agius4** 2018-11-07 12:59 UTC
Labels: comp: devkit/build-angular, type: feature
