### ISSUE TITLE
The ability to resolve SASS using the library namespace in workspace projects

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#25311] opened 2023-06-02 17:27 UTC
### Command

build

### Description

I wrote up the description in this SO question:

https://stackoverflow.com/questions/76387206/resolving-a-library-projects-sass-files-from-an-application-in-the-same-workspac

### Describe the solution you'd like

Also in the SO question:
https://stackoverflow.com/questions/76387206/resolving-a-library-projects-sass-files-from-an-application-in-the-same-workspac

### Describe alternatives you've considered

Relative imports ...

**Comment by alan-agius4** [comment] 2023-06-02 18:15
Duplicate of https://github.com/angular/angular-cli/issues/23552

**Closed by alan-agius4** 2023-06-02 18:15 UTC
