### ISSUE TITLE
Angular 10: ng serve not working in IE 11- but ng build --prod works fine in IE 11 when deployed the build to a server

### ISSUE THREAD

**Issue by sistla001** [angular/angular-cli#18235] opened 2020-07-13 03:46 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, This is working fine with Angular 9.

### Description

 Create a new angular 10 application using angular cli 10.0.3. Opt in for IE 11 in .browserslistrc. Run `ng serve` . Works fine in chrome but doesn't show anything in IE11. There is no console error as well. 
Note: Works in IE 11 when deployed the build to a server. `ng build --prod` outputs es5 and es2015 bundles.

## 🔥 Exception or Error
<pre><code>

No Exception or Error in IE console

</code></pre>

## 🌍 Your Environment
<pre><code>

 10.0.2

</code></pre>

**Anything else relevant?**

Yes, it is browser specific issue. 
IE 11 
version: 11.900.18362.0
Update Versions: 11.0.195

**Comment by destus90** [comment] 2020-07-13 05:01
Duplicate of https://github.com/angular/angular-cli/issues/14455

**Comment by alan-agius4** [comment] 2020-07-13 08:20
Duplicate of #14455

**Closed by alan-agius4** 2020-07-13 08:20 UTC

**Comment by sistla001** [comment] 2020-07-13 16:01
> Duplicate of #14455

14455 is an Angular 8 issue. this issue is with the latest CLI (10.0.2). It seems like it got resurfaced, shouldn't this be open until it is resolved for 10.0.2?

**Comment by alan-agius4** [comment] 2020-07-13 16:30
@sistla001, this is not a bug and is working as expected.

See: https://github.com/angular/angular-cli/issues/14455#issuecomment-493739768

**Comment by sistla001** [comment] 2020-07-14 00:46
Understood.. Thanks for pointing out.. I didn't realize that I updated target to es2015 when updating to angular 10.
