### ISSUE TITLE
tsconfig paths not respected for styles

### ISSUE THREAD

**Issue by nnixaa** [angular/angular-cli#9018] opened 2017-12-28 16:32 UTC
So the issue is that the `paths` setting from the `tsconfig.app.json` is not respected for style files imports since the cli 1.3.0.

My setup is that I have a module inside of my project, aliased in `tsconfig.app.json` using:
```
    ...

    "paths": {
      "@core/*": [
        "./core/*"
      ]
    }
```
The module consists of various ts and scss files.

The files are imported as:
`import { SomeClass } from '@core/module/file';`

and for styles as:
`@import '~@core/module/styles'; // this fails since 1.3.0`

Since angular-cli@1.3.0 the styles import of this kind is not working.

Simple reproducible example:

https://github.com/nnixaa/cli-scss-alias-issue/commit/40c33c8db58ae6f9b6c73670f0a16624428d388a

### Versions
```
tested and reproducible on cli 1.3.0, 1.6.2, 1.6.3
tested and works fine on cli 1.2.6, 1.2.7
```

### Repro steps
- clone the project https://github.com/nnixaa/cli-scss-alias-issue
- run `npm start`

### Observed behavior

```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module build failed:
@import '~@core/module/styles'; // this fails since 1.3.0
^
      File to import not found or unreadable: ~@core/module/styles.
Parent style sheet: stdin
      in /Users/nixa/Development/Sandbox/scss-alias-tsconfig/src/styles.scss (line 2, column 1)
Error:
@import '~@core/module/styles'; // this fails since 1.3.0
^
      File to import not found or unreadable: ~@core/module/styles.
Parent style sheet: stdin
      in /Users/nixa/Development/Sandbox/scss-alias-tsconfig/src/styles.scss (line 2, column 1)
    at options.error (/Users/nixa/Development/Sandbox/scss-alias-tsconfig/node_modules/node-sass/lib/index.js:291:26)
 @ ./src/styles.scss 4:14-191
 @ multi ./src/styles.scss
```

### Desired behavior
Should import styles correctly as per configured `paths` setting.

### Possibly related
https://github.com/angular/angular-cli/issues/8117 (workaround used there fixes the issue)
https://github.com/angular/angular-cli/issues/8036

**Comment by PsyGik** [comment] 2018-04-17 15:34
Any updates/fixes/workaround on this?

**Comment by iwantwin** [comment] 2018-05-30 09:39
Any updates on this?

**Comment by radonirinamaminiaina** [comment] 2018-07-28 09:31
Same problem

**Comment by lazysergey** [comment] 2018-08-27 11:35
still valid issue

**Comment by btkfrank** [comment] 2019-02-06 16:27
> still valid issue. workaround for this is to add this entry in `.angular-cli.json`
> 
> ```
>     {
>         "apps": [{
>             ...
>             "stylePreprocessorOptions": {
>                 "includePaths": [
>                     "./app/global-styles"
>                 ]
>             },
>             ...
>         }]
>     }
> ```

Do you know if there is a way to make VS Code go to definition(ctrl/cmd + click) still works?
This can fix the build issue, but I am missing go to definition

**Comment by eestein** [comment] 2019-10-01 19:53
Any news on this? The workaround does not work for me.

My tsconfig:

```typescript
"paths": {
    "@projx/components": [
        "projects/projx/components/src/public_api"
    ],
    "@projx/components/*": [
        "projects/projx/components/*"
    ],
    "~@projx/components/themes/default": [
        "projects/projx/components/src/lib/styles/themes/default.scss"
    ]
}
```

Inside my local SCSS file:

```scss
@import '~@projx/components/themes/default';
```

Still, it doesn't work.

**Comment by alan-agius4** [comment] 2020-05-26 07:55
Closing as this is working as intended. TypeScript config paths are meant to work solely for TypeScript.

As suggested above you can use `includePaths` to shorten your SCSS import.

**Closed by alan-agius4** 2020-05-26 07:55 UTC
Labels: comp: devkit/build-angular, type: feature
