### ISSUE TITLE
Installation problem. (broccoli@1.0.0-beta.6 postinstall)

### ISSUE THREAD

**Issue by alvaromorenomorales** [angular/angular-cli#500] opened 2016-04-22 08:57 UTC
1. Linux (Ubuntu 14.04)
3. Steps:  sudo npm install -g angular-cli
4. The log: 

ubuntu@Laptop:~/dev/angular2$ sudo npm install -g angular-cli
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng

> broccoli@1.0.0-beta.6 postinstall /usr/local/lib/node_modules/angular-cli/node_modules/broccoli
> multidep test/multidep.json

broccoli-plugin 1.0.0: Installing
npm ERR! tar.unpack untar error /home/ubuntu/.npm/broccoli-plugin/1.0.0/package.tgz
npm ERR! Linux 3.19.0-58-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/angular-cli/node_modules/.bin/npm" "install" "broccoli-plugin@1.0.0"
npm ERR! node v5.9.1
npm ERR! npm  v2.14.21
npm ERR! path /usr/local/lib/node_modules/broccoli-plugin
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/broccoli-plugin'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/broccoli-plugin']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/broccoli-plugin',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/broccoli-plugin',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/angular-cli/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/angular-cli/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/angular-cli/node_modules/broccoli/test/multidep/broccoli-plugin-1.0.0/npm-debug.log
Error: npm exited with exit code 243, signal null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/multidep/index.js:90:28)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
/usr/local/lib
└── (empty)

npm ERR! Linux 3.19.0-58-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v5.9.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! broccoli@1.0.0-beta.6 postinstall: `multidep test/multidep.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the broccoli@1.0.0-beta.6 postinstall script 'multidep test/multidep.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the broccoli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     multidep test/multidep.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs broccoli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls broccoli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/dev/angular2/npm-debug.log
npm ERR! code 1
ubuntu@Laptop:~/dev/angular2$ ng --help
El programa «ng» no está instalado. Puede instalarlo escribiendo:
sudo apt-get install ng-common

> ---------------------------------------------------------------
5. Useful details.

I've installed broccoli and broccoli plugin globally and I'm still getting the same error. I also tried to create the missing folder but it also fails saying that the folder can`t be erased: 

npm ERR! path /usr/local/lib/node_modules/broccoli-plugin
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rmdir

npm ERR! Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/broccoli-plugin'

> ---------------------------------------------------------------

Is there a way for bypassing this error? 
Thank in advance
Al.

**Comment by reinos** [comment] 2016-04-22 09:14
+1

**Comment by filipesilva** [comment] 2016-04-22 13:28
This is a dupe of a couple of existing issues so far, but the answers are usually deep inside those threads.

You can find a detailed explanation and solution in https://github.com/angular/angular-cli/issues/389#issuecomment-213420501.

**Closed by filipesilva** 2016-04-22 13:28 UTC

**Comment by alvaromorenomorales** [comment] 2016-04-22 14:55
Thanks it worked perfectly!!
