### ISSUE TITLE
How to customize angular cli to install additional dependencies while we creating new project

### ISSUE THREAD

**Issue by naveen678274** [angular/angular-cli#9593] opened 2018-02-11 04:03 UTC
let suppose i am creating new project , i need bootstrap to be installed as i run ng new my-app

**Comment by Brocco** [comment] 2018-02-12 19:39
You can comment on this issue with some ideas #9387

Closing this issue as duplicate of #9387

**Closed by Brocco** 2018-02-12 19:39 UTC
