### ISSUE TITLE
pwa

### ISSUE THREAD

**Issue by nyabwana** [angular/angular-cli#3716] opened 2016-12-23 08:09 UTC
OS
Mac OSX ( El Capitan)

angular-cli: 1.0.0-beta.19-3
node: 6.7.0
os: darwin x64

When should we expect the mobile flag to be reactivated? Also, what do we have to do in order to create Progressive web apps now? Angular mobile seems so dependent on cli yet the --mobile flag has been dead for a while now.

**Comment by filipesilva** [comment] 2016-12-30 18:11
Dupe of https://github.com/angular/angular-cli/issues/2228.

**Closed by filipesilva** 2016-12-30 18:11 UTC
