### ISSUE TITLE
Dot notation in name of class after ng g class <name.component>

### ISSUE THREAD

**Issue by ArturAntonov** [angular/angular-cli#9453] opened 2018-01-31 13:48 UTC
### Versions
```
Angular CLI: 1.6.5
Node: 7.10.1
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0


```

### Repro steps

* Step 1
**use** 
```
ng g class view.action
```
**result**
create src/app/view.action.ts (29 bytes)
**text in created file:**
```
export class View.Action {
}
```

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

### Desired behavior

I 'd like to create class with dot in file name. And i'd like to get className in normal PascalCase.

### Mention any other details that might be useful (optional)

If i generate class with command
```
ng g class view-action
```
then I get normal name of class ViewAction. But I need to generate files with dot.

Thank you.

**Comment by dgp1130** [comment] 2020-05-30 00:27
Duplicate of #13824.

Also related to #11051.

**Closed by dgp1130** 2020-05-30 00:27 UTC
Labels: comp: schematics/angular, freq2: medium, severity2: inconvenient, triage #1, type: bug/fix
