### ISSUE TITLE
ng build --watch --watch-matcher="Compiled successfully" --watch-script=sayhi.js

### ISSUE THREAD

**Issue by OlecsandrKirpa** [angular/angular-cli#24807] opened 2023-03-03 12:13 UTC
### Command

build

### Description

Hello, it would be really cool to be able to execute some code once project has been built again.

```
ng build --watch --watch-matcher="Compiled successfully" --watch-script=sayhi.js
```

After each change, the application gets built, and if --watch-matcher="Compiled successfully" is successful, call the .js file.

### Describe the solution you'd like

if I am in the root of my project, and we have a file called sayhi.js.
```js
// /root/of/app/sayhi.js
console.log('hi');
```
and I start
```
ng build --watch --watch-matcher="Compiled successfully" --watch-script=sayhi.js
```
then, when I change something in my app, app gest built, and if successful, I must see
```
hi
```

**Comment by OlecsandrKirpa** [comment] 2023-03-03 18:15
Hello, I would like to add an example to be more specific.
I'd like the command
```
ng build --watch --watch-matcher="Compiled successfully" --watch-script=sayhi.js
```
to be equivalent to running, when there are some changes,
```
ng build && node sayhi.js
```

btw i know there are some other solutions like "run-when-changed" but a native solution would definetly work better.

Thanks!
Sasha

**Comment by alan-agius4** [comment] 2023-03-07 13:22
Duplicate of https://github.com/angular/angular-cli/issues/11787

**Closed by alan-agius4** 2023-03-07 13:22 UTC
