### ISSUE TITLE
Can't start test

### ISSUE THREAD

**Issue by mangelozzi** [angular/angular-cli#28356] opened 2024-09-05 09:29 UTC
### Command

test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I tried to follow the the [test tutorial](https://angular.dev/guide/testing), but when when I try to run the test runner, it falls over. Most of the help is about allowing a certain file, but there is nothing about allowing a data URL file path. I have no idea and can't find documentation on how to add it to a `tsconfig` file so it can be built.

### Minimal Reproduction

It's a giant code base, I don't know how to make it Minimal.

But here are the relevant parts:
```
// tsconfig.spec.json
/* To learn more about this file see: https://angular.io/config/tsconfig. <---- PS this link no longer works*/
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "outDir": "./out-tsc/spec",
        "types": ["jasmine"]
    },
    "include": ["src/**/*.spec.ts", "src/**/*.d.ts"]
}
```

### Exception or Error

```text
$ npm run ng test

> ng-client@0.0.0 ng
> ng test

✔ Browser application bundle generation complete.

ng-virtual-main.js!=!data:text/javascript;base64,CiAgaW1wb3J0IHsgZ2V0VGVzdEJlZCB9IGZyb20gJ0Bhbmd1bGFyL2NvcmUvdGVzdGluZyc7CiAgaW1wb3J0IHsKICAgIEJyb3dzZXJEeW5hbWljVGVzdGluZ01vZHVsZSwKICAgIHBsYXRmb3JtQnJvd3NlckR5bmFtaWNUZXN0aW5nLAogICB9IGZyb20gJ0Bhbmd1bGFyL3BsYXRmb3JtLWJyb3dzZXItZHluYW1pYy90ZXN0aW5nJzsKCiAgLy8gSW5pdGlhbGl6ZSB0aGUgQW5ndWxhciB0ZXN0aW5nIGVudmlyb25tZW50LgogIGdldFRlc3RCZWQoKS5pbml0VGVzdEVudmlyb25tZW50KEJyb3dzZXJEeW5hbWljVGVzdGluZ01vZHVsZSwgcGxhdGZvcm1Ccm93c2VyRHluYW1pY1Rlc3RpbmcoKSwgewogICAgZXJyb3JPblVua25vd25FbGVtZW50czogdHJ1ZSwKICAgIGVycm9yT25Vbmtub3duUHJvcGVydGllczogdHJ1ZQogIH0pOwo= - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: data:text/javascript;base64,CiAgaW1wb3J0IHsgZ2V0VGVzdEJlZCB9IGZyb20gJ0Bhbmd1bGFyL2NvcmUvdGVzdGluZyc7CiAgaW1wb3J0IHsKICAgIEJyb3dzZXJEeW5hbWljVGVzdGluZ01vZHVsZSwKICAgIHBsYXRmb3JtQnJvd3NlckR5bmFtaWNUZXN0aW5nLAogICB9IGZyb20gJ0Bhbmd1bGFyL3BsYXRmb3JtLWJyb3dzZXItZHluYW1pYy90ZXN0aW5nJzsKCiAgLy8gSW5pdGlhbGl6ZSB0aGUgQW5ndWxhciB0ZXN0aW5nIGVudmlyb25tZW50LgogIGdldFRlc3RCZWQoKS5pbml0VGVzdEVudmlyb25tZW50KEJyb3dzZXJEeW5hbWljVGVzdGluZ01vZHVsZSwgcGxhdGZvcm1Ccm93c2VyRHluYW1pY1Rlc3RpbmcoKSwgewogICAgZXJyb3JPblVua25vd25FbGVtZW50czogdHJ1ZSwKICAgIGVycm9yT25Vbmtub3duUHJvcGVydGllczogdHJ1ZQogIH0pOwo= is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```

### Your Environment

```text
$ npm run ng version

> ng-client@0.0.0 ng
> ng version


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.2.3
Node: 20.9.0
Package Manager: npm 10.1.0
OS: linux x64

Angular: 17.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.3
@angular-devkit/build-angular   17.2.3
@angular-devkit/core            17.2.3
@angular-devkit/schematics      17.2.3
@angular/cdk                    17.2.2
@angular/cli                    17.2.3
@angular/material               17.2.2
@angular/ssr                    17.2.3
@schematics/angular             17.2.3
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by alan-agius4** [comment] 2024-09-05 09:32
Duplicate of https://github.com/angular/angular-cli/issues/25936

**Closed by alan-agius4** 2024-09-05 09:32 UTC
