### ISSUE TITLE
How to add `--inspect-brk` to `ng e2e` so we can debug protractor tests while using node 8?

### ISSUE THREAD

**Issue by rjsteinert** [angular/angular-cli#10289] opened 2018-04-11 18:23 UTC
In order to debug protractor tests with node 8 and above, the protractor docs [suggest adding](https://github.com/angular/protractor/blob/master/docs/debugging.md#disabled-control-flow) `--inspect-brk` when running tests.

```
node --inspect-brk bin/protractor <config_file>
```

How do we add that option when running `ng e2e`?

**Comment by hevans90** [comment] 2018-06-05 13:20
The protractor docs seem aimed mainly at AngularJS applications... some clarity would be nice here

**Comment by hevans90** [comment] 2018-06-05 15:12
After some experimentation I managed to get this to work, using the following (disgusting) command:

`node --inspect-brk ./node_modules/\@angular/cli/bin/ng e2e  ./protractor.conf.js`

I ran this in the root of my Angular 6 application, after which my terminal spat this out:

![image](https://user-images.githubusercontent.com/12142999/40984918-dcfae3f8-68da-11e8-914e-d540c05d80ff.png)

And nothing appeared to happen... until I opened a chrome tab on: `chrome://inspect/#devices`:

![image](https://user-images.githubusercontent.com/12142999/40984970-fab24986-68da-11e8-8d5b-4f08a8e2de30.png)

Clicking inspect above opens an instance of DevTools and immediately breaks the code at the top of the `ng` module. Hit continue in your debugger to run your e2e tests, and hit any `debugger` statements in your code!

Happy e2e-ing :)

**Comment by maurei** [comment] 2018-06-14 12:22
@hevans90 

If don't want it to break on the first line change `inspect-brk` to `inspect`

Anyway, I can't get it to work. I need to add `--protractor-config` (and the path because my conf file is in `./e2e/`)

`node --inspect-brk  ./node_modules/\@angular/cli/bin/ng e2e --protractor-config ./e2e/protractor.conf.js`

The error I then get is:
![screen shot 2018-06-14 at 14 19 10](https://user-images.githubusercontent.com/9339132/41411685-eec7065c-6fdd-11e8-8f3b-95dc9ee5f127.png)

I tried to specify a different host:

`node --inspect-brk=9222  ./node_modules/\@angular/cli/bin/ng e2e --protractor-config ./e2e/protractor.conf.js`

and

`node --inspect-brk=9222  ./node_modules/\@angular/cli/bin/ng e2e --protractor-config ./e2e/protractor.conf.js --host=9223`

The first would give exactly the same error as the screenshot, the second gives:
![screen shot 2018-06-14 at 14 22 04](https://user-images.githubusercontent.com/9339132/41411800-57c44d4a-6fde-11e8-8669-da9a5b9bccd4.png)


Some help would be appreciated :-( 

An off-the-shelve solution in angular-cli would be appreciated too!

**Comment by maurei** [comment] 2018-06-15 13:20
The following did the trick for me:

`node --inspect-brk ./node_modules/protractor/bin/protractor ./e2e/protractor.conf.js`

**Comment by james-schwartzkopf** [comment] 2018-08-16 17:01
The --inspect*** options get stripped by the CLI.

https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/utils/run-module-as-observable-fork.ts#L25-L30


But I modified those lines, first to ignore --inspect=0, then to just explicitly add --inspect-brk, and neither one worked, so something else seems to be going on here.  I even tried adding NODE_OPTIONS: '--inspect--brk=0' to the env forkOptions.


In the mean time you can use this to manually launch protractor in debug mode:
NODE_OPTIONS=--inspect-brk node_modules/.bin/protractor e2e/protractor.conf.js --baseUrl=http://localhost:4200/


You will have to run ng serve separately

**Comment by pepebbs** [comment] 2019-04-04 13:01
> The following did the trick for me:
> 
> `node --inspect-brk ./node_modules/protractor/bin/protractor ./e2e/protractor.conf.js`

This one is the only solution that worked for me! Thanks!

**Comment by ermarkar** [comment] 2019-08-17 12:14
> After some experimentation I managed to get this to work, using the following (disgusting) command:
> 
> `node --inspect-brk ./node_modules/\@angular/cli/bin/ng e2e ./protractor.conf.js`
> 
> I ran this in the root of my Angular 6 application, after which my terminal spat this out:
> 
> ![image](https://user-images.githubusercontent.com/12142999/40984918-dcfae3f8-68da-11e8-914e-d540c05d80ff.png)
> 
> And nothing appeared to happen... until I opened a chrome tab on: `chrome://inspect/#devices`:
> 
> ![image](https://user-images.githubusercontent.com/12142999/40984970-fab24986-68da-11e8-8d5b-4f08a8e2de30.png)
> 
> Clicking inspect above opens an instance of DevTools and immediately breaks the code at the top of the `ng` module. Hit continue in your debugger to run your e2e tests, and hit any `debugger` statements in your code!
> 
> Happy e2e-ing :)

Hi, I am little confused, this command need to hit along with ng test?

**Comment by wutzebaer** [comment] 2020-02-06 07:45
for me it was
`node --inspect-brk ./node_modules/\@angular/cli/bin/ng e2e`

or when starting my own instance
`node --inspect-brk ./node_modules/\@angular/cli/bin/ng e2e --dev-server-target`

**Comment by codertube** [comment] 2020-09-05 06:21
> node --inspect-brk

how can i use the ng e2e command with 'options' like below ?

`"e2e-debug": "node --inspect-brk .\\node_modules\\@angular\\cli\\bin\\ng e2e -c=integration --suite e2e --webdriverUpdate=false .\\e2e\\protractor.conf.js"`

I get 

> Unknown option: '.\e2e\protractor.conf.js'

 error and test doesn't resume after hitting first line of ng.

if I remove .\\e2e\\protractor.conf.js from above command, test resumes after hitting first line of ng, but doesn't stop at any place where debugger is added in spec file.

**Comment by alan-agius4** [comment] 2021-05-12 07:12
Duplicate of #16683

**Closed by alan-agius4** 2021-05-12 07:12 UTC
Labels: comp: devkit/build-angular, devkit/build-angular: e2e, triage #1
