### ISSUE TITLE
Any way to generate components etc. without being under the /app dir?

### ISSUE THREAD

**Issue by getabetterpic** [angular/angular-cli#9240] opened 2018-01-17 00:13 UTC
### Versions
```
Angular CLI: 1.6.1
Node: 6.11.2
OS: darwin x64
Angular: 4.3.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, tsc-wrapped
... upgrade

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
typescript: 2.5.2
webpack-dev-server: 2.7.1
webpack: 3.5.6
```

### Repro steps
* `ng g component components/test --app=ui`

### Observed behavior
```
  create app/javascript/ui/app/components/test/test.component.html (23 bytes)
  create app/javascript/ui/app/components/test/test.component.spec.ts (614 bytes)
  create app/javascript/ui/app/components/test/test.component.ts (236 bytes)
  update app/javascript/ui/ui.module.ts (721 bytes)
```

### Desired behavior

Would like to be able to have the files generated under `app/javascript/ui/components/test/test.component.ts` without the `app` portion of the path.

### Mention any other details that might be useful

We have two main applications that both consume this UI 'module' for lack of a better term. The UI module itself isn't a standalone application so it doesn't make sense to have its components/services/etc namespaced under an `app` folder. I'd be happy to put in a PR for a flag in the `.angular-cli.json` to handle this if that would be the best way to solve this.

**Comment by filipesilva** [comment] 2019-10-08 16:46
I think this is a duplicate of https://github.com/angular/angular-cli/issues/9370.

**Closed by filipesilva** 2019-10-08 16:46 UTC
Labels: comp: schematics/angular, freq2: medium, severity2: inconvenient, type: bug/fix
