### ISSUE TITLE
Wrong order of style-tags in head-tag in a multi-app repo.

### ISSUE THREAD

**Issue by infacto** [angular/angular-cli#19058] opened 2020-10-09 15:28 UTC
# 🐞 bug report

It's a blocker. Please handle with higher priority.

### Affected Package
I think it's about the compiler or any other related package which handles the style-tag order.

### Description

I have to Angular project. A default build and a multi-project one.
Both has the same setup. In this case it uses Ionic. But this does not matter. I use the Angular CLI for builds.
The `angular.json` is the same. Execpt of the path of course. (And some missing e2e and unit test. Nothing related.)

Both repos works great. But on runtime, I found some weird issues. The order of style-tags are different in html-head.
The order of the multi-app one is not correct. Please read on ...

## 🔬 Minimal Reproduction

A Stackblitz example is not possible in this case. Please download the zip repos. (click on the link in the header of the table.)

**Style-Tags**
The following is a table with the order of all style-tags and a short code snippet inside. The style-tags itself have no id. So, only the code snippet can identify it. (remeber: click on the header link to download the related repo.)

| [Working Demo](https://github.com/ionic-team/ionic-framework/files/5345465/issue-demo-2.zip)<br/><small>(Click to download)</small>                                 | [Problem Demo](https://github.com/ionic-team/ionic-framework/files/5339318/issue-demo.zip)<br/><small>(Click to download)</small>                                 |
| -------------------------------------------- | -------------------------------------------- |
| **1** (data-styles) `ion-select-popover` ... | **1** (data-styles) `ion-select-popover` ... |
| **2** `html.plt-mobile ion-app` ...          | **7** `:root { --ion-color-primary` ...      |
| **3** `ion-header` ...                       | **8** `// App Global CSS` ... `html.ios` ... |
| **4** `ion-list` ...                         | **2** `html.plt-mobile ion-app` ...          |
| **5** `ion-item-group` ...                   | **3** `ion-header` ...                       |
| **6** `.sc-ion-buttons-md-h` ...             | **6** `.sc-ion-buttons-md-h` ...             |
| **7** `:root { --ion-color-primary` ...      | **4** `ion-list` ...                         |
| **8** `// App Global CSS` ... `html.ios` ... | **5** `ion-item-group` ...                   |

(In the working demo, you may see other versions of the dependency. Sorry for that. But it does not matter. You can update it if you want. It will not change / fix the problem.)

## 🔥 Exception or Error
You can see that the number `8` is loaded before number `4`. The order is wrong. How to ensure the correct order? The setup is similar. I don't see any related problem. The official Angular multi-app repo does not work. It should have the same order as the working demo.

## 🌍  Your Environment

**Angular Version (Problem Repo / Multi-App):**
<pre><code>
Angular CLI: 10.1.6
Node: 10.22.0
OS: win32 x64

Angular: 10.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.6
@angular-devkit/build-angular   0.1001.6
@angular-devkit/core            10.1.6
@angular-devkit/schematics      10.1.6
@angular/cli                    10.1.6
@schematics/angular             10.1.6
@schematics/update              0.1001.6
rxjs                            6.6.3
typescript                      3.9.7
</code></pre>

**Angular Version (Working Repo / Single-App):**

<pre><code>
Angular CLI: 10.1.6
Node: 10.22.0
OS: win32 x64

Angular: 10.1.5
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.6
@angular-devkit/build-angular   0.1001.6
@angular-devkit/core            10.1.6
@angular-devkit/schematics      10.1.6
@angular/cli                    10.1.6
@schematics/angular             10.1.6
@schematics/update              0.1001.6
rxjs                            6.6.3
typescript                      3.9.7
</code></pre>

(The same; Versions of my current repo on local machine. The zip-repo attachment may differ. Proof that it is irrelevant.)

**Anything else relevant?**
I use the latest Chrome and Chromium browser with dev-tools. You can check the style-tags in head-tag. The order is different. I cannot find the problem. I guess a bug in Angular...

Please also see: https://github.com/ionic-team/ionic-framework/issues/22266
Here you can see a use case of the problem. ...
In the demo projects you can see that `ion-no-padding` should work. But because of the wrong order, this style is not dominant anymore. It will work with the important-flag. But this is not the solution. The question is, why is the multi-app repo not working?

**Comment by petebacondarwin** [comment] 2020-10-13 06:56
I've transferred this issue to the CLI project, since I believe that CLI is responsible for adding these styles...

**Comment by alan-agius4** [comment] 2020-10-13 11:07
Hi @infacto, 

The upcoming version 11 provides several improvements to source maps and the debugging experience (including the above mentioned issue). For more information, please see: #18377

With regards to the CSS ordering, can you try to set `"extractCss": true` under build option and see if the problem persists with this setting? Alternative you can try to update to version 11, which extractCss is now done by default.

**Comment by infacto** [comment] 2020-10-13 12:29
Hi @alan-agius4 ,
Thank you for your reponse. Yes, "extractCss" works because the "link" tag (stylesheet) is declared a little further below in the `head` tag. I tought I already tried this option. But anyway, thank for this workaround. But this is maybe just a coincidence. I mean the position of the style-link-tag. Who ensures the position? I think Angular should always place this styles at the bottom in head-tag. ... I'm not sure if this is already done. I need more tests. But I guess this works indeed, because it's already assigned in index.html. But on runtime, I see some style-tags after the link-tag. Maybe from components. ...

How to set `extractCss` for non-production builds in angular.json? I used the argument in command: `ng build --extractCss=true`. I the that this option is set for `production`, but where is the place for dev mode in this json? I already tried some stuff and searched the web. But nothing helped.
This should work with dev build, prod build and serve. But the `extractCss` flag does not work in serve. So the development is pretty slow without live reload.

How to use Angular 11? It's not yet published on npm. I know that I can refer urls as dependency in package.json. But how does this exactly work for Angular?

Anyway, I wonder why the order is different between single and multiple apps with the same configuration. The `extractCss` does not work in `serve`. I would still treat this is as bug. Angular should ensure that the styles from the json are appended at the end of the head tag. The other styles should be inserted before the global styles. ... I'm not entirely satisfied with this workaround / solution. ...

**Comment by alan-agius4** [comment] 2020-10-13 13:19
Hi, 

Because `extractCss` is not a `dev-server` option, but rather a `build` option it needs to be set in the `build` options in `angular.json` even when using `ng serve`. This is because most build configuration for `ng serve` is provided via the configured `build` options in `angular.json`.

The style tags in question are actually created by Webpack's style loader https://webpack.js.org/loaders/style-loader/, and the injection order is not something that we can control AFAIK, that being said, since this issue is no longer replicated when using the non-deprecated behaviour I think we shouldn't investigate this any further.

Angular 11 is already published on NPM as a pre-release version, and you can update using `ng update @angular/cli --next`.

**Comment by infacto** [comment] 2020-10-14 06:47
Thanks for the support.
`ng update @angular/cli --next` didn't work. It claims that the package is already up to date.
`npm i -D @angular/cli@11.0.0-next.6` (same with all other deps) works. ... 
In this version is see that there is also a link-tag with styles.css in serve mode. I though this (extractCss) is not possible?
Anyway, it looks better now. The link-tag is not at the bottom, but after some affected files. Followed by some style-tags declared in dashboard.page.scss. Ok, I can drive this with solution. But not sure how far? 

The order of styles is important. We shouldn't not accept this wrong or random order. We probably can control that. At least the global styles from angular.json. We could could separate it. Append this styles to the body-tag. Or assign an ID to the style-tags to be able to move it. Maybe we can find out why this seems to only affects to the multi-repo. The Angular version 11 looks promising. It may fix this issue. I'm a bit sceptical. Maybe we can figure out why this only affects the multi-repo as it looks. I just don't like such things. Note, that it works now, not because it's a link-tag now. It's because it's appended later. No one ensures that this will always work. *sigh* But ok, since this link-tag with the href is selectable, I could move it down to the body if necessary on runtime. A really dirty workaround if needed. 

When is the planned release date for Angular 11? I would prefer to use a stable version for this project.
If you are absolutely sure, you can close this issue. I'm not 100% sure. I'll see it over time when complete the migration of Ionic 5 to this Angular monorepo. I will watch it and report it again if necessary. - Thanks again.

**Comment by alan-agius4** [comment] 2020-10-14 10:19
Hi @infacto, 

- >`ng update @angular/cli --next` didn't work. It claims that the package is already up to date. 

Should be addressed in: #19071

- > In this version is see that there is also a link-tag with styles.css in serve mode. I though this (extractCss) is not possible? 

extractCss is the new default, the other behaviour is deprecated and will be removed in the future. 

- Angular 11 will be released is scheduled for November 11.

Closing as the problem should no longer be replicated with the non deprecated behaviour. If the problem persists after upgrading or opting out of the deprecated behavior, please open a new issue, provide a minimal repository reproducing the problem.

**Closed by alan-agius4** 2020-10-14 10:19 UTC
