### ISSUE TITLE
Cannot destructure property

### ISSUE THREAD

**Issue by Cstrp** [angular/angular-cli#24611] opened 2023-01-25 23:12 UTC
### Command

generate

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.1.0

### Description

this errror show every run ng g c etc.

```
An unhandled exception occurred: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
```

### Minimal Reproduction

1. ng n test-project --skip-install --directory (current or ./)
2. create default folders -> mkdir {shared,modules}/{models,components...etc}
3. next step -> ng g i shared/models/testIterface
4. error

### Exception or Error

```text
description on the generated angular-cli error:


[error] TypeError: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
    at GenerateCommandModule.getSchematics (/home/hie/Documents/WeatherApp/node_modules/.pnpm/@angular+cli@15.1.2/node_modules/@angular/cli/src/commands/generate/cli.js:141:29)
    at getSchematics.next (<anonymous>)
    at GenerateCommandModule.getSchematicsToRegister (/home/hie/Documents/WeatherApp/node_modules/.pnpm/@angular+cli@15.1.2/node_modules/@angular/cli/src/commands/generate/cli.js:158:76)
    at async GenerateCommandModule.builder (/home/hie/Documents/WeatherApp/node_modules/.pnpm/@angular+cli@15.1.2/node_modules/@angular/cli/src/commands/generate/cli.js:35:55)
    at async runCommand (/home/hie/Documents/WeatherApp/node_modules/.pnpm/@angular+cli@15.1.2/node_modules/@angular/cli/src/command-builder/command-runner.js:113:5)
    at async default_1 (/home/hie/Documents/WeatherApp/node_modules/.pnpm/@angular+cli@15.1.2/node_modules/@angular/cli/lib/cli/index.js:70:16)
```
```


### Your Environment

```text
Angular CLI: 15.1.3
Node: 18.13.0
Package Manager: npm 9.4.0
OS: linux x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1501.3 (cli-only)
@angular-devkit/core         15.1.3 (cli-only)
@angular-devkit/schematics   15.1.3 (cli-only)
@schematics/angular          15.1.3 (cli-only)
```

### Anything else relevant?

linux and windows system angular-cli not work

**Comment by alan-agius4** [comment] 2023-01-26 06:10
Duplicate of https://github.com/angular/angular-cli/issues/24586 and https://github.com/angular/angular-cli/issues/24600

**Closed by alan-agius4** 2023-01-26 06:10 UTC
