### ISSUE TITLE
ng set defaults.styleExt scss corrupts environments in angular-cli.json

### ISSUE THREAD

**Issue by ernest-rhinozeros** [angular/angular-cli#4064] opened 2017-01-17 12:02 UTC
### OS?
Linux (Ubuntu 16.04.1 LTS)

### Versions.
angular-cli: 1.0.0-beta.25.5
node: 6.9.4
os: linux x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Repro steps.
```
> mkdir foo
> ng init
> ng set defaults.styleExt scss
> git diff
```

### The log given by the failure.
no failure

### Mention any other details that might be useful.
I haven't touched `angular-cli.json`, after the above mentioned command it resulted in this:

```
{
  "project": {
    "version": "1.0.0-beta.25.5",
    "name": "foo"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
  "assets",
  "favicon.ico"
],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.css"
      ],
      "scripts": [
      ],
      "environments": {
        "source": {"source":"environments/environment.ts","dev":"environments/environment.ts","prod":"environments/environment.prod.ts"},
        "dev": {"source":"environments/environment.ts","dev":"environments/environment.ts","prod":"environments/environment.prod.ts"},
        "prod": {"source":"environments/environment.ts","dev":"environments/environment.ts","prod":"environments/environment.prod.ts"}
      }
    }
  ],
  "addons": [
  ],
  "packages": [
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}
```

here is a `git diff`:
```
diff --git a/angular-cli.json b/angular-cli.json
index 5af2798..6993355 100644
--- a/angular-cli.json
+++ b/angular-cli.json
@@ -8,9 +8,9 @@
       "root": "src",
       "outDir": "dist",
       "assets": [
-        "assets",
-        "favicon.ico"
-      ],
+  "assets",
+  "favicon.ico"
+],
       "index": "index.html",
       "main": "main.ts",
       "test": "test.ts",
@@ -20,16 +20,19 @@
       "styles": [
         "styles.css"
       ],
-      "scripts": [],
+      "scripts": [
+      ],
       "environments": {
-        "source": "environments/environment.ts",
-        "dev": "environments/environment.ts",
-        "prod": "environments/environment.prod.ts"
+        "source": {"source":"environments/environment.ts","dev":"environments/environment.ts","prod":"environments/environment.prod.ts"},
+        "dev": {"source":"environments/environment.ts","dev":"environments/environment.ts","prod":"environments/environment.prod.ts"},
+        "prod": {"source":"environments/environment.ts","dev":"environments/environment.ts","prod":"environments/environment.prod.ts"}
       }
     }
   ],
-  "addons": [],
-  "packages": [],
+  "addons": [
+  ],
+  "packages": [
+  ],
   "e2e": {
     "protractor": {
       "config": "./protractor.conf.js"
@@ -41,7 +44,7 @@
     }
   },
   "defaults": {
-    "styleExt": "css",
+    "styleExt": "scss",
     "prefixInterfaces": false,
     "inline": {
       "style": false,
(END)
```

**Comment by filipesilva** [comment] 2017-01-17 12:36
Dupe of https://github.com/angular/angular-cli/issues/4044, but thank you for taking the time to report it.

**Closed by filipesilva** 2017-01-17 12:36 UTC
