### ISSUE TITLE
Components are not properly generated

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#9700] opened 2018-02-20 14:26 UTC
```bash
cd C:/Develop/rosnfo-ui/rosnfo-ui/src/app/bank-portal/open-account/features/pbu-office/
$ ng g c QuickSale
```

When I generate a component then `ts` and `scss` files are moved to another location (why then one more `app` directory is created)^

```bash
"C:\Program Files\nodejs\node.exe" C:/Develop/rosnfo-ui/rosnfo-ui/node_modules/@angular/cli\bin\ng generate component QuickSale
  create app/bank-portal/open-account/features/pbu-office/quick-sale/quick-sale.component.html (41 bytes)
  create src/app/bank-portal/open-account/features/pbu-office/quick-sale/quick-sale.component.ts (281 bytes)
  create app/bank-portal/open-account/features/pbu-office/quick-sale/quick-sale.component.scss (0 bytes)
  update src/app/bank-portal/open-account/features/pbu-office/pbu-office.module.ts (1899 bytes)
Done
```

### Versions
```
$ ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.0
Node: 8.9.1
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.2.1
@angular/cli: 1.7.0
@angular/material: 5.2.1
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.4.0
@angular-devkit/schematics: 0.4.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.6.2
webpack-bundle-analyzer: 2.10.0
webpack: 3.11.0

```

If you restart

```
"C:\Program Files\nodejs\node.exe" C:/Develop/rosnfo-ui/rosnfo-ui/node_modules/@angular/cli\bin\ng generate component QuickSale
  create src/app/bank-portal/open-account/features/pbu-office/quick-sale/quick-sale.component.html (29 bytes)
  create app/bank-portal/open-account/features/pbu-office/quick-sale/quick-sale.component.ts (281 bytes)
  create __path__/__name@dasherize@if-flat__/__name@dasherize__.component.__styleext__ (0 bytes)
Done
```

quick-sale.component.html (not set name component)
```
<p>
  <%= dasherize(name) %> works!
</p>
```

**Comment by Brocco** [comment] 2018-02-22 20:17
Duplicate of #9480

**Closed by Brocco** 2018-02-22 20:17 UTC
Labels: comp: cli/generate
