### ISSUE TITLE
Module parse failed: Unexpected token by library containing `.svg` file

### ISSUE THREAD

**Issue by marwie** [angular/angular-cli#25275] opened 2023-05-26 09:30 UTC
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello,

I'm currently facing an issue where one of the libraries we use in the project contains a `.svg` file which currently prevents angular from starting the local server or building

The error we see is:
```
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <?xml version="1.0" encoding="UTF-8"?><svg id="Ebene_3" xmlns="http://www.w3.org/
```

I havent been able to add a custom webpack config yet - any pointers would be appreciated.
Currently the angular config is using ``"builder": "@angular-devkit/build-angular:browser",``

Is there a built-in way to ignore e.g. svg from being processed? Or a way to add a file handler?

### Minimal Reproduction

- install `@needle-tools/engine` or any npm package containing a `.svg` file
- run `ng serve` in the project (see env below)

make sure to import the library in one of your files

Repo: https://github.com/luixxma/angular-needle

### Exception or Error

```text
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <?xml version="1.0" encoding="UTF-8"?><svg id="Ebene_3" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 160 187.74"><defs><style>.cls-1{fill:url(#Unbenannter_Verlauf_122);}.cls-2{fill:#f3e600;}.cls-3{fill:url(#Unbenannter_Verlauf_113);}.cls-4{fill:url(#gradient-6);}.cls-5{fill:url(#Unbenannter_Verlauf_110);}.cls-6{fill:url(#Unbenannter_Verlauf_101);}.cls-7{fill:#9c3;}.cls-8{fill:#ffe1
```

### Your Environment

```text
Angular CLI: 16.0.1
Node: 16.16.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 16.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@nguniversal/builders           16.0.2
@schematics/angular             16.0.1
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by alan-agius4** [comment] 2023-05-26 10:25
The mentioned library is importing the SVG like a ECMA module. This is Webpack specific behaviour which is not supported and not intended to work. 

```ts
import _logo from "./logo.svg"
export const logoSVG = _logo;
```

Closing as the failure is correct here and by design.

**Closed by alan-agius4** 2023-05-26 10:25 UTC

**Comment by marwie** [comment] 2023-05-26 11:13
Hello @alan-agius4 thanks for the fast reply. Do you have any information why it works in webpack 5 when running in a next.js context?

Do you have information about how to modify the webpack.config for angular-cli projects?

**Comment by marwie** [comment] 2023-05-26 11:27
Fixed by embedding the svg string instead of importing it

**Comment by alan-agius4** [comment] 2023-05-26 12:16
> Do you have any information why it may work in webpack 5 when running in a next.js context?

Probably next.js allows using Webpack specific feature. 

> How do you recommend asset files inside packages should be loaded/handled?

This is an issue with the library I suggest to file an issue with them. Inlining the SVG is a good solution.

> Do you have information about how to modify the webpack.config for angular-cli projects?

You can use 3rd party builders like [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus). Note that using custom builders or custom webpack configuration are not supported by the Angular team. The fact that currently the CLI uses Webpack by default is an implementation detail and it will change in the future.

**Comment by marwie** [comment] 2023-05-26 12:28
Yes next.js exposes the webpack config and you can modify it as you'd wish.

How would you recommend to transform code when building an Angular app or adding loader plugin? Does Angular provide an API for that which is decoupled from the bundler being used? 
From reading and searching I've came across this reply a few times and I wonder why you dont expose it and if you ever switch the bundler in a major release then people would have to adjust their projects IF they chose to make "lower-level" adjustments? Perhaps you could also add a warning when someone does this?
