### ISSUE TITLE
Installing 1.6 - schematics/@angular peer dependency warning

### ISSUE THREAD

**Issue by jtsom** [angular/angular-cli#8787] opened 2017-12-07 12:49 UTC
### Versions
```
Angular CLI: 1.6.0
Node: 8.9.2
OS: darwin x64
Angular:
```

### Repro steps

* npm install -g @angular/cli

### Observed behavior
```
npm WARN @schematics/angular@0.1.10 requires a peer of @angular-devkit/schematics@0.0.40 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/schematics@0.0.10 requires a peer of @angular-devkit/schematics@0.0.40 but none is installed. You must install peer dependencies yourself.
```

### Desired behavior

No Warnings about missing dependencies

**Comment by titocr** [comment] 2017-12-07 17:25
Came here to say basically say the same. I'm running it on node 7.6.0 and macOs 10.11.6.

**Comment by Brocco** [comment] 2017-12-07 17:28
Duplicate of #8767

**Closed by Brocco** 2017-12-07 17:28 UTC
