### ISSUE TITLE
[bug] electron16 + angular13 use ipcRenderer, get error

### ISSUE THREAD

**Issue by acklj1** [angular/angular-cli#22302] opened 2021-12-04 10:39 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

no

### Description

electron16 + angular13 use ipcRenderer, get error

![image](https://user-images.githubusercontent.com/18612941/144705985-9805d503-3d42-4249-8068-edf53796e7d8.png)

I search other issue, answer is change webpack config, but angular builder is not webpack
![image](https://user-images.githubusercontent.com/18612941/144706091-ed259d5a-fcf6-4009-8821-cb3f231c96bc.png)
builder is angular-devkit/build-angular:browser
I must use ipcRenderer, like
import { ipcRenderer } from 'electron';

but ng build is error

please help to resolve it

## 🔥 Exception or Error

<pre><code>
./node_modules/electron/index.js:1:11-24 - Error: Module not found: Error: Can't resolve 'fs' in 'D:\gitproject\das\das\node_modules\electron'

./node_modules/electron/index.js:3:13-28 - Error: Module not found: Error: Can't resolve 'path' in 'D:\gitproject\das\das\node_modules\electron'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.4
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-12-04 11:01
Duplicate of #20821

**Closed by alan-agius4** 2021-12-04 11:01 UTC
