### ISSUE TITLE
How I can use CLI for different modules (RC5)?

### ISSUE THREAD

**Issue by wis-ekubesh** [angular/angular-cli#2203] opened 2016-09-18 18:31 UTC
Hi, I can't understand a small thing.. How I can configure and use angular CLI for different modules in RC5 and later? 
For example I have a 4 modules:

1. src/module1
2. src/module2
3. src/module3
4. src/module4

and I want to generate new component for module3. How I can do it?

**Comment by monojack** [comment] 2016-09-18 21:20
use `ng g c module2/component-name` to generate a new component inside `module2` folder.
AFAIK, it will be declared inside the correct module.

**Comment by filipesilva** [comment] 2016-09-22 03:09
@Brocco can you weigh in?

**Comment by monojack** [comment] 2016-09-23 05:45
I can confirm that it's working as stated above

**Comment by Brocco** [comment] 2016-09-24 03:47
@wis-ekubesh The way the CLI injects/imports declare-ables (components/directives/pipes) into modules is folder based. When you generate the CLI will look for a single `*.module.ts` file in that directory and continue up the folder structure until it finds a matching module file. Once it finds that file it will import and declare your new component/directive/pipe in that module.

There are 2 scenarios (by design) where this will fail.

- There are multiple module files in a directory
- There are no module files found even in the application root directory

Both scenarios will error out to the console to notify you of what went wrong.

With that being said, in your example are `module1` and `module2` directories? If so, you'll be fine generating items in those directories. If not, you should really consider having each module in it's own folder to organize them.

The suggestions by @monojack are accurate for how to generate items into a given module.

I am closing this issue, but if you have further questions, please ask.

**Closed by Brocco** 2016-09-24 03:47 UTC
Labels: type: question/support
