### ISSUE TITLE
Unable to get the “apply” property of a null or undefined reference [object Error] in IE and edge

### ISSUE THREAD

**Issue by AmenallahMeftehh** [angular/angular-cli#8948] opened 2017-12-20 10:54 UTC
I found some answers that say I must uncomment the import lines in polyfills.ts I did it but it still doesn't work. The problem when I select one or some folder, then I click on the delete button, a pop up is shown with 2 buttons yes and no then when I click yes there is this error only in IE and edge like in the picture attached. 

![image](https://user-images.githubusercontent.com/18208672/34203764-8cc52cc2-e57c-11e7-91b6-67e5f5ecae72.png)

**Comment by filipesilva** [comment] 2017-12-21 14:23
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #6110. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-12-21 14:23 UTC

**Comment by AmenallahMeftehh** [comment] 2017-12-26 12:13
@filipesilva i saw it but it does not solve my problem :( 
my problem is, on edge there is not this error in the console but the delete action doesn't work.
in IE there is this error on console but now when  i'm adding   exports: [RouterModule] in app.module the error disappears in console but the delete action doesn't work.
