### ISSUE TITLE
:host-context css does not get applied while AOT build

### ISSUE THREAD

**Issue by chikakow** [angular/angular-cli#10454] opened 2018-04-24 19:14 UTC
Angular CLI: 1.7.4
Node: 8.9.0
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

* Step 1
Create a component with SCSS  :host{ color: black; }   :host-context(.some-parent .inner-parent) { color: red; }
* Step 2
Use the component in another component's html <div class=".some-parent"><div class=".inner-parent"><app-step1></app-step1></div></div>
* Step 3
Do ng serve and verify that you see color red.  But then if you do ng build --prod you see color black ignoring :host-context style which is defined later.  If you do ng build --prod --aot=false, then you will see red again 

### Observed behavior
With AOT enabled build, :host-context style css is skipped and doesn't get included.
This what we observed below is generated ng build --prod
![image](https://user-images.githubusercontent.com/3085026/39208608-7fcfb804-47d1-11e8-9cef-9836f9a8f660.png)

and this is ng serve
![image](https://user-images.githubusercontent.com/3085026/39208834-ff897850-47d1-11e8-9aa1-b19715a9cddc.png)

### Desired behavior
ng build --prod will generate the same css as ng serve.

### Mention any other details that might be useful (optional)
I reverted cli version all the way back to 1.4.9 but got the same issue.

**Comment by mattbrooks2010** [comment] 2018-06-22 16:02
Related to https://github.com/angular/angular/issues/23034

**Comment by vulpfox** [comment] 2018-11-04 14:50
Same problem in Angular 7.

**Comment by alan-agius4** [comment] 2019-02-05 11:17
Duplicate of [angular/angular#23034](https://github.com/angular/angular/issues/23034)

**Closed by alan-agius4** 2019-02-05 11:17 UTC

**Comment by SebastianPodgajny** [comment] 2019-03-04 10:44
@alan-agius4 problem is in CLI and CleanCss plugin, can you reopen here?
