### ISSUE TITLE
`scripts.bundle.js` not rebuilding when file included in `scripts` changes

### ISSUE THREAD

**Issue by DaftMonk** [angular/angular-cli#7828] opened 2017-09-25 20:58 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Versions.
@angular/cli: 1.4.3
node: 6.7.0
os: darwin x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4
### Repro steps.
`ng new scriptsTest`
`cd scriptsTest`
`echo "console.log('hello')" > ./src/update.js`

Update .angular-cli.json to include `update.js` in scripts, e.g.

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "scripts-test"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": ["update.js"],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```

Run `ng serve` and open the webpage.

You will see `hello` logged to the console.

Now edit the `src/update.js` file, change it to console.log('hello world');

Webpack will trigger a rebuild of all the other bundles, but scripts bundle will stay the same. The page will reload, and the console will log `hello` again, instead of `hello world`.

Restarting the build completely is the only way to get the change.

### Desired functionality.
We'd like to see the external script changes trigger an update to the scripts.bundle.js. We're using `scripts` to include our ng1 bundle, and our changes to that bundle are not getting built.

### Mention any other details that might be useful.
This might be related to this commit: https://github.com/angular/angular-cli/commit/e8f27f0

**Comment by MarkPieszak** [comment] 2017-10-02 17:26
Just as note for anyone effected by this, pin your `cli` version to `"@angular/cli": "1.4.2"`, and scripts will work as intended.

**Comment by PrimosK** [comment] 2017-10-16 13:53
Setting `cli` to `1.4.2` doesn't seem to help. 

Example project which demonstrates the issue can be found [there](https://github.com/PrimosK/angular-cli-issue-7828-example).

**Comment by born2net** [comment] 2017-11-21 23:46
same issue using latest ng 1.5.3
scripts files not being included :(

**Comment by alamgirqazi** [comment] 2017-11-27 04:55
I'm having the same issue. using ` "@angular/cli": "1.5.0"`

**Comment by sameer-sunny** [comment] 2017-12-09 14:23
I am facing the same problem,
With both
 
`"devDependencies": {
    "@angular/cli": "1.1.3",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }`

**AND**

`"devDependencies": {
    "@angular/cli": "1.5.5",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }`

@filipesilv can you please help me resolving this issue?

**Comment by clydin** [comment] 2018-01-05 21:44
This should be corrected in 1.6.3.  If the problem still occurs, please re-open the issue.

**Closed by clydin** 2018-01-05 21:44 UTC
Labels: priority: 1 (urgent), severity4: regression, type: bug

**Comment by khushbuyeole** [comment] 2018-03-13 07:54
I am getting "Uncaught ReferenceError: ng is not defined
    at scripts.bundle.js:1644" on console

**Comment by khushbuyeole** [comment] 2018-03-13 07:55
plz help

**Comment by jodavaga** [comment] 2018-05-07 17:14
Not working. Im using the CLI 1.7.4 and still  not including the JS files.
what is going on?? please help

**Comment by mohit632** [comment] 2018-05-16 10:56
I was facing the same issue. Apparently, I had added the scripts under test in json file.
