### ISSUE TITLE
My environment is conflicting with cli ng new- app.module.ts does not exist

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#9717] opened 2018-02-21 16:45 UTC
### Versions
CLI installed globally and not in an Angular app
```
Angular CLI: 1.7.0
Node: 8.5.0
OS: darwin x64
Angular: 
...
```

### Repro steps
* yarn global add @angular/cli@latest
* ng new my-test

### Observed behavior
```
$ ng new my-test
Error: Path "/app/app.module.ts" does not exist.
Path "/app/app.module.ts" does not exist.
```

### Desired behavior
A new app scaffolded! :)

### Mention any other details that might be useful (optional)
I know this isn't enough details to repro, but posting it to drive the conversation and start looking for the problem.

**Comment by filipesilva** [comment] 2018-02-22 21:02
This issue is a duplicate of https://github.com/angular/angular-cli/issues/8989. I asked @Brocco and this should be fixed in latest.

**Closed by filipesilva** 2018-02-22 21:02 UTC
