### ISSUE TITLE
codeCoverageExclude not working in Angular 14.2.2

### ISSUE THREAD

**Issue by jdgamble555** [angular/angular-cli#23890] opened 2022-09-10 01:30 UTC
### Command

ng test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

unsure

### Description

I believe this post - https://github.com/angular/angular-cli/issues/23403 - was closed out prematurely.

**angular.json**
```typescript
"test": {
  ...
  "options": {
    ...
    "codeCoverageExclude": ["/src/app/myfolder/**"]
   }
}
```
And the folder still gets tested.

J

### Minimal Reproduction

Test out codeCoverageExclude in the latest version of Angular (14.2.2) and you will see it does not work.

### Your Environment

```text
Windows 11, VSCode, using Angular Universal with Webpack.

@angular-devkit/architect       0.1402.2
@angular-devkit/build-angular   14.2.2
@angular-devkit/core            14.2.2
@angular-devkit/schematics      14.2.2
@angular/cli                    14.2.2
@angular/fire                   7.4.1
@nguniversal/builders           14.2.0
@nguniversal/express-engine     14.2.0
@schematics/angular             14.2.2
rxjs                            7.5.6
typescript                      4.7.2
```

**Comment by JoostK** [comment] 2022-09-10 08:12
Does using a relative path instead of an absolute path resolve the issue? I wouldn't be surprised if the absolute path specifies that only the `src` directory in the root of the filesystem is to be excluded.

**Comment by alan-agius4** [comment] 2022-09-10 08:34
As @JoostK mentioned likely this is indeed caused by the usage of the absolute path.

**Comment by jdgamble555** [comment] 2022-09-10 12:54
Wouldn't that still be a bug if it only works with the relative path?  Every example out there uses `src/something...`.  The relative path (from `angular.json` would just be `/src/app/myfolder/**` anyway.  I test that, and it still doesn't work.

J

**Comment by alan-agius4** [comment] 2022-09-12 06:03
Although we don't valid paths and in most cases they happen to work, technically files in angular.json should be relative. Unfortunately, I was not able to reproduce. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2022-09-12 06:05
Just to clear out one point that I saw in your description, ("And the folder still gets tested."). It is expected that the directory is tested but it should not be included in the code-coverage report.

**Comment by jdgamble555** [comment] 2022-09-15 02:18
It is included in the code coverage report `ng test --no-watch --code-coverage`.  I also tried: 
```
{
  "codeCoverage": true,
  "codeCoverageExclude": ["src/app/myfolder/**/*"]
}
```

Still not working...

J

**Comment by alan-agius4** [comment] 2022-09-15 05:37
@jdgamble555, please provide a runnable reproduction which can be created using the steps provided above. 

Thanks

**Comment by jdgamble555** [comment] 2022-09-15 21:06
@alan-agius4 - You can easily see it does not work.

https://github.com/jdgamble555/code-coverage

J

**Comment by alan-agius4** [comment] 2022-09-16 09:28
Hi @jdgamble555, 

I tried your reproduction and `myfolder` was excluded from the code-coverage report.

<img width="611" alt="Screenshot 2022-09-16 at 11 28 33" src="https://user-images.githubusercontent.com/17563226/190605744-ede70bf2-0d7f-4368-903e-6bb1af255e32.png">


<img width="1062" alt="Screenshot 2022-09-16 at 11 28 17" src="https://user-images.githubusercontent.com/17563226/190605735-7afb2126-c40c-44a0-8454-7fff6ffb7577.png">

**Comment by alan-agius4** [comment] 2022-09-16 13:50
@jdgamble555, as mentioned previously https://github.com/angular/angular-cli/issues/23890#issuecomment-1243259855 `codeCoverageExclude` only excludes files from code-coverage report and does not effect which tests are excluded from the run. 

The second screenshot above is the test run report which is different. The code-coverage report by default is saved in the `coverage` directory and needs to be opened manually.  

Closing as this is working as intended, but feel free to reply if you have any questions.

**Closed by alan-agius4** 2022-09-16 13:50 UTC
Labels: need: repro steps

**Comment by jdgamble555** [comment] 2022-09-16 13:52
So the `--code-coverage` flag does not run code coverage? This is where I am confused.

J

**Comment by alan-agius4** [comment] 2022-09-16 14:09
`--code-coverage` does run code coverage, but Coverage reports will not be displayed in the browser. These will be generated in the `coverage` directory. In addition to that, a summary of the coverage will also be displayed in the terminal.

**HTML coverage report**
![image](https://user-images.githubusercontent.com/17563226/190657977-a1376ef9-2c03-4148-b03c-c36b7f001aa2.png)

**Summary coverage report**
![image](https://user-images.githubusercontent.com/17563226/190658244-81aafbd5-bee0-4322-aa0a-92f7639a88bf.png)

**Comment by jdgamble555** [comment] 2022-09-16 14:18
Got it.  Well make a note for a separate feature request to hide directories from testing, not code-coverage.

Appreciate the help!

J
