### ISSUE TITLE
fileReplacements doesn't work with .html files

### ISSUE THREAD

**Issue by ms-dosx86** [angular/angular-cli#20070] opened 2021-02-17 10:47 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 I'm not sure from what version it behaves like that, but probably from 11

### Description

 I used to replace my `index.html` file during local development with `index-local.html` not to use google analytics locally. But now I see that `index.html` hasn't been replaced.

## 🔬 Minimal Reproduction

Create a new app and try to replace index.html with a new configuration. You will get an error that "src/index.html" doesn't match the validation schema.

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.2.0
Node: 12.9.1
OS: darwin x64

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.1.5

</code></pre>

**Anything else relevant?**

It looks like that now CLI doesn't allow to replace HTML files, if so, I wasn't able to find anything about it in the official docs. But I was able to fix it by using "index" and "output". Is this an official way to do that? Thanks.

**Comment by alan-agius4** [comment] 2021-02-17 11:01
Duplicate of #19390 and #19390

You should use the `index` option instead.

**Closed by alan-agius4** 2021-02-17 11:01 UTC
