### ISSUE TITLE
Support unit test selection in the `ng new` configuration

### ISSUE THREAD

**Issue by moniuch** [angular/angular-cli#25642] opened 2023-08-05 13:12 UTC
### Command

new, test

### Description

CLI should have a configuration option to specify the unit test runner.

Currently, even though the Jest support is still experimental, there is hardly any guidance on how to quickly spin up a jest-driven app. The available resources differ in that one recommends `"builder": "@angular-builders/jest:run"` and another `"builder": "@angular-devkit/build-angular:jest"`.

The latter, even though it is suggested by IDE:

![image](https://github.com/angular/angular-cli/assets/681956/ca4cce96-b163-418c-bc86-5773ac6e737a)

doesn't seem to validate against the JSON schema:

![image](https://github.com/angular/angular-cli/assets/681956/602d3591-4809-43db-a60b-3c702953634c)

unless you accept the autocomplete item which includes double `@` sign, but then it results in:

![image](https://github.com/angular/angular-cli/assets/681956/10b63334-e6a7-455b-93ec-3d8d60e41d6d)

There is of course some additional package installation and uninstallation going on, as well as ts.config massaging.
And the only way for me to have console free of warnings:

`warning: unable to locate custom jest configuration file at path "/........./jest.config.js"`

was to create an empty jest.config.js file (probably has to do with [this issue](https://github.com/just-jeb/angular-builders/issues/84)).

All in all, as you see, DX is not great, hits developer with a lot of confusion, takes a lot of manual work. Therefore having a "factory recommended" solution in place would be a great time-saver.

### Describe the solution you'd like

- add a `ng new` flag `--unit-test=karma|jest`
- add a `ng new` prompt (radio buttons) - with `(experimental)` hint for the user until the feature becomes stable
- add a schematic to convert karma to jest for the existing karma-driven projects 
- add docs obviously
- bonus: add a Stackblitz template for an angular app with jest

### Describe alternatives you've considered

need to do everything manually

**Comment by alan-agius4** [comment] 2023-08-09 06:19
Duplicate of https://github.com/angular/angular-cli/issues/22978

**Closed by alan-agius4** 2023-08-09 06:19 UTC
