### ISSUE TITLE
[17.2.1] Increase in build times for libraries

### ISSUE THREAD

**Issue by atuzovic** [angular/angular-cli#27161] opened 2024-02-24 14:42 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.1.4

### Description

We have updated our internal libraries from Angular 17.1.x to 17.2.x and have also updated CLI to the latest 17.2.1 version.

Build times have been significantly increased, rising from 2 minutes to 25 minutes for one particular library, and similar has happened with other libraries where build time has increased up to 10 times.

We have tried to update the build configuration to match the latest obtained by running "ng generate library" command but we did not get any improvements.

By reading through the release notes of both Angular and Angular CLI, we have not been able to determine if there was any kind of breaking change that would induce this kind of slowdown.

When the build is taking place, node.exe takes 100% CPU and eats about 45 GB of RAM, making the PC freeze while compilation is done. The exact behavior is happening on all our workstations.

We have tried to use Node LTS 20.11.1 as well as 21.6.2 - results were the same.

### Minimal Reproduction

It is hard to provide steps for reproduction at this point.
We are willing to run any tests and provide diagnostics, however ng build --verbose does not seem to work with libraries and we were not able to find appropriate alternative.

### Your Environment

```text
Angular CLI: 17.2.1
Node: 21.6.2 (Unsupported)
Package Manager: npm 10.4.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1702.1 (cli-only)
@angular-devkit/core         17.2.1 (cli-only)
@angular-devkit/schematics   17.2.1 (cli-only)
@schematics/angular          17.2.1 (cli-only)
```

**Comment by pathmissing** [comment] 2024-02-24 20:39
I can confirm that we have a similar issue after updating to Angular 17.2. We had to increase the available memory of our build machine significantly. With Angular 17.1, the build peaked at 1.9 GB. Since Angular 17.2, we peak at about 15.9 GB. If the machine has not enough memory, the CPU usage increases dramatically, the load average spikes at 230 for a 6C/12T machine.

**Comment by atuzovic** [comment] 2024-02-26 14:17
@clydin When we have updated Angular to 17.2.x, we have updated ng-packgr as well to 17.2.x.
By "version output" - you mean to get versions of Angular and it's tooling specified in package.json of project?

**Comment by clydin** [comment] 2024-02-26 14:29
Executing `ng version` from within the project should provide a more detailed output of Angular package versions used to build the project.

**Comment by clydin** [comment] 2024-02-26 14:33
Can you manually install an older version of `ng-packagr` (`npm i -D ng-packagr@17.1`, for instance) and try a build of the library?

**Comment by atuzovic** [comment] 2024-02-26 14:44
Angular CLI: 17.2.1
Node: 21.6.2 (Unsupported)
Package Manager: npm 10.4.0
OS: win32 x64

Angular: 17.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.1
@angular-devkit/build-angular   17.2.1
@angular-devkit/core            17.2.1
@angular-devkit/schematics      17.2.1
@angular/cdk                    17.2.1
@angular/cli                    17.2.1
@angular/google-maps            17.2.1
@angular/material               17.2.1
@schematics/angular             17.2.1
ng-packagr                      17.2.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4

**Comment by atuzovic** [comment] 2024-02-26 14:55
@clydin  Ok, so after downgrade to ng-packgr 17.1.2 build went back to normal times without high CPU usage, so issue is clearly related to it.
How do we proceed now?
Should we open new ticket on ng-packgr repo or?

**Comment by alan-agius4** [comment] 2024-03-04 08:54
Closed via https://github.com/ng-packagr/ng-packagr/pull/2799

**Closed by alan-agius4** 2024-03-04 08:54 UTC
Labels: type: bug/fix, severity4: memory/performance, devkit/build-angular:library
