### ISSUE TITLE
ng generate --module - inserts incorrect when using swedish characters

### ISSUE THREAD

**Issue by kilathaar** [angular/angular-cli#9361] opened 2018-01-24 13:01 UTC
### Versions
```
ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.5
Node: 9.4.0
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
* `ng new project`
* `cd project`
* `ng generate component hö --module=app`
* `ng generate service hö --module=app`

### Observed behavior
`cat src/app/app.module.ts`

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';


import { AppComponent } from './app.component';
import { HöComponent } from './hö/hö.compone;
import { HöService } from './hö.service'nt';


@NgModule({
  declarations: [
    AppComponent,
    HöComponent
  ],
  imports: [
    BrowserModule
  ],
  providerHöServices: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### Desired behavior
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';


import { AppComponent } from './app.component';
import { HöComponent } from './hö/hö.component';
import { HöService } from './hö.service';


@NgModule({
  declarations: [
    AppComponent,
    HöComponent
  ],
  imports: [
    BrowserModule
  ],
  provider: [HöServices],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### Mention any other details that might be useful (optional)
Possible conversion error between byte and char? Swedish characters seems to equal 2 bytes when position to insert is determined and 1 byte when actual insert occurs.

**Comment by hansl** [comment] 2018-02-01 20:37
Duplicate of #8064.

**Closed by hansl** 2018-02-01 20:37 UTC
Labels: comp: cli/generate
