### ISSUE TITLE
ng serve not recognizing changes

### ISSUE THREAD

**Issue by jloosli** [angular/angular-cli#4372] opened 2017-02-02 21:00 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Ubuntu 16.04

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.29
node: 6.9.5
os: linux x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/flex-layout: 2.0.0-beta.4
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/cli: 1.0.0-beta.29
@angular/compiler-cli: 2.4.5

### Repro steps.

Updated Angular CLI:

* Removed angular-cli globally on system and installed @angular/cli@latest globally
* removed node_modules as installled @angular/cli@latest locally to project
* Ran `ng update` and diffed everything to make sure I am up to date. Main changes were Adding in "lint" & "polyfills" section to angular-cli.json and removing polyfills from main.ts.

Tried to make changes to the project: 

* Ran `ng serve` (no errors)
* Made coding changes and saved file
* {new webpack compiling triggered} (output in log section below):
* browser console adds messages: `[WDS] App updated. Recompiling...` and `[WDS] Nothing changed.`
* If I change the file and save again, the webpack compilation changes again and I see that the componentHash is exactly the same.

### The log given by the failure.

-> % ng serve
** NG Live Development Server is running on http://localhost:4200. **
Hash: a198636f6859674a0b0a                                                               
Time: 10870ms
chunk    {0} 0.chunk.js, 0.bundle.map 589 kB {1} {2} {4} [rendered]
chunk    {1} 1.chunk.js, 1.bundle.map 5.85 kB {0} {2} {4} [rendered]
chunk    {2} 2.chunk.js, 2.bundle.map 6.3 kB {0} {1} {4} [rendered]
chunk    {3} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {7} [initial] [rendered]
chunk    {4} main.bundle.js, main.bundle.map (main) 9.04 kB {6} [initial] [rendered]
chunk    {5} styles.bundle.js, styles.bundle.map (styles) 31.7 kB {7} [initial] [rendered]
chunk    {6} vendor.bundle.js, vendor.bundle.map (vendor) 4.17 MB [initial] [rendered]
chunk    {7} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
webpack: Compiling...
Hash: a198636f6859674a0b0a                                                         
Time: 925ms
chunk    {0} 0.chunk.js, 0.bundle.map 589 kB {1} {2} {4}
chunk    {1} 1.chunk.js, 1.bundle.map 5.85 kB {0} {2} {4}
chunk    {2} 2.chunk.js, 2.bundle.map 6.3 kB {0} {1} {4}
chunk    {3} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {7} [initial]
chunk    {4} main.bundle.js, main.bundle.map (main) 9.04 kB {6} [initial]
chunk    {5} styles.bundle.js, styles.bundle.map (styles) 31.7 kB {7} [initial]
chunk    {6} vendor.bundle.js, vendor.bundle.map (vendor) 4.17 MB [initial]
chunk    {7} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]
webpack: Compiled successfully.

### Mention any other details that might be useful.

Manually refreshing the browser doesn't pick up on the code changes either (webpack isn't changing what is in memory).

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Brocco** [comment] 2017-02-02 21:02
Duplicate of #4338

**Closed by Brocco** 2017-02-02 21:02 UTC
