### ISSUE TITLE
How to add the autoprefixer to 1.0.0-beta.11-webpack.2

### ISSUE THREAD

**Issue by myAoyue** [angular/angular-cli#1725] opened 2016-08-17 15:25 UTC
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
>
**Mac OSX EI Capitan**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
>
**angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.0
os: darwin x64**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
>
As the title

4. The log given by the failure. Normally this include a stack trace and some
   more information.
>
I didn't find any configuration file about css|sass|scss|less in ng2 project.

5. Mention any other details that might be useful.
>

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by euangoddard** [comment] 2016-08-18 08:42
Isn't this a duplicate of #1512?

**Comment by wulfsberg** [comment] 2016-08-18 08:54
Not *strictly*.
Angular-CLI supports some pre-processors out of the box., and #1512 is a request to similarly support Autoprefixer/PostCSS "natively".
This seems more a question of "given that Angular-CLI doesn't do it for me automagically, how do I crack open the webpack config and add it myself".
Of course, if we get #1512, this one is a non-issue.

**Closed** 2016-08-18 09:23 UTC

**Comment by euangoddard** [comment] 2016-08-18 09:26
@wulfsberg fair enough :smile:

**Comment by wulfsberg** [comment] 2016-08-18 09:53
Given that #1522 is a "nice to have" priority, this is a question I'd like the answer to myself. I am not particularly fluent in Webpack, and it doesn't seem trivial (if at all possible?) to manipulate Angular-CLI's Webpack settings.

Being locked out of the PostCSS environment with Autoprefixer, CssNano and CssNext is close to a dealbreaker for me.

**Comment by viewstack** [comment] 2016-10-01 14:04
Why is this closed? Is there a way to use autoprefixer now with the latest angular-cli version 1.0.0-beta.16 ?
