### ISSUE TITLE
Scss @use not working in using angular 16 esbuild

### ISSUE THREAD

**Issue by mkecommercesolutions-ahmet** [angular/angular-cli#25147] opened 2023-05-05 11:11 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

hello everyone, my problem is that when using esbuild that comes with angular 16 with scss, I am facing the following problem.

[ERROR] Can't find stylesheet to import.
  ╷
1 │ @use '/src/assets/styles/abstracts' as *;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### Please provide a link to a minimal reproduction of the bug

none

### Please provide the exception or error you saw

```true
X [ERROR] Can't find stylesheet to import.
  ╷
1 │ @use "/src/assets/styles/abstracts" as *;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by alan-agius4** [comment] 2023-05-05 11:35
Duplicate of https://github.com/angular/angular-cli/issues/23698

**Closed by alan-agius4** 2023-05-05 11:35 UTC

**Comment by JeanMeche** [comment] 2023-05-05 11:38
@alan-agius4  Isn't the issue here the leading slash ?

**Comment by alan-agius4** [comment] 2023-05-05 11:47
> @alan-agius4 Isn't the issue here the leading slash ?

No, because the file will still not be able to be located from the containing stylesheet, as it is not relative. Therefore, `includePaths` needs to be supplied.

It works with Webpack because the sass-loaders adds additional paths from were to locate file which is an overhead.
