### ISSUE TITLE
This version of CLI is only compatible with Angular versions ^13.0.0 || ^13.3.0-rc.0, but Angular version 14.0.0 was found instead

### ISSUE THREAD

**Issue by glauberalmeida** [angular/angular-cli#23275] opened 2022-06-03 00:48 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build

### Description

After migrating from Angular 13 to Angular 14, it is not possible to build using angular/cli@14.0.0

This message is displayed when running ng build:

This version of CLI is only compatible with Angular versions ^13.0.0 || ^13.3.0-rc.0,
but Angular version 14.0.0 was found instead.

## 🔬 Minimal Reproduction

In an Angular 13 project perform migration to Angular 14.

ng update @angular/core@14 @angular/cli@14

After migration performed and ng s working, run the build:

ng build

Message is displayed:
This version of CLI is only compatible with Angular versions ^13.0.0 || ^13.3.0-rc.0,
but Angular version 14.0.0 was found instead.

Please visit the link below to find instructions on how to update Angular.
https://update.angular.io/

## 🌍 Your Environment

<pre><code>
Angular CLI: 14.0.0
Node: 16.10.0
Package Manager: yarn 1.19.0 
OS: linux x64

Angular: 14.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@angular/flex-layout            13.0.0-beta.38
@angular/http                   7.2.16
@schematics/angular             14.0.0
rxjs                            7.5.5
typescript                      4.7.2

</code></pre>

**Comment by alan-agius4** [comment] 2022-06-03 07:29
Can you please provide the output of `npm ls @angular-devkit/build-angular`?

**Comment by damilgra** [comment] 2022-06-03 15:08
I ran into the exact same issue. In my case, the issue is a result of using @angular-builders/custom-webpack (v 13.1.0). I got past this error by replacing the relevant "builder" settings in angular.json

**Comment by otsybulsky** [comment] 2022-06-06 08:30
I need to use @angular-builders/custom-webpack (now it is v13.1.0). @damilgra How did you solve this incompatible?

**Comment by glauberalmeida** [comment] 2022-06-06 10:37
> Can you please provide the output of `yarn ls @angular-devkit/build-angular`?

`├─┬ @angular-builders/custom-webpack@13.1.0
  │  └── @angular-devkit/build-angular@13.3.7
  └── @angular-devkit/build-angular@14.0.0`

**Comment by glauberalmeida** [comment] 2022-06-06 10:55
Everything indicates update a future module update in progress @angular-builders/custom-webpack -> https://github.com/just-jeb/angular-builders/issues/1219

**Comment by alan-agius4** [comment] 2022-06-06 10:56
Closing since this is caused by a 3rd party builder which is not supported by the Angular team.

**Closed by alan-agius4** 2022-06-06 10:56 UTC
Labels: need: more info

**Comment by glauberalmeida** [comment] 2022-06-06 13:45
For those who have module dependency and cannot remove, this solution works -> [@abadakhshan](https://github.com/abadakhshan)  https://github.com/just-jeb/angular-builders/issues/1219#issuecomment-1146736928
