### ISSUE TITLE
Variables in styleUrls not working

### ISSUE THREAD

**Issue by DzmVasileusky** [angular/angular-cli#14144] opened 2019-04-12 09:35 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] serve
```

### Description
 A clear and concise description of the problem...
Using variables in styleUrls array or setting styleUrls to an array variable isn't working.

## 🔬 Minimal Reproduction

Run <pre><code>ng serve</code></pre>

Works fine:
<pre><code>@Component({
    selector: 'some-component',
    styleUrls: ['./some-component.less'],
    templateUrl: './some-component.pug'
})
export class SomeComponent {}
</code></pre>  

Not working if styleUrls set to a variable:
<pre><code>const pathes = ['./some-component.less'];

@Component({
    selector: 'some-component',
    styleUrls: pathes,
    templateUrl: './some-component.pug'
})
export class SomeComponent {}
</code></pre>  
Gives  
<pre><code>GET http://localhost:8080/some-component.less 404 (Not Found)</code></pre>

Not working if some of style urls is a variable:
<pre><code>const path = './some-component.less';

@Component({
    selector: 'some-component',
    styleUrls: [path],
    templateUrl: './some-component.pug'
})
export class SomeComponent {}
</code></pre>  
Just don't apply styles to a component without any errors.

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.6
Node: 8.11.4
OS: darwin x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              0.5.13
@angular-devkit/schematics        0.5.13
@angular/cdk                      7.3.5
@angular/cli                      7.3.6
@angular/material                 7.3.5
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.4.0
typescript                        3.2.2
webpack                           4.29.0
</code></pre>

**Comment by alan-agius4** [comment] 2019-04-12 09:53
Hi, thanks for opening this issue, however at the moment this is not supported.

**Comment by DzmVasileusky** [comment] 2019-04-12 10:32
> Hi, thanks for opening this issue, however at the moment this is not supported.

Any explanation or workaround?

I'll explain why I need this feature.
Absolute urls won't be implemented for styleUrls as described in https://github.com/angular/angular/issues/4974
But It's really annoying to calculate and write long relative pathes to some shared rendered styles.
In my case it is <pre><code>'../../../../../less/app/auth-forms.less'</code></pre>
It's just frustrating.
So I tried to calculate pathes with __dirname from Webpack.
<pre><code>const getRelativePath = (dirname: string, context: string = ''): string => {

    return dirname.replace(context, '').split('/').reduce((path: string) => {

        return path + '../';

    }, '');

};

const root = getRelativePath(__dirname, 'src/');

@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    selector: 'some-component',
    styleUrls: [`${root}less/app/auth-forms.less`],
    templateUrl: './some-component.pug'
})
</code></pre>

**Comment by PogoniiA** [comment] 2019-04-19 13:18
Any news on how to work this around?

**Comment by deebloo** [comment] 2019-04-21 16:22
@DzmVasileusky this is because anything in an angular decorator is compiled at build time not at runtime. There is no current way to accomplish this.

**Comment by DzmVasileusky** [comment] 2019-04-22 06:09
> @DzmVasileusky this is because anything in an angular decorator is compiled at build time not at runtime. There is no current way to accomplish this.

Why not tying to resolve variables on compilation? `__dirname` is Webpack variable accessible while building I guess

**Comment by PogoniiA** [comment] 2019-04-23 08:10
@DzmVasileusky I might have a solution. 

`@Component({
  selector: 'app-example',
  templateUrl: './header.component.html',
  styles: [require('./example.component.scss'), require('./example.component.'+ environment.variable +'.scss')]
})`

I am still testing it, but seems that it works.

**Comment by DzmVasileusky** [comment] 2019-04-26 16:03
@PogoniiA 
`styleUrls` are compiled with tree-shaking unlike `styles`.
I mean it won't create duplicates of same file styles listed in multiple components

**Comment by alan-agius4** [comment] 2020-12-01 12:44
Duplicate of https://github.com/angular/angular-cli/issues/9237

**Closed by alan-agius4** 2020-12-01 12:44 UTC
Labels: comp: ngtools/webpack, type: feature
