### ISSUE TITLE
Static files not being served when running app with 'ng serve'

### ISSUE THREAD

**Issue by TylerJBrown192** [angular/angular-cli#6329] opened 2017-05-15 22:49 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
$ ng --version
@angular/cli: 1.0.1
node: 6.9.1
os: win32 x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0

### Repro steps.
1. Add a .txt or .json file anywhere in the project
2. Add another in /src/assets/
3. Run `ng serve` from the command line in the Angular application
4. Open up the dev console and look for the files in the Sources tab OR set up a service to make a HTTP request to the file path you expect the static file to be at
5. A 404 will occur

### The log given by the failure.
N/A

### Desired functionality.
Would like to be able to access static files within the Angular application.

### Mention any other details that might be useful.
When building out an Angular v2 application (when Angular CLI was still in beta release) I was able to serve static text files inside of my /app directory and get them with Http.get('app/example-dir/test-file.json') from @angular/http

**Comment by 9034725985** [comment] 2017-05-15 23:53
have you tried --no-aot? 

I have a similar bug. 

I think it is related to #4806 

here is my commit. I deploy to firebase and I have to do --no-aot to get the desired result 
https://github.com/betternode/fakenews/commit/7cb097ac2db348e924947886412cf061a2f1bc4f 

I was hoping `<img src="assets/1232015064656.jpg" alt="jesus">` would work with `--aot true` I think this is a bug somewhere

**Comment by sumitarora** [comment] 2017-05-16 01:30
Duplicate of https://github.com/angular/angular-cli/issues/6158

**Closed by sumitarora** 2017-05-16 01:30 UTC
