### ISSUE TITLE
Dots in Generated Names are Ignored

### ISSUE THREAD

**Issue by gdboling** [angular/angular-cli#1444] opened 2016-07-25 18:14 UTC
Mac OSX (El Capitan)

angular-cli: 1.0.0-beta.10
node: 6.2.2
os: darwin x64

App created with ng

When executing the following: `ng g component brand.list` I would expect to end up with `brand.list.component.ts` and related files. However, it ignores everything after the first `.` and I just get `brand.component.ts` and related files named the same..

**Comment by Brocco** [comment] 2017-01-09 02:02
Thanks for taking the time to create the issue. This is by design, the CLI follows the angular style guide (can be found at [angular.io](https://angular.io/)) in which dashes are the delimiters for "words" and dots precede the file extension and the type of file ("component", "directive", "service").

For that reason I am closing this issue as this is operating as intended.

**Closed by Brocco** 2017-01-09 02:02 UTC
Labels: command: generate, type: bug
