### ISSUE TITLE
vendor.********.bundle.js size is too large in production

### ISSUE THREAD

**Issue by AungMyoKyaw** [angular/angular-cli#4059] opened 2017-01-17 04:20 UTC
### OS?
> Mac OSX (Yosemite)

### Versions.
> 1.0.0-beta.24

### My App Repo
> https://github.com/AungMyoKyaw/NightlifeCoordinationApp

>ng build --prod --aot
vendor.**.bundle.js size is still too large.
angular-cli compress this file for production but it does not remove comment.
is there options for this ?
please

**Comment by grizzm0** [comment] 2017-01-17 10:09
No there is currently no option to remove comments. This has been up for discussion but has to run through the legal team before being implemented.

I did a test where I removed comments from the *.js files. It only saved 1-2kb anyhow.

**Comment by deebloo** [comment] 2017-01-17 12:25
124k gzipped is about right for the vendor bundle that includes Core, Router, Forms, and Http modules.  If this issue is about the overall size of the Angular project I believe it is something the core team is working on.

**Comment by filipesilva** [comment] 2017-01-17 12:29
Also core-js and zone.js. Those two are part of the main bundle currently.

**Comment by filipesilva** [comment] 2017-01-17 12:29
Closed as answered.

**Closed by filipesilva** 2017-01-17 12:29 UTC

**Comment by rxjs-space** [comment] 2017-01-19 10:10
@deebloo , I got gzipped size similar to 124k for a fresh angular-cli generated app. But from [angular.io aot section](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html), they have [a chart](https://angular.io/resources/images/cookbooks/aot-compiler/toh6-bundle.png) stating total bundle size 269k(not gzipped), while the fresh angular-cli gives 421k(not gzipped) for vendor.bundle with `ng build --prod --aot --sm`, as in [this chart](https://rxjs-space.github.io/files/vendor.source-map-analysis.html). Any idea why 50% more bigger?

**Comment by deebloo** [comment] 2017-01-19 13:18
@rxjs-space have not read the article. does it include zone.js and polyfills with that bundle? also a freshly genrated cli app includes more then just core.

**Comment by rxjs-space** [comment] 2017-01-19 13:35
@deebloo , no, zone.js and polyfills are not included in the smaller bundle. If we only compare the package '@angular/core', the difference is still significant, that is 57k vs 135k. You may find more details through the chart links in my last comment.

**Comment by deebloo** [comment] 2017-01-19 14:26
Here is a screenshot of a hello world with no polyfills (other then zone.js and reflect), and it is much closer to 57k

![screen shot 2017-01-19 at 9 23 26 am](https://cloud.githubusercontent.com/assets/6563621/22110266/175b0002-de29-11e6-9973-21e4e805c9e7.png)

**Comment by deebloo** [comment] 2017-01-19 14:29
@rxjs-space would be happy to share the app code for this hello world, but should move to a different platform since this issue is closed

**Comment by rxjs-space** [comment] 2017-01-20 00:35
@deebloo , It's amazing that you get a vendor bundle at 313k(unzipped) or 71k(gzipped). I'd be grateful to have the app code. Please advise how you would like to share it.

**Comment by deebloo** [comment] 2017-01-20 01:10
I'll share when I am back  at a computer. This is just for hello world so as you add the router, http, etc it will grow

**Comment by deebloo** [comment] 2017-01-20 13:10
I'll share when I am back  at a computer. This is just for hello world so as you add the router, http, etc it will grow

**Comment by deebloo** [comment] 2017-01-20 14:30
```TS
// app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

```TS
// app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <h1>Hello World</h1>
  `
})
export class AppComponent { }
```

```ts
// polyfills.ts
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
```

**Comment by rxjs-space** [comment] 2017-01-20 15:13
@deebloo , thanks for the code. With your code, I got similar result as yours -- vendor.bundle size 308k unzipped and 70k gzipped. That is quite good. [Here's the breakdown](https://rxjs-space.github.io/files/vendor.bundle.js%20-%20hello%20world%20without%20polyfills.html). But with source-map-explorer, for @angular/core, the result is still 135k, where in angular [doc's aot section](https://angular.io/resources/images/cookbooks/aot-compiler/toh6-bundle.png), it is 57k. Maybe the size diff is caused by different bundle system, angular doc used rollup. I have not used rollup and will try it out soon.

**Comment by rxjs-space** [comment] 2017-01-20 15:48
With John Papa's [toh repo](https://github.com/johnpapa/angular2-tour-of-heroes), I can have a build.js  with @angular/core at 72k for a toh app ([here's the detail](https://rxjs-space.github.io/files/whole.toh.build.js%20-%20Source%20Map%20Explorer.html)), while angular-cli gives a 135k @angular/core for bare hello world. I think we may need to start a new issue for this.

**Comment by itsnotvalid** [comment] 2017-01-25 05:00
I have noticed that a small app I built would get me 7xxk of main.bundle using beta 26 with AOT enabled. Seems quite huge to me.

**Comment by orgertot** [comment] 2017-02-02 10:33
@itsnotvalid : same issue.. 
Its basically a new project created with the cli. I imported just the angular-jwt. But this would not explain the 500kb more.

The question is: I have many entries in my polyfills.ts. Do I need that many and do they have that high impact on the size?

My discoveries:

1. Removing blanks and line breaks and comments in the vendor.***.bundle.js will save **~40kb** (729922 bytes to 687178 bytes) with --prod and --aot

**Comment by SquadraCorse** [comment] 2017-02-09 18:48
@orgertot what is your main.js size running `ng serve`?

**Comment by noyancur** [comment] 2017-10-22 09:51
are there any solution with new updates without `--prod`? It gives me 3.50MB vendor.bundle.js, it is still so big

**Comment by reco** [comment] 2017-10-25 15:50
i agree this is a disaster ;(

**Comment by grizzm0** [comment] 2017-10-27 07:52
Why do you need a small bundle without --prod? The reason the dev bundle is large is mainly because of sourcemaps which can be disabled with --no-sourcemap. Then there's alot of minifying etc that doesn't get executed in a dev build aswell.

**Comment by George35mk** [comment] 2017-11-16 11:59
my vendor.bundle.js is 16.3 MB What i should Do ??

**Comment by maapteh** [comment] 2017-11-16 14:25
angular 5 and their cli create much smaller files, although in my case it took more time to build but the size was really small (even no vendor created anymore).

**Comment by pacurtin** [comment] 2017-12-11 04:27
Try this out:

` ng build -prod -aot --buildOptimizer`

**Comment by arunprasathv** [comment] 2018-02-28 16:45
My vendor bundle.js is 3.45 MB. How can i reduce it to keep under 2 MB. 

I've used   -  ng build -prod -aot --buildOptimizer

 👍 1

**Comment by clydin** [comment] 2018-02-28 17:34
Just a quick note: `ng build --prod` is equivalent to `ng build --prod --aot --buildOptimizer`
Also, `ng build --prod` does not generate a vendor bundle by default.

**Comment by dssagar93** [comment] 2018-11-15 11:29
Any luck in 2018 guys ? I am getting vector bundle of 3MB even after ng build --prod --aot --buildOptimizer (seems to be similar to ng build --prod). My site is too slow !

**Comment by pacurtin** [comment] 2018-11-16 00:46
@dssagar93 If your site is slow in production try something like https://www.webpagetest.org/ and make sure your server has gzip enabled.

With gzip enabled my main.js went from 5.5mb to 1.4mb

I'm also going to try splitting my app into sub modules as detailed here: https://malcoded.com/posts/angular-fundamentals-modules

That way users will lazy-load some parts of my app and won't have such a big download when all they really need to see at first is a login page or a home page.

**Comment by dssagar93** [comment] 2018-11-16 05:11
I have GZIP already enabled. I don't know what is causing the issue. When I check the network tab in Chrome dev tools there is a long idle time of around 8 seconds while loading the site. I dont understand what that idle time is for !
