### ISSUE TITLE
Fresh install doesn't run karma / ng test: No captured browser

### ISSUE THREAD

**Issue by mhp-borisbojic** [angular/angular-cli#19778] opened 2021-01-13 10:42 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Worked fine with Angular v11.0.5 and below

### Description

After updating to angular 11.0.6 / 11.0.7 / 11.0.8, karma developes some weird behavior.

In a current project, karma runs all tests, but doesn't exit. What's also new is the two additional messages (which were not in the karma startup before, too):

```
13 01 2021 11:08:29.053:WARN [karma]: No captured browser, open http://localhost:9876/
13 01 2021 11:08:29.058:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9876/
13 01 2021 11:08:29.058:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
13 01 2021 11:08:29.062:INFO [launcher]: Starting browser ChromeHeadless
13 01 2021 11:08:52.166:WARN [karma]: No captured browser, open http://localhost:9876/
13 01 2021 11:08:52.440:INFO [Chrome Headless 88.0.4298.0 (Mac OS 11.0.0)]: Connected on socket TLcm9Pu1tshFFJQ0AAAA with id 93685
```

With Angular v11.0.5, there are no "No captured browser" warnings and everything runs fine.

I also tried out **a complete fresh angular project** by using `ng new xyz` ... even with this super basic project, `ng test` doesn't run:

```
13 01 2021 11:28:41.898:INFO [karma-server]: Karma v5.1.1 server started at http://localhost:9876/
13 01 2021 11:28:41.898:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
13 01 2021 11:28:41.903:INFO [launcher]: Starting browser Chrome
✔ Browser application bundle generation complete.
13 01 2021 11:28:44.985:WARN [karma]: No captured browser, open http://localhost:9876/
✔ Browser application bundle generation complete.
13 01 2021 11:29:41.909:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
13 01 2021 11:29:43.910:WARN [launcher]: Chrome was not killed in 2000 ms, sending SIGKILL.
13 01 2021 11:29:45.910:WARN [launcher]: Chrome was not killed by SIGKILL in 2000 ms, continuing.
```

## 🔬 Minimal Reproduction
node v14.15.4
npm 6.14.11
yarn 1.22.10
Simple steps to reproduce this bug.

ng new ng11test
ng test

## 🔥 Exception or Error

In a current project:

<pre><code>
13 01 2021 11:08:29.053:WARN [karma]: No captured browser, open http://localhost:9876/
13 01 2021 11:08:29.058:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9876/
13 01 2021 11:08:29.058:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
13 01 2021 11:08:29.062:INFO [launcher]: Starting browser ChromeHeadless
13 01 2021 11:08:52.166:WARN [karma]: No captured browser, open http://localhost:9876/
13 01 2021 11:08:52.440:INFO [Chrome Headless 88.0.4298.0 (Mac OS 11.0.0)]: Connected on socket TLcm9Pu1tshFFJQ0AAAA with id 93685
</code></pre>

Fresh install:

<pre><code>13 01 2021 11:28:41.898:INFO [karma-server]: Karma v5.1.1 server started at http://localhost:9876/
13 01 2021 11:28:41.898:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
13 01 2021 11:28:41.903:INFO [launcher]: Starting browser Chrome
✔ Browser application bundle generation complete.
13 01 2021 11:28:44.985:WARN [karma]: No captured browser, open http://localhost:9876/
✔ Browser application bundle generation complete.
13 01 2021 11:29:41.909:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
13 01 2021 11:29:43.910:WARN [launcher]: Chrome was not killed in 2000 ms, sending SIGKILL.
13 01 2021 11:29:45.910:WARN [launcher]: Chrome was not killed by SIGKILL in 2000 ms, continuing.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.6
Node: 14.15.4
OS: darwin x64

Angular: 11.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.6
@angular-devkit/build-angular   0.1100.6
@angular-devkit/core            11.0.6
@angular-devkit/schematics      11.0.6
@angular/cli                    11.0.6
@schematics/angular             11.0.6
@schematics/update              0.1100.6
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by alan-agius4** [comment] 2021-01-13 11:00
Should be addressed by #19736 

Same root cause of #19773 and #19735

**Closed by alan-agius4** 2021-01-13 11:00 UTC
