### ISSUE TITLE
ngc 5.X.X generates unused imports

### ISSUE THREAD

**Issue by paulsouche** [angular/angular-cli#8320] opened 2017-11-03 00:47 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/compiler-cli 5.0.0
node 8.6.0
npm 5.5.1
yarn 1.2.1
windows 10
ubuntu 17.10

### Repro steps.

Use [my repo](https://github.com/paulsouche/ngcui-8320)

### The log given by the failure.

No failure but problem with webpack later in the assets

### Desired functionality.

ngc should not generate typings imports

### Mention any other details that might be useful.

Hi,

I've noticed that since @angular/compiler 5.0.0 unused imports are generated.

Let's say I have a module 'my-module/types' exporting only interfaces and I import this module in an angular library. Previously in 4.X.X `import {whatever} from 'my-module/types'` were not generated by ngc. But now in 5.X.X, this is generated and unused. I don't think it's a typescript issue because if I run tsc compilation, it does not generate these imports.

ngc does not fail but I've issues when I import my module in webpack.

You can reproduce with [my repo](https://github.com/paulsouche/ngcui-8320)

Thanks anyway for the great job

EDIT

I have edited my repo and if we transpile like in angular@4 with `annotationAs` flags, imports are not generated. Hope it helps...

**Comment by alan-agius4** [comment] 2019-01-04 12:35
Duplicate of https://github.com/angular/angular/issues/21280#issuecomment-451352901

**Closed by alan-agius4** 2019-01-04 12:35 UTC
Labels: need: investigation, priority: 1 (urgent)
