### ISSUE TITLE
There is an error in virtual-fs/host/test.d.ts in the @angular-devkit/core@0.7.5 distribution.

### ISSUE THREAD

**Issue by iwe7** [angular/angular-cli#12019] opened 2018-08-28 11:22 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

file at @angular-devkit/core/src/virtual-fs/host/test.d.ts
```ts
    protected _list(path: Path): import("../../../../../../../../../../../Users/hansl/Sources/hansl/angular-cli/packages/angular_devkit/core/src/virtual-fs/path").PathFragment[];
    $list(path: string): import("../../../../../../../../../../../Users/hansl/Sources/hansl/angular-cli/packages/angular_devkit/core/src/virtual-fs/path").PathFragment[];

```

**Comment by alan-agius4** [comment] 2018-08-28 11:37
Thanks for reporting this issue. However, this issue is a duplicate of #11992. Please subscribe to that issue for future updates.

**Closed by alan-agius4** 2018-08-28 11:37 UTC
