### ISSUE TITLE
Angular CLI 1.5.0 Channel closed automatically 

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [angular/angular-cli#8541] opened 2017-11-18 13:26 UTC
Hi All,

Auto compiling  we are getting the following error

> ERROR in Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at AngularCompilerPlugin._updateForkedTypeChecker (E:\Workspace\AtomIQ\atomiq_v2\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:370:34)
    at Promise.resolve.then (E:\Workspace\AtomIQ\atomiq_v2\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:208:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by micronyks** [comment] 2017-11-18 14:30
It happens frequently after some duration.  Someone please respond to this issue.

**Comment by hansl** [comment] 2017-11-21 17:55
@PrabakarKaruppasamy could you try upgrading Node and see if that fixes the problem?

Will leave this issue open for a few days but might close as answered if there's no reply.

**Comment by micronyks** [comment] 2017-11-21 18:45
Yes its related to the difference between node and angular cli version. Upgrading the node version resolved my issue.

**Comment by devoto13** [comment] 2017-11-21 19:05
This should probably be closed as duplicated of https://github.com/angular/angular-cli/issues/8331 as it does not provide any extra details. Although the issues seems to be pretty common (according to upvotes). I also experience this error quite often with CLI 1.5.2.

**Comment by filipesilva** [comment] 2017-11-24 10:40
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #8331. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-11-24 10:40 UTC
Labels: need: more info, type: bug
