### ISSUE TITLE
can't bind ng model error overlay is not showing in the ui when i have commented out the imported FormModule in a lazy loaded module

### ISSUE THREAD

**Issue by irfanit93** [angular/angular-cli#18209] opened 2020-07-10 08:32 UTC
Environment:
![image](https://user-images.githubusercontent.com/25997947/87132774-fbf08580-c2b3-11ea-9a40-a46c6d29cad0.png)
Steps to reproduce:
1. Create project with angular cli, ng new <project_name> --routing
2. Then, ng generate module home --route home --module app.module
3.Then i modified the path of the lazy loaded module from "home" to "", so that my home page is lazy loaded.
![image](https://user-images.githubusercontent.com/25997947/87133446-f5164280-c2b4-11ea-97f6-755716dd93c3.png)
4. Then ng serve
5. My home page(lazy loaded module component) has two way data binding using ng Model on input field, so i imported FormModule in my lazy loaded module. When i uncommented the import code of FormModule and the "FormModule" in the imports array, the ui reloads. It should show can't bind to ngModel error in both ui and command prompt since i am commenting out the FormModule code. But the error is showing only in command prompt. The error is not showing in the ui.

My Lazy Loaded Module code:(commented out)
![image](https://user-images.githubusercontent.com/25997947/87134955-019b9a80-c2b7-11ea-87b6-50f0689db5c6.png)

 Hope you will fix it soon.

**Comment by alan-agius4** [comment] 2020-07-10 11:25
Duplicate of https://github.com/angular/angular-cli/issues/17487

**Closed by alan-agius4** 2020-07-10 11:25 UTC
