### ISSUE TITLE
Migrating from Angular 12.2.13 to Angular 13.0.2 Unsuccessful Part 3

### ISSUE THREAD

**Issue by benedict-chng** [angular/angular-cli#22322] opened 2021-12-09 10:10 UTC
Hi,

Recently I raised 2 support-requests but before I had the chance to try out the suggestion, @alan-agius4 had already closed it. Please refer to https://github.com/angular/angular-cli/issues/22229 and https://github.com/angular/angular-cli/issues/22316.

The problem is the suggested solution in https://github.com/angular/angular-cli/issues/22229 solves the problem that occured for me during migration but when I tried to run it, the application complained about a missing CSS file (which I described in https://github.com/angular/angular-cli/issues/22316). I can read the error logs and I understand the error occured because of a missing CSS file (you don't have to tell me) but the code that tries to read it is in the Angular framework itself and not my application code.

Is this a defect in the Angular framework?

Please do not close the support request (@alan-agius4) until I have the chance to implement the suggested fix. Otherwise I will have to raise another request again.

Rgds,
Benedict

**Comment by alan-agius4** [comment] 2021-12-09 10:36
Hi @benedict-chng,

Apologies about, although ignored the issue templates and neglected to provide the required information to investigate an potentiation issue. I thought that the error was self explanatory enough (`An unhandled exception occurred: ENOENT: no such file or directory, lstat 'C:\Workspace\Nova\Avatar\node_modules\angular-archwizard\archwizard.css`.)
 
This indicated that you are referring an incorrect path likely you have some mis-configuration in your `angular.json`. 

If the problem persists, ensure you provide all of the required information when filling out the issue template including a minimal reproduction. Issues without the required information will be closed. You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2021-12-09 10:39
Note: you can still comment on closed issues.

**Comment by alan-agius4** [comment] 2021-12-09 10:40
Closing this and re-opening https://github.com/angular/angular-cli/issues/22316 since there is more context of the issue there.

**Closed by alan-agius4** 2021-12-09 10:40 UTC
Labels: need: more info
