### ISSUE TITLE
Can not install @angular/cli@1.5.4 using NPM

### ISSUE THREAD

**Issue by shenqinb** [angular/angular-cli#9328] opened 2018-01-23 09:04 UTC
can not install @1.5.4 using command: sudo npm install @1.5.4 -g

it fails with error @0.0.51 requires a peer of @0.0.28 but none was installed.

after installation, command "ng -v" doesn't work, it show below errors:
module.js:471
throw err;
^

Error: Cannot find module ''
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/usr/local/lib/node_modules//node_modules//src/tree/virtual.js:10:16)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

**Comment by filipesilva** [comment] 2018-01-25 10:37
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/9283#issuecomment-358937066. Please subscribe to that issue for future updates.

Please see https://github.com/angular/angular-cli/issues/9283#issuecomment-358937066 for a list of released versions that address this.

**Closed by filipesilva** 2018-01-25 10:37 UTC
