### ISSUE TITLE
Application fails to load in IE 11 due to registry entry "NoNavButtons"

### ISSUE THREAD

**Issue by prasadmamidi7** [angular/angular-cli#8890] opened 2017-12-15 13:53 UTC
Angular application does not load if it is configured with routes information in IE 11 when following registry entry is set to true

"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Restrictions\NoNavButtons". which was set to 1.

### Versions
```

Angular CLI: 1.6.0
Node: 8.9.2
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.6.2
webpack: 3.10.0

```

### Repro steps
*  Create a sample application with angular cli 1.6.0
* Make sure your define some route configuration
*  Build with --prod switch
*   Try to launch the application in IE 11 on win 10 

### Observed behavior
Following error is throw 
ERROR Error: Uncaught (in promise): Error: Unspecified error.
Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:83662:13)
   at PathLocationStrategy.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11897:9)
   at Location.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11473:9)
   at Router.prototype.resetUrlToCurrentUrlTree (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92718:9)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92707:17)
   at ZoneDelegate.prototype.invoke (https://localhost:5000/polyfills.bundle.js?v=OTos7wKjgnJobHuxbZDKGRsvBX2Ezqg_-coGvikK2yw:6257:13)
   at onInvoke (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:607
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Uncaught (in promise): Error: Unspecified error.
Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:83662:13)
   at PathLocationStrategy.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11897:9)
   at Location.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11473:9)
   at Router.prototype.resetUrlToCurrentUrlTree (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92718:9)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92707:17)
   at ZoneDelegate.prototype.invoke (https://localhost:5000/polyfills.bundle.js?v=OTos7wKjgnJobHuxbZDKGRsvBX2Ezqg_-coGvikK2yw:6257:13)
   at onInvoke (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:60745:17)
   at ",
      message: "Uncaught (in promise): Error: Unspecified error.
Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:83662:13)
   at PathLocationStrategy.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11897:9)
   at Location.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11473:9)
   at Router.prototype.resetUrlToCurrentUrlTree (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92718:9)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92707:17)
   at ZoneDelegate.prototype.invoke (https://localhost:5000/polyfills.bundle.js?v=OTos7wKjgnJobHuxbZDKGRsvBX2Ezqg_-coGvikK2yw:6257:13)
   at onInvoke (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:60745:17)
   at ",
      name: "Error",
      promise: { },
      rejection: { },
      stack: "Error: Uncaught (in promise): Error: Unspecified error.
Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:83662:13)
   at PathLocationStrategy.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11897:9)
   at Location.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11473:9)
   at Router.prototype.resetUrlToCurrentUrlTree (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92718:9)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92707:17)
   at ZoneDelegate.prototype.invoke (https://localhost:5000/polyfills.bundle.js?v=OTos7wKjgnJobHuxbZDKGRsvBX2Ezqg_-coGvikK2yw:6257:13)
   at onInvoke (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:60745:17)",
      task: { },
      zone: { }
   }

ERROR Error: Uncaught (in promise): Error: Unspecified error.
Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:83662:13)
   at PathLocationStrategy.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11897:9)
   at Location.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11473:9)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92663:25)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:5201:21)
   at SafeSubscriber.prototype.__tryOrSetError (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:5834:13)
   at SafeSubscriber.prototype.next (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrK
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Uncaught (in promise): Error: Unspecified error.
Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:83662:13)
   at PathLocationStrategy.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11897:9)
   at Location.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11473:9)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92663:25)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:5201:21)
   at SafeSubscriber.prototype.__tryOrSetError (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:5834:13)
   at SafeSubscriber.prototype.next (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:5774:18)
 ",
      message: "Uncaught (in promise): Error: Unspecified error.
Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:83662:13)
   at PathLocationStrategy.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11897:9)
   at Location.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11473:9)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92663:25)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:5201:21)
   at SafeSubscriber.prototype.__tryOrSetError (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:5834:13)
   at SafeSubscriber.prototype.next (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:5774:18)
 ",
      name: "Error",
      promise: { },
      rejection: { },
      stack: "Error: Uncaught (in promise): Error: Unspecified error.
Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:83662:13)
   at PathLocationStrategy.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11897:9)
   at Location.prototype.replaceState (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:11473:9)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:92663:25)
   at Anonymous function (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:5201:21)
   at SafeSubscriber.prototype.__tryOrSetError (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:5834:13)
   at SafeSubscriber.prototype.next (https://localhost:5000/vendor.bundle.js?v=M8V4riK3sAd0IS8CjnCVNoIzw3RjVKcfr_lIjQPrKb8:577",
      task: { },
      zone: { }
   }

### Desired behavior
Application shall be launched regardless of whether the mentioned registry entry is set or not.

### Mention any other details that might be useful (optional)
This has become a major blocker for our application. I would like know whether how we can resolve this.
- Some sort of switch which will be checked before pushing any url information on the  navigation buttons of the browser

In fact we do not want the user to use browser navigation buttons, as most of our application 
- all of them are targeted to the healthcare domain and it is a risk if we enable the navigation buttons. 
- all of them are targeted for IE 11 on win 10
- all of them are not like usual website app for public , but they are specifically used inside the clinic on one box.

**Comment by hansl** [comment] 2017-12-19 23:42
Duplicate of https://github.com/angular/angular/issues/21062

**Closed by hansl** 2017-12-19 23:42 UTC
