### ISSUE TITLE
ng serve url rewrite

### ISSUE THREAD

**Issue by denkomanceski** [angular/angular-cli#2412] opened 2016-09-29 08:54 UTC
Its a simple problem, I am using normal (html5) route strategy and not hashtag strategy, and when I go to a url which has some dynamic param (/archetype/display/:archetypeId) it works fine but when the server refreshes the page I get ```Cannot GET /archetype/display/openEHR-EHR-CLUSTER.infusion_details.v1.0.0```.
I think the server needs to handle this so angular will pick up and resolve the route?

In the app I have set up ```<base href="/">```, I also tried {provide: APP_BASE_HREF, useValue: '/'} in the root module still nothing..

Edit: If the route is a number /archetype/display/123 the page loads fine but of course the server cannot find the item

Edit2: It seems that it doesnt work because i have a dot (.) in the dynamic parameter. If I remove the dot it works fine. Probably the server thinks its some file extension or something maybe?
Regards

**Comment by Thiago-Medeiros** [comment] 2016-09-30 11:43
Wich server? If apache rewrite everything to index.html

**Comment by denkomanceski** [comment] 2016-09-30 11:46
I assume its a express server.. its the server that ```ng serve``` uses at background

**Comment by filipesilva** [comment] 2016-10-05 20:55
Duplicate of https://github.com/angular/angular-cli/issues/2168

**Closed by filipesilva** 2016-10-05 20:55 UTC
