### ISSUE TITLE
Lazy loaded libraries stopped working after update to 7.3

### ISSUE THREAD

**Issue by piernik** [angular/angular-cli#13793] opened 2019-02-28 11:18 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.2

### Description

I did update using `ng update --all --force=true` (had to use `--force=true` because update wanted to install `typescript@3.3.3333` which was not allowed (<3.3)).

After updating `ng serve` stopped working throwing:
```
ERROR in ./src/app/utils/lazy-loading.ts 71:49
Module parse failed: Unexpected token (71:49)
You may need an appropriate loader to handle this file type.
|             return __generator(this, function (_a) {
|                 switch (_a.label) {
>                     case 0: return [4 /*yield*/, import('zxcvbn').then(function (resp) {
|                             return resp.default;
|                         })];
```

Here is my code for lazy loading external libs:

```
export class LazyLoading {
  static async loadZXCVBN(): Promise<any> {
    const zxcvbn = await import ('zxcvbn').then(resp => {
      return resp.default;
    });
    return zxcvbn;
  }
}
```

Here is my `tsconfig` (nothing changed):
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    //    "module": "es2015",
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "@app/*": [
        "src/app/*"
      ],
      "@mocks/*": [
        "src/mocks/*"
      ],
      "@decorators/*": [
        "src/app/utils/decorators/*"
      ]
    }
  }
}
```

Can someone give me a fast solution?

## 🔥 Exception or Error
<pre><code>
ERROR in ./src/app/utils/lazy-loading.ts 71:49
Module parse failed: Unexpected token (71:49)
You may need an appropriate loader to handle this file type.
|             return __generator(this, function (_a) {
|                 switch (_a.label) {
>                     case 0: return [4 /*yield*/, import('zxcvbn').then(function (resp) {
|                             return resp.default;
|                         })];

</code></pre>

## 🌍 Your Environment
<pre><code>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.2.3
@angular-devkit/schematics        7.2.3
@angular/.cdk.MODULES             <error>
@angular/cdk                      7.3.3
@angular/cli                      7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.2.3
@schematics/update                0.13.3
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-02-28 11:25
Duplicate of https://github.com/angular/angular-cli/issues/13767

**Closed by alan-agius4** 2019-02-28 11:25 UTC
