### ISSUE TITLE
Tree shaking problem when accessing nested structure

### ISSUE THREAD

**Issue by spwin** [angular/angular-cli#20742] opened 2021-05-12 08:11 UTC
# Bug Report

### Description

There is some tree shaking problems when accessing non primitive structure on the same const which was used for conditional imports.

Short example:
**environment.ts**:
```
export const environment = {
  production: true,
  includeModule: false,
  nestedObject: {
    childProperty: 'just testing',
  },
};

```

**`TestModule` is still included**
```
  imports: [BrowserModule, environment.includeModule ? TestModule : []],
  providers: [
    { provide: new InjectionToken('Test'), useValue: environment.nestedObject },
  ],
```
**`TestModule` is NOT included**
```
  imports: [BrowserModule, environment.includeModule ? TestModule : []],
  providers: [
    {
      provide: new InjectionToken('Test'),
      useValue: {
        childProperty: environment.nestedObject.childProperty,
      },
    },
  ],
```
The only difference is that we're accessing non-primitive parameter from `environment` const. My guess is the webpack is somehow confused about the variable then and cannot be sure `environment.includeModule` is false thus ends up including module in the bundle.

## Minimal Reproduction
[Reproduction repo](https://github.com/spwin/angular-tree-shaking-issue-1)

To reproduce just run:
`yarn && npm run build && npm run analyse` to confirm the main bundle is 300+KB

Then modify `AppModule` to use only access primitive parameters on `environment` const, like in example above or in repo description.

Run `npm run build && npm run analyse` to confirm main bundle size ia 100 KB now

## Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.3
Node: 14.15.5
OS: linux x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cli                    11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.6
typescript                      4.0.7

</code></pre>

**Anything else relevant?**
The issue is happening when using any non-primitive type of the variable like object, array etc.. 

It's not the first time I occurred the weird tree shaking issues, mostly caused by side effects (https://github.com/angular/angular/issues/41145) and these things are very difficult to identify and isolate. I was wondering if there are any lint rules you would recommend to prevent tree shaking issues or some conventions so we can use them to build some rules? Similar with the environment file, are there any conventions to keep the flat primitives only structure of the object?

I'm trying to identify side effects by using experimental webpack 5 as then in `stats.json` there are side effects identified but it's pain to go through them and try to trace backwards if that causes some tree shaking issues and if some bits being included in the main bundle.

From `stats.json` I noticed the most side effects are caused because of `ExportedVariableDeclaration` in the top level of the file (enums and consts) but what's the correct way to share `enum` or `const` between multiple files and avoid optimisation bailouts? As if you move these to `*.types.ts` then the all `*.types.ts` will be marked as side effects by webpack in stats.json and there will be optimisation bailout for each of them.

**Comment by alan-agius4** [comment] 2021-05-12 09:37
Hi @spwin,

This appears to be an issue with [Terser](https://github.com/terser/terser) and not Webpack.

This can be reproduced quite easily by changing the contents of `main.ts` too

```ts
const environment = {
  includeModule: false,
  nested: {},
};

const foo = [environment.includeModule ? 2 : 0, environment.nested];
console.log(foo);
```

This will result in the following output
```ts
(window.webpackJsonp = window.webpackJsonp || []).push([ [ 1 ], {
    0: function(module, exports, __webpack_require__) {
        module.exports = __webpack_require__("zUnb");
    },
    zUnb: function(module, exports) {
        const environment = {
            includeModule: !1,
            nested: {}
        };
        console.log([ 1, environment.includeModule ? 2 : 0, environment.nested ]);
    }
}, [ [ 0, 0 ] ] ]);
```

Interestingly when accessing a property of an nested object literal that returns a primitive value DCE works.
```ts
const environment = {
  includeModule: false,
  nested: {
    child: '',
  },
};

const foo = [environment.includeModule ? 2 : 0, environment.nested.child];
console.log(foo);
```
```ts
(window.webpackJsonp = window.webpackJsonp || []).push([ [ 1 ], {
    0: function(module, exports, __webpack_require__) {
        module.exports = __webpack_require__("zUnb");
    },
    zUnb: function(module, exports) {
        console.log([ 0, "" ]);
    }
}, [ [ 0, 0 ] ] ]);
```

The same result can be achieved using the following online REPL
https://xem.github.io/terser-online/

> It's not the first time I occurred the weird tree shaking issues, mostly caused by side effects (angular/angular#41145) and these things are very difficult to identify and isolate. I was wondering if there are any lint rules you would recommend to prevent tree shaking issues or some conventions so we can use them to build some rules? Similar with the environment file, are there any conventions to keep the flat primitives only structure of the object?

The bug/limitation here, is actually caused by how the object literal is accessed, if you actually accessed if you actually accessed `{ provide: new InjectionToken('Test'), useValue: environment.nestedObject.childProperty },`, Terser would drop the unused code. As a recommendation, I suggest to use [bundle budgets](https://angular.io/guide/build#configuring-size-budgets) so that you can catch size regressions before a PR is merged.

> I'm trying to identify side effects by using experimental webpack 5 as then in stats.json there are side effects identified but it's pain to go through them and try to trace backwards if that causes some tree shaking issues and if some bits being included in the main bundle.

> From stats.json I noticed the most side effects are caused because of ExportedVariableDeclaration in the top level of the file (enums and consts) but what's the correct way to share enum or const between multiple files and avoid optimisation bailouts? As if you move these to *.types.ts then the all *.types.ts will be marked as side effects by webpack in stats.json and there will be optimisation bailout for each of them.

Are the enums shared across multiple lazy-loaded chunks?, If so ,this is expected as this will prevent the module from being merged and will cause it to have it's own scope, that said in many cases the size increase here is negligible. See https://webpack.js.org/plugins/module-concatenation-plugin/#optimization-bailouts fore more information about bailouts.

**Comment by spwin** [comment] 2021-05-13 00:17
Hey @alan-agius4, thanks for the fast reply and explanations!
Created the issue in Terser repo.

As a temp solution I'll try to:
- remove all non-primitive structures from `environment` which cannot be redefined (arrays, maps)
- reconstruct objects when we're defining providers, eg.
```
{ provide: SOME_CONFIG, useValue: {
  subConfigOne: environment.someConfig.subConfigOne,
  subCOnfigTwo: environment.someConfig.subConfigTwo,
}}
```
instead of 
```
{ provide: SOME_CONFIG, useValue: environment.someConfig }
```

> Are the enums shared across multiple lazy-loaded chunks?, If so ,this is expected as this will prevent the module from being merged and will cause it to have it's own scope, that said in many cases the size increase here is negligible.

The enums are indeed shared across multiple chunks, but shouldn't they be included in each chunk separately then increasing the total bundle size, but not increasing the main bundle? From [webpack docs](https://webpack.js.org/plugins/module-concatenation-plugin/#optimization-bailouts) it says:

Condition | Outcome
-- | --
Imported From Other Chunk | Root
Imported By Multiple Other Module Groups | Root

Where "Root means a new module group will be created", but not entirely sure does it mean the new module group will be created in the main chunk or in every chunks that uses the shared structure.


For the side effects I noticed you're using `"node_modules/tslint-no-toplevel-property-access/rules"` https://github.com/angular/angular/blob/master/tslint.json which purpose is to identify side effects https://github.com/filipesilva/check-side-effects . It looks like having that rule might prevent some side effects and tree shaking issues.

**Comment by alan-agius4** [comment] 2021-05-13 06:31
The outcome depends on two factors. 

1) is `commonChunk` enabled, which is true by default. https://angular.io/cli/build 
   When `commonChunk` enabled, the shared logic is extracted into a new common module.
   When `commonChunk` disabled, the shared logic is duplicated in the each module.
2) Is the shared item used in the main entrypoint.
    When it is, the shared logic is included only in main entrypoint.


> For the side effects I noticed you're using "node_modules/tslint-no-toplevel-property-access/rules" https://github.com/angular/angular/blob/master/tslint.json which purpose is to identify side effects https://github.com/filipesilva/check-side-effects . It looks like having that rule might prevent some side effects and tree shaking issues.

Oops, forgot about that lint rule.

**Comment by alan-agius4** [comment] 2021-05-13 06:31
The outcome depends on two factors. 

1) is `commonChunk` enabled, which is true by default. https://angular.io/cli/build 
   When `commonChunk` enabled, the shared logic is extracted into a new common module.
   When `commonChunk` disabled, the shared logic is duplicated in the each module.
2) Is the shared item used in the main entrypoint.
    When it is, the shared logic is included only in main entrypoint.


> For the side effects I noticed you're using "node_modules/tslint-no-toplevel-property-access/rules" https://github.com/angular/angular/blob/master/tslint.json which purpose is to identify side effects https://github.com/filipesilva/check-side-effects . It looks like having that rule might prevent some side effects and tree shaking issues.

Oops, forgot about that lint rule.

**Comment by alan-agius4** [comment] 2021-05-13 09:07
Closing as there is nothing actionable from the Angular tooling side here.

**Closed by alan-agius4** 2021-05-13 09:07 UTC
Labels: type: faq
