### ISSUE TITLE
[v7-rc.1] `ng test` in `createApplication=false` workspace passes with failed spec

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-cli#12456] opened 2018-10-03 15:39 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 7.0.0-rc.1
Node: 10.11.0
OS: darwin x64
Angular: 7.0.0-rc.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.9.0-rc.1
@angular-devkit/build-angular      0.9.0-rc.1
@angular-devkit/build-ng-packagr   0.9.0-rc.1
@angular-devkit/build-optimizer    0.9.0-rc.1
@angular-devkit/build-webpack      0.9.0-rc.1
@angular-devkit/core               7.0.0-rc.1
@angular-devkit/schematics         7.0.0-rc.1
@angular/cli                       7.0.0-rc.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.0-rc.1
@schematics/angular                7.0.0-rc.1
@schematics/update                 0.9.0-rc.1
ng-packagr                         4.2.0
rxjs                               6.3.3
typescript                         3.1.1
webpack                            4.19.1
```

### Repro steps

1. `ng new foobar --create-application=false`
2. `ng generate lib foobar-lib`
3. Add broken spec
```ts
  it('should create', () => {
    expect(null).toBeTruthy();
  });
```
4. `ng test --no-watch` 
5. Passed (bug)
6. `ng test --no-watch --reporters=progress`
7. Failed (correct)

### The log given by the failure

```
> ng test --no-watch
04 10 2018 00:25:46.067:INFO [karma]: Karma v3.0.0 server started at http://0.0.0.0:9876/
04 10 2018 00:25:46.070:INFO [launcher]: Launching browser Chrome with unlimited concurrency
04 10 2018 00:25:46.074:INFO [launcher]: Starting browser Chrome
04 10 2018 00:25:53.388:INFO [Chrome 69.0.3497 (Mac OS X 10.12.6)]: Connected on socket JYXPPPo6Mw0pHIIfAAAA with id 51502435
```

No failure. 

### Desired functionality

wIth `--reporters` option, it fails properly.

```
> ng test --no-watch --reporters=progress
04 10 2018 00:28:20.343:INFO [karma]: Karma v3.0.0 server started at http://0.0.0.0:9876/
04 10 2018 00:28:20.353:INFO [launcher]: Launching browser Chrome with unlimited concurrency
 10% building modules 2/3 modules 1 active ...rojects/test-lib/src sync /\.spec\.ts$/04 10 2018 00:28:20.364:INFO [launcher]: Starting browser Chrome
04 10 2018 00:28:25.694:INFO [Chrome 69.0.3497 (Mac OS X 10.12.6)]: Connected on socket qfBoO8aVAJ31QhNdAAAA with id 5910633
Chrome 69.0.3497 (Mac OS X 10.12.6) TestLibComponent should create FAILED
        Expected null to be truthy.
            at UserContext.<anonymous> (http://localhost:9876/src/lib/test-lib.component.spec.ts?:23:18)
            at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/Users/laco/Works/v7rc-test-example-lib/node_modules/zone.js/dist/zone.js?:388:1)
            at ProxyZoneSpec.push.../../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/Users/laco/Works/v7rc-test-example-lib/node_modules/zone.js/dist/zone-testing.js?:288:1)
            at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/Users/laco/Works/v7rc-test-example-lib/node_modules/zone.js/dist/zone.js?:387:1)
Chrome 69.0.3497 (Mac OS X 10.12.6): Executed 2 of 2 (1 FAILED) (0.101 secs / 0.094 secs)
TOTAL: 1 FAILED, 1 SUCCESS
```

### Mention any other details that might be useful

This behavior may relate to #12455 . `--reporters` option regression affects multiple locations.

**Comment by alan-agius4** [comment] 2018-10-03 15:50
Duplicate of #12455

**Closed by alan-agius4** 2018-10-03 15:50 UTC
