### ISSUE TITLE
templateUrl not being converted to template: __webpack_require__() when building an ngUgrade project with AOT

### ISSUE THREAD

**Issue by jamesbrobb** [angular/angular-cli#11616] opened 2018-07-20 19:58 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

npm 6.1.0

Angular CLI: 6.0.8
Node: 8.11.3
OS: darwin x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

### Repro steps

1) clone https://github.com/jamesbrobb/ng-upgrade-boilerplate
2) `npm install`
3) `ng build`
4) Search the outputted `dist/main.js` for `titleComponent.tpl.html`
5) `templateUrl` for ng1 components have been converted to `template: __webpack_require__(/*! ./titleComponent.tpl.html */ "./src/lib/app/angularJSProj/components/titleComponent/titleComponent.tpl.html"),`

6) `ng build --aot`
7)  Search the outputted `dist/main.js` for `titleComponent.tpl.html`
8) `templateUrl` for ng1 components have not been converted

### Desired functionality

When `ng build --aot` is run ng1 component `templateUrl` is converted to `template: __webpack_require__("./template/path")`

**Comment by alan-agius4** [comment] 2020-05-27 11:09
Duplicate of https://github.com/angular/angular-cli/issues/11523#issuecomment-408171645

**Closed by alan-agius4** 2020-05-27 11:09 UTC
Labels: comp: ngtools/webpack, triage #1, type: feature
