### ISSUE TITLE
Module build failed {filename} is not part of the compilation at Angular 5.0.0

### ISSUE THREAD

**Issue by kenneth-igaw** [angular/angular-cli#8296] opened 2017-11-02 09:26 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

**angular**: `"5.0.0"`
**angular/cli**: `"1.5.0-rc.8"`
**ngtools/webpack**: `"1.8.0-rc.8"`

### Repro steps.

webpack building with `AngularCompilerPlugin`

### The log given by the failure.
```
Module build failed: Error: {filename} is not part of the compilation.
```

### Mention any other details that might be useful.

Hello.

I am trying to update angular `v5.0.0` released yesterday.

But the error is occurred when i try to compile with `AngularCompilerPlugin` plugin.

The webpack throws an error as 

```
Module build failed {filename} is not part of the compilation
// ex) filename => app.main.ts
```

my tsconfig.json is as follows

```json
// tsconfig.json
{
  "version": "1.0.0",
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "removeComments": false,
    "suppressImplicitAnyIndexErrors": false,
    "strictNullChecks": false,
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "lib": [
    "dom",
    "dom.iterable",
    "es2015",
    "scripthost"
  ],
  "exclude": [
    "node_modules",
    "Content/scripts/app.aot",
    "Content/scripts/app/typings",
    "Content/scripts/app/app.main.aot.ts",
    "Content/homeworks"
  ]
}
```

And this is my `AngularCompilerPlugin` option

```js
new AngularCompilerPlugin ({
    tsConfigPath: rootDir + '/tsconfig.json',
    entryModule: contentDir + '/scripts/app/app.module#AppModule'
}),
```

Other webpack configuration is not changed.

And everything worked well until I replaced the `AotPlugin`.

So I tried to fix the plugin's code directly to fix the problem.

And there's one question in this process,

If there is no key in object, it will exist as `undefined`.

In `compiler_host.ts`, Why does `stats` compare to `null` ?

```typescript
const stats = this._files[fileName];
if (stats == null) {
    ....
}
```

I changed above code as follows for quickfix the issue

```typescript
const stats = this._files[fileName];
if (!stats) {
    ....
}
```

It's worked, However i think it is not the best practice.

**Comment by KennethanCeyer** [comment] 2017-11-02 09:36
I will put a comment with my personal account to check the progress of the issue.

**Comment by filipesilva** [comment] 2017-11-02 14:22
Hello, this issue is a duplicate of https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325. You'll find more information there about what this error means.

**Closed by filipesilva** 2017-11-02 14:22 UTC
