### ISSUE TITLE
Find available port when running ng serve instead of asking the user to specify it manually

### ISSUE THREAD

**Issue by gsans** [angular/angular-cli#18638] opened 2020-08-27 17:08 UTC
# 🚀 Feature request

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
When running `ng serve` for a second project it should use the next available port instead of throwing an error. Eg: 4201

### Describe the solution you'd like
If I run `ng serve` and port 4200 is being used I expect the command to be smart enough to try the next available port until successful. Eg: 4201, 4202, etc

### Describe alternatives you've considered
This feature is available in all these: Stencil, React and Vue.

**Comment by clydin** [comment] 2020-08-27 17:15
Duplicate of #17464

**Comment by mgechev** [comment] 2020-08-27 18:07
As we discussed offline, we don't want to automatically increment the port. First, we'd want to ask the developer with a prompt if they want to proceed. Alternatively, we may have some DX implications.

**Closed** 2020-08-28 07:52 UTC
Labels: comp: devkit/build-angular, devkit/build-angular: dev-server, type: feature
