### ISSUE TITLE
ng-xi18n error when importing angular component from node_modules

### ISSUE THREAD

**Issue by reynardmh** [angular/angular-cli#3314] opened 2016-11-29 14:36 UTC
### OS?
Mac OSX (Sierra)

### Versions.
angular-cli: 1.0.0-beta.20-4
node: 7.0.0
os: darwin x64

### Repro steps.

I created the app with CLI, copied the tsconfig.json from src to the root project so ng-xi18n can run. Here is the reproducible repo with detailed explanation of what I did. 

https://github.com/reynardmh/bugdemo-angular-i18n

basically `ng serve` works, and the app runs, but `ng-xi18n` failed because I imported `CoolComponent` from node_modules. If I don't import the `CoolComponent`, `ng-xi18n` works fine.  

This bug was originally posted in angular project, but @vicb thought this is a CLI issue and asked to reopen it in the angular-cli project.  

https://github.com/angular/angular/issues/12760

### The log given by the failure.

```
Error: Unexpected value 'CoolComponent' declared by the module 'AppModule'
    at /bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:14722:29
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:14702:56)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
    at analyzeNgModules (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:12700:16)
    at Object.analyzeAndValidateNgModules (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:12704:20)
Extraction failed
```

**Comment by vicb** [comment] 2016-11-29 17:38
The solution is that the CLI should provide a command wrapping `ng-xi18n`.

I discussed this with @hansl when an issue was created for project using sass (`ng-xi18n` would not have the right `ResourceLoader`). 
I don't know the status.

@hansl could you please give a status update ? Thanks

**Comment by vicb** [comment] 2016-11-29 18:37
@hansl told me that the new command will probably not be available before final - meaning sometime early next year.

He could help giving directions to someone willing to send a PR.

**Comment by vicb** [comment] 2016-11-29 18:42
closing as a dup of #2201

**Closed by vicb** 2016-11-29 18:42 UTC

**Comment by zhumingvictor** [comment] 2016-11-29 19:17
2201 closed as a duplicate of this and this is close as duplicate of 2201. A dead loop.

**Comment by hansl** [comment] 2016-11-29 20:04
@zhumingvictor  https://github.com/angular/angular-cli/issues/2201 isn't closed..?
