### ISSUE TITLE
Angular CLI postinstall script fails (with global flag), due to absence of ng-update-message.js  

### ISSUE THREAD

**Issue by baker-james** [angular/angular-cli#10728] opened 2018-05-08 12:30 UTC
### Versions
```
Node: v8.11.0
NPM: 5.6.0
OS: Linux Fedora 28
```

### Repro steps
```
sudo npm install -g @angular/cli
```

### Observed behavior
```
/usr/bin/ng -> /usr/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@6.0.0 postinstall /usr/lib/node_modules/@angular/cli
> node ./bin/ng-update-message.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/@angular/cli/bin/ng-update-message.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @angular/cli@6.0.0 postinstall: `node ./bin/ng-update-message.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @angular/cli@6.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-08T12_16_40_014Z-debug.log

```

### Desired behavior

The file **ng-update-message.js** is found, allowing NPM to install the Angular CLI globally

### Mention any other details that might be useful (optional)

The install is successful if installed locally, by running...

```
cd ~/Desktop
npm install @angular/cli
```

In this case, **ng-update-message.js** is present under node_modules/@angular/cli/bin/

**Comment by HockeyJustin** [comment] 2018-05-11 10:44
I am working on a new machine and have just tried a global install of angular-cli  - the first step in the tour of heroes tutorial. Same result as descibed here. 

Console (as admin)

C:\WINDOWS\system32>npm install -g @angular/cli
npm WARN engine @angular/cli@6.0.1: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine opn@5.3.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine @schematics/angular@0.6.1: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine @angular-devkit/core@0.6.1: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine @angular-devkit/architect@0.6.1: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine @schematics/update@0.6.1: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine @angular-devkit/schematics@0.6.1: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine is-wsl@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine camelcase@4.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine request@2.85.0: wanted: {"node":">= 4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine hosted-git-info@2.6.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine hosted-git-info@2.6.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine upath@1.0.5: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN optional dep failed, continuing fsevents@1.2.3
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine har-validator@5.0.3: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine typescript@2.7.2: wanted: {"node":">=4.2.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine sntp@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine hoek@4.2.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine atob@2.1.1: wanted: {"node":">= 4.5.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine atob@2.1.1: wanted: {"node":">= 4.5.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine punycode@2.1.0: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
C:\Users\myusername\AppData\Roaming\npm\ng -> C:\Users\myusername\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng

> @angular/cli@6.0.1 postinstall C:\Users\myusername\AppData\Roaming\npm\node_modules\@angular\cli
> node ./bin/ng-update-message.js

C:\Users\myusername\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng-update-message.js:7
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! @angular/cli@6.0.1 postinstall: `node ./bin/ng-update-message.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular/cli@6.0.1 postinstall script 'node ./bin/ng-update-message.js'.
npm ERR! This is most likely a problem with the @angular/cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/ng-update-message.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls @angular/cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

**Comment by HockeyJustin** [comment] 2018-05-11 11:07
I have just found this could be to do with the version of NodeJS or NPM. I've just got the latest installer from the NodeJs website and everything seems to have gone through ok.

**Comment by hansl** [comment] 2018-05-14 21:08
I tried locally with Node 8.10, 9.11 and 10.1 and it works fine (could not reproduce). I'm going to say it's a Node fluke (there are always many in the first minors) and close this. If it still happens to you please open a new issue. Thanks!

**Closed by hansl** 2018-05-14 21:08 UTC
Labels: comp: cli/update, freq3: high, severity3: broken, type: bug

**Comment by Jikaworld** [comment] 2018-05-17 15:33
I had the same error, and this is the solution worked for me:

`sudo npm install -g @angular/cli --unsafe-perm=true --allow-root`

I found it [here](https://github.com/npm/npm/issues/17268)

**Comment by BaskaraSethupathi** [comment] 2018-07-06 08:50
Hello Everyone,


Please help me out form this. i'm also getting this same problem. 



> @angular/cli@6.0.8 postinstall C:\Users\Apphub\AppData\Roaming\npm\node_modules\@angular\cli
> node ./bin/ng-update-message.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! file bash
npm ERR! path bash
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn bash
npm ERR! @angular/cli@6.0.8 postinstall: `node ./bin/ng-update-message.js`
npm ERR! spawn bash ENOENT
npm ERR!
npm ERR! Failed at the @angular/cli@6.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:


npm -v 6.1.0
node 10.6.0

**Comment by jeanlucburot** [comment] 2018-07-16 11:35
@Jikaworld You don't need `--allow-root`. This command suffices: `sudo npm install -g @angular/cli --unsafe-perm=true`

**Comment by AshMcConnell** [comment] 2018-07-31 07:55
Thanks @Jikaworld this solved a lot of problems for our docker build!
