### ISSUE TITLE
[1.4.x] service generation warning is no longer present

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#7680] opened 2017-09-13 09:56 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.1
node: 8.4.0
os: darwin x64
@angular/animations: 5.0.0-beta.3
@angular/common: 5.0.0-beta.3
@angular/compiler: 5.0.0-beta.3
@angular/core: 5.0.0-beta.3
@angular/forms: 5.0.0-beta.3
@angular/platform-browser: 5.0.0-beta.3
@angular/platform-browser-dynamic: 5.0.0-beta.3
@angular/router: 5.0.0-beta.3
@angular/cli: 1.4.1
@angular/compiler-cli: 5.0.0-beta.3
@angular/language-service: 5.0.0-beta.3
typescript: 2.4.2

### Repro steps.
```
> ng g service race
create src/app/race.service.spec.ts (368 bytes)
create src/app/race.service.ts (111 bytes)
```

The command used to emit a warning about providing the service somewhere to use it.

### Desired functionality.

The warning should still be present.

**Comment by alan-agius4** [comment] 2018-10-08 13:51
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

By default services will be injected in the `root` injector

**Closed by alan-agius4** 2018-10-08 13:51 UTC
Labels: priority: 2 (required), severity3: broken
