### ISSUE TITLE
angular-devkit/build-angular@0.803.21 Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by cojack** [angular/angular-cli#16518] opened 2019-12-31 09:42 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.803.20

### Description

 A clear and concise description of the problem...
After upgrading package up to 0.803.21 build crashed with following error message:

`An unhandled exception occurred: Call retries were exceeded`

## 🔬 Minimal Reproduction

This happen for internal project, I doesn't have any public repo to reproduce this problem.
but I also use different builder as `@angular-builders/custom-webpack:browser`

## 🔥 Exception or Error
<pre><code>

{
  "header": {
    "reportVersion": 1,
    "event": "Allocation failed - JavaScript heap out of memory",
    "trigger": "FatalError",
    "filename": "report.20191231.101121.7421.0.001.json",
    "dumpEventTime": "2019-12-31T10:11:21Z",
    "dumpEventTimeStamp": "1577783481404",
    "processId": 7421,
    "cwd": "/home/cojack/Projects/project_a//web-app",
    "commandLine": [
      "/home/cojack/.nvm/versions/node/v12.13.1/bin/node",
      "/home/cojack/Projects/project_a/web-app/node_modules/jest-worker/build/workers/processChild.js"
    ],
    "nodejsVersion": "v12.13.1",
    "glibcVersionRuntime": "2.30",
    "glibcVersionCompiler": "2.17",
    "wordSize": 64,
    "arch": "x64",
    "platform": "linux",
    "componentVersions": {
      "node": "12.13.1",
      "v8": "7.7.299.13-node.16",
      "uv": "1.33.1",
      "zlib": "1.2.11",
      "brotli": "1.0.7",
      "ares": "1.15.0",
      "modules": "72",
      "nghttp2": "1.39.2",
      "napi": "5",
      "llhttp": "1.1.4",
      "http_parser": "2.8.0",
      "openssl": "1.1.1d",
      "cldr": "35.1",
      "icu": "64.2",
      "tz": "2019c",
      "unicode": "12.1"
    },
    "release": {
      "name": "node",
      "lts": "Erbium",
      "headersUrl": "https://nodejs.org/download/release/v12.13.1/node-v12.13.1-headers.tar.gz",
      "sourceUrl": "https://nodejs.org/download/release/v12.13.1/node-v12.13.1.tar.gz"
    },
    "osName": "Linux",
    "osRelease": "5.3.0-24-generic",
    "osVersion": "#26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019",
    "osMachine": "x86_64",
    "cpus": [
      {
        "model": "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",
        "speed": 4322,
        "user": 3363000,
        "nice": 800,
        "sys": 919800,
        "idle": 64668100,
        "irq": 0
      },
      {
        "model": "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",
        "speed": 4322,
        "user": 3476900,
        "nice": 900,
        "sys": 679400,
        "idle": 64846300,
        "irq": 0
      },
      {
        "model": "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",
        "speed": 4211,
        "user": 3121400,
        "nice": 1300,
        "sys": 884700,
        "idle": 64936400,
        "irq": 0
      },
      {
        "model": "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",
        "speed": 4192,
        "user": 3641400,
        "nice": 1500,
        "sys": 709600,
        "idle": 64647300,
        "irq": 0
      },
      {
        "model": "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",
        "speed": 4211,
        "user": 3243700,
        "nice": 900,
        "sys": 711400,
        "idle": 65024000,
        "irq": 0
      },
      {
        "model": "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",
        "speed": 4322,
        "user": 3224600,
        "nice": 1000,
        "sys": 714600,
        "idle": 64983300,
        "irq": 0
      },
      {
        "model": "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",
        "speed": 4206,
        "user": 3087900,
        "nice": 1200,
        "sys": 812600,
        "idle": 65075500,
        "irq": 0
      },
      {
        "model": "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",
        "speed": 4217,
        "user": 3479700,
        "nice": 6100,
        "sys": 807000,
        "idle": 64716200,
        "irq": 0
      }
    ],
    "networkInterfaces": [
      {
        "name": "lo",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "127.0.0.1",
        "netmask": "255.0.0.0",
        "family": "IPv4"
      },
      {
        "name": "eno1",
        "internal": false,
        "mac": "fc:aa:14:9b:fe:f4",
        "address": "192.168.0.40",
        "netmask": "255.255.255.0",
        "family": "IPv4"
      },
      {
        "name": "eno1",
        "internal": false,
        "mac": "fc:aa:14:9b:fe:f4",
        "address": "192.168.0.13",
        "netmask": "255.255.255.0",
        "family": "IPv4"
      },
      {
        "name": "lo",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "::1",
        "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
        "family": "IPv6",
        "scopeid": 0
      },
      {
        "name": "eno1",
        "internal": false,
        "mac": "fc:aa:14:9b:fe:f4",
        "address": "fd01::feaa:14ff:fe9b:fef4",
        "netmask": "ffff:ffff:ffff:ffff::",
        "family": "IPv6",
        "scopeid": 0
      },
      {
        "name": "eno1",
        "internal": false,
        "mac": "fc:aa:14:9b:fe:f4",
        "address": "fe80::feaa:14ff:fe9b:fef4",
        "netmask": "ffff:ffff:ffff:ffff::",
        "family": "IPv6",
        "scopeid": 2
      }
    ],
    "host": "cojack-desktop"
  },
  "javascriptStack": {
    "message": "No stack.",
    "stack": [
      "Unavailable."
    ]
  },
  "nativeStack": [
    {
      "pc": "0x0000000000b04935",
      "symbol": "report::TriggerNodeReport(v8::Isolate*, node::Environment*, char const*, char const*, std::string const&, v8::Local<v8::String>) [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    },
    {
      "pc": "0x00000000009db9e3",
      "symbol": "node::OnFatalError(char const*, char const*) [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    },
    {
      "pc": "0x0000000000b39f1e",
      "symbol": "v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    },
    {
      "pc": "0x0000000000b3a299",
      "symbol": "v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    },
    {
      "pc": "0x0000000000ce5635",
      "symbol": " [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    },
    {
      "pc": "0x0000000000ce5cc6",
      "symbol": "v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    },
    {
      "pc": "0x0000000000cf1b5a",
      "symbol": "v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    },
    {
      "pc": "0x0000000000cf2a65",
      "symbol": "v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    },
    {
      "pc": "0x0000000000cf5478",
      "symbol": "v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    },
    {
      "pc": "0x0000000000cbbda7",
      "symbol": "v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType) [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    },
    {
      "pc": "0x0000000000ff1e0b",
      "symbol": "v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    },
    {
      "pc": "0x0000000001374fd9",
      "symbol": " [/home/cojack/.nvm/versions/node/v12.13.1/bin/node]"
    }
  ],
  "javascriptHeap": {
    "totalMemory": 2153500672,
    "totalCommittedMemory": 2149651632,
    "usedMemory": 2133716656,
    "availableMemory": 48464168,
    "memoryLimit": 2197815296,
    "heapSpaces": {
      "read_only_space": {
        "memorySize": 262144,
        "committedMemory": 32568,
        "capacity": 261872,
        "used": 32296,
        "available": 229576
      },
      "new_space": {
        "memorySize": 4194304,
        "committedMemory": 1263032,
        "capacity": 2094976,
        "used": 269984,
        "available": 1824992
      },
      "old_space": {
        "memorySize": 1992667136,
        "committedMemory": 1992332912,
        "capacity": 1978190672,
        "used": 1978190672,
        "available": 0
      },
      "code_space": {
        "memorySize": 1998848,
        "committedMemory": 1731616,
        "capacity": 1585440,
        "used": 1585440,
        "available": 0
      },
      "map_space": {
        "memorySize": 1576960,
        "committedMemory": 1490224,
        "capacity": 1038720,
        "used": 1038720,
        "available": 0
      },
      "large_object_space": {
        "memorySize": 152752128,
        "committedMemory": 152752128,
        "capacity": 152595992,
        "used": 152595992,
        "available": 0
      },
      "code_large_object_space": {
        "memorySize": 49152,
        "committedMemory": 49152,
        "capacity": 3552,
        "used": 3552,
        "available": 0
      },
      "new_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 2094976,
        "used": 0,
        "available": 2094976
      }
    }
  },
  "resourceUsage": {
    "userCpuSeconds": 124.513,
    "kernelCpuSeconds": 2.31152,
    "cpuConsumptionPercent": 198.163,
    "maxRss": 2287325184,
    "pageFaults": {
      "IORequired": 8,
      "IONotRequired": 1177927
    },
    "fsActivity": {
      "reads": 2688,
      "writes": 24
    }
  },
  "uvthreadResourceUsage": {
    "userCpuSeconds": 58.5566,
    "kernelCpuSeconds": 1.14001,
    "cpuConsumptionPercent": 93.2759,
    "fsActivity": {
      "reads": 2688,
      "writes": 24
    }
  },
  "libuv": [
  ],
  "environmentVariables": {
    "PROFILEHOME": "",
    "KDE_FULL_SESSION": "true",
    "npm_package_dependencies__okta_okta_angular": "~1.2.2",
    "npm_package_devDependencies__angular_language_service": "^8.2.11",
    "npm_package_devDependencies__types_node": "^12.11.1",
    "npm_package_devDependencies_ts_node": "~7.0.0",
    "npm_package_devDependencies_tslint": "~5.15.0",
    "npm_config_cache_lock_stale": "60000",
    "npm_config_ham_it_up": "",
    "npm_package_scripts_compodoc": "compodoc --unitTestCoverage coverage/coverage-summary.json -p tsconfig.json",
    "npm_package_dependencies__angular_animations": "~8.2.11",
    "npm_package_devDependencies__types_algoliasearch": "^3.34.5",
    "npm_config_legacy_bundling": "",
    "npm_config_sign_git_tag": "",
    "LANGUAGE": "",
    "USER": "cojack",
    "PAM_KWALLET5_LOGIN": "/run/user/1000/kwallet5.socket",
    "npm_package_devDependencies_jest": "^24.9.0",
    "npm_config_user_agent": "npm/6.13.4 node/v12.13.1 linux x64",
    "npm_config_always_auth": "",
    "XDG_SEAT": "seat0",
    "npm_config_bin_links": "true",
    "npm_config_key": "",
    "SSH_AGENT_PID": "2173",
    "XDG_SESSION_TYPE": "x11",
    "npm_package_dependencies__angular_common": "~8.2.11",
    "npm_config_allow_same_version": "",
    "npm_config_description": "true",
    "npm_config_fetch_retries": "2",
    "npm_config_heading": "npm",
    "npm_config_if_present": "",
    "npm_config_init_version": "1.0.0",
    "npm_config_user": "1000",
    "npm_node_execpath": "/home/cojack/.nvm/versions/node/v12.13.1/bin/node",
    "GREP_COLOR": "1;33",
    "AUTOFEATURE": "true autotest",
    "KONSOLE_VERSION": "190803",
    "SHLVL": "1",
    "npm_package_dependencies_rxjs": "~6.4.0",
    "npm_package_devDependencies__types_jasminewd2": "^2.0.8",
    "npm_package_devDependencies_protractor": "~5.4.0",
    "npm_config_prefer_online": "",
    "npm_config_noproxy": "",
    "HOME": "/home/cojack",
    "OLDPWD": "/home/cojack",
    "npm_config_force": "",
    "DESKTOP_SESSION": "plasma",
    "NVM_BIN": "/home/cojack/.nvm/versions/node/v12.13.1/bin",
    "npm_package_dependencies__angular_material": "~8.2.3",
    "npm_config_only": "",
    "npm_config_read_only": "",
    "LSCOLORS": "Gxfxcxdxdxegedabagacad",
    "npm_package_scripts_sonar": "sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$CI_COMMIT_REF_SLUG",
    "npm_package_engines_node": "~12",
    "npm_package_devDependencies_jasmine_core": "~3.4.0",
    "npm_config_cache_min": "10",
    "npm_config_init_license": "ISC",
    "SHELL_SESSION_ID": "95c42d9d4e304aaa9892c16b62d86c24",
    "GTK_RC_FILES": "/etc/gtk/gtkrc:/home/cojack/.gtkrc:/home/cojack/.config/gtkrc",
    "XDG_SEAT_PATH": "/org/freedesktop/DisplayManager/Seat0",
    "KDE_SESSION_VERSION": "5",
    "npm_package_devDependencies__types_jasmine": "~3.3.8",
    "npm_config_editor": "vi",
    "npm_config_rollback": "true",
    "npm_config_tag_version_prefix": "v",
    "GIT_HOSTING": "git@git.domain.com",
    "KONSOLE_DBUS_SESSION": "/Sessions/1",
    "npm_config_cache_max": "Infinity",
    "npm_config_timing": "",
    "npm_config_userconfig": "/home/cojack/.npmrc",
    "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
    "SCM_CHECK": "true",
    "npm_package_dependencies__datorama_akita": "~4.17.0",
    "npm_package_dependencies_neat_csv": "~5.1.0",
    "npm_package_devDependencies__angular_compiler_cli": "^8.2.11",
    "npm_config_engine_strict": "",
    "npm_config_init_author_name": "",
    "npm_config_init_author_url": "",
    "npm_config_preid": "",
    "npm_config_tmp": "/tmp",
    "COLORTERM": "truecolor",
    "npm_package_dependencies__angular_cdk": "~8.2.3",
    "npm_package_dependencies_algoliasearch": "~3.35.1",
    "npm_package_devDependencies_typescript": "~3.5.3",
    "npm_config_depth": "Infinity",
    "npm_config_package_lock_only": "",
    "npm_config_save_dev": "",
    "npm_config_usage": "",
    "NVM_DIR": "/home/cojack/.nvm",
    "npm_package_contributors_2_email": "rdykty@neoteric.eu",
    "npm_package_dependencies_angular2_text_mask": "~9.0.0",
    "npm_package_devDependencies_jasmine_spec_reporter": "~4.2.1",
    "npm_package_readmeFilename": "README.md",
    "npm_config_metrics_registry": "https://registry.npmjs.org/",
    "npm_config_cafile": "",
    "npm_config_otp": "",
    "npm_config_package_lock": "true",
    "npm_config_progress": "true",
    "npm_config_https_proxy": "",
    "npm_config_save_prod": "",
    "npm_package_scripts_sonar_mr": "sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$CI_COMMIT_REF_SLUG -Dsonar.branch.target=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME",
    "npm_package_dependencies__angular_core": "~8.2.11",
    "npm_package_dependencies_tslib": "~1.10.0",
    "npm_config_audit": "true",
    "npm_config_cidr": "",
    "npm_config_onload_script": "",
    "npm_config_sso_type": "oauth",
    "LOGNAME": "cojack",
    "npm_package_dependencies_hammerjs": "~2.0.8",
    "npm_package_devDependencies__compodoc_compodoc": "^1.1.11",
    "npm_config_rebuild_bundle": "true",
    "npm_config_save_bundle": "",
    "npm_config_shell": "/bin/bash",
    "WINDOWID": "0",
    "TODO": "t",
    "QT_AUTO_SCREEN_SCALE_FACTOR": "0",
    "_": "/home/cojack/.nvm/versions/node/v12.13.1/bin/npm",
    "npm_package_private": "true",
    "npm_package_dependencies__angular_platform_browser_dynamic": "~8.2.11",
    "npm_package_devDependencies__types_jest": "^24.0.19",
    "npm_package_devDependencies_sonarqube_scanner": "^2.5.0",
    "npm_config_dry_run": "",
    "npm_config_format_package_lock": "true",
    "npm_config_prefix": "/home/cojack/.nvm/versions/node/v12.13.1",
    "XDG_SESSION_CLASS": "user",
    "COLORFGBG": "15;0",
    "KONSOLE_PROFILE_NAME": "Default",
    "npm_package_scripts_lint": "ng lint",
    "npm_package_dependencies_class_transformer": "~0.2.3",
    "npm_config_scope": "",
    "npm_config_browser": "",
    "npm_config_cache_lock_wait": "10000",
    "npm_config_ignore_prepublish": "",
    "npm_config_registry": "https://registry.npmjs.org/",
    "npm_config_save_optional": "",
    "npm_config_searchopts": "",
    "npm_config_versions": "",
    "TERM": "xterm-256color",
    "XDG_SESSION_ID": "6",
    "npm_package_devDependencies__types_lodash": "^4.14.149",
    "npm_config_cache": "/home/cojack/.npm",
    "npm_config_proxy": "",
    "npm_config_send_metrics": "",
    "npm_package_scripts_start": "ng serve",
    "npm_package_dependencies__angular_compiler": "~8.2.11",
    "npm_package_devDependencies__angular_builders_jest": "^8.2.0",
    "npm_config_global_style": "",
    "npm_config_ignore_scripts": "",
    "npm_config_version": "",
    "HISTCONTROL": "ignorespace:erasedups",
    "GTK2_RC_FILES": "/etc/gtk-2.0/gtkrc:/home/cojack/.gtkrc-2.0:/home/cojack/.config/gtkrc-2.0",
    "npm_package_dependencies__datorama_akita_ng_entity_service": "~1.3.0",
    "npm_package_dependencies_xstate": "~4.6.7",
    "npm_config_local_address": "",
    "npm_config_viewer": "man",
    "npm_config_node_gyp": "/home/cojack/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
    "PATH": "/home/cojack/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/cojack/Projects/project_a/web-app/node_modules/.bin:/home/cojack/.nvm/versions/node/v12.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
    "SESSION_MANAGER": "local/cojack-desktop:@/tmp/.ICE-unix/2237,unix/cojack-desktop:/tmp/.ICE-unix/2237",
    "IRC_CLIENT": "irssi",
    "npm_package_name": "web-app",
    "npm_package_scripts_compodoc_serve": "compodoc -s",
    "npm_package_dependencies_file_saver": "~2.0.2",
    "npm_config_audit_level": "low",
    "npm_config_prefer_offline": "",
    "NODE": "/home/cojack/.nvm/versions/node/v12.13.1/bin/node",
    "XDG_SESSION_PATH": "/org/freedesktop/DisplayManager/Session1",
    "XDG_RUNTIME_DIR": "/run/user/1000",
    "XCURSOR_THEME": "breeze_cursors",
    "npm_config_color": "true",
    "npm_config_sign_git_commit": "",
    "DISPLAY": ":0",
    "npm_package_dependencies__angular_forms": "~8.2.11",
    "npm_package_dependencies_ngx_toastr": "~10.2.0",
    "npm_package_devDependencies__angular_builders_custom_webpack": "^8.2.0",
    "npm_config_fetch_retry_mintimeout": "10000",
    "npm_config_maxsockets": "50",
    "npm_config_offline": "",
    "npm_config_sso_poll_frequency": "500",
    "HISTSIZE": "5000",
    "LANG": "en_GB.UTF-8",
    "XDG_CURRENT_DESKTOP": "KDE",
    "npm_config_umask": "0002",
    "XDG_SESSION_DESKTOP": "KDE",
    "XAUTHORITY": "/tmp/xauth-1000-_0",
    "npm_package_scripts_ng": "ng",
    "npm_package_scripts_e2e": "ng e2e",
    "npm_package_scripts_license_check": "license-checker",
    "npm_package_dependencies_iterare": "~1.2.0",
    "npm_package_gitHead": "af20b8250d9686c5b9eac4283e3071c29d153508",
    "npm_config_fund": "true",
    "npm_config_fetch_retry_maxtimeout": "60000",
    "npm_config_loglevel": "notice",
    "npm_config_logs_max": "10",
    "npm_config_message": "%s",
    "npm_lifecycle_script": "ng build",
    "SSH_AUTH_SOCK": "/tmp/ssh-tgef5zg0oRv6/agent.2129",
    "npm_package_scripts_test": "ng test && npm run sonar",
    "npm_config_ca": "",
    "npm_config_cert": "",
    "npm_config_global": "",
    "npm_config_link": "",
    "SHELL": "/bin/bash",
    "npm_package_version": "0.2.7",
    "npm_package_contributors_2_name": "Radosław Dykty",
    "npm_config_access": "",
    "npm_config_also": "",
    "npm_config_save": "true",
    "npm_config_unicode": "true",
    "npm_lifecycle_event": "build",
    "npm_package_scripts_build": "ng build",
    "npm_package_dependencies__angular_router": "~8.2.11",
    "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"build\"],\"original\":[\"run\",\"build\"]}",
    "npm_config_before": "",
    "npm_config_long": "",
    "npm_config_production": "",
    "npm_config_searchlimit": "20",
    "npm_config_unsafe_perm": "true",
    "npm_config_update_notifier": "true",
    "npm_package_dependencies_lodash": "~4.17.15",
    "npm_package_dependencies_ngx_file_drop": "~8.0.8",
    "npm_config_auth_type": "legacy",
    "npm_config_node_version": "12.13.1",
    "npm_config_tag": "latest",
    "KONSOLE_DBUS_SERVICE": ":1.30",
    "npm_config_git_tag_version": "true",
    "npm_config_commit_hooks": "true",
    "npm_config_script_shell": "",
    "npm_config_shrinkwrap": "true",
    "GPG_AGENT_INFO": "/run/user/1000/gnupg/S.gpg-agent:0:1",
    "npm_package_devDependencies_license_checker": "^25.0.1",
    "npm_config_fetch_retry_factor": "10",
    "npm_config_save_exact": "",
    "npm_config_strict_ssl": "true",
    "BASH_IT_THEME": "bobby",
    "XDG_VTNR": "1",
    "npm_package_scripts_test_mr": "ng test && npm run sonar:mr",
    "npm_package_devDependencies__angular_cli": "^8.3.9",
    "npm_config_dev": "",
    "npm_config_globalconfig": "/home/cojack/.nvm/versions/node/v12.13.1/etc/npmrc",
    "npm_config_init_module": "/home/cojack/.npm-init.js",
    "npm_config_parseable": "",
    "PWD": "/home/cojack/Projects/project_a//web-app",
    "npm_config_globalignorefile": "/home/cojack/.nvm/versions/node/v12.13.1/etc/npmignore",
    "npm_execpath": "/home/cojack/.nvm/versions/node/v12.13.1/lib/node_modules/npm/bin/npm-cli.js",
    "XDG_CONFIG_DIRS": "/etc/xdg/xdg-plasma:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings",
    "BASH_IT": "/home/cojack/.bash_it",
    "NVM_CD_FLAGS": "",
    "XDG_DATA_DIRS": "/usr/share/plasma:/usr/local/share:/usr/share:/var/lib/snapd/desktop",
    "npm_package_engines_npm": "~6",
    "npm_package_dependencies_jschardet": "~2.1.0",
    "npm_package_devDependencies_codelyzer": "^5.1.2",
    "npm_package_devDependencies_dotenv_webpack": "^1.7.0",
    "npm_config_cache_lock_retries": "10",
    "npm_config_searchstaleness": "900",
    "npm_config_node_options": "",
    "npm_config_save_prefix": "^",
    "npm_config_scripts_prepend_node_path": "warn-only",
    "KDE_SESSION_UID": "1000",
    "npm_config_group": "1000",
    "npm_config_init_author_email": "",
    "npm_config_searchexclude": "",
    "npm_package_dependencies_zone_js": "~0.9.1",
    "npm_package_devDependencies__angular_devkit_build_angular": "^0.803.21",
    "npm_package_devDependencies_jest_preset_angular": "^7.1.1",
    "npm_config_git": "git",
    "npm_config_optional": "true",
    "npm_package_dependencies__angular_platform_browser": "~8.2.11",
    "npm_package_dependencies_ngx_papaparse": "~4.0.4",
    "npm_config_json": "",
    "INIT_CWD": "/home/cojack/Projects/project_a//web-app",
    "WEBPACK_DEV_SERVER": "true",
    "JEST_WORKER_ID": "4",
    "FORCE_COLOR": "1"
  },
  "userLimits": {
    "core_file_size_blocks": {
      "soft": 0,
      "hard": "unlimited"
    },
    "data_seg_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "file_size_blocks": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_locked_memory_bytes": {
      "soft": 67108864,
      "hard": 67108864
    },
    "max_memory_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "open_files": {
      "soft": 1048576,
      "hard": 1048576
    },
    "stack_size_bytes": {
      "soft": 8388608,
      "hard": "unlimited"
    },
    "cpu_time_seconds": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_user_processes": {
      "soft": 62878,
      "hard": 62878
    },
    "virtual_memory_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    }
  },
  "sharedObjects": [
    "linux-vdso.so.1",
    "/lib/x86_64-linux-gnu/libdl.so.2",
    "/lib/x86_64-linux-gnu/libstdc++.so.6",
    "/lib/x86_64-linux-gnu/libm.so.6",
    "/lib/x86_64-linux-gnu/libgcc_s.so.1",
    "/lib/x86_64-linux-gnu/libpthread.so.0",
    "/lib/x86_64-linux-gnu/libc.so.6",
    "/lib64/ld-linux-x86-64.so.2"
  ]
}
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.20
Node: 12.13.1
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cdk                      8.2.3
@angular/cli                      8.3.20
@angular/material                 8.2.3
@ngtools/webpack                  8.3.21
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-12-31 09:51
Duplicate of https://github.com/angular/angular-cli/issues/16515

**Closed by alan-agius4** 2019-12-31 09:51 UTC
