### ISSUE TITLE
Unable to create a new project

### ISSUE THREAD

**Issue by drpain** [angular/angular-cli#10745] opened 2018-05-09 08:28 UTC
### Versions
```
Angular CLI: 6.0.0
Node: 9.3.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0
@angular-devkit/core         0.6.0
@angular-devkit/schematics   0.6.0
@schematics/angular          0.6.0
@schematics/update           0.6.0
rxjs                         6.1.0
typescript                   2.7.2

```

### Repro steps
Just followed the basic steps on Angular.io

```
npm install -g @angular/cli
ng new my-app
```

### Observed behavior
Fails with the following error:
```
Schematic "ng-new" not found in collection "@schematics/angular".
Error: Schematic "ng-new" not found in collection "@schematics/angular".
    at SchematicEngine.createSchematic (/home/rudis1261/.nvm/versions/node/v9.3.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:155:23)
    at CollectionImpl.createSchematic (/home/rudis1261/.nvm/versions/node/v9.3.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/collection.js:12:29)
    at NodeWorkflow.execute (/home/rudis1261/.nvm/versions/node/v9.3.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/workflow/node-workflow.js:70:38)
    at Promise (/home/rudis1261/.nvm/versions/node/v9.3.0/lib/node_modules/@angular/cli/models/schematic-command.js:141:22)
    at new Promise (<anonymous>)
    at NewCommand.runSchematic (/home/rudis1261/.nvm/versions/node/v9.3.0/lib/node_modules/@angular/cli/models/schematic-command.js:140:16)
    at NewCommand.<anonymous> (/home/rudis1261/.nvm/versions/node/v9.3.0/lib/node_modules/@angular/cli/commands/new.js:77:25)
    at Generator.next (<anonymous>)
    at /home/rudis1261/.nvm/versions/node/v9.3.0/lib/node_modules/@angular/cli/commands/new.js:7:71
    at new Promise (<anonymous>)
```

### Desired behavior
This should just bootstrap a fresh project, but doesn't

### Mention any other details that might be useful (optional)
I googled a bit and some suggested that I install @angular/cli with yarn. I tried that as well, but still have the same error. I tried uninstalling / reinstalling. Nothing

**Comment by clydin** [comment] 2018-05-09 17:40
Duplicate of #10691

Please see the above issue for possible solutions.

**Closed by clydin** 2018-05-09 17:40 UTC

**Comment by drpain** [comment] 2018-05-10 06:51
Super strange, this morning it is working. The only thing that happened in between now and then is that I reset my node to stable using nvm:

```
# Installed the latest
nvm install stable

# default to the latest default node
nvm alias default node

# installed the latest npm
npm install -g npm

# uninstalled ang-cli
npm uninstall @nagular/cli

# installed the latest
npm install @angular/cli@latest
```

My versions now look like this:
```
Angular CLI: 6.0.0
Node: 10.1.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0
@angular-devkit/core         0.6.0
@angular-devkit/schematics   0.6.0
@schematics/angular          0.6.0
@schematics/update           0.6.0
rxjs                         6.1.0
typescript                   2.7.2
```
