### ISSUE TITLE
ng build dropping .woff file extensions

### ISSUE THREAD

**Issue by SeriousLemon** [angular/angular-cli#8099] opened 2017-10-18 23:04 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.8
node: 6.10.3
os: win32 x64
@angular/animations: 4.4.5
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.5
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/router: 4.4.5
@angular/cli: 1.4.8
@angular/compiler-cli: 4.4.5
@angular/language-service: 4.4.5
typescript: 2.3.4

Windows 10

### Repro steps.

Include Font-Awesome in the project. Run `ng build`. The dist folder contains the Font-Awesome font files with missing extensions: 
![image](https://user-images.githubusercontent.com/5023169/31746755-c5329f2a-b4b4-11e7-8dce-faa0b26338f9.png)

**Comment by nicholasblexrud** [comment] 2017-10-19 01:33
+1 getting same issue. Seems to be happening for .woff2 and .ttf too. I also had a straggler image and that was missing its extension (.png) too.
![build-errors](https://user-images.githubusercontent.com/5520610/31750111-8961eb66-b443-11e7-9469-e49cfdc5fcd3.PNG)

**Comment by pwfraley** [comment] 2017-10-19 08:44
Same Problem here.  I just tripped over it, because the IIS will not serve files without an known extension, under nginx no problem.  This problem seems to affect fonts (woff and woff2) as well as images (png).  It seems to happen with the build switch --output-hashing all

**Comment by Taha-Di-Nero** [comment] 2017-10-19 10:06
For me 1.4.8 version breaks loading font-awesome. I just downgrade to 1.4.7 which works fine.

**Comment by martino01** [comment] 2017-10-19 10:43
Same here. The issue seems to be in the 1.4.8 version. Downgrading resolves the problem.

**Comment by smoke** [comment] 2017-10-19 11:12
I can only guess this is caused by https://github.com/angular/angular-cli/commit/776af86 

@filipesilva you might want to check this out.

**Comment by filipesilva** [comment] 2017-10-19 11:21
This is indeed caused by https://github.com/angular/angular-cli/commit/776af86#diff-9eb0a75e499bdadd44d6dc62218812b8R193, the `.[ext]` bit is missing there.

**Comment by karloscode** [comment] 2017-10-19 11:54
Same problem too.

**Comment by avoerman** [comment] 2017-10-19 15:08
Same problem here with .jpg images, and font awesome files.

**Comment by Bidthedog** [comment] 2017-10-19 17:49
Having the same problem. `ng serve` works as expected, but once built and uploaded to an IIS server, the files without extensions can't be served.

**Comment by filipesilva** [comment] 2017-10-19 18:03
We should have this resolved soon, when https://github.com/angular/angular-cli/pull/8108 is merged and released.

**Comment by filipesilva** [comment] 2017-10-19 18:04
Meanwhile, reverting to `v1.4.7` (or `1.5.0-rc.0`) should fix the problem.

**Closed** 2017-10-19 21:50 UTC
Labels: priority: 1 (urgent), severity4: regression, type: bug

**Comment by eppsilon** [comment] 2018-01-25 21:06
Was this ever fixed in 1.4.x? I am still seeing it in 1.4.10.

**Comment by rmeshksar** [comment] 2018-05-07 16:55
For me it works fine on 1.4.9 but not on 1.4.10

**Comment by MedinaGitHub** [comment] 2019-03-15 17:11
my version of angular-cli is 7.0.3  and I also have the same problem
