### ISSUE TITLE
[hashing] sometime leads to Unexpected token < from runtime.js

### ISSUE THREAD

**Issue by indraraj26** [angular/angular-cli#17562] opened 2020-04-28 08:45 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: no idea

### Description

 
We are getting sometime Unexpected token < when we are using outputHashing: 'all' and the site is hosted on aws with gitlab pipeline.

## 🔥 Exception or Error
<pre><code>

Unexpected token < from runtime.js
</code></pre>

## 🌍 Your Environment
<pre><code>

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.0
Node: 10.16.0
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/material                 9.2.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by mix5003** [comment] 2020-04-29 02:02
i think this is not relate to angular cli. but it relate to your webserver.

i don't known exact command for aws. but in normal case you should add header `Cache-Control' 'no-cache, must-revalidate, max-age=0` to `index.html`.

i think this is problem when `index.html` try to load old `runtime.js` but it not exists on server. so it load error page that not actual js (something like `<html><head><title>404 Not Found</title></head></html>`

**Comment by alan-agius4** [comment] 2020-04-29 08:21
Hi @indraraj26, 
@mix5003 is most certainly right here.

Closing as this issue is not caused by the Angular CLI and this issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Closed by alan-agius4** 2020-04-29 08:21 UTC
