### ISSUE TITLE
the ability to work with Schematics pragmatically via API, instead of cli

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular-cli#17878] opened 2020-06-08 12:58 UTC
please provide  documentations for schematics API to work with schematics without the cli.

**Comment by alan-agius4** [comment] 2020-06-08 13:10
Hi @eng-dibo, this seems to be a duplicate of https://github.com/angular/angular-cli/issues/15779

**Closed by alan-agius4** 2020-06-08 13:10 UTC
