### ISSUE TITLE
ng serve try to open .svn folders 

### ISSUE THREAD

**Issue by ishara** [angular/angular-cli#923] opened 2016-05-26 04:59 UTC
ng serve try to open .svn folders. How to avoid this?
> ---------------------------------------------------------------
1. OS?  Windows 10.

2. Versions. 
angular-cli: 1.0.0-beta.5
node: 5.10.1
os: win32 x64

E:\ishara\Project>ng serve
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
EPERM: operation not permitted, open 'E:\ishara\Project\dist\app\+reservation\.svn\entries'
Error: EPERM: operation not permitted, open 'E:\ishara\Project\dist\app\+reservation\.svn\entries'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at TreeSync.<anonymous> (E:\ishara\Project\node_modules\tree-sync\index.js:61:19)
    at Array.forEach (native)
    at TreeSync.sync (E:\ishara\Project\node_modules\tree-sync\index.js:50:14)
    at Class.module.exports.Task.extend.copyToOutputPath (E:\ishara\Project\node_modules\angular-cli\lib\models\builder.js:124:10)
    at E:\ishara\Project\node_modules\angular-cli\lib\models\builder.js:132:21
    at lib$rsvp$$internal$$tryCatch (E:\ishara\Project\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (E:\ishara\Project\node_modules\rsvp\dist\rsvp.js:1048:17)
    at E:\ishara\Project\node_modules\rsvp\dist\rsvp.js:331:11
    at lib$rsvp$asap$$flush (E:\ishara\Project\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by filipesilva** [comment] 2016-06-01 01:54
Can you provide me with reproduction steps?

**Comment by filipesilva** [comment] 2016-07-27 16:52
Closed as obsolete due to #1455.

**Closed by filipesilva** 2016-07-27 16:52 UTC
Labels: need: repro steps, type: question/support
