### ISSUE TITLE
can not work on windows 10

### ISSUE THREAD

**Issue by pensacola1989** [angular/angular-cli#3017] opened 2016-11-04 12:54 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> angular-cli: 1.0.0-beta.19-3
node: 6.8.1
os: win32 x64

### Repro steps.
> it's created by cli

### The log given by the failure.
> [node-sass@3.11.1] scripts.postinstall success, use 211ms
All packages installed (1165 packages installed from npm registry, use 2m, speed 64.16kB/s, json 1414(8.62MB), tarball 0B)                             9465ms building modules         7ms add11641ms1709ms asset48ms emittingHash: 8fa4df10bec17af6f64f
Version: webpack 2.1.0-beta.25
Time: 13405ms
           Asset       Size  Chunks             Chunk Names
  main.bundle.js    2.48 MB    0, 2  [emitted]  main
styles.bundle.js    10.4 kB    1, 2  [emitted]  styles
       inline.js    5.53 kB       2  [emitted]  inline
        main.map    2.58 MB    0, 2  [emitted]  main
      styles.map    14.7 kB    1, 2  [emitted]  styles
      inline.map    5.59 kB       2  [emitted]  inline
      index.html  474 bytes          [emitted]

ERROR in multi main
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localhost:4200/' in 'C:\Users\Daniel-PC\Documents\angular2_wordspace\testcli\node_modules\.npminstall\angular-cli\1.0.0-beta.19-3\angular-cli\models' @ multi main
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.81 kB       0
webpack: bundle is now VALID.

### and also run "npm install " in the target folder 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-11-04 18:02
Dupe of https://github.com/angular/angular-cli/issues/2891

**Closed by filipesilva** 2016-11-04 18:02 UTC
