### ISSUE TITLE
path in index

### ISSUE THREAD

**Issue by erhard** [angular/angular-cli#2568] opened 2016-10-07 15:17 UTC
### OS?
> all OSes

### Versions.
> 1.0.0 beta 16

If you programm the angular app as part of another app for example Rails application the path of the css file and the javascriptfile is relativ to the public dir. If you put the angular part in for example public/ang  the js and css file should have the path "ang/main.js in the index.html to load the javascripts and css.

Example 👍 

the generated (ng build --prod) and modified index.html
```
<script type="text/javascript" src="apollo/ang/inline.js"></script><script type="text/javascript" src="apollo/ang/styles.e87a73ae6c0622a05f75.bundle.js"></script><script type="text/javascript" src="apollo/ang/main.99efe10dac980567b9ae.bundle.js"></script></body>
</html>

```
this should be done via ng build --path "apollo/ang"

This feature would be very helpful to integrate angular2 with angular-cli in other application

**Comment by fullstackdave** [comment] 2016-10-07 15:52
Agreed, JS source files and the resulting HTML needs to separate destination directories, and a simple HTML file with ONLY the resource script definitions would be very helpful.

**Comment by arlowhite** [comment] 2016-10-07 17:16
You can set base href with `ng build --base-href`, but I agree more flexibility is needed.

If you try to use base href to load these files from another directory, it will work, but also impact other URLs in your app.

For example, say you want these files under **/assets/** so you set --base-href=/assets/

This will work, but other relative URLs will be impacted.
`http.get('api/foo')` will GET /assets/api/foo

So angular-cli really needs something like a **outResourcesUrlPrefix** option.

**Comment by clydin** [comment] 2016-10-08 04:59
@arlowhite, If you didn't want your `http.get` to be impacted, why would you use a relative URL?  The whole point of a relative URL is that it can be impacted by its context.

Changing the base href is really the way to go;  lazy-loaded routes, image tags in templates, url()'s from inline CSS, etc. should all keep working.

**Comment by arlowhite** [comment] 2016-10-08 20:58
My point was that in this scenario, you do want base href to impact your API URLs. Maybe you deploy under **/** sometimes, and **/my-app/** other times and the angular-cli app is deployed alongside some service.

Of course you could just prefix all your API URLs with some configurable variable. There are a lot of ways the developer can deal with the problem. But if angular-cli provided a **resourceUrlPrefix** option in addition to **baseHref**, it would be convenient for developers that use relative URLs in their app and also want to relocate the webpack resources to be served from another path.

**Comment by clydin** [comment] 2016-10-09 01:21
@arlowhite, my apologies. From the comment it seemed like you were just using the relative URL because it was quick and easy and happened to work.  I would still caution against the approach, it's a little _magical_ and a new developer taking over the project could very easily break things.  And if the base href ever needed to be changed, there's going to be a large amount of find/replace.

As a general pattern, I'd recommend an _app config_ service containing app-wide settings that can be injected where needed. One of those can be the base API server URL.  If needed this URL could even be computed at startup from `document.location`.

**Comment by filipesilva** [comment] 2016-10-10 13:29
Dupe of https://github.com/angular/angular-cli/issues/2276 I think. If that's not the case, let me know and I'll reopen.

**Closed by filipesilva** 2016-10-10 13:29 UTC
