### ISSUE TITLE
pnpm support for angular 16+

### ISSUE THREAD

**Issue by omidpaydar** [angular/angular-cli#27906] opened 2024-06-22 13:32 UTC
### Command

build

### Description

I want to use pnpm in the Angular build process in a case where the node_modules folder is not copied for each project and only uses its reference globally. When using this method, I get the error that the modules folder does not exist. Is there a solution for this method?

**Comment by alan-agius4** [comment] 2024-06-22 13:45
Duplicate of https://github.com/angular/angular-cli/issues/16980

**Closed by alan-agius4** 2024-06-22 13:45 UTC
