### ISSUE TITLE
Internet Explorer prod build broken at runtime by 8.3.20 upgrade

### ISSUE THREAD

**Issue by Wisdomb33r** [angular/angular-cli#16405] opened 2019-12-10 06:56 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.3.19

### Description

Production build is completely fine when compiled with 8.3.19 and is working on Internet Explorer. Upgrading to 8.3.20 (and devkit/build-angular to 0.803.20 accordingly) is breaking the runtime execution of the app. No other project change besides this 19-to-20 change.

## 🔬 Minimal Reproduction

The problem is NOT present when I use `ng serve` nor it is with `ng serve --prod` (assuming here the target is es5). I could only get the error when the final prod build is deployed on a web server (with differential loading active). The error stacktrace is consequently lost in the minified JS and doesn't say much about the problem location.

## 🔥 Exception or Error
<pre><code>
Object doesn't support property or method 'some'
</code></pre>

According to MDN, Arrays.some is supported by Internet Explorer since version 9. I searched my entire code for calls to any `some` method and could not find a single one.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.20
Node: 12.13.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.20
@angular-devkit/build-angular      0.803.20
@angular-devkit/build-optimizer    0.803.20
@angular-devkit/build-webpack      0.803.20
@angular-devkit/core               8.3.20
@angular-devkit/schematics         8.3.20
@angular/cdk                       8.2.3
@angular/cli                       8.3.20
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   8.3.20
@schematics/angular                8.3.20
@schematics/update                 0.803.20
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**
IE11

Browserslist :
<pre><code>
> 0.5%
last 2 versions
Firefox ESR
not dead
IE 9-11 # For IE 9-11 support, remove 'not'.
</code></pre>

Compiler options for `ng build --prod` :
module : exnext
target: es2015

**Comment by clydin** [comment] 2019-12-10 15:42
Duplicate of #16366

**Closed by clydin** 2019-12-10 15:42 UTC
Labels: comp: devkit/build-angular, freq1: low, severity5: regression, type: bug/fix
