### ISSUE TITLE
Environment flags not working

### ISSUE THREAD

**Issue by VictorJuliani** [angular/angular-cli#7138] opened 2017-07-25 17:10 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.2.4
node: 6.10.3
os: win32 x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.4
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1
```

### Repro steps.
1. Create a new project through **ng new** and install dependencies
2. **Import** environments/environment in app.component
3. Add some conditional behavior depending on the environment
4. Serve the project with env attribute (tried all these)
```
ng serve --e=prod --env=prod -e=prod -env=prod --environment=prod -environment=pro
d
```

### Desired functionality.
It should import the correct environment properties accordingly to the flag used.

### Mention any other details that might be useful.
It stopped working after a yarn upgrade ran on my project and then I tested with a fresh new project generated by the cli.

**Comment by alexzuza** [comment] 2017-07-25 19:51
I had the same issue recently but it was related with `enhanced-resolve` package. But you seems use the fixed version of angular-cli

**Comment by chadbr** [comment] 2017-07-25 20:43
I have the same problem... the enhanced-resolve hack fixes this?

**Comment by chadbr** [comment] 2017-07-25 21:10
any ideas when it started? I'm back to 1.2.2 so far and still broken -- broken in all of 1.2.x?

**Comment by chadbr** [comment] 2017-07-25 21:17
ok - it's broken in 1.2... rolling back to 1.1.2 fixed it...

**Comment by etaylor8086** [comment] 2017-07-25 22:57
Running node 6.10.2. I narrowed down the issue to webpack using `enhanced-resolve@3.4.1` on my project. Deleting my `node_modules/` directory and running `npm install` will still install the `3.4.1` version of this package from as far back as `@angular/cli@1.1.2`, from what I've tested.

I can't say the following solution is good, but as a temporary workaround I've simply installed `enhanced-resolve@3.3.0` as a dev dependency:

`npm install --save-dev enhanced-resolve@3.3.0`

I'm not using this package anywhere else in my project, so this works for me until I find a better way. Maybe I could set up a `npm-shrinkwrap.json` and force webpack to use `enhanced-resolve@3.3.0`?

**Comment by etaylor8086** [comment] 2017-07-25 23:57
Issue is described in more detail here: https://github.com/webpack/enhanced-resolve/issues/98

[Angular devs checked in a fix earlier today](https://github.com/angular/angular-cli/commit/c26a5f774c284d8ba0a7b0385b3c0328b9218a49), just a matter of the next release including it (hopefully soon)

**Comment by etaylor8086** [comment] 2017-07-26 00:47
Aaaaaand I missed the part where this exact fix was rolled into the 1.2.4 CLI release yesterday. Update to that version (you should be fine with your Node version) and you should be set.

**Comment by chadbr** [comment] 2017-07-26 03:39
I noticed the issue on 1.2.4 -- upgraded yesterday... it wasn't working for me.

**Comment by VictorJuliani** [comment] 2017-07-26 11:54
Both my global and local versions are 1.2.4 and it still doesn't work for me.
The yarn.lock file contains an enhanced-resolver@3.0.0, but it has the ^3.0.0 version too. The workaround (installing enhanced-resolver as a dev-dependency) didn't work either.

**Comment by netdeamon** [comment] 2017-07-26 15:27
I installed @angular/cli version with 1.1.0 and 1.2.1, but the environment flags were not working.

**Comment by kl4n4** [comment] 2017-07-26 16:12
still doesnt work for me either - already tried @angular/cli versions 1.2.3, 1.2.4 and 1.3.0-rc.1

build itself works (when using --prod flag, AoT has to be disabled) but in the final JS bundle the values of dev environment.ts are included.

**Comment by netdeamon** [comment] 2017-07-26 16:25
Does it have to do anything with the angular version? I am using 4.3.1 version of angular. Should I downgrade angular version to use lower version of cli? I am using angular 4.3.X for the new http interceptors.

**Comment by chadbr** [comment] 2017-07-26 16:29
@netdeamon make sure you delete your .lock file when you're rolling back cli (or any package...) -- 1.1.x works for me...

**Comment by netdeamon** [comment] 2017-07-26 16:37
@chadbr What is the angular version that you are using? I am using 4.3.1 angular and 1.1.2 angular cli version. But it was not picking up the right environment file. I delelted the .lock file that you suggested.

**Comment by netdeamon** [comment] 2017-07-26 16:45
Thanks @chadbr , it worked for me. I was experimenting with the .angular-cli.json while solving this issue. Using the 1.1.2 version of angular/cli with 4.3.1 angular worked for me. Thanks

**Comment by filipesilva** [comment] 2017-07-27 09:45
I tried to repro this on a new project using `@angular/cli@1.2.5` and wasn't able to see it. This is what I did:

- in  `main.ts` added `console.log('main.ts environment.production:', environment.production);`
- in `app.component.ts` added 
```
import { environment } from '../environments/environment';
console.log('app.component.ts environment.production:', environment.production);
```
- ran `ng serve` and saw:
```
app.component.ts environment.production: false
main.ts environment.production: false
```
- ran `ng serve --prod`  and saw:
```
app.component.ts environment.production: true
main.ts environment.production: true
```
- ran `ng serve --env=prod`  and saw:
```
app.component.ts environment.production: true
main.ts environment.production: true
```

So I think it is working correctly. You mentioned you used yarn though... and as far as I know there is a problem with yarn itself: https://github.com/angular/angular-cli/issues/7136#issuecomment-318313404

I'm closing this issue in favor of that one.

**Closed by filipesilva** 2017-07-27 09:45 UTC

**Comment by chadbr** [comment] 2017-07-31 16:14
for people following along... 1.2.6 fixes the issue for me.

thanks -- Chad

**Comment by AnthonyGiretti** [comment] 2017-10-03 19:42
I'm sorry but it's still not working for me:

i have this :
"environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts",
        "qa": "environments/environment.qa.ts"
      }

and it uses prod configuration 
i ran this: ng build --env=qa

**Comment by hiyali** [comment] 2017-11-24 09:10
Same issue with custom flag.

**Comment by marcuslind90** [comment] 2017-11-27 11:07
I'm having this issue when using `--prod` or `--environment=prod`. It ignores the production file and keep using my development environment.ts file.

**Comment by hiyali** [comment] 2017-11-27 16:45
I solved my problem now with many apps environment, it is a path problem I guess, you can do below for resolve this issue.
change `.angular-cli.json`
```javascript
"environments": {
  "dev": "./environments/environment.ts",
  "prod": "./environments/environment.prod.ts",
  "local": "./environments/environment.local.ts"
}
```
move `./src/environments` to `./src/someApp/environments`, and added the environment.local.ts.
And enjoy.
```shell
ng s -a someApp -e local
ng b -a someApp -e local
ng b -a someApp --prod // for production
ng s -a someApp // for development
```

**Comment by chadbr** [comment] 2017-11-27 17:13
@filipesilva should I open a new bug report for this or should this one be re-opened?

**Comment by filipesilva** [comment] 2017-11-30 10:59
@chadbr can you provide a reproduction I can follow to see it not working please? Happy to reopen then.

**Comment by darincardin** [comment] 2018-04-12 19:03
same issue ("@angular/cli": "1.4.9"),.....and the bug is listed as closed?

**Comment by AnthonyGiretti** [comment] 2018-04-12 19:04
Closed

Le jeu. 12 avr. 2018 à 15:04, Darin Cardin <notifications@github.com> a
écrit :

**Comment by phra** [comment] 2018-05-01 12:47
it seems broken again with `Angular CLI: 1.7.4` on Mac..
