### ISSUE TITLE
Creating a new project with --style=scss doesn't work properly

### ISSUE THREAD

**Issue by bulletinmybeard** [angular/angular-cli#3798] opened 2016-12-31 00:29 UTC
### OS: macOS Sierra (10.12.2 – 16C67)
angular-cli: 1.0.0-beta.19-3
node: 7.2.1
os: darwin x64

### Versions: 1.0.0-beta.19-3
node: 7.2.1
os: darwin x64

When creating a new project with the parameter `--style=scss`, the code block with `./app.component.scss` in `./app/app.component.ts` doesn't work until you rewrite this part.

**Doesn't work**
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styles: [
    './app.component.scss'
  ]
})
```

**Works fine**
```
import { Component, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styles: [
    require('./app.component.scss').toString()
  ],
  encapsulation: ViewEncapsulation.None
})
```

Cheers

**Comment by mattdistefano** [comment] 2016-12-31 00:56
Have you tried with the current version?

**Comment by bulletinmybeard** [comment] 2016-12-31 01:15
Unfortunately, I ran into some strange issues when I upgraded **Angular-CLI** to **v1.0.0-beta.24** and Angular 2 to **@angular/core@latest** (because I had to upgrade angular as well!) and I have no time to make it work. Therefore I'm working with versions they are compatible with each other. Especially because of a good few 3rd party modules, I have to use for the project.

Cheers

**Comment by robertbaker** [comment] 2016-12-31 03:37
I'm on latest, can reproduce.

**Comment by clydin** [comment] 2016-12-31 13:38
The styles field is for inline styles. URLs should be placed in styleUrls.

**Comment by bulletinmybeard** [comment] 2016-12-31 13:39
@clydin exactly!

**Comment by clydin** [comment] 2016-12-31 14:24
That doesn't seem to be the case.

Running `ng new styletest --style=scss` generates:
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'app works!';
}
```

Also, looking at the template from beta.19 shows that it should be generating the appropriate output as well.
https://github.com/angular/angular-cli/blob/23a6cc658aa6c342b0e2558730c3576eda4ced57/packages/angular-cli/blueprints/ng2/files/__path__/app/app.component.ts#L13

**Comment by hansl** [comment] 2017-01-21 21:01
Closing this as deprecated. Seems to be working fine.

**Closed by hansl** 2017-01-21 21:01 UTC
