### ISSUE TITLE
no chunks created when lazy loading...

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#4121] opened 2017-01-19 19:45 UTC
### problem
I am using ng-cli with lazy loading:

```
...
{path: 'studioweb', pathMatch: 'full', redirectTo: '/App1/Dashboard'},  // IE/FF compatibility
    {
        path: 'App1', component: Appwrap,
        children: [
            {path: '', component: Appwrap, canActivate: [AuthService]},
            {path: 'Dashboard', component: Dashboard, data: {title: 'Dashboard'}, canActivate: [AuthService]},
            {path: 'Campaigns', loadChildren: '../app/campaigns/index#CampaignsLazyModule', data: {title: 'Campaigns'}, canActivate: [AuthService]},
            {path: 'Fasterq', loadChildren: '../app/fasterq/index#FasterqLazyModule', data: {title: 'Fasterq'}, canActivate: [AuthService]},
...
```

I generate the build dist with:
```
ng build --target=production --base-href ./
```

and I don't see any chunks.
and while all "seems" to work, I am not sure lazy loading is working, almost as if Webpack bundles it all in?!?!?!

How can I confirm if lazy loading is working?
Why are chunks not created? bug?

### OS?

angular-cli: 1.0.0-beta.25.5
node: 6.5.0
os: win32 x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/language-service: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.2.1
@angular/compiler-cli: 2.4.4

snap:

![nochunks](https://cloud.githubusercontent.com/assets/5090936/22122393/a1635c46-de3c-11e6-8480-7336ae35c45c.PNG)

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by filipesilva** [comment] 2017-01-19 19:52
Dupe of https://github.com/angular/angular-cli/issues/2496

**Comment by born2net** [comment] 2017-01-19 19:53
that issue is closed... please advise ...

**Closed by filipesilva** 2017-01-19 19:52 UTC

**Comment by born2net** [comment] 2017-02-02 20:57
looks like build .28-3 still does not generate any chunks for lazy loading

**Comment by eklee** [comment] 2017-02-10 01:40
Same with build .30. Lazy routes work fine, but no chunking.

**Comment by laserus** [comment] 2017-02-15 11:00
@born2net @eklee I had the same issue, but now it works with .31 perfectly

**Comment by heppokoact** [comment] 2017-12-14 04:48
In my case, I remove the lazy load module from "imports" in app.module.ts and it's solved.

**Comment by mitsukikaminaga** [comment] 2017-12-14 04:50
In my case, I remove the lazy load module from "imports" in app.module.ts and it's solved.
