### ISSUE TITLE
Angular 6+ library development workflow should follow npm development conventions

### ISSUE THREAD

**Issue by nfriend** [angular/angular-cli#10751] opened 2018-05-09 13:55 UTC
### Versions
```
Angular CLI: 6.0.0
Node: 8.9.1
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.0
@angular-devkit/build-angular      0.6.0
@angular-devkit/build-ng-packagr   0.6.0
@angular-devkit/build-optimizer    0.6.0
@angular-devkit/core               0.6.0
@angular-devkit/schematics         0.6.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.0
@schematics/angular                0.6.0
@schematics/update                 0.6.0
ng-packagr                         3.0.0-rc.3
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.6.0
```

### Observed behavior
[With the release of Angular 6, the CLI now supports the concept of creating Angular 6+ libraries.](https://github.com/angular/angular-cli/wiki/stories-create-library)  However, the workflow imposed by the CLI does not line up with a typical npm module development workflow:

- A library cannot be generated without first generating an app.
- Building the library creates an _entirely new module_ in the `dist` directory, complete with its own `package.json`.  As a result, publishing the module requires the developer to run `npm publish` from within the `dist` folder, rather than at the root of the project.
- In the same vein, linking an Angular library for local development requires the `npm link` command to be run from within the `dist` folder.
- Because the library has its own `package.json`, it's unclear where library dependencies should be installed.  If dependencies are installed into the root `package.json`, the dependencies don't get included in the package published to npm.  However, if the dependencies are instead installed into the library's `package.json` (i.e. `./projects/my-module/package.json`), an error is thrown when `ng build my-module` is run (`BUILD ERROR: Dependency XXX must be explicitly whitelisted`).
- After a library is built, a total of **five** package-related files exist in the project directory.  This has the potential to be very confusing:
  - `./package.json`
  - `./projects/package.json` 
  - `./projects/ng-package.json` 
  - `./projects/ng-package.prod.json` 
  - `./dist/my-module/package.json` 

### Desired behavior
The Angular 6+ library development experience should match that of developing a typical npm module:

- An Angular 6+ library should be able to be generated without first creating an app.
- Building an Angular library should not create a new module (e.g. a new `package.json`).
- The `npm publish` and `npm link` commands should be able to be run from the root of the project.

**Comment by maxtacco** [comment] 2018-05-09 17:00
@nfriend, I'm not sure if you consider the fact that people build Angular libraries that are used by multiple Angular projects and are published to NPM as separate packages. So, it would be nice to support the generation of Angular libraries without creating an app first, but I don't see how the other 2 points make sense.

Also, you can try using "devDependencies" combined with "peerDependencies" when building a library.

**Comment by yogesh-randhawa** [comment] 2018-05-09 22:12
Totally agree with maxtacco. We should be able to build the ng 6 libraries independently and import them as npm dependencies in any app.

**Comment by joashmusyoka** [comment] 2018-05-15 09:17
I think it would also be nice to create a namespaced library e.g `@namespace/library`. Tried to do that but when importing I had to use `import { Stuff } from library`. It seemed to ignore the namespace bit

**Comment by mcaden** [comment] 2018-05-15 17:39
I view the app at the base as a great place to create a "sample" app for the library - ensuring that as set up the library created under it can be consumed.

However, `ng build` on the base app actually kills the `dist` folder - which destroys the as-built library.

**Comment by maxtacco** [comment] 2018-05-15 17:43
@mcaden, I experienced the same issue. I updated "dest" property in ng-package.json of my library to output to a different folder as a fix for now.

**Comment by jSchez** [comment] 2018-05-24 14:54
Totally agree.

The Angular guys are greating a great job but please: stop monopolizing all the workflow, and sorry to say it this way. 
Angular itself uses npm ecosystem. Why cannot we just make 

> ng library whatever

, which would create a basic project structure ready to be linked by a cli app ? Similar to
https://github.com/jvandemo/generator-angular2-library

Ng-packagr is great, but I really think big angular applications need the flexibility of npm, and not a strict schema where you cannot watch changes or attach sass files to the dist.

Best regards.

**Comment by sergiolc** [comment] 2018-06-07 09:45
@joashmusyoka , I have it working fine. Just remember to add:
```
"paths": {
    "@namespace/library": ["dist/namespace/library"]
}
```
in your tsconfig file.
Hope it helps.

**Comment by joashmusyoka** [comment] 2018-06-07 10:03
Thanks, I will try this

**Comment by abcfoundry** [comment] 2018-06-19 12:03
I'm really hoping that addressing the "library" workflow and features becomes a priority to angular cli team.  It's critical to enable the ecosystem.  Think of all the angularjs libraries that are just dormant now!  If we truly want angular to flourish, library creation and publishing should be a no brainer!  Simply put we need simplified workflow and dependency control/flexibility.

**Comment by jimbarrett33** [comment] 2018-06-19 14:54
A positive thing about the default app and library(s) in the same Workspace is that if you are building out a new app and re-usable libraries at the same time you can build and debug the libraries as part of your app development -- your app is actually the "sample" app. At some point as the app and libraries become more mature, the Library projects can be shared/published as NPM packages.

**Comment by gp187** [comment] 2018-06-28 06:29
It's all about the `dist` getting deleted on the build. Here's my workaround

Creating a library
`ng generate library tvmaze --prefix=tv`

Go to `path/to/your/app/tsconfig.json` and delete 
```
"tvmaze/*": [  "projects/tvmaze/dist/*"]
```
and now change the path for the `tvmaze` from `projects/tvmaze/dist` to `../distPack/tvmaze`
```
"tvmaze": [  "../distPack/tvmaze"]
```

**NOTE**: you can also add a namespace to be nice, just change to `@supername/tvmaze`

Go to `projects/tvmaze/ng-package.json` and change the `dist` to `distPack`
```
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../distPack/tvmaze",
  "deleteDestPath": false,
  "lib": {
    "entryFile": "src/public_api.ts"
  }
}
```


Now just use it 
`import {TvmazeModule} from '@supername/tvmaze';`

**Comment by qqnc** [comment] 2018-06-28 16:13
I altered the projects folder to src and make src folder as demo/playground as my library source.  That structure makes sense to me.   I agree that angular-cli should create a library without a workspace.  However, for some monorepo, multiple package.json to maintain dependencies seems necessary.

**Comment by jcroll** [comment] 2018-08-07 21:47
Ok can someone please clarify for me: is the official method for creating a git repo for npm angular 6 library to create an _entire_ angular 6 application with a `projects` folder and then your actual library in that folder? If that is the case that seems to me a bit bizarre, if anyone wants to contribute to your library they will be confused with all this app code in it.

What if you want to move your library into its own git repo? Is the best practice to create a git submodule in your `products` folder of your top level app?

**Comment by jSchez** [comment] 2018-08-08 07:11
@jcroll In my experience, there is no such thing as "official method" yet. It all depends on the situation you are in and what you are willing to sacrifice.

**Comment by wulfsberg** [comment] 2018-08-08 12:59
For the situation @jcroll mentions, I'd lean towards having the library in the `projects` folder and using the root project for demonstration and documentation. I don't find it bizarre to have the app code around it; on the contrary, I'd find it a help to see how library could/should be used in an actual app.
It sort of feels like the actual "payload"; the library itself, is rather hidden in a "random subfolder" this way, but for an Angular developer, it is a recognizable structure.

But as @jSchez says, I think we're currently all feeling our way around, trying to figure out the best practices.

**Comment by Antaris** [comment] 2018-08-18 19:47
In terms of the issue of having to create an app as well as a lib, is it not beneficial to have a sample app paired alongside your library so you can demonstrate busage as well as test?

**Comment by mikejr83** [comment] 2018-09-10 17:51
Is it also such that a library must be a single module?

I'm taking a library written on an earlier version of the Angular CLI and ripping the modules out and adding them to the library "project". I've been able to export them all through the `public_api.ts` file using barrel files. However, building in prod mode, using AOT, I get a host of errors either in building the library portion or when trying to import modules in the "containing app".

I liken the current approach used by the CLI as somewhat similar to how VisualStudio works. It creates a "solution". The solution is your demo application. You can add more "projects" from the various things that can be done through the schematics. 

It just seems frustrating that after the all the work that has been done and touted in the version 6 release that there are still these basic tooling issues. Look at other large or "production grade" type libraries. For example angular material. They support Angular 6 and even the CLI, but you'll be quick to notice that their project is not using the CLI itself.

**Comment by kqadem** [comment] 2018-09-10 22:42
> @mikejr83 
> However, building in prod mode, using AOT, I get a host of errors either in building the library portion or when trying to import modules in the "containing app".

Ensure your prod build also creates [valid  .metadata.json](https://angular.io/guide/aot-compiler#phase-1-analysis).

Btw: Importing from directoryies ('/') will cause ng-packagr to **Not** emit Metadata, sometimes even without throwing compile errors. You need to directly import from ('/index')

See https://github.com/ng-packagr/ng-packagr/issues/917

**Comment by rweng** [comment] 2019-02-08 17:38
> @joashmusyoka , I have it working fine. Just remember to add:
> 
> ```
> "paths": {
>     "@namespace/library": ["dist/namespace/library"]
> }
> ```
> in your tsconfig file.
> Hope it helps.

However, in the angular schema `@` is not allowed for projects, see https://github.com/angular/angular-cli/blob/4718de4dae9bbdf25882091610dfc0afc54341b0/packages/angular/cli/lib/config/schema.json#L30

**Comment by ciekawy** [comment] 2019-02-26 17:27
would it be possible to have one library but group it inside so then I can do: 
```
import { SomeService } from '@myOrg/lib/services';
import { SomeEntity } from '@myOrg/lib/model'
```

a bit side question I still think is related

**Comment by spenoir** [comment] 2019-05-03 09:10
I really think there needs to be some documentation on this or a part 3 to the very useful: [Angular in depth library series](https://blog.angularindepth.com/creating-a-library-in-angular-6-87799552e7e5)

I want to be able to use my library in three ways:

1. using the tester app which works well.
2. Locally as a library in a different app altogether, this also works fine and is described in the angularindepth articles clearly.
3. As an unpublished private npm package installed via git.

Step 3 is the problem. I guess I will just commit my entire dist folder and in theory, editing paths in tsconfig will probably work like @rweng suggests above. Shame we can't use the tarball in some way. Npm can't install from a git package subfolder which I have looked into. Only other option would be a private npm registry I guess, something I don't know much about.

**Comment by alan-agius4** [comment] 2020-11-13 11:34
Thanks everyone for participating in this conversation, however as any long outstanding issue the discussion is going off topic. Before closing, I'll try to answer and clarify as many points as I can.

> An Angular 6+ library should be able to be generated without first creating an app. 

This is possible via `ng new --no-create-application`, See: https://angular.io/cli/new

> Building an Angular library should not create a new module (e.g. a new package.json)

We follow the mono-repo model, similar to other tools, such as Lerna and Bazel. Where the dependencies in the root level package.json are shared among all projects of the workspace. Hence the root level package.json, is not reserved to any project in the workspace.

>The `npm publish` and `npm link` commands should be able to be run from the root of the project.

I think changing this now would be more confusing and overall I think that having a `dist` package is cleaner and more intuitive (What you see if what you get sort of thing). Over the years, I experienced multiple times that libraries using the publish from the root causes accident breakages. Because either they missed to update the `.npmignore` or the `files` option in `package.json`. Not to mention that this approach does require more maintenance and is not as straightforward to publish from a dedicated distributable folder

Also, this is rather limiting and you will not be able to do certain transitions on files such as `package.json` as it will override the source package.json. Apart from that it's would be rather messy to write the transpilled `.js` file next to the `.ts` sourcefiles.

> Confusing library dependencies and root level dependencies
In many cases a library should not any dependencies, most of the dependencies used in the library should be declared as peer dependencies. See: https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md

> In the same vein, linking an Angular library for local development requires the npm link command to be run from within the dist folder.

Indeed although for a better DX we recommend using a mono repo instead of `npm link`.

> After a library is built, a total of five package-related files exist in the project directory. This has the potential to be very confusing.

Those files have now been reduced and they all serve different purposes.

- ./package.json - mono repo dependencies
- ./projects/package.json - library package.json, should contain version, desc, name, peerDependencies
- ./projects/ng-package.json - ng-packagr configuration file
- ./dist/my-module/package.json - the augmented package.json from the library src.

**Closed by alan-agius4** 2020-11-13 11:34 UTC
Labels: type: RFC / discussion / question
