### ISSUE TITLE
Can't serve fresh install Angular Ivy Enabled with PWA and Universal 

### ISSUE THREAD

**Issue by paulwscom** [angular/angular-cli#14990] opened 2019-07-04 01:59 UTC
# 🐞 Bug report

### Command (mark with an `x`)
- [x] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes

### Description
Just a fresh install angular ivy enabled with PWA and Universal

## 🔬 Minimal Reproduction
ng new shiny-ivy-app --enable-ivy
ng add @angular/pwa --project *project-name*
ng add @nguniversal/express-engine --clientProject angular.io-example
ng serve --open

## 🔥 Exception or Error
<pre><code>Schema validation failed with the following errors:
Data path "" should have required property 'main'.</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.0
Node: 10.15.3
OS: win32 x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.801.0
@angular-devkit/build-angular              0.801.0
@angular-devkit/build-optimizer            0.801.0
@angular-devkit/build-webpack              0.801.0
@angular-devkit/core                       8.1.0
@angular-devkit/schematics                 8.1.0
@angular/pwa                               0.801.0
@ngtools/webpack                           8.1.0
@nguniversal/express-engine                8.1.0
@nguniversal/module-map-ngfactory-loader   8.1.0
@schematics/angular                        8.1.0
@schematics/update                         0.801.0
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.35.2</code></pre>

**Comment by mgechev** [comment] 2019-07-04 02:58
Thanks for reporting this issue! Ivy is in an opt-in preview, which means that it's not officially supported yet. In other words, we'd recommend using `--enable-ivy` flag only for experimental purposes.

I'll leave the issue open so we can keep track of the progress.

**Comment by bobspace** [comment] 2019-07-04 03:16
I'm encountering the same issue with an even simpler repro case:
```
ng new my-app
ng add @nguniversal/express-engine --clientProject my-app
npm run build:ssr && npm run serve:ssr
```
Just trying to do the bare bones getting started case and it's not working.

**Comment by hoalarious** [comment] 2019-07-04 03:18
Just got the same issue. Worked around it by re-adding build options in angular.json
<pre><code>
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/browser",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.webmanifest",
              "src/sitemap.xml",
              "src/robots.txt"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },

</pre></code>

Afterwords you may get another error:
<pre><code>
ERROR in Node does not exist: C:/something/angularProject/node_modules/@nguniversal/express-engine
</pre></code>

Got around this one by removing
<pre><code>
export { ngExpressEngine } from "@nguniversal/express-engine";
export { provideModuleMap } from "@nguniversal/module-map-ngfactory-loader";
</pre></code>
in main.server.ts

In the end still not working though... Please help 💃

**Comment by hoalarious** [comment] 2019-07-04 03:32
Got further by adding this line back in from old code

<pre><code>
import {enableProdMode} from '@angular/core';
// Express Engine
import {ngExpressEngine} from '@nguniversal/express-engine';
// Import module map for lazy loading
import {provideModuleMap} from '@nguniversal/module-map-ngfactory-loader';
</pre></code>
into server.ts

and removing ngExpressEngine and provideModuleMap from 
<pre><code>
const {AppServerModuleNgFactory, LAZY_MODULE_MAP, ngExpressEngine, provideModuleMap} = require('./dist/server/main');

</pre></code>
into server.ts

At the bottom of the outputted server.js file might load the wrong DIR to main.js. So you might need to update the DIR appropriately.

<pre><code>
/***/ }),
/* 398 */
/***/ (function(module, exports) {

module.exports = require("./server/main");

/***/ })
/******/ ]);
</pre></code>

into something like module.exports = require("./[project-name]-server/main");

**Comment by paulwscom** [comment] 2019-07-04 03:53
@hoalarious It will not work for `npm run build:ssr` if you're lazy loading modules

**Comment by hoalarious** [comment] 2019-07-04 03:56
I couldn't get it to work with Ivy btw. Gonna stay way from Ivy until it's more stable.

**Comment by alan-agius4** [comment] 2019-07-04 05:48
There seems to be a regression in Angular Universal Schematics which are causing options to be removed when using `ng add`. 

I will take a look at it today.

**Comment by alan-agius4** [comment] 2019-07-04 06:19
Closing in favor of https://github.com/angular/universal/issues/1189

**Closed by alan-agius4** 2019-07-04 06:19 UTC
