### ISSUE TITLE
Angular Json Version 2 With Standalone Configurations

### ISSUE THREAD

**Issue by kurtisblaine** [angular/angular-cli#21961] opened 2021-10-15 18:17 UTC
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No, the previous versions contained this bug.

### Description

Angular json version 2 supports standalone configuration files. When running the pwa schematic from the @angular/pwa collection, it throws an exception that only version 1 is expected. 

## 🔬 Minimal Reproduction

1. Use standalone configs for each project in monorepo.
{
"version": 2,
"projects": {
"test-app": "apps/test-app/",
}
}

2. Run @angular/pwa: pwa with these arguments.
{
project: test-app,
title: 'Test App'
}

## 🔥 Exception or Error

<pre><code>

Error: Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]
    at Object.readJsonWorkspace (C:\repos\Daktronics-Web-Platform\node_modules\@angular\pwa\node_modules\@angular-devkit\core\src\workspace\json\reader.js:31:15)
    at async Object.readWorkspace (C:\repos\Daktronics-Web-Platform\node_modules\@angular\pwa\node_modules\@angular-devkit\core\src\workspace\core.js:90:25)
    at async Object.getWorkspace (C:\repos\Daktronics-Web-Platform\node_modules\@angular\pwa\node_modules\@schematics\angular\utility\workspace.js:53:27)
    at async C:\repos\Daktronics-Web-Platform\node_modules\@angular\pwa\pwa\index.js:69:27

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.1.3
Node: 14.17.5
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 12.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.3
@angular-devkit/build-angular   12.1.3
@angular-devkit/core            12.1.3
@angular-devkit/schematics      12.1.3
@angular/cli                    12.1.3
@angular/pwa                    0.1102.5
@schematics/angular             12.1.3
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

**Comment by clydin** [comment] 2021-10-15 18:28
Duplicate of #21959

**Closed as completed by clydin** 2021-10-15 18:28 UTC
