### ISSUE TITLE
problem with dev-server when dot in url ( e.g. /path/before.after )

### ISSUE THREAD

**Issue by joepjoosten** [angular/angular-cli#26881] opened 2024-01-16 12:46 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using the new build system (@angular-devkit/build-angular:browser-esbuild or @angular-devkit/build-angular:application), and runing ng serve, having a route that can contain dots in the path don't wont work, because vite is not rewriting this path to /index.html to serve to angular browser application.

When running with:
`DEBUG=* ng serve`

I get the following message:
`vite:html-fallback Not rewriting GET /path/before.after because the path includes a dot (.) character.`

When i dug a little further i found out it's related to the connect-history-api-fallback package used by the webpack-dev-server package. 

Using @angular-devkit/build-angular:browser, with the babel compiler, behaves differently, and allows for rewriting with a dot in the path.

### Minimal Reproduction

1. Build a small app, with a route like '/path/before.after'. Make sure that you are using @angular-devkit/build-angular:browser-esbuild or @angular-devkit/build-angular:application.
2. Start dev-server
3. Directly route to /path/before.after

### Exception or Error

```text
`vite:html-fallback Not rewriting GET /path/before.after because the path includes a dot (.) character.`
```

### Your Environment

```text
Angular CLI: 17.0.10
Node: 20.10.0
Package Manager: npm 10.2.3
OS: darwin arm64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.10
@angular-devkit/core         17.0.10
@angular-devkit/schematics   17.0.10
@angular/cli                 17.0.10
@schematics/angular          17.0.10
```

**Comment by alan-agius4** [comment] 2024-01-16 13:30
Duplicate of https://github.com/angular/angular-cli/issues/25671 

This has been fixed in 17.1.0 which will be released as stable later this week.

**Closed by alan-agius4** 2024-01-16 13:30 UTC
