### ISSUE TITLE
Making angular-cli work with strict CSP?

### ISSUE THREAD

**Issue by atticae** [angular/angular-cli#3430] opened 2016-12-06 13:07 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 7

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.6.0
os: win32 x64
chrome: 54.0.2840.99 m (64-bit)

### Repro steps.
1. Run `ng new csp-test`
1. Add the following meta tag to index.html:
`  <meta http-equiv="Content-Security-Policy" content="default-src 'none';
    script-src 'self';
    style-src 'self';
    img-src 'self';
    connect-src 'self' ws://localhost:4200;
    font-src 'self';">`
1. Run `ng serve -aot`
1. Open `localhost:4200` in chrome

### The log given by the failure.
The following errors show up in the Chrome debugger console:

>Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.
> insertStyleElement @ addStyles.js:115
>
>Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-xylbkVtqJQuRDTD/O50Zkbb0PJR006+vxsulnu5EOD4='), or a nonce ('nonce-...') is required to enable inline execution.
> applyToTag @ addStyles.js:225
>
>Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.
> DomSharedStylesHost._addStylesToHost @ shared_styles_host.js:55

### Mention any other details that might be useful.
Is there any way to make angular2 with angular-cli work with a strict Content Security Policy? I realize I can add 'unsafe-inline', but that defeats a lot of the purpose of CSP.

**Comment by clydin** [comment] 2016-12-06 14:59
I don't think there is a way to completely avoid `unsafe-inline` for styles.  And if you define any scripts in `angular-cli.json`, you'll also need `unsafe-eval' unfortunately.

**Comment by hansl** [comment] 2016-12-06 17:57
These are limitations of webpack, unfortunately. The styles get loaded in the JavaScript bundle by Webpack and injected in the header.

I'm going to close this working as intended. It's unfortunate but this won't be fixed for the final version, and you'll need to loosen the restrictions for CSP. 

We will revisit this when we start working on the next version of the CLI.

**Closed by hansl** 2016-12-06 17:57 UTC

**Comment by MatthiasDebaere** [comment] 2017-02-22 12:09
+1

**Comment by xnnkmd** [comment] 2017-05-19 12:08
@hansl It would be wonderful if we could create secure apps with angular cli. Which version do you think could address this?

**Comment by raDiesle** [comment] 2017-06-26 08:01
+1

**Comment by rajatkhanna82** [comment] 2017-06-26 23:00
+1

**Comment by Nimesko** [comment] 2017-07-03 13:47
If you use 'nonce' or run a task (gulp or grunt) that calculates the SHA of the script, it is a way to solve this problem. However, there is another similar problem: blocking the 'eval'. This one does not have artifacts similar to 'inline-script'

**Comment by saulshanabrook** [comment] 2017-07-03 14:35
I just opened a new issue for the latest version of Angular CLI to allow it to build without eval and Function: https://github.com/angular/angular-cli/issues/6872

**Comment by manuchadha1979** [comment] 2018-03-19 07:10
I suppose the issue is still open. Is it expected to be resolved in next Angular release? For the moment, I am using unsafe-eval and unsafe-inline iin my CSP to make the code work.

**Comment by clydin** [comment] 2018-03-19 16:13
`unsafe-eval` is no longer required if using a production build (with the reflect polyfills removed as they are only needed for JIT).  

`unsafe-inline` is still required for styles.  If that's not acceptable for the project's requirements, the other option is to only use global styles in the application and to not use any Angular libraries which contain component styles.  Note that the project will lose full benefits of the component-based architecture under this scenario.

**Comment by codemasterover9000** [comment] 2018-04-06 13:05
For a project of ours, we'll need to mitigate all unsafe-inlines as well. Will this be possible in a future angular release?

**Comment by PJTewkesbury** [comment] 2018-05-23 14:54
Hi, Is there any update on this issue, or are we left with no CSP for the time being?

**Comment by pmulac** [comment] 2018-08-06 14:42
@clydin Is it not possible to output all possible inline styles into a single css file so that 'unsafe-inline' can be removed? Many organizations (especially enterprise) require no 'unsafe-inline', and using only global styles is not a good option (it goes against Angular philosophy/project structure/workflow).  Frankly, if that's the only option, I would drop Angular and choose a different framework for a web app.

I would hope the team is still considering this issue.

**Comment by clydin** [comment] 2018-08-22 14:59
@blowsie is there a reason you would need the hashes for the files?

A CSP configuration similar to the following should work for a new project with material.  This would of course need to be adjusted for a projects specific needs and requirements.
(broken into multiple lines for clarity)
```
default-src 'none';
script-src 'self';
style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
img-src 'self';
connect-src 'self';
font-src https://fonts.gstatic.com
```

**Comment by blowsie** [comment] 2018-08-22 15:20
@clydin uses hashes prevents script execution of modified files, which could protect in many scenarios, including public machines. 

Without hashing with the script could be modified and and you could be none the wiser.

**Comment by clydin** [comment] 2018-08-22 15:27
That is Subresource Integrity ([SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)) not CSP.  This is already supported within the CLI by using the `subresourceIntegrity` option.

It is generally used when files are stored by a third-party and authenticity is required.  Generally if the files are self hosted and HTTPS is used, an attacker would need access to the server.  And in which case they could also modify the hashes as well.  However, as an extra layer of protection, it doesn't have much downside.

**Comment by lhj42** [comment] 2018-09-17 08:42
@clydin Any chance we could get that extra layer of protection so that we can also avoid using unsafe-inline for styles?

**Comment by mcm-ham** [comment] 2018-09-27 01:05
Webpack does support generation of nonce for inline tags, can't this be supported in AngularCLI? https://github.com/webpack/webpack/pull/3210

**Comment by mcm-ham** [comment] 2018-09-27 03:37
Added https://github.com/angular/angular-cli/issues/12378 for request to add nonce support that would address this issue.
