### ISSUE TITLE
ng g interceptor ? 

### ISSUE THREAD

**Issue by acharyaks90** [angular/angular-cli#11475] opened 2018-07-06 05:20 UTC
###  Feature Request (mark with an `x`)
```
- [  `x` ] feature request  ng g interceptor 
```

### Area
```
-[ ] generator for interceptor
```

**Comment by skanygin** [comment] 2018-09-11 09:52
Should be close as duplicate of https://github.com/angular/angular-cli/issues/6937.

**Comment by alan-agius4** [comment] 2018-10-29 11:33
Duplicate of #6937

**Closed** 2018-10-29 11:33 UTC
Labels: comp: schematics/angular, type: feature
