### ISSUE TITLE
Component decorators doesn't work in production mode

### ISSUE THREAD

**Issue by d3n1el1** [angular/angular-cli#21668] opened 2021-08-27 14:49 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

No

### Description

We have been working on a custom component decorator (the default Angular @Component decorator is still in use, along with our custom one).

Minimal reproduction of the bug:
**Custom Decorator:** 
```
export function CustomComponent(componentId: string): any {
  return (component: any): any => {
    console.log(componentId, component); // <--- Won't be executed at all
    return component;
  };
}
```

**Test Component**
```
import { Component} from '@angular/core';

@CustomComponent('testComponent')
@Component({
  selector: 'app-test',
  template: ''
})
export class TestComponent {
}
```

How to make the decorator work:
Set the flag `optimization: false` in angular.json
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "test": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/test",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json"
          },
          "configurations": {
            "production": {
              "optimization": false <-- if set to true, custom decorator doesn't work
            }
          },
          "defaultConfiguration": "production"
        }
      }
    }
  },
  "defaultProject": "test"
}

```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.3 and 10.2.3
Node: 14.15.3
Package Manager: npm 6.14.9
OS: Windows 10 LTSC x64


{
  "name": "test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "prod": "ng serve --prod",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.3",
    "@angular/cli": "~12.2.3",
    "@angular/compiler-cli": "~12.2.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.3.5"
  }
}
```
```


### Anything else?

_No response_

**Comment by d3n1el1** [comment] 2021-08-31 08:37
@JoostK your solution was the best so far, but we are looking for a more generic solution.

Do you know if this excluding of components in compile-time, can be done with custom Webpack config?

**Comment by alan-agius4** [comment] 2021-09-01 09:49
> So, to sum up. Even though the AOT is always ON, the flag optimization: true/false makes the removal of the code. If the flag optimization is false, the bundle will be big as in JIT, but just compiled already?

The size should be similar although JIT should be slightly bigger.

> Do you know if this excluding of components in compile-time, can be done with custom Webpack config?
You can potentially add a custom transformer that mark certain component as "used" although this is not as trivial as the example shown by @JoostK above. Personally I would not suggest you to go down that route. Also, be aware that custom webpack configurations are not supported by the Angular team.

Closing since this is working as intended.

**Closed by alan-agius4** 2021-09-01 09:49 UTC
