### ISSUE TITLE
ng init creates a styles.css  

### ISSUE THREAD

**Issue by BenjaminHofstetter** [angular/angular-cli#2959] opened 2016-10-31 11:00 UTC
### OS?
Mac OSX  El Capitan

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: darwin x64

### Repro steps.
this is an angular cli project

### The log given by the failure.
-

I did an update of angular cli

```
rm -rf node_modules dist tmp
npm install --save-dev angular-cli@latest
npm install
ng init
```

I am using a src/styles.scss instead of a src/styles.css. 'ng init' creates a new src/styles.css file. And I have to remove it manually every time I do an angular cli update.

Is it possible to check the app.styles array in angular-cli.json to avoid the creation of the src/styles.css during 'ng init'?

**Comment by Meligy** [comment] 2016-10-31 12:13
Did you tell it **not** to override `angular-cli.json`?

If yes, then it can be considered a bug.

It's probably by design though. I expect that it doesn't respect `angular-cli.json` because it generates it!

I always run `ng init --style=scss --routing` when I'm upgrading Angular CLI. I even made it an NPM script, called it `reset`.

**Comment by BenjaminHofstetter** [comment] 2016-10-31 13:08
I told it **not** to override angular-cli.json.

**Comment by filipesilva** [comment] 2016-11-03 17:31
It's a bug. We don't ready the current `angular-cli.json` when doing `init`.

**Comment by sumitarora** [comment] 2017-05-11 15:21
Closing as obsolete `ng init` is no longer available command.

**Closed by sumitarora** 2017-05-11 15:21 UTC
Labels: priority: 3 (nice to have), type: bug
