### ISSUE TITLE
MergeStrategy seems to be completely broken (mergeWith failure)

### ISSUE THREAD

**Issue by william-lohan** [angular/angular-cli#11337] opened 2018-06-21 16:33 UTC
Re-post of https://github.com/angular/devkit/issues/745

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
Node v8.11.1
NPM 5.8.0
Mac OS High Sierra

### Repro steps
Use the following schematic
```ts
import { Rule, url, apply, mergeWith, chain, MergeStrategy } from '@angular-devkit/schematics';

export function index(): Rule {
  return chain([
    simpleMerge(),
  ]);
}

function simpleMerge(): Rule {

  const source = url('./files');

  return mergeWith(source, MergeStrategy.Overwrite);
}
```

### The log given by the failure
>schematics .:boilerplate
>
>ERROR! /src/app/app.component.html already exists.
>ERROR! /src/app/app.component.spec.ts already exists.
>ERROR! /src/app/app.component.ts already exists.
>ERROR! /src/app/app.module.ts already exists.
>ERROR! /src/assets/.gitkeep already exists.
>ERROR! /src/environments/environment.prod.ts already exists.
>ERROR! /src/environments/environment.ts already exists.
>ERROR! /src/index.html already exists.

### Desired functionality
All files should be overwritten.

### Mention any other details that might be useful
I tried every MergeStrategy possible (AllowOverwriteConflict, etc.), same result.

https://github.com/angular/devkit/issues/745
https://stackoverflow.com/questions/48957132/how-to-overwrite-file-with-angular-schematics

**Comment by clydin** [comment] 2018-06-21 16:51
Could you provide the versions used?

I cannot answer with certainty without knowing the versions but this PR (https://github.com/angular/angular-cli/pull/11274) will most likely correct the behavior.

**Comment by gatimus** [comment] 2018-06-21 23:48
version 0.6.8

dup repo https://github.com/gatimus/schematics-merge-strategy

**Comment by hansl** [comment] 2018-07-19 17:34
Could you try with the RC of 0.7? I fixed a lot of issues by reworking the whole Tree implementation, should have fixed a few of those merging issues (amongst others, e.g. branching).

**Comment by hansl** [comment] 2018-07-19 17:35
Dupe of https://github.com/angular/angular-cli/issues/11246. Let's keep this one for tracking though as it has more information.

**Comment by cgatian** [comment] 2018-08-02 21:09
This is making me cry 😢

**Comment by joeson1** [comment] 2018-08-10 14:08
Is this already fixed?
I have following workaround:
```
const templateSource = apply(url('./project-files'), [
      template({ ...strings, ...options }),
      move(options.path),
      forEach((fileEntry: FileEntry) => {
        if (host.exists(fileEntry.path)) {
          host.overwrite(fileEntry.path, fileEntry.content);
        }
```
        return fileEntry;
      }),
    ]);

**Comment by tinesoft** [comment] 2018-08-12 15:30
Hi,

For me, the issue appears after upgrading my schematics "dependencies" from:
```
 {
    "@angular-devkit/core": "^0.6.8",
    "@angular-devkit/schematics": "^0.6.8",
    "typescript": "^2.5.1"
  },
```

to:
```
 {
    "@angular-devkit/core": "^0.7.3",
    "@angular-devkit/schematics": "^0.7.3",
    "typescript": "^2.9.0"
  },
```

Version v0.6.8's `mergeWith`  was working fine...

@joeson1 : i tried your workaround, but it didn't help 😞 ...

**Comment by gatimus** [comment] 2018-08-13 15:08
@joeson1 where do you assign `host`?

**Comment by gatimus** [comment] 2018-08-13 15:09
@tinesoft I get the exact same behavior with v0.6.8 as with v0.7.3

**Comment by egervari** [comment] 2018-10-22 12:46
I'm still having this issue, in case someone needs to know it's still not fixed. Using version 0.8.6

**Comment by bautistaaa** [comment] 2018-10-28 20:53
I have the same issue, however if I run `schematics my-schematic:my-schematic` it will work BUT if I run `ng g my-schematic:my-schematic` it will give me the `already exists` error message. Can anyone explain why?

**Comment by cgatian** [comment] 2018-11-09 16:50
@egervari and @bautistaaa could you let me know if this workaround works for you? 

https://stackoverflow.com/a/53230034/684869

**Comment by denisoby** [comment] 2019-02-04 17:07
@mattezell Thank you for workaround example. However, I'd assume that you don't need this "move('.')" - everything should work even w/o it.

**Comment by matheo** [comment] 2019-02-11 00:42
I have the same problem not using a Source but trying to create/override custom stuff in the Tree. There's no simple way via MergeStrategy to avoid the `exists` check?

My hacky intuition thought that using `tree.overwrite` with `MergeStrategy.AllowOverwriteConflict` would default to `create` the files I'm trying to overwrite. Or `create` with `AllowCreationConflict` would overwrite, something like that would be useful.

**Comment by shusson** [comment] 2019-02-11 13:57
> There's no simple way via MergeStrategy to avoid the `exists` check?

I believe this is exactly what `MergeStrategy.Overwrite` is suppose to do.

**Comment by GregOnNet** [comment] 2019-03-15 16:19
Hi,

I experience the same issue.
I setup a minimal reproduction: https://github.com/GregOnNet/merge-strategie-issue

### Setup

- The repository contains a file `.prettierrc`
- My schematic `overwrite` loads another `.prettierrc` from `./templates`
- `MergeStrategy.Overwrite` is configured as 2nd parameter of `apply`.
- The repository contains a unit test to check if the template overwrites the origin file.

### Observed behaviour

- The unit test succeeds
- The integration test using `schematics` fails
  > Please refer to section `Repro Steps` to see the details.

## Versions

```
Node v11.11.0
NPM 6.9.0
Mac MacOS Mojave 10.14.3

@angular-devkit/core: 7.3.6
@angular-devkit/schematics: 7.3.6
```

## Repro Steps

```bash
git clone https://github.com/GregOnNet/merge-strategie-issue.git
cd merge-strategie-issue

npm install
npm test # Everything is fine
npm run build

schematics .:overwrite
# ERROR
ERROR! /.prettierrc already exists.
The Schematic workflow failed. See above.
```

If I can provide any further information, please let me know. 👍

**Comment by tscislo** [comment] 2019-07-30 18:05
Is there any plan to fix this? Any current workarounds?

**Comment by william-lohan** [comment] 2019-07-30 18:40
@tscislo this is my current workaround:

```ts
export function overwriteIfExists(host: Tree): Rule {
  return forEach(fileEntry => {
    if (host.exists(fileEntry.path)) {
      host.overwrite(fileEntry.path, fileEntry.content);
      return null;
    }
    return fileEntry;
  });
}

export function mySchematic(options: MyOptions): Rule {
  return (host: Tree, context: SchematicContext) => {
    /* ...logic... */
    const templateSource = apply(
      url('./files'),
      [
        template({
          ...strings,
          ...options
        }),
        move(options.path),
        options.overwrite ? overwriteIfExists(host) : noop()
      ]
    );

    return mergeWith(templateSource);
  };
}
```

Also other variations in answers her https://stackoverflow.com/questions/48957132/how-to-overwrite-file-with-angular-schematics

**Comment by gund** [comment] 2019-10-30 22:01
For me even workarounds did not work.
When I apply them - changes are simply ignored and I get message `Nothing to be done.`...

**Comment by myin142** [comment] 2020-07-22 17:39
A note about the workaround using manual forEach and overwrite.
Make sure that you put the `forEach` before the `move` since the file paths that you get are relative to the root project. And also make sure that you create the files first before trying to overwrite them. (e.g calling `externalSchematic` first).Took me a while to notice that.

**Closed** 2021-01-28 08:34 UTC
Labels: comp: devkit/schematics, freq1: low, severity3: broken, triage #1, type: bug/fix
