### ISSUE TITLE
Locally installed CLI beta.31 is not initializing the project ('ng init' failed)

### ISSUE THREAD

**Issue by kuncevic** [angular/angular-cli#4761] opened 2017-02-16 23:39 UTC
As per this pull request https://github.com/angular/angular-cli/commit/761e86f2224c718f62dcc100059096d5752c0726 CLI should be able to run without global install. 
There was no issues with that until beta.31

### OS?
Windows 7

### Versions.
My project local CLI, `npm run ng -- -v`:
```
@angular/cli: 1.0.0-beta.31
node: 6.9.2
os: win32 x64
@angular/cli: 1.0.0-beta.31
```

### Repro steps.

- `npm init -y`
- alter `package.json` by adding `"ng":"ng"` in to scripts (https://github.com/angular/angular-cli/commit/761e86f2224c718f62dcc100059096d5752c0726).
- `install @angular/cli --save`
- `npm run ng -- init`

### The log given by the failure.
```
c:\Projects\my-app>npm run ng -- init

> my-app@1.0.0 ng c:\Projects\my-app
> ng "init"

installing ng2
? Overwrite package.json? Yes, overwrite

c:\Projects\my-app>

```

### Expected

```
installing ng2
? Overwrite package.json? Yes, overwrite
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.json
  create angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.json
  create .gitignore
  create karma.conf.js
  overwrite package.json
  create protractor.conf.js
  create tslint.json
Successfully initialized git.
Installing packages for tooling via npm.
```

### Mention any other details that might be useful.
Working with locally installed beta.30 and below.

p.s:
Also I tried to run `npm run ng -- update` as per this PR https://github.com/angular/angular-cli/commit/2211172 but having exactly same thing happening.

**Comment by Meligy** [comment] 2017-02-17 00:01
Duplicate of https://github.com/angular/angular-cli/issues/4653 / https://github.com/angular/angular-cli/issues/4584.

**Comment by kuncevic** [comment] 2017-02-17 00:10
@Meligy Yeah i c, in my case I am initializing just fresh project having `package.json` like that:
```
{
  "name": "my-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "ng": "ng"
  },
}
```
If it is makes any difference

**Comment by Meligy** [comment] 2017-02-17 01:53
I'm afraid it doesn't matter. The command was broken in beta.31, and now it's removed in master. It won't be there in v1.0 final, and will not exist again until it's rewritten for v2.0.

**Comment by kuncevic** [comment] 2017-02-17 03:40
So i c that PR https://github.com/angular/angular-cli/pull/4628 that removing `init` and `update`.
But how would you initialize a new CLI app without having CLI globally installed? It is seams to be impossible now.

**Comment by Meligy** [comment] 2017-02-17 09:43
At the moment you'll have to download the CLI to another folder different from the new project folder and use it.

At least until something happens with https://github.com/angular/angular-cli/issues/4762 and it gets opened / superseded with something.

**Closed** 2017-02-17 11:38 UTC
