### ISSUE TITLE
Help no longer works for generate command

### ISSUE THREAD

**Issue by smokerbag** [angular/angular-cli#9492] opened 2018-02-02 17:57 UTC
### Versions
```
Angular CLI: 1.6.7
Node: 9.5.0
OS: linux x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

* Create a new cli project, for this I just did a `ng new cli`
* Run help for generate command `ng help generate` or `ng generate --help`
* Fails with an error and stacktrace

### Observed behavior
```
Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at Class.getCollectionName (/home/scott/cli/node_modules/@angular/cli/commands/generate.js:57:36)
    at Class.printDetailedHelp (/home/scott/cli/node_modules/@angular/cli/commands/generate.js:179:37)
    at commandFiles.forEach.cmd (/home/scott/cli/node_modules/@angular/cli/commands/help.js:57:38)
    at Array.forEach (<anonymous>)
    at Class.run (/home/scott/cli/node_modules/@angular/cli/commands/help.js:36:22)
    at resolve (/home/scott/cli/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (/home/scott/cli/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at CLI.callHelp (/home/scott/cli/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:222:17)
    at Promise.resolve.then.then.then.then.result (/home/scott/cli/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:156:23)
```

### Desired behavior

Should work

### Mention any other details that might be useful (optional)

This worked fine in 1.6.5. I updated 1.6.7 and it stopped.

**Comment by clydin** [comment] 2018-02-02 18:37
Duplicate of https://github.com/angular/angular-cli/issues/9412.

**Closed by clydin** 2018-02-02 18:37 UTC
