### ISSUE TITLE
ng test options mentioned in testing docs don't work

### ISSUE THREAD

**Issue by bartvanderwal** [angular/angular-cli#13137] opened 2018-12-05 14:40 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality/Repro/other details that might be useful
I would like to be able to follow the testing guide when using the new angular 7:
https://angular.io/guide/testing#configure-cli-for-ci-testing-in-chrome

But similar to as mentioned in now closed issue #11582 these docs on testing at angular.io still mention/instruct the public to use the `--browser option` instead of the new `--browsers`. And also the --single-run option, which I understand should now be `--watch=false`

So this instruction:
>`ng test --single-run --no-progress --browser=ChromeHeadlessCI`

Should now be:
>`ng test --watch=false --no-progress --browsers=ChromeHeadlessCI`

The next line in the docs source mentions also returns two now missing cli options in the current ng cli 7.0.7 that I'm using:
>`ng e2e --no-progress --config=protractor-ci.conf.js`

returns:
`Unknown option: '--no-progress'`
`Unknown option: '--config'`

Can you fix the docs or the CLI to be consistent. And as workaround perhaps specify alternative for the last two options of `ng test`.

**Comment by alan-agius4** [comment] 2018-12-05 14:43
Duplicate of https://github.com/angular/angular/issues/27331

**Closed by alan-agius4** 2018-12-05 14:43 UTC
