### ISSUE TITLE
Feature Request: option to generate folder if missing

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#4014] opened 2017-01-14 21:25 UTC
I believe it would be helpful to generate a folder, if it doesn't exist. For example:

```
ng g c models/person
```

... this will generate a class named person in the `models` folder only if that folder exists. This often forces the user to perform `mkdir models` first.

This is a minor feature request, but one that I think will be helpful in many cases.

**Comment by hansl** [comment] 2017-01-14 22:06
https://github.com/angular/angular-cli/pull/3912 will make the parent dir all the time.

**Comment by hansl** [comment] 2017-01-14 22:06
Also dupe of https://github.com/angular/angular-cli/issues/3307 (although title is misleading)

**Closed by hansl** 2017-01-14 22:06 UTC

**Comment by johnpapa** [comment] 2017-01-15 18:01
ah, thanks for the cross link
