### ISSUE TITLE
Angualr -CLI -ERROR 

### ISSUE THREAD

**Issue by adhivenkatesh** [angular/angular-cli#18211] opened 2020-07-10 13:18 UTC
Hi Guys,

The error is is coming please help to come out

npm uninstall -g @angular/cli@latest
npm install -g @angular/cli@latest

But still the error is coming 

THE ERROR PART IS HERE  after running ng serve --o
This version of CLI is only compatible with Angular versions 0.0.0 || ^9.0.0-beta || >=9.0.0 <10.0.0,
but Angular version 10.0.3 was found instead.

Please visit the link below to find instructions on how to update Angular.
https://update.angular.io/

--------------------------
Angular CLI: 9.1.11
Node: 12.14.0
OS: win32 x64

Angular: 10.0.3
... common, compiler, compiler-cli, core, forms, localize
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.2
@angular-devkit/build-angular     0.1000.2
@angular-devkit/build-optimizer   0.1000.2
@angular-devkit/build-webpack     0.1000.2
@angular-devkit/core              10.0.2
@angular-devkit/schematics        9.1.11
@angular/cli                      9.1.11
@ngtools/webpack                  1.10.2
@schematics/angular               9.1.11
@schematics/update                0.901.11
rxjs                              6.6.0
typescript                        3.9.6
webpack                           4.43.0

PS D:\ANGULAR-PROJECTS\ECG-Angular2-TypeScript-master\ECG-Angular2-TypeScript-master> ng serve --o

**Comment by daniloff200** [comment] 2020-07-10 13:25
Hi @adhivenkatesh 
That error already mentioned in https://github.com/angular/angular-cli/issues/18207 ,  and you can find info about there too, so, you just need to wait, until version tag issue will be resolved

**Comment by alan-agius4** [comment] 2020-07-10 13:57
Duplicate of https://github.com/angular/angular-cli/issues/18207

**Closed by alan-agius4** 2020-07-10 13:57 UTC
