### ISSUE TITLE
Support different UT frameworks other than Jasmine/Karma

### ISSUE THREAD

**Issue by mcosta74** [angular/angular-cli#13458] opened 2019-01-17 12:07 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality
Would be nice if would be possible to select which unit test framework will be used in the project. Many developers use for instance `Jest` also for Angular applications.
The proposal is to add a flag (for instance `--ut`) to the `new` command to allow to select the tool to use.
This implies to:
* change the schematic for configuration files
* change schematic for `generate` command

### Mention any other details that might be useful
I followed this [article](https://www.xfive.co/blog/testing-angular-faster-jest/)

**Comment by alan-agius4** [comment] 2019-01-17 12:48
Duplicate of https://github.com/angular/angular-cli/issues/4543

**Closed by alan-agius4** 2019-01-17 12:48 UTC
