### ISSUE TITLE
Angular-cli + angular universal

### ISSUE THREAD

**Issue by vforv** [angular/angular-cli#3524] opened 2016-12-12 11:11 UTC
Could you please consider option about adding angular universal to angular cli?
Problem is that we can build angular app now but that apps cannot be crawled by google bots.

**Comment by filipesilva** [comment] 2016-12-12 13:57
Dupe of https://github.com/angular/angular-cli/issues/1050, and related to https://github.com/angular/angular-cli/issues/3013

**Closed by filipesilva** 2016-12-12 13:57 UTC
