### ISSUE TITLE
ng test never exits karma when singleRun=true

### ISSUE THREAD

**Issue by pblasco** [angular/angular-cli#3329] opened 2016-11-30 21:02 UTC
### OS?
OSX El Capitan (10.11.6)

### Versions.
angular-cli: 1.0.0-beta.20-3
node: 6.9.1
os: darwin x64

### Repro steps.
Generate a new application using the cli
change singleRun=true in the karma.conf.js
run ng test

After running successfully, the process will hang and never complete.
I reproduced this locally and also on my CI server using bitbucket pipelines

### Mention any other details that might be useful.
Changing the angular-cli version to 1.0.0.beta19-3 in package.json fixes this problem, and the karma process exits immediately on successful testing.  It seems to be introduced in beta20

**Comment by sreenivasulun** [comment] 2016-12-01 01:51
I also got the same issue. Then I am able to over come with "ng test --single-run".

Are you able to generate coverage report? for me coverage report generation is not working.

**Comment by tushar-chauhan** [comment] 2016-12-01 15:45
@pblasco I also verified this.

**OS?**
macOS Sierra 10.12.1 (16B2657)

**Versions.**
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: darwin x64

**Repro steps.**

Generate a new application using the cli
change `singleRun=true` in the karma.conf.js
run `ng test`

Moreover, I had another observation.
If you set `autoWatch: false` with `singleRun=true`, it doesn't even run the test cases.
The process hangs in both the cases and never completes.

It will be helpful if someone can verify the second scenario too.

**Comment by tushar-chauhan** [comment] 2016-12-01 15:50
@sreenivasulun Your suggestion works fine to get single-run work as usual.

code coverage and lint were made optional in angular-cli version [1.0.0-beta.19](https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#100-beta19-2016-10-28)

To get everything(single-run, code coverage report and linting) working as before, one can still use:
```
ng test --single-run --lint --code-coverage
```

**Comment by filipesilva** [comment] 2016-12-30 13:39
Dupe of https://github.com/angular/angular-cli/issues/3554. This one was opened before, but I ended up replying to the other one first with some details about the cause.

**Closed by filipesilva** 2016-12-30 13:39 UTC
