### ISSUE TITLE
MigrationStrategy error

### ISSUE THREAD

**Issue by jonbcampos** [angular/angular-cli#11246] opened 2018-06-14 19:40 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [X] schematics
```

### Versions

node: v9.10.1
npm: 6.1.0

### Repro steps
get this repo: https://github.com/jonbcampos/simple-schematics-error
commands:
ng new test
cd test
// add local repo to project, npm link for local dev, etc
ng g simple:simple
- alternative -
ng g simple:simple --overwrite=true

### The log given by the failure
both cmds fail with the following error
ERROR! src/app/app.component.html already exists.
The Schematic workflow failed. See above.

### Desired functionality
honors mergestrategy request

### Mention any other details that might be useful
if I run test (`npm test`) the tests pass but when I run the code the code fails. I can manually delete files but this also fails if I embed another schematic. I can create that test too shortly.

**Comment by hansl** [comment] 2018-07-19 17:32
Please report the version next time.

Could you try with the latest RC.3 ?  I am pretty sure we fixed this a bit ago but it was introducing changes to the API so we did this in Schematics 0.7.

**Comment by hansl** [comment] 2018-07-19 17:35
This is a duplicate of https://github.com/angular/angular-cli/issues/11337. Closing this issue as there's more information in the other one.

**Closed by hansl** 2018-07-19 17:35 UTC
Labels: comp: devkit/schematics, need: more info, type: bug
