### ISSUE TITLE
cli commands (`add`, `update`) remove empty lines from `package.json`

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12092] opened 2018-09-04 22:59 UTC
_From @gkalpak on May 18, 2018 11:11_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [x] schematics
```

### Versions
All

### Repro steps
Some commands that modify `package.json` (e.g. `ng update ...` or `ng add @angulatr/pwa` (probably other `ng add` commands as well), remove an extra empty lines at the end of the file.

### Desired functionality
Modifications in `package.json` should preserve empty lines. (Ideally, all whitespace should be preserved.)
Having an empty line at the end of each file is a common convention and removing such lines creates unnecessary noise in diffs. (Also note that other tools (e.g. `yarn install`) tend to add them back, which creates more unnecessary noise :grin:)

_Copied from original issue: angular/devkit#940_

**Comment by alan-agius4** [comment] 2018-10-30 14:31
Duplicate of #11744

**Closed by alan-agius4** 2018-10-30 14:31 UTC
Labels: comp: devkit/schematics, type: bug/fix
