### ISSUE TITLE
File with only interfaces shows warning "part of the TypeScript compilation but it's unused"

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#16025] opened 2019-11-01 21:27 UTC
This issue impacts 9.0.0-rc.0 and happened while updating https://github.com/SAP/cloud-commerce-spartacus-storefront.

After updating to version 9, serving the project shows a warning:

```
kamik@RED-X1C6 MINGW64 /d/sandbox/cloud-commerce-spartacus-storefront (update-9)
$ yarn start
yarn run v1.17.3
$ ng serve --proxy-config mock-server/proxy.backend.js
10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 4.99 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 222 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.7 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.67 MB [initial] [rendered]
Date: 2019-11-01T18:12:29.381Z - Hash: f2699ec64930156b5cb5 - Time: 31495ms

WARNING in D:/sandbox/cloud-commerce-spartacus-storefront/projects/storefrontlib/src/feature-toggles.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Compiled with warnings.
```

The referenced file is included in the compilation, but is composed entirely of interfaces:
```
export interface FeatureToggles {
  features?: {
    /**
     * Configure feature level.
     * Value corresponds to minor (feature) release version number: '1.0', '1.1', etc.
     * Each subsequent level contains all of the features from previous one.
     */
    level?: string;
    consignmentTracking?: boolean;
    anonymousConsents?: boolean;
  };
}
```
Since interfaces have no runtime representation, this file gets a warning about not being used.

**Comment by alan-agius4** [comment] 2019-11-03 13:17
Duplicate of https://github.com/angular/angular-cli/issues/16025

**Comment by alan-agius4** [comment] 2019-11-03 13:18
Duplicate of https://github.com/angular/angular-cli/issues/15626

**Closed by alan-agius4** 2019-11-03 13:17 UTC
Labels: comp: devkit/build-angular, freq1: low, severity1: confusing, type: bug/fix
