### ISSUE TITLE
ng new project1 -sg : No folder is created 

### ISSUE THREAD

**Issue by rajegit** [angular/angular-cli#1065] opened 2016-06-11 14:46 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu - 15.0

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

angular-cli: 0.1.0
node: 5.5.0
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
did ng new project1 -sg . Everything worked but no folder was created. 

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by rajegit** [comment] 2016-06-11 16:12
Am I looking at wrong place , there was not error nor anything abnormal .

**Comment by aciccarello** [comment] 2016-06-15 12:50
Good to hear things worked correctly. You can probably close this issue for the CLI team now.

**Comment by filipesilva** [comment] 2016-06-17 00:43
This seems to be a dupe of https://github.com/angular/angular-cli/issues/884. If not, please tell me so I can reopen the issue.

**Closed by filipesilva** 2016-06-17 00:43 UTC
