### ISSUE TITLE
3th party lib hammer keep referring to .map files when made production build

### ISSUE THREAD

**Issue by stefanaerts** [angular/angular-cli#2713] opened 2016-10-14 19:14 UTC
> ## Please provide us with the following information:
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

mac osx
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
> angular-cli: 1.0.0-beta.16  
> node: 6.5.0  
> os: darwin x64  
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
> yes
### The log given by the failure.

> Normally this include a stack trace and some more information.

![image](https://cloud.githubusercontent.com/assets/3684599/19399598/a112a444-9252-11e6-8640-a9c50e3ba1bc.png)
### Mention any other details that might be useful.

When i do ng build --target=production --environment=prod   

it keeps generating a reference to js.map file for hammer
![image](https://cloud.githubusercontent.com/assets/3684599/19399652/db8e283c-9252-11e6-9785-735ac627ea79.png)

Then when i do a refresh or redirect in the url i get this message:
Failed to parse SourceMap: https://ethnicfoods-b928a.firebaseapp.com/hammer.min.js.map

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-10-17 16:31
Fixed in https://github.com/angular/angular-cli/pull/2519 I believe. If you still have the same problem with the next release, let me know and I'll reopen.

**Comment by stefanaerts** [comment] 2016-10-17 18:23
I updated to cli 1.0.0-beta.17
But i stil see the sourcemapping .
So to be sure, am I right that there should not be a reference to a map
file of hammer when i made this build ?
ng build --target=production --environment=prod

[image: Inline image 1]

**Comment by stefanaerts** [comment] 2016-10-17 18:26
this is in my angular-cli.json file:
[image: Inline image 1]

**Comment by stefanaerts** [comment] 2016-10-17 18:38
What does this mean? declaration in unreachable code should be dropped?
[image: Inline image 1]

**Comment by filipesilva** [comment] 2016-10-17 23:40
Since #2519 didn't fix it for you I'll reopen.

Can you give me exact repro steps to get this behaviour? If I start with a brand new CLI app, what do I need to do to see it?

Your last three comments should have images I think, but none appeared here.

**Comment by stefanaerts** [comment] 2016-10-18 07:35
1)I install hammerjs, so i have a folder node_modules/hammerjs
2) i add to angular-cli.json   the following configuration:
   "scripts": [
"../node_modules/hammerjs/hammer.min.js"
      ],

3) ng build --target=production --environment=prod

4) So now there is a dist folder:
   This is the content of the folder:
[image: Inline image 1]

Do you see the picture above this line?

So as you can see there is a
-inline.js
- main.<uniquenumber>.bundle.js
- main.<uniquenumber>.bundle.js.gz
- scripts.<uniquenumber>.bundle.js
- scripts.<uniquenumber>.bundle.js.gz
-styles.<uniquenumber>.bundle.js
-styles.<uniquenumber>.bundle.js.gz

5) So as there are no js.map files in dist folder i would expect that for
hammerjs there is no reference anymore to a js.map file in the generated
scripts.<uniquenumber.bundle.js file.

But as you can see in thsi picture below this line there is line in the
file that contains:
(window,document,"Hammer");\n//# sourceMappingURL=hammer.min.js.map

[image: Inline image 2]


6) So when I deploy this to firebase and i open the application(firebase
url) in my browser i get in the console the message
Failed to parse SourceMap : https://<someurl>.
firebaseapp.com/hammer.min.js.map

[image: image]
<https://cloud.githubusercontent.com/assets/3684599/19399598/a112a444-9252-11e6-8640-a9c50e3ba1bc.png>
So i guess the angular-cli/webpack chaking/minify/whatever stuff is not
working correctly for the 3th party hammerjs minified js file ?

Maybe its because its already minified?

Kind Regards,
Stefan.

**Comment by devCrossNet** [comment] 2016-10-19 16:06
@stefanaerts I solved it by referencing the non-minified version of hammer.

**Comment by stefanaerts** [comment] 2016-10-19 16:28
@devCrossNet 
As i expected, thanks for verifying.
@filipesilva So this means we should not include minified files in the angular-cli.json configuration file? 
I also added this line to styles.css
"@import '~@angular/material/core/theming/prebuilt/deeppurple-amber.css';"

Thats also gave a reference to a .map file in the dist/styles.<uniquenumber>.bundle.js
![image](https://cloud.githubusercontent.com/assets/3684599/19527781/a523a08a-9629-11e6-91c5-0b8eabb288f6.png)

**Comment by filipesilva** [comment] 2016-10-23 17:59
@stefanaerts you should be able to use both minified and un-minified versions in the scripts/styles array. I think this is a bug in how we process those files. Will look into it.

**Comment by mgechev** [comment] 2018-12-17 19:13
@stefanaerts would you verify if you hit the issue with the latest CLI? If you do, would you share a minimal example on GitHub so we can reproduce it locally?

**Comment by mgechev** [comment] 2018-12-21 22:00
Closing the issue due to inactivity. If the problem still exists in the latest version of the CLI, please open a new issue following the template and providing a minimal demo where we can reproduce it. Thanks! :-)

**Closed by mgechev** 2018-12-21 22:00 UTC
Labels: comp: devkit/build-angular, freq1: low, severity1: confusing, type: bug/fix
