### ISSUE TITLE
hash and deploy-url for media

### ISSUE THREAD

**Issue by zh99998** [angular/angular-cli#15374] opened 2019-08-19 13:23 UTC
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...
now only scripts and media referenced by stylesheets can be hashed.
media in component html like `<img src="...">` can't be hashed, both it in or not in `assets` folder.
deploy-url not affect them too.

which is harder to read and may have trouble to deal with dynamic
### Describe the solution you'd like
 If you have a solution in mind, please describe it.
media referenced by html need to be hashed, just like them referenced by css.

in my deployment only index.html served from main domain and all other static files are from CDN. so hash and deploy-url support is important.

for backward compatibility, it could behind a build config.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment] 2019-08-19 13:41
Duplicate of https://github.com/angular/angular-cli/issues/3415

**Closed by alan-agius4** 2019-08-19 13:41 UTC
