### ISSUE TITLE
ng generate with --style=none

### ISSUE THREAD

**Issue by marko164** [angular/angular-cli#22911] opened 2022-03-29 20:22 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When running `ng generate component` with `--style=none`, created component has extra comma after templateUrl

## 🔬 Minimal Reproduction

<pre><code>ng generate component test-component --style=none</code></pre>

<pre><code>
import { Component, OnInit, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'test-component',
  templateUrl: './test-component.component.html',, <-------------
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TestComponentComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.3.0
Node: 16.13.1
Package Manager: npm 8.1.2
OS: linux x64

Angular: 13.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.0
@angular-devkit/build-angular   13.3.0
@angular-devkit/core            13.3.0
@angular-devkit/schematics      13.3.0
@schematics/angular             13.3.0
rxjs                            7.5.5
typescript                      4.6.3
</code></pre>

**Comment by alan-agius4** [comment] 2022-03-29 20:51
Duplicate of https://github.com/angular/angular-cli/issues/22857

**Closed by alan-agius4** 2022-03-29 20:51 UTC
