### ISSUE TITLE
CLI seems to ignore changes in code when changedetection sets in

### ISSUE THREAD

**Issue by Rockstaa** [angular/angular-cli#5704] opened 2017-03-28 07:29 UTC
**Bug Report or Feature Request** 

- [x] bug report
- [ ] feature request

**Versions**

@angular/cli: 1.0.0
node: 7.7.4
os: win32 x64 (Windows 8.1)
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/animations: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

**Repro steps.**

Upgraded our project to angular-cli@1.0.0 / angular@4.0.0 and run ng-serve made some code improvements and check them after the auto recompiling

**The log given by the failure.**

I'm starting my developement routine with starting the project with ng serve then I made some code improvements, then the auto re-compile / change detection sets in. It seems that the cli ignores them completly cause nothing happens, there are no changes that I made and no console logs. After ending ng serve and starting it new, all is fine and the changes and logs are available.

**Comment by Meligy** [comment] 2017-03-28 13:00
Can you reproduce this from an `ng new` project?

**Comment by Rockstaa** [comment] 2017-03-29 06:05
Thank you for your reply Meligy, yes I can reproduces this with a fresh **ng new** project, when i'm changing the title in the **app.component.ts** it seems that the compiler sometimes ignore the changes. Sometimes he show's the new App Title but most of the time it ignores the changes.  I added a video up on this post so you could see the problem. 

[ngnew-changedetection.zip](https://github.com/angular/angular-cli/files/877974/ngnew-changedetection.zip)

**Comment by teddymro** [comment] 2017-03-29 15:06
I happen to have the same problem while using Webstorm. On VS Code works ok... for the moment.

**Comment by Rockstaa** [comment] 2017-03-30 06:17
Thank you teddymro, I played around with webstorm and in **Settings** -> **Appearance & Behavior** -> **System Settings** is a Property called **Use** **"safe write" (save changes to a temporary file first"**. If this property is checked changes will temporarily be detected, if it's turned off all works fine for me.  Thank you for giving me this little hint for this solution. Maybe you can check this too.

**Comment by davido-valdor** [comment] 2017-04-26 14:45
I have the same problem using VIM.

**Comment by Rockstaa** [comment] 2017-04-27 06:48
I don't know much about VIM but, maybe there is an option like "safe write" in VIM too, to solve this problem?

**Comment by filipesilva** [comment] 2017-05-03 11:15
Dupe of https://github.com/angular/angular-cli/issues/5117

**Comment by filipesilva** [comment] 2017-05-03 11:15
There is a solution for Vim there as well.

**Closed by filipesilva** 2017-05-03 11:15 UTC
