### ISSUE TITLE
webpack import(`@angular/common/locales/${mylocale}`) not working

### ISSUE THREAD

**Issue by leon** [angular/angular-cli#22088] opened 2021-11-04 13:20 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

We load our locales dynamically using a dynamic import and `registerLocaleData`

this works in angular 12
```
const localeModule = await import(
  /* webpackInclude: /(sv|nb|da|fi|de|fr)/ */
  /* webpackChunkName: "locale" */
  `@angular/common/locales/${this.locale}.js`
)
registerLocaleData(localeModule.default)
```

# The Problem
I found the root cause and it's not a angular problem, but a webpack one
https://github.com/webpack/webpack/issues/13865

But I though someone else might get stuck on the same thing, so I would add it as a regression.

# Workaround
A workaround is to use a relative or absolute path to the node_modules folder instead

```
const localeModule = await import(
  /* webpackInclude: /(sv|nb|da|fi|de|fr).mjs$/ */
  /* webpackExports: "default" */
  /* webpackChunkName: "locale" */
  `node_modules/@angular/common/locales/${this.locale}`
)
registerLocaleData(localeModule.default)
```

### Please provide the exception or error you saw

```true
Module not found: Error: Package path ./locales is not exported from package /myrepo/node_modules/@angular/common (see exports field in /myrepo/node_modules/@angular/common/package.json)
```

**Comment by StanislavByzov** [comment] 2021-11-09 13:18
I'm facing the same issue

**Comment by StanislavByzov** [comment] 2021-11-09 18:57
This answer helped me https://github.com/highlightjs/highlight.js/issues/3223#issuecomment-953337602

**Comment by lmoralejo** [comment] 2021-11-11 13:11
> This answer helped me [highlightjs/highlight.js#3223 (comment)](https://github.com/highlightjs/highlight.js/issues/3223#issuecomment-953337602)

It helped me too.

**Comment by alan-agius4** [comment] 2021-11-12 11:55
It's important to point out that using Webpack specific features such as magic comments above are not supported by the Angular tooling team. The fact that the Angular CLI is using Webpack is an implementation detail which can change in the future.

**Comment by jcompagner** [comment] 2021-11-22 13:41
> This answer helped me [highlightjs/highlight.js#3223 (comment)](https://github.com/highlightjs/highlight.js/issues/3223#issuecomment-953337602)


this for me doesn't work...
if i do this:

            const module1 =  `@angular/common/locales/${localeId}.js`;
            import(module1).then(


then yes it compiles, but i got a warning:
 Warning: Critical dependency: the request of a dependency is an expression

and also the locale files are not generated (no output for the angular locales)

if i do this:

  import(`../../node_modules/@angular/common/locales/${localeId}.js`)

which other say you now should do, that also doesn't work because yes then the files are generated but the actual import at runtime doesn't work...


![image](https://user-images.githubusercontent.com/3274268/142871632-4e3bea3a-7bf0-4134-a900-23045c702714.png)


as you can see the import askes for "./nl.js" but the map doesn't have that there is a "./global/" in front of it. so it doesn't map and can't load it..

So how can i get this working? or is this just not possible right now and i need to postpone the angular 13 upgrade?

**Comment by jcompagner** [comment] 2021-11-22 14:08
Worked around that:

  import(`../../node_modules/@angular/common/locales/global/${localeId}.js`)

so i really need to take them directly from the global dir itself, then the "/global/" prefix is gone. 
and it maps it just fine.

**Comment by jcompagner** [comment] 2021-11-22 14:13
it seems that we blame a WebPack bug right?
But why is it that these 2 that i also use:

import(`numbro/languages/${localeId}`).
import(`@uppy/locales/lib/${localeId}.js`)

are still working like a charm?
no need to change any code for that?

**Comment by geo242** [comment] 2021-11-23 23:02
Here is what is currently working for me with v13. I use this in a library and I can verify that the consuming applications of this library are getting the appropriate locale files built. I only want certain locals included.

```
import(
  /* webpackInclude: /(en|es|id)\.mjs$/ */
  `/node_modules/@angular/common/locales/${locale}.mjs`
  ).then(module => {
  registerLocaleData(module.default);
});```

**Comment by adampasc** [comment] 2021-12-03 08:15
Is there any chance this will be fixed with one of the next releases? Our team also has to postpone angular13 migration due to this. None of the above workarounds seem to get the job done for us.

**Comment by alan-agius4** [comment] 2021-12-03 09:03
@adampasc, this issue is not caused by Angular, but rather it’s a Webpack bug. 

Please see: https://github.com/webpack/webpack/issues/13865

**Comment by jcompagner** [comment] 2021-12-03 10:42
> @adampasc, this issue is not caused by Angular, but rather it’s a Webpack bug.
> 
> Please see: [webpack/webpack#13865](https://github.com/webpack/webpack/issues/13865)

i find this comment really weird
We do that special import of locale files not only for angular but also for a few others...
we do the same for numbro:

  return import(`numbro/languages/${localeId}`)

for Uppy:

import(`@uppy/locales/lib/${localeId}.js`)

also for CKEditor but that works a bit different

and all those still are working fine, no need to change anything, its purely the angular locales that with the upgrade to 13 that are suddenly not working in the above way anymore.

**Comment by alan-agius4** [comment] 2021-12-03 11:33
This is because dynamic imports don't work in Webpack when an `exports` with wildcard is specified in package.json

Example
```json
  "exports": {
    "./locales/global/*": {
      "default": "./locales/global/*.js"
    },
    "./locales/*": {
      "default": "./locales/*.mjs"
    },
```

**Comment by StanislavByzov** [comment] 2022-02-22 17:25
This approach worked for me:
`import('node_modules/@angular/common/locales/${this.locale}.mjs');`

**Comment by alan-agius4** [comment] 2022-05-27 13:22
Closing since this is not actionable from our end as this is a Webpack bug.  Please see: https://github.com/webpack/webpack/issues/13865

**Comment by alan-agius4** [comment] 2022-05-27 13:22
https://github.com/angular/angular-cli/issues/22088#issuecomment-1139615012

**Closed by alan-agius4** 2022-05-27 13:22 UTC
Labels: type: bug/fix, freq1: low, severity5: regression, comp: devkit/build-angular, state: blocked on upstream
