### ISSUE TITLE
Recompile fails when using environment configuration and ng serve -e=envName

### ISSUE THREAD

**Issue by itmayziii** [angular/angular-cli#6132] opened 2017-04-29 18:54 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0-rc.1
npm: 4.2.0
node: v7.4.0

### Repro steps.
1. Environment file located at src/environments/environment.dev.ts

2. This configuration in the .angular-cli.json
`      "environments": {
        "dev": "environments/environment.dev.ts",
        "prod": "environments/environment.prod.ts"
      }`

3. Run ng serve -e=dev
4. Everything will compile fine the first time, go and make a small change and save one of your component files and it will fail to recompile.

You can use this repo branch as an example. 
https://github.com/itmayziii/blog-ui/tree/Sjhx8HgD_contact_form/src

### The log given by the failure.

Module build failed: Error: ENOENT: no such file or directory, open '/Users/txm241/Sites/blog-ui/src/environments/environment.ts'

### Desired functionality.
I expect ng serve to recompile the app successfully.

**Comment by sumitarora** [comment] 2017-05-01 16:30
@itmayziii Is it still an issue. I don't see the branch on github.

**Comment by RodrigoMattosoSilveira** [comment] 2017-05-05 20:12
I have a related, but slightly different issue. I created an environment named `ua`; when  I use it with `ng serve --env=ua` it works fine; unfortunately, when I change the software, the automatic rebuild reverts back to the default environment! Any thoughts on how to overcome this?

**Comment by filipesilva** [comment] 2017-05-08 10:45
Closing in favor of https://github.com/angular/angular-cli/issues/6201, which seems to have the same root cause but contains a few more details.

**Closed by filipesilva** 2017-05-08 10:45 UTC
Labels: need: repro steps
