### ISSUE TITLE
angular-cli 1.6.5 doesn't load assets when serving

### ISSUE THREAD

**Issue by CreativeMindW** [angular/angular-cli#9378] opened 2018-01-25 08:28 UTC
I updated angular-cli from 1.6.3 to 1.6.5. but in my windows system when I try ng serve all my assets (like images and.. ) missed. however, in my mac system, it doesn't have any problem. finally, i downgraded angular-cli to 1.6.3 and everything works well. as you can see in the attached image in 1.6.5 seems that web pack missed assets folder in serving.
![image](https://user-images.githubusercontent.com/31847887/35378087-c3b0d7e8-01c6-11e8-8d13-68c3e91707ba.png)

**Comment by filipesilva** [comment] 2018-01-25 10:06
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/9230. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2018-01-25 10:06 UTC
