### ISSUE TITLE
Test-coverage says that coverage is not 100%, but it truly is!

### ISSUE THREAD

**Issue by askarby** [angular/angular-cli#5871] opened 2017-04-07 07:53 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.5
os: darwin x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/platform-server: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

```
### Repro steps.

Upgrade your 100% tested angular 2.4.8 app to 4.0.1, along with Angular CLI 1.0.0

### The log given by the failure.

There's no actual failure (stacktrace thown), but the behaviour of the text-coverage is wrong. I'm hitting every line, statement, branch and function of the code, but coverage does not "cover" constructor signature.

### Desired functionality.

The test coverage should be 100%, and was until I upgraded from Angular 2.4.8 (CLI 1.0.0 RC.0) to Angular 4.01 (CLI 1.0.0).

**Before**
![before](https://cloud.githubusercontent.com/assets/44014/24790092/03db101e-1b76-11e7-802b-49bf2178fa60.png)

**After**
![after](https://cloud.githubusercontent.com/assets/44014/24790554/1c47ae18-1b77-11e7-9199-8e674dca4a19.png)

**Coverage error (example)**
![example](https://cloud.githubusercontent.com/assets/44014/24790762/db299288-1b77-11e7-9398-3abdc0ec49c7.png)

### Mention any other details that might be useful.
My karma.conf.js file looks like:

```javascript
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma'),
      require('karma-spec-reporter'),
      require('karma-appveyor-reporter')
    ],
    files: [
      {pattern: './src/test.ts', watched: false}
    ],
    preprocessors: {
      './src/test.ts': ['@angular/cli']
    },
    mime: {
      'text/x-typescript': ['ts', 'tsx']
    },
    coverageIstanbulReporter: {
      reports: [ 'html', 'lcovonly', 'text' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: config.angularCli && config.angularCli.codeCoverage
      ? ['spec', 'coverage-istanbul', 'appveyor']
      : ['spec', 'appveyor'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

I'm unfortunately not permitted to share the code-base, since it's a closed source, propriatary product I'm working on. I can however provide you with various configuration files. So, do **not** refrain from asking for these.

**Comment by victornoel** [comment] 2017-04-10 08:53
We have the same problem on this opensource project: https://gitlab.com/linagora/petals-cockpit (in branch `front/unit-test-reducers`).

**Comment by chris-jones-pixitmedia** [comment] 2017-04-12 09:45
Same issue here, certain constructor params are marked as 'branch not covered'. Same code / tests run against previous versions of the CLI report 100% coverage.

**Comment by marekszczepansky** [comment] 2017-04-24 15:07
Unfortunately I have the same. Even 4 issues in one constructor :(

**Comment by Jeffarese** [comment] 2017-04-25 08:44
:+1: having the same problem

**Comment by freeman29** [comment] 2017-05-03 09:41
👍 encountered same issue

**Comment by filipesilva** [comment] 2017-05-04 15:03
At one point we switched the karma code-coverage plugin, that might be related.

**Comment by elektroels** [comment] 2017-05-08 12:55
Same problem

**Comment by kenisteward** [comment] 2017-05-12 19:02
Same issue but I'm looking into the matter.  Will start looking at what exactly the karma plugin is doing.

**Comment by dimitriy-k** [comment] 2017-06-12 11:19
fix it please :)

**Comment by ryzy** [comment] 2017-06-18 22:17
Because of that reason, I'm using newest `ng`, but replacing karma.conf with `karma-remap-istanbul` setup (like it was before we switched to `code-coverage plugin`).

It's not silver bullet, the issue is still present in setup with `karma-remap-istanbul`, but with less branches reported as not-tested.

**Comment by rg1220** [comment] 2017-07-02 12:55
+1 Having the same issue in several places:

<img width="530" alt="screen shot 2017-07-02 at 8 55 13 am" src="https://user-images.githubusercontent.com/6728645/27769959-30f460c4-5f04-11e7-9369-0c1b2a4ead7f.png">

<img width="657" alt="screen shot 2017-07-02 at 8 54 40 am" src="https://user-images.githubusercontent.com/6728645/27769954-1e957698-5f04-11e7-8cd6-e3cd8b6af543.png">

**Comment by rg1220** [comment] 2017-07-02 13:06
Appears to be a duplicate of https://github.com/angular/angular-cli/issues/5526

**Comment by askarby** [comment] 2017-07-11 06:29
@rg1220 

Well, not exactly... since we're not only experiencing it in constructors, but also in class parameters.

**Comment by aniruddhadas9** [comment] 2017-08-15 15:46
I am also unable to cover 100% code coverage due to this problem. Will wait until it will be pushed into later version.

currently using 1.1.0

```
  constructor(private elementRef: ElementRef, private tagApi: TagApi, private tagTypeApi: TagTypeApi,
              private businessObjectDefinitionTagApi: BusinessObjectDefinitionTagApi) {
  }
 
```

these two properties are not covered expect everything else is fine.
_private tagApi: TagApi, private tagTypeApi: TagTypeApi,_

**Comment by filipesilva** [comment] 2017-10-21 15:27
Going to close this one as duplicate of #5526, they are the same and the other one has a lot more info on the problem.

**Closed by filipesilva** 2017-10-21 15:27 UTC
Labels: effort1: easy (hours), need: investigation, priority: 2 (required), severity1: confusing
