### ISSUE TITLE
ngtools/webpack not work with angular 5.2

### ISSUE THREAD

**Issue by keyiis** [angular/angular-cli#9199] opened 2018-01-14 06:54 UTC
I used ngtools/webpack@1.6.0 complier angular@4.3.1,all work fine,but when i upgrade ngtools/webpack to 1.9.4 and angular to 5.2. no error and waring output in complier process,the generator file only has pre line `webpackJsonp([1],[function(n,exports){}],[0]);` .below is my config
**paclage.json**
```
"@angular/compiler-cli": "^5.2.0",
    "@angular/platform-server": "^5.2.0",
    "@ngtools/webpack": "^1.9.4",
"webpack": "^3.5.4",
    "webpack-dev-server": "^2.6.1",
    "webpack-merge": "^4.1.0",
"@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
```
**webpack.config(only change below)**
```
const AngularCompilerPlugin = require('@ngtools/webpack').AngularCompilerPlugin;
module: {
    rules: [
      {
        test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
        loader: '@ngtools/webpack',
      }
    ]
  },
plugins: [
    new AngularCompilerPlugin({
      tsConfigPath: helpers.root('tsconfig.aot.json'),
      entryModule: helpers.rootAngular('/ad/app/app.module#AppModule')
    })
```
**tsconfig.json**
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2015",
      "es2016",
      "es2017",
      "dom"
    ],
    "noEmit": true,
    "skipDefaultLibCheck": true,
    "removeComments": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
      "node_modules/@types",
      "third-type-definitions"
    ]
  },
  "angularCompilerOptions": {
    "skipMetadataEmit": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "exclude":["node_modules","output"]
}
```
**main.ts**
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';
import {enableProdMode} from '@angular/core';
if (global['node_env'] !== 'development') {
    enableProdMode();
}
platformBrowserDynamic().bootstrapModule(AppModule);
```

**Comment by wKoza** [comment] 2018-01-14 07:12
I have no problem with my template https://github.com/wKoza/simple-angular-starter which use @ngtools/webpack.

**Comment by keyiis** [comment] 2018-01-14 07:42
@wKoza i compared your code,can't find any issuse,webpack generator file only has one line
`webpackJsonp([1],[function(n,exports){}],[0]);`

**Comment by keyiis** [comment] 2018-01-14 11:42
**# Each update @ngtools/webpack is a painful process！**
I still can't find out what went wrong，because no error or warning output in complier process.

**Comment by keyiis** [comment] 2018-01-15 09:07
I didn't find any solution,so decide degrade to angular 4.3.

**Comment by wKoza** [comment] 2018-01-15 09:13
@keyiis, do you have tested your application code in my template ?

**Comment by keyiis** [comment] 2018-01-15 09:43
@wKoza I already changed config same as your config exclude some path and file's name.i will create a repo to reproduce the issuse,but my app is too big,so need take some time to dismantle.

**Comment by keyiis** [comment] 2018-01-15 09:50
@wKoza When i upgrade to 5.2,all work fine with JIT mode,so i think the issuse mybe in ngtools/webpack,but no error output in log,so i can't find any clues to solve the problem.

**Comment by vincex** [comment] 2018-01-15 14:22
Same problem for me. As far as i can see seems that in the factory during bootstrap the moduleType is undefined

**Comment by filipesilva** [comment] 2018-01-25 13:07
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by vincex** [comment] 2018-01-25 17:54
Seems that my problem is related to something different. 
It appears only when an application has one main.ts file that contains the entry module definition.

**main.ts**
```typescript
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }  from './app/app.component';

@NgModule({
  imports:      [ BrowserModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);
```

If the application follows the standard files structure with one "main.ts" file and one "app.module.ts" file the ngtools plugins works correctly with angular 5.2.

**Comment by filipesilva** [comment] 2018-01-31 10:00
Ok that's valuable information. It sounds like a big with how we replace the bootstrap for AOT.

**Comment by sujithgowda** [comment] 2018-02-06 11:55
remove noEmit:true from tsconfig

**Comment by rdicroce** [comment] 2018-02-07 18:52
I also encountered this issue. I can confirm that moving the bootstrap call to another file works around the problem.

**Comment by thiagoschmitz** [comment] 2018-03-21 15:37
I had the same issue here, I changed the AOTPlugin config. Instead of using entryModule, I'm using mainPath. It solved the issue.

**Comment by kolesnik** [comment] 2018-03-23 16:46
+1

**Comment by cagegit** [comment] 2018-11-03 03:37
> remove noEmit:true from tsconfig

it work for me,big thanks!

**Comment by mgechev** [comment] 2019-08-19 20:22
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:22 UTC
Labels: comp: ngtools/webpack, freq1: low, severity3: broken, type: bug/fix
