### ISSUE TITLE
Fresh project, error building

### ISSUE THREAD

**Issue by Marooned-MB** [angular/angular-cli#17272] opened 2020-03-21 16:50 UTC
# 🐞 Bug report

### Command (mark with an `x`)
- [x] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Fresh project won't build.

## 🔬 Minimal Reproduction
1) I've downloaded latest node (v12.16.1) with npm (v6.13.4)
2) installed new angular-cli using `npm install -g @angular/cli`
3) created new project using `ng new FooBar`
4) run it via `ng serve` (and alias `npm start`)
5) get error and build failed

## 🔥 Exception or Error
<pre><code>
>npm start

> roll-and-draw@0.0.0 start 
> ng serve

chunk {main} main.js, main.js.map (main) 3.18 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 1.63 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.78 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 344 kB [initial] [rendered]
Date: 2020-03-21T16:33:42.995Z - Hash: 5765291ceaadc047a79b - Time: 8419ms

ERROR in FooBar/src/main.ts
Module build failed (from FooBar/node_modules/@ngtools/webpack/src/index.js):
Error: FooBar\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (FooBar\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:933:23)
    at FooBar\node_modules\@ngtools\webpack\src\loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR in FooBar/src/polyfills.ts
Module build failed (from FooBar/node_modules/@ngtools/webpack/src/index.js):
Error: FooBar\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (FooBar\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:933:23)
    at FooBar\node_modules\@ngtools\webpack\src\loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
</code></pre>

## 🌍 Your Environment
<pre><code>
>ng version
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / ? \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.7
Node: 12.16.1
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2</code></pre>

**Comment by Marooned-MB** [comment] 2020-03-22 20:08
Ok, after more digging I stumbled upon solution: https://github.com/angular/angular-cli/issues/9909#issuecomment-468266347

> saradotramli commented on 28 Feb 2019
> Editing angular.json to add following attribute under the node "projects/{yourprojectname}/architect/build/options" should help:
"preserveSymlinks": true

Maybe this shuld be default option? Unfortunately, error message doesn't give a hint about that solution. Not sure if I should close this issue - main issue is that fresh project won't compile without that change, so I'll leave issue open for someone to decide what's next.

**Comment by sacgrover** [comment] 2020-03-23 06:27
@Marooned-MB  I am not able to reproduce it with given steps.. With same environment, Everything is working fine for me.

**Comment by alan-agius4** [comment] 2020-03-23 08:53
Hi @Marooned-MB, I am also unable to reproduce this locally. Can you please share a reproduction?

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by Marooned-MB** [comment] 2020-03-23 09:49
Ok, so using linked solution I did a test.
When I create new project in `c:\foo`, then it builds correctly.
When I create new project in `c:\Documents and Settings\Username\projects\foo` then it fails.
`c:\Documents and Settings` is alias to `c:\Users` (at least on Windows7)

Can you recheck on above path?

**Comment by alan-agius4** [comment] 2020-03-23 12:30
Indeed  `C:\Documents and Settings\<profile>` is a symlink to `c:\users\<profile>` and only exists for compatibility reasons with Windows XP. 

So two possible solutions here;
1) Use `preserveSymlinks` since you are in a symlink environment. 
2) Use `C:\users` instead of the `C:\Documents and Settings` unless for some reason you require to use that path for compatibility.

Closing as this is working as expected.

**Closed by alan-agius4** 2020-03-23 12:30 UTC
Labels: need: repro steps

**Comment by Marooned-MB** [comment] 2020-03-23 12:39
Not sure why `preserveSymlinks` can't be enabled by default in new projects so such issues won't be a problem for anyone from start.
And D&S folder is used as a default so looks like OS behavior.

**Comment by alan-agius4** [comment] 2020-03-23 12:56
That would be a breaking change since if users rely on a symlinked path, when using `preserveSymlinks` the resolved paths will be real paths which might break existing users.

Also, typically `preserveSymlinks` is off by default in other tools ex: Node, TypeScript, Webpack, Rollup etc.. So for consistence, IHO I think it's best to keep it off by default.
