### ISSUE TITLE
Cli build should support loading modules with *.tsx extension.

### ISSUE THREAD

**Issue by majo44** [angular/angular-cli#8046] opened 2017-10-13 15:06 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0-rc.0
Node: 6.11.0
OS: win32 x64
Angular: 5.0.0-rc.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.5.0-rc.0
@angular-devkit/build-optimizer: 0.0.27
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.33
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.0
@schematics/angular: 0.0.45
typescript: 2.5.3
webpack: 3.7.1
```

### Repro steps.
1. call `ng new testproject`
2. cd testproject
3. rename src\app\app.component.ts to src\app\app.component.tsx
4. add to tsconfig.json compilerOptions
    "jsx": "react",
    "jsxFactory": "h"
5. call `ng build`

### The log given by the failure.
```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './app.component' in 'c:\temp\testproject\src\app'
resolve './app.component' in 'c:\temp\testproject\src\app'
  using description file: c:\temp\testproject\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: c:\temp\testproject\package.json (relative path: ./src/app)
    using description file: c:\temp\testproject\package.json (relative path: ./src/app/app.component)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        c:\temp\testproject\src\app\app.component doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        c:\temp\testproject\src\app\app.component.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        c:\temp\testproject\src\app\app.component.js doesn't exist
      as directory
        c:\temp\testproject\src\app\app.component doesn't exist
[c:\temp\testproject\src\app\app.component]
[c:\temp\testproject\src\app\app.component.ts]
[c:\temp\testproject\src\app\app.component.js]
[c:\temp\testproject\src\app\app.component]
 @ ./src/app/app.module.ts 9:0-47
 @ ./src/main.ts
 @ multi ./src/main.ts
```

### Desired functionality.
The tsx is providing just extended syntax sugar, which can be used for different porpoises. In my case I'm using mono-repo approach and I'm delivering part of components as web-components where I'm using jsx/tsx.  
For compiler there should not be difference in extension of module. 

Ropen of https://github.com/angular/angular/issues/19691#issuecomment-336222081

**Comment by filipesilva** [comment] 2017-10-16 16:49
Discussed offline, we should support it.

**Comment by majo44** [comment] 2017-10-30 12:27
Any chance to got this in 1.5.0 ?

**Comment by rsxdalv** [comment] 2017-11-22 16:36
What work is left to pull this PR?

**Comment by mcharmas** [comment] 2017-11-24 14:37
Is there any workaround this issue?

**Comment by majo44** [comment] 2017-11-24 15:31
UGLY workaround: https://gist.github.com/majo44/4862b8e7db6254975669e0a3f9d67a2a#file-angular-cli-1-5-0-tsx-loading-ugly-fix (we have this in postinstall)

We are working on PR.

**Comment by mcharmas** [comment] 2017-11-27 09:51
@majo44 thx, I guess it's better solution then ejecting to webpack

**Comment by urish** [comment] 2018-02-08 23:09
@majo44 any news regarding the PR ?

**Comment by majo44** [comment] 2018-02-09 09:49
@urish unfortunately we are not actively working on PR, so far we stick with workaround and old version of cli :(

**Comment by urish** [comment] 2018-02-09 10:13
The workaround also works with the latest CLI (tested last night), however
I'd love to see this integrated into the CLI...

**Comment by psamusev** [comment] 2018-03-16 16:13
@urish It has stopped work with @angular/cli >= 1.7.0

**Comment by lygstate** [comment] 2018-04-01 17:18
@majo44 PR thanks.

**Comment by lygstate** [comment] 2018-04-01 17:45
@psamusev I am working fine with 1.7.3, so what's the problem you faced?

**Comment by psamusev** [comment] 2018-04-02 07:21
@lygstate I'm talking about live reload with help of **ng serve** - server doesn't see changes and doesn't execute reload

**Comment by rsxdalv** [comment] 2018-04-02 07:35
@psamusev It sees them one level deep (i.e myfile.ts `... import .. myotherfile.tsx ...` myotherfile.ts `... import .. mythirdfile.tsx ...`, only first and second will be seen)

**Comment by psamusev** [comment] 2018-04-02 12:09
@rsxdalv I expect it shouldn't work in this way :)

**Comment by rsxdalv** [comment] 2018-04-02 12:30
@psamusev Eyes open for your PR.

**Comment by psamusev** [comment] 2018-04-13 12:28
workaround is to make import with **.tsx** and the end if import file

`
import 'myTsxfile.tsx'
`

**Comment by sakalys** [comment] 2018-05-03 14:19
@psamusev this does not work. Using your suggestion it errors out:
```
You may need an appropriate loader to handle this file type.
```

**Comment by psamusev** [comment] 2018-05-03 15:17
@sakalys  you have to import only with string path. I mean
```
import 'myImportfile.tsx
```
works, however

```
import { SomeComponent } from 'myImportfile.tsx'
```
will not work

**Comment by sakalys** [comment] 2018-05-04 06:11
Oh, thank you, sir. I'll definitely check.

**Comment by rsxdalv** [comment] 2018-05-12 08:28
@zh99998 Take advantage of versioning: downgrade. Very few updates have been worth their salt beyond reducing future upgrade pains. Later, you might be able to revert back to 6.0.1 when the fix is updated.

**Comment by urish** [comment] 2018-05-19 17:59
Just sent a PR to make it work with the latest CLI (6.x). I'm using this in one of my projects successfully. Fingers crossed! 🤞

**Comment by psamusev** [comment] 2018-06-29 07:51
@urish looks like your fix doesn't work when build is for server module (I create universal product)
I'm using:
`"@angular-devkit/build-angular": "~0.7.0-beta.2",
"@angular/cli": "~6.1.0-rc.0",`

**Comment by rhalff** [comment] 2018-07-02 16:37
I'm currently solving this issue in an extra build step for projects containing jsx:

```typescript
import * as ngPackage from 'ng-packagr'

ngPackage
  .ngPackagr()
  .forProject(
     'projects/<angular-lib-project>'
  )
  .withTsConfig(
    'projects/<angular-lib-project>/tsconfig.lib.json'
  )
  .build()
  .catch(error => {
    console.error(error)
    process.exit(1)
  })
```
The file layout of the library can remain as is in this case.

You'll also have to add `"jsx": true` in your `ng-package.json` and set `"jsx": "react|react-native|preserve"` inside the typescript configuration file.

**Comment by ar53n** [comment] 2018-07-02 22:21
How i can test *.spec.tsx files? Have anyone that problem?

**Comment by lacolaco** [comment] 2018-07-24 06:53
I'm using `ngx-build-plus` to compile `.tsx` files
https://github.com/manfredsteyer/ngx-build-plus/

webpack.extra.js

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.tsx$/,
        use: 'ts-loader'
      }
    ]
  },
  resolve: {
    extensions: ['.tsx'],
  }
};
```

I think `ngcLoader` should handle `.tsx` file as well as `.ts`

**Comment by davidenke** [comment] 2018-09-20 10:44
Are there any updates on this? For us `*.tsx` support is working only on non-aot builds. Running `ng serve --aot=true` seams not to work.

Do you need a reproduction case?

**Comment by psamusev** [comment] 2018-09-20 13:05
@davidenke There is a PR to fix it - https://github.com/angular/angular-cli/pull/11407

**Comment by davidenke** [comment] 2018-09-20 13:09
@psamusev it's not reviewed yet, maybe because of the failed circle ci tests?

**Comment by psamusev** [comment] 2018-09-20 14:33
@davidenke I think so.

**Comment by clydin** [comment] 2018-09-28 17:34
Support has been merged and will be available in 7.0.

**Closed by clydin** 2018-09-28 17:34 UTC
Labels: priority: 2 (required), type: feature

**Comment by jimthedev** [comment] 2019-01-18 16:31
I have been unable to get this working at all. Is it documented anywhere so that I can confirm I am on the right versions of everything?

**Comment by ahpoi** [comment] 2019-01-23 12:35
@jimthedev 
I have managed to get it working, I had to upgrade to angular 7, and in the tsconfig for compiler option, you need to add `"jsx": "react".

**Comment by jimthedev** [comment] 2019-01-23 15:04
@ahpoi This worked for me. It seems to be working pretty well.

**Comment by FRSgit** [comment] 2019-04-05 15:12
For future travelers - when using jsx with stenciljs I needed to have these two config options in `tsconfig.json`:
```json
    "jsx"        : "react",
    "jsxFactory" : "h"
```
