### ISSUE TITLE
ng build failures do not cause non-zero exit code

### ISSUE THREAD

**Issue by JohannesRudolph** [angular/angular-cli#10047] opened 2018-03-22 21:36 UTC
### Versions
```
iDevBook01:panel jr (develop *) $ ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.3
Node: 8.10.0
OS: darwin x64
Angular: 5.2.9
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps
Break your app by keyboard-monkey-punching some absolutely invalid typescript in your `app.component.ts`.

### Observed behavior
```
iDevBook01:panel jr (develop *) $ ng build --target=production --environment=mesh --app=mesh --aot=true --progress=true --output-path=./dist/mesh --delete-output-path=true --stats-json=true 
Date: 2018-03-22T21:16:37.071Z                                                     
Hash: f82eaaff21a3d21d1b7a
Time: 7461ms
chunk {0} styles.20e3500e976c50d790e3.bundle.css (styles) 193 kB [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in : Unexpected value 'AppComponent in /Users/jr/dev/meshfed-release/panel/src/app/app.component.ts' declared by the module 'AppModule in /Users/jr/dev/meshfed-release/panel/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.
src/app/app.component.ts(1,11): error TS1005: ';' expected.
src/app/app.component.ts(1,86): error TS1005: ';' expected.

Unhandled rejection Error: ENOENT: no such file or directory, open '/Users/jr/dev/meshfed-release/panel/dist/mesh/stats.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at callback (/Users/jr/dev/meshfed-release/panel/node_modules/@angular/cli/tasks/build.js:56:24)
    at onCompiled (/Users/jr/dev/meshfed-release/panel/node_modules/webpack/lib/Compiler.js:237:12)
    at applyPluginsAsync.err (/Users/jr/dev/meshfed-release/panel/node_modules/webpack/lib/Compiler.js:510:14)
    at next (/Users/jr/dev/meshfed-release/panel/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/Users/jr/dev/meshfed-release/panel/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/Users/jr/dev/meshfed-release/panel/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/Users/jr/dev/meshfed-release/panel/node_modules/webpack/lib/Compiler.js:507:11)
    at next (/Users/jr/dev/meshfed-release/panel/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/Users/jr/dev/meshfed-release/panel/node_modules/@angular/cli/plugins/suppress-entry-chunks-webpack-plugin.js:38:17)
    at Compilation.applyPluginsAsyncSeries (/Users/jr/dev/meshfed-release/panel/node_modules/tapable/lib/Tapable.js:206:13)
    at applyPluginsAsync.err (/Users/jr/dev/meshfed-release/panel/node_modules/webpack/lib/Compilation.js:677:19)
    at next (/Users/jr/dev/meshfed-release/panel/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/Users/jr/dev/meshfed-release/panel/node_modules/webpack/lib/ProgressPlugin.js:123:6)
    at Compilation.applyPluginsAsyncSeries (/Users/jr/dev/meshfed-release/panel/node_modules/tapable/lib/Tapable.js:206:13)

iDevBook01:panel jr (develop *) $ $?
-bash: 0: command not found
```

### Desired behavior
The `ng build` command should return a non-zero exit code

**Comment by PoiScript** [comment] 2018-03-26 11:25
I have the same problem as you. It seems that the build will always return the 0 exit code when `--stats-json` option is given. This bug is quite annoying in the CI, so I hope that the Angular CLI team can be aware of this :).

**Comment by tfiwm** [comment] 2018-05-11 09:42
Is same like this one https://github.com/angular/angular-cli/issues/9720

**Comment by alan-agius4** [comment] 2018-10-11 12:46
Duplicate of #9720

**Closed by alan-agius4** 2018-10-11 12:46 UTC
