### ISSUE TITLE
Cannot find module 'package.json'

### ISSUE THREAD

**Issue by AmitMY** [angular/angular-cli#2997] opened 2016-11-03 09:05 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10

### Versions.

> Cannot find module 'package.json'
> Error: Cannot find module 'package.json'
>     at Function.Module._resolveFilename (module.js:472:15)
>     at Function.Module._load (module.js:420:25)
>     at Module.require (module.js:500:17)
>     at require (internal/module.js:20:19)
>     at AddonDiscovery.discoverAtPath (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\addon-discovery.js:205:20)
>     at AddonDiscovery.<anonymous> (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\addon-discovery.js:114:26)
>     at Array.map (native)
>     at AddonDiscovery.discoverFromDependencies (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\addon-discovery.js:109:68)
>     at AddonDiscovery.discoverProjectAddons (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\addon-discovery.js:48:29)
>     at Project.discoverAddons (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\project.js:353:40)
>     at Project.initializeAddons (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\project.js:372:8)
>     at Project.eachAddonCommand (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\project.js:425:10)
>     at module.exports (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\cli\lookup-command.js:33:13)
>     at CLI.<anonymous> (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\cli\cli.js:34:26)
>     at tryCatch (D:\xampp\htdocs\Fronend\node_modules\rsvp\dist\rsvp.js:538:12)
>     at invokeCallback (D:\xampp\htdocs\Fronend\node_modules\rsvp\dist\rsvp.js:553:13)
>     at publish (D:\xampp\htdocs\Fronend\node_modules\rsvp\dist\rsvp.js:521:7)
>     at flush (D:\xampp\htdocs\Fronend\node_modules\rsvp\dist\rsvp.js:2373:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> 

### Repro steps.
No idea.

### The log given by the failure.

> Cannot find module 'package.json'
> Error: Cannot find module 'package.json'
>     at Function.Module._resolveFilename (module.js:472:15)
>     at Function.Module._load (module.js:420:25)
>     at Module.require (module.js:500:17)
>     at require (internal/module.js:20:19)
>     at AddonDiscovery.discoverAtPath (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\addon-discovery.js:205:20)
>     at AddonDiscovery.<anonymous> (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\addon-discovery.js:114:26)
>     at Array.map (native)
>     at AddonDiscovery.discoverFromDependencies (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\addon-discovery.js:109:68)
>     at AddonDiscovery.discoverProjectAddons (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\addon-discovery.js:48:29)
>     at Project.discoverAddons (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\project.js:353:40)
>     at Project.initializeAddons (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\project.js:372:8)
>     at Project.eachAddonCommand (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\models\project.js:425:10)
>     at module.exports (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\cli\lookup-command.js:33:13)
>     at CLI.<anonymous> (D:\xampp\htdocs\Fronend\node_modules\angular-cli\lib\cli\cli.js:34:26)
>     at tryCatch (D:\xampp\htdocs\Fronend\node_modules\rsvp\dist\rsvp.js:538:12)
>     at invokeCallback (D:\xampp\htdocs\Fronend\node_modules\rsvp\dist\rsvp.js:553:13)
>     at publish (D:\xampp\htdocs\Fronend\node_modules\rsvp\dist\rsvp.js:521:7)
>     at flush (D:\xampp\htdocs\Fronend\node_modules\rsvp\dist\rsvp.js:2373:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> 

### Mention any other details that might be useful.
I worked on my front, for a while, and then started work on the back, The backend required 4 new dependencies: 'express', 'body-parser', 'request', 'http'

I thought that there is no harm to currently do it in the same project.

**Comment by AmitMY** [comment] 2016-11-03 09:08
Issue discovered!
When installing 'http' it says:
> "http": "0.0.0",

You should add a handler..
(Current fix? using "latest")

**Comment by filipesilva** [comment] 2016-11-04 16:43
Haven't seen that error before. I really need repro steps if you want me to look into this issue.

**Comment by filipesilva** [comment] 2016-11-04 17:43
Actually, dupe of https://github.com/angular/angular-cli/issues/2997

**Closed by filipesilva** 2016-11-04 17:43 UTC
Labels: need: repro steps
