### ISSUE TITLE
Command ng set defaults.styleExt scss fail

### ISSUE THREAD

**Issue by newaeonweb** [angular/angular-cli#2143] opened 2016-09-15 17:29 UTC
Command fail with error: Cannot read property 'serialize' of undefined

1. Mac OSX ( El Capitan)

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.14
node: 4.2.2
os: darwin x64

3. Start a project with no stylesheet options.
    Running: ng set defaults.styleExt scss

4. The log given by the failure. Normally this include a stack trace and some
   more information.
  Log is too long

**Comment by kmckinley** [comment] 2016-09-17 12:23
I'm running into the same problem.  Also on Mac OSX (El Capitan)

angular-cli: 1.0.0-beta.14
node: 5.11.1
os: darwin x64

**Comment by hardikkaji** [comment] 2016-09-17 12:51
I am facing same issue.

> angular-cli: 1.0.0-beta.14
> node: 5.2.0
> os: win32 x64

**Comment by calogeroguagenti** [comment] 2016-09-17 16:18
Same issue

> angular-cli: 1.0.0-beta.14
> node: 6.4.0
> os: darwin x64

**Comment by peterblazejewicz** [comment] 2016-09-18 17:03
> Log is too long

The gist with log: https://gist.github.com/peterblazejewicz/8671b8c55ddb9cb6d728fbcf53997ae8

**Comment by filipesilva** [comment] 2016-09-22 03:05
Dupe of https://github.com/angular/angular-cli/issues/1900

**Closed by filipesilva** 2016-09-22 03:05 UTC

**Comment by AndersFly666** [comment] 2016-09-22 13:03
Same issue

angular-cli: 1.0.0-beta.15
node: 6.6.0
os: win32 x64

Log: [https://gist.github.com/AndersFly666/699ce2e27faed5c96e5a5899ed77d2f9](url)

**Comment by zalog** [comment] 2016-10-02 14:03
Same here.

angular-cli: 1.0.0-beta.16
node: 4.5.0
os: win32 x64

**Comment by JanStureNielsen** [comment] 2016-10-02 15:16
@zalog  -- http://stackoverflow.com/questions/39812448/angular-cli-installation-failure

**Comment by dexteriti** [comment] 2016-10-07 16:36
Is there any solution to this?

I kept changing it manually, but it is annoying to say the least.

**Comment by 07Gond** [comment] 2016-10-11 18:01
This has been fixed in f7bf0aa.

You can upgrade angular-cli from github directly using:
`npm install -g https://github.com/angular/angular-cli`

Or:

You can edit the file: 
"_%PROJECT%\node_modules\angular-cli\models\json-schema\schema-tree_" 
and replace the line **235** with:
`serializer.property(key, function () { return serializer.outputValue(value[key])});`

**Comment by calogeroguagenti** [comment] 2016-10-12 11:48
Thank you @07Gond
