### ISSUE TITLE
Add support for Node.JS v18 (lack of it possibly causes unbound breakpoints)

### ISSUE THREAD

**Issue by SimonTheBaptist** [angular/angular-cli#23113] opened 2022-05-10 18:15 UTC
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc

Once I updated my system from Node.JS 16.15.0 to 18.1.0, breakpoints in Angular code stopped working - they became unbound.
After I've downgraded Node.JS back to v16 they started working again.

When running "ng --version", I got:
Angular CLI: 13.3.5
Node: 18.1.0 (Unsupported)
Package Manager: npm 8.9.0
OS: win32 x64

Angular: 13.3.6
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.5
@angular-devkit/build-angular   13.3.5
@angular-devkit/core            13.3.5
@angular-devkit/schematics      13.3.5
@angular/cli                    13.3.5
@schematics/angular             13.3.5
rxjs                            7.5.5
typescript                      4.4.4

Warning: The current version of Node (18.1.0) is not supported by Angular.

I'm assuming the unbound breakpoints problem is because Node.JS 18 is not yet supported.
Can you please add support for it?

**Comment by alan-agius4** [comment] 2022-05-10 19:02
Duplicate of https://github.com/angular/angular/issues/45870

**Closed by alan-agius4** 2022-05-10 19:02 UTC
