### ISSUE TITLE
AOT UnitTest support

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#8131] opened 2017-10-20 16:10 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### Versions.
`
angular/cli: 1.4.1
node: 6.9.0
os: darwin x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.1
@angular/compiler-cli: 4.3.6
typescript-collections: 1.2.3
typescript: 2.3.4

`

### Desired functionality.
Are there any plan to support AOT unittests ?

**Comment by filipesilva** [comment] 2017-10-25 09:51
There is a PR for it (https://github.com/angular/angular-cli/pull/8007), as as mentioned inhttps://github.com/angular/angular-cli/pull/8007#issuecomment-336973766 this support is still experimental and we'll wait until the feature stabilizes before incorporating it into the CLI.

**Comment by timbru31** [comment] 2018-02-15 16:10
This is a duplicate of #6650, isn't it? If yes this one should be closes IMO 👍

**Comment by filipesilva** [comment] 2018-02-15 16:57
@timbru31 good catch, will close as duplicate of #6650.

**Closed by filipesilva** 2018-02-15 16:57 UTC
Labels: priority: 2 (required), type: RFC / discussion / question, type: feature
