### ISSUE TITLE
Configurable environment settings

### ISSUE THREAD

**Issue by gabrielw007** [angular/angular-cli#24578] opened 2023-01-19 15:21 UTC
### Description

There is a nice ability in angular to define multiple environments and have a different build per each of them.
The only problem is that environment file is NOT configurable on prod but there are settings need that ability for us, 
for example: "serverApiUrl" which we need to be configurable on prod.

So, in addition to what we have today, we need an ability to define configurable settings according to the environment used.

### Proposed solution

various options i can think about:

- enable defining configurable properties in environment files
- enable creating a config file per environment and using it in code like environment with file replace in angular.json like environment

### Alternatives considered

currently we can create a "configFile" property in all environments, but all those files are assets, so all of them are deployed during CI\CD although a specific environment has been built.

**Comment by alan-agius4** [comment] 2023-01-19 18:01
Duplicate of https://github.com/angular/angular-cli/issues/4318

**Closed by alan-agius4** 2023-01-19 18:01 UTC
