### ISSUE TITLE
Cesium imlementation

### ISSUE THREAD

**Issue by yairtawil** [angular/angular-cli#2985] opened 2016-11-02 10:07 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 4.5.0
os: win32 x64

### Repro steps.

Hi!

I am trying to put var 'CESIUM_BASE_URL' value to be '../node_modules/cesium/Build/Cesium'

window['CESIUM_BASE_URL'] = '../node_modules/cesium/Build/Cesium';

and I am getting 404 error from the server:

![error](https://cloud.githubusercontent.com/assets/10003115/19924519/f233eb20-a0f4-11e6-9927-6b39de5bf7b9.PNG)

if I copy Cesium folder from node_modules to src/assets
and changed 'CESIUM_BASE_URL' value to 'assets/Cesium' like this:

window['CESIUM_BASE_URL'] = 'assets/Cesium';

it's working fine!

how can I reach '/node_modules/cesium/Build/Cesium' folder without getting 404 error??

thanks, 
Yair.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Meligy** [comment] 2016-11-02 11:35
Try adding `"../node_modules/cesium/Build/Cesium"` to the `assets` array in your `angular-cli.json` file, and then run `ng build`, and see if gets copied to the output folder correctly.

Cheers,

**Comment by yairtawil** [comment] 2016-11-02 12:21
ok!
I'v done what you suggested - but not 'Cesium' folder in the 'dist' 

      "assets": [
        "assets",
        "favicon.ico",
        "../node_modules/cesium/Build/Cesium"
      ],

any idea? 
thanks, 
Yair

**Comment by filipesilva** [comment] 2016-11-04 15:50
Dupe of #2837, see my comment in https://github.com/angular/angular-cli/issues/2837#issuecomment-258457033.

**Closed by filipesilva** 2016-11-04 15:50 UTC

**Comment by yairtawil** [comment] 2016-11-06 05:28
Thanks!!
