### ISSUE TITLE
Support environment variable in build time

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#17526] opened 2020-04-22 09:26 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Create-react-app support   [Custom Environment Variables](https://create-react-app.dev/docs/adding-custom-environment-variables)

We need custom-environment-variables for build. for example:

```ts
Sentry.init({
  dsn: environment.SENTRY_DSN,
  environment: environment.production ? 'production' : 'development',
  release: process.env.ANGULAR_APP_COMMIT_SHA, // git commit sha1
});
```

ANGULAR_APP_COMMIT_SHA changes in every build. We can't write it in `environment.prod.ts`

### Describe the solution you'd like

Support environment variable in build.

Maybe something like process.env.ANGULAR_APP_* or other global variables

**Comment by alan-agius4** [comment] 2020-04-22 09:45
Duplicate of #4318.

Probably a better solutions would be to use runtime configuration, see #7506 which provides several options for runtime configuration.

**Closed by alan-agius4** 2020-04-22 09:45 UTC
