### ISSUE TITLE
ng serve does not watch for file changes in services

### ISSUE THREAD

**Issue by ayush987goyal** [angular/angular-cli#10628] opened 2018-05-04 09:10 UTC
After updating a project to v6, the file changes in services are not watched by `ng serve`. I generated a new project by `ng new` and then moved my old `src/app` directory to this new project.

### Versions
```
Angular CLI: 6.0.0
Node: 8.9.3
OS: win32 x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

**Comment by filipesilva** [comment] 2018-05-04 17:14
This issue is a duplicate of https://github.com/angular/angular-cli/issues/1610. Please check that issue for known reasons why live-reload might fail. If I had to bet, you might have your import in a different case (e.g. `my-Service` vs `my-service`), which is a common mistake.

**Closed by filipesilva** 2018-05-04 17:14 UTC

**Comment by gabucito** [comment] 2018-05-08 20:46
I actually have the same problem.  Live reload was working before updating the project to angular-cli 6.
However, I tried creating a completely new project and live reload works fine.
