### ISSUE TITLE
Cannot find module '@angular/cdk/./schematics/migration.json' when updating @angular/material

### ISSUE THREAD

**Issue by tachojelev** [angular/angular-cli#19726] opened 2021-01-06 11:23 UTC
## Description

Hello guys, when I am trying to upgrade my Angular 10 project to Angular 10.

I successfully updated the core and cli packages with:
```ts
ng update @angular/core @angular/cli
```

After trying to update the material package, which updates the cdk package as well, I get the following error:
```ts
ng update @angular/material
```

![image](https://user-images.githubusercontent.com/12784974/103762997-def9fc80-5021-11eb-97b4-1ba68b7aa96e.png)

The @angular/cdk folder inside node_modules contains the schematics folder and the migration.json file inside of it, so it seems that the problem might be coming from that **extra "./"** and the path becomes incorrect.

Can you advise on how I can fix this error, so the necessary migrations are executed successfully and the ng update passes?

**Comment by alan-agius4** [comment] 2021-01-06 11:53
@tachojelev, can you please provide the full content of the log file and also the output of `npm ls @angular/cdk`?

I did try to replicate this locally on a version 10 project but I wasn't able to reproduce the reported issue.


```
update-ten git:(master) ng update @angular/material
Using package manager: 'npm'
Collecting installed dependencies...
Found 31 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cdk @ "11.0.3" (was "10.2.7")...
    Updating package.json with dependency @angular/material @ "11.0.3" (was "10.2.7")...
  UPDATE package.json (1319 bytes)
✔ Packages installed successfully.
** Executing migrations of package '@angular/cdk' **

❯ Updates the Angular CDK to v11.

      ✓  Updated Angular CDK to version 11

  Migration completed.

** Executing migrations of package '@angular/material' **

❯ Updates Angular Material to v11.

    ⚠  General notice: The HammerJS v9 migration for Angular Components is not able to migrate tests. Please manually clean up tests in your project if they rely on HammerJS.
    Read more about migrating tests: https://git.io/ng-material-v9-hammer-migrate-tests

      ✓  Updated Angular Material to version 11

  Migration completed.
```

**Comment by tachojelev** [comment] 2021-01-06 12:16
Hi @alan-agius4 

Executing ```npm ls @angular/cdk``` displays the following:
```
└── UNMET DEPENDENCY @angular/cdk@11.0.3 

npm ERR! missing: @angular/cdk@11.0.3, required by my-project@1.0.0
```

After the ng update command, the cdk is indeed missing:
![image](https://user-images.githubusercontent.com/12784974/103767661-b4ac3d00-5029-11eb-9465-5b5a24763f5d.png)

Log:
```
[error] Error: Cannot find module '@angular/cdk/./schematics/migration.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at UpdateCommand.run (<path-to-my-project>/node_modules/@angular/cli/commands/update-impl.js:493:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by tachojelev** [comment] 2021-01-06 12:35
As an alternative, can I expect that manually editing the cdk and material versions in the package.json, making an npm install and then doing:
```
ng update @angular/cdk --migrate-only --from 10 --to 11
ng update @angular/material --migrate-only --from 10 --to 11
```

is the same as:
```
ng update @angular/cdk
ng update @angular/material
```
?

**Comment by alan-agius4** [comment] 2021-01-06 12:41
Yeah it’s the same. Although it is strange that `@angular/cdk` is not being installed.

Maybe you can also try to remove the lock file.

**Comment by tachojelev** [comment] 2021-01-06 12:48
@alan-agius4 I tried the approach with removing the lock file and the update does not get performed at all
```
Package '@angular/material' is already up to date.
```
I will try using the alternative approach with the manual migration.

**Comment by alan-agius4** [comment] 2021-01-06 15:09
> @alan-agius4 I tried the approach with removing the lock file and the update does not get performed at all
> 
> ```
> Package '@angular/material' is already up to date.
> ```
> 
> I will try using the alternative approach with the manual migration.

That probably because either you didn’t revert the package.json or didn’t run npm install after the failed migration.

The easiest way forward would be to run the migration with `—-migrate-only` at this point.

**Comment by alan-agius4** [comment] 2021-01-11 07:34
@tachojelev, did you solve the issue?

**Comment by alan-agius4** [comment] 2021-01-14 09:51
Closing a there was no further communication. If the problem persists feel free to open a new issue.

**Closed by alan-agius4** 2021-01-14 09:51 UTC
Labels: need: more info
