### ISSUE TITLE
ng serve unknown options --named-chunks --extract-css that are allowed by ng build

### ISSUE THREAD

**Issue by fmorriso** [angular/angular-cli#12650] opened 2018-10-19 13:06 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
ps>node --version
v8.11.2
ps>npm --version
6.4.1
ps>ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.0.1
Node: 8.11.2
OS: win32 x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.1
@angular-devkit/build-angular     0.10.1
@angular-devkit/build-optimizer   0.10.1
@angular-devkit/build-webpack     0.10.1
@angular-devkit/core              7.0.1
@angular-devkit/schematics        7.0.1
@angular/cli                      7.0.1
@ngtools/webpack                  7.0.1
@schematics/angular               7.0.1
@schematics/update                0.10.1
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```

### Repro steps
```
ng build --extract-css
ng serve --extract-css

ng build --named-chunks
ng serve --named-chunks

```

### The log given by the failure

The following errors occur when the two `ng serve` commands mentioned above are issued:
```
Unknown option: '--extract-css'
Unknown option: '--named-chunks'
```
The corresponding `ng build` commands accept both command-line parameters.

### Desired functionality

What would like to see implemented?

_consistent_ acceptance of common command-line arguments between `ng build` and `ng serve`.

What is the usecase?
I want to avoid the tedium of modifying the bewilderingly complex `angular.json` file and, instead, rely upon the more easily understood package.json file to specify my build and serve options.

**Comment by alan-agius4** [comment] 2018-11-20 09:48
Duplicate of #10532

**Closed by alan-agius4** 2018-11-20 09:48 UTC
Labels: comp: devkit/build-angular, type: feature
