### ISSUE TITLE
Regression: raw-loader is missing

### ISSUE THREAD

**Issue by NicBright** [angular/angular-cli#15653] opened 2019-09-23 07:30 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, the regression was introduced with #10567

### Description

It is no longer possible to do `require('./my-template.html')` in an AngularJS file. This is, because `raw-loader` was removed with #10567 or, respectively, https://github.com/angular/angular-cli/commit/dfb08b95b73f3e75d0f2cd0c61f336dc86d0769a#diff-fdb0776b9f2db468444818966705634c

## 🔬 Minimal Reproduction
- This issue is rather obvious and imho doesn't need to be reproduced, just look at the change in https://github.com/angular/angular-cli/commit/dfb08b95b73f3e75d0f2cd0c61f336dc86d0769a#diff-fdb0776b9f2db468444818966705634cL310 ... the raw-loader has been removed for `.html` files. 

The suggested alternative of using `directTemplateLoading` doesn't work ... I'm not sure why but my guess is that `directTemplateLoading` is supposed to work only for Angular related stuff. Any js files unrelated to Angular (like e.g. AngularJS files) seem to be loaded in a different way.

The workaround to add `raw-loader!` in front of every `.html`-require is extremely unpleasant.

**Comment by alan-agius4** [comment] 2019-09-23 08:04
Duplicate of https://github.com/angular/angular-cli/issues/14855

**Closed by alan-agius4** 2019-09-23 08:04 UTC
