### ISSUE TITLE
Cannot apply a change to a different path.

### ISSUE THREAD

**Issue by dumyjob** [angular/angular-cli#3169] opened 2016-11-17 03:15 UTC
admin@user MINGW64 /e/git/ng2-adminlte/src/app/logon (master)
$ ng g component ./sign-in
installing component
  create src\app\sign-in\sign-in.component.css
  create src\app\sign-in\sign-in.component.html
  create src\app\sign-in\sign-in.component.spec.ts
  create src\app\sign-in\sign-in.component.ts
Cannot apply a change to a different path.
Error: Cannot apply a change to a different path.
    at MultiChange.appendChange (E:\git\ng2-adminlte\node_modules\@angular-cli\ast-tools\src\change.js:45:19)
    at E:\git\ng2-adminlte\node_modules\@angular-cli\ast-tools\src\change.js:36:86
    at Array.forEach (native)
    at new MultiChange (E:\git\ng2-adminlte\node_modules\@angular-cli\ast-tools\src\change.js:36:45)
    at E:\git\ng2-adminlte\node_modules\@angular-cli\ast-tools\src\ast-utils.js:222:16
    at tryCatch (E:\git\ng2-adminlte\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:195:12)
    at invokeCallback (E:\git\ng2-adminlte\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:210:13)
    at publish (E:\git\ng2-adminlte\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:178:7)
    at flush (E:\git\ng2-adminlte\node_modules\es6-promise\dist\lib\es6-promise\asap.js:94:5)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)

ng version:   
$ ng --version
angular-cli: 1.0.0-beta.19-3
node: 5.0.0
os: win32 ia32

**Comment by Meligy** [comment] 2016-11-17 07:51
Does the same problem happen with just normal Windows command prompt?

The path you give to the generate command is usually relative to `src/app` without you having to indicate it by using `./` or anything. I'm not sure if the `./` scenario is supported at all, but it still shouldn't fail the way you describe.

Please try with normal command prompt to rule away the possibility of MINGW64 doing anything funky.

Thanks.

Cheers,

**Comment by dumyjob** [comment] 2016-11-17 08:26
<code>ng g component ./sign-in</code>,it's work on Windows command,failed on git bash.

**Comment by Meligy** [comment] 2016-11-17 09:56
Oh. This is going to be a tough nut to crack.

My guess is that Git Bash is messing with your input, maybe replacing `/` with `\`, and maybe also sending absolute path (both cases are unusual, but not sure if they fail).

If this is the case, can I ask you to try and wrap the path in single quotes`'`? Like:

```
ng g component './sign-in'
```

If this fails, then try in Windows command line changing `/` to `\`, and if this fail, I'm guessing there'll be a bug for that (whether there is or not, that would be the underlying bug if this is the case).

It might be fixed in latest version already, beta.20-4, but I wouldn't recommend upgrading and testing until https://github.com/angular/angular-cli/pull/3158 is resolved.

**Comment by dumyjob** [comment] 2016-11-18 02:04
At git Bash,
<code>
ng g component './dash'
 </code>
it works,but it generate component at app directory.
the result:
<code>
admin@user MINGW64 /e/git/ng2-admin-lite/src/app/dashboard (master)
$ ng g component './dash'
installing component
  create src\app\dash\dash.component.css
  create src\app\dash\dash.component.html
  create src\app\dash\dash.component.spec.ts
  create src\app\dash\dash.component.ts
</code>
At Windows command,I change <code>/</code> to <code>\</code> . the generate result is same as original.
the result:
<code>
E:\git\ng2-admin-lite\src\app\dashboard>ng g component .\dash
installing component
  create src\app\dashboard\dash\dash.component.css
  create src\app\dashboard\dash\dash.component.html
  create src\app\dashboard\dash\dash.component.spec.ts
  create src\app\dashboard\dash\dash.component.ts
</code>

**Comment by afgane** [comment] 2016-12-01 22:07
I seem to be seeing the same error with the latest release:
```
$ ng --version
angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: darwin x64
```

```
$ ng g module logout
installing module
  create src/app/logout/logout.module.ts
installing component
  create src/app/logout/logout.component.css
  create src/app/logout/logout.component.html
  create src/app/logout/logout.component.spec.ts
  create src/app/logout/logout.component.ts
Cannot apply a change to a different path.
Error: Cannot apply a change to a different path.
    at MultiChange.appendChange (/Users/eafgan/projects/pprojects/launcher/ui/node_modules/@angular-cli/ast-tools/src/change.js:45:19)
    at /Users/eafgan/projects/pprojects/launcher/ui/node_modules/@angular-cli/ast-tools/src/change.js:36:86
    at Array.forEach (native)
    at new MultiChange (/Users/eafgan/projects/pprojects/launcher/ui/node_modules/@angular-cli/ast-tools/src/change.js:36:45)
    at /Users/eafgan/projects/pprojects/launcher/ui/node_modules/@angular-cli/ast-tools/src/ast-utils.js:222:16
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by Meligy** [comment] 2016-12-02 06:25
This output shows beta 20-4. There has been beta 21 for a while and beta 22 should have been available on npm any minute.

**Comment by afgane** [comment] 2016-12-02 17:24
Sill seeing the same error with beta 21.

**Comment by rapPayne** [comment] 2016-12-16 17:19
I experienced the same error after creating a component, deleting that same component via 'rm -r' and then re-creating it. The cause for me was that I didn't remove the reference from app.module.ts. Once I deleted it manually from app.module.ts, ng g myComponent throws no errors. @Meligy, maybe that will give you a clue as to the real source?

**Closed** 2016-12-31 16:56 UTC
Labels: command: generate, priority: 2 (required), type: bug
