### ISSUE TITLE
ng build -prod FAILS with UglifyJs error when targeting ES2015!!

### ISSUE THREAD

**Issue by tx8821** [angular/angular-cli#7149] opened 2017-07-26 13:28 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report
- [ ] feature request
```
### Versions.

Project 1: @angular/cli: 1.1.3
Project 2: @angular/cli: 1.3.0-rc.1

node: 7.10.0
os: win32 x64

**In tsconfig.json: "target": "es2015"**

### Repro steps.

Create new app. Target tsconfig to ES2015. Build with -prod flag. Get the errors.

### The log given by the failure.

ERROR in main.d3a567e3e4474c9592a2.bundle.js from UglifyJs
Unexpected token: name (AppModule) [main.d3a567e3e4474c9592a2.bundle.js:23,6]

### Mention any other details that might be useful.

When I set ES2015 as target in my tsconfig, I can't use -prod flag anymore! Getting UglifyJs errors!
My limited research concludes that Uglify cannot parse ES6, link here: https://github.com/webpack/webpack/issues/2972#issuecomment-261705632

**I need -prod flag, and I need to target ES2015. Am I missing something?**

**Comment by siedentm** [comment] 2017-07-26 14:11
As far as I know UglifyJS does not support es2015.

This is a statement from the UglifyJS Readme:
> Those wishing to minify ES2015+ (ES6+) should use the npm package uglify-es.

**Comment by coryrylan** [comment] 2017-07-26 16:44
What @siedentm said is correct. Currently the CLI does not support ES2015 as an option when compiling modules I believe. The CLI would have to adjust the uglify path dependent on the module type set in the TSConfig.

**Comment by filipesilva** [comment] 2017-07-31 10:50
Duplicate of https://github.com/angular/angular-cli/issues/2907

**Closed by filipesilva** 2017-07-31 10:50 UTC

**Comment by hiepxanh** [comment] 2017-10-12 10:23
hello, I upgrade to angular 5 beta 4 and still get errror  Unexpected token: name (AppModule), what should i do ?
