### ISSUE TITLE
Ng command only works when using sudo

### ISSUE THREAD

**Issue by Owain94** [angular/angular-cli#2510] opened 2016-10-04 20:24 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

MacOS Sierra 10.12.1

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

sw_vers -productVersion
10.12.1

npm --version
3.10.3

node --version
v6.7.0

sudo ng --version
angular-cli: 1.0.0-beta.16
node: 6.7.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Here is a recording I made to show the issue

[https://asciinema.org/a/aqnrpimuf0agzznrq5fp7acss](https://asciinema.org/a/aqnrpimuf0agzznrq5fp7acss)

[![asciicast](https://asciinema.org/a/aqnrpimuf0agzznrq5fp7acss.png)](https://asciinema.org/a/aqnrpimuf0agzznrq5fp7acss)

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
None
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by m44rt3np44uw** [comment] 2016-10-04 20:35
I experience the same problem. #2426

**Comment by RoopeHakulinen** [comment] 2016-10-07 12:01
How long have you waited for it to start since in the video you kill it quite quickly? It will take some time when not ran as sudo. The command itself is answering since there is "command not found" or anything.

**Comment by filipesilva** [comment] 2016-10-10 01:41
Dupe of https://github.com/angular/angular-cli/issues/2426, seems to have a solution in https://github.com/angular/angular-cli/issues/2426#issuecomment-251557545.

**Closed by filipesilva** 2016-10-10 01:41 UTC
