### ISSUE TITLE
THis is the issue i m unable to install angular cli

### ISSUE THREAD

**Issue by pardhasaradhihulk** [angular/angular-cli#12860] opened 2018-11-03 14:16 UTC
![screenshot 1](https://user-images.githubusercontent.com/22253045/47953246-17fd3900-dfa1-11e8-98a2-ef9d634ecb7a.png)

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

**Comment by pardhasaradhihulk** [comment] 2018-11-03 14:17
kindely get solution to this error

i installed node and then installing angular

npm install -g @angular/cli
after that if it is installed correclty or not checking purpose i m using ng -v command it is unable to display the angular cli  picture

**Comment by wvanderdeijl** [comment] 2018-11-03 21:03
Duplicate of #12861

**Closed** 2018-11-04 12:13 UTC
