### ISSUE TITLE
cli: 12.2.0 Error: Transformation map 1 must have exactly one source file.

### ISSUE THREAD

**Issue by sysmat** [angular/angular-cli#21530] opened 2021-08-09 06:54 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was:  12.1.4

## 🔥 Exception or Error

<pre><code>
✔ Browser application bundle generation complete.

Error: Optimization error [main-es2015.580ccf2d9dad4d47d777.js]: Error: Transformation map 1 must have exactly one source file.
Did you specify these with the most recent transformation maps first?
    at buildSourceMapTree (C:\Users\tomaz\Projekti\Gitlab_Arnes\portal-hub\dmsedudoc\frontend\node_modules\@ampproject\remapping\dist\remapping.umd.js:729:23)
    at Object.remapping [as default] (C:\Users\tomaz\Projekti\Gitlab_Arnes\portal-hub\dmsedudoc\frontend\node_modules\@ampproject\remapping\dist\remapping.umd.js:831:23)   
    at default_1 (C:\Users\tomaz\Projekti\Gitlab_Arnes\portal-hub\dmsedudoc\frontend\node_modules\@angular-devkit\build-angular\src\webpack\plugins\javascript-optimizer-worker.js:44:44)
    at async C:\Users\tomaz\Projekti\Gitlab_Arnes\portal-hub\dmsedudoc\frontend\node_modules\piscina\dist\src\worker.js:141:26
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.0
Node: 14.16.0
Package Manager: npm 6.14.11
OS: win32 x64

Angular: 12.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.0
@angular-devkit/build-angular   12.2.0
@angular-devkit/core            12.2.0
@angular-devkit/schematics      12.2.0
@schematics/angular             12.2.0
rxjs                            7.3.0
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-08-09 06:59
Duplicate of https://github.com/angular/angular-cli/issues/21508

**Closed by alan-agius4** 2021-08-09 06:59 UTC

**Comment by sysmat** [comment] 2021-08-09 09:11
is there any solution, from duplicate not working, and it is still closed

**Comment by alan-agius4** [comment] 2021-08-09 09:32
https://github.com/angular/angular-cli/issues/21508#issuecomment-894214200

**Comment by sysmat** [comment] 2021-08-09 09:36
as I wrote it not working

> https://github.com/angular/angular-cli/issues/21508#issuecomment-894214200

**Comment by alan-agius4** [comment] 2021-08-09 09:41
As an interim solution until the next patch release you need to enable vendor sourcemaps in `angular.json`. 

```json
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
    ...
    "sourceMap": {
      "vendor": true
    }
  },
```

See: https://angular.io/guide/workspace-config#source-map-configuration for more information about this option.

**Comment by sysmat** [comment] 2021-08-09 09:47
@alan-agius4 thx, I was using the wrong config for angular.json
