### ISSUE TITLE
Feature request: --stats-json for browser-only bundle

### ISSUE THREAD

**Issue by zip-fa** [angular/angular-cli#28671] opened 2024-10-19 22:52 UTC
### Command

build

### Description

Hi. Currently, --stats-json with application builder generates stats.json file for both server & browser files. Since there are lots of files, it's not possible to determine what end-user will actually download. My proposal is to create separate stats.json file for server and browser chunks or to prefix server chunks somehow (like, server-chunk-xyz.js)

**Comment by alan-agius4** [comment] 2024-10-20 06:34
Duplicate of https://github.com/angular/angular-cli/issues/28185

**Closed by alan-agius4** 2024-10-20 06:34 UTC
