### ISSUE TITLE
`class.name` should be kept when optimizing

### ISSUE THREAD

**Issue by konsultaner** [angular/angular-cli#12887] opened 2018-11-07 08:43 UTC
### Bug Report or Feature Request
```
- [x] bug report
- [x] feature request
```

### Command
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
<pre><code>
Node: 8.10.0
OS: win32 x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.3
@angular-devkit/build-angular      0.10.3
@angular-devkit/build-optimizer    0.10.3
@angular-devkit/build-webpack      0.10.3
@angular-devkit/core               7.0.3
@angular-devkit/schematics         7.0.3
@angular/.cdk.MODULES              <error>
@angular/cdk                       7.0.2
@angular/cli                       7.0.3
@angular/material                  7.0.2
@angular/material-moment-adapter   7.0.2
@ngtools/webpack                   7.0.3
@schematics/angular                7.0.3
@schematics/update                 0.10.3
rxjs                               6.3.3
typescript                         3.1.4
webpack                            4.23.1
</code></pre>

### Repro steps
I've already reported this [issue in the angular/angular](https://github.com/angular/angular/issues/26965) repo. The optimizer reduces the class names and therefore kills reflection based code. It is obviously bad practise to use the classesName to build generic interfaces, but Typescript offers this feature and thus the optimizer should somehow respect it.

I have the following method:

```
public getModelCrudService<T>(modelClass: new () => T): void {
    console.log(modelClass.name);
}
```

calling it in development mode , i.e. `ng server` this code prints the name of whatever class is called. Calling this code in `ng build --prod` the method prints only `t`.

Since this is bad practise I'm not sure if this is a bug report or a feature request. In my opinion the optimizer should set the `modelClass.name` property with the original class name when reducing the class name lengths.

**Comment by alan-agius4** [comment] 2018-11-07 13:00
Duplicate of https://github.com/angular/angular-cli/issues/3861 and https://github.com/angular/angular-cli/issues/11910

**Closed by alan-agius4** 2018-11-07 13:00 UTC

**Comment by keenondrums** [comment] 2019-02-20 12:24
@konsultaner I created a [small custom builder for that](https://github.com/keenondrums/angular-builder-custom-terser-options). Hopefully we won't have to use for a long time and Angular teams adds this functionality at some point to their default builder.
