### ISSUE TITLE
ng g app-shell throws Error "Chunk cannot be found"

### ISSUE THREAD

**Issue by PascalTemel** [angular/angular-cli#8863] opened 2017-12-13 13:52 UTC
### Versions
```
Angular CLI: 1.6.0
Node: 8.4.0
OS: linux x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.1
@angular/cli: 1.6.0
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.5.3
webpack: 3.7.1
```

### Repro steps
* ng new foobar
* import RouterModule
* ng g universal universal
* ng g app-shell fooshell --universal-app universal

### Observed behavior
The following error is thrown
```
Error: Chunk cannot be found.
Chunk cannot be found.
```

### Desired behavior
Guidance towards fixing the error, the error shouldn't occur

**Comment by Brocco** [comment] 2017-12-14 15:03
Closing...
Duplicate of angular/devkit#297

**Closed by Brocco** 2017-12-14 15:03 UTC
Labels: priority: 1 (urgent), severity3: broken

**Comment by khchong** [comment] 2017-12-15 08:18
As a workaround, just delete the lines that import RouterModule (where you import it from @angular/router and also where you inject it in the @NgModule conifg) and let the cli generate them. You can add your route definitions afterwards.
