### ISSUE TITLE
Cli how to override webpack

### ISSUE THREAD

**Issue by yuancongcong** [angular/angular-cli#5196] opened 2017-03-03 09:55 UTC
>Compress the picture
> ---------------------------------------------------------------

### OS?
> node: 6.9.2
os: win32 x64
@angular/common: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.2.4
@angular/platform-server: 2.4.7
@angular/router: 3.0.0

### Repro steps.
> angular-cli.json 
```
  "webpack": {
        "development": {
            "config": "config/webpack.dev.conf.js"
        }, 
        "prod": {
            "config": "config/webpack.prod.conf.js"
        }
    }
```
Why not load it,, load the default configuration

**Comment by filipesilva** [comment] 2017-03-03 14:24
Dupe of https://github.com/angular/angular-cli/issues/1656

**Closed by filipesilva** 2017-03-03 14:24 UTC
