### ISSUE TITLE
ng serve. Apllication in chrome reloads few times

### ISSUE THREAD

**Issue by pavelmorozov** [angular/angular-cli#8195] opened 2017-10-26 11:08 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.9
node: 6.11.5
os: linux x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4

### Repro steps.

setup Ubuntu 16.04
repeat steps described here https://angular.io/guide/quickstart to create new application
install Google chrome Version 62.0.3202.62 (Official Build) (64-bit) and make it default browser

start new application with ng serve --open opens Chrome and application in it, but page reloads few times (the number is random). When I save any my-app source file, chrome reloads and here same few times reload. This not happen with Firefox. It loads application just once.

### The log given by the failure.

Not sure what else I can put here. Ask me if I can help.

### Desired functionality.

I want application page be loaded just one time in chrome, instead of random reloads number. I could use Firefox, though there are a lot of tutorials explain debug process with Chrome browser. This makes hard to debug application.

### Mention any other details that might be useful.

The application as simple as ng new my-app

**Comment by danielrhartman** [comment] 2017-10-26 18:12
I'm seeing a similar issue with a simple hello world type app using Chrome 62.0.3202.62 and Ubuntu 16.04.

**Comment by Quake11rus** [comment] 2017-10-26 19:09
Same on chrome 61 and Mac OS high sierra

**Comment by rakshans1** [comment] 2017-10-27 07:20
Same issue for me too. Setup same as of @danielrhartman

**Comment by alexssource** [comment] 2017-10-27 07:35
Same issue for me too.
Ubuntu 17.10 + Chrome 62.0.3202.62 (Official Build) (64-bit) + Chromium 64.0.3252.0 (Developer Build) (64-bit)

**Comment by filipesilva** [comment] 2017-10-27 14:26
Heya, I tried reproducing this but I didn't see the random number of reloads. Can you tell me what text editors you're using? Also, does this happen with `1.5.0-rc.7`?

**Comment by pavelmorozov** [comment] 2017-10-30 10:22
This looks like not depend on text editor. I tried with Ubuntu gedit, Angular IDE (Eclipse), and MS Visual Studio code. It is all the same.

What is your test set up? Ubuntu version? To confirm this I set up fresh clean Ubuntu on VirtualBox so it is quite strange that you cannot reproduce this.

Sorry cannot test it too much deeper, just not have enough time

**Comment by pietiepb** [comment] 2017-11-02 09:50
I am experiencing the same issue. I am using Centos 7 with webstorm.
If I found time this week I will test 1.5.0-rc.7

**Comment by kovax** [comment] 2017-11-03 10:54
I have this issue with the very same setup as described by @pavelmorozov. To help the investigation I have uploaded the console log after I have killed the 'ng serve'. The http GET is repeated approximately every 2 second.

[localhost-1509706109549.log](https://github.com/angular/angular-cli/files/1440779/localhost-1509706109549.log)

**Comment by dcoli** [comment] 2017-11-08 17:37
Also seeing on Lubuntu with Angular 4 CLI, Chromium, and the Sublime Text editor.

**Comment by dcoli** [comment] 2017-11-08 17:37
I should add this didn't seem to be happening until the last hour or two.

**Comment by pietiepb** [comment] 2017-11-10 16:58
It seems to be disappeared after adding a proper unsubscribe from an observable. I forgot to unsubscribe from an observable that got subscribed on init.
Added the unsubscribe in the OnDestroy and no reloads anymore

**Comment by pavelmorozov** [comment] 2017-11-15 16:20
What file you updated? Can you provide what exactly was changed?

**Comment by kovax** [comment] 2017-11-16 11:05
I am pretty new to all this (Angular/Observable) so please correct me if I am wrong but I think this issue is related to this topic:

https://stackoverflow.com/questions/38008334/angular-rxjs-when-should-i-unsubscribe-from-subscription

**Comment by neeraj2018** [comment] 2018-01-18 15:06
I am experiencing the same issue even on simple 'Hello World' app. Any solution?

**Comment by dcoli** [comment] 2018-01-18 15:54
If you're new at this, you might have node watching your code for updates and automatically compiling. If so, don't initiate a build manually. That will result in two page refreshes.

**Comment by pavelmorozov** [comment] 2018-01-18 16:16
how to not initiate build manually. We use **ng serve** to start application

**Comment by dcoli** [comment] 2018-01-18 16:24
I believe that command automatically builds on save.

What IDE are you using? If you do a simple save of your edits, probably Ctl-s or Cmd-s, it probably won't build. I'm only familiar with sublime and the typescript package, which uses a manual Ctl-b to build.

**Comment by pavelmorozov** [comment] 2018-01-18 16:31
Thanks. I saw this happen with simple text editor like gEdit. Same with VSCode or Eclipse

**Comment by dcoli** [comment] 2018-01-18 16:54
Are you familiar with Observable? Unsubscribing was what worked for me, if
I recall correctly. Not sure if they're used in your Hello, World.

**Comment by pavelmorozov** [comment] 2018-01-18 17:10
The sample application build with
`ng new my-app`
I believe there is no any observables - pretty simple html with @Component template

**Comment by pavelmorozov** [comment] 2018-01-18 17:11
By the way after few updates this issue not disturbes me too much

**Comment by neeraj2018** [comment] 2018-01-19 04:50
It doesn't matter which Editor I am using or if we build the App manually. I just write 'Hello World' without any other Modules, Observable, Unsubscribing. If I am not subscribing anything how come I need to use unsubscribing?

It happened every time I save my edits with Ctrl+s which is very common in any editor. In-actual on save, browser have to refresh single time (to rebuild the app with new changes) but it refresh browser random times (2-10 times). In-fact sometime I have to kill browser's reload manually.

**Comment by alexssource** [comment] 2018-02-01 08:45
I see the problem is only happens in chrome browsers on Linux platform.
My solution is to use the Yandex browser which is build on chrome engine and has the same developer tools

**Comment by filipesilva** [comment] 2019-01-28 16:05
Closing as there haven't been any additional reports for this problem recently, and I cannot reproduce it as well. If you are still experiencing this problem please open a new issue with a reproduction.

**Closed by filipesilva** 2019-01-28 16:05 UTC
Labels: comp: devkit/build-angular

**Comment by satishpatro44** [comment] 2019-04-25 11:50
What I think is you are starting your localhost with https without providing self signed or proper certification. Means, not secured you may be getting in browser URL. WDS(WebPack Dev Servver) Disconnected may be you are getting in Devtools's console. This happnes, if it not secured. May be this problem you are facing
