### ISSUE TITLE
ng new <appname> ... fails when not performed on c:\ drive

### ISSUE THREAD

**Issue by Coderrob** [angular/angular-cli#12845] opened 2018-11-02 02:12 UTC
### Bug Report or Feature Request
```
- [x] bug report
```

### Command
```
- [x] new
```

### Versions
node v10.7.0
npm v6.1.0
ng v7.0.4
Windows 10

### Repro steps

1. Open command prompt
1. Change the disk to a drive other than `c:\`
   - `e:` for example
1. Enter `ng new some-app`
1. Enter `Y` to add Angular routing
1. Scroll down to `SCSS` and hit `Enter`

#### Output:

![ng-new](https://user-images.githubusercontent.com/7213776/47889766-9fb83b80-de19-11e8-9c0e-0eb1927288f9.PNG)

### Mention any other details that might be useful

I have run through and uninstalled global `angular/cli` also verified cache afterwards. I installed it again even using `@latest`. I've installed 10.x and 8.x Node/NPM versions switching back and forth with `nvm` to no avail. 

It seems that the Angular app will be created just fine on a `C:\` but not any other disk. I verified permissions were correct, ran everything as administrator, and could not come up with any reasons why it would fail.

One interesting thing to note is when I ran the `ng new <appname>` on a non-c drive an empty folder named as the drive letter was created at the same directory level. I've reproduced it several times. Otherwise I've only been able to get the `ng new` to work on the `C:\`. 

#### Drive letter folder created:

![drive-letter](https://user-images.githubusercontent.com/7213776/47890027-f5d9ae80-de1a-11e8-95ea-9f04867ddd32.PNG)

#### Working on `C:\`:

![ng-new-on-c](https://user-images.githubusercontent.com/7213776/47889887-40a6f680-de1a-11e8-81f8-d2d71579579f.PNG)

**Comment by alan-agius4** [comment] 2018-11-02 06:32
Duplicate of https://github.com/angular/angular-cli/issues/12670

**Closed by alan-agius4** 2018-11-02 06:32 UTC
