### ISSUE TITLE
ng serve error: no such file or directory

### ISSUE THREAD

**Issue by HansS** [angular/angular-cli#408] opened 2016-04-08 07:57 UTC
Hans@HP-HANS C:\Users\Hans\Web\js\angular20\angular-cli
> cd books

Hans@HP-HANS C:\Users\Hans\Web\js\angular20\angular-cli\books
> ng serve

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See www.ember-cli.com/user-guide/#windows for details.

ENOENT: no such file or directory, open 'C:\Users\Hans\Web\js\angular20\angular-cli\books\src\client\tsconfig.json'
Error: ENOENT: no such file or directory, open 'C:\Users\Hans\Web\js\angular20\angular-cli\books\src\client\tsconfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Angular2App.toTree.Angular2App._getTsTree (C:\Users\Hans\Web\js\angular20\angular-cli\books\node_modules\angular-cli\lib\broccoli\angular2-app.js:229:32)
    at Angular2App.toTree (C:\Users\Hans\Web\js\angular20\angular-cli\books\node_modules\angular-cli\lib\broccoli\angular2-app.js:37:21)
    at module.exports (C:\Users\Hans\Web\js\angular20\angular-cli\books\angular-cli-build.js:9:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\Hans\Web\js\angular20\angular-cli\books\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\Hans\Web\js\angular20\angular-cli\books\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\Hans\Web\js\angular20\angular-cli\books\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Users\Hans\Web\js\angular20\angular-cli\books\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)

Hans@HP-HANS C:\Users\Hans\Web\js\angular20\angular-cli\books

**Comment by PascalPrecht** [comment] 2016-04-08 12:39
This is a dupe of https://github.com/angular/angular-cli/issues/402

**Comment by Brocco** [comment] 2016-04-08 12:43
@PascalPrecht is correct, you can find more info for fixing this [here](https://github.com/angular/angular-cli/issues/402#issuecomment-207418306)

**Closed by Brocco** 2016-04-08 12:43 UTC

**Comment by markjritchie** [comment] 2016-04-11 13:03
I ran:
 `ng new funds` (still can't generate the ambient typings)
`cd funds`
`ng test`
and received:

`BuildingENOENT: no such file or directory, open 'D:\EOX2\funds\src\client\tsconfig.json'
Error: ENOENT: no such file or directory, open 'D:\EOX2\funds\src\client\tsconfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Angular2App.toTree.Angular2App._getTsTree (D:\EOX2\funds\node_modules\angular-cli\lib\broccoli\angular2-app.js:22 9:32)
    at Angular2App.toTree (D:\EOX2\funds\node_modules\angular-cli\lib\broccoli\angular2-app.js:37:21)
    at module.exports (D:\EOX2\funds\angular-cli-build.js:9:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\EOX2\funds\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\EOX2\funds\node_modules\angular-cli\node_modules\angular-cli\lib\models
\builder.js:89:10)
    at new Class (D:\EOX2\funds\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\EOX2\funds\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build.js:15:19)`

There wasn't any client directory created under app. I', logging this here as the other is closed
