### ISSUE TITLE
new Worker() doesn't work from a library

### ISSUE THREAD

**Issue by HazzMan2409** [angular/angular-cli#29225] opened 2024-12-24 11:55 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Creating a new worker with the

```ts
new Worker(new URL('<workerfile>', import.meta.url))
```

syntax doesn't work from within a library in node_modules.

Also see https://github.com/angular/angular-cli/issues/26991, it is not fixed.

### Minimal Reproduction

https://github.com/HazzMan2409/ng-worker-issue/tree/main

### Exception or Error

```text

```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 19.0.6
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 19.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.6
@angular-devkit/build-angular   19.0.6
@angular-devkit/core            19.0.6
@angular-devkit/schematics      19.0.6
@angular/cli                    19.0.6
@schematics/angular             19.0.6
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by alan-agius4** [comment] 2024-12-28 13:30
Duplicate of https://github.com/angular/angular-cli/issues/28994

**Closed by alan-agius4** 2024-12-28 13:30 UTC
