### ISSUE TITLE
How install module crypto ?

### ISSUE THREAD

**Issue by pogran** [angular/angular-cli#6009] opened 2017-04-19 10:04 UTC

**Comment by deebloo** [comment] 2017-04-19 13:23
@pogran please fill out the issue template

**Comment by choucry13** [comment] 2017-04-20 07:20
https://www.npmjs.com/package/npmdoc-angular-crypto may help you.

**Comment by filipesilva** [comment] 2017-05-05 15:37
Dupe of https://github.com/angular/angular-cli/issues/1548

**Closed by filipesilva** 2017-05-05 15:37 UTC

**Comment by agabardo** [comment] 2018-12-16 17:10
Why close a topic if the answer in the other topic mentioned don't actually cover the issue?
This Crypto library is by far the messiest thing I ever encountered in Angular.
