### ISSUE TITLE
[Feature Request] ng add with --save-dev option

### ISSUE THREAD

**Issue by rajeshtezu90** [angular/angular-cli#25026] opened 2023-04-16 14:10 UTC
### Command

add

### Description

Currently we don't have any cli option to add an external library as a dev dependency with `ng add` command.

### Describe the solution you'd like

There seems to be an option to configure how we want to add dependency but the config is through the `package.json` file as specified in [this PR](https://github.com/angular/angular-cli/pull/15815) and it will apply to all the libs being added using `ng add` command but it will be nice to have cli option such as `ng add --save-dev [name]` or something similar.

### Describe alternatives you've considered

Workaround is the solution provided in [this PR](https://github.com/angular/angular-cli/pull/15815) but it would be nicer to have the solution as a cli flag.

**Comment by rajeshtezu90** [comment] 2023-04-20 08:04
Ah I see,  while adding `@angular-devkit/build-angular` it is getting added in the `dependencies` section which would make more sense in the the `devDependencies`. I checked the [package.json](https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/package.json) file in the `@angular_devkit/build_angular` and it does not contain `"ng-add"` so, default location might be `dependencies`.

**Comment by rajeshtezu90** [comment] 2023-04-20 08:09
Ah I see,  while adding `@ngrx/store-devtools` it is getting added in the `dependencies` section which would make more sense in the the `devDependencies`. I checked the [package.json](https://github.com/ngrx/platform/blob/master/modules/store-devtools/package.json) file in the `@ngrx/store-devtools` and it does not contain `"ng-add"` so, default location might be `dependencies`.

**Comment by alan-agius4** [comment] 2023-04-20 10:28
Hi @rajeshtezu90, I suggest that you file an issue with the NGRX team. 

Although, in this case the mentioned package is somewhat correct to be listed as a dependency, as this is not a build tool which is only needed for development. The `@ngrx/store-devtools` package is part of your application bundle that is also including on production.

Closing as this is working as intended on the Angular CLI side.

**Closed by alan-agius4** 2023-04-20 10:28 UTC
