### ISSUE TITLE
cli fails to create new project when target of '--collection' flag is a symlink

### ISSUE THREAD

**Issue by blkdog** [angular/angular-cli#9094] opened 2018-01-04 17:20 UTC
### Versions
```
Angular CLI: 1.6.3
Node: 6.9.1
OS: darwin x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.3
@angular/cli: 1.6.3
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.0.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
* Step 1
create a new schematics project, I will call it `@c3/angular` (or copy from @angular/dev-kit) and link it into the global install.

** Alternatively you can globally install the package & then link**

`cd {package_dir}`
`npm link`
* Step 2
Install @angular/cli tool via npm @ link to your custom schematics package
`npm install @angular/cli`
`cd {@angular/cli}`
`npm link @c3/angular`
* Step 3
run the cli tool
`ng new --collection=@c3/angular myapp`

### Observed behavior
`ng new --collection=@c3/angular myapp`
`Cannot find module '/Users/u0081009/.nvm/versions/node/v6.9.1/lib/node_modules/@c3/angular/application'
Error: Cannot find module '/Users/u0081009/.nvm/versions/node/v6.9.1/lib/node_modules/@c3/angular/application'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at new ExportStringRef (/Users/u0081009/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js:15:32)
    at NodeModulesEngineHost._resolveReferenceString (/Users/u0081009/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:61:21)
    at NodeModulesEngineHost.createSchematicDescription (/Users/u0081009/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:151:34)
    at SchematicEngine.createSchematic (/Users/u0081009/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:82:40)
    at CollectionImpl.createSchematic (/Users/u0081009/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/collection.js:11:29)
    at Object.getSchematic (/Users/u0081009/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/utilities/schematics.js:45:23)
    at Class.run (/Users/u0081009/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/tasks/schematic-get-options.js:12:40)
    at Class.beforeRun (/Users/u0081009/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/commands/new.js:91:31)`

If I then unlink & uninstall (globally) the @c3/angular schematic package & install it directly into the @angular/cli ...
`npm uninstall -g @c3/angular`
`cd {@angular/cli}`
`npm install @c3/angular` <- install local to project

everything works & I get my custom project ... :)

### Desired behavior
I would like to be able to do local development on custom schematic packages & be able to link them into the @angular/cli via the --collection tag

### Mention any other details that might be useful (optional)
I use .nvm to manage my node installs, but that doesn't seem to matter, ..

**Comment by clydin** [comment] 2018-01-04 17:52
This issue appears to be a duplicate of https://github.com/angular/devkit/issues/351. Please follow that issue for further updates.

**Closed by clydin** 2018-01-04 17:52 UTC
