### ISSUE TITLE
Error: Transform failed with 1 error: Unexpected "\xe7" on Windows platform

### ISSUE THREAD

**Issue by Quentame** [angular/angular-cli#23726] opened 2022-08-11 13:30 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 11

### Description

Originally from an Angular 10 project, I bumped it to 11, and now I'm trying 12.
But I am having an error from `esbuild`, `Unexpected "\xe7"`,  when `npm run build [or serve]` (see the log bellow).

I searched for the suspected character "\xe7", and I found "ç" (https://www.compart.com/en/unicode/U+00E7).
I looked for those in the project, and not iteration of it were found in the project (some in the `node_modules`).

The odd thing is: It is not working on my dev platform `OS: win32 x64`, but working on GitLab CI `OS: linux x64`

I tried to update as best as possible, mostly using https://update.angular.io/ , release notes and migration guides (https://v11.angular.io/guide/updating-to-version-11 + https://v12.angular.io/guide/updating-to-version-12).
Maybe I forgot something ?

## 🔬 Minimal Reproduction

Unfortunatly the project is private and I don't know yet how to reproduce, sorry.

## 🔥 Exception or Error

```shell
√ Browser application bundle generation complete.

Error: Optimization error [main-es2017.js]: Error: Transform failed with 1 error:
main-es2017.js:1:0: error: Unexpected "\xe7"
    at failureErrorWithLog (C:\dev\workspace\voc-ihm\node_modules\esbuild\lib\main.js:1493:15)
    at C:\dev\workspace\voc-ihm\node_modules\esbuild\lib\main.js:1282:29
    at C:\dev\workspace\voc-ihm\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\dev\workspace\voc-ihm\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (C:\dev\workspace\voc-ihm\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

## 🌍 Your Environment

On my dev machine, which is having the issue
```shell
$ npx ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.2.18
Node: 14.20.0
Package Manager: npm 7.24.2
OS: win32 x64

Angular: 12.2.16
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.18
@angular-devkit/build-angular   12.2.18
@angular-devkit/core            12.2.18
@angular-devkit/schematics      12.2.18
@angular/cli                    12.2.18
@schematics/angular             12.2.18
rxjs                            6.6.7
typescript                      4.3.5

```

On GitLab CI machine, where there is no issue
```shell
$ npx ng version
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    
Angular CLI: 12.2.18
Node: 14.20.0
Package Manager: npm 7.24.2
OS: linux x64
Angular: 12.2.16
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.18
@angular-devkit/build-angular   12.2.18
@angular-devkit/core            12.2.18
@angular-devkit/schematics      12.2.18
@angular/cli                    12.2.18
@schematics/angular             12.2.18
rxjs                            6.6.7
typescript                      4.3.5
```
**Anything else relevant?**

`package.json` dependencies, maybe I miss an update
```json
  "dependencies": {
    "@angular/animations": "~12.2.16",
    "@angular/common": "~12.2.16",
    "@angular/compiler": "~12.2.16",
    "@angular/core": "~12.2.16",
    "@angular/forms": "~12.2.16",
    "@angular/localize": "^12.2.16",
    "@angular/platform-browser": "~12.2.16",
    "@angular/platform-browser-dynamic": "~12.2.16",
    "@angular/router": "~12.2.16",
    "@ng-bootstrap/ng-bootstrap": "^10.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "angular-svg-icon": "^10.0.0",
    "bootstrap": "^4.3.1",
    "focus-visible": "^5.1.0",
    "font-awesome": "^4.7.0",
    "jquery": "^3.6.0",
    "ng-boosted": "^10.3.0",
    "ngx-quill": "^14.3.0",
    "node-sass": "^4.14.1",
    "popper.js": "^1.16.1",
    "quill": "^1.3.7",
    "quill-image-drop-module": "^1.0.3",
    "quill-image-resize-module": "^3.0.0",
    "ramda": "^0.27.1",
    "remove-accents": "^0.4.2",
    "rxjs": "~6.6.7",
    "swiper": "^8.3.2",
    "tablesorter": "^2.31.3",
    "tsconfig-paths": "^3.9.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.7"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.2.18",
    "@angular/cli": "~12.2.18",
    "@angular/compiler-cli": "~12.2.16",
    "@angular/language-service": "~12.2.16",
    "@typescript-eslint/eslint-plugin": "^4.4.1",
    "@typescript-eslint/parser": "^4.5.0",
    "commitizen": "^4.2.4",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^7.2.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-config-airbnb-typescript": "^12.0.0",
    "eslint-config-prettier": "^6.13.0",
    "eslint-import-resolver-typescript": "^2.3.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-typescript-sort-keys": "^1.5.0",
    "prettier": "^2.1.2",
    "ts-node": "^7.0.1",
    "typescript": "~4.3.5"
  },
```

Seen issue #23030 but it doesn't seem the same thing.

Maybe I should also create an issue on `esbuild` ?

**Comment by alan-agius4** [comment] 2022-08-11 13:54
@Quentame, without a reproduction it's hard to tell if the issue has been fixed in esbuild or not. A lot has changed since esbuild since 0.14.10. 

There are a couple of ways you can test if this issue has already been addressed.

1) Update esbuild to the latest version, you can use [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to do this. 
2) Update to Angular and Angular CLI 14.1.

If the problem persists please provide a simple repository reproducing the problem. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by Quentame** [comment] 2022-08-11 14:09
I forgot to add, but `esbuild` version is `0.13.8`, a dep from `@angular-devkit/build-angular`.

OK, I'm trying to update more.

**Comment by alan-agius4** [comment] 2022-08-23 13:46
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Closed by alan-agius4** 2022-08-23 13:46 UTC
Labels: need: repro steps
