### ISSUE TITLE
Production build stuck on 92% build optimization

### ISSUE THREAD

**Issue by tbnovaes** [angular/angular-cli#14751] opened 2019-06-12 20:55 UTC
# 🐞 Bug report

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Previous versions were already slow, but this latest version is completely breaking my build.

### Description

It's impossible to build the project for production without using 

`node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod` and even using it the build get stuck on 92% for several minutes. (setting `--optimization=false`) reduces the time significantly.

Also in my case the application is building twice in a row. I'm trying to generate a docker image and the same Dockerfile I was using before it not working anymore.

## 🔬 Minimal Reproduction
Hard to reproduce since it mostly affect medium or large applications.

Easiest way is to build with --optimization set to `true` and to `false` and see the huge difference in time.

## 🌍 Your Environment
```
Angular CLI: 8.0.0
Node: 12.3.1
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.0
@angular-devkit/core         8.0.0
@angular-devkit/schematics   8.0.0
@schematics/angular          8.0.0
@schematics/update           0.800.0
rxjs                         6.4.0
```

**Comment by alan-agius4** [comment] 2019-06-13 05:26
Hi, this might related to https://github.com/angular/angular-cli/issues/14505

**Comment by alan-agius4** [comment] 2019-06-13 05:34
Hi, this might be a duplicate of https://github.com/angular/angular-cli/issues/14505

**Comment by tbnovaes** [comment] 2019-06-13 14:14
I'm not using any dependency that could cause this type of issue. Here are my package.json dependencies.

```
"dependencies": {
    "@agm/core": "^1.0.0-beta.6",
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.1",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "^8.0.0",
    "@angular/http": "^7.2.15",
    "@angular/material": "^8.0.1",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/pwa": "^0.800.2",
    "@angular/router": "^8.0.0",
    "@angular/service-worker": "^8.0.0",
    "@auth0/angular-jwt": "^2.1.0",
    "@ngrx/effects": "^8.0.0",
    "@ngrx/entity": "^8.0.0",
    "@ngrx/router-store": "^8.0.0",
    "@ngrx/store": "^8.0.0",
    "@ngrx/store-devtools": "^8.0.0",
    "airbrake-js": "^1.6.8",
    "angulartics2": "^7.5.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.6.9",
    "cross-fetch": "^3.0.4",
    "google-libphonenumber": "^3.2.2",
    "hammerjs": "^2.0.8",
    "highcharts": "^7.1.2",
    "highcharts-angular": "^2.4.0",
    "humanize-duration": "^3.18.0",
    "js-marker-clusterer": "^1.0.0",
    "leaflet": "1.4.0",
    "leaflet-fullscreen": "^1.0.2",
    "leaflet-search-control": "^2.0.5",
    "luxon": "^1.16.0",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.25",
    "ngx-avatar": "^3.7.0",
    "ngx-content-loading": "^0.1.3",
    "prunecluster": "^2.1.0",
    "rxjs": "^6.5.2",
    "socket.io-client": "^2.2.0",
    "tslib": "^1.9.0",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.2",
    "@angular-devkit/build-ng-packagr": "^0.800.2",
    "@angular/cli": "^8.0.2",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@ngrx/schematics": "^8.0.0",
    "@types/hammerjs": "^2.0.36",
    "@types/jasmine": "^3.3.13",
    "@types/jasminewd2": "^2.0.6",
    "@types/luxon": "^1.15.1",
    "@types/moment": "^2.13.0",
    "@types/moment-timezone": "^0.5.12",
    "@types/node": "^12.0.7",
    "@types/socket.io-client": "^1.4.32",
    "codelyzer": "^5.1.0",
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "ng-packagr": "^5.3.0",
    "node-sass": "^4.12.0",
    "protractor": "^5.4.2",
    "standard-version": "^6.0.1",
    "ts-node": "^8.2.0",
    "tsickle": "^0.35.0",
    "tslib": "^1.9.0",
    "tslint": "^5.17.0",
    "typescript": "^3.5.1"
  }
```

Build Time: 127567ms / 129690ms => Typescript 3.4.5
Build Time: 134870ms / 169316ms => Typescript 3.5.1

However, it became impossible to compile it on Docker, it gets stuck on the 92% for several minutes, then it is like angular is silently failing the build and docker jumps to the next step without creating the bundle for the app.

Also still getting the strange behavior of app being compiled twice in a row. Compilation finishes, and automatically start a second run, that takes longer than the first one (as you can see on the build times I posted above)

Here is my Dockerfile

```
### STAGE 1: Build ###
FROM node:12.3.1-alpine as builder

COPY package.json package-lock.json ./

RUN yes | npm i --only=production && npm i @angular/cli && mkdir -p /usr/src/app && mv ./node_modules /usr/src/app

WORKDIR /usr/src/app

COPY . .

RUN npm run build:libs
RUN npm run build:app

### STAGE 2: Setup ###
FROM nginx:alpine

COPY nginx/default.conf /etc/nginx/conf.d/
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 4200
```

Here is what happens when Docker is compiling:

```
92% additional asset processing
 92% additional asset processing scripts-webpack-plugin
 92% chunk asset optimization
 92% chunk asset optimization LicenseWebpackPlugin

 92% chunk asset optimization cleancss-webpack-plugin

 92% chunk asset optimization TerserPlugin
Removing intermediate container 483af9e22a7d

 ---> 4878c081f28f
```

Here is the final build (as you can see libs were compiled, but the app wasn't and is not present on the dist folder)
```
Step 14/14 : RUN ls /usr/share/nginx/html


 ---> Running in 39d7629e7728

directives
intl-phone-input
models
pipes
utils
websocket
```

**Comment by alan-agius4** [comment] 2019-06-19 07:40
> Also still getting the strange behavior of app being compiled twice in a row. Compilation finishes, and automatically start a second run, that takes longer than the first one (as you can see on the build times I posted above)

The double builds are caused by differential loading which is a new Angular CLI feature which you can read about this here:  https://angular.io/guide/deployment#differential-loading

With regards to the memory issue, i think it's best to keep it tracked in a single threat that is https://github.com/angular/angular-cli/issues/13734#issuecomment-500849058

**Closed by alan-agius4** 2019-06-19 07:40 UTC
Labels: comp: devkit/build-optimizer, need: more info

**Comment by tbnovaes** [comment] 2019-06-19 13:39
@alan-agius4 thank you!
