### ISSUE TITLE
index html generator converts tags to html entities after angular 12 upgrade

### ISSUE THREAD

**Issue by edinfor** [angular/angular-cli#21585] opened 2021-08-16 21:26 UTC
# 🐞 Bug report

We are currently pointing our index file to index.jsp file and have the following parameters to setup the page, but after angular 12 upgrade, angular build automatically converts the tags to html entities and broke the page from rendering properly.

```
<%@ include file="/example/header.jsp" %>
<%@ page import="com.example.helper" %>
```

becomes 

```
&lt;%@ include file="/example/header.jsp" %&gt;
&lt;%@ page import="com.example.helper" %&gt;

```

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Yes, previously on angular 11.2.12 without problem.

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre>Angular CLI: 12.2.1
Node: 16.6.2 (Unsupported)
Package Manager: yarn 1.22.10
OS: win32 x64

Angular: 12.2.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.1
@angular-devkit/build-angular   12.2.1
@angular-devkit/core            12.2.1
@angular-devkit/schematics      12.2.1
@schematics/angular             12.2.1
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.3.5
<code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-08-16 21:39
Duplicate of https://github.com/angular/angular-cli/issues/21462

**Closed by alan-agius4** 2021-08-16 21:39 UTC
