### ISSUE TITLE
Module parse failed: Unexpected token (1:0)

### ISSUE THREAD

**Issue by GlauberF** [angular/angular-cli#18939] opened 2020-05-27 11:52 UTC
# 🐞 bug report

### Affected Package
@angular/....

### Description
I'm getting an error, which for me has no logic.
Since the form being written for this component is the same as the one written in others, however the error happens only in 1 component

## 🔬 Minimal Reproduction
https://we.tl/t-8aOej6GxM5

## 🔥 Exception or Error
```
WARNING in ./src/@vimbo/components/dynamic-component/dynamic-component.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <ng-container *ngIf="_components">
|     <ng-container *ngFor="let component of _components; trackBy: ( '_id' | trackByVimbo )">
|         <ng-template
: Compiled successfully.
```
![Captura de Tela_selecionar área_20200527085159](https://user-images.githubusercontent.com/11314585/83015784-56c96880-9ff7-11ea-9fb7-26e3af7b1613.png)

## 🌍  Your Environment

```
Angular CLI: 9.1.5
Node: 12.16.3
OS: linux x64

Angular: 9.1.4
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.5
@angular-devkit/build-angular      0.901.5
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.5
@angular-devkit/core               9.1.5
@angular-devkit/schematics         9.1.5
@angular/cdk                       9.2.2
@angular/cli                       9.1.5
@angular/compiler-cli              9.1.6
@angular/flex-layout               9.0.0-beta.29
@angular/language-service          9.1.6
@angular/material                  9.2.2
@angular/material-moment-adapter   9.2.2
@ngtools/webpack                   9.1.5
@nguniversal/builders              9.1.1
@nguniversal/common                9.1.0
@nguniversal/express-engine        9.1.0
@schematics/angular                9.1.5
@schematics/update                 0.901.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
```

**Comment by JoostK** [comment] 2020-09-30 13:07
Moving to CLI for better support, as this is not a framework issue.

**Comment by alan-agius4** [comment] 2020-09-30 13:47
Duplicate of https://github.com/angular/angular-cli/issues/14855#issuecomment-510592634

**Comment by GlauberF** [comment] 2020-09-30 19:44
This worries me (https://github.com/angular/angular-cli/issues/14855#issuecomment-510592634) @alan-agius4  why do I use to dynamically import component webpack annotations and you commented:

> Webpack specific features may not work in the future

**Comment by alan-agius4** [comment] 2020-09-30 19:55
Being able to require an HTML file is really a Webpack thing, in  ppJavaScript this doesn’t work.

**Closed** 2020-09-30 19:55 UTC

**Comment by alan-agius4** [comment] 2020-09-30 19:59
Being able to require an HTML file is really a Webpack thing, in JavaScript this doesn’t work because an HTML file is not a JS module.

The fact that the Angular CLI uses webpack is an implementation detail which might change in the future. Also, any webpack specific feature which currently works might break without warning in future versions of Angular CLI.
