### ISSUE TITLE
New project needs npm regardless of yarn is set as package manager

### ISSUE THREAD

**Issue by absrd** [angular/angular-cli#11828] opened 2018-08-09 10:04 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: v8.11.3
yarn: 1.9.4
ng:
```
Angular CLI: 6.1.2
Node: 8.11.3
OS: linux x64
Angular: 6.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.2
@angular-devkit/build-angular     0.7.2
@angular-devkit/build-optimizer   0.7.2
@angular-devkit/build-webpack     0.7.2
@angular-devkit/core              0.7.2
@angular-devkit/schematics        0.7.2
@ngtools/webpack                  6.1.2
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
```
Arch Linux x64

### Repro steps

```

ng new flexi
cd flexi
ng update --all
```

```
### The log given by the failure
<!-- Normally this include a stack trace and some more information. -->
/home/fk/workspace/flexi/node_modules/@schematics/update/update/npm.js:44
                throw error;
                ^

Error: Command failed: npm get @types:registry
/bin/sh: npm: command not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)

```

### Desired functionality

Shouldn't need npm.

### Mention any other details that might be useful

Have an older project running without npm

**Comment by hansl** [comment] 2018-08-15 22:13
Duplicate of #11694.

**Closed by hansl** 2018-08-15 22:13 UTC
Labels: comp: angular/cli, freq2: medium, severity3: broken, type: bug/fix
