### ISSUE TITLE
ng new projName --service-worker doesn't work

### ISSUE THREAD

**Issue by markgoho** [angular/angular-cli#10229] opened 2018-04-08 01:35 UTC
### Versions
``` bash
Angular CLI: 6.0.0-rc.2
Node: 8.9.3
OS: win32 x64
Angular: 6.0.0-rc.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 6.0.0-rc.2
@angular-devkit/architect: 0.5.4
@angular-devkit/build-angular: 0.5.4
@angular-devkit/build-optimizer: 0.5.4
@angular-devkit/core: 0.5.4
@angular-devkit/schematics: 0.5.4
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-rc.2.4
@schematics/angular: 0.5.4
@schematics/update: 0.5.4
typescript: 2.7.2
webpack: 4.5.0
```

### Repro steps
* `ng new projectName --service-worker`

### Observed behavior
no service worker in `package.json`
no flag set in `angular.json`

### Desired behavior
this should function similar to how 1.7.3 worked

### Mention any other details that might be useful (optional)
Probably related to #10198

**Comment by filipesilva** [comment] 2018-04-10 20:25
Heya, I think this is mostly a dupe of https://github.com/angular/angular-cli/issues/10042 now that I'm looking at it more closely.

**Closed by filipesilva** 2018-04-10 20:25 UTC
Labels: 6.0.0-rc
