### ISSUE TITLE
ng build --prod --aot --output-hashing none stuck at chunk asset optimization after Angular V 5 upgrade

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular-cli#8344] opened 2017-11-04 15:05 UTC
After Upgrading to Angular Version 5 the aot compilation seems to be stuck at 92 % chunk Optimisation for ages.
and Completes after a full 4 mins
```
Date: 2017-11-03T13:54:26.604Z
Hash: 35cf6c5f7a300435f807
Time: 222890ms
chunk {0} 0.chunk.js () 16.7 kB  [rendered]
chunk {1} main.bundle.js (main) 2.56 MB [initial] [rendered]
chunk {2} polyfills.bundle.js (polyfills) 63.8 kB [initial] [rendered]
chunk {3} styles.bundle.css (styles) 296 kB [initial] [rendered]
chunk {4} inline.bundle.js (inline) 1.36 kB [entry] [rendered]
```
Any reason for this slowness

**Comment by shusson** [comment] 2017-11-06 02:30
I'm seeing the same thing

**Comment by finalxcode** [comment] 2017-11-06 07:00
me too

**Comment by rametta** [comment] 2017-11-06 21:01
Me too, mine sometimes >7mins

**Comment by rahulrsingh09** [comment] 2017-11-07 04:58
I asked some one from the Angular team they are telling as build optimiser is enabled by default this is causing the prod build to be slower

**Comment by wuzhouyang** [comment] 2017-11-09 07:22
Yes, me too. But as the result I have got a smaller bundles.

**Comment by theunreal** [comment] 2017-11-20 11:40
Same here. 
 just using `ng build --prod`. Angular & Angular-cli 5 final.

**Comment by codech3ry** [comment] 2017-12-01 02:31
I'm facing the same issue and its the same with --build-optimizer=false

**Comment by lakshmanavula** [comment] 2017-12-04 09:45
Yes, me too, It is taking 2-3 min simple project and In the lager project taking 10+ Min

**Comment by filipesilva** [comment] 2017-12-07 16:37
Heya all,

With 1.5, `--build-optimizer` is turned on by default on production builds. It does make them slower but should result is smaller bundles.

There were some memory problems that we have meanwhile fixed. Can you try using 1.6.0 instead?

**Comment by theunreal** [comment] 2017-12-07 17:03
Thanks @filipesilva, I will check the performance of 1.6.0 against 1.5.0 without the build optimizer and will share the result here.

**Comment by theunreal** [comment] 2017-12-11 12:32
@filipesilva This build --prod is still extremely slow,
Time: 261184ms

**Comment by elvirdolic** [comment] 2017-12-12 20:03
@theunreal how large is your app? Our build is much slower. 

Time: 597079ms
Angular CLI: 1.6.0
Node: 8.9.0
OS: win32 x64
Angular: 5.1.0

**Comment by NikolaosWakem** [comment] 2017-12-14 11:11
Angular CLI: 1.6.1
Node: 7.8.0
OS: win32 x64
Angular: 5.1.1

Our project went from a few minutes to 27.5 minutes for  

ng build --prod --output-hashing none

**Comment by zoharyosef** [comment] 2017-12-31 13:00
Also on our project
ng build --prod
Angular 5.1.1
On the dev machine it takes about 4 mins.
On the build server it takes more than an hour.

Thanks

**Comment by elvirdolic** [comment] 2018-01-21 21:32
@zoharyosef 

we have since 1.6.5 the same issue. ON build server it takes now 30 minutes and on dev machine ng build --prod takes 5 minutes

Did you find out something?

**Comment by Sathishchary** [comment] 2018-02-21 16:56
I am also facing same problem here. ng build --prod is taking more than 15 mints to build the project.  I am  using 
cli : 1.7.0
angular :5.2.0
node: 6.9.1
os: windows 10 
thanks

**Comment by abhinavJai** [comment] 2018-03-08 08:05
if you want to speedup the build process then you have to increase the memory.

For making build faster in production, we need to set the memory size in local machine
Steps 1:-               C:\Users\<username>\AppData\Roaming\npm  
Steps 2:-               Replace the ng.cmd file(attached here)

So by doing this, it will rectify “Java Script heap out of memory”  error as well.


![aaa](https://user-images.githubusercontent.com/37173226/37139864-8b1db038-22d5-11e8-9778-7c0207e8fb85.jpg)

**Comment by vinayakshukre** [comment] 2018-03-21 10:46
How to do these settings on linux machine ? I can see below code in /usr/bin/npm file, 

![image](https://user-images.githubusercontent.com/7592284/37705765-19a440d6-2d23-11e8-9e50-d20b5b512dd0.png)

and below code in /usr/bin/ng file

![image](https://user-images.githubusercontent.com/7592284/37705806-388ffae4-2d23-11e8-86bd-f01a563dce56.png)

It is taking more than 60 minutes for my ng build --prod command.

**Comment by vinayakshukre** [comment] 2018-03-29 09:11
Adding following in package.json caused build time to improve. Now same build happens in less than 20 minutes. I increased memory to 12 GB

 "scripts": {
    "build": "node --max_old_space_size=12288 ./node_modules/@angular/cli/bin/ng build --prod"
}

**Comment by rightisleft** [comment] 2018-05-08 22:12
This is pretty bad - simple bootstrap application with under 10 components takes 6 minutes when adding --prod 

```
8 x core : Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
```

```
Date: 2018-05-08T21:58:53.162Z
Hash: 8c7031545fe5681c541f
Time: 385794ms
chunk {0} main.0dacfdf444f92476e7b7.bundle.js (main) 3.31 MB [initial] [rendered]
chunk {1} polyfills.3b62166b1130a1e3b571.bundle.js (polyfills) 59.8 kB [initial] [rendered]
chunk {2} styles.65b4dbcde2c74fed70b8.bundle.css (styles) 285 kB [initial] [rendered]
chunk {3} inline.02c5a2b14b98749c9aca.bundle.js (inline) 804 bytes [entry] [rendered]
[END] WEB COMPILER STEPS
[END] CORE COMPILER STEPS
[go] Task status: passed, took: 7m 17.240s
[go] Current job status: passed
```

**Comment by clabough** [comment] 2018-05-09 15:27
If you're stuck at 92%, try commenting out any `[styleUrls]` in your components and see if that makes a difference. I was experiencing that and switched to linked stylesheets because when I removed my [styleUrls], it completed the build.

**Comment by migerusantte** [comment] 2018-06-13 14:15
I was having the same issue (my build was stuck at 92% and taking around 18 minutes to complete...)
I increased memory allocation for node and also disabled some options in the build command this way:

node --max_old_space_size=5048 "%~dp0\..\@angular\cli\bin\ng" build  --prod  --sourcemaps false --build-optimizer false --aot false

This way my build only takes 33 seconds.
Hope this help you pass that 92% chunk optimization faster.

**Comment by harshasaha** [comment] 2018-06-25 09:45
@abhinavJai........ Thank you it works for me.

**Comment by filipesilva** [comment] 2019-01-28 16:07
Closing as there haven't been any additional reports for this problem recently, and I cannot reproduce it as well. If you are still experiencing this problem please open a new issue with a reproduction.

**Closed by filipesilva** 2019-01-28 16:07 UTC
Labels: comp: devkit/build-angular, need: more info
