### ISSUE TITLE
ng update: `unable to get local issuer certificate` error during update

### ISSUE THREAD

**Issue by RanadeepPolavarapu** [angular/angular-cli#10669] opened 2018-05-05 17:58 UTC
### Versions
```
Angular CLI: 6.0.0
Node: 10.0.0
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core
... forms, http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/cdk                      5.2.5
@angular/cli                      6.0.0
@angular/material                 5.2.5
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              5.5.10
typescript                        2.6.2
```
NPM: `6.0.0`
Yarn: `1.6.0`

### Repro steps

* Run `ng update @angular/cli` or simply `ng update`.

### Observed behavior  
An error occurs with message:
```
unable to get local issuer certificate
```

### Desired behavior

Expected to update `@angular/cli` as denoted in instructions to upgrade from `5.2.10` to `6.0.0` on [update.angular.io](https://update.angular.io)

### Mention any other details that might be useful (optional)
Both `yarn` and `npm` have `strict-ssl` set to `false` in the config. It seems that CLI is not using the config of the package managers when fetching the new dependencies during update.

This happens in a corporate environment when behind a Self Signed Root CA (MITM of all TLS traffic).

**Comment by clydin** [comment] 2018-05-08 00:37
Duplicate of #10596

**Closed by clydin** 2018-05-08 00:37 UTC
