### ISSUE TITLE
Vagrant machine - issues question/discussion

### ISSUE THREAD

**Issue by Arth95** [angular/angular-cli#1965] opened 2016-09-03 09:48 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 8.1 with Vagrant Ubuntu 16.04

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I have two issues, one when installing cli with sudo npm install angular-cli, second when I try to create new project with sudo ng new testApp

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Installing:
```
npm WARN optional Skipping failed optional dependency /angular-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN string-replace-loader@1.0.3 requires a peer of webpack@1.x.x || 2.x.x but none was installed.
npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of @angular/platform-server@^2.0.0-rc.5 but none was installed.
npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN @angular/core@2.0.0-rc.6 requires a peer of zone.js@^0.6.17 but none was installed.
npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but none was installed.
```

New project:
```
ENOENT: no such file or directory, chmod '/vagrant/testApp/node_modules/angular-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
Error: ENOENT: no such file or directory, chmod '/vagrant/testApp/node_modules/angular-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
    at Error (native)

```
5. Mention any other details that might be useful.

Ive run Vagrant with admin permissions
I've that ENOENT error is common in Vagrant becasue of shared folder.
Creating project in /home/vagrant works, but in sync folder doesnt

Question:
Is it possible to use Vagrant with angular-cli?
Is there alternative for Vagrant that works in similar way?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-09-21 03:16
Dupe of https://github.com/angular/angular-cli/issues/1880
See https://github.com/angular/angular-cli/issues/1880#issuecomment-248469386 for some more details.

**Closed by filipesilva** 2016-09-21 03:16 UTC
