### ISSUE TITLE
bug in ng generate with camelCase path

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular-cli#13553] opened 2019-01-31 07:39 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Don't know whether it is present in previous version

### Description

follow this steps to reproduce

**ng g m menuList**
     - menu-list 
     ---- menu-list.module.ts 

**ng g c menuList/menu**
     - menuList 
     ---- menu 
     ------- menu.component.ts

why it is not creating the component in my menu-list folder?
Also the component gets declared in `menu-list.module.ts` which is different folder <--bug

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.2.2
Node: 10.10.0
OS: win32 x64
Angular: 7.2.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.2
@angular-devkit/build-angular     0.11.2
@angular-devkit/build-optimizer   0.11.2
@angular-devkit/build-webpack     0.11.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.2.2
@angular/cli                      7.2.2
@ngtools/webpack                  7.1.2
@schematics/angular               7.2.2
@schematics/update                0.12.2
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.23.1

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-01-31 09:48
This is by design as to match the Angular style guides https://angular.io/guide/styleguide

Going to mark it as needs further discussion to check with the team if we should handle this or not.

**Comment by alan-agius4** [comment] 2019-02-07 18:40
Following the team meeting, I am closing this as some people might depend on the fact that folder names are not in kebab cases.

**Closed by alan-agius4** 2019-02-07 18:40 UTC
