### ISSUE TITLE
Error: Cannot find module 'rsvp' - After upgrading to latest angular-cli

### ISSUE THREAD

**Issue by HansS** [angular/angular-cli#1243] opened 2016-06-29 07:40 UTC
> ng serve
module.js:327
    throw err;
    ^

Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\node_modules\leek\lib\leek.js:3:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Hans@HP-HANS C:\Users\Hans\Web\frontend\platform\js\angular20\angular2-questions-manekinekko
> ng version
module.js:327
    throw err;
    ^

Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\node_modules\leek\lib\leek.js:3:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Hans@HP-HANS C:\Users\Hans\Web\frontend\platform\js\angular20\angular2-questions-manekinekko
>

**Comment by filipesilva** [comment] 2016-07-04 00:41
Dupe of https://github.com/angular/angular-cli/issues/1186

**Closed by filipesilva** 2016-07-04 00:41 UTC

**Comment by sfjadi2010** [comment] 2016-11-13 23:37
Dupe of #1242
