### ISSUE TITLE
Built projects include many copies of license

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#2637] opened 2016-10-10 22:24 UTC
My `--prod` generated `main.xxx.js` file contains many copies of the Google copyright license. I expected it to be minified away.
angular-cli: 1.0.0-beta.17

```bash
ng new cli9
cd cli9
ng build --prod
```

This generates a bundle with 283 copies of the license. It should contain 0-1.

**Comment by gunnsth** [comment] 2016-10-11 11:06
This is clearly a bug.

In addition, it would be nice if one could specify a license above one's own code.  I noticed the Google license appearing above my own code.

**Comment by deebloo** [comment] 2016-10-11 11:54
one thing I will point out is that this won't really affect the final bundle size after compression. I agree there should only be one/none though

**Comment by tomwanzek** [comment] 2016-10-11 13:56
@gunnsth I agree, I have noticed the same behaviour with the Google license bleeding into non-google module code. There is no role for a Google license to appear above module segments that are not part of Google's code base.

This is related to #2386.

cc @hansl I believe you had already started looking into this in the above issue. Although the license bleed was not mentioned there.

**Comment by filipesilva** [comment] 2016-10-14 16:55
Dupe of https://github.com/angular/angular-cli/issues/2386 overall I believe, better to track it there.

**Closed by filipesilva** 2016-10-14 16:55 UTC
