### ISSUE TITLE
ng test hangs on SIGTERM in architect-command.ts

### ISSUE THREAD

**Issue by rcollette** [angular/angular-cli#14118] opened 2019-04-10 03:54 UTC
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Possibly as of 7.1 or 7.2 branch.  Was not seeing this behavior in CLI 1.2.6 but am seeing it in 7.3.7

### Description

I am running lint, test and build simultaneously using the npm concurrently package.  This has always worked in ngcli 1.2.6.   When one of the tasks fails, concurrently issues a SIGTERM to the other tasks (fail fast), and the other tasks should shut down gracefully.  In 7.3.7 this results in an error in `ng test`. 

What is making this issue bad for me, is that when running this in a docker build (node:10.15.3-alpine) on a gitlab runner, the docker build just hangs, possibly in an infinite loop.  The gitlab runner never releases.    

When I run the demo from macOS, I do get back to a command prompt.  I can't explain the discrepancy.

## 🔬 Minimal Reproduction
The basic reproduction steps are to use concurrently to run `ng test` and then `process.exit(1)` in another concurrently run task _after_ the tests have started to run.

Please run `npm run demo` in this reproduction.  
https://github.com/rcollette/ngcli-test-sigterm-demo

Keep in mind that the timeout in sigterm.js may need to be adjusted.   On my machine 10s was enough time to get the tests started but before they finish.

## 🔥 Exception or Error
Output from an actual application build.
<pre>
<code>
> concurrently --kill-others-on-fail "npm:lint" "npm:test:server" "npm:build:server" 

[test:server] 
[test:server] > embark3-ui@0.0.0 test:server /build
[test:server] > ng test --code-coverage --source-map --watch=false --progress=false
[test:server] 
[lint] 
[lint] > embark3-ui@0.0.0 lint /build
[lint] > ng lint --type-check
[lint] 
[build:server] 
[build:server] > embark3-ui@0.0.0 build:server /build
[build:server] > ng build --progress=false --prod --aot --source-map --es5-browser-support=false
[build:server] 
[lint] Linting "embark3-ui"...
[lint] 
[lint] ERROR: /build/src/app/shared/modals/entitlement/entitlement-modal.component.spec.ts:67:9 - Expected property shorthand in object literal ('{startDate}').
[lint] ERROR: /build/src/app/shared/modals/entitlement/entitlement-modal.component.spec.ts:68:9 - Expected property shorthand in object literal ('{endDate}').
[lint] 
[lint] Lint errors found in the listed files.
[lint] Linting "embark3-ui-e2e"...
[lint] 
[lint] 
[lint] All files pass linting.
[lint] npm ERR! code ELIFECYCLE
[lint] npm ERR! errno 1
[lint] npm ERR! embark3-ui@0.0.0 lint: `ng lint --type-check`
[lint] npm ERR! Exit status 1
[lint] npm ERR! 
npm ERR! Failed at the embark3-ui@0.0.0 lint script.
[lint] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[lint] 
[lint] npm ERR! A complete log of this run can be found in:
[lint] npm ERR!     /root/.npm/_logs/2019-04-09T20_26_17_967Z-debug.log
[lint] npm run lint exited with code 1
--> Sending SIGTERM to other processes..
[build:server] npm run build:server exited with code SIGTERM
--> Sending SIGTERM to other processes..
[test:server] Cannot read property 'success' of undefined
[test:server] TypeError: Cannot read property 'success' of undefined
[test:server]     at TestCommand.runSingleTarget (/build/node_modules/@angular/cli/models/packages/angular/cli/models/architect-command.ts:242:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
</code></pre>

Output from reproduction example
<pre>
<code>
US-RI026CO-MLT:sigterm richardcollette$ npm run demo
> sigterm@0.0.0 demo /Users/richardcollette/code/sigterm/sigterm
> concurrently --kill-others-on-fail "npm:lint" "npm:test" "npm:build" "npm:sigterm" 

[lint] 
[lint] > sigterm@0.0.0 lint /Users/richardcollette/code/sigterm/sigterm
[lint] > ng lint
[lint] 
[sigterm] 
[sigterm] > sigterm@0.0.0 sigterm /Users/richardcollette/code/sigterm/sigterm
[sigterm] > node sigterm.js
[sigterm] 
[build] 
[build] > sigterm@0.0.0 build /Users/richardcollette/code/sigterm/sigterm
[build] > ng build
[build] 
[test] 
[test] > sigterm@0.0.0 test /Users/richardcollette/code/sigterm/sigterm
[test] > ng test
[test] 
[lint] Linting "sigterm"...
[lint] 
[lint] 
[lint] All files pass linting.
[lint] Linting "sigterm-e2e"...
[lint] 
[lint] 
[lint] All files pass linting.
[lint] npm run lint exited with code 0
[test] 09 04 2019 23:50:38.660:WARN [karma]: No captured browser, open http://localhost:9877/
[test] 09 04 2019 23:50:38.664:INFO [karma-server]: Karma v4.0.1 server started at http://0.0.0.0:9877/
[test] 09 04 2019 23:50:38.664:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
[test] 09 04 2019 23:50:38.674:INFO [launcher]: Starting browser Chrome
[sigterm] npm ERR! code ELIFECYCLE
[sigterm] npm ERR! errno 1
[sigterm] npm ERR! sigterm@0.0.0 sigterm: `node sigterm.js`
[sigterm] npm ERR! Exit status 1
npm ERR! 
[sigterm] npm ERR! Failed at the sigterm@0.0.0 sigterm script.
[sigterm] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[sigterm] 
[sigterm] npm ERR! A complete log of this run can be found in:
[sigterm] npm ERR!     /Users/richardcollette/.npm/_logs/2019-04-10T03_50_41_955Z-debug.log
[sigterm] npm run sigterm exited with code 1
--> Sending SIGTERM to other processes..
[build] npm run build exited with code SIGTERM
--> Sending SIGTERM to other processes..
[test] Cannot read property 'success' of undefined
[test] TypeError: Cannot read property 'success' of undefined
[test]     at TestCommand.runSingleTarget (/Users/richardcollette/code/sigterm/sigterm/node_modules/@angular/cli/models/packages/angular/cli/models/architect-command.ts:242:21)
[test]     at <anonymous>
[test]     at process._tickCallback (internal/process/next_tick.js:188:7)
[test] npm run test exited with code SIGTERM
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sigterm@0.0.0 demo: `concurrently --kill-others-on-fail "npm:lint" "npm:test" "npm:build" "npm:sigterm" `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sigterm@0.0.0 demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richardcollette/.npm/_logs/2019-04-10T03_50_42_902Z-debug.log
<code>
</pre>
## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 8.11.3
OS: darwin x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by alan-agius4** [comment] 2019-04-12 11:05
Hi, I tried to look at this however in the shared repo there is no `demo` npm script.

**Comment by rcollette** [comment] 2019-04-12 13:26
Ugh, sorry about that.   I'm on vacation for 10 days and don't have my laptop.   I'll update when I get back.

**Comment by rcollette** [comment] 2019-04-29 22:05
@alan-agius4 -  Sorry for the delay.   I am back from vacation and updated the demonstration project.

**Comment by markmonty** [comment] 2019-05-14 00:52
I'm getting the same/similar error after my tests have executed successfully.

`
[INFO] TOTAL: 130 SUCCESS
[INFO] 13 05 2019 23:54:53.482:DEBUG [karma-server]: Run complete, exiting.
[INFO] 13 05 2019 23:54:53.482:DEBUG [launcher]: Disconnecting all browsers
[INFO] 13 05 2019 23:54:53.531:DEBUG [launcher]: Process ChromeHeadless exited with code null and signal SIGTERM
[INFO] 13 05 2019 23:54:53.531:DEBUG [temp-dir]: Cleaning temp dir /tmp/karma-8145424
[INFO] 13 05 2019 23:54:53.557:DEBUG [launcher]: Finished all browsers
[INFO] 13 05 2019 23:54:53.559:DEBUG [karma-server]: Received stop event, exiting.
[INFO] 13 05 2019 23:54:53.559:DEBUG [launcher]: Disconnecting all browsers
[INFO] 13 05 2019 23:54:58.676:INFO [karma-server]: Karma v4.0.1 server started at http://0.0.0.0:9876/
[INFO] 13 05 2019 23:54:58.676:INFO [launcher]: Launching browsers ChromeHeadlessSandbox with concurrency unlimited
[INFO] 13 05 2019 23:54:58.676:ERROR [launcher]: Cannot load browser "ChromeHeadlessSandbox": it is not registered! Perhaps you are missing some plugin?
[INFO] 13 05 2019 23:54:58.677:ERROR [karma-server]: Error: Found 1 load error
[INFO]     at Server.webServer.listen (/var/lib/jenkins/workspace/client-ci-build/js/node_modules/karma/lib/server.js:182:27)
[INFO]     at Object.onceWrapper (events.js:273:13)
[INFO]     at Server.emit (events.js:187:15)
[INFO]     at emitListeningNT (net.js:1324:10)
[INFO]     at process._tickCallback (internal/process/next_tick.js:63:19)
[ERROR] Cannot read property 'success' of undefined
[ERROR] TypeError: Cannot read property 'success' of undefined
[ERROR]     at TestCommand.runSingleTarget (/var/lib/jenkins/workspace/tsc-client-ci-build/js/node_modules/@angular/cli/models/packages/angular/cli/models/architect-command.ts:242:21)
[ERROR]     at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! ovs-client@0.0.0 coverage-headless: `ng test --source-map=false --code-coverage --watch=false --browsers=ChromeHeadlessSandbox`
[ERROR] npm ERR! Exit status 1
`

I thought this was initially caused when I updated the devkit to 0.13.8 but I rolled it back and the issue still seems to be occurring:
"@angular-devkit/build-angular": "0.11.0"

**Comment by alan-agius4** [comment] 2019-05-19 06:53
This also happens if for example an invalid browser is provided in `karma.config.json`

**Comment by rcollette** [comment] 2019-05-22 13:13
OK, finally saw this happen on the server.   It causes the build to hang forever.  

![Screen Shot 2019-05-22 at 9 10 18 AM](https://user-images.githubusercontent.com/136476/58177150-cf257d00-7c71-11e9-9ba5-865fb5c44456.png)

**Comment by alan-agius4** [comment] 2019-07-04 12:13
Hi all, is this still reproducible with latest version so `@angular-devkit/build-angular` and `@angular/cli`?

**Comment by rcollette** [comment] 2019-07-04 18:05
I'm starting a new project in Angular 8 on Friday.   I should be able to get to re-testing this next week.

**Comment by alan-agius4** [comment] 2019-08-13 11:17
@rcollette any updates?

**Comment by alan-agius4** [comment] 2019-08-15 17:37
Closing as this issue should be solved.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2019-08-15 17:37 UTC
Labels: comp: devkit/architect, freq1: low, need: more info, severity3: broken, type: bug/fix

**Comment by rcollette** [comment] 2019-08-16 13:17
Sorry I wasn't able to check in V8.   Turns out our design system has to be updated first to accommodate  NG-Bootstrap updates, etc.
