### ISSUE TITLE
ng build should --prod by default

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular-cli#14870] opened 2019-06-24 03:38 UTC
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

We maintain an angular component library and we almost could receive dozens of the same question every week, that is 
> `Why the angular build out is so big(3MB or larger)? and why the performance is so poor? we do not want to use it any longer`

when they run `ng build` or `npm run build`

We have to explain that `prod` mode is not the default mode, plz use `ng build --prod` instead.

The `ng build --prod` has been detailed in the official documentation, but many new users just skip the document and just run `npm run build (equals ng build)` in the project generated by `@angular/cli`.

Angular may lose quite a lot of users due to the misunderstanding of `ng build`.
I think it is time to make `--prod` mode default in command `ng build`.

### Describe the solution you'd like
make `--prod` mode default in command `ng build`.

### Describe alternatives you've considered

it may bring break changes, but I think most of the angular developers should use `ng build --prod` now

**Comment by alan-agius4** [comment] 2019-06-24 05:15
Duplicate of https://github.com/angular/angular-cli/issues/14471

**Closed by alan-agius4** 2019-06-24 05:15 UTC
