### ISSUE TITLE
migration to angular 6 problem

### ISSUE THREAD

**Issue by czechk** [angular/angular-cli#11765] opened 2018-08-03 14:13 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps
Just run production build (ng build --prod) and drop to http server
there's no problem when using ng serve locally

### The log given by the failure
Devtools console gives me: **Uncaught SyntaxError: Invalid or unexpected token**
and points me to vendor.js and mark this lines below as errors

...
__webpack_require__.d(__webpack_exports__, "��PRE_STYLE", function() { return ��PRE_STYLE; });
__webpack_require__.d(__webpack_exports__, "��AnimationGroupPlayer", function() { return AnimationGroupPlayer; });
...

### Desired functionality
Page loads properly

**Comment by filipesilva** [comment] 2018-08-04 11:39
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment] 2018-09-10 21:32
Closing as no reproduction provided.

**Closed by alan-agius4** 2018-09-10 21:32 UTC
Labels: need: repro steps

**Comment by admosity** [comment] 2018-11-09 22:09
```

**Comment by admosity** [comment] 2018-11-09 22:13
![image](https://user-images.githubusercontent.com/4655972/48290854-677cb280-e442-11e8-8114-98fd57f98e23.png)

![image](https://user-images.githubusercontent.com/4655972/48290877-782d2880-e442-11e8-984d-66b705db6bc5.png)

For anyone coming here, it seems like some unicode characters or something of that sort snuck into the code base. I assume it's the same case here:

![image](https://user-images.githubusercontent.com/4655972/48290946-a4e14000-e442-11e8-859f-164e6b3fea55.png)

@filipesilva @alan-agius4 

This issue only surfaced while running `ng serve --aot`. Took quite awhile to find.

**Comment by JeeDay** [comment] 2019-01-25 13:36
Hello,

If you read this : I was facing exactly the same issue and I resolved it simply.

**MY CASE** :

It was totally my bad, Angular 6 had no unicode issue.

I am using Azure Devops to deploy my Angular websites ( The same principe can be applied if you use other equivalent tools like Circle CI or if you do it manually simply ).

I have set up a task which is responsible to replace my placeholders by values.

For example if this task detect that a file contains '#{MY_API_URL}#' it will replace it by the real api url.

**WHAT WAS THE CAUSE ?**

This task modified the encoding of the js files ( including vendor.js ) ( event if no placeholder to replace was found in it ). So the unicode of my vendor.js file was not utf8 at the end of this task execution.

**HOW DID I SOLVE IT ?**

In this task  I set up the file encoding to utf8, after that all the files encoding were still right ( utf8 )

after the execution of this task.

** HOW CAN YOU SOLVE IT ? **

-> If you are using a devops tools, check that there is no task which is modifying the encoding of your js files.

-> If you build it manually, check your work environment ( IDE, Machine, etc .. ) and the encoding of your generated files ( it must be utf8 )
