### ISSUE TITLE
Error loading fonts with @font-face if using i18n, because paths aren't prepended with the language

### ISSUE THREAD

**Issue by Ks89** [angular/angular-cli#15147] opened 2019-07-23 14:11 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, the previous version in which this bug was not present was angular-cli 7.x.x

### Description

If I build the angular app without i18n everything is ok, but If I use i18n all @font-face font paths aren't prefixed with the language.

## 🔬 Minimal Reproduction
Add Roboto ttf font to assets folder, then add to styles.scss

@font-face {
  font-family: 'Roboto-Regular';
  font-style: normal;
  font-weight: normal;
  src: url('/assets/Roboto-Regular.ttf') format('truetype');
}
Use this font somewhere in the app.

Now build the app with "ng build --prod --aot" and load it with a very basic expressjs server like this one:

```
var express = require('express');
var app = express();

app.use(express.static('public'));

app.listen(3000, function() {
  console.log('Example app listening on port 3000!');
});
```

Then add i18n to the app and build the app with english language, so the app will be exposed at localhost:3000/en and the expressjs server will be something like this:

```
var express = require('express');
var app = express();

app.use(express.static('public/en'));

app.listen(3000, function() {
  console.log('Example app listening on port 3000!');
});
```

Now if you try to access the app via browser, you'll get the error:

```
Failed to decode downloaded font: <URL>
OTS parsing error: invalid version tag
```  

If I modify all files in dist folder, replacing all "url('/assets/" occurrences with "url('/en/assets/", the error disappears. 

## 🔥 Exception or Error
Browser's console shows:
<pre><code>
Failed to decode downloaded font: <URL>
OTS parsing error: invalid version tag
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.1.2
Node: 10.16.0
OS: darwin x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/cdk                      8.1.1
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**

Tested on Chrome 75.0.3770.142

**Comment by Ks89** [comment] 2019-07-23 14:30
Is it related to this https://github.com/angular/angular-cli/issues/6599?

**Comment by Ks89** [comment] 2019-07-24 09:11
I tried this solution found [HERE](https://github.com/angular/angular-cli/issues/14587):

```
url('~src/assets/MY_FONT_PATH')
```

and It worked, however I'm not sure if this is the right way to do this. Which is the recommended solution? Is there an official way to do this and/or a FAQ somewhere on the official angular website?

**Comment by alan-agius4** [comment] 2019-07-24 12:32
Hi @Ks89, are you setting a base href of `en` to load all resouces from `/en`?

I suggest that you set the path to your font file relative to your stylesheet. Ie `assets/Roboto-Regular.ttf`, this will also enable fingerprinting of the resources file as opposite to when using root paths `/`.

**Comment by Ks89** [comment] 2019-07-24 13:05
Yes, my base href becomes `<base href="/en/">`.

I'm building with this command:
```
ng build --output-path=dist/en
           --prod
           --aot
           --delete-output-path
           --base-href /en/
           --i18n-file=src/locale/messages.en.xlf
           --i18n-format=xlf
           --i18n-locale=en
```

Is it wrong? Should i remove --base-href?

**Comment by Ks89** [comment] 2019-07-24 13:12
My question above about `--base-href /en/` is because at the end of this page https://angular.io/guide/i18n  there is baseHref in this example:

```
"configurations": {
  "fr": {
    "aot": true,
    "outputPath": "dist/my-project-fr/",
    "baseHref": "/fr/",
    "i18nFile": "src/locale/messages.fr.xlf",
    "i18nFormat": "xlf",
    "i18nLocale": "fr",
    "i18nMissingTranslation": "error",
  }
```

so I supposed that it's required.

**Comment by alan-agius4** [comment] 2019-07-24 13:13
The regression is because in version 8, we are trying to standardise the base href logic. 
There is more info https://github.com/angular/angular-cli/issues/14587#issuecomment-497368020

No, you should not remove the `baseHref` option

The suggested approach is to use relative paths instead of root relative paths.

**Comment by Ks89** [comment] 2019-07-24 13:19
Ok, but what does it mean "relative paths"?  Where the relative path starts?

For example, if my folders are:

- scss
   - file-with-font.scss
- assets
   - fonts
      - roboto

Which is the right relative path to put into font-face in file-with-font.scss?
Is it something like: ../assets/fonts/roboto/ ?

**Comment by alan-agius4** [comment] 2019-07-24 13:32
Relative from the scss file.

In the above case yes `../assets/fonts/roboto/`

**Comment by Ks89** [comment] 2019-07-24 13:54
Ok I found the problem.

I added font-face in styles.scss with assets/.... and now it's working.

My previous setup was:

styles.scss:
```
@import "theme";


theme/_theme.scss:
```
/// the font face import with assets/...
```

and in my angular.json:
```
"stylePreprocessorOptions": {
              "includePaths": [
                "src/theme"
              ]
            },
```

This cause the problem of this issue. The only way to build was ~src/assets/..., otherwise the build fails with relative paths.

**Comment by Ks89** [comment] 2019-07-24 16:00
If this is the expected behaviour (see my previous comment) and not a bug I can close the issue.

**Comment by alan-agius4** [comment] 2019-07-25 07:42
Hi, Sass itself doesn't provide Url rewiring for resources, meaning that the resources should be relative to top level scss file which will produce an output. (IE: A non partial scss file)

Let me try demonstrate this with some examples.

Let's assume that I have the following font file, under `src/fonts/foo.woff2`

- `src/app/app.component.scss` - will produce an `src/app/app.component.css` when compiled so the font path should be relative to that meaning it should be `../fonts/foo.woff2`
- `src/styles.scss` which imports `src/styles/_theme.scss` and font is defined in `_theme.scss` -  in this case `_theme.scss` will not produce a direct output, as the output of it will be inside of `styles.css` which means that when defining a font inside of `_theme.scss` it should be relative to `style.scss` which in this case would be `fonts/foo.woff2`

I hope this is a bit more clear.

**Closed by alan-agius4** 2019-07-25 07:42 UTC
