### ISSUE TITLE
Breaking change about image paths on beta.16

### ISSUE THREAD

**Issue by dzonatan** [angular/angular-cli#2441] opened 2016-09-30 13:06 UTC
> angular-cli: 1.0.0-beta.16
> node: 6.5.0
> os: win32 x64

## Problem
On **<=beta.15** all image paths (`<img src="my/path"`) were resolved as absolute paths from `src` folder. Even ones without starting slash `/`. Meaning we could use an existing image in `src/assets/image.png` like this `<img src="assets/image.png">` from anywhere we want.

With **beta.16** all image paths starting without slash `/` are now relative.

Using relative paths like `<img src="../../assets/image.png">` are most of the time pain in the ass and makes more sense to use them absolute (`<img src="/assets/image.png">`). 
And there comes the problem when using absolute paths with custom base tag (`--base-href /myPath/`).
It's obvious that it wont work because path such as `/assets/image.png` will ignore base tag and directly request app domain.

## Actions required

- Update `CHANGELOG.md` about this breaking change for ones who were using absolute paths for images without starting `/`, they should use it now.
- Support absolute image paths with `--base-href` option _by some webpack plugin which would prefix all image paths with that base url or make it relative (?)_

**Comment by Bulan** [comment] 2016-09-30 13:58
Possible duplicate with #2396

**Comment by filipesilva** [comment] 2016-10-05 21:04
Dupe of #2396

**Closed by filipesilva** 2016-10-05 21:04 UTC
