### ISSUE TITLE
webpack --config  Duplicate identifiers when building express server.js and prerender.js

### ISSUE THREAD

**Issue by FelipeLujan** [angular/angular-cli#10459] opened 2018-04-25 03:38 UTC
### Versions
```
Angular CLI: 1.7.4
Node: 9.11.1
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular/platform-server: 5.2.10
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack-cli: 2.0.15
webpack: 3.11.0

```

### Repro steps
I took an AoT working project and followed [this procedure](https://github.com/angular/angular-cli/wiki/stories-universal-rendering) to make it SEO ready
* Step 1: made sure the project is still working for JIT compilation.  build:client-and-server-bundles builds both versions successfully
* Step 2 npm install --save prerender-node prerender http-server webpack webpack-cli
* Step 3 took the  webpack.server.config.js from [Angular universal starter](https://github.com/angular/universal-starter)
 and copied to the root of my project in order to build server.js and prerender.js with the dependencies used in my project
* Step 4 run webpack --config webpack.server.config.js --progress --colors to run the imported file

### Observed behavior

```
ERROR in ./server.ts
[tsl] ERROR in /home/pipe/Documents/coding/Angular/RemodelacionesLujan/server.ts(3,9)
      TS2300: Duplicate identifier 'enableProdMode'.

ERROR in ./server.ts
[tsl] ERROR in /home/pipe/Documents/coding/Angular/RemodelacionesLujan/server.ts(12,10)
      TS2300: Duplicate identifier 'enableProdMode'.

ERROR in ./server.ts
[tsl] ERROR in /home/pipe/Documents/coding/Angular/RemodelacionesLujan/server.ts(9,13)
      TS2300: Duplicate identifier 'express'.

ERROR in ./server.ts
[tsl] ERROR in /home/pipe/Documents/coding/Angular/RemodelacionesLujan/server.ts(14,13)
      TS2300: Duplicate identifier 'express'.

ERROR in ./server.ts
[tsl] ERROR in /home/pipe/Documents/coding/Angular/RemodelacionesLujan/server.ts(10,9)
      TS2300: Duplicate identifier 'join'.

ERROR in ./server.ts
[tsl] ERROR in /home/pipe/Documents/coding/Angular/RemodelacionesLujan/server.ts(15,10)
      TS2300: Duplicate identifier 'join'.

ERROR in Entry module not found: Error: Can't resolve './prerender.ts' in '/home/pipe/Documents/coding/Angular/RemodelacionesLujan'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bs4starter@0.0.0 webpack:server: `webpack --config webpack.server.config.js --progress --colors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the bs4starter@0.0.0 webpack:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above
```

prerender.js is not created

### Desired behavior
both server.js and prerender.js should be created. Which actually happens with [Angular universal starter](https://github.com/angular/universal-starter)

this is my first time describing an issue, sorry if i'm missing any info, i'll provide any further description needed.

Package.json
```
{
  "name": "bs4starter",
  "version": "0.0.0",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/angular/universal-starter.git"
  },
  "contributors": [
    "AngularClass <hello@angularclass.com>",
    "PatrickJS <patrick@angularclass.com>",
    "Jeff Whelpley <jeff@gethuman.com>",
    "Jeff Cross <crossj@google.com>",
    "Mark Pieszak <mpieszak84@gmail.com>",
    "Jason Jean <jasonjean1993@gmail.com>",
    "Fabian Wiles <fabian.wiles@gmail.com>"
  ],
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build:prerender": "npm run build:client-and-server-bundles && npm run webpack:server && npm run generate:prerender",
    "build:client-and-server-bundles": "ng build --prod --aot && ng build --prod --aot  --app 1 --output-hashing=false",
    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
    "generate:prerender": "cd dist && node prerender",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:prerender": "cd dist/browser && http-server",
    "serve:ssr": "node dist/server",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ng-bootstrap/ng-bootstrap": "^1.1.2",
    "@nguniversal/common": "^5.0.0",
    "@nguniversal/express-engine": "^5.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0",
    "angular-font-awesome": "^3.1.2",
    "angularfire2": "^5.0.0-rc.6.0",
    "bootstrap": "4.1.0",
    "core-js": "^2.4.1",
    "express": "^4.16.3",
    "firebase": "4.12.1",
    "font-awesome": "^4.7.0",
    "http-server": "^0.11.1",
    "node-sass": "4.8.3",
    "prerender": "^5.4.2",
    "prerender-node": "^3.1.1",
    "rxjs": "^5.5.6",
    "ts-loader": "3.5.0",
    "webpack": "^3.11.0",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@angular/platform-server": "^5.2.10",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3",
    "webpack-cli": "^2.0.15"
  }
}
```

thanks

**Comment by jackweldon** [comment] 2018-05-23 11:37
Did you find a fix for this?

**Comment by FelipeLujan** [comment] 2018-05-23 11:52
Hi.
No I didn't

**Comment by facuxt** [comment] 2018-06-21 12:58
You sould copy prerender.ts aswell from the same universal-starter repo...

**Comment by alan-agius4** [comment] 2020-01-09 09:27
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2020-01-09 09:27 UTC
