### ISSUE TITLE
Styles don't included when node_module folder is a symbolic link

### ISSUE THREAD

**Issue by dianjuar** [angular/angular-cli#5515] opened 2017-03-20 03:07 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.0.0-rc.2
node: 6.9.5
os: linux x64
```

### Repro steps.

I have several angular projects so to save disk space y decied to have one `node_modules` folder an each angular project have a symbolic to that unique node_modules folder. Think a shared node_module folder.

When I want to use [Bootstrap](http://getbootstrap.com/), the styles are not enqueued having the symbolic link but, with out it, it does.

> I am taking a course so, I have several angular projects for each lesson. With this hack I save about 2gb or more of disk space. Maybe somebody has several angular projects on a server an do this hack too to save space disk too.

### The log given by the failure.

No error given by `ng serve` and browser console either

### Mention any other details that might be useful.

I enqueue the style on `.angular-cli.json`

```
"styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css"
      ],
```

**Comment by filipesilva** [comment] 2017-03-23 21:34
We have a couple of known problems with symlinks in general. Dupe of https://github.com/angular/angular-cli/issues/3797.

**Closed by filipesilva** 2017-03-23 21:34 UTC
