### ISSUE TITLE
HTML Selector regex is incorrect

### ISSUE THREAD

**Issue by harrismirza** [angular/angular-cli#21039] opened 2021-06-03 16:33 UTC
Hi,

I think the regex for HTML selectors is incorrect, it is too restrictive. 

I couldn't find anything in the HTML spec, but the CSS specification has the following :

"
In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".
"
https://www.w3.org/TR/CSS21/syndata.html#characters

I think this is what the regex was trying to implement, but this blocks double hyphens, a hyphen followed by a digit throughout the whole string rather than just at the beginning as the spec suggests.

The regex is at the following location:
https://github.com/angular/angular-cli/blob/3a287beab38de6bbd596d9cd2593346cf49b42fc/packages/schematics/angular/utility/validation.ts#L21

I think it should be replaced by the following: 

`^[-a-zA-Z][a-zA-Z]+[.0-9a-zA-Z]*(:?-[.0-9a-zA-Z]*)*$`

I have written some tests in RegExr here: regexr.com/5uauo

I will also raise a PR for this on the weekend.

Thanks,
Harris Mirza

**Comment by alan-agius4** [comment] 2021-06-03 16:40
Duplicate of https://github.com/angular/angular-cli/issues/11051

PRs are welcome.

**Closed** 2021-06-03 16:48 UTC
