### ISSUE TITLE
ng xi18n silently fails to extract tags

### ISSUE THREAD

**Issue by JanEggers** [angular/angular-cli#8399] opened 2017-11-08 12:23 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0
Node: 8.7.0
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.
ng xi18n --verbose > xi18n.log

### The log given by the failure.
there is no log generated by ng

### Desired functionality.
a log should be generated containing the errors or at least they should be logged to console. my project builds. but extracting i18n from the templates silently fails. i created a repro with an app component with i18n tags and the libraries i use.

### Mention any other details that might be useful.
https://github.com/JanEggers/repro

**Comment by JanEggers** [comment] 2017-11-10 11:52
i tracked it down to ngx-bootstrap if i comment that out in vendor.ts messages.xlf is generated.

@hansl can you please have a look / verify my findings. and find out whats causing the error and why it is not shown?

**Comment by intellix** [comment] 2017-11-10 13:56
Perhaps a duplicate of: https://github.com/angular/angular-cli/issues/8065

**Comment by JanEggers** [comment] 2017-11-10 14:20
related because i dont get an error.

but it is no duplicate because my packages are uptodate and ng build works without errors

**Comment by ocombe** [comment] 2017-11-14 08:23
Yes it's a duplicate, my issue was similar: it would build just fine but not extract because of an error only in the extraction mode. And I believe that the solution would be the same so I'm closing this one, please follow up on the other issue.

**Closed by ocombe** 2017-11-14 08:23 UTC
