### ISSUE TITLE
unable to create new project

### ISSUE THREAD

**Issue by swethapatlola** [angular/angular-cli#11009] opened 2018-05-25 06:09 UTC
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

### Mention any other details that might be useful (optional)
Schematic input does not validate against the Schema: {"dryRun":false,"version":"6.0.4","skipGit":false,"skipInstall":false,"linkCli":false,"commit":true,"newProjectRoot":"projects","inlineStyle":false,"inlineTemplate":false,"routing":false,"prefix":"app","style":"css","skipTests":false}
Errors:

  Data path "" should NOT have additional properties(dryRun).

**Comment by clydin** [comment] 2018-05-25 10:10
Duplicate of #11006

**Closed by clydin** 2018-05-25 10:10 UTC
