### ISSUE TITLE
ng update doesn't respect configured npm registry

### ISSUE THREAD

**Issue by crfrolik** [angular/angular-cli#18267] opened 2020-07-15 20:43 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Unknown

### Description

If you change your npm registry to a private one via `npm config set registry`, and then run `ng update`, you get warnings like this:

```
Fetching dependency metadata from registry...
    404 Not Found - GET https://registry.npmjs.org/foo-bar-baz - Not found
```

The CLI should be looking in my private registry, not in `registry.npmjs.org`.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.3
Node: 12.18.2
OS: linux x64

Angular: 10.0.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.3
@angular-devkit/build-angular      0.1000.3
@angular-devkit/build-ng-packagr   0.1000.3
@angular-devkit/build-optimizer    0.1000.3
@angular-devkit/build-webpack      0.1000.3
@angular-devkit/core               10.0.3
@angular-devkit/schematics         10.0.3
@angular/cli                       10.0.3
@ngtools/webpack                   10.0.3
@schematics/angular                10.0.3
@schematics/update                 0.1000.3
ng-packagr                         10.0.1
rxjs                               6.6.0
typescript                         3.9.6
webpack                            4.43.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-07-16 07:08
Duplicate of https://github.com/angular/angular-cli/issues/14993

**Closed by alan-agius4** 2020-07-16 07:08 UTC
