### ISSUE TITLE
Split imports to DLLs (Vendor files)

### ISSUE THREAD

**Issue by montella1507** [angular/angular-cli#3042] opened 2016-11-07 09:23 UTC
Hello, 

because the build time of the solution is seriously slow (40sec first build, 15sec on watch) i strongly suggest to allow splitting vendor files to DLL bundle = not to build everything (Angular 2, RxJS, Material theme..) with every change in your source code.

It would speed up the build time 5times..

**Comment by gelliott181** [comment] 2016-11-07 17:58
I'd like to see the results of this change. Faster build times with less rebuilding would be wonderful, but I'm wondering just how accurate the 5x build speed increase is. Do you have this implemented for yourself?

**Comment by filipesilva** [comment] 2016-11-21 12:31
Dupe of https://github.com/angular/angular-cli/issues/1980

**Closed by filipesilva** 2016-11-21 12:31 UTC
