### ISSUE TITLE
Changes in imported .less files dont update the page in hmr or serve mode

### ISSUE THREAD

**Issue by maxim1006** [angular/angular-cli#10953] opened 2018-05-22 13:13 UTC
### Versions
Angular CLI: 6.0.3
Node: 10.1.0
OS: win32 x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3

### Repro steps
* Step 1 - create main.less file and add it to global styles in angular.json
* Step 2 - create some.less file and @import it in main.less

### Observed behavior
```
When you make any changes in some.less, the page will not upate in hmr or serve mode.
```

### Desired behavior
```
Page upates in hmr or serve mode when some changes occur in imported styles in global .less files
```

**Comment by clydin** [comment] 2018-05-22 13:17
Duplicate of #10899

**Closed by clydin** 2018-05-22 13:17 UTC
