### ISSUE TITLE
angular CLI installation error (version 10.0.1 and up to 10.0.5)

### ISSUE THREAD

**Issue by mihui** [angular/angular-cli#18462] opened 2020-08-06 10:51 UTC
# 🐞 Bug report

 Hi there, I can't install the CLI, there are some errors

### Description

 Installation error on macOS and Linux

## 🔬 Minimal Reproduction

```log
npm install @angular/cli --save
```

## 🔥 Exception or Error
<pre><code>npm install @angular/cli --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@yarnpkg%2flockfile - Not found
npm ERR! 404 
npm ERR! 404  '@yarnpkg/lockfile@1.1.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@angular/cli'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
</code></pre>

## 🌍 Your Environment
<pre><code>macOS and Linux
</code></pre>

**Anything else relevant?**
N/A

**Comment by ogarvey** [comment] 2020-08-06 10:59
Getting the same thing on Windows 10 Pro x64 1909 - 18363.959

Using Node 12.6.1 and npm 6.13.4.

> npm i -g @angular/cli
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@yarnpkg%2flockfile - Not found
> npm ERR! 404
> npm ERR! 404  '@yarnpkg/lockfile@1.1.0' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 It was specified as a dependency of '@angular/cli'
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\oliverg\AppData\Roaming\npm-cache\_logs\2020-08-06T10_54_15_718Z-debug.log

**Comment by joaomelo26** [comment] 2020-08-06 10:59
Also facing this issue.

**Comment by avich007** [comment] 2020-08-06 11:00
Facing Similar Issue while installing angular/cli

**Comment by sid-maddy** [comment] 2020-08-06 11:00
There is an ongoing [NPM issue](https://web.archive.org/web/20200806105739/https://status.npmjs.org/) with scoped packages

**Comment by hamazaspavetisyan** [comment] 2020-08-06 11:01
Same here

**Comment by neetsingh** [comment] 2020-08-06 11:08
same issue here..
![image](https://user-images.githubusercontent.com/16643679/89525056-43125d80-d803-11ea-9603-51b8ba2d62f0.png)

**Comment by alan-agius4** [comment] 2020-08-06 11:21
Duplicate of https://github.com/angular/angular-cli/issues/18460

**Comment by neetsingh** [comment] 2020-08-06 11:21
seems like issue is been resolve but now getting another issue 
![image](https://user-images.githubusercontent.com/16643679/89526240-1101fb00-d805-11ea-945a-ca90b691fdf3.png)

**Closed** 2020-08-06 11:21 UTC
