### ISSUE TITLE
Angular 6.0.0 --stats-json or sourceMap blocking at 95% when optimisation&buildOptimizer are set to true 

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular-cli#10747] opened 2018-05-09 10:03 UTC
```
Versions
Angular CLI: 6.0.0
Node: 9.8.0
OS: win32 x64
Angular: 6.0.0
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
angular-devkit/build-angular: 0.6.0,
angular/cli: 6.0.0,
angular/compiler-cli: 6.0.0,
rxjs: 6.0.0
typescript: 2.7.2
webpack: 4.6.0
```

### Repro steps
Build with this configuration :
```
 "optimization": true,
              "outputHashing": "none",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": true,
              "buildOptimizer": true,
```

### Observed behavior
Blocking at 95% but folder and map exist on filesystem, cli never finish 95% step. (it works if disabled optimisation option)
```95% emitting index-html-webpack-plugin```

### Desired behavior
Finish generation build with sourcemap when optimisation and buildOptimizer are enabled in configuration

**Comment by istiti** [comment] 2018-05-09 11:08
you did good job, I confirm your copy/paste works well ! https://github.com/angular/angular-cli/issues/10747

**Comment by vytautas-pranskunas-** [comment] 2018-05-09 11:58
@istiti exactly - only difference your ticket was somwhere below and used RC - i confirmed that it is the same with final 6 release.

**Comment by clydin** [comment] 2018-05-09 13:42
Duplicate of #10591

**Closed by clydin** 2018-05-09 13:42 UTC
