### ISSUE TITLE
angular 8 application not working in local ISS while using "ng build --prod"

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular-cli#16159] opened 2019-11-12 09:35 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

**Yes, working fine angular 7**

### Description

while hosting my application into local IIS with target "es2015", my application not working. we facing alignment issue due to control rendering initialized before styles loaded in application.

But working fine, when i set **target** as "**es5**"

## 🔬 Minimal Reproduction

1. download sample from below link:

> https://www.syncfusion.com/downloads/support/directtrac/general/ze/RTE1827193720

2. Give "npm i" to install required packages.

3. use below command to build application

> ng build --prod

## 🔥 Exception or Error
 when target is "**es2015**", application breaks. refer below screenshot

![Screenshot (23)](https://user-images.githubusercontent.com/36756050/68659659-a9609d00-055d-11ea-9ecf-975c7b28c821.png)

IF i set **target** as "es5", application works fine. refer below

![Screenshot (22)](https://user-images.githubusercontent.com/36756050/68659979-53402980-055e-11ea-90a8-c2001a8529b9.png)

## 🌍 Your Environment
<pre><code>

    "@angular/animations": "~8.2.11",
    "@angular/common": "~8.2.11",
    "@angular/compiler": "~8.2.11",
    "@angular/core": "~8.2.11",
    "@angular/forms": "~8.2.11",
    "@angular/platform-browser": "~8.2.11",
    "@angular/platform-browser-dynamic": "~8.2.11",
--------------------------------------------------------------
    "@angular-devkit/build-angular": "~0.803.10",
    "@angular/cli": "~8.3.10",
    "@angular/compiler-cli": "~8.2.11",

</code></pre>

**Anything else relevant?**
  ensure "es2015" compilation

**Comment by alan-agius4** [comment] 2019-11-12 10:49
Hi, I tried to reproduce locally and it seems to be related to a runtime issue, as there is also a different HTML structure invoked.

Working
```html
<div class="e-toolbar-items" _ngcontent-dvf-c0="">
  <div class="e-toolbar-item e-tbtn-align" _ngcontent-dvf-c0="" aria-disabled="false" title="Bold"><button
      class="e-tbar-btn e-control e-btn e-lib e-icon-btn" _ngcontent-dvf-c0="" type="button"
      id="richtexteditor_1826258758_0_toolbar_Bold" tabindex="-1" style="width: auto;"><span
        class="e-btn-icon e-bold e-icons" _ngcontent-dvf-c0=""></span></button></div>
  <div class="e-toolbar-item e-tbtn-align" _ngcontent-dvf-c0="" aria-disabled="false" title="Italic"><button
      class="e-tbar-btn e-control e-btn e-lib e-icon-btn" _ngcontent-dvf-c0="" type="button"
      id="richtexteditor_1826258758_0_toolbar_Italic" tabindex="-1" style="width: auto;"><span
        class="e-btn-icon e-italic e-icons" _ngcontent-dvf-c0=""></span></button></div>
</div>
```

Not working
```html
<div class="e-toolbar-items" _ngcontent-vxq-c0=""></div>
```

The issue seems to be that when the scripts are deferred which `module` scripts are by default. This also breaks in es5 when scripts are deferred.

Hence, it seems to be more of a bug which is caused by the rich-text editor rather than the Angular CLI.

**Comment by kumaresan-subramani** [comment] 2019-11-12 10:51
HI @alan-agius4 ,

But same application works fine with "target" as "es5". i have checked it locally

**Comment by alan-agius4** [comment] 2019-11-12 11:13
If you use `es5` with differed scripts it will fail.

Ie: add `defer` attribute to the script tags.

**Comment by kumaresan-subramani** [comment] 2019-11-12 11:22
@alan-agius4 , is there any way to remove `defer` attribute while generating `prod` build with target `es2015`

And can you suggest how to handle this

**Comment by alan-agius4** [comment] 2019-11-12 11:28
No, module tags are always defer and they is no way to change that. 

I am not familiar with the internals of the rich-editor that you are using so I cannot really say what's the problem there.

**Comment by kumaresan-subramani** [comment] 2019-11-12 11:30
Okay @alan-agius4 .

Thanks for your information

**Comment by alan-agius4** [comment] 2019-11-12 12:00
Closing as this is not actionable by us.

**Closed by alan-agius4** 2019-11-12 12:00 UTC
