### ISSUE TITLE
ng serve ( webpack dev server ) is not terminated and keeps zombie in the system when run from local dependencies

### ISSUE THREAD

**Issue by Hotell** [angular/angular-cli#9705] opened 2018-02-20 21:17 UTC
### Versions
```
Angular CLI: 1.7.0
Node: 8.9.3
OS: darwin x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps
```sh
ng new --skip-install -sg -it my-app && cd my-app

yarn install

yarn start --aot --open

CTRL+C
```

### Observed behavior

![image](https://user-images.githubusercontent.com/1223799/36449673-bbdf4e30-168b-11e8-8ac7-2c8a176c4b0e.png)

When executing locally installed `ng` via `npm start` or `yarn start`

Server is not terminated and keeps running. Extensive hunt for hanging Node PID is needed, followed by killing the process with `kill PID` ouch!

![image](https://user-images.githubusercontent.com/1223799/36450084-1fe85e8e-168d-11e8-9f2b-a90402a9fcec.png)

when server is run via globally installed `ng` it is killed as expected....

### Desired behavior

When `yarn ng serve` is terminated, it should be properly terminated

**Comment by devoto13** [comment] 2018-02-21 00:03
Duplicate of https://github.com/angular/angular-cli/issues/9647

**Comment by filipesilva** [comment] 2018-02-22 20:47
Closing as duplicate of #9647.

**Closed by filipesilva** 2018-02-22 20:47 UTC
