### ISSUE TITLE
Bug (command: new): --skip-tests doesn't skip e2e

### ISSUE THREAD

**Issue by neo** [angular/angular-cli#8393] opened 2017-11-07 22:28 UTC
### Bug Report or Feature Request (mark with an `x`)

- [X] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
```
Angular CLI: 1.5.0
Node: 9.1.0
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.

Running

```
ng new testapp --skip-tests
```

would still see the e2e files and config files of karma and protractor

### The log given by the failure.

N/A

### Desired functionality.

It shouldn't include the test files like these, should it?

### Mention any other details that might be useful.

N/A

**Comment by Brocco** [comment] 2017-11-14 03:11
That's a potential debate, but for what you're looking for, consider using this:

```
ng new testapp --minimal
```

This will create a new app with no test structures (spec files or dependencies) and will also inline both styles and templates.

**Comment by neo** [comment] 2017-11-14 14:10
That's what I used instead. Thanks!

But on the other hand, saw some commit history contains the `--skip-e2e` flag, tried and also didn't work. So is there no way to exclude e2e tests right now?

**Comment by NoNameProvided** [comment] 2018-01-25 08:53
We would love to see also a `skip-e2e` option, as we are rolling our own. What was the reason removing the already existing implementation?

**Comment by filipesilva** [comment] 2019-10-08 16:50
Marking as duplicate of https://github.com/angular/angular-cli/issues/9160 just because that one has a bit more traction.

**Closed by filipesilva** 2019-10-08 16:50 UTC
Labels: comp: schematics/angular, freq1: low, severity2: inconvenient, type: bug/fix
