### ISSUE TITLE
[CLI/NEW] Ask if should add unit test lib and E2E tool

### ISSUE THREAD

**Issue by ampmonteiro** [angular/angular-cli#25344] opened 2023-06-08 18:43 UTC
### Command

new

### Description

When initialize / setup/ create a new App beside ask for router, should also ask if want to install / setup Unit test and also and  e2e test tools ( similar like Vue does).

 instead of for example run the command related e2e and asking if want to setup / install cypress,

make  more sense at the begin of setup of new app  because since angular will provide new tool for unit test ( jest ) make sense to be decouple of component generator.

Also should verify if exist new unit test tool setup before generate a component / service, etc and in case of existing unit test tool ask if want to also be generated a unit test file.

**Comment by alan-agius4** [comment] 2023-06-08 18:47
Duplicate of https://github.com/angular/angular-cli/issues/22978

**Closed by alan-agius4** 2023-06-08 18:47 UTC
