### ISSUE TITLE
Application compiles with missing output now

### ISSUE THREAD

**Issue by sundarchi1** [angular/angular-cli#11863] opened 2018-08-11 18:33 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
**NodeJS:** 10.8.0
**npm:** 6.2.0
**CLI:** 6.1.3

### Repro steps
Create project.
Build/serve project.
Look in output window of IDE.
Notice missing output. This used to be a long list of stuff, like all the files being processed, chunked, UglifyJS, etc, basically the compiler (webpack?) output. This just started happening within the past few days.

![2018-08-11_14-16-20](https://user-images.githubusercontent.com/31782486/43994924-f8f5734e-9d72-11e8-9890-02b820dc1d5c.png)

### Desired functionality
Restore the output or please clarify reason of removal.

**Comment by hansl** [comment] 2018-08-15 22:07
https://github.com/angular/angular-cli/pull/11805 changed the _default_ behaviour for non-TTY terminals. You can set `progress: true` in your `options` object of your `build` target in your `angular.json` file and that should override the setting.

Closing this as working as intended.

**Closed by hansl** 2018-08-15 22:07 UTC
Labels: comp: angular/cli
