### ISSUE TITLE
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser after Angular 12 update

### ISSUE THREAD

**Issue by alsoicode** [angular/angular-cli#20853] opened 2021-05-19 17:13 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes. `ng serve` worked as expected using 11.2.11

### Description

After updating to Angular 12 via the advanced instructions at https://update.angular.io/?l=3&v=11.0-12.0, `ng serve` now throws an error:

```
Error: /Users/btaylor/work/angular-apps/mdsl-authoring/assets/scss/_colors.scss:1:4: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

Error: /Users/btaylor/work/angular-apps/mdsl-authoring/assets/scss/custom-bootstrap.scss:1:1: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

Error: /Users/btaylor/work/angular-apps/mdsl-authoring/assets/scss/global.scss:296:12: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

Error: /Users/btaylor/work/angular-apps/mdsl-authoring/assets/scss/mdsl-composer/mdsl-composer-variables.scss:103:1: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
```

## 🔬 Minimal Reproduction

I'm not sure if this issue is reproduce-able, but the contents of our Scss files are quite unremarkable. Example:

// _colors.scss

```
// Bootstrap Overrides
$text-secondary: #2E93B1;
$text-muted: #ccc;
$link-color: #2E93B1;

.text-secondary {
  color: $text-secondary !important;
}

// LabCorp UI Overrides
$theme-colors: (
  'primary': #003A70,
  'secondary': #2E93B1,
  'success': #155724,
  'danger': #790E1D,
  'warning': #C59C38,
  'info': #007A6E,
  'light': #EDF1F4,
  'dark': #0B1519,
);

// UI design colors
$primary: #007FA3;
$highlighted: #D57800;
$accent: #5F456F;
$accent-secondary: #808080;
$related: #D1EAF1;

```

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre>OS X 11.3.1 (Beta) using Node 14.17.0<code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-05-19 17:17
Duplicate of https://github.com/angular/angular-cli/issues/20812

**Closed by alan-agius4** 2021-05-19 17:17 UTC
