### ISSUE TITLE
ng [command] --help does not work outside angular project folder for some commands

### ISSUE THREAD

**Issue by kuncevic** [angular/angular-cli#19057] opened 2020-10-13 06:12 UTC
# 🐞 Bug report
### Command that does not work for in case of `global cli` marked with an `x`
- [ ] new
- [ x] build
- [ x] serve
- [ x] test
- [ x] e2e
- [ x] generate
- [ x] add
- [ ] update
- [ x] lint
- [ x] xi18n
- [ x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes

### Description
Help info should be available for any angular-cli related command regardless you inside angular-cli project folder (local cli) or outside angular-cli project folder (global cli)

## 🔬 Minimal Reproduction
Navigate outside angular-cli project in console then run any below command:
```
ng build --help
ng serve --help
ng test --help
ng e2e --help
ng generate --help
ng add --help
ng lint --help
ng xi18n --help
ng run --help
```

## 🔥 Exception or Error
`Getting error: /private/var/folders/jj/sjmtmgms0d73pgpp6xqjgq480000gn/T/ng-UIzJTX/angular-errors.log" for further details.`
Here is `cat angular-errors.log`:
```
[error] Error: Unable to locate a workspace file for workspace path.
    at Object.readWorkspace (/Users/Name/.nvm/versions/node/v12.18.4/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/workspace/core.js:75:19)
    at async RunCommand.initialize (/Users/Name/.nvm/versions/node/v12.18.4/lib/node_modules/@angular/cli/models/architect-command.js:31:31)
    at async RunCommand.validateAndRun (/Users/Name/.nvm/versions/node/v12.18.4/lib/node_modules/@angular/cli/models/command.js:124:9)
    at async Object.runCommand (/Users/Name/.nvm/versions/node/v12.18.4/lib/node_modules/@angular/cli/models/command-runner.js:198:24)
    at async default_1 (/Users/Name/.nvm/versions/node/v12.18.4/lib/node_modules/@angular/cli/lib/cli/index.js:59:31)
```

## 🌍 Your Environment
```
Angular CLI: 10.1.4
Node: 12.18.4
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.4 (cli-only)
@angular-devkit/core         10.1.4 (cli-only)
@angular-devkit/schematics   10.1.4 (cli-only)
@schematics/angular          10.1.4 (cli-only)
@schematics/update           0.1001.4 (cli-only)
```

Also tested with the @next version and got exactly same issue

```
Angular CLI: 11.0.0-next.6
Node: 12.18.4
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.0-next.6 (cli-only)
@angular-devkit/core         11.0.0-next.6 (cli-only)
@angular-devkit/schematics   11.0.0-next.6 (cli-only)
@schematics/angular          11.0.0-next.6 (cli-only)
@schematics/update           0.1100.0-next.6 (cli-only)

```

**Comment by alan-agius4** [comment] 2020-10-13 06:43
Duplicate of https://github.com/angular/angular-cli/issues/16241

**Closed by alan-agius4** 2020-10-13 06:43 UTC
