### ISSUE TITLE
Memory usage of node process for ng test/serve is very high

### ISSUE THREAD

**Issue by kolbma** [angular/angular-cli#5613] opened 2017-03-24 08:34 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

 ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.2
node: 6.10.1
os: win32 x64 (Win10)
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.10

### Repro steps.

Run npm test or npm start which runs ng test / ng serve

### The log given by the failure.

Memory usage for each node process is between 600MB and 1000MB. That's a lot, I think, although the application is really small (about 500 lines of code).

### Desired functionality.

I can't believe that this high memory usage is intended.

### Mention any other details that might be useful.

Do you need a dump file?

**Comment by filipesilva** [comment] 2017-03-24 15:06
This has been the case for a while, so in that sense it is intended (e.g. not a bug).

I do agree it's quite a bit and there's probably room for improvement there.

**Comment by timruffles** [comment] 2017-03-27 10:08
With a reasonably large project I get OOM when the process hits Node's memory limit. Since you [can't set Node's memory](https://github.com/npm/npm/issues/12238) limit via env var, I have to dig around manually to run the tests.

```

**Comment by kolbma** [comment] 2017-03-27 10:24
@timruffles Yes, the memory usage of npm install is also crazy. But this is another topic.

Is the problem that developers don't understand that JSON-objects in memory need memory and isn't just a virtual, magic document from outer space ;-)

**Comment by buu700** [comment] 2017-05-14 07:35
Running two concurrent `ng serve`s, I had to increase the memory allocated for Docker from 2 GB to 4 GB just to prevent OOMing. This seems really wrong. Is it loading all of node_modules into RAM or something?

**Comment by kpudlik** [comment] 2017-05-15 15:08
Agree. `@angular/cli makes` my laptop's fans getting crazy.
I've made my comparison to pure Webpack setup and `create-react-app` and `@angular/cli` is much worse. Any ideas?

**Comment by reppners** [comment] 2017-08-15 10:31
This issue is rather old but I've never had a problem on my local setup until recently updating to CLI v1.3.0

It's running on macOS Sierra 10.12.6 and I have to restart `ng serve` twice a day because node runs out of memory.

The apps size is about 150 components, no big dependencies other than angular material.

**Comment by russelltrafford** [comment] 2017-09-29 19:20
Since there isnt a suitable recent ticket I can +1, im adding that we're having major issues with Jenkins and angular builds taking up way too much memory and causing the no response in 20000ms issue. From looking at the resources, excessive RAM usage from angular cli and npm seems to be the cause during builds

**Comment by kolbma** [comment] 2017-10-01 09:38
No solution for angular but I'm using now npm 5.4.2 and this version and some before (5.x.y) are much faster and use less memory.

**Comment by jbw91** [comment] 2017-10-03 21:03
I also have gotten to where I'm constantly restarting my `ng serve` due to it running out of memory, and my app isn't very large at all, perhaps 30 components, plus Angular Material.

**Comment by voznik** [comment] 2017-11-18 12:08
![image](https://user-images.githubusercontent.com/5063203/32980128-b20ac63a-cc69-11e7-9c6f-1f226da31a53.png)
I'm on `@angular/cli v 1.5.0` | `node 6.12.0` | `npm 5.4.2`, and `ng serve` uses 1.1Gb of RAM... what the hell?!

**Comment by tinshee** [comment] 2018-01-05 02:38
Any  update？   Same issue using 'ng serve --hmr'

**Comment by leonetosoft** [comment] 2018-06-25 19:21
Same problem here !!!!
When you make changes it will swell !!! It starts low, every time it changes some file it increases.


![memory usage](https://user-images.githubusercontent.com/3596786/41870942-7ada03c8-788b-11e8-912b-8c877fd3cd7d.png)

**Comment by pckrishnadas88** [comment] 2018-07-20 06:54
Same issue. system freezes.

**Comment by valmirphp** [comment] 2018-08-06 23:56
+1

**Comment by leonetosoft** [comment] 2018-08-08 01:15
This softens the situation: node --max_old_space_size=512 \"./node_modules/@angular/cli/bin/ng\" serve
Put in packeage.json in scripts....

**Comment by Franki1986** [comment] 2018-09-04 18:57
Same here, working with latest version of all.. With about 15 components and 3 services getting 3 gb of ram consumption an browser is freezing..

**Comment by RyanZhou713** [comment] 2018-12-03 05:48
+1, Same issue with me, every day need close and open Angular, my project based on Nebular ngx-Admin, about 30~40 components, any update on this issue?  
Version details as below
Node: 8.11.3
OS: win32 x64
Angular: 6.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.3
@angular-devkit/build-angular     0.8.3
@angular-devkit/build-optimizer   0.8.3
@angular-devkit/build-webpack     0.8.3
@angular-devkit/core              0.8.3
@angular-devkit/schematics        0.8.3
@angular/cdk                      5.2.5
@angular/cli                      6.2.3
@ngtools/webpack                  6.2.3
@schematics/angular               0.8.3
@schematics/update                0.8.3
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.20.2

**Comment by mmakarios** [comment] 2018-12-03 12:40
Memory running out was happening to me because I had a serializer file with a function returning an object with several entries.

```
function(obj) {
  return {
    key1: value1,
    key2: value2,
    ...
    key30: value30,
    ...
}
```

Also, some features in VS Code stopped working just by opening this file. After examining its Process Explorer, VS Code's `tsserver` process was utilizing an enormous amount of memory (it was exploding when opening that file and not decreasing after closing it). So in my case the issue was probably related to TypeScript.

I fixed just using `Object.assign()` instead of returning an object directly.

**Comment by laflaneuse** [comment] 2018-12-07 08:06
+1

**Comment by skylarmb** [comment] 2018-12-17 23:15
I have a similar issue. I cant run typescript compilation after deploy on an EC2 instance with 1gb of ram (900+mb free), even with all optimizations turned off. It runs out of memory and crashes almost instantly. 

```json
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": false,
              "namedChunks": false,
              "aot": false,
              "extractLicenses": false,
              "vendorChunk": false,
              "buildOptimizer": false
```

**Comment by skylarmb** [comment] 2019-01-17 19:36
@RodolpheGohard have you tried lowering `max_old_space_size`? 8192mb is 8gb... Try `--max_old_space_size=1024` maybe? I was able to get it working on a system with 1gb of ram (t2.micro) that was previously crashing due to out of memory by setting `--max_old_space_size=900` (900mb), it just made the build process slower.

**Comment by RodolpheGohard** [comment] 2019-01-18 15:44
@skylarmb it fails with a out of memory error

**Comment by adwiens** [comment] 2019-02-21 17:01
Crazy that this is still an issue in 2019...
![screenshot from 2019-02-21 10-55-49](https://user-images.githubusercontent.com/6962078/53187117-05e2ed00-35c8-11e9-912e-a78ee49fe0ed.png)

**Comment by adwiens** [comment] 2019-02-21 17:14
> This softens the situation: node --max_old_space_size=512 "./node_modules/@angular/cli/bin/ng" serve

Doesn't work - "JavaScript heap out of memory"

**Comment by tjvanderende** [comment] 2019-04-14 09:38
> Crazy that this is still an issue in 2019...
> ![screenshot from 2019-02-21 10-55-49](https://user-images.githubusercontent.com/6962078/53187117-05e2ed00-35c8-11e9-912e-a78ee49fe0ed.png)

Yes, can't even run it longer then 30 minus, before my computer runs stuck, due lack of memory. Pretty insane. Only happens with angular cli.

**Comment by blogcraft** [comment] 2019-07-19 15:56
My Node.js is using 1.9 GB of RAM when debugging Angular 8.1.1 😞

**Comment by NuclleaR** [comment] 2019-08-23 17:46
My nodejs process is using 6+ GB of RAM when I run my tests.

**Comment by catchmareck** [comment] 2019-09-10 14:07
Can't believe it hasn't been solved for over 2 years. I don't understand why `ng serve` needs ~600mb of RAM just to run the live development server. It does nothing and it "eats" so much RAM. And when you start changing files, it "eats" even more. Comparing to the `create-react-app` it's really hard to believe that it's absolutely necessary for Angular to reserve so much memory. Has anyone found a tip or something that could be responsible for such high usage?

**Comment by skylarmb** [comment] 2019-09-11 16:34
@catchmareck my solution was quitting and getting a new job at a company that uses React instead of Angular (seriously) 😂

**Comment by achieverprince** [comment] 2019-10-09 05:15
I am also facing this issue.
In Angular 6.X prod build of the project was taking only 2-3 minutes (I don't think it crossed 1GB of RAM usage)
After upgrading to 7.x it takes 8-10 minutes in the same machine (RAM usage is ~5GB now)
Like 3-4 times increase in build time after upgrading.

I am not sure if it is related to Node.js or CLI, but I am spending a solid amount of time building the project every day. :(

**Comment by jlzapata** [comment] 2019-10-23 14:19
I have the same issue. I tested building the app without the build flag and took over 4GB of RAM and with the flag it took over 5GB of RAM. In the task manager the task that take more memory is node.js.

This image is before running the app:
![beforeNgServe](https://user-images.githubusercontent.com/28404174/67401510-3fb42b00-f57d-11e9-8deb-6479175e8bd0.png)

This is after:
![afterNgServe](https://user-images.githubusercontent.com/28404174/67402201-3ecfc900-f57e-11e9-8a07-4143c617ca1c.png)

And this is the version I'm using:
![ngVersion](https://user-images.githubusercontent.com/28404174/67402373-7e96b080-f57e-11e9-8116-7f668465fae3.png)

**Comment by ankurpowar** [comment] 2019-11-07 10:55
Generating new App width ng new TestApp consuming around 300 mb when served with no changes

**Comment by simontol** [comment] 2019-11-08 21:09
I can't believe this is still an issue after 2 years. My PC literally freezes when running 'ng serve'.
Fedora 31 on Intel 8 core Xeon 8gb ram + SSD.

**Comment by dssagar93** [comment] 2019-11-13 07:00
2019 anyone? I have windows 10 and the moment I run ng serve --open to run Angular app, the VS Code suddenly works slow, Visual Studio 2017 also becomes slow and the node.exe CPU usage is super high.

**Comment by KShewengger** [comment] 2019-11-26 15:15
It worked for me by adding `node --max_old_space_size=8048` on your npm script.

Reference:
https://dev.to/koscheyscrag/fix-of-angular-cli-javascript-heap-out-of-memory-error-while-running-ng-serve--1jjh

https://stackoverflow.com/a/56409615/6891406

**Comment by blogcraft** [comment] 2019-12-05 20:15
With Angular 9 right around the corner, let's see if this problem gets worse or better.

**Comment by vpsnotas** [comment] 2019-12-18 22:45
> This softens the situation: node --max_old_space_size=512 "./node_modules/@angular/cli/bin/ng" serve
> Put in packeage.json in scripts....

A little bit better on my mac but using  --max_old_space_size=1024

**Comment by hamed6** [comment] 2019-12-20 07:16
my app angular 8.3(few components) is run on ubuntu 16.4 with 2g memory and im facing the same issue. its being killed, and that's killing me...

**Comment by gotwig** [comment] 2019-12-31 16:07
I try to use Angular together with Glitch.com (something like stackblitz) but I cant use it with ng serve because it regulary exceeds the memory limit of 512 mb so its not usable.

Any idea what I can do? I want to use glitch.com to work on private projects from everywhere...

**Comment by Rahut-5771** [comment] 2020-01-05 18:21
This is really depressing, I am struggling from 2 days to deploy my app on aws t2 micro. I have memory swap of 4GB and still it;s giving the same error.

**Comment by hzeroo** [comment] 2020-02-09 17:56
With Angular 9 the memory usage decreased significantly during `ng serve`, at least for me.

**Comment by blogcraft** [comment] 2020-02-10 15:28
> My Node.js is using 1.9 GB of RAM when debugging Angular 8.1.1 😞

> **Update:** My Node.js is now using 2.6 GB of RAM when debugging Angular 8.2.6 😞

**Update**: My Node.js is now using 901 MB of RAM when debugging Angular 9.0.0 🎈🥳

**Comment by blogcraft** [comment] 2020-02-12 13:32
> My Node.js is using 1.9 GB of RAM when debugging Angular 8.1.1 😞

> **Update:** My Node.js is now using 2.6 GB of RAM when debugging Angular 8.2.6 😞

**Update:** My Node.js is now using 1..5 GB of RAM when debugging Angular 9.0.0 😮

**Comment by wartab** [comment] 2020-02-24 16:01
Since Angular 9, our project reached an all time high of 2.3 GB for `ng serve` and 0.7 GB for a process type-checker-worker. Webstorm using 2 GB on startup and the JS language service of Webstorm using 1.1 GB, we're already at over 6 GB RAM used just for basic client sided development tools. Add Chrome with Dev tools, Visual Studio, and SQL Server and fairly good developer machines with 16GB RAM are starting to tank a severe performance hit.

I can remember Angular's processes using way less RAM a year ago. I'm unsure what exactly caused this to progressiveley increase.

**Comment by blogcraft** [comment] 2020-02-24 21:58
> Since Angular 9, our project reached an all time high of 2.3 GB for `ng serve` and 0.7 GB for a process type-checker-worker. Webstorm using 2 GB on startup and the JS language service of Webstorm using 1.1 GB, we're already at over 6 GB RAM used just for basic client sided development tools. Add Chrome with Dev tools, Visual Studio, and SQL Server and fairly good developer machines with 16GB RAM are starting to tank a severe performance hit.
> 
> I can remember Angular's processes using way less RAM a year ago. I'm unsure what exactly caused this to progressiveley increase.

Tried using only VS Code instead of WebStorm and Visual Studio?

**Comment by joschne** [comment] 2020-03-11 09:09
Is starting to get problematic in our company: Computers with not more than 8 GB RAM start to freeze. We're using Angular CLI 8.3.22. I hope Angular 9 makes it better.

According to @blogcraft it gets a little better, according to @wartab it's getting worse.

Is there more people having experience with 9?

**Comment by Franki1986** [comment] 2020-03-11 09:52
For me it is getting better. Release build time earlyer was over 3 minutes with 3.5 memory of ram usage. Now under 2 minutes and 2gb with angular 9.
I have a big project with devextreme coponents.

**Comment by arielmoraes** [comment] 2020-04-14 06:47
Could a team member or a top colaborator from the Angular project give us some detailed information about why that happens? That RAM usage is horrible for some software houses.

**Comment by Sarfarazsajjad** [comment] 2020-04-18 18:25
macbook pro 2015 core i7, 16gb ram, fans going crazy with ng build, ng test, ng server etc.  
@angular/cli 8.3.21,

also most ci platforms have 4gb ram limit, so our tests and builds are failing on pipeline

**Comment by blogcraft** [comment] 2020-04-19 16:10
> macbook pro 2015 core i7, 16gb ram, fans going crazy with ng build, ng test, ng server etc.
> @angular/cli 8.3.21,
> 
> also most ci platforms have 4gb ram limit, so our tests and builds are failing on pipeline

I use Azure DevOps for CI, maybe give it a shot?

**Comment by vrkansagara** [comment] 2020-05-17 13:54
I think Angular core team has to come up with solution otherwise they are going to loosing developer.Because developer can not buy machine every year but they can learn new thing every year. 
![image](https://user-images.githubusercontent.com/12006483/82149122-0d00b580-9874-11ea-8784-c34e946b1e78.png)

**Comment by intellix** [comment] 2020-05-17 13:55
the CPU usage is insane as well. I've got ng serve running locally in the background and haven't touched the frontend for at least an hour, just left it idle. It's using 90% CPU and I'm not using it.

This is on a MBP 15" Late 2019

**Comment by timothyBrake** [comment] 2020-05-22 10:40
> the CPU usage is insane as well. I've got ng serve running locally in the background and haven't touched the frontend for at least an hour, just left it idle. It's using 90% CPU and I'm not even using it.
> 
> This is on a MBP 15" Late 2019

High CPU usage (constant 90% on ng serve) on a MacBook Pro can be solved by installing newest version of fsevents
The high memory usage is still a mystery though so any response from dev team would be great.

**Comment by alan-agius4** [comment] 2020-05-26 08:34
Hi all, this issue has been open for 3 years now and was originally reporting using Angular CLI `1.0.0-rc.2`.

Since then, a lot of things changed in Angular and Angular CLI, while memory usage might still be high when using `ng serve` and `ng test`. It's very unlikely that the root cause is shared with that of 3 years.

While there are a lot of comments in this thread, little provide actionable information

**Comment by alan-agius4** [comment] 2020-05-26 08:51
Hi all,

This thread has been open for 3 years now and was originally reporting using Angular CLI `1.0.0-rc.2`.

Since then, a lot of things changed in the entire eco-system, while memory usage might still be high when using `ng serve` and `ng test` today. It's very unlikely that the root cause is the same as that of 3 years ago.

Having all the feedback in a single thread makes it hard to get meaningful reports, or to inform people of what versions the regressions that affect them were fixed.

High memory usage can have a number of root causes ranging from a Node.js (EX version 11 is known to have memory related bugs), compiler, application architecture, NGCC or Angular CLI. Unfortunately without a reproduction (Even shared privately) it would be almost impossible to find and solve the root cause.

Thus, my recommendation would be to open new issue and provide all the information requested in the issue template, that way we will be able to action the issue. 

Thank you all for your understanding.

**Closed by alan-agius4** 2020-05-26 08:51 UTC
Labels: comp: devkit/build-angular, freq2: medium, severity4: memory/performance, type: bug/fix

**Comment by wartab** [comment] 2020-05-26 08:54
Imagine closing the issue being the only response to this increasingly worsening problem.

**Comment by alan-agius4** [comment] 2020-05-26 10:23
@wartab, on my machine a new Angular projects takes 366Mb for the main process + 169Mb for the forked checker during `ng serve`,  of course as an application get bigger and bigger so does the memory requirements.

![Screenshot 2020-05-26 at 12 05 10](https://user-images.githubusercontent.com/17563226/82888097-34791180-9f49-11ea-95ac-36835b7e0d5f.png)

Unfortunately, this is no silver bullet that solves the memory issue, and every problem here might very well have a different root cause. Yet there isn't enough information in a given comment to help use understand how we can reproduce the issue. So please help us to help you, by filling a new issue providing all the information required even better a reproduction.

We deferentially do want to get to the bottom of this, but cannot investigate and eventually fix something which we cannot reproduce.

**Comment by arielmoraes** [comment] 2020-05-26 13:46
@alan-agius4 in your perspective, is it normal a new project consuming almost 500 Mb of RAM? I think you just reproduced the issue.

**Comment by SchnWalter** [comment] 2020-05-26 14:43
@arielmoraes, there isn't much Angular CLI can do abut this. I would say, 500 MB is resonable given the complexity of the Angular CLI.

Also, you can see that the TypeScript compiler can consumes a GB on a medium projects, just search for [high memory usage](https://github.com/microsoft/TypeScript/search?q=high+memory+usage&type=Issues) in the TypeScript issue queue.

If you are still not convinced, you can build the demo file from [Building your first TypeScript file](https://www.typescriptlang.org/docs/handbook/typescript-tooling-in-5-minutes.html) handbook, it consumes 152MB. So, I would say that 500MB for Angular CLI is very good. If you want to convince your self, here's a repo:
> https://github.com/SchnWalter/typescript-memory-usage

that contains that just builds this file:
```ts
function greeter(person) {
  return "Hello, " + person;
}

let user = "Jane User";

document.body.textContent = greeter(user);
```

If you run `npm run build:log-memory-usage` (linux/mac required for memory usage stats), you will see this output. `152MB` for the code above + one comment.
```
> typescript-memory-usage@1.0.0 build:log-memory-usage /workspace/playground/typescript-memory-usage
> /usr/bin/time --verbose -- npm run build
> typescript-memory-usage@1.0.0 build /workspace/playground/typescript-memory-usage
> tsc greeter.ts
Command being timed: "npm run build"
User time (seconds): 2.68
System time (seconds): 0.08
Percent of CPU this job got: 160%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.72
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 152856
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 0
Minor (reclaiming a frame) page faults: 39940
Voluntary context switches: 1976
Involuntary context switches: 343
Swaps: 0
File system inputs: 0
File system outputs: 16
Socket messages sent: 0
Socket messages received: 0
Signals delivered: 0
Page size (bytes): 4096
Exit status: 0
```
