### ISSUE TITLE
'ng generate enum' generates class instead

### ISSUE THREAD

**Issue by arispen** [angular/angular-cli#7855] opened 2017-09-27 10:15 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.3
node: 7.0.0
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4

### Repro steps.

$ ng generate enum testenum
  create src/app/testenum.enum.ts (26 bytes)

generated file contents:
```
export class Testenum {
}

```

**Comment by filipesilva** [comment] 2017-09-27 11:07
Duplicate of https://github.com/angular/angular-cli/issues/7639, fixed by https://github.com/angular/devkit/pull/160.

**Closed by filipesilva** 2017-09-27 11:07 UTC
