### ISSUE TITLE
Wrong Import Path of a component.

### ISSUE THREAD

**Issue by ahaan729** [angular/angular-cli#2419] opened 2016-09-29 15:33 UTC
### OS?
> Windows 7

### Versions.
> angular-cli: 1.0.0-beta.16
> node: 6.6.0
> os: win32 x64

### Repro steps.
- Created a new component with the below command
   ng g component home/tabs/tab

- The import statement in the AppModule.ts becomes incorrect 
    **import { TabComponent } from './home\tabs\tab/tab.component';**

### The log given by the failure.
- Cannot find module './home      abs     ab/tab.component'.

### Mention any other details that might be useful.

- Every time I create a new component under an existing component the path of the import statement needs to be corrected manually.
    **import { TabComponent } from './home/tabs/tab/tab.component';**
- That's a major fix to be done. Else creating components in the sub-folders would create an every time.

**Comment by gelliott181** [comment] 2016-09-29 16:43
Please see #2132 and #2357.

You can't generate components in subdirectories right now because doing so pulls the path directly from the OS. Thanks to Windows prefering `\` we get mix and match slashes in our paths.

**Comment by ahaan729** [comment] 2016-09-30 05:02
So is it wrong to create a Child Component that way?
And will this be supported in later versions?

**Comment by filipesilva** [comment] 2016-10-05 20:48
Dupe of https://github.com/angular/angular-cli/issues/1719, has been fixed since.

**Closed by filipesilva** 2016-10-05 20:48 UTC

**Comment by ahaan729** [comment] 2016-10-09 16:37
Thanks @filipesilva
