### ISSUE TITLE
fix(generate/service): creation output appears twice

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular-cli#347] opened 2016-03-25 10:54 UTC
Running

```
ng g service contacts-service
```

Generates the following output

```
$ ng g service contacts-service
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
installing service
  create src/app/services/contacts-service/contacts-service.spec.ts
  create src/app/services/contacts-service/contacts-service.ts
  create src/app/services/contacts-service/contacts-service.spec.ts
  create src/app/services/contacts-service/contacts-service.ts
```

Not sure if it in fact **creates** the service + spec file twice, or if it just logs twice. If the former, then ofc the second call will override the first one, so the resulting files are okay.

However, I think this needs to be fixed.

**Comment by Brocco** [comment] 2016-03-28 02:52
Was this with version 0.0.26 or 0.0.27? I have not been able to reproduce locally. The concept of a `services` directory has been deprecated and should not created unless you specified you wanted it created there.

**Comment by Brocco** [comment] 2016-04-19 13:56
Closing as I have not been able to reproduce this.

@PascalPrecht if you are still seeing this, it may possibly be due to you having the CLI npm linked and globally installed? Try that fix and if that doesn't work, reopen and we can re-investigate.

**Closed by Brocco** 2016-04-19 13:56 UTC
