### ISSUE TITLE
install angular-cli error

### ISSUE THREAD

**Issue by yalishizhude** [angular/angular-cli#4670] opened 2017-02-13 15:51 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> node 4.5

### Repro steps.
> npm i -g @angular/cli

### The log given by the failure.
> gyp info using node-gyp@3.5.0
gyp info using node@4.4.7 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "D:\Work\python\python.exe" in the PATH
gyp verb `which` succeeded D:\Work\python\python.exe D:\Work\python\python.exe
gyp verb check python version `D:\Work\python\python.exe -c "import platform; print(platform.python_version());"` returned: "3.6.0\r\n"
gyp verb could not find "D:\Work\python\python.exe". checking python launcher
gyp verb could not find "D:\Work\python\python.exe". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "D:\Work\python\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (D:\Work\Nodejs\node_modules\@angular\cli\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at Object.<anonymous> (D:\Work\Nodejs\node_modules\@angular\cli\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at D:\Work\Nodejs\node_modules\@angular\cli\node_modules\node-sass\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "D:\\Work\\Nodejs\\node.exe" "D:\\Work\\Nodejs\\node_modules\\@angular\\cli\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Work\Nodejs\node_modules\@angular\cli\node_modules\node-sass
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Work\\Nodejs\\node.exe" "D:\\Work\\Nodejs\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\yalis\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=C:\\Users\\yalis\\.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=D:\\Work\\Nodejs\\node_modules\\cnpm\\node_modules\\node-gyp\\bin\\node-gyp.js" "i" "-g" "@angular/cli"
npm ERR! node v4.4.7
npm ERR! npm  v2.14.22
npm ERR! code ELIFECYCLE
npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\yalis\npm-debug.log

### Mention any other details that might be useful.

python directory
![image](https://cloud.githubusercontent.com/assets/3870098/22890313/f405e234-f246-11e6-9588-47b5dd793cdb.png)
env PYTHON
![image](https://cloud.githubusercontent.com/assets/3870098/22890344/0c071204-f247-11e6-9834-c9422b496724.png)

**Comment by Ploppy3** [comment] 2017-02-13 16:01
It requires [Node 6.9.0](https://github.com/angular/angular-cli#prerequisites)

**Comment by filipesilva** [comment] 2017-03-09 13:57
It might not look like it, but this is a dupe of https://github.com/angular/angular-cli/issues/4429.

Your system cannot get the `node-sass` binary so it's trying to build it manually.

**Closed by filipesilva** 2017-03-09 13:57 UTC
