### ISSUE TITLE
`ng new` with --skipGit still generates some git files

### ISSUE THREAD

**Issue by jelbourn** [angular/angular-cli#18122] opened 2020-07-02 13:31 UTC
# Bug report

### Command
```
ng new --skipGit appname
```

### Description

Running `ng new` with `--skipGit` still generates a `.gitignore` and a `.gitkeep` file. 

## Minimal Reproduction
```
ng new --skipGit appname
```

### Environment
Angular CLI: 10.0.1
Node: 12.18.2
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1000.1
@angular-devkit/core         10.0.1
@angular-devkit/schematics   10.0.1
@schematics/angular          10.0.1
@schematics/update           0.1000.1
rxjs                         6.5.5

**Comment by alan-agius4** [comment] 2020-07-02 14:34
Duplicate of https://github.com/angular/angular-cli/issues/8638

**Closed by alan-agius4** 2020-07-02 14:34 UTC

**Comment by alan-agius4** [comment] 2020-07-02 15:55
@jelbourn, can you please provide some more insights in the above mentioned issues to why `skipGit` should not create ‘.git‘ files? thanks.

**Comment by jelbourn** [comment] 2020-07-06 23:31
In my case I already had a `gitignore` in my repo and the Angular CLI project was in a subdirectory. I just interpreted `skipGit` as "Skip everything related to git" and not "Don't initialize a git repo from scratch". Don't feel super strongly either way. (Also I didn't find the existing issue because I searched for "skipGit" instead of "skip-git")
