### ISSUE TITLE
while preloading modules view will be struck

### ISSUE THREAD

**Issue by adityarw** [angular/angular-cli#11987] opened 2018-08-23 14:35 UTC
i have around 10 modules each module contains atleast of 25-30 components, while preloading all the modules the login view will be struck m unable to fill the login credentials until it load all the module..

please add this feature..

please preload the modules background so that we can do our work on current view..

HI,

This is feature request.

In document they have given we can request feature so please don't close this..

**Comment by alan-agius4** [comment] 2018-08-23 15:43
Duplicate of #11344

**Closed by alan-agius4** 2018-08-23 15:43 UTC
