### ISSUE TITLE
ng serve loads data outside its root folder

### ISSUE THREAD

**Issue by JimmyBjorklund** [angular/angular-cli#21162] opened 2021-06-18 14:47 UTC
Hi The ng serve loads data outside its root folder:

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✔ Compiled successfully.
Watchpack Error (initial scan): Error: EACCES: permission denied, lstat '/mnt/c/DumpStack.log.tmp'
Watchpack Error (initial scan): Error: EACCES: permission denied, lstat '/mnt/c/hiberfil.sys'
Watchpack Error (initial scan): Error: EACCES: permission denied, lstat '/mnt/c/pagefile.sys'
Watchpack Error (initial scan): Error: EACCES: permission denied, lstat '/mnt/c/swapfile.sys'
Watchpack Error (stats): Error: EACCES: permission denied, lstat '/mnt/c/pagefile.sys'

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Dont know, sorry

### Description

When starting the ng serve, to looks way outside its root directory.

## 🔬 Minimal Reproduction

Ubuntu on windows. 
start any angular project that is located on c drive and it will access data outside its 
root directory.

Angular CLI: 12.0.5
Node: 14.15.0
Package Manager: npm 7.6.3
OS: linux x64

Angular: 12.0.5
... animations, cli, common, compiler, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4

**Comment by alan-agius4** [comment] 2021-06-18 15:21
This looks like watchpack bug https://github.com/webpack/watchpack/issues/187

**Comment by alan-agius4** [comment] 2021-06-22 08:32
Closing since this is caused by an upstream package and is not actionable from our end. Please continue following and provide necessary details in https://github.com/webpack/watchpack/issues/187

**Closed by alan-agius4** 2021-06-22 08:32 UTC
