### ISSUE TITLE
Incompatible peer dependencies found when updating a brand new project

### ISSUE THREAD

**Issue by willgm** [angular/angular-cli#11138] opened 2018-06-06 20:26 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
Angular CLI: 6.0.8
Node: 8.9.0
OS: linux x64
Angular: 6.0.4

### Repro steps
```shell
ng new my-proj
cd my-proj
ng update --all
```

### The log given by the failure
```
                  Package "karma-jasmine-html-reporter" has a missing peer dependency of "jasmine" @ ">=3".
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.9.1").
Incompatible peer dependencies found. See above.
```

### Desired functionality
To have a successful message.

**Comment by tsu-la** [comment] 2018-06-07 14:01
I also ran into this issue and trying to install typescript 2.8  installs version 2.8.4 which also gives an error.

**Comment by aphexddb** [comment] 2018-06-07 15:40
Also seeing this migrating an older project,.

### Versions
Angular CLI: 6.0.8
Node: 8.9.4
OS: OSX 10.13.5
Angular: 4.4.7

### Repro steps
ng update --all

### The log given by the failure

```
ng update --all
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.9.1")
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.9.1").
Incompatible peer dependencies found. See above.
```

**Comment by hansl** [comment] 2018-06-07 17:06
Hi @aphexddb,

Unfortunately, this one comes down as a feature. `ng update --all` will still validate that all dependencies are compatible with each others, but typescript's `latest` is 2.9, which isn't compatible with Angular's compiler. You can use `ng update --all --force` to force the update, or just update dependencies one at a time.

Now there's a case to be made that `--all` should be smarter and only update compatible versions. I think we need a feature in the future (e.g. `--smart`) that would do that, but in the meantime this is the best that makes sense.

Closing this as working as intended.

**Closed by hansl** 2018-06-07 17:06 UTC
Labels: schematics/update

**Comment by willgm** [comment] 2018-06-07 21:13
Hi @hansl,

In a new project, if we run just `ng update` is says that there is nothing to update, but if we use the flag `--all` it gives this "incompatible peer dependency" error. It looks contradictory or at least confusing for me. Shouldn't the `--all` flag just execute what is at the `ng update` list? And do nothing if it is empty?

**Comment by Trapulo** [comment] 2018-06-12 15:25
ame error updating an existing project from angular 5.2 to 6.0.4

**Comment by Fieel** [comment] 2018-12-12 09:53
Any news on this? I installed Typescript 3.1.6 as a workaround and have no problems.
