### ISSUE TITLE
Is Versioning of Resources supported? We are using angular-cli for production app. We are in need of versioing of resources support, when ever we do a production build, so that end user doesn't refresh the cache inorder to load the new resources.

### ISSUE THREAD

**Issue by jagadeshpaladugula** [angular/angular-cli#1328] opened 2016-07-12 06:08 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by efriandika** [comment] 2016-07-13 07:27
look at to #987

**Comment by jagadeshpaladugula** [comment] 2016-07-13 08:13
@efriandika  Thanks a lot for pointing to the root issue

**Comment by Splaktar** [comment] 2016-07-14 04:33
Duplicate of #1327 please close.

**Closed** 2016-07-14 06:00 UTC
