### ISSUE TITLE
Hi I tried to install angular cli through the command :

### ISSUE THREAD

**Issue by Hema-Sasank** [angular/angular-cli#20378] opened 2021-03-25 17:58 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment] 2021-03-26 18:16
Duplicate of #20379

**Closed by clydin** 2021-03-26 18:16 UTC
