### ISSUE TITLE
Default tab size

### ISSUE THREAD

**Issue by IRCraziestTaxi** [angular/angular-cli#4852] opened 2017-02-20 20:42 UTC
In #1252 the request for CLI options or ability to reference .editorconfig for tab size when generating files was largely ignored. The reasoning was fair - too much effort for minimal impact on a matter of style, not functionality.

However, many, many comments were made that 4 spaces is by and large the accepted standard - basically universally accepted. @filipesilva stated that:

"The style guide has no recommendations on tabs vs spaces..."

So why not conform to the undisputed fact that 4 spaces is standard and make 4 spaces the default? I have seen nobody say that 2 spaces is preferred or even that it is not ugly and does not make code hard to read - quite the opposite, in fact.

**Comment by filipesilva** [comment] 2017-02-20 21:13
Dupe of https://github.com/angular/angular-cli/issues/1252.

**Closed by filipesilva** 2017-02-20 21:13 UTC

**Comment by IRCraziestTaxi** [comment] 2017-02-20 21:16
@filipesilva I would argue this is not a duplicate because #1252 regarded not having an option or functionality to change the default tab size. This issue regards changing the tab size altogether.

**Comment by filipesilva** [comment] 2017-02-20 21:26
I'm sorry but all there is to be said about this topic has already been said in #1252. 

I recognise and understand that different users have different preferences regarding this subject, and that it is annoying to have to reformat after running generators. 

The solution to that is not to take switch from one default to the other, it is to offer the option as described in #1252. But as I said on https://github.com/angular/angular-cli/issues/1252#issuecomment-281070150 that's something to be looked at in v2.0 at best.
