### ISSUE TITLE
Cannot generate a component on a dir path other than the default "app/" 

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12141] opened 2018-09-04 23:24 UTC
_From @shairez on March 2, 2018 9:41_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
Node v8.9.0
Npm 5.6.0
Windows 10

### Repro steps

Let's say I have the following structure - 

```
app/
  app.module.ts

custom-app/
  app.module.ts
```

And I want to create a new component under `custom-app`

From the root of the project, trying to run any of these : 

`ng g c my-comp -m="../custom-app/app.module.ts"`
**or**
`ng g c custom-app/my-comp -m="../custom-app/app.module.ts"`
**or even**
`ng g c /src/custom-app/my-comp -m="../custom-app/app.module.ts"`

results in a component being created under the `/app` folder and not `/custom-app`. 

### The log given by the failure
```js
  create src/app/custom-app/my-comp/my-comp.component.html (26 bytes)
  create src/app/custom-app/my-comp/my-comp.component.spec.ts (629 bytes)
  create src/app/custom-app/my-comp/my-comp.component.ts (271 bytes)
  create src/app/custom-app/my-comp/my-comp.component.css (0 bytes)
  update src/custom-app/app.module.ts (419 bytes)
```

### Desired functionality

I would expect that - 

1. Specifying a module would create the component underneath that specific module's folder

2. If not, at least specifying a different path (starting from the `src` folder) will generate that component under that custom path

### Mention any other details that might be useful
none

_Copied from original issue: angular/devkit#476_

**Comment by pascallaprade-beslogic** [comment] 2018-10-29 22:48
We also have this issue, and have the same definition for required functionality.

Here is the output of `npx ng --version`:

```
λ npx ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.0.3
Node: 11.0.0
OS: win32 x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```

### Details

If we try to create a new component, for example `ng generate component Test`, it will be created in `src/app/test`. If we specify a subfolder, it will also be relative to app. For example, `ng generate component shared/Test` will be created in `src/app/shared/test`.

However, we do not want all our code to be located in `app`, as we think that `src` is a sufficient root for our code to live in.

The only way we can avoid this problem is by either execute the generate command from the target folder, or to start our paths with `..`.

I will open a separate issue for that (if there is none already existing), but when generating components with a relative `..` path, our `styleext` configuration is ignored and the stylesheet generated is plain CSS, so this is not an option for us.

Moving around in the folders could work, but since we have many components to generate, it will become tedious to constantly navigate to the proper folder before generating said new components.

As such, I would expect that the generate command should generate entities relative to the `sourceRoot` path defined in the `angular.json` config file. For us, the `sourceRoot` is the default value, `src`.

### Desired functionality

If `sourceRoot` means something else than "the root folder where the source code lives", then a new configuration option should be added, such as `generateRoot`, so that we can specify ourselves the directory in which `generate` targets should be generated. Otherwise, `generate` should generate entities relatively to the `sourceRoot` path specified in the `angular.json` configuration file, as suggested by the author of the issue. If there is a reason why this cannot or should not be done, said reason should be clearly documented so that we can refer to that documentation when taking code structure decisions.

**Comment by alan-agius4** [comment] 2023-04-27 15:01
Duplicate of https://github.com/angular/angular-cli/issues/9370

**Closed as completed** 2023-04-27 15:01 UTC
Labels: feature, area: @schematics/angular, feature: insufficient votes
