### ISSUE TITLE
touched/untouched not working with ng build --prod

### ISSUE THREAD

**Issue by MaxGorshkov** [angular/angular-cli#8997] opened 2017-12-26 08:10 UTC
### Versions
```
ng --version

Angular CLI: 1.6.2
Node: 9.3.0
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
* Step 1
ng new testProject
* Step 2
cd testProject
* Step 3
npm install
* Step 4
add code in /src/app/app.component.html:

```
  <li>
    <h2><a target="_blank" rel="noopener" href="https://blog.angular.io/">Angular blog</a></h2>
  </li>
  <!--my code begin-->
  <li>
    <div>
      <label>field</label>
      <input [(ngModel)]="model.field" #field="ngModel"/>
    </div>
  </li>
  <li>
    <div>untouched - {{field.untouched}} </div>
    <div>pristine - {{field.pristine}} </div>
  </li>
  <!--my code end-->
```
* Step 5
add code in /src/app/app.component.ts:
```
export class AppComponent {
  title = 'app';
  // my code begin
  model = {
    field: ''
  };
  // my code end
}
```
* Step 6
add code in /src/app/app.module.ts:

`import { FormsModule, ReactiveFormsModule } from '@angular/forms';`
...
```
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule
  ],
```
* Step 7
npm run build

### Observed behavior
![wrong](https://user-images.githubusercontent.com/14037804/34351325-bf438ee4-ea3d-11e7-81e1-7a5595aec185.gif)

### Desired behavior
as after run ng serve:
![success](https://user-images.githubusercontent.com/14037804/34351327-c3a6cbe0-ea3d-11e7-96f4-6087ebd79282.gif)

**Comment by julianobrasil** [comment] 2017-12-26 10:15
In fact it seems that more things are not working here. I comment another issue in Material 2 repo, but I think it's related. Below is the copy of what I posted in Material Repo.

> (...) I could reproduce it in a test app, available in heroku. In the images below you can notice that not just the label stops working, **but also the interpolation** (see the gifs, just beneath the inputs). It doesn't seems to be related just to material... maybe `@angular/cli`'s `build-optimizer` flag has something to do with it. I noticed the problem using Chrome and Firefox (Windows 10)

### without --prod

![image](https://media.giphy.com/media/l0HUqJQsXldkSGwpy/giphy.gif)

### with --prod
![image](https://media.giphy.com/media/l49JPlaGVUnsSvj0c/giphy.gif)

If it helps, the repo for the test app above: https://github.com/julianobrasil/material2-test

Some time after you push to master (it's not protected - anyone can push), the app can be viewed from https://angular-julianobrasil.herokuapp.com/ (it's a free heroku account so it goes to sleep after 30 min idle and takes some time to wake up after someone tries do access it for the first time)

**Comment by cuiliang** [comment] 2017-12-26 11:25
I have slimier problem. 
If publish site with 'ng build --prod', (keydown) and (click) of a input control will not fire. 
If use ' ng build --aot --build-optimizer true --output-hashing all --extract-css true --name
d-chunks false --sourcemaps false --environment prod', the events will be fired normally.

cli version: 1.6.2
angular version: 5.1.2

**Comment by trotyl** [comment] 2017-12-26 11:27
Likely to be caused by [`uglify-es`](https://unpkg.com/uglify-es@3.3.2/)'s latest update.

**Comment by julianobrasil** [comment] 2017-12-26 11:42
@cuiliang, I'll try that. But the funny part is that if I compile the project locally (in my Windows 10 machine), it seems to work just fine. When I deploy to heroku (compile remotely), the problem comes up.

**Comment by julianobrasil** [comment] 2017-12-26 11:43
@cuiliang, it worked

**Comment by julianobrasil** [comment] 2017-12-26 11:45
This @cuiliang's suggestion (https://github.com/angular/angular-cli/issues/8997#issuecomment-353957698) worked for me:

```
ng build --aot --build-optimizer true --output-hashing all --extract-css true --name
         d-chunks false --sourcemaps false --environment prod
```

**Comment by trotyl** [comment] 2017-12-26 12:17
```javascript
new UglifyJSPlugin({
    sourceMap: buildOptions.sourcemaps,
    uglifyOptions: {
        ecma: wco.supportES2015 ? 6 : 5,
        warnings: buildOptions.verbose,
        ie8: false,
        // mangle: {
        //     safari10: true,
        // },
        mangle: false,
        compress: uglifyCompressOptions,
        output: {
            ascii_only: true,
            comments: false,
            webkit: true,
        },
    }
}),
```

Confirmed it can be solved by disable the `mangle` option in uglifyJS plugin.

**Comment by filipesilva** [comment] 2017-12-26 13:08
@julianobrasil Thank you for putting up a repro, it helps a lot. I'm trying to see what the issue with it but I don't think I can reproduce... This is what I did:

```
git clone https://github.com/julianobrasil/material2-test
cd material2-test
npm i
npm run ng -- serve --prod
```

Then I opened `http://localhost:4200/` and interacted with the boxes:

![material2](https://user-images.githubusercontent.com/4172079/34357250-65c21e9e-ea3d-11e7-9726-7c06d60f664b.gif)

The input box content seems to be reflected outside of it.

@julianobrasil mentioned it doesn't happen locally for him (https://github.com/angular/angular-cli/issues/8997#issuecomment-353959248) so maybe that's why it doesn't happen locally for me either.

Other users mentioned disabling Uglify mangle helped. Maybe it is related to the Uglify version. We use `uglifyjs-webpack-plugin` which internally uses `uglify-es`. You can check the versions with `npm ls uglify-es`:
```
$ npm ls uglify-es
material2-test@0.0.0 D:\sandbox\material2-test
`-- @angular/cli@1.6.2
  `-- uglifyjs-webpack-plugin@1.1.2
    `-- uglify-es@3.2.1
```

For users that are experiencing this problem, what version of `uglify-es` is displayed **on the machine where the bundle is built**?

**Comment by vthinkxie** [comment] 2017-12-26 13:11
@filipesilva `uglify-es@3.3.2` will cause the error.

**Comment by julianobrasil** [comment] 2017-12-26 13:27
@filipesilva, I did a lot of things after my comment above saying it worked fine over here... now the problem is happening locally too. I don't know whether the uglify was 3.2.1 at that time, but now:

![image](https://user-images.githubusercontent.com/25405143/34357622-c3f3efdc-ea2f-11e7-8a53-f276051fd67e.png)

**Comment by trotyl** [comment] 2017-12-26 13:29
Bisected to `3.2.2`(OK) to `3.3.0`(Not OK)

**Comment by julianobrasil** [comment] 2017-12-26 13:39
Just to confirm @trotyl's info, in other projects that are still working right:

![image](https://user-images.githubusercontent.com/25405143/34357834-6cc53642-ea31-11e7-8361-6ad0c2dc7ef4.png)

**Comment by filipesilva** [comment] 2017-12-26 13:49
I'm investigating what changed in the uglify output between those two versions.

Meanwhile for those affected you can force install `uglify@3.2.2` by running this command:
```
npm i uglify-es@3.2.2 --save-exact && rm -rf package-lock.json node_modules && npm i && npm ls uglify-es
```

At the end it should output the following:
```
+-- @angular/cli@1.6.2
| `-- uglifyjs-webpack-plugin@1.1.2
|   `-- uglify-es@3.2.2  deduped
`-- uglify-es@3.2.2
```

You can see the right version (`3.2.2`) version is listed under `uglifyjs-webpack-plugin`. This is a temporary workaround.

**Comment by filipesilva** [comment] 2017-12-26 14:52
I've been looking into this and saving output in https://github.com/filipesilva/material2-test/tree/uglifyjs-debug.

I haven't found what changed exactly yet. You can see the different in output for the main bundle in https://github.com/filipesilva/material2-test/commit/cf6a59e3961be5c4b6a0f9671690200cd19a762d?w=1 (click `Load diff` for `uglify-es@3.2.2` on the left and `uglify-es@3.3.2` on the right).

I can say that a fair bit has changed though. I can also see that the main bundle is 12k bigger with `3.3.2`.

**Comment by filipesilva** [comment] 2017-12-26 15:21
@kzc do you perhaps have an idea of what might have changed, or what I can do to narrow down my search of what's broken?

**Comment by mlurker** [comment] 2017-12-26 16:11
@filipesilva our project is also affected. When we deploy, a flag --prod is used. I've followed this direction and it helped: https://github.com/angular/angular-cli/issues/8997#issuecomment-353957698
Replacing --prod with list of options eliminates one of the steps that invokes UglifyJS (https://github.com/angular/angular-cli/wiki/build).

**Comment by kzc** [comment] 2017-12-26 16:15
@filipesilva Please take a look at the `uglify-es` commit log for recent changes and bug fixes:

https://github.com/mishoo/UglifyJS2/commits/harmony

All I can suggest is to update to the most recent version and if it still fails then file an uglify issue with a reproducible JS input.

**Comment by joaopgrassi** [comment] 2017-12-26 16:22
Can confirm this as well. I was just about to publish my Angular chrome extension and when running --prod the styles are all messed up. As @mlurker and @cuiliang mentioned, running the commands fixes the problem.

**Comment by filipesilva** [comment] 2017-12-26 16:24
@mlurker I suggest you use my workaround in https://github.com/angular/angular-cli/issues/8997#issuecomment-353970841 instead of replacing the build command, as doing the latter will leave you with much bigger bundles.

@kzc I'm going through the most recent commits (https://github.com/mishoo/UglifyJS2/pull/2656, https://github.com/mishoo/UglifyJS2/pull/2658 and https://github.com/mishoo/UglifyJS2/pull/2659) and applying them manually but it doesn't seem to make a difference. Also tried https://github.com/mishoo/UglifyJS2/pull/2661.

Trying to get in touch with the core team to figure out which bits of core code could originate the current behaviour to narrow it down and get you a good issue repro.

**Comment by slubowsky** [comment] 2017-12-26 16:30
For what its worth very similar problems with other non material components as well (ngx-bootstrap if it matters). They are non functional, silently not reacting to user clicks. Curiously, the same components used elsewhere on the same page (in other lazy loaded components) continue to work.

Running with `ng serve --aot --build-optimizer true --output-hashing all --extract-css true --named-chunks false --sourcemaps false --environment prod` as suggested above, everything works.

**Comment by filipesilva** [comment] 2017-12-26 16:40
https://github.com/angular/angular-cli/issues/8992 has the same root cause as this issue.

**Comment by Alekcei** [comment] 2017-12-26 21:21
How resolve problem
```
[alekcei@localhost BID]$ npm ls uglify-es
app5test@0.0.0 /home/alekcei/workspase/BID
└─┬ @angular/cli@1.6.2
  └─┬ uglifyjs-webpack-plugin@1.1.4
    └── uglify-es@3.3.2 
```
```[alekcei@localhost BID]$ ./node_modules/.bin/ng  -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.2
Node: 8.1.2
OS: linux x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```
But not working
The problem is similar in the commentary
https://github.com/angular/angular-cli/issues/8997#issuecomment-353950777

**Comment by julianobrasil** [comment] 2017-12-26 21:24
@Alekcei, take a look at https://github.com/angular/angular-cli/issues/8997#issuecomment-353970841

**Comment by Alekcei** [comment] 2017-12-26 21:35
Sorry.
```npm i uglify-es@3.2.2 --save-exact```
```
[alekcei@localhost BID]$ npm ls uglify-es
app5test@0.0.0 /home/alekcei/workspase/BID
├─┬ @angular/cli@1.6.2
│ └─┬ uglifyjs-webpack-plugin@1.1.4
│   └── uglify-es@3.2.2  deduped
└── uglify-es@3.2.2 
```
Yes, it's working now
большое спасибо

**Comment by Alekcei** [comment] 2017-12-26 21:40
But not working  `--no-build-optimizer`
```
ERROR Error: No NgModule metadata found for 'function (){}'.
    at t.TMtu.t.resolve (2.b2a6116….chunk.js:1)
    at t.TMtu.t.getNgModuleMetadata (2.b2a6116….chunk.js:1)
    at e.TMtu.t._loadModules (2.b2a6116….chunk.js:1)
    at e.TMtu.t._compileModuleAndAllComponents (2.b2a6116….chunk.js:1)
    at e.TMtu.t.compileModuleAndAllComponentsAsync (2.b2a6116….chunk.js:1)
    at t.TMtu.t.compileModuleAndAllComponentsAsync (2.b2a6116….chunk.js:1)
    at Function.TMtu.t.createDinamicPetitionOperationComponent (2.b2a6116….chunk.js:1)
    at t.TMtu.t.createOperationsPetitionContent (2.b2a6116….chunk.js:1)
    at e._next (2.b2a6116….chunk.js:1)
    at e.E9/g.e.__tryOrUnsub (vendor.07efdf9….bundle.js:1)
(anonymous) @ vendor.07efdf9….bundle.js:1
LMZF.t.handleError @ vendor.07efdf9….bundle.js:1
next @ vendor.07efdf9….bundle.js:1
e.object.i @ vendor.07efdf9….bundle.js:1
E9/g.e.__tryOrUnsub @ vendor.07efdf9….bundle.js:1
E9/g.e.next @ vendor.07efdf9….bundle.js:1
E9/g.e._next @ vendor.07efdf9….bundle.js:1
E9/g.e.next @ vendor.07efdf9….bundle.js:1
TO51.e.next @ vendor.07efdf9….bundle.js:1
LMZF.e.emit @ vendor.07efdf9….bundle.js:1
(anonymous) @ vendor.07efdf9….bundle.js:1
t.invoke @ polyfills.947cc91….bundle.js:1
r.run @ polyfills.947cc91….bundle.js:1
LMZF.t.runOutsideAngular @ vendor.07efdf9….bundle.js:1
onHandleError @ vendor.07efdf9….bundle.js:1
t.handleError @ polyfills.947cc91….bundle.js:1
r.runTask @ polyfills.947cc91….bundle.js:1
e.invokeTask @ polyfills.947cc91….bundle.js:1
v @ polyfills.947cc91….bundle.js:1
d @ polyfills.947cc91….bundle.js:1
```
again missing MetaData

**Comment by Ledzz** [comment] 2017-12-26 22:06
Got a weird behavior: focus event on input fired four times on page load (no autofocus, ofc), both ngSubmit and submit events stopped working (page loaded on submit) and many other html event issues. Fixed by removing `--prod`.

**Comment by dojchek** [comment] 2017-12-26 22:54
I have similar issue - events from a nested component which are emmitted from ngFor are not handled properly by parent component.
Example:
```
@Component({
  selector: 'cdg-list',
  template: `
                <ul>
                    <li *ngFor="let item of items">
                        <a (click)="addItem.next()">Add</a>
                        <a (click)="deleteItem.next()">Delete</a>
                        <a (click)="editItem.next()">Edit</a>
                    </li>
                </ul>
            `,
})
export class ListComponent {
  @Input() items: any[] = [];

  @Output() addItem = new EventEmitter();
  @Output() deleteItem = new EventEmitter();
  @Output() editItem = new EventEmitter();
}


@Component({
  selector:        'app',
  template:        `
                       <cdg-list [items]="['foobar', 'foo', 'test', 'bar']"
                                 (addItem)="onAdd()"
                                 (editItem)="onEdit()"
                                 (deleteItem)="onDelete()">
                       </cdg-list>
                   `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent {
  onAdd() { alert('ADD'); }
  onDelete() { alert('DELETE'); }
  onEdit() { alert('EDIT'); }
}

```
In app component, onEdit() handler will always be called, no matter which event gets triggered from 'dumb' component(ListComponent).
This only happens when building with --prod switch and if I set uglifier mangle=false  then the issue is gone.
Not sure if this is the same issue, but the source of this issue is definately the same.

One thing to note is that I'm having this issue with angular/cli 1.5+ (tested it with 1.5.0, up to 1.6.3) and angular 5+ (5.0.0, up to 5.2.0-beta)
[Example](http://recordit.co/Cwc3kJmNWH)

**Comment by julianobrasil** [comment] 2017-12-27 00:10
@Ledzz, @dojchek : are you seeing the bug _after_ aplying @filipesilva's suggested workaround: https://github.com/angular/angular-cli/issues/8997#issuecomment-353970841?

**Comment by dojchek** [comment] 2017-12-27 00:18
No, the bug is gone with that walk-around (can also be done just by setting mangle=false as suggested in above).

**Comment by MaxGorshkov** [comment] 2017-12-27 06:25
Why angular cli not fixed stable versions of dependency packages in package.json? I think, that this strategy saved all angular builds in the world in this case)

**Comment by trotyl** [comment] 2017-12-27 06:39
@MaxGorshkov `uglify-es` is the sub-dependency of `uglify-js-pllugin`, fixing `uglify-js-pllugin` version will not help with that.

**Comment by Ledzz** [comment] 2017-12-27 07:53
@julianobrasil didn't try this, I've used [this method](https://github.com/angular/angular-cli/issues/8997#issuecomment-353957698)

**Comment by joaopgrassi** [comment] 2017-12-27 08:51
Solution #8997 from @filipesilva worked for me.

**Comment by filipesilva** [comment] 2017-12-27 09:20
@MaxGorshkov Angular CLI does not have a direct dependency in `uglify-es`, like @trotyl said, and so we cannot pin it. Even if we did, `uglify-es@3.3.2` is not a prerelease version or anything, it is an official stable version.

Pinning (using a specific version of a dependency) does not work because you cannot pin subdependencies. In the NPM ecosystem the way you ensure reproducible installs is not via pinning dependencies but rather by using lockfiles, either `package-lock.json` or `yarn.lock`.

**Comment by d3viant0ne** [comment] 2017-12-27 10:37
@filipesilva => #9006

**Comment by filipesilva** [comment] 2017-12-27 10:42
Thanks @d3viant0ne, will try to get a release of Angular CLI up. @danbucholtz you might want to pin as well on Ionic's side.

**Comment by filipesilva** [comment] 2017-12-27 12:15
Keeping issue opened until the workaround is released.

**Comment by filipesilva** [comment] 2017-12-27 15:01
The bug causing these problems is reported with repros at https://github.com/mishoo/UglifyJS2/issues/2663.

**Comment by filipesilva** [comment] 2017-12-27 21:22
`@angular/cli@1.6.3` is now released, which should set the minimum version of `uglifyjs-webpack-plugin` to use a pinned `uglify-es@3.2.2`. Big thanks to @d3viant0ne for updating and releasing it 👍 

Meanwhile https://github.com/mishoo/UglifyJS2/issues/2663 has also been fixed and should be part of the next release of `uglify-es`.

**Closed by filipesilva** 2017-12-27 21:22 UTC
Labels: blocked, priority: 0 (critical), type: bug, type: faq

**Comment by icepoint0** [comment] 2017-12-28 02:30
nice work . i can update now.
