### ISSUE TITLE
Project cannot be build `Cannot read properties of undefined (reading 'file')`

### ISSUE THREAD

**Issue by ms270169** [angular/angular-cli#25496] opened 2023-07-06 09:54 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Building a new Angular 16.1.0 project via @angular/cli fails.
The project was not modified after creation!

### Minimal Reproduction

```sh
$ npm -g install @angular/cli
...
```
```sh
$ ng version
...
Angular CLI: 16.1.3
Node: 16.19.0
Package Manager: npm 8.19.3
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1601.3 (cli-only)
@angular-devkit/core         16.1.3 (cli-only)
@angular-devkit/schematics   16.1.3 (cli-only)
@schematics/angular          16.1.3 (cli-only)
```
```sh
$  ng new ngx
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE ngx/README.md (1057 bytes)
CREATE ngx/.editorconfig (274 bytes)
CREATE ngx/.gitignore (548 bytes)
CREATE ngx/angular.json (2685 bytes)
CREATE ngx/package.json (1034 bytes)
CREATE ngx/tsconfig.json (901 bytes)
CREATE ngx/tsconfig.app.json (263 bytes)
CREATE ngx/tsconfig.spec.json (273 bytes)
CREATE ngx/.vscode/extensions.json (130 bytes)
CREATE ngx/.vscode/launch.json (470 bytes)
CREATE ngx/.vscode/tasks.json (938 bytes)
CREATE ngx/src/main.ts (214 bytes)
CREATE ngx/src/favicon.ico (948 bytes)
CREATE ngx/src/index.html (289 bytes)
CREATE ngx/src/styles.css (80 bytes)
CREATE ngx/src/app/app-routing.module.ts (245 bytes)
CREATE ngx/src/app/app.module.ts (393 bytes)
CREATE ngx/src/app/app.component.css (0 bytes)
CREATE ngx/src/app/app.component.html (23115 bytes)
CREATE ngx/src/app/app.component.spec.ts (982 bytes)
CREATE ngx/src/app/app.component.ts (207 bytes)
CREATE ngx/src/assets/.gitkeep (0 bytes)
✔ Packages installed successfully.
...
```
```sh
$ cd ngx
$ npm run build

> ngx@0.0.0 build
> ng build

✔ Browser application bundle generation complete.

./node_modules/@angular/common/fesm2022/common.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
TypeError: /tmp/ngx/node_modules/@angular/common/fesm2022/common.mjs: Cannot read properties of undefined (reading 'file')

./node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
TypeError: /tmp/ngx/node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs: Cannot read properties of undefined (reading 'file')

./node_modules/@angular/router/fesm2022/router.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
TypeError: /tmp/ngx/node_modules/@angular/router/fesm2022/router.mjs: Cannot read properties of undefined (reading 'file')
```

### Exception or Error

```text
/node_modules/@angular/common/fesm2022/common.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
TypeError: /tmp/ngx/node_modules/@angular/common/fesm2022/common.mjs: Cannot read properties of undefined (reading 'file')

./node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
TypeError: /tmp/ngx/node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs: Cannot read properties of undefined (reading 'file')

./node_modules/@angular/router/fesm2022/router.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
TypeError: /tmp/ngx/node_modules/@angular/router/fesm2022/router.mjs: Cannot read properties of undefined (reading 'file')
```

### Your Environment

```text
Angular CLI: 16.1.3
Node: 16.19.0
Package Manager: npm 8.19.3
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1601.3 (cli-only)
@angular-devkit/core         16.1.3 (cli-only)
@angular-devkit/schematics   16.1.3 (cli-only)
@schematics/angular          16.1.3 (cli-only)
```

**Comment by alan-agius4** [comment] 2023-07-06 10:19
This seems to be indeed caused by a change (intentional or not) in Babel which is breaking the Angular linker.

**Comment by CondensedMilk7** [comment] 2023-07-06 10:25
I am experiencing the same issue.

Interestingly, I downgraded to angular 15 globally, and creating a new project results in the same build error.

versions in package.json:

```json
  "dependencies": {
    "@angular/animations": "^15.2.0",
    "@angular/common": "^15.2.0",
    "@angular/compiler": "^15.2.0",
    "@angular/core": "^15.2.0",
    "@angular/forms": "^15.2.0",
    "@angular/platform-browser": "^15.2.0",
    "@angular/platform-browser-dynamic": "^15.2.0",
    "@angular/router": "^15.2.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.2.9",
    "@angular/cli": "~15.2.9",
    "@angular/compiler-cli": "^15.2.0",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.9.4"
  }
```

**Comment by codingsamuel** [comment] 2023-07-06 10:28
A temporary fix would be:

"@babel/generator": "7.22.5",
"@babel/parser": "7.22.5",
"@babel/traverse": "7.22.5"

**Comment by mbenzenhoefer** [comment] 2023-07-06 10:34
I have the same issue with `v15.2.9`

**Comment by yoonasy** [comment] 2023-07-06 10:47
> A temporary fix would be:
> 
> "@babel/generator": "7.22.5", "@babel/parser": "7.22.5", "@babel/traverse": "7.22.5"

thank u, it's works on v16

**Comment by beohoang98** [comment] 2023-07-06 10:59
I have same issue on `~14.2.0`

**Comment by hambra** [comment] 2023-07-06 11:12
same here with v16 :(

**Comment by Rahul-kalsha** [comment] 2023-07-06 11:16
Getting same issue in Angular **15.2.9**

**Comment by meraj-markettime** [comment] 2023-07-06 11:20
> Getting same issue in Angular **15.2.9**

![image](https://github.com/angular/angular-cli/assets/82381740/a39581a7-5886-4df0-9010-1937b4732ad1)

**Comment by thaoula** [comment] 2023-07-06 11:27
It seems to also be affecting our Angular 16 builds using ESBUILD also.

**Comment by thaoula** [comment] 2023-07-06 11:40
As suggested here -
https://github.com/babel/babel/issues/15752

Can you try and add this to package.json
"overrides": {
"@babel/traverse": "7.22.6"
},

**Comment by thanoskoutr** [comment] 2023-07-06 11:40
Getting the same issue with latest Angular v14 (`14.2.12`).

**Comment by Alfxjx** [comment] 2023-07-06 11:54
WARN  deprecated @babel/traverse@7.22.7: [WARNING] Use 7.22.6 instead of 7.22.7, reason: https://github.com/babel/babel/issues/15752
 
 use pnpm i and found this waring, use the overrides and it fixed

```
"overrides": {
  "@babel/traverse": "7.22.6"
},
```

**Comment by Sapython** [comment] 2023-07-06 11:54
I am facing this issue too.

Checked this in v15 and v16

<img width="1679" alt="image" src="https://github.com/angular/angular-cli/assets/45693173/60b07b31-0546-47e5-a928-7aa59853baa4">

**Comment by VKAlwaysWin** [comment] 2023-07-06 11:59
Same for us (latest Angular 13)

**Comment by prnkrawat** [comment] 2023-07-06 12:01
I am also facing this issue while creating the new project.
<img width="960" alt="angularissue" src="https://github.com/angular/angular-cli/assets/103996562/3738e362-c3ef-42c9-8ea0-152a9619cba0">

**Comment by VedantBTS** [comment] 2023-07-06 12:12
I am also facing the same issue when I created new project but for older created projects the issue is not there.

**Comment by Isabelcasmot** [comment] 2023-07-06 12:21
I have the same issue and I tried the :
"overrides": {
"@babel/traverse": "7.22.6"
},

on package.json but is not working

**Comment by vampirepapi** [comment] 2023-07-06 12:24
> I have the same issue and I tried the : "overrides": { "@babel/traverse": "7.22.6" },
> 
> on package.json but is not working

try deleting node_modules and `npm install ` and then `ng serve`
it will work 👯‍♂️

**Comment by Isabelcasmot** [comment] 2023-07-06 12:27
> 

I tried tha also,  the issue is still there :(

**Comment by VedantBTS** [comment] 2023-07-06 12:28
I also tried by deleting node_modules and npm install and then ng serve, but it's not working for me too

**Comment by vampirepapi** [comment] 2023-07-06 12:29
strange, worked for me btw

**Comment by vampirepapi** [comment] 2023-07-06 12:30
![image](https://github.com/angular/angular-cli/assets/39551118/ae24d6dc-c0d7-4cfd-a081-f0da5463e047)
![image](https://github.com/angular/angular-cli/assets/39551118/3b81790d-3cf4-4c30-8e7d-dbf1b0a05bf7)

**Comment by jcbuilds** [comment] 2023-07-06 12:30
I'm also facing the same issue with `Angular 15.1.6`.

**Comment by alan-agius4** [comment] 2023-07-06 12:34
This issue has been caused `@babel/traverse@7.22.7`, the Babel team has reverted the change that caused this bug via https://github.com/babel/babel/pull/15754 and released a new version `@babel/traverse@7.22.8`. (Thanks @nicolo-ribaudo).

Please ensure to remove NPM "overrides" and Yarn "resolutions" from your `package.json` and sync the lock file. The easier way would be to delete `node_modules`, `yarn.lock` and `package-lock.json`.

```
$ rm -rf node_modules yarn.lock package-lock.json
```

If after the above you are are still encountering this problem and you are not using the public NPM repository, make sure that your NPM mirror is synced.

**Comment by lorenzo-ap** [comment] 2023-07-06 12:35
> A temporary fix would be:
> 
> "@babel/generator": "7.22.5", "@babel/parser": "7.22.5", "@babel/traverse": "7.22.5"

This worked for me

**Comment by VedantBTS** [comment] 2023-07-06 12:37
Hey guys for me the issue just got solved. I just included 
  "overrides": {
    "@babel/traverse": "7.22.6"
    } 
    in the package.json and then I deleted node_modules, did npm install and then did ng serve.

**Comment by nicolo-ribaudo** [comment] 2023-07-06 12:37
Babel 7.22.8 released -- the steps listed in the original issue description (https://github.com/angular/angular-cli/issues/25496#issue-1791213810) now succesfully create and build an Angular project.

Please make sure to update `@babel/core` and `@babel/traverse` to 7.22.8!

**Comment by Isabelcasmot** [comment] 2023-07-06 12:39
Sorry, after adding rm -rf node_modules yarn.lock package-lock.json to my  CMD  says that "rm" is not recognized as an internal or external command. Wut?

**Comment by ocombe** [comment] 2023-07-06 12:40
I can confirm that it works now with the new version of babel traverse (automatically installed, no need to change anything to the original config)

**Comment by alan-agius4** [comment] 2023-07-06 12:41
@Isabelcasmot, for Windows you can use `npx rimraf -rf node_modules yarn.lock package-lock.json`

**Comment by alan-agius4** [comment] 2023-07-06 12:42
Closing as this issue has been resolved upstream. See: https://github.com/angular/angular-cli/issues/25496#issuecomment-1623604147.

**Closed by alan-agius4** 2023-07-06 12:42 UTC
Labels: type: bug/fix, freq4: critical, severity5: regression, area: devkit/build-angular, devkit/build-angular: browser

**Comment by janpauldahlke** [comment] 2023-07-06 15:33
fast reaction. gj
