### ISSUE TITLE
ng-cli .22 hangs, using angular v2.2.4

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#3508] opened 2016-12-10 15:45 UTC
ng-cli .22 hangs, using angular v2.2.3
> ---------------------------------------------------------------

```
root@DESKTOP-VEUHFOL /cygdrive/c/msweb/studioDashboard
$ ng serve --port 4203
** NG Live Development Server is running on http://localhost:4203. **
 24% building modules 123/123 modules 0 active
```

### OS?
Windows 10

### Versions.
```
$ ng --version
angular-cli: 1.0.0-beta.22
node: 6.5.0
os: win32 x64
```

any updates on this?

regards

Sean.

**Comment by Ploppy3** [comment] 2016-12-10 16:18
I'm pretty sure angular-cli 22-1 is supposed to run on angular 2.2.3, not 2.2.4.

**Comment by born2net** [comment] 2016-12-10 16:22
sorry updated 2.2.3, same issue...

**Comment by mattdistefano** [comment] 2016-12-10 17:30
Is this a brand new project or an existing one that was upgraded?

**Comment by born2net** [comment] 2016-12-10 17:32
its a ng2 project (not ng1 upg to ng2)...
you can see the repo here: https://github.com/born2net/studioDashboard/tree/ngcli (ngcli branch)

**Comment by bufke** [comment] 2016-12-10 19:56
I'm also seeing it hang when upgrading from 21 to 22.
```
** NG Live Development Server is running on http://localhost:4200. **
 10% building modules 1/1 modules 0 activecan't resolve module ./ngsdk/api from /tmp/passit-frontend/src/app/app.module.ts
(node:2068) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: can't find symbol undefined exported from module /tmp/passit-frontend/src/app/ngsdk/api.ts, resolving symbol AppModule in /tmp/passit-frontend/src/app/app.module.ts, resolving symbol AppModule in /tmp/passit-frontend/src/app/app.module.ts
 19% building modules 79/79 modules 0 active
```

It will hang at 19% forever and not crash nor use any cpu. The resolve module is pretty trivial and works on 21. Assuming there is some underlying issue here.

**Comment by born2net** [comment] 2016-12-10 20:00
ya its a show stopper... happens on all of projects

**Comment by mattdistefano** [comment] 2016-12-10 22:23
You sure you're running angular 2.2.x and not 2.3? IIRC I had this issue when trying to use 2.3.

**Comment by born2net** [comment] 2016-12-10 22:47
yes positive.
see attached
![err](https://cloud.githubusercontent.com/assets/5090936/21076719/a384df78-bee7-11e6-8c22-cf77167c09b6.PNG)


regards

Sean

**Comment by born2net** [comment] 2016-12-10 22:50
if you have time please test as I really would like to use the new --hmr flag in .22
```
git clone https://github.com/born2net/studioDashboard.git
cd studioDashboard
npm i
ng serve
```

**Comment by chenopinya** [comment] 2016-12-11 12:14
Happens to me as well. Stuck on 20%

**Comment by rolandoldengarm** [comment] 2016-12-12 06:31
Here as well, stuck at 22%

````
 22% building modules 102/102 modules 0 active
````

**Comment by cacogr** [comment] 2016-12-12 10:23
Same here. Updated from a working .21 project to .22

```
(node:5308) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in ...
```

**Comment by mhmo91** [comment] 2016-12-12 13:47
Fuck my life, just got the same error
ng-serve gets stuck!
$ ng ser 20% building modules 91/91 modules 0 active                            
Win 10
"version": "1.0.0-beta.22-1"
Any body got a solution?

**Comment by filipesilva** [comment] 2016-12-12 14:44
Dupe of https://github.com/angular/angular-cli/issues/3368

**Closed by filipesilva** 2016-12-12 14:44 UTC
