### ISSUE TITLE
HookWebpackError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nolafs** [angular/angular-cli#21636] opened 2021-08-24 15:10 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

The production build worked perfectly fine under Angular 11. 

### Description

Optimisation does not work under Angular 12 after upgrading the project. 

## 🔬 Minimal Reproduction

Production build with optimisation turned on.

## 🔥 Exception or Error

<pre><code>
```
[error] HookWebpackError: Maximum call stack size exceeded
    at makeWebpackError (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/olafsiebert/html/allstarschallenge/node_modules/webpack/lib/Compilation.js:2515:12
    at eval (eval at create (/Users/olafsiebert/html/allstarschallenge/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:114:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- inner error --
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at streamChunksOfRawSource (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunksOfRawSource.js:14:25)
    at module.exports (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunksOfRawSource.js:40:5)
    at RawSource.streamChunks (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:56:10)
    at module.exports (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at ReplaceSource.streamChunks (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/ReplaceSource.js:176:44)
    at module.exports (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at streamAndGetSourceAndMap (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamAndGetSourceAndMap.js:27:53)
    at CachedSource.streamChunks (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:208:35)
    at module.exports (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at ConcatSource.streamChunks (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:112:55)
    at module.exports (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at streamAndGetSourceAndMap (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamAndGetSourceAndMap.js:27:53)
    at CachedSource.streamChunks (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:208:35)
    at module.exports (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at ConcatSource.streamChunks (/Users/olafsiebert/html/allstarschallenge/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:112:55)

```
</code></pre>

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.2
Node: 14.15.5
Package Manager: npm 7.16.0
OS: darwin x64

Angular: 12.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.2
@angular-devkit/build-angular   12.2.2
@angular-devkit/core            12.2.2
@angular-devkit/schematics      12.2.2
@angular/fire                   6.1.5
@nguniversal/builders           12.1.0
@nguniversal/express-engine     12.1.0
@schematics/angular             12.2.2
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

**Comment by alan-agius4** [comment] 2021-08-24 15:34
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by nolafs** [comment] 2021-08-24 16:00
Thanks for getting back to me. 

It has do with my custom library, I switched the sub repository branch to an older version and it compiled just fine. I am currently in deadline stress. I will have look and compare the branches to figure what is causing the issue when I have bit more time. I let you what I find.

**Comment by Bjeaurn** [comment] 2021-08-25 09:58
Is your custom library open source? I'd be happy to try and see if I can get it to work...

**Comment by NetMajom** [comment] 2021-08-30 06:34
> Thanks for getting back to me.
> 
> It has do with my custom library, I switched the sub repository branch to an older version and it compiled just fine. I am currently in deadline stress. I will have look and compare the branches to figure what is causing the issue when I have bit more time. I let you what I find.

```
ng serve

⠋ Generating browser application bundles (phase: sealing).../Users/name/Projects/xy/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunksOfSourceMap.js:21
        const lines = source.match(SPLIT_LINES_REGEX);
                             ^

RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at streamChunksOfSourceMapFull (/Users/netmajom/Projects/xy/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunksOfSourceMap.js:21:23)
    at module.exports (/Users/name/Projects/xy/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunksOfSourceMap.js:389:6)
    at SourceMapSource.streamChunks (/Users/name/Projects/xy/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:211:11)
    at module.exports (/Users/name/Projects/xy/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at ReplaceSource.streamChunks (/Users/name/Projects/xy/node_modules/webpack/node_modules/webpack-sources/lib/ReplaceSource.js:176:44)
    at module.exports (/Users/name/Projects/xy/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at ConcatSource.streamChunks (/Users/name/Projects/xy/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:112:55)
    at module.exports (/Users/name/Projects/name/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at streamAndGetSourceAndMap (/Users/name/Projects/xy/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamAndGetSourceAndMap.js:27:53)

```

I have the same problem. I figure out if I set the `"sourceMap": false` is always fine, but in development it's very hard to debug without it. I think the problem related to scss somehow, because if I playing with the scss version number its working, then it's not. So randomly. If I starting the project again, and again, its working, so this error so random.

@nolafs what is your version what its good for you, and not get that error?

**Comment by VaporMontey** [comment] 2021-09-13 08:51
If it can be useful using Angular 12.1.x the error is not present, with the newer version (12.1.x) I get the error building in production configuration

**Comment by alan-agius4** [comment] 2021-09-13 10:13
Duplicate of https://github.com/angular/angular-cli/issues/21599

Please follow and provide a reproduction in https://github.com/webpack/webpack-sources/issues/131

**Closed by alan-agius4** 2021-09-13 10:13 UTC
Labels: need: repro steps

**Comment by Bjeaurn** [comment] 2021-09-13 15:52
There has been a breakthrough in webpack/webpack-sources#131, `webpack-sources@3.2.1` has a fix for the edge cases most of us were probably running into. 

If you find more edges with this problem, make sure you file an issue there.

@alan-agius4 Do we need to update anything in the Angular ecosystem to make sure we lock to at least that package?

**Comment by alan-agius4** [comment] 2021-09-13 17:33
@Bjeaurn, no, there isn’t anything to do from our end. 

You just need to re-generate the lock file.
