### ISSUE TITLE
CLI v6.0.0 failing to generate components - unable to locate module

### ISSUE THREAD

**Issue by SamScholefield** [angular/angular-cli#10725] opened 2018-05-08 12:13 UTC
### Versions
```
Angular CLI: 6.0.0
Node: 8.9.1
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```
### Repro steps
```
ng new my-project
cd my-project
ng g c my-component --m app
```

### Observed behavior
Terminal output:
```
Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
```

### Desired behavior
Component folder/files generated in `./src/app`  
Component imported in `app.module.ts'

**Comment by clydin** [comment] 2018-05-08 14:11
Duplicate of #10653

**Closed by clydin** 2018-05-08 14:11 UTC
