### ISSUE TITLE
Error in ng generate component

### ISSUE THREAD

**Issue by louridas** [angular/angular-cli#8398] opened 2017-11-08 12:08 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
Angular CLI: 1.5.0
Node: 6.11.5
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.

```
ng generate component foo
```

### The log given by the failure.

ERROR in src/app/foo/foo.component.ts(7,18): error TS2304: Cannot find name 'ViewEncapsulation'.

### Desired functionality.

The generated component refers to `ViewEncapsulation` without importing it.  Either it should be imported, or it should not appear at all. Right now it is:
```javascript
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-foo',
  templateUrl: './foo.component.html',
  styleUrls: ['./foo.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class FooComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
```

So the line:
```javascript
encapsulation: ViewEncapsulation.None
```
should probably go, or the import at the start should be:
```javascript
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
```
BTW, why should it be `ViewEncapsulation.None`?

**Comment by FreakDroid** [comment] 2017-11-08 12:54
Related [8374](https://github.com/angular/angular-cli/issues/8374)

**Comment by deebloo** [comment] 2017-11-08 12:57
I think the bug is that viewEncapsulation is set at all.

**Comment by FreakDroid** [comment] 2017-11-08 12:58
#8374

**Comment by yaroslavert** [comment] 2017-11-08 14:10
+

**Comment by JohannesHoppe** [comment] 2017-11-08 14:43
This is a bug, the generated code does not even have a correct import.
Also `encapsulation: ViewEncapsulation.None` should be by no way the default.

**Comment by JohannesHoppe** [comment] 2017-11-08 15:28
fixed via https://github.com/angular/devkit/commit/a8a6559649c8815b2b24561bd6ef00e4e4ad4ab8

**Comment by gkalpak** [comment] 2017-11-10 09:36
angular/devkit@a8a6559 takes care of importing `ViewEncapsulation` when necessary.
The issue of using `ViewEncapsulation.None` by default still remains.

Some background:
I believe using `None` as the default value for `ViewEncapsulation` was an issue [since the beginning][1], but was cancelled out in most cases by [another bug][2] (which was fixed in angular/devkit@6d7a7ea57, revealing the original issue).

AFAICT, the default value needs to be changed from `None` to `Emulated` in the following files:
- [schematics/angular/application/schema.json][3]
- [schematics/angular/component/schema.json][4]

[1]: https://github.com/angular/devkit/commit/f4c7d57ec7464044a00096f2dd9967a78e813f53#diff-7d6fec95974e7c9bd9f9d4f959e7e3f8R32
[2]: https://github.com/angular/devkit/commit/6d7a7ea5709c31d839d98ecad4bb174c34a476e9#diff-eeb3cee732192f31a85d561abb3f98c6L12
[3]: https://github.com/angular/devkit/blob/079f472781f9ce9c48ee5a88d781a35597bc1d6c/packages/schematics/angular/application/schema.json#L40
[4]: https://github.com/angular/devkit/blob/079f472781f9ce9c48ee5a88d781a35597bc1d6c/packages/schematics/angular/component/schema.json#L38

**Comment by JohannesHoppe** [comment] 2017-11-10 11:17
@gkalpak  I completely agree to this!
This was done by purpose:  https://github.com/angular/devkit/blob/6d7a7ea5709c31d839d98ecad4bb174c34a476e9/packages/schematics/angular/component/index_spec.ts#L65
But I'm confused why we want to have this breaking change?

Nobody would expect `None` as the default. Since it's not the default Angular-behavior. This should be fixed very soon, or a lot of people will have a hard time to realize this fundamental change.

@Brocco can you explain this to us? I'm confused!

**Comment by Brocco** [comment] 2017-11-14 03:15
This issue has been reported several times and is currently being tracked via #8398 closing this issue.
Duplicate of #8398

**Comment by Brocco** [comment] 2017-11-14 03:26
Woops, my bad, LOL... reopening. 😀

**Closed** 2017-11-14 14:04 UTC

**Comment by dhananjayve** [comment] 2019-04-01 15:17
Error while generating component. Please help me
The "c" alias is already in use by the "--collection" option and cannot be used by the "--change-detection" option. Please use a different alias.

ng -v
Your global Angular CLI version (7.1.4) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.4
Node: 10.15.3
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.7.4
@angular-devkit/architect: 0.13.7
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 7.3.7
@angular-devkit/schematics: 7.3.7
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 7.3.7
@schematics/package-update: 0.3.2
@schematics/update: 0.13.7
typescript: 2.5.3
webpack: 3.11.0
