### ISSUE TITLE
Can I dynamically change the deploy url when app start ?

### ISSUE THREAD

**Issue by wuzhouyang** [angular/angular-cli#8021] opened 2017-10-12 08:50 UTC
I know that I can use the angular-cli to config the deploy-url like `--deploy-url http://xxxxxxx/`, but when I want to change the deploy-url I must to build again. I want to write somethings global like 
<pre><code>
<script type="text/javascript">  
    window['setting'] = {
      'siteurl':'https://xxxxxxxx/'
    }
</script>
</code></pre>
in the root html. And Can I set the deploy-url use the already exist variable when the app start so that I can change the url without build again?

**Comment by ctrl-brk** [comment] 2017-10-12 12:19
I''m not sure that cli is aware about your html files. What you can do is to create a script which will update cli config with the correct value before the build.

**Comment by clydin** [comment] 2017-10-12 13:14
Using deploy url at all should be unnecessary if all the deployed files are reachable at the ascribed `http://xxxxxxx/` address.

**Comment by filipesilva** [comment] 2017-10-16 10:46
I think this issue is a duplicate of https://github.com/angular/angular-cli/issues/3855. There are suggestions there on how you can setup runtime configuration.

**Closed by filipesilva** 2017-10-16 10:46 UTC

**Comment by Kamilius** [comment] 2018-02-06 06:29
@filipesilva I've read https://github.com/angular/angular-cli/issues/3855 all the way down, but I don't see where to assign `deployUrl`, so my application will know where to fetch public resources from upon initializing. This URL may change from page load to page load.

**Comment by RajnishKatharotiya** [comment] 2018-03-20 11:22
@wuzhouyang for make global deployUrl, You can add following code into your app section of Angular CLI file.

```
"apps": [
    { 
      "deployUrl": "/path/",
}]
```

may this will help you.

**Comment by Kamilius** [comment] 2018-03-22 20:38
I don’t know if anyone’s reading this topic before advising anything, but the main question is about “changing deployUrl” when app is already running (in runtime). Not on the stage of building app with angular-cli, as @RajnishKatharotiya @ctrl-brk are proposing.

**Comment by ram-reddy** [comment] 2018-06-21 15:51
I want to build once, deploy at multiple environments (assume the static files I'm serving from cdn/different domain  and not from the same origin of index page)

**Comment by david-salvador-wefox** [comment] 2018-07-25 08:41
I read you Kamilius!, I am also looking for a solution to this, since **when deploying an Angular app to Salesforce as an apex page**, the static assets locations are set dynamically at the time of **deployment**. And for Lazy Loading currently the `--deploy-url` used to **lazy load js chunks** **_needs to be known_** **at build time**.

**Comment by david-salvador-wefox** [comment] 2018-07-25 08:42
I read you Kamilius!, I am also looking for a solution to this, since **when deploying an Angular app to Salesforce as an apex page**, the static assets locations are set dynamically at the time of **deployment**. And for Lazy Loading,... currently,... the `--deploy-url` used to customize where to **lazy load js chunks** from.... **_needs to be known_** **at build time**.

**Comment by stealth-17** [comment] 2018-08-17 15:04
@filipesilva  I believe this issue needs to be reopened as @ram-reddy  said, when I need to implement build once and deploy in dev, test and prod the same build it is not possible now. This is a major issue when we develop an enterprise level application.

**Comment by vipultaylor** [comment] 2019-01-12 13:41
> I read you Kamilius!, I am also looking for a solution to this, since **when deploying an Angular app to Salesforce as an apex page**, the static assets locations are set dynamically at the time of **deployment**. And for Lazy Loading,... currently,... the `--deploy-url` used to customize where to **lazy load js chunks** from.... **_needs to be known_** **at build time**.

@david-salvador-wefox I managed to sort of 'hack' my way to a solution. Its not pretty but gets the job done.

On my Apex page i introduced a resourceUrl attribute to my app-root

> \<app-root resourceUrl="{!URLFOR($Resource.Angular)}">Loading...\</app-root>

then in my app.component file

> declare let \_\_webpack_public_path\_\_;
> \_\_webpack_public_path\_\_ = this.eleRef.nativeElement.getAttribute('resourceUrl'); + '/';

adding the trailing '/' to ensure appropriate relative path

This is not the best solution and I am still looking for a more elegant solution

**Comment by Sathishchary** [comment] 2019-07-10 06:23
I am also looking for better solution.

**Comment by Sathishchary** [comment] 2019-07-10 06:58
I have used this url,,

https://www.jvandemo.com/how-to-use-environment-variables-to-configure-your-angular-application-without-a-rebuild/#

**Comment by tommy86r** [comment] 2019-07-22 15:26
> > I read you Kamilius!, I am also looking for a solution to this, since **when deploying an Angular app to Salesforce as an apex page**, the static assets locations are set dynamically at the time of **deployment**. And for Lazy Loading,... currently,... the `--deploy-url` used to customize where to **lazy load js chunks** from.... **_needs to be known_** **at build time**.
> 
> @david-salvador-wefox I managed to sort of 'hack' my way to a solution. Its not pretty but gets the job done.
> 
> On my Apex page i introduced a resourceUrl attribute to my app-root
> 
> > <app-root resourceUrl="{!URLFOR($Resource.Angular)}">Loading...</app-root>
> 
> then in my app.component file
> 
> > declare let __webpack_public_path__;
> > __webpack_public_path__ = this.eleRef.nativeElement.getAttribute('resourceUrl'); + '/';
> 
> adding the trailing '/' to ensure appropriate relative path
> 
> This is not the best solution and I am still looking for a more elegant solution

I did the same and it works fine in development mode but doesn't work in production

**Comment by MatissJanis** [comment] 2019-08-14 07:16
Can this be re-opened? The linked issue is something different.
