### ISSUE TITLE
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.

### ISSUE THREAD

**Issue by cwaj400** [angular/angular-cli#24627] opened 2023-01-29 20:05 UTC
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

11.x

### Description

Installing a new package, say puppeteer (https://www.npmjs.com/package/puppeteer) and then attempting to run app using ng serve causes webpack issues.
Adding some packages which were causing an issue seems to resolve this, such as: 

`"compilerOptions": {
    "paths": {
      "path": [
        "./node_modules/path-browserify",
        "./node_modules/stream-browserify",
        "./node_modules/https-browserify",
        "./node_modules/puppeteer-core",
        "./node_modules/url"
      ]
    },`

is fine, but I keep getting errors, such as `If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }
`

Is this a problem with webpack in the angular-devkit/build-angular library?

### Minimal Reproduction

New project, (ng new project). 
Install puppeteer, npm install puppeteer.
Run ng serve.

### Exception or Error

```text
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }

./node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:71:34-58 - Error: Module not found: Error: Can't resolve 'child_process' in '/Users/wangelljames/Documents/Software/borked-invoices/node_modules/puppeteer-core/lib/cjs/puppeteer/node'
```

### Your Environment

```text
Angular CLI: 15.0.5
Node: 14.21.1
Package Manager: npm 6.14.17
OS: darwin x64

Angular: 15.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.3
@angular-devkit/build-angular   15.1.3
@angular-devkit/core            15.1.3
@angular-devkit/schematics      15.0.5
@angular/cli                    15.0.5
@schematics/angular             15.0.5
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by clydin** [comment] 2023-01-30 17:52
Unfortunately, we are unable to replicate the issue as described.
Is it possible that `puppeteer` was accidentally imported within the Angular application? `puppeteer` is intended for use with Node.js but not directly in Web application code.  Attempting to do so will most likely cause errors as shown above.
If this is not the case, please provide a minimal reproduction so that the issue can be investigated further.

**Comment by alan-agius4** [comment] 2023-02-06 08:02
Closing due to the lack of communication. Please feel free to open a new issue if the problem persists.

**Closed by alan-agius4** 2023-02-06 08:02 UTC
Labels: needs: more info
