### ISSUE TITLE
Wrong case styles by generating nested paths

### ISSUE THREAD

**Issue by WuglyakBolgoink** [angular/angular-cli#18059] opened 2020-06-29 12:05 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

idk...

### Description

Problem with Case Styles

## 🔬 Minimal Reproduction

```bash
$ ng generate module publicPages --module app.module  --routing
#                         ^^^ camel-case

CREATE src/app/public-pages/public-pages-routing.module.ts (255 bytes)
CREATE src/app/public-pages/public-pages.module.ts (301 bytes)
#                   ^^^ kebab-case - this is ok!



$ ng generate module publicPages/login --module app.module --routing -d
#                         ^^^ use same camel-case form for generation components inside of module

UPDATE src/app/app.module.ts (1709 bytes)
CREATE src/app/publicPages/login/login-routing.module.ts (249 bytes)
CREATE src/app/publicPages/login/login.module.ts (276 bytes)
#                   ^^^ camel-case - this is not ok! because `ng g m` generate folder with kebab-case
```

It will be great if ngCLI can analyze this first and convert all UpperCase words into KebabCase.

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.0.0
Node: 10.21.0
OS: darwin x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cli                      10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Comment by alan-agius4** [comment] 2020-06-29 12:34
Duplicate of https://github.com/angular/angular-cli/issues/13553

**Closed by alan-agius4** 2020-06-29 12:34 UTC

**Comment by WuglyakBolgoink** [comment] 2020-06-29 20:03
@alan-agius4 

yes, but #13553 was not fixed and closed with inactivity status..

**Comment by alan-agius4** [comment] 2020-06-29 20:12
@WuglyakBolgoink, #13553 was closed as working as expected. See this comment https://github.com/angular/angular-cli/issues/13553#issuecomment-461547060

**Comment by WuglyakBolgoink** [comment] 2020-06-29 20:29
> @WuglyakBolgoink, #13553 was closed as working as expected. See this comment [#13553 (comment)](https://github.com/angular/angular-cli/issues/13553#issuecomment-461547060)

@alan-agius4 ah... sorry.

then ok :-)
