### ISSUE TITLE
ESBuild throws errors when copying assets during build [Next8]

### ISSUE THREAD

**Issue by spock123** [angular/angular-cli#26042] opened 2023-10-14 23:51 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When making a production build of our code, using browser-esbuild, the process throws an error when it comes to copying assets into the dist folder.

The same build works in the old builder.

The involved files and folders do exist, as it also works in the old (current) builder.
Destination is a directory, as it's the folder for our build.

### Please provide the exception or error you saw

```true
[Error: EISDIR: illegal operation on a directory, copyfile '/Users/spock/projects/fresto/apps/totti/src/robots.txt' -> '/Users/spock/projects/fresto/apps/totti/dist/totti'] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'copyfile',
  path: '/Users/spock/projects/fresto/apps/totti/src/robots.txt',
  dest: '/Users/spock/projects/fresto/apps/totti/dist/totti'
}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0-next.8
Node: 18.18.1
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 17.0.0-next.8
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1700.0-next.8
@angular-devkit/build-angular        17.0.0-next.8
@angular-devkit/core                 17.0.0-next.8
@angular-devkit/schematics           17.0.0-next.8
@angular/cdk                         17.0.0-next.6
@angular/fire                        7.5.0
@angular/material                    17.0.0-next.6
@angular/material-date-fns-adapter   17.0.0-next.6
@schematics/angular                  17.0.0-next.8
rxjs                                 7.5.7
typescript                           5.2.2
zone.js                              0.14.0
```

**Comment by alan-agius4** [comment] 2023-10-15 13:35
Duplicate of https://github.com/angular/angular-cli/issues/26021

**Closed by alan-agius4** 2023-10-15 13:35 UTC
