### ISSUE TITLE
Installation with warning

### ISSUE THREAD

**Issue by zankevich** [angular/angular-cli#4485] opened 2017-02-07 12:24 UTC
`npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.`

Steps to reproduce:
---
```
npm uninstall -g angular-cli @angular/cli
npm cache clean
npm install -g @angular/cli@latest
```
ENV
---
MacOS 10.12.3
Node 6.9.5

**Comment by grizzm0** [comment] 2017-02-07 12:27
Dupe of #4484

**Closed** 2017-02-07 12:28 UTC
