### ISSUE TITLE
app.module.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property

### ISSUE THREAD

**Issue by sundaralingampn** [angular/angular-cli#8368] opened 2017-11-06 11:49 UTC
app.module.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property

**Comment by RicardoVaranda** [comment] 2017-11-06 12:53
Hi @sundaralingampn ,

Could you please use the provided template when reporting an issue as it makes it easier for us to help you debug the problem, without a guided repro of this issue it's quite difficult to aid you.

**Comment by Jesu26** [comment] 2017-11-15 12:30
Hi ,
I am also facing the same problem.

while compiling the solution via ng serve -o after angular 5 update this issue occurs.

i have used npm link to link all my modules. 

ERROR in ./platform/userModule/app/app.module.ts
Module build failed: Error: E:\temp\trunk\platform\userModule\app\app.module.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (E:\temp\trunk\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:624:23)
    at plugin.done.then (E:\temp\trunk\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by korayguclu** [comment] 2017-11-16 09:05
I am also having the same problem very annoying. 


```
ERROR in .../web/src/app/index.ts
Module build failed: Error: ...\web\src\app\index.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (...\web\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:624:23)
    at plugin.done.then (...\web\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ ./src/app/app.module.ts 16:0-60
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by userlucy** [comment] 2017-11-20 22:19
I am facing aussi the same problem. I run with @augular/cli 1.5.3. The project already compiled successfully once. When I did some modification, the same error shown up. I used the compiled backup source file to run ng serve again. The error persist. This is really an annoying issue.

I tried aussi the 1.6beta version, still getting the same message. Hoping some one can help...

**Comment by filipesilva** [comment] 2017-11-24 10:15
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #8284. Please subscribe to that issue for future updates.

For those that have Ts files in your node_modules, please read through https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325. It explains why TS files in node_modules are not compiled.

**Closed by filipesilva** 2017-11-24 10:15 UTC

**Comment by ddeniska81** [comment] 2017-12-25 21:09
I had the issue like this after upgrade to  CLI . 
The issue was fixed with file rename and all links for it in the same lower case. Before the upgrade it was not an issue.
