### ISSUE TITLE
use 'ng serve --aot' failed

### ISSUE THREAD

**Issue by long-hai-yang** [angular/angular-cli#8042] opened 2017-10-13 10:12 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

    "@angular/cli": "1.4.6",
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/platform-server": "^4.2.4",
    "@angular/router": "^4.2.4",
    "typescript": "~2.3.3",
    "node":"6.9.1",
     "npm":"5.3.0"

### Repro steps.

if use "ng server" success;
use 'ng serve --aot'  failed.

### The log given by the failure.

 ng serve --aot

 92% chunk asset optimization
<--- Last few GCs --->

  259239 ms: Mark-sweep 1312.8 (1416.9) -> 1312.8 (1430.9) MB, 927.9 / 0.0 ms [allocation failure] [GC in old space requested].
  260168 ms: Mark-sweep 1312.8 (1430.9) -> 1312.8 (1430.9) MB, 928.5 / 0.0 ms [allocation failure] [GC in old space requested].
  261123 ms: Mark-sweep 1312.8 (1430.9) -> 1317.3 (1416.9) MB, 955.5 / 0.0 ms [last resort gc].
  262073 ms: Mark-sweep 1317.3 (1416.9) -> 1321.8 (1416.9) MB, 949.7 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

    2: arguments adaptor frame: 3->1
Security context: 000000510D3CFB61 <JS Object>
    3: InnerArrayForEach(aka InnerArrayForEach) [native array.js:~935] [pc=00000216E0B6BF11] (this=000000510D304381 <undefined>,bq=00000174017B6429 <JS Function (SharedFunctionInfo 000001F3446DDCB9)>,br=000000510D30C851 <JS Function SourceNode (SharedFunctionInfo 00000354348D3089)>,w=00000174017650C9 <JS Array[8127]>,x=8127)
    4: forEach [native array.js...

### Desired functionality.

Which may lead to this aspect of the problem

**Comment by filipesilva** [comment] 2017-10-16 12:41
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/5618. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-10-16 12:41 UTC
