### ISSUE TITLE
ng update --all not working

### ISSUE THREAD

**Issue by mungpara** [angular/angular-cli#11635] opened 2018-07-24 02:33 UTC
I run ng update --all command but it show below error.

Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.9.2").

Incompatible peer dependencies found. See above.

**Comment by ivelfan** [comment] 2018-07-24 07:41
Same error when I download the angular-cli repo and I launch `npm run test`.

**Comment by filipesilva** [comment] 2018-07-24 09:36
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #11387. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2018-07-24 09:36 UTC
