### ISSUE TITLE
Corrupted `ng update` installs the beta version of @angular packages

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular-cli#15284] opened 2019-08-09 08:32 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Unknown

### Description

`ng update @angular/cli` installs the beta version of @angular packages & shows incompatibility warnings. 

## 🔬 Minimal Reproduction

-

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/7990765/62765537-9cc93600-ba90-11e9-98e9-65757a0d89b5.png)

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.2.0
Node: 12.3.1
OS: win32 x64
Angular: 8.2.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@angular/cdk                      8.1.2
@angular/cli                      8.2.0
@angular/material                 8.1.2
@angular/pwa                      0.12.4
@ngtools/webpack                  8.2.0
@schematics/angular               7.2.4
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**

This project was previously updated to the beta branch of Angular to test ivy and it seems that since then, I always got problems updating my project.

**Comment by clydin** [comment] 2019-08-09 09:25
Duplicate of #14980

**Closed by clydin** 2019-08-09 09:25 UTC
