### ISSUE TITLE
Angular10 fileReplacements not work

### ISSUE THREAD

**Issue by sun293529884** [angular/angular-cli#19251] opened 2020-10-29 06:01 UTC
"@angular-devkit/build-angular": "~0.1000.4",
"@angular/cli": "^10.2.0",
"@angular/compiler-cli": "~10.0.5",

config:
"production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                },
                {
                  "replace": "src/assets/environments/env.js",
                  "with": "src/assets/environments/env.dev.js"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "5mb",
                  "maximumError": "10mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "50kb",
                  "maximumError": "60kb"
                }
              ]
            },

The js file cant be replaced

**Comment by alan-agius4** [comment] 2020-10-29 07:22
Duplicate of #16779

**Closed by alan-agius4** 2020-10-29 07:22 UTC
