### ISSUE TITLE
New angular-cli generated project has webpack error

### ISSUE THREAD

**Issue by rbirkgit** [angular/angular-cli#7078] opened 2017-07-21 06:50 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.2.2

### Repro steps.
Generate new project

### The log given by the failure. 
After projects gets generated I do this: "npm ls --depth=0"

That shows:

npm ERR! peer dep missing: webpack@^2.2.0, required by extract-text-webpack-plugin@2.1.2

### Desired functionality.
No errors

**Comment by viliks** [comment] 2017-07-21 11:53
@angular/cli dependency should be updated to extract-text-webpack-plugin@3.0.0

**Comment by RicardoVaranda** [comment] 2017-07-21 12:22
Revert back to 1.2.1 for the time being, the issue is due to version 1.2.2 using webpack 3.3.0
https://github.com/angular/angular-cli/blob/1.2.x/packages/%40angular/cli/package.json#L85

Rather than 2.4.0
https://github.com/angular/angular-cli/blob/v1.2.1/package.json#L99

**Comment by filipesilva** [comment] 2017-07-21 15:26
Just wanted to chine in as a maintainer and highlight @RicardoVaranda's comment. This was a mistake on our part.

**Comment by filipesilva** [comment] 2018-01-17 09:13
Closing as outdated.

**Closed by filipesilva** 2018-01-17 09:13 UTC
Labels: priority: 0 (critical), type: bug

**Comment by amitesh786** [comment] 2018-10-26 22:57
Visit the angular webpack website, I have mentioned direct link ```https://v5.angular.io/guide/webpack```

* Update the package.json
* After that remove node_modules ```rm -rf node_modules/``` 
* Install ```npm install```
* run the command as you mentioned above - ```npm ls --depth=0```

```
├── @angular/cli@6.2.5
├── @angular/common@4.2.6
├── @angular/compiler@4.2.6
├── @angular/core@4.2.6
├── @angular/forms@4.2.6
├── @angular/http@4.2.6
├── @angular/platform-browser@4.2.6
├── @angular/platform-browser-dynamic@4.2.6
├── @angular/router@4.2.6
├── @types/core-js@2.5.0
├── @types/jasmine@2.5.41
├── @types/node@6.14.0
├── angular2-template-loader@0.6.2
├── awesome-typescript-loader@3.5.0
├── core-js@2.5.7
├── corifeus-builder@2018.10.25-0
├── css-loader@0.26.4
├── extract-text-webpack-plugin@2.0.0-beta.5
├── file-loader@0.9.0
├── html-loader@0.4.5
├── html-webpack-plugin@2.30.1
├── jasmine-core@2.99.1
├── karma@1.7.1
├── karma-chrome-launcher@2.2.0
├── karma-jasmine@1.1.2
├── karma-sourcemap-loader@0.3.7
├── karma-webpack@2.0.13
├── null-loader@0.1.1
├── raw-loader@0.5.1
├── rimraf@2.6.2
├── rxjs@5.0.1
├── style-loader@0.13.2
├── typescript@2.0.10
├── webpack@2.2.1
├── webpack-dev-server@2.4.1
├── webpack-merge@3.0.0
└── zone.js@0.8.26
```
* I have re-created this problem, as I can see the version issue. So just visit the website and update the version.
