### ISSUE TITLE
Angular 15 fails with scss errors when building with browser:es-build 

### ISSUE THREAD

**Issue by vmuresanu** [angular/angular-cli#24467] opened 2022-12-24 21:34 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When trying to use es-build I get the following errors. Tried the solution specified in https://github.com/angular/angular-cli/issues/24356, but it didn't work for me. Also found https://github.com/angular/angular-cli/issues/24271 and other related issues, but still no luck.

```scss
[ERROR] [plugin angular-sass] Can't find stylesheet to import.
  ╷
1 │ @use 'colors' as *;
  │ ^^^^^^^^^^^^^^^^^^
  ╵
  src/app/ng-modules/containers/organization-management/containers/user-roles/dialogs/user-roles-modal.component.scss 1:1  root stylesheet


✘ [ERROR] [plugin angular-sass] Error: The "path" argument must be of type string. Received an instance of TypeError
  ╷
3 │ @use 'globals' as g;
  │ ^^^^^^^^^^^^^^^^^^^
  ╵
  src/styles/components/_mat-form-field.scss 3:1  @import
  src/styles/styles.scss 9:9                      root stylesheet

    angular:styles/global:styles:4:8:
      4 │ @import 'src/styles/styles.scss';
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~
```

### Minimal Reproduction

ng build

### Your Environment

```text
Package                         Version
---------------------------------------------------------
@angular/core                   15.0.4
@angular-devkit/build-angular   15.0.4
rxjs                            7.8.0
typescript                      4.8.4
```

**Comment by masterworgen** [comment] 2022-12-26 06:00
https://github.com/angular/angular-cli/issues/24356 - try this

**Comment by clydin** [comment] 2022-12-27 19:21
Can you provide the current value of the `includePaths ` option for the project as well as the location of the `global` and `colors` files relative to the workspace root (the location of the `angular.json` file)?

**Comment by vmuresanu** [comment] 2022-12-28 08:22
Current value of includePaths -`"includePaths": ["src/styles/variables"]` - this works for regular build. For esbuild I tried to change to `[""]` and `["."]` but still no luck
Location of angular.json - `<rootDir>/angular.json`
Location of global and color scss - `<rootDir>/src/styles/variables`

**Comment by clydin** [comment] 2022-12-28 16:58
Is the `ng build` command being executed from the workspace root? I was able to reproduce the problem if the current working directory was not the workspace root.  There appears to be a bug regarding the `includePaths` not always being resolved correctly in such cases.

**Comment by vmuresanu** [comment] 2022-12-30 09:03
Tried it again to double check and yes - ng build is being executed from the workspace root.

**Comment by gitromain** [comment] 2023-01-12 16:02
Hello, I had the same problem, I changed `@use "src/styles/variables";` to `@use "src/styles/variables.scss";`
It solved the "Can't find stylesheet to import" problem.

But then it seems that some variables are no longer found : 

`X [ERROR] [plugin angular-sass] Undefined variable.
   ╷
83 │   background: $color-primary-01-500;
   │               ^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\app\pages\attributes-campaign\attributes-campaign-creation\attributes-campaign-creation.component.scss 83:15  root stylesheet
`

**Comment by clydin** [comment] 2023-01-12 16:06
Unfortunately, we have been unable to reproduce the issue as described.  If you could provide a minimal reproduction of the issue, we can troubleshoot further.
Also, please try with the latest version of the CLI (currently 15.1.1) to see if that resolves the problem.

**Comment by alan-agius4** [comment] 2023-01-17 15:46
Unfortunately without a reproduction we are unable to look into this issue any further.  

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by clydin** [comment] 2023-01-17 15:49
@monkeycatdog The error you provided is from a Webpack based build (`@angular-devkit/build-angular:browser`).  This issue is about the experimental esbuild-based builder (`@angular-devkit/build-angular:browser-esbuild`).
Please open a separate issue if you are encountering problems with the default builder.

**Comment by vmuresanu** [comment] 2023-01-18 12:49
I have reproduced the issue - https://github.com/vmuresanu/Repro-App . Like I stated in original issue, the problem is in 
```json
"stylePreprocessorOptions": {
   "includePaths": ["src/styles/variables"]
},
```
What it does is it allows to use short syntax: 
`@use "globals" as *`
But if I point to relative path - `@use "./../styles/variables/globals" as g;` es-build works. So it is definitely the problem in stylePreprocessorOptions.

Steps to Reproduce:
1. ng build with - `browser-esbuild` - observe the error
2. ng build with `browser` - the is no errors

**Comment by alan-agius4** [comment] 2023-01-18 13:55
Thanks for the repro @vmuresanu. 

What is happening here is that `global` in being resolved incorrectly as a node package even though it does not export any CSS. 

Code: https://github.com/angular/angular-cli/blob/c3adf11a5a880f6299bdc6ae64f6f06b42791147/packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts#L120-L129

**Closed** 2023-01-19 22:13 UTC
Labels: type: bug/fix, freq1: low, severity3: broken, area: devkit/build-angular, devkit/build-angular:browser-esbuild
