### ISSUE TITLE
AoT build fails using multiple apps in own project with dependency between them

### ISSUE THREAD

**Issue by CSchulz** [angular/angular-cli#7883] opened 2017-09-29 13:21 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.4.4
node: 6.10.2
os: darwin x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4
```

### Repro steps.
https://github.com/CSchulz/angular-cli-multiple-apps-with-common

Start the project with `npm start`.

### The log given by the failure.
```
ERROR in multiple-apps-with-common/showcase/$$_gendir/src/app.component.ngfactory.ts (10,21): Cannot find module '../../../src/app/common.component.ngfactory'.
ERROR in multiple-apps-with-common/showcase/$$_gendir/src/app/app.component.ngfactory.ts (11,21): Cannot find module './app.component'.
ERROR in multiple-apps-with-common/showcase/$$_gendir/src/app/common.component.ngfactory.ts (10,21): Cannot find module './common.component'.
ERROR in multiple-apps-with-common/showcase/$$_gendir/src/index.ngfactory.ts (10,21): Cannot find module './index'.
ERROR in multiple-apps-with-common/showcase/$$_gendir/src/index.ngfactory.ts (11,21): Cannot find module './app/app.component'.
ERROR in multiple-apps-with-common/showcase/$$_gendir/src/app.module.ngfactory.ts (12,21): Cannot find module '../../../src/app/app.component.ngfactory'.
```

### Desired functionality.
The repository contains a common module, which is part of a library and the showcase should be used to show the functionality.

**Comment by filipesilva** [comment] 2017-10-10 08:58
Heya, this is a duplicate of https://github.com/angular/angular-cli/issues/6387. You can find an explanation for why this doesn't work in https://github.com/angular/angular-cli/issues/6228#issuecomment-301024884.

**Closed by filipesilva** 2017-10-10 08:58 UTC
