### ISSUE TITLE
@ngtools/webpack Conflict between DefinePlugin and AngularCompilerPlugin

### ISSUE THREAD

**Issue by daniel-nagy** [angular/angular-cli#9051] opened 2018-01-01 05:13 UTC
Variables defined by the Webpack `DefinePlugin` are not available to the config object of the `RouterModule`.

### Versions
```
@angular/compiler: 5.1.2
@angular/compiler-cli: 5.1.2
```

### Repro steps

```javascript
// webpack config
new DefinePlugin({
  PRODUCTION: Boolean(env.production)
}),
```

```typescript
// app module
const router = RouterModule.forRoot([...], {
  enableTracing: !PRODUCTION
});

@NgModule({
  imports: [
    router
  ]
})
export class AppModule {

}
```

### Observed behavior
The value of `PRODUCTION` as defined by the `DefinePlugin` is not used and `enableTracing` is always true.

### Desired behavior
I should be able to configure the `RouterModule` using variables defined by the `DefinePlugin`.

### Mention any other details that might be useful (optional)

The following [test.zip](https://github.com/angular/angular-cli/files/1595616/test.zip) file contains a minimal project to reproduce the issue. Download the zip file then run

```
npm install
npm start
```

Open a browser to localhost:3000 and notice that the router events are always logged to the console regardless of the value of `PRODUCTION` as defined in the webpack.config.js file.

**Comment by Toxicable** [comment] 2018-01-02 05:53
how about using `env.production` instead?
imported from `environment.ts`
more here https://github.com/angular/angular-cli/wiki/stories-application-environments

**Comment by daniel-nagy** [comment] 2018-01-02 16:22
I’m not using the Angular CLI. Will the AngularCompiler Wepack plugin look for an .angular-cli.json file?

The environment file approach won’t allow for code elimination when minified, unlike the DefinePlugin.

**Comment by vagonpidarasov** [comment] 2018-01-03 16:26
This is only happens when ENV variables are used in decorators' metadata.

**Comment by dgp1130** [comment] 2020-05-30 00:31
Duplicate of #9051.

**Closed by dgp1130** 2020-05-30 00:31 UTC
Labels: comp: ngtools/webpack, freq1: low, severity2: inconvenient, triage #1, type: bug/fix

**Comment by atamansv** [comment] 2020-06-02 21:58
> Duplicate of #9051.

Duplicates itself?

**Comment by dgp1130** [comment] 2020-06-02 22:01
Apologies, should be duplicate of #9874. Must have copy-pasted from the wrong tab.

**Comment by vtulin** [comment] 2020-06-11 21:58
Subscribe.
I pass env variables in my webpack to server and Angular AOT client.
Everything is fine on server, but client env are empty {}.
