### ISSUE TITLE
ng add @angular/pwa is failing

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#11750] opened 2018-08-02 12:39 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [X] add
```

### Versions

Angular CLI: 6.1.2
Node: 10.1.0
OS: darwin x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.2
@angular-devkit/build-angular     0.7.2
@angular-devkit/build-optimizer   0.7.2
@angular-devkit/build-webpack     0.7.2
@angular-devkit/core              0.7.2
@angular-devkit/schematics        0.7.2
@angular/cdk                      6.4.2
@angular/cli                      6.1.2
@angular/material                 6.4.2
@angular/pwa                      0.7.2
@ngtools/webpack                  6.1.2
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2

### Repro steps
ng new my-app
ng add @angular/pwa

### The log given by the failure

$ ng add @angular/pwa --project=weather
Installing packages for tooling via yarn.
yarn add v1.7.0
[1/4] 🔍  Resolving packages...
⠂ @angular/pwa(node:51115) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ @angular/pwa@0.7.2
info All dependencies
└─ @angular/pwa@0.7.2
✨  Done in 4.79s.
Installed packages for tooling via yarn.
Path "/ngsw-config.json" already exist.

### Desired functionality
ng add @angular/pwa should detect that the file isn't there and generate it

### Mention any other details that might be useful
The file doesn't exist, I double checked.

**Comment by filipesilva** [comment] 2018-08-02 17:12
Duplicate of https://github.com/angular/angular-cli/issues/11640

**Closed by filipesilva** 2018-08-02 17:12 UTC
