### ISSUE TITLE
Unexpected Warning: rules skipped due to selector errors (reference: #20839)

### ISSUE THREAD

**Issue by erictor** [angular/angular-cli#20906] opened 2021-05-22 18:49 UTC
A similar issue was reported 4 days ago, #20839, and has since been closed.

#### Environment:
Updated my Angular project from Angular 11 / Angular CLI 11 to Angular 12 / Angular CLI 12

#### Did this work in the previous version?
Yes.

#### Description:
In my styles.scss I have the following import as the first line:

<pre><code>@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');</code></pre>

#### Warning Text Displaying in Chrome Dev Tools:
<pre><code>1 rules skipped due to selector errors
0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');</code></pre>

I validated at fonts.google.com that the import is composed correctly.  The error is specifically pointing after family=Roboto:ital,wght@0,100; to "0,300;" (and beyond).

The Warning displays upon initial view in browser and each time the browser is refreshed.

**Comment by alan-agius4** [comment] 2021-05-24 06:03
Hi @erictor, 

The root cause seems to be a bug in [Critters](https://github.com/GoogleChromeLabs/critters) which doesn't handle properly the `@import`.

Therefore, can you please file an issue in their issue tracker?

That being said, for performance reasons due to extra network hops and delay in initialising the blocking request. It is not recommended to use `@import url` especially to remote URL and Google fonts, unless you have prefetch or preload tags for these urls in your HTML page.

The recommended approach is to have this resource referenced in your `index.html` file using a `link` element. When you build for production and using this approach, the CSS contents of the Google fonts will be inlined in the HTML page, this will help to improve the LCP and FCP or the application by removing a render blocking request.

**Closed by alan-agius4** 2021-05-24 06:03 UTC

**Comment by erictor** [comment] 2021-05-24 06:11
@alan-agius4   1. Thank you for your advice re: import and performance issues with it -- I will immediately implement your advice in my SPA project.   2. Re [Critters](https://github.com/GoogleChromeLabs/critters), can your project end up taking a dependency on it even if you aren't explicitly mentioning it in package.json?  For example, am I possibly getting it due to specifying types/node 15.3.1 in my devDependencies?   Thanks again.

**Comment by alan-agius4** [comment] 2021-05-24 06:16
> Re Critters, can your project end up taking a dependency on it even if you aren't explicitly mentioning it in package.json? For example, am I possibly getting it due to specifying types/node 15.3.1 in my devDependencies? Thanks again.

Critters is a dependency of `@angular-devkit/build-angular`. https://github.com/angular/angular-cli/blob/92a7d2fe387276247e11e0d89c7ecc2011d41b12/packages/angular_devkit/build_angular/package.json#L31

**Comment by erictor** [comment] 2021-05-24 06:17
@alan-agius4 Thank you.  That's very clear.
