### ISSUE TITLE
 High cpu usage with ngc in watch mode

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#10504] opened 2018-04-27 22:57 UTC
originally posted as https://github.com/angular/angular/issues/23570

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

I am having issue with very high cpu usage in ngc with watch mode... (~140%-190%). I am using @angular/cli in version 1.7.4 but also there is a problem on 1.6.8

![zrzut ekranu 2018-04-26 o 21 58 35](https://user-images.githubusercontent.com/7131693/39328898-12e0514a-499d-11e8-92f1-c087123e1a3c.png)

tsconfig-aot.dist.json:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "declaration": true,
    "removeComments": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "pretty": true,
    "stripInternal": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "rootDir": "./tmp/src-inlined-dist",
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "files": [
    "./tmp/src-inlined-dist/index.ts"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "src",
    "e2e",
    "bundle"
  ],
  "angularCompilerOptions": {
    "genDir": "dist",
    "debug": false,
    "skipTemplateCodegen": true,
    "skipMetadataEmit": false,
    "strictMetadataEmit": true
  }
}
```
tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "paths": {
      "components": [ "bundle" ]
    }
  },
  "exclude": [
    ".ng_build",
    "node_modules",
    "dist"
  ]
}
```

Project structure
├── .angular-cli.json
├── .editorconfig
├── .gitignore
├── .npmignore
├── .npmrc
├── .vscode
├── components 
├── dist
├── e2e
├── gulpfile.js
├── index.d.ts
├── index.js
├── index.js.map
├── karma.conf.js
├── ng-package.json
├── package.json
├── protractor.conf.js
├── README.md
├── src
├── tmp
├── tsconfig-aot.bundle.json
├── tsconfig-aot.dist.json
├── tsconfig.json
└── tslint.json

directory: 12 file: 38 symboliclink: 1

## Environment

 
For Tooling issues:
- Node version: 9.4
- Platform:  Mac OSX sierra high

**Comment by darekf77** [comment] 2018-04-28 19:17
Ok I found that when I've got linked my external npm project called "**tnp**" inside **node_modules** folder there is a problem with high cpu usage in ngc watch mode...

After removing link: *node_modules/tnp* problem doesn't exist...

My **tnp** project structure
```
.DS_Store
.git
.gitignore
.npmignore
.npmrc
.vscode
README.md
bin
dist
index.d.ts
index.js
index.js.map
node_modules
package.json
projects # this folder includes my project
src
tests
tmp
tsconfig.json
webpack.config.js
```
Folder *projects* inlcudes my project with ngc watch problem... but it is ignored anyway in tsconfig.json of this *tnp* project.

```
{
    "compilerOptions": {
        "noUnusedLocals": false,
        "target": "es5",
        "module": "commonjs",
        "declaration": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "sourceMap": true,
        "outDir": "dist",
        "moduleResolution": "node",
        "allowSyntheticDefaultImports": true,
        "types": [
            "node"
        ],
        "lib": [
            "es2015",
            "es2015.promise",
            "es2015.generator",
            "es2015.collection",
            "es2015.core",
            "es2015.reflect",
            "es2016",
            "dom"
        ],
        "typeRoots": [
            "node_modules/@types"
        ],
        "baseUrl": "./src"
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules",
        "preview",
        "actions",
        "projects",
        "docs",
        "dist",
        "tests"
    ]
}
```
I am not sure why... but **ngc** does to much operation on this *tnp* project folder... and thats why constant high cpu

**Comment by epelc** [comment] 2018-07-10 17:32
@darekf77 how did you find out it was `tnp`? Also getting high cpu usage but with `ng serve`(I assume it uses ngc under the covers)

**Comment by dsebastien** [comment] 2019-11-10 14:58
I'm not sure it is the same issue, but with polling enabled, I also notice high/constant CPU usage issues. As described here: #2748.

I have the issue under Docker & Kubernetes. During development, I run ng serve within Docker/Kubernetes against an hostPath volume (i.e., a local folder mounted into the Docker/Kubernetes container/pod.

I need polling enabled, otherwise the container doesn't know about the file changes and I would need to resort to other means to "touch" the relevant files (e.g., VSCode file watchers)

**Comment by clydin** [comment] 2019-11-10 15:15
High CPU usage is expected when polling is enabled.  The polling time period can be increased but that is a trade off between timely rebuilds and CPU usage.  This is also not Angular CLI specific.  File watching is expensive in environments that do not support native OS file watching mechanics.

**Comment by dsebastien** [comment] 2019-11-10 15:22
Of course, this makes sense. Still, the possibility to reduce the scope of file polling could help diminish the burden for those of us who do need to resort to polling. In my case, I don't need the polling to look at the node_modules folder contents and it is probably where a lot of CPU cycles get wasted.

**Comment by alan-agius4** [comment] 2020-05-27 11:44
Duplicate of https://github.com/angular/angular/issues/23570

**Closed by alan-agius4** 2020-05-27 11:44 UTC
Labels: triage #1
