### ISSUE TITLE
.30 latest templates changes not applied on re-build (video)

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#4497] opened 2017-02-07 17:44 UTC
.30 latest templates changes not applied on re-build (video)--

### OS?

```
@angular/cli: 1.0.0-beta.30
node: 6.9.5
os: win32 x64
@angular/cli: 1.0.0-beta.30
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/language-service: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.6
@ngtools/webpack: 1.2.8
```

please see the video:
https://dl.dropboxusercontent.com/u/93017334/TempIssue.mp4

repo: https://github.com/born2net/studioweb

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by filipesilva** [comment] 2017-03-09 12:07
Dupe of https://github.com/angular/angular-cli/issues/5117

**Closed by filipesilva** 2017-03-09 12:07 UTC
