### ISSUE TITLE
Ng 8 prod mode is failing

### ISSUE THREAD

**Issue by rahul0923** [angular/angular-cli#15709] opened 2019-09-29 18:38 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Ng7
### Description

 A clear and concise description of the problem...
The issue happen only on our CI pipeline
Running the build in prod mode is failing with an error

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/19897523/65837550-95aeef00-e2ad-11e9-8b1f-03c7dbf1595c.png)

## 🌍 Your Environment
![image](https://user-images.githubusercontent.com/19897523/65837562-af503680-e2ad-11e9-891d-29333c5381af.png)

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-09-29 20:36
Duplicate of https://github.com/angular/angular-cli/issues/15493

**Closed by alan-agius4** 2019-09-29 20:36 UTC
