### ISSUE TITLE
Angular application is reloading automatically

### ISSUE THREAD

**Issue by smrita-garg** [angular/angular-cli#16279] opened 2019-11-25 10:07 UTC
>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.19
Node: 10.15.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cli                      8.3.19
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

This is my ng version.

But when I run ng serve command , application reloads again and again
Please suggest

**Comment by smrita-garg** [comment] 2019-11-25 11:25
@HannesT117 @alan-agius4 ..please suggest.
I see there is similar issue . I have tried options but did not work
https://github.com/angular/angular-cli/issues/13099

**Comment by alan-agius4** [comment] 2019-11-25 12:54
This is probably a duplicate of https://github.com/angular/angular-cli/issues/16227

**Comment by alan-agius4** [comment] 2019-11-25 12:55
Can you provide a reproduction? Or at the very least your angular.json?

**Comment by smrita-garg** [comment] 2019-11-26 05:25
Hi @alan-agius4 , #16227 solved my issue .
Thanks :)

**Closed** 2019-11-26 05:25 UTC
Labels: need: repro steps

**Comment by filipesilva** [comment] 2019-11-29 16:53
@smrita-garg if you ended up figuring out what was wrong based on #16227, can you add your resolution there please? The original poster of that issue seems to still be having problems.
