### ISSUE TITLE
[1.5.0-rc2] @angular/compiler-cli package was not properly installed.

### ISSUE THREAD

**Issue by RicardoVaranda** [angular/angular-cli#7904] opened 2017-10-02 13:32 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```
Cli is failing to run after a fresh install, follow the steps below: 

### Repro steps.
```
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@next
ng -v
```

### The log given by the failure.

```
/usr/local/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:14
    throw new Error('The "@angular/compiler-cli" package was not properly installed. Error: ' + e);
    ^

Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler'
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/commands/build.js:6:19)
    at Module._compile (module.js:570:32)
```

**Comment by filipesilva** [comment] 2017-10-02 13:55
Getting this error while using `ng -v` is due to improperly loading `@ngtools/webpack` outside of build commands.

It should have been caught by our CI but something is wrong in our setup, I'm investigating.

**Comment by filipesilva** [comment] 2017-10-02 15:06
Turns out this is actually a duplicate of https://github.com/angular/angular-cli/issues/7694

**Closed by filipesilva** 2017-10-02 15:06 UTC
Labels: priority: 0 (critical), type: bug
