### ISSUE TITLE
sourcesContent added by angular serve in *.map files, cause vscode Go To Implementations not work

### ISSUE THREAD

**Issue by UchihaYuki** [angular/angular-cli#22702] opened 2022-02-14 02:27 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When I `ng build` or `ng serve`, the anguar libraries' *.map files will be modified, a `sourcesContent` property will be added, which cause vscode Go To Implementations not work.
PS: Those libraries are written by me, and I shipped with both typescript source code and source map. After uninstall then reinstall my libraries, Go To Implementations will work again. I think the modification made by angular caused this. Is there a way to disable this behavior?

## 🌍 Your Environment

<pre><code>
Angular CLI: 11.2.18
Node: 16.13.1
OS: win32 x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------  
@angular-devkit/architect       0.1102.18
@angular-devkit/build-angular   0.1102.18
@angular-devkit/core            11.2.18
@angular-devkit/schematics      11.2.18
@angular/cli                    11.2.18
@schematics/angular             11.2.18
@schematics/update              0.1102.18
rxjs                            6.6.7
typescript                      4.0.8

</code></pre>

**Comment by alan-agius4** [comment] 2022-02-14 09:34
The is caused by NGCC which is needed for Angular libraries that have been compiled with older versions of Angular. NGCC is no longer needed when compiled with Angular 13+.

That said, in general it is not expected that TypeScript sources are included in `node_modules` See: https://github.com/angular/angular-cli/issues/22701

Closing as NGCC doesn't support such a library setup.

**Closed by alan-agius4** 2022-02-14 09:34 UTC
