### ISSUE TITLE
localhost:4200 not found and Not start ng serve

### ISSUE THREAD

**Issue by rushhit93** [angular/angular-cli#15083] opened 2019-07-15 11:26 UTC
Firstly -> NPM download my computer and install. 
### Node version : 12.6 , NPM: 6.9
PowerShell -> Typing this codes

 1 npm install -g @angular/cli **(Version : 8.1.1)**
 2 ng new angular
 3 cd angular (https://github.com/rushhit93/angular)
 4 ng serve or ng serve -o

Give me an error "ng serve " like this.
**_

> An unhandled exception occurred: argument fn must be a function
> See "C:\Users...." for further details.

_**

After I'm looking http://localhost:4200 
 - Page Not Found 

I'm researching forums but not working please help me.
How can i solve this sitiation?

**Comment by alan-agius4** [comment] 2019-07-15 11:29
Can you kindly provide the contents of the error log file?

Thanks

**Comment by alan-agius4** [comment] 2019-07-15 11:33
I cloned your project and I am unable to replicate the above reported issue.

**Comment by rushhit93** [comment] 2019-07-15 11:33
I don't understand but i think this file .

> [error] TypeError: argument fn must be a function
>     at Function.wrapfunction [as function] (C:\Users\Raşit\desktop\angular\node_modules\depd\index.js:399:11)
>     at populateConstructorExports (C:\Users\Raşit\desktop\angular\node_modules\http-errors\index.js:264:45)
>     at Object.<anonymous> (C:\Users\Raşit\desktop\angular\node_modules\http-errors\index.js:30:1)
>     at Module._compile (internal/modules/cjs/loader.js:776:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:643:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>     at Module.require (internal/modules/cjs/loader.js:683:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.<anonymous> (C:\Users\Raşit\desktop\angular\node_modules\send\index.js:15:19)

**Comment by rushhit93** [comment] 2019-07-15 11:41
@alan-agius4 upload errors log
[angular-errors.log](https://github.com/angular/angular-cli/files/3392057/angular-errors.log)

**Comment by rushhit93** [comment] 2019-07-15 11:47
> I cloned your project and I am unable to replicate the above reported issue using Node 12.6 on OSX.

I am using Node 12.6 on Win7 is there a problem ? This problem, i think port problem but i can't change port. Because it's working xammp localhost on 80 port.

**Comment by rushhit93** [comment] 2019-07-15 12:06
@elvisbegovic can you help ?

**Comment by elvisbegovic** [comment] 2019-07-15 12:22
@rushhit93  if you think it's port problem then try another one free `ng s --port 4222`

I can confirm what Alan says, I tried your project under this environnement 
```
Angular CLI: 8.1.1
Node: 12.6.0
OS: win32 x64 (Windows 10)
Angular: 8.1.1
```

and I don't have problem, it build !

**Comment by rushhit93** [comment] 2019-07-15 12:54
Why not working i don't understand 4200 port not working. Do u have any idea ?

**Comment by elvisbegovic** [comment] 2019-07-15 13:09
@rushhit93  ah wait, does it works on another port ? if yes I think you can close this issue because it is not related to angular. To confirm please run `netstat -ano | find "4200"` if this port is used by another thing you should close it or simply use another port?

**Comment by rushhit93** [comment] 2019-07-15 15:31
> @rushhit93 ah wait, does it works on another port ? if yes I think you can close this issue because it is not related to angular. To confirm please run `netstat -ano | find "4200"` if this port is used by another thing you should close it or simply use another port?

Sorry but not use this port. I trying 80 port listenning and established but 4200 port hasn't a thing. I don't understand. I read all forums, not found anything this subject

**Comment by rushhit93** [comment] 2019-07-15 17:13
I solved @elvisbegovic  and @alan-agius4  

node : 12,6 not working angular. Maybe, my computer didnt work because it is win7 not win10 but now its working. 

> Angular CLI: 8.1.1
> Node: 10.16.0
> OS: win32 x64 (Windows 7)
> Angular: 8.1.1

**Closed** 2019-07-15 17:13 UTC

**Comment by abdullahkaraman** [comment] 2019-08-05 09:02
@rushhit93 sorunu nasıl çözdün reis bende de aynı sorun var.

**Comment by rushhit** [comment] 2019-08-06 13:10
Node 12 yi kullanma node 10 yap
Angular CLI: 8.1.1
Node: 10.16.0
OS: win32 x64 (Windows 7)
Angular: 8.1.1
