### ISSUE TITLE
Debug watch builds are slower in angular 7

### ISSUE THREAD

**Issue by HarelM** [angular/angular-cli#13112] opened 2018-12-01 21:37 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions:
npm: 6.2.0
node: v8.11.3
angular-cli: 7.1.0

### Repro steps
Using the following repository:
https://github.com/IsraelHikingMap/Site
Inside IsraelHiking.web run `npm install`, 
`npm run build -- --watch`
change a file and measure the time it takes to finish incremental build.
Now do the same for the `openlayers` branch.
Changes in incremental build are significant...

### Desired functionality
incremental build time should not change that much between angular 6 and 7.

### Mention any other details that might be useful
Overall build time of production is also becoming an issue which got a bit worse in angular 7.

**Comment by alan-agius4** [comment] 2018-12-02 11:51
Duplicate of https://github.com/angular/angular-cli/issues/13102

**Closed by alan-agius4** 2018-12-02 11:51 UTC
