### ISSUE TITLE
ng new not creating project

### ISSUE THREAD

**Issue by dgonza12** [angular/angular-cli#11882] opened 2018-08-14 00:26 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node 8.9.4

```
Angular CLI: 6.1.3
Node: 8.9.4
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.3
@angular-devkit/core         0.7.3
@angular-devkit/schematics   0.7.3
@schematics/angular          0.7.3
@schematics/update           0.7.3
rxjs                         6.2.2
typescript                   2.9.2

```

npm 5.6.0
MacOs High Sierra 10.13.6

### Repro steps

npm install -g @angular/cli
ng new appname

### The log given by the failure

Tree type is not supported.

### Desired functionality

generate project

### Mention any other details that might be useful

I've tried uninstalling and reinstalling as well as going back to 6.1.0 but it still does not fix my problem

**Comment by kob-e** [comment] 2018-08-14 06:59
Duplicate of #11707

**Closed** 2018-08-14 13:50 UTC

**Comment by will0684** [comment] 2018-08-20 17:37
Why are all 3 related issues closed? It is still a problem where uninstalling-reinstalling local and global packages gets in the way, and even that does not work all of the time and a rollback is required, which also may not work. Can we reopen one of these issues?
