### ISSUE TITLE
[Issue] ng init fails in fresh clone

### ISSUE THREAD

**Issue by d3viant0ne** [angular/angular-cli#4590] opened 2017-02-10 11:06 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX 10.12.3

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
 ```
@angular/cli: 1.0.0-beta.31
node: 7.5.0
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
- Create a new repo with a readme
- Clone the repo
- `ng init`

Selecting `overwrite` or `skip`, the CLI just aborts.

**Workaround:** Deleting the readme and running `ng init` the CLI runs initial setup as expected.

### The log given by the failure.
> Normally this include a stack trace and some more information.

No stack Trace output...

![screen shot 2017-02-10 at 5 02 11 am](https://cloud.githubusercontent.com/assets/8420490/22824663/6e562658-ef4e-11e6-9c32-0b7adbabc84b.png)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

- Previous version of the CLI was removed, cache cleaned & verified to be nuked.
- CLI install executed without issue

**Comment by filipesilva** [comment] 2017-02-10 11:17
Dupe of https://github.com/angular/angular-cli/issues/4584

**Closed by filipesilva** 2017-02-10 11:17 UTC

**Comment by d3viant0ne** [comment] 2017-02-10 11:21
Ah early morning search fails .. sorry :)
