### ISSUE TITLE
ng build --prod taking too much time - more than 40 minutes

### ISSUE THREAD

**Issue by ArielBar** [angular/angular-cli#9503] opened 2018-02-04 07:07 UTC
after I upgraded to angular 5 
when i do ->ng build --prod it's took 42.615133

Angular CLI: 1.6.7
Node: 8.9.1
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.7
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0

before upgrading to Angular 5 the build took 11.6135 Minutes

with this packages:
@angular/cli: 1.4.3
node: 8.9.1
os: win32 x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
typescript: 2.5.3

**Comment by clydin** [comment] 2018-02-04 16:21
Duplicate of https://github.com/angular/angular-cli/issues/6795.  Version 1.7.0 (current in beta as 1.7.0-beta.3) will contain multiple performance enhancements in this area.

**Closed by clydin** 2018-02-04 16:21 UTC
