### ISSUE TITLE
ng update @angular/cli installs 9.0.0-next.0

### ISSUE THREAD

**Issue by zakhenry** [angular/angular-cli#15237] opened 2019-08-02 14:56 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Yes?

### Description

 A clear and concise description of the problem...
ng update should install the latest stable version, unless `--next` is passed. Running this now installs `9.0.0-next.0`

## 🔬 Minimal Reproduction

1. Install angular 8 project
1. run ng update @angular/cli
1. see 9.0.0-next.0 was (attempted to be) installed.
## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.2.0
Node: 10.15.3
OS: darwin x64
Angular: 9.0.0-next.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.1
@angular-devkit/build-angular      0.802.0
@angular-devkit/build-ng-packagr   0.802.0
@angular-devkit/build-optimizer    0.802.0
@angular-devkit/build-webpack      0.801.1
@angular-devkit/core               8.1.1
@angular-devkit/schematics         8.1.1
@angular/cdk                       8.0.1
@angular/cli                       8.2.0
@angular/material                  8.0.2
@angular/pwa                       0.13.5
@schematics/angular                7.3.5
@schematics/update                 0.802.0
ng-packagr                         5.4.3
rxjs                               6.5.2
typescript                         3.5.3
webpack                            4.29.6

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-08-02 16:49
Duplicate of https://github.com/angular/angular-cli/issues/14980

**Closed by alan-agius4** 2019-08-02 16:49 UTC

**Comment by i-aleksandrov** [comment] 2019-08-29 14:14
I noticed that running only `ng update @angular/cli@8.2.2` by itself causes it to be updated to 8.2.2, but the other angular dependencies to version 9.0.0-next, while running `ng update @angular/cli@8.2.2 @angular/core8.2.2` actually works correctly.

I had cli version 8.0.3 and successfully updated to 8.2.2 running both cli and core update at the same time.

Hope this helps because the other issue is closed as too heated.
