### ISSUE TITLE
Custom Angular Library

### ISSUE THREAD

**Issue by HassanRamadan11** [angular/angular-cli#22684] opened 2022-02-10 08:29 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler, language-service

### Is this a regression?

No

### Description

I created custom angular library  contain angular material,then i install it in my project.
finally i try to use my library in my angular project I faced issue in chrome console
"The NgModule 'AppModule' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available".
and some times after updating the version of my library it's Module does not work again in import array.

**Comment by alan-agius4** [comment] 2022-02-17 16:09
Closing due to lack of a reproduction.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Closed by alan-agius4** 2022-02-17 16:09 UTC
Labels: need: repro steps
