### ISSUE TITLE
Rename lazy-loaded bundles with the name of their module

### ISSUE THREAD

**Issue by BenjaminSchubert** [angular/angular-cli#5582] opened 2017-03-23 10:00 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

@angular/cli: 1.0.0-rc.4
node: 6.10.0
os: linux x64
@angular/common: 4.0.0-rc.6
@angular/compiler: 4.0.0-rc.6
@angular/core: 4.0.0-rc.6
@angular/forms: 4.0.0-rc.6
@angular/http: 4.0.0-rc.6
@angular/platform-browser: 4.0.0-rc.6
@angular/platform-browser-dynamic: 4.0.0-rc.6
@angular/router: 4.0.0-rc.6
@angular/cli: 1.0.0-rc.4
@angular/compiler-cli: 4.0.0-rc.6

### Desired functionality.

When using lazy loaded modules, they get extracted by Webpack to separate bundles, which is great. 

However, the names of the bundles are really obscure : `[0-9]+\.$hash\.js` which is not practical when trying to debug things in one of them.

I would really like something like `$name_of_the_module.$hash.js` instead, which would allow us to know directly which bundle is this. I don't know if webpack would be able of this though.

Thanks a lot !

**Comment by intellix** [comment] 2017-03-23 10:39
Dupe of: https://github.com/angular/angular-cli/issues/5171

**Comment by PEsteves8** [comment] 2017-03-23 18:33
Yup, there are a few issues asking for this. I also tried doing ng eject and messing directly with the webpack config. However, the chunk [name] seems to end up being the same as the [id] (all those numbers).  So I'm not really sure on how to get named chunks that way either. (or separating them into different directories, but I don't think webpack supports that)

**Comment by filipesilva** [comment] 2017-03-23 23:54
Closing as dupe, thans @intellix !

**Closed by filipesilva** 2017-03-23 23:54 UTC
