### ISSUE TITLE
request and har-validator deprecated

### ISSUE THREAD

**Issue by nainardev** [angular/angular-cli#18821] opened 2020-09-19 02:56 UTC
# 🐞 Bug report

### Command
```sh
npm i -g @angular/cli
```

### Is this a regression?
What?

### Description
`request@2.86.2` and `har-validator@5.1.5` are both deprecated

## 🔬 Minimal Reproduction
`npm i -g @angualr/cli`
## 🔥 Exception or Error
```sh
$ npm i -g @angular/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

## 🌍 Your Environment
```sh
Node - v14.11
npm - v6.14.5
@angular/cli@10.1.2
Windows VIII
```

**Comment by alan-agius4** [comment] 2020-09-19 07:58
Duplicate of #16952

Note: `har-validator` is a dependency of `request`.

**Closed by alan-agius4** 2020-09-19 07:58 UTC

**Comment by MuhammadRaheelFayyaz** [comment] 2020-10-01 16:44
try yarn instead of  npm
`sudo yarn global add  @angular/cli
`
