### ISSUE TITLE
JIT is ok, use AOT failed

### ISSUE THREAD

**Issue by XuJinNet** [angular/angular-cli#8797] opened 2017-12-08 08:26 UTC
ng serve --aot --port 9000 --host 0.0.0.0
```
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './app/app.module.ngfactory' in '/Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/src'
resolve './app/app.module.ngfactory' in '/Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/src'
  using description file: /Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/package.json (relative path: ./src)
    using description file: /Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/package.json (relative path: ./src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/src/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/src/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/src/app/app.module.ngfactory.js doesn't exist
      as directory
        /Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/src/app/app.module.ngfactory doesn't exist
[/Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/src/app/app.module.ngfactory]
[/Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/src/app/app.module.ngfactory.ts]
[/Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/src/app/app.module.ngfactory.js]
[/Users/xujin/My_Projects/CSharp/antme-uwp/antme/antme-uwp-web/src/app/app.module.ngfactory]
 @ ./src/main.ts 4:0-66
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

Dependencies:
```
"dependencies": {
        "@angular/animations": "^5.1.0",
        "@angular/common": "^5.1.0",
        "@angular/compiler": "^5.1.0",
        "@angular/core": "^5.1.0",
        "@angular/forms": "^5.1.0",
        "@angular/platform-browser": "^5.1.0",
        "@angular/platform-browser-dynamic": "^5.1.0",
        "@angular/router": "^5.1.0",
        "core-js": "^2.4.1",
        "lodash": "^4.17.4",
        "rxjs": "^5.5.2",
        "zone.js": "^0.8.14"
    },
    "devDependencies": {
        "@angular/cli": "^1.6.0",
        "@angular/compiler-cli": "^5.1.0",
        "@angular/language-service": "^5.1.0",
        "@angularclass/hmr": "^2.1.3",
        "@types/jasmine": "~2.5.53",
        "@types/jasminewd2": "~2.0.2",
        "@types/lodash": "^4.14.87",
        "@types/node": "^8.0.31",
        "codelyzer": "^4.0.1",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.1.2",
        "rimraf": "^2.6.1",
        "ts-node": "~3.2.0",
        "tslint": "~5.7.0",
        "typescript": "~2.5.3"
    }
```

macOS: 10.13.2
Node: 8.9.2
CLI: 1.6.0
Angular: 5.1.0

**Comment by diko316** [comment] 2017-12-08 10:39
Same here:

```shell
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './app/app.module.ngfactory' in '/opt/app/src'
resolve './app/app.module.ngfactory' in '/opt/app/src'
  using description file: /opt/app/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /opt/app/package.json (relative path: ./src)
    using description file: /opt/app/package.json (relative path: ./src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /opt/app/src/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /opt/app/src/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /opt/app/src/app/app.module.ngfactory.js doesn't exist
      as directory
        /opt/app/src/app/app.module.ngfactory doesn't exist
[/opt/app/src/app/app.module.ngfactory]
[/opt/app/src/app/app.module.ngfactory.ts]
[/opt/app/src/app/app.module.ngfactory.js]
[/opt/app/src/app/app.module.ngfactory]
 @ ./src/main.ts 3:0-66
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

```

Ubuntu: 16.04
Node: 7.5.0
CLI: 1.6.0
Angular: 5.0.0

**Comment by robi26** [comment] 2017-12-08 14:50
Same problem here
Angular CLI: 1.6.0
Node: 8.9.1
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0

**Comment by SherwinJames** [comment] 2017-12-08 15:00
Same problem for me.

Angular CLI: 1.6.0
Node: 8.9.0
OS: Windows 10 x64
Angular: 5.1.0

**Comment by Andrey-Pavlov** [comment] 2017-12-08 15:04
I managed to fix the bug for AOT by enabling error details
https://github.com/angular/angular/issues/20292#issuecomment-350260569

**Comment by matheo** [comment] 2017-12-13 19:51
Thanks @Andrey-Pavlov!
I lost some hours trying to get the specific error message, and ~5.0.0 worked!

**Comment by burakkilic** [comment] 2017-12-14 17:53
@Andrey-Pavlov How did you fixed? Can you explain a bit more?

**Comment by iagomelanias** [comment] 2017-12-14 18:00
@burakkilic did you try to downgrade your CLI version to `~1.5`? This worked for me.

**Comment by burakkilic** [comment] 2017-12-14 18:18
I downgraded Angular to 5.0.0 and could see the exact error.  Then I upgrade again 👍

**Comment by iagomelanias** [comment] 2017-12-14 18:40
@burakkilic and the CLI?

**Comment by burakkilic** [comment] 2017-12-14 18:49
I didn't downgrade the CLI

**Comment by iagomelanias** [comment] 2017-12-14 18:50
@burakkilic 
> did you try to downgrade your CLI version to ~1.5? This worked for me.

**Comment by XuJinNet** [comment] 2017-12-25 05:57
After upgrade to the latest Angular and CLI, can view the exact error

**Comment by crutchcorn** [comment] 2017-12-26 17:31
Duplicate of #21164, #20292, #21051, and #20978.

Upgrade to Angular 5.1.1, this will solve the problem.

**Comment by filipesilva** [comment] 2018-01-09 12:59
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by matheo** [comment] 2018-01-09 16:16
In my case, there was a non-reported error about non-existing ChangeDetectorRef for a leaf component, and that didn't allow the generation of the module.ngfactory.

I followed the instructions in the comments to see the exact error and I was able to solve it.

**Comment by UltraKenchie** [comment] 2018-08-14 04:57
Same here when adding RouterModule. Error doesn't show on first build, then cannot find RouterModule on app upon hot reload. Disabling aot seems to have solved the problem temporarily. (This was a fresh ng new project via CLI 6.1.2)

Angular CLI: 6.1.2
Node: 8.11.1
OS: win10 x64
Angular: 6.1.2 (updated, same error when 6.0.4)

**Comment by alan-agius4** [comment] 2018-09-18 16:53
Closing as no re-production was provided.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2018-09-18 16:53 UTC
Labels: need: repro steps, priority: 1 (urgent), severity3: broken
