### ISSUE TITLE
Build failed with deleteOutputPath: false option in config

### ISSUE THREAD

**Issue by kostyahoriainov** [angular/angular-cli#21093] opened 2021-06-09 07:38 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11.2.14

### Description

Build failes, if add deleteOutputPath: false in build options.

Seems like it might happend after update to webpack 5, cuz on angular v11 (with wepback 4) everything was fine.

```
ng build

√ Browser application bundle generation complete.
An unhandled exception occurred: Could not find asset for file: main.bbac280f1a66c93defc1.js
See "C:\Users\admin\AppData\Local\Temp\ng-jbrLjq\angular-errors.log" for further details.

```

## 🔬 Minimal Reproduction

Create a new project via `ng new`, add `deleteOutputPath: false`  param in build options, and run `ng build` several times. After first build everything is fine, but if to run it again with no code changes, error occurred and build failes.

## 🔥 Exception or Error

<pre><code>
√ Browser application bundle generation complete.
An unhandled exception occurred: Could not find asset for file: main.bbac280f1a66c93defc1.js
See "C:\Users\admin\AppData\Local\Temp\ng-jbrLjq\angular-errors.log" for further details.
</code></pre>

![image](https://user-images.githubusercontent.com/43550315/121311853-7afb9d00-c90d-11eb-85e2-87a96da9bbc1.png)

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.3
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@schematics/angular             12.0.3
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-06-09 07:43
Duplicate of https://github.com/angular/angular-cli/issues/21038

**Closed by alan-agius4** 2021-06-09 07:43 UTC
