### ISSUE TITLE
Can't create new Angular project with angular-cli

### ISSUE THREAD

**Issue by zmbq** [angular/angular-cli#9129] opened 2018-01-08 10:42 UTC
I've installed @angular/cli version 1.6.3 and then did:

    ng new frontend --routing
    cd frontend
    ng build

I got an error saying main.ts and polyfills.ts are not included in tsconfig.json .

I've seen two issues on the matter, one was about ts placed in the wrong place, the other was closed as a duplicate of the first. This is clearly not the same case - I did not create *any* ts files, and all I need to do is run that series of commands and get the exact same behavior. This happens on several of our development machines (all with Windows 10)

### Versions
```
Angular CLI: 1.6.3
Node: 8.9.3
OS: win32 x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

```
    ng new frontend --routing
    cd frontend
    ng build
```

### Observed behavior
The following errors:
```
ERROR in d:/chelem/ShalevItzkovitz/Interactions/frontend/src/main.ts
Module build failed: Error: d:\chelem\ShalevItzkovitz\Interactions\frontend\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (d:\chelem\ShalevItzkovitz\Interactions\frontend\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:653:23)
    at plugin.done.then (d:\chelem\ShalevItzkovitz\Interactions\frontend\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous> @ multi ./src/main.ts

ERROR in d:/chelem/ShalevItzkovitz/Interactions/frontend/src/polyfills.ts
Module build failed: Error: d:\chelem\ShalevItzkovitz\Interactions\frontend\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (d:\chelem\ShalevItzkovitz\Interactions\frontendnode_modules\@ngtools\webpack\src\angular_compiler_plugin.js:653:23)
    at plugin.done.then (d:\chelem\ShalevItzkovitz\Interactions\frontend\node_modules\@ngtoolswebpack\src\loader.js:467:39)
    at <anonymous> @ multi ./src/polyfills.ts
```
### Desired behavior
`ng new` should create a project that can be built and served.

**Comment by Taha-Di-Nero** [comment] 2018-01-08 17:03
Tried to reproduce the problem but the build succeed.
I noted that you have 5.1.3 as angular version but when I run 'ng new frontend --routing ' produce the following package.json:

> {
>   "name": "frontend",
>   "version": "0.0.0",
>   "license": "MIT",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build --prod",
>     "test": "ng test",
>     "lint": "ng lint",
>     "e2e": "ng e2e"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "^5.0.0",
>     "@angular/common": "^5.0.0",
>     "@angular/compiler": "^5.0.0",
>     "@angular/core": "^5.0.0",
>     "@angular/forms": "^5.0.0",
>     "@angular/http": "^5.0.0",
>     "@angular/platform-browser": "^5.0.0",
>     "@angular/platform-browser-dynamic": "^5.0.0",
>     "@angular/router": "^5.0.0",
>     "core-js": "^2.4.1",
>     "rxjs": "^5.5.2",
>     "zone.js": "^0.8.14"
>   },
>   "devDependencies": {
>     "@angular/cli": "1.6.3",
>     "@angular/compiler-cli": "^5.0.0",
>     "@angular/language-service": "^5.0.0",
>     "@types/jasmine": "~2.5.53",
>     "@types/jasminewd2": "~2.0.2",
>     "@types/node": "~6.0.60",
>     "codelyzer": "^4.0.1",
>     "jasmine-core": "~2.6.2",
>     "jasmine-spec-reporter": "~4.1.0",
>     "karma": "~1.7.0",
>     "karma-chrome-launcher": "~2.1.1",
>     "karma-cli": "~1.0.1",
>     "karma-coverage-istanbul-reporter": "^1.2.1",
>     "karma-jasmine": "~1.1.0",
>     "karma-jasmine-html-reporter": "^0.2.2",
>     "protractor": "~5.1.2",
>     "ts-node": "~3.2.0",
>     "tslint": "~5.7.0",
>     "typescript": "~2.4.2"
>   }
> }

**Comment by filipesilva** [comment] 2018-01-09 11:38
@zmbq just to confirm, you're saying that `ng new` does not create the TS files right? Can you show me the console output from running `ng new appname` please? 

Yesterday I also saw an odd problem with a generator where files were not created on Windows 10. I'm guessing it's a similar problem, but seeing the log for `ng new` would help.

**Comment by zmbq** [comment] 2018-01-09 13:01
```
C:\Users\itay\sources\ShalevItzkovitz\Interactions [master] > ng new frontend --routing --style=scss
  create frontend/e2e/app.e2e-spec.ts (290 bytes)
  create frontend/e2e/app.po.ts (208 bytes)
  create frontend/e2e/tsconfig.e2e.json (235 bytes)
  create frontend/karma.conf.js (923 bytes)
  create frontend/package.json (1320 bytes)
  create frontend/protractor.conf.js (722 bytes)
  create frontend/README.md (1024 bytes)
  create frontend/tsconfig.json (363 bytes)
  create frontend/tslint.json (3040 bytes)
  create frontend/.angular-cli.json (1245 bytes)
  create frontend/.editorconfig (245 bytes)
  create frontend/.gitignore (516 bytes)
  create frontend/src/assets/.gitkeep (0 bytes)
  create frontend/src/environments/environment.prod.ts (51 bytes)
  create frontend/src/environments/environment.ts (387 bytes)
  create frontend/src/favicon.ico (5430 bytes)
  create frontend/src/index.html (295 bytes)
  create frontend/src/main.ts (370 bytes)
  create frontend/src/polyfills.ts (2405 bytes)
  create frontend/src/styles.scss (80 bytes)
  create frontend/src/test.ts (1085 bytes)
  create frontend/src/tsconfig.app.json (211 bytes)
  create frontend/src/tsconfig.spec.json (304 bytes)
  create frontend/src/typings.d.ts (104 bytes)
  create frontend/src/app/app-routing.module.ts (245 bytes)
  create frontend/src/app/app.module.ts (395 bytes)
  create frontend/src/app/app.component.html (1173 bytes)
  create frontend/src/app/app.component.spec.ts (1103 bytes)
  create frontend/src/app/app.component.ts (208 bytes)
  create frontend/src/app/app.component.scss (0 bytes)
Installing packages for tooling via yarn.
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@angular/cli > @angular-devkit/schematics > @schematics/schematics@0.0.11" has unmet peer dependency "@angular-
devkit/core@0.0.22".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 64.65s.
Installed packages for tooling via yarn.
Directory is already under version control. Skipping initialization of git.
Project 'frontend' successfully created.
```

**Comment by zmbq** [comment] 2018-01-09 13:02
Here is the output of `ng build`:
```
C:\Users\itay\sources\ShalevItzkovitz\Interactions\frontend [master] > ng build
Date: 2018-01-09T13:00:45.702Z
Hash: a73c63c6ee645ae53d98
Time: 2180ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 867 bytes [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 892 bytes [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 3.02 kB [initial] [rendered]

ERROR in d:/chelem/ShalevItzkovitz/Interactions/frontend/src/main.ts
Module build failed: Error: d:\chelem\ShalevItzkovitz\Interactions\frontend\src\main.ts is missing from the TypeScript c
ompilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (d:\chelem\ShalevItzkovitz\Interactions\frontend\node_modules\@ngtools\webp
ack\src\angular_compiler_plugin.js:653:23)
    at plugin.done.then (d:\chelem\ShalevItzkovitz\Interactions\frontend\node_modules\@ngtools\webpack\src\loader.js:467
:39)
    at <anonymous>
 @ multi ./src/main.ts
ERROR in d:/chelem/ShalevItzkovitz/Interactions/frontend/src/polyfills.ts
Module build failed: Error: d:\chelem\ShalevItzkovitz\Interactions\frontend\src\polyfills.ts is missing from the TypeScr
ipt compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (d:\chelem\ShalevItzkovitz\Interactions\frontend\node_modules\@ngtools\webp
ack\src\angular_compiler_plugin.js:653:23)
    at plugin.done.then (d:\chelem\ShalevItzkovitz\Interactions\frontend\node_modules\@ngtools\webpack\src\loader.js:467
:39)
    at <anonymous>
 @ multi ./src/polyfills.ts
```

**Comment by filipesilva** [comment] 2018-01-09 13:06
@zmbq and you don't have the `src/main.ts` file after `ng new`, correct?

**Comment by zmbq** [comment] 2018-01-09 13:27
@filipesilva , I do have src/main.ts . I'm attaching a file with the entire content of the directory created by `ng new` (I just removed node_modules from the zip file)

[frontend.zip](https://github.com/angular/angular-cli/files/1615202/frontend.zip)

**Comment by filipesilva** [comment] 2018-01-09 13:33
I'm sorry but I cannot reproduce what you're seeing... I downloaded your file, ran `npm install` and then `npm run ng -- build` and it built correctly:

```
kamik@T460p MINGW64 D:/sandbox/frontend
$ npm run ng -- build

> frontend@0.0.0 ng D:\sandbox\frontend
> ng "build"

Date: 2018-01-09T13:31:27.310Z
Hash: f520f53812d927e1da2e
Time: 7503ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 9.67 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 202 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.7 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.73 MB [initial] [rendered]
```

Do you have symlinks or juntions in that path? I'm looking at the log you posted and the error is shown in a different folder than the one you run the commands from.

If so then the bug you are running into is https://github.com/angular/angular-cli/issues/8603.

**Comment by zmbq** [comment] 2018-01-09 13:39
One of the directories there is indeed a junction. I tried running `ng build –preserve-symlinks ` yesterday and it didn’t make any difference. For some really impossible to comprehend reason, today it *does* work with –preserve-symlinks…

 

  So it is the same bug. Thanks and sorry.

**Comment by filipesilva** [comment] 2018-01-09 13:44
Maybe at the time you had a version of Angular CLI with a bug that prevented it from working. I'll close as a duplicate of #8603 then.

**Closed by filipesilva** 2018-01-09 13:44 UTC
Labels: need: more info, priority: 1 (urgent), type: bug

**Comment by zmbq** [comment] 2018-01-09 14:02
It was definitely version 1.6.3, as well. Oh well.

**Comment by Caiuse** [comment] 2018-02-07 12:59
I had this bug today, running with `–preserve-symlinks` worked but without it would not build. I was running with from windows cmd. I think there is still a problem.

**Comment by r-havelka** [comment] 2018-02-16 14:46
I was having this same bug for a couple hours. I found out that I was in the wrong working directory.
my directory: `~/My Documents/Github/MyProject/client`
correct directory: `~/Documents/Github/MyProject/client`
