### ISSUE TITLE
ng new --help is missing a lot of the options

### ISSUE THREAD

**Issue by brianharwell** [angular/angular-cli#8051] opened 2017-10-14 02:19 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

When you do `ng new --help` you are given a list of options which you can view [here](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/commands/new.ts). This list does not match the documentation found [here](https://github.com/angular/angular-cli/blob/master/docs/documentation/new.md).

**Comment by pavilion** [comment] 2017-10-15 16:12
It is true. 
Missing 'collection'.

**Comment by filipesilva** [comment] 2017-10-16 12:54
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/7723. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-10-16 12:54 UTC
