### ISSUE TITLE
Lazy-loading not supported using application builder's prerender

### ISSUE THREAD

**Issue by RobSis** [angular/angular-cli#28811] opened 2024-11-07 15:06 UTC
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

When performing pre-rendering with the new application builder, dynamically loaded components can't be used.

This was not an issue with the legacy (webpack-based) prerender and is not an issue with other build modes (ssr, serve, development).

```javascript
   const promise = import("./components/pageA.component").then(m => m.PageAComponent);
   promise.then(componentClass => {
      // This clause is never called when prerendering with the new builder, but works on the legacy webpack prerender.
      this.loadComponentDynamically(componentClass, this.child, content)
   });
```

Lazy-loading in router continues to work:

```javascript
   export const routes: Routes = [{
     path: 'pageC',
     loadComponent: () => import('./components/pageC.component').then(m => m.PageCComponent)
  },
```

### Minimal Reproduction

A minimal example demonstrating the problem: https://github.com/RobSis/angular-lazy-components/

Or on StackBlitz: https://stackblitz.com/~/github.com/RobSis/angular-lazy-components

Run `npm run legacy-prerender` and see that `dist/lazy-components/browser/pageA/index.html` contains rendered component.

Run `npm run prerender` to see that while Router lazy-loaded `pageC/index.html` is rendered, `pageA/index.html` is empty. 

### Exception or Error

No error visible.

### Your Environment

Angular CLI: 18.2.11
Node: 20.9.0
Package Manager: npm 10.1.0
OS: linux x64

Angular: 18.2.11
... animations, cli, common, compiler, compiler-cli, core
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.11
@angular-devkit/build-angular   18.2.11
@angular-devkit/core            18.2.11
@angular-devkit/schematics      18.2.11
@schematics/angular             18.2.11
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

### Anything else relevant?

The chunk file seems to be correctly created:

```
Browser bundles        
Lazy chunk files        | Names               |  Raw size
chunk-WI2JHTDR.js       | pageA-component     |   1.45 kB | 
chunk-KGLGRA3U.js       | pageC-component     |   1.20 kB |
```

**Comment by alan-agius4** [comment] 2024-11-07 17:34
Duplicate of https://github.com/angular/angular/issues/53191

**Closed by alan-agius4** 2024-11-07 17:34 UTC
