### ISSUE TITLE
Debug vendor code included with npm

### ISSUE THREAD

**Issue by alastair-todd** [angular/angular-cli#5687] opened 2017-03-27 10:56 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.9.4
os: win32 x64
@angular/common: 4.0.0-rc.6
@angular/compiler: 4.0.0-rc.6
@angular/core: 4.0.0-rc.6
@angular/forms: 4.0.0-rc.6
@angular/http: 4.0.0-rc.6
@angular/platform-browser: 4.0.0-rc.6
@angular/platform-browser-dynamic: 4.0.0-rc.6
@angular/router: 4.0.0-rc.6
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0-rc.6

### Repro steps.

Create a new project, install some dependency with types

```
npm i --save leaflet
npm i --save-dev @types/leaflet

```
### Desired functionality.

A way to emit the non-minified version of the vendor script file so that it can be stepped into. Currently no way of debugging 3rd party in the context of an app.

All we currently get is one line like:

```
module.exports = "(function(f){if(typeof exports===\"object\ ...


//////////////////
// WEBPACK FOOTER
// ./~/raw-loader!./~/leaflet/dist/leaflet.js
// module id = 431
// module chunks = 3

```

**Comment by filipesilva** [comment] 2017-03-27 12:16
Mostly a dupe of https://github.com/angular/angular-cli/issues/5687, where a way to get all vendor sourcemaps should be supported.

**Closed by filipesilva** 2017-03-27 12:16 UTC

**Comment by alastair-todd** [comment] 2017-03-27 13:30
@filipesilva you have created a circular reference :)

#5687 is this post

**Comment by alastair-todd** [comment] 2017-03-28 05:58
@filipesilva could you please correctly reference the dupe? Thanks.

**Comment by alastair-todd** [comment] 2017-03-31 14:56
@filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva @filipesilva
