### ISSUE TITLE
angular-cli doesn't work when node_modules is located in a parent directory

### ISSUE THREAD

**Issue by Arbuzov** [angular/angular-cli#19491] opened 2020-11-27 12:03 UTC
# 🐞 Bug report

### ng build

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Can`t build a project if parent directory named node_modules

## 🔬 Minimal Reproduction
1. create a folder named node_modules
2. checkout the project where
3. exec npm install
4. exec ng build

## 🔥 Exception or Error
<pre><code>
[error] Error: Could not resolve './lib/notification/index' from dist\core\esm2015\public-api.js
    at error (C:\Users\info\Desktop\node_modules\ngx-spacebridge\node_modules\rollup\dist\shared\rollup.js:5251:30)
    at ModuleLoader.handleResolveId (C:\Users\info\Desktop\node_modules\ngx-spacebridge\node_modules\rollup\dist\shared\rollup.js:18389:24)
    at Promise.all.Array.from (C:\Users\info\Desktop\node_modules\ngx-spacebridge\node_modules\rollup\dist\shared\rollup.js:18358:22)</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.1
Node: 10.19.0
OS: win32 x64

Angular: 11.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@angular/language-service       11.0.2
@schematics/angular             11.0.1
@schematics/update              0.1100.1
ng-packagr                      11.0.3
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by alan-agius4** [comment] 2020-11-27 12:26
@Arbuzov dod you forget to link up the reproduction?

Also from the stack trace I am seeing that this is a library build. Hence likely it’s an ng-packagr or rollup issue.

**Comment by Arbuzov** [comment] 2020-11-27 12:49
@alan-agius4 the repo which was used for the reproduction is private. I cant share it.
I reproduced the problem in the another way.
1. create a node_modules directory
2. ng new new-app
3. cd ./new-app
4. ng build

<code><pre>
ERROR in ./src/app/app.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\info\Desktop\node_modules\new-app\src\app\app.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\info\Desktop\node_modules\new-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:938:23)
    at plugin.done.then (C:\Users\info\Desktop\node_modules\new-app\node_modules\@ngtools\webpack\src\loader.js:42:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

ERROR in ./src/environments/environment.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\info\Desktop\node_modules\new-app\src\environments\environment.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\info\Desktop\node_modules\new-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:938:23)
    at plugin.done.then (C:\Users\info\Desktop\node_modules\new-app\node_modules\@ngtools\webpack\src\loader.js:42:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
</pre></code>

**Comment by alan-agius4** [comment] 2020-11-30 09:34
Hi @Arbuzov,

I just had a look at this, it seems that TypeScript compiler is not generating all the files in this case. I managed to replicate this by using `tsc` directly.

```
$ yarn tsc -p tsconfig.app.json
$ tree out-tsc
out-tsc
└── app
    ├── main.js
    ├── main.js.map
    ├── polyfills.js
    └── polyfills.js.map

1 directory, 4 files

$ mv ../../node_modules ../../dir
yarn tsc -p tsconfig.app.json
$ tree out-tsc
out-tsc
└── app
    ├── app
    │   ├── app.component.js
    │   ├── app.component.js.map
    │   ├── app.module.js
    │   └── app.module.js.map
    ├── environments
    │   ├── environment.js
    │   └── environment.js.map
    ├── main.js
    ├── main.js.map
    ├── polyfills.js
    └── polyfills.js.map

3 directories, 10 files
```

Side note:  in general I would suggest not to name custom directories `node_modules`. `node_modules` is a special directory name when it comes to Node.JS runtime during module resolution. Also typically these folders are safe to delete as they are re-generated via an installation. Having a `node_modules` directory which is actually not a generated via an NPM/Yarn install might causes confusion IMHO.

Closing as this is not caused by the Angular CLI. Please contact the author(s) of the [TypeScript](https://github.com/microsoft/TypeScript/issues) project or file an issue on their issue tracker.

**Closed by alan-agius4** 2020-11-30 09:34 UTC

**Comment by Arbuzov** [comment] 2020-11-30 11:33
@alan-agius4 exactly
In my case then I launch tsc directly it creates required js files.

I want to create an angular library publish it inside the corporate private repo and use it in other projects.

To build the lib after install I added "posinstall" action "ng build" and it fails

**Comment by alan-agius4** [comment] 2020-11-30 12:09
It's not recommended that you include uncompiled `.ts` file in your node_modules. A library should be compiled and bundled pre-published. 

Some of the reasons  for this;
1) Different TypeScript versions between the application and library.
2) Different compiler options settings.
3) Different @angular versions.
4) Doesn't conform with the Angular package format https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview

If you want create a publishable Angular library following the best practices, you can do the below.

```
ng new lib-workspace --no-create-application
ng g library my-lib
ng build --prod
npm publish dist/my-lib
```

More info: https://angular.io/guide/creating-libraries

Note: the library can be used in the mono-repo without the need of using npm install/yarn install.
