### ISSUE TITLE
`ng help command` not supported while it works in ember-cli

### ISSUE THREAD

**Issue by mgol** [angular/angular-cli#3195] opened 2016-11-18 15:16 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

macOS 10.12.1 (16B2555)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Just run:
```
ng help set
```
You can substitute `set` for any other CLI command.

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
$ ng help set
undefined
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

Ember CLI allows to print help for a specific command:
```
$ ember help build
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Requested ember-cli commands:

ember build <options...>
  Builds your app and places it into the output path (dist/ by default).
  aliases: b
  --environment (String) (Default: development)
    aliases: -e <value>, -dev (--environment=development), -prod (--environment=production)
  --output-path (Path) (Default: dist/)
    aliases: -o <value>
  --watch (Boolean) (Default: false)
    aliases: -w
  --watcher (String)
  --suppress-sizes (Boolean) (Default: false)
```

This is extremely useful as the whole help can be quite large and hard to navigate.

**Comment by Brocco** [comment] 2016-12-08 04:46
Duplicate of #3168 closing this issue in favor of the other.

**Comment by mgol** [comment] 2016-12-08 08:32
@Brocco I don't think it's a duplicate; #3168 is purely about the `ng --help` -> `ng help` change.

**Closed** 2016-12-13 03:11 UTC
