### ISSUE TITLE
Cannot run `ng new` on existing Angular project

### ISSUE THREAD

**Issue by gingi** [angular/angular-cli#19987] opened 2021-02-05 16:30 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't know

### Description

Unable to create a workspace in an existing Angular project.

## 🔬 Minimal Reproduction

```shell
$ mkdir tmp-project
$ cd tmp-project
$ touch README.md .gitignore
$ ng new project-name --directory=./ --defaults
A merge conflicted on path "/README.md".
$ ng new project-name --directory=./ --defaults --force
A merge conflicted on path "/README.md".
```

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.1.3
Node: 12.20.1
OS: darwin x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1101.3 (cli-only)
@angular-devkit/core         11.1.3 (cli-only)
@angular-devkit/schematics   11.1.3 (cli-only)
@schematics/angular          11.1.3 (cli-only)
@schematics/update           0.1101.3 (cli-only)

</code></pre>

**Comment by alan-agius4** [comment] 2021-02-05 16:58
This is working as expected, you cannot create a workspace inside and existing Angular workspace.
 
 If you want to create a new application inside an existing workspace you need use 

```
ng generate application <project-name>
```

Duplicate of https://github.com/angular/angular-cli/issues/15247

**Closed by alan-agius4** 2021-02-05 16:58 UTC

**Comment by gingi** [comment] 2021-02-05 17:07
Thank you. But this command doesn't work either. I'm trying to retrofit an existing Angular repo with an Angular workspace. It does not have a project definition for a workspace:

```
$ ng generate application MyProject
The generate command requires to be run in an Angular project, but a project definition could not be found.
```

How would I go about doing that?

**Comment by alan-agius4** [comment] 2021-02-05 17:14
The easier way would be to use `ng new` in different directory and copy manually the existing application files after the workspace is created.
