### ISSUE TITLE
Complex style configuration in angular.json not working with npm 'linked' CSS

### ISSUE THREAD

**Issue by DavidUrting** [angular/angular-cli#17772] opened 2020-05-20 08:56 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Not sure, this is the first time I have this situation.

### Description

When using a 'complex' style configuration in angular.json in combination with a .css file coming from a linked NPM package the .css file is not bundled. When installing the NPM as a regular NPM package or when configuring a direct path to the .css the .css is bundled.

So in a nutshell, it seems that the 'complex' style configuration does not support NPM links.

## 🔬 Minimal Reproduction

1. create an npm package in a directory _/some-package_. Add a .css file in _/some-package/dist/some-package.css_ and a package.json. Name the package _@company/some-package_.
2. create an Angular application in _/application_. 
3. add a link to 'some-package' int the dependencies section of the package.json of the application: `"@company/some-package": "file:../some-package"`.
4. Run `npm install` in /application.
4. add a complex style configuration to angular.json that refers the css in the package:
```
            "styles": [
              "src/styles.scss",
              {
                "input": "node_modules/@company/some-package/dist/some-package.css",
                "bundleName": "some-package",
                "inject": true
              }
            ],
```
When running ng build or ng serve the css is not bundled and as such the styles are not applied.
When I refer the css directly it works:
```
            "styles": [
              "src/styles.scss",
              {
                "input": "../some-package/dist/some-package.css",
                "bundleName": "some-package",
                "inject": true
              }
            ],
```

A Github repository that reproduces the problem can be found on [https://github.com/DavidUrting/angular-style-configuration-npm-link-issue](https://github.com/DavidUrting/angular-style-configuration-npm-link-issue).

## 🔥 Exception or Error
<pre><code>
No errors/exceptions.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.6
Node: 12.16.2
OS: win32 x64

Angular: 9.1.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.6
@angular-devkit/build-angular     0.901.6
@angular-devkit/build-optimizer   0.901.6
@angular-devkit/build-webpack     0.901.6
@angular-devkit/core              9.1.6
@angular-devkit/schematics        9.1.6
@angular/cli                      9.1.6
@ngtools/webpack                  9.1.6
@schematics/angular               9.1.6
@schematics/update                0.901.6
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-05-20 09:36
Duplicate of https://github.com/angular/angular-cli/issues/3500

**Closed by alan-agius4** 2020-05-20 09:36 UTC
