### ISSUE TITLE
Angular 9: Not exist on type 'JQuery<any>'

### ISSUE THREAD

**Issue by Toso82** [angular/angular-cli#16905] opened 2020-02-10 08:17 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was:  8.2

### Description

In previus version i don't have this error i define types for my Jquery extension:

```typescript
declare var ForMaps:any

interface JQuery {
    forMapsSearch(options?: any): any;
    forMapsDraw(options?: any): any;
    forMapsMarker(options?: any): any;
    forMapsCatasto(options?: any): any;
    forMapsTavolare(options?: any): any;    
    forMapsOmi(options?: any): any;
    forMapsLivelliAmministrativi(options?: any): any;
    forMapsPuntiFiduciali(options?: any): any;
    forMapsElencoNazionale(options?: any): any;
    forMapsPoi(options?: any): any;
    forMapsAnnunci(options?: any): any;

}
```

## 🔬 Minimal Reproduction

`ng serve`

## 🔥 Exception or Error
<pre><code>

ERROR in src/app/component/for-maps/for-maps.component.ts:41:24 - error TS2304: Cannot find name 'ForMaps'.
    
    41     this.forMaps = new ForMaps(this.IdMappa,
                              ~~~~~~~
    src/app/component/for-maps/for-maps.component.ts:52:21 - error TS2339: Property 'forMapsDraw' does not exist on type 'JQuery<any>'.
    
    52     $(this.forMaps).forMapsDraw();
                           ~~~~~~~~~~~
    src/app/component/for-maps/for-maps.component.ts:53:21 - error TS2339: Property 'forMapsCatasto' does not exist on type 'JQuery<any>'.
    
    53     $(this.forMaps).forMapsCatasto();
                           ~~~~~~~~~~~~~~
    src/app/component/for-maps/for-maps.component.ts:54:21 - error TS2339: Property 'forMapsTavolare' does not exist on type 'JQuery<any>'.
    
    54     $(this.forMaps).forMapsTavolare();
                           ~~~~~~~~~~~~~~~
    src/app/component/for-maps/for-maps.component.ts:55:21 - error TS2339: Property 'forMapsOmi' does not exist on type 'JQuery<any>'.
    
    55     $(this.forMaps).forMapsOmi();
                           ~~~~~~~~~~
    src/app/component/for-maps/for-maps.component.ts:56:21 - error TS2339: Property 'forMapsLivelliAmministrativi' does not exist on type 'JQuery<any>'.
    
    56     $(this.forMaps).forMapsLivelliAmministrativi();
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/app/component/for-maps/for-maps.component.ts:57:21 - error TS2339: Property 'forMapsPuntiFiduciali' does not exist on type 'JQuery<any>'.
    
    57     $(this.forMaps).forMapsPuntiFiduciali();
                           ~~~~~~~~~~~~~~~~~~~~~
    src/app/component/for-maps/for-maps.component.ts:58:21 - error TS2339: Property 'forMapsPoi' does not exist on type 'JQuery<any>'.
    
    58     $(this.forMaps).forMapsPoi();
                           ~~~~~~~~~~
    src/app/component/for-maps/for-maps.component.ts:59:21 - error TS2339: Property 'forMapsAnnunci' does not exist on type 'JQuery<any>'.
    
    59     $(this.forMaps).forMapsAnnunci();
                           ~~~~~~~~~~~~~~
    src/app/component/for-maps/for-maps.component.ts:67:30 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.
    
    67            latLng: new (<any>L).latLng(x.Latitudine, x.Longitudine),
                                    ~
    src/app/component/for-maps/for-maps.component.ts:97:53 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.
    
    97       (<any>this.forMaps.map).flyToBounds(new (<any>L).LatLngBounds(listcoordinate));
                                                           ~
    src/app/component/for-maps/for-maps.component.ts:106:25 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.
    
    106           latLng: (<any>L).latLng(component.Latitudine, component.Longitudine),
                                ~
    src/app/component/for-maps/for-maps.component.ts:115:26 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.
    
    115         .setLatLng((<any>L).latLng(component.Latitudine, component.Longitudine));
                                 ~
    src/app/component/for-maps/for-maps.component.ts:127:25 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.
    
    127           latLng: (<any>L).latLng(change.Latitudine.currentValue, change.Longitudine.currentValue),
                                ~
    src/app/component/for-maps/for-maps.component.ts:136:26 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.
    
    136         .setLatLng((<any>L).latLng(change.Latitudine.currentValue, change.Longitudine.currentValue));
        

</code></pre>


## 🌍 Your Environment
<pre><code>
<!-- run `ng version` and paste output below -->
<!-- ✍️-->
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 13.7.0
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->

<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->

**tsconfig.app.json**
```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": [ "jquery", "googlemaps","node" ],
    "allowJs": true
    
  },  "files": [
    "main.ts",
    "polyfills.ts"
  ]
}
```

**tsconfig.spec.json**
```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

**Comment by fredjeck** [comment] 2020-02-10 11:12
Potentially linked to #16907

**Comment by alan-agius4** [comment] 2020-02-10 13:00
Can you try to add the below in your `tsconfig.app.json`.

```
"include": [
    "**/*.d.ts"
 ]
```

**Comment by Toso82** [comment] 2020-02-10 13:05
@alan-agius4  Correct something but not this:

```ps
ERROR in src/app/component/for-maps/for-maps.component.ts:67:30 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.

67            latLng: new (<any>L).latLng(x.Latitudine, x.Longitudine),
                                ~
src/app/component/for-maps/for-maps.component.ts:97:53 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.

97       (<any>this.forMaps.map).flyToBounds(new (<any>L).LatLngBounds(listcoordinate));
                                                       ~
src/app/component/for-maps/for-maps.component.ts:106:25 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.

106           latLng: (<any>L).latLng(component.Latitudine, component.Longitudine),
                            ~
src/app/component/for-maps/for-maps.component.ts:115:26 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.

115         .setLatLng((<any>L).latLng(component.Latitudine, component.Longitudine));
                             ~
src/app/component/for-maps/for-maps.component.ts:127:25 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.

127           latLng: (<any>L).latLng(change.Latitudine.currentValue, change.Longitudine.currentValue),
                            ~
src/app/component/for-maps/for-maps.component.ts:136:26 - error TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.

136         .setLatLng((<any>L).latLng(change.Latitudine.currentValue, change.Longitudine.currentValue));
                             ~

```

**Comment by alan-agius4** [comment] 2020-02-10 13:37
https://stackoverflow.com/questions/46092807/l-refer-to-a-umd-global-compilation-error

**Comment by fredjeck** [comment] 2020-02-10 14:00
> "include": [
>     "**/
 
Thanks a lot for that one, it solves my issue, now my local typings file is picked up correctly

**Comment by Toso82** [comment] 2020-02-10 14:11
@alan-agius4  Thanks i solve import  on top of my component

```typescript
import * as L from 'leaflet';
```

Maybe it is aot unable now to default

**Comment by alan-agius4** [comment] 2020-02-10 14:15
> Maybe it is aot unable now to default
In V9 AOT is indeed enabled by default, however that errors is TypeScript related.

Closing as it seems that the issue is solved.

**Closed by alan-agius4** 2020-02-10 14:15 UTC
Labels: need: more info
