### ISSUE TITLE
feature: do not compile lazy loaded modules if they were not modified

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#4079] opened 2017-01-18 00:42 UTC
### OS?
all

### Versions.
all

### feature:
I would love to be able to break down my application to lazy loaded modules and have the cli (webpack) skip modules which are lazy loaded and thus there is no need to re-compile them on every save while in development mode.

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by hansl** [comment] 2017-01-18 01:02
Duplicate of #4080

**Closed by hansl** 2017-01-18 01:02 UTC
