### ISSUE TITLE
Warnings for deprecated libraries when creating new angular application

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#19194] opened 2020-10-24 01:22 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Not sure

### Description
Generating a new angular workspace produces warnings for deprecated libraries

## 🔬 Minimal Reproduction
```bash
> npx @angular/cli@v11.0.0-rc.0 new web-appliations --create-application=false --strict
```

## 🔥 Exception or Error
<pre><code>
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
</code></pre>

<img width="1142" alt="warnings_ng_cli" src="https://user-images.githubusercontent.com/13006107/97064683-beb7b700-1575-11eb-8386-31e6eae38ff8.png">

## 🌍 Your Environment
<pre><code>
$ ng version
Angular CLI: 11.0.0-rc.0
Node: 15.0.1
OS: darwin x64

Angular: 11.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.0-rc.0
@angular-devkit/core         11.0.0-rc.0
@angular-devkit/schematics   11.0.0-rc.0
@schematics/angular          11.0.0-rc.0
@schematics/update           0.1100.0-rc.0
rxjs                         6.6.3
typescript                   4.0.3
    
Done in 0.99s.
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-10-24 06:43
Duplicate of https://github.com/angular/angular-cli/issues/18821

**Closed by alan-agius4** 2020-10-24 06:43 UTC
