### ISSUE TITLE
deploy on the nginx,then exec npm run serve:ssr

### ISSUE THREAD

**Issue by yangjunfocus** [angular/angular-cli#17553] opened 2020-04-27 09:27 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
i tried to exec `node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod ` and `node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng run demo:server:production` but it can't work
 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve:ssr'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'preserve:ssr', 'serve:ssr', 'postserve:ssr' ]
5 info lifecycle utsource-wap@0.0.0~preserve:ssr: utsource-wap@0.0.0
6 info lifecycle utsource-wap@0.0.0~serve:ssr: utsource-wap@0.0.0
7 verbose lifecycle utsource-wap@0.0.0~serve:ssr: unsafe-perm in lifecycle true
8 verbose lifecycle utsource-wap@0.0.0~serve:ssr: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Node\Node\Angular\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle utsource-wap@0.0.0~serve:ssr: CWD: C:\Node\Node\Angular
10 silly lifecycle utsource-wap@0.0.0~serve:ssr: Args: [ '/d /s /c', 'node dist/over/server/main.js --watch' ]
11 silly lifecycle utsource-wap@0.0.0~serve:ssr: Returned: code: 134  signal: null
12 info lifecycle utsource-wap@0.0.0~serve:ssr: Failed to exec serve:ssr script
13 verbose stack Error: utsource-wap@0.0.0 serve:ssr: `node dist/over/server/main.js --watch`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid utsource-wap@0.0.0
15 verbose cwd C:\Node\Node\Wap
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve:ssr"
18 verbose node v12.14.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 134
22 error utsource-wap@0.0.0 serve:ssr: `node dist/over/server/main.js --watch`
22 error Exit status 134
23 error Failed at the utsource-wap@0.0.0 serve:ssr script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.3
Node: 10.15.3
OS: win32 x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.3
@angular-devkit/build-angular     0.901.3
@angular-devkit/build-optimizer   0.901.3
@angular-devkit/build-webpack     0.901.3
@angular-devkit/core              9.1.3
@angular-devkit/schematics        9.1.3
@ngtools/webpack                  9.1.3
@nguniversal/builders             9.1.0
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.3
@schematics/update                0.901.3
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-04-27 10:39
Duplicate of https://github.com/angular/universal/issues/1641

**Closed by alan-agius4** 2020-04-27 10:39 UTC
