### ISSUE TITLE
Page reload and refresh of content not working

### ISSUE THREAD

**Issue by JJkip** [angular/angular-cli#3064] opened 2016-11-08 12:25 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX El Capitan 10.11.6

### Versions.
> ng --version
>angular-cli: 1.0.0-beta.19-3
>node: 7.0.0
>os: darwin x64

### Repro steps.
>App created using the new cli beta 19

### The log given by the failure.
> No log because the app doesn't reloads or refresh updated content

### Mention any other details that might be useful.
When i create a new angular 2 app using the updated cli and npm, no changes are reflected on the browser until i stop running then serve the app again. npm start also has the same issue.

> ---------------------------------------------------------------

**Comment by filipesilva** [comment] 2016-11-21 13:29
Dupe of https://github.com/angular/angular-cli/issues/2833. Please read that issue for resolution instructions. You likely are referencing the wrong path in a import.

**Closed by filipesilva** 2016-11-21 13:29 UTC
