### ISSUE TITLE
Confusing angular execution file order

### ISSUE THREAD

**Issue by Serginho** [angular/angular-cli#20522] opened 2021-04-14 11:53 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No

### Description
Writing some console.logs on the first line of different angular cli project files. I could see this weird order.
<img width="465" alt="captura_de_pantalla_2021-04-14_a_las_13 35 33" src="https://user-images.githubusercontent.com/315972/114704773-46150480-9d27-11eb-9910-be657b61036f.png">

- `serializable.ts`: is a console.log inside a custom decorator
- other files: angular cli project known files

## 🔬 Minimal Reproduction
- `ng new repro`
- put `console.log` in all files
- `yarn start`
<img width="787" alt="Captura de pantalla 2021-04-14 a las 13 47 39" src="https://user-images.githubusercontent.com/315972/114705728-57aadc00-9d28-11eb-8852-4302e17ef315.png">

I thought the order would be:

-polyfills
-main
-app.module
-app.component

## 🌍 Your Environment
```
Angular CLI: 10.2.3
Node: 12.16.3
OS: darwin x64

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.3
@angular-devkit/build-angular   0.1002.3
@angular-devkit/core            10.2.3
@angular-devkit/schematics      10.2.3
@angular/cli                    10.2.3
@schematics/angular             10.2.3
@schematics/update              0.1002.3
rxjs                            6.6.7
typescript                      4.0.7
```

**Comment by alan-agius4** [comment] 2021-04-14 12:40
This is caused by how file are bundle and not by Angular. 

When you do  top levels `console.log` which are not scoped in a `constructor` or a life cycle hook. The `log` will be invoked when the file is being evaluated which doesn't follow the real application life cycle. Therefore, the order you are seeing above, is relative in which order that particular `log` is present in the bundle. This is because, the leaf dependencies are added to top of the bundle while the entrypoint `main.ts` is always at the bottom.

**Comment by Serginho** [comment] 2021-04-14 12:52
@alan-agius4 I run out this issue analyzing this code:

```
import {enableProdMode} from '@angular/core';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';
import {environment} from '~environments/environment';

import {RootModule} from './app/root.module';

if (environment.angularProduction) {
  enableProdMode();
}

platformBrowserDynamic()
  .bootstrapModule(RootModule)
  .catch(err => console.error(err));
```

Then, maybe this is not the right place to put `enableProdMode();` cause if I use `isDevmode()` in a shared typescript module that probably will be evaluated before this code. It's... weird. In this context, `isDevMode()` is useless.

**Comment by alan-agius4** [comment] 2021-04-14 13:19
Hi @Serginho, 

It's unclear if what that `serializer.ts` is and if `isDevMode` is being invoked at top level. But if it is, it's working as expected.

> So... main.ts is not the webpack entrypoint, isn't it?

It is.

**Comment by Serginho** [comment] 2021-04-14 14:31
@alan-agius4 Here is an example something like serializable: an object with properties decorated

```ts
export function FooPropertyDecorator() {
  return function(target: any, propertyName: string) {
    if (isDevMode()) {
      scanAdditionalMetadataToPreventErrors();
    }
  };
}
```

**Comment by alan-agius4** [comment] 2021-04-14 14:52
Since the log is in a decorator is invoked during evaluation.

See: https://www.typescriptlang.org/docs/handbook/decorators.html#decorator-composition

**Closed by alan-agius4** 2021-04-14 14:52 UTC
