### ISSUE TITLE
ng serve does not consider/update pipes

### ISSUE THREAD

**Issue by clement-jacquet** [angular/angular-cli#4336] opened 2017-02-02 03:44 UTC
Angular-CLI don't update pipes on save.

### OS?
> Windows 10 64bits

### Versions.
> 1.0.0-beta.26

### Repro steps.
> Add new pipe to your project by doing `ng g p pipename`, launch app with `ng serve` then update your pipe in your editor/IDE and save it. Angular-CLI will recompile the app but won't consider the pipe's changes.

**Comment by Meligy** [comment] 2017-02-02 09:42
I just tried with beta.29 and this seems to work fine.

Steps:

```
ng new sampleapp
cd sampleapp
ng g pipe sample
```

The modified `sample.pipe.ts`:

```
transform(value: any, args?: any): any
  return value + ' add 123';
}
```

Then modified `app.component.html`:

```
<h1>
  {{title | sample}}
</h1>
```

Then ran `ng serve`, and opened Chrome.

Then, while still serving, changed `sample.pipe.ts` to:

```
transform(value: any, args?: any): any
  return value + ' add 123 456';
}
```

And switched to Chrome.. The browser has already refreshed and I could see the new pipe value.

**Comment by ramesh-yadav** [comment] 2017-02-02 09:56
Same as #4338

**Comment by clement-jacquet** [comment] 2017-02-02 18:38
@Meligy Just installed beta 29 and followed your steps, but the error still occurs

**Comment by filipesilva** [comment] 2017-02-03 15:54
Dupe of https://github.com/angular/angular-cli/issues/4338

**Closed by filipesilva** 2017-02-03 15:54 UTC
