### ISSUE TITLE
Generated directive does not follow the styleguide

### ISSUE THREAD

**Issue by Gelio** [angular/angular-cli#1435] opened 2016-07-23 10:42 UTC
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions.
angular-cli: 1.0.0-beta.10
node: 6.2.2
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
``` bash
ng generate directive AnimateOnScroll
```
The generated class's name is simply *AnimateOnScroll*, but according to [the styleguide](https://angular.io/docs/ts/latest/guide/style-guide.html#!#02-03) it should be _AnimateOnScroll**Directive**_

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Not related.

5. Mention any other details that might be useful.

**Comment by apaganobeleno** [comment] 2016-07-25 02:02
I think this is a duplicate of #1217, right ?

**Comment by filipesilva** [comment] 2016-07-27 02:14
Correct, it is a duplicate. Closing, but the other issue will receive attention.

**Closed by filipesilva** 2016-07-27 02:14 UTC

**Comment by apaganobeleno** [comment] 2016-07-30 16:47
@filipesilva awesome, thanks!
