### ISSUE TITLE
Component with side-effectful decorator is tree-shaken (Ivy tree shakes entry components)

### ISSUE THREAD

**Issue by CarstenLeue** [angular/angular-cli#15809] opened 2019-09-20 18:58 UTC
# 🐞 bug report

### Affected Package
Angular Ivy compiler in AOT mode

### Is this a regression?

Yes, this works in non-ivy AOT builds

### Description

I have ngModules that contain `entryComponents` like so:

```typescript
@NgModule({
  declarations: [PageLayoutComponent],
  imports: [CommonModule, WchNgComponentsModule],
  entryComponents: [PageLayoutComponent]
})
export class PageLayoutModule {
}
```

When adding this module to my application module, the `PageLayoutComponent` component will be part of the final bundle, no matter whether its is referenced by a template, a route or the bootstrap process. This works for both AOT and JIT mode.

With Ivy enabled this is **not** the case, the component is NOT part of the final bundle, despite the fact that it is referenced as an entry component.
In JIT mode the component is included, in AOT mode it is not.

For my usecase this is a problem because I am attaching a custom decorator to the component and I expect this decorator to execute when the module is loaded. This in turn is done to be able to dynamically instantiate these components without having to reference them explicitly, the custom decorator registers the components.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.5
Node: 10.16.3
OS: win32 x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.5
@angular-devkit/build-angular     0.803.5
@angular-devkit/build-optimizer   0.803.5
@angular-devkit/build-webpack     0.803.5
@angular-devkit/core              8.3.5
@angular-devkit/schematics        8.3.5
@angular/cli                      8.3.5
@ngtools/webpack                  8.3.5
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment] 2019-10-10 22:22
I'm transferring this issue to our CLI team, as optimization is the job of the bundler/tree-shaker, not Angular itself.

**Comment by alan-agius4** [comment] 2019-10-11 06:58
Hi I had a quick look at this and I am not understanding why a `Component` with a custom decorator should be retained in the final bundle if the actual component is never referenced in any template.

**Comment by CarstenLeue** [comment] 2019-10-11 07:09
@alan-agius4 because it is referenced in the `entryComponents` of its module. Pre-Ivy this caused the component not to be tree shaken.

In our project we use the custom decorators to "register" the decorated components with our application, so they can then be instantiated dynamically via a `ComponentFactoryResolver`.

My expectation is that angular maintains a reference to the components mentioned in `entryComponents`, so the bundler will not tree shake it.

**Comment by alan-agius4** [comment] 2019-10-11 08:50
//cc @alxhub, build optimizer will mark classes as pure and hence when a class is unused it will be eventually dropped by terser.

**Comment by alan-agius4** [comment] 2019-10-17 17:33
Following a discussion around this with the team the suggested way forward is to reference the class and mark it as used so it gets retained.

Something like the below;
```ts
window.retain = [ FooComponent ];
```

We don't feel that we should do anything around this as `entryComponents` were not intended to be used to retain unused classes.

**Comment by vikerman** [comment] 2019-10-31 17:32
We have a workaround as mentioned above. Closing this issue.

**Closed by vikerman** 2019-10-31 17:32 UTC

**Comment by ssmartin** [comment] 2019-11-20 10:14
> Following a discussion around this with the team the suggested way forward is to reference the class and mark it as used so it gets retained.
> 
> Something like the below;
> 
> ```ts
> window.retain = [ FooComponent ];
> ```
> 
> We don't feel that we should do anything around this as `entryComponents` were not intended to be used to retain unused classes.

Hi @alan-agius4 ,

The angular documentation states: "The entryComponents array
Though the @NgModule decorator has an entryComponents array, most of the time you won't have to explicitly set any entry components because Angular adds components listed in @NgModule.bootstrap and those in route definitions to entry components automatically. Though these two mechanisms account for most entry components, **if your app happens to bootstrap or dynamically load a component by type imperatively, you must add it to entryComponents explicitly"**

So for me your answer does not make too much sense. We have a similar issue on Angular 8 but we are not using the IVY AOT build. Nevertheless, a component that we want to load dynamically is tree shake causing problems in our app. 
Also the workaround provided here is a bit extreme... then why bother using the entryComponents anymore if we need to do such workarounds? 

Regards,
Sergiu

**Comment by ssmartin** [comment] 2019-11-20 10:48
Furthermore, we have a service annotated witht the @Injectable and so on and that is also tree shake despite the fact that is imported and used in two other services - I really think that starting Angular 8 the way how the tree shake is made has some serious flaws.

**Comment by alan-agius4** [comment] 2019-11-20 11:22
@ssmartin, this issue is related to Ivy. Can you kindly file a new issue togather with the minimal reproduction please? 

Thanks.
