### ISSUE TITLE
How to maintain 2 different versions of Angular 2 cli

### ISSUE THREAD

**Issue by MukundSonaiya** [angular/angular-cli#5950] opened 2017-04-13 10:36 UTC
After updating to latest angular cli I am not able to run the older projects using downgraded version. Is there any way I can manage 2 different version of angular cli in system?

I get following error :- 

The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/Users/mqc/MyProjects/AngularProjects/ArcBlok/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mqc/MyProjects/AngularProjects/ArcBlok/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! block-right-cli@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the block-right-cli@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the block-right-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs block-right-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls block-right-cli
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mqc/.npm/_logs/2017-04-13T10_45_33_394Z-debug.log

Process finished with exit code 1

**Comment by grizzm0** [comment] 2017-04-13 11:13
Dupe of #5933

**Comment by hansl** [comment] 2017-04-13 20:00
Answered in #5955.

**Closed by hansl** 2017-04-13 20:00 UTC
