### ISSUE TITLE
angular-devkit/schematics: Tree.read() returns null when tsconfig.json contains path mappings

### ISSUE THREAD

**Issue by BePo65** [angular/angular-cli#20118] opened 2020-10-13 17:45 UTC
I getvthe following error in my application (with about 10 modules). To isolate the root cause I created a minimal angular app that shows the effect.

#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. generate new angular project `ng new test-app --defaults=true --routing=false --style=scss`
2. add `paths` to `tsconfig.json`
```
      :
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "@lib/*": ["hacks/private-libs/*"],
      "@app/*": ["app/*"],
      "@env/*": ["environments/*"],
      "@config/*": ["app/config/*"],
      "@shared/*": ["app/shared/*"]
    }
      :
```
3. modify `main.ts` to use paths defined in `tsconfig.json`
```
      :
import { AppModule } from '@app/app.module';
import { environment } from '@env/environment';
      :
```
4. add @angular/material using `ng add @angular/material`
 
 
#### Expected Behavior

`ng add @angular/material` resolves import paths using `paths` definition in tsconfig.json

#### Actual Behavior

error:
```
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Choose a prebuilt theme name, or "custom" for a custom theme: Indigo/Pink        [ Preview: https://material.angular.i
o?theme=indigo-pink ]
? Set up global Angular Material typography styles? Yes
? Set up browser animations for Angular Material? Yes
UPDATE package.json (1343 bytes)
√ Packages installed successfully.
Could not read Angular module file: /src/@app/app.module.ts
```

#### Environment

- Angular: tried V9.1 and V10
- CDK/Material:
- Browser(s): --
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by alan-agius4** [comment] 2021-02-22 21:03
Duplicate of https://github.com/angular/angular-cli/issues/12740

**Closed by alan-agius4** 2021-02-22 21:03 UTC
Labels: comp: devkit/schematics, hotlist: angular material, type: bug/fix
