### ISSUE TITLE
Completion message for 'ng lint' is duplicated

### ISSUE THREAD

**Issue by ImranAhmed** [angular/angular-cli#11231] opened 2018-06-13 15:23 UTC
### Bug Report or Feature Request (mark with an `x`)
- [x ] bug report -> please search issues before submitting

### Versions
$ node --version
v8.9.4

$ npm --version
5.6.0

$ ng --version

Angular CLI: 6.0.3
Node: 8.9.4
OS: win32 x64
Angular: 6.0.0

### Repro steps
execute `ng lint` on any project

### The log given by the failure
The message on completion is always duplicated, see below.

![image](https://user-images.githubusercontent.com/2539520/41360961-d0b2bdd6-6f25-11e8-9c44-7bc5354c6e7e.png)

### Desired functionality
The completion message should not be duplicated

**Comment by AmandaFoster** [comment] 2018-06-25 21:54
This also applies to error messages, and the console reports success even on errors:
```
ng lint  
ERROR: testing/directives/router-link.stub.ts[7, 5]: In the class "RouterLinkStubDi
rective", the directive input property "routerLink" should not be renamed. However, you should use an alias when the dir
ective name is also an input property, and the directive name doesn't describe the property. In this last case, you can
disable this rule with `tslint:disable-next-line:no-input-rename`.
ERROR: testing/directives/router-link.stub.ts[7, 5]: In the class "RouterLinkStubDi
rective", the directive input property "routerLink" should not be renamed. However, you should use an alias when the dir
ective name is also an input property, and the directive name doesn't describe the property. In this last case, you can
disable this rule with `tslint:disable-next-line:no-input-rename`.

Lint errors found in the listed files.


All files pass linting.
```

**Comment by ajspera** [comment] 2018-07-13 19:05
This is because it actually runs linting on 2 'projects'. One being the app src, and the other being the e2e tests. If you run ng lint --fix you will see an error that describes what I'm talking about.

**Comment by lucasklaassen** [comment] 2018-09-27 14:49
Duplicate of: https://github.com/angular/angular-cli/issues/11088

**Closed** 2018-09-27 17:20 UTC
Labels: comp: devkit/build-angular, freq2: medium, severity5: regression, type: bug/fix
