### ISSUE TITLE
mac os sierra 10.12.3 install fail

### ISSUE THREAD

**Issue by bboywulong** [angular/angular-cli#4548] opened 2017-02-09 02:29 UTC
> information:
> ---------------------------------------------------------------

### OS?
> Mac OS Sierra 10.12.3

### Versions.
> node v6.9.5
typescript@2.1.5
typings@2.1.0

### Repro steps.
> sudo npm install -g @angular/cli

### The log given by the failure.
> `RandyLees-MacBook-Pro:~ randylee$ sudo npm install -g @angular/cli
Password:
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! unpack Could not read data for @angular/tsc-wrapped@0.5.2
npm ERR! unpack Could not read data for @angular-cli/ast-tools@1.0.16
npm ERR! unpack Could not read data for @angular-cli/base-href-webpack@1.0.16
npm ERR! unpack Could not read data for @angular/compiler@2.4.6
npm ERR! unpack Could not read data for @angular/compiler-cli@2.4.6
npm ERR! unpack Could not read data for @angular/core@2.4.6
npm ERR! unpack Could not read data for @ngtools/json-schema@1.0.2
npm ERR! unpack Could not read data for @ngtools/webpack@1.2.8
npm ERR! unpack Could not read data for @angular/cli@1.0.0-beta.30
npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "@angular/cli"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@angular/tsc-wrapped"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/randylee/npm-debug.log`

> ---------------------------------------------------------------

**Comment by dhrubomoy** [comment] 2017-02-09 04:59
I am also getting similar error in mac OS Sierra 10.12 and node version is 7.5.0. I am getting following error after running `sudo npm install -g @angular/cli` :

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN gentlyRm not removing /Users/Dhrubo/.npm-global/bin/ng as it wasn't installed by /Users/Dhrubo/.npm-global/lib/node_modules/@angular/cli
/Users/Dhrubo/.npm-global/bin/ng -> /Users/Dhrubo/.npm-global/lib/node_modules/@angular/cli/bin/ng
/Users/Dhrubo/.npm-global/lib
└─┬ @angular/cli@1.0.0-beta.30 
  └── UNMET PEER DEPENDENCY rxjs@^5.0.1

npm WARN @angular/core@2.4.7 requires a peer of rxjs@^5.0.1 but none was installed.
```

**Comment by catull** [comment] 2017-02-09 13:21
This is a duplicate of #4530. Try the solution suggested there.

**Comment by filipesilva** [comment] 2017-02-09 13:54
@bboywulong you seem to have some proxy/firewall/npm version issue. You're not getting packages correctly.

@dhrubomoy yours is a dupe as catull said.

**Closed by filipesilva** 2017-02-09 13:54 UTC
