### ISSUE TITLE
ng github-pages:deploy getting Error - 'Command failed: git rm -r'

### ISSUE THREAD

**Issue by PottertheJavaOtter** [angular/angular-cli#3558] opened 2016-12-14 14:13 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> MacOS Sierra

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 6.7.0
os: darwin x64

### Repro steps.
> Created the app by using ng new <projName> --sytle=scss

### The log given by the failure.
> ➜  plus-side git:(master) ng github-pages:deploy
Hash: 1b1af12ffc0c72795f79                                               r Time: 20486ms
chunk    {0} main.22c20baba2abc41a3bda.bundle.js, main.22c20baba2abc41a3bda.bundle.map (main) 2 MB {2} [initial] [rendered]
chunk    {1} styles.b2328beb0372c051d06d.bundle.js, styles.d41d8cd98f00b204e9800998ecf8427e.bundle.css, styles.b2328beb0372c051d06d.bundle.map, styles.b2328beb0372c051d06d.bundle.map (styles) 69 bytes {2} [initial] [rendered]
chunk    {2} inline.d41d8cd98f00b204e980.bundle.js, inline.d41d8cd98f00b204e980.bundle.map (inline) 0 bytes [entry] [rendered]
Command failed: git rm -r
usage: git rm [<options>] [--] <file>...

    -n, --dry-run         dry run
    -q, --quiet           do not list removed files
    --cached              only remove from the index
    -f, --force           override the up-to-date check
    -r                    allow recursive removal
    --ignore-unmatch      exit with a zero status even if nothing matched

Error: Command failed: git rm -r
usage: git rm [<options>] [--] <file>...

    -n, --dry-run         dry run
    -q, --quiet           do not list removed files
    --cached              only remove from the index
    -f, --force           override the up-to-date check
    -r                    allow recursive removal
    --ignore-unmatch      exit with a zero status even if nothing matched

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

### Mention any other details that might be useful.
I havent done anything beside run ng github-pages:deploy and I had received this error

**Comment by wolfhoundjesse** [comment] 2016-12-14 17:06
There is a [fix to ignore errors](https://github.com/angular/angular-cli/commit/0a68cc5f152aea2773f8dcd95a86f70242f26499)

I tossed that `.catch()` statement into my github-pages-deploy.js, and everything worked as intended.

**Comment by PottertheJavaOtter** [comment] 2016-12-14 19:20
I tried it, and it seems to work. However I am getting a different issue with the pages now.

I am getting this issue:

Failed to load resource: the server responded with a status of 404 (Not Found) for several files when I go to the corresponding domain

**Comment by hansl** [comment] 2016-12-14 19:51
Not sure what that new error is but you should file a new issue for this with more details (though that looks like a configuration issue on your side, so not sure what we can do). 

Closing this as fixed (it will be published with the next release.

**Closed by hansl** 2016-12-14 19:51 UTC
