### ISSUE TITLE
Cannot read property 'debug' of undefined in Production code

### ISSUE THREAD

**Issue by s20sujith** [angular/angular-cli#14757] opened 2019-06-13 07:06 UTC
when i run production code 
browser shows me
 ```
Uncaught TypeError: Cannot read property 'debug' of undefined
    at Function.set (main.f367047a957d9be7d097.js:1)
    at new e (main.f367047a957d9be7d097.js:1)
    at main.f367047a957d9be7d097.js:1
    at Jh (main.f367047a957d9be7d097.js:1)
    at main.f367047a957d9be7d097.js:1
    at new e (main.f367047a957d9be7d097.js:1)
    at Object.Cf [as createNgModuleRef] (main.f367047a957d9be7d097.js:1)
    at t.create (main.f367047a957d9be7d097.js:1)
    at main.f367047a957d9be7d097.js:1
    at n.invoke (polyfills.c6871e56cb80756a5498.js:1)
```

### package.json
```json
{
"dependencies": {
    "@angular/animations": "angular/animations-builds",
    "@angular/cdk": "angular/cdk-builds",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/material": "angular/material2-builds",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "@ngrx/effects": "^7.0.0",
    "@ngrx/router-store": "^7.0.0",
    "@ngrx/store": "^7.0.0",
    "@ngrx/store-devtools": "^7.0.0",
    "ag-grid-angular": "^19.1.2",
    "ag-grid-community": "^19.1.4",
    "angular-tree-component": "^8.4.0",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "ng2-search-filter": "^0.4.7",
    "ngx-filter-pipe": "^2.1.2",
    "oidc-client": "^1.6.0",
    "rxjs": "~6.3.3",
    "sweetalert": "^2.1.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.3",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.130",
    "@types/node": "~8.9.4",
    "browser-sync": "^2.26.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
```

**Comment by filipesilva** [comment] 2019-06-13 09:23
I think you're having some weird errors and can't debug it, and so, understandably, you're frustrated. But this is a tracker for bugs and feature requests. If we can we also try to help with support requests. We're very lucky to have awesome community members that also spend time trying to help people here in the issue tracker.

But we can't really help much at all if you don't fill in the issue template. I read your issue and have no idea what's going wrong and how to help you. And when other users search the issue tracker and see your issue, it also doesn't help them.

So I think the best thing to do is to close this issue, and ask you to open a new one. In that new one please fill in the issue template and give us an idea of what's happening and how to reproduce it. That way we'll have a chance to help you.

**Closed by filipesilva** 2019-06-13 09:23 UTC

**Comment by MikeKovetsky** [comment] 2019-07-31 16:25
@s20sujith I am getting this error from time to time in both production and development modes. Did you manage to find the reason? Thank you

**Comment by MikeKovetsky** [comment] 2019-07-31 16:30
The Angular frontend seems to stuck during state transfer process from Angular Universal. The browser version of application does not initiate and the ssr page is shown. Stack trace:
`
Uncaught TypeError: Cannot read property 'debug' of undefined
    at HTMLDocument.<anonymous> (80-init.js:429)
    at t.invokeTask (polyfills.8c23c0915d0cd55b66f9.js:formatted:4130)
    at n.runTask (polyfills.8c23c0915d0cd55b66f9.js:formatted:3959)
    at n.invokeTask [as invoke] (polyfills.8c23c0915d0cd55b66f9.js:formatted:4190)
    at b (polyfills.8c23c0915d0cd55b66f9.js:formatted:5010)
    at HTMLDocument.m (polyfills.8c23c0915d0cd55b66f9.js:formatted:5024)`

Probably, some problems with zone.
