### ISSUE TITLE
Angular-cli@1.0.0-beta.11-webpack.2 BUG - relative components generation

### ISSUE THREAD

**Issue by razordesign** [angular/angular-cli#1714] opened 2016-08-16 12:04 UTC
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 x64

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli@1.0.0-beta.11-webpack.2
node 5.9.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
STEP1. Write "ng new APPNAME"
STEP2. Write "ng g component Component1" //this command ignores uppercase letter on Component1 - that's the first bug
STEP3. get into the dir of that component1 by "cd src" -> "cd app" -> "cd component1"
STEP4. Write "ng g component Component1Child1"
STEP5. ng build -watch 

4. The log given by the failure. Normally this include a stack trace and some
   more information.
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './component1component1child1/component1child1.component' 

5. Mention any other details that might be useful.
When you enter app.module.ts you see that the path for Component1Child1 looks like that:
import { Component1Child1Component} from './component1**\**component1child1/component1child1.component';

As you can see the slash is wrong way. It inserted this "\" instead of "/". After fixing that the app works well. It's just a typo that is being generated every time you generate component inside of another component.

**Comment by MrCroft** [comment] 2016-08-21 11:22
Yup,

While already in the app folder:
1. `mkdir src/app/layout`
2. `ng generate component layout/header`

Now, if you check **app.module.ts**, the import statement added by the CLI looks like this:
`import { HeaderComponent } from './layout\header/header.component';` - notice the second slash in the path is a backslash.
I have to go in app.module.ts and replace the backslash with forward-slash myself.
Otherwise, `ng build` fails with: "Cannot find module './layoutheader/header.component'." (initially I would have expected it to treat the backslash the same like a regular "/" slash in a path, but it doesn't).

```
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.4.0
os: win32 x64
```

**Comment by filipesilva** [comment] 2016-08-23 14:16
Dupe of https://github.com/angular/angular-cli/issues/1719

**Closed by filipesilva** 2016-08-23 14:16 UTC
