### ISSUE TITLE
ng help generate does not show the list of blueprints

### ISSUE THREAD

**Issue by denofevil** [angular/angular-cli#2564] opened 2016-10-07 09:26 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
macOS

### Versions.
angular-cli: 1.0.0-beta.16
node: 6.7.0
os: darwin x64

### Repro steps.
1. Generate app with angular-cli
2. Run ng help generate
3. Generic help will be generated, no blueprints listing

### The log given by the failure.
```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ng build <options...>
  Builds your app and places it into the output path (dist/ by default).
  aliases: b
  --target (String) (Default: development)
    aliases: -t <value>, -dev (--target=development), -prod (--target=production)
  --environment (String) (Default: )
    aliases: -e <value>
  --output-path (Path) (Default: null)
    aliases: -o <value>
  --watch (Boolean) (Default: false)
    aliases: -w
  --watcher (String)
  --suppress-sizes (Boolean) (Default: false)
  --base-href (String) (Default: null)
    aliases: -bh <value>
  --aot (Boolean) (Default: false)

ng doc <keyword>
  Opens the official Angular documentation for a given keyword.

ng e2e
  Run e2e tests in existing project

ng generate <blueprint> <options...>
  Generates new code from blueprints.
  aliases: g
  --dry-run (Boolean) (Default: false)
    aliases: -d
  --verbose (Boolean) (Default: false)
    aliases: -v
  --pod (Boolean) (Default: false)
    aliases: -p
  --classic (Boolean) (Default: false)
    aliases: -c
  --dummy (Boolean) (Default: false)
    aliases: -dum, -id
  --in-repo-addon (String) (Default: null)
    aliases: --in-repo <value>, -ir <value>

ng get
  Get a value from the configuration.

ng init <glob-pattern> <options...>
  Creates a new angular-cli project in the current folder.
  aliases: i
  --dry-run (Boolean) (Default: false)
    aliases: -d
  --verbose (Boolean) (Default: false)
    aliases: -v
  --blueprint (String)
    aliases: -b <value>
  --link-cli (Boolean) (Default: false)
    aliases: -lc
  --skip-npm (Boolean) (Default: false)
    aliases: -sn
  --skip-bower (Boolean) (Default: true)
    aliases: -sb
  --name (String) (Default: )
    aliases: -n <value>
  --source-dir (String) (Default: src)
    aliases: -sd <value>
  --style (String) (Default: css)
  --prefix (String) (Default: app)
    aliases: -p <value>
  --mobile (Boolean) (Default: false)
  --routing (Boolean) (Default: false)

ng lint
  Lints code in existing project

ng new <options...>
  Creates a new directory and runs ng init in it.
  --dry-run (Boolean) (Default: false)
    aliases: -d
  --verbose (Boolean) (Default: false)
    aliases: -v
  --blueprint (String) (Default: ng2)
    aliases: -b <value>
  --link-cli (Boolean) (Default: false)
    aliases: -lc
  --skip-npm (Boolean) (Default: false)
    aliases: -sn
  --skip-bower (Boolean) (Default: true)
    aliases: -sb
  --skip-git (Boolean) (Default: false)
    aliases: -sg
  --directory (String)
    aliases: -dir <value>
  --source-dir (String) (Default: src)
    aliases: -sd <value>
  --style (String) (Default: css)
  --prefix (String) (Default: app)
    aliases: -p <value>
  --mobile (Boolean) (Default: false)
  --routing (Boolean) (Default: false)

ng serve <options...>
  Builds and serves your app, rebuilding on file changes.
  aliases: server, s
  --port (Number) (Default: 4200)
    aliases: -p <value>
  --host (String) (Default: localhost) Listens on all interfaces by default
    aliases: -H <value>
  --proxy-config (Path)
    aliases: -pc <value>
  --watcher (String) (Default: events)
    aliases: -w <value>
  --live-reload (Boolean) (Default: true)
    aliases: -lr
  --live-reload-host (String) Defaults to host
    aliases: -lrh <value>
  --live-reload-base-url (String) Defaults to baseURL
    aliases: -lrbu <value>
  --live-reload-port (Number) (Defaults to port number within [49152...65535])
    aliases: -lrp <value>
  --live-reload-live-css (Boolean) (Default: true) Whether to live reload CSS (default true)
  --target (String) (Default: development)
    aliases: -t <value>, -dev (--target=development), -prod (--target=production)
  --environment (String) (Default: )
    aliases: -e <value>
  --ssl (Boolean) (Default: false)
  --ssl-key (String) (Default: ssl/server.key)
  --ssl-cert (String) (Default: ssl/server.crt)
  --aot (Boolean) (Default: false)

ng set <options...>
  Set a value in the configuration.
  --global (Boolean) (Default: false)
    aliases: -g

ng test <options...>
  Runs your app's test suite.
  aliases: t
  --watch (Boolean) (Default: true)
    aliases: -w
  --browsers (String)
  --colors (Boolean)
  --log-level (String)
  --port (Number)
  --reporters (String)
  --build (Boolean) (Default: true)

ng version <options...>
  outputs angular-cli version
  aliases: v, --version, -v
  --verbose (Boolean) (Default: false)
```

Expecting something like:
```
(node:113) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Requested ember-cli commands:

ng generate <blueprint> <options...>
  Generates new code from blueprints.
  aliases: g
  --dry-run (Boolean) (Default: false)
    aliases: -d
  --verbose (Boolean) (Default: false)
    aliases: -v
  --pod (Boolean) (Default: false)
    aliases: -p
  --classic (Boolean) (Default: false)
    aliases: -c
  --dummy (Boolean) (Default: false)
    aliases: -dum, -id
  --in-repo-addon (String) (Default: null)
    aliases: --in-repo <value>, -ir <value>


  Available blueprints:
    ng2:
      class <class-type>
      component <name> <options...>
        --flat (Boolean) (Default: false)
        --route (Boolean) (Default: false)
        --inline-template (Boolean) (Default: false)
          aliases: -it
        --inline-style (Boolean) (Default: false)
          aliases: -is
        --prefix (Boolean) (Default: true)
      component-test <name>
      directive <name> <options...>
        --flat (Boolean) (Default: true)
      enum <name>
      interface <interface-type>
      mobile <name> <options...>
        --source-dir (String) (Default: src)
          aliases: -sd <value>
        --prefix (String) (Default: app)
          aliases: -p <value>
        --mobile (Boolean) (Default: false)
      model <name> <attr:type>
        Generates an ng-data model.
      ng2 <name> <options...>
        --source-dir (String) (Default: src)
          aliases: -sd <value>
        --prefix (String) (Default: app)
          aliases: -p <value>
        --style (String) (Default: css)
        --mobile (Boolean) (Default: false)
      pipe <name> <options...>
        --flat (Boolean) (Default: true)
      route <name>
      route-test <name>
      service <name> <options...>
        --flat (Boolean) (Default: true)
      service-test <name>
    angular-cli:
      acceptance-test <name>
        Generates an acceptance test for a feature.
      adapter <name> <options...>
        Generates an ng-data adapter.
        --base-class (String)
      adapter-test <name>
        Generates an ng-data adapter unit test
      addon <name>
        The default blueprint for angular-cli addons.
      addon-import <name>
        Generates an import wrapper.
      app <name>
        The default blueprint for angular-cli projects.
      blueprint <name>
        Generates a blueprint and definition.
      component-addon <name>
        Generates a component. Name must contain a hyphen.
      controller <name>
        Generates a controller.
      controller-test <name>
        Generates a controller unit test.
      helper <name>
        Generates a helper function.
      helper-addon <name>
        Generates an import wrapper.
      helper-test <name>
        Generates a helper unit test.
      http-mock <endpoint-path>
        Generates a mock api endpoint in /api prefix.
      http-proxy <local-path> <remote-url>
        Generates a relative proxy to another server.
      in-repo-addon <name>
        The blueprint for addon in repo angular-cli addons.
      initializer <name>
        Generates an initializer.
      initializer-addon <name>
        Generates an import wrapper.
      initializer-test <name>
        Generates an initializer unit test.
      instance-initializer <name>
        Generates an instance initializer.
      instance-initializer-addon <name>
        Generates an import wrapper.
      instance-initializer-test <name>
        Generates an instance initializer unit test.
      lib <name>
        Generates a lib directory for in-repo addons.
      mixin <name>
        Generates a mixin.
      mixin-test <name>
        Generates a mixin unit test.
      model-test <name>
        Generates a model unit test.
      resource <name>
        Generates a model, template, route, and registers the route with the router.
      route-addon <name>
        Generates import wrappers for a route and its template.
      serializer <name>
        Generates an ng-data serializer.
      serializer-test <name>
        Generates a serializer unit test.
      server <name>
        Generates a server directory for mocks and proxies.
      template <name>
        Generates a template.
      test-helper <name>
        Generates a test helper.
      transform <name>
        Generates an ng-data value transform.
      transform-test <name>
        Generates a transform unit test.
      util <name>
        Generates a simple utility module/function.
      util-test <name>
        Generates a util unit test.
      vendor-shim <name>
        Generates an ES6 module shim for global libraries.
```

### Mention any other details that might be useful.
WebStorm uses this infomartion to provide list of the things that you can generate. If there's another way to list templates, we can use it instead. cc @hansl 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by arlowhite** [comment] 2016-10-07 17:39
Version: 

> angular-cli: 1.0.0-beta.16
> node: 6.3.1
> os: linux x64

ng help isn't working for other commands either, for example `ng help serve`
(prints entire help page instead of just serve help)

`ng` indicates this should work:

> ng help <command-name (Default: all)> <options...>
>   Outputs the usage instructions for all commands or the provided command
>   aliases: h, --help, -h
>   --verbose (Boolean) (Default: false)
>     aliases: -v
>   --json (Boolean) (Default: false)
>

**Comment by filipesilva** [comment] 2016-10-10 02:18
Dupe of https://github.com/angular/angular-cli/issues/2300, fixed in https://github.com/angular/angular-cli/pull/2580

**Closed by filipesilva** 2016-10-10 02:18 UTC
