### ISSUE TITLE
Route abnormal behavior using ng serve with proxy

### ISSUE THREAD

**Issue by Bulinlinbu** [angular/angular-cli#9072] opened 2018-01-03 10:37 UTC
### Versions
```
Angular CLI: 1.6.3
Node: 9.3.0
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
Create an empty project, with 2 components Page1Component & Page2Components.
In app.modules.ts create routes like this : 
```
import { Routes, RouterModule } from "@angular/router";
const routes: Routes = [
  { path: '', component: Page1Component },
  { path: 'page2', component: Page2Component }
 ];
```
and add "RouterModule.forRoot(routes)" into imports.

app.component.html replace content with :
```
<a href="page2">Goto Page 2</a>
<router-outlet></router-outlet>
```

create proxy.conf.json to map with a apache / nginx / custom webserver (in my case) / local webserver which root is you src repo : 
```
{
  "/": {
    "target": "http://localhost",
    "secure": false,
    "logLevel": "debug"
  }
}
```

### Observed behavior
Case 1 : working
>ng serve
You can see "page1 works"
Click on link "Goto Page 2"
Browser goes to "http://127.0.0.1:4300/page2" and displays "page2 works".

Press F5 to reload : works fine

Case 2 : not working
>ng serve --proxy-config proxy.conf.json
You can see "page1 works"
Click on link "Goto Page 2"
Browser goes to "http://127.0.0.1:4300/page2" and get 404

Notice that console display this : [HPM] GET /page2 -> http://localhost
It's not normal : angular shoudn't call page2 as a resource but should detect it as route.

### Desired behavior
ng serve should works in the same way with / without proxy

**Comment by BramVM** [comment] 2018-01-11 12:30
I got the same problem for refreshing a page using ng serve --proxy ... . I think the display message isn't showing you the page being requested. In my case the display message only displays my data calls.

**Comment by BramVM** [comment] 2018-01-11 13:09
Got it fixed by changing my api url's to start with prefix "api/" and specifying the proxy-setting to this prefix.
`{
  "/api/**": {
    "target": "http://localhost",
    "secure": false,
    "logLevel": "debug"
  }
}`

I think the the proxy settings mess with the angular server rules. (Since angular is a single page application its redirecting other http calls to index)

**Comment by Bulinlinbu** [comment] 2018-01-13 08:56
Yeah ! It works for me too with "/api/**" instead of "/"

But why "api" and not "catapult' or "titicaca" ?

One point : if you have some "pathRewrite" rule in proxy conf, you must create anoter rule, because every external path is redirected to index.html

**Comment by tmburnell** [comment] 2018-02-07 16:31
I have been using proxy configs for quite some time mine look like this:
```
"/api": { "target": "http://localhost:4300", "secure": false },
"/authenticate": { "target": "http://localhost:4300", "secure": false },
"/logout": { "target": "http://localhost:4300", "secure": false }
```
because I run a either a node server or a springboot server on another port.  All API calls are routed through an `api/v#/...` path.
However it is true that any exceptions would have to be put here like my login and logout.

So I was actually surprised to even see that page1 loaded in the provided example because i would have though proxy should have routed the request to your other url.

**Comment by filipesilva** [comment] 2019-01-28 16:21
Thanks for reporting this issue. This issue was originally reported a long time ago and since there we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by filipesilva** 2019-01-28 16:21 UTC
Labels: comp: devkit/build-angular

**Comment by nhhockeyplayer** [comment] 2019-02-12 13:00
What happens if your backend server is prefixed by name api
AND
your angular app is named api

Will this produce a proxy path conflict? Is angular smart enough?

**Comment by efagerberg** [comment] 2019-04-22 14:53
Hey folks I see the proxy behavior does not work with `/` either. My case might be rare, but we have this app that uses an express backend. The main gripe we have with just using an angular server is that it is not the same as running our actual express server. So we want to proxy all the requests to the backend.

A big reason we want to do this is because it also puts in place out template engine which injects a new relic api call in the head of every page. Without this engine setup we get this string at the top of each page.
<img width="473" alt="Screen Shot 2019-04-22 at 10 52 44 AM" src="https://user-images.githubusercontent.com/7632073/56506528-c9127400-64ec-11e9-869f-ad79f26a1cb6.png">

Fundamentally I think our approach is we want the code in development to reflect what we deploy in production, while having an ideal hot reloading setup to iterate on components.
Would love to hear thoughts on this use case as it does seem slightly different than just wanting to proxy an API, but to proxy all the angular requests to a backend.
