### ISSUE TITLE
Support "export * as ns from 'some-module'"

### ISSUE THREAD

**Issue by maroon1** [angular/angular-cli#19500] opened 2020-11-29 06:33 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Support [ECMAScript Proposal: export ns from](https://github.com/tc39/proposal-export-ns-from)

For now, it will throw a SyntaxError during compiling.

```text
Module parse failed: Unexpected token (1:9)
File was processed with these loaders:
 * ./node_modules/@ngtools/webpack/src/index.js
You may need an additional loader to handle the result of these loaders.
> export * as Form from './form';
```

**Comment by alan-agius4** [comment] 2020-11-29 08:04
Duplicate of https://github.com/angular/angular-cli/issues/17231#issuecomment-709372331

**Closed by alan-agius4** 2020-11-29 08:04 UTC
