### ISSUE TITLE
AoT compilation not working

### ISSUE THREAD

**Issue by scarmarco** [angular/angular-cli#2882] opened 2016-10-25 14:04 UTC
I'm getting this error everytime I build/serve with --aot option.

https://github.com/angular/angular/issues/9663 Same issue like this, but on Sierra.

> ng serve --aot
> Looks like you have a different program called watchman, falling back to NodeWatcher.
> Visit http://ember-cli.com/user-guide/#watchman for more info.
> can't resolve module @angular/core/src/di/opaque_token from /Users/.../src/index.ts
> Cannot read property 'parse' of undefined
> TypeError: Cannot read property 'parse' of undefined
>     at ReflectorHost.normalizeAssetUrl (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/reflector_host.ts:70:28)
>     at ReflectorHost.findDeclaration (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/reflector_host.ts:175:27)
>     at StaticReflector.initializeConversionMap (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:185:34)
>     at new StaticReflector (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:72:57)
>     at AotPlugin._setupOptions (/.../node_modules/@ngtools/webpack/src/plugin.js:122:27)
>     at new AotPlugin (/.../node_modules/@ngtools/webpack/src/plugin.js:34:14)
>     at Object.exports.getWebpackAotConfigPartial (/Users/marco/Documents/github/v4/node_modules/angular-cli/models/webpack-build-typescript.js:57:13)
>     at new NgCliWebpackConfig (/.../node_modules/angular-cli/models/webpack-config.js:18:42)
>     at Class.run (/.../node_modules/angular-cli/tasks/serve-webpack.js:21:22)
>     at /.../node_modules/angular-cli/commands/serve.js:92:26
>     at process._tickCallback (internal/process/next_tick.js:103:7)
> ---
### OS?

> Mac OSX Sierra
### Versions.

> angular-cli: 1.0.0-beta.18
> node: 6.9.1
> os: darwin x64

**Comment by inska** [comment] 2016-10-26 06:55
Similar here.
Which version do you using Typescript? 2.1.0 dev?

**Comment by nukuuk** [comment] 2016-10-26 09:27
same here

**Comment by simonh1000** [comment] 2016-10-26 11:02
Same here
angular-cli: 1.0.0-beta.18
node: 6.3.1
os: darwin x64
```
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "latest",
    "codelyzer": "~1.0.0-beta.0",
    "deep-freeze": "0.0.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.7.0",
    "karma": "1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.4.0",
    "tslint": "3.15.1",
    "typescript": "2.0.3"
  }
```

**Comment by mdmitriy** [comment] 2016-10-26 13:51
Have the same
angular-cli: 1.0.0-beta.18
node: v6.9.1
os: Linux Mint 18

**Comment by zackarychapple** [comment] 2016-10-26 14:55
Try dumping node modules and installing again. I didn't run into this issue with the same OS and versions.

**Comment by simonh1000** [comment] 2016-10-26 15:22
Didn't fix it for me

**Comment by wachh** [comment] 2016-10-26 16:25
having the same issue on Ubuntu

**Comment by simonh1000** [comment] 2016-10-26 17:07
Out of the blue, it started compiling again, although the subsequent code crashed

![screen shot 2016-10-26 at 19 06 02](https://cloud.githubusercontent.com/assets/5256724/19736377/4aefcd7e-9baf-11e6-9401-3814eff85a4d.png)

**Comment by scarmarco** [comment] 2016-10-26 19:41
> Try dumping node modules and installing again. I didn't run into this issue with the same OS and versions.

Tried that, no success :(

> Which version do you using Typescript? 2.1.0 dev?

I'm on Typescript 2.0.2

> I upgraded everything (ncu -u) and reinstalled. Compilation now completes, but with an error midway

Do you mind explain exactly what you did?

**Dependencies for better context**

[Project dependencies](http://pastebin.com/raw/QfsqFY5g)

**Comment by wachh** [comment] 2016-10-26 23:02
I used npm-check-updates to update all my dependencies and the issue is gone. However I ran into this other issue #2452

**Comment by scarmarco** [comment] 2016-10-27 00:38
@wachh Ok it worked!

Now I'm getting:

> Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol SharedModule in /Users/.../src/app/shared/shared.module.ts, resolving symbol SharedModule in /Users/.../src/app/shared/shared.module.ts

Any ideas, I found some stuff on other issues, but already fix what it seems to be fix and still getting it.

**Comment by Destreyf** [comment] 2016-10-30 08:18
@scarmarco Compile without the aot flag, you'll find you have an error in your code (or a dependency) that is causing aot to get stuck.

**Comment by filipesilva** [comment] 2016-11-03 16:33
Closing since it seems like an Angular Compiler bug itself, as reported on angular/angular#9663.

**Closed by filipesilva** 2016-11-03 16:33 UTC
