### ISSUE TITLE
favicon not being deployed/displayed

### ISSUE THREAD

**Issue by peterennis** [angular/angular-cli#2232] opened 2016-09-19 21:35 UTC
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Peter Ennis>ng version
angular-cli: 1.0.0-beta.14
node: 6.6.0
os: win32 x64

I have tried a number of options in the index.html file to get
the favicon showing but without success.

The localhost site and direct github link show the favicon.

The site is a masked redirect from godaddy to github gh-pages
using the ng github-pages:deploy

Some examples of favicon testing that fail, but have worked in the past
with other deploy methods:

```
<head>
  <meta charset="utf-8">
  <title>Adaept</title>
  <base href="/adaept/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="https://adaept.github.io/adaept/favicon.ico">
  <!-- <link rel="icon" sizes="16x16 32x32" href="favicon.ico?v=2">
       <link rel="icon" type="image/x-icon" href="favicon.ico"> -->
```

When I look in the dist folder and parent there is no favicon.ico file available to be deployed.

Does the file have to be manually copied? I would expect deploy to take care of this.

![capture68](https://cloud.githubusercontent.com/assets/140737/18649666/994b7a2e-7e75-11e6-8cb0-854587a6f622.PNG)

**Comment by jbeckton** [comment] 2016-09-19 23:20
I had to put mine in the assets folder and change the path in the index.html

**Comment by peterennis** [comment] 2016-09-20 01:42
I could not find any assets folder in the system. Starting with new ...
Here: https://github.com/angular/angular-cli/issues/713
is another reference from @ustaDAH

**Comment by peterennis** [comment] 2016-09-20 01:49
This also seems related: https://github.com/angular/angular-cli/issues/2202

**Comment by jbeckton** [comment] 2016-09-20 20:28
You have to create an assets folder in your src folder. By convention the CLI will copy it for you to /dist

**Comment by ustaDAH** [comment] 2016-09-21 17:24
@jbeckton @peterennis yes that worked.

**Comment by pauldubois777** [comment] 2016-09-21 18:15
How do we find out if the team still wants to have the favicon.ico file copied during build?  
It appears this might have been lost in [Pull Request 2056 ](https://github.com/angular/angular-cli/pull/2056)

If it should still do this, I think the following will fix it...

In packages\angular-cli\models\webpack-build-common.ts update the plugins object to include a copy of the favicon.ico file:
```
      new CopyWebpackPlugin([
        {
          context: path.resolve(appRoot, appConfig.assets),
          from: { glob: '**/*', dot: true },
          ignore: [ '.gitkeep' ],
          to: path.resolve(projectRoot, appConfig.outDir, appConfig.assets)
        }, {
>>        from: path.resolve(projectRoot, appConfig.root, 'favicon.ico'),
>>        to: path.resolve(projectRoot, appConfig.outDir)
        }
      ])
```

Paul

**Comment by nmorado** [comment] 2016-09-21 19:20
This works! Thanks

**Comment by filipesilva** [comment] 2016-09-22 01:07
Dupe of https://github.com/angular/angular-cli/issues/2137

**Closed by filipesilva** 2016-09-22 01:07 UTC

**Comment by ustaDAH** [comment] 2016-09-22 13:56
I'd be tempted to rather have favicon.ico in the assets folder and change the url in the index.html accordingly. (And of course also change `ng new ...` to generate seed sources as such).

**Comment by JScafidi616** [comment] 2018-02-21 18:13
It Works! Thanks!
