### ISSUE TITLE
$$_gendir/app/app.module.ngfactory.ts doesn't exist

### ISSUE THREAD

**Issue by antonybudianto** [angular/angular-cli#3761] opened 2016-12-28 01:50 UTC
### OS?
> El Capitan

### Versions.
Not using CLI, but ngtools/webpack
"@ngtools/webpack": "1.2.1"

Node 7.2.0
npm 4.0.3

### Repro steps.
Clone
https://github.com/antonybudianto/angular-hackathon-starter.git

checkout to `update-up` branch

Change skipCodeGeneration to `false` (**yes, skipping code generation will run well**)
https://github.com/antonybudianto/angular-hackathon-starter/commit/3e3ca623d6d22fd246164b78d74c1128c125b6be#diff-a46fd1ee64f763b8b5abfae3b5543f28R35

```
npm install

npm run build
```

### The log given by the failure.

```
10% building modules 4/4 modules 0 activeError                                    
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/webpack/lib/Compilation.js:233:38
    at onDoneResolving (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/webpack/lib/NormalModuleFactory.js:40:20)
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/webpack/lib/NormalModuleFactory.js:117:20
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/webpack/node_modules/async/dist/async.js:3694:9
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/webpack/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/webpack/node_modules/async/dist/async.js:934:13)
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/webpack/node_modules/async/dist/async.js:840:16
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/webpack/node_modules/async/dist/async.js:3691:13
    at apply (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/webpack/node_modules/async/dist/async.js:21:25)
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/webpack/node_modules/async/dist/async.js:56:12
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/webpack/lib/NormalModuleFactory.js:112:22
    at onResolved (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/tapable/lib/Tapable.js:145:46)
    at innerCallback (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/tapable/lib/Tapable.js:247:15
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:39:4
    at loggingCallbackWrapper (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/tapable/lib/Tapable.js:145:46)
    at innerCallback (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/tapable/lib/Tapable.js:247:15
    at innerCallback (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/antony/Documents/Code/Web/angular-hackathon-starter/node_modules/tapable/lib/Tapable.js:247:15
resolve './$$_gendir/app/app.module.ngfactory' in '/Users/antony/Documents/Code/Web/angular-hackathon-starter/src'
  using description file: /Users/antony/Documents/Code/Web/angular-hackathon-starter/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/antony/Documents/Code/Web/angular-hackathon-starter/package.json (relative path: ./src)
    using description file: /Users/antony/Documents/Code/Web/angular-hackathon-starter/package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      as directory
        /Users/antony/Documents/Code/Web/angular-hackathon-starter/src/$$_gendir/app/app.module.ngfactory doesn't exist
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/antony/Documents/Code/Web/angular-hackathon-starter/src/$$_gendir/app/app.module.ngfactory doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/antony/Documents/Code/Web/angular-hackathon-starter/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/antony/Documents/Code/Web/angular-hackathon-starter/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist
 10% building modules 4/6 modules 2 active ...ter/node_modules/zone.js/dist/zone.js
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JonasPHess** [comment] 2016-12-28 15:57
Same Problem here

**Comment by antonybudianto** [comment] 2016-12-30 05:12
Looks like angularfire2 issue, but the point is, the error stack of angularfire2 didn't show up here

**Comment by filipesilva** [comment] 2016-12-30 21:11
Dupe of https://github.com/angular/angular-cli/issues/3691 it seems. I'll mention there that it's likely related to angularfire2.

**Closed by filipesilva** 2016-12-30 21:11 UTC
