### ISSUE TITLE
Module is updated even if -d

### ISSUE THREAD

**Issue by nickelas** [angular/angular-cli#7034] opened 2017-07-18 14:12 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.2
node: 8.1.2
os: linux x64
@angular/animations: 4.3.0
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.1.2
@angular/compiler-cli: 4.3.0
@angular/language-service: 4.3.0

Ubuntu 

### Repro steps.

ng g m m1 -m app.module.ts -d

### Desired functionality.

The specified module should probably not be updated when using --dry-run

### Mention any other details that might be useful.
I think it only happens on modules and when using the -m flag

**Comment by filipesilva** [comment] 2017-07-28 15:01
Duplicate of https://github.com/angular/angular-cli/issues/6810, it is being tracked there.

**Closed by filipesilva** 2017-07-28 15:01 UTC
