### ISSUE TITLE
Allow to load the bundle and asset files with specefic query parameters in addition of output hashing 

### ISSUE THREAD

**Issue by icecoldfire** [angular/angular-cli#22197] opened 2021-11-19 08:30 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

The only solution now against caching problems are using the output hashing option when building the project. We propose an additional option that allows to load the files with an unique query parameter. This is an effective solution against the following problems that can occur:

#### Cached index.html file with old bundle files removed
When an user loads the page with an cached index.html file it will try to load also the old assets files. These are default hashed in the following pattern `<bundle_name>.<hash>.js`. The server will that respond with an 404 because these files are removed and can't be served. This is an ongoing issue because of lazy loading not all bundle files are loaded at the first page view.

#### New index.html file with old bundle files partially cached
Almost the same problem described as above but we have noticed that in some conditions the browsers is loading the new index.html and javascript files but still is caching the css files.

### Describe the solution you'd like

We would like to have an option to allow to set an custom query parameter when loading the files. When output hashing is set on `none` the file name should be in these form: `<bundle_name>.js` but the file should be loading using an GET request in the following format: `<bundle_name>.js?<version_number>`.

You will see that this is an addition to output hasing because you can also have the following file name `<bundle_name>.<hash>.js` and loading the file in the following way: `<bundle_name>.<hash>.js?<version_number>`

### Describe alternatives you've considered
Using other caching control options but this doesn't complete solve the problem.

**Comment by alan-agius4** [comment] 2021-11-19 09:41
Hi @icecoldfire, 

Thanks for this feature request. I want to point out a couple of things in regards to what you mentioned above. 

> Cached index.html file with old bundle files removed

It is recommend you use `Cache-Control: no-cache` for the index file. Adding “no-cache” doesn't mean that the file is not to be cached, but rather it tells the browser to validate resources on the server before use it from the cache. This is were `Etags` come into play.

> New index.html file with old bundle files partially cached

I am not following, if the bundles are different due to the hash in the filename, how can these be served from cache when there is a new release?

To adding to your proposed solution, using a hash in the query doesn't come with its' own caveats and in general this pattern is not recommended. Let's imagine a use-case:

- The users open your application versioned `123`, `main.js?123`
- Users leaves the application open
- The new version of the application is published with version `456`
- Users requests another lazy loaded module lazy?123`
- Application crashes during runtime likely with a cryptic error because `lazy-2` now contains code which is not compatible with version 123 due to the changes done in version `456`.

Typically, these use-cases can be mitigated by using a CDN wether public or a private one. CDNs will cache the files for a  a certain period of time until they are not longer requested or the TTL expires, even when they are purged from origin.

**Comment by alan-agius4** [comment] 2021-11-19 13:32
>  I don't need to explain to you that in corporate infrastructure wrong configured reverse proxies or servers are not uncommon.

I am sorry but in this case, this should be raised and fixed at the root cause, ie internally in your corporate proxy and it shouldn't be expected that the Angular CLI will implement workarounds that will need to be supported for the years to come. Implementing such feature may seem trivial, but this will need to be documented, supported and maintained which will can take a lot of effort.

> In our understanding is that hashes only change when the files are edited. So when an file has the same output it would have the same hash? This can lead that some files are cached but not all.

Correct, but in which case the cached file will be retrieved from cache and uncached files will be retrieved from the origin.

**Comment by alan-agius4** [comment] 2021-11-23 10:21
Closing as per above.

**Closed by alan-agius4** 2021-11-23 10:21 UTC
