### ISSUE TITLE
Compilation crash: `Error: Content and Map of this Source is not available (only size() is supported)`

### ISSUE THREAD

**Issue by andreialecu** [angular/angular-cli#22237] opened 2021-11-26 14:09 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build
- [x] serve

### Is this a regression?

Yes, didn't see this with Angular 12.

### Description

I'm running into `Error: Content and Map of this Source is not available (only size() is supported) with Angular.`

This seems to have been reported in various other places recently:
[stackoverflow.com/questions/70066980/angular-12-content-and-map-of-this-source-is-not-available-only-size-is-suppo
](https://stackoverflow.com/questions/70066980/angular-12-content-and-map-of-this-source-is-not-available-only-size-is-suppo)

I'm not sure if this is an Angular or Webpack issue, I also crossposted this to webpack: https://github.com/webpack/webpack/issues/14840

## 🔬 Minimal Reproduction

I don't have a clear reproduction, however I was able to add some logs in `emitAsset` here, which is part of the stack trace:
https://github.com/webpack/webpack/blob/14582fc41504595b04f01561ea19d27391d6b9ac/lib/Compilation.js#L4171-L4176

I added:

```js
	emitAsset(file, source, assetInfo = {}) {
		if (this.assets[file]) {
			try {
				!isSourceEqual(this.assets[file], source);
			} catch (err) {
				console.error(file, this.assets[file], source);
				throw err;
			}
```

The output before the crash is:

```
fontawesome-webfont.eot SizeOnlySource { _size: 165742 } RawSource {
  _valueIsBuffer: true,
  _value: <Buffer 6e 87 02 00 ac 86 02 00 01 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 90 01 00 00 00 00 4c 50 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 165692 more bytes>,
  _valueAsBuffer: <Buffer 6e 87 02 00 ac 86 02 00 01 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 90 01 00 00 00 00 4c 50 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 165692 more bytes>,
  _valueAsString: undefined
}
```

It always seems to crash on the same `eot` file. Notice that `this.assets[file]` for this file is a `SizeOnlySource`.

## 🔥 Exception or Error

```
.../node_modules/webpack-sources/lib/SizeOnlySource.js:16
                return new Error(
                       ^

Error: Content and Map of this Source is not available (only size() is supported)
    at SizeOnlySource._error (.../node_modules/webpack-sources/lib/SizeOnlySource.js:16:10)
    at SizeOnlySource.buffer (.../node_modules/webpack-sources/lib/SizeOnlySource.js:30:14)
    at _isSourceEqual (.../node_modules/webpack/lib/util/source.js:21:51)
    at isSourceEqual (.../node_modules/webpack/lib/util/source.js:43:17)
    at Compilation.emitAsset (.../node_modules/webpack/lib/Compilation.js:4155:9)
    at .../node_modules/webpack/lib/Compiler.js:546:28
    at .../node_modules/webpack/lib/Compiler.js:1127:17
    at eval (eval at create (.../node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
The terminal process "zsh '-c', 'yarn run start'" terminated with exit code: 1.
```

## 🌍 Your Environment
```
Angular CLI: 13.0.2
Node: 16.13.0
Package Manager: yarn 3.1.0
OS: darwin arm64

Angular: 13.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@angular/flex-layout            12.0.0-beta.35
@schematics/angular             13.0.2
rxjs                            7.4.0
typescript                      4.4.4```

**Anything else relevant?**

<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->

<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->

**Comment by andreialecu** [comment] 2021-11-26 14:12
As an update, it seems that if I clear `.angular/cache` it works for a while.

**Comment by andreialecu** [comment] 2021-11-26 14:15
The webpack team indicates this is a problem with Angular: https://github.com/webpack/webpack/issues/14840#issuecomment-980005874

**Comment by alan-agius4** [comment] 2021-11-26 15:08
I am not sure how they determined this is a bug on the Angular side. I actually doubt this especially since you mentioned caching, which in applications it's totally under Webpack's control.

The only place that I am aware that Sources are replaced with `SizeOnlySource` is actually deep in Webpack, see https://github.com/webpack/webpack/blob/122db57e7bb0ddb8327b37eeaa0adb9bd5135962/lib/Compiler.js#L742-L756 in the Angular CLI we don't create an asset as `SizeOnlySource`.

Can you explain how is `fontawesome-webfont.eot` being including in the compilation?

**Comment by andreialecu** [comment] 2021-11-26 15:11
`fontawesome-webfont.eot` is in `src/assets/font` and it's specified in `angular.json`

```json
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "preserveSymlinks": true,
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/assets/sounds",
              "src/manifest.webmanifest",
              "src/assets/font",
              "src/assets/img",
              "src/robots.txt"
            ],
```

**Comment by alan-agius4** [comment] 2021-11-26 15:48
@andreialecu, and how are you referencing the `fontawesome-webfont.eot` in your CSS, if yes, is it in a component CSS or Global CSS? I am asking because unless you are referencing the font using `^` there is no need to copy this as an asset, because assets referenced in CSS will automatically be copied.

 Also, does this happen during `ng build`, `ng serve` or both?

**Comment by andreialecu** [comment] 2021-11-26 15:56
It's referenced via an `@import`:

```scss
$fa-font-path: '~assets/font/font-awesome';
@import '~font-awesome/scss/font-awesome';
```

Using `font-awesome@^4.7.0` in `package.json` (this is an older project).

I'm currently no longer able to reproduce it, but it's been coming and going the past few days.

The behavior I was seeing was as follows:

- There's an initial compilation, and `✔ Compiled successfully.` is printed.
- A second compilation starts (without any changes being done), and on this second compilation, it also prints `✔ Compiled successfully.` but crashes immediately after.

I have this in scrollback history from when I added the logging to webpack so here's a screenshot.

<img width="847" alt="Screenshot 2021-11-26 at 17 56 08" src="https://user-images.githubusercontent.com/697707/143606196-6946019f-83bb-44af-a445-8339b52a99dc.png">

**Comment by andreialecu** [comment] 2021-11-26 16:03
Also I'm not sure if it happens on `ng build`, but I think it's somehow impacted by `package.json` changes.

The past few days I've kept running into this error and it would magically go away and come back after adding/removing random dependencies to `package.json`. It's possible that webpack's cache ends up in a bad state at some point. As a general (questionable 🙂) practice, I generally kept `ng serve` running while adding/removing dependencies.

I found the "bad" cache in the trash bin but I currently can't reproduce it even by swapping it in. I made various `package.json` changes in the mean time, so this might confirm it's related to dependencies as well.

**Comment by andreialecu** [comment] 2021-11-26 16:13
Also a report from the Angular discord here, but it was largely ignored:

<img width="995" alt="Screenshot 2021-11-26 at 18 13 04" src="https://user-images.githubusercontent.com/697707/143607979-32ed081a-bd12-49bc-90c0-4851a5d1a4d8.png">

https://discord.com/channels/748677963142135818/748806247926726736/909373589860524073

**Comment by Mersal-Mohamed** [comment] 2021-11-26 16:25
yes i get this error and when i get stuck on it 
i removed the project and clone it again from the origin repo 
and it works good

**Comment by alan-agius4** [comment] 2021-11-26 16:25
> The key probably lies in SizeOnlySource. And why that is being compared to a RawSource.

Indeed and this seems to be something internal to Webpack especially since this only happens with caching. Overall, I highly doubt that this is caused by the Angular CLI, as mentioned we don't use `SizeOnlySource`. That being said, without a reproduction it's hard to tell what is happening. 

> Also a report from the Angular discord here, but it was largely ignored:
> 
> <img alt="Screenshot 2021-11-26 at 18 13 04" width="995" src="https://user-images.githubusercontent.com/697707/143607979-32ed081a-bd12-49bc-90c0-4851a5d1a4d8.png">
> 

> https://discord.com/channels/748677963142135818/748806247926726736/909373589860524073

Discord is not the right place to report bugs.

**Comment by Mersal-Mohamed** [comment] 2021-11-26 16:27
> 

i reported in angular channel on discord to get quick help not to report a bug

**Comment by andreialecu** [comment] 2021-11-26 16:51
This was reopened on the webpack side. 

https://github.com/webpack/webpack/issues/14840

Since reports seem to be popping up, if someone has an open source repo where this happens, please save your `.angular/cache`. It's probably related to a bad cache entry of some sort, and that might help track it down.

**Comment by andreialecu** [comment] 2021-12-02 08:30
@alan-agius4 what would be the reason for angular to do a two step compilation? 

In my project when running `serve` it always compiles once (slowly), then it does another pass which completes very fast (less than 1 second).

It was after this second pass that the crash was occurring.

The webpack team seems suspicious about this behavior and they seem to imply this might still be an issue on the angular side.

**Comment by alan-agius4** [comment] 2021-12-02 09:12
> what would be the reason for angular to do a two step compilation?

This should only happen during the first run and is caused by the Angular compatibility compiler (NGCC), is due that libraries need to be converted to compatible with Ivy.

Unfortunately, it’s hard to determine the root cause without a reproduction or at least steps on how to reproduce.

**Comment by andreialecu** [comment] 2021-12-02 09:19
@alan-agius4 well, it just started happening again. If you're able to connect on Discord perhaps I can help track it down there. I don't have any specific repro steps because it seems random.

If you search for `Error: Content and Map of this Source` on the official Angular discord server you'll be able to find me.

**Comment by alan-agius4** [comment] 2021-12-02 17:17
Following a convo on discord with @andreialecu, it turns out that this stylesheet is actually referenced in a component and therefore it doesn’t use mini-css. I therefore suspect that this might be an issue with our plugin.

**Comment by lalo-mx** [comment] 2021-12-03 14:38
After updating to versión 13.0 it started happening(not always fails)

**Fails**

`ng build --build-optimizer=false --watch --base-href=/app/
`

**Works**

`ng build --build-optimizer=false --source-map=true --watch --base-href=/app/
`

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.4
Node: 16.13.1
Package Manager: npm 8.1.4
OS: win32 x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4


</code></pre>



## Workaround

It looks that it could be caused by a style in a SASS file(most likely).

<pre><code>
.sample1 {
	background-image: url('./assets/sample1.gif');
}


</code></pre>

**Comment by alan-agius4** [comment] 2021-12-06 14:32
@lalo-mx, would you be able to share a reproduction? Or maybe we can schedule a remote debugging session? Without a reproduction it would be hard to get to the bottom of this. 

If you'd like to debug this, @alexander-akait suggest that you can add a breakpoint/console.log here https://github.com/webpack/webpack-sources/blob/main/lib/SizeOnlySource.js#L15 and https://github.com/webpack/webpack/blob/main/lib/Compiler.js#L546.

**Comment by lalo-mx** [comment] 2021-12-07 17:25
@alan-agius4 I have not been able to create a reproduction. Any new project works as expected even with same configuration.

Do you have any ideas why main.js would compile three times?

`ng build --build-optimizer=false --source-map=true --watch --base-href=/app/`

```

✔ Browser application bundle generation complete.
✔ Index html generation complete.

Initial Chunk Files  | Names             |      Size
vendor.js            | vendor            |   7.91 MB
**main.js              | main              |   4.10 MB**
dx.light.css         | dx.light          | 768.58 kB
componentColors.css  | componentColors   | 415.73 kB
polyfills.js         | polyfills         | 127.00 kB
materialFonts.css    | materialFonts     |  79.51 kB
styles.css           | styles            |  75.61 kB
foundation.css       | foundation        |  68.63 kB
scripts.js           | scripts           |  20.32 kB
runtime.js           | runtime           |  14.35 kB
loader.css           | loader            |   2.75 kB
dx.common.css        | dx.common         |   1.04 kB

                     | Initial Total     |  13.55 MB

Lazy Chunk Files     | Names             |      Size
6896.js              | -                 |  18.60 MB
3367.js              | -                 |   2.69 MB
2080.js              | -                 |   2.01 MB
386.js               | -                 |   1.80 MB
8405.js              | -                 | 836.25 kB
4101.js              | -                 | 538.23 kB
3184.js              | -                 | 412.57 kB
9088.js              | -                 | 403.57 kB
8181.js              | -                 | 278.66 kB
5592.js              | -                 | 201.96 kB
6194.js              | -                 | 115.35 kB
1455.js              | -                 | 114.73 kB
9546.js              | -                 | 103.11 kB
4964.js              | -                 | 101.89 kB
polyfills-core-js.js | polyfills-core-js |  92.39 kB
1727.js              | -                 |  77.04 kB
7018.js              | -                 |  65.53 kB
835.js               | -                 |  62.13 kB
5006.js              | -                 |  59.63 kB
8009.js              | -                 |  54.13 kB
6447.js              | -                 |  53.94 kB
9751.js              | -                 |  53.35 kB
8468.js              | -                 |  51.96 kB
3045.js              | -                 |  51.42 kB
2371.js              | -                 |  42.71 kB
9702.js              | -                 |  40.78 kB
9096.js              | -                 |  34.52 kB
2729.js              | -                 |  32.47 kB
4513.js              | -                 |  30.92 kB
643.js               | -                 |  30.75 kB
1640.js              | -                 |  30.73 kB
8368.js              | -                 |  28.41 kB
1096.js              | -                 |  27.10 kB
8715.js              | -                 |  27.08 kB
6932.js              | -                 |  24.82 kB
2542.js              | -                 |  24.56 kB
6879.js              | -                 |  23.87 kB
polyfills-dom.js     | polyfills-dom     |  19.48 kB
8932.js              | -                 |  16.79 kB
2167.js              | -                 |  14.99 kB
1893.js              | -                 |  14.84 kB
510.js               | -                 |  14.20 kB
35.js                | -                 |  13.80 kB
6214.js              | -                 |  11.38 kB
1767.js              | -                 |  11.19 kB
9436.js              | -                 |  10.46 kB
3940.js              | -                 |  10.40 kB
1173.js              | -                 |  10.08 kB
9527.js              | -                 |   9.14 kB
8548.js              | -                 |   9.00 kB
8018.js              | -                 |   8.85 kB
8867.js              | -                 |   8.60 kB
9084.js              | -                 |   8.19 kB
4262.js              | -                 |   7.50 kB
1512.js              | -                 |   7.43 kB
4090.js              | -                 |   7.40 kB
6684.js              | -                 |   7.08 kB
9391.js              | -                 |   6.98 kB
3219.js              | -                 |   6.87 kB
2283.js              | -                 |   6.81 kB
9638.js              | -                 |   6.62 kB
7940.js              | -                 |   6.36 kB
9381.js              | -                 |   6.33 kB
7593.js              | -                 |   6.30 kB
9051.js              | -                 |   6.06 kB
7016.js              | -                 |   6.01 kB
3338.js              | -                 |   5.94 kB
2451.js              | -                 |   5.85 kB
7421.js              | -                 |   5.81 kB
common.js            | common            |   5.76 kB
7914.js              | -                 |   5.75 kB
6060.js              | -                 |   5.63 kB
1775.js              | -                 |   5.53 kB
4486.js              | -                 |   5.50 kB
6889.js              | -                 |   5.41 kB
6853.js              | -                 |   5.10 kB
1720.js              | -                 |   5.08 kB
3324.js              | -                 |   5.05 kB
2302.js              | -                 |   4.90 kB
2730.js              | -                 |   4.88 kB
5781.js              | -                 |   4.79 kB
40.js                | -                 |   4.77 kB
4951.js              | -                 |   4.65 kB
1578.js              | -                 |   4.62 kB
8080.js              | -                 |   4.61 kB
2413.js              | -                 |   4.55 kB
8644.js              | -                 |   4.53 kB
4270.js              | -                 |   4.47 kB
1940.js              | -                 |   4.45 kB
2013.js              | -                 |   4.45 kB
5087.js              | -                 |   4.21 kB
2331.js              | -                 |   4.17 kB
508.js               | -                 |   4.16 kB
699.js               | -                 |   4.15 kB
6030.js              | -                 |   4.14 kB
4819.js              | -                 |   4.08 kB
7450.js              | -                 |   4.01 kB
2626.js              | -                 |   3.95 kB
9218.js              | -                 |   3.94 kB
9279.js              | -                 |   3.90 kB
3366.js              | -                 |   3.85 kB
8104.js              | -                 |   3.73 kB
1697.js              | -                 |   3.68 kB
5159.js              | -                 |   3.65 kB
9991.js              | -                 |   3.60 kB
8241.js              | -                 |   3.55 kB
6213.js              | -                 |   3.50 kB
4490.js              | -                 |   3.46 kB
2244.js              | -                 |   3.46 kB
6045.js              | -                 |   3.37 kB
4406.js              | -                 |   3.34 kB
6815.js              | -                 |   3.34 kB
4002.js              | -                 |   3.34 kB
3384.js              | -                 |   3.28 kB
5018.js              | -                 |   3.24 kB
6166.js              | -                 |   3.21 kB
5700.js              | -                 |   3.21 kB
6549.js              | -                 |   3.20 kB
1040.js              | -                 |   3.19 kB
4868.js              | -                 |   3.15 kB
1471.js              | -                 |   3.15 kB
3182.js              | -                 |   3.14 kB
4542.js              | -                 |   3.14 kB
8131.js              | -                 |   3.08 kB
2546.js              | -                 |   3.08 kB
6480.js              | -                 |   3.04 kB
1489.js              | -                 |   3.00 kB
5331.js              | -                 |   3.00 kB
1981.js              | -                 |   2.97 kB
8525.js              | -                 |   2.94 kB
7177.js              | -                 |   2.88 kB
5934.js              | -                 |   2.78 kB
1989.js              | -                 |   2.74 kB
7020.js              | -                 |   2.69 kB
6095.js              | -                 |   2.67 kB
4520.js              | -                 |   2.67 kB
8016.js              | -                 |   2.65 kB
2652.js              | -                 |   2.63 kB
9173.js              | -                 |   2.62 kB
7854.js              | -                 |   2.60 kB
4204.js              | -                 |   2.58 kB
8643.js              | -                 |   2.47 kB
9205.js              | -                 |   2.39 kB
5596.js              | -                 |   2.16 kB
7224.js              | -                 |   1.99 kB
4643.js              | -                 |   1.99 kB
458.js               | -                 | 941 bytes
5233.js              | -                 | 908 bytes
600.js               | -                 | 466 bytes
927.js               | -                 | 465 bytes
3865.js              | -                 | 444 bytes
9938.js              | -                 | 444 bytes
2401.js              | -                 | 435 bytes
6093.js              | -                 | 435 bytes
6989.js              | -                 | 435 bytes
8454.js              | -                 | 435 bytes
287.js               | -                 | 434 bytes
2496.js              | -                 | 339 bytes
9561.js              | -                 | 339 bytes
4544.js              | -                 | 330 bytes
4791.js              | -                 | 330 bytes
6530.js              | -                 | 330 bytes
8839.js              | -                 | 330 bytes
7356.js              | -                 | 329 bytes

Build at: 2021-12-07T17:14:55.771Z - Hash: 1c7c2c26e429b7ba - Time: 133087ms

Warning: <custompath>\dayjs\dayjs.ts depends on 'dayjs/locale/es'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: <custompath>\test.module.ts depends on 'ngx-kjua'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies


✔ Browser application bundle generation complete.
✔ Index html generation complete.

Initial Chunk Files | Names |    Size
**main.js             | main  | 4.10 MB**

175 unchanged chunks

Build at: 2021-12-07T17:15:16.115Z - Hash: 7921c8a114ef7457 - Time: 28395ms
✔ Browser application bundle generation complete.
✔ Index html generation complete.

Initial Chunk Files | Names |    Size
**main.js             | main  | 4.10 MB**

175 unchanged chunks

Build at: 2021-12-07T17:15:25.762Z - Hash: 9931beabf2c5b6d9 - Time: 9450ms

```

**Comment by lalo-mx** [comment] 2021-12-08 13:58
@alan-agius4 I applied the solution for https://github.com/webpack/webpack/issues/14911 and it fixes the crash.

**Comment by andreialecu** [comment] 2021-12-08 14:08
@lalo-mx I doubt that https://github.com/webpack/webpack/issues/14911 itself fixed the crash unless you're able to get it back again after reverting the change.

In my case, any minor changes fix the crash. Things like adding, updating or removing dependencies will fix the crash. In particular, deleting the `.angular/cache` directory fixes the crash for a while, until it eventually comes back.

**Comment by pfeigl** [comment] 2021-12-08 14:20
Just to add to this: We are seeing the exact opposite. We get the error on first builds (before the cache is belt up) and also get it repeatedly.

After a first run, the problem mostly does not come back.

Clearing the cache shows the problem again.

**Comment by lalo-mx** [comment] 2021-12-08 14:35
@andreialecu Maybe, the sequence  of my tests was:

1. Build without patch: Fails
2. Build with patch: Success
3. Build without patch: Fails

**Comment by lalo-mx** [comment] 2021-12-09 17:06
With cache disabled the issue is more easily reproducible in my environment.
`ng config cli.cache.enabled false`

**Comment by alan-agius4** [comment] 2021-12-09 17:18
@lalo-mx, would you be able to share a reproduction? Or maybe we can schedule a remote debugging session? Unfortunately without a reproduction it would be hard to get to the bottom of this.

**Comment by lalo-mx** [comment] 2021-12-09 20:33
@alan-agius4  Not 100% sure if is the same error but it crashes similarly [sample-angular-13.zip](https://github.com/angular/angular-cli/files/7688248/sample-angular-13.zip)

`npm run start-fast`

**Comment by linlexing** [comment] 2021-12-10 07:09
Since upgrading to NG13, I have also encountered this error at random
```
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/front **


√ Compiled successfully.
✔ Browser application bundle generation complete.

71 unchanged chunks

Build at: 2021-12-10T06:53:51.120Z - Hash: 8c692cc50c1a3a1d - Time: 4210ms

√ Compiled successfully.
✔ Browser application bundle generation complete.

71 unchanged chunks

Build at: 2021-12-10T06:53:53.969Z - Hash: 8c692cc50c1a3a1d - Time: 2167ms

√ Compiled successfully.
C:\gosrc\src\dbweb\builds\common\front\node_modules\webpack-sources\lib\SizeOnlySource.js:16
                return new Error(
                       ^

Error: Content and Map of this Source is not available (only size() is supported)
    at SizeOnlySource._error (C:\gosrc\src\dbweb\builds\common\front\node_modules\webpack-sources\lib\SizeOnlySource.js:16:10)
    at SizeOnlySource.buffer (C:\gosrc\src\dbweb\builds\common\front\node_modules\webpack-sources\lib\SizeOnlySource.js:30:14)
    at _isSourceEqual (C:\gosrc\src\dbweb\builds\common\front\node_modules\webpack\lib\util\source.js:21:51)
    at isSourceEqual (C:\gosrc\src\dbweb\builds\common\front\node_modules\webpack\lib\util\source.js:43:17)
    at Compilation.emitAsset (C:\gosrc\src\dbweb\builds\common\front\node_modules\webpack\lib\Compilation.js:4171:9)
    at C:\gosrc\src\dbweb\builds\common\front\node_modules\webpack\lib\Compiler.js:548:28
    at C:\gosrc\src\dbweb\builds\common\front\node_modules\webpack\lib\Compiler.js:1129:17
    at eval (eval at create (C:\gosrc\src\dbweb\builds\common\front\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
The environment：
```
Angular CLI: 13.0.4
Node: 16.13.0
Package Manager: yarn 1.22.10
OS: win32 x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cdk                    13.1.0
@angular/cli                    13.0.4
@angular/material               13.1.0
@schematics/angular             13.0.4
rxjs                            6.6.7
typescript                      4.4.4
```

**Comment by alan-agius4** [comment] 2021-12-10 11:19
> @alan-agius4 Not 100% sure if is the same error but it crashes similarly [sample-angular-13.zip](https://github.com/angular/angular-cli/files/7689665/sample-angular-13.zip)
> 
> Updating to latest @angular/cli and @angular/core to 13.1.0 version appears to fix it, i will run more tests.
> 
> `npm run start-fast`

@lalo-mx, I downloaded the project, but I wasn't able to reproduce the error.

**Comment by asayamakk** [comment] 2021-12-23 09:44
In my case, I deleted `node_modules`and `.yarn/cache` directories and fixed this problem so far. I hope this might help.

**Comment by alan-agius4** [comment] 2022-01-11 09:34
Hi all,  is this still reproducible?

**Comment by lalo-mx** [comment] 2022-01-14 14:39
@alan-agius4  The issue is not reproducible for us anymore. It has has been stable for more than a month now.

**Comment by alan-agius4** [comment] 2022-01-14 14:53
@andreialecu also confirmed via discord that he can no longer replicate this. Therefore I am closing the issue.

If the problem persist, please open a new issue, provide a simple repository reproducing the problem.

**Closed by alan-agius4** 2022-01-14 14:53 UTC
Labels: need: repro steps
