### ISSUE TITLE
Add A "remove component (ng rm c <componentName>)" option in Angular CLi 

### ISSUE THREAD

**Issue by AndreaColomboIT** [angular/angular-cli#24785] opened 2023-02-27 07:25 UTC
### Command

generate

### Description

In the Angular Cli isn't possible to <b> remove a component from the poject by CLI </b>. 

If i have to remove a component, i need to delete the folder, and manually remove all the imports from the files where i used the component.

### Describe the solution you'd like

It could be the same as the generate component feature but instead of creating a new one, it should delete one from the project, and all relative links.

It could be `ng rm c <componentName>`

I would like to contribute myself to this feature because is something i was considering for a long time. Thank you so much.

**Comment by alan-agius4** [comment] 2023-02-27 08:47
Duplicate of https://github.com/angular/angular-cli/issues/24703

**Closed by alan-agius4** 2023-02-27 08:47 UTC
