### ISSUE TITLE
`ng add @nguniversal/express-engine` fails in a project without an `app.module.ts`

### ISSUE THREAD

**Issue by ciriousjoker** [angular/angular-cli#24784] opened 2023-02-26 17:50 UTC
### Command

add

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Tried to set up a fully standalone project with ssr, but `ng add` fails.

### Minimal Reproduction

1. `ng new repro-angular-ssr --minimal --skip-tests --strict --style css --inline-template --inline-style`
2. `ng generate @angular/core:standalone` (selected bootstrap at path `./`)

**This now fails:**

`ng add @nguniversal/express-engine --verbose`

**Repo:**
https://github.com/ciriousjoker/repro-angular-ssr

### Exception or Error

```text
ℹ Using package manager: npm
⠋ Searching for compatible package version...Locating potential npmrc files:
✔ Found compatible package version: @nguniversal/express-engine@15.2.0.
✔ Package information loaded.

The package @nguniversal/express-engine@15.2.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Bootstrap call not found
```

### Your Environment

```text
Angular CLI: 15.2.0
Node: 16.19.0
Package Manager: npm 9.4.0
OS: darwin arm64

Angular: 15.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0
@angular-devkit/build-angular   15.2.0
@angular-devkit/core            15.2.0
@angular-devkit/schematics      15.2.0
@schematics/angular             15.2.0
rxjs                            7.8.0
typescript                      4.9.5
```

### Anything else relevant?

**Possibly related:**
- #23316 
- #24666

**Comment by ciriousjoker** [comment] 2023-02-26 18:49
I guess it looks like this isn't even supposed to work right now:
https://github.com/angular/universal/issues/2906

**Comment by alan-agius4** [comment] 2023-02-27 08:47
Duplicate of https://github.com/angular/universal/issues/2906

**Closed by alan-agius4** 2023-02-27 08:47 UTC
