### ISSUE TITLE
component sass files with Shadow DOM not working with angular-cli@latest: 1.0.0-beta.14

### ISSUE THREAD

**Issue by richavyas** [angular/angular-cli#2215] opened 2016-09-19 09:24 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
    Mac OSX (Yosemite)

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.14
node: 6.1.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   This app ran successfully with the latest webpack/angular-cli@latest but it's not loading component sass files with shadow dom. e.g.:
#### app.component.ts
   ```
   styleUrls: ['app/app.component.scss'],
   templateUrl: 'app/app.component.html',
   ```
  It loads the html correctly and gives no error for sass file but doesn't load the nested sass

 #### mycomponent.scss
    ```
   :host /deep/ {
       ...,
   
   }
   ```

   #### Setup info:
   Router : upgraded to rc.7
   Webpack: "2.1.0-beta.22"
   angular-cli@latest

4. The log given by the failure. Normally this include a stack trace and some
   more information.
   No error while ng build or serve. Build happens successfully but this sass doesn't load.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-09-22 03:24
Dupe of https://github.com/angular/angular-cli/issues/2088 I think. If that's not the case I'll reopen.

**Closed by filipesilva** 2016-09-22 03:24 UTC

**Comment by richavyas** [comment] 2016-09-22 04:14
Hi @filipesilva, this one was actually for component scss files and not for global styles.

Another thing to highlight here is that I am not able to load html & scss files with giving complete path. So what I have to do right now is this:
```@Component({
  selector: 'docs-covalent',
  templateUrl: 'app/app.component.html',
  styleUrls: ['app/app.component.scss'],
})```

Can this be the reason that app.component.scss is not being loaded. Do we have to give complete path while defining the component? If not, is there a generic/compile step that I would have missed.

**Comment by richavyas** [comment] 2016-09-22 18:53
Hey @filipesilva, lets keep this ticket closed as I got the build and app running successfully with `angular-cli@1.0.0-beta.1`, FTW :)
