### ISSUE TITLE
Making a change to an e2e test while running ng e2e causes entire app to rebuild, slow

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#8364] opened 2017-11-06 07:15 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
$ ng --version                                                          
    _                      _                 ____ _     ___             
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|            
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |             
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |             
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|            
               |___/                                                    
@angular/cli: 1.4.2                                                     
node: 6.10.1                                                            
os: win32 x64                                                           
```

### Repro steps.
- run `ng e2e --port=4201`
- make a change to an e2e test
- rebuild takes about 1.15 minutes.

With `ng serve` a code change only takes ~10 seconds to recompile. Why is rebuilding as part of e2e so slow?

**Comment by picheli20** [comment] 2017-11-10 16:34
Have you already tried to set the `--sourcemap false`? It reduces a lot the build time (check https://github.com/angular/angular-cli/issues/5775)

**Comment by FrancescoBorzi** [comment] 2019-03-19 11:12
any news about this?

**Comment by filipesilva** [comment] 2019-10-08 13:22
I think this issue is a duplicate of https://github.com/angular/angular-cli/issues/2861. We don't have a watch mode for e2e so `ng e2e` shouldn't be rebuilding anything in the first place.

**Closed by filipesilva** 2019-10-08 13:22 UTC
Labels: priority: 3 (nice to have), severity2: inconvenient
