### ISSUE TITLE
71% sealing ...

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#8126] opened 2017-10-20 08:12 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
```

### Versions.
@angular/cli: 1.4.9
node: 6.11.0
os: win32 x64
@angular/*: 4.4.6
@angular/cli: 1.4.9
typescript: 2.3.4

### Repro steps.
udpate from 1.4.6 to 1.4.9  then run `ng s --sm=false`

### The log given by the failure.
blockin 71% sealing 1mn then go ahead

here's gif  :
![71](https://user-images.githubusercontent.com/2789203/31811257-28180fec-b57f-11e7-84b7-82390112b6d7.gif)

And how I hide all theses modules in console I juste want filename as before  this polluate my console very ugly.

![image](https://user-images.githubusercontent.com/2789203/31811152-bdf857d4-b57e-11e7-880e-0fab8e13e929.png)

**Comment by royibernthal** [comment] 2017-10-22 02:48
I'm experiencing the same issue.

**Comment by liuxinqiang** [comment] 2017-10-23 02:04
Same problem...

**Comment by bingzheyuan** [comment] 2017-10-23 09:38
Same for me, and much worse, I have code splitting in TS and generating 350+ chunks, the sealing takes hours for webpack 3.7+ but only 5s in 3.6.4

denpendencies of mine:
node@6.9.5
win 7 64bit
typescript@2.5.3
awesome-typescript-loader@3.2.3

**Comment by mtekkie** [comment] 2017-10-23 18:33
I have the same problem.

**Comment by bingzheyuan** [comment] 2017-10-24 07:16
I have same issue, could you check webpack version? The issue shows up starting from webpack@^3.7. For webpack 3.6, sealing takes only seconds.

**Comment by Taitalus** [comment] 2017-10-24 11:25
@bingzheyuan  I checked that.. `@angular/cli@1.4.9` uses `webpack@3.7.1`

**Comment by novus57** [comment] 2017-10-24 15:25
I also have the same issue and almost are very sure that the problem is with the Webpack.

**Comment by filipesilva** [comment] 2017-10-25 09:49
This does sound like a problem in the new webpack versions. We updated to 3.7.1 in https://github.com/angular/angular-cli/pull/8014 and 3.8.1 in https://github.com/angular/angular-cli/pull/8132. 

3.8.1 might fix this, but it wasn't released in 1.4.9. It should be in 1.5.0 final that is coming out very soon, and you can also try out `1.5.0-rc.3` meanwhile.

**Comment by novus57** [comment] 2017-10-25 10:03
Thanks. It works on 1.5.0-rc.3 and node `6.11.0`.

**Comment by Taitalus** [comment] 2017-10-26 06:25
yes. it works a lot faster than the previous.

**Comment by istiti** [comment] 2017-10-26 06:35
works only for this 71% step not faster globally , be clear

**Comment by Taitalus** [comment] 2017-10-27 05:47
yes. lastly my build would take about 11.5 mins now it's taking 2.5 mins. lot improved on that perspective. but it's not fast like the earlier versions.

**Comment by istiti** [comment] 2017-10-27 06:24
I confirm in v1.5.0-rc.3 it doesn't block a lot on 71%, now I have little blocking at step
`76% basic chunk optimization` donno whats done here... 

here you are: 
![rld](https://user-images.githubusercontent.com/2789203/32090503-08e22c40-baf0-11e7-9ee4-05b63686b1b7.gif)

**Comment by istiti** [comment] 2017-10-30 11:03
is this fixed in rc6 because there is not block  at 71% but only at 
`0% compiling` more than 30seconds
and semestimes on 
` 10% building modules 0/1 modules 1 active ...s\i10\src\app\app.module.ngfactory.js` more than 30seconds

it depend one or other 

(in new project it's very fast)

**Comment by Taitalus** [comment] 2017-10-30 12:36
@istiti facing this `10% building modules wait..` here too.

**Comment by filipesilva** [comment] 2017-11-04 18:12
I think 1.5,0 final addressed the issue discussed here so I'm closing this issue.

**Closed by filipesilva** 2017-11-04 18:12 UTC
Labels: priority: 1 (urgent), type: bug
