### ISSUE TITLE
sporadic recompilation with no obvious reason

### ISSUE THREAD

**Issue by gozzoo** [angular/angular-cli#14146] opened 2019-04-12 10:07 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] serve
```

### Is this a regression?

No, it has been happening in all previous angular-cli versions.

### Description

After I start `ng serve` it promptly recompiles the project after each change in any of the source files.

What's stange is that re-compilation can be caused by seemingly unrelated events like resizing termial window in VSCode or starting production build in another terminal `ng build --prod`. Recompilation is oftern triggered by loading the app in the browser. It also happened after I did file search in VSCode.

## 🌍 Your Environment
```
Angular CLI: 7.3.8
Node: 10.14.2
OS: win32 ia32
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
```

**Comment by alan-agius4** [comment] 2019-04-12 10:08
Duplicate of https://github.com/angular/angular-cli/issues/14116

**Closed by alan-agius4** 2019-04-12 10:08 UTC
