### ISSUE TITLE
Documentation Angular Schematics (methods and interfaces)

### ISSUE THREAD

**Issue by boeckMt** [angular/angular-cli#19795] opened 2021-01-14 16:13 UTC
# 🚀 Feature request
Better Documentation of public Interfaces of Angular Schematics.

relates to: https://github.com/angular/angular-cli/issues/19525#issuecomment-737041158_

### Description
There isn't a lot of documentation on how to use the Schematics and which interfaces are public and can be used.

In the linked Issue: https://github.com/angular/angular-cli/issues/19525#issuecomment-737041158 there was the suggestion to use the below Interfaces for working with the workspace and projects
> The new API has different interfaces, you can use the following instead.
> WorkspaceSchema -> WorkspaceDefinition
> WorkspaceProject -> ProjectDefinition
> https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/core/src/workspace/definitions.ts

but these does not reflect the structure of the [`angular.json`](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/lib/config/schema.json) file.

### Describe the solution you'd like
It would be helpful to have a more exhaustive documentation on Schematics e.g. on https://angular.io/guide/schematics and which methods and Interfaces can be used to create own Schematics.

**Comment by alan-agius4** [comment] 2021-01-14 16:33
This is will be addressed once the following two issues https://github.com/angular/angular-cli/issues/15335 and https://github.com/angular/angular-cli/issues/12134 are resolved.

At the moment most of the APIs under `@schematics/angular` are private.

A good rule of thumb is that anything which is not exported from the main or secondary entrypoints and requires a deep import to use is to be considered private.

**Comment by alan-agius4** [comment] 2021-01-14 16:39
Duplicate of https://github.com/angular/angular/issues/29241

**Closed by alan-agius4** 2021-01-14 16:39 UTC

**Comment by boeckMt** [comment] 2021-01-15 08:58
> This is will be addressed once the following two issues #15335 and #12134 are resolved.
> 
> At the moment most of the APIs under `@schematics/angular` are private.
> 
> A good rule of thumb is that anything which is not exported from the main or secondary entrypoints and requires a deep import to use is to be considered private.

Ok, thanks for the information!
