### ISSUE TITLE
Angular version 12 doesn't allow node version 15 and 16

### ISSUE THREAD

**Issue by floross** [angular/angular-cli#20796] opened 2021-05-14 17:15 UTC
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc

### Description

You cannot use the node version `15.x` or `16.x`. Is there a way to not enfore node version to "^12.14.1 || ^14.0.0" and allow latest version of it ?

## 🔬 Minimal Reproduction

```bash
> node -v
v16.0.0
> yarn
```

## 🔥 Exception or Error

```bash
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
error @angular-devkit/build-angular@12.0.0: The engine "node" is incompatible with this module. Expected version "^12.14.1 || ^14.0.0". Got "16.0.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## 🌍 Your Environment

`"@angular/cli": "^12.0.0"`
`node v16.x`

**Comment by alan-agius4** [comment] 2021-05-14 17:43
Duplicate of https://github.com/angular/angular/issues/42076

**Comment by JoostK** [comment] 2021-05-26 20:34
I reopened this because the CLI also needs to be updated (FW has switched to a more permissive version range)

**Closed** 2021-05-31 11:47 UTC
Labels: comp: angular/cli, comp: build & ci, freq2: medium, severity3: broken, type: bug/fix
