### ISSUE TITLE
Adding a service with ng g [path-to-service/service-name] fails with [path-to-service] is not a valid path

### ISSUE THREAD

**Issue by shawncodewell** [angular/angular-cli#3073] opened 2016-11-09 03:39 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 7 x64

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: win32 x64

### Repro steps.
app was created with CLI.
execute ng g [path-to-service/service-name]
If I then manually create the folder [path-to-service], and run the command again, it works fine, and the service-name is created in the [path-to-service] folder.

### The log given by the failure.
installing service
Invalid path: "C:\Development\Learning\Angular2\MyFullDemoSolution\src\DemoNg2Client\src\app\services2"" is not a valid path.

**Comment by filipesilva** [comment] 2016-11-21 14:08
It is by design that the generators will not create subfolders.

**Comment by filipesilva** [comment] 2016-11-21 14:08
Also, dupe of https://github.com/angular/angular-cli/issues/2806 with more discussion there.

**Closed by filipesilva** 2016-11-21 14:08 UTC
