### ISSUE TITLE
MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by mohibrahimm** [angular/angular-cli#10325] opened 2018-04-13 16:33 UTC
This is the issue I'm getting

Angular CLI: 1.7.2
Node: 8.9.4
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

Deploy files to to server
Service Worker caches all the files
Deploy updated files to server
Get this error on refresh after deploying updated files: Refused to execute script from Refused to apply style from
 'https://martmax.co/martmax/styles.90e231a43b112dde0a8e.bundle.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to execute script from 'https://martmax.co/martmax/inline.42eab311bb328d4389bc.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
martmax.co/:1 Refused to execute script from 'https://martmax.co/martmax/polyfills.a6e3c1aba633d4169f73.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
martmax.co/:1 Refused to execute script from 'https://martmax.co/martmax/scripts.a5ebe8c46eb086e27504.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
martmax.co/:1 Refused to execute script from 'https://martmax.co/martmax/main.dd14f2660d7784d60e49.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
martmax.co/:1 Refused to apply style from 'https://martmax.co/martmax/styles.90e231a43b112dde0a8e.bundle.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Doing a hard refresh (CMD + SHIFT + R) skips the service worker cache and loads the newly deployed files without any issues. And then doing a regular refresh causes the error to come back.

My sw.js is not being cached and have nginx setup.

Deploying an update and refreshing pulls files from service worker, but they have the incorrect content-
![image](https://user-images.githubusercontent.com/29049288/38746672-7dcf0e42-3f48-11e8-85d9-0db4a27bb138.png)
![image](https://user-images.githubusercontent.com/29049288/38746692-8a3b2e9a-3f48-11e8-8876-11c36cf78dce.png)

![image](https://user-images.githubusercontent.com/29049288/38746713-99dbb482-3f48-11e8-8ae4-909969865f55.png)

My initial guess is that it's an issue with index.html , but asking if you guys have any other guesses.

@comewalk @jesperronn @mprobst @filipesilva
@Brocco @texel

**Comment by anupamarachuri** [comment] 2018-04-18 17:26
Same issue. Any luck?

**Comment by s73obrien** [comment] 2018-04-18 20:14
So, I don't know if this is the same issue that you guys are having, but I am working with an ejected project and, in my efforts, I noticed that, in the webpack.config.development.js file, the BaseHrefWebpackPlugin was being called with an empty parameters object:
```javascript
    new BaseHrefWebpackPlugin({}),
```
So I changed it to:
```javascript
    new BaseHrefWebpackPlugin({baseHref: baseHref}),
```

And set the constant declared at the beginning of the file to:
```javascript
const baseHref = "/";
```

And it started working flawlessly.  Again, no idea if that is what is going on for you, as I see you are working on an un-ejected project, but hopefully it helps somehow!

**Comment by TimMeissner** [comment] 2018-05-16 08:31
I have the same issue with loading a js file in a script tag from the assets folder.

**Comment by ergwun** [comment] 2018-05-17 07:44
@TimMeissner I had the same issue (js file in script tag from assets folder) where the script tag was beign dynamically generated, and was using 'text/javascript' as the type. Changing it to 'application/javascript' fixed it.

**Comment by blacksonic** [comment] 2018-05-17 15:15
Same here, blocks us from upgrading to Angular 6.
Changing the script type didnt solve the issue for me.

**Comment by VahidN** [comment] 2018-05-19 14:08
If you are a .NET Core developer, you should set the `content-types` manually, because their default value is null or empty:
```csharp
var provider = new FileExtensionContentTypeProvider();
app.UseStaticFiles(new StaticFileOptions
{
    ContentTypeProvider = provider // this is not set by default
});
```
For other web servers you should do the same by setting the correct `content-types`.

**Comment by blacksonic** [comment] 2018-05-19 19:32
@VahidN I dont understand, where should I put this code? Angular CLI serves the files in my case.

**Comment by VahidN** [comment] 2018-05-21 03:54
Angular CLI uses `webpack-dev-server`. I think `they` should make it configurable to set mimeTypes
```javascript
mime: {
      'application/javascript': ['js'],
      'text/css': ['css'],
   }
```

**Comment by blacksonic** [comment] 2018-05-21 06:38
It worked with previous versions and if I use plain WebpackDevServer it serves files without issues.

**Comment by filipesilva** [comment] 2018-05-21 11:50
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by blacksonic** [comment] 2018-05-22 10:57
While trying to reproduce the issue, it is caused by breaking changes in the names of the bundled files.

The files lost their `bundle` suffix and `inline` became `runtime`. The bad part is that I haven't found any mentions about these changes.

The generated files are now:
- `runtime.js`
- `polyfills.js`
- `vendor.js`
- `main.js`

Non existing files return status code 404 in text response and this is why Chrome throws these errors mentioned in the ticket title.

**Comment by filipesilva** [comment] 2018-05-22 11:07
@blacksonic we have changed the bundle names, yes. But also changed our build pipeline to use the updated names.

Do you have a custom index file from which you load the bundles manually?

**Comment by blacksonic** [comment] 2018-05-22 13:23
Yes, we have a different service that uses these files.

**Comment by veluria** [comment] 2018-05-29 14:12
In my case I just forgot that I had a base href in my `index.html`. Just posting in case anyone is as forgetful as I.

**Comment by attilacsanyi** [comment] 2018-05-29 14:33
What do you mean by base href @veluria ? Do we need to remove `<base href="/">` from `index.html`? It was there almost from the beginning. Thx.

**Comment by veluria** [comment] 2018-05-29 14:35
@attilacsanyi I had a different one (`<base href="/app">`) and that was what caused this error for me when using `ng serve`! :)

**Comment by dgsqrs** [comment] 2018-06-01 20:49
I try using this option --output-hashing=none and it seems to do the work (for now..). You can add it to your ng build --prod command

**Comment by b-johnse** [comment] 2018-06-06 20:06
Similar to a few of the above, disabling cache in the network tab of chrome dev tools allowed me to load the page, but it is not a fair expectation for users. This behavior came after upgrading to 6, and my project is not ejected and is not using service workers. With any new version deployed it happens, so my suspect is the output hashing because it will render index.html but it seems to not know how to use anything the browser cached.

**Comment by b-johnse** [comment] 2018-06-08 15:27
So as I look more at it, I think for me it is the opposite of what I said... the index.html seems cached and is asking for the old hashes which is why the server returns a 404, and it tries to apply the error response which gives the above error in console (my console errors are identical).

**Comment by pklejnowski** [comment] 2018-06-09 10:40
Regarding what @blacksonic said. I have the same problem - I mean application looking for files `*.bundle.js` although those files are generated without suffix `bundle`. If I will add manually that suffix to each file then everything works fine. Is there anyway to fix it?

**Comment by pklejnowski** [comment] 2018-06-09 10:54
@filipesilva is there any reason why you have removed `bundle` suffix? Those files ain't "bundled" anymore?

**Comment by pkdsite** [comment] 2018-06-13 07:42
Same problem here, MIME type ('text/html') is not executable, and strict MIME type checking is enabled. 
I am working on a Node Project.

**Comment by manojdcoder** [comment] 2018-06-22 05:58
I had same issue with Angular 6, I updated my **base** tag in _index.html_ as follows and issue was resolved.

```
<head>
    <meta charset="utf-8">
    <base href="/">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
```

**Comment by Dharmendert20** [comment] 2018-07-03 08:07
Yeah i had the same issue. I have applied type='text/html' in link tag and issue was resolved.

**Comment by janhurst** [comment] 2018-07-10 05:38
I am seeing this issue in a project where my angular-cli generated app is in a subdir of my "main" project dir, and I try to use `ng serve --serve-path <subdir>`.

I reproduced this by generating a new project and running `ng serve --serve-path .` from the freshly generated project.

The output of my `ng --version` is:

> Angular CLI: 6.0.8
> Node: 10.6.0
> OS: win32 x64
> Angular: 6.0.7
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.6.8
> @angular-devkit/build-angular     0.6.8
> @angular-devkit/build-optimizer   0.6.8
> @angular-devkit/core              0.6.8
> @angular-devkit/schematics        0.6.8
> @angular/cli                      6.0.8
> @ngtools/webpack                  6.0.8
> @schematics/angular               0.6.8
> @schematics/update                0.6.8
> rxjs                              6.2.1
> typescript                        2.7.2
> webpack                           4.8.3
> 


I may very well be misunderstanding the usage and intent of the --serve-path flag in this use case, so my apologies in advance.

**Comment by knrt10** [comment] 2018-08-22 11:12
Same error `Refused to apply style from 'http://localhost:3000/styles.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.` I even tried `<base href="/">` but it didn't worked. Does someone have any idea how to make it work?

**Comment by Dharmendert20** [comment] 2018-08-22 11:26
Use "text/html" in link tag
<link rel="stylesheet" href="#" type="text/html" >

It will work.

**Comment by shauryac** [comment] 2018-09-14 03:53
I'm running into same issue. Any help , plz-
https://stackoverflow.com/questions/52323908/refused-to-execute-script-runtime-js-because-mime-type-is-not-executable

**Comment by Dharmendert20** [comment] 2018-09-14 05:11
Hi there,

Please add text/html in link tag
<link rel="stylesheet" href="#" type="text/html" >

Regards
Dharmender

**Comment by shauryac** [comment] 2018-09-14 14:43
@Dharmendert20 thanks for reply. Did you look at my generated index.html ? It has the following link tag:
` <link rel="icon" type="image/x-icon" href="favicon.ico">`
The exact error: Refused to execute script from 'http://localhost:63342/runtime.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

 I don't think it makes sense to change the type for link. The issue is with <script> tag that gets generated on ng build in the index.html. Changing the type in script from text/javascript to text/html removes these errors when inspect. But it doesn't show anything on UI .

**Comment by Dharmendert20** [comment] 2018-09-14 15:34
Hye Surya thanks for asking,

Can you give me the screenshot of your html head tag?
I want to see your all scripts which you put in then i will analys.

Generally this error occurs when you forget to mention "text/html" in type
attribute of scripts tag or base href tag.

**Comment by shauryac** [comment] 2018-09-14 15:55
@Dharmendert20 - Below is the actual index.html . As I mentioned on changing <script type> to "text/html" the error goes away(browser-> inspect ->console). But then on tomcat startup I dont see any UI associated with it.

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Welcome App</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="runtime.js"></script><script type="text/javascript" src="polyfills.js"></script><script type="text/javascript" src="styles.js"></script><script type="text/javascript" src="vendor.js"></script><script type="text/javascript" src="main.js"></script></body>
</html>

```

Here are Angular files in project structure

![image](https://user-images.githubusercontent.com/14253414/45561176-b3c5c080-b80c-11e8-860f-f8c7daebf6e3.png)

**Comment by alan-agius4** [comment] 2018-09-18 16:58
Closing as no re-production was provided.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2018-09-18 16:58 UTC
Labels: comp: devkit/build-angular, need: repro steps

**Comment by janhurst** [comment] 2018-09-19 14:15
@alan-agius4 I provided a repro above

**Comment by valscan** [comment] 2018-09-20 10:51
The mime types error proved to be a red-herring. Fixed by escaping the backslash on the end of the --deploy-url value in package.json. Previously hadn't needed escaping.

**Comment by valscan** [comment] 2018-09-20 10:58
Correction - add forward slash to url.

**Comment by valscan** [comment] 2018-09-20 11:00
Mime types error was a red-herring for us. Fixed by adding forward slash to --deploy-url value in package.json. Forward slash on end of value not previously required.

**Comment by FloNeu** [comment] 2018-09-25 13:29
@alan-agius4 Reopen! Please! Also having this issue...

**Comment by prasworld** [comment] 2018-10-22 17:40
> @TimMeissner I had the same issue (js file in script tag from assets folder) where the script tag was being dynamically generated, and was using 'text/javascript' as the type. Changing it to 'application/javascript' fixed it.

How can I change a script tag when it is being generated by Htmlscriptelement?

**Comment by danutzcodrescu** [comment] 2018-10-27 15:58
Using markercluster v1.4, I have managed to make it work in Angular 7 by doing this:
``` import * as L from 'leaflet';
import 'leaflet.markercluster/dist/leaflet.markercluster';```

**Comment by tobiasfiechter** [comment] 2018-10-29 16:09
I had the same problem, but by removing the "--servePath" or "serve-path" parameter and adding a title in my root component and ggiving this title as argument to "ng serve" I got the same result but without error.

app.component.ts:
```
export class AppComponent {
    title = 'my-fancy-title';
}
```
package.json:
```
"scripts": {
    "ng": "ng",
    "start": "ng serve my-fancy-title"
}
```

**Comment by ThisGuyRghtHereee** [comment] 2019-03-19 17:24
> Mime types error was a red-herring for us. Fixed by adding forward slash to --deploy-url value in package.json. Forward slash on end of value not previously required.

I'm specifically having an issue with stylesheets loading on child routes of different modules.
Say you have a lazy loaded module APP -> Child Module (/route)
with sub routes App Module -> Child Module (/route) -> Sub route (/route/sub-route)
The stylesheets source was ('stylesheet-asdf1234.css') and is now ('sub-route/stylesheet-asdf1234.css').
Clearly that doesn't exist, so you get the error about MIME type being html, not css. If you try that url I get caught in my PageNotFound component ('**' path).
`Refused to apply style from 'http://localhost:4200/sub-route/styles.e7ed8ba15a7569f72520.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

This only happens when I run a production build. I never have to specify --deploy-url / running development mode (ng serve).

Explainging the above a bit more: my application loads fine with styles when I load http://localhost:4200 (/). Navigating to any first level route (/route) has no issue. Loading routes off those (/route/child) has no issue until you hit Refresh in Chrome. Bam! Mime type error (wrong source for css, as listed above).

My configuration:
base href in index.html is `<base href="/">`
base href in tsconfig.json > compilerOptions > "baseUrl": "./"
Not sure where else this would be set..

**Comment by C0rporeus** [comment] 2019-05-08 06:42
> > El error de los tipos Mime fue una pista falsa para nosotros. Se corrigió agregando una barra inclinada al valor --deploy-url en package.json. Barra diagonal hacia adelante al final del valor no requerido previamente.
> 
> Tengo un problema específico con las hojas de estilo que se cargan en rutas secundarias de diferentes módulos. 
> Supongamos que tiene una APLICACIÓN de módulo con carga lenta -> Módulo 
> secundario (/ ruta) con rutas secundarias Módulo de aplicación -> Módulo secundario (/ ruta) -> Ruta secundaria (/ ruta / ruta secundaria) 
> La fuente de las hojas de estilo fue ('stylesheet-asdf1234 .css ') y es ahora (' sub-route / stylesheet-asdf1234.css '). 
> Claramente eso no existe, por lo que obtienes el error de que el tipo MIME es html, no css. Si intentas esa URL, quedo atrapado en mi componente PageNotFound (ruta '**').
> `Refused to apply style from 'http://localhost:4200/sub-route/styles.e7ed8ba15a7569f72520.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`
> 
> Esto solo sucede cuando ejecuto una compilación de producción. Nunca tengo que especificar --deploy-url / running development mode (ng serve).
> 
> Explicando un poco más lo anterior: mi aplicación se carga bien con los estilos cuando carga [http: // localhost: 4200](http://localhost:4200) (/). La navegación a cualquier ruta de primer nivel (/ ruta) no tiene ningún problema. Cargar rutas desde esos (/ route / child) no tiene ningún problema hasta que presionas Actualizar en Chrome. Bam! Error de tipo Mime (fuente incorrecta para css, como se indica más arriba).
> 
> Mi configuración: 
> base href en index.html es `<base href="/">`
> base href en tsconfig.json> compilerOptions> "baseUrl": "./" 
> No estoy seguro de dónde más se establecería esto ...


Paradoxically before his answer I decided to add to the base tag "._" (this in the html) and it worked, although I still do not set the assets, the images in the browser are the same as they were invoked in the project ...

**Comment by BabC** [comment] 2019-06-26 09:53
Hi !

I don't know if it will help but I had the exact same issue than the original post from @mohibrahimm. I'm working on a project where we have a main app, based on '/' routes, and a second one based on '/second-app'. We upgraded from Angular 4.4 to 8.0 and the second app wasn't working anymore (errors where the same as the first post).

We fixed it by switching the script in package.json from:
`"start-second": "ng serve [...] --base-href /second-app/"`
to
`"start-second": "ng serve [...] --base-href / --deploy-url /second-app/"`

And adding in the second app main module the provider
` providers: [    {provide: APP_BASE_HREF, useValue: '/second-app/'}]`

It is now working like a charm !

Reading more about --base-href and --deploy-url : [here](https://shekhargulati.com/2017/07/06/angular-4-use-of-base-href-and-deploy-url-build-options/)

**Comment by rudolfolah** [comment] 2019-07-14 00:49
I just ran into this and it looks like the issue is with using differential builds and how builds are created for modern browser: https://angular.io/guide/deployment#differential-loading

>Each script tag has a type="module" or nomodule attribute. Browsers with native support for ES modules only load the scripts with the module type attribute and ignore scripts with the nomodule attribute. Legacy browsers only load the scripts with the nomodule attribute, and ignore the script tags with the module type that load ES modules

Here's how you disable this:

>To explicitly disable differential loading:
>1. Enable the dead or IE browsers in the `browserslist` config file by removing the not keyword in front of them.
>2. Set the target in the compilerOptions to es5.

and doing the other steps here: https://angular.io/guide/deployment#local-development-in-older-browsers

**Comment by mcaden** [comment] 2019-07-29 18:25
Same as @valscan we had this error and it was a complete red-herring. Adding depoy-url fixed it. We did not encounter this until upgrading to angular 8. Our multiple projects on angular 7 do not have the issue.

**Comment by map612** [comment] 2019-08-14 02:19
If you are hosting the project under a nginx server, try to add below configuration.

        location ~ \.css {
            add_header  Content-Type    text/css;
        }
        location ~ \.js {
           add_header  Content-Type    application/x-javascript;
        }

**Comment by Sairyss** [comment] 2019-08-19 10:59
> So, I don't know if this is the same issue that you guys are having, but I am working with an ejected project and, in my efforts, I noticed that, in the webpack.config.development.js file, the BaseHrefWebpackPlugin was being called with an empty parameters object:
> 
> ```js
>     new BaseHrefWebpackPlugin({}),
> ```
> 
> So I changed it to:
> 
> ```js
>     new BaseHrefWebpackPlugin({baseHref: baseHref}),
> ```
> 
> And set the constant declared at the beginning of the file to:
> 
> ```js
> const baseHref = "/";
> ```
> 
> And it started working flawlessly. Again, no idea if that is what is going on for you, as I see you are working on an un-ejected project, but hopefully it helps somehow!

Had same issue with React, setting  "homepage" in package.json to "/" helped.

` "homepage": "/"`
