### ISSUE TITLE
[Feature Request] Provide a way to hook into Webpack compilation process

### ISSUE THREAD

**Issue by texel** [angular/angular-cli#5408] opened 2017-03-14 00:11 UTC
I need to load different types of assets in templates and use Webpack plugins which aren't supported by Angular CLI out of the box. Right now my only option for customizing the compilation process is to fork the Angular CLI project and use my own custom version.

Would it be possible to expose configuration such that I'm able to inject my own Webpack plugin during the build process? If so, I could keep the surface area of my customizations small and support my use cases while also being able to respond to breaking upstream changes in Angular CLI.

I'm willing to flesh this idea out more and contribute a PR, but I'd be interested in getting people's opinions and would also like to know the current state of ongoing extensibility discussions and how this plays into them (#2906 for instance).

**Comment by Meligy** [comment] 2017-03-14 04:26
This is considered for v2 of the CLI. No design yet so feel free to kick it off with your ideas.

For v1, the available way is `ng eject`.

**Comment by filipesilva** [comment] 2017-03-18 12:51
Dupe of https://github.com/angular/angular-cli/issues/1656. For 2.0 we're looking at having an addon system to what allow hooks.

As @Meligy said, you can use `ng eject` as well.

**Closed by filipesilva** 2017-03-18 12:51 UTC
