### ISSUE TITLE
Upgrading from AngularJS 1.x to Angular9 (lazy load) increases bundle size

### ISSUE THREAD

**Issue by dionisoros** [angular/angular-cli#17184] opened 2020-03-10 13:05 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

Upgrading from AngularJS 1.7 to Angular9 **increases** significantly my **bundle** size and I don't know exactly what should I have to do in order to have a performant one. I have followed Angular doc https://angular.io/guide/upgrade#lazy-loading-angularjs and I've been choosing the idea of lazy load by creating a service to lazy load AngularJS and creating a component to render AngularJS content. So my app is split in 2: app (the angular 9 app) & app-ajs (angular 1.7 module lazy load). Do you have some advice for me?

## 🔬 Minimal Reproduction
ng build --prod

## 🔥 Exception or Error
<pre><code>
chunk {2} polyfills-es2015.2833a368ca73de6537c1.js (polyfills) 36.1 kB [initial] [rendered]
chunk {3} polyfills-es5.395be9279c34c7a831c3.js (polyfills-es5) 128 kB [initial] [rendered]
chunk {0} runtime-es2015.6a6f96a035de1c5e6327.js (runtime) 2.26 kB [entry] [rendered]
chunk {0} runtime-es5.6a6f96a035de1c5e6327.js (runtime) 2.26 kB [entry] [rendered]
chunk {1} main-es2015.d9165050abbfeb653c6a.js (main) 511 kB [initial] [rendered]
chunk {1} main-es5.d9165050abbfeb653c6a.js (main) 593 kB [initial] [rendered]
chunk {5} 5-es2015.7829d7a94f7463041b34.js () 3.76 MB  [rendered]
chunk {5} 5-es5.7829d7a94f7463041b34.js () 3.79 MB  [rendered]
chunk {6} 6-es2015.ebb14112c61f83a5506f.js () 41.7 kB  [rendered]
chunk {6} 6-es5.ebb14112c61f83a5506f.js () 43.7 kB  [rendered]
chunk {4} styles.3813771ffed65dd17680.css (styles) 490 kB [initial] [rendered]
chunk {scripts} scripts.88a6e8bd2f1d6aefcaa0.js (scripts) 233 kB [entry] [rendered]

</code></pre>

Seems like **5-es2015** and **5-es5** are pretty big and probably that's because I have a lot of code in **app-ajs** (angular 1) module. What do you think?

**Comment by clydin** [comment] 2020-03-10 14:38
Can you please provide the output of the `ng version` command as well as the `production` configuration section for the project from the `angular.json` file?
The build output shown above does not appear to be the output from a build that uses the production options contained within a newly generated project. The `--prod` command flag is an alias for `--configuration=production`.

**Comment by dionisoros** [comment] 2020-03-10 19:11
@clydin 
`Angular CLI: 8.1.2
Node: 13.0.1
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.2
@angular-devkit/core         8.1.2
@angular-devkit/schematics   8.1.2
@schematics/angular          8.1.2
@schematics/update           0.801.2
rxjs                         6.4.0`

**angular.json** -> 
` "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }
          }`

**Comment by clydin** [comment] 2020-03-11 01:03
That configuration does not appear to align with the built output.  For example, the configuration specifies no vendor files and no source maps; both of which are present in the output shown above.
Can you confirm that the project being built has this production configuration? Was `ng build --prod` the command entered on the terminal or was `npm run build --prod` (or similar) used?

The version output also appears to be from an older version of Angular CLI 8 and not 9.  Was the `ng version` command run within the project?

**Comment by dionisoros** [comment] 2020-03-11 08:27
Sorry @clydin ! MYU 

> Angular CLI: 8.3.6
Node: 13.0.1
OS: linux x64
Angular: 9.0.0-next.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

And the angular.json production: 

>             "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }

**Comment by dionisoros** [comment] 2020-03-11 08:45
@clydin it was my mistake, I ran "npm run build" which is "ng build" in my case, without `--prod` flag and that was the problem. Now I have these bundles: 

> chunk {0} runtime-es2015.6a6f96a035de1c5e6327.js (runtime) 2.26 kB [entry] [rendered]
chunk {0} runtime-es5.6a6f96a035de1c5e6327.js (runtime) 2.26 kB [entry] [rendered]
chunk {2} polyfills-es2015.2833a368ca73de6537c1.js (polyfills) 36.1 kB [initial] [rendered]
chunk {6} 6-es2015.ebb14112c61f83a5506f.js () 41.7 kB  [rendered]
chunk {6} 6-es5.ebb14112c61f83a5506f.js () 43.7 kB  [rendered]
chunk {3} polyfills-es5.395be9279c34c7a831c3.js (polyfills-es5) 128 kB [initial] [rendered]
chunk {1} main-es2015.d9165050abbfeb653c6a.js (main) 511 kB [initial] [rendered]
chunk {1} main-es5.d9165050abbfeb653c6a.js (main) 593 kB [initial] [rendered]
chunk {5} 5-es2015.7829d7a94f7463041b34.js () 3.76 MB  [rendered]
chunk {5} 5-es5.7829d7a94f7463041b34.js () 3.79 MB  [rendered]
chunk {4} styles.3813771ffed65dd17680.css (styles) 490 kB [initial] [rendered]
chunk {scripts} scripts.88a6e8bd2f1d6aefcaa0.js (scripts) 233 kB [entry] [rendered]

**Comment by dionisoros** [comment] 2020-03-11 14:22
@clydin I've just updated the description, thank you!

**Comment by alan-agius4** [comment] 2020-07-08 12:40
@dionisoros, 
> Seems like only 5-es2015 and 5-es5 are very big, most of the functionality I have in angular1-module and I think that's the problem, a lot of es6 code & libraries there. What do you think?

Likely that's reason why that file is large, unfortunately there is not much we can do in this regards, especially without a reproduction it's hard to tell whats happening exactly.

I am going to close this, since this is not actionable from our end.

**Closed by alan-agius4** 2020-07-08 12:40 UTC
Labels: comp: etc/misc, need: more info, triage #1

**Comment by dionisoros** [comment] 2020-07-08 12:54
@alan-agius4  Forgot to mention the fix. 
So, using **gzip** was a good solution in order to reduce **5-es2015**  from almost **4mb** to **1mb**
