### ISSUE TITLE
Two or more projects are using identical roots. Unable to determine project using current working directory. Using default workspace project instead.

### ISSUE THREAD

**Issue by NikitaPooja** [angular/angular-cli#14842] opened 2019-06-20 11:22 UTC
I am receiving below warning when running command `ng generate module test --routing `

Two or more projects are using identical roots. Unable to determine project using current working directory. Using default workspace project instead.
Two or more projects are using identical roots. Unable to determine project using current working directory. Using default workspace project instead.

Try Out: -
I have solved my problem by specifying the root property of my project to e2e in angular.json file.
That is I changed this:
 "Gene": {
      "root": "e2e"
....
by default root property of my project is empty like below
"Gene": {
      "root": ""
....

When I specify the root property of my project to e2e in angular.json file then please tell me which issue is occur in my project. 
How to solve this problem without specifying the root property of my project to e2e??

**Comment by alan-agius4** [comment] 2019-06-20 13:15
Duplicate of #11532

**Closed by alan-agius4** 2019-06-20 13:15 UTC
