### ISSUE TITLE
ng build lib --watch output css not changes sometimes

### ISSUE THREAD

**Issue by kolkov** [angular/angular-cli#16272] opened 2019-11-23 12:08 UTC
Hi! If I change `scss` file in library, app refreshes, but style not changes sometimes.

```
Angular CLI: 9.0.0-rc.3
Node: 12.13.1
OS: win32 x64
Angular: 9.0.0-rc.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.3
@angular-devkit/build-angular      0.900.0-rc.3
@angular-devkit/build-ng-packagr   0.900.0-rc.3
@angular-devkit/build-optimizer    0.900.0-rc.3
@angular-devkit/build-webpack      0.900.0-rc.3
@angular-devkit/core               9.0.0-rc.3
@angular-devkit/schematics         9.0.0-rc.3
@ngtools/webpack                   9.0.0-rc.3
@schematics/angular                9.0.0-rc.3
@schematics/update                 0.900.0-rc.3
ng-packagr                         9.0.0-rc.1
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
```

**Comment by kolkov** [comment] 2019-11-23 15:35
But if I remove or add some character, this workes with refresh.

**Comment by alan-agius4** [comment] 2019-11-23 18:31
Hi @kolkov, can you please clarify if correct css is not reflected in the consuming application or at a library level in the dist folder?

**Comment by kolkov** [comment] 2019-11-23 21:08
@alan-agius4 If I understand correctly lib compiles properly. And I can't debug my lib. I can't see debug info in chrome dev tools.

![image](https://user-images.githubusercontent.com/3740898/69485255-fdb52800-0e4d-11ea-8d94-30d1eef475e9.png)

I remove `!important;` from host, but I still see:

![image](https://user-images.githubusercontent.com/3740898/69485267-14f41580-0e4e-11ea-9e9b-66dae157b593.png)

and in lib folder I see:

![image](https://user-images.githubusercontent.com/3740898/69485273-2e955d00-0e4e-11ea-93a3-7b23b55beb74.png)

**Comment by alan-agius4** [comment] 2019-11-24 12:22
Mostly likely this is a duplicate of https://github.com/angular/angular-cli/issues/13588

Will take a look in the coming days

**Comment by alan-agius4** [comment] 2019-11-25 19:00
I had a look at it, and it seems not related to the issue above, also as mentioned above by the reported it doesn't happen consistently.

The problem seems to be related and webpack notifications to the browser. This is being the changes are in the served bundle it's just not reflected in the browser, as when a user does hit CTRL + F5 the style change is visible.

**Comment by kolkov** [comment] 2019-11-28 10:51
This fixed in rc.4. thanks!

**Comment by alan-agius4** [comment] 2019-11-28 10:57
In that case I am going to close the issue. 

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2019-11-28 10:57 UTC
Labels: comp: devkit/build-angular, freq1: low, severity3: broken, type: bug/fix
