### ISSUE TITLE
Chunks are not gzipped in production

### ISSUE THREAD

**Issue by mwawrusch** [angular/angular-cli#2340] opened 2016-09-25 12:29 UTC
**When using lazy loading modules the resulting chunks (like 0.59ea61d3b756000074ac.chunk.js ) are not gzipped.**

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**Yosemite**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

**angular-cli: 1.0.0-beta.15
node: 6.1.0
os: darwin x64**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

**Create an app with a lazy loaded module. run ng build --prod**

4. The log given by the failure. Normally this include a stack trace and some
   more information.

n/a

5. Mention any other details that might be useful.

n/a

**Comment by mrgoos** [comment] 2016-09-25 12:32
Could be duplicate of #2028?

**Comment by mwawrusch** [comment] 2016-09-25 13:00
@mrgoos I think it's different, after further investigation I noticed that some chunks are gzipped, others not

```
-rw-r--r--   1 mwawrusch  staff     2981 Sep 25 05:58 0.59ea61d3b756000074ac.chunk.js
-rw-r--r--   1 mwawrusch  staff    57620 Sep 25 05:58 012cf6a10129e2275d79d6adac7f3b02.woff
-rw-r--r--   1 mwawrusch  staff   742949 Sep 25 05:58 054fa50baa6598a7bf0c6deec135d3a4.svg
-rw-r--r--   1 mwawrusch  staff   183252 Sep 25 05:58 056caeabe95749fe2b973bb9a0cd0776.ttf
-rw-r--r--   1 mwawrusch  staff    89432 Sep 25 05:58 081b11ebaca8ad30fd092e01451015dc.woff
-rw-r--r--   1 mwawrusch  staff    39810 Sep 25 05:58 1.42dcada3952637b70f07.chunk.js
-rw-r--r--   1 mwawrusch  staff    12614 Sep 25 05:58 1.42dcada3952637b70f07.chunk.js.gz
-rw-r--r--   1 mwawrusch  staff   185004 Sep 25 05:58 11b5cc9584f2c007a22966a031ead20e.ttf
-rw-r--r--   1 mwawrusch  staff    21893 Sep 25 05:58 183079184d96a491f16e3cc70414975d.eot
-rw-r--r--   1 mwawrusch  staff   767510 Sep 25 05:58 1a9e39e536aed26b863b243e68f97e3a.svg
-rw-r--r--   1 mwawrusch  staff   776042 Sep 25 05:58 1f37c7545ae9f63d2279f99875678396.svg
-rw-r--r--   1 mwawrusch  staff    17374 Sep 25 05:58 2.ff4ce882dc16f9a25557.chunk.js
-rw-r--r--   1 mwawrusch  staff     6098 Sep 25 05:58 2.ff4ce882dc16f9a25557.chunk.js.gz
```

**Comment by deebloo** [comment] 2016-09-26 16:06
@mwawrusch I think this may be down to how large the chunks are. I know that there is a threshold where compressing the file will actually hurt performance. I would check and see how large the chunks are and see if they are gzipped as they get bigger.

**Comment by mwawrusch** [comment] 2016-09-26 16:20
That seems like a reasonable assumption, as only the smaller files are kept unzipped.
I propose to always zip files, to avoid potential deployment problems. 

Example:
A file shrinks below the threshold and is no longer zipped. However it remains on S3 and cloudfront as the zipped version, which is now no longer the current version. Those kind of problems are incredibly expensive to debug.

**Comment by filipesilva** [comment] 2016-10-05 15:07
Closing as dupe of https://github.com/angular/angular-cli/issues/2028, better to keep gzip discussion there.

**Closed by filipesilva** 2016-10-05 15:07 UTC
