### ISSUE TITLE
Cannot create new app from scratch with ng new my-app. Error: input.mergeMap is not a function

### ISSUE THREAD

**Issue by AndreMantas** [angular/angular-cli#8823] opened 2017-12-10 14:37 UTC
### Versions
```
$ ng -v
_                      _                 ____ _     ___
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
/ △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
|___/

Angular CLI: 1.6.0
Node: 8.9.3
OS: win32 x64
Angular:
...
```

Windows 10

### Repro steps

* Install Node LTS version
* npm install -g @angular/cli
* ng new my-app

### Observed behavior
```
input.mergeMap is not a function
TypeError: input.mergeMap is not a function
    at Object.callRule (C:\Users\andre.mantas\node_modules\@angular-devkit\schematics\src\rules\call.js:70:18)
    at SchematicImpl.call (C:\Users\andre.mantas\node_modules\@angular-devkit\schematics\src\engine\schematic.js:35:23)
    at Promise (C:\Users\andre.mantas\node_modules\@angular\cli\tasks\schematic-run.js:73:23)
    at new Promise (<anonymous>)
    at Class.run (C:\Users\andre.mantas\node_modules\@angular\cli\tasks\schematic-run.js:72:16)
    at Class.run (C:\Users\andre.mantas\node_modules\@angular\cli\tasks\init.js:71:33)
    at Class.run (C:\Users\andre.mantas\node_modules\@angular\cli\commands\new.js:134:25)
    at resolve (C:\Users\andre.mantas\node_modules\@angular\cli\ember-cli\lib\models\command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (C:\Users\andre.mantas\node_modules\@angular\cli\ember-cli\lib\models\command.js:240:12)
```

### Desired behavior

Create a new angular app without errors

### Mention any other details that might be useful (optional)

I don't know if this is useful but here is the output of installing CLI
```
$ npm install -g @angular/cli
C:\Users\andre.mantas\AppData\Roaming\npm\ng -> C:\Users\andre.mantas\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
npm WARN @schematics/angular@0.1.10 requires a peer of @angular-devkit/schematics@0.0.40 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/schematics@0.0.10 requires a peer of @angular-devkit/schematics@0.0.40 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/cli@1.6.0
added 115 packages and updated 1 package in 36.156s
```

**Comment by TroyMurphy** [comment] 2017-12-10 16:18
Similar traceback on calling ng generate component using MacOSX

**Comment by asalhani** [comment] 2017-12-10 17:45
Similar error when I try to use ng generate component using Windows 10. Please advice

**Comment by TroyMurphy** [comment] 2017-12-10 19:10
I reset my angular dependencies to what I was using before (5.0.2) and deleted node_modules and did a clean install which has solved my problem, at least for now. It looks like I had some incompatible setup between @angular-devkit/schematics and my @angular install.

**Comment by gabigeo** [comment] 2017-12-11 15:15
Check your package.json in "dependencies" and get the version required for "@angular-devkit/schematics".
Then npm install it:
npm install @angular-devkit/schematics@0.0.XX

After this "ng generate" will work.

**Comment by Brocco** [comment] 2017-12-11 17:29
Closing...
Duplicate of #8782

**Closed by Brocco** 2017-12-11 17:29 UTC

**Comment by AndreMantas** [comment] 2017-12-12 10:56
I can't change my package.json because i have no project... How is this duplicate?

**Comment by gabigeo** [comment] 2017-12-12 11:23
Another way to find what version of schematics you need is to look at the warnings received at initial npm install. (You can delete node_modules and npm install again)
For example I've got two warnings about schematics with different versions.
Install the oldest. 
In my case it worked with:
`npm install @angular-devkit/schematics@0.0.34`

**Comment by Reema4692** [comment] 2017-12-13 13:07
I was facing the same issue and "npm install @angular-devkit/schematics@0.0.34" worked for me on MAC. Thanks @gabigeo.

**Comment by srihari-ananthakrishna** [comment] 2018-01-04 09:56
Worked for me as @gabigeo has mentioned! Thanks!

**Comment by mohdabsar** [comment] 2018-09-11 19:14
my error is:
npm ERR! Unexpected end of JSON input while parsing near '...ript","version":"1.0.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-09-11T19_05_56_894Z-debug.log
Package install failed, see above.

C:\Users\user> C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-09-11T19_05_56_894Z-debug.log
plzz reply me as soon as possible
