### ISSUE TITLE
npm WARN deprecated source-map-resolve@0.6.0 -- dependencies: deprecated warning

### ISSUE THREAD

**Issue by pawan-gwebs** [angular/angular-cli#22788] opened 2022-03-02 10:04 UTC
### What are you trying to do?

I'm getting warning "npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated". This warning is from the dependencies "stylus" of package "@angular-devkit/build-angular".

Will it be fix in next release?

### What troubleshooting steps have you tried?

Warning comes in production build or during "npm install"
npm i
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated

### Reproduction

Steps to reproduce:
1. npm i
2. 

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by alan-agius4** [comment] 2022-03-02 11:33
Duplicate of https://github.com/angular/angular-cli/issues/22748

**Closed by alan-agius4** 2022-03-02 11:33 UTC
Labels: needs triage, troubleshooting
