### ISSUE TITLE
Can not isntall angular-cli or use ng command in MAC El-Capitan

### ISSUE THREAD

**Issue by dipcse07** [angular/angular-cli#2324] opened 2016-09-24 05:24 UTC
I am using osX El Capitan 
my node version is 6.6.0

When i try to install angular-cli  with sudo there is so many warnings and error and after the command completes the installation when is write ng --version it gives me these errors  :(

MDSAZIDs-iMac:~ MYMAC$ ng --version

fs.js:640 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode); ^

TypeError: path must be a string or Buffer

at TypeError (native)
at Object.fs.openSync (fs.js:640:18)
at Object.fs.readFileSync (fs.js:508:33)
at Function.Version.fromProject (/usr/local/lib/node_modules/angular-cli/upgrade/version.js:87:31)
at Function.Version.isPreWebpack (/usr/local/lib/node_modules/angular-cli/upgrade/version.js:111:31)
at Function.Version.assertPostWebpackVersion (/usr/local/lib/node_modules/angular-cli/upgrade/version.js:97:18)
at /usr/local/lib/node_modules/angular-cli/bin/ng:25:15
at /usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:44:21
at ondir (/usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:187:31)
at /usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:153:39

**Comment by alizzen** [comment] 2016-09-25 10:31
same issue

**Comment by erezBk** [comment] 2016-09-25 16:05
same issue ... 
mac  - el-capitan
node - v4.5.0
npm - 3.10.8

**Comment by matt-erhart** [comment] 2016-09-29 21:05
Same on windows 10, node v6.6.0, npm 3.9.6.

**Comment by vadost** [comment] 2016-10-01 09:28
Same on ubuntu 14.04, node v6.7.0, npm 3.10.3. Please help!

**Comment by filipesilva** [comment] 2016-10-08 23:38
Dupe of https://github.com/angular/angular-cli/pull/2178

**Closed by filipesilva** 2016-10-08 23:38 UTC

**Comment by santlico** [comment] 2017-09-17 05:03
for me i'm using mac and i fix it by using 
sudo npm install -g angular-cli

i hope it's help u :)
