### ISSUE TITLE
Option for ng new to use yarn instead of npm install

### ISSUE THREAD

**Issue by adi** [angular/angular-cli#2651] opened 2016-10-11 18:01 UTC
Is it possible to have a ng new option that replaces the use of npm install with yarn ?

Thank you,
Adrian

**Comment by intellix** [comment] 2016-10-11 23:33
Just done a few tests locally with a new angular-cli project and the theory and results are staggering.

yarn: 120s and then 45s after deleting node_modules folder
npm: 155s and always

After an install already to determine there's nothing to do:
yarn: 0.3s
npm: 30s

In my opinion yarn should outright be the default and only way to install, even based on things like lock files by default and deterministic results.

**Comment by kylecordes** [comment] 2016-10-12 00:16
I don't have the timings in front of me, but I saw a bigger timing difference than your first pair of numbers above. Of course it varies by hardware etc.

It seems to me that yarn is a very helpful leap forward in the NPM world. Something we have been waiting for for a while, some fundamental improvements (determinism, so important) as well as the practical benefit of being faster. The most pleasing part is that it did not require replacing the repositories or metadata format, this is all benefit obtained by writing different code to run in the client. Of course it's also important to remember that it was just released, and has some ways to go to reach something close to feature parity.

Of relevance to Angular-CLI specifically: CLI pushes NPM quite hard.

* Substantial tree of transitive dependencies
* Heavily used on Windows, where many NPM challenges are exacerbated
* Many people arrive here because they are trying to adopt Angular, and they are grabbing CLI as the very slick tooling to do so, and as a result they are experiencing NPM for the first time, with CLI
* CLI is under ongoing (and extremely helpful) development, so many users uninstall and reinstall regularly

As a result of all these things, yarn is especially big win for CLI, more so than for projects that use fewer dependencies, or changing less often, or are typically used by very experienced NPM users, etc.

**Comment by clydin** [comment] 2016-10-12 18:46
For anyone that wants to use yarn right now, no code changes are necessary.
Just use `--skip-npm` with new/init and then run yarn in the project directory.

**Comment by victornoel** [comment] 2016-10-12 20:35
@clydin that's not enough, any of the commands run by ng (such as test or e2e) are run using npm, just do a `grep -r npm` in angular-cli source code and you will see.
Still, I don't' think it asks for a lot of change to either switch to yarn or have the package manager backend be switchable on demand :)

**Comment by clydin** [comment] 2016-10-12 21:22
@victornoel actually it is.  NPM is simply being used as a task runner in those cases.

**Comment by kylecordes** [comment] 2016-10-12 21:44
I was thinking about how it might be possible for CLI to provide the best experience by default. Whatever experience arrives by default is what most brand-new users will have, and it would be **great** if those new users could have the yard experience.

How about this?

* By default, and if it is available, use ```yard```
* If yard is not available, by default, use ```npm install```
* If ```--skip-npm```, do nothing; user can then run whichever command they want explicitly afterward

The instructions to get started could then be:

```
npm i -g yard
yard global add angular-cli
ng new blah-blah
...
```

(Or similar, I typed the above from memory from yesterday and it might not be exactly correct.)

The above idea reflects a philosophy of "likely best results by default, other things optional". An alternative philosophy is "old behavior by default, new behavior optional".

**Comment by intellix** [comment] 2016-10-12 23:46
yarn :) sounds good to me to choose it if it exists

**Comment by victornoel** [comment] 2016-10-13 07:18
@clydin maybe we are not talking of the same thing :) I realise this issue is about ng new, not ng in general, that's why my comment is not relevant maybe.
Simply, when using other commands than ng new, npm is used, for example when running e2e, link-cli or lint.

**Comment by clydin** [comment] 2016-10-13 17:59
Of the commands that use npm, only `new`, `init`, and `link-cli` use the package management functionality of npm and would therefore interfere with yarn.  The `e2e` and `lint` use `npm run` which essentially just executes the relevant script.  `new` and `init` are handled by using `--skip-npm`.  That leaves `link-cli` which in general should not be used.  It only provides value to someone developing the CLI itself; and in that case it is not really need as it can be done manually afterwards.

This doesn't mean first-class support for yarn wouldn't be useful (at least in the long-term).  Especially if yarn doesn't succumb to the package linking bug that renders `link-cli` practically useless.

**Comment by pi0** [comment] 2016-10-14 11:12
Please checkout [YarNPM](https://github.com/pi0/yarnpm) :)

**Comment by filipesilva** [comment] 2016-10-14 22:36
There are only two real commands that use `npm install`, `ng new` and `ng init`. On both of them you can opt to forego `npm` usage by passing in the `--skip-npm` flag. This means that if you want to use `yarn`, nothing really stops you now.

I recognize that the speed improvements are dramatic, which is awesome. Install speed is important because no one wants to wait long while starting a new project.

So, hypothetically, Yarn usage would help solve the install problem. Wouldn't address the cause, which is the very large dependency tree, but would help minimize the symptoms.

Now let's talk about the downsides. 

It's a new system dependency, of which we only have two at the moment: node4 and npm3. A lot of people don't even realize they need npm3, resulting in a fair number of issues filed. Expecting users to also have yarn is... not really something that's reasonable.

It's another new tech, undoubtedly with its fair share of issues like anything else. This repo already gets a lot of npm issues, not sure I'm looking forward to also have yarn issues being filed against the CLI.

Scope is also something to be considered. Either it's the default and affects the majority of users, or it's a niche optimization. If you're savvy enough to *want* yarn, you sure are savvy enough to do it manually. To be clear though, no one that's actually participating on this thread is part of the majority. If you've ever looked at the issue CLI issue tracker, you are not part of the majority.

Lastly there's the issue of configuration. A lot of people have npm configured to their needs. Proxies, private repos, whatever. Stuff that they need on their environment, otherwise they cannot work. I don't think yarn offers parity on that front.

For these reasons I am not a big fan of defaulting to yarn. 

Not opposed to having some kind of flag to facilitate yarn usage, but a PR implementing it has to find a way to test it in all CI envs: Linux, OSX and Windows.

**Comment by leonletto** [comment] 2016-10-15 18:44
If there comes a point where this is implemented (when?), you can just add an environment variable to select yarn if you want that eg: export ngpm=yarn.  Then those who want to use it can easily set that and forget it.   The ng-cli developers can then choose the functions which they want to implement yarn support for based on which are consistent.

**Comment by pi0** [comment] 2016-10-15 18:47
@leonletto Aliasing a Nice Classic solution :) But what about not compatible features? (commands are not exactly the same)

**Comment by clydin** [comment] 2016-10-15 18:51
As previously mentioned, nothing needs to be implemented to use yarn right now.  Just use --skip-npm on new/init.

**Comment by gelidus** [comment] 2016-11-20 12:24
I just added this into my `.bashrc`

```bash
ngproj() {
    ng new $1 --skip-npm && cd $1 && yarn
}
```

Usage:
```bash
ngproj proj_name
```

**Comment by beeman** [comment] 2016-12-03 08:53
Great idea @gelidus!

I automated it even further by initializing a git repo, making an initial commit and opening my IDE, as I always tend to do those steps after creating a new project.
 
```
ng-new() {
    ng new $1 --skip-npm && cd $1 && yarn && git init && git add . && git commit -am "Initial commit" && wstorm .
}
```

**Comment by d3viant0ne** [comment] 2016-12-18 06:00
Personally I partially agree with @filipesilva. Yarn shouldn't be the default, for all it's strengths I am sure us Yarn users are in the minority.

That said, I have seen the deterministic nature of how yarn operates break cli projects when you install with it. Perhaps a more reasonable path would be to simply validate that you can run the Travis validations on a matrix using yarn for the install.

That would ensure it works properly for those of us that want to use it without adding a dependency for those that don't.

**Comment by gelidus** [comment] 2016-12-23 11:23
We recently ran into a lot of problems using yarn :( our builds are sometimes failing on segfaults. There are open issues on yarn for this. Check twice if you want to use yarn within wercker/travis.

Yarn may not be mature enough at this moment.

**Comment by hansl** [comment] 2017-01-20 19:44
We're going to move this discussion to the tracking issue #3886. Closing this but you can keep the discussion going.

**Closed by hansl** 2017-01-20 19:44 UTC
Labels: type: discussion

**Comment by kuncevic** [comment] 2017-03-28 04:24
Just tried to use yarn, again, there are so much issues using yarn on windows. just jumped back to npm.

**Comment by ricardoemerson** [comment] 2017-05-02 16:10
You can define it as default using:
 `ng set --global packageManager=yarn`

**Comment by larssn** [comment] 2017-07-04 17:36
I'm guessing the benchmarks between npm and yarn will be more similar now that npm5 is out.

**Comment by obfusticatedcode** [comment] 2017-11-07 06:56
You can also get the latest version of yarn using:
`curl -o- -L https://yarnpkg.com/install.sh | bash`
And include @ symbol for angular/cli.
`yarn add global @angular/cli`

**Comment by imzhengfei** [comment] 2018-05-23 03:32
Below commands not work on **angular-cli@6.x** :

```shell
ng new --skip-npm <project>
# or
ng set --global packageManager=yarn
# or
ng config --set packageManager=yarn
# or
ng config --set --global packageManager=yarn
```
I found below command still work on **angular-cli@6.x** :
```shell
ng new --skip-install <project>
```

See: [Angular CLI: Speed up installing dependencies with Yarn](https://yakovfain.com/2016/11/06/angular-cli-speed-up-installing-dependencies-with-yarn/)

**Comment by beeman** [comment] 2018-05-23 03:36
@imzhengfei in my blogpost you can read how to set YARN as default in Angular CLI v6:

https://medium.com/@beeman/using-yarn-with-angular-cli-v6-7f53a7678b93

```
ng config -g cli.packageManager yarn
```
