### ISSUE TITLE
npm install error (angular-cli) 

### ISSUE THREAD

**Issue by kaslioglu** [angular/angular-cli#2647] opened 2016-10-11 15:36 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
node 6.7.0

### Repro steps.
>i can't install angular-cli

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any
[npm-debug.txt](https://github.com/angular/angular-cli/files/522277/npm-debug.txt)

 other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by grizzm0** [comment] 2016-10-11 16:42
Dupe of #2633. Missing git from PATH. Git is currently needed as we're using some packages which haven't been tagged with npm yet.

**Comment by JanStureNielsen** [comment] 2016-10-11 16:44
@kaslioglu -- the GitHub issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.

> 2 info using npm@2.15.9

You need to upgrade; see http://stackoverflow.com/questions/39812448/angular-cli-installation-failure

**Comment by filipesilva** [comment] 2016-10-14 17:10
Closing as the two answers so far should cover the errors described.

**Closed by filipesilva** 2016-10-14 17:10 UTC
