### ISSUE TITLE
'prevent using assets from outside the project' should be configurable

### ISSUE THREAD

**Issue by bartes** [angular/angular-cli#8629] opened 2017-11-24 15:26 UTC
### Desired behavior
https://github.com/angular/angular-cli/commit/64c60313d7c972de870cf5af7c52efbe712e8856
should be optional/configurable.
Some setups with external backends need to have build files generated outside of the project (at least in dev mode). 
For production setup it is somehow ok to build and copy files to outside project location, but that becomes challenging while working in dev watch mode.

so it would be great to have flag for that functionality

### Versions
```
Angular CLI: 1.6.0-rc.0
Node: 9.2.0
OS: darwin x64
Angular: 5.1.0-beta.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.6.0-rc.0
@angular/language-service: 5.1.0-beta.1
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0-rc.0
@schematics/angular: 0.1.7
typescript: 2.5.3
webpack: 3.8.1
```

**Comment by bartes** [comment] 2017-11-24 15:27
I guess this is related https://github.com/angular/angular-cli/issues/8613

**Comment by filipesilva** [comment] 2017-11-27 09:43
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #8613. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-11-27 09:43 UTC
