### ISSUE TITLE
webpack build chain somehow fails with 6.0.0-beta.5

### ISSUE THREAD

**Issue by konsultaner** [angular/angular-cli#10082] opened 2018-03-27 14:14 UTC
### Versions
```
Angular CLI: 1.6.7
Node: 8.10.0
OS: win32 x64
Angular: 6.0.0-beta.7
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

@angular/cdk: 6.0.0-beta.4
@angular/cli: 1.6.7
@angular/compiler-cli: 5.2.9
@angular/language-service: 5.2.9
@angular/material: 6.0.0-beta.4
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
I added a reproducer.

1. unzip
2. `npm install`
3. `ng serve` -> it works
4. update `package.json` from `"@angular/cli": "1.6.7"` to `"@angular/cli": "6.0.0-beta.5"` 
5. `npm install`
6. `ng serve` -> it fails

### Observed behavior
Building an the external dependency fails or are not included with the latest beta5 

### Desired behavior
Should work just as well as it did with 1.6.7
[reproducer.zip](https://github.com/angular/angular-cli/files/1852316/reproducer.zip)

### Extras
It seems like my imported autobahn lib is not compiled into browser code. It's msgpack5 component is the one that makes it fail somehow.

**Comment by robertbaker** [comment] 2018-03-30 12:42
That's because there are breaking changes and simply doing that isn't going to work.

Additionally, just changing that version in project.json just does your local cli, you need to update your global cli as well.

Update to the latest beta for global and local. Then generate a new project with the new cli. Then use a diff tool to update your app. The app layout structure has changed in the latest beta, a few files deleted, added, and the src folder has moved. 

(This is a breaking release, as indicated by the major version bump!)

Please close this issue.

**Comment by konsultaner** [comment] 2018-04-03 06:44
@robertbaker the beta I tried did not generate a angular 6 but an angular 5 project. If the new beta does somthing different, I'll migrate the way you discribed. Thank you!

**Comment by konsultaner** [comment] 2018-04-19 15:32
> Then generate a new project with the new cli. Then use a diff tool to update your app. The app layout structure has changed in the latest beta, a few files deleted, added, and the src folder has moved.

@robertbaker I did what you said but it is still not possible. I created a brand new project with the latest cli (which actually is missing the `rxjs-compat` package) npm installed all my other depandencies including autobahn.js. It compiles perfectly, but the browser still runs into this issue.

I import autobahn like this:

    import {Connection, auth_cra} from 'autobahn';

**Comment by mgechev** [comment] 2018-12-26 19:43
Are you still able to reproduce this issue with the latest version?

**Comment by alan-agius4** [comment] 2019-02-05 11:54
Closing as no further feedback was provided by the reporter.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Closed by alan-agius4** 2019-02-05 11:54 UTC
