### ISSUE TITLE
No support for Webpack resolve.alias 

### ISSUE THREAD

**Issue by andrii-oleksyshyn** [angular/angular-cli#5287] opened 2017-03-07 18:23 UTC
Hello,

It's a copy of issue #5031, it was closed as already implemented but I couldn't manage to make it work.

**Steps to reproduce:**

I've added this to my tsconfig.json:
```
"compilerOptions": {
  "baseUrl": "src",
  "paths": {
      "shared/*": ["app/shared/*"]
  }
}
```

Path to the constants file: `src/app/shared/constants/index.ts`

When I import it as usual `import { testConst } from './shared/constants/index';`, it works fine:

But when I use absolute path, it crashes:
`import { testConst } from 'shared/constants/index';`

Webpack error:
```
ERROR in C:/Projects/myProject/UI/src/app/app.component.ts (2,27): Cannot find module 'shared/constants/index'.)
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'shared/constants/index' in 'C:\Projects\myProject\UI\src\app'
```

Could someone confirm that this feature works? Does it need additional config?

**Comment by antonberezan** [comment] 2017-03-13 15:51
Seems it has nothing to do with #5031. The issue definitely with WebPack config. I've looked through the sources, cli doesn't add resolve.alias in Webpack config. [See here](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/models/webpack-configs/common.ts#L70), it adds node_modules path only. 
So, I decided to add my alias manually in that file and it worked. 

Seems we need to expand angular-cli config for aliases. WDYT guys?

**Comment by andrii-oleksyshyn** [comment] 2017-03-13 20:07
There was already discussion(#1465) regarding expending of angular-cli config and implementing this feature.

**Comment by filipesilva** [comment] 2017-03-17 22:47
Dupe of #5031, I will followup to your question there.

**Closed by filipesilva** 2017-03-17 22:47 UTC

**Comment by thomaswmanion** [comment] 2017-09-18 15:44
Could we reopen this for support for Sass? There doesn't seem to currently be a way to alias CSS...

**Comment by Pkandel** [comment] 2018-01-08 21:51
As @thomaswmanion said, the alias for sass is not working. This is how my path looks like now when I try to import the global `style.scss` file `@import '../../.././styles.scss'`. Looks Weird and the alias does not worked for that :(
