### ISSUE TITLE
TypeError: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.

### ISSUE THREAD

**Issue by luisrodriguesds** [angular/angular-cli#24600] opened 2023-01-24 12:14 UTC
### Command

generate

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I try to use this command

`ng g c modules/shared/component/newComponent`
or
`npm run ng -- g c modules/shared/component/newComponent`

It's dropping me this error. This stared after I updated the dependencies.

Any ideia?

An unhandled exception occurred: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined. 
See "C:\Users\AppData\Local\Temp\ng-F5vgKW\angular-errors.log" for further details.

[error] TypeError: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
    at GenerateCommandModule.getSchematics (C:\www\dashboard\node_modules\@angular\cli\src\commands\generate\cli.js:141:29)
    at getSchematics.next (<anonymous>)
    at GenerateCommandModule.getSchematicsToRegister (C:\www\dashboard\node_modules\@angular\cli\src\commands\generate\cli.js:158:76)
    at async GenerateCommandModule.builder (C:\www\dashboard\node_modules\@angular\cli\src\commands\generate\cli.js:35:55)
    at async runCommand (C:\www\smartex\dashboard\node_modules\@angular\cli\src\command-builder\command-runner.js:113:5)
    at async default_1 (C:\www\smartex\dashboard\node_modules\@angular\cli\lib\cli\index.js:70:16)

![image](https://user-images.githubusercontent.com/42545036/214288365-a05e29b7-c888-41f2-a40f-e909d79b91fe.png)

### Minimal Reproduction

When I try to use this command

`ng g c modules/shared/component/newComponent`

![image](https://user-images.githubusercontent.com/42545036/214288635-649d4180-d632-42cd-8c14-207afb871b53.png)

```
{
  "name": "dashboard",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --localize",
    "build:development": "npm run build -- --configuration=development",
    "build:stage": "npm run build -- --configuration=staging",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "test:ci": "npm run test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI",
    "lint": "ng lint",
    "prettier": "prettier --check \"./**/*.{js,ts,scss,html,yml,json,md}\"",
    "prettier:fix": "prettier --write \"./**/*.{js,ts,scss,html,yml,json,md}\"",
    "e2e": "ng e2e",
    "cypress:open": "cypress open",
    "cypress:run": "cypress run"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^15.1.1",
    "@angular/cdk": "^15.1.1",
    "@angular/common": "^15.1.1",
    "@angular/compiler": "^15.1.1",
    "@angular/core": "^15.1.1",
    "@angular/forms": "^15.1.1",
    "@angular/material": "^15.1.1",
    "@angular/platform-browser": "^15.1.1",
    "@angular/platform-browser-dynamic": "^15.1.1",
    "@angular/router": "^15.1.1",
    "@angular/service-worker": "^15.1.1",
    "@js-temporal/polyfill": "^0.4.3",
    "rxjs": "~7.8.0",
    "tslib": "^2.4.1",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.1.2",
    "@angular-eslint/builder": "15.2.0",
    "@angular-eslint/eslint-plugin": "15.2.0",
    "@angular-eslint/eslint-plugin-template": "15.2.0",
    "@angular-eslint/schematics": "15.2.0",
    "@angular-eslint/template-parser": "15.2.0",
    "@angular/cli": "~15.1.2",
    "@angular/compiler-cli": "^15.1.1",
    "@angular/localize": "^15.1.1",
    "@commitlint/cli": "^17.4.2",
    "@commitlint/config-angular": "^17.4.2",
    "@cypress/schematic": "^2.4.0",
    "@types/jasmine": "~4.3.1",
    "@typescript-eslint/eslint-plugin": "5.48.2",
    "@typescript-eslint/parser": "5.48.2",
    "cypress": "12.3.0",
    "eslint": "^8.32.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "husky": "^8.0.3",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "lint-staged": "^13.1.0",
    "prettier": "^2.8.3",
    "prettier-eslint": "^15.0.1",
    "typescript": "~4.9.4"
  }
}
```

### Exception or Error

```text
[error] TypeError: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
    at GenerateCommandModule.getSchematics (C:\www\dashboard\node_modules\@angular\cli\src\commands\generate\cli.js:141:29)
    at getSchematics.next (<anonymous>)
    at GenerateCommandModule.getSchematicsToRegister (C:\www\dashboard\node_modules\@angular\cli\src\commands\generate\cli.js:158:76)
    at async GenerateCommandModule.builder (C:\www\dashboard\node_modules\@angular\cli\src\commands\generate\cli.js:35:55)
    at async runCommand (C:\www\smartex\dashboard\node_modules\@angular\cli\src\command-builder\command-runner.js:113:5)
    at async default_1 (C:\www\smartex\dashboard\node_modules\@angular\cli\lib\cli\index.js:70:16)
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.1.2
Node: 16.18.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.1.2
@angular/cli                    15.1.2
@schematics/angular             15.1.2
rxjs                            7.6.0
typescript                      4.8.4
```

**Comment by alan-agius4** [comment] 2023-01-24 12:23
Duplicate of https://github.com/angular/angular-cli/issues/24586

**Closed by alan-agius4** 2023-01-24 12:23 UTC
