### ISSUE TITLE
@angular-devkit/build-angular using ora spinner with default "stdErr" stream can break test environments

### ISSUE THREAD

**Issue by julianess** [angular/angular-cli#22642] opened 2022-02-03 09:05 UTC
# 🐞 Bug report

### Command

- [ ] new
- [ ] build
- [ ] serve
- [X] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

This was working in Angular <=10 because the "ora" package was not used to create a beautiful spinner in the console stream.

### Description

The ora spinner is using **process.stderr** as default stream which causes some test runners to fail the entire test execution because there was something written to the stdErr output.
This behavior can be changed to use **process.stdout** instead which should be enough for this kind of logging.

## 🔬 Minimal Reproduction

using e.g. karma 6.3.12

ng test any-library-you-want-to

## 🔥 Exception or Error

There is no actual issue, but this is what the spinner is used for in the test command:
<pre>
<code>\ Generating browser application bundles (phase: building)...
√ Browser application bundle generation complete.</code>
</pre>

I'm sure the spinner is used in other commands, too. But for the most uses cases (e.g. local development) writing to strErr stream is not relevant except for testing strategies. An issue in the stdErr stream could cause test runners to declare the run as failed even all tests succeeded.

## 🌍 Your Environment

<pre>
<code>Angular CLI: 11.2.0
Node: 14.18.2
OS: win32 x64

Angular: 11.2.0

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.18
@angular-devkit/build-angular   0.1102.18
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.18
@schematics/angular             11.2.18
@schematics/update              0.1102.0
ng-packagr                      11.2.0
rxjs                            6.6.3
typescript                      4.0.8</code></pre>

**Anything else relevant?**

This affects all versions of Angular 11+

**Comment by alan-agius4** [comment] 2022-02-03 10:08
Hi @julianess, 

I am sorry about the issue you are experiencing, but this is working as intended. `stderr` is intended to be used to print diagnostics, progress messages and should not be assumed to indicate an error.

This seems to be an issue with your test runner, instead this should rely on the exit codes of the process.

Duplicate of https://github.com/angular/angular-cli/issues/16994, https://github.com/angular/angular-cli/issues/16940 and https://github.com/angular/angular/pull/35310#issuecomment-585185084

**Closed by alan-agius4** 2022-02-03 10:08 UTC

**Comment by julianess** [comment] 2022-02-03 10:33
Hi @alan-agius4,
besides this is a configuration issue on our testrunner maybe, I've never heard about "progress" beeing logged into stdErr stream of node. Where is it described? As I found out on the official node documentation, there is the intention to use it for failing commands and nothing less then real error purpose. Logging progress as "error" seems not to be common.

**Comment by alan-agius4** [comment] 2022-02-03 11:08
> As I found out on the official node documentation, there is the intention to use it for failing commands and nothing less then real error purpose

Mind providing a link?

> I've never heard about "progress" beeing logged into stdErr stream of node. Where is it described?

This is not limited to Node.js, but it's a convention for all languages that diagnostics related logs which progress is one of them are written to stderr.  You can see https://stackoverflow.com/questions/3385201/confused-about-stdin-stdout-and-stderr for more information.

Note: the the Angular CLI is not the only tool that uses stderr to print non errors, example Webpack CLI https://github.com/webpack/webpack-cli/issues/1017#issuecomment-517569237 also does this.

**Comment by julianess** [comment] 2022-02-03 12:42
Not directly mentioning or excluding diagnosis but the way stderr is handled is described in those places (https://nodejs.org/api/process.html#processstderr, https://nodejs.dev/learn/output-to-the-command-line-using-nodejs#stdout-and-stderr). But in my point of view successful diagnosis information should definitely not be part of any error file / stream as the wording "error" already implies. It's the same way as not abusing "console.error" call for any **success** or **progress** messages. I've never seen any Angular related stuff tracking progress as **error** before. So does this spinner just because the default of the underlying package is set so.

**Comment by alan-agius4** [comment] 2022-02-03 15:04
That is a common misconception that stderr should be used for errors because of the name but this is not the case. Progress messages are considered as diagnostic and these typically don't belong in stdout. 

For example POSIX [defines standard error as](http://pubs.opengroup.org/onlinepubs/9699919799/functions/stderr.html)
> for writing diagnostic output

SImilar thread unrelated to Angular and progress bars https://github.com/bazelbuild/bazel/issues/10496.
