### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_applyBodyHighContrastModeCssClasses')

### ISSUE THREAD

**Issue by nikhil1027** [angular/angular-cli#23549] opened 2022-07-13 05:01 UTC
facing same issue as in https://github.com/angular/components/issues/22250
and https://github.com/angular/components/issues/24185

Angular CLI: 11.1.0
Node: 16.15.1
OS: darwin x64

Angular: 11.2.14
... animations, core
Ivy Workspace: Yes

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1101.2
@angular-devkit/build-angular       0.1101.2
@angular-devkit/core                11.1.2
@angular-devkit/schematics          11.1.0 (cli-only)
@angular/cdk                        10.2.7
@angular/common                     11.1.2
@angular/compiler                   11.1.2
@angular/compiler-cli               11.1.2
@angular/forms                      11.1.2
@angular/http                       7.2.16
@angular/language-service           11.1.2
@angular/material                   10.2.7
@angular/platform-browser           11.1.2
@angular/platform-browser-dynamic   11.1.2
@angular/router                     11.1.2
@schematics/angular                 11.1.0 (cli-only)
@schematics/update                  0.1101.0 (cli-only)
rxjs                                6.6.7
typescript                          4.1.6

error:

main-es2015.86f82ddd897ee3dcee6a.js:1 TypeError: Cannot read properties of undefined (reading '_applyBodyHighContrastModeCssClasses')
    at new t (main-es2015.86f82ddd897ee3dcee6a.js:1:2465560)
    at Object.a [as factory] (main-es2015.86f82ddd897ee3dcee6a.js:1:1977349)
    at Zs.hydrate (main-es2015.86f82ddd897ee3dcee6a.js:1:1977894)
    at Zs.get (main-es2015.86f82ddd897ee3dcee6a.js:1:1975800)
    at main-es2015.86f82ddd897ee3dcee6a.js:1:1976662
    at Set.forEach (<anonymous>)
    at Zs._resolveInjectorDefTypes (main-es2015.86f82ddd897ee3dcee6a.js:1:1976646)
    at new Fl (main-es2015.86f82ddd897ee3dcee6a.js:1:2018220)
    at Ll.create (main-es2015.86f82ddd897ee3dcee6a.js:1:2018916)
    at main-es2015.86f82ddd897ee3dcee6a.js:1:2036511

**Comment by alan-agius4** [comment] 2022-07-13 06:34
Duplicate of https://github.com/angular/components/issues/22250#issuecomment-831351491

**Closed by alan-agius4** 2022-07-13 06:34 UTC

**Comment by nikhil1027** [comment] 2022-07-13 06:52
Hi @alan-agius4 , I have mentioned that this issue is sam as above two issues, but i do not see any version mismatch.

**Comment by alan-agius4** [comment] 2022-07-13 08:08
Your material and cdk packages are version 10 while I’m Angular framework is on 11.

Important to note that Angular 11 is not longer support, see: https://angular.io/guide/releases#support-policy-and-schedule
