### ISSUE TITLE
Need to support un-minify global JS scripts for debugging

### ISSUE THREAD

**Issue by junjunruan** [angular/angular-cli#6407] opened 2017-05-22 14:42 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.0.2
node: 6.10.1
os: darwin x64

### Repro steps.

I have an angular-cli project, and manually copied some 3rd party **un-minified** JS lib files under `src/app` folder, and then reference it in .angular-cli.json scripts array (like `"scripts": ['app/myLib.js']`). Everything works well.

Here is my command to run the app:
$ ng serve --ssl --port 3000 --open
or
$ ng serve --prod --sourcemap --ssl --port 3000

Since I need to overwrite those JS files to add some customized features, I want to debug the un-minified JS files in Chrome devtools. However, by using either of the commands above to run the app, it can only give me minified JS libraries under `Chrome devtools --> sources --> webpack:// --> . --> src --> app`

### Desired functionality.

Hope angular-cli can have option to un-minify 3rd party JS libs in the source code (like un-minify ts files), but minify them in the build bundle.

**Comment by franktroia** [comment] 2017-05-23 13:18
Dupe of #6166?

**Comment by filipesilva** [comment] 2017-05-23 13:24
Good catch @franktroia, it is indeed a dupe of that issue 👍

**Closed by filipesilva** 2017-05-23 13:24 UTC
Labels: priority: 3 (nice to have), severity2: inconvenient, type: feature
