### ISSUE TITLE
Add Pug (Jade) support?

### ISSUE THREAD

**Issue by Shyam-Chen** [angular/angular-cli#996] opened 2016-06-03 09:14 UTC

**Comment by aciccarello** [comment] 2016-06-03 13:46
This should be implemented as an addon. This was mentioned in a [design document](https://docs.google.com/document/d/11e-GBl9ldDGXcB3myy1HUCWJmS_QsMRdzGquvu6MxZg/edit#bookmark=id.n7kqq68b3pvp) but I'm not sure if the project has quite figure out how to integrate with addons.

**Comment by aciccarello** [comment] 2016-06-03 13:55
On second look I noticed this PR: #626

**Comment by filipesilva** [comment] 2016-06-03 16:10
Yes the PR is up and I'll be looking into merging it soon. Meanwhile I'm closing this issue as a duplicate of https://github.com/angular/angular-cli/issues/40

**Closed by filipesilva** 2016-06-03 16:10 UTC
