### ISSUE TITLE
Bug: ng test --code-coverage doesn't display spec results in the browser in CLI rc2

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#5513] opened 2017-03-20 01:44 UTC
### OS
Mac  OSX Sierra 10.12.3

### Versions
@angular/cli: 1.0.0-rc.2
node: 6.9.1
os: darwin x64
@angular/common: 4.0.0-rc.5
@angular/compiler: 4.0.0-rc.5
@angular/core: 4.0.0-rc.5
@angular/forms: 4.0.0-rc.5
@angular/http: 4.0.0-rc.5
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0-rc.5
@angular/platform-browser-dynamic: 4.0.0-rc.5
@angular/router: 4.0.0-rc.5
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 4.0.0-rc.5

### Repro steps.

- Install RC2
- Run `ng test --code-coverage`

The browser opens and the spec list does not appear

- Run `ng test`

The browser opens and the spec list does appear

- Install RC1
- Run `ng test --code-coverage`

The browser opens and the spec list does appear

In all cases, the spec execution results are shown correctly in the terminal.

It seems there was a regression from rc1 to rc2 on this

![image](https://cloud.githubusercontent.com/assets/1202528/24086841/1bd2341e-0ced-11e7-8469-a7ef3ad6baba.png)

**Comment by delasteve** [comment] 2017-03-20 03:09
Should be fixed with https://github.com/angular/angular-cli/pull/5514

**Comment by filipesilva** [comment] 2017-03-20 12:22
Closing as dupe of https://github.com/angular/angular-cli/issues/5136

**Closed by filipesilva** 2017-03-20 12:22 UTC
Labels: command: test, priority: 3 (nice to have), type: enhancement
