### ISSUE TITLE
Warnings after upgrade to Angular 10

### ISSUE THREAD

**Issue by luoxiao-xy** [angular/angular-cli#18662] opened 2020-08-31 01:45 UTC
After upgrading to Angular 10, I get the following warnings when creating a production build of my app:
`WARNING in ./node_modules/angular2-draggable/__ivy_ngcc__/fesm2015/angular2-drag
gable.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/angular2-draggable/lib/angular-draggable.direct
ive.ts" URL is not supported
Error: Failed to parse source map: "ng:/angular2-draggable/lib/angular-draggable
.directive.ts" URL is not supported
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 10:0-60 70:16-38
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/angular2-draggable/__ivy_ngcc__/fesm2015/angular2-drag
gable.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/angular2-draggable/lib/angular-draggable.module
.ts" URL is not supported
Error: Failed to parse source map: "ng:/angular2-draggable/lib/angular-draggable
.module.ts" URL is not supported
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 10:0-60 70:16-38
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/angular2-draggable/__ivy_ngcc__/fesm2015/angular2-drag
gable.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/angular2-draggable/lib/angular-resizable.direct
ive.ts" URL is not supported
Error: Failed to parse source map: "ng:/angular2-draggable/lib/angular-resizable
.directive.ts" URL is not supported
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 10:0-60 70:16-38
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/angular2-draggable/__ivy_ngcc__/fesm2015/angular2-drag
gable.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/angular2-draggable/lib/models/position.ts" URL
is not supported
Error: Failed to parse source map: "ng:/angular2-draggable/lib/models/position.t
s" URL is not supported
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 10:0-60 70:16-38
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/angular2-draggable/__ivy_ngcc__/fesm2015/angular2-drag
gable.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/angular2-draggable/lib/models/size.ts" URL is n
ot supported
Error: Failed to parse source map: "ng:/angular2-draggable/lib/models/size.ts" U
RL is not supported
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 10:0-60 70:16-38
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/angular2-draggable/__ivy_ngcc__/fesm2015/angular2-drag
gable.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/angular2-draggable/lib/widgets/helper-block.ts"
 URL is not supported
Error: Failed to parse source map: "ng:/angular2-draggable/lib/widgets/helper-bl
ock.ts" URL is not supported
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 10:0-60 70:16-38
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/angular2-draggable/__ivy_ngcc__/fesm2015/angular2-drag
gable.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/angular2-draggable/lib/widgets/resize-handle.ts
" URL is not supported
Error: Failed to parse source map: "ng:/angular2-draggable/lib/widgets/resize-ha
ndle.ts" URL is not supported
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 10:0-60 70:16-38
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/primeng/__ivy_ngcc__/fesm2015/primeng-api.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/primeng/api/confirmationservice.ts" URL is not
supported
Error: Failed to parse source map: "ng:/primeng/api/confirmationservice.ts" URL
is not supported
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 11:0-66 45:12-26 46:12-31
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/primeng/__ivy_ngcc__/fesm2015/primeng-api.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/primeng/api/messageservice.ts" URL is not suppo
rted
Error: Failed to parse source map: "ng:/primeng/api/messageservice.ts" URL is no
t supported
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 11:0-66 45:12-26 46:12-31
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/primeng/__ivy_ngcc__/fesm2015/primeng-api.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/primeng/api/primeng-api.ts" URL is not supporte
d
Error: Failed to parse source map: "ng:/primeng/api/primeng-api.ts" URL is not s
upported
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 11:0-66 45:12-26 46:12-31
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/primeng/__ivy_ngcc__/fesm2015/primeng-api.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/primeng/api/primengconfig.ts" URL is not suppor
ted
Error: Failed to parse source map: "ng:/primeng/api/primengconfig.ts" URL is not
 supported
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 11:0-66 45:12-26 46:12-31
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/primeng/__ivy_ngcc__/fesm2015/primeng-api.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/primeng/api/shared.ts" URL is not supported
Error: Failed to parse source map: "ng:/primeng/api/shared.ts" URL is not suppor
ted
    at fetchFromURL (D:\sundproj\node_modules\source-map-loader\dist\utils.js:16
7:11)
    at D:\sundproj\node_modules\source-map-loader\dist\index.js:88:41
    at Array.map (<anonymous>)
    at Object.loader (D:\sundproj\node_modules\source-map-loader\dist\index.js:7
6:57)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts 11:0-66 45:12-26 46:12-31
 @ ./src/main.ts
 @ multi ./src/main.ts
`
There are many more, not all of them are shown here！
` "@angular/cli": "~10.0.8",
"typescript": "~3.9.7",`
**But without these warnings in 'ng serve', everything is OK. These warnings cover almost all of my dependent packages！**

**Comment by alan-agius4** [comment] 2020-08-31 07:56
Duplicate of https://github.com/angular/angular-cli/issues/18028

**Closed by alan-agius4** 2020-08-31 07:56 UTC
