### ISSUE TITLE
Using externalSchematic breaks debug mode

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12125] opened 2018-09-04 23:20 UTC
_From @maciejtreder on April 5, 2018 21:19_

### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x ] devkit
- [  ] schematics
```

### Versions

Node: v8.5.0
npm: 5.3.0
OS: macOS El Capitan

@schematics/schematics@0.5.1
@angular-devkit/schematics-cli@0.4.7

### Repro steps
```
import { chain, externalSchematic, Rule } from '@angular-devkit/schematics';

export function application(options: any): Rule {
  return chain([
      externalSchematic('@schematics/angular', 'application', options)
    ]);
}
```

### The log given by the failure
```
An error occured:
Error: Could not find (undefined)
    at Object.getWorkspace (/Users/mtreder/Documents/private/work/angular-universal-serverless/schematics/node_modules/@schematics/angular/utility/config.js:14:15)
    at /Users/mtreder/Documents/private/work/angular-universal-serverless/schematics/node_modules/@schematics/angular/application/index.js:241:36
    at MergeMapSubscriber.input.pipe.mergeMap_1.mergeMap.inputTree [as project] (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/src/rules/call.js:80:24)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/Subscriber.js:93:18)
    at ScalarObservable._subscribe (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/observable/ScalarObservable.js:49:24)
    at ScalarObservable.Observable._trySubscribe (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/Observable.js:172:25)
    at ScalarObservable.Observable.subscribe (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/Observable.js:160:93)
    at MergeMapOperator.call (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/operators/mergeMap.js:87:23)
```

### Desired functionality
Normally the list of files in staging is displayed.

_Copied from original issue: angular/devkit#635_

**Comment by clydin** [comment] 2020-05-30 01:50
Duplicate of #11726

**Closed by clydin** 2020-05-30 01:50 UTC
Labels: comp: schematics/angular, priority: 3 (nice to have), triage #1, type: bug/fix
