### ISSUE TITLE
no-build-optimizer doesn't work @angular/cli:1.6.2

### ISSUE THREAD

**Issue by Alekcei** [angular/angular-cli#9008] opened 2017-12-27 16:43 UTC
Again disappeared decoratoes
@angular/cli": "1.6.2"
the flag --no-build-optimizer does not work
I am used ./node_modules/.bin/ng build --prod --no-build-optimizer

--no-build-optimizer not working in @angular/cli:1.6.2. But if use @angular/cli:1.5.0 then all Ok

**Comment by clydin** [comment] 2017-12-27 17:29
Please fill out the issue template so that the issue can be properly investigated.

Also please explain which decorators.  Angular decorators are removed in AOT mode.  This is intentional.  AOT mode does not require the angular metadata at runtime.

**Comment by Alekcei** [comment] 2017-12-27 18:25
https://github.com/angular/angular-cli/issues/8728

**Comment by clydin** [comment] 2017-12-27 18:39
Closing as duplicate of #8728.

**Closed by clydin** 2017-12-27 18:39 UTC
