### ISSUE TITLE
build report is not correct for lazy chuck CSS

### ISSUE THREAD

**Issue by asanoic** [angular/angular-cli#19858] opened 2021-01-24 06:03 UTC
my `angular.json` file has following styles
```
                        "styles": [
                            "web-ui/styles.scss",
                            {
                                "input": "web-ui/lazy-style.scss",
                                "inject": false,
                                "bundleName": "lazy-style"
                            }
                        ],
```
and after I build using `ng b --prod`
the report like, the last line about budgets is not correct
```
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files               | Names         |      Size
main.ea9cbd559e4c662834cb.js      | main          | 302.23 kB
polyfills.f9cd57347f1906e04ab2.js | polyfills     |  36.00 kB
runtime.65c4eb4be5736c726c25.js   | runtime       |   2.36 kB
styles.09e2c710755c8867a460.css   | styles        |   0 bytes

                                  | Initial Total | 340.59 kB

Lazy Chunk Files                  | Names         |      Size
lazy-style.css                    | lazy-style    | 204.04 kB
7.e3f997aaa1c1be1c5173.js         | -             |  77.22 kB
6.1580e9bc5113c363123d.js         | -             |  60.20 kB
8.a044aea76bce9286d877.js         | -             |  12.50 kB
10.96191d8497c9b3cc8a95.js        | -             |   8.16 kB
common.b410b99c2a6f6bf24f46.js    | common        |   1.53 kB
9.87240014e80b8c64a09f.js         | -             | 631 bytes

Build at: 2021-01-24T05:57:44.015Z - Hash: 3ea7f4a829d845353cae - Time: 29546ms

Warning: budgets: initial exceeded maximum budget. Budget 500.00 kB was not met by 44.63 kB with a total of 544.63 kB.
```
versions

```
@angular-devkit/build-angular@0.1100.7
@angular/animations@11.1.0
@angular/cli@11.1.0
@angular/common@11.1.0
@angular/compiler-cli@11.1.0
@angular/compiler@11.1.0
@angular/core@11.1.0
@angular/forms@11.1.0
@angular/platform-browser-dynamic@11.1.0
@angular/platform-browser@11.1.0
@angular/router@11.1.0
```

**Comment by alan-agius4** [comment] 2021-01-25 07:43
Duplicate of https://github.com/angular/angular-cli/issues/17672

**Closed by alan-agius4** 2021-01-25 07:43 UTC
