### ISSUE TITLE
AOT compiler doesn't include lazy-loaded external modules (ngtools/webpack)

### ISSUE THREAD

**Issue by maciejtreder** [angular/angular-cli#8070] opened 2017-10-16 16:32 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
[ x ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using `@ngtools/webpack` with lazy-loaded external module (from git/npm repository), the AOT compilation is breaking.

Code:
```
RouterModule.forRoot([
      { path: '', component: HomeComponent, pathMatch: 'full'},
      { path: 'lazy', loadChildren: './lazy/lazy.module#LazyModule'},
      { path: 'external', loadChildren: '@angular-universal-serverless/external-module/release#ExternalModule'}
])
```

Compilation error:
```
ERROR in ./src/ngfactory lazy
Module not found: Error: Can't resolve '/path/to/my/project/angular-universal-serverless/src/ngfactory/node_modules/@angular-universal-serverless/external-module/release/src/index.js' in '/Users/mtreder/Documents/private/work/angular-universal-serverless/src/ngfactory'
 @ ./src/ngfactory lazy
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main.server.aot.ts
```

## Expected behavior
Compilation should be successful

## Minimal reproduction of the problem with instructions

External module repo: https://github.com/maciejtreder/angular-external-module
Main application repo: https://github.com/maciejtreder/angular-universal-serverless/tree/externalModule

## What is the motivation / use case for changing the behavior?
To split big Angular applications in to smaller modules (ie for microservices purpose)

## Environment

<pre><code>
Angular version: 4.4.5

 
For Tooling issues:
- Node version: 8.5.0  
- Npm version: 5.3.0
- Platform:  Mac 

</code></pre>
StackOverflow thread can be found here: https://stackoverflow.com/questions/46774625/aot-compiler-include-lazy-loaded-external-module

**Comment by filipesilva** [comment] 2017-10-18 08:48
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/6373. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-10-18 08:48 UTC
