### ISSUE TITLE
Support .angular-cli as Javascript file

### ISSUE THREAD

**Issue by bekos** [angular/angular-cli#7564] opened 2017-08-31 17:31 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
### Desired functionality.

I would like you to support `.angular-cli` as `js` file instead of `json`. This will give extra flexibility in customizing properties of this file, dynamically maybe based on environmental variables, or even based on production/development build.

For example, on my production build I want to include `scripts` like Google Tag Manager, TrackJs etc that I don't want during development, or use the minified version of an external script on production build and non-minified during development, etc

Actually it would be nice to have access "automatically" to the corresponding environment file during build, in the `.angular-cli`

**Comment by srlee309** [comment] 2017-09-02 04:26
It looks like there is an existing feature request for this: #6917

**Comment by filipesilva** [comment] 2017-09-05 09:07
Closing as duplicate of #6917, like @srlee309 mentioned. Your usecases are interesting though, I recommend mentioning them there.

**Closed by filipesilva** 2017-09-05 09:07 UTC
