### ISSUE TITLE
Build and test all projects in the correct sequence following dependencies.

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular-cli#13722] opened 2019-02-20 13:39 UTC
# 🚀 Feature request

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
Angular CLI nowadays supports multiple projects per single workspace. This was an important improvement, however, I am still missing a smarter build command that would `build` all the projects in a correct sequence. And the same is applicable to `test` command.

**What does the correct sequence mean**
Usually in a bigger monorepo workspaces developed packages can have dependencies on one another, which means that simple alphabetical order of build/test will not work.

**Example**

```bash
Libraries & dependencies
├── Library 1
│   ├── Library 3
├── Library 2
│   ├── Library 3
├── Library3
```

In the example above current sequence of `ng test` would be `Library 1 - Library 2 - Library 3`, but the correct sequence would be `Library 3 - Library 1 - Library 2`

### Describe the solution you'd like
Every project in a workspace already contains `package.json` (_obviously_). We could use `peerDependencies` to declare the dependencies between projects of the workspace. Then `build` and `test` commands would be able to detect the dependencies and build the libraries in the correct sequence.

I have written myself a node executable that does exactly that. Follows the dependency tree and builds the libraries in the correct sequence.
If that is something you see as a valuable addition to Angular CLI I would be more than happy to contribute.

### Describe alternatives you've considered
Currently, the only alternative is to write `ng build` commands in an npm script, which is practically unmaintainable in bigger workspaces.

**Comment by alan-agius4** [comment] 2019-02-20 13:51
Duplicate of https://github.com/angular/angular-cli/issues/11002

**Closed by alan-agius4** 2019-02-20 13:51 UTC
