### ISSUE TITLE
esbuild fails when run from network path

### ISSUE THREAD

**Issue by mcalmus** [angular/angular-cli#26469] opened 2023-11-23 10:39 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

esbuild fails with

[ERROR] The entry point "//path/to/file.css" cannot be marked as external [plugin angular-compiler]

when run from a path on a network share

rmReproduced using a bare “ng new” project on Windows 10 from a mapped network drive. Everything works fine when moved to a local drive. 

### Please provide the exception or error you saw

```true
[ERROR] The entry point "//path/to/file.css" cannot be marked as external [plugin angular-compiler]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 17
```

**Comment by alan-agius4** [comment] 2023-11-23 11:20
I suspect this might have the same root cause of https://github.com/angular/angular-cli/issues/26379

Can you kindly try to update `node_modules/@angular-devkit/build-angular/src/builders/application/options.js` with the contents in  https://gist.github.com/alan-agius4/7dcb48c5adccb1f2fb54cfbef3403689 and see if it solves the problem?

**Comment by alan-agius4** [comment] 2023-11-30 13:48
Is still still a problem with 17.0.5?

**Comment by alan-agius4** [comment] 2023-12-05 08:47
Closing due to the lack of confirmation.

**Closed by alan-agius4** 2023-12-05 08:47 UTC
Labels: needs: more info

**Comment by mcalmus** [comment] 2023-12-05 21:41
@alan-agius4 I'm sorry I didn't respond sooner. I have been unable to test with 17.0.5, but it continued to fail using the file from the gist. I will test with 17.0.5 as soon as our workplace NPM mirror has been updated.

**Comment by mcalmus** [comment] 2023-12-06 21:24
Verified this as fixed in 17.0.5.

**Comment by alan-agius4** [comment] 2023-12-07 09:26
Glad to hear that.
