### ISSUE TITLE
ng build is broken: Could not resolve fs, net, os, crypto. But ng serve works (latest angular-cli).

### ISSUE THREAD

**Issue by vadimcoder** [angular/angular-cli#27863] opened 2024-06-17 02:03 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

I am a first time Angular user

### Description

`The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.`

<img width="986" alt="Screenshot 2024-06-17 at 6 00 22 AM" src="https://github.com/angular/angular-cli/assets/439939/423362ac-ceb4-44d2-a292-361c60dc9bdb">

### Minimal Reproduction

```
ng new myApp
cd myApp
npm install --save paper
import paper from 'paper';
console.log(paper);
npm start      // works OK - see the output in the console
npm run build // fails
```

### Your Environment

```text
Angular CLI: 18.0.4
Node: 18.20.0
Package Manager: npm 10.5.0
OS: darwin arm64

Angular: 18.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.4
@angular-devkit/build-angular   18.0.4
@angular-devkit/core            18.0.4
@angular-devkit/schematics      18.0.4
@angular/cli                    18.0.4
@schematics/angular             18.0.4
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by alan-agius4** [comment] 2024-06-17 05:21
Duplicate of https://github.com/angular/angular-cli/issues/27425

**Closed by alan-agius4** 2024-06-17 05:21 UTC
