### ISSUE TITLE
ng update does not run properly

### ISSUE THREAD

**Issue by SkiGeek82** [angular/angular-cli#4723] opened 2017-02-15 20:47 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
@angular/cli: 1.0.0-beta.31
node: 6.9.2
os: win32 x64
@angular/common: 2.3.1
@angular/compiler: 2.3.1
@angular/compiler-cli: 2.3.1
@angular/core: 2.3.1
@angular/forms: 2.3.1
@angular/http: 2.3.1
@angular/platform-browser: 2.3.1
@angular/platform-browser-dynamic: 2.3.1
@angular/router: 3.3.1
@angular/cli: 1.0.0-beta.31
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
updated from angular-cli beta.20-4 to beta.31
Followed the steps in the MD
got to the step where you run ng update and it asks if I want to update .editorconfig then I entered y pressed enter and it goes back to the command prompt

```
PS C:\dev\myapp> ng update
installing ng2
? Overwrite .editorconfig? Yes, overwrite
PS C:\dev\myapp>
```

I have tried every option Y, n, d all with the same result
I have tried in the standard windows command prompt both standard and as administrator
I tried in powershell both standard and as administrator
I even tried using bash on windows

All had the same result

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Da13Harris** [comment] 2017-02-15 21:52
We experienced the same issue. As a workaround, since our files were already in source control (TFS), we deleted any that caused the "Overwrite" error and used TFS to manage our differences. Pretty painful, but it worked. (Well, aside from our new missing Webpack library error. :-/)

**Comment by SkiGeek82** [comment] 2017-02-15 22:30
Thanks @Da13Harris, sounds a bit painful. Do you know if the ng update command works on a Mac or on other systems?

**Comment by 1thrasher** [comment] 2017-02-15 22:32
@SkiGeek82 It does not work on OSX either. I just followed @Da13Harris advice, and yes, it is painful.

**Comment by Meligy** [comment] 2017-02-15 22:54
Duplicate of https://github.com/angular/angular-cli/issues/4653 / https://github.com/angular/angular-cli/issues/4584.

**Comment by hansl** [comment] 2017-02-16 01:25
Closing this as dupe of the 2 issues @Meligy pointed out.

**Closed by hansl** 2017-02-16 01:25 UTC
