### ISSUE TITLE
using uglify-webpack-plugin version 1.0.0-beta with uglify-es

### ISSUE THREAD

**Issue by osadan** [angular/angular-cli#7063] opened 2017-07-20 12:50 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions.

ng version - 1.2.1 ( latest)

### Repro steps.

II tried to use uglify-es (changed the version in webapck package.json) (wanting to compile my code to es6) I used uglify-webpack-plugin version 1.0.0.beta
and I figured that the options coming from the ng build (on models/webpack-config.ts)
```
 public addTargetDefaults(buildOptions: BuildOptions): BuildOptions {
```
is reaching to the uglify-webpack-plugin function as 
```
options:{ 
//datahere
} 
```
and the uglify-webpack-plugin is expected the options to be 
```
this.uglifyOptions = this.options.uglifyOptions
```

**Comment by filipesilva** [comment] 2017-07-28 13:42
Heya, I'm consolidating all the ES2015 support requests on the same issue, so it can be better actioned on.

Duplicate of https://github.com/angular/angular-cli/issues/2907.

**Closed by filipesilva** 2017-07-28 13:42 UTC
