### ISSUE TITLE
installing via yarn doesn't work

### ISSUE THREAD

**Issue by foolusion** [angular/angular-cli#2984] opened 2016-11-02 07:06 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

node --version
6.7.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

    yarn global add angular-cli
    ng --version
    # it crashes in cmd and shows the following error in powershell
    C:\Users\andrew>"$basedir/C:/Users/andrew/AppData/Local/Yarn/config/global/node_modules/.bin/ng.cmd"   "$@"
    The filename, directory name, or volume label syntax is incorrect.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

Feel free to close this if it's a yarn issue and not angular.
Just found yarnpkg/yarn#1324 which seems related

**Comment by Meligy** [comment] 2016-11-02 09:07
Yarn global installs are a mess at the moment. And this issue looks like an exact duplicate of the yarn one, which shows other CLI tools affected than the CLI.

I have got a workaround where I have a custom project folder, and I install locally to it, and added it's`node_modules/.bin` to the PATH.

If that sort of thing fils, that would be a different issue (with either yarn or the CLI).

**Comment by filipesilva** [comment] 2016-11-04 15:46
You'll have to take it up to the `yarn` tracker unfortunately. It's their job to achieve `npm` feature parity. If there's something minor we can do to help I'll review a PR.

**Closed by filipesilva** 2016-11-04 15:46 UTC
