### ISSUE TITLE
Cannot load svg files using angular-cli

### ISSUE THREAD

**Issue by bsakweson** [angular/angular-cli#9156] opened 2018-01-10 18:50 UTC
### Versions
```
angular-cli: 1.6.3
angular: 5.0.0
angular material: 5.0.4
```

### Repro steps
* Setup a project 
* Added flag-icon-css uing npm
* Step import flag-icon-css in `styles.scss`
* Add an icon from the flag-icon-css

```
$flag-icon-css-path: '~flag-icon-css/flags' !default;
@import '../node_modules/flag-icon-css/sass/flag-icon';
```

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
All icons return 404 error though path is correct


ConnectedPositionStrategy.apply @ overlay.es5.js:1146
OverlayRef.updatePosition @ overlay.es5.js:792
(anonymous) @ overlay.es5.js:625
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
TakeSubscriber._next @ take.js:83
Subscriber.next @ Subscriber.js:92
schedulerFn @ core.js:4339
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4319
(anonymous) @ core.js:4724
ZoneDelegate.invoke @ zone.js:388
Zone.run @ zone.js:138
NgZone.runOutsideAngular @ core.js:4701
checkStable @ core.js:4724
onLeave @ core.js:4797
onInvokeTask @ core.js:4747
ZoneDelegate.invokeTask @ zone.js:420
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:495
invokeTask @ zone.js:1536
globalZoneAwareCallback @ zone.js:1562
overlay.es5.js:1146 GET http://localhost:4200/...../node_modules/flag-icon-css/flags/1x1/vu.svg 404 (Not Found)
```

### Desired behavior
Icon paths should be resolved correctly

**Comment by clydin** [comment] 2018-01-10 19:40
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #9154.

**Closed by clydin** 2018-01-10 19:40 UTC
