### ISSUE TITLE
Project in Angular 5 not working in IE11

### ISSUE THREAD

**Issue by andry85mae** [angular/angular-cli#9578] opened 2018-02-09 09:54 UTC
### Versions
Angular CLI: 1.6.3
Node: 6.11.3
OS: win32 x64
Angular: 5.2.0
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/animations: 4.4.6
@angular/cdk: 5.0.4
@angular/cli: 1.6.3
@angular/material: 5.0.4
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack-dev-server: 2.9.7
webpack: 3.10.0

### Repro steps
Build application
Run app in IE11

### Observed behavior
when try to execute this code:

```
// Execute the module function
 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```
with moduleId ="../../../core/esm5/core.js"

an error is throw: "Unable to get property 'call' of undefined or null reference"

### Desired behavior

the application run in IE11

### Mention any other details that might be useful (optional)

I already uncomment the polyfill.ts

**Comment by ddimaria** [comment] 2018-02-11 08:23
See [#4128](https://github.com/angular/angular-cli/issues/4128)

**Comment by Brocco** [comment] 2018-02-12 15:48
Duplicate of #4128

Closing in favor of the other issue.

**Closed by Brocco** 2018-02-12 15:48 UTC

**Comment by andry85mae** [comment] 2018-02-12 16:02
hi

thanks you for the suggestion.
I already try this solution. this is my polyfils

`/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';


import 'core-js/es7/array';


/**
 * Required to support Web Animations `@angular/animation`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 //**/
 //import 'web-animations-js';  // Run `npm install --save web-animations-js`.



/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
 //import 'intl';  // Run `npm install --save intl`.
/**
 * Need to import at least one locale-data with intl.
 */
 //import 'intl/locale-data/jsonp/en';
`

**Comment by abbymrs** [comment] 2018-06-13 06:32
My angular 5 project also has the same error even I have uncommented the polyfill for IE, still cannot work in IE browser.

**Comment by GRRedWings** [comment] 2018-06-14 19:40
I have a similar issue.  I have no errors, yet IE just will not load.

**Comment by exhtml** [comment] 2018-06-21 18:46
Same here, following the steps of uncommenting the polyfills. Any suggestion will be much appreciated. Thank you very much!

**Comment by LeoNdec** [comment] 2018-06-26 14:31
I actually had a similar issue.  I uncommented the following in polyfills.ts:

import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';

import 'core-js/es7/reflect';

And, instead of ng build --prod, I just ran ng build.

Not perfect, sitll fighting bugs, but I was able to get IE to load.

**Comment by dannyzhan** [comment] 2018-06-29 10:49
I have the same issue, not sure why it's closed.

**Comment by MeltdownZA** [comment] 2018-07-04 03:53
@dannyzhan Its closed because its not a bug see the post by @LeoNdec

**Comment by thesmallbang** [comment] 2018-07-10 17:19
@MeltdownZA I have reviewed the post by @LeoNdec and it does not reference any fix. You are recommending we not build with --prod?
