### ISSUE TITLE
Unable to install angular-cli through command line

### ISSUE THREAD

**Issue by escapeimagery** [angular/angular-cli#2430] opened 2016-09-29 23:09 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10 current version and updated

### Versions.
> Angular-cli not installed
> Node version 4.5.0

### Repro steps.
>This was an initial install globally in preparation for a new repo. I tried to install the program via npm as instructed in your git repo. 

npm install -g angular-cli 

### The log given by the failure.
> Normally this include a stack trace and some more information.
266448 error Windows_NT 10.0.14393
266449 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular-cli" "-g"
266450 error node v4.5.0
266451 error npm  v2.15.9
266452 error code EPEERINVALID
266453 error peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its siblings' peerDependencies requirements!
266453 error peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
266453 error peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
266453 error peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
266453 error peerinvalid Peer string-replace-loader@1.0.5 wants webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta
266453 error peerinvalid Peer webpack-dev-server@2.1.0-beta.3 wants webpack@^2.1.0-beta
266454 verbose exit [ 1, true ]

### Mention any other details that might be useful.
I have checked for any globally installed npm programs that may be outdated and tried a full global npm update however they all appear to be current just in case this was affecting the issue
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by escapeimagery** [comment] 2016-09-29 23:20
I have updated to the latest node version and received these errors also
node  v6.7.0
npm v3.10.3

npm WARN optional Skipping failed optional dependency /angular-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\escap\AppData\Roaming\npm\node_modules\.staging\abbrev-d2e8ed6a
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\escap\AppData\Roaming\npm\node_modules\.staging\abbrev-d2e8ed6a' -> 'C:\Users\escap\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\escap\AppData\Roaming\npm\node_modules\.staging\abbrev-d2e8ed6a' -> 'C:\Users\escap\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\escap\npm-debug.log
npm ERR! code 1

**Comment by rolandoldengarm** [comment] 2016-09-30 00:30
Colleague of mine had the same issue and upgrading to Node v6 fixed it.

**Comment by escapeimagery** [comment] 2016-09-30 16:43
Just a minor update I upgrade npm and node but I still experienced the same issues on windows 10 however on the same computer but on Linux distro the angular-cli installed without issue. Both systems are recently a new install with the same package versions globally so I'm unsure if this issue is something to do with the new windows 10 upgrade which to be honest is very buggy. As of now i will be sticking to Linux however I hope this flag will highlight maybe an issue should others report similar issues.

For me the issue is closed as I will be using the functioning version on Linux from now.

**Comment by defabien** [comment] 2016-09-30 16:54
I had the same issue on windows 10 with npm 2 installed, but with npm 3, the issue was resolved.

**Comment by nemoo** [comment] 2016-09-30 20:45
I have the same issue, upgrading to node 3 did not help. I also have the new windows 10 upgrade.
npm 3.10.8
node v6.7.0

**Comment by cclelio** [comment] 2016-10-02 07:42
You can use this workaround https://github.com/angular/angular-cli/issues/1190

npm uninstall -g angular-cli
npm install -g angular-cli

**Comment by filipesilva** [comment] 2016-10-08 23:55
@escapeimagery your original post was caused by using npm2, whereas npm3 is a requirement of using `angular-cli`.

Your second issue is a dupe of https://github.com/angular/angular-cli/issues/1190, as @cclelio noted.

**Closed by filipesilva** 2016-10-08 23:55 UTC

**Comment by mahyari** [comment] 2016-10-20 20:20
I have the same problem on windows 10 with below information:
```
node version: v6.9.1
npm version: 3.10.9
```

I was clean npm cache, unistall angular-cli and install again but problem exist!

details information:
```
C:\Users\Current_User>npm install angular-cli -g -f
npm WARN using --force I sure hope you know what you are doing.
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-f6d15fb1\7e55907cd54a2e91b96d25a660acc6a2a6453f54: Cloning into 'C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-f6d15fb1\7e55907cd54a2e91b96d25a660acc6a2a6453f54'...
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-f6d15fb1\7e55907cd54a2e91b96d25a660acc6a2a6453f54: fatal: '/cygdrive/c/Users/Current_User/AppData/Roaming/npm-cache/_git-remotes/git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe/C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe' does not appear to be a git repository
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-f6d15fb1\7e55907cd54a2e91b96d25a660acc6a2a6453f54: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-f6d15fb1\7e55907cd54a2e91b96d25a660acc6a2a6453f54:
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-f6d15fb1\7e55907cd54a2e91b96d25a660acc6a2a6453f54: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-f6d15fb1\7e55907cd54a2e91b96d25a660acc6a2a6453f54: and the repository exists.
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-f6d15fb1\7e55907cd54a2e91b96d25a660acc6a2a6453f54:
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3 C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-a782214a\7e55907cd54a2e91b96d25a660acc6a2a6453f54: Cloning into 'C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-a782214a\7e55907cd54a2e91b96d25a660acc6a2a6453f54'...
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3 C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-a782214a\7e55907cd54a2e91b96d25a660acc6a2a6453f54: fatal: '/cygdrive/c/Users/Current_User/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3/C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3' does not appear to be a git repository
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3 C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-a782214a\7e55907cd54a2e91b96d25a660acc6a2a6453f54: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3 C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-a782214a\7e55907cd54a2e91b96d25a660acc6a2a6453f54:
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3 C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-a782214a\7e55907cd54a2e91b96d25a660acc6a2a6453f54: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3 C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-a782214a\7e55907cd54a2e91b96d25a660acc6a2a6453f54: and the repository exists.
npm ERR! git clone C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3 C:\Users\Current_User\AppData\Local\Temp\npm-4924-6b7f0b8e\git-cache-a782214a\7e55907cd54a2e91b96d25a660acc6a2a6453f54:
npm ERR! git clone --template=C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: Cloning into bare repository 'C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5'...
npm ERR! git clone --template=C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: Host key verification failed.
npm ERR! git clone --template=C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5:
npm ERR! git clone --template=C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: and the repository exists.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Current_User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular-cli" "-g" "-f"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5
npm ERR! Cloning into bare repository 'C:\Users\Current_User\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Current_User\npm-debug.log

C:\Users\Current_User>
```

**Comment by brinkkemper** [comment] 2018-06-01 09:14
Had the same problem, upgrade Node via [their website](https://nodejs.org/) fixed it for me
