### ISSUE TITLE
Website: The Learn Angular link in the bottom bar points to wwww.angular.io ... which doesn't work

### ISSUE THREAD

**Issue by benlesh** [angular/angular-cli#11619] opened 2018-07-21 00:34 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```
### Repro steps
Navigate to cli.angular.io, and try to click the `Learn Angular` link at the bottom of the page.

### What happens?

Womp womp. It goes nowhere fast.

### Desired functionality
It should navigate to  angular.io

### Mention any other details that might be useful
Special thanks to [Ahmet Omer for tweeting about this](https://twitter.com/ahmetomerv/status/1020455005835485184)

**Comment by Brocco** [comment] 2018-07-23 18:09
Assigning this to @hansl this [site](https://cli.angular.io/) is not part of the public repo.

**Comment by Brocco** [comment] 2018-07-23 18:09
Also, this issue exists on the main angular repo... angular/angular#23381

**Comment by hansl** [comment] 2018-07-23 18:12
This is a dupe of angular/angular#23381

**Closed by hansl** 2018-07-23 18:12 UTC
Labels: effort1: easy (hours), type: bug, type: docs
