### ISSUE TITLE
Add postcss plugins to style pipeline

### ISSUE THREAD

**Issue by unlight** [angular/angular-cli#15766] opened 2019-10-05 23:42 UTC
# 🚀 Feature request
Currently PostCSS plugins are hardcoded and there is no chances to modify (add) it.
See `@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/styles.js@getStylesConfig`

Custom builders cannot help here, because we need edit plugins for webpack loader, they do not have such features.

This comment https://github.com/angular/angular-cli/issues/1656#issuecomment-239366723 says about webpack config, but what about postcss config?
Can angular-cli pick `postcss.config.js` and apply plugins defined there?

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

**Comment by MatthiasKunnen** [comment] 2019-11-03 22:46
Duplicate of #8427

**Comment by unlight** [comment] 2019-12-26 07:49
https://github.com/just-jeb/angular-builders/issues/634

**Comment by alan-agius4** [comment] 2020-01-16 18:07
Thanks @MatthiasKunnen indeed this is a duplicate of #8427.

**Closed by alan-agius4** 2020-01-16 18:07 UTC
Labels: comp: devkit/build-angular, type: feature
