### ISSUE TITLE
[Angular 14]: Build is failing

### ISSUE THREAD

**Issue by school-coder** [angular/angular-cli#23792] opened 2022-08-25 14:06 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes. The build suddenly getting failed continously

### Description

**Note:** The build machines also build angular with node and npm of lower versions. They are successful.

## 🔬 Minimal Reproduction
The Build is getting failed in build machines for docker.

## 🔥 Exception or Error

<pre><code>
/FS/fslocal/jenkins_home/workspace/DPO-Docker-Build-1015/modules/dpo-ui/node_modules/esbuild/lib/main.js:678
      throw new Error("The service is no longer running" + closeData.reason);
            ^

Error: The service is no longer running: write EPIPE
    at sendResponse (/FS/fslocal/jenkins_home/workspace/DPO-Docker-Build-1015/modules/dpo-ui/node_modules/esbuild/lib/main.js:678:13)
    at handleRequest (/FS/fslocal/jenkins_home/workspace/DPO-Docker-Build-1015/modules/dpo-ui/node_modules/esbuild/lib/main.js:741:7)
    at handleIncomingPacket (/FS/fslocal/jenkins_home/workspace/DPO-Docker-Build-1015/modules/dpo-ui/node_modules/esbuild/lib/main.js:756:7)
    at Socket.readFromStdout (/FS/fslocal/jenkins_home/workspace/DPO-Docker-Build-1015/modules/dpo-ui/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

> Task :modules:dpo-ui:npm_run_build FAILED

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 14.0.2                                   
Node: 16.15.1                                         
Package Manager: npm 8.11.0                           

</code></pre>

**Comment by alan-agius4** [comment] 2022-08-25 14:12
Duplicate of https://github.com/angular/angular-cli/issues/22338

**Closed by alan-agius4** 2022-08-25 14:12 UTC
