### ISSUE TITLE
`cli.warnings.typescriptMismatch = false` is not working alone

### ISSUE THREAD

**Issue by JounQin** [angular/angular-cli#11716] opened 2018-07-31 07:54 UTC
### Bug Report or Feature Request (mark with an `x`)

- [x] bug report -> please search issues before submitting
- [ ] feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Versions

```
Angular CLI: 6.1.1
Node: 10.7.0
OS: darwin x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.1
@angular-devkit/build-angular     0.7.1
@angular-devkit/build-optimizer   0.7.1
@angular-devkit/build-webpack     0.7.1
@angular-devkit/core              0.7.1
@angular-devkit/schematics        0.7.1
@angular/cli                      6.1.1
@ngtools/webpack                  6.1.1
@schematics/angular               0.7.1
@schematics/update                0.7.1
rxjs                              6.2.2
typescript                        3.0.1
webpack                           4.9.2
```

### Repro steps

new project from `@angular/cli`, upgrade TypeScript to 3.0, add warning config to `angular.json`:
``` json
{
  "cli": {
    "warnings": {
      "typescriptMismatch": false
    }
  }
}
```
run `ng serve`

### The log given by the failure

`ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.10.0 but 3.0.1 was found instead.`

### Desired functionality

There should be no error thrown. For now, we can add some `@angular/compiler` related config to `tsconfig.app.json` as workaround:
``` json
{
  "angularCompilerOptions": {
    "disableTypeScriptVersionCheck": true
  }
}
```
Is it should be implemented inside `@angular/cli` or option `typescriptMismatch` is useless anyway?

**Comment by hansl** [comment] 2018-07-31 12:55
We don't support 3.0 in both the CLI and the Compiler CLI. The `typescriptMismatch` flag is only for the Angular CLI. That's correct that just setting it will not disable the Compiler CLI warning. If you need to use an unsupported version of TypeScript with your code you'll have to disable both warnings, but please note that your code might not work properly.

Closing this as answered. The current behaviour is working as intended.

**Closed by hansl** 2018-07-31 12:55 UTC
