### ISSUE TITLE
Cannot find module 'portfinder'

### ISSUE THREAD

**Issue by JoshWilliams92** [angular/angular-cli#2296] opened 2016-09-22 17:04 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

# Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

# ng --version not working, node version 4.50 (LTS)

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

# No App created yet

4. The log given by the failure. Normally this include a stack trace and some
   more information.

# Error cannot find module 'portfinder'

5. Mention any other details that might be useful.

# I installed globally via NPM as normal and when I try to either check the version or generate a new project it throws the same error.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JanStureNielsen** [comment] 2016-09-22 20:43
@JoshWilliams92 -- this looks like a dup of #1782

**Comment by JoshWilliams92** [comment] 2016-09-28 09:07
I have resolved the issue by globally installing the portfinder module and then npm installing it in my main project directory after generating a new project. I had this problem today also with the reflect-metadata module but repeated the same process as above.

**Comment by filipesilva** [comment] 2016-10-06 17:22
Dupe of #1782.

**Closed by filipesilva** 2016-10-06 17:22 UTC
