### ISSUE TITLE
ng7 can not generate new project

### ISSUE THREAD

**Issue by wszgrcy** [angular/angular-cli#12215] opened 2018-09-09 07:23 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### The log given by the failure

PS D:\test> ng test
The test command requires to be run **in** an Angular project, but a project definition could not be found.
PS D:\test> ng new ng7
The new command requires to be run **outside** of a project, but a project definition was found at "D:\test".
PS D:\test> ng v
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

```
Angular CLI: 7.0.0-beta.2
Node: 8.11.4
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.9.0-beta.2
@angular-devkit/core         0.9.0-beta.2
@angular-devkit/schematics   0.9.0-beta.2
@schematics/angular          0.9.0-beta.2
@schematics/update           0.9.0-beta.2
rxjs                         6.2.2
typescript                   3.0.3

PS D:\test>

### Desired functionality

why I run `ng test` it hint  **requires to be run **in**** and `ng new` it hint **requires to be run **outside****

**Comment by alan-agius4** [comment] 2018-09-09 08:30
Duplicate of https://github.com/angular/angular-cli/issues/12215

**Closed by alan-agius4** 2018-09-09 08:30 UTC

**Comment by sstone2423** [comment] 2018-10-23 01:27
Wasn't able to find a duplicate in the issue search... Can we reopen this as I'm having the same problem with all `ng` commands inside the angular project root folder

**Comment by mo-norant** [comment] 2018-10-24 08:19
Same issue here

`The serve command requires to be run in an Angular project, but a project definition could not be found.` error when ng serve is issued

**Comment by tgoawa** [comment] 2018-10-24 15:52
Also experiencing this in a project I tried upgrading the Angular CLI to 7.0.2

**Comment by MarkyMarc35** [comment] 2018-10-25 11:56
Experiencing the same issue in a project I updated to Angular CLI 7

**Comment by JohnGrisham** [comment] 2018-10-27 01:41
My issue was that my angular.json file was not in the root of my project. I moved it there and this fixed the error for me.

**Comment by joe20123** [comment] 2018-10-27 05:38
I came across the same error. The reason is that new angular cli update makes angular-cli.json redundant, and it is replaced with angular.json instead. My previous Angular Cli version is 1.7.4, so to make the change, I ran the following command, it will make the conversion for you:

ng update @angular/cli --migrate-only --from=1.7.4

**Comment by demonguru18** [comment] 2018-10-30 16:12
Here is an Starter Project I created for Asp.net Core 2.1, Angular 7.0.3 and Bootstrap 4.1.3 You can download this project and start. 
https://github.com/demonguru18/Angular7DotNetCore2.1BootStrap4

**Comment by demonguru18** [comment] 2018-11-01 16:39
> > Here is an Starter Project I created for Asp.net Core 2.1, Angular 7.0.3 and Bootstrap 4.1.3 You can download this project and start.
> > https://github.com/demonguru18/Angular7DotNetCore2.1BootStrap4
> 
> Can you please tell the steps to start the execution of this project.
it should just work, when you press F5

**Comment by demonguru18** [comment] 2018-11-01 17:06
Here are the Steps to Execute - doc File (Google Drive Link)
https://drive.google.com/file/d/1Vf1zlvfgWC3ZVQtICcLeGQP6-Tvk1Kwr/view?usp=sharing

**Comment by demonguru18** [comment] 2018-11-01 17:13
before you execute - Please do this 
Also Can you check you have - Updated version on Angular installed Globally
ng version
image
If you don't see this, to Update angular globally
npm uninstall -g angular-cli
npm cache clean or npm cache verify (if npm > 5)
npm install -g @angular/cli@latest

**Comment by MHX123** [comment] 2018-12-06 08:20
I also encountered this problem. Is there any way to solve this problem?

**Comment by WarrenWalker** [comment] 2018-12-11 02:56
![image](https://user-images.githubusercontent.com/17193429/49775417-0d328280-fd5d-11e8-8d7a-4e142a3d2910.png)

So instead of naming the new project in a single command, I just waiting to be prompted.

$ ng new

as seen in the screenshot.

**Comment by nani554** [comment] 2019-01-06 08:51
Recently i also faced this issue, nothing helped me atlast after thinking for a while i got to know that node-modules were not installed yet and installing the packages( npm i) solved the problem.

**Comment by afifkraiem** [comment] 2019-02-01 09:32
ng update @angular/cli
this command fixes the problem for me

**Comment by willdonner** [comment] 2019-03-19 02:32
`npm link @angular/cli`
worked for me

**Comment by tiwarinitin94** [comment] 2019-06-20 10:22
@afifkraiem Thank you so much this worked for me.

**Comment by DocGreenRob** [comment] 2019-09-04 04:14
I'm having the same issue...

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 8.3.2
Node: 10.16.3
OS: win32 x64
Angular: 5.0.0
... common, compiler, core, forms, http, platform-browser
... platform-browser-dynamic

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.2 (cli-only)
@angular-devkit/build-optimizer   0.0.35
@angular-devkit/core              8.3.2 (cli-only)
@angular-devkit/schematics        8.3.2 (cli-only)
@angular/compiler-cli             8.2.0
@schematics/angular               8.3.2 (cli-only)
@schematics/update                0.803.2 (cli-only)
rxjs                              5.5.2
typescript                        2.8.3
webpack                           3.12.0
```

and when I run `ng update @angular/cli --migrate-only --from=8.3.2` I get the following error:

```
Using package manager: 'npm'
Collecting installed dependencies...
Found 80 dependencies.
Package is not installed.
```

**Comment by DocGreenRob** [comment] 2019-09-04 04:15
test

**Comment by somixyz** [comment] 2019-09-17 17:45
Me too... i'm beginner with angular, can someone help, what could be a problem ? 
I'm trying to start simple angular app, but the problem is actually with different CLI versions. 

http://prntscr.com/p7e4tv
on the left side is new version, on the right is older version.

**Comment by demonguru18** [comment] 2019-09-25 16:34
> Me too, i got the same message... i'm beginner with angular, can someone more experienced could help, what could be a problem ?
> I'm trying to start simple angular app, but the problem is actually with different CLI versions.
> I tried with above mentioned code to migrate but didn't help. Tried also with `ng update ` with some variations and `npm install `, but unsuccessfully.
> 
> http://prntscr.com/p7e4tv
> on the left side is new version, on the right is older version.

Update/Install latest version of npm - for mac or linux OS use sudo before command
 Run `npm -v ` to see which version you have, then `npm install npm@latest -g` to install the newest npm update. Run `npm -v` again if you want to make sure npm updated correctly.

Update angular to latest  version Globally
**sudo npm uninstall -g angular-cli** // For Mac

**npm uninstall -g angular-cli** // For Windows Open Powershell on Administrator Mode

Then we need to clear the cache using the following command.
sudo npm cache verify

Now, install the Angular CLI using the following command.
sudo npm install -g @angular/cli@latest

If you have created an Angular project then go inside that folder and type the following command.
ng update @angular/core

You can update RxJS using the ng update command.
ng update rxjs
