### ISSUE TITLE
ng build optimization:true no longer get routing events

### ISSUE THREAD

**Issue by mattmbrightside** [angular/angular-cli#17903] opened 2020-06-10 20:49 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Not sure

### Description

In my app component I load this code (from an injected service)
    this.router.events.pipe(
      filter(e => e.constructor.name === 'NavigationEnd'),
      pairwise()
    ).subscribe((e: any[]) => {
      //do things with events
    });

With optimization:false I receive events as I navigate through my app's routes.  With optimization:true I do not receive any events.

## 🔬 Minimal Reproduction
ng build using angular.json with
architect: {build: {options: optimization:true}}

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.7
Node: 13.11.0
OS: darwin x64

Angular: 9.1.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.7
@angular-devkit/build-angular      0.901.3
@angular-devkit/build-ng-packagr   0.901.3
@angular-devkit/build-optimizer    0.901.3
@angular-devkit/build-webpack      0.901.3
@angular-devkit/core               9.0.7
@angular-devkit/schematics         9.0.7
@angular/cli                       9.0.7
@ngtools/webpack                   9.1.3
@schematics/angular                9.0.7
@schematics/update                 0.900.7
ng-packagr                         9.1.1
rxjs                               6.5.5
typescript                         3.7.5
webpack                            4.39.2

</code></pre>

**Anything else relevant?**
Not browser specific

**Comment by clydin** [comment] 2020-06-10 23:29
`constructor.name` is the problem in this case.  It should be avoided whenever possible as it will not work when minifying code which is one of the main actions of the optimization option.  It also does not conclusively determine whether the class is actually as expected.  Any class could have that name but might not have the expected functionality.

Something similar to the following should work in this case:
```
    router.events.pipe(
       filter(e => e instanceof NavigationEnd),
    ).subscribe((e: NavigationEnd) => {

    });
```

**Comment by alan-agius4** [comment] 2020-06-11 07:43
As @clydin mentioned, `constructor.name` will not work when using optimization. This is because one of the optimizations done to reduce the bundle size even further is to mangle class names.

Closing as this is working as intended and using `instanceof` is a better alternative.

**Closed by alan-agius4** 2020-06-11 07:43 UTC
Labels: comp: devkit/build-angular, devkit/build-angular: browser, type: faq

**Comment by mattmbrightside** [comment] 2020-06-11 15:13
Thanks for the clarification.  Perhaps a useful build feature would be emitting a build warning when the use of constructor.name is detected (or similarly a codelyzer lint rule)
