### ISSUE TITLE
Paths decalred in compilerOptions tsconfig.app.json not working

### ISSUE THREAD

**Issue by alexmtzs** [angular/angular-cli#17873] opened 2020-06-06 08:43 UTC
I have already seen some issues related with this topic here but any one can fix my issue..

CONTEXT OF THE ISSUE:
It is curios i have similar setup in other project and it is working perfect. As context of how i got on this, I'm trying to do a merge between ASP .Net Boilerplate but replaing the front with ngx-admin.

Original project uses only main tsconfig.json file in source. Ngx-admin uses tsconfig.json main folder and tsconfig.app.json and tsconfig.spec.json in src folder. As well as tsconfig.e2e.json in e2e folder.
All was perfect until i started merging this files.

So, I created and attached a smaill brand new repro project: 

STEPS TO DUPLICATE
1. Download the attached project
2. Run npm install
3. Open src/AppPreBootstrap.ts file
4. BUG: You will see that the import to AppConsts class does not work as @shared/AppConsts is not recognized.
5. BUG: Try to retype @sha  and intellisense does not bring the option to add @shared........
6. Optionally you can run ng serve, But in this project this issue does not affect the compilation but warning about classes not used.
[DuplicateTsConfigissue.zip](https://github.com/angular/angular-cli/files/4739674/DuplicateTsConfigissue.zip)
![ErrorTSCONFIG](https://user-images.githubusercontent.com/57273906/83940078-86226700-a7a7-11ea-93fd-d0706e136cb5.png)

**Comment by alan-agius4** [comment] 2020-06-08 12:29
Hi @alexmtzs, this is a duplicate of #8138 and was addressed in version 10 via #17586. 

The fix requires TypeScript 3.9 which leverages the usage of the new "solutions style" tsconfig files. You can read about this here https://devblogs.microsoft.com/typescript/announcing-typescript-3-9-rc/#solution-style-tsconfig

**Closed by alan-agius4** 2020-06-08 12:29 UTC
