### ISSUE TITLE
Running tests on monorepo requires cleaning dist/test-out when using @angular-devkit/build-angular:jest

### ISSUE THREAD

**Issue by rafagsiqueira** [angular/angular-cli#25190] opened 2023-05-11 12:23 UTC
### Command

test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Since compiled tests are always moved to the same folder "dist/test-out", running tests from different projects in a monorepo requires cleaning the dist/test-out folder manually first. Exposing an option for the output dir, or putting the compiled specs on a folder relative to each subproject could solve the issue.

### Minimal Reproduction

ng test <project 1>
ng test <project 2>

### Your Environment

```text
Angular CLI: 16.0.0
Node: 18.16.0
Package Manager: yarn 3.5.0
OS: darwin x64

Angular: 16.0.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0-rc.1
@angular/cdk                    16.0.0
@angular/cli                    16.0.0
@angular/flex-layout            15.0.0-beta.42
@angular/material               16.0.0
@angular/pwa                    16.0.0
@schematics/angular             16.0.0
ng-packagr                      16.0.1
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by dgp1130** [comment] 2023-05-11 16:33
Yeah, we're not quite at monorepo support yet. Eventually I'm hoping to move the `test-out` folder to some temporary directory which gets cleaned up afterwards so it won't even be in the project structure at all.

**Comment by rafagsiqueira** [comment] 2023-05-11 17:20
Could you parameterize the outPut dir as an option for the builder? Then we might be able to solve this and a workaround for https://github.com/angular/angular-cli/issues/25188 could also rely on the outDir, as long as no two files have the same name within each project.

**Comment by dgp1130** [comment] 2023-05-11 21:04
Once we move the output outside of the project directory, then this won't be an issue at all. No need for users to define an `outputDir` at all.

**Comment by rafagsiqueira** [comment] 2023-05-11 21:38
That would be great. Thank you for your work on this. I have been using jest with Angular for a while now using the jest-preset-angular project, but it's been a nightmare so far when combined with esm, monorepos and IDE integration. Do you have a ballpark timeframe for this move of the output folder? It's preventing me from using the builder, for the time being.

**Comment by dgp1130** [comment] 2023-05-11 21:53
This is all experimental right now, so there's a lot of work left to be done. Even if the output directory wasn't an issue, I still wouldn't recommend general usage of the builder yet.

**Comment by Prabin1111** [comment] 2023-05-12 04:23
do we need additional setup for code-coverage

**Comment by dgp1130** [comment] 2023-06-07 22:30
Duplicate of #25308

**Closed by dgp1130** 2023-06-07 22:30 UTC
Labels: type: bug/fix, freq1: low, severity3: broken, area: devkit/build-angular, devkit/build-angular: jest
