### ISSUE TITLE
Build fails after migrating to v14

### ISSUE THREAD

**Issue by rvg296** [angular/angular-cli#23713] opened 2022-08-09 22:44 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression? 

 Yes, the previous version in which this bug was not present was: 13.1.3

### Description

 A clear and concise description of the problem...
Getting an issue with serving or building the application after incremental upgrades to v14. Our previous version of the application was in v8, but after following the recommended steps from update.angular.io, we followed and upgraded the application to 14.1.1. But for some reason, the application does not build or even serve and shows various errors. This is related to the [23490](https://github.com/angular/angular-cli/issues/23490) but however, it didnt help because deleting the node modules folder and performing npm install or yarn install still throwed issues.

## 🔥 Exception or Error

<pre><code>
⠙ Generating browser application bundles (phase: setup)...Error: EPERM: operation not permitted, lstat 'D:/System Volume Information'
    at Module.lstatSync (node:fs:1516:3)
    at NodeJSFileSystem.lstat (file:///D:/test/iMap/node_modules/@angular/compiler-cli/bundles/chunk-TOKOIIBI.js:342:16)
    at EntryPointCollector.walkDirectoryForPackages (file:///D:/test/iMap/node_modules/@angular/compiler-cli/bundles/chunk-HE5WHX7C.js:764:28)        
    at file:///D:/test/iMap/node_modules/@angular/compiler-cli/bundles/chunk-HE5WHX7C.js:892:70
    at trackDuration (file:///D:/test/iMap/node_modules/@angular/compiler-cli/bundles/chunk-HE5WHX7C.js:656:18)
    at ProgramBasedEntryPointFinder.walkBasePathForPackages (file:///D:/test/iMap/node_modules/@angular/compiler-cli/bundles/chunk-HE5WHX7C.js:892:25)
    at ProgramBasedEntryPointFinder.findOrLoadEntryPoints (file:///D:/test/iMap/node_modules/@angular/compiler-cli/bundles/chunk-HE5WHX7C.js:882:100) 
    at ProgramBasedEntryPointFinder.getEntryPointWithDeps (file:///D:/test/iMap/node_modules/@angular/compiler-cli/bundles/chunk-HE5WHX7C.js:868:30)  
    at ProgramBasedEntryPointFinder.findEntryPoints (file:///D:/test/iMap/node_modules/@angular/compiler-cli/bundles/chunk-HE5WHX7C.js:826:39)        
    at file:///D:/test/iMap/node_modules/@angular/compiler-cli/bundles/chunk-HE5WHX7C.js:1273:33
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
styles.css, styles.js | styles        | 535.86 kB |
scripts.js            | scripts       | 388.36 kB |
polyfills.js          | polyfills     | 206.71 kB |
vendor.js             | vendor        | 206.08 kB |
runtime.js            | runtime       |   6.52 kB |
main.js               | main          | 796 bytes |

                      | Initial Total |   1.31 MB

Build at: 2022-08-09T22:28:53.706Z - Hash: 56a14e1509a8cb8a - Time: 9655ms

./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit

Error: Failed to initialize Angular compilation - NGCC failed.

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

× Failed to compile.
</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 14.1.1
Node: 16.14.0
Package Manager: npm 8.16.0
OS: win32 x64

Angular: 14.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.1
@angular-devkit/build-angular   14.1.1
@angular-devkit/core            14.1.1
@angular-devkit/schematics      14.1.1
@schematics/angular             14.1.1
rxjs                            7.5.6
typescript                      4.7.4

</code></pre>

**Anything else relevant?**

Dependencies as follows:

<pre><code>
"@angular/animations": "^14.1.1",
    "@angular/cdk": "^14.1.1",
    "@angular/common": "^14.1.1",
    "@angular/compiler": "^14.1.1",
    "@angular/core": "^14.1.1",
    "@angular/forms": "^14.1.1",
    "@angular/material": "^14.1.1",
    "@angular/platform-browser": "^14.1.1",
    "@angular/platform-browser-dynamic": "^14.1.1",
    "@angular/platform-server": "^14.1.1",
    "@angular/router": "^14.1.1",
    "async-mutex": "^0.3.2",
    "bootstrap": "^5.2.0",
    "chart.js": "^3.9.1",
    "core-js": "^3.24.1",
    "esri-loader": "3.3.0",
    "font-awesome": "^4.7.0",
    "jquery": "^3.4.1",
    "ng2-charts": "4.0.0",
    "ngx-color-picker": "^12.0.1",
    "oidc-client": "^1.11.5",
    "popper.js": "^1.15.0",
    "rxjs": "^7.5.6",
    "tslib": "^2.0.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.11.7
</code></pre>

Dev Dependencies as follows:

<pre><code>
"@angular-builders/custom-webpack": "^14.0.0",
    "@angular-devkit/build-angular": "^14.1.1",
    "@angular-eslint/builder": "14.0.2",
    "@angular-eslint/eslint-plugin": "14.0.2",
    "@angular-eslint/eslint-plugin-template": "14.0.2",
    "@angular-eslint/schematics": "14.0.2",
    "@angular-eslint/template-parser": "14.0.2",
    "@angular/cli": "^14.1.1",
    "@angular/compiler-cli": "^14.1.1",
    "@angular/language-service": "^14.1.1",
    "@types/arcgis-js-api": "4.22.0",
    "@types/jasmine": "^4.0.3",
    "@types/jasminewd2": "^2.0.10",
    "@types/jquery": "^3.5.14",
    "@types/node": "^18.6.5",
    "@typescript-eslint/eslint-plugin": "5.33.0",
    "@typescript-eslint/parser": "5.33.0",
    "eslint": "^8.18.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsdoc": "^39.3.6",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "faker": "^6.6.6",
    "jasmine-core": "^4.3.0",
    "jasmine-spec-reporter": "^7.0.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "protractor": "~7.0.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.7.4"
</code></pre>

**Comment by alan-agius4** [comment] 2022-08-10 08:04
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2022-08-22 06:55
Closing due to lack of information.

**Closed by alan-agius4** 2022-08-22 06:55 UTC
Labels: need: repro steps
