### ISSUE TITLE
Commas and semicolons counted as branches in code coverage

### ISSUE THREAD

**Issue by FalloutPL** [angular/angular-cli#6600] opened 2017-06-07 07:48 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.1.0
node: 7.2.1
os: win32 ia32
@angular/animations: 4.1.3
@angular/cli: 1.1.0
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
```

### Repro steps.

```ng test --code-coverage```

### The log given by the failure.

![image](https://user-images.githubusercontent.com/5012042/26867634-6a5b824a-4b66-11e7-9d8f-714cb127be38.png)

![image](https://user-images.githubusercontent.com/5012042/26867534-04aa03cc-4b66-11e7-8771-ceb31cb9e2b6.png)

### Desired functionality.

commas and semicolons should not be counted as branches

**Comment by filipesilva** [comment] 2017-06-07 11:48
The code coverage pipeline has a bunch of moving parts (webpack loader, karma plugin, instanbul proper). This might be a problem in any of those. Needs investigation.

**Comment by FalloutPL** [comment] 2017-06-07 12:21
How i can help?

**Comment by whyboris** [comment] 2017-06-07 12:53
Can confirm the problem within my project in very many files despite 100% test coverage. For example after `@Input()` declarations and within the constructor after `private` declarations.

**Comment by sumitarora** [comment] 2017-06-07 13:37
Duplicate of: https://github.com/angular/angular-cli/issues/5871

**Closed by sumitarora** 2017-06-07 13:37 UTC
Labels: need: investigation, priority: 2 (required)
