### ISSUE TITLE
Extract i18n broken in v16 due to sourcemap issue

### ISSUE THREAD

**Issue by mattlewis92** [angular/angular-cli#25413] opened 2023-06-21 12:41 UTC
### Command

extract-i18n

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.x

### Description

Extracting i18n is broken with certain libraries after upgrading to v16.

The issue appears to be in the sourcemap processing of the library, as deleting the libraries source map fixes the issue.

I tried upgrading the library to the latest v16 (`npm i angular-calendar@next` on the reproduction repo to try it) and confirmed the issue is still present so I think the issue must be fixed in the angular CLI itself (or in a dependency?)

### Minimal Reproduction

```
git clone https://github.com/mattlewis92/angular-calendar-ng16-test.git
cd angular-calendar-ng16-test
npm i 
npx ng extract-i18n
```

### Exception or Error

```text
mattlewis@Matts-MacBook-Pro-3 angular-calendar-ng16-test % npx ng extract-i18n                                                                
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |  Raw Size
main.js             | main          |   1.96 MB | 
polyfills.js        | polyfills     | 120.30 kB | 
runtime.js          | runtime       |   6.38 kB | 

                    | Initial Total |   2.08 MB

Build at: 2023-06-21T12:35:46.006Z - Hash: 69af8508e517ec82 - Time: 2500ms

./node_modules/angular-calendar/fesm2020/angular-calendar.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
Error: /Users/mattlewis/Code/open-source/angular-calendar-ng16-test/node_modules/angular-calendar/fesm2020/angular-calendar.mjs: `column` must be greater than or equal to 0 (columns start
```

### Your Environment

```text
mattlewis@Matts-MacBook-Pro-3 angular-calendar-ng16-test % npx ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.1.0
Node: 18.16.0
Package Manager: npm 9.7.1
OS: darwin arm64

Angular: 16.1.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@angular/cli                    16.1.0
@schematics/angular             16.1.0
rxjs                            7.8.1
typescript                      5.1.3
    
```
```


### Anything else relevant?

_No response_

**Comment by clydin** [comment] 2023-06-22 14:21
Duplicate of #25414

**Closed by clydin** 2023-06-22 14:21 UTC
