### ISSUE TITLE
--style --routing and more missing from ng new since 1.4.x

### ISSUE THREAD

**Issue by dalu** [angular/angular-cli#8059] opened 2017-10-14 20:42 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.7
node: 8.7.0
os: linux x64

### Repro steps.
install angular cli >=1.4.0

### The log given by the failure.
```
# ng new --help
ng new <options...>
  Creates a new directory and a new Angular app eg. "ng new [name]".
  aliases: n
  --dry-run (Boolean) (Default: false) Run through without making any changes. Will list all files that would have been created when running "ng new".
    aliases: -d, --dryRun
  --verbose (Boolean) (Default: false) Adds more details to output logging.
    aliases: -v, --verbose
  --skip-install (Boolean) (Default: false) Skip installing packages.
    aliases: -si, --skipInstall
  --skip-commit (Boolean) (Default: false) Skip committing the first commit to git.
    aliases: -sc, --skipCommit
  --collection (String) Schematics collection to use.
    aliases: -c <value>, --collection <value>
```

### Desired functionality.
`--style` `--routing` and more present, and what is `--collection`? It's not documented.

**Comment by dalu** [comment] 2017-10-14 21:17
### Desired functionality

```
wrk ~ # npm install -unsafe-perms -g @angular/cli@1.3.2
/usr/bin/ng -> /usr/lib/node_modules/@angular/cli/bin/ng
+ @angular/cli@1.3.2
added 78 packages, removed 37 packages, updated 18 packages and moved 2 packages in 34.792s
wrk ~ # ng new --help
ng new <options...>
  Creates a new directory and a new Angular app eg. "ng new [name]".
  aliases: n
  --dry-run (Boolean) (Default: false) Run through without making any changes. Will list all files that would have been created when running "ng new".
    aliases: -d, --dryRun
  --verbose (Boolean) (Default: false) Adds more details to output logging.
    aliases: -v, --verbose
  --skip-install (Boolean) (Default: false) Skip installing packages.
    aliases: -si, --skipInstall
  --skip-git (Boolean) (Default: false) Skip initializing a git repository.
    aliases: -sg, --skipGit
  --skip-tests (Boolean) (Default: false) Skip creating spec files.
    aliases: -st, --skipTests
  --skip-commit (Boolean) (Default: false) Skip committing the first commit to git.
    aliases: -sc, --skipCommit
  --directory (String) The directory name to create the app in.
    aliases: -dir <value>, --directory <value>
  --source-dir (String) (Default: src) The name of the source directory. You can later change the value in ".angular-cli.json" (apps[0].root).
    aliases: -sd <value>, --sourceDir <value>
  --style (String) (Default: css) The style file default extension. Possible values: css, scss, less, sass, styl(stylus). You can later change the value in ".angular-cli.json" (defaults.styleExt).
    aliases: --style <value>
  --prefix (String) (Default: app) The prefix to use for all component selectors. You can later change the value in ".angular-cli.json" (apps[0].prefix).
    aliases: -p <value>, --prefix <value>
  --routing (Boolean) (Default: false) Generate a routing module.
    aliases: --routing
  --inline-style (Boolean) (Default: false) Should have an inline style.
    aliases: -is, --inlineStyle
  --inline-template (Boolean) (Default: false) Should have an inline template.
    aliases: -it, --inlineTemplate
  --minimal (Boolean) (Default: false) Should create a minimal app.
    aliases: --minimal
```

**Comment by filipesilva** [comment] 2017-10-16 13:04
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/7723. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-10-16 13:04 UTC
