### ISSUE TITLE
Add bun runtime support for faster builds

### ISSUE THREAD

**Issue by jdgriffith** [angular/angular-cli#25809] opened 2023-09-08 21:44 UTC
### Command

build

### Description

Bun is extremely fast at file IO and utilizes some of the fastest OS APIs for handling file writes/reads. It is also a quick runtime in general for any compute necessary to transpile and build. For these reasons, I think adding bun support specifically for the build process and possibly for hot reloading for the development flow, would be incredibly valuable. 

Bun just reached 1.0 and should be looked at closer as a valuable tool for increasing the DX in major projects such as this.

https://github.com/oven-sh/bun

### Describe the solution you'd like

This could maybe be implemented as a flag that is passed to utilize bun for any of the major work during the build process.

**Comment by alan-agius4** [comment] 2023-09-09 04:22
Duplicate of https://github.com/angular/angular/issues/51694

**Closed by alan-agius4** 2023-09-09 04:22 UTC
