### ISSUE TITLE
No loader is configured for ".svg" (esbuild)

### ISSUE THREAD

**Issue by noguespi** [angular/angular-cli#26336] opened 2023-11-12 10:06 UTC
### Command

build

### Description

Please add the ability to import .svg in .ts with esbuild.

Example of use case:

```
import icons from "../assets/icons/icons.svg";

export class IconModule {
  constructor(iconRegistry: MatIconRegistry, sanitizer: DomSanitizer) {
    iconRegistry.addSvgIconSetLiteral(sanitizer.bypassSecurityTrustHtml(icons))
  }
}
```
In this specific use case we could use `addSvgIconSetLiteral` and an URL but the svg won't be part of the build anymore. 

When it's part of the build we can have  size stats about svg in our bundle and possibly get the .svg files hashed (cache busting), useful when you set multiple svg files inside a single svg using symbols (which angular component icon supports btw). 

We could also import it directly in a template without having to create a [svg component](https://angular.io/guide/svg-in-templates)

### Describe alternatives you've considered

As an alternative you can rename the .svg to .txt, it will be loaded using the [esbuild text](https://esbuild.github.io/content-types/#text) loader.

**Comment by KarlXOL** [comment] 2023-11-12 15:44
Can't believe new build system has been released without having the option to at least configure this.
Like custom-webpack, ...

**Comment by alan-agius4** [comment] 2023-11-14 14:55
This is working as expected since SVG is not a valid ESM Module.

**Comment by KarlXOL** [comment] 2023-11-14 19:13
> This is working as expected since SVG is not a valid ESM Module.

It's not about "working as designed". 
It's about missing functionality making angular competitive compared to other SPA-Framework providing.

By the way, esbuild could be configured to deal with SVG. But in the way angular is integrating esbuild, this configuration option seems to be blocked.

**Closed** 2023-11-16 17:11 UTC
