### ISSUE TITLE
18.1.0: Firebase "Class extends value undefined is not a constructor or null"

### ISSUE THREAD

**Issue by niwolf** [angular/angular-cli#28038] opened 2024-07-11 13:22 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After updating to version 18.1.0. I am getting the following error on `ng-serve`: 
```
Watch mode enabled. Watching for file changes...
NOTE: Raw file sizes do not reflect development server per-request transformations.
Re-optimizing dependencies because lockfile has changed
  ➜  Local:   http://localhost:4200/
  ➜  press h + enter to show help
Re-optimizing dependencies because lockfile has changed
15:17:17 [vite] Error when evaluating SSR module /@fs/{pathToRepo}/.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js?v=de27081b:
|- TypeError: Class extends value undefined is not a constructor or null
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (/{pathToRepo}/.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js:5662:36)
```

### Please provide a link to a minimal reproduction of the bug

-

### Please provide the exception or error you saw

```true
15:17:17 [vite] Error when evaluating SSR module /@fs/{pathToRepo}/.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js?v=de27081b:
|- TypeError: Class extends value undefined is not a constructor or null
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (/{pathToRepo}/.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js:5662:36)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.0
Node: 18.20.2
Package Manager: npm 10.5.0
OS: darwin arm64

Angular: 18.1.0
... animations, build, cdk, cli, common, compiler, compiler-cli
... core, forms, material, platform-browser
... platform-browser-dynamic, platform-server, router, ssr

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1801.0
@angular-devkit/core         18.1.0
@angular-devkit/schematics   18.1.0
@angular/fire                18.0.1
@schematics/angular          18.1.0
rxjs                         7.8.1
typescript                   5.4.5
zone.js                      0.14.7
```

**Comment by clcarter** [comment] 2024-07-12 01:49
Had the same problem. Looks like the issue is caused by conflicting versions of the  `undici` dependency,  installed by `@angular/fire` and `@angular-devkit/build-angular`. 

```sh
pnpm why undici
Legend: production dependency, optional only, dev only

test@0.0.0 ~/workspace/webdocs/test

dependencies:
@angular/fire 18.0.1
├─┬ firebase 10.12.3
│ ├─┬ @firebase/auth 1.7.5
│ │ └── undici 5.28.4
│ ├─┬ @firebase/auth-compat 0.5.10
│ │ ├─┬ @firebase/auth 1.7.5
│ │ │ └── undici 5.28.4
│ │ └── undici 5.28.4
│ ├─┬ @firebase/firestore 4.6.4
│ │ └── undici 5.28.4
│ ├─┬ @firebase/firestore-compat 0.3.33
│ │ └─┬ @firebase/firestore 4.6.4
│ │   └── undici 5.28.4
│ ├─┬ @firebase/functions 0.11.6
│ │ └── undici 5.28.4
│ ├─┬ @firebase/functions-compat 0.3.12
│ │ └─┬ @firebase/functions 0.11.6
│ │   └── undici 5.28.4
│ ├─┬ @firebase/storage 0.12.6
│ │ └── undici 5.28.4
│ └─┬ @firebase/storage-compat 0.3.9
│   └─┬ @firebase/storage 0.12.6
│     └── undici 5.28.4
└─┬ rxfire 6.0.5
  └─┬ firebase 10.12.3 peer
    └─┬ @firebase/auth 1.7.5
      └── undici 5.28.4

devDependencies:
@angular-devkit/build-angular 18.1.0
├─┬ @angular/build 18.1.0
│ └── undici 6.19.2
└── undici 6.19.2
```

Fix was to simply add an override in `package.json` (Example for pnpm):
```json
  "pnpm": {
    "overrides" : {
      "undici": "6.19.2",
      "undici-types": "6.19.2"
    }
  }
```

Then, after deleting the lockfile and node_modules, and reinstalling packages, everything worked.

Hope this helps!

**Comment by niwolf** [comment] 2024-07-12 06:25
> @niwolf Can you provide a minimal reproduction for us? Otherwise there's nothing actionable here for us to look into.

@thePunderWoman Unfortunately not really, sorry.
As note: I am using SSR and AngularFire. Before updating the Angular core packages from 18.0.x to 18.1.0 everything was working fine. After updating to 18.1.0 I just got these error messages after `ng serve` compiled successfully:

```
08:15:13 [vite] Error when evaluating SSR module /@fs/Users/... {pathToMyRepo}.../.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js?v=de27081b:
|- TypeError: Class extends value undefined is not a constructor or null
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (/Users/... {pathToMyRepo}.../.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js:5662:36)
  at __require2 (/Users/... {pathToMyRepo}.../.angular/cache/18.1.0/vite/deps_ssr/chunk-INDP74QC.js:50:50)
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/formdata.js (/Users/... {pathToMyRepo}.../.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js:5854:9)
    
08:15:13 [vite] Error when evaluating SSR module /main.server.mjs:
|- TypeError: Class extends value undefined is not a constructor or null
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (/Users/... {pathToMyRepo}.../.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js:5662:36)
  at __require2 (/Users/... {pathToMyRepo}.../.angular/cache/18.1.0/vite/deps_ssr/chunk-INDP74QC.js:50:50)
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/formdata.js (/Users/... {pathToMyRepo}.../.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js:5854:9)
   
08:15:13 [vite] Internal server error: Class extends value undefined is not a constructor or null
      at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (/Users/... {pathToMyRepo}.../.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js:5662:36)
      at __require2 (/Users/... {pathToMyRepo}.../.angular/cache/18.1.0/vite/deps_ssr/chunk-INDP74QC.js:50:50)
      at node_modules/@firebase/auth/node_modules/undici/lib/fetch/formdata.js (/Users/... {pathToMyRepo}.../.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js:5854:9)
```

I hope this is helping you.

**Comment by niwolf** [comment] 2024-07-12 06:33
> Had the same problem. Looks like the issue is caused by conflicting versions of the `undici` dependency, installed by `@angular/fire` and `@angular-devkit/build-angular`.
> 
> ```shell
> pnpm why undici
> Legend: production dependency, optional only, dev only
> 
> test@0.0.0 ~/workspace/webdocs/test
> 
> dependencies:
> @angular/fire 18.0.1
> ├─┬ firebase 10.12.3
> │ ├─┬ @firebase/auth 1.7.5
> │ │ └── undici 5.28.4
> │ ├─┬ @firebase/auth-compat 0.5.10
> │ │ ├─┬ @firebase/auth 1.7.5
> │ │ │ └── undici 5.28.4
> │ │ └── undici 5.28.4
> │ ├─┬ @firebase/firestore 4.6.4
> │ │ └── undici 5.28.4
> │ ├─┬ @firebase/firestore-compat 0.3.33
> │ │ └─┬ @firebase/firestore 4.6.4
> │ │   └── undici 5.28.4
> │ ├─┬ @firebase/functions 0.11.6
> │ │ └── undici 5.28.4
> │ ├─┬ @firebase/functions-compat 0.3.12
> │ │ └─┬ @firebase/functions 0.11.6
> │ │   └── undici 5.28.4
> │ ├─┬ @firebase/storage 0.12.6
> │ │ └── undici 5.28.4
> │ └─┬ @firebase/storage-compat 0.3.9
> │   └─┬ @firebase/storage 0.12.6
> │     └── undici 5.28.4
> └─┬ rxfire 6.0.5
>   └─┬ firebase 10.12.3 peer
>     └─┬ @firebase/auth 1.7.5
>       └── undici 5.28.4
> 
> devDependencies:
> @angular-devkit/build-angular 18.1.0
> ├─┬ @angular/build 18.1.0
> │ └── undici 6.19.2
> └── undici 6.19.2
> ```
> 
> Fix was to simply add an override in `package.json` (Example for pnpm):
> 
> ```json
>   "pnpm": {
>     "overrides" : {
>       "undici": "6.19.2",
>       "undici-types": "6.19.2"
>     }
>   }
> ```
> 
> Then, after deleting the lockfile and node_modules, and reinstalling packages, everything worked.
> 
> Hope this helps!

@clcarter This also seems to work for me. Thank you vm!
Maybe the conflicting versions of the `undici` dependency, can still be fixed?

**Comment by alan-agius4** [comment] 2024-07-12 08:09
The Angular CLI does not depend on `undici`; it is solely a `devDependency` and is not installed in the user's project. The fact that the issue is resolved by the override suggests a problem with `undici` version `5.28.4`, which has been addressed in later versions. Therefore, it is likely that the `firebase` packages should be updated to use a newer version of `undici`.

**Comment by muuvmuuv** [comment] 2024-07-12 08:52
Also having an issue with 18.1.0 where it reports an error on new let-syntax. I noticed that Angular now has `@angular/build`, did they move away from `@angular-devkit/build-angular`?

```
✘ [ERROR] NG5002: Incomplete block "let c". If you meant to write the @ character, you should use the "&#64;" HTML entity instead. [plugin angular-compiler]
```

**Comment by niwolf** [comment] 2024-07-12 08:58
> The Angular CLI does not depend on `undici`; it is solely a `devDependency` and is not installed in the user's project. The fact that the issue is resolved by the override suggests a problem with `undici` version `5.28.4`, which has been addressed in later versions. Therefore, it is likely that the `firebase` packages should be updated to use a newer version of `undici`.

@alan-agius4 Thanks for your answer.
Ok, I only use AngularFire. Can AngularFire be updated when the `firebase` packages were updated to use a newer version of `undici`? So that might fix the issue, won't it?

**Comment by niwolf** [comment] 2024-07-12 09:06
> AngularFire is managed by the firebase team.

Alright, got it. Thanks again!

**Comment by alan-agius4** [comment] 2024-07-15 14:07
Closing this since there are no actionable items for us at this time.

**Closed by alan-agius4** 2024-07-15 14:07 UTC
Labels: needs: repro steps

**Comment by Ken-Wainwright** [comment] 2024-07-18 10:07
I have the exact same problem. I have setup a new web app project in Visual Code and did not change any code at all. Everything works fine. then I add @angular/fire and the first error I got was  No overload matches this call.
  Overload 1 of 3, '(options: FirebaseOptions, name?: string | undefined): FirebaseApp', gave the following error.
    Object literal may only specify known properties, and '"locationId"' does not exist in type 'FirebaseOptions'.
  Overload 2 of 3, '(options: FirebaseOptions, config?: FirebaseAppSettings | undefined): FirebaseApp', gave the following error.
    Object literal may only specify known properties, and '"locationId"' does not exist in type 'FirebaseOptions'. [plugin angular-compiler]

I commented out the locationID line but then I got 0:48:08 [vite] Error when evaluating SSR module /@fs/C:/Users/HP ProDesk i5/angularWorkspace/web-app/.angular/cache/18.1.1/vite/deps_ssr/chunk-UEELBQ5E.js?v=9fb4ba3a:
|- TypeError: Class extends value undefined is not a constructor or null       
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (eval 
at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:5603:36)
    at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:53:50)
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/formdata.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:5795:9)
    at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:53:50)
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/body.js (eval 
at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:5971:9)
    at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:53:50)
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/response.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:13858:9)
    at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:53:50)
    at node_modules/@firebase/auth/node_modules/undici/index.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:19773:33)  
    at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:53:50)

10:48:08 [vite] Error when evaluating SSR module /@fs/C:/Users/HP ProDesk i5/angularWorkspace/web-app/.angular/cache/18.1.1/vite/deps_ssr/@angular_fire_firestore.js?v=9fb4ba3a:
|- TypeError: Class extends value undefined is not a constructor or null       
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (eval 
at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:5603:36)
    at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:53:50)
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/formdata.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:5795:9)
    at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:53:50)
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/body.js (eval 
at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:5971:9)
    at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:53:50)
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/response.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:13858:9)
    at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:53:50)
    at node_modules/@firebase/auth/node_modules/undici/index.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:19773:33)  
    at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), <anonymous>:53:50)

I I decided to check things out and the app runs fine if I comment out
 //provideFirestore(() => getFirestore()),
    //provideStorage(() => getStorage()),

**Comment by JGSolutions** [comment] 2024-07-20 01:49
@clcarter 
what is pnpm? Is it another object nderneath devDependencies?
"devDependencies": { ... },
  "pnpm": {
    "overrides" : {
      "undici": "6.19.2",
      "undici-types": "6.19.2"
    }
  }

**Comment by clcarter** [comment] 2024-07-20 05:33
[pnpm](https://pnpm.io/) is a package management system, like yarn or npm itself.  In this case, I am using pnpm as my package manager and this is how you override package versions in pnpm. Here, `undici` and `undici-types` are the only dependencies for which I'm enforcing version resolution.

 For yarn you would either use the [`yarn set resolution`](https://yarnpkg.com/cli/set/resolution) command, or you would add the [resolutions](https://yarnpkg.com/configuration/manifest#resolutions) object to your `package.json`.

 ```sh
"resolutions": {
  "undici": "6.19.2",
  "undici-types": "6.19.2"
}
```

For npm, as of version 8.3, you can use the top-level `overrides` object:

```sh
"overrides" : {
  "undici": "6.19.2",
  "undici-types": "6.19.2"
}
```
reference: https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions

**Comment by JGSolutions** [comment] 2024-07-20 12:24
thx @clcarter works.

I hope the angularFire team and implement a proper fix for this but. So far so good. :)

**Comment by AhsanAyaz** [comment] 2024-08-06 09:47
Thanks @clcarter . That helped! ❤️ 
Hoping the the firebase team fixes this soon!

**Comment by alexdabast** [comment] 2024-08-12 09:32
@JGSolutions and @AhsanAyaz if no body raise the issue on angular/fire repo I doubt that it will be fixed ...

**Comment by JGSolutions** [comment] 2024-08-12 16:49
Sad!

**Comment by saifullahamin** [comment] 2024-08-14 17:34
@clcarter works, thanks.

**Comment by robertIsaac** [comment] 2024-08-18 13:32
BTW disabling angular cache `ng cache disable` fix the problem

**Comment by robertIsaac** [comment] 2024-08-18 14:07
@clcarter using 
```
"overrides" : {
  "undici": "6.19.2",
  "undici-types": "6.19.2"
}
```

while make `ng serve` works
it makes my tests fails
```
    ReferenceError: ReadableStream is not defined

      3 | import type { CreateUserDto } from '@interviews/models';
      4 | import type { User } from '@prisma/client';
    > 5 | import { getAuth, onAuthStateChanged } from 'firebase/auth';
        | ^
      6 | import { BehaviorSubject, Observable, filter, of } from 'rxjs';
      7 | import { catchError, tap } from 'rxjs/operators';
      8 | import { environment } from '../../environments/environment';

      at Object.<anonymous> (../../node_modules/undici/lib/web/fetch/response.js:536:3)
      at Object.<anonymous> (../../node_modules/undici/lib/web/fetch/index.js:11:5)
      at Object.<anonymous> (../../node_modules/undici/index.js:106:19)
      at Object.<anonymous> (../../node_modules/@firebase/auth/dist/node/totp-e2052706.js:7:14)
      at Object.<anonymous> (../../node_modules/@firebase/auth/dist/node/index.js:5:12)
      at Object.<anonymous> (../../node_modules/firebase/auth/dist/index.cjs.js:5:12)
```
