### ISSUE TITLE
Need a way to configure Autoprefixer

### ISSUE THREAD

**Issue by fr0** [angular/angular-cli#6145] opened 2017-05-01 22:01 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.0.1
node: 6.10.2
os: darwin x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0

### Repro steps.

Not a bug.

### The log given by the failure.

N/A

### Desired functionality.

I have an app that uses css grid. I get the following error after running `ng serve --open`:
```
IE supports only grid-row with / and span. You should add grid: false option to Autoprefixer and use some JS grid polyfill for full spec support
```
So, it's telling me I need to configure Autoprefixer via autoprefixer({grid: false}) to make this error go away. However, until I saw this error I had no idea what autoprefixer was, or that I was even using it.

Where do I add this configuration? Yes, I know my app won't support IE if I do this. That's fine.

**Comment by clydin** [comment] 2017-05-02 22:06
Warnings are currently being reported as errors for ng serve in development mode.  This should be corrected in the release.

**Comment by fr0** [comment] 2017-05-03 01:00
That's great to hear!
For users like me who aren't concerned with IE11 and want to configure Autoprefixer to not show those warnings at all, is there an option to configure it (without using the `ng eject` command, since that has other consequences)?
Thanks for the response.

**Comment by filipesilva** [comment] 2017-05-03 10:25
Closing as a duplicate of #6150.

@fr0 there is no such option, no. Overall we do want users to see warnings.

**Closed by filipesilva** 2017-05-03 10:25 UTC
