### ISSUE TITLE
Shared assets across locales

### ISSUE THREAD

**Issue by demurgos** [angular/angular-cli#26853] opened 2024-01-11 19:50 UTC
### Command

build

### Description

I am using `@angular-devkit/build-angular:application` with `"assets"` and `"localize": true`.

The way these options interact, each locale gets its own separate directory in `./dist/<appName>/browser/<locale>/` and there's no way to place shared assets at the root of the browser directory `./dist/<appName>/browser`.

This means in particular that if I define `"assets": ["./src/favicon.ico"]`, it gets placed at paths such as `/en-US/favicon.ico` and not `/favicon.ico` (this breaks the expected file location).

### Describe the solution you'd like

Shared and localized assets should be differentiated, probably by adding an option to `assetPattern`. This should control if the output is relative to the browser root or localized dir.

### Describe alternatives you've considered

A workaround is to have a manual post-build step to copy the assets, but it's messy.

**Comment by alan-agius4** [comment] 2024-01-11 20:06
Duplicate of https://github.com/angular/angular-cli/issues/26286

**Closed by alan-agius4** 2024-01-11 20:06 UTC
