### ISSUE TITLE
ng [commandname] -- help  throws error for few cli commands outside angular project

### ISSUE THREAD

**Issue by ManoharNuli** [angular/angular-cli#13128] opened 2018-12-04 08:06 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ x] build
- [ x] serve
- [ x] test
- [ x] e2e
- [ x] generate
- [ x] add
- [ ] update
- [ x] lint
- [ x] xi18n
- [ x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node v10.14.1
npm 6.4.1
ng 7.1.1
windows 10 Enterprise
64bit
 x64 -based processer
os win32

### Repro steps

Install angular cli globally
Open command shell from any location
Run the below command
ng add --help

### The log given by the failure

Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\GGUB\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:35:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\GGUB\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:22:49)
    at E2eCommand._loadWorkspaceAndArchitect (C:\Users\GGUB\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:176:49)
    at E2eCommand.initialize (C:\Users\GGUB\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:28:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

### Desired functionality

C:\angular\app1>ng add --help
arguments:
  collection
    The package to be added.

options:
  --defaults
    When true, disables interactive input prompts for options with a default.
  --dry-run (-d)
    When true, runs through and reports activity without writing out results.
  --force (-f)
    When true, forces overwriting of existing files.
  --help
    Shows a help message for this command in the console.
  --interactive
    When false, disables interactive input prompts.

### Mention any other details that might be useful

Help command works only inside angular project folder for all the commands. The above mentioned commands expects the user to be inside angular project folder and throws error on angular.json file. The Documentation on CLI doesn't mention this point.

**Comment by alan-agius4** [comment] 2018-12-04 08:19
Duplicate of #12454

**Closed by alan-agius4** 2018-12-04 08:19 UTC
