### ISSUE TITLE
load css、scss error when use symbolic link

### ISSUE THREAD

**Issue by lihuabest** [angular/angular-cli#19708] opened 2021-01-04 05:32 UTC
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [x ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No.

### Description

angular cli not load css、scss files when node_modules created by symbolic link in window10, angular v8,v9 has this problem.

![微信图片_20210104131838](https://user-images.githubusercontent.com/1559817/103503490-63684600-4e8f-11eb-9d81-4cf35d04fbfb.png)

## 🔬 Minimal Reproduction
No.
## 🔥 Exception or Error
<pre><code>
mklink /d  "target folder\node_modules" "source folder\node_modules"

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.2
Node: 13.13.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.2 (cli-only)
@angular-devkit/core         11.0.2 (cli-only)
@angular-devkit/schematics   11.0.2 (cli-only)
@schematics/angular          11.0.2 (cli-only)
@schematics/update           0.1100.2 (cli-only)

</code></pre>

**Anything else relevant?**
No.

**Comment by alan-agius4** [comment] 2021-01-04 07:25
Duplicate of https://github.com/angular/angular-cli/issues/3500

**Closed by alan-agius4** 2021-01-04 07:25 UTC
