### ISSUE TITLE
Entry for test is ignored when using ng test --app

### ISSUE THREAD

**Issue by franktroia** [angular/angular-cli#6702] opened 2017-06-15 21:14 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.1.1
node: 6.10.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

### Repro steps.

1. ng new some-project
2. Add a new application to `.angular-cli.json` and change the test entry values.
```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "some-project"
  },
  "apps": [
    {
      "root": "src",
      "name": "first",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "first.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    },
    {
      "root": "src",
      "name": "second",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "second.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }    
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```
3. Execute `ng test --app second`

### The log given by the failure.

```
ERROR in Entry module not found: Error: Can't resolve 'd:\temp\newcli\one-six\src\first.ts' in 'd:\temp\newcli\one-six\node_modules\@angular\cli\models\webpack-configs'
```
Since neither first.ts or second.ts exists, I would expect the error to indicate second.ts was not found. Even if I add the files, only first.ts is used.

### Desired functionality.

The entry file for test when using multiple apps should be honored.

**Comment by Bobdina** [comment] 2017-07-14 11:09
Problem seems to be here:
https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/models/webpack-configs/test.ts#L22

**Comment by EdwinMeijne** [comment] 2017-10-19 13:24
I am encountering this issue as well. I see that @Bobdina committed a PR but never signed the agreement.
Would it be possible for this few lines of code to somehow still end up in the codebase?

**Comment by Bobdina** [comment] 2017-10-19 14:32
@EdwinMeijne 
Well, I did sign the cla, but apparently my checkins are registered under a different (fake) email address than the one I used to sign. I'm not a git expert, and I looked up how to fix it, but it seemed quite complicated at the time (I recall having to rewrite your entire git version history?). I gave up then and there, hoping someone else would pick this up.

The changeset is like 2 lines of code (smaller than the workaround), so of course anyone is free to retry that same commit properly.

**Comment by magemello** [comment] 2017-10-26 18:31
is this issue fixed?

**Comment by EdwinMeijne** [comment] 2017-11-09 07:13
We decided we would want to test all code when doing changes, as our plan is to create 10+ apps within the same repository which mostly share library code and the core redux store. So didn't investigate further.

**Comment by yfain** [comment] 2018-01-25 22:54
The issue still exists in Angular CLI 1.6.5.

**Comment by AngularTx** [comment] 2018-04-10 17:47
any updates on this issues ?

**Comment by alan-agius4** [comment] 2018-10-08 11:33
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2018-10-08 11:33 UTC
Labels: priority: 2 (required), severity3: broken
