### ISSUE TITLE
Flag to disable build/serve colors for text viewers that don't support them

### ISSUE THREAD

**Issue by rsxdalv** [angular/angular-cli#6478] opened 2017-05-26 12:50 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.0.0

### Repro steps.

ng build >> log.txt

### The log given by the failure.

`chunk    {[1m[33m4[39m[22m} [1m[32minline.bundle.js, inline.bundle.js.map[39m[22m (inline) 0 bytes[1m[33m [entry][39m[22m[1m[32m [rendered][39m[22m
`

### Desired functionality.

There's no way to disable colors in output. Leading to lines and lines of:
`chunk    {[1m[33m4[39m[22m} [1m[32minline.bundle.js, inline.bundle.js.map[39m[22m (inline) 0 bytes[1m[33m [entry][39m[22m[1m[32m [rendered][39m[22m
`
in log files. This makes log lines absurdly long and generally reader unfriendly. Plus, the color option being only available for testing makes it even more confusing, as one would expect such an option to be global.

### Mention any other details that might be useful.

This is an issue with any non-console or otherwise color unsupporting viewer. For both builds and live reload, in high reliance systems it doesn't seem viable to constantly designate a terminal window for the output of one component of the product, since 95+% of the time you won't need it.

**Comment by rsxdalv** [comment] 2017-05-26 13:01
Note: currently this can be removed like this on UNIX:
`ng build | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"  > log.txt`
According to: https://stackoverflow.com/a/18000433
It works for me, however, I cannot guarantee it's consistency, so exercise caution when piping your logs.

**Comment by ivanseidel** [comment] 2017-06-30 13:13
This should be a bare basic option for Angular cli, as it is intended to be used within a CI, and it might not have color support out of the box (With Jenkins + Blue Ocean for instance, it cannot be achieved. And the logs are just crazy and hard to look at)

<img width="1224" alt="screen shot 2017-06-30 at 10 13 14" src="https://user-images.githubusercontent.com/3102127/27736968-c8238dc8-5d7c-11e7-8e16-bb89b24f2d5f.png">
<img width="1239" alt="screen shot 2017-06-30 at 10 13 19" src="https://user-images.githubusercontent.com/3102127/27736972-cc1aface-5d7c-11e7-8e41-393cb2fc0fca.png">

**Comment by rsxdalv** [comment] 2017-06-30 14:25
@ivanseidel There are some things that help improve it, like, --no-progess (or similar). But I know your feeling, it's a shock, especially before there was an issue, and it felt like no one else had ever launched it on jenkins or redirected stdout to file and seen the horror.

**Comment by haidaraM** [comment] 2017-07-28 07:41
I think this option should be a must have. I'm facing the same problem when I deploy my application with GitLab CI and Ansible. The logs are almost unreadable because of the coloring. 

The coloring is pretty nice but sometimes useless when using some CI tools.

**Comment by zstadler** [comment] 2017-08-02 06:50
Based on @rsxdalv comment above, when running `ng build` in MS-Studio's Package Manager Console, the escape sequences can be removed using
```
ng build --progress=false | %{$_ -replace "\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]",""}
```

**Comment by textbook** [comment] 2017-08-03 17:08
Given that the colours seem to be based on [chalk](https://www.npmjs.com/package/chalk), which uses [supports color](https://github.com/chalk/supports-color), I'd expect setting the env variable `FORCE_COLOR=0` to *"forcefully disable"* the colours, but this doesn't work either.

**Comment by rsxdalv** [comment] 2017-08-04 07:30
@textbook That's when this feature gets fun, isn't it?

**Comment by jmacloue** [comment] 2018-01-10 20:58
Funny thing, it looks like the following line in angular-cli sources is responsible for colorizing the ``ng build`` output:

https://github.com/angular/angular-cli/blob/b6b8acc1bf9928fc8016d77980dc61e9d978876b/packages/%40angular/cli/models/webpack-configs/utils.ts#L8

It's compiled into ``utils.js`` version upon install, and if you replace ``colors`` property value with ``false`` there - the color is gone everywhere in angular-cli output. So, despite dependency on ``supports-color``, it just isn't invoked by ``ng build ...``.

Actually I'd consider it a bug rather than a feature request - other angular-cli commands seem to use ``supports-color`` correctly - e.g., ``ng help | less`` doesn't show color codes. I suppose it's because the ``webpack`` options override becomes global somehow.

**Comment by v-karbovnichy** [comment] 2018-01-11 18:34
@sumitarora consider changing the label to `type: bug` as per previous comment, and also maybe change the priority 🙏

**Comment by mmuehlberger** [comment] 2018-07-16 15:12
Just an update for everyone interested (as I've spend some time investigating this issue myself today): This will be fixed in `@angular-devkit/build-angular` v0.7.0 as they removed `chalk` and are using their own `terminal` capabilities from `@angular-devkit/core`. Haven't seen this mentioned anywhere though.

You can use an environment variable like `CI=1`, to disable color output if you're doing something custom, but it seems it's already preconfigured, for the most common solutions.

See here how it's determined if to use colors or not: https://github.com/angular/angular-cli/blob/44086c60ff1d6c26d30850bef125120f6c498ac1/packages/angular_devkit/core/src/terminal/caps.ts#L79-L144

**Comment by zstadler** [comment] 2018-07-16 15:39
It looks like setting the `CI` environment variable will not work on Windows platforms.

**Comment by scsprong** [comment] 2018-08-02 08:12
Please use the environment variable NO_COLOR to align with the NO_COLOR-project: http://no-color.org/

**Comment by jschank** [comment] 2018-09-15 19:06
For me, using a solarized theme in my terminal, the output is particularly unreadable.
![ng_cli_colors](https://user-images.githubusercontent.com/30314/45589730-e0570680-b8f8-11e8-8df5-bb51b0e328c1.png)

**Comment by syndicatedshannon** [comment] 2019-08-22 22:26
#13426

**Comment by clydin** [comment] 2020-01-04 01:04
Numerous improvements in this area have been made to the Angular CLI since this issue has been opened.  The latest version of the CLI should no long present the problems described.  However,  if the problem is still being encountered with the latest version, please open a new issue detailing the problem.

**Closed by clydin** 2020-01-04 01:04 UTC
Labels: comp: devkit/core, type: feature
