### ISSUE TITLE
ng update not respecting the user level .npmrc auth token

### ISSUE THREAD

**Issue by gaborari** [angular/angular-cli#21439] opened 2021-07-28 12:19 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11.1.0

### Description

 I have a private npm feed which provides packages for internal projects.
The projects are having their own .npmrc files (project-level npmrc) without tokens - the tokens could be found in the user-level .npmrc file (c:\users\xxx\\.npmrc).

Updating the mentioned package is performed by `ng update mypackage` in the projects.

Issues started to rise about a week ago - when performing the `ng update mypackage`:

With non-latest cli, 11.1.0, after it downloads a version dynamically:

Found 174 dependencies.
Fetching dependency metadata from registry...
Error fetching metadata for 'mypackage': Unable to authenticate, need: Bearer authorization_uri=....", TFS-Federated

After updating to the latest cli, I get similar error:

An unhandled exception occurred: Unable to authenticate, need: Bearer authorization_uri

Based on my debugging, the newer cli versions are not picking up the tokens from the user-level npmrc.
If I add the tokens to the project-level npmrc files, then the ng update could be performed - but this is not a viable option, committing tokens to the repositories would be a problem.

## 🔬 Minimal Reproduction

`ng update mypackage`

where mypackage is accessible in a private repository, and the project level npmrc file contains only the registry setting, and always-auth true

## 🔥 Exception or Error

<pre><code>
Error fetching metadata for 'mypackage': Unable to authenticate, need: Bearer authorization_uri=....", TFS-Federated

An unhandled exception occurred: Unable to authenticate, need: Bearer authorization_uri
</code></pre>

## 🌍 Your Environment

<pre><code>
local cli (but when performing the update, the cli downloads a newer version)
Angular CLI: 11.1.0
Node: 12.18.4
OS: win32 x64

Angular CLI: 12.1.3
Node: 12.18.4
Package Manager: npm 6.14.6
OS: win32 x64

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-07-28 12:45
Same root cause of https://github.com/angular/angular-cli/issues/21406 which will be addressed in the next release.

**Closed by alan-agius4** 2021-07-28 12:45 UTC
