### ISSUE TITLE
angular 17 all dynamic routes loads very slow 

### ISSUE THREAD

**Issue by shubhamsyal007** [angular/angular-cli#28379] opened 2024-09-09 13:02 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

angular 17 all dynamic routes loads very slow when page is reloading from the browser or on opening it on new tab. tried adding all my dynamic routes in routes.txt before ng-build by a script but what if routes which i am getting from cms get updated or number of routes gets increase in the cms than i have to regenarate routes.txt and also there are 7-8k dynamic pages it is difficult to prerender them.

### Please provide the exception or error you saw

```true
Everything is described above.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.5
Node: 18.20.2
Package Manager: npm 10.5.0
OS: darwin arm64

Angular: 17.3.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.14
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            16.2.14
@angular-devkit/schematics      17.3.5
@angular/flex-layout            14.0.0-beta.41
@angular/ssr                    17.3.6
@schematics/angular             17.3.5
rxjs                            6.6.7
typescript                      5.4.5
zone.js                         0.14.4
```

### Anything else?

my server.ts file
import { APP_BASE_HREF } from '@angular/common';
import { CommonEngine } from '@angular/ssr';
import express from 'express';
import { createWindow } from 'domino';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import bootstrap from './src/main.server';
import { readFileSync } from 'fs';
var DomParser = require('dom-parser')

import 'localstorage-polyfill'
// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const serverDistFolder = dirname(fileURLToPath(import.meta.url));
  const browserDistFolder = resolve(serverDistFolder, '../browser');
  const indexHtml = join(serverDistFolder, 'index.server.html');
  const template = readFileSync(join(browserDistFolder, 'index.html')).toString();
const win = createWindow(template);
(global['window'] as Window) = win;
Object.defineProperty(win.document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true,
    };
  },
});
global['document'] = win.document;
global['DOMParser'] = DomParser
global['localStorage'] = localStorage;

const commonEngine = new CommonEngine({
  enablePerformanceProfiler: false,
});

  server.set('view engine', 'html');
  server.set('views', browserDistFolder);

  // Example Express Rest API endpoints
  // server.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(browserDistFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Angular engine
  server.get('*', (req, res, next) => {
    const { protocol, originalUrl, baseUrl, headers } = req;

    commonEngine
      .render({
        bootstrap,
        documentFilePath: indexHtml,
        url: `${protocol}://${headers.host}${originalUrl}`,
        publicPath: browserDistFolder,
        providers: [{ provide: APP_BASE_HREF, useValue: baseUrl }],
      })
      .then((html) => res.send(html))
      .catch((err) => next(err));
  });

  return server;
}

function run(): void {
  const port = process.env['PORT'] || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

run();

**Comment by atscott** [comment] 2024-09-09 15:43
Transferring to CLI repo but my first impression is that this is just due to no prerendering on these routes and is working as expected.

**Comment by alan-agius4** [comment] 2024-09-09 15:47
I believe this is functioning as expected, with requests being rendered at runtime rather than prerendered. Several factors could contribute to the slow performance, including API call delays, network latency, a large DOM, or the use of inline critical CSS. It's also crucial to ensure that server-side rendered (SSR) pages are properly cached.

However, without at least a CPU profile or a minimal reproduction of the issue, it's difficult to take any actionable steps on our end.

**Closed** 2024-09-09 17:50 UTC

**Comment by shubhamsyal007** [comment] 2024-09-10 04:11
> I believe this is functioning as expected, with requests being rendered at runtime rather than prerendered. Several factors could contribute to the slow performance, including API call delays, network latency, a large DOM, or the use of inline critical CSS. It's also crucial to ensure that server-side rendered (SSR) pages are properly cached.
> 
> However, without at least a CPU profile or a minimal reproduction of the issue, it's difficult to take any actionable steps on our end.

i need to make all these dynamic pages fast. It load only loads page fast when that route is added in routes.txt. Is there any other way that we can fix it ? by changing some configuration in angular.json file?

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "website": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath": "dist/website",
            "index": "src/index.html",
            "browser": "src/main.ts",
            "polyfills": [
              "zone.js"
            ],
            "tsConfig": "tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/sitemap.xml",
              "src/website-sitemap.xml",
              "src/robots.txt",
              "src/.well-known/assetlinks.json",
              "src/.well-known/apple-app-site-association",
              {
                "glob": "**/*",
                "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
                "output": "/assets/"
              }
            ],
            "styles": [
              "src/styles.scss",
              "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css"
            ],
            "scripts": [
              "src/assets/lib/hljs/highlight.pack.js"
            ],
            "server": "src/main.server.ts",
            "prerender": true,    
            "ssr": {
              "entry": "server.ts"
            },
            "extractLicenses": false,
            "sourceMap": true,
            "optimization": true,
            "namedChunks": true
          },
          "configurations": {
            "prod": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "20kb"
                }
              ]
            },
            "staging": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.staging.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "20kb"
                }
              ]
            }
          },
          "defaultConfiguration": ""
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "website:build",
            "proxyConfig": "src/proxy.conf.json"
          },
          "configurations": {
            "prod": {
              "browserTarget": "website:build:production"
            },
            "staging": {
              "browserTarget": "website:build:staging"
            }
          }
        }
      }
    }
  },
  "cli": {
    "analytics": false
  }
}

**Comment by shubhamsyal007** [comment] 2024-09-10 06:06
> Transferring to CLI repo but my first impression is that this is just due to no prerendering on these routes and is working as expected.

how can i enable prerendering for dynamic routes also. Above, i have added my angular.json file

**Comment by alan-agius4** [comment] 2024-09-10 06:27
Please see: https://angular.dev/guide/prerendering

**Comment by shubhamsyal007** [comment] 2024-09-10 06:48
> Please see: https://angular.dev/guide/prerendering

i tries this too but to add all these 7k-8k routes in routes.txt is very difficult and to prerender these much pages is quite difficult too and i am fetching this route data from cms but after build is once done after than route is added to cms than this prerendering will not be applicable on it. and if i need to create build everytime cms gets update so there is no point to use cms

**Comment by alan-agius4** [comment] 2024-09-10 08:10
@shubhamsyal007, in your case, it seems that SSR might be a better solution than prerendering. As for the slowness, there could be multiple factors contributing to it, as mentioned earlier.
