### ISSUE TITLE
Ng new command throwing error

### ISSUE THREAD

**Issue by tvarghesedt** [angular/angular-cli#12924] opened 2018-11-10 08:39 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version
v10.13.0

npm --version
6.4.1

ng --version

Angular CLI: 7.0.5
Node: 10.13.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.5
@angular-devkit/core         7.0.5
@angular-devkit/schematics   7.0.5
@schematics/angular          7.0.5
@schematics/update           0.10.5
rxjs                         6.3.3
typescript                   3.1.6

OS- Windows 7

### Repro steps

I ran the "ng new myworkspace" command 

### The log given by the failure

I got the following log in command prompt terminal-

CREATE myworkspace/e2e/src/app.po.ts (208 bytes)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

### Desired functionality

I would like to create a new workspace/app

### Mention any other details that might be useful

None in mind for now

**Comment by alan-agius4** [comment] 2018-11-10 11:03
Duplicate of #12670

**Closed by alan-agius4** 2018-11-10 11:03 UTC

**Comment by Jatin-8898** [comment] 2018-12-12 15:59
Same Error as Above.
Kindly help to fix this issue.
