### ISSUE TITLE
@angular/common/http Type definitions not exported for VS Code by default

### ISSUE THREAD

**Issue by Waddlen** [angular/angular-cli#21521] opened 2021-08-06 17:38 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new

### Is this a regression?

 I did not experience this issue with Angular 10

### Description

`@angular/common/http` type definitions are not exported for VS Code in a fresh Angular project

## 🔬 Minimal Reproduction

`ng new myApp`
open myApp in VS Code
open `app.component.ts` and add this constructor: `constructor(private http: HttpClient, private router: Router) {}`
VS Code has intellisense to import `@angular/router`, but not `@angular/common/http`

## 🌍 Your Environment

<pre><code>Angular CLI: 12.2.0
Node: 14.17.4
Package Manager: npm 6.14.14
OS: linux x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1202.0 (cli-only)
@angular-devkit/core         12.2.0 (cli-only)
@angular-devkit/schematics   12.2.0 (cli-only)
@schematics/angular          12.2.0 (cli-only)
</code></pre>

**Anything else relevant?**
Related to #16879, same problem in [this user's comment](https://github.com/angular/angular-cli/issues/16879#issuecomment-683898655) after the issue was closed.

Workaround: manually add `@angular/common/http` type definitions with `tsconfig.json` 
```
  "compilerOptions": {
    "typeRoots": ["node_modules/@types", "node_modules/@angular/common/http"]
    ... // other compiler options
  },

**Comment by clydin** [comment] 2021-08-06 17:42
Duplicate of angular/angular#40407

**Closed by clydin** 2021-08-06 17:42 UTC
