### ISSUE TITLE
Pass extra terser options through the angular.json

### ISSUE THREAD

**Issue by AlexAegis** [angular/angular-cli#14487] opened 2019-05-21 17:41 UTC
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

Right now I can't just add these extra terser options to a custom webpack config and expect it to work because the "bundleOptimizer: true" option would just overwrite the whole thing. (Given the nature of the config I'm not expecting that this would be possible anytime, hence this proposal:) If I'd to disable that, I'd need to re-implement the whole thing just to change one option. And when I do it naively with a simple setup it straight up fails. (Probably because ng8 now builds both legacy and modern bundles and would require different setups, as I've seen that in this repo where the default config is assembled. But I have no way differentiating that in a custom config file.)

### Describe the solution you'd like

Add a terserOptions config option -- which accepts an object -- into the project's angular.json config (under architect.build.configurations.production). And merge it into the default terserOptions object if exists. (This one here: https://github.com/angular/angular-cli/blob/74f2ee68d6d166903d5ef571d8a793bd4994e142/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L284)

### Use-case

I'd like to have the terser option "keep_classnames" turned on (set to a set of classes which are to be persisted) because of a serialization/deserialization mechanic that resolves the class that belongs to a JSON (stored in a database) by the name of the class. If the name of the class is minified,  these persistent, serialized objects would not be cross-compatible between dev and prod builds. Also there's no guarantee that between different prod versions these minified class names wouldn't change over time.

**Comment by alan-agius4** [comment] 2019-05-21 17:49
Duplicate of #3861 and #11910

**Closed by alan-agius4** 2019-05-21 17:49 UTC
