### ISSUE TITLE
Ability to disable asset optimization locally

### ISSUE THREAD

**Issue by rightisleft** [angular/angular-cli#3203] opened 2016-11-19 04:17 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OS X 10.12.1

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.19-3
node: 6.7.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Vanilla Client 

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
It says here that we cannot modify the webpack config:
https://github.com/angular/angular-cli/issues/1656#issuecomment-240171375

However, there are 2 optional steps in the asset pipeline that take forever to compile
5882ms chunk asset optimization
3979ms asset optimization

Please expose a way to either configure webpack or disable these optional steps for development mode.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-12-22 17:34
This is essentially a dupe of https://github.com/angular/angular-cli/issues/1980.

**Closed by filipesilva** 2016-12-22 17:34 UTC
