### ISSUE TITLE
AoT: The keyword 'private' is reserved

### ISSUE THREAD

**Issue by drager** [angular/angular-cli#2890] opened 2016-10-25 20:26 UTC
### OS?

Linux (Ubuntu)
### Versions.

angular-cli: 1.0.0-beta.18
node: 6.3.1
os: linux x64
TypeScript Version 2.1.0-dev.20161025 (I believe the same problem occurred with 2.0.3 as well)
### Repro steps.

This is the code that the causes the error:

``` ts
import {Component, Input} from '@angular/core'
import {Location} from '@angular/common'
import {Router, ActivatedRoute, NavigationEnd} from '@angular/router'
import {Angular2Apollo} from 'angular2-apollo'
import gql from 'graphql-tag'
import {NgRedux} from 'ng2-redux'

@Component({
  selector: 'top-bar',
  templateUrl: 'template.html',
  styleUrls: ['style.scss'],
})
export class TopBar {
  constructor(
    private apollo: Angular2Apollo,
    private location: Location,
    private reduxStore: NgRedux<any>,
    private route: ActivatedRoute,
    private router: Router,
  ) {
    ...
  }
}
```
### The log given by the failure.

``` /src/app/components/top-bar/top-bar.ts
Module parse failed: node_modules/angular-cli/node_modules/@ngtools/webpack/src/index.js!src/app/components/top-bar/top-bar.ts The keyword 'private' is reserved (20:12)
You may need an appropriate loader to handle this file type.
| toggleRightMenu: Function;
| toggleLeftMenu: Function;
| constructor(private, apollo, Angular2Apollo, private, location, Location, private, reduxStore, NgRedux < any > , private, route, ActivatedRoute, private, router, Router);
| {
|     this.router.events
 @ ./src/app/app.ngfactory.ts 23:0-57
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/main.ts
```

**Comment by SeerUK** [comment] 2016-10-26 17:57
Have you tried updating to a newer version of angular-cli? I can't reproduce this issue. It looks like an error with the webpack config not handling .ts files properly. What command did you run to get this error?

**Comment by drager** [comment] 2016-10-26 19:06
@SeerUK: I there any newer version than `1.0.0-beta.18`? I ran `ng serve --aot`

**Comment by SeerUK** [comment] 2016-10-26 19:11
Aah, my bad about the version - I thought I'd seen a newer one. That's strange, the code does look fine. Can you reproduce this with a new project with similar code?

**Comment by skovmand** [comment] 2016-10-30 13:11
I have this error too! I have no idea what to do. I'm running webpack-2.0.0-beta.25 with @ngtools/webpack, so no Angular CLI as I would like to keep my webpack build system.

Here is my error trace:

```
ERROR in ./src/app/sections/search/components/tag-selector.component.ts
Module parse failed: /Users/skovmand/Code/web/idraetsmusik.dk/idraetsmusik.dk/node_modules/@ngtools/webpack/src/index.js!/Users/skovmand/Code/web/idraetsmusik.dk/idraetsmusik.dk/src/app/sections/search/components/tag-selector.component.ts Unexpected token (14:41)
You may need an appropriate loader to handle this file type.
|         this.currentTagStream = tagChanged;
|     }
|     TagSelector.prototype.EventEmitter = ;
|     return TagSelector;
| }());
 @ ./src/app/sections/search/pages/track-search-by-tag-page.component.ngfactory.ts 31:0-65
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/main.ts

ERROR in ./src/app/sections/search/components/sortable-column.component.ts
Module parse failed: /Users/skovmand/Code/web/idraetsmusik.dk/idraetsmusik.dk/node_modules/@ngtools/webpack/src/index.js!/Users/skovmand/Code/web/idraetsmusik.dk/idraetsmusik.dk/src/app/sections/search/components/sortable-column.component.ts The keyword 'private' is reserved (25:12)
You may need an appropriate loader to handle this file type.
|     sortChangedSubscription;
| Subscription;
| constructor(private, trackSearchEvents, TrackSearchEventService, protected, el, ElementRef);
| { }
| // Since we are initialising the subscription on ngOnInit, we must make sure the stream is replaying events, since there will be a period without listeners.
 @ ./src/app/sections/search/components/all-tracks.component.ngfactory.ts 35:0-56
 @ ./src/app/sections/search/pages/all-tracks-page.component.ngfactory.ts
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/main.ts
```

In the first error something has disappeared:
```TagSelector.prototype.EventEmitter = ;```

In the second error it has listed private as a separate parameter:
```constructor(private, trackSearchEvents, TrackSearchEventService, protected, el, ElementRef);```

**Comment by cederigo** [comment] 2016-11-01 22:16
Same issue here. I'm using:
```sh
$ ng version
angular-cli: 1.0.0-beta.18
node: 6.5.0
os: darwin x64
Typescript: 2.0.6
```

It has something to do with semicolons ;-) Steps to reproduce:
```sh
$ ng new ola
$ cd ola && npm install @angular/compiler-cli @angular/platform-server --save
```

Edit `app.component.ts`:
```typescript
import { Component, Input } from '@angular/core';
import { Location } from '@angular/common';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @Input() a: string /* missing ; */
  @Input() b: string /* missing ; */
  @Input() c: string /* missing ; */

  constructor(private l: Location) {}
}
```
```sh
$ ng serve --aot # Causes same error as described above
```

Things I tried:
 - Remove `@Input()` decorator -> Fixes issue
 - Remove 3rd input -> Fixes issue
 - Add semicolons -> Fixes issue

Im interested in whats really going on here!

**Comment by skovmand** [comment] 2016-11-02 06:34
Interesting! My codebase is not using semicolons at all. I'll try to see it adding semicolons fixes the error.

**Comment by skovmand** [comment] 2016-11-02 06:50
Adding semicolons fixes the problem here too.

**Comment by skovmand** [comment] 2016-11-02 19:14
I have found that if I add semicolons to all @Input and @Output and @ViewChild annotations (maybe other too, haven't checked yet), the errors go away.

**Comment by filipesilva** [comment] 2016-11-04 16:18
This seems like a bug but I can't say if it's on the CLI or on `ngc`. Will tag and leave open.

**Comment by finalxcode** [comment] 2016-12-02 05:41
Except semicolons error, when you use aot,  should the keyword 'private'  be change to 'public'?

**Comment by hansl** [comment] 2017-02-23 18:48
On the contrary; private members are not accessible by templates. The fact they are in JIT is an error (which I think is corrected). Always use public members or `@Input`.

Closing this as obsolete. Please file a new issue if you still have problems.

**Closed by hansl** 2017-02-23 18:48 UTC
Labels: command: build, feature: aot, priority: 2 (required)
