### ISSUE TITLE
Open the app straightaway with "ng serve"

### ISSUE THREAD

**Issue by huyph** [angular/angular-cli#1911] opened 2016-08-31 01:45 UTC
`ng serve` doesn't automatically open the app. I am wondering if there is any config to achieve this.

Thanks.

**Comment by sudhashri** [comment] 2016-08-31 04:02
lite-server can be used in place of livereload server(angular-cli default server). Lite-server is only for production ready.

**Comment by filipesilva** [comment] 2016-09-21 00:52
Dupe of https://github.com/angular/angular-cli/issues/1081

**Closed by filipesilva** 2016-09-21 00:52 UTC
