### ISSUE TITLE
ng lint fails after fresh install - lists no files

### ISSUE THREAD

**Issue by Blasz** [angular/angular-cli#1021] opened 2016-06-06 04:15 UTC
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux Ubuntu 14.04 

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

```
$ ng --version
(node:7726) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.5
node: 6.2.1
os: linux x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

```
ng new foo
cd foo
ng lint
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
$ ng lint
(node:7613) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

> foo@0.0.0 lint /home/vagrant/foo
> tslint "src/**/*.ts"


Lint errors found in the listed files.
```

5. Mention any other details that might be useful.

Not sure if this is related to the node fs/watchman lines that are output after every ng command (annoying).

**Comment by delight** [comment] 2016-06-06 12:40
duplicate of #867 ... error is fixed with #848 

you can manually edit tslint.json or wait for the next angular-cli release

**Comment by filipesilva** [comment] 2016-06-07 17:01
Closing as duplicate, but I reopened the other issue to reflect that tslint shouldn't swallow errors as a user there commented.

**Closed by filipesilva** 2016-06-07 17:01 UTC

**Comment by vkniazeu** [comment] 2016-10-07 12:30
FWIW, same just happened to me with Angular 2.0.2 update.
