### ISSUE TITLE
CLI is ignoring defaults.styleExt

### ISSUE THREAD

**Issue by eatinasandwich** [angular/angular-cli#7682] opened 2017-09-13 14:14 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.1

### Repro steps.

Run "ng set defaults.styleExt scss" 
Run "ng g c my/component"

Also had previously altered .angular-cli.json with defaults.styleExt = scss

### The log given by the failure.

```
C:\git\nps_portal>ng set defaults.styleExt scss

C:\git\nps_portal>ng g c hub/narwhal
  create src/app/hub/narwhal/narwhal.component.html (26 bytes)
  create src/app/hub/narwhal/narwhal.component.spec.ts (635 bytes)
  create src/app/hub/narwhal/narwhal.component.ts (273 bytes)
  create src/app/hub/narwhal/narwhal.component.css (0 bytes)
  update src/app/hub/hub.module.ts (1041 bytes)
```

### Desired functionality.

CLI should generate stylesheets with the extension found in defaults.styleExt

### Mention any other details that might be useful.

Was previously using version 1.2.6 and did not have this issue.

**Comment by Empereol** [comment] 2017-09-13 15:04
I can confirm this is also happening to me with version `1.4.1`.

**Comment by AhsanAyaz** [comment] 2017-09-13 17:46
Duplicate of #7624, #7644 & #7647,& #7522

**Closed** 2017-09-13 17:52 UTC
