### ISSUE TITLE
`ng g component my-component` adds Backslashes on app.module.ts on Windows

### ISSUE THREAD

**Issue by 4lador** [angular/angular-cli#2132] opened 2016-09-15 13:32 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

## Environment : 
Windows 10
angular-cli: 1.0.0-beta.14
node: 6.3.1
os: win32 x64

## Reproduce

1. App created on Windows, using angular-cli@webpack `ng new newapp`.
2. Creating and moving to another folder inside the app root folder : `mkdir app/feature && cd app/feature`
3. Creating a new component using the angular-cli@webpack `ng g component my-component`

## Error
```
Module not found: Error: Can't resolve './feature
egister-form/register-form.component' in 'E:\Dev\Learning\shooping-angular2\src\app'
```

## Helpful informations
Details : On Windows, in the app.module.ts, the path is created using a backslash as first char after the current path.

`import { RegisterFormComponent } from './feature\register-form/register-form.component';`

should become:

`import { RegisterFormComponent } from './feature/register-form/register-form.component';`

**Comment by LucasReSilva** [comment] 2016-09-15 14:11
Same here 
## Environment :
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: win32 x64

**Comment by mbaljeetsingh** [comment] 2016-09-20 17:31
The issue is still there with the cli beta 15

> angular-cli: 1.0.0-beta.15
> node: 4.4.6
> os: win32 x64

Anybody looking into it?

**Comment by gelliott181** [comment] 2016-09-29 12:57
It'd be really nice if we could get a quick response from the team acknowledging this issue. This isn't some breaking feature, but given the cross-platform nature, proper path generation is more an expected functionality than a nice to have feature.

**Comment by filipesilva** [comment] 2016-10-05 16:36
Dupe of https://github.com/angular/angular-cli/issues/1719, already fixed.

**Closed by filipesilva** 2016-10-05 16:36 UTC
