### ISSUE TITLE
cant install error

### ISSUE THREAD

**Issue by mid0ri** [angular/angular-cli#3033] opened 2016-11-06 07:48 UTC
I have installed the latest npm but when I try to install angular-cli it wont install. 
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> npm(version 3.10

### Repro steps.
>npm install -g angular-cli

**Comment by mid0ri** [comment] 2016-11-06 07:50
[shit.txt](https://github.com/angular/angular-cli/files/573701/shit.txt)

**Comment by B0BBB** [comment] 2016-11-08 14:11
following can't install the either.... me and all my project team
So frustarating .....

**Comment by filipesilva** [comment] 2016-11-16 17:26
Your log shows errors like this:

```
53595 verbose stack Error: ENOENT: no such file or directory, rename 'C:\Users\Khanh\AppData\Roaming\npm\node_modules\.staging\abbrev-de033a53' -> 'C:\Users\Khanh\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
```

That is a dupe of https://github.com/angular/angular-cli/issues/1190, see that issue for solutions.

**Closed by filipesilva** 2016-11-16 17:26 UTC
