### ISSUE TITLE
Option to generate environments when creating a new Angular in versions 15 and higher

### ISSUE THREAD

**Issue by Marius-Romanus** [angular/angular-cli#24433] opened 2022-12-14 11:28 UTC
### Command

new

### Description

Hello,

I haven't been able to figure out the real reason for removing the environments in version 15 of the CLI, other than to simplify the configuration (which I'm fine with).

But I think it would at least be interesting to have an option (https://angular.io/cli/new#options) when creating a new Angular project to automatically generate the files as before, since in many cases the environments are still used.

If I'm not mistaken, the autogenerated files are:

```
src/environments/environment.ts
src/environments/environment.prod.ts
```

Changes when generating angular.json:

```
"fileReplacements": [
         {
          "replace": "src/environments/environment.ts",
          "with": "src/environments/environment.prod.ts"
         }
 ],
```

regards!

### Describe the solution you'd like

By default it would be the same as now, but by adding the "--environments" flag, it would remain the same as before version 15.

**Comment by alan-agius4** [comment] 2022-12-14 13:23
Duplicate of https://github.com/angular/angular-cli/issues/24381

**Closed by alan-agius4** 2022-12-14 13:23 UTC
