### ISSUE TITLE
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]                                                                                                      19% building modules 77/93 modules 16 active ..._modules/@angular/common/esm5/http.jsError: No module factory available for dependency type: ContextElementDependency

### ISSUE THREAD

**Issue by LuisBonsembiante** [angular/angular-cli#8736] opened 2017-12-04 20:27 UTC
ng-version 1.5.5

npm start

the problem ocurred when you try to start de server with npm start

**Comment by clydin** [comment] 2017-12-04 21:02
Thanks for reporting this issue. However, this issue appears to be a duplicate of an existing issue #6417.  This comment in particular may be useful: https://github.com/angular/angular-cli/issues/6417#issuecomment-334859000

**Closed by clydin** 2017-12-04 21:02 UTC
