### ISSUE TITLE
Regression in Angular12: fingerprint resources

### ISSUE THREAD

**Issue by acalvo** [angular/angular-cli#21268] opened 2021-07-02 09:14 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 11

### Description

 Up to Angular11 we could make:

```typescript
import icons from '../assets/icons.svg';
```

This way, the asset was fingerprinted when compiled for production. But this solution was removed in https://github.com/angular/angular-cli/commit/6732294ff34ca35698cec5a9ca91b664dd684289 . From that commit I understand that now it should work without anything else... but it doesn't at least in this case.

## 🔬 Minimal Reproduction

Just try to import a SVG and use it later for something (like passing it to Material):

```typescript
import icons from '../assets/icons.svg';

...

matIconRegistry.addSvgIconSet(domSanitizer.bypassSecurityTrustResourceUrl(icons));
```

## 🔥 Exception or Error

<pre><code>
./src/assets/icons.svg:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.1.0
Node: 14.17.1
Package Manager: npm 7.19.0
OS: darwin x64

Angular: 12.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@schematics/angular             12.1.0
rxjs                            6.6.7
typescript                      4.3.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-07-02 09:22
This is working as intended and only assets referenced in CSS are fingerprinted.

In version 12, we removed the undocumented, unsupported Webpack feature to require an asset as if it was an ECMA module using this also had the side effect of fingerprinting assets not referenced in CSS. 

Duplicate of https://github.com/angular/angular-cli/issues/20816

**Comment by alan-agius4** [comment] 2021-07-02 09:26
A better alternative would be to control your caching policy or introduce a service worker that takes care of that.

**Closed by alan-agius4** 2021-07-02 09:26 UTC

**Comment by acalvo** [comment] 2021-07-02 09:34
Ok... actually we wanted to fingerprint it as part of our caching policy. If it has the hash in its name, we can set aggressive cache policies for that file. Otherwise, if it's a generic `icons.svg`, we can't cache it as it can change anytime.

Would this be considered if opened as a feature request? Or is something that doesn't fit in the Angular roadmap?
