### ISSUE TITLE
node-gyp disaster

### ISSUE THREAD

**Issue by vitaly-t** [angular/angular-cli#3428] opened 2016-12-06 09:55 UTC
I work as an Angular JS developer in the banking industry, and it hurts me to say that this tool while almost indispensable for any serious Angular 2.0 project, is plagued by its dependency on `node-gyp`.

The latter is bringing so much pain when trying to deploy `angular-cli` across multiple DEV machines, it often puts a halt on any effort migrating from Angular 1.x.

Please guys, heed this, and consider an implementation approach that avoids any `node-gyp` dependency, begging you! :pray:

**Comment by hansl** [comment] 2016-12-06 20:54
We are looking at getting rid of `node-sass` itself and letting projects that need sass support to install it themselves. As it stands now we depend on `node-sass` which uses `node-gyp`. Closing this is a dupe of #3199.

**Closed by hansl** 2016-12-06 20:54 UTC
