### ISSUE TITLE
[ERROR] No loader is configured for ".less"

### ISSUE THREAD

**Issue by ivomju** [angular/angular-cli#24584] opened 2023-01-20 12:19 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

@angular-devkit/build-angular:browser

### Description

The team tried the new builder `@angular-devkit/build-angular:browser-esbuild` but face one particular issue with `.less` files. When we build using the previous version that error don't occur.

### Minimal Reproduction

What we did was:
- Replace `@angular-devkit/build-angular:browser` by `@angular-devkit/build-angular:browser-esbuild`
- Ran the following `ng build project-name --configuration production`

While running, this error appeared:

<img width="502" alt="Screenshot 2023-01-20 at 12 07 46" src="https://user-images.githubusercontent.com/4333168/213692822-2b5cb9f0-e307-47aa-964c-57b3f8a30b53.png">

But, replacing back the builder to the older one, everything is working fine.

### Exception or Error

```text
✘ [ERROR] No loader is configured for ".less" files: src/theme.less
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.0.4
Node: 18.12.1
Package Manager: npm 8.19.2
OS: darwin x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@angular/cdk                    15.0.3
@schematics/angular             15.0.4
rxjs                            7.8.0
typescript                      4.8.4
```

### Anything else relevant?

Another thing that we notice was that the esbuild doesn't log the result of the build on the console.

**Comment by alan-agius4** [comment] 2023-01-20 12:34
Duplicate of https://github.com/angular/angular-cli/issues/24329

**Closed by alan-agius4** 2023-01-20 12:34 UTC
