### ISSUE TITLE
Build tree shaking do not remove every unused code 

### ISSUE THREAD

**Issue by adrienboulle** [angular/angular-cli#21725] opened 2021-09-08 11:05 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

I have generated a new project - `ng create test-ts` - and added just a few unused variables and only one that is used.

(in grey, unused variables):

![image](https://user-images.githubusercontent.com/14262895/132498324-a344ae04-8699-4515-b9d4-55c4f08cc230.png)

Extract from generated main.js:

![image](https://user-images.githubusercontent.com/14262895/132497661-cb5f06ad-08ad-4106-9a60-ca97c518862e.png)

The `kpiResourceMap` is in the final bundle (and unassigned) but never used in the app, so it should be removed. 

### Please provide a link to a minimal reproduction of the bug

https://github.com/MYRE-CORP/test-ts

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.4
Node: 14.15.3
Package Manager: npm 7.21.0
OS: Ubuntu
```

**Comment by clydin** [comment] 2021-09-08 15:55
This case is related to dead code elimination safety.  In the above code, `new Map` is at the module level which will cause the expression to be executed at module evaluation time.  Such code that can possibility have side effects cannot be safely removed since removal may alter the behavior of the application at runtime.  Since the `Map` constructor has the possibility of throwing an exception it has possible side effects.  Determining whether the `Map` construction is safe at build time is a non-trivial analysis effort for JavaScript and one which current optimizers do not perform.  However, if the expression has been manually reviewed to be side effect free, the expression can be annotated to provide a hint to the optimizer that it is safe to be removed.  This should be possible by adding a pure annotation as a leading comment similar to the following:
`const kpiResourceMap = /*#__PURE__*/ new Map(....)`

**Comment by adrienboulle** [comment] 2021-09-08 17:58
@clydin ok I see, thanks for those explantions

What about that case?

![image](https://user-images.githubusercontent.com/14262895/132560144-9f51119f-50f4-453f-98d9-032e30ade6ee.png)

![image](https://user-images.githubusercontent.com/14262895/132560190-409eb2f4-3c79-42bc-8c71-c8da6ecff0f4.png)

The class have two static functions, one calling the other, the class is never used and the static functions also never used _outside_ the class. Class is not tree shakened, is it also because it really to analyse in fact the code is unused ?

**Comment by clydin** [comment] 2021-09-09 14:21
If that is the output of a server build, then that would currently be the expected behavior.  Server builds are currently not intended to be as completely optimized as browser builds since they not transferred to the client and are typically part of long lived processes with cached runtime representations of the code.  For example (and in this case specifically), server builds attempt to keep the names of classes and functions and do not minify identifiers.  This behavior has been based on prior user request/feedback and can be adjusted in the future based on additional use cases and/or concerns.

**Comment by alan-agius4** [comment] 2021-09-10 17:50
@adrienboulle, is the above server code?

**Comment by alan-agius4** [comment] 2021-09-21 07:45
Closing due to lack of communication.

**Closed by alan-agius4** 2021-09-21 07:45 UTC
Labels: need: more info
