### ISSUE TITLE
`ng test` does not work in WebStrom 2016.3.1: "Chrome have not captured"

### ISSUE THREAD

**Issue by jongunter** [angular/angular-cli#3324] opened 2016-11-30 17:16 UTC
### OS?
Windows 8.1

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 6.3.0
os: win32 x64

### Repro steps.
1. Initiated a CLI project using WebStorm. Make zero changes to the code.
2. Run `ng test` using the WebStorm terminal
3. Chrome launches but Karma can never connect to it.

**If I try this using my terminal outside of WebStorm (Cmder), the tests run fine**

### The log given by the failure.
```
30 11 2016 10:12:48.013:WARN [karma]: No captured browser, open http://localhost:9876/
30 11 2016 10:12:48.036:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
30 11 2016 10:12:48.038:INFO [launcher]: Launching browser Chrome with unlimited concurrency
30 11 2016 10:12:48.050:INFO [launcher]: Starting browser Chrome
30 11 2016 10:13:48.054:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
30 11 2016 10:13:48.331:INFO [launcher]: Trying to start Chrome again (1/2).
30 11 2016 10:14:48.335:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
30 11 2016 10:14:48.563:INFO [launcher]: Trying to start Chrome again (2/2).
30 11 2016 10:15:48.566:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
30 11 2016 10:15:48.790:ERROR [launcher]: Chrome failed 2 times (timeout). Giving up.
```

**Comment by jongunter** [comment] 2016-11-30 17:24
Hmmm...it seems changing the port number in `karma.conf.js` fixed the issue for me. But why was it only failing in WebStorm (I checked to make sure nothing else was using that port)? 

If other people are experiencing this issue, perhaps we could add a warning in the documentation, or even change the port number?

**Comment by filipesilva** [comment] 2016-12-30 10:46
I'll leave this open for a while to see if more people have the issue. I think it's pretty weird it only happens with webstorm, maybe it's using that specific port for some console communication.

**Comment by chenop** [comment] 2017-04-18 16:51
For me,

Testing on Intellij 15.0.6 - works ok, Karma connected
Testing on Webstorm 16.3.6 - works ok, Karma connected

I failed to reproduce the problem.
Maybe this is something local that blocks you?

#goodnessSquad

**Comment by ctrl-brk** [comment] 2017-04-18 17:02
I'm having similar issue on my work machine. It will not capture Chrome if there's an already open Chrome instance. It will open a new tab but than give up. If I close all Chrome windows and than run tests it seems to work. Might be because of stupid security restrictions we have here.
On my home machine everything works fine. It will always open a new Chrome window, not tab, no matter if there are any other open windows.

**Comment by filipesilva** [comment] 2017-05-22 14:37
Closing as outdated.

**Closed by filipesilva** 2017-05-22 14:37 UTC
Labels: community: help wanted
