### ISSUE TITLE
run: ' ng build --prod' error

### ISSUE THREAD

**Issue by wangyajundev** [angular/angular-cli#15640] opened 2019-09-20 06:56 UTC
`ng build --prod`

err:
An unhandled exception occurred: EEXIST: file already exists, copyfile '/Users/r/repository/ng-app/node_modules/.cache/angular-build-dl/content-v2/sha512/36/86/afb82f76da09848c154ccb79a5213dc67698763412e526216fbce17a94bd0b1762da3627677b3ee97a05cdc837739fdc4dbdc08b13fbd50cbb0fb9a0b512' -> '/Users/r/repository/ng-app/dist/ng-app/runtime-es2015.85f895af57b038f1e5b4.js'
See "/private/var/folders/33/pdb8zsnj3vgf_b11ylqm28jm0000gn/T/ng-NfpxH9/angular-errors.log" for further details.

```
Angular CLI: 8.3.5
Node: 11.10.0
OS: darwin x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.5
@angular-devkit/build-angular     0.803.5
@angular-devkit/build-optimizer   0.803.5
@angular-devkit/build-webpack     0.803.5
@angular-devkit/core              8.3.5
@angular-devkit/schematics        8.3.5
@angular/cli                      8.3.5
@ngtools/webpack                  8.3.5
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by alan-agius4** [comment] 2019-09-20 11:26
Duplicate of https://github.com/angular/angular-cli/issues/15544

Should be fixed in the next release.

**Closed by alan-agius4** 2019-09-20 11:26 UTC

**Comment by wangyajundev** [comment] 2019-09-24 08:35
using v12.10.0 is no problem.
