### ISSUE TITLE
Cant Install Angular

### ISSUE THREAD

**Issue by RkSabando** [angular/angular-cli#18461] opened 2020-08-06 09:45 UTC
can't install angular using 'npm i -g @angular/cli'

![Screen Shot 2020-08-06 at 5 41 28 PM](https://user-images.githubusercontent.com/56343034/89517670-a0f77300-d80c-11ea-9037-5f4b4154822f.png)

**Comment by cfi2017** [comment] 2020-08-06 09:48
This seems to be the same issue as #18459 and 18460 and possibly #18458.

**Comment by alan-agius4** [comment] 2020-08-06 11:21
Duplicate of https://github.com/angular/angular-cli/issues/18460

**Closed by alan-agius4** 2020-08-06 11:21 UTC
