### ISSUE TITLE
Service is not automatically provided - minor improvement

### ISSUE THREAD

**Issue by skonx** [angular/angular-cli#9916] opened 2018-03-09 15:45 UTC
At the present time, a service is not provided (and not set in the provider list) of the specified module.
In the previous versions, it was automatically provided.
Should be confortable to re-set this feature ;)

### Versions
```
Angular CLI: 1.7.3
Node: 6.10.3
OS: darwin x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.2.3
@angular/cli: 1.7.3
@angular/material-moment-adapter: 5.2.3
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack-bundle-analyzer: 2.11.1
webpack: 3.11.0
```

### Repro steps

`ng g service core/MySuperService -m core --spec false` won't add MySuperService in the provider list of CoreModule.

**Comment by hansl** [comment] 2018-06-07 17:30
With Tree-shakable providers, you no longer need to provide your service in a module. This is a new feature in Angular 6 that makes it easier to setup and use services, and tree shake them away when they're not needed.

Closing this as Working as Intended.

**Closed by hansl** 2018-06-07 17:30 UTC
Labels: comp: cli/generate
