### ISSUE TITLE
Show some inidcation of progress during long-running migrations

### ISSUE THREAD

**Issue by mcalmus** [angular/angular-cli#20820] opened 2021-05-17 12:49 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem or missing capability...

Some migrations run for a very long time with no user feedback. For instance, the "Updates the Angular CDK to v12." migration ran for > 20 minutes with no indication whether something had hung or was just taking a long time.

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

It would be nice to have some visual indication the process was continuing, even if it was going to be a long time. Even displaying dots that indicated passage of time would be better than the way it is now.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment] 2021-05-17 12:53
Duplicate of https://github.com/angular/angular-cli/issues/12479

**Closed by alan-agius4** 2021-05-17 12:53 UTC
