### ISSUE TITLE
angular 6 issue with loading(lazyloading) child modules

### ISSUE THREAD

**Issue by adityarw** [angular/angular-cli#10821] opened 2018-05-12 11:26 UTC
const routes: Routes = [
  {
    path: 'customers',
    loadChildren: 'app/customers/customers.module#CustomersModule'
  },
  {
    path: 'orders',
    loadChildren: 'app/orders/orders.module#OrdersModule'
  },
  {
    path: '',
    redirectTo: '',
    pathMatch: 'full'
  }
];

in the above example it giving error like this "modules not found"
to make above example to work i need to import child modules in app modules..

when i changed from app/ to ./ it is working fine .

as anything changed in angular 6 or is it a bug please let me know.. and solution to use like as before (loadChildren: 'app/orders/orders.module#OrdersModule')???

const routes: Routes = [
  {
    path: 'customers',
    loadChildren: './customers/customers.module#CustomersModule'
  },
  {
    path: 'orders',
    loadChildren: './orders/orders.module#OrdersModule'
  },
  {
    path: '',
    redirectTo: '',
    pathMatch: 'full'
  }
];

**Comment by iwe7** [comment] 2018-05-12 12:09
应该是个bug

**Comment by WineyeLiu** [comment] 2018-05-14 03:51
i have this problem too
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.0
Node: 8.10.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0
@angular-devkit/core         0.6.0
@angular-devkit/schematics   0.6.0
@schematics/angular          0.6.0
@schematics/update           0.6.0
rxjs                         6.1.0
typescript                   2.7.2

**Comment by WineyeLiu** [comment] 2018-05-14 06:07
i have the same problem.
thank you, it works well when i change app/ to ./ 
i think it's not a bug. the angular doc should get updated.

**Comment by alan-agius4** [comment] 2018-08-30 08:54
Closing as indeeded it doesn't look like a bug

**Closed by alan-agius4** 2018-08-30 08:54 UTC
Labels: comp: devkit/build-angular

**Comment by adityarw** [comment] 2018-08-30 09:10
@alan-agius4  then why it is not working??
