### ISSUE TITLE
'event emitter' is working strange when build with --prod option.

### ISSUE THREAD

**Issue by bjkimFlitto** [angular/angular-cli#9179] opened 2018-01-12 09:07 UTC
### Versions
```
Angular CLI: 1.6.2
Node: 8.9.0
OS: darwin x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps
```
* ng serve --prod OR ng build --prod
```

### Observed behavior

1. There are 3 `@Output.`
2. Excute one of `EventEmitter` that I want to emit.
3. It emits other `EventEmitter` that placed on end of code.
4. `EventEmitter` that I want to emit is even not excuted.

**child.component.ts**
```
@Output() onSelectItem = new EventEmitter<any>();
@Output() onSelectAll = new EventEmitter<any>();
@Output() onPageChanged = new EventEmitter<any>();

selectItem(item) {
  this.onSelectItem.emit(item);  // emit this event.
}
```
**parent.component.html**
```
<app-child
      (onSelectItem)="onSelectItem($event)"
      (onSelectAll)="selectAllItems($event)"
      (onPageChanged)="listChanged($event)"></app-child>
```

**parent.component.ts**
```
onSelectItem($event) {
  console.log('onSelectItem');
}

selectAllItems($event) {
  console.log('onSelectAll');
}

listChanged($event) {
  console.log('listChanged');
} 
```

**result of output** 
```
listChanged
```

### Desired behavior
It works well on `dev` environments.
It works strange only when I build with `--prod` option.

### Mention any other details that might be useful (optional)
Below list are what I tried.
- change all default prod options to dev options. 
https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds
- update UglifyJS version to 3.3.4
- make new project with `ng new` command and to same thing like my project. (It works well.)
- change order of event Emitters that I want to emit to end of code. (EventEmitter that placed end of code only works.)

Here is my Package.json 
```
{
  "dependencies": {
    "@angular/animations": "^4.4.3",
    "@angular/common": "^4.4.3",
    "@angular/compiler": "^4.4.3",
    "@angular/core": "^4.4.3",
    "@angular/forms": "^4.4.3",
    "@angular/http": "^4.4.3",
    "@angular/platform-browser": "^4.4.3",
    "@angular/platform-browser-dynamic": "^4.4.3",
    "@angular/router": "^4.4.3",
    "@auth0/angular-jwt": "^1.0.0-beta.8",
    "@swimlane/ngx-charts": "^6.1.0",
    "body-parser": "^1.18.1",
    "bootstrap": "^3.3.7",
    "brace": "^0.10.0",
    "cookie-parser": "^1.4.3",
    "cors": "^2.8.4",
    "d3": "^4.11.0",
    "express": "^4.15.3",
    "express-param": "^1.0.2",
    "file-saver": "^1.3.3",
    "fluent-ffmpeg": "^2.1.2",
    "font-awesome": "^4.7.0",
    "geoip-lite": "^1.2.1",
    "google-auth-library": "^0.11.0",
    "googleapis": "^22.2.0",
    "icheck": "^1.0.2",
    "jquery": "^3.2.1",
    "jquery-slimscroll": "^1.3.8",
    "jsonwebtoken": "^7.4.3",
    "jwt-simple": "^0.5.1",
    "lodash": "^4.17.4",
    "metismenu": "^2.7.0",
    "moment": "^2.20.1",
    "multer": "^1.3.0",
    "mydaterangepicker": "^4.1.9",
    "ng-socket-io": "^0.1.91",
    "ngx-bootstrap": "^1.9.3",
    "ngx-mydatepicker": "^2.3.4",
    "ngx-toastr": "^5.3.1",
    "ngx-ui-switch": "1.3.9",
    "node-rdkafka": "^1.0.6",
    "passport": "^0.4.0",
    "passport-jwt": "^3.0.0",
    "pg": "^7.3.0",
    "pg-hstore": "^2.3.2",
    "pg-native": "^2.2.0",
    "request": "^2.83.0",
    "request-promise": "^4.2.2",
    "rxjs": "^5.5.6",
    "sequelize": "^4.28.6",
    "socket.io": "^2.0.3",
    "socket.io-client": "^2.0.3",
    "spinkit": "^1.2.5",
    "ts-express-decorators": "2.2.0",
    "underscore": "^1.8.3",
    "watson-developer-cloud": "^2.34.0",
    "xlsx": "^0.11.2",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.2",
    "@angular/compiler-cli": "^4.4.3",
    "@angular/language-service": "^4.4.3",
    "@types/body-parser": "^1.16.4",
    "@types/chai": "^4.0.3",
    "@types/connect-redis": "0.0.6",
    "@types/express": "^4.11.0",
    "@types/geoip-lite": "^1.1.29",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.9",
    "@types/jsonwebtoken": "^7.2.3",
    "@types/metismenu": "^2.6.1",
    "@types/mocha": "^2.2.43",
    "@types/multer": "^1.3.2",
    "@types/node": "^6.0.95",
    "@types/passport": "^0.3.3",
    "@types/passport-jwt": "^2.0.23",
    "@types/request": "^2.0.0",
    "@types/sequelize": "^4.0.80",
    "@types/socket.io": "^1.4.29",
    "@types/supertest": "^2.0.2",
    "chai": "^4.1.1",
    "codelyzer": "~3.0.1",
    "concurrently": "^3.5.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "mocha": "^4.0.1",
    "nodemon": "^1.14.1",
    "protractor": "~5.1.2",
    "supertest": "^3.0.0",
    "ts-node": "^3.0.6",
    "tslint": "~5.3.2",
    "typescript": "^2.6.2",
    "uglify-js": "^2.8.29"
  }
}

```

**Comment by Brocco** [comment] 2018-01-12 15:47
I was not able to reproduce this error with this setup... https://stackblitz.com/edit/angular-uwxra8?file=app%2Fapp.component.ts

Also, tried locally w/ a CLI project with the same code using both dev and prod builds.

**Comment by bjkimFlitto** [comment] 2018-01-16 02:55
@Brocco I guess it's because of uglify or target es version.

here is my config files for more info.

**.angular-cli.json**
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "test"
  },
  "apps": [
    {
      "root": "client",
      "outDir": "dist-public",
      "assets": [
        "assets",
        "favicon.ico",
        "login.html",
        "login-style.css",
        "animate.css"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "vt",
      "styles": [
        "styles.scss"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/metismenu/dist/metisMenu.js",
        "../node_modules/jquery-slimscroll/jquery.slimscroll.min.js",
        "../node_modules/file-saver/FileSaver.js",
        "../node_modules/icheck/icheck.min.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "dev1": "environments/environment.dev1.ts",
        "dev2": "environments/environment.dev2.ts",
        "dev3": "environments/environment.dev3.ts",
        "stg": "environments/environment.stg.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "component": {
    }
  },
  "warnings": {
    "typescriptMismatch": false
  }
}

```

**tsconfi.json**
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "client",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "types":[
      "node",
      "chai",
      "mocha",
      "express",
      "reflect-metadata"
    ]
  }
}
```

**tsconfig.app.json**
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": [
      "node"
    ]
  },
  "exclude": [
    "server/**/*",
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

**Comment by bjkimFlitto** [comment] 2018-01-24 03:39
@clydin just wonder any process or need more info?

**Comment by bjkimFlitto** [comment] 2018-01-24 03:42
@clydin I think it could be some info.
I ask at stackoverflow about angular-cli build issue. not same issue but it also happen when build with prod options.
https://stackoverflow.com/questions/48092392/filereader-api-doesnt-wok-with-angular4

**Comment by filipesilva** [comment] 2018-01-31 10:00
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment] 2018-09-18 16:49
Closing as no re-production was provided.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2018-09-18 16:49 UTC
Labels: comp: devkit/build-angular, need: repro steps

**Comment by LeoCreer** [comment] 2018-11-02 22:14
I am having the same issue.
