### ISSUE TITLE
Error should describe which property has issue in visitPropertyWrite();

### ISSUE THREAD

**Issue by valllabh** [angular/angular-cli#15528] opened 2019-09-05 06:25 UTC
"Cannot assign to a reference or variable!"
If above error occurs in browser it's  absolutely impossible to trace which ref or variable is causing the issue.

Consider huge application with 100s of developers working if someone messes up it is not possible to trace which variable has caused issue without modifying `compiler_util/expression_converter.ts` OR `compiler.js` to trace.

In below code error should also describe which variable has caused an issue possibly in which file. I wonder how compiler is missing this while building error is coming in browser only.
https://github.com/angular/angular/blob/58be2ff88400d7dc876d357f8cc3eb01b0912aae/packages/compiler/src/compiler_util/expression_converter.ts#L552

**Comment by alan-agius4** [comment] 2019-09-05 08:30
Duplicate of https://github.com/angular/angular-cli/issues/15432

**Closed by alan-agius4** 2019-09-05 08:30 UTC
