### ISSUE TITLE
Invalid resource URL

### ISSUE THREAD

**Issue by janousek** [angular/angular-cli#20968] opened 2021-05-27 13:47 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes.

### Description

Resource URL generated by WebpackResourceLoader is invalid. It is caused by this line:
https://github.com/angular/angular-cli/blob/638344afe1774ea5573b26def4b2a41cc14f6b8b/packages/ngtools/webpack/src/resource_loader.ts#L110

It should looks like this:
```
const entry = data ? `angular-resource://${resourceType},${hash}` : filePath; 
```

This is regression caused by this change:
https://github.com/angular/angular-cli/commit/8e741e187a2885c52e97ef084b5cbbf20d9c89fe#diff-8f746eb1f9444d4c0e52eea0175d6a080fd8f7c38b8c8056e5abba89de3337c4

For me, this bug currently causes this error during i18n extraction:

> angular-resource:style,13704965354860b52a891d7d35de9bb3:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by clydin** [comment] 2021-05-27 14:00
That's a valid URI.  A data URI, for instance, are of the form `data:[<mediatype>][;base64],<data>` (no slashes).

The error there is caused by the content failing to parse.

**Comment by janousek** [comment] 2021-05-27 14:08
@clydin If this is correct URI, then the bug is here:
https://github.com/angular/angular-cli/blob/638344afe1774ea5573b26def4b2a41cc14f6b8b/packages/angular_devkit/build_angular/src/extract-i18n/index.ts#L243
Because it requires slashes.

**Comment by clydin** [comment] 2021-05-27 14:09
Yes. that should be corrected.  However, that would only affect i18n extraction and not a build.

**Comment by clydin** [comment] 2021-05-27 14:11
As a temporary workaround, you can use 12.0.0 to extract and then re-upgrade to the latest until the next patch release.

**Comment by alan-agius4** [comment] 2021-05-31 13:07
Closed via https://github.com/angular/angular-cli/pull/20971

**Closed by alan-agius4** 2021-05-31 13:07 UTC
Labels: devkit/build-angular: i18n, freq1: low, severity5: regression, type: bug/fix
