### ISSUE TITLE
Cannot generate Reducers or effects with the Angular CLI (15.1.2)

### ISSUE THREAD

**Issue by eleemans** [angular/angular-cli#24604] opened 2023-01-25 12:06 UTC
### Command

generate

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.1.1

### Description

Cannot generate reducers or effects with the angular .

When using the command ng generate reducer (or ng g reducer) or ng generate @ngrx/schematics:reducer I get the following error: 
_An unhandled exception occurred: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
See "/private/var/folders/8r/0_dt1j351932ppgt33f60yfh0000gn/T/ng-IBPnCP/angular-errors.log" for further details._

### Minimal Reproduction

1. ng new sample
2. ng add @ngrx/store@latest --no-minimal
3. ng config cli.defaultCollection @ngrx/schematics
4. ng g reducer
5. error

I can fix it with the following:
1. go to @angular/cli/src/commands/generate/cli.js
2. **add if (collection.description.schematics[schematicName] !== undefined)** in 
async *getSchematics() {
        const seenNames = new Set();
        for (const collectionName of await this.getCollectionNames()) {
            const workflow = this.getOrCreateWorkflowForBuilder(collectionName);
            const collection = workflow.engine.createCollection(collectionName);
            for (const schematicName of collection.listSchematicNames(true /** includeHidden */)) {
                // If a schematic with this same name is already registered skip.
                if (!seenNames.has(schematicName)) {
                    seenNames.add(schematicName);
                    if (collection.description.schematics[schematicName] !== undefined){
                        const { aliases } = collection.description.schematics[schematicName];
                        const schematicAliases = aliases && new Set(aliases);
                        yield { schematicName, schematicAliases, collectionName };
                    }
                }
            }
        }
    }

### Exception or Error

```text
An unhandled exception occurred: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
See "/private/var/folders/8r/0_dt1j351932ppgt33f60yfh0000gn/T/ng-IBPnCP/angular-errors.log" for further details.
```

### Your Environment

```text
Angular CLI: 15.1.2
Node: 18.12.1
Package Manager: npm 9.2.0
OS: darwin arm64

Angular: 15.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.1.2
@angular/cli                    15.1.2
@schematics/angular             15.1.2
rxjs                            7.8.0
typescript                      4.9.4
```

### Anything else relevant?

I can fix it with the following:
1. go to @angular/cli/src/commands/generate/cli.js
2. **add if (collection.description.schematics[schematicName] !== undefined)** in 
async *getSchematics() {
        const seenNames = new Set();
        for (const collectionName of await this.getCollectionNames()) {
            const workflow = this.getOrCreateWorkflowForBuilder(collectionName);
            const collection = workflow.engine.createCollection(collectionName);
            for (const schematicName of collection.listSchematicNames(true /** includeHidden */)) {
                // If a schematic with this same name is already registered skip.
                if (!seenNames.has(schematicName)) {
                    seenNames.add(schematicName);
                    if (collection.description.schematics[schematicName] !== undefined){
                        const { aliases } = collection.description.schematics[schematicName];
                        const schematicAliases = aliases && new Set(aliases);
                        yield { schematicName, schematicAliases, collectionName };
                    }
                }
            }
        }
    }

**Comment by alan-agius4** [comment] 2023-01-25 12:12
Duplicate of https://github.com/angular/angular-cli/issues/24586 and https://github.com/angular/angular-cli/issues/24600

**Closed by alan-agius4** 2023-01-25 12:12 UTC
