### ISSUE TITLE
[es-build - Angular 17] Real outputPath in angular.json without "browser" Subfolder being forced of dist assets

### ISSUE THREAD

**Issue by iqmeta** [angular/angular-cli#26356] opened 2023-11-14 18:01 UTC
### Command

build

### Description

With Angular 17 forced "browser" in dist path was introduced,
which breaks a lot with middlewares/api and base-ref paths hosting multiple angular ui's within one wwwroot.
Addtional dev setups with paths matching unitl now the final deployment path does now break on setup with complex solutions.

See problems of some devs already descriped here:  https://github.com/angular/angular-cli/issues/26304

I guess a lots of more enterprise dev will hit this change after trying to upgrade the angular 16 and earlier projects.

### Describe the solution you'd like

Let developers / devops set the real output path for the build assets
in the angular.json 

```
 "outputPath": {
     browser: "../backend/wwwroot/admin",
     ssr: "../backend/not-public-server-side-rendering",
     whatever: "\\server\share\whatever"
}
```
Something like this would give dev fully fredom of deploy paths avoiding some addional hacky move scripts and so on.

### Describe alternatives you've considered

Additional and until now unnecessary move/delete scripts of the content in the /browser/ folder and so on.

**Comment by dgp1130** [comment] 2023-11-14 20:12
Duplicate of #26304

**Closed by dgp1130** 2023-11-14 20:12 UTC
