### ISSUE TITLE
Angular-app-rewired

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#9710] opened 2018-02-21 10:27 UTC
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

I understand that the Angular team does not have the ability to provide configurations for easy manipulation of development and full control over extensions:
Pin: https://github.com/angular/angular-cli/issues/9657#issuecomment-367250883

But many need: `Rewire Your App` as it is done in React
https://github.com/timarney/react-app-rewired

**Comment by robwormald** [comment] 2018-02-21 22:26
Note that react-app-rewired is *not* maintained by the React team, and you are more than welcome to build such a thing and support it yourself. We will not support such a thing, for all the same reasons the React team does not support it: we cannot guarantee the ability to evolve the CLI without breaking everyone if we expose the underlying machinery. 

Per the warning from the README: 
> By doing this you're breaking the "guarantees" that CRA provides. That is to say you now "own" the configs. No support will be provided. Proceed with caution.

Again, per https://github.com/angular/angular-cli/issues/9657#issuecomment-367250883, your best option currently is to maintain your own webpack config, and use our `@ngtools/compiler` plugin. In the future, the  `https://github.com/angular/devkit` project may offer the ability to override the `ng` commands, but again, you'd be responsible for maintaining such overrides.

To be clear: If you want access to the Webpack configuration, you will need to eject, or use your own Webpack setup. Repeatedly asking will not change this.

In any case, this repo is the wrong place for this request. Closing as a duplicate of https://github.com/angular/angular-cli/issues/9657

**Closed by robwormald** 2018-02-21 22:26 UTC
