### ISSUE TITLE
In Angular 12, ng serve not showing compilation errors properly in browser overlay and console

### ISSUE THREAD

**Issue by yogesh-kamat** [angular/angular-cli#20896] opened 2021-05-21 21:01 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes

 Yes, the previous version in which this bug was not present was:
<pre><code>Angular CLI: 11.2.13
Node: 14.17.0
OS: darwin x64
Angular: 11.2.14</pre></code>

### Description

When I run ng serve any TS error such as TS2564 are properly shown in terminal but not in browser overlay or console. In the browser, it's only showing Failed to compile. Previously it was showing a complete error message.

## 🔬 Minimal Reproduction

Just create a new app with angular CLI and create property abc with type string in app.component.ts but do not initialize it which will give a compilation error TS2564 due to strict type checking. But the error is not shown properly in the browser overlay or console. It is just showing Failed to compile.

## 🌍 Your Environment
<pre><code>Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin x64
Angular: 12.0.1
</code></pre>

**Anything else relevant?**
When I debugged the error in the chrome browser I found out that the file located at /node_modules/webpack-dev-server/client/index.js has an error function which is accepting an argument named _errors. The error function is expecting errors array in string format => ['...........'] but it's actually getting the array as an array of objects with a key message which contains the actual error => [{message: '......'}]

**Comment by alan-agius4** [comment] 2021-05-21 21:17
Duplicate of https://github.com/angular/angular-cli/issues/20710

TLTD; the stable version of webpack-dev-server is not fully compatible with Webpack 5. We will update once there is a stable version that supports Webpack 5.

**Closed by alan-agius4** 2021-05-21 21:17 UTC
