### ISSUE TITLE
Add TAB path autocomplete for ng generate command

### ISSUE THREAD

**Issue by ScarletFlash** [angular/angular-cli#16130] opened 2019-11-09 10:49 UTC
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 
Please, add path autocomplete possibility for `ng g `command.
Now, I need to check that the path is correct manualy:
```
ng g c /pages/main-page/components/smth
```
or run two commands:
```
cd /src/app/pages/main-page/components/
``` 
```
ng g c smth
```

### Describe the solution you'd like
I'd like to be able to use TAB autocomplete on `ng g ...`

### Describe alternatives you've considered
1. `cd` to navigate to target directory (TAB autocomplete works here)
2. `ng g ...` to generate smth.

**Comment by clydin** [comment] 2020-05-27 19:07
Duplicate of #11043

**Closed by clydin** 2020-05-27 19:07 UTC
Labels: comp: etc/misc, type: feature
