### ISSUE TITLE
Generate output bundle in production with "UTF-8 with BOM" encoding

### ISSUE THREAD

**Issue by iivanovgit** [angular/angular-cli#16253] opened 2019-11-21 15:42 UTC
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: "@angular-devkit/build-angular": "0.800.6".

"@angular-devkit/build-angular": "0.800.6" was generating the special symbol in [o.Éµp,r.ElementRef,r.Renderer2,r.PLATFORM_ID] escaped in unicode.

### Description

In our final bundle main.js generated in Production mode contains the following symbols "Éµp" example: [o.Éµp,r.ElementRef,r.Renderer2,r.PLATFORM_ID]. 
Then when we serve it with apache tomcat v.8.5.47 or apache tomcat v.9.0.27 the browser thows a console error which is "Uncaught SyntaxError: Invalid or unexpected token" on Windows machines

### Way to workaround it
re-save the output bundle file (main.js) in UTF-8 with BOM

## 🔬 Minimal Reproduction
1) "@angular-devkit/build-angular": "~0.803.18" in package.json
2) build in production mode
3) serve the app in  apache tomcat v.8.5.47 or apache tomcat v.9.0.27 on Windows machines

## 🔥 Exception or Error
<pre><code>
Uncaught SyntaxError: Invalid or unexpected token

</code></pre>

## 🌍 Your Environment
angular.json production portion
<pre>
<code>
"configurations": {
                  "production": {
                     "fileReplacements": [
                        {
                           "replace": "src/environments/environment.ts",
                           "with": "src/environments/environment.prod.ts"
                        }
                     ],
                     "optimization": true,
                     "outputHashing": "all",
                     "sourceMap": false,
                     "extractCss": true,
                     "namedChunks": false,
                     "aot": true,
                     "extractLicenses": false,
                     "vendorChunk": false,
                     "buildOptimizer": true
                  }
               }
</code>
</pre>

package.json
<pre><code>
"dependencies": {
      "@angular/animations": "~8.2.6",
      "@angular/common": "~8.2.6",
      "@angular/compiler": "~8.2.6",
      "@angular/core": "~8.2.6",
      "@angular/forms": "~8.2.6",
      "@angular/platform-browser": "~8.2.6",
      "@angular/platform-browser-dynamic": "~8.2.6",
      "@angular/platform-server": "~8.2.6",
      "@angular/router": "~8.2.6",
      "@ngx-translate/core": "~11.0.1",
      "@ngx-translate/http-loader": "~4.0.0",
      "@webcomponents/custom-elements": "^1.2.4",
      "angulartics2": "^6.2.0",
      "core-js": "^3.2.1",
      "css-vars-ponyfill": "^1.17.1",
      "html2canvas": "1.0.0-alpha.12",
      "mutationobserver-shim": "^0.3.2",
      "ng-pick-datetime": "7.0.0",
      "reflect-metadata": "^0.1.8",
      "rxjs": "~6.4.0",
      "zone.js": "^0.9.1"
   },
   "devDependencies": {
      "@angular-devkit/build-angular": "~0.803.18",
      "@angular/cdk": "~8.2.0",
      "@angular/cli": "~8.3.4",
      "@angular/compiler-cli": "~8.2.6",
      "@angular/language-service": "~8.2.6",
      "@types/core-js": "~2.5.2",
      "@types/node": "~12.7.5",
      "@types/html2canvas": "~0.0.35",
      "@types/jasmine": "^3.3.13",
      "@types/uglify-js": "^3.0.4",
      "ajv": "^6.4.0",
      "d3": "^5.4.0",
      "jasmine-core": "^3.3.0",
      "jasmine-spec-reporter": "^4.2.1",
      "karma": "^4.1.0",
      "karma-chrome-launcher": "^2.2.0",
      "karma-coverage": "^1.1.2",
      "karma-coverage-istanbul-reporter": "^2.0.5",
      "karma-firefox-launcher": "^1.1.0",
      "karma-html-reporter": "^0.2.7",
      "karma-ie-launcher": "^1.0.0",
      "karma-jasmine": "^2.0.1",
      "karma-jasmine-html-reporter": "^1.4.0",
      "karma-mocha-reporter": "^2.2.5",
      "karma-remap-coverage": "^0.1.5",
      "karma-sourcemap-loader": "^0.3.7",
      "ts-node": "~8.4.1",
      "tslint": "~5.20.0",
      "typescript": "~3.5.3"
   }

</code></pre>

**Anything else relevant?**
It is not browser related. Reproduced on Chrome, Firefox, Edge
The bug might be duplicate of https://github.com/angular/angular-cli/issues/13908

**Comment by clydin** [comment] 2019-11-21 15:50
Is the server sending the correct `Content-Type` for the file's content?
The on-disk content and the content that the server sends to the client are not guaranteed to be the same.  The server is the only element of the system that has control over the data actually being sent to the client.  As such the server should send a character set identifier within the `Content-Type` header that corresponds to the data that the server is sending.

**Comment by iivanovgit** [comment] 2019-11-22 09:00
@clydin yes the server was sending the correct Content-Type as UTF-8 encoding, we tried to set it on the request and response but no effect so far

**Comment by iivanovgit** [comment] 2020-01-06 15:21
A reliable enough solution that we did, was to merge an empty file with a BOM header to the app bundle.

**Comment by jcgonzave** [comment] 2020-04-24 22:10
I tried using "@angular-devkit/build-angular": "0.803.25", but I had the same issue. I think the special symbols "Éµ" correspond to the symbol "ɵ" (Greek Theta), which seems to be used by the Angular team to indicate that some method is private to the framework.

As @iivanovgit says, it works fine using "@angular-devkit/build-angular": "0.800.6" in which the symbol "ɵ" is escaped to \u0275.

**Comment by dgp1130** [comment] 2020-05-27 23:26
I'm not able to reproduce any errors within Angular builds on the latest CLI. I added the lines:

```typescript
const Éµp = 'test';
console.log(Éµp);
```

And this prints test with `ng serve` and `ng serve --prod`. I also tried `ng build` and `ng build --prod` using `python -m SimpleHTTPServer`, which worked successfully. I think our build process is correct, so if Tomcat isn't serving these files correctly, then that seems like a Tomcat issue.

Closing as I don't see anything actionable on the Angular side. Please re-open if I'm missing something here.

```
$ ng version
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.7
Node: 12.16.1
OS: linux x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cli                      9.1.7
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

**Closed by dgp1130** 2020-05-27 23:26 UTC
Labels: comp: devkit/build-angular, devkit/build-angular: browser, freq1: low, severity2: inconvenient, triage #1, type: bug/fix, workaround2: non-obvious
