### ISSUE TITLE
[ng13]  ng serve auto compiling infinitely without any changes

### ISSUE THREAD

**Issue by Wenrong108** [angular/angular-cli#22163] opened 2021-11-15 08:38 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

Hi, after upgrading ng13 from ng12, I got this issue. It worked well in ng v12.
 
![image](https://user-images.githubusercontent.com/57497730/141749109-fcf86bf8-2a4a-4ef1-8f41-05fe140fec04.png)

### Please provide the environment you discovered this bug in

```true
Angular CLI: 13.0.1
Angular Core: 13.0.0
Node: 14.17.3
```

**Comment by JoostK** [comment] 2021-11-15 08:54
Moving to the CLI as that's responsible for setting up watch mode. That said, without a reproduction this is unlikely to be actionable.

**Comment by alan-agius4** [comment] 2021-11-15 10:01
Hi @Wenrong108,

Please provide the output of `ng version` and as @JoostK mentioned without a reproduction even shared privately it will be hard to get to the bottom of this.

**Comment by Wenrong108** [comment] 2021-11-15 10:30
Hi, @alan-agius4 , here is `ng version` result

![image](https://user-images.githubusercontent.com/57497730/141766226-3398c0fa-8a0f-4ff3-aa63-b881f75a79bb.png)

**Comment by alan-agius4** [comment] 2021-11-15 10:52
- Are you using custom builders by any chance?
- Can you run `npm ls @ngtools/webpack`?
- Can you also try to delete `node_modules`, `package-lock.json` and run `npm install` again?


Another observation which is unrelated to the above issue I am seeing a number of "outdated" packages, `@schematics/angular`, `@angular-devkit/schematics`. `@angular/pwa`? Unless you have custom schematics these packages should not be directly in your `package.json`.  Also, `@angular/http` is no longer supported.

**Comment by Wenrong108** [comment] 2021-11-15 11:36
Hi, @alan-agius4. thanks for your reply.

- I never use custom builders
- npm ls @ngtools/webpack
![image](https://user-images.githubusercontent.com/57497730/141775302-e89573c8-9cfe-4c7f-95ea-7800baff3a19.png)
- Can you also try to delete node_modules, package-lock.json and run npm install again?
I did so many times, but nothing effect.

**Comment by alan-agius4** [comment] 2021-11-15 11:44
@Wenrong108, in that case without a reproduction / remote debugging session it would be hard to get to the bottom of this.

**Comment by Wenrong108** [comment] 2021-11-18 03:44
Hi, @alan-agius4 , by the way, why does the issue happen in only **ng v13**? it works well in **ng v12**.

**Comment by alan-agius4** [comment] 2021-11-18 05:42
@Wenrong108, without a reproduction we cannot investigate and ascertain in what’s is causing the problem.

**Comment by vincentpalita** [comment] 2021-11-24 15:47
I ran into the same issue, but it seems to be related to an old issue that should have been fixed in 12.0.3 when polling is enabled. 
By disabling polling everything works normally again. Please view issue: https://github.com/angular/angular-cli/issues/20891

**Comment by alan-agius4** [comment] 2021-11-24 16:17
@vincentpalita, can you please provide a reproduction?

**Comment by vincentpalita** [comment] 2021-11-24 17:04
@alan-agius4 it seems to be related to the new cache system.

On a small repository with the poll option to 2000ms the problem will not appear. 
But if you set it to 10ms it will instantly happen as soon as you save a file for example. 

To reproduce (make sure you @angular/cli global package is up to date with v13):

```
ng new i22163
// Y to routing, and choose SCSS
cd i22163
ng serve --poll 10 --verbose
```
Then for example save a new line in the style.scss file of the app located in src folder.

It will then do this:
![issue](https://user-images.githubusercontent.com/2738822/143282818-93d8cd5d-de31-4dfc-8c77-8b9a3f348ce3.gif)

I intentionally lowered the polling to 10ms to get the problem, on our repository, which is very big (700+ libs) it happens even with 2000ms, but if we remove the option it works well again.

I am available for a remote call if you want more information!
Thank you for your help!!

**Comment by Xumochuan** [comment] 2021-11-25 07:29
I've got the same issue for even angular new version 13.0.3 :(

**Comment by alan-agius4** [comment] 2021-11-25 07:53
@vincentpalita,
 I am unable to reproduce using the steps provided above. Are you using docker by any chance? Also, can you also please provide the output of `ng version`?

@Xumochuan,
3Gb seems quite a lot, can you please provide the size of each sub directory of `cache`?. 
The `.angular` has been created in the project root for a number of reasons:
- ease of access
- immutable `node_modules`
- Compatibility with PNP package managers where there is no `node_modules` directory. 

This pattern is also used by other tools one of the most popular one is Eslint, where by default it writes a cache file in the root.

You can clean the cache at any time, and also you can change the cache path if desired, See https://angular.io/cli/cache for more information.

Back to the original issue,  @Xumochuan and @Wenrong108 are you also using `polling`?

**Comment by vincentpalita** [comment] 2021-11-25 08:02
@alan-agius4 
No, I am not using docker for the example provided. 
Please find below the output `ng version`

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.0.3
Node: 16.13.0
Package Manager: yarn 1.22.4
OS: darwin x64

Angular: 13.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@schematics/angular             13.0.3
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by alan-agius4** [comment] 2021-11-25 08:39
I also tried using Node.js 16.13 and I am still unable to replicate this issue.

Out of curiosity, does this happen if you touch the file outside of your IDE?

```
touch src/styles.scss
```

**Comment by Xumochuan** [comment] 2021-11-25 08:44
@alan-agius4 , have you tried to upgrade any project from ng v12 to ng v13?

**Comment by alan-agius4** [comment] 2021-11-25 08:53
I am testing using the exact same versions provided in the above `ng version`.

**Comment by alan-agius4** [comment] 2021-11-25 11:58
@vincentpalita, I tried to set the polling value down to 1ms and I was still unable to replicate this behaviour. Can it be that you have another application that is interacting with file once you save them?

**Comment by vincentpalita** [comment] 2021-11-25 13:15
@alan-agius4 I quit the IDE, launched the app from terminal. Tried again, same status: unlimited build once I touched a file. If you would like to open a remote session to see that on my desktop, feel free to DM me!

**Comment by alan-agius4** [comment] 2021-11-25 13:25
A remote session would definitly be helpful. I don't see a way to contact you in your GH profile. Can you please reach out personally on twitter or via email? Thank you.

**Comment by alan-agius4** [comment] 2021-11-30 15:14
Following a debug session with @vincentpalita, we managed to track down what is causing the problem. Will be working on a fix shortly.


Thanks again @vincentpalita for your help.

**Closed** 2021-11-30 17:28 UTC
Labels: type: bug/fix, freq1: low, severity5: regression, comp: devkit/build-angular

**Comment by dev181992** [comment] 2021-12-16 08:42
Hi, @vincentpalita , how did you solve this issue?

**Comment by vincentpalita** [comment] 2021-12-16 09:13
@dev181992 it was fixed by alan-agius4 as shown in this ticket.

**Comment by dev181992** [comment] 2021-12-16 09:17
Hi, @alan-agius4 , could you help me solve issue?

**Comment by vincentpalita** [comment] 2021-12-16 09:31
@dev181992 you just need to update to the latest angular/cli version and it will go away.

**Comment by dev181992** [comment] 2021-12-16 09:48
@vincentpalita , I updated angular/cli (v13.1.1) today, but still issue

**Comment by alan-agius4** [comment] 2021-12-16 10:12
@dev181992, can you please provide the output of `ng v`?

**Comment by dev181992** [comment] 2021-12-16 10:37
@alan-agius4 , sure. please look at this:
![image](https://user-images.githubusercontent.com/47884397/146355973-011fbebd-a419-4fd8-989c-433dbd57d283.png)

**Comment by alan-agius4** [comment] 2021-12-16 10:44
The versions looks okay, so you should be experiencing this issue when polling is used.

I suggest that you file a new issue with a reproduction so that we can investigate this issue further. Although might be related to https://github.com/webpack/webpack/issues/14911
