### ISSUE TITLE
@ngtools/webpack doesn't honor __webpack_public_path__ when using AOT

### ISSUE THREAD

**Issue by lyonzy** [angular/angular-cli#7967] opened 2017-10-07 22:14 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
Node: 7.7.3
`@ngtools/webpack`: 1.7.2

### Repro steps.
I'm trying to use `__webpack_public_path__` to set the path to my static assets at runtime.

**index.ejs:**
`<html data-public-path="<%= environment.publicPath %>/">`

**webpackPublicPath.js:**
`__webpack_public_path__ = document.documentElement.attributes['data-public-path'].value;`

This works without AOT and I get this:

**Uncompiled templates:**
`<img src=\"" + __webpack_require__(334) + "\" \r\n        `

**CSS:**
`url(" + __webpack_require__(766) + ");` 

It works because inside `__webpack_require__(334)` there's this:
```
/* 334 */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__.p + "5ed24d4ae6cc383d46255d5d63ce06c7.png";

/***/ }),
```

And `__webpack_require__.p` gets set to my public path at runtime (it's synonymous with `__webpack_public_path__`).

However when I enable AOT, it seems to evaluate the paths at compile-time, and I get this:
<sup>(my _compile-time_ webpack `output.publicPath` is `<%= environment.publicPath %>/` because that's where bundle.js will live)</sup>

**Compiled templates:**
`(_l()(), i2.ɵeld(0, null, null, 0, 'img', [['src', '<%= environment.publicPath %>/ea8fb8fa5ee24249a9958e931974afc4.svg'], ['style', 'width: 100%;']], `

**CSS:**
`url(<%= environment.publicPath %>/f709ffcea4703610d6373f5fe69b2620.jpg);`

### Desired functionality.
It would be really nice to see this when using AOT:
**Compiled templates:**
`(_l()(), i2.ɵeld(0, null, null, 0, 'img', [['src', __webpack_require__(766)], ['style', 'width: 100%;']], `

**CSS:**
`url(" + __webpack_require__(766) + ");`

**Comment by hansl** [comment] 2017-10-12 00:04
Hi @lyonzy,

Yes, AOT requires all templates, including CSS and HTML, to be available during the compilation. AOT transforms these templates into code.

The workaround (and real solution) is to use Angular code to change the SRC based on your `__webpack_public_path__`. Basically you'd need to create a directive that matches `img[src]` and change the `src` attribute to prepend the code, in JavaScript (which is what Webpack does for you). There are a few projects that do this already, and it works.

CSS has no workaround.

Closing this as working as intended.

**Closed by hansl** 2017-10-12 00:04 UTC

**Comment by CrispyBacon12** [comment] 2018-01-15 01:10
I'm in a similar situation as @lyonzy.

Our assets are served from a different domain than the main page, which can't be known until runtime. Hearing that CSS has no workaround is disappointing.

**Comment by MatissJanis** [comment] 2018-05-03 08:05
Has anyone found a solution to this issue yet?
