### ISSUE TITLE
TypeError: Cannot read property 'jsonData' of undefined

### ISSUE THREAD

**Issue by harleenarora** [angular/angular-cli#21371] opened 2021-07-20 06:41 UTC
During app rebuild this error happens:

let data = module.buildInfo.jsonData;
TypeError: Cannot read property 'jsonData' of undefined

Webpack 5.42.0

**Comment by alan-agius4** [comment] 2021-07-20 06:44
Duplicate of #21349

**Closed by alan-agius4** 2021-07-20 06:44 UTC
