### ISSUE TITLE
Build error with 1.7.1 when using Angular Material

### ISSUE THREAD

**Issue by sinedied** [angular/angular-cli#9726] opened 2018-02-22 09:45 UTC
### Versions
```
<!--
Angular CLI: 1.7.0
Node: 8.9.1
OS: darwin x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.2.2
@angular/cli: 1.7.1
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.2.2
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.6.2
webpack: 3.11.0
-->
```

### Repro steps
* `git clone https://github.com/ngx-rocket/generator-ngx-rocket`
* `npm link .`
* `mkdir repro && cd repro`
* `ngx new`. Select all default options but choose "Angular Material" for the UI question
* `npm run e2e`

### Observed behavior
With `angular-cli@1.7.1` I have this error when I build a project using Angular Material:
```
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/main.scss
(Emitted value instead of an instance of Error) CssSyntaxError: /Users/noda/github/generator-ngx-app/sample/node_modules/material-design-icons/iconfont/material-icons.css:10:12: Can't resolve '../node_modules/material-design-icons/iconfont/MaterialIcons-Regular.ttf)%20format(%27truetype%27' in '/Users/noda/github/generator-ngx-app/sample/src'

   8 |        url(MaterialIcons-Regular.woff2) format('woff2'),
   9 |        url(MaterialIcons-Regular.woff) format('woff'),
> 10 |        url(MaterialIcons-Regular.ttf) format('truetype');
     |            ^
  11 | }
 ```

When reverting back to `angular-cli@1.7.0` everything works perfectly.

### Desired behavior
App builds correctly with `angular-cli@1.7.1`

**Comment by wartab** [comment] 2018-02-22 10:01
Roughly the same mistake is happening with Devextreme icons when trying to load them using angular-cli 1.7.1. Reverting to 1.7.0 also solves this for me.

**Comment by biolauri** [comment] 2018-02-22 13:00
I would say that the new regex `url\(\s*(?:"([^"]+)"|'([^']+)'|(.+))\s*\)` in [*postcss-cli-resources.ts (line 124)*](https://github.com/angular/angular-cli/commit/dea244f#diff-e5fcb0b47828ee6c49b8eb0d4bbcc893R124)  also matches the `format()` strings, so post-css can't resolve the urls.

**Comment by biolauri** [comment] 2018-02-22 13:14
The last group should be evaluated lazy, like so `url\(\s*(?:"([^"]+)"|'([^']+)'|(.+?))\s*\)`. That matches only URLs (and still matches all test examples correctly.  
To get this tested for the future, the following example could be added:
```css
@font-face {
  src: url(./assets/font.woff2) format('woff2'),
    url'(./assets/font.woff') format('woff'),
    url("../assets/font.ttf") format('truetype'),
```

**Comment by cdslijngard** [comment] 2018-02-22 13:49
Reverting back to @angular/cli@1.7.0 does not fix the issue for me.

**Comment by clydin** [comment] 2018-02-22 13:58
Yes; the last part was intended to be lazy.  A fix and additional test coverage is in the process of being added.
Also, note that this issue only affects unquoted urls.  If and where possible, quotes can be added to temporarily workaround issue.

**Comment by desimetallica** [comment] 2018-02-22 14:14
@clydin quotes solved for me.

**Comment by cdslijngard** [comment] 2018-02-22 14:38
@clydin Thanks for your reply! After changing the quotes, it all seems to work fine. Thanks for suggesting.

**Comment by biolauri** [comment] 2018-02-22 14:42
@cdslijngard Do you have a local and global cli installed (on every machine running cli commands)? Maybe the versions differ?

**Comment by sinedied** [comment] 2018-02-22 15:15
@clydin unfortunately I cannot add quotes in `@angular/material` packages, so I have to wait for the fix 😉

**Comment by aleppos** [comment] 2018-02-22 15:26
Same issue with material-design-icons

**Comment by aleppos** [comment] 2018-02-22 15:30
@biolauri you have error in syntax 
url'(./assets/font.woff') format('woff'),
should be like this 
url('./assets/font.woff') format('woff'),

**Comment by clydin** [comment] 2018-02-22 17:07
@sinedied Understood.  We will have a fix in for the next patch release.  Also, just to clarify, this is not actually a problem with the `@angular/material` package.  It shouldn't have any material icon font-face rules.

The material starting guide actually recommends including the material icons via the google font service as it will typically provide better performance: https://material.angular.io/guide/getting-started#step-6-optional-add-material-icons

**Comment by biolauri** [comment] 2018-02-22 18:28
Thanks @aleppos, I fixed it. :)

**Comment by cyrilletuzi** [comment] 2018-02-23 12:02
Same issue.

There is a serious problem in CLI management which needs to be solved.

First, it's the third times we have a CSS regression issue in minor or patch releases, just in the last few weeks. It's not acceptable in such an important project. Tests are clearly insufficient.

Then and most importantly, it's not normal to have to wait so long for regressions fixes, just because the CLI team sticks to a completely inflexible and arbitrary calendar. Regressions should be fixed and new patch releases published immediately, like in any other library. I really don't understand this way of managing Angular (and I'm not alone on this point). All process are automated so it's easy to publish a new release.

**Comment by sinedied** [comment] 2018-02-23 13:01
@clydin Yes the error lies with material icons, but using Google Fonts is not an option since my targets includes Cordova and offline support is needed.

I also agree with @cyrilletuzi : while I cannot deny that the angular CLI does a great job overall, it's not normal to have patch releases that breaks app builds so often. For the 1.6 branch, I had to wait for 1.6.5 until I could build my apps again. In the meanwhile, we can't do anything else than reverting to a previous version.

I also proposed using our CI which builds apps reflecting more "real world" use cases to complement your tests (https://github.com/angular/angular-cli/issues/9317) and setup a canary branch for this, but as it's not part of your release process all I can do is raise issues like this one each time it breaks which is not quite ideal.

**Closed** 2018-02-23 21:38 UTC
Labels: comp: cli/build, freq3: high, severity5: regression

**Comment by clebertmoura** [comment] 2018-03-02 16:39
After execute an: npm upgrade , it worked for me!

**Comment by tanybt51** [comment] 2018-08-05 08:40
I tried to host Material icons offline and I had this issue. The best solution that worked to me was:
commonds:
`ng add @angular/material`

`npm i material-design-icons`

and instead of including the fonts in the style.css, I added this line in the angular.json next:
```

 "styles": [
              {
                "input": "node_modules/@angular/material/prebuilt-themes/indigo-pink.css"
                
              },
              {
                "input": "node_modules/material-design-icons/iconfont/material-icons.css"
                
              }, 
```
apparently the cli have troubles with @import, so this way it's working good.
