### ISSUE TITLE
ng serve fails to serve pages when large cookies are present

### ISSUE THREAD

**Issue by glatzert** [angular/angular-cli#14801] opened 2019-06-17 12:48 UTC
# 🐞 Bug report

### Command (mark with an `x`)
- [x] serve
```

### Is this a regression?
Unknown

### Description
`ng serve` will not respond properly, if the browser sends cookies around 8kB

## 🔬 Minimal Reproduction
Start a simple page in `ng serve`
Create a or multiple cookie (whatever method).
Make the size of the cookies exceed ~8k in total.
See `ng serve` fail for the next requests.

## 🔥 Exception or Error
<pre><code>
Server Responds with 400
</code></pre>


## 🌍 Your Environment
<pre><code>
Angular CLI: 6.1.3
Node: 10.15.3
OS: win32 x64
</code></pre>

**Anything else relevant?**
Browsers tested: Chrome and Firefox
OS tested: Win10 1809

**Comment by alan-agius4** [comment] 2019-06-17 13:42
Hi, In most cases browsers have a hard limit of 4kb when it comes to a single cookie. 

That said, for multiple cookies that some up to 8Kb, the root cause is related tohttps://github.com/webpack/webpack-dev-server/issues/1711

**Comment by glatzert** [comment] 2019-07-11 16:15
Probably the problem can be circumvented by setting NODE_OPTIONS (see https://nodejs.org/api/cli.html#cli_node_options_options)

**Comment by deepakshrma** [comment] 2019-08-19 15:25
I think, Limited cookies to stop hacking and attacks. We should not remove the restriction. `ng serve` is only for the developement process. Not for prod.

https://www.nearform.com/blog/protecting-node-js-from-uncontrolled-resource-consumption-headers-attacks/

**Comment by glatzert** [comment] 2019-08-19 15:38
Our development process is using a proper authentication, which issues cookies.
Those cookies are protected via ASP.Net Core DataProtection and contain access tokens, thus exceeding the 8k very quickly, so a switch to control the max-header-size inside ng-cli would be nice.
Currently the workaround with node_options solve this for us.

I agree not running `ng serve` in production (and I'll call everyone who does unprofessional).

**Comment by mgechev** [comment] 2019-08-19 19:59
@glatzert, thank you for pointing out that `node_options` could be used to workaround the problem.

Since this issue appears to be not very common, I'd suggest to close it and use the workaround you suggested for now. If we notice frequent complains, we can revisit and think of another alternative.

**Closed by mgechev** 2019-08-19 19:59 UTC
Labels: blocked, comp: ngtools/webpack, freq1: low, severity3: broken
