### ISSUE TITLE
AOT - incorrect environment

### ISSUE THREAD

**Issue by deebloo** [angular/angular-cli#2673] opened 2016-10-12 20:07 UTC
### OS?

OSX El Capitan
### Versions.

angular-cli: 1.0.0-beta.17
node: 6.7.0
os: darwin x64
### Repro steps.

-- create a new app with ng new
-- in src/app/app.module.ts 

``` TS
import { environment } from '../environments/environment';
```

-- then in the NgModule add

``` TS
@NgModule({
  imports: [
    ...
  ],
  declarations: [
    ...
  ],
  providers: [{ provide: AppConfig, useValue: environment }],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

-- run `ng build --prod --aot`

If you inject AppConfig into a component or service you will get the incorrect environment.
I am pretty sure aot is breaking the environment switching. when statically analyzing the app module aot pulls in the initial config if passing it to module. The only way I have managed to work around is to copy the file with a script before build.

**Comment by deebloo** [comment] 2016-10-13 11:09
for those needing a workaround you can use a script to copy the file to environment.ts BEFORE running build and aot. This is the one I use on my CI server.

```BASH
echo "HACK!!!"
__dirname="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cp $__dirname/src/environments/environment.$1.ts $__dirname/src/environments/environment.ts
echo "Copied environment.$2.ts"
`

**Comment by SimonKunz** [comment] 2016-11-04 18:19
I can confirm this behavior. It only occurs when building with the --aot flag.

**Comment by a-legrand** [comment] 2016-12-12 14:31
I try this, with success !

```js
export function env() {
    return environment;
}

@NgModule({
  imports: [
    ...
  ],
  declarations: [
    ...
  ],
  providers: [{ provide: AppConfig, useFactory: env }],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by deebloo** [comment] 2016-12-12 14:36
That is a much better workaround then what I was doing! Solid idea

**Comment by cortopy** [comment] 2016-12-12 15:51
Experiencing same behaviour, except that workaround only works if AppConfig is within the environment file. Conditionally adding config within other files will not work

**Comment by dabele91** [comment] 2017-01-02 10:18
Same issue here. The enableProdMode() method in the main.ts doesn't get called, because aot compiling only loads the default environment.ts file.

**Comment by dabele91** [comment] 2017-01-02 10:39
Same issue here. I try to get my firebase config from the environment, but i always receive the default environment file.

**Comment by deebloo** [comment] 2017-01-02 14:26
Like @a-legrand mentioned. A workaround right now is to useFactory instead of useValue

**Comment by Toxicable** [comment] 2017-01-09 09:37
Also experiencing this issue, attempted to use a factory but for some reason the result of the factory wasn't being injected, instead the actual function was. I was most likely doing something wrong but this issue is still the root of it.

**Comment by dmattsson** [comment] 2017-01-16 09:19
Just want to bump this. I added --aot to our prod environment and thus exposed our DEV database to the public. Thankfully there was no big harm this time, but this could potentially have some really serious implications!

**Comment by filipesilva** [comment] 2017-02-06 10:06
@deebloo I'm having some trouble reproducing this. Can you provide me with a repo where this happens, or tell me what's the definition of `AppConfig` in your example?

**Comment by deebloo** [comment] 2017-02-06 20:55
@filipesilva ill create a small repo with the latest cli

**Comment by deebloo** [comment] 2017-02-06 21:04
@filipesilva https://github.com/deebloo/env-error

**Comment by filipesilva** [comment] 2017-02-09 09:34
Fixed by https://github.com/angular/angular-cli/pull/4542

**Closed by filipesilva** 2017-02-09 09:34 UTC
Labels: command: build, feature: aot, priority: 1 (urgent), type: bug

**Comment by xiehongyang** [comment] 2017-06-04 12:56
I just have the same issue here when using the ng2-admin 1.0.0 version 
[(https://github.com/akveo/ng2-admin/blob/master/package.json)](url)
Could anyone help me on this? Thanks
