### ISSUE TITLE
Import dragula in angular-cli 1.6 JIT not working

### ISSUE THREAD

**Issue by natcohen** [angular/angular-cli#9059] opened 2018-01-02 13:19 UTC
I use dragula in my angular-cli project and need to import the dragula object. In my package.json, I added dragula as a dependency and in my component, I import dragula as follow:

    import dragula from 'dragula';

I then log the object to see if it exists `console.log(dragula)`. Surprisingly when I compile the app in AOT mode, the object exists while when I build it in JIT mode, it doesn't exist! This bug was not present in angular-cli v1.5.5 and started to appear in v1.6

**Comment by wartab** [comment] 2018-01-03 10:30
After almost a minute of being on Dragula's Github page, I found this. Maybe you should try the provided solutions for Angular they link to? https://github.com/valor-software/ng2-dragula

**Comment by natcohen** [comment] 2018-01-03 12:43
@wartab Thanks for your useless contribution! I already use ng2-dragula.

FYI, ng2-dragula uses dragula and if you want to add [dom-autoscroller](https://github.com/hollowdoor/dom_autoscroller) for example, you need to import the dragula object. So when you say "ridiculous assumptions" while I've spent way more than a minute trying to figure out what the problem could be, it is offensive. Remain humble especially when you've spent only one minute on this issue!

**Comment by filipesilva** [comment] 2018-01-03 13:46
I think this issue is a duplicate of https://github.com/angular/angular-cli/issues/9058. Please follow that issue for further updates. A note though: this doesn't seem to be related to JIT vs AOT, but rather dev vs prod. I cannot reproduce what you see with `ng serve --aot` but can with `ng serve --prod`.

**Closed by filipesilva** 2018-01-03 13:46 UTC
