### ISSUE TITLE
Lint + ng serve

### ISSUE THREAD

**Issue by Lonli-Lokli** [angular/angular-cli#17345] opened 2020-03-30 18:21 UTC
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Provide an ability to runinting during ng serve via option or hook

### Describe the solution you'd like

It might be option ng serve --lint

Also it's possible with pure Webpack build of angular, which Angular CLI use under the hood.

**Comment by alan-agius4** [comment] 2020-03-30 18:33
Duplicate of https://github.com/angular/angular-cli/issues/2551 

See https://github.com/angular/angular-cli/issues/4114#issue-201906134 for more context.

**Comment by alan-agius4** [comment] 2020-03-30 18:34
Hi @Lonli-Lokli, this is a duplicate of https://github.com/angular/angular-cli/issues/2551 

Kindly see https://github.com/angular/angular-cli/issues/4114#issue-201906134 for more context.

**Closed** 2020-03-30 18:34 UTC

**Comment by Lonli-Lokli** [comment] 2020-03-30 19:47
@alan-agius4 I cannot agree on that. It's my decision as a developer what I want - faster rebuild time with linting or without, depending on _my_ needs, not my tooling (ie Angular CLI).
As I see in your referenced commit, a lot of people from Angular community were disagree with @filipesilva .

So can you please reopen this issue?

**Comment by alan-agius4** [comment] 2020-03-31 11:06
Hi @Lonli-Lokli, 

You as a developer as free extend the default browser / devserver builder and include linting if you wish to do so. However, we don't feel that this should be provided by the default builder in the CLI as mentioned previously in the post link shared above. 

IMHO, "build" should be doing one thing and one thing only and that is building your project and not linting for formatting related mistakes. I think formatting related tasks are better enforced via pretty commit hooks.

**Comment by Lonli-Lokli** [comment] 2020-03-31 11:14
@alan-agius4 
_IMHO, "build" should be doing one thing and one thing only and that is building your project and not linting for formatting related mistakes._  
you have --deployUrl , --statsJson options which already violate your rule.

_I think formatting related tasks are better enforced via pretty commit hooks._
linting whole repository is ok when your repository is relatively small, in our case it is not true. Compare to case when only affected files are linted.

**Comment by alan-agius4** [comment] 2020-03-31 13:03
Hi again,
>you have --deployUrl , --statsJson options which already violate your rule.
There are 2 build related options. 
- deployUrl:  A built time URL where files will be deployed, which will be inlined in the JS and CSS bundles.
- statsJson: build related statistics

> linting whole repository is ok when your repository is relatively small, in our case it is not true. Compare to case when only affected files are linted.

That is actually a one of the reasons why linting shouldn't be part of build pipeline but rather using a pre-commit hook so to lint only the files that changed.

If you have a large repository and you are seeing that linting is slower, integrating lint as part of the build workflow will only make the build time slower since you will be linting and building your application at the same time.

Therefor if your lint takes `60s` and your builds takes another `60s`, if `lint` is integrated into `build/serve` you build will not take `~120s`.  From performance aspect you will not gain anything by integrating lint in serve/build. As a matter of fact it will only make build times slower.
