### ISSUE TITLE
while preloading modules view will be struck

### ISSUE THREAD

**Issue by adityarw** [angular/angular-cli#11985] opened 2018-08-23 13:38 UTC
i have around 10 modules each module contains atleast of 25-30 components, while preloading all the modules the login view will be struck m unable to fill the login credentials until it load all the module..

please fix this issue..

please preload the modules background so that we can do our work on current view..

@filipesilva

Bro,

This is an feature request, this for improving load time of an application.

if u think this not a suitable for supports.

Then Your framework(Angular) is not suitable for an Enterprise Application....

please try to reproduce above issue and share your experince.

**Comment by clydin** [comment] 2018-08-23 13:54
Duplicate of #11344

**Closed by clydin** 2018-08-23 13:54 UTC

**Comment by adityarw** [comment] 2018-08-23 14:41
@clydin

showing not interested in adding new feature.

Its okay.

lets try this and share your experince

some other day you will come to know about this by your own team..
will work on this.

Thanks for your support.
