### ISSUE TITLE
Feature suggestion: Fast recompile when no changes are made

### ISSUE THREAD

**Issue by HarelM** [angular/angular-cli#7812] opened 2017-09-24 14:29 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
Latest

### Desired functionality.
I'm using angular-cli from visual studio - and I added the compilation using angular-cli to my compilation flow (which also compiles my C# code).
Which means every time I change anything thing in the code I would like the compilation to work.
This happens automatically for all the code written in C# - no changes = fast compilation.
I was hoping this could be done as well for angular-cli - meaning: If i didn't change any of my ts code, didn't add any package, or anything like that - the compilation will be supper fast or there will not be any compilation at all.

### Mention any other details that might be useful.
The reason for this request is that every time I load my server this compilation happens (which is good since I want to make sure I'm running on my latest code) but it takes time even if I didn't change a line of code since the last compilation.

I have briefly looked for a feature like this but couldn't find one here, I'll be surprised if this is not a dup...

**Comment by clydin** [comment] 2017-09-24 22:32
For typical development workflows, either `ng serve` or `ng build --watch` are the recommended approaches.  `ng build` is designed and intended to perform a complete build.
More in-depth integration with the IDE would provide for this type of functionality as well as much more.  However, i'm not currently aware of any work in regards to a visual studio plugin of this nature.

**Comment by filipesilva** [comment] 2017-09-25 10:23
I think what @HarelM is requesting is that subsequent `ng build` would be fast if nothing changed, this is thus a duplicate of https://github.com/angular/angular-cli/issues/7467. There is some discussion and reasoning for not adding it there.

**Closed by filipesilva** 2017-09-25 10:23 UTC

**Comment by HarelM** [comment] 2017-09-25 10:48
Thanks! sounds like the same issue.

**Comment by clydin** [comment] 2017-09-25 13:50
For the special case of _no files changed_, there is an alternate option that wouldn't require changes to the CLI.  The IDE could check timestamps of the app files and compare to the built files.  If any are older than the built files, it would run the build command.  If not, do nothing.
Checking all the files within the app's directory is obviously a naive implementation.  But for the IDE to receive the list of only relevant files would require a library/programmatic version `ng build`  and a VS plugin to tie everything together.
