### ISSUE TITLE
Unable to complete ng new.

### ISSUE THREAD

**Issue by allenz0810** [angular/angular-cli#3919] opened 2017-01-09 17:32 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Window 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
![image](https://cloud.githubusercontent.com/assets/5561722/21775968/444bee66-d666-11e6-9f88-78f54549f4bd.png)

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

I'm try to create new project (ng new Map). It does not go any where(more then 3 hours and i try to  re-run for couples times all same result) 

![image](https://cloud.githubusercontent.com/assets/5561722/21776133/0c697f08-d667-11e6-89b7-e0f770ba4f05.png)

### Mention any other details that might be useful.

When install angular-cli, it takes around 1 day to finish installed. (npm install -g angular-cli)

> ---------------------------------------------------------------

**Comment by beeman** [comment] 2017-01-09 18:06
Hi @allenz0810, thanks for creating this issue.

It looks like it's hanging on the step where it installs the dependencies from NPM.

What you can do to debug this is ad the `--skip-npm` parameter to `ng new`, and then manually run the `npm install` afterwards, to see if that shows you what the issue is.

**Comment by allenz0810** [comment] 2017-01-09 22:59
@beeman  thank you for answer my question, `--skip-npm` work for creating project. But then i have another issue when doing (npm install this already takes up 5 hours and still ongoing.).

![image](https://cloud.githubusercontent.com/assets/5561722/21787005/c45e1650-d694-11e6-95d5-94a26042d90a.png)

**Comment by baruchvlz** [comment] 2017-01-09 23:10
@allenz0810 It seems this has happen before with other NPM packages. Maybe this comment might help you https://github.com/npm/npm/issues/11028#issuecomment-168833321

**Comment by beeman** [comment] 2017-01-09 23:20
@allenz0810 it also might be that it's your connection. NPM tends to get very slow when the internet connection is not stable. 

You might want to try doing an `npm install` in another node project to see if this is the case.

**Comment by Brocco** [comment] 2017-01-10 01:55
This issue seems unrelated the to the CLI, closing as the project seems to be creating without issue. Good luck getting your dependencies to install.

**Closed by Brocco** 2017-01-10 01:55 UTC
