### ISSUE TITLE
ng serve connect ETIMEDOUT

### ISSUE THREAD

**Issue by bafinneg** [angular/angular-cli#2755] opened 2016-10-18 01:29 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
macOS Sierra

### Versions.
angular-cli: 1.0.0-beta.17
node: 6.5.0
os: darwin x64

### Repro steps.
ng new test
cd test
ng serve

### The log given by the failure.

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Error: connect ETIMEDOUT fd00:9ca4:7675:4e2e:7153:a688:b525:2149:4200
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

### Mention any other details that might be useful.

Hello!

Today I've been encountering a timeout when trying to run ng serve on a new (or ng init) project. 

ng build works fine
ng serve in my existing projects work fine

Uninstalled & reinstalled angular cli using the instruction, no change.
Not sure what's causing the timeout on this go around. No recent updates to my dev environment.
Thank you!

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by decooliveira** [comment] 2016-10-18 02:42
I'm going through the same problem.

**Comment by nemec784** [comment] 2016-10-18 06:58
Same problem

**Comment by haninaguib** [comment] 2016-10-18 07:40
ps: Still cant find a solution (not even sure what the problem is). 
I am not running behind a proxy or anything strange.

OS X: 10.11.6 (El Capitan)
angular-cli: 1.0.0-beta.14 (also tried beta.17)
node: 6.8.1
os: darwin x64

It is a new project. (ie created via ng new today)
Existing projects are working.

**Comment by b091** [comment] 2016-10-18 07:58
I think it's because some of the angular-cli dependency which was automatically updated because of "^version".

If you will delete `./node_modules` and make `npm install` your existing project will get the same issue ;)

I dont know which one yet

**Comment by bafinneg** [comment] 2016-10-18 08:03
Good find @b091! That's a good lead. 
I wonder if fixing up package.json would could be a workaround? I'll be able to try it tomorrow.

@haninaguib same here no proxy on my end either.

**Comment by nikejaycn** [comment] 2016-10-18 08:08
Same problem in the new ng project.
the old project working well.
```
os: macOS Sierra
angular-cli: 1.0.0-beta.17
node: 6.8.1
os: darwin x64
```

**Comment by b091** [comment] 2016-10-18 08:09
portfinder is an issue it works with `1.0.7` it's not working with `1.0.8`

**Comment by nemec784** [comment] 2016-10-18 08:27
Yep,

`npm install portfinder@1.0.7` 

solves the problem

**Comment by l3bel** [comment] 2016-10-18 08:30
Same here.
Turning WiFi off before issuing "ng serve" works for me

**Comment by l3bel** [comment] 2016-10-18 08:31
@nemec784 , npm install portfinder@1.0.7 works, thanks !

**Comment by programmerinprogress** [comment] 2016-10-18 13:23
Just wanted to note that prior to running 
`npm install portfinder@1.0.7` (which worked for me), my ng serve would just hang, this is definitely an issue in beta 17 

I'm running OSX Yosemite

**Comment by b091** [comment] 2016-10-19 04:13
portfinder `1.0.9` released it's working now. You can close this issue ;)

**Comment by filipesilva** [comment] 2016-10-23 14:20
Dupe of https://github.com/angular/angular-cli/issues/2769, fixed by https://github.com/angular/angular-cli/pull/2831

**Closed by filipesilva** 2016-10-23 14:20 UTC
