### ISSUE TITLE
installation angular-cli on Windows: [execSync v1.0.2]     Native code compile failed!!

### ISSUE THREAD

**Issue by LuizToni** [angular/angular-cli#2373] opened 2016-09-27 18:04 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 4.5.0
os: win32 x64
npm: 3.10.8
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

> execSync@1.0.2 install C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn node-gyp ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.

> node-zopfli@1.4.0 install C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.5.0 (node-v46 ABI) (falling back to source compile with node-gyp)
Compilando os projetos desta solução um de cada vez. Para habilitar a compilação paralela, adicione a opção "/m".
MSBUILD : error MSB4132: A versão das ferramentas "2.0" não é reconhecida. As versões de ferramentas disponíveis são "4
.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Luiz Toni\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Luiz Toni\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=C:\\Users\\Luiz Toni\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64"
gyp ERR! cwd C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Luiz Toni\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli
node-pre-gyp ERR! node -v v4.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\Luiz Toni\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v46-win32-x64'(1)

*5.  Mention any other details that might be useful.

Using Python 2.7.12;
msbuild.exe -version
      Microsoft (R)  build engine version 4.6.1586.0
      [Microsoft .NET Framework, Version 4.0.30319.42000]
Translated:
Compiling projects this solution one at a time. To enable parallel compilation, add the "/ m" option.
 error MSB4132: The version of the tools "2.0" is not recognized. Versions of tools available are "4.0 "
After this installation usually proceeds
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-09-27 18:40
Dupe of https://github.com/angular/angular-cli/issues/1991

**Comment by filipesilva** [comment] 2016-09-27 18:40
Dupe of https://github.com/angular/angular-cli/issues/1991

**Closed by filipesilva** 2016-09-27 18:40 UTC
