### ISSUE TITLE
Build got failed while using 'ng build ---aot'

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular-cli#14717] opened 2019-06-10 13:02 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

NO

### Description

I have set **"target": "es6"**, when i try to serve my application using below command

> ng serve ---aot

It throws below error:

![Screenshot (269)](https://user-images.githubusercontent.com/36756050/59196047-349ec680-8bab-11e9-9297-72ff078cd2cd.png)

If i change target to **"es2015"** and  try to run using below commands

> ng serve --prod

> ng serve --aot

it throws a same error:

![Screenshot (271)](https://user-images.githubusercontent.com/36756050/59196453-55b3e700-8bac-11e9-9d42-bb5eeab1b3eb.png)

### Working fine
When using "ng serve" with target es2015 and es6

And all commands are working fine with target as es5

## 🔬 Minimal Reproduction

1. Download sample
[angularIssue.zip](https://github.com/angular/angular-cli/files/3272115/angularIssue.zip)

2. Run "npm i" 

3. The give anyone command from below list:

      - ng serve --aot
      - ng build --aot
      - ng serve --prod
      - ng build --prod

## 🔥 Exception or Error

![Screenshot (271)](https://user-images.githubusercontent.com/36756050/59196453-55b3e700-8bac-11e9-9d42-bb5eeab1b3eb.png)

## 🌍 Your Environment

>     "@angular-devkit/build-angular": "^0.800.2",
>     "@angular-devkit/build-optimizer": "^0.800.2",
>     "@angular/cli": "~8.0.0",
>     "@angular/compiler-cli": "~8.0.0",

**Comment by kumaresan-subramani** [comment] 2019-06-10 13:28
Hi @alan-agius4 ,

FYI

**Comment by alan-agius4** [comment] 2019-06-10 14:03
At first it thought it was caused by Build Optimizer based on the above screenshots but it seems that it also fails when not using Build Optimizer.

**Comment by kumaresan-subramani** [comment] 2019-06-10 14:08
OKay @alan-agius4 ,

Thanks for your fast reply

**Comment by kumaresan-subramani** [comment] 2019-06-10 14:19
Hi @alan-agius4 ,

How do you say issue occurs also when not using build-optimizer?

While using Below three commands build-optimizer must be used

> ng serve --aot
> ng build ---prod

**Comment by alan-agius4** [comment] 2019-06-10 14:49
`—aot` doesn’t use build optimizer by default only `—prod` does

**Comment by kumaresan-subramani** [comment] 2019-06-11 05:13
Hi @alan-agius4 ,

### the issue occurs only when i providing something in "providers"

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { GridModule, PageService } from '@syncfusion/ej2-angular-grids';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, GridModule],
  providers: [PageService],
  bootstrap: [AppComponent]
})
export class AppModule {}

```

### if i give like below it is working fine
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { GridModule, PageService } from '@syncfusion/ej2-angular-grids';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, GridModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}

```

I have only provided service but i didn't use in my application level

**Comment by kumaresan-subramani** [comment] 2019-06-11 08:49
HI @alan-agius4 ,

Did you get anything regarding this?

**Comment by kumaresan-subramani** [comment] 2019-06-14 07:07
The same issue persists in the latest release also

>     "@angular/animations": "~8.1.0-next.2",
>     "@angular/common": "~8.1.0-next.2",
>     "@angular/compiler": "~8.1.0-next.2",
>     "@angular/core": "~8.1.0-next.2",
>     "@angular/forms": "~8.1.0-next.2",
>     "@angular/platform-browser": "~8.1.0-next.2",
>     "@angular/platform-browser-dynamic": "~8.1.0-next.2",
>     "@angular/router": "~8.1.0-next.2",

**Comment by kumaresan-subramani** [comment] 2019-08-06 07:19
Hi,

Any improvement on this issue?

**Comment by kumaresan-subramani** [comment] 2019-08-19 05:48
HI @alan-agius4 ,

I think, still facing issue but i am not sure why?

## Repo Steps:

Step1: download below sample

[targetIssue.zip](https://github.com/angular/angular-cli/files/3514370/targetIssue.zip)

Step2: Give below commands

> npm i

> ng serve

application will work fine but if you change target to **es2015** or **es6** it throws below error:

![Screenshot (29)](https://user-images.githubusercontent.com/36756050/63241884-fa206c80-c272-11e9-9e34-002bd0637e23.png)


Anything regarding this?

**Comment by kumaresan-subramani** [comment] 2019-08-21 13:11
HI @alan-agius4 

Still I am facing same issue, can you please update  on this.

Thanks.

**Comment by mgechev** [comment] 2019-08-21 18:54
Looks like duplicate of https://github.com/angular/angular-cli/issues/15392. Please provide minimal demo so we can reproduce the problem.

**Closed by mgechev** 2019-08-21 18:54 UTC
Labels: freq1: low, severity3: broken, type: bug/fix
