### ISSUE TITLE
Error in ng update, ng update ignores npm ssl-strict setting

### ISSUE THREAD

**Issue by AlgoTrader** [angular/angular-cli#10689] opened 2018-05-07 09:01 UTC
### Versions
Angular CLI: 6.0.0
Node: 8.9.4
Angular: 5.2.8

### Repro steps
ng update @angular/cli

### Observed behavior
>ng update @angular/cli
unable to verify the first certificate

### Desired behavior
no error 

### Mention any other details that might be useful (optional)
I added `ssl: {strict: false}` to fix it in `node_modules/@schematics/update/update/npm.js`
```
            const client = new RegistryClient({
                proxy: {
                    http: options[0],
                    https: options[1],
                },
              ssl: {strict: false}
            });
```

Real fix should respect the `strict-ssl` npm settings.

**Comment by AlgoTrader** [comment] 2018-05-07 09:07
https://github.com/angular/angular-cli/issues/10669 is related issue

**Comment by clydin** [comment] 2018-05-08 00:28
Duplicate of #10596

**Closed by clydin** 2018-05-08 00:28 UTC
