### ISSUE TITLE
Option to not output inline bundle

### ISSUE THREAD

**Issue by emilio-martinez** [angular/angular-cli#8601] opened 2017-11-22 19:22 UTC
### Versions
```
Angular CLI: 1.5.0
Node: 6.11.1
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.5
typescript: 2.5.3
webpack: 3.8.1
```

### Observed behavior

Build process outputs an `inline.bundle.js`. This is great for people who want it. However, upon inspection, if somebody didn't want to have this content inlined, it would be great to have this included in one of the other bundles.

### Desired behavior

Adding a CLI flag that determines whether inline should be separate or included in one of the other bundles. Personally, I don't think it should be authorable which bundle it should be included into, i.e., I think this should be a boolean flag and the CLI team should determine which bundle is most appropriate.

**Comment by aciccarello** [comment] 2017-11-29 21:30
This is related to #2307 which discusses either inlining the bundle or including it in the main bundle

**Comment by alan-agius4** [comment] 2020-05-26 08:00
Duplicate of #2307

**Closed by alan-agius4** 2020-05-26 08:00 UTC
Labels: comp: devkit/build-angular, type: feature
