### ISSUE TITLE
Post upgrade to Angular 9 - Module parse failed: Unexpected token (2:0)

### ISSUE THREAD

**Issue by ronyf** [angular/angular-cli#18364] opened 2020-07-25 00:17 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.0.5

### Description

 A clear and concise description of the problem...
when I run `npm start` I get a lot of **WARNING** and the html won't load

## 🔬 Minimal Reproduction

My `package.json`:
```
"dependencies": {
    "@angular/animations": "9.1.12",
    "@angular/cdk": "9.2.4",
    "@angular/common": "9.1.12",
    "@angular/compiler": "9.1.12",
    "@angular/core": "9.1.12",
    "@angular/forms": "9.1.12",
    "@angular/material": "9.2.4",
    "@angular/localize": "9.1.12",
    "@angular/platform-browser": "9.1.12",
    "@angular/platform-browser-dynamic": "9.1.12",
    "@angular/router": "9.1.12",
    "@angular/upgrade": "9.1.12",
    "@datorama/akita": "5.2.1",
    "@datorama/akita-ngdevtools": "5.0.3",
    "@ncstate/sat-popover": "5.0.0",
    "@ng-bootstrap/ng-bootstrap": "6.2.0",
    "@swimlane/ngx-charts": "13.0.4",
    "@uirouter/angular-hybrid": "9.0.0",
    "@uirouter/visualizer": "7.0.0",
    "ag-grid": "18.1.2",
    "ag-grid-angular": "23.2.1",
    "ag-grid-community": "23.2.1",
    "ag-grid-enterprise": "23.2.1",
    "angular": "1.5.9",
    "angular-animate": "1.5.8",
    "angular-bootstrap": "0.12.2",
    "angular-breadcrumb": "0.4.1",
    "angular-daterangepicker": "0.2.2",
    "angular-gridster2": "9.3.3",
    "angular-hotkeys": "chieffancypants/angular-hotkeys#1.4.5",
    "angular-local-storage": "0.7.1",
    "angular-mocks": "1.7.8",
    "angular-router-loader": "0.8.5",
    "angular-sanitize": "1.5.9",
    "angular-schema-form": "0.8.6",
    "angular-timeago": "0.4.6",
    "angular-tree-control": "0.2.24",
    "angular-ui-bootstrap": "2.5.6",
    "angular-uuid4": "0.3.1",
    "angular-websocket": "2.0.1",
    "angulartics": "1.5.0",
    "angulartics-mixpanel": "0.1.4",
    "awesome-typescript-loader": "5.2.1",
    "bootstrap": "4.3.1",
    "bootstrap-3-typeahead": "4.0.2",
    "bootstrap-daterangepicker": "3.0.5",
    "bootstrap-tagsinput": "0.7.1",
    "classlist.js": "1.1.20150312",
    "core-js": "3.6.5",
    "deepmerge": "2.0.1",
    "font-awesome": "4.4.0",
    "fs-extra": "9.0.1",
    "loaders.css": "0.1.2",
    "lodash": "4.17.10",
    "mini-css-extract-plugin": "0.9.0",
    "mixpanel": "0.10.2",
    "mixpanel-browser": "2.22.4",
    "moment": "2.22.2",
    "ng-flow": "2.1.4",
    "ng-infinite-scroll": "1.2.1",
    "ngPluralizeFilter": "1.0.1",
    "ngclipboard": "1.1.0",
    "ngx-build-plus": "9.0.6",
    "ngx-restangular": "^5.0.0",
    "ngx-take-until-destroy": "5.4.0",
    "ngx-timeago": "1.0.4",
    "ngx-toastr": "12.1.0",
    "ngx-webstorage-service": "4.1.0",
    "octicons": "3.1.0",
    "optimize-css-assets-webpack-plugin": "5.0.3",
    "path": "0.12.7",
    "restangular": "1.6.1",
    "rxjs": "6.6.0",
    "rxjs-compat": "6.6.0",
    "stylelint-prettier": "1.1.2",
    "tslib": "1.12.0",
    "uglifyjs-webpack-plugin": "2.2.0",
    "ui-select": "0.19.8",
    "uuid": "8.1.0",
    "zone.js": "0.10.3"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "9.2.0",
    "@angular-builders/jest": "9.0.1",
    "@angular-devkit/build-angular": "0.901.12",
    "@angular-devkit/schematics": "9.1.12",
    "@angular-devkit/core": "9.1.12",
    "@angular/cli": "9.1.12",
    "@angular/compiler-cli": "9.1.12",
    "@angular/language-service": "9.1.12",
    "@schematics/angular": "9.1.12",
    "@babel/core": "7.10.5",
    "@ngneat/spectator": "5.12.0",
    "@ngtools/webpack": "9.1.12",
    "@storybook/addon-actions": "5.3.0",
    "@storybook/addon-knobs": "5.3.0",
    "@storybook/addon-links": "5.3.0",
    "@storybook/addon-notes": "5.3.0",
    "@storybook/addon-options": "5.3.0",
    "@storybook/addons": "5.3.0",
    "@storybook/angular": "5.3.0",
    "@storybook/storybook-deployer": "2.8.6",
    "@types/angular": "1.6.51",
    "@types/angular-ui-bootstrap": "0.13.43",
    "@types/jest": "24.0.18",
    "@types/jquery": "3.3.31",
    "@types/node": "12.11.1",
    "adjust-sourcemap-loader": "1.2.0",
    "akita-schematics": "2.0.1",
    "angular-scenario": "1.7.8",
    "angular2-template-loader-guardicore": "0.6.5",
    "autoprefixer": "9.8.5",
    "babel-loader": "8.0.6",
    "clipboard": "2.0.1",
    "codelyzer": "5.1.2",
    "copy-webpack-plugin": "4.5.4",
    "css-loader": "2.1.0",
    "d3": "4.13.0",
    "d3-array": "1.2.4",
    "d3-color": "1.3.0",
    "d3-format": "1.4.1",
    "d3-hierarchy": "1.1.8",
    "d3-scale": "1.0.7",
    "d3-shape": "1.3.5",
    "d3.chart": "0.3.0",
    "del-webpack-plugin": "1.2.0",
    "hammerjs": "2.0.8",
    "html-loader": "0.5.5",
    "html-minifier": "4.0.0",
    "html-replace-webpack-plugin": "2.5.6",
    "html-webpack-inline-source-plugin": "0.0.10",
    "html-webpack-plugin": "3.2.0",
    "jest": "25.5.4",
    "jest-junit": "11.0.1",
    "jest-preset-angular": "8.2.1",
    "jquery": "3.3.1",
    "ng-clipboard": "1.0.2",
    "node-sass": "4.12.0",
    "precss": "4.0.0",
    "prettier": "1.16.4",
    "resolve-url-loader": "3.0.0",
    "sane": "4.0.2",
    "script-loader": "0.7.2",
    "shx": "0.3.2",
    "source-map-loader": "0.2.4",
    "ts-jest": "25.5.1",
    "ts-node": "8.10.2",
    "tslint": "5.20.1",
    "tslint-config-prettier": "1.18.0",
    "tslint-eslint-rules": "5.4.0",
    "tslint-lines-between-class-members": "1.3.6",
    "tslint-plugin-prettier": "2.1.0",
    "typescript": "3.8.3",
    "url-loader": "1.1.2",
    "webpack": "4.44.0",
    "webpack-cli": "3.3.12",
    "webpack-dev-server": "3.11.0",
    "webpack-shell-plugin-next": "0.6.4"
  },

```

## 🔥 Exception or Error
<pre><code>

WARNING in ./some/file.html 2:0
Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
> <some-element
|       xxxxx
|       xxxxx
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.12
Node: 10.22.0
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.2.4
@angular/material                 9.2.4
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.6.0
typescript                        3.8.3
webpack                           4.44.0
</code></pre>

**Anything else relevant?**

I'm running both angular 9 and angular 1.5.8 with ui-router/hybrid solution.
It worked perfectly with angular 7.
I had this error in angular 8 as well and updating packages solved it.

**Comment by alan-agius4** [comment] 2020-07-25 08:40
Duplicate of https://github.com/angular/angular-cli/issues/14855

**Closed by alan-agius4** 2020-07-25 08:40 UTC
