### ISSUE TITLE
Terminal error message reference

### ISSUE THREAD

**Issue by ladyleet** [angular/angular-cli#1538] opened 2016-08-03 14:47 UTC
Hi! Not sure if this is useful or not, but thought I'd bring it up. I'm just reporting the error message being wrong. :) Not the issue - I fixed that. ;) 

1. OS?  Mac OSX

2. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
When I ng serve and it doesn't work I get an error message. However, the link is broken here. 

```No angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.```

3. The log given by the failure. Normally this include a stack trace and some
   more information.
<img width="1048" alt="screenshot 2016-08-03 07 23 16" src="https://cloud.githubusercontent.com/assets/8270563/17369003/4e2df430-594b-11e6-8d47-b032ed47557b.png">

**Comment by dpsthree** [comment] 2016-08-03 15:26
Hey @ladyleet, we just hit this error too? How did you fix it? We are starting from a brand new project.

**Comment by splintercode** [comment] 2016-08-03 15:35
See this issue here https://github.com/angular/angular-cli/issues/1528

**Comment by filipesilva** [comment] 2016-08-10 16:49
Dupe of https://github.com/angular/angular-cli/issues/1528, fixed today in the latest webpack release.

**Closed by filipesilva** 2016-08-10 16:49 UTC
