### ISSUE TITLE
how to show local timestamp in angular-cli compile output?

### ISSUE THREAD

**Issue by dada0z** [angular/angular-cli#15524] opened 2019-09-05 02:41 UTC
when ng serve and file changed, angular-cli will automatically compile and output to console.
Like this,
![image](https://user-images.githubusercontent.com/6371260/64307679-6d431600-cfc9-11e9-9888-3ad0482c1a09.png)
but the date is UTC+0.
How to show local timestamp in angular-cli compile output?

**Comment by alan-agius4** [comment] 2019-09-05 04:31
Duplicate of https://github.com/angular/angular-cli/issues/12562

**Closed by alan-agius4** 2019-09-05 04:31 UTC
