### ISSUE TITLE
Import folders of SVG assets

### ISSUE THREAD

**Issue by splacentino** [angular/angular-cli#2521] opened 2016-10-05 08:28 UTC
Hello.

I am using the [ng-lightning](https://github.com/ng-lightning/ng-lightning) module on my project. To work well, I had to import the vendor css from the package in the main styles.css file with "@import".
```css
@import "../node_modules/myPackage/assets/styles/style.min.css"
```
But to work better, I need assets/icons folders from the package. How to include them ?

```js
node_modules/myPackage/assets/icons // subfolders of svg files
```

`ng-lightning` use a path to svg folder at the import. I can't give a node_modules/* path

```js
import { NglModule } from 'ng-lightning/ng-lightning';

@NgModule({
  imports: [
    NglModule.forRoot({ svgPath: 'path_to_include_svg_folder' })
  ]
  bootstrap: [AppComponent]
})
```

**Comment by Meligy** [comment] 2016-10-05 23:47
Unfortunately this is pretty much a duplicate of https://github.com/angular/angular-cli/issues/1942, which seems to be a while before getting a resolution.

**Comment by filipesilva** [comment] 2016-10-09 19:52
#1942 was solved via https://github.com/angular/angular-cli/pull/2570, but that PR wouldn't allow for the functionality you need. Since `node_modules` isn't copied over to `dist/`, you'll need to have those assets inside your project (in `src/assets/` for instance).

**Closed by filipesilva** 2016-10-09 19:53 UTC
