### ISSUE TITLE
Failed to buildin v1.7.1 and @next

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#9741] opened 2018-02-23 07:47 UTC
### Versions
```
Angular CLI: 1.7.1 **AND** 6.0.0-beta.3
Node: 8.9.3
OS: win32 x64
Angular: 6.0.0-beta.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.2.1
@angular/cli: 1.7.1 **AND** 6.0.0-beta.3
@angular/material: 5.2.1
@angular-devkit/build-optimizer: 0.4.2
@angular-devkit/core: 0.4.2
@angular-devkit/schematics: 0.4.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.3
@schematics/angular: 0.4.2
@schematics/package-update: 0.4.2
typescript: 2.6.2
webpack: 3.11.0

```

### Repro steps
ng s or ng build --prod

### Observed behavior
![cli6beta3](https://user-images.githubusercontent.com/2789203/36544050-c47f45bc-17e5-11e8-8771-10ca4bb172a1.gif)

### Others
Works with @angular/cli@1.7.0

Command executed:  `npm run ok`
```
"ok": "npm run fr && npm run de",
"fr": "node --max-old-space-size=8192 ./node_modules/@angular/cli/bin/ng build --prod --progress=false --vendor-chunk=true --app=prod --output-path dist/fr --locale fr --bh /fr/ --i18n-format xtb --i18n-file src/locale/fr.xtb",
"de": "node --max-old-space-size=8192 ./node_modules/@angular/cli/bin/ng build --prod --progress=false --vendor-chunk=true --app=prod --output-path dist/de --locale de --bh /de/ --i18n-format xtb --i18n-file src/locale/de.xtb",
```

**Comment by filipesilva** [comment] 2018-02-23 09:32
@istiti can you get that build log into a github gist or something similar? It looks like CSS. Maybe it's related with some recent CSS fixes that went in.

/cc @clydin

**Comment by istiti** [comment] 2018-02-23 10:30
@filipesilva  yes it is css , I think this cant help you its simply slds lib, but here is a little part of output [gist ](https://gist.github.com/istiti/85d26ada996c4c7476ad8130532abf9a) 

actually i have in angular-cli.json:`"styles": ["styles.css"]`

and in styles.css : `@import "assets/styles/salesforce-lightning-design-system.min.css";`

**Comment by filipesilva** [comment] 2018-02-23 11:17
This seems to be the real error:
> ../node_modules/raw-loader!../node_modules/postcss-loader/lib??embedded!./styles.css
(Emitted value instead of an instance of Error) CssSyntaxError: C:\Users\...\src\assets\styles\salesforce-lightning-design-system.min.css:9:1060: Can't resolve 'assets/fonts/webfonts/SalesforceSans-BoldItalic.woff2)%20format(%22woff2%22),url(assets/fonts/webfonts/SalesforceSans-BoldItalic.woff)%20format(%22woff%22' in 'C:\Users\...\src'

I'm not sure if those `%20` and `%22` should be there.

**Comment by filipesilva** [comment] 2018-02-23 14:17
https://github.com/angular/angular-cli/pull/9738 should fix this.

**Comment by clydin** [comment] 2018-02-23 14:21
Also a duplicate of #9726

**Closed by clydin** 2018-02-23 14:21 UTC
Labels: comp: cli/build, freq2: medium, severity5: regression, type: bug
