### ISSUE TITLE
`export * as ns from './file'` inconsistencies

### ISSUE THREAD

**Issue by Booster2ooo** [angular/angular-cli#20095] opened 2021-02-19 11:22 UTC
# 🐞 bug report

### Affected Package

 
The issue is caused by package @ngtools/webpack ?

### Is this a regression?

 
I don't think it's a regression

### Description

The use of `export * as ns from './file'` sometimes works, sometimes creates an error. In all cases, TS is configured with `"module": "es2020", "target": "es2015"` (I think).

## 🔬 Minimal Reproduction

 
https://github.com/Booster2ooo/angular-export-as

## 🔥 Exception or Error

<pre><code>Error: ./projects/module-with-export-as/src/lib/data/index.ts 1:9
Module parse failed: Unexpected token (1:9)
File was processed with these loaders:
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
> export * as Anwsers from './answer';
| 
 @ ./projects/module-with-export-as/src/lib/test.spec.ts 1:0-33 4:18-25
 @ ./projects/module-with-export-as/src sync \.spec\.ts$
 @ ./projects/module-with-export-as/src/test.ts
</code></pre>

## 🌍  Your Environment

**Angular Version:**

<pre><code>Angular CLI: 11.1.4
Node: 10.23.1
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1101.4
@angular-devkit/core         11.1.4
@angular-devkit/schematics   11.1.4
@schematics/angular          11.1.4
@schematics/update           0.1101.4
</code></pre>

**Anything else relevant?**

I don't think so

**Comment by petebacondarwin** [comment] 2021-02-19 11:44
Transferring to CLI project as I think this is related to bundling...

**Comment by alan-agius4** [comment] 2021-02-19 12:01
Duplicate of https://github.com/angular/angular-cli/issues/19500 and https://github.com/angular/angular-cli/issues/17231#issuecomment-709372331

**Closed by alan-agius4** 2021-02-19 12:01 UTC

**Comment by Booster2ooo** [comment] 2021-02-19 12:13
I'm not sure it's useful but I'd like to underline that it _**is working**_ in some cases, which I find unsettling.

**Comment by alan-agius4** [comment] 2021-02-19 13:23
it's working in some cases, because a library is bundled using Rollup, which does support this syntax. However, when testing the library and/or using `export * as` directly in the application sourcefiles Webpack will be used to bundle this. Prior to Webpack 5, this syntax was not supported.
