### ISSUE TITLE
Application builder doesn't copy assets in watch mode

### ISSUE THREAD

**Issue by kyesil** [angular/angular-cli#29136] opened 2024-12-14 17:57 UTC
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

browser builder

### Description

When running ng build --watch with either the application builder, there is initial build where everything is copied to the destination folder but if a change is made to an text based files in assets after the initial bundle, then nothing happens. I'd expect the assets defined in the builders' "assets" option to also be updated during watch mode.

When I try the same in the webpack based "browser" builder, then detect changes and everything is copied.

### Minimal Reproduction

In angular.json, put the following inside "architect":
`
   "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath":  "dist",
            "index": "src/index.html",
            "browser": "src/main.ts",
            "polyfills": [
              "zone.js"
            ],
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/assets
            ],
			...
          },
			....
              "outputHashing": "all"
            },
            "development": {
              "optimization": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
`
Put some text file inside of src/assets.
Run `ng build --watch`  or ` ng build --watch --poll 1200`.
Make a change to the text file inside the assets folder
Notice that the file hasn't been updated inside the dist folder

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 19.0.5
Node: 22.12.0
Package Manager: npm 10.9.2
OS: win32 x64

Angular: 19.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.5
@angular-devkit/build-angular   19.0.5
@angular-devkit/core            19.0.5
@angular-devkit/schematics      19.0.5
@angular/cdk                    19.0.3
@angular/cli                    19.0.5
@angular/material               19.0.3
@schematics/angular             19.0.5
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by alan-agius4** [comment] 2024-12-14 18:02
Duplicate of https://github.com/angular/angular-cli/issues/28415

**Closed by alan-agius4** 2024-12-14 18:02 UTC
