### ISSUE TITLE
enable declarationMap in workspace libraries

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#17888] opened 2020-06-09 08:50 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

see https://www.typescriptlang.org/v2/tsconfig#declarationMap

> You should strongly consider turning this on if you’re using project references.

`ng generate library my-lib` will add path mapping in tsconfig.json. So we should enable  declarationMap

**Comment by alan-agius4** [comment] 2020-06-09 09:04
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1464

**Comment by alan-agius4** [comment] 2020-06-09 09:20
Actually let's re-open this, since it's slightly different but block it on  ng-packagr/ng-packagr#1464

**Comment by alan-agius4** [comment] 2020-06-09 09:30
Also, this needs some digging to see if it's even useful since we don't use project referenced.

**Comment by xiaoxiangmoe** [comment] 2020-06-09 09:56
I included these files in my npm package:

* ts source code
* compiled js code
* .d.ts file
* map files of js and .d.ts

When I use this npm library, I can jump directly to the ts source code by *VSCode Go to Definition*, which is very convenient.

**Comment by xiaoxiangmoe** [comment] 2020-06-09 10:02
Also, should we use Project References in angular?

**Comment by alan-agius4** [comment] 2020-06-09 10:49
> should we use Project References in angular?
No, the Angular CLI / Compiler don't support composite projects.

I do see, that they can be useful in a monorepo, however, when shipping a library I don't think that dts maps will add any value unless you also ship the typescript source files.

**Comment by alan-agius4** [comment] 2020-06-12 09:37
We had a chat around this yesterday and we decided that we should enable `declarationMap` for non production builds.

**Closed** 2020-06-12 17:39 UTC
Labels: comp: schematics/angular, type: feature
