### ISSUE TITLE
ng update ignores proxy config

### ISSUE THREAD

**Issue by daniel-seitz** [angular/angular-cli#13166] opened 2018-12-11 08:37 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

issue was partially discussed here (https://github.com/angular/angular-cli/issues/10624) after .npmrc issues and later (original issue solved) determined that there is a different issue.

1. **we use yarn with a private repo behind a corporate proxy.**
2. local .npmrc:
   `registry=[some url, masked out]
   always-auth=true`
3. yarn lock contains packages where I see some as resolved with [some url, masked out]
   also there are packages with `https://registry.yarnpkg.com/some-package-and-so-on`
4. global .yarnrc (in C:\Users\MyUserName):
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
lastUpdateCheck 1543945019859
```
5. global .npmrc (in C:\Users\MyUserName):
```
//some_path_with_some_token
proxy= http://our_proxy_with_port/
https-proxy= http://our_proxy_with_port
```
6. trying to follow commands from update.angular.io
7. `yarn install` works, everything else from 6. works but not `ng update @angular/cli`, message comes up after a while (1 minute or so):
`request to https://registry.npmjs.org/@types%2fjasmine failed, reason: connect ETIMEDOUT`
seems to be on a random package, at another try I got:
`request to https://registry.npmjs.org/codelyzer failed, reason: connect ETIMEDOUT [some ip address and port]`

**Assumption:**

**It seems that ng update @angular/cli ignores the proxy since it should go to the configured proxy or https-proxy instead of npmjs.org.**

Should the command be ng update @angular/cli@next? (Results in same error message)
P.S.  I tried migrate only - which works - and then update the packages via yarn, also works. 
I just think that I might miss something that ng update does as well, other than migrating to the angular.json file and lifting the packages to the recent version.

8. currently still running angular 5.1.1
9. tried as described with @next option in `yarn global add @angular/cli@next` and `yarn add @angular/cli@next
`
10. ng --version:
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.2.0-beta.1
Node: 8.12.0
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.12.0-beta.1
@angular-devkit/core         7.2.0-beta.1
@angular-devkit/schematics   7.2.0-beta.1
@angular/cli                 7.2.0-beta.1
@angular/language-service    4.4.6
@schematics/angular          7.2.0-beta.1
@schematics/update           0.12.0-beta.1
rxjs                         5.5.3
typescript                   2.4.2
```

**Comment by catull** [comment] 2018-12-11 14:05
@alan-agius4 
The same .npmrc is used to initially retrieve all dependencies listed in package.json w/ `npm install`.

Thus, the configuration is not the problem, such as firewall rule that causes a time-out.

**Comment by clydin** [comment] 2018-12-11 15:59
@daniel-seitz If you are running the latest beta can you try running update with the `--verbose` option and report the output?

I'll also push a PR (and hopefully get it into beta.2) that will expand the verbose output to also include the final set of options to further aid in troubleshooting.

**Comment by daniel-seitz** [comment] 2018-12-13 15:14
@clydin thank for for pushing, I tested verbose with beat.2
For each dependency in package.json this is written:
```

Locating potential npmrc files:
Trying 'C:\Program Files\nodejs\etc\npmrc'...not found.
Trying 'C:\Users\my_user_name\.npmrc'...found.
Trying 'C:\Users\.npmrc'...not found.
Trying 'C:\Users\my_user_name\.npmrc'...found.
Trying 'C:\Users\my_user_name\source\.npmrc'...not found.
Trying 'C:\Users\my_user_name\source\repos\.npmrc'...not found.
Trying 'C:\Users\my_user_name\source\repos\NameOfRepoLocation\.npmrc'...not found.
Trying 'C:\Users\my_user_name\source\repos\NameOfRepoLocation\OurRepo\.npmrc'...found.

Locating potential yarnrc files:
Trying 'C:\Program Files\nodejs\etc\yarnrc'...not found.
Trying 'C:\Users\my_user_name\.yarnrc'...found.
Trying 'C:\Users\.yarnrc'...not found.
Trying 'C:\Users\my_user_name\.yarnrc'...found.
Trying 'C:\Users\my_user_name\source\.yarnrc'...not found.
Trying 'C:\Users\my_user_name\source\repos\.yarnrc'...not found.
Trying 'C:\Users\my_user_name\source\repos\NameOfRepoLocation\.yarnrc'...not found.
Trying 'C:\Users\my_user_name\source\repos\NameOfRepoLocation\OurRepo\.yarnrc'...not found.
```
So in total more than 50 times this whole block here. Could be enhanced but this is another story.
Then it takes a while until:
```
request to https://registry.npmjs.org/jasmine-core failed, reason: connect ETIMEDOUT 
```
Interestingly in my **yarn.lock** there are 2 entries for jasmine-core:
```
jasmine-core@2.5.2
   version: 2.5.2
   resolved: "our-proxy/jasmine-core/..."
```
```
jasmine-core@~2.8.0
   version: 2.8.0
   resolved: "https://registry.yarnpkg.com/jasmine-core/..."
```
Not sure if that is normal.

**Comment by ahasall** [comment] 2018-12-19 14:11
Try `ng update --registry=<your_internal_registry>`.

**Comment by dmnk** [comment] 2019-01-03 07:33
dupe of https://github.com/angular/angular-cli/issues/10952 ?

**Comment by woppa684** [comment] 2019-01-08 07:43
> Try `ng update --registry=<your_internal_registry>`.

That won't work in our environment however ... 

```
Unable to authenticate, need: Bearer, Basic realm="<our base URI>", Negotiate, NTLM
````

**Comment by Soeren86n** [comment] 2019-01-08 08:15
> Try `ng update --registry=<your_internal_registry>`.

same like before. `request to http://registry.npmjs.org/@angular%2flanguage-service failed, reason: connect ETIMEDOUT 104.16.19.35:80
`

**Comment by santoshyadav198613** [comment] 2019-01-10 10:09
Same error here, it somhow it is trying to connect to

**Comment by Nexxado** [comment] 2019-01-13 12:01
> Try ng update --registry=<your_internal_registry>

Worked for me, also behind corporate proxy with our own registry

**Comment by mgechev** [comment] 2019-01-13 18:56
Thanks for sharing the solution which works for you!

**Comment by mgechev** [comment] 2019-01-13 18:57
@Nexxado, thanks for sharing :)

**Comment by dmnk** [comment] 2019-01-14 06:41
@mgechev, i think you've been a bit quick on the draw. Most of us don't have the chance to use internal registries, and OF COURSE it works, if you're accessing an internal service, no matter if the proxy configuration is respected by ng updated. (which seems to be NOT the case).

**Comment by mgechev** [comment] 2019-01-14 07:38
@dmnk yep, you're right. Just reopened.

**Comment by woppa684** [comment] 2019-01-14 07:53
Also relates to my comment here https://github.com/angular/angular-cli/issues/9646#issuecomment-452205165

**Comment by CSchulz** [comment] 2019-01-17 09:52
It seems that the npmrc is completly ignored, we have configured our registry there project wide.

Does not work:
```
npx ng update @angular/cli
404 Not Found - GET https://registry.npmjs.org/stylelib - Not found
```

Works:
```
npx ng update @angular/cli --registry=https://nexus/repository/npmjs/
```

**Comment by CSchulz** [comment] 2019-01-17 09:54
Can you retry it with 7.2.2? It fixed our issue with the project npmrc file.

**Comment by clydin** [comment] 2019-03-01 19:23
This should now be corrected with the latest version of the CLI.  If anyone is still encountering problems, please open a new issue detailing the problem.

**Closed by clydin** 2019-03-01 19:23 UTC
Labels: comp: schematics/update

**Comment by nathan-K-** [comment] 2019-03-12 09:27
Hi,

While migrating from angular 6.0 to angular 7, I'm facing the same problem with angular cli v7.3.5 (both local and global).
'proxy' and 'https-proxy' are set for both yarn and npm (using yarn though), but ``` ng update --package-manager "yarn" --verbose @angular/cli @angular/core``` is failing :

```
    Locating potential npmrc files:
    Trying 'C:\Program Files\nodejs\etc\npmrc'...not found.
    Trying 'C:\Users\myUser\.npmrc'...found.
    Locating potential yarnrc files:
    Trying 'C:\Program Files\nodejs\etc\yarnrc'...not found.
    Trying 'C:\Users\myUser\.yarnrc'...found.
    ...
    request to https://registry.npmjs.org/@angular%2fcli failed, reason: connect ETIMEDOUT 104.16.22.35:443
    request to https://registry.npmjs.org/@angular-devkit%2fbuild-angular failed, reason: connect ETIMEDOUT 104.16.22.35:443
```

**Comment by daniel-seitz** [comment] 2019-05-04 13:44
Sorry for the time off and missing feedback from my side. I'm assigned to another project and can't really test it anymore.
@clydin I saw the new documentation and corresponding changes, thank you for this! And @everybody-here thank you for your effort.

**Comment by daniel-seitz** [comment] 2019-05-27 13:19
Back in the original project - just tried with @angular/cli@7.3.9
It works. Thank you again, done.
