### ISSUE TITLE
Found a fix for missing module "process-nextick-args" error

### ISSUE THREAD

**Issue by johnazre** [angular/angular-cli#2189] opened 2016-09-17 05:40 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Mac OSX (El Capitan)

2. Versions: NodeJS 4.x.x, NPM 3.x.x (I found the fix before posting here, but that's what it was.)

3. Repro steps: Was not able to fully install an app because of missing module "process-nextick-args" error.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Cannot find module 'process-nextick-args'
Error: Cannot find module 'process-nextick-args'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/usr/local/lib/node_modules/angular-cli/node_modules/readable-stream/lib/_stream_readable.js:6:23)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/usr/local/lib/node_modules/angular-cli/node_modules/readable-stream/readable.js:6:28)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/usr/local/lib/node_modules/angular-cli/node_modules/memory-fs/lib/MemoryFileSystem.js:8:14)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-dev-middleware/middleware.js:5:24)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-dev-server/lib/Server.js:3:28)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/usr/local/lib/node_modules/angular-cli/tasks/serve-webpack.js:8:24)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/usr/local/lib/node_modules/angular-cli/commands/serve.js:7:23)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Class.module.exports.includedCommands (/usr/local/lib/node_modules/angular-cli/addon/index.js:21:16)
at /usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/project.js:392:61
at Array.forEach (native)
at Project.addonCommands (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/project.js:391:15)
at Project.eachAddonCommand (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/project.js:426:30)
at module.exports (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/cli/lookup-command.js:33:13)
at CLI. (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/cli/cli.js:34:26)
at tryCatch (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
at invokeCallback (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
at publish (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
at flush (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:82:5)
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickCallback (node.js:349:13)

5. Mention any other details that might be useful.

I was able to fix this by installing the newest version of NodeJS (v6.6.0) from the package on nodejs.org, then uninstalling and reinstalling the angular-cli.

I hope that helps someone!!!

**Comment by sgruhier** [comment] 2016-09-17 10:19
Thanks
or if you cannot upgrade node, a simple 
```
npm install -g process-nextick-args
```
works too

**Comment by johnazre** [comment] 2016-09-17 16:01
After pushing it it to a repo and pulling it on my Windows 10 computer. I encountered the same "process-nextick-args" issue when trying to run "ng serve". After installing it globally, it still didn't work, but after installing it to devDependencies it worked. Just to make sure it wasn't one or the other, I removed the global installation and it broke again. After replacing the global version and removing the local version in devDependencies, it broke again. Looks like you have to have "process-nextick-args" installed both globally and locally to your devDependencies for it to work, or at least such is the case with Windows 10.

**Comment by filipesilva** [comment] 2016-09-22 02:07
Dupe of https://github.com/angular/angular-cli/issues/1930

**Closed by filipesilva** 2016-09-22 02:07 UTC

**Comment by MatteoNY** [comment] 2016-09-26 21:20
Thanks! fix for next tick worked on my work PC Win.7

**Comment by abe6558** [comment] 2017-11-13 00:23
Thanks! Finally that fixed it.

**Comment by sushilcmd** [comment] 2018-02-05 09:09
I think this issue occur because of node version .So update your node and npm version.
I had same issue then i updated my node and npm version and install angular CLI :) 

#### Check node version
 nodejs --version

#### Update node version
sudo apt-get install nodejs

#### Update npm version
sudo apt-get install npm

#### Install angular CLI
npm install -g @angular/cli
