### ISSUE TITLE
How to set 'publicPath' after 'deployUrl' option is deprecated

### ISSUE THREAD

**Issue by nulilakshman** [angular/angular-cli#24383] opened 2022-12-06 10:26 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We are loading the angular application JavaScript embedded widget, and our application internally using lazy loading concept. Earlier we used --deployurl to set the domain of the application where the actual scripts were deployed. As the deployUrl is deprecated which property we need to use to set it. We tried with --base-href but its not working as expected.

If we don't set the URL, it will try to load the script from the URL that belong to the main application, but it should be loaded from the widget domain. 

Currently this can be achieved by using deploy-url during widgets app build. How to do it without this option?

### Minimal Reproduction

"build:prod": "ng build --configuration production --deployUrl http://scorewidget.cdk.com/",

### Your Environment

```text
13.1.0
```

**Comment by alan-agius4** [comment] 2022-12-06 10:53
Duplicate of https://github.com/angular/angular-cli/issues/22113

**Closed by alan-agius4** 2022-12-06 10:53 UTC
