### ISSUE TITLE
ng update v7.2.15 to v.8.2.5 have some dependencies not found

### ISSUE THREAD

**Issue by HelloValue** [angular/angular-cli#15542] opened 2019-09-06 10:27 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc
```

### Description
i use `ng update @angular/cli @angular/core`  upgrade my angular version.
but have some errors. 
“Package "codelyzer" has an incompatible peer dependency to "@angular/platform-browser" (requires ">=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0" (extended), would install "8.2.5")”

## 🔬 Minimal Reproduction

Angular CLI: 7.3.4
Node: 10.16.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.3.4
@angular/cdk                      7.3.3
@angular/cli                      7.3.4
@ngtools/webpack                  6.0.8
@schematics/angular               7.3.4
@schematics/update                0.13.4
rxjs                              6.5.3
typescript                        3.2.4
webpack                           4.8.3

## 🔥 Exception or Error
Package "codelyzer" has an incompatible peer dependency to "@angular/platform-browser" (requires ">=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0" (extended), would install "8.2.5").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires ">=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0" (extended), would install "8.2.5").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/core" (requires ">=2.3.1 <7.0.0
|| >6.0.0-beta <7.0.0" (extended), would install "8.2.5").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires ">=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0" (extended), would install "8.2.5").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/common" (requires ">=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0" (extended), would install "8.2.5").

## 🌍 Your Environment
Angular CLI: 7.3.4
Node: 10.16.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.3.4
@angular/cdk                      7.3.3
@angular/cli                      7.3.4
@ngtools/webpack                  6.0.8
@schematics/angular               7.3.4
@schematics/update                0.13.4
rxjs                              6.5.3
typescript                        3.2.4
webpack                           4.8.3
-----------------------------------------------------------
run `ng update` 
Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       7.3.4 -> 8.3.3           ng update @angular/cli
      @angular/core                      7.2.15 -> 8.2.5          ng update @angular/core
      ng-zorro-antd                      7.0.2 -> 8.2.1           ng update ng-zorro-ant

----------------------------------------------------------------------------------
my typescript version is  3.4.2.
node  version  is  10.16.3.

**Comment by alan-agius4** [comment] 2019-09-08 14:57
Duplicate of https://github.com/angular/angular-cli/issues/14980

**Closed by alan-agius4** 2019-09-08 14:57 UTC
