### ISSUE TITLE
ng update @angular/cli --next failed

### ISSUE THREAD

**Issue by doggy8088** [angular/angular-cli#16056] opened 2019-11-04 07:18 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No.

### Description

I'm upgrading from `8.3.17`. It failed without any detail. Just said `Invalid JSON character: "{" at 74:32.`. I'm sure my JSON file (`angular.json`) is valid.

## 🔥 Exception or Error

```sh
ng update @angular/cli  --next --migrate-only --from 8 --verbose
```

<pre><code>
Locating potential npmrc files:
Trying 'C:\Program Files\nodejs\etc\npmrc'...not found.
Trying 'C:\Users\user\.npmrc'...found.
Trying 'C:\Projects\.npmrc'...not found.
Trying 'C:\Projects\.npmrc'...not found.
Trying 'C:\Projects\src\.npmrc'...not found.
Using package manager: 'npm'
Collecting installed dependencies...
Found 40 dependencies.
"next" option has no effect when using "migrate-only" option.
** Executing migrations of package '@angular/cli' **

>  Update an Angular CLI project to version 9.
Invalid JSON character: "{" at 74:32.
×  Migration failed. See above for further details.

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.0
Node: 10.16.3
OS: win32 x64
Angular: 9.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.0
@angular-devkit/build-angular      0.900.0-rc.0
@angular-devkit/build-optimizer    0.900.0-rc.0
@angular-devkit/build-webpack      0.900.0-rc.0
@angular-devkit/core               9.0.0-rc.0
@angular-devkit/schematics         9.0.0-rc.0
@angular/cdk                       8.2.3
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   9.0.0-rc.0
@schematics/angular                9.0.0-rc.0
@schematics/update                 0.900.0-rc.0
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

I just found the main fail point of this migration.

Here is my `angular.json` snippet:

```json
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/luxshare-ict-oms",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/web.config"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "dev": {
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.dev.ts"
              }],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },
            "production": {
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.prod.ts"
              }],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [{
                "type": "initial",
                "maximumWarning": "2mb",
                "maximumError": "5mb"
              }]
            }
          }
        },
```

The main problem is on the `"budgets"` section. If I just simply re-format this into this:

```json

        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/luxshare-ict-oms",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/web.config"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "dev": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }
          }
        },
```

Then it just works.

**Comment by alan-agius4** [comment] 2019-11-04 07:51
@doggy8088 can you share the angular.jaon prior of running the update?

**Comment by alan-agius4** [comment] 2019-11-04 09:47
Duplicate of #15462

**Closed by alan-agius4** 2019-11-04 09:47 UTC
Labels: comp: schematics/angular, freq1: low, severity3: broken, type: bug/fix
