### ISSUE TITLE
Angular cli keeps recompiling even nothing changed

### ISSUE THREAD

**Issue by vovikdrg** [angular/angular-cli#13125] opened 2018-12-04 00:45 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x ] serve
- [x ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 7.0.4
Node: 8.9.4
OS: win32 x64
Angular: 7.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

### Repro steps
Our team do have strange issue. Angular CLI keeps recompiling constantly. 
We are running project with ` ng serve --host=localhost.domain.com --port=8081 --configuration=dev --verbose`

And after sometime it will recompile even we dont change anything

> 
> Built at: 2018-12-04 11:32:16
>                         Asset        Size                  Chunks                    Chunk Names
>           cash-cash-module.js     121 KiB        cash-cash-module                    cash-cash-module
>                icon-clock.svg    1.24 KiB
>                back-hover.svg  1000 bytes
>            check-inactive.svg   886 bytes
>              check-active.svg   923 bytes
>                icon-check.svg   834 bytes
>                   spinner.gif    87.9 KiB
>                 preloader.svg    5.09 KiB
>                   success.svg    1.02 KiB
>                     error.svg    1.15 KiB
>                  database.svg    1.24 KiB
>                  thumb-up.svg    1.81 KiB
>                money-hand.svg    1.89 KiB
>                      next.svg    1.07 KiB
>                       pie.svg    1.34 KiB
>                 fluctuate.svg     1.3 KiB
>                      mail.svg    1.16 KiB
>                     order.svg    1.42 KiB
>                      back.svg  1010 bytes
>                     common.js     5.6 KiB                  common                    common
>                       main.js     563 KiB                    main             [big]  main
>                  polyfills.js     460 KiB               polyfills             [big]  polyfills
>     product-product-module.js    1.47 MiB  product-product-module             [big]  product-product-module
>                    runtime.js     8.9 KiB                 runtime                    runtime
>                    styles.css    89.8 KiB                  styles                    styles
>                          0.js    1.45 MiB                       0             [big]
>                     vendor.js       8 MiB                  vendor             [big]  vendor
>       cash-cash-module.js.map    73.2 KiB        cash-cash-module                    cash-cash-module
>                 common.js.map       2 KiB                  common                    common
>                   main.js.map     413 KiB                    main                    main
>              polyfills.js.map     407 KiB               polyfills                    polyfills
> product-product-module.js.map    1.55 MiB  product-product-module                    product-product-module
>                runtime.js.map    9.03 KiB                 runtime                    runtime
>                styles.css.map     174 KiB                  styles                    styles
>                      0.js.map    1.74 MiB                       0
>                 vendor.js.map    8.51 MiB                  vendor                    vendor
>                    index.html   807 bytes                          [emitted]
> Entrypoint main [big] = runtime.js runtime.js.map vendor.js vendor.js.map main.js main.js.map
> Entrypoint polyfills [big] = runtime.js runtime.js.map polyfills.js polyfills.js.map
> Entrypoint styles = runtime.js runtime.js.map styles.css styles.css.map
> chunk    {0} 0.js, 0.js.map 1.45 MiB <{common}> <{product-product-module}>
> chunk {cash-cash-module} cash-cash-module.js, cash-cash-module.js.map (cash-cash-module) 77.8 KiB <{common}> <{main}> <{product-product-module}> <{runtime}> <{vendor}> ={common}= >{common}< >{product-product-module}<
> chunk {common} common.js, common.js.map (common) 2.65 KiB <{cash-cash-module}> <{common}> <{main}> <{product-product-module}> <{runtime}> <{vendor}> ={cash-cash-module}= ={product-product-module}= >{0}< >{cash-cash-module}< >{common}< >{product-product-module}< split chunk (cache group: common) (name: common)
> chunk {main} main.js, main.js.map (main) 390 KiB ={runtime}= ={vendor}= >{cash-cash-module}< >{common}< >{product-product-module}< [initial]
> chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 314 KiB ={runtime}= [initial]
> chunk {product-product-module} product-product-module.js, product-product-module.js.map (product-product-module) 1.3 MiB <{cash-cash-module}> <{common}> <{main}> <{runtime}> <{vendor}> ={common}= >{0}< >{cash-cash-module}< >{common}<
> chunk {runtime} runtime.js, runtime.js.map (runtime) 0 bytes ={main}= ={polyfills}= ={styles}= ={vendor}= >{cash-cash-module}< >{common}< >{product-product-module}< [entry]
> chunk {styles} styles.css, styles.css.map (styles) 89.8 KiB ={runtime}= [initial]
> chunk {vendor} vendor.js, vendor.js.map (vendor) 7.03 MiB ={main}= ={runtime}= >{cash-cash-module}< >{common}< >{product-product-module}< [initial] split chunk (cache group: vendor) (name: vendor)
> i ｢wdm｣: Compiled successfully.

But if I run same command without `--verbose` then output will be:

> Date: 2018-12-04T00:39:32.097Z - Hash: d6736946413fd5378009 - Time: 6616ms
> 9 unchanged chunks
> i ｢wdm｣: Compiled successfully.
> i ｢wdm｣: Compiling...
> 
> Date: 2018-12-04T00:39:33.379Z - Hash: d6736946413fd5378009 - Time: 997ms
> 9 unchanged chunks
> i ｢wdm｣: Compiled successfully.
> i ｢wdm｣: Compiling...
> 
> Date: 2018-12-04T00:42:39.061Z - Hash: d6736946413fd5378009 - Time: 1389ms
> 9 unchanged chunks
> i ｢wdm｣: Compiled successfully.

- Some times is so bad that it recompile almost once a minute.
- From observation it starts as soon as I do first change and save.
- Company has strict security so I am not sure which software is installed.
- For some team member is ok they dont have this problem.
- Same problem is with karma tests they keep recompiling

**Comment by alan-agius4** [comment] 2018-12-04 05:18
Duplicate of https://github.com/angular/angular-cli/issues/13099

**Closed by alan-agius4** 2018-12-04 05:18 UTC
