### ISSUE TITLE
JsonGenerator.js:119 getSize() throws undefined error and crash "ng serve"

### ISSUE THREAD

**Issue by tosehee** [angular/angular-cli#21355] opened 2021-07-16 20:23 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 11

### Description

 With "ng serve" running, make any changes to the any .ts. It saves and cause the refresh. It works for the first save, but in 2nd save, it crashes with the following.

```
Generating browser application bundles.../Users/slee/work/deposco/client/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/json/JsonGenerator.js:119
		let data = module.buildInfo.jsonData;
		                            ^

TypeError: Cannot read property 'jsonData' of undefined
    at JsonGenerator.getSize (/Users/slee/work/deposco/client/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/json/JsonGenerator.js:119:31)
    at NormalModule.size (/Users/slee/work/deposco/client/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/NormalModule.js:1224:43)
    at NormalModule.cleanupForCache (/Users/slee/work/deposco/client/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/NormalModule.js:364:9)
    at NormalModuleFactory.cleanupForCache (/Users/slee/work/deposco/client/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/NormalModuleFactory.js:670:11)
    at Compiler._cleanupLastNormalModuleFactory (/Users/slee/work/deposco/client/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:383:34)
    at Compiler.createNormalModuleFactory (/Users/slee/work/deposco/client/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1049:8)
    at Compiler.newCompilationParams (/Users/slee/work/deposco/client/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1071:30)
    at Compiler.compile (/Users/slee/work/deposco/client/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1082:23)
    at /Users/slee/work/deposco/client/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Watching.js:188:19
    at Hook.eval [as callAsync] (eval at create (/Users/slee/work/deposco/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
```

**Comment by clydin** [comment] 2021-07-16 20:31
Duplicate of #21349

**Closed by clydin** 2021-07-16 20:31 UTC
