### ISSUE TITLE
Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by muhammedMoussa** [angular/angular-cli#16732] opened 2020-01-22 13:26 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 while building after 92%

## 🔬 Minimal Reproduction
```
ng build --prod 
```
in angular.json 
```
"configurations": { 
    ...,
    "sourceMap": false
}
```

## 🔥 Exception or Error
<pre><code>

</code>
92% chunk asset optimization TerserPlugin
<--- Last few GCs --->

[8384:000002227461AF20]  1286511 ms: Mark-sweep 1939.1 (2054.6) -> 1938.9 (2054.1) MB, 4143.4 / 0.1 ms  (average mu = 0.076, current mu = 0.003) allocation failure GC in old space requested
[8384:000002227461AF20]  1290391 ms: Mark-sweep 1939.5 (2054.1) -> 1939.4 (2054.8) MB, 3877.0 / 0.1 ms  (average mu = 0.040, current mu = 0.001) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF7DB3C2A5D]
    1: StubFrame [pc: 00007FF7DB343AE1]
Security context: 0x01ba85f408a1 <JSObject>
    2: _replaceInStringNode [0000006D927BAEB1] [D:\for_build\AccFlex_Cloud_Front\accflex-erp\node_modules\webpack-sources\lib\ReplaceSource.js:~194] [pc=00000167FEE21567](this=0x01cf89a77c51 <Source map = 00000326372B2CF1>,0x000fa445ce11 <JSArray[93248]>,0x000fa445ce31 <ReplacementEnumerator map = 0000008A776804D1>,0...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200122.151018.8384.0.001.json
Node.js report completed
</pre>

## 🌍 Your Environment
<pre><code>

</code>
Angular CLI: 8.3.0
Node: 12.12.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.0
@angular-devkit/core         8.3.0
@angular-devkit/schematics   8.3.0
@schematics/angular          8.3.0
@schematics/update           0.803.0
rxjs                         6.4.0
</pre>

**Anything else relevant?**

this issue comes from old version, will be good if not exist in v9

**Comment by clydin** [comment] 2020-01-22 14:37
Duplicate of #16515

**Closed by clydin** 2020-01-22 14:37 UTC
