### ISSUE TITLE
AOT runtime issue - Uncaught TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by radoslavpetranov** [angular/angular-cli#5769] opened 2017-03-30 21:16 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
```

### Repro steps.
This happens when I run `ng serve --aot`. If I just run `ng serve` everything works fine.

### The log given by the failure.
```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (person-change.service.ts:8)
    at company.subServices.ts:77
    at Object.<anonymous> (company.subServices.ts:91)
    at __webpack_require__ (bootstrap 9953f62…:52)
    at Object.<anonymous> (case.service.ts:85)
    at __webpack_require__ (bootstrap 9953f62…:52)
    at Object.MaritialStatusEnum.getInstance.instance (currency.enum.ts:72)
    at __webpack_require__ (bootstrap 9953f62…:52)
    at Object.CountryEnum.getInstance.instance (address.model.ts:211)
    at __webpack_require__ (bootstrap 9953f62…:52)
    at Object.<anonymous> (address.subService.ts:42)
    at __webpack_require__ (bootstrap 9953f62…:52)
    at Object.<anonymous> (company.subServices.ts:125)
    at __webpack_require__ (bootstrap 9953f62…:52)
```

### Desired functionality.
The app to work - it was working in --aot mode before some changes I've been working on today.

### Mention any other details that might be useful.
The error is triggered by the following class which extends a generic abstract class

```
import {Injectable} from "@angular/core";
import {PersonModel} from "../../models/person/person.model";
import {ObjectChangeService} from "./object-change.service";

@Injectable()
export class PersonChangeService extends ObjectChangeService<PersonModel> {

}
// The error in my Chrome console -  at __extends (person-change.service.ts:8) - is triggered/shown at the closing '}' in the line above

// WEBPACK FOOTER //
// ./src/app/services/change/person-change.service.ts
````

The compilation is successful - I get the error during runtime

```
** NG Live Development Server is running on http://localhost:4200 **
Hash: 9953f6279102d223f071
Time: 49537ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 2.02 MB {3} [initial] [rendered]
chunk    {1} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 77.5 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.2 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
```

**Comment by radoslavpetranov** [comment] 2017-03-31 14:31
For the record, the culprit is a ` ReflectiveInjector.resolveAndCreate` call that I'm making. 2 of the services inside the ` ReflectiveInjector.resolveAndCreate` call are causing the error. If I comment out these 2 services for testing purposes the error is gone.

**Comment by radoslavpetranov** [comment] 2017-03-31 20:56
In case anyone else cares, it appears this maybe a WebPack issue

https://github.com/Microsoft/TypeScript/issues/14734

**Comment by radoslavpetranov** [comment] 2017-04-01 15:02
Last update on this issue - I didn't manage to figure out what's causing the bad compilation that was triggering the `undefined` error so finally I changed some stuff around and ditched the `ReflectiveInjector.resolveAndCreate` approach for the regular DI approach which ultimately got rid of the issue. 

If nobody cares about this feel free to close the issue. I learned my lesson - forget that manual injection even exists.

**Comment by killface** [comment] 2017-04-06 04:07
You can also get this error if you're using `APP_INITIALIZER` and try to use a class that wasn't listed in the `deps` array.

**Comment by lichunbin814** [comment] 2017-04-07 06:07
@radoslavpetranov  How do you solve it ?

**Comment by radoslavpetranov** [comment] 2017-04-07 06:34
I said in my last comment - I realized this is happening only when I compile in AOT and only when I'm using manual DI (i.e. `ReflectiveInjector.resolveAndCreate`). I changed my code around to get rid of the `ReflectiveInjector.resolveAndCreate` call and to switch to regular (i.e. constructor) DI and I didn't see the issue any more. Sorry but I don't have a real solution to the issue - I just went around it.

**Comment by sasxa** [comment] 2017-04-28 18:56
I got this error when I was importing from barrels:

    import { User } from './../../features/users';
    import { User } from './../../features/users/index';

Importing directly from file resolves the issue:

    import { User } from './../../features/users/user.model';

Note that `User` in my case is just a TypeScript class, no decorators or DI stuff...

**Comment by filipesilva** [comment] 2017-05-03 13:16
Closing as it looks like @radoslavpetranov solved it in the end.

**Closed** 2017-05-03 13:16 UTC

**Comment by neridonk** [comment] 2017-05-11 08:38
Okey this error is still present, workaround is to use the Import not from Barrels like @sasxa  said also avoid ReflectiveInjector.resolveAndCreate

**Comment by josipN** [comment] 2017-05-12 09:06
@sasxa Good job! It was the solution I was looking for!

**Comment by victorprocure** [comment] 2017-05-25 04:27
I came across this while searching for a solution to this issue for me. Unfortunately @radoslavpetranov solution did not working for me. What I found however was that my files were being served up in ISO-8859 as the Content-Type by my webserver, instead of UTF-8.
Once I switched Content-Type to UTF-8 in Spring-Boot (in my case), everything worked correctly.

**Comment by shlomiassaf** [comment] 2017-06-14 21:44
@filipesilva 

I got this now when upgrading to 4.2.0 from 4.1.1

It's either from the compiler-cli or tsc-wrapped dunno which

**Comment by mustafaekim** [comment] 2017-06-15 20:07
I am getting the same runtime error only when I try to run my angular app (4.1) after compiling with AOT/rollup even though the compilation does not cause any error. I dont know what to do because that is an angular app that I develop for more than 6 months and that's the first time I tried compiling with AOT/rollup. The error I get (as it is above) does not tell me anything friendly so I do not know where I should focus. I already use more than 10+ external npm libraries and I wrote 50+ classes. What do you recommend me?

**Comment by solisarg** [comment] 2017-06-30 19:04
I get the error in a different context, while running some tests. I get ride of the error changing the order of the imports at the top of the test file

**Comment by kodeine** [comment] 2017-07-31 06:43
i am facing the same issue and cant find exact root cause of this error.

**Comment by Murilo-Perrone** [comment] 2017-08-16 05:37
I got this error message while experimenting with the following code:

`    Object.assign(q, {answerType: 'default'} ); `

Which was trying to assign a string to a previously assigned enum property of a class:

`answerType: AnswerTypeEnum = AnswerTypeEnum.text;`

The issue here is that the error message and stack trace don't give me any clue at all about what's wrong with the code. Instead, they pointed out to unrelated files.

Hope that helps.

**Comment by radoslavpetranov** [comment] 2017-10-12 09:25
I updated from CLI 1.2.1 to 1.4.5 yesterday and I started getting warnings that circular dependencies were detected and I started getting that same `Uncaught TypeError: Object prototype may only be an Object or null: undefined` error allover again when running in `--aot` mode.

I ended up dropping all my barrel files and switched to direct file imports and that resolved both the circular dependency warnings and the `--aot` error from this issue. I thought I'd share this in case someone else is struggling with the same problem.

**Comment by patrickmichalina** [comment] 2017-10-14 14:32
Ok for anyone having this issue, please check that in the constructor, you are not using a Type that does not exist in the bundle..

I had
```js
import { Response } from 'express'

constructor( @Optional() @Inject(RESPONSE) response: Response) {
    this.response = response
}
```

but the issue was typing response to an interface that doesn't exist at runtime

so my solution to maintain strong typing in the project was:

```js
import { Response } from 'express'

private response: Response

constructor( @Optional() @Inject(RESPONSE) response: any) {
    this.response = response
}
```
