### ISSUE TITLE
ng new takes long to finish

### ISSUE THREAD

**Issue by web-dave** [angular/angular-cli#1830] opened 2016-08-25 06:31 UTC
To Setup a Project the command `ng new` takes very Long to finish. More than 10 minutes are too much I think.

angular-cli: 1.0.0-beta.11-webpack.2
node: 4.4.0
os: win 10 win32 x64

Dave.

**Comment by cre8** [comment] 2016-08-26 08:59
AngularCLI files are created in less than a second. But there are a lot of packages that have to be downloaded. This takes a lot of time :(

**Comment by filipesilva** [comment] 2016-08-28 17:28
Dupe of https://github.com/angular/angular-cli/issues/1263

**Closed by filipesilva** 2016-08-28 17:28 UTC

**Comment by alfaiz-momin** [comment] 2017-06-09 19:13
How much time it takes?
I tried two times, it stops after creating some folders for a while!...

**Comment by gyanchandk** [comment] 2017-09-02 16:04
The simple solution to this problem is _close the command window forcefully_ to abort the process,and then delete the node-modules folder which has been created so far. Finally run **npm install** command to have node-modules explicitly .

**Comment by stephenasamoah** [comment] 2018-01-23 11:30
Another approach is to use the `--skip-install` flag which generates a new project without installing all the node modules. You can then run `npm install` later to install all the required modules.

**Comment by b-mi** [comment] 2018-08-12 07:39
ng new project is EXACTLY SAME as ng new project --skip-install, then npm install. node_modules is binary exactly same. I tested it. DO NOT GIVE FALSE ADVICES WHICH YOU DID NOT TESTED, YOU WASTE OUR TIME. These pages are full of false advices, and between them are a few good advices.

**Comment by b-mi** [comment] 2018-08-12 07:59
This is quick:
ng new proj --skip-install
npm update

But to run app is there is need to install this:
npm install --save @angular-devkit/build-angular @angular/compiler-cli

And this install nearly same as npm install (slightly less) - 23749 files, 181 MB (full node_modules 205 MB).

**Comment by brunopugliese** [comment] 2019-04-04 18:53
Although I agree that "ng new project --skip-install" followed by "npm install" should be the SAME as "ng new project", for me ng new project takes forever and using the separate npm install does not.

Not entirely sure what could be the real issue.
