### ISSUE TITLE
Angular 16 ESbuild not recoginzing main.ts and polyfills.ts files even after including in tsconfig.app.json

### ISSUE THREAD

**Issue by SandeepCheemakurthi** [angular/angular-cli#27189] opened 2024-03-03 05:10 UTC
### Command

build, config, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

trying to serve the application with forceEsbuild option, but after running the ng serve, throwing error. Also application works fine and there is no problem in serving the application without forceEsbuild option. Tried with node v16 and v18, but no luck.

Using the below dependency versions
"@angular-devkit/build-angular": "16.2.12",
"@angular/common": "^16.2.8",
"@angular/compiler": "^16.2.8",
"@angular/core": "^16.2.8",
	
tsconfig.app.json:
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": ["node"]
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ],
  "exclude": [
    "src/test.ts",
    "src/**/*.spec.ts"
  ]
}

X [ERROR] File 'src\main.ts' is missing from the TypeScript compilation. [plugin angular-compiler]

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.

X [ERROR] File 'src\polyfills.ts' is missing from the TypeScript compilation. [plugin angular-compiler]

    angular:polyfills:angular:polyfills:1:7:
      1 │ import 'src/polyfills.ts';

### Minimal Reproduction

ng serve

### Your Environment

```text
Angular CLI: 16.2.12
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 16.2.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------    
@angular-devkit/architect          0.1602.12
@angular-devkit/build-angular      16.2.12
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/core               16.2.12
@angular-devkit/schematics         16.2.12
@angular/cdk                       16.2.13
@angular/material                  16.2.13
@schematics/angular                16.2.12
ng-packagr                         16.2.3
rxjs                               7.8.1
typescript                         4.9.5
zone.js                            0.14.3
```

**Comment by SandeepCheemakurthi** [comment] 2024-03-03 05:12
@alan-agius4 Can Please help on this.

**Comment by Omkar76** [comment] 2024-03-03 09:19
Looks like fix for this was shipped in angular 17 but not 16.

**Comment by SandeepCheemakurthi** [comment] 2024-03-03 14:13
> Looks like fix for this was shipped in angular 17 but not 16.

So ESBuild can't be used for angular 16 applications?

**Comment by JeanMeche** [comment] 2024-03-03 15:52
Depending on your `polyfill.ts` you could have its content directly on the `polyfills` entry in the `angular.json`.

**Comment by SandeepCheemakurthi** [comment] 2024-03-03 15:56
> Depending on your `polyfill.ts` you could have its content directly on the `polyfills` entry in the `angular.json`.

Polyfills issue I could solve it, but for main.ts?

**Comment by JeanMeche** [comment] 2024-03-03 15:58
Do you use a custom `baseUrl` as in #25341  ?

**Comment by SandeepCheemakurthi** [comment] 2024-03-03 16:00
> Do you use a custom `baseUrl` as in #25341  ?

baseUrl:"./" ,  it's configured in this way

**Comment by alan-agius4** [comment] 2024-03-04 08:52
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Closed by alan-agius4** 2024-03-04 08:52 UTC
