### ISSUE TITLE
Add new webpack config for new URL('...', import.meta.url)

### ISSUE THREAD

**Issue by gfsd3v** [angular/angular-cli#22888] opened 2022-03-24 00:12 UTC
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Hello guys,

Is it planned to add support for the new config in webpack for `new URL('...', import.meta.url)` syntax?

Context:
https://github.com/webpack/webpack/pull/15246
https://github.com/angular/angular-cli/issues/22388 @alan-agius4 

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment] 2022-03-24 05:58
Duplicate of https://github.com/angular/angular-cli/issues/22351#issuecomment-1013012092

**Closed by alan-agius4** 2022-03-24 05:58 UTC
