### ISSUE TITLE
NG g with --lint-fix in subdirectory fails

### ISSUE THREAD

**Issue by Akxe** [angular/angular-cli#17171] opened 2020-03-07 15:55 UTC
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

@angular/cli 9.0.4

### Description

The `--lint-fix` will crash, if the command doesn't run from within the same folder the `angular.json` file is.

## 🔬 Minimal Reproduction

Create angular project, navigate to  `/src/app/`  or any other and run any `generate` command with `--lint-fix` flag.
```
ng g m map/map-html-marker --lint-fix
ng g m map/map-html-marker --lint-fix
```

## 🔥 Exception or Error
<pre><code>
C:\Users\akxe\Documents\Programming\Rex-client\src\app [map-html-marker]> ng g m map/map-html-marker/map-html-marker --lint-fix
CREATE src/app/map/map-html-marker/map-html-marker/map-html-marker.module.ts (199 bytes)
ENOENT: no such file or directory, scandir 'C:\Users\akxe\Documents\Programming\Rex-client\src\app\src\app\map\map-html-marker\map-html-marker'
C:\Users\akxe\Documents\Programming\Rex-client\src\app [map-html-marker +1 ~0 -0 !]> ng g m map/map-html-marker --lint-fix
CREATE src/app/map/map-html-marker/map-html-marker.module.ts (199 bytes)
CREATE src/app/map/map-html-marker/map-html-marker.component.html (30 bytes)
CREATE src/app/map/map-html-marker/map-html-marker.component.spec.ts (679 bytes)
CREATE src/app/map/map-html-marker/map-html-marker.component.ts (386 bytes)
CREATE src/app/map/map-html-marker/map-html-marker.component.scss (0 bytes)
UPDATE src/app/map/map-html-marker/map-html-marker.module.ts (291 bytes)
ENOENT: no such file or directory, scandir 'C:\Users\akxe\Documents\Programming\Rex-client\src\app\src\app\map\map-html-marker'
</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.5
Node: 12.16.1
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.1.1
@angular/google-maps              9.0.1
@angular/material                 9.1.1
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
No

**Comment by alan-agius4** [comment] 2020-03-08 10:00
Duplicate of https://github.com/angular/angular-cli/issues/12480

**Closed by alan-agius4** 2020-03-08 10:00 UTC
