### ISSUE TITLE
100% CPU on ng build --prod, hangs on scss

### ISSUE THREAD

**Issue by dalu** [angular/angular-cli#11314] opened 2018-06-20 09:14 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

```
darko@wrk ~ $ node --version
v10.4.1
darko@wrk ~ $ npm --version
6.1.0
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.8
Node: 10.4.1
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.1
typescript                   2.7.2
```

### Repro steps

I can't. I could upload the source somewhere and give you temporary access to it.

### The log given by the failure

There is no log. There is no way to debug the build process.
```
ng build --prod --verbose
 10% building modules 3/4 modules 1 active …ormProjects/raidrecruit/src/styles.scss
```
```
ps auxw
darko    10312  113  1.8 1423532 309616 pts/0  Rl+  11:11   0:30 ng
```

### Desired functionality

The build process should not be stuck on scss of all things.

### Mention any other details that might be useful

It worked yesterday and previously.
It works when building without `--prod`.
How can I debug the build process?

**Comment by dalu** [comment] 2018-06-20 09:45
When downloading the css and replacing imports in styles.scss it <strike>still hangs</strike> goes through but it takes a few minutes and it appears to hang at the same point.
The one thing that was changed were button classes. from roughly `[class]="condition ? 'btn btn-block btn-success':'btn btn-block btn-danger'"` to `<button *ngIf="user_id === raid.keycloak_id && raid.setup.dps_2.healer !== ''" class="btn btn-block btn-danger">`

**Comment by dalu** [comment] 2018-06-20 09:48
Err. I don't know what's happening.
I use Webstorm. Now and when the css build process went through I did something in Webstorm and that particular file, for instance I pressed ctrl+z when the css build process was running, and now I marked and ctrl+c 

Could it be an issue with file watchers?

**Comment by alan-agius4** [comment] 2018-06-20 10:43
Can you please create a small reproduction?

**Comment by dalu** [comment] 2018-06-20 16:35
I believe I have to upload all of it somewhere, it's the sum not just one part.
I went and run ng build --prod then took a shower and returned to find it actually compiled.
```
Date: 2018-06-20T15:49:25.602Z
Hash: 908a22a2d61e441fc450
Time: 564130ms
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.928ece099bd66621c9f1.css (styles) 128 kB [initial] [rendered]
chunk {2} polyfills.2f4a59095805af02bd79.js (polyfills) 59.6 kB [initial] [rendered]
chunk {3} main.832118c83f0ddb93f360.js (main) 861 kB [initial] [rendered]
```
However it took almost 10 minutes but the app isn't really all that big or complicated, about a week worth of work.
Still I don't want it to be public.
I can give you access over at https://git.icod.de/ but I'd need an email address.

**Comment by alan-agius4** [comment] 2018-06-21 06:51
I had a look at this, and it looks like the angular compiler is taking too long.

Running the below
```
node_modules\.bin\ngc -p src\tsconfig.app.json
```

takes a lot of time.

**Comment by dalu** [comment] 2018-06-22 09:53
Thanks, I guess I'll have to. This is my first larger angular project involving 7 or more models.
I already thought about splitting it all into sub-components because on every change I would need to change all copies and this was really time-consuming.

I've removed the public flag, if you need access again in the future, please let me know.

**Comment by alan-agius4** [comment] 2018-06-22 10:02
What I suggest is that you create a dump component which doesn't fully reflect your `model` but rather be slightly more generic 


Something along these lines;
```html
<div class="card">
	<div class="card-body">
		<div class="card-title">
		<div >
			{{ name }}
		</div>
		</div>
		<div>{{subTitle}}</div>
		<button *ngIf="sRole(Name) && !isSigned()" (click)="joinRaid(name)">
			Join
		</button>
		<button (click)="leaveRaid(name)">
			Unsign {{firstName}}
		</button>
		<button (click)="leaveRaid(name)">
		Kick From Raid
		</button>
	</div>
</div>
```

As most of your templates are the same and just the data is different.

**Comment by dalu** [comment] 2018-06-22 12:06
You know what. I don't want to do that. It's unnecessary waste of time.

**Comment by filipesilva** [comment] 2018-08-10 09:15
There's some pretty good discussion here, and this seems like some performance issue with `ngc` proper (which is maintained at https://github.com/angular/angular).

I don't want to close this one because of all the information here already but you'll get a lot more traction at https://github.com/angular/angular, especially if you include a repro of the component that cause the low performance.

**Comment by dalu** [comment] 2018-08-10 13:45
No problem. I was reporting a bug and I finished the project I was working on. If you'd like to forward it or not that's your thing. Close at will.

**Comment by daem0ndev** [comment] 2019-01-04 00:39
We have an angular 7.1.4 project with ionic v4 and are experiencing the same identical hang on prod ng build, precisely at the styles.scss file as well. Our source is not public so wondering if there’s any other clues or info I could provide to help out.

**Comment by Danieliverant** [comment] 2019-05-02 16:06
same problem, stuck on scss on 38%. help?

**Comment by pabrams** [comment] 2019-08-15 16:50
Same here.  What's going on? How do I get some debug info, or where are the log files?

**Comment by pabrams** [comment] 2019-08-15 16:58
Me too. 
![image](https://user-images.githubusercontent.com/1376688/63111732-524a2c80-bf5c-11e9-8273-5e71c0028114.png)

**Comment by filipesilva** [comment] 2019-08-15 18:25
We've been tracking performance issues for Angular CLI 8 in https://github.com/angular/angular-cli/issues/13734. I think it's better to close this issue in favor of that one. Please see https://github.com/angular/angular-cli/issues/13734#issuecomment-521743839 for the latest update.

**Closed by filipesilva** 2019-08-15 18:25 UTC
Labels: blocked, comp: devkit/build-angular, freq1: low, severity3: broken, type: bug/fix
