### ISSUE TITLE
Failed to install angular cli on centos because require-from-string@^1.1.0 not available in repository

### ISSUE THREAD

**Issue by tovinayv** [angular/angular-cli#9119] opened 2018-01-07 08:55 UTC
Failed to install @angular/cli

-bash-4.1$ npm i @angular/cli
npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/dbc/blr-dbc404/vinayv/nodejs/lin64/bin/node" "/dbc/blr-dbc404/vinayv/nodejs/lin64/bin/npm" "i" "@angular/cli"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: require-from-string@^1.1.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.0.2
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

-bash-4.1$ lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.6 (Final)
Release:        6.6
Codename:       Final

**Comment by tovinayv** [comment] 2018-01-07 08:56
-bash-4.1$ npm -v
3.10.10
-bash-4.1$ node -v
v6.9.4

**Comment by clydin** [comment] 2018-01-08 15:59
This is a duplicate of issue #9113 and has been resolved.

**Closed by clydin** 2018-01-08 15:59 UTC
