### ISSUE TITLE
 Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):

### ISSUE THREAD

**Issue by david-baghdasaryan** [angular/angular-cli#25498] opened 2023-07-06 12:40 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm create new app and after first `serve` throw this build error 

![image](https://github.com/angular/angular-cli/assets/29034829/3b9d39bc-b88c-4c89-80b7-c02615792e63)

### Minimal Reproduction

ng new 
ng serve

### Exception or Error

```text
./node_modules/@angular/common/fesm2022/common.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
TypeError: D:\apps\Other\form-angular\node_modules\@angular\common\fesm2022\common.mjs: Cannot read properties of undefined (reading 'file')

./node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
TypeError: D:\apps\Other\form-angular\node_modules\@angular\platform-browser\fesm2022\platform-browser.mjs: Cannot read properties of undefined (reading 'file')
```

### Your Environment

```text
@angular-devkit/architect       0.1601.1
@angular-devkit/build-angular   16.1.1
@angular-devkit/core            16.1.1
@angular-devkit/schematics      16.1.1
@angular/cli                    16.1.1
@schematics/angular             16.1.1
rxjs                            7.8.1
typescript                      5.1.3
```

**Comment by svoboda-rabstvo** [comment] 2023-07-06 12:46
I have the same error

**Comment by flonussi** [comment] 2023-07-06 12:47
Some here, we didn't even install any new dependencies, it just stopped working

**Comment by alan-agius4** [comment] 2023-07-06 12:48
Duplicate of https://github.com/angular/angular-cli/issues/25496

**Closed by alan-agius4** 2023-07-06 12:48 UTC
