### ISSUE TITLE
e2e test on a new project fails using ng 4.0.0.rc.3.

### ISSUE THREAD

**Issue by daBishMan** [angular/angular-cli#5385] opened 2017-03-11 19:02 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows  10.

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-rc.1
node: 7.6.0
os: win32 x64
@angular/common: 4.0.0-rc.3
@angular/compiler: 4.0.0-rc.3
@angular/core: 4.0.0-rc.3
@angular/forms: 4.0.0-rc.3
@angular/http: 4.0.0-rc.3
@angular/platform-browser: 4.0.0-rc.3
@angular/platform-browser-dynamic: 4.0.0-rc.3
@angular/router: 4.0.0-rc.3
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 4.0.0-rc.3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Create a new project using `ng new TalentSearch-Client --style=sass -sg -dir gig-ts-client/ -p dhi -si`
I ran npm install after that.

### The log given by the failure.
> Normally this include a stack trace and some more information.
when running e2e without any modification I get

$ ng e2e
** NG Live Development Server is running on http://localhost:49152 **
(node:19608) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Hash: 0886637fd0d99b80aec7
Time: 6342ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 3.69 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.89 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.26 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
[11:57:14] I/update - chromedriver: file exists C:\git\gig\gig-ts-client\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.28.zip
[11:57:14] I/update - chromedriver: unzipping chromedriver_2.28.zip
[11:57:14] I/update - chromedriver: chromedriver_2.28.exe up to date
[11:57:14] I/launcher - Running 1 instances of WebDriver
[11:57:14] I/direct - Using ChromeDriver directly...
[11:57:17] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'jasmine'. (2688)
Cannot find type definition file for 'node'. (2688)
e2e\app.e2e-spec.ts (3,1): Cannot find name 'describe'. (2304)
e2e\app.e2e-spec.ts (6,3): Cannot find name 'beforeEach'. (2304)
e2e\app.e2e-spec.ts (10,3): Cannot find name 'it'. (2304)
e2e\app.e2e-spec.ts (12,5): Cannot find name 'expect'. (2304)
    at getOutput (C:\git\gig\gig-ts-client\node_modules\ts-node\src\index.ts:312:17)
    at C:\git\gig\gig-ts-client\node_modules\ts-node\src\index.ts:343:18
    at Object.compile (C:\git\gig\gig-ts-client\node_modules\ts-node\src\index.ts:476:19)
    at Module.m._compile (C:\git\gig\gig-ts-client\node_modules\ts-node\src\index.ts:406:44)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\git\gig\gig-ts-client\node_modules\ts-node\src\index.ts:409:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\git\gig\gig-ts-client\node_modules\jasmine\lib\jasmine.js:87:5
    at Array.forEach (native)
    at Jasmine.loadSpecs (C:\git\gig\gig-ts-client\node_modules\jasmine\lib\jasmine.js:86:18)
    at Jasmine.execute (C:\git\gig\gig-ts-client\node_modules\jasmine\lib\jasmine.js:181:8)
    at C:\git\gig\gig-ts-client\node_modules\protractor\built\frameworks\jasmine.js:132:15
    at Function.promise (C:\git\gig\gig-ts-client\node_modules\q\q.js:682:9)
    at C:\git\gig\gig-ts-client\node_modules\protractor\built\frameworks\jasmine.js:104:14
    at _fulfilled (C:\git\gig\gig-ts-client\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\git\gig\gig-ts-client\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\git\gig\gig-ts-client\node_modules\q\q.js:796:13)
    at C:\git\gig\gig-ts-client\node_modules\q\q.js:556:49
    at runSingle (C:\git\gig\gig-ts-client\node_modules\q\q.js:137:13)
    at flush (C:\git\gig\gig-ts-client\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[11:57:17] E/launcher - Process exited with error code 100

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by daBishMan** [comment] 2017-03-11 19:54
The tsconfig.e2e.json using --ng4 is the following:  

> {
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../dist/out-tsc-e2e",
    "module": "commonjs",
    "target": "es6",
    "types":[
      "jasmine",
      "node"
    ]
  }
}

**Comment by peteralbert** [comment] 2017-03-12 23:45
Same issue here - blank `ng new -ng4` project, exactly the same error message.

**Comment by peteralbert** [comment] 2017-03-12 23:57
Here's the fix/workaround - see #5082!

You need to add 

```
"typeRoots": [
  "../node_modules/@types"
]
```

to `tsconfig.e2e.json`

**Comment by daBishMan** [comment] 2017-03-13 14:16
thanks @peteralbert that worked for me.

**Comment by filipesilva** [comment] 2017-03-18 00:45
Dupe of https://github.com/angular/angular-cli/issues/5082

**Closed by filipesilva** 2017-03-18 00:45 UTC
