### ISSUE TITLE
bug(commonjs): erroneous ngfactory

### ISSUE THREAD

**Issue by CaerusKaru** [angular/angular-cli#7910] opened 2017-10-03 02:26 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.5.0-beta.2
node: 8.6.0
os: darwin x64
@angular/animations: 5.0.0-rc.0
@angular/cdk: 2.0.0-beta.11
@angular/common: 5.0.0-rc.0
@angular/compiler: 5.0.0-rc.0
@angular/core: 5.0.0-rc.0
@angular/forms: 5.0.0-rc.0
@angular/http: 5.0.0-rc.0
@angular/material: 2.0.0-beta.11
@angular/platform-browser: 5.0.0-rc.0
@angular/platform-browser-dynamic: 5.0.0-rc.0
@angular/platform-server: 5.0.0-rc.0
@angular/router: 5.0.0-rc.0
@angular/cli: 1.5.0-beta.2
@angular/compiler-cli: 5.0.0-rc.0
@angular/language-service: 5.0.0-rc.0
typescript: 2.5.3
```

### Repro steps.

1. Clone the sample repo found [here](https://github.com/CaerusKaru/universal-cli-bug)
2. Change into the `cli` directory
3. Run `npm install` and `npm run build:dynamic`

To show the second type of error (detailed below):
1. After the steps above, remove `MatCardModule` from `app.module.ts`, and remove the reference to `<mat-card>` in `app.component.ts`.
2. Run `npm run build:dynamic && npm run serve:dynamic` (which should succeed this time)
3. Navigate to `localhost:4000`. Disable JavaScript and reload the page
4. Attempt to navigate to the lazy route, examine the server for the error log

To show the third type of error (detailed below):
1. Re-enable JavaScript on `localhost:4000` and reload the page
2. Attempt to navigate to the lazy route, examine the browser console for the error log

### The log given by the failure.

```
ERROR in ./dist/server/main.bundle.js
Module not found: Error: Can't resolve '@angular/material/card/typings/index.ngfactory' in '/Users/main/universal-cli-bug/cli/dist/server'
 @ ./dist/server/main.bundle.js 1:2433-2490
 @ ./prerender.ts
```

### Desired functionality.

AOT compilation needs to work for commonjs bundling where the bundle includes a lazy-loaded module that also includes an external module like Angular Material.

### Mention any other details that might be useful.

This is an issue only when the external module is included in a lazy-loaded module. If it's included at the top-level, it works as expected. It also works as expected in cli@1.4.4

**Comment by CaerusKaru** [comment] 2017-10-06 01:17
Tested with 1.5.0 betas 3 and 4, neither resolved the issue

**Comment by CaerusKaru** [comment] 2017-10-24 11:50
@filipesilva Is there any update on this issue? I feel like 1.5.0 is nearing final and there has been no progress made here.

To add on to symptoms of this issue, adding the `bundle-dependencies` flag results in a different error: 

`Error: No NgModule metadata found for '[object Object]'`. This error occurs when the server spins up and tries to compile the module with JIT

When running without the flag, the bundle size for the main module is also significantly smaller than it should be (which makes sense, since most of the lazy-loaded content isn't being compiled).

cc @hansl for `bundle-dependencies` issue

**Comment by filipesilva** [comment] 2017-10-24 12:16
@CaerusKaru do you think this is related to https://github.com/angular/angular-cli/issues/7901 perhaps? It also had to do with lazy modules and https://github.com/angular/angular-cli/pull/8157 fixed it.

@Brocco can you have a look?

**Comment by CaerusKaru** [comment] 2017-10-24 12:50
@filipesilva It's unrelated, the issue persists in RC.3

@Brocco Here's the updated rub, as far as my investigations have gone:

1. The error no longer surfaces during bundling when the module in question is lazy-loaded, but it does surface now when the module is imported at the top level (I've updated the repo above to reflect this)
2. If the top-level import is removed, the build succeeds, but navigating to the lazy-loaded page with the module returns the following error: 
```
TypeError: factory.create is not a function
    at MapSubscriber.project (/Users/main/universal-cli-bug/cli/dist/server.js:132272:51)
    at MapSubscriber._next (/Users/main/universal-cli-bug/cli/dist/server.js:135287:35)
    at MapSubscriber.Subscriber.next (/Users/main/universal-cli-bug/cli/dist/server.js:26375:18)
    at /Users/main/universal-cli-bug/cli/dist/server.js:109872:36
    at ZoneDelegate.invoke (/Users/main/universal-cli-bug/cli/dist/server.js:123046:26)
    at Object.onInvoke (/Users/main/universal-cli-bug/cli/dist/server.js:5080:33)
    at ZoneDelegate.invoke (/Users/main/universal-cli-bug/cli/dist/server.js:123045:32)
    at Zone.run (/Users/main/universal-cli-bug/cli/dist/server.js:122796:43)
    at /Users/main/universal-cli-bug/cli/dist/server.js:123527:57
    at ZoneDelegate.invokeTask (/Users/main/universal-cli-bug/cli/dist/server.js:123079:31)
    at resolvePromise (/Users/main/universal-cli-bug/cli/dist/server.js:123478:31)
    at resolvePromise (/Users/main/universal-cli-bug/cli/dist/server.js:123449:17)
    at /Users/main/universal-cli-bug/cli/dist/server.js:123527:17
    at ZoneDelegate.invokeTask (/Users/main/universal-cli-bug/cli/dist/server.js:123079:31)
    at Object.onInvokeTask (/Users/main/universal-cli-bug/cli/dist/server.js:5071:33)
    at ZoneDelegate.invokeTask (/Users/main/universal-cli-bug/cli/dist/server.js:123078:36)
    at Zone.runTask (/Users/main/universal-cli-bug/cli/dist/server.js:122846:47)
    at drainMicroTaskQueue (/Users/main/universal-cli-bug/cli/dist/server.js:123256:35)
    at ZoneTask.invokeTask (/Users/main/universal-cli-bug/cli/dist/server.js:123157:21)
    at Server.ZoneTask.invoke (/Users/main/universal-cli-bug/cli/dist/server.js:123142:48)
```

I'm hoping this is a simple module resolution issue, because it's incredibly frustrating.

**Comment by CaerusKaru** [comment] 2017-10-24 12:55
@Brocco I updated the steps above to reflect all three types of error. I forgot to mention that even when server-side isn't used, and the client has bootstrapped, there's another error printed to the browser console:

`ERROR Error: Uncaught (in promise): Error: Cannot find module './lazy/lazy.module.ngfactory'.
Error: Cannot find module './lazy/lazy.module.ngfactory'.`

**Comment by CaerusKaru** [comment] 2017-10-24 12:59
Adding on, here is the size comparison for running `ng serve` and `ng build`:

```
> ng-serve
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {lazy.module} lazy.module.chunk.js () 6.48 kB {main}  [rendered]
chunk {main} main.bundle.js (main) 19.5 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 599 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 33.6 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 13.1 MB [initial] [rendered]
```

```
> npm run build:dynamic
chunk {0} 0.cddcc3dcb8d7ea7e3346.chunk.js () 273 bytes {2}  [rendered]
chunk {1} polyfills.b1bfde5be7cfa1575ad5.bundle.js (polyfills) 65.6 kB {5} [initial] [rendered]
chunk {2} main.a824cc0ebdbede8e6103.bundle.js (main) 5.34 kB {4} [initial] [rendered]
chunk {3} styles.d41d8cd98f00b204e980.bundle.css (styles) 0 bytes {5} [initial] [rendered]
chunk {4} vendor.d8a76c426ca21b112566.bundle.js (vendor) 512 kB [initial] [rendered]
chunk {5} inline.89dfd35ffca9b95b8f60.bundle.js (inline) 1.47 kB [entry] [rendered]
...
chunk {0} main.bundle.js (main) 15.3 kB [entry] [rendered]
chunk {1} styles.bundle.css (styles) 0 bytes [entry] [rendered]
```

**Comment by filipesilva** [comment] 2017-10-24 13:21
@MarkPieszak @toxicable do you have any insight maybe?

**Comment by CaerusKaru** [comment] 2017-10-25 00:36
@Brocco @filipesilva Is there a chance this is related to the shift from AotPlugin to AngularCompilerPlugin? As a test, I ran `ng serve` and then `ng serve --aot`, and the latter gave me this error:

```
Uncaught ReferenceError: platformBrowser is not defined
    at HTMLDocument.eval (webpack-internal:///../../../../../src/main.ts:11)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:425)
    at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:192)
    at ZoneTask.invokeTask [as invoke] (webpack-internal:///../../../../zone.js/dist/zone.js:499)
    at invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:1540)
    at HTMLDocument.globalZoneAwareCallback (webpack-internal:///../../../../zone.js/dist/zone.js:1566)
```

Running without aot runs the program as expected, but this means that production builds are broken.

**Comment by CaerusKaru** [comment] 2017-10-25 01:15
Here's another question, could this have anything to do with how Angular Material is currently built? It's using `tsc-wrapped` right now, but is transitioning to using `ngc` with this PR: https://github.com/angular/material2/pull/6018

**Comment by hansl** [comment] 2017-10-25 19:33
Some sub issues should be fixed with #8188

**Comment by MarkPieszak** [comment] 2017-10-26 00:19
I haven't seen this one yet, but i'll take a look!

**Comment by CaerusKaru** [comment] 2017-10-26 01:37
@hansl I installed cli-builds with #8188, but now the build doesn't respect tsconfig `paths` specified as follows: 

```json
"paths": {
  "@app/*": ["app/*"],
  "@env/*": ["environments/*"]
}
```

**Comment by CaerusKaru** [comment] 2017-10-26 03:36
`ng serve --aot` issues fixed by #8188, deleted above comment.

**Comment by CaerusKaru** [comment] 2017-10-26 03:43
#8188 also fixes the `ng build --prod` issues for the browser build, but the server build is still busted.

**Comment by vikerman** [comment] 2017-10-26 06:55
Can reproduce the server issue with Angular rc.6 and CLI 1.5 RC.3 and universal-starter repo.

LAZY_MODULE_MAP generated inside the server bundle has reference to the Module instead of the NgModuleFactory - causing factory.create to be undefined.

**Comment by hansl** [comment] 2017-10-26 17:28
We have a separate fix for lazy modules in ng5. The problem is that making it work for ng5 seems to break ng4 so we'll do another RC with this fix whren it's ready (today hopefully)

**Comment by CaerusKaru** [comment] 2017-10-27 02:32
In case https://github.com/angular/angular-cli/commit/7a36f6ab2d8cf678d2c57e9001eeb0a1c61d3995 was designed to be the fix, it does not fix the issue.

**Comment by Toxicable** [comment] 2017-10-27 04:09
@CaerusKaru what error are you getting?
the universal-starter upgraded to the latest versions is working fine for me

**Comment by CaerusKaru** [comment] 2017-10-27 04:11
@Toxicable To be clear, this is when you import an Angular Material module into any NgModule (lazy-loaded or otherwise). You can use my sample repo as a starter. The error has not changed from the one initially posted.

**Comment by vikerman** [comment] 2017-10-27 21:36
@CaerusKaru - hey - I think we started using this bug to track the factory.create error because we started seeing that in the universal starter.

We will look into the original 'Module not Found' issue.

**Comment by hansl** [comment] 2017-10-30 22:02
Duplicate of https://github.com/angular/angular/issues/20031

**Comment by hansl** [comment] 2017-10-30 22:02
Please follow the discussion over the other issue, as this is an issue from Angular's own `ngc`, which has a fix already in flight. Thanks!

**Closed by hansl** 2017-10-30 22:02 UTC
Labels: priority: 1 (urgent), severity3: broken

**Comment by CaerusKaru** [comment] 2017-10-31 00:11
Thanks to everyone on this issue for tracking this down and getting a fix out so quickly. You all rock!
