### ISSUE TITLE
ng14 Project "undefined" does not exist.

### ISSUE THREAD

**Issue by RobertVogt** [angular/angular-cli#24566] opened 2023-01-18 18:07 UTC
### Command

generate

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

ng 12

### Description

After upgrading to ng14 Using the command ng g c some-component results in the error "Project "undefined" does not exist."
Trying to add "defaultProject": "someProject"  gives the error "value is Deprecated"

This is a vicious cycle of unproductivity?  ...I need to create all files by hand???

### Minimal Reproduction

Upgrade angular project with component library from 12 to 14
Try to generate a new component in component library

### Exception or Error

```text
Project "undefined" does not exist.
```

### Your Environment

```text
_                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.2.10
Node: 14.21.1
Package Manager: npm 6.14.17
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cdk                    13.3.9
@angular/cli                    14.2.10
@schematics/angular             14.2.10
ng-packagr                      14.3.0
rxjs                            6.6.7
typescript                      4.8.2
```

**Comment by alan-agius4** [comment] 2023-01-18 19:13
Duplicate of https://github.com/angular/angular-cli/issues/23848

**Closed by alan-agius4** 2023-01-18 19:13 UTC
