### ISSUE TITLE
ng build ---prod with "optimization: true" causes browser error.

### ISSUE THREAD

**Issue by rafaelfgx** [angular/angular-cli#10658] opened 2018-05-05 02:00 UTC
### Versions

```
Angular CLI: 6.0.0
Node: 10.0.0
OS: win32 x64
Angular: ...

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2

```
### Repro steps

1. Create new Angular 6 project with "ng new app-test" command.
2. Run "ng build ---prod" command.
3. Host the "dist" generated folder on a http server, such as "http-server" (https://www.npmjs.com/package/http-server). 
4. Open the url in Chrome.

### Observed behavior

**Error: Uncaught ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor.**

![1](https://user-images.githubusercontent.com/7357119/39658623-6d47b082-4fed-11e8-9f53-2abb49cc52e4.PNG)

If you change the **optimization** property **from true to false** in the **angular.json** file, and repeat the above steps, the application loads normally.

![image](https://user-images.githubusercontent.com/7357119/39658632-9e1f89dc-4fed-11e8-90c8-9762a1bc7de3.png)

![39658675-6402a382-4fee-11e8-8d5a-e862f4f50ccb](https://user-images.githubusercontent.com/7357119/39664085-5d0d8072-5054-11e8-881f-8e0a57b4506f.png)

### Desired behavior

The application should load correctly using **optimization: true**.

**Comment by yokots** [comment] 2018-05-05 13:13
@rafaelfgx see [here](https://github.com/angular/angular-cli/issues/7799#issuecomment-386582136)

**Comment by rafaelfgx** [comment] 2018-05-05 13:49
@yokots With **build target es2017 or esnext** the same error occurs.

**Comment by aripp** [comment] 2018-05-06 06:57
See also [here](https://github.com/angular/angular-cli/issues/10655)

**Comment by HitkoDev** [comment] 2018-05-07 12:49
Related webpack issue: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/269

**Comment by citizentim** [comment] 2018-05-07 18:17
Also seeing this issue with Angular 6.  Confirmed that setting optimization to false in angular.cli works around the problem.

**Comment by citizentim** [comment] 2018-05-07 18:45
Targeting ES5 also works around the problem for me.  I was targeting ES6 previously.

**Comment by citizentim** [comment] 2018-05-07 21:59
With the greatest respect, this is the second breaking problem with ES6 output by the CLI in as many months (there was also a build optimizer issue having to do with WebPack - see https://github.com/angular/angular-cli/issues/9495).  It would seem that ES6 is not one of the test cases when bringing the CLI to GA.  If my summation is correct, may I humbly suggest that a test case be added so that seemingly obvious issues such as this are caught prior developers to undertaking the work of upgrading?

And may I add, fine work overall; Angular's trajectory is fantastic  - it's just frustrating having to deal with ES6 output issues again.

**Comment by realmar** [comment] 2018-05-07 22:12
I have configured the `tsconfig.json` in my Angular 6 project as follow:

```json
{
 ...
    "target": "es5",
 ...
}
```

I'm experiencing this problem too, even with ES5. So this problem is not exclusive to ES6. (I mean `tsconfig.json` is the right file, correct? I dont know of any other.)

**Comment by rafaelfgx** [comment] 2018-05-08 01:00
@citizentim,

As you mentioned: "Though this has increased my main bundle size from 2M to 6.9M, so it's not a practical workaround."

I complement, with all respect:

It's a major problem something like that comes out in the final version. It appears that the build has not been tested.

**Comment by clydin** [comment] 2018-05-08 17:31
The build optimizer currently does not fully support ES2015+.  There is ongoing work to provide this support.  Current recommendation is to disable it unless using ES5.

Duplicate of angular/devkit#816

**Closed by clydin** 2018-05-08 17:31 UTC
Labels: comp: cli/build, comp: devkit/build-optimizer

**Comment by bh3605** [comment] 2018-08-31 15:26
Disabling the buildOptimizer worked for me. I'm on the latest version and also targeting es5. Having the buildOptimizer set to true is literally stripping out a portion of code from a library I'm using. This causes undefined errors to be thrown.  It's microsoft's own msal npm package and the portion that's being stripped out is their AuthorityType enum.

**Comment by sparebytes** [comment] 2018-10-03 22:50
Updating to Angular 7 rc0 fixed this for me. See [my comment on another thread](https://github.com/angular/angular-cli/issues/11129#issuecomment-426828858)

**Comment by liorwohl** [comment] 2018-11-07 11:49
After a few days of wasting time I found that my angular elements webcomponent that should work in IE11 is getting "Function Expected" error because of angular cli optimization: true. 
Without optimization i'm starting to see it kinda working.
The webcomponent went from 600kb to 2.6mb. i will try external minification for now.
I'm using Angular 7.0.2
