### ISSUE TITLE
Diferents scripts.bundle.js

### ISSUE THREAD

**Issue by ViictorG1** [angular/angular-cli#8194] opened 2017-10-26 11:04 UTC
Hi,

Know you why my new scripts.bundle.js is diferrent of my new scripts.bundle.js?

With is my project break some scripts js.

NEW SCRIPTS:
[new_scripts.208323b16203ec890d7b.bundle.zip](https://github.com/angular/angular-cli/files/1418030/new_scripts.208323b16203ec890d7b.bundle.zip)

OLD SCRIPTS:
[old_scripts.43c02bf1b0647a47d56d.bundle.zip](https://github.com/angular/angular-cli/files/1418031/old_scripts.43c02bf1b0647a47d56d.bundle.zip)

Thanks.

**Comment by filipesilva** [comment] 2017-10-26 12:14
Hi, you seem to be opening a duplicate of https://github.com/angular/angular-cli/issues/8173. It's better to keep the conversation on a single issue instead of opening several so I'll close this one.

**Closed by filipesilva** 2017-10-26 12:14 UTC

**Comment by ViictorG1** [comment] 2017-10-26 12:16
Can you answer my question there then? Please @filipesilva
