### ISSUE TITLE
ERROR in multi ./src/styles.sass

### ISSUE THREAD

**Issue by AJHanekom** [angular/angular-cli#13632] opened 2019-02-08 17:18 UTC
Angular version 7.3.0

Recreate: Creating a new project with "ng new project" and selecting scss styling.
Problem: auto generated styles file is generated with extension .sass
Solution: Fixed by correcting the extension in angular.json

OS is ubuntu - not sure if relevant.

**Comment by alan-agius4** [comment] 2019-02-08 17:19
Duplicate of https://github.com/angular/angular-cli/issues/13550

Kindly update to the latest version of the cli

**Comment by alan-agius4** [comment] 2019-02-08 17:19
Duplicate of https://github.com/angular/angular-cli/issues/13550

Kindly update to the latest version of the cli

**Closed by alan-agius4** 2019-02-08 17:19 UTC
