### ISSUE TITLE
Feature: Add option for setting indentation

### ISSUE THREAD

**Issue by Ledzz** [angular/angular-cli#2566] opened 2016-10-07 11:41 UTC
I think I'm not the only one who prefers tabs to spaces. Also I know that many people use different space count on indentation. 
I suggest adding defaults.indent option to angular-cli.json.

**Comment by fullstackdave** [comment] 2016-10-07 19:39
Curious, what would this be used for?  I am assuming you are talking about how the code is laid out; couldn't you modify that in your IDE?

**Comment by Ledzz** [comment] 2016-10-07 19:59
@fullstackdave yes, ofc I can, but I have to do this with every file file generated. I think I can automate it (I'm using Sublime Text 3), but I use it for other projects and I don't know how to do it without any problems with other files.

**Comment by filipesilva** [comment] 2016-10-10 02:25
Dupe of https://github.com/angular/angular-cli/issues/1252

**Closed by filipesilva** 2016-10-10 02:25 UTC

**Comment by Fowowski** [comment] 2017-03-24 21:26
Well, that referenced issue didn't end too good.

Quite frankly I do not understand why there is a really nice `.editorconfig` but after setting the `indent_size` to `4` from `2` and executing `ng g component mycomponent` I still have to use the inbuilt option in visual studio code to format document to be `4` spaces long for each tab as I set it in my preferences. Just why this file is there if CLI ignores it? Does it also ignores rest of it or just this one option?

This really isn't an issue for professional programmers who know their tools but from time to time you can get that amazing opportunity to have an intern on your project who will touch the codebase and I think this option could be helpful for those guys and also you're gonna have one thing less on your list of things you have to watch that guy for.

**Comment by mpragliola** [comment] 2017-04-11 13:02
+1 I really don't understand, I have to re-edit everytime the scaffolded files

**Comment by prestonvanloon** [comment] 2017-04-11 14:23
@mpragliola the blueprint files are tab space 2. There isn't a setting to change tab space, you would need a whole new blueprint with tab space 4 or run some formatter on the newly generated file with your config settings.

**Comment by froodley** [comment] 2017-04-18 20:18
Yeah, that other thread aside... I'm with everyone else who would like this feature, and it seems like if you have the value set in .editorconfig it should be honored.  Having to reformat everything the cli generates is not desirable.

@prestonvanloon what about replacing the double-spaces with an arbitrary character and then using the .editorconfig to replace that character on the way out?

**Comment by AneelaBrister** [comment] 2017-04-24 16:49
I would also like the feature to generate components etc. with tabs instead of spaces. Thank you.

**Comment by tstackhouse** [comment] 2017-05-02 17:23
:+1:

**Comment by theryansmee** [comment] 2017-05-06 16:26
Agreed. I am loving the CLI but i spend half my time converting from tabs to spaces and then 2-4 width.. To have this fixed would the polish on an otherwise super useful tool.

**Comment by kleber-swf** [comment] 2017-05-07 17:02
Since it seems that this issue will not be fixed anytime soon and since it takes some time to manually format the files every time I create a component (and I create them very often), I've made an **ugly**, not recomended workaround for this: I edited the file `npm_modules/@angular/cli/blueprints/component/files/__path__/__name__.component.ts` to have my usual formatting (with tabs).

Please note that this is a **workaround** and it's not recommended.

And please, please, let's not argue what is "best" or "right" about using tabs, spaces or their sizes. Let's just accept that each professional likes the configuration that is best for their eyes :)

**Comment by iliketomatoes** [comment] 2017-05-11 15:18
I love tabs and hate spaces, plz halp!

**Comment by filipesilva** [comment] 2017-05-12 08:47
This should be available soon-ish via automatically running TS Lint fixers on generators. This is being tracked in #6272.

**Comment by bentaly** [comment] 2017-09-29 12:43
@kleber-swf Genius
