### ISSUE TITLE
Is ng cli planing to make ng cli gui like vue-cli-gui?

### ISSUE THREAD

**Issue by iamdenny** [angular/angular-cli#11476] opened 2018-07-06 05:26 UTC
### Question

Is ng cli planing to make ng-cli-gui like vue-cli-gui ?

ref : https://github.com/egoist/vue-cli-gui

It will be awesome if it made.

**Comment by Sergged** [comment] 2018-08-12 18:13
https://marketplace.visualstudio.com/items?itemName=sasxa-net.angular-gui As I understand it is something like just vue-cli-gui, but third-person developed

**Comment by seanbotha123** [comment] 2018-08-13 07:44
https://angularconsole.com

**Comment by alan-agius4** [comment] 2019-01-21 09:56
Duplicate of https://github.com/angular/angular-cli/issues/10342

**Comment by alan-agius4** [comment] 2019-01-21 09:57
Closing as this is out side of the scope of the CLI and at the moment there is https://angularconsole.com which can be used.

**Closed by alan-agius4** 2019-01-21 09:57 UTC
Labels: comp: angular/cli, type: RFC / discussion / question
