### ISSUE TITLE
Dev server crashing with &:host in scss

### ISSUE THREAD

**Issue by zip-fa** [angular/angular-cli#25386] opened 2023-06-15 20:15 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Accidentally added & before :host could lead to devserver crash

### Minimal Reproduction

These styles crashed my dev-server:

```
&:host {
  position: relative;
  display: block;
}
```

### Exception or Error

```text
node:internal/event_target:1037
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: Cannot read properties of undefined (reading 'column')
    at convertSourceSpan (/Users/name/Documents/project/node_modules/@angular-devkit/build-angular/src/sass/worker.js:146:30)
    at MessagePort.<anonymous> (/Users/name/Documents/project/node_modules/@angular-devkit/build-angular/src/sass/worker.js:111:27)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:762:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:762:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v20.3.0
```

### Your Environment

```text
Angular CLI: 16.0.1
Node: 20.3.0 (Unsupported)
Package Manager: npm 9.6.7
OS: darwin arm64

Angular: 16.1.0
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@angular/cdk                    16.0.1
@angular/cli                    16.0.1
@angular/material               16.0.1
@nguniversal/builders           16.0.1
@nguniversal/express-engine     16.0.1
@schematics/angular             16.0.1
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by clydin** [comment] 2023-06-15 20:34
Duplicate of #25134

**Closed by clydin** 2023-06-15 20:34 UTC
