### ISSUE TITLE
ERROR EVERYWHERE ng new

### ISSUE THREAD

**Issue by mrhili** [angular/angular-cli#17743] opened 2020-05-16 10:03 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x ] new

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
I trying doing ng new and everytime i get the error
 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre>
λ ng new randomImages
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE randomImages/angular.json (3614 bytes)
CREATE randomImages/package.json (1246 bytes)
CREATE randomImages/README.md (1029 bytes)
CREATE randomImages/tsconfig.json (489 bytes)
CREATE randomImages/tslint.json (3125 bytes)
CREATE randomImages/.editorconfig (274 bytes)
CREATE randomImages/.gitignore (631 bytes)
CREATE randomImages/browserslist (429 bytes)
CREATE randomImages/karma.conf.js (1024 bytes)
CREATE randomImages/tsconfig.app.json (210 bytes)
CREATE randomImages/tsconfig.spec.json (270 bytes)
CREATE randomImages/src/favicon.ico (948 bytes)
CREATE randomImages/src/index.html (298 bytes)
CREATE randomImages/src/main.ts (372 bytes)
CREATE randomImages/src/polyfills.ts (2835 bytes)
CREATE randomImages/src/styles.css (80 bytes)
CREATE randomImages/src/test.ts (753 bytes)
CREATE randomImages/src/assets/.gitkeep (0 bytes)
CREATE randomImages/src/environments/environment.prod.ts (51 bytes)
CREATE randomImages/src/environments/environment.ts (662 bytes)
CREATE randomImages/src/app/app-routing.module.ts (246 bytes)
CREATE randomImages/src/app/app.module.ts (393 bytes)
CREATE randomImages/src/app/app.component.html (25757 bytes)
CREATE randomImages/src/app/app.component.spec.ts (1077 bytes)
CREATE randomImages/src/app/app.component.ts (216 bytes)
CREATE randomImages/src/app/app.component.css (0 bytes)
CREATE randomImages/e2e/protractor.conf.js (808 bytes)
CREATE randomImages/e2e/tsconfig.json (214 bytes)
CREATE randomImages/e2e/src/app.e2e-spec.ts (645 bytes)
CREATE randomImages/e2e/src/app.po.ts (301 bytes)
\ Installing packages...npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! Unexpected end of JSON input while parsing near '...WI0qTv/oBjQDzDUC4m23T'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-05-16T09_57_13_611Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See abov

<code>

</code></pre>

## 🌍 Your Environment
<pre>

<code>

λ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.6
Node: 14.2.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.6
@angular-devkit/core         9.1.6
@angular-devkit/schematics   9.1.6
@schematics/angular          9.1.6
@schematics/update           0.901.6
rxjs                         6.5.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-05-16 11:57
The above error generally signifies that the NPM got corrupted.

Try to clean the cache by using `npm cache clean --force`

Closing as this is not caused by the Angular CLI.

**Closed by alan-agius4** 2020-05-16 11:57 UTC
