### ISSUE TITLE
ng serve - relative path in url css data type is interpreted wrong

### ISSUE THREAD

**Issue by Kai-Dominik** [angular/angular-cli#5291] opened 2017-03-08 09:29 UTC
### OS?
Windows 10

### Versions.
@angular/cli: 1.0.0-rc.1
node: 6.10.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

### Repro steps.
- Create a new angular 2 app with the cli.
- Put an image or a svg in the folder src/assets/images/.
- Create an element in app.component.html and set in the app.component.css the image as an background image like `background:url("assets/images/sample.svg")`.
- Serve the app via ng serve

### The log given by the failure.
ERROR in ./src/app/app.component.css
Module not found: Error: Can't resolve './assets/images/sample.svg' in 'D:\test\TestApp\src\app'
 @ ./src/app/app.component.css 6:67-111
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

### Mention any other details that might be useful.
Steps I tried already.
- I changed the path to `url("./assets/images/sample.svg")` which didn't change anything.
- I changed the path to `url("/assets/images/sample.svg")` and I could serve the app without problem but when building (ng build) and opening the index.html, than I see the following error in the browser console: file:///D:/assets/images/sample.svg.

### Expectation
My expectations is that `url("assets/images/sample.svg")` is the correct way to reference the file and that ng serve should search the file relative to the index.html instead of relative to the path from the css file.

**Comment by filipesilva** [comment] 2017-03-17 22:50
Dupe of https://github.com/angular/angular-cli/issues/4778. Please see that issue for the difference between absolute and relative urls.

**Closed by filipesilva** 2017-03-17 22:50 UTC
