### ISSUE TITLE
Unable to remove files created by chained rule

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12122] opened 2018-09-04 23:19 UTC
_From @maciejtreder on April 17, 2018 20:31_

### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x ] devkit
- [ ] schematics
```

### Versions

node v8.11.1
npm 5.6.0
angular-devkit/core: 0.5.6

### Repro steps
```
import {
    Rule, chain
} from '@angular-devkit/schematics';

export default function (options: any): Rule {
    if (!options.directory) {
        options.directory = options.name;
    }

    return chain([
        createFile(options),
        removeFile(options)
    ]);
}
function createFile(options: any): Rule {
    return (tree => {
        tree.create(`${options.directory}/someFile`, 'someContent');
    });
}

function removeFile(options: any):Rule {
    return (tree => {
        console.log(tree.exists(`${options.directory}/someFile`));
        tree.delete(`${options.directory}/someFile`);
    });
}

```

### The log given by the failure

true
ERROR! myApp/someFile does not exist..

### Desired functionality

Should remove a file from the tree

_Copied from original issue: angular/devkit#726_

**Comment by alan-agius4** [comment] 2018-09-05 05:38
Duplicate of 
https://github.com/angular/angular-cli/issues/11460

**Closed by alan-agius4** 2018-09-05 05:38 UTC
