### ISSUE TITLE
The CLI complains about unresolved dependency to typescript

### ISSUE THREAD

**Issue by notbear** [angular/angular-cli#22342] opened 2021-12-10 10:07 UTC
# 🐞 Bug report

### Command

- [X] new

### Is this a regression?

Yes, the previous version in which this bug was not present was: 12.x

### Description

The CLI complains about unresolved dependency to typescript

## 🔬 Minimal Reproduction

- try command `ng new test-angular-13`
- include routing: yes
- styles: SCSS
- observe the output (example below)

## 🔥 Exception or Error

<pre><code>
❯ ng new test-angular-13
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/
documentation/syntax#scss                ]
CREATE test-angular-13/README.md (1059 bytes)
CREATE test-angular-13/.editorconfig (274 bytes)
CREATE test-angular-13/.gitignore (620 bytes)
CREATE test-angular-13/angular.json (3261 bytes)
CREATE test-angular-13/package.json (1079 bytes)
CREATE test-angular-13/tsconfig.json (863 bytes)
CREATE test-angular-13/.browserslistrc (600 bytes)
CREATE test-angular-13/karma.conf.js (1432 bytes)
CREATE test-angular-13/tsconfig.app.json (287 bytes)
CREATE test-angular-13/tsconfig.spec.json (333 bytes)
CREATE test-angular-13/.vscode/extensions.json (130 bytes)
CREATE test-angular-13/.vscode/launch.json (474 bytes)
CREATE test-angular-13/.vscode/tasks.json (938 bytes)
CREATE test-angular-13/src/favicon.ico (948 bytes)
CREATE test-angular-13/src/index.html (299 bytes)
CREATE test-angular-13/src/main.ts (372 bytes)
CREATE test-angular-13/src/polyfills.ts (2338 bytes)
CREATE test-angular-13/src/styles.scss (80 bytes)
CREATE test-angular-13/src/test.ts (745 bytes)
CREATE test-angular-13/src/assets/.gitkeep (0 bytes)
CREATE test-angular-13/src/environments/environment.prod.ts (51 bytes)
CREATE test-angular-13/src/environments/environment.ts (658 bytes)
CREATE test-angular-13/src/app/app-routing.module.ts (245 bytes)
CREATE test-angular-13/src/app/app.module.ts (393 bytes)
CREATE test-angular-13/src/app/app.component.scss (0 bytes)
CREATE test-angular-13/src/app/app.component.html (23364 bytes)
CREATE test-angular-13/src/app/app.component.spec.ts (1100 bytes)
CREATE test-angular-13/src/app/app.component.ts (220 bytes)
⠧ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test-angular-13@0.0.0
npm ERR! Found: typescript@4.5.3
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"~4.5.2" from the root project
npm ERR!   peer typescript@">=4.4.3 <4.6" from @angular-devkit/build-angular@13.1.0
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~13.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@">=4.4.2 <4.5" from @angular/compiler-cli@13.0.3
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"~13.0.0" from the root project
npm ERR!   peer @angular/compiler-cli@"^13.0.0 || ^13.1.0-next" from @angular-devkit/build-angular@13.1.0
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~13.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/harry/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/harry/.npm/_logs/2021-12-10T10_00_29_427Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.1.0
Node: 16.13.0
Package Manager: npm 8.1.0
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.0 (cli-only)
@angular-devkit/core         13.1.0 (cli-only)
@angular-devkit/schematics   13.1.0 (cli-only)
@schematics/angular          13.1.0 (cli-only)
    

</code></pre>

**Comment by alan-agius4** [comment] 2021-12-10 10:12
Duplicate of https://github.com/angular/angular-cli/issues/22333

**Closed by alan-agius4** 2021-12-10 10:12 UTC
