### ISSUE TITLE
ng build consumes all memory & swap

### ISSUE THREAD

**Issue by nsoft** [angular/angular-cli#16454] opened 2019-12-15 17:35 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Unknown
### Description

 
From time to time (maybe one in 8-10 times) the build seems to run away consuming memory infinitely and crashing my machine if I don't catch it and kill it quick enough. Below is a screen shot of system monitor for one such event (where I did catch it in time)
![image](https://user-images.githubusercontent.com/3340874/70866051-aed14e80-1f32-11ea-96ef-9a9bb6f8e760.png)
The build I am running is a slightly modified version of the output from `ng new`

## 🔬 Minimal Reproduction

1. Open System Monitor, to resources page, and be ready to kill what you are about to start.
1. clone git@github.com:nsoft/ns-login.git
1. checkout revision 198c3f677d77652f59c6e7b08e4ef1dcf273436d
1. cd into the /admin directory
1. run `ng build` several times (or `./gradlew build` which in turn runs ng build)

I have seen this occur with `ng build` run on the command line, run via gradle, or run via intellij invoking gradle when deploying to tomcat. About 50% of the time when this happens the build fails after locking up the computer for a couple minutes. I suspect this the OS killing it (but haven't tried to verify. This survival seems more likely if the machine was not running low on memory to start with.

## 🔥 Exception or Error
<pre><code>
No Error, just an unresponsive computer that remains unresponsive >30 min, 
with all memory and swap consumed.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.20
Node: 11.8.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.20
@angular-devkit/core         8.3.20
@angular-devkit/schematics   8.3.20
@schematics/angular          8.3.20
@schematics/update           0.803.20
rxjs                         6.4.0

</code></pre>

**Anything else relevant?**

No browser involved

I am developing on Ubuntu 18.0.4. The above specified revision represents a very slightly modified version of the output from `ng new` I am quite new to Angular, and so My normal assumption would be that I've messed something up, and I'd hesitate to file a report, but _intermittent_ run-away memory like this has to be a bug, even if it resulted from some thing I did... 

I searched, but the bugs I find talk about out of memory errors, and that's not my case.

Another interesting bit is that the process list in System Monitor will NOT show any  process consuming a corresponding hunk of memory, so you can't find and kill it that way.

**Comment by nsoft** [comment] 2019-12-15 23:23
This appears to be related to something you provide in your demo components that are generated by `ng new`.  The problem goes away once the placeholder stuff is removed. Yet this is a really ugly failure mode.

**Comment by clydin** [comment] 2019-12-16 00:58
This is most likely due to the use of Node.js 11.  This version has reached its end of life and is no longer supported.  Please consider updating to a supported version.  Version 12 is recommended for optimal performance (currently 12.13.1).  Please see https://nodejs.org for more information.

**Comment by alan-agius4** [comment] 2020-01-08 17:58
@nsoft, have you tried Node 12?

**Comment by nsoft** [comment] 2020-01-08 20:38
Sorry not yet. haven't yet rolled back to this project, which was not paid work... $$ first unfortunately. Definately plan to get back to it.

**Comment by alan-agius4** [comment] 2020-02-25 10:44
Closing as no further communication was provided by the issue creator. 

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2020-02-25 10:44 UTC
Labels: need: more info
