### ISSUE TITLE
ERROR Cannot find module 'crypto'

### ISSUE THREAD

**Issue by DaniyalAlam09** [angular/angular-cli#26050] opened 2023-10-17 15:12 UTC
### Command

new

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Cannot find module 'crypto'
webpackMissingModule@http://localhost:3000/static/js/bundle.js:13826:85
./node_modules/pusher/lib/pusher.js@http://localhost:3000/static/js/bundle.js:13826:166
options.factory@http://localhost:3000/static/js/bundle.js:56544:31
__webpack_require__@http://localhost:3000/static/js/bundle.js:55967:33
fn@http://localhost:3000/static/js/bundle.js:56201:21
./src/server.js@http://localhost:3000/static/js/bundle.js:475:35

### Minimal Reproduction

Module not found: Error: Can't resolve 'url' in 'D:\web-editor\node_modules\pusher\lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
        - install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "url": false }

### Exception or Error

```text
no error should be run smoothly
```

### Your Environment

```text
'ng' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by alan-agius4** [comment] 2023-10-17 15:18
Duplicate of https://github.com/angular/angular-cli/issues/25509

**Closed by alan-agius4** 2023-10-17 15:18 UTC
