### ISSUE TITLE
problem in creating new app

### ISSUE THREAD

**Issue by Asisakdesign** [angular/angular-cli#737] opened 2016-05-12 12:04 UTC
**OS: windows 8.1**

**Versions:**
(node:3976) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 0.1.0
node: 6.1.0
os: win32 x64

**Step with Error code**
 **_ng new my-dream-app_**
(node:3428) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Cannot find module 'config-chain'
Error: Cannot find module 'config-chain'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\work\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\lib\config\core.js:2:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by spboyer** [comment] 2016-05-12 13:33
Appears to be a node 6.x issue

**Comment by neilhem** [comment] 2016-05-12 17:55
Try to update global version of angular-cli to the latest version `npm install --global angular-cli`, then run `ng new my-dream-app` command again.

**Comment by mdocter** [comment] 2016-05-12 21:08
Installed the CLI today. Version output is:
```
angular-cli: 1.0.0-beta.1
node: 4.4.3
os: win32 x64
```
But during the first `npm install` after a `ng new ...` I also see npm warnings:
```
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```
So this is probably caused by an older version of the `graceful-fs` module. Can it be updated to version 4 or higher?

**Comment by neilhem** [comment] 2016-05-13 04:27
This is just warn, do you successfully installed dependencies?

**Comment by mdocter** [comment] 2016-05-13 07:55
Yep, it successfully installed the following versions:
```
lodash-node@2.4.1
graceful-fs@4.1.4
```
So the warning mentions graceful-fs@3.0.0, but eventually v4.1.4 is installed... weird.

Note: I don't have the error mentioned by @Asisakdesign and I'm running on Windows, so no sudo there, but I run the Git Bash as Administrator as advised in the CLI docs.

**Comment by neilhem** [comment] 2016-05-13 14:02
@mdocter seems like graceful-fs is dependency of another sub modules, so just installing latest version of graceful-fs doesn't mean every package will start using it

**Comment by mdocter** [comment] 2016-05-13 14:42
I didn't do an explicit install of this newer version. The normal initial `npm install` selected it, which is fine by me.

**Comment by hansl** [comment] 2016-05-13 18:53
These are transitive dependencies that we have no control over. Closing this, we might revisit all our dependencies in the future.

**Closed by hansl** 2016-05-13 18:53 UTC
