### ISSUE TITLE
Angular CLI is not recognized

### ISSUE THREAD

**Issue by segalxandr** [angular/angular-cli#9421] opened 2018-01-29 14:26 UTC
"No matches found" .

### Versions
WebStorm-181.3007.17 EPA 
Angular CLI: 1.6.6
Node: 9.4.0
OS: win32 x64
Angular: 5.2.2
### Repro steps

* Step 1 Create new Angular CLI project
* Step 2 File | New | Angular CLI
* Step 3 "No matches found" displayed

**Comment by manojvignesh** [comment] 2018-01-29 16:38
Facing the same problem with
Angular CLI: 1.6.6
Angular: 5.0.0

IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Build #IU-173.4301.25, built on January 15, 2018

### Repro steps
* Alt + Insert
* Angular Cli
* No match found

**Comment by 2beers** [comment] 2018-01-29 18:50
Same here. Either something changed in CLI and webstorm needs to release an update or there is a bug in CLI.

**Comment by manojvignesh** [comment] 2018-01-30 02:51
It's already reported to Jetbrains [#WEB-30866](https://youtrack.jetbrains.com/issue/WEB-30866) which points to the CLI issue #9412 . They'll be pushing a workaround soon it seems.

**Comment by filipesilva** [comment] 2018-01-30 09:11
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/9412. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2018-01-30 09:11 UTC
