### ISSUE TITLE
There is no dependencies(@angular/animations) when I use ng new ****

### ISSUE THREAD

**Issue by trueVitality** [angular/angular-cli#5782] opened 2017-03-31 14:55 UTC
There is no dependencies(@angular/animations) when I use ng new ****

Fix that guys.

thx

**Comment by sumitarora** [comment] 2017-03-31 14:58
@trueVitality You can always add it to `package.json` if you need it.

**Comment by dave11mj** [comment] 2017-03-31 17:21
This might be related to a feature request I had a in mind https://github.com/angular/angular-cli/pull/5786

**Comment by filipesilva** [comment] 2017-05-04 13:30
Marking as as dupe of https://github.com/angular/angular-cli/issues/5785, there's more information there.

**Closed by filipesilva** 2017-05-04 13:30 UTC
