### ISSUE TITLE
Allow the merging of configurations for array properties

### ISSUE THREAD

**Issue by bridzius** [angular/angular-cli#25430] opened 2023-06-23 10:37 UTC
### Command

build

### Description

Currently, array configurations, like `assets: []`, `scripts: []`, `styles: []`, etc from base configuration are overriden when also defined in a separate configuration.
```json
"architect": {
  "build": {
    "builder": "@angular-devkit/build-angular:browser",
    "options": {
      <...properties>
      "assets": [
        "src/favicon.ico",
        "src/assets"
      ]
    },
    "configurations": {
      "production": {
        "assets": ["src/folder"], 
        "budgets": [
```
In this case, `npx ng build --configuration production` would override the assets from the base options and we would end up with 
```json
{
  "assets": [
    "src/folder"
  ]
}
```

Repro: https://github.com/bridzius/asset-override-repro 

### Describe the solution you'd like

I would prefer an option, where array properties would be merged, instead of overriden. This would mean that `npx ng build --configuration production` would end up with 
```json
{
  "assets": [
    "src/favicon.ico",
    "src/assets",
    "src/folder"
  ]
}
```

### Describe alternatives you've considered

I tried configuration merging (https://angular.io/guide/workspace-config#alternate-build-configurations), but it still only overrides, instead of merge.

**Comment by alan-agius4** [comment] 2023-06-23 13:28
Duplicate of https://github.com/angular/angular-cli/issues/11149

**Closed by alan-agius4** 2023-06-23 13:28 UTC
