### ISSUE TITLE
Wrong label when running command outside of angular-cli project directory

### ISSUE THREAD

**Issue by alerat** [angular/angular-cli#3882] opened 2017-01-06 15:49 UTC
### OS?
> Windows 7

### Versions.
> 1.0.0-beta.24:

### Repro steps.
> run ng serve outside of angular-cli project directory

### The log given by the failure.
> You have to be inside an `ember-cli` project in order to use the serve command

### Mention any other details that might be useful.

Replace ember-cli by angular-cli

**Comment by beeman** [comment] 2017-01-08 06:19
Duplicate of https://github.com/angular/angular-cli/issues/3675 https://github.com/angular/angular-cli/issues/3697 , fixed in #3688

**Closed** 2017-01-08 06:37 UTC
