### ISSUE TITLE
An unhandled exception occurred: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rkusuma** [angular/angular-cli#16225] opened 2019-11-19 07:28 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.3.9

### Description

I have typescript class with thousands of static property, when running `ng build --prod` it will throw an Error `An unhandled exception occurred: Maximum call stack size exceeded`.

- update `target` in `tsconfig.json` to `"target": "es5"` -> build success
- update `buildOptimizer` in `angular.json` to `"buildOptimizer": false` -> build success

How to make the build succeed when using `"buildOptimizer": true` and `"target": "es2015"`?

## 🔬 Minimal Reproduction

- Clone [https://github.com/rkusuma/angular-cli839-sample](https://github.com/rkusuma/angular-cli839-sample)
- run `ng build --prod`

## 🔥 Exception or Error
<pre><code>An unhandled exception occurred: Maximum call stack size exceeded
See "/private/var/folders/g6/yq3yptmn6w5fr_9k3f_db5fr0000gp/T/ng-ZIr3Yd/angular-errors.log" for further details.</code></pre>

inside `angular-errors.log`
<pre><code>
[error] RangeError: Maximum call stack size exceeded
    at checkExpressionWorker (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53913:39)
    at checkExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53878:38)
    at checkBinaryLikeExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53241:28)
    at checkBinaryExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53229:20)
    at checkExpressionWorker (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53986:28)
    at checkExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53878:38)
    at checkBinaryLikeExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53241:28)
    at checkBinaryExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53229:20)
    at checkExpressionWorker (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53986:28)
    at checkExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53878:38)
    at checkBinaryLikeExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53241:28)
    at checkBinaryExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53229:20)
    at checkExpressionWorker (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53986:28)
    at checkExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53878:38)
    at checkBinaryLikeExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53241:28)
    at checkBinaryExpression (/Users/xxx/GitHub/angular-cli839-sample/node_modules/typescript/lib/typescript.js:53229:20)</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.19
Node: 10.16.3
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cli                      8.3.19
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

**Comment by filipesilva** [comment] 2019-11-19 12:24
Yeah this is definitely related with processing https://github.com/rkusuma/angular-cli839-sample/blob/master/src/app/label.constant.ts. We can probably do it in a less stack-intensive way. Thanks for the great report btw!

**Comment by alan-agius4** [comment] 2019-11-19 13:41
This should be fixed with Angular CLI 9 and TypeScript 3.6.

**Comment by alan-agius4** [comment] 2019-11-19 14:14
This should be fixed with Angular CLI 9 and TypeScript 3.6. 

The issue is caused because in version 8, in some cases we used TSC to downlevel the code instead of Babel. However this was fixed in version 9 as we moved completely to Babel.

As a workaround in version 8 you can opt to use the full differential loading feature using;

```cmd
NG_BUILD_DIFFERENTIAL_FULL=true ng build --prod
```

**Comment by filipesilva** [comment] 2019-11-19 17:21
Closing as there seems to be a fix merged already.

**Closed by filipesilva** 2019-11-19 17:21 UTC
Labels: comp: devkit/build-angular, freq1: low, severity5: regression, type: bug/fix

**Comment by rkusuma** [comment] 2019-11-19 17:49
@filipesilva @alan-agius4 thanks for the reply!

So in v8 the current workaround is using NG_BUILD_DIFFERENTIAL_FULL=true?
