### ISSUE TITLE
Feature Request: Add the ability to add filter to ng test so that single spec files can be tested

### ISSUE THREAD

**Issue by PG2000** [angular/angular-cli#3469] opened 2016-12-08 14:01 UTC
### OS?
> Ubutnu 16.04

### Mention any other details that might be useful.

Very often it would be useful to test a single .spec file or to provide a wildcard
I think a line like this would be very nice:

ng test --filter=some-filter*

**Comment by mattdistefano** [comment] 2016-12-08 16:59
Actually requested this very thing a couple days ago in #3436. Should probably consolidate there.

**Comment by PG2000** [comment] 2016-12-08 17:04
Ah perfect...

**Comment by hansl** [comment] 2016-12-08 20:38
Dupe of #3436

**Closed** 2016-12-08 20:38 UTC
