### ISSUE TITLE
After ng new (no ssr) ng serve wont compile

### ISSUE THREAD

**Issue by brettaio** [angular/angular-cli#26431] opened 2023-11-20 17:34 UTC
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

All of em

### Description

ng serve
- Building...X [ERROR] File 'src\main.ts' is missing from the TypeScript compilation. [plugin angular-compiler]

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.

Application bundle generation failed. [5.327 seconds]
Watch mode enabled. Watching for file changes...

### Minimal Reproduction

Using NVM 1.1.11 on windows 11,  node v20.9.0 and npm 10.1.0.

Ran 'ng new app-name'

Application was generated, 

Ran 'ng serve' 

Issue listed below  

### Exception or Error

```text
ng serve
- Building...X [ERROR] File 'src\main.ts' is missing from the TypeScript compilation. [plugin angular-compiler]

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.


Application bundle generation failed. [5.327 seconds]
Watch mode enabled. Watching for file changes...
```

### Your Environment

```text
Angular CLI: 17.0.1
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.1
@angular-devkit/build-angular   17.0.1
@angular-devkit/core            17.0.1
@angular-devkit/schematics      17.0.1
@angular/cli                    17.0.1
@schematics/angular             17.0.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

I got this to work thanks to ai telling me to "include": ["src/**/*.ts"] to compiler options, but I want to be able to run ng new on a project and serve the starter app, which isn't happening - also the case when generating a new SSR project, out of the box.

**Comment by brettaio** [comment] 2023-11-20 17:39
I noticed npm -g list @angular/cli is 17.0.1 and @angular/core is 17.0.3 so I am going to make sure -g @angular/core is 17.0.1 and try again

**Comment by alan-agius4** [comment] 2023-11-20 18:09
Duplicate of https://github.com/angular/angular-cli/issues/26379

**Closed by alan-agius4** 2023-11-20 18:09 UTC
