### ISSUE TITLE
While creating a new project I am getting this issue, with npm version-7.12.1, node version-v14.17.0

### ISSUE THREAD

**Issue by Siba-07** [angular/angular-cli#20746] opened 2021-05-12 17:19 UTC
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: selector@0.0.0
npm ERR! Found: jasmine-core@3.6.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/sibasis/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sibasis/.npm/_logs/2021-05-12T17_16_19_050Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

===========================================================================================
LOG FILE
===========================================================================================
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install', '--quiet' ]
1 info using npm@7.12.1
2 info using node@v14.17.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/sibasis/Desktop/AdAI/autogen/auto-sel/selector/.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/sibasis/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 14ms
19 timing npm:load:configload Completed in 14ms
20 timing npm:load:setTitle Completed in 36ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 56ms
26 timing config:load:flatten Completed in 3ms
27 timing arborist:ctor Completed in 2ms
28 timing arborist:ctor Completed in 0ms
29 timing idealTree:init Completed in 24ms
30 timing idealTree:userRequests Completed in 0ms
31 silly idealTree buildDeps
32 silly fetch manifest @angular/animations@~11.2.13
33 http fetch GET 200 https://registry.npmjs.org/@angular%2fanimations 3434ms
34 silly fetch manifest @angular/core@~11.2.13
35 http fetch GET 200 https://registry.npmjs.org/@angular%2fcore 1699ms
36 silly fetch manifest rxjs@~6.6.0
37 http fetch GET 304 https://registry.npmjs.org/rxjs 259ms (from cache)
38 silly fetch manifest zone.js@~0.11.3
39 http fetch GET 200 https://registry.npmjs.org/zone.js 458ms
40 silly fetch manifest @angular/common@~11.2.13
41 http fetch GET 200 https://registry.npmjs.org/@angular%2fcommon 2119ms
42 silly fetch manifest @angular/compiler@~11.2.13
43 http fetch GET 200 https://registry.npmjs.org/@angular%2fcompiler 1782ms
44 silly fetch manifest @angular/forms@~11.2.13
45 http fetch GET 200 https://registry.npmjs.org/@angular%2fforms 2466ms
46 silly fetch manifest @angular/platform-browser@~11.2.13
47 http fetch GET 200 https://registry.npmjs.org/@angular%2fplatform-browser 2641ms
48 silly fetch manifest @angular/platform-browser-dynamic@~11.2.13
49 http fetch GET 200 https://registry.npmjs.org/@angular%2fplatform-browser-dynamic 2771ms
50 silly fetch manifest @angular/router@~11.2.13
51 http fetch GET 200 https://registry.npmjs.org/@angular%2frouter 1709ms
52 silly fetch manifest tslib@^2.0.0
53 http fetch GET 304 https://registry.npmjs.org/tslib 385ms (from cache)
54 silly fetch manifest @angular-devkit/build-angular@~0.1102.12
55 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fbuild-angular 241975ms
56 silly fetch manifest @angular/compiler-cli@~11.2.13
57 http fetch GET 200 https://registry.npmjs.org/@angular%2fcompiler-cli 4141ms
58 silly fetch manifest typescript@~4.1.5
59 http fetch GET 200 https://registry.npmjs.org/typescript 20862ms
60 silly fetch manifest @angular/localize@^11.0.0 || ^11.2.0-next
61 http fetch GET 200 https://registry.npmjs.org/@angular%2flocalize 2496ms
62 silly fetch manifest @angular/service-worker@^11.0.0 || ^11.2.0-next
63 http fetch GET 200 https://registry.npmjs.org/@angular%2fservice-worker 3296ms
64 silly fetch manifest karma@~6.1.0
65 http fetch GET 200 https://registry.npmjs.org/karma 2249ms
66 silly fetch manifest ng-packagr@^11.0.0 || ^11.2.0-next
67 http fetch GET 200 https://registry.npmjs.org/ng-packagr 1639ms
68 silly fetch manifest protractor@~7.0.0
69 http fetch GET 200 https://registry.npmjs.org/protractor 580ms
70 silly fetch manifest tailwindcss@^2.0.0
71 http fetch GET 200 https://registry.npmjs.org/tailwindcss 1524ms
72 silly fetch manifest autoprefixer@^10.0.2
73 http fetch GET 200 https://registry.npmjs.org/autoprefixer 1127ms
74 silly fetch manifest postcss@^8.1.0
75 http fetch GET 200 https://registry.npmjs.org/postcss 1100ms
76 silly fetch manifest tslint@~6.1.0
77 http fetch GET 200 https://registry.npmjs.org/tslint 1255ms
78 silly fetch manifest @angular/cli@~11.2.12
79 http fetch GET 304 https://registry.npmjs.org/@angular%2fcli 279ms (from cache)
80 silly fetch manifest @types/jasmine@~3.6.0
81 http fetch GET 200 https://registry.npmjs.org/@types%2fjasmine 547ms
82 silly fetch manifest @types/node@^12.11.1
83 http fetch GET 200 https://registry.npmjs.org/@types%2fnode 5195ms
84 silly fetch manifest codelyzer@^6.0.0
85 http fetch GET 200 https://registry.npmjs.org/codelyzer 488ms
86 silly fetch manifest jasmine-core@~3.6.0
87 http fetch GET 200 https://registry.npmjs.org/jasmine-core 392ms
88 silly fetch manifest jasmine-spec-reporter@~5.0.0
89 http fetch GET 200 https://registry.npmjs.org/jasmine-spec-reporter 373ms
90 silly fetch manifest karma-chrome-launcher@~3.1.0
91 http fetch GET 200 https://registry.npmjs.org/karma-chrome-launcher 341ms
92 silly fetch manifest karma-coverage@~2.0.3
93 http fetch GET 200 https://registry.npmjs.org/karma-coverage 380ms
94 silly fetch manifest karma-jasmine@~4.0.0
95 http fetch GET 200 https://registry.npmjs.org/karma-jasmine 330ms
96 silly fetch manifest karma-jasmine-html-reporter@^1.5.0
97 http fetch GET 200 https://registry.npmjs.org/karma-jasmine-html-reporter 306ms
98 silly fetch manifest jasmine-core@>=3.7.1
99 timing idealTree Completed in 311020ms
100 timing command:install Completed in 311027ms
101 verbose stack Error: unable to resolve dependency tree
101 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1222:25)
101 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1189:34)
101 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:893:11)
101 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
101 verbose stack     at async Promise.all (index 1)
101 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:135:5)
101 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:137:5)
102 verbose cwd /Users/sibasis/Desktop/AdAI/autogen/auto-sel/selector
103 verbose Darwin 20.2.0
104 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--quiet"
105 verbose node v14.17.0
106 verbose npm  v7.12.1
107 error code ERESOLVE
108 error ERESOLVE unable to resolve dependency tree
109 error
110 error While resolving: selector@0.0.0
110 error Found: jasmine-core@3.6.0
110 error node_modules/jasmine-core
110 error   dev jasmine-core@"~3.6.0" from the root project
110 error
110 error Could not resolve dependency:
110 error peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
110 error node_modules/karma-jasmine-html-reporter
110 error   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
110 error
110 error Fix the upstream dependency conflict, or retry
110 error this command with --force, or --legacy-peer-deps
110 error to accept an incorrect (and potentially broken) dependency resolution.
110 error
110 error See /Users/sibasis/.npm/eresolve-report.txt for a full report.
111 verbose exit 1

**Comment by alan-agius4** [comment] 2021-05-12 17:31
Duplicate of #20719, #20736 and #20718

**Closed by alan-agius4** 2021-05-12 17:31 UTC
