### ISSUE TITLE
Relative url('..') in scss files cannot be resolved

### ISSUE THREAD

**Issue by httpdigest** [angular/angular-cli#5752] opened 2017-03-30 09:25 UTC
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Output from: `ng --version`:
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 7.8.0
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
```

### Repro steps.
* `ng new url-test`
* `cd url-test`
* in .angular-cli.json change the "styles.css" to "styles.scss" and change the defaults/styleExt from "css" to "scss"
* rename src/styles.css to src/styles.scss
* add the two new folders: `src/theme/images` and `src/theme/styles`
* add a new file `src/theme/styles/mystyle.scss` with the content: `body { background: url('../images/background.png'); }`
* add a new file `src/theme/images/background.png` being any PNG image
* add the following to src/styles.scss: `@import './theme/styles/mystyle.scss';`
* run `ng build`
* observe that the output is:

### The log given by the failure.
```
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module not found: Error: Can't resolve '../images/background.png' in 'some/absolute/path/to/ng4-test/src'
 @ ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:56-91
 @ ./src/styles.scss
 @ multi ./src/styles.scss
```

### Desired functionality.
What would [you] like to see implemented?

Currently, the behaviour when specifically using SCSS is different from using CSS. When using CSS (styles.css and mystyle.css) then everything works and the background.png image is found.
This should be the same when using SCSS.

What is the usecase?
Using SCSS instead of CSS for more expressiveness in an obviously more complex application than the one provided here.

**Comment by httpdigest** [comment] 2017-03-30 09:28
I would like to make it very clear, that when explicitly using CSS (instead of SCSS) by doing the following:
* in .angular-cli.json: leave the "styles.css" as proposed by `ng new` and also leave the defaults/styleExt to "css"
* leave the styles.css as styles.css (and not styles.scss as mentioned above)
* add the mystyle as mystyle.css (and not mystyle.scss as mentioned above)
* include the mystyle.css as `@import './theme/styles/mystyle.css';`

**Comment by xuchao1** [comment] 2017-03-30 09:40
you may have an error in your scss file.
`Error: Can't resolve '../images/background.png' in '..../ng4-test/src'`
check your file path again？

**Comment by httpdigest** [comment] 2017-03-30 09:41
No, that was just to mask off the actual file system path. Please take the paths as layed out in the "Repro steps." section. They are very exact and very explicitly these paths written there.

**Comment by demirk4n** [comment] 2017-03-30 11:27
@httpdigest Could you please push the relevant parts of your code to a repo and share?

**Comment by httpdigest** [comment] 2017-03-30 11:35
@demirk4n please see the exhaustive and complete "Repro steps." steps in the initial post. It contains every necessary step to reproduce the case and takes only half a minute to setup.

**Comment by httpdigest** [comment] 2017-03-30 13:49
Looks like the section [Problems with url(...)](https://github.com/webpack-contrib/sass-loader#problems-with-url) in the sass-loader README.md describes this exact problem and a possible solution, using the resolve-url-loader.

**Comment by httpdigest** [comment] 2017-03-30 15:21
Okay, using the 'resolve-url-loader' completely resolves my issue. The relevant part in `@angular/cli` where this needed to be added for me in order to work, was in the `models/webpack-config/styles.js` file like so:
```JavaScript
    const commonLoaders = [
        // css-loader doesn't support webpack.LoaderOptionsPlugin properly,
        // so we need to add options in its query
        `css-loader?${JSON.stringify({ sourceMap: cssSourceMap, importLoaders: 1 })}`,
        'resolve-url-loader', // <- this is new!
        'postcss-loader'
    ];
```
Then after a `npm install --save-dev resolve-url-loader`, the `ng build` of both the example described in the reproduction steps in this issue above as well as my more complex application worked.

Currently, we now rely on patching webpack's models/webpack-configs/styles.js in a npm postinstall step. I'd be nice if this can be added into Webpack itself.

**Comment by zuo305** [comment] 2017-04-03 03:23
I am using css, and i have the same issue.

ERROR in ./src/app/hotel-search/firstpage-search/firstpage-search.component.css
Module not found: Error: Can't resolve './../asserts/images/peopleMinwhite.svg' in '/Users/john/b2b-site/src/app/hotel-search/firstpage-search'

**Comment by httpdigest** [comment] 2017-04-03 08:19
As it turned out, the issue I was having was related to (and _only_ related to) SCSS, which can be fixed by using the [resolve-url-loader](https://www.npmjs.com/package/resolve-url-loader).
Did you really mention the correct paths in your post? Are you 100% sure that it is exactly `asserts/images` and not `assets/images`?

**Comment by zakdances** [comment] 2017-04-05 22:57
Having this same issue with scss. As a work-around, I use a root reference like this: `"./~/assets/images/hat.svg"`.

**Comment by luketn** [comment] 2017-04-26 15:17
We're also having the same issue attempting to import the Materialize CSS SASS library. We're unable to use the work-around mentioned by @zakdances because the library isn't under our control.

`@import './materialize-src/sass/materialize';`

Outcome:
`ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module not found: Error: Can't resolve '../fonts/roboto/Roboto-Bold.woff'`

+1 for adding a feature to angular cli to include the resolve-url-loader for SASS relative path resolution.

**Comment by filipesilva** [comment] 2017-05-03 12:16
@httpdigest would you be interested in making a PR that adds your proposed change (https://github.com/angular/angular-cli/issues/5752#issuecomment-290445070)?

**Comment by filipesilva** [comment] 2017-05-03 12:20
Actually, now I remember why I didn't add `resolve-url-loader`... it has a very important caveat, sourcemaps MUST be enabled for it to work: https://github.com/bholloway/resolve-url-loader#important

This issue is actually a duplicate of https://github.com/angular/angular-cli/issues/5213, my response can be found at https://github.com/angular/angular-cli/issues/5213#issuecomment-284783844.

**Closed by filipesilva** 2017-05-03 12:20 UTC

**Comment by evaldobratti** [comment] 2017-05-15 17:19
@filipesilva I'm facing the same problem as @luketn, this is preventing me to migrate an app to angular-cli
