### ISSUE TITLE
Migration failed with package alias in package.json

### ISSUE THREAD

**Issue by RDUser-dev** [angular/angular-cli#28373] opened 2024-09-09 08:13 UTC
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

If package.json contains an npm package alias such as ``"@types/ol-ext": "npm:@siedlerchr/types-ol-ext@^3.5.0", `` the command ``ng update`` fails with error ``Migration failed: 404 Not Found - GET https://registry.npmjs.org/@types%2fol-ext - Not found``

### Minimal Reproduction

- create a package alias by running ``npm i -D @types/ol-ext@npm:@siedlerchr/types-ol-ext``
- run ng update ``ng update``

### Exception or Error

```text
Migration failed: 404 Not Found - GET https://registry.npmjs.org/@types%2fol-ext - Not found

in angular-errors.log i can see

[error] HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@types%2fol-ext - Not found
    at C:\Users\[...]\node_modules\npm-registry-fetch\lib\check-response.js:95:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RegistryFetcher.packument (C:\Users\[...]\node_modules\pacote\lib\registry.js:90:19)
    at async Promise.all (index 8)
    at async C:\Users\[...]\node_modules\@angular\cli\src\commands\update\schematic\index.js:656:36
    at async callRuleAsync (C:\Users\[...]\node_modules\@angular-devkit\schematics\src\rules\call.js:77:18)
```

### Your Environment

```text
Angular CLI: 18.2.3
Node: 20.13.1
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 18.2.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, router

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1802.3
@angular-devkit/build-angular    18.2.3
@angular-devkit/core             18.2.3
@angular-devkit/schematics       18.2.3
@angular-devkit/schematics-cli   18.2.3
@schematics/angular              18.2.3
rxjs                             7.8.1
typescript                       5.4.5
zone.js                          0.14.10
```

**Comment by alan-agius4** [comment] 2024-09-09 09:21
Duplicate of https://github.com/angular/angular-cli/issues/25224

**Closed by alan-agius4** 2024-09-09 09:21 UTC
