### ISSUE TITLE
sink._addParentTeardownLogic is not a function on ng new

### ISSUE THREAD

**Issue by MehtaAr25** [angular/angular-cli#12316] opened 2018-09-20 07:11 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
MacBook-Air:Projects $ ng --version

Angular CLI: 6.2.3
Node: 8.12.0
OS: darwin x64
Angular: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.3
@angular-devkit/core         0.8.3
@angular-devkit/schematics   0.8.3
@schematics/angular          0.8.3
@schematics/update           0.8.3
rxjs                         6.2.2

MacBook-Air:Projects $ npm --version
6.4.1

MacBook-Air:Projects $ node --version
v8.12.0

### Repro steps
ng new <project name>

### The log given by the failure
sink._addParentTeardownLogic is not a function

### Desired functionality
Creation of new Angular Project

### Mention any other details that might be useful
I think it might be due to issue of Rxjs Version 6.2.2 in Angular CLI but I dont know how to update Rxjs version in Global @angular/cli

**Comment by alan-agius4** [comment] 2018-09-20 08:58
Duplicate of https://github.com/angular/angular-cli/issues/12262

**Closed by alan-agius4** 2018-09-20 08:58 UTC

**Comment by MehtaAr25** [comment] 2019-01-05 10:04
Team,
The Issue is still not resolved and i am getting the same issue. I tried downgrading rxjs to 6.2.2 but still it shows the same thing. I am helpless to create a new project. Can anyone help
