### ISSUE TITLE
ng serve do not auto update the dist after changing source files.

### ISSUE THREAD

**Issue by harilal** [angular/angular-cli#2287] opened 2016-09-22 07:45 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 14.04

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
 Added some components.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

The "ng serve"  runs the server on port 4200 but after editing and saving the source file it do not get updated . Most time need to manually run ng build and then ng serve or need to restart ng serve

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by udr013** [comment] 2016-09-27 13:25
I noticed when i make a new project in a folder containing white spaces in the name/path some files are missing in node-modules (970 folders)and auto update doesn't work. When creating a project in a folder without white spaces everything works fine, node-modules(979 folders). (This is on Linux mint).

**Comment by esikuriansky** [comment] 2016-10-11 23:09
udr013 ! You fixed the problem for me. Thanks

**Comment by filipesilva** [comment] 2016-10-14 17:26
Dupe of https://github.com/angular/angular-cli/issues/1610 then. Will look for fix there.

**Closed by filipesilva** 2016-10-14 17:26 UTC
Labels: need: investigation

**Comment by gs-nitin27** [comment] 2017-06-01 09:52
i have tried all the thing but nothing is going right

angular-cli: 1.0.4
node: 6.10.3
os: ubuntu 14.04 x64
