### ISSUE TITLE
Unnecessary prompts for ng new when using create application false (i.e. Conditional Prompts)

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#14067] opened 2019-04-03 12:45 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No

### Description

When running `ng new` with create application false users are still prompted for both `routing` and `style` properties when those are related to the application that would be created.

It would be great to not be prompted for those values when create application is set to false as they are not relevant.

## 🔬 Minimal Reproduction

```
ng new foo --create-application=false
```

## 🔥 Exception or Error

Prompted for values both the `routing` and `style` properties

## 🌍 Your Environment

CLI version 7.x

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-04-03 12:56
Hi @Brocco, thanks for reporting this. However this is a duplicate of https://github.com/angular/angular-cli/issues/13383

**Closed by alan-agius4** 2019-04-03 12:56 UTC

**Comment by Brocco** [comment] 2019-04-03 12:58
You are absolutely correct, thanks! I didn't see that one in my searching.

**Comment by alan-agius4** [comment] 2019-04-03 13:04
I'll rename the issue to your title as it's easier to find
