### ISSUE TITLE
missing modules when ng new <app>

### ISSUE THREAD

**Issue by lightsonupstairs** [angular/angular-cli#1207] opened 2016-06-25 23:21 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 7
npm 2.15.5
node 4.4.5

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.8

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Creating a new ng app get a list of missing modules(one at time).
"exists-sync": "0.0.3",
    "object-assign":"4.1.0",
    "minimatch":"3.0.2",
    "walk-sync":"0.2.6",
    "through":"2.3.8"

I followed the steps in the read me for uninstalling and reinstall -g latest.
used the ng new command and received a list of missing modules (listed above)
**exact error**
Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\ng2\cli2\cli2\node_modules\angular-cli\node_modul
s\ember-cli\lib\models\project.js:11:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

c:\ng2\cli2\cli2>npm install -g exists-sync
exists-sync@0.0.3 C:\Users\admin\AppData\Roaming\npm\node_modules\exists-sync

c:\ng2\cli2\cli2>ng serve
module.js:327
    throw err;
    ^

Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\ng2\cli2\cli2\node_modules\angular-cli\node_modul
s\ember-cli\lib\models\project.js:11:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

c:\ng2\cli2\cli2>npm install

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Did the uninstall remove these files and not replace them during beta.8 install.

5. Mention any other details that might be useful.

Solution:  install the modules above with npm install -g and add to package.json --> the run npm install inside your new app folder with the updated package.json.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by Splaktar** [comment] 2016-06-26 16:14
Duplicate of #1186. This should be closed.

**Closed** 2016-06-30 12:18 UTC
