### ISSUE TITLE
Use module name as component selector prefix

### ISSUE THREAD

**Issue by jmendiara** [angular/angular-cli#5795] opened 2017-04-02 07:50 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

```sh
$ ng --version
@angular/cli: 1.0.0
node: 6.10.0
os: darwin x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
```

### Repro steps.

```sh
$ ng g m babies --routing
$ ng g c babies/detail 
```
this generates 
```ts
@Component({
  selector: 'app-detail',
  templateUrl: './detail.component.html',
  styleUrls: ['./detail.component.scss']
})
//...
```

### Desired functionality.

As per https://angular.io/docs/ts/latest/guide/style-guide.html#!#02-07 
> Do use a custom prefix for a component selector. For example, the prefix toh represents from Tour of Heroes and the prefix admin represents an admin feature area.
> Do use a prefix that identifies the feature area or the app itself.

When you create a component in a feature, it's likely that feature can be exported. Having `app` prefix when creating a component inside a feature asumes the feature _should_ live inside an `app` context, and can cause more collisions.

Therefore, setting the module prefix to their components by _default_ will lead to better practices

The expected result would be
```sh
$ ng g m babies --routing
$ ng g c babies/detail 
```
could generate
```ts
@Component({
  selector: 'babies-detail',
  templateUrl: './detail.component.html',
  styleUrls: ['./detail.component.scss']
})
//...
```

### Mention any other details that might be useful.
Related #5794

**Comment by filipesilva** [comment] 2017-05-04 14:14
This is part of a larger-ish discussion regarding supporting several prefixes, and how to auto-determine them. I don't think there's a good way of auto-detecting though. The best way to do this atm is to use the `--prefix` flag when making a component.

**Comment by SamanthaAdrichem** [comment] 2019-06-12 13:14
Atleast it should become `'app-babies-detail'` if you ask me.

**Comment by kyliau** [comment] 2020-06-26 16:31
I think there are two components to this issue:
1. Can user provide a custom prefix when running `ng generate`?
2. Can CLI automatically determine the right prefix?

For (1), this is already possible with the [`--prefix`](https://angular.io/cli/generate#component-command) flag.
In your example, you can run 
```
$ ng g c babies/detail --prefix babies 
```

For (2) this is difficult to implement right for every user, with little benefit.

Since it's relatively low effort to achieve your intended behavior, and it's already possible to do that today, I'll close this issue for now. Please reopen if you'd like further discussion.

**Closed by kyliau** 2020-06-26 16:31 UTC
Labels: comp: schematics/angular, need: further discussion, severity2: inconvenient, triage #1, type: feature
