### ISSUE TITLE
Error during compilation after fixing a syntax error

### ISSUE THREAD

**Issue by DeborahK** [angular/angular-cli#16036] opened 2019-11-01 23:35 UTC
# 🐞 bug report

### Affected Package

 None

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.7

### Description

 If I have a syntax error in the code, *then* start the app with `npm start`, when I fix the error, the compiler generates the following error:
```
ERROR in ./src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property. 
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:920:23)
    at plugin.done.then (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:920:23)
    at plugin.done.then (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## 🔬 Minimal Reproduction

 This has been somewhat difficult to reproduce.

This is what I did, and can reproduce it every time following these steps.

1) Made a syntax error in my code

```
    ngOnInit() {
        this.sub = this.productService.selectedProductChanges$.subscribe({
            next: selectedProduct => this.product = selectedProduct,
            error: err => this.errorMessage = err
        };     // <- Missing paren here
    }
```
2) Started the app with `npm start`

3) I see the correct `')' expected` error message

4) Fixed the error, got the error message as shown below.

5) At this point I have to stop the compiler and restart, then it compiles without issue.

Here is the output from the console:

```
PS C:\Users\...> npm start

> apm@0.0.0 start C:\Users\...
> ng serve -o

10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.07 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 714 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.04 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2019-11-01T23:24:46.037Z - Hash: 9acd019b2df6dfe09939 - Time: 2676ms

ERROR in src/app/products/product-shell/product-shell-detail.component.ts:23:10 - error TS1005: ')' expected.

23         };
            ~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
i ｢wdm｣: Compiling...

Date: 2019-11-01T23:24:55.928Z - Hash: 44abf69c38b2e0c5ade5
3 unchanged chunks
chunk {main} main.js, main.js.map (main) 2.78 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 1.42 kB [initial] [rendered]
Time: 331ms

ERROR in ./src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property. 
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:920:23)
    at plugin.done.then (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:920:23)
    at plugin.done.then (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
i ｢wdm｣: Failed to compile.
```

If you want to try out the same code I'm using, you can find it here: https://github.com/DeborahK/Angular-Communication/tree/master/APM-Final%20v8

You'll need to update it to v9 using these steps:

npm install --no-save @angular/cli@next
ng update @angular/cli @angular/core --next

## 🔥 Exception or Error
<pre><code>

ERROR in ./src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property. 
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:920:23)
    at plugin.done.then (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:920:23)
    at plugin.done.then (C:\Users\Deborah\Documents\GitHub\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
i ｢wdm｣: Failed to compile.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

@StephenFluin @alan-agius4

**Comment by alan-agius4** [comment] 2019-11-02 07:21
This is tracked here: https://github.com/angular/angular/issues/32214

**Comment by filipesilva** [comment] 2019-11-04 11:39
I followed these commands: 
```
git clone https://github.com/DeborahK/Angular-Communication/
cd "Angular-Communication/APM-Final v8"
npm install
npm install --no-save @angular/cli@next
ng update @angular/cli @angular/core --next
ng update @angular/cli @angular/core --next --force
```

A couple of notes here:

I had to use `--force` on the update because of these:
```
kamik@RED-X1C6 MINGW64 /d/sandbox/Angular-Communication/APM-Final v8 (master)
$ ng update @angular/cli @angular/core --next
Using package manager: 'npm'
Collecting installed dependencies...
Found 33 dependencies.
Fetching dependency metadata from registry...
Package '@angular/cli' is already up to date.
                  Package "angular-in-memory-web-api" has an incompatible peer dependency to "@angular/core" (requires ">=8.0.0", would install "9.0.0-rc.0").
                  Package "angular-in-memory-web-api" has an incompatible peer dependency to "@angular/common" (requires ">=8.0.0", would install "9.0.0-rc.0").
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires ">=3.1 < 3.6", would install "3.6.4").
Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
```

`npm install --no-save @angular/cli@next` is not the right command to run according to https://next.angular.io/guide/updating-to-version-9. This will install CLI in version 9, but the update guide instructs users to install the latest version 8 instead.

Following the rest of the steps doesn't give me the same error though:
```
kamik@RED-X1C6 MINGW64 /d/sandbox/Angular-Communication/APM-Final v8 (master)
$ ng serve
10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.02 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 122 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.01 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2019-11-04T10:43:56.354Z - Hash: 7d09de3a40835aa15675 - Time: 5970ms

ERROR in src/app/products/product-shell/product-shell-detail.component.ts:21:8 - error TS1005: ')' expected.

21        ;
          ~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
i ｢wdm｣: Compiling...

Date: 2019-11-04T10:44:10.592Z - Hash: 8376511fff53f696c847
1 unchanged chunks
chunk {main} main.js, main.js.map (main) 48.1 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 262 kB [initial] [rendered]
chunk {products-product-module} products-product-module.js, products-product-module.js.map (products-product-module) 50.9 kB  [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9.02 kB [entry] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.66 MB [initial] [rendered]
Time: 9450ms

WARNING in D:/sandbox/Angular-Communication/APM-Final v8/src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
i ｢wdm｣: Compiled with warnings.
```

Something surprising here is that after the update I actually got older versions of the CLI:
```
Angular CLI: 8.3.5
Node: 10.16.0
OS: win32 x64
Angular: 9.0.0-rc.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.5
@angular-devkit/build-angular     0.803.5
@angular-devkit/build-optimizer   0.803.5
@angular-devkit/build-webpack     0.803.5
@angular-devkit/core              8.3.5
@angular-devkit/schematics        8.3.5
@angular/cli                      8.3.5
@ngtools/webpack                  8.3.5
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.39.2
```

I think this happened because we started on CLI `9.0.0-rc.0`. It still looks like a bug. It also prevented CLI migrations from running.

I tried again but this time I installed the right CLI version:

```
git clone https://github.com/DeborahK/Angular-Communication/
cd "Angular-Communication/APM-Final v8"
npm install
npm install --no-save @angular/cli@^8.3.15
ng update @angular/cli @angular/core --next
ng update @angular/cli @angular/core --next --force
```

At this point I can see the reported error after following the rest of the steps:
```
kamik@RED-X1C6 MINGW64 /d/sandbox/Angular-Communication/APM-Final v8 (master)
$ ng serve
10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.02 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 691 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.04 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2019-11-04T11:04:24.847Z - Hash: 9e3f35c6dad74f342116 - Time: 5215ms

ERROR in src/app/products/product-shell/product-shell-detail.component.ts:21:9 - error TS1005: ')' expected.

21         ;
           ~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
i ｢wdm｣: Compiling...

Date: 2019-11-04T11:11:28.838Z - Hash: 5a686f2e20a06b8a4bf6
3 unchanged chunks
chunk {main} main.js, main.js.map (main) 2.66 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 1.32 kB [initial] [rendered]
Time: 630ms

ERROR in ./src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\sandbox\Angular-Communication\APM-Final v8\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.      
    at AngularCompilerPlugin.getCompiledFile (D:\sandbox\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:920:23)
    at plugin.done.then (D:\sandbox\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\sandbox\Angular-Communication\APM-Final v8\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property. 
    at AngularCompilerPlugin.getCompiledFile (D:\sandbox\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:920:23)
    at plugin.done.then (D:\sandbox\Angular-Communication\APM-Final v8\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I can confirm that this happens only when compiling with AOT (the migration adds it automatically) and with Ivy. Compiling without Ivy don't have this problem.

**Comment by filipesilva** [comment] 2019-11-04 12:40
Yes, this is a variation of https://github.com/angular/angular/issues/32214#issuecomment-549335630. Reported what's happening there.

**Comment by IgorMinar** [comment] 2019-11-16 00:31
I'll close this as dupe of angular/angular#32214 please follow that issue for status update.

**Closed by IgorMinar** 2019-11-16 00:31 UTC
Labels: blocked, comp: ngtools/webpack, freq3: high, severity5: regression, type: bug/fix
