### ISSUE TITLE
latest cli doesn't honor sass extension

### ISSUE THREAD

**Issue by sfabriece** [angular/angular-cli#7708] opened 2017-09-15 19:30 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.2
node: 8.4.0
os: win32 x64

### Repro steps.

In a project that uses `scss` as style. 
Generate a new component. 
The css for the component will be `.css` instead of `.scss`.
### Desired functionality.

correct extension used for css

**Comment by AhsanAyaz** [comment] 2017-09-15 23:30
Duplicate of #7624, #7644, #7647,& #7522

**Comment by Brocco** [comment] 2017-09-22 16:11
Closing as a duplicate.

**Closed by Brocco** 2017-09-22 16:11 UTC
