### ISSUE TITLE
No exclude option in documentation

### ISSUE THREAD

**Issue by megamindbrian** [angular/angular-cli#7298] opened 2017-08-08 06:29 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.28.3
node: 7.7.2
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.2
@angular/compiler-cli: 4.1.3

### Repro steps.

Use angular-cli serve command.  Open SourceTree or Webstorm on your "watched" project folder.  Switch windows and notice ng rebuilding everytime the window changes focus.

### Mention any other details that might be useful.

Please document how to use an --exclude option from the "watch" mode so that we can avoid rebuilding when webstorm loses focus.  There is no reason to rebuild every single time the window focus changes.  When I select a CSS tag that I am looking at, my project rebuilds and the entire page reloads while I am in the middle of looking at the code.  Please recommend how to stop this from happening.  It is very annoying.

**Comment by filipesilva** [comment] 2017-08-21 12:23
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #2425. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-08-21 12:23 UTC
Labels: priority: 2 (required), severity2: inconvenient
