### ISSUE TITLE
Error install 1.0.0-beta.11-webpack

### ISSUE THREAD

**Issue by jvbianchi** [angular/angular-cli#1522] opened 2016-08-02 19:40 UTC
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
   OSX El Capitan
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:
   angular-cli:1.0.0-beta.11-webpack
   node:v6.3.1
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   npm i -g angular-cli@1.0.0-beta.11-webpack
4. The log given by the failure. Normally this include a stack trace and some
   more information.

`karma-webpack@1.7.0 requires a peer of webpack@^1.4.0 but none was installed.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/user/.nvm/versions/node/v6.3.1/bin/node" "/Users/user/.nvm/versions/node/v6.3.1/bin/npm" "i" "-g" "angular-cli@1.0.0-beta.11-webpack"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! path /Users/user/.nvm/versions/node/v6.3.1/lib/node_modules/angular-cli
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access

npm ERR! enoent ENOENT: no such file or directory, access '/Users/user/.nvm/versions/node/v6.3.1/lib/node_modules/angular-cli'
npm ERR! enoent ENOENT: no such file or directory, access '/Users/user/.nvm/versions/node/v6.3.1/lib/node_modules/angular-cli'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/mycode/code/npm-debug.log`

**Comment by sirajc** [comment] 2016-08-02 19:46
This related to, or duplicate of #1520

**Comment by TheLarkInn** [comment] 2016-08-03 01:29
Yes it is @sirajc thank you for tying the bug to it.

**Comment by FabienDehopre** [comment] 2016-08-05 13:06
I have another error message...
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN karma-webpack@1.7.0 requires a peer of webpack@^1.4.0 but none was installed.
npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "angular-cli@webpack"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path /home/fabien/devs/sample/node_modules/.staging/sshpk-bb6b4d5e
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/home/fabien/devs/sample/node_modules/.staging/sshpk-bb6b4d5e' -> '/home/fabien/devs/sample/node_modules/ember-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/fabien/devs/sample/node_modules/.staging/sshpk-bb6b4d5e' -> '/home/fabien/devs/sample/node_modules/ember-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fabien/devs/sample/npm-debug.log
```
I don't know if it's related or another issue.

**Comment by suchja** [comment] 2016-08-05 23:23
I do get a similar message like @FabienDehopre 

```
Linux 4.4.16-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "angular-cli@webpack"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! path /usr/src/app/new-hello/node_modules/ember-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/src/app/new-hello/node_modules/ember-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/src/app/new-hello/node_modules/ember-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```
I tried all sorts of different combinations of node and npm (all in a docker container) without any success.

Installation with `npm install -g angular-cli@webpack` succeed without any major issues. Then I called `ng new hello` which resulted in:

```
Successfully initialized git.
ENOENT: no such file or directory, chmod '/usr/src/app/new-hello/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
Error: ENOENT: no such file or directory, chmod '/usr/src/app/new-hello/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
    at Error (native)
```
Is there any kind of debug switch to get more information on what the problem really is?

**Comment by filipesilva** [comment] 2016-08-15 01:14
I don't think the errors in this thread are actually related to https://github.com/angular/angular-cli/issues/1520. 

These seem to indicate a problem with the npm install itself:
```
npm ERR! enoent ENOENT: no such file or directory, access '/Users/user/.nvm/versions/node/v6.3.1/lib/node_modules/angular-cli'
npm ERR! enoent ENOENT: no such file or directory, access '/Users/user/.nvm/versions/node/v6.3.1/lib/node_modules/angular-cli'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```
```
npm ERR! enoent ENOENT: no such file or directory, rename '/home/fabien/devs/sample/node_modules/.staging/sshpk-bb6b4d5e' -> '/home/fabien/devs/sample/node_modules/ember-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/fabien/devs/sample/node_modules/.staging/sshpk-bb6b4d5e' -> '/home/fabien/devs/sample/node_modules/ember-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```
```
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/src/app/new-hello/node_modules/ember-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/src/app/new-hello/node_modules/ember-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```

I don't really have an answer for now. I can't reproduce it myself  (win10, node v5.12.0, npm 3.8.6) so it might be a setup dependent thing.

I know this is the default answer for npm issues but... have you tried uninstalling the global `angular-cli`, doing `npm cache clean` and then re-installing?

**Comment by Mavlarn** [comment] 2016-08-25 14:42
I also got this error and can not create new project, is there any solution before new version?

**Comment by kevingelion** [comment] 2016-09-23 20:36
Still having this issue as well. Why was this closed?

**Comment by hansl** [comment] 2016-12-22 19:18
Closing this as obsolete.

**Closed by hansl** 2016-12-22 19:18 UTC
Labels: need: repro steps, type: bug

**Comment by elimisteve** [comment] 2017-01-13 04:43
Fixed it.

I had moved `node_modules/<package_name>` to `node_modules/<package_name>-MOVED` so that npm would be forced to reinstall it, but instead I got the same errors as @FabienDehopre and @suchja. But moving my `node_modules/<package_name>-MOVED` directory someplace else entirely fixed this; `npm install` now works as I wanted!
