### ISSUE TITLE
Build fails for Ivy

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular-cli#20778] opened 2021-05-14 01:18 UTC
# 🐞 Bug report

### Command

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes.

### Description

Build production configuration fails for package @ngtools/webpack

## 🔥 Exception or Error

<pre><code>
Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: angularCompiler.getNextProgram is not a function
    at xx\ClientApp\node_modules\@angular-devkit\build-angular\node_modules\@ngtools\webpack\src\ivy\plugin.js:390:61
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 @ multi ./src/main.ts main[0]</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.0
Node: 16.1.0
Package Manager: npm 7.13.0
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   0.1102.13
@angular-devkit/build-webpack   0.1200.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@angular/flex-layout            11.0.0-beta.33
@ngtools/webpack                12.0.0
@schematics/angular             12.0.0
ng-packagr                      12.0.0
rxjs                            6.6.7
typescript                      4.2.4
webpack                         5.37.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-05-14 05:42
Can you please provide the output of `npm ls @ngtools/webpack`?

**Comment by rudivanbiljon** [comment] 2021-05-14 07:42
I have the same problem. Here is my output of npm ls @ngtools/webpack:

`
+-- @angular-builders/custom-webpack@11.1.1
| `-- @angular-devkit/build-angular@0.1102.13
|   `-- @ngtools/webpack@11.2.13
`-- @angular-devkit/build-angular@12.0.0
  `-- @ngtools/webpack@12.0.0
`

**Comment by rudivanbiljon** [comment] 2021-05-14 09:18
I have the same problem. Here is my output of npm ls @ngtools/webpack:

```
+-- @angular-builders/custom-webpack@11.1.1  
| `-- @angular-devkit/build-angular@0.1102.13  
|   `-- @ngtools/webpack@11.2.13  
`-- @angular-devkit/build-angular@12.0.0  
  `-- @ngtools/webpack@12.0.0  
```

Output of ng version:

```
Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
ng-packagr                      12.0.0
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by alan-agius4** [comment] 2021-05-14 10:12
@rudivanbiljon, It appears that a you are using third-party builder `@angular-builders/custom-webpack` is being used, which is not compatbaler with Angular 12. This builder is also not supported by the Angular team. Please contact the maintainer of the third-party builder if the project continues to experience issues after making the above suggested changes.

@zehavibarak, is it the same in your case?

**Comment by zehavibarak** [comment] 2021-05-14 10:15
If you are referring to the second bug, or rather the 1st, the one you closed - not it’s not and you should know it by now.

**Comment by alan-agius4** [comment] 2021-05-14 10:25
@zehavibarak, please maintain appropriate behaviour and follow our code of conduct https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md. 

You reported **this** issue, and hence I asked you some questions to determine the root cause of **this** issue and your answer was. 
> If you are referring to the second bug, or rather the 1st, the one you closed - not it’s not and you should know it by now.

Please provide the requested information related to this issue or otherwise I will have to close the issue.

1. output of `npm ls @ngtools/webpack`
2. Are you using `@angular-builders/custom-webpack` or any 3rd party builders?

Thanks for your understanding.

**Comment by zehavibarak** [comment] 2021-05-14 19:30
No I haven’t. Please open the other issue till you or someone else fix it.

**Comment by alan-agius4** [comment] 2021-05-14 20:12
I am going to close this issue since the reporter is demonstrating an unprofessional and uncooperative behaviour which violates our code of conduct, even after being previously warned.

**Closed by alan-agius4** 2021-05-14 20:12 UTC
Labels: need: more info
