### ISSUE TITLE
Browserslist: caniuse-lite is outdated

### ISSUE THREAD

**Issue by sam-s4s** [angular/angular-cli#16575] opened 2020-01-06 00:20 UTC
# 🐞 bug report

### Is this a regression?

 Yes and no - it's the underlying npm dependencies that have changed to cause this problem, not angular itself.

(problem was not present on the 20th of December, for example)

### Description
When building an angular project, we now receive a warning that caniuse-lite is outdated is outdated.

## 🔬 Minimal Reproduction
ng new
ng build

## 🔥 Exception or Error
<pre><code>
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.21
Node: 10.15.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.21
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.3.21
@angular-devkit/schematics        8.3.21
@angular/cli                      8.3.21
@ngtools/webpack                  8.3.21
@schematics/angular               8.3.21
@schematics/update                0.803.21
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Additional comments:**

We might need a new version of angular 8 to fix this problem (8.2.15)

**Comment by alan-agius4** [comment] 2020-01-08 10:32
Duplicate of https://github.com/angular/angular-cli/issues/16560

**Closed by alan-agius4** 2020-01-08 10:32 UTC
