### ISSUE TITLE
[schematics] ast-utils insertImport() import 'fileName'

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular-cli#18138] opened 2020-07-03 12:54 UTC
in `@schematics/angular/utility/ast-utils`, the function `insertImport` can generate the following import delarations:

```
insertImport(source, fileToEdit, "symbolName" ,"fileName", false);

//will generate:
import { symbolName } from 'fileName'
```

and ...

```
insertImport(source, fileToEdit, "* as symbolName", "fileName", true);
//note isDefault = true (the last parameter)

//will generate:
import * as symbolName from 'fileName'
```

but if there is no symbolName it should remove 'from'
```
insertImport(source, fileToEdit, '', "fileName");

//should generate:
import  'fileName';

//but it generates:
import from 'fileName';
```

**Comment by alan-agius4** [comment] 2020-07-03 13:30
Hi @eng-dibo, the `ast-utils` are part of the private api and internally we don't use this style of import. 

There are plans to provide helpers methods as part of the public API, but it's currently still in design phase.

Closing the issue is being experiencing when using private API's.

**Closed by alan-agius4** 2020-07-03 13:30 UTC
