### ISSUE TITLE
`ng build` or `ng build --environment prod` works, but `ng build --prod` or `ng build --aot` fails

### ISSUE THREAD

**Issue by catull** [angular/angular-cli#9923] opened 2018-03-10 00:44 UTC
### Versions
ng version: 1.7.3
node version: 9.8.0
OS: macOS 10.12.6 (Sierra)

### Repro steps
```shell
git clone git@github.com:catull/bootstraping-ngx-admin-lte.git
cd bootstraping-ngx-admin-lte
git checkout upgrade-dependencies
npm install
```

### These work
`ng build`
`ng build --environment prod`

### These fail
`ng build --prod`
`ng build --aot`

### Observed behaviour

Non-prod and non-AOT build is fine.

### Desired behaviour

Would like to benefit from AOT build

**Comment by jwuliger** [comment] 2018-03-11 10:04
I can report the very same issue.

**Comment by pascallaprade-beslogic** [comment] 2018-03-12 17:50
If you want the full `--prod` behaviour, I found out that the longer form `--target=production` still works while they fix the problem with the former: https://github.com/angular/angular-cli/issues/9914#issuecomment-371894801.

**Comment by Brocco** [comment] 2018-03-12 21:36
@pascallaprade-beslogic Thanks for sharing that link... I'm closing this issue.

Duplicate of #9914

**Closed by Brocco** 2018-03-12 21:36 UTC
