### ISSUE TITLE
ng update results in npm ERR! Could not resolve dependency

### ISSUE THREAD

**Issue by egnexstep** [angular/angular-cli#20347] opened 2021-03-22 10:27 UTC
I have a angular project I created last week, running Angular 11.2.25 and I thought I would update to the latest version ( I see that the latest version now is 11.2.6 for core)

Running ng update, shows:

> The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 35 dependencies.
    We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       11.2.4 -> 11.2.5         ng update @angular/cli
      @angular/core                      11.2.5 -> 11.2.6         ng update @angular/core

    There might be additional packages which don't provide 'ng update' capabilities that are outdated.
    You can update the additional packages by running the update command of your package manager.

And then running ng update @angular/cli just shows me this:

> The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 35 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1102.5" (was "0.1102.4")...
    Updating package.json with dependency @angular/cli @ "11.2.5" (was "11.2.4")...
  UPDATE package.json (1486 bytes)
⠙ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular-devkit/build-angular@0.1102.4
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1102.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~0.1102.5" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/service-worker@11.2.6
npm ERR! node_modules/@angular/service-worker
npm ERR!   peerOptional @angular/service-worker@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.5
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1102.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/bjojo/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bjojo/.npm/_logs/2021-03-22T10_14_39_738Z-debug.log
✖ Package install failed, see above.
✖ Migration failed. See above for further details.

Shouldn't this just work or am I missing something? (I also tried using --force, with the same result...)

**Comment by alan-agius4** [comment] 2021-03-22 10:45
Which version of NPM 7 are you using?

If you are not using 7.6 or later, kindly update.

**Comment by egnexstep** [comment] 2021-03-22 10:46
I am using npm version 7.6.3

**Comment by alan-agius4** [comment] 2021-03-22 11:03
This seems like a duplicate of https://github.com/angular/angular-cli/issues/20180 where it looks like an NPM defect as  `11.2.6` does satisfy `^11.0.0 || ^11.2.0-next` but NPM is saying it does not.

**Closed by alan-agius4** 2021-03-22 11:03 UTC
