### ISSUE TITLE
@angular-devkit/build-angular@0.13.5 breaks angular universal

### ISSUE THREAD

**Issue by robertisaacBBN** [angular/angular-cli#13865] opened 2019-03-10 08:49 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: @angular-devkit/build-angular@0.13.4

### Description
when run `npm run build:ssr && npn run serve:ssr` and open http://localhost:4000 from the browser it shows
```
Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped
    at View.engine (C:\Users\rober\ng\test-ssr\dist\server.js:39238:23)
    at View.render (C:\Users\rober\ng\test-ssr\dist\server.js:123884:8)
    at tryRender (C:\Users\rober\ng\test-ssr\dist\server.js:121592:10)
    at Function.render (C:\Users\rober\ng\test-ssr\dist\server.js:121544:3)
    at ServerResponse.render (C:\Users\rober\ng\test-ssr\dist\server.js:130425:7)
    at C:\Users\rober\ng\test-ssr\dist\server.js:135:9
    at Layer.handle [as handle_request] (C:\Users\rober\ng\test-ssr\dist\server.js:123312:5)
    at next (C:\Users\rober\ng\test-ssr\dist\server.js:123060:13)
    at Route.dispatch (C:\Users\rober\ng\test-ssr\dist\server.js:123035:3)
    at Layer.handle [as handle_request] (C:\Users\rober\ng\test-ssr\dist\server.js:123312:5)
```
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
```
ng new test-ssr
cd test-ssr
ng add @nguniversal/express-engine --clientProject test-ssr
npm run build:ssr
npm run serve:ssr
# open http://localhost:4000 will show error
npm i @angular-devkit/build-angular@0.13.4
npm run build:ssr
npm run serve:ssr
# will work normally
```

## 🔥 Exception or Error
<pre><code>
Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped
    at View.engine (C:\Users\rober\ng\test-ssr\dist\server.js:39238:23)
    at View.render (C:\Users\rober\ng\test-ssr\dist\server.js:123884:8)
    at tryRender (C:\Users\rober\ng\test-ssr\dist\server.js:121592:10)
    at Function.render (C:\Users\rober\ng\test-ssr\dist\server.js:121544:3)
    at ServerResponse.render (C:\Users\rober\ng\test-ssr\dist\server.js:130425:7)
    at C:\Users\rober\ng\test-ssr\dist\server.js:135:9
    at Layer.handle [as handle_request] (C:\Users\rober\ng\test-ssr\dist\server.js:123312:5)
    at next (C:\Users\rober\ng\test-ssr\dist\server.js:123060:13)
    at Route.dispatch (C:\Users\rober\ng\test-ssr\dist\server.js:123035:3)
    at Layer.handle [as handle_request] (C:\Users\rober\ng\test-ssr\dist\server.js:123312:5)
</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.5
Node: 11.9.0
OS: win32 x64
Angular: 7.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.5
@angular-devkit/build-angular     0.13.5
@angular-devkit/build-optimizer   0.13.5
@angular-devkit/build-webpack     0.13.5
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cli                      7.3.5
@ngtools/webpack                  7.3.5
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by alan-agius4** [comment] 2019-03-10 16:30
Duplicate of https://github.com/angular/universal/issues/1139

**Closed** 2019-03-11 20:40 UTC
Labels: comp: devkit/build-angular, freq3: high, severity5: regression, type: bug/fix

**Comment by robertisaacBBN** [comment] 2019-03-12 09:26
good morning @alan-agius4 

when will this fix be published?
