### ISSUE TITLE
cliSystemConfigPackages is not defined

### ISSUE THREAD

**Issue by thehashrocket** [angular/angular-cli#1688] opened 2016-08-14 14:42 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX Sierra

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.10
node: v5.10.1

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
  1. Do a fresh install of an angular-cli app (ex. `ng create bleh`).
  2. Serve the app and view in Firefox. (ex. `ng serve`)
  3. Open Firefox Dev Tools and reload the app.
  4. Behold the error which appears in console and see that the app no longer reloads.
<img width="1168" alt="screen shot 2016-08-14 at 8 28 34 am" src="https://cloud.githubusercontent.com/assets/342353/17649788/171f510c-61fa-11e6-91de-714c2b02728e.png">

4. The log given by the failure. Normally this include a stack trace and some
   more information.
`"@http://localhost:4200/system-config.js:34:5Call@http://localhost:4200/vendor/es6-shim/es6-shim.js:289:14forEach@http://localhost:4200/vendor/es6-shim/es6-shim.js:1295:14@http://localhost:4200/system-config.js:33:1bootstrap/__exec@http://localhost:4200/vendor/systemjs/dist/system.src.js:1506:10bootstrap/</</entry.execute@http://localhost:4200/vendor/systemjs/dist/system.src.js:3647:9linkDynamicModule@http://localhost:4200/vendor/systemjs/dist/system.src.js:3247:18link@http://localhost:4200/vendor/systemjs/dist/system.src.js:3090:11bootstrap/</</</<.execute@http://localhost:4200/vendor/systemjs/dist/system.src.js:3427:13doDynamicExecute@http://localhost:4200/vendor/systemjs/dist/system.src.js:796:20link@http://localhost:4200/vendor/systemjs/dist/system.src.js:998:20doLink@http://localhost:4200/vendor/systemjs/dist/system.src.js:650:7updateLinkSetOnLoad@http://localhost:4200/vendor/systemjs/dist/system.src.js:698:18proceedToTranslate/</<@http://localhost:4200/vendor/systemjs/dist/system.src.js:510:11Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:4200/vendor/zone.js/dist/zone.js:323:20Zone</Zone</Zone.prototype.run@http://localhost:4200/vendor/zone.js/dist/zone.js:216:25scheduleResolveOrReject/<@http://localhost:4200/vendor/zone.js/dist/zone.js:571:53Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:4200/vendor/zone.js/dist/zone.js:356:24Zone</Zone</Zone.prototype.runTask@http://localhost:4200/vendor/zone.js/dist/zone.js:256:29drainMicroTaskQueue@http://localhost:4200/vendor/zone.js/dist/zone.js:474:26ZoneTask/this.invoke@http://localhost:4200/vendor/zone.js/dist/zone.js:426:22"`

5. Mention any other details that might be useful.
This behavior does not happen in Chrome, just Firefox. I literally changed nothing in the app, just `ng create` and then `ng serve`. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-08-19 02:32
Dupe of https://github.com/angular/angular-cli/issues/1417 I believe. Correct me if I;m wrong.

**Closed by filipesilva** 2016-08-19 02:32 UTC
