### ISSUE TITLE
migration from LESS2 (ng1) to LESS3 (ng6) allow to use option javascriptEnabled

### ISSUE THREAD

**Issue by WuglyakBolgoink** [angular/angular-cli#11495] opened 2018-07-07 19:03 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Area
```
- [x] devkit
```

can we merge this PR?
https://github.com/angular/devkit/pull/866/files

I try to migrate from ng1 to ng6. In our less files there are many mixins.
now I got error like:

```
ERROR in ./src/styles/main.less (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/less-loader/dist/cjs.js??ref--15-3!./src/styles/main.less)
Module build failed: 


    .transitionExt(top ease 250ms);
  ^
Inline JavaScript is not enabled. Is it set in your options?
      in /Users/dev/app/src/styles/core/base.less (line 239, column 4)
```

als temporary solution for back-compatibility is adding "javascriptEnabled:true" to less compiler.

is it possible to add in `angular.json` or `package.json` this option?

**Comment by clydin** [comment] 2018-07-09 14:00
Duplicate of #10430

**Closed by clydin** 2018-07-09 14:00 UTC
