### ISSUE TITLE
"EISDIR: illegal operation on a directory, copyfile" when using nested assets

### ISSUE THREAD

**Issue by magnattic** [angular/angular-cli#15854] opened 2019-10-16 12:57 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 8

### Description
When you have subfolders with files in your `/src/assets/` folder, the angular cli build fails.

## 🔬 Minimal Reproduction
>ng new ng9n10 && cd ng9n10
>mkdir src/assets/test
>touch src/assets/test/test.png
>npm run build

## 🔥 Exception or Error
<pre><code>
Unable to copy assets: EISDIR: illegal operation on a directory, copyfile '/home/xyz/code/ng9n10/src/assets/test' -> '/home/xyz/code/ng9n10/dist/ng9n10/assets/test'
</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 9.0.0-next.9
Node: 11.14.0
OS: linux x64
Angular: 9.0.0-next.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.9
@angular-devkit/build-angular     0.900.0-next.9
@angular-devkit/build-optimizer   0.900.0-next.9
@angular-devkit/build-webpack     0.900.0-next.9
@angular-devkit/core              9.0.0-next.9
@angular-devkit/schematics        9.0.0-next.9
@angular/cli                      9.0.0-next.9
@ngtools/webpack                  9.0.0-next.9
@schematics/angular               9.0.0-next.9
@schematics/update                0.900.0-next.9
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.41.0
</code></pre>

**Comment by alan-agius4** [comment] 2019-10-16 13:06
Duplicate of https://github.com/angular/angular-cli/issues/15816

Should be released in the next release which should happen later on today.

Thanks.

**Closed by alan-agius4** 2019-10-16 13:06 UTC
