### ISSUE TITLE
Use Generated Class .name in spec describe

### ISSUE THREAD

**Issue by ConnorSmith-pf** [angular/angular-cli#21451] opened 2021-07-29 06:51 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When using the CLI to generate a Component, or a Service etc, the initial describe parameter is a string of the class just generated.

`ng g c TestComponent`
Generates test.component.spec.ts, with `describe('TestComponent', () => {...`

### Describe the solution you'd like

A potentially easier solution would be to generate the describe block like: `describe(TestComponent.name, () => {...`. This will help if the Component/Service etc gets renamed/refactored.

### Describe alternatives you've considered

Alternatives are simply changing the initial describe parameter upon creation, or writing our own schematic.

**Comment by alan-agius4** [comment] 2021-07-29 07:00
Duplicate of https://github.com/angular/angular-cli/issues/19026

**Closed by alan-agius4** 2021-07-29 07:00 UTC
