### ISSUE TITLE
Deprecation of 'deployUrl' will/has caused the HashLocation routing to break when the baseHref is not on the same domain

### ISSUE THREAD

**Issue by djhouseknecht** [angular/angular-cli#23070] opened 2022-05-03 17:04 UTC
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
In v13 of Angular, the [deployUrl](https://angular.io/guide/deployment#the-deploy-url) was deprecated and users were encouraged to use the [base tag](https://angular.io/guide/deployment#the-base-tag) (ie. `baseHref`) instead.

`baseHref` and the router only seem to work if the assets are served from _the same domain_ as the `index.html` (ie. "the index file"). This greatly limits and even blocks some Angular applications.

There are timeswhen the actual index file of the app is hosted on a separate domain. 

### Description
Given the following criteria: 
* The build Angular app's assets are uploaded to a **cdn**. 
  * Example: `https://s3.cdn.com/my-angular-app/build-123/<contents-of-the-dist-folder>`
* The `index.html` file of the app is then **"deployed"** to a separate domain. 
  * Example: `https://s3.cdn.com/my-angular-app/build-123/index.html` is moved to `https://apps.mydomain.com/my-angular-app/index.html`

The combined use of `--deployUrl` and `--baseHref` gives Angular apps the ability to do this. 

However, this cannot be accomplished with _only using_ the `--baseHref` option. The two outcomes:
1. if `index.html` uses `--baseHref` equal to the **cdn** (ie. `https://s3.cdn.com/my-angular-app/...`)
    * assets are able to load
    * route _throws an error_ and does not load the app (see error below)
2. if `index.html` uses `--baseHref` equal to the **"deployed"** domain (ie. `https://apps.mydomain.com/my-angular-app/`)
    * assets _cannot load_ because they are not uploaded to **deployed** domain

## 🔬 Minimal Reproduction
I created a minimum reproduction repo. It has a detailed README with setup and testing instructions. It also adds a little more context and clarity around the difference between a **cdn** url and the **deployed** url. 

* https://github.com/djhouseknecht/angular-deploy-url-repro

## 🔥 Exception or Error

<pre><code>Unhandled Navigation Error: SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://localhost:8080/fake-cdn/#/' cannot be created in a document with origin 'http://localhost:4200' and URL 'http://localhost:4200/thor/'.
</code></pre>

> Error is taken from the mini repo above
## 🌍 Your Environment

<pre><code>
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

**Anything else relevant?**
Extra relevant information in the minimum repo. The question/concern comes down to: 
* If the `deployUrl` is removed, will there be another way to accomplish a similar behavior of `deployUrl` without breaking the router?

**Comment by alan-agius4** [comment] 2022-05-03 17:24
Duplicate of https://github.com/angular/angular/issues/43303

**Closed by alan-agius4** 2022-05-03 17:24 UTC

**Comment by djhouseknecht** [comment] 2022-05-04 20:48
## Addressing the Duplicate Issue
From the duplicate issue, [it states that:](https://github.com/angular/angular/issues/43303#issuecomment-911466967)

> These are old techniques:
> 1. Hash location strategy, as you mentioned this is supported for old server setup and no a days most users should have transitioned towards the path location strategy.
> 2. CDN for assets only. This is also a relatively old technique which we don't recommand, we strongly recommand that the entire application is hosted on a CDN.

I would argue that albeity these are "old" techniques they are still very valid and have their place. For example: 

1. Not all Angular users will have access to the server to setup the server rewrite rules for the "modern" path strategy. 
    * In our use case, we are using Route 53 & cloudflare to host a S3 bucket for our organizations web apps. 
      These apps can be _any_ framework that the individual teams choose. Given some federal restrictions and 
      other organization audit rules, it is unfesible to setup individual apps with specific routing rules. 
2. All our assets and index files are already (technically) hosted on a CDN. One just has Route53 attatching it to a custom domain. 
    * the more traditional "cdn" is an S3 bucket with cloudflare, ie: 
        * `https://{cloudflare-hash}.cloudflare.com/{app-name}/{build-number}/...`
    * the "deployed" cdn has Route53 attatched to it so customers can load something like this: 
        * `https://apps.{our-domain}.com/{app-name}/#/`

Given our DevOps setups and legal restrictions, the above solution works perfectly. 

Also, a couple advantages of this setup: 
* It requires no extra server configuration for development teams to deploy or manage their web applications 
    (not to mention they can use whichever SPA framework they prefer). 
* We can deploy our apps' `index.html` file to _any_ location on the "deployed" cdn and not have to worry about the server rules. For example: 
    * We could have our prod version of the app deployed here: 
        * `https://apps.{our-domain}.com/{app-name}/#/`
    * And then have a "beta" version deployed here for testing and beta customers to use: 
        * `https://apps.{our-domain}.com/{app-name}/beta/#/`
    * We could do this with _any_ url naming scheme we want because the assets are on the cloudflare CDN 
      and the Angular app's hash routing does not care what the `window.location.pathname` is. 
        * Footnote: we set `<base href="">` to `window.location.pathname` to get this method to work. 

I could go into more detail, but I am mostly trying to share that the Hash routing and ability to load assets 
from a separate CDN are _huge_ advantages for us. The `deployUrl` made that possible and easy to configure. 

## My Current Solution
For anyone else coming here with the same question/issue, here is how we solved this for our angular apps 
([using the suggestion here](https://github.com/angular/angular/issues/43303#issuecomment-919095124)):

### app.module.ts

``` ts
/* other imports */
import { HashLocationStrategy } from '@angular/common';
import { Injectable } from '@angular/core';

@Injectable()
export class CustomLocationStrategy extends HashLocationStrategy {
  get baseHref () {
    return this['_baseHref'];
  }

  /**
   * Override this to use `APP_BASE_HREF` + '/#/' + desired angular route
   */
  override prepareExternalUrl (internal: string): string {
    const url = this.joinWithHash(this.baseHref, internal);
    return url;
  }

  private joinWithHash (baseHref: string, hashRoute: string): string {
    let url = baseHref || '/';

    if (!url.endsWith('/')) {
      url += '/';
    }

    if (!hashRoute.startsWith('#')) {
      url += '#';
    }

    url += hashRoute;

    return url;
  }
}

@NgModule({
  /* other stuff */
  providers: [
    /* tell the router to use the "deployed" cdn and not the `<base href="...">` value (which is the asset cdn) */
    { provide: APP_BASE_HREF, useValue: window.location.origin + window.location.pathname },
    /* use our new strategy to ensure we build out the correct urls for `window.location.pushState` (so it doesn't error) */
    { provide: LocationStrategy, useClass: CustomLocationStrategy }
  ]
})
export class AppModule { }
```

Then when we build: 
``` sh
ng build --configuration production --baseHref={our-cdn-url}
```

## Bug/Question

Looking over the code for [hash_location_strategy.ts](https://github.com/angular/angular/blob/478131c519cd3e12fbede458d5c6ecdc1ca0c9ce/packages/common/src/location/hash_location_strategy.ts#L73-L76), I am wondering why it handles the `APP_BASE_HREF` so differently then the [Path location_strategy](https://github.com/angular/angular/blob/478131c519cd3e12fbede458d5c6ecdc1ca0c9ce/packages/common/src/location/location_strategy.ts#L147-L149)?

``` ts
// hash_location_strategy.ts
override prepareExternalUrl(internal: string): string {
  const url = joinWithSlash(this._baseHref, internal);
  return url.length > 0 ? ('#' + url) : url;
}

// location_strategy.ts
override prepareExternalUrl(internal: string): string {
  return joinWithSlash(this._baseHref, internal);
}
```

For example, given: 
``` html
<!-- index.html -->
<head>
  <base href="https://cdn.com">
</head>
```
And: 
``` ts
// app.module.ts
  providers: [
    { provide: APP_BASE_HREF, useValue: 'https://example.com/' }
  ]
```
And an Angular route to `/home`, the two strategies behavior like:

* **PathLocationStrategy** respects the `APP_BASE_HREF`, ignores the `document`'s baseHref, and builds: 
    * `https://example.com/home`
* **HashLocationStrategy** _always_ uses the `document`'s baseHref and adds `APP_BASE_HREF` to the beginning of the Angular route:
    * `https://cdn.com/#/https://example.com/home`
    * desired would be the same as _PathLocationStrategy_, just with a `#` between the Angular route and `APP_BASE_HREF` like: 
        * `https://example.com/#/home`

@alan-agius4, I don't know a ton about the router's inner-workings aside from the research I've done into this issue, 
but would it make sense to have the `HashLocationStrategy` build URLs the same as `PathLocationStrategy` does with
respects to the `APP_BASE_HREF`? 

I'm not sure if this would break current hash based routers, but it seems reasonable to have these two strategies 
behave the same in regards to the `APP_BASE_HREF`.
