### ISSUE TITLE
Failed to build project with Angular CLI 11.0.3

### ISSUE THREAD

**Issue by eastyu** [angular/angular-cli#19541] opened 2020-12-03 15:08 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11.0.2

### Description

 It fails to build a new fresh project

## 🔬 Minimal Reproduction

Step to reproduce:
1. ```ng new webapp```
2. ```ng build --prod```
## 🔥 Exception or Error
<pre>

Compiling @angular/animations : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
⠹ Generating browser application bundles (phase: building)...## There is an issue with `node-fibers` ##
`/Users/user/webapp/node_modules/fibers/bin/darwin-x64-88/fibers.node` is missing.

Try running this to fix the issue: /usr/local/bin/node /Users/user/webapp/node_modules/fibers/build
Error: Cannot find module '/Users/user/webapp/node_modules/fibers/bin/darwin-x64-88/fibers'
Require stack:
- /Users/user/webapp/node_modules/fibers/fibers.js
- /Users/user/webapp/node_modules/sass-loader/dist/utils.js
- /Users/user/webapp/node_modules/sass-loader/dist/index.js
- /Users/user/webapp/node_modules/sass-loader/dist/cjs.js
- /Users/user/webapp/node_modules/loader-runner/lib/loadLoader.js
- /Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/user/webapp/node_modules/webpack/lib/NormalModule.js
- /Users/user/webapp/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/user/webapp/node_modules/webpack/lib/Compiler.js
- /Users/user/webapp/node_modules/webpack/lib/webpack.js
- /Users/user/webapp/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
- /Users/user/webapp/node_modules/@angular-devkit/build-webpack/src/index.js
- /Users/user/webapp/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /Users/user/webapp/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/user/webapp/node_modules/@angular-devkit/architect/node/index.js
- /Users/user/webapp/node_modules/@angular/cli/models/architect-command.js
- /Users/user/webapp/node_modules/@angular/cli/commands/build-impl.js
- /Users/user/webapp/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/user/webapp/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/user/webapp/node_modules/@angular/cli/utilities/json-schema.js
- /Users/user/webapp/node_modules/@angular/cli/models/command-runner.js
- /Users/user/webapp/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/user/webapp/node_modules/fibers/fibers.js:14:39)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at getSassOptions (/Users/user/webapp/node_modules/sass-loader/dist/utils.js:134:25)
    at Object.loader (/Users/user/webapp/node_modules/sass-loader/dist/index.js:36:49)
    at LOADER_EXECUTION (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
⠸ Generating browser application bundles (phase: building)...## There is an issue with `node-fibers` ##
`/Users/user/webapp/node_modules/fibers/bin/darwin-x64-88/fibers.node` is missing.

Try running this to fix the issue: /usr/local/bin/node /Users/user/webapp/node_modules/fibers/build
Error: Cannot find module '/Users/user/webapp/node_modules/fibers/bin/darwin-x64-88/fibers'
Require stack:
- /Users/user/webapp/node_modules/fibers/fibers.js
- /Users/user/webapp/node_modules/sass-loader/dist/utils.js
- /Users/user/webapp/node_modules/sass-loader/dist/index.js
- /Users/user/webapp/node_modules/sass-loader/dist/cjs.js
- /Users/user/webapp/node_modules/loader-runner/lib/loadLoader.js
- /Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/user/webapp/node_modules/webpack/lib/NormalModule.js
- /Users/user/webapp/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/user/webapp/node_modules/webpack/lib/Compiler.js
- /Users/user/webapp/node_modules/webpack/lib/webpack.js
- /Users/user/webapp/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
- /Users/user/webapp/node_modules/@angular-devkit/build-webpack/src/index.js
- /Users/user/webapp/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /Users/user/webapp/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/user/webapp/node_modules/@angular-devkit/architect/node/index.js
- /Users/user/webapp/node_modules/@angular/cli/models/architect-command.js
- /Users/user/webapp/node_modules/@angular/cli/commands/build-impl.js
- /Users/user/webapp/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/user/webapp/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/user/webapp/node_modules/@angular/cli/utilities/json-schema.js
- /Users/user/webapp/node_modules/@angular/cli/models/command-runner.js
- /Users/user/webapp/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/user/webapp/node_modules/fibers/fibers.js:14:39)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at getSassOptions (/Users/user/webapp/node_modules/sass-loader/dist/utils.js:134:25)
    at Object.loader (/Users/user/webapp/node_modules/sass-loader/dist/index.js:36:49)
    at LOADER_EXECUTION (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
✔ Browser application bundle generation complete.

Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binary. See message above.
    at Object.<anonymous> (/Users/user/webapp/node_modules/fibers/fibers.js:23:9)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at getSassOptions (/Users/user/webapp/node_modules/sass-loader/dist/utils.js:134:25)
    at Object.loader (/Users/user/webapp/node_modules/sass-loader/dist/index.js:36:49)
    at /Users/user/webapp/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at VirtualFileSystemDecorator.readFile (/Users/user/webapp/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:44:13)
    at processResource (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at iteratePitchingLoaders (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/Users/user/webapp/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at iteratePitchingLoaders (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/user/webapp/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/Users/user/webapp/node_modules/loader-runner/lib/loadLoader.js:47:3)
 @ multi ./node_modules/@angular/material/prebuilt-themes/indigo-pink.css ./src/styles.scss styles[1]

Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binary. See message above.
    at Object.<anonymous> (/Users/user/webapp/node_modules/fibers/fibers.js:23:9)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at getSassOptions (/Users/user/webapp/node_modules/sass-loader/dist/utils.js:134:25)
    at Object.loader (/Users/user/webapp/node_modules/sass-loader/dist/index.js:36:49)

Error: ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/postcss-loader/dist/cjs.js??ref--13-2!./node_modules/resolve-url-loader??ref--13-3!./node_modules/sass-loader/dist/cjs.js??ref--13-4!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binary. See message above.
    at Object.<anonymous> (/Users/user/webapp/node_modules/fibers/fibers.js:23:9)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at getSassOptions (/Users/user/webapp/node_modules/sass-loader/dist/utils.js:134:25)
    at Object.loader (/Users/user/webapp/node_modules/sass-loader/dist/index.js:36:49)
</pre>

## 🌍 Your Environment
<pre>

Angular CLI: 11.0.3
Node: 15.2.1
OS: darwin x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@angular/cdk                    11.0.1
@angular/material               11.0.1
@schematics/angular             11.0.3
@schematics/update              0.1100.3
rxjs                            6.6.3
typescript                      4.0.5
</pre>

**Anything else relevant?**

My OS version is macOS Big Sur 11.0.1

**Comment by clydin** [comment] 2020-12-03 15:41
Unfortunately, we are unable to reproduce the issue via the provided reproduction steps.
Was the `fibers` package manually installed after creating the project?  The `fibers` package is not installed by default and must be manually installed to opt-in to its usage with Sass compilation.  From the error, it appears that the installation of the `fibers` package did not fully succeed or was initially installed on an older version of Node.js.  The `fibers` package uses a native module which may need to be built on installation depending on the version of Node.js and the operating system.  If this is the case, then deleting the project's `node_modules` directory and then re-installing should rectify the issue.

**Comment by eastyu** [comment] 2020-12-03 15:58
@clydin thanks for response. I didn't install fibers manually after creating the project. And I checked my node_modules folder, there is fibers folder, but no ```darwin-x64-88``` under the bin folder. There are only ```darwin-x64-83``` and ```darwin-x64-72``` for my macOS. Why it is looking for ```darwin-x64-88```? Is this version related?

**Comment by alan-agius4** [comment] 2020-12-04 07:20
The `darwin-x64-88` binary is required for Node.js 15, however `fibers` doesn't yet support this version. https://www.npmjs.com/package/fibers#supported-platforms

From my experience, they will support only Node.js versions which will become LTS. This is because odd versions of Node.js are prerelease versions and will become unsupported after 6 months. https://nodejs.org/en/about/releases/

There are 2 things you can do.
1) As @clydin mentioned using `fibers` is opt-in, you can opt-out at any time by running `npm uninstall fibers`
2) Another alternative would be to use an LTS version of Node.Js such as v14

Closing as there is nothing we can do from our end.

**Closed by alan-agius4** 2020-12-04 07:20 UTC
Labels: need: more info

**Comment by alan-agius4** [comment] 2020-12-13 19:36
Earlier versions of NPM 7 has a bug were optional peer dependencies are installed.
