### ISSUE TITLE
Angular CLI 1.6.3 Missing Dependency Errors from npm

### ISSUE THREAD

**Issue by TheSamsterZA** [angular/angular-cli#9010] opened 2017-12-27 22:17 UTC
### Versions
```
Angular CLI: 1.6.3
Node: 8.9.3
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

1. `ng new myapp --routing`
2. `cd myapp`
3. `npm list --depth=0`

### Observed behavior
Step 3 errors with:
```
+-- @angular/animations@5.1.2
+-- @angular/cli@1.6.3
+-- @angular/common@5.1.2
+-- @angular/compiler@5.1.2
+-- @angular/compiler-cli@5.1.2
+-- @angular/core@5.1.2
+-- @angular/forms@5.1.2
+-- @angular/http@5.1.2
+-- @angular/language-service@5.1.2
+-- @angular/platform-browser@5.1.2
+-- @angular/platform-browser-dynamic@5.1.2
+-- @angular/router@5.1.2
+-- @types/jasmine@2.5.54
+-- @types/jasminewd2@2.0.3
+-- @types/node@6.0.95
+-- codelyzer@4.0.2
+-- core-js@2.5.3
+-- jasmine-core@2.6.4
+-- jasmine-spec-reporter@4.1.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.1.1
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.3
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.1.2
+-- rxjs@5.5.6
+-- ts-node@3.2.2
+-- tslint@5.7.0
+-- typescript@2.4.2
`-- zone.js@0.8.18

npm ERR! missing: hawk@3.1.3, required by node-pre-gyp@0.6.39
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.6.39
npm ERR! missing: rimraf@2.6.1, required by node-pre-gyp@0.6.39
npm ERR! missing: tar@2.2.1, required by node-pre-gyp@0.6.39
npm ERR! missing: boom@2.10.1, required by hawk@3.1.3
npm ERR! missing: cryptiles@2.0.5, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by hawk@3.1.3
npm ERR! missing: sntp@1.0.9, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by boom@2.10.1
npm ERR! missing: boom@2.10.1, required by cryptiles@2.0.5
npm ERR! missing: hoek@2.16.3, required by sntp@1.0.9
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.0
npm ERR! missing: readable-stream@2.2.9, required by are-we-there-yet@1.1.4
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: combined-stream@1.0.5, required by request@2.81.0
npm ERR! missing: hawk@3.1.3, required by request@2.81.0
npm ERR! missing: mime-types@2.1.15, required by request@2.81.0
npm ERR! missing: safe-buffer@5.0.1, required by request@2.81.0
npm ERR! missing: delayed-stream@1.0.0, required by combined-stream@1.0.5
npm ERR! missing: combined-stream@1.0.5, required by form-data@2.1.4
npm ERR! missing: mime-types@2.1.15, required by form-data@2.1.4
npm ERR! missing: extsprintf@1.0.2, required by jsprim@1.4.0
npm ERR! missing: extsprintf@1.0.2, required by verror@1.3.6
npm ERR! missing: mime-db@1.27.0, required by mime-types@2.1.15
npm ERR! missing: safe-buffer@5.0.1, required by tunnel-agent@0.6.0
npm ERR! missing: glob@7.1.2, required by rimraf@2.6.1
npm ERR! missing: fs.realpath@1.0.0, required by glob@7.1.2
npm ERR! missing: inflight@1.0.6, required by glob@7.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: path-is-absolute@1.0.1, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: brace-expansion@1.1.7, required by minimatch@3.0.4
npm ERR! missing: balanced-match@0.4.2, required by brace-expansion@1.1.7
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.7
npm ERR! missing: block-stream@0.0.9, required by tar@2.2.1
npm ERR! missing: fstream@1.0.11, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by block-stream@0.0.9
npm ERR! missing: graceful-fs@4.1.11, required by fstream@1.0.11
npm ERR! missing: inherits@2.0.3, required by fstream@1.0.11
npm ERR! missing: mkdirp@0.5.1, required by fstream@1.0.11
npm ERR! missing: rimraf@2.6.1, required by fstream@1.0.11
npm ERR! missing: fstream@1.0.11, required by tar-pack@3.4.0
npm ERR! missing: once@1.4.0, required by tar-pack@3.4.0
npm ERR! missing: readable-stream@2.2.9, required by tar-pack@3.4.0
npm ERR! missing: rimraf@2.6.1, required by tar-pack@3.4.0
npm ERR! missing: tar@2.2.1, required by tar-pack@3.4.0
npm ERR! missing: fstream@1.0.11, required by fstream-ignore@1.0.5
npm ERR! missing: inherits@2.0.3, required by fstream-ignore@1.0.5
npm ERR! missing: minimatch@3.0.4, required by fstream-ignore@1.0.5
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: buffer-shims@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: core-util-is@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.2.9
npm ERR! missing: isarray@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: process-nextick-args@1.0.7, required by readable-stream@2.2.9
npm ERR! missing: string_decoder@1.0.1, required by readable-stream@2.2.9
npm ERR! missing: util-deprecate@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: safe-buffer@5.0.1, required by string_decoder@1.0.1
```

### Desired behavior

No warnings/errors from npm by using the Angular CLI.

### Mention any other details that might be useful (optional)

Follow-on from #8767.

[As I mentioned before](https://github.com/angular/angular-cli/issues/8767#issuecomment-350865848), this is detrimental to the first-run experience for new users. I am training my team and telling them to ignore this without adequately explaining why makes me feel like I don't really understand how this should work. Please take heed: **I'd much prefer it if installing and using the Angular CLI did not throw up things that might cause issues down the line.**

**Comment by TheSamsterZA** [comment] 2017-12-27 22:54
FYI I am getting the same errors from npm on @angular/cli@1.6.0. @filipesilva please have a look.

**Comment by filipesilva** [comment] 2017-12-28 08:49
I can reproduce the errors you are seeing:

```
kamik@T460p MINGW64 /d/sandbox
$ npm install -g @angular/cli@1.6.3
C:\Program Files\nodejs\ng -> C:\Program Files\nodejs\node_modules\@angular\cli\bin\ng

> node-sass@4.7.2 install C:\Program Files\nodejs\node_modules\@angular\cli\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\kamik\AppData\Roaming\npm-cache\node-sass\4.7.2\win32-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Program Files\nodejs\node_modules\@angular\cli\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.7.2 postinstall C:\Program Files\nodejs\node_modules\@angular\cli\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\kamik\AppData\Roaming\nvm\v8.9.1\node_modules\@angular\cli\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/cli@1.6.3
added 855 packages in 26.674s

kamik@T460p MINGW64 /d/sandbox
$ ng new myapp --routing
  create myapp/e2e/app.e2e-spec.ts (287 bytes)
  create myapp/e2e/app.po.ts (208 bytes)
  create myapp/e2e/tsconfig.e2e.json (235 bytes)
  create myapp/karma.conf.js (923 bytes)
  create myapp/package.json (1317 bytes)
  create myapp/protractor.conf.js (722 bytes)
  create myapp/README.md (1021 bytes)
  create myapp/tsconfig.json (363 bytes)
  create myapp/tslint.json (3040 bytes)
  create myapp/.angular-cli.json (1240 bytes)
  create myapp/.editorconfig (245 bytes)
  create myapp/.gitignore (516 bytes)
  create myapp/src/assets/.gitkeep (0 bytes)
  create myapp/src/environments/environment.prod.ts (51 bytes)
  create myapp/src/environments/environment.ts (387 bytes)
  create myapp/src/favicon.ico (5430 bytes)
  create myapp/src/index.html (292 bytes)
  create myapp/src/main.ts (370 bytes)
  create myapp/src/polyfills.ts (2405 bytes)
  create myapp/src/styles.css (80 bytes)
  create myapp/src/test.ts (1085 bytes)
  create myapp/src/tsconfig.app.json (211 bytes)
  create myapp/src/tsconfig.spec.json (304 bytes)
  create myapp/src/typings.d.ts (104 bytes)
  create myapp/src/app/app-routing.module.ts (245 bytes)
  create myapp/src/app/app.module.ts (395 bytes)
  create myapp/src/app/app.component.html (1173 bytes)
  create myapp/src/app/app.component.spec.ts (1103 bytes)
  create myapp/src/app/app.component.ts (207 bytes)
  create myapp/src/app/app.component.css (0 bytes)
Installing packages for tooling via npm.

> node-sass@4.7.2 install D:\sandbox\myapp\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\kamik\AppData\Roaming\npm-cache\node-sass\4.7.2\win32-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\sandbox\myapp\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.7.2 postinstall D:\sandbox\myapp\node_modules\node-sass
> node scripts/build.js

Binary found at D:\sandbox\myapp\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
npm WARN @angular/http@5.1.0 requires a peer of @angular/core@5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@5.1.0 requires a peer of @angular/platform-browser@5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1027 packages in 34.791s
Installed packages for tooling via npm.
Successfully initialized git.
Project 'myapp' successfully created.

kamik@T460p MINGW64 /d/sandbox
$ cd myapp/

kamik@T460p MINGW64 /d/sandbox/myapp (master)
$ npm list --depth=0
myapp@0.0.0 D:\sandbox\myapp
+-- @angular/animations@5.1.2
+-- @angular/cli@1.6.3
+-- @angular/common@5.1.2
+-- @angular/compiler@5.1.2
+-- @angular/compiler-cli@5.1.2
+-- UNMET PEER DEPENDENCY @angular/core@5.1.2
+-- @angular/forms@5.1.2
+-- @angular/http@5.1.0
+-- @angular/language-service@5.1.2
+-- UNMET PEER DEPENDENCY @angular/platform-browser@5.1.2
+-- @angular/platform-browser-dynamic@5.1.2
+-- @angular/router@5.1.2
+-- @types/jasmine@2.5.54
+-- @types/jasminewd2@2.0.3
+-- @types/node@6.0.92
+-- codelyzer@4.0.1
+-- core-js@2.5.1
+-- jasmine-core@2.6.4
+-- jasmine-spec-reporter@4.1.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.1.1
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.0
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.1.2
+-- rxjs@5.5.5
+-- ts-node@3.2.2
+-- tslint@5.7.0
+-- typescript@2.4.2
`-- zone.js@0.8.18

npm ERR! peer dep missing: @angular/core@5.1.0, required by @angular/http@5.1.0
npm ERR! peer dep missing: @angular/platform-browser@5.1.0, required by @angular/http@5.1.0
npm ERR! missing: hawk@3.1.3, required by node-pre-gyp@0.6.39
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.6.39
npm ERR! missing: rimraf@2.6.1, required by node-pre-gyp@0.6.39
npm ERR! missing: tar@2.2.1, required by node-pre-gyp@0.6.39
npm ERR! missing: boom@2.10.1, required by hawk@3.1.3
npm ERR! missing: cryptiles@2.0.5, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by hawk@3.1.3
npm ERR! missing: sntp@1.0.9, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by boom@2.10.1
npm ERR! missing: boom@2.10.1, required by cryptiles@2.0.5
npm ERR! missing: hoek@2.16.3, required by sntp@1.0.9
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.0
npm ERR! missing: readable-stream@2.2.9, required by are-we-there-yet@1.1.4
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: combined-stream@1.0.5, required by request@2.81.0
npm ERR! missing: hawk@3.1.3, required by request@2.81.0
npm ERR! missing: mime-types@2.1.15, required by request@2.81.0
npm ERR! missing: safe-buffer@5.0.1, required by request@2.81.0
npm ERR! missing: delayed-stream@1.0.0, required by combined-stream@1.0.5
npm ERR! missing: combined-stream@1.0.5, required by form-data@2.1.4
npm ERR! missing: mime-types@2.1.15, required by form-data@2.1.4
npm ERR! missing: extsprintf@1.0.2, required by jsprim@1.4.0
npm ERR! missing: extsprintf@1.0.2, required by verror@1.3.6
npm ERR! missing: mime-db@1.27.0, required by mime-types@2.1.15
npm ERR! missing: safe-buffer@5.0.1, required by tunnel-agent@0.6.0
npm ERR! missing: glob@7.1.2, required by rimraf@2.6.1
npm ERR! missing: fs.realpath@1.0.0, required by glob@7.1.2
npm ERR! missing: inflight@1.0.6, required by glob@7.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: path-is-absolute@1.0.1, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: brace-expansion@1.1.7, required by minimatch@3.0.4
npm ERR! missing: balanced-match@0.4.2, required by brace-expansion@1.1.7
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.7
npm ERR! missing: block-stream@0.0.9, required by tar@2.2.1
npm ERR! missing: fstream@1.0.11, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by block-stream@0.0.9
npm ERR! missing: graceful-fs@4.1.11, required by fstream@1.0.11
npm ERR! missing: inherits@2.0.3, required by fstream@1.0.11
npm ERR! missing: mkdirp@0.5.1, required by fstream@1.0.11
npm ERR! missing: rimraf@2.6.1, required by fstream@1.0.11
npm ERR! missing: fstream@1.0.11, required by tar-pack@3.4.0
npm ERR! missing: once@1.4.0, required by tar-pack@3.4.0
npm ERR! missing: readable-stream@2.2.9, required by tar-pack@3.4.0
npm ERR! missing: rimraf@2.6.1, required by tar-pack@3.4.0
npm ERR! missing: tar@2.2.1, required by tar-pack@3.4.0
npm ERR! missing: fstream@1.0.11, required by fstream-ignore@1.0.5
npm ERR! missing: inherits@2.0.3, required by fstream-ignore@1.0.5
npm ERR! missing: minimatch@3.0.4, required by fstream-ignore@1.0.5
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: buffer-shims@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: core-util-is@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.2.9
npm ERR! missing: isarray@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: process-nextick-args@1.0.7, required by readable-stream@2.2.9
npm ERR! missing: string_decoder@1.0.1, required by readable-stream@2.2.9
npm ERR! missing: util-deprecate@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: safe-buffer@5.0.1, required by string_decoder@1.0.1
```

But I also find this behaviour odd, because I know the install did not fail in any way. So I try to look up one of the dependencies listed as missing:
```
$ npm list safe-buffer
myapp@0.0.0 D:\sandbox\myapp
+-- @angular/cli@1.6.3
| +-- less@2.7.3
| | `-- request@2.81.0
| |   +-- safe-buffer@5.1.1  deduped
| |   `-- tunnel-agent@0.6.0
| |     `-- safe-buffer@5.1.1  deduped
| +-- memory-fs@0.4.1
| | `-- readable-stream@2.3.3
| |   +-- safe-buffer@5.1.1  deduped
| |   `-- string_decoder@1.0.3
| |     `-- safe-buffer@5.1.1  deduped
| +-- uglifyjs-webpack-plugin@1.1.5
| | `-- cacache@10.0.1
| |   `-- ssri@5.0.0
| |     `-- safe-buffer@5.1.1  deduped
| +-- webpack@3.10.0
| | `-- node-libs-browser@2.1.0
| |   `-- crypto-browserify@3.12.0
| |     +-- browserify-cipher@1.0.0
| |     | +-- browserify-aes@1.1.1
| |     | | `-- safe-buffer@5.1.1  deduped
| |     | `-- evp_bytestokey@1.0.3
| |     |   +-- md5.js@1.3.4
| |     |   | `-- hash-base@3.0.4
| |     |   |   `-- safe-buffer@5.1.1  deduped
| |     |   `-- safe-buffer@5.1.1  deduped
| |     +-- create-hash@1.1.3
| |     | +-- cipher-base@1.0.4
| |     | | `-- safe-buffer@5.1.1  deduped
| |     | `-- sha.js@2.4.9
| |     |   `-- safe-buffer@5.1.1  deduped
| |     +-- create-hmac@1.1.6
| |     | `-- safe-buffer@5.1.1  deduped
| |     +-- pbkdf2@3.0.14
| |     | `-- safe-buffer@5.1.1  deduped
| |     +-- randombytes@2.0.5
| |     | `-- safe-buffer@5.1.1  deduped
| |     `-- randomfill@1.0.3
| |       `-- safe-buffer@5.1.1  deduped
| `-- webpack-dev-server@2.9.7
|   +-- bonjour@3.5.0
|   | `-- multicast-dns@6.2.1
|   |   `-- dns-packet@1.2.2
|   |     `-- safe-buffer@5.1.1  deduped
|   +-- compression@1.7.1
|   | `-- safe-buffer@5.1.1  deduped
|   +-- express@4.16.2
|   | `-- safe-buffer@5.1.1  deduped
|   `-- spdy@3.4.7
|     +-- safe-buffer@5.1.1  deduped
|     `-- spdy-transport@2.0.20
|       `-- safe-buffer@5.1.1  deduped
+-- @angular/compiler-cli@5.1.2
| `-- chokidar@1.7.0
|   `-- UNMET OPTIONAL DEPENDENCY fsevents@1.1.3
|     `-- UNMET OPTIONAL DEPENDENCY node-pre-gyp@0.6.39
|       +-- UNMET OPTIONAL DEPENDENCY request@2.81.0
|       | +-- UNMET DEPENDENCY safe-buffer@5.0.1
|       | `-- UNMET OPTIONAL DEPENDENCY tunnel-agent@0.6.0
|       |   `-- UNMET DEPENDENCY safe-buffer@5.0.1
|       `-- UNMET OPTIONAL DEPENDENCY tar-pack@3.4.0
|         `-- UNMET DEPENDENCY readable-stream@2.2.9
|           `-- UNMET DEPENDENCY string_decoder@1.0.1
|             `-- UNMET DEPENDENCY safe-buffer@5.0.1
`-- karma@1.7.1
  `-- safe-buffer@5.1.1
```

It looks like the dependencies listed as missing are part of `fsevents`, which is an optional dependency of `chokidar`. Specifically, `fsevents` is not installable on Windows, so it is expected that it isn't there.

I don't know why `npm list` shows optional dependencies as missing though. I checked the npm issue tracker and found an issue for this: https://github.com/npm/npm/issues/19393. I'm closing this one in favor of that one since the problem seems to be in npm.

**Closed by filipesilva** 2017-12-28 08:49 UTC

**Comment by TheSamsterZA** [comment] 2017-12-28 23:37
@filipesilva I can confirm that downgrading from **npm@5.6.0** to **npm@5.5.1** fixes this issue. Sorry about that, and thanks for jumping onto this so quickly! Happy holidays! :tada:

**Comment by Alecto** [comment] 2018-01-25 09:39
i have the same error.
