### ISSUE TITLE
Peer dependencies missing @angular/cli@1.0.0-beta.31

### ISSUE THREAD

**Issue by d3lm** [angular/angular-cli#4583] opened 2017-02-10 09:38 UTC
I just tried to install the latest version of the angular-cli `@angular/cli@1.0.0-beta.31`. The installation ends with warnings, however, when I try to run `ng serve` I get the following error:

```
Cannot find module '@angular/compiler-cli'
Error: Cannot find module '@angular/compiler-cli'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:5:24)
```
Also if I run `npm list -g --depth=0` I get the following errors:

```
npm ERR! peer dep missing: @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0, required by @ngtools/webpack@1.2.9
npm ERR! peer dep missing: @angular/compiler-cli@^2.3.1 || >=4.0.0-beta <5.0.0, required by @ngtools/webpack@1.2.9
npm ERR! peer dep missing: @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0, required by @ngtools/webpack@1.2.9
npm ERR! peer dep missing: @angular/tsc-wrapped@^0.5.0, required by @ngtools/webpack@1.2.9
```

I am running on a Mac (El Capitan 10.11.6) and `ng -v` outputs the following:

```
@angular/cli: 1.0.0-beta.31
node: 7.4.0
os: darwin x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/flex-layout: 2.0.0-beta.4
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1
```

**Comment by filipesilva** [comment] 2017-02-10 10:33
Dupe of https://github.com/angular/angular-cli/issues/4575

**Closed by filipesilva** 2017-02-10 10:33 UTC
