### ISSUE TITLE
Component remove miss entries in app.module.ts

### ISSUE THREAD

**Issue by fhdk** [angular/angular-cli#1660] opened 2016-08-12 06:56 UTC
**1. OS**
Linux 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux

**2. Versions.**
angular-cli: local (v1.0.0-beta.11-webpack.2, branch: master)
node: 6.3.1

**3. Repro steps.**
`ng new dash`
`cd dash`
`ng generate component dashboard`
`ng remove component dashboard`
`ng serve`

**4. The log**
Version: webpack 2.1.0-beta.18
Time: 6257ms
              Asset       Size  Chunks             Chunk Names
     main.bundle.js    3.05 MB    0, 2  [emitted]  main
polyfills.bundle.js     231 kB    1, 2  [emitted]  polyfills
          inline.js    4.96 kB       2  [emitted]  inline
           main.map    3.59 MB    0, 2  [emitted]  main
      polyfills.map     287 kB    1, 2  [emitted]  polyfills
         inline.map    5.13 kB       2  [emitted]  inline
         index.html  477 bytes          [emitted]  

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './sidebar/sidebar.component' in '/mnt/development/dash/src/app'
 @ ./src/app/app.module.ts 20:0-63
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in [default] /mnt/development/dash/src/app/app.module.ts:12:33 
Cannot find module './sidebar/sidebar.component'.

**5. Mention any other details that might be useful.**
N/A

**Comment by filipesilva** [comment] 2016-08-18 03:29
Dupe of https://github.com/angular/angular-cli/issues/900.

Basically, we don't really implement the `ng remove` command overall. It's still there as an `ember-cli` one.

**Closed by filipesilva** 2016-08-18 03:29 UTC
