### ISSUE TITLE
Failed to load  angular2-in-memory-web-api with the webpack commit on master

### ISSUE THREAD

**Issue by lcantat** [angular/angular-cli#1498] opened 2016-07-30 08:27 UTC
**1. OS : Windows 7**
**2. Versions**.  

```
angular2-in-memory-web-api": "0.0.14
angular-cli: local (v1.0.0-beta.10, branch: master)
commit d5e1c55ecb5d3cc7853bf575e5dc6f72902ec4ef: "build: Use webpack as our backend for building CLI apps."
```
**3. Repro steps.** 

code of app bootstraping :
```
import { XHRBackend, HTTP_PROVIDERS } from '@angular/http';
import { InMemoryBackendService, SEED_DATA }  from 'angular2-in-memory-web-api';

bootstrap(AppComponent, [
    HTTP_PROVIDERS,
   { provide: XHRBackend, useClass: InMemoryBackendService },
    { provide: SEED_DATA,  useClass: HeroData }                           
  HTTP_PROVIDERS,
  AppRouterProviders
])
```

**4. The log given by the failure.**
```
WARNING in ./~/angular2-in-memory-web-api/http-status-codes.js
Cannot find SourceMap 'http-status-codes.js.map': Error: Can't resolve './http-status-codes.js.map' in '\node_modules\angular2-in-memory-web-api'
 @ ./~/angular2-in-memory-web-api/index.js 6:9-39
 @ ./src/main.ts
 @ multi main
```

**5. Mention any other details that might be useful.**
I think that such things can be solved using webpack configuration, but I don't know where to modify the webpack configuration file in a project generated with angular-cli

**Comment by un33k** [comment] 2016-07-30 13:03
Seeing the same with ng2-redux package.

```typescript
import { NgRedux } from 'ng2-redux';
bootstrap(AppComponent, [
    NgRedux,
    HTTP_PROVIDERS
  ]);
```

```log
WARNING in ./~/ng2-redux/lib/utils/invariant.js
Cannot find source file '../../src/utils/invariant.ts': Error: Can't resolve '../../src/utils/invariant.ts' in '/code/node_modules/ng2-redux/lib/utils'
 @ ./~/ng2-redux/lib/components/ng-redux.js 27:18-47
 @ ./~/ng2-redux/lib/index.js
 @ ./src/main.ts
 @ multi main
```

**Comment by filipesilva** [comment] 2016-07-30 16:24
Duplicate of https://github.com/angular/angular-cli/issues/1482 I believe.

**Closed by filipesilva** 2016-07-30 16:24 UTC

**Comment by CalvinDale** [comment] 2016-08-04 20:44
I'm also experiencing the same behavior with the `ng2-redux` library mentioned by @un33k. This thread, the duplicate thread and its related links haven't so far clued me into a way to resolve this issue. And `ng2-redux` functionality isn't working with these warnings.

**Comment by SethDavenport** [comment] 2016-08-05 03:41
I've used ng2-redux with webpack 1 fine in several projects. However these warnings are very strange - why is the CLI looking for `.ts` files?  Ng2-Redux, while written in typescript, doesn't expose its typescript source in npm. We publish the transpiled code and a type definitions file.

I'm stumped as to where the `../../src/index.ts` path is even coming from...

My best guess at this point is something unexpected with Typescript 2 or Webpack 2 (we typically use 1.8 and 1.13 respectively).

**Comment by SethDavenport** [comment] 2016-08-05 03:47
OK those paths are in the source map in our case.
