### ISSUE TITLE
Unable to create library

### ISSUE THREAD

**Issue by guysenpai** [angular/angular-cli#11014] opened 2018-05-25 12:16 UTC
### Versions
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.3
Node: 9.11.1
OS: darwin x64
Angular: 6.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cdk                      6.1.0
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.1.0
@angular/pwa                      0.6.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
 ng generate library modulo-theme --prefix mod
Unexpected token } in JSON at position 581
error Command failed with exit code 1.
```

### Desired behavior

I want to generate a library

**Comment by hamoom** [comment] 2018-05-25 18:35
having a similar issue

ng generate library aa-header
Unexpected token ] in JSON at position 863

**Comment by hamoom** [comment] 2018-05-25 21:19
I had this trailing comma in my styles in my angular.json file.  it was causing the error.

```
            "styles": [
              "src/styles.css",
            ],
```

**Comment by hansl** [comment] 2018-06-07 18:03
We have a fix for this. In the meantime this is a dupe of https://github.com/angular/angular-cli/issues/10757.

**Closed by hansl** 2018-06-07 18:03 UTC
Labels: comp: cli/generate
