### ISSUE TITLE
Angular CLI does not apply custom webpack loader 

### ISSUE THREAD

**Issue by abadakhshan** [angular/angular-cli#18474] opened 2020-08-07 06:37 UTC
Angular CLI does not apply custom webpack loader 

I define custom webpack and add a custom loader for ts or html files but loader transformation does not apply on output.

it seems that Angular CLI uses its own mechanism for reading files.

https://github.com/angular/angular-cli/blob/e8e832e5a8b8e0311725bcdd60b6990e6d6c0236/packages/ngtools/webpack/src/compiler_host.ts#L182

Sample repository: https://github.com/abadakhshan/test-custom-loader

**Comment by alan-agius4** [comment] 2020-08-07 08:21
Duplicate of https://github.com/angular/angular-cli/issues/16544

**Closed by alan-agius4** 2020-08-07 08:21 UTC

**Comment by abadakhshan** [comment] 2020-08-07 09:34
What is the alternative solution to this problem?
Is it possible that we have transformers for all files like we have for index.html?

**Comment by alan-agius4** [comment] 2020-08-07 10:39
The alternatives depend on what you are trying achieve with your "loader".

**Comment by abadakhshan** [comment] 2020-08-07 15:04
Hi @alan-agius4 
I want to do some transformation on HTML files before angular compilition.
I use this approache to apply Html template merging

**Comment by alan-agius4** [comment] 2020-08-07 15:30
You need to disable `directTemplateLoading` of the `angularCompilerPlugin` via a custom builder.

See http://github.com/angular/angular-cli/issues/15861 for some more context.

**Note: this approach is not supported by the Angular tooling team.**
