### ISSUE TITLE
ng serve too slow in v11

### ISSUE THREAD

**Issue by MursalovAltun** [angular/angular-cli#20089] opened 2021-02-19 07:21 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
on angular v10 it took 3-6 seconds to recompile on changes, now this value is around 30-40 seconds

### Description

After upgrading to angular v11 ng serve become too slow

## 🔬 Minimal Reproduction

Just create a new project via CLI and run ng serve. 

## 🔥 Exception or Error

No exceptions or errors

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.1
Node: 14.15.5
OS: linux x64

Angular: 11.2.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1102.1
@angular-devkit/build-angular     0.1102.1
@angular-devkit/build-optimizer   0.1102.1
@angular-devkit/core              11.2.1
@angular-devkit/schematics        11.2.1
@schematics/angular               11.2.1
@schematics/update                0.1102.1
rxjs                              6.6.3
typescript                        4.0.5

</code></pre>

**Comment by alan-agius4** [comment] 2021-02-19 07:34
Duplicate of https://github.com/angular/angular/issues/40635

**Closed by alan-agius4** 2021-02-19 07:34 UTC
