### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by RaedsLab** [angular/angular-cli#8418] opened 2017-11-09 10:21 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.

@angular/cli: 1.4.6
node: 6.10.3
os: win32 x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.12-a7faebc
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.12-a7faebc
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.6
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.6.0-rc

### Repro steps.

There is no way to pass a variable from ng command to application, like in node applications.

```sh
MYAPIKEY=XYZ ng serve
```

### Desired functionality.

To have something like

```js
process.env
```

**Comment by scurk1415** [comment] 2017-11-10 11:03
You can have multiple environments.

make a new environment `environment.test.ts` add it in you app cli config 

`"environments": {
        "dev": "environments/environment.ts",
        "test": "environments/environment.test.ts",
        "prod": "environments/environment.prod.ts"
      }`

and run it wit h `ng serve --env=test`

**Comment by RaedsLab** [comment] 2017-11-10 11:06
Yes, 

But that requires creating different files, I would like for example to set a URL that changes every build, it would be very impractical to create a new environment file every time.

**Comment by RaedsLab** [comment] 2017-11-13 10:39
up?

**Comment by Brocco** [comment] 2017-11-14 18:12
Duplicate of #4419

**Closed by Brocco** 2017-11-14 18:12 UTC
