### ISSUE TITLE
Class constructor cannot be invoked without 'new' after upgrading to Angular 10

### ISSUE THREAD

**Issue by FrancescoBorzi** [angular/angular-cli#18067] opened 2020-06-29 09:45 UTC
# 🐞 bug report

### Affected Package

Not sure about the affected package. It worked fine with Angular 9

### Is this a regression?

Yes

### Description

In our Angular app we use this library that adds a simple wrapper around Forms in order to add some typings:

https://github.com/dirkluijk/ngx-typesafe-forms

It worked fine until Angular 9, now it's failing with:

> TypeError: Class constructor FormControl cannot be invoked without 'new'

The source code of the `FormControl` class is:

https://github.com/dirkluijk/ngx-typesafe-forms/blob/master/projects/ngx-typesafe-forms/src/lib/form-control.ts

## 🔬 Minimal Reproduction

We are working on it but weren't able to create a minimal reproduction yet.

## 🔥 Exception or Error
<pre><code>
TypeError: Class constructor FormControl cannot be invoked without 'new'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.0
Node: 12.18.1
OS: darwin x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.8
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.8
@angular-devkit/schematics        9.1.8
@angular/cdk                      10.0.0
@angular/cli                      10.0.0
@angular/material                 10.0.0
@angular/pwa                      0.901.8
@ngtools/webpack                  9.1.9
@schematics/angular               9.1.8
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

Worked fine with Angular 9

**Comment by lagoshny** [comment] 2020-06-29 20:05
I have reproduce this issue when using **@lagoshny/ngx-hal-client** library **compiled for angular 10** in **my app based on angular 7**.

The example of app with angular 7 with @lagoshny/ngx-hal-client dependency you can find here  https://github.com/lagoshny/ng-example-app.

**Note:** **@lagoshny/ngx-hal-client** has **two versions** with differences only in **ng-packagr** version:

**1.1.1-alfa-unstable** (https://github.com/lagoshny/ngx-hal-client/tree/angular10_migration) - _(this one used in the example app)_ compiled for angular 10 with **"ng-packagr": "^10.0.0"**.
When run the example  app with this version I have error in console _**"ERROR TypeError: "class constructors must be invoked with 'new'".**_

**1.1.0** (https://github.com/lagoshny/ngx-hal-client) - compiled for angular 10 with **"ng-packagr": "^9.1.5"**.
When run the example app with this version all work fine.

In the **example app used 1.1.1-alfa-unstable version** that you can reproduce this error.
If you change version to 1.1.0 all will work fine.

**Comment by alan-agius4** [comment] 2020-06-29 20:59
@JonWallsten, can you please provide the output  `ng version`? Are you using a custom Angular CLI builder to build your application? As in the stacktrace I am seeing ‘angular.js` which is not a standard file generated by the CLI.

**Comment by JonWallsten** [comment] 2020-06-30 04:53
@alan-agius4: I'm using Webpack/AngularCompilerPlugin. I'll get you a repro in a couple of hours.

**Comment by JonWallsten** [comment] 2020-06-30 07:24
@alan-agius4: 
Repro:
1. Clone https://github.com/JonWallsten/monorepo-new/tree/angular-10-repro (sent you an invite)
2. Run `npm run full-install` in the root.
3. Run `npm run dev:edit`
4. Open: http://localhost:3060
5. Check console for error message

**Comment by alan-agius4** [comment] 2020-06-30 08:38
@JonWallsten and @lagoshny, the issue you are experiencing is due to one of the breaking changes in Angular 10. Were the deprecated esm5 and fesm5 formats are no longer generated and form no longer part of the APF spec.

@JonWallsten, since you are not using the Angular CLI, you will need to downlevel the distributed Angular libraries to es5 on your own. You can use Babel or similar tools to achieve this.

@lacolaco, in your case since you are using the Angular package format 10 in an Angular CLI pre version 10, no downleveling is happening when targeting directly ES5, in this case you have 2 options either don't use Angular 10 to build your library, or migrate your applications to use Angular 10. The latter is the recommended approach. Also, it's important to point out that Angular version 7 is no longer supported by the Angular team.

@FrancescoBorzi, I am seeing a mixture of version of Angular devkit packages (0.901.8, 0.901.9, 0.1000.0, 9.1.9), this typically is an indicator of 2 things, either you have dev dependencies in your workspaces which are not need and incorrect, or you are using a 3rd party Angular CLI builder. 

More context about the APF changes: https://github.com/angular/angular/pull/36944

**Comment by JonWallsten** [comment] 2020-06-30 08:59
@alan-agius4 : I see. So there's no plan to support this either? Using target ES2015 would be the other option, right? I think we still have to support IE11, so that would have to wait though.

**Comment by alan-agius4** [comment] 2020-06-30 09:11
@JonWallsten, you can use ES2015 as target which solves the issues, but indeed this won't work for IE 11 which requires ES5.


Indeed, for non Angular CLI users, it is expected that when targetting ES5 and their build pipeline doesn't handle downlevelling they will end up in a broken state.
You have two options for you here, either start using the Angular CLI, which does downlevelling out of the box when targeting ES5 or implement downlevelling in your build pipeline.

**Comment by alan-agius4** [comment] 2020-06-30 09:12
@JonWallsten, you can use ES2015 as target which solves the issues, but indeed this won't work for IE 11 which requires ES5.

Indeed, for non Angular CLI users, it is expected that when targetting ES5 and their build pipeline doesn't handle downlevelling they will end up in a broken state, and there won't be any out-of-box support for this scenario.

You have two options for you here, either start using the Angular CLI, which does downlevelling out of the box when targeting ES5 or implement downlevelling in your build pipeline.

**Comment by JonWallsten** [comment] 2020-06-30 09:22
@alan-agius4: Thanks! I'll look into it!

**Comment by alan-agius4** [comment] 2020-07-02 10:43
Closing as per above explanation.

**Closed by alan-agius4** 2020-07-02 10:43 UTC
Labels: type: faq
