### ISSUE TITLE
Separate build of lazy modules

### ISSUE THREAD

**Issue by AndyGrom** [angular/angular-cli#12272] opened 2018-09-14 14:34 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Window 7
node v10.10.0
npm 6.1.0

 
Angular CLI: 6.1.5                                              
Node: 10.10.0                                                   
OS: win32 x64                                                   
Angular: 6.1.4                                                  
... animations, common, compiler, compiler-cli, core, forms     
... http, platform-browser, platform-browser-dynamic, router    
                                                                
Package                            Version                      
------------------------------------------------------------    
@angular-devkit/architect          0.7.1                        
@angular-devkit/build-angular      0.7.1                        
@angular-devkit/build-ng-packagr   0.8.1                        
@angular-devkit/build-optimizer    0.7.1                        
@angular-devkit/build-webpack      0.7.1                        
@angular-devkit/core               0.7.1                        
@angular-devkit/schematics         0.7.5                        
@angular/cdk                       6.4.6                        
@angular/cli                       6.1.5                        
@angular/material                  6.4.6                        
@ngtools/json-schema               1.1.0                        
@ngtools/webpack                   6.1.1                        
@schematics/angular                0.7.5                        
@schematics/update                 0.7.5                        
ng-packagr                         4.1.1                        
rxjs                               6.2.2                        
typescript                         2.7.2                        
webpack                            4.9.2                        
```

### Repro steps

I have a big project with more than 100+ lazy loading modules. 

### Desired functionality

Currently, angular-cli too slowly build the project. It utilizes more 3Gb memory during development build and build takes 70 seconds. Moreover, the production build takes 5.5G RAM and 6 minutes.
The code of lazy modules changes very often, but the code of shared libraries changes infrequently. 

Can I build the lazy module code separately of the main application? This approach gives a very large increase in the performance of the build.

**Comment by alan-agius4** [comment] 2018-12-14 08:20
This is an interesting idea, though lazy loaded modules are part of the application which makes it hard to build on its own, since some code and dependencies are shared. It is also important to highlight that when having `commonChunks` enabled changing a lazy loaded module might have an effect on the a common chunk, if a dependency is introduced in a lazy loaded module.

**Comment by alan-agius4** [comment] 2018-12-14 13:14
Duplicate of https://github.com/angular/angular-cli/issues/8275

**Closed by alan-agius4** 2018-12-14 13:14 UTC
Labels: priority: 3 (nice to have), type: feature
