### ISSUE TITLE
Get an error when I use project option for custom schematics

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular-cli#12828] opened 2018-11-01 07:38 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps

I created a schematics with project option:
schema.json
```js
{
  "$schema": "http://json-schema.org/schema",
  "id": "CustomSchematics",
  "title": "Custom schematic",
  "type": "object",
  "properties": {
      "project": {
          "type": "string",
          "description": "The name of a project to modify"
       }
  }
}
```

If the project name does not exist in the workspace, I use the defaultProject value
It is work when I run with schematic-cli:
schematics mycollection:custom-schematic --project=wrongname

but I get an error when running with ng command:
ng g mycollection:custom-schematic --project=wrongname

### The log given by the failure

Project 'wrongname' could not be found in workspace.
Error: Project 'wrongname' could not be found in workspace.
    at Workspace._getProjectTool (C:\Users\volkov.vladislav\Documents\Work\Github\ng-exmpl\app12\node_modules\@angular-devkit\core\src\workspace\workspace.js:192:19)
    at Workspace.getProjectSchematics (C:\Users\volkov.vladislav\Documents\Work\Github\ng-exmpl\app12\node_modules\@angular-devkit\core\src\workspace\workspace.js:169:21)
    at Object.getSchematicDefaults (C:\Users\volkov.vladislav\Documents\Work\Github\ng-exmpl\app12\node_modules\@angular\cli\utilities\config.js:237:34)
    at GenerateCommand.runSchematic (C:\Users\volkov.vladislav\Documents\Work\Github\ng-exmpl\app12\node_modules\@angular\cli\models\schematic-command.js:313:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3`
`

**Comment by alan-agius4** [comment] 2018-11-02 08:56
When using the `ng` command project must be a valid project. However in schematics, `project` is just another option.

**Comment by alan-agius4** [comment] 2018-11-07 18:13
Closing as it’s working as intended.

**Closed by alan-agius4** 2018-11-07 18:13 UTC
