### ISSUE TITLE
gzip not getting created on ng build --prod

### ISSUE THREAD

**Issue by cyrilcherian** [angular/angular-cli#5330] opened 2017-03-09 11:30 UTC
### OS
Linux 14

### Versions.
@angular/cli: 1.0.0-rc.1
node: 6.4.0

### Repro steps.
ng build --target=production
or 
ng build --prod

Does not generate the gzip for any of the js file in the dist folder.

**Comment by RicardoVaranda** [comment] 2017-03-09 11:46
Dupe of #5272 , This is outside of the scope of cli, you should be configuring the gzip settings in the server which is hosting your files like apache/nginx etc.

**Comment by filipesilva** [comment] 2017-03-09 11:52
Closing as dupe, thanks @RicardoVaranda!

**Closed by filipesilva** 2017-03-09 11:52 UTC

**Comment by kaynz** [comment] 2017-04-20 06:36
@RicardoVaranda @filipesilva 
Most webservers (like nginx) are able to serve static files, e.g. if you have a vendor.bundle.js.gz next to your vendor.bundle.js, it'll serve the already compressed .gz file instead of using cpu to compress it again.

Therefore  I think it would be great if ng build --prod would create gzipped files directly.

**Comment by vcorr** [comment] 2017-05-24 11:45
I agree, I understood it did create gz-files at some point, but this functionality was removed?

**Comment by John0x** [comment] 2017-06-12 12:17
I don't see a reasony, why the cli should not support gzipping. Why has it been removed?

**Comment by jgodi** [comment] 2017-06-12 13:08
You can see the answer here: https://github.com/angular/angular-cli/pull/4618#issuecomment-279175818

**Comment by drjackson** [comment] 2017-07-12 16:21
I wish there was still at least an option for gzip.

**Comment by zac1st1k** [comment] 2017-08-03 01:54
in fact, `webpack-dev-server` supports gzip. https://github.com/webpack/webpack-dev-server/tree/master/examples/compression Anguar CLI can pass the parameter down to the server. It is really good for estimating the production performance on a local environment.

**Comment by tan9** [comment] 2018-10-05 13:12
I ended up using "gzip-all":https://www.npmjs.com/package/gzip-all in my package.json:
```json
{
    "...": "...",
    "scripts": {
        "...": "...",
        "build-prod": "ng build --prod && gzip-all \"dist/anti-fraud/*.*\"",
        "...": "...",
    },
    "...": "...",
}
```

**Comment by rynop** [comment] 2018-10-09 19:11
I think the trend is for SPA to be hosted in a static object store like S3.  While a CDN can be put in front to gzip on the fly, IMO it is a waste.

My vote would be to put it back into `ng build` as an optional param, given the number of people that need the use case and the trend mentioned above.

**Comment by tdev9** [comment] 2019-01-21 20:40
Optional params to generate gzip would be very helpful to don't have to use workarounds.
