### ISSUE TITLE
Multiple projects in Angular workspace don't get tested by running ng test without a project name

### ISSUE THREAD

**Issue by MattiJarvinen** [angular/angular-cli#26850] opened 2024-01-11 13:59 UTC
### Command

test

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

It's been a while but this is a documented feature... :(

### Description

As per documentation https://angular.io/cli/test

ng test [project]
ng t [project]

Takes the name of the project, as specified in the projects section of the angular.json workspace configuration file. When a project name is not supplied, it will execute for all projects.

In practice it doesn't.

### Minimal Reproduction

ng new repro-app --no-create-application
cd repro-app
ng generate application admin --defaults
ng generate application www --defaults
ng test

End result is that only tests from admin project are run.

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.10
Node: 20.9.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.10
@angular-devkit/build-angular   17.0.10
@angular-devkit/core            17.0.10
@angular-devkit/schematics      17.0.10
@angular/cli                    17.0.10
@schematics/angular             17.0.10
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

### Anything else relevant?

Tests run with adding a project name eg. `ng test admin` , but the documentation says running without project name should run tests from all projects.

**Comment by alan-agius4** [comment] 2024-01-11 14:15
Duplicate of https://github.com/angular/angular-cli/issues/21473

**Closed by alan-agius4** 2024-01-11 14:15 UTC
