### ISSUE TITLE
Allow extract-i18n to only add i18n tags that do not already exist in target translation file

### ISSUE THREAD

**Issue by spock123** [angular/angular-cli#26851] opened 2024-01-10 14:52 UTC
### Description

As it is now, running extract-i18n is pretty much useless, because once it's run, any consecutive runs will overwrite the translation file entries.

This means, that once run, any new translation tokens added to the project will have to be manually added to all translation files. 

Our use case: we are adding translations to a large site, with 5-8 languages. 
The translation of the project will be a long process, and we cannot add tags to the entire project in one swift move. We have to take it step by step.

However, due to the way extract-i18n works, we cannot use it, as it will just write all i18n tokens found in the code, to the target file.

FWIW, we are using translation files with the JSON format.

### Proposed solution

Add a setting to extract-i18n (for example --no-override ) so that it will not override already existing entries for that ID.

### Alternatives considered

 A) https://github.com/daniel-sc/ng-extract-i18n-merge

Poorly maintained, and only supports XLIFF format.

B) write own script that picks out the translations and adds them to the current translation files (would only work with json). 

C) use other 3rd party runtime translation libraries but we don't want that - we want compile time , as it's much better imho.

**Comment by alan-agius4** [comment] 2024-01-11 15:51
Duplicate of https://github.com/angular/angular-cli/issues/23428

**Closed by alan-agius4** 2024-01-11 15:51 UTC
