### ISSUE TITLE
No matching version found for browserslist@^4.9.1. when installing @angular-devkit/build-angular

### ISSUE THREAD

**Issue by Javaman2** [angular/angular-cli#17234] opened 2020-03-16 16:42 UTC
# 🐞 Bug report

### Command (mark with an `x`)
 

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 
Probably

### Description
After running ng update from version 8.2.5, the Angular-devkit/build-angular module shows an error when running ng --version. (see title)

 So when we try to update browserslist to ^4.9.1 npm doesn't recognize that version. 
 

## 🔬 Minimal Reproduction
 
We simply ran an ng update on an angular 8.2.5 project, then had lots of issues from there. 

 

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.2
Node: 13.6.0
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.900.6
@angular-devkit/build-angular   <error>
@angular-devkit/core            9.0.6
@angular-devkit/schematics      9.0.2
@angular/cdk                    9.0.0
@angular/cli                    9.0.2
@angular/material               9.0.0
@schematics/angular             9.0.2
@schematics/update              0.900.2
rxjs                            6.5.4
typescript                      3.7.5

</code></pre>

**Anything else relevant?**
 
No

**Comment by alan-agius4** [comment] 2020-03-16 16:58
Hi, I am sorry but this is not caused by Angular CLI as per the npm registry, the version 4.9.1 is published and available as the latest tag: https://www.npmjs.com/package/browserslist/v/4.9.1.

If you are using a registry proxy please make sure that it's synced with the public npm registry. 

Closing as this is not actionable by us.

**Closed by alan-agius4** 2020-03-16 16:58 UTC

**Comment by Javaman2** [comment] 2020-03-16 17:05
Thanks!

**Comment by Javaman2** [comment] 2020-03-24 19:40
Yes the root cause was an .npmrc file I didn't know about.  This redirects npm to use other (internal) repositories.
