### ISSUE TITLE
many files are created at wrong place when creating a project using ng new with -sd 

### ISSUE THREAD

**Issue by cvgaviao** [angular/angular-cli#8692] opened 2017-11-30 14:45 UTC
### Versions
```
Angular CLI: 1.5.3
Node: 8.9.1
OS: linux x64

```

### Repro steps
* ng new --prefix core --routing -sc -sd src/core --style scss -v prj-web
* ng build

### Observed behavior

The project will be created apparently ok. 
The .angular-cli.json file will contain an app which "root" will point to "src/core" folder. But the created files (tsconfig.app.json, main.ts, etc) on this app declaration won't be found since they were created at /src folder.  
```
Error: ENOENT: no such file or directory, stat '/home/black/Development/prj-web/src/core/tsconfig.app.json'
    at Object.fs.statSync (fs.js:948:11)
```

### Desired behavior
Seems that app files should be in the same source directory pointed by -sr parameter in order to build ok.

**Comment by clydin** [comment] 2017-11-30 15:28
Thanks for reporting this issue. However, this issue is appears to be a duplicate of an existing issue #8461. Please subscribe to that issue for future updates.

**Closed by clydin** 2017-11-30 15:28 UTC
