### ISSUE TITLE
Invalid tsconfig.app.json after generating web worker

### ISSUE THREAD

**Issue by christianlundberg** [angular/angular-cli#15037] opened 2019-07-10 16:49 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Angular only began official support of web workers so I guess not.

### Description

After running `ng g web-worker sheet --project=enterprise`, the tsconfig.app.json looks like this:

```
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "outDir": "../../dist/out-tsc",
        "types": []
    },
    "exclude": ["src/test.ts", "**/*.spec.ts",]    "src/**/*.worker.ts"
,
    "include": ["**/*.ts"]
}
```
Notice `"src/**/*.worker.ts"` was placed outside of the `exclude` array. This causes plenty of errors upon building the app which is how I discovered the error.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.1.0
Node: 12.3.1
OS: win32 x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.1
@angular-devkit/build-angular      0.801.0
@angular-devkit/build-optimizer    0.801.0
@angular-devkit/build-webpack      0.801.0
@angular-devkit/core               8.0.1
@angular-devkit/schematics         8.0.1
@angular/cdk                       8.0.0
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.0.0
@angular/material-moment-adapter   8.0.0
@ngtools/webpack                   8.1.0
@schematics/angular                8.0.1
@schematics/update                 0.801.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2
</code></pre>

**Comment by alan-agius4** [comment] 2019-07-10 18:04
Duplicate of https://github.com/angular/angular-cli/issues/14776

**Closed by alan-agius4** 2019-07-10 18:04 UTC
