### ISSUE TITLE
Upgrade from ng 9 to ng 10 platformBrowserDynamic TypeError: this.store.select(...).filter is not a function

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#18289] opened 2020-07-14 19:04 UTC
Upgrade from ng 9 to ng 10 HTTP error: platformBrowserDynamic TypeError: this.store.select(...).filter is not a function

UPDATE: possibly related: https://github.com/valor-software/ngx-bootstrap/issues/4831
but I am not using this library.

ng 9 all is great when I publish final release via CLI.

ng 10 upg getting an error of :

platformBrowserDynamic TypeError: this.store.select(...).filter is not a function

in browser

```
Angular CLI: 10.0.2
Node: 10.15.0
OS: win32 x64

Angular: 10.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.2
@angular-devkit/build-angular      0.1000.2
@angular-devkit/build-optimizer    0.1000.2
@angular-devkit/build-webpack      0.1000.2
@angular-devkit/core               10.0.2
@angular-devkit/schematics         10.0.2
@angular/cdk                       9.2.4
@angular/cli                       10.0.2
@angular/flex-layout               9.0.0-beta.31
@angular/google-maps               9.2.4
@angular/http                      7.2.16
@angular/material                  9.2.4
@angular/material-moment-adapter   9.2.4
@angular/pwa                       0.803.26
@ngtools/webpack                   10.0.2
@schematics/angular                10.0.2
@schematics/update                 0.1000.2
rxjs                               6.5.5
typescript                         3.9.6
webpack                            4.43.0
````

This is the error screen shot:

![err](https://user-images.githubusercontent.com/5090936/87465628-d45a2f80-c5c9-11ea-9ec9-3c9db7372729.PNG)

rolling back to ng yields no issues.

this is my publish commands:

![cmd](https://user-images.githubusercontent.com/5090936/87465731-feabed00-c5c9-11ea-85bc-b7e3b6fc36c1.PNG)

on publishing no errors, just some warnings:

```
WARNING in C:\msweb\studiopro-web\src\app\containers\adnet\AdnetActions.ts depends on 'rxjs/add/operator/catch'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\msweb\studiopro-web\src\app\containers\get-started\started-downloads\started-downloads.component.ts depends on 'platform'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\msweb\studiopro-web\node_modules\rxjs\ReplaySubject.js depends on 'rxjs-compat/ReplaySubject'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\msweb\studiopro-web\src\app\containers\overview\overview.module.ts depends on 'highcharts/highcharts-more.src'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in
```
regards

Sean

**Comment by JoostK** [comment] 2020-07-17 18:08
This is indeed due to rxjs-compat no longer being supported in Angular CLI 10. The side-effecful module imports to register operators on the Observable prototype all require rxjs-compat, as this mode of operation has been removed in RxJS 6 (which Angular adopted in its v6, coincidentally.) Probably there's some dependency that's still depending on it. You can probably determine the cause by inspecting the code where that error occurs.

Related: #18272, #18213, #18052, #18045 and #18035.

**Comment by JoostK** [comment] 2020-07-17 18:09
I'm inclined to close this, but given that this is quite hard to debug and only shows up at runtime I'm wondering if there could be a way to error at build time instead.

**Comment by alan-agius4** [comment] 2020-07-17 18:36
We could do a couple of things here. We can remove the rxjs-compat package from dev dependencies during the update, this should cause build time errors. Also, when finding the mentioned package during the migration we should issue a warning with a lint to the RxJS migration guide.

**Comment by alan-agius4** [comment] 2020-07-17 18:49
Had a chat with @clydin, and we decided to go with a warning/info message during the migration.

Something similar to https://github.com/angular/angular-cli/blob/233d701c7a9a8fab2f301dd28fbd94b2194d682e/packages/schematics/angular/migrations/update-10/update-dependencies.ts#L55-L60

**Comment by sacgrover** [comment] 2020-07-19 11:36
@alan-agius4 Have you already started working on it?

**Comment by alan-agius4** [comment] 2020-07-20 12:17
@sacgrover, no I didn't start on this. Though @clydin found the root cause of the problem and landed a PR. https://github.com/angular/angular-cli/pull/18292

Nonetheless, I think issuing an info message with a lint to the RxJs migration guide when finding rxjs-compat would be good to have. So feel free to land a PR for that 😁

Closing as the above mentioned PR has been merged.

**Closed by alan-agius4** 2020-07-20 12:17 UTC
Labels: comp: schematics/angular, freq3: high, severity2: inconvenient, type: bug/fix
