### ISSUE TITLE
[Feature Request] Ability to do publishable 'library' builds

### ISSUE THREAD

**Issue by e-schultz** [angular/angular-cli#5473] opened 2017-03-17 12:09 UTC
### Bug Report or Feature Request (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Versions.

N/A

### Repro steps.
N/A

### The log given by the failure.
N/A

### Desired functionality.
What would like to see implemented?

The ability to do a build of a module that is appropriate to publish as a npm package/library 

What is the usecase?:

Common use case is wanting to create a reusable 'ui-component' library to be used across multiple applications, and be appropriately versioned.

For example

src->app->kitchen sink demo
src->ui-kit->module with components/directives 

`ng serve` would run the app

ability to do something like `ng build --target=library --app=ui-kit` that would make a build of the `ui-kit` that would be appropriate to publish as it's own library. 

### Mention any other details that might be useful.
n/a

**Comment by filipesilva** [comment] 2017-03-18 15:13
Dupe of https://github.com/angular/angular-cli/issues/1692

**Closed by filipesilva** 2017-03-18 15:13 UTC
