### ISSUE TITLE
CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by gieboyz** [angular/angular-cli#7024] opened 2017-07-18 06:28 UTC
Hi i know already another post has been answer this problem before but, i just want to know what the differences between using 
method 1 : `node --max_old_space_size=8192 node_modules/\@angular/cli/bin/ng build --prod --aot`
and using
method 2 : `ng build --prod --aot false`

if i using `node --max_old_space_size=8192 node_modules/\@angular/cli/bin/ng build --prod --aot`
the results always stuck on 92% like this
![method 1](https://user-images.githubusercontent.com/9793593/28303253-570ae804-6bbc-11e7-8c7d-b4aff78ad291.png)

but if i using `ng build --prod --aot false` all process working well
![method2](https://user-images.githubusercontent.com/9793593/28303269-7571054e-6bbc-11e7-8d78-e1424a72e39d.png)

i really not understand why just add **false** everything it works, but if i not using **false** the build will show error message CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

can you tell me what the problem in method 1? 

### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [X ] feature request
```

### Versions.

npm : 4.5.0
node : 7.6.0
windows 7

### the pacakge.json.

> "dependencies": {
>     "@angular/animations": "^4.0.0",
>     "@angular/common": "^4.0.0",
>     "@angular/compiler": "^4.0.0",
>     "@angular/core": "^4.0.0",
>     "@angular/forms": "^4.0.0",
>     "@angular/http": "^4.0.0",
>     "@angular/platform-browser": "^4.0.0",
>     "@angular/platform-browser-dynamic": "^4.0.0",
>     "@angular/router": "^4.0.0",
>     "angular2-jwt": "^0.2.3",
>     "angular2-select": "^1.0.0-beta.3",
>     "angular2-toaster": "^4.0.0",
>     "bootstrap": "^3.3.7",
>     "core-js": "^2.4.1",
>     "jquery": "^3.2.1",
>     "jquery-flot": "^0.8.3",
>     "jquery-slimscroll": "^1.3.8",
>     "jqueryui": "^1.11.1",
>     "metismenu": "^2.7.0",
>     "ng2-bs3-modal": "^0.10.4",
>     "primeng": "^4.1.0",
>     "rxjs": "^5.1.0",
>     "zone.js": "^0.8.4"
>   },
>   "devDependencies": {
>     "@angular/cli": "1.2.0",
>     "@angular/compiler-cli": "^4.0.0",
>     "@angular/language-service": "^4.0.0",
>     "@ types/jasmine": "~2.5.53",
>     "@ types/jasminewd2": "~2.0.2",
>     "@ types/jquery": "^3.2.6",
>     "@ types/node": "~6.0.60",
>     "codelyzer": "~3.0.1",
>     "gulp": "^3.9.1",
>     "gulp-gzip": "^1.4.0",
>     "jasmine-core": "~2.6.2",
>     "jasmine-spec-reporter": "~4.1.0",
>     "karma": "~1.7.0",
>     "karma-chrome-launcher": "~2.1.1",
>     "karma-cli": "~1.0.1",
>     "karma-coverage-istanbul-reporter": "^1.2.1",
>     "karma-jasmine": "~1.1.0",
>     "karma-jasmine-html-reporter": "^0.2.2",
>     "protractor": "~5.1.2",
>     "ts-node": "~3.0.4",
>     "tslint": "~5.3.2",
>     "typescript": "~2.3.3"
>   }

**Comment by alanhg** [comment] 2017-07-21 05:44
I also met this error

**Comment by filipesilva** [comment] 2017-07-28 11:08
To answer your question, `--aot false` disabled AOT compilation. Other than that, this is a duplicate of https://github.com/angular/angular-cli/issues/5618.

**Closed by filipesilva** 2017-07-28 11:08 UTC
