### ISSUE TITLE
`application` builder issue with localize

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#25911] opened 2023-09-27 15:53 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using the application builder, using a component that relies on localize results in an exception, even if localize has been added to the project.

Consider a route config as follow:
```ts
import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';

export const routes: Routes = [
  { path: '', component: HomeComponent }
];
```

`HomeComponent` uses `NgbPagination` from ng-boostrap, which uses localize.
```html
<ngb-pagination [collectionSize]="20" size="lg"></ngb-pagination>
```

Even after adding `localize` with `ng add @angular/localize` , the application has a runtime error when displaying the component.

### Minimal Reproduction

clone https://github.com/cexbrayat/i18n-lazy-loading

```
npm i
ng serve
```

If you change the builder to the browser one, then the pagination component correctly displays

### Exception or Error

```text
ERROR Error: Uncaught (in promise): Error: It looks like your application or one of its dependencies is using i18n.
Angular 9 introduced a global `$localize()` function that needs to be loaded.
Please run `ng add @angular/localize` from the Angular CLI.
(For non-CLI projects, add `import '@angular/localize/init';` to your `polyfills.ts` file.
For server-side rendering applications add the import to your `main.server.ts` file.)
_global.$localize<@http://localhost:4200/.angular/cache/17.0.0-next.6/vite/deps/chunk-ZVLRK7IP.js?v=5921499a:22191:11
consts@http://localhost:4200/.angular/cache/17.0.0-next.6/vite/deps/@ng-bootstrap_ng-bootstrap.js?v=793732a8:18830:17
createTView@http://localhost:4200/.angular/cache/17.0.0-next.6/vite/deps/chunk-ZVLRK7IP.js?v=5921499a:10416:58
getOrCreateComponentTView@http://localhost:4200/.angular/cache/17.0.0-next.6/vite/deps/chunk-ZVLRK7IP.js?v=5921499a:10407:24
addComponentLogic@http://localhost:4200/.angular/cache/17.0.0-next.6/vite/deps/chunk-ZVLRK7IP.js?v=5921499a:10…
```

### Your Environment

```text
Angular CLI: 17.0.0-next.6
Node: 18.16.0
Package Manager: npm 9.7.1
OS: darwin arm64

Angular: 17.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-next.6
@angular-devkit/build-angular   17.0.0-next.6
@angular-devkit/core            17.0.0-next.6
@angular-devkit/schematics      17.0.0-next.6
@angular/cli                    17.0.0-next.6
@schematics/angular             17.0.0-next.6
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

### Anything else relevant?

The error goes away when shifting back to the `browser` builder

**Comment by JeanMeche** [comment] 2023-09-27 15:55
Hi, isn't this a dupe of #25099 ?

**Comment by cexbrayat** [comment] 2023-09-27 16:01
Maybe it is, you're right. I recently updated the schematics to make it work with the application builder, so I was expecting it to work now (and it does in simple examples), but it looks like there is still work to do in the builder for some use cases.

**Comment by alan-agius4** [comment] 2023-09-27 16:48
I18n support has been added.

**Closed** 2023-10-09 17:40 UTC
Labels: type: bug/fix, freq1: low, severity3: broken, area: devkit/build-angular, devkit/build-angular:i18n, devkit/build-angular:application
