### ISSUE TITLE
Production build fails

### ISSUE THREAD

**Issue by AmitMY** [angular/angular-cli#7646] opened 2017-09-10 14:15 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.4.1
node: 8.4.0
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.1
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
typescript: 2.3.4
```

### Repro steps.
`ng build --prod`

### The log given by the failure.

> ng build --prod
> Date: 2017-09-10T14:08:09.449Z
> Hash: 1597dc528e5411ab3bb4
> Time: 17346ms
> chunk {0} polyfills.67d068662b88f84493d2.bundle.js (polyfills) 64.1 kB {4} [initial] [rendered]
> chunk {1} main.2337b90653a0c45c31e8.bundle.js (main) 23.7 kB {3} [initial] [rendered]
> chunk {2} styles.d099489fcced365e3169.bundle.css (styles) 18 kB {4} [initial] [rendered]
> chunk {3} vendor.5c27761de53ff74202e9.bundle.js (vendor) 1.81 MB [initial] [rendered]
> chunk {4} inline.2a33c113af51e7e703d8.bundle.js (inline) 1.45 kB [entry] [rendered]
> 
> ERROR in vendor.5c27761de53ff74202e9.bundle.js from UglifyJs
> Name expected [vendor.5c27761de53ff74202e9.bundle.js:16309,18]

### Desired functionality.
Either a more readable error, or for it to work

### Mention any other details that might be useful.
Trying to build https://github.com/Webiks/force-horse-demo
It is in early stages, so it uses a local dependency in the `styles.css` file, which if you want to build locally you need to remove (first line of that file)

**Comment by yokots** [comment] 2017-09-11 06:28
same here

**Comment by valdestrijus** [comment] 2017-09-11 11:05
Hello, i have similar problems with my project, but not quite sure if it is problems with my code or any other third party libs, I can successfully build prod version with fresh angular-cli porject.

My case: 
### Versions.
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.1
node: 8.3.0
os: linux x64
@angular/animations: 4.4.0-RC.0
@angular/common: 4.4.0-RC.0
@angular/compiler: 4.4.0-RC.0
@angular/core: 4.4.0-RC.0
@angular/forms: 4.4.0-RC.0
@angular/http: 4.4.0-RC.0
@angular/platform-browser: 4.4.0-RC.0
@angular/platform-browser-dynamic: 4.4.0-RC.0
@angular/router: 4.4.0-RC.0
@angular/cli: 1.4.1
@angular/compiler-cli: 4.4.0-RC.0
@angular/language-service: 4.4.0-RC.0
typescript: 2.5.2

### The log given by the failure.
```
 11% building modules 12/12 modules 0 activeWarning: Can't resolve all parameters for NgbModalRef in /home/valdas/www/govest/app/node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts: ([object Object], [object Object], [object Object], ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for NgbModalRef in /home/valdas/www/govest/app/node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts: ([object Object], [object Object], [object Object], ?). This will become an error in Angular v5.x
Date: 2017-09-11T10:58:34.280Z                                                          
Hash: dd655a3a100c16d26f4c
Time: 51255ms
chunk {0} 0.db52783a28486542ce37.chunk.js (common) 9.37 kB {12}  [rendered]
chunk {1} 1.a36349742f79c06c31af.chunk.js () 40.7 kB {12}  [rendered]
chunk {2} 2.21cee4493b6bc569c03f.chunk.js () 30.6 kB {12}  [rendered]
chunk {3} 3.da0aef26e2c9dcb6fadf.chunk.js () 3.53 kB {12}  [rendered]
chunk {4} 4.69a32d3bd31556b00389.chunk.js () 3.5 kB {12}  [rendered]
chunk {5} 5.c110980766a592bf624f.chunk.js () 3.55 kB {12}  [rendered]
chunk {6} 6.196ce138ca88d7e11066.chunk.js () 2.83 kB {12}  [rendered]
chunk {7} 7.3861b3aa36198afeb07f.chunk.js () 2.81 kB {12}  [rendered]
chunk {8} 8.026f311cde8d68c8c07d.chunk.js () 3.64 kB {12}  [rendered]
chunk {9} 9.cfac44b3422d2724752c.chunk.js () 3.44 kB {12}  [rendered]
chunk {10} 10.0bfb747c889e23783a24.chunk.js () 3.53 kB {12}  [rendered]
chunk {11} polyfills.0342a3cd8944a09c76ff.bundle.js (polyfills) 98.2 kB {15} [initial] [rendered]
chunk {12} main.a0ac138634f47fb9589d.bundle.js (main) 242 kB {14} [initial] [rendered]
chunk {13} styles.fe3b456a041f5dd5f39e.bundle.css (styles) 258 kB {15} [initial] [rendered]
chunk {14} vendor.558a86e3381882c119ca.bundle.js (vendor) 1.79 MB [initial] [rendered]
chunk {15} inline.aa25e5e0c3dd9e5a5e13.bundle.js (inline) 1.73 kB [entry] [rendered]

ERROR in   Error: Parse Error: </html
  
  - htmlparser.js:235 new HTMLParser
    [app]/[html-minifier]/src/htmlparser.js:235:13
  
  - htmlminifier.js:946 minify
    [app]/[html-minifier]/src/htmlminifier.js:946:3
  
  - htmlminifier.js:1299 exports.minify
    [app]/[html-minifier]/src/htmlminifier.js:1299:10
  
  - index.js:296 
    [app]/[html-webpack-plugin]/index.js:296:16
  
  - util.js:16 tryCatcher
    [app]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [app]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [app]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [app]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [app]/[bluebird]/js/release/promise.js:693:18
  
  - async.js:133 Async._drainQueue
    [app]/[bluebird]/js/release/async.js:133:16
  
  - async.js:143 Async._drainQueues
    [app]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [app]/[bluebird]/js/release/async.js:17:14
  

```
There might be some issues with my own code and third party libs but can not read anything of this error.
For me it looks like UglifyJs is not able to perform operation but the error output is different than yours.
What I found that I am able to build chunked but not minified version of my project by using command like this: ```ng build --environment=prod --build-optimizer --aot true --output-hashing all --sourcemaps false --extract-css true```

**Comment by wingsbob** [comment] 2017-09-12 15:03
I think all these issues are supposed to be gathered in #2907

**Comment by filipesilva** [comment] 2017-09-25 17:00
This issue is a duplicate of https://github.com/angular/angular-cli/issues/5741. If you turn sourcemaps on you will see the cause of the error.

```
kamik@T460p MINGW64 D:/sandbox/force-horse-demo (master)
$ ng build --prod --sourcemap
Date: 2017-09-25T16:56:29.701Z
Hash: 06391c163276f0cc604a
Time: 17824ms
chunk {0} polyfills.5c955edf4d00da5aa0c4.bundle.js, polyfills.5c955edf4d00da5aa0c4.bundle.js.map (polyfills) 64.1 kB {4} [initial] [rendered]
chunk {1} main.3255f15663b5c44e7a15.bundle.js, main.3255f15663b5c44e7a15.bundle.js.map (main) 24 kB {3} [initial] [rendered]
chunk {2} styles.7411b9041dad72eeed20.bundle.css, styles.7411b9041dad72eeed20.bundle.css.map (styles) 80 bytes {4} [initial] [rendered]
chunk {3} vendor.b2354de14cefc17d1ccb.bundle.js, vendor.b2354de14cefc17d1ccb.bundle.js.map (vendor) 1.8 MB [initial] [rendered]
chunk {4} inline.d4208ee074e515fb2fcf.bundle.js, inline.d4208ee074e515fb2fcf.bundle.js.map (inline) 1.51 kB [entry] [rendered]

ERROR in vendor.b2354de14cefc17d1ccb.bundle.js from UglifyJs
Name expected [D:/sandbox/force-horse-demo/node_modules/force-horse/src/helpers/debug-logger/debug-logger.js:1,0][vendor.b2354de14cefc17d1ccb.bundle.js:16320,18]
```

**Closed by filipesilva** 2017-09-25 17:00 UTC
Labels: priority: 2 (required), severity3: broken
