### ISSUE TITLE
Schema validation rejects *.html files in fileReplacements (Regression in 11.0.0 & 11.0.1)

### ISSUE THREAD

**Issue by dougamos** [angular/angular-cli#19438] opened 2020-11-19 14:06 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build
- [x] serve

### Is this a regression?

Yes, the previous version in which this bug was not present was: 10.2.3

### Description

There are new changes in files `.\node_modules\@angular-devkit\build-angular\src\browser\schema.json` and `.\node_modules\@angular-devkit\build-angular\src\server\schema.json` that restrict using *.html files in fileReplacements operations that were always available in previous versions.

We use different index.html files depending on the environment so use fileReplacements to do this.

This is similar to #19378.

## 🔥 Exception or Error

Schema validation failed with the following errors:
<pre><code>
  Data path ".fileReplacements[0]" should NOT have additional properties(replace).
  Data path ".fileReplacements[0].replace" should match pattern "\.([cm]?j|t)sx?$".
  Data path ".fileReplacements[0]" should match exactly one schema in oneOf.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.4
Node: 10.22.0
OS: darwin x64

Angular: undefined
... 
Ivy Workspace: <error>

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.4 (cli-only)
@angular-devkit/core         10.1.4 (cli-only)
@angular-devkit/schematics   10.1.4 (cli-only)
@schematics/angular          10.1.4 (cli-only)
@schematics/update           0.1001.4 (cli-only)
 </code></pre>

**Comment by alan-agius4** [comment] 2020-11-19 14:12
Duplicate of https://github.com/angular/angular-cli/issues/19390

**Closed by alan-agius4** 2020-11-19 14:12 UTC
