### ISSUE TITLE
Can't serve due to uglifyjs-webpack-plugin 1.1.7 release

### ISSUE THREAD

**Issue by admosity** [angular/angular-cli#9427] opened 2018-01-29 20:03 UTC
### Versions
```
Angular CLI: 1.6.5
Node: 8.7.0
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

* `ng new project`
* `ng serve`
* `npm run start` - does the same thing

### Observed behavior
```
> npm run start

> client1@0.0.0 start /u/admosity/git/_personal/lerna-repo/packages/client1
> ng serve

Cannot find module 'uglifyjs-webpack-plugin'
Error: Cannot find module 'uglifyjs-webpack-plugin'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/u/admosity/git/_personal/lerna-repo/packages/client1/node_modules/@angular/cli/models/webpack-configs/production.js:13:24)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/u/admosity/git/_personal/lerna-repo/packages/client1/node_modules/@angular/cli/models/webpack-configs/index.js:9:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client1@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client1@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /u/admosity/.npm/_logs/2018-01-29T19_50_52_816Z-debug.log
```

### Desired behavior

Project should run

### Mention any other details that might be useful (optional)
webpack-contrib/uglifyjs-webpack-plugin#217

**Comment by seekheart** [comment] 2018-01-29 20:09
I can confirm same issue.

**Comment by philljones** [comment] 2018-01-29 20:09
Getting the same issue.

**Comment by davishen** [comment] 2018-01-29 20:10
+1

**Comment by gitDylanHub** [comment] 2018-01-29 20:11
https://stackoverflow.com/questions/48509026/cant-run-new-angular-cli-project/48509222#48509222

**Comment by tuffs** [comment] 2018-01-29 20:11
Same issue here.

**Comment by apbarratt** [comment] 2018-01-29 20:12
Yep, I'm getting this too.

**Comment by sgomanf** [comment] 2018-01-29 20:12
Same issue. angular-cli@1.6.6

**Comment by seekheart** [comment] 2018-01-29 20:13
I think it's anything 1.6.x and up? I can still ng serve an old project running 1.4.4

**Comment by tanwarsatya** [comment] 2018-01-29 20:15
Same issue on 1.6.6, it was working fine earlier.

**Comment by Eonfow** [comment] 2018-01-29 20:16
Latest install is using uglifyjs-webpack-plugin@1.1.7, specifying uglifyjs-webpack-plugin@1.1.6 in package.json solved the issue for me.

**Comment by EricWafford** [comment] 2018-01-29 20:16
@seekheart is correct, in the cli package json it's pulling in "uglifyjs-webpack-plugin": "^1.1.5", and the issue is with this package's recent 1.1.7 release. 

as a temporary workaround, ```npm i --save-dev uglifyjs-webpack-plugin@1.1.6``` in the local project does seem to fix the issue. Not the best solution, but it got ```ng serve``` to work.

**Comment by kikar** [comment] 2018-01-29 20:18
Confirm `npm i --save-dev uglifyjs-webpack-plugin@1.1.6 ` temporarly fixes the issue

**Comment by hansl** [comment] 2018-01-29 20:20
Webpack published an empty `uglifyjs-webpack-plugin`. I contacted them and they're looking at it. Thanks for your patience.

**Comment by TerrySlack** [comment] 2018-01-29 20:41
Unfortunately, @EricWafford's solution does not seem to work.  I've recreated several projects.  Removed the node_modules folder, and the lock file.  Force cleaned and verified the cache and then did a fresh install.  Also ensured that all packages are up todate.  I still get the missing uglifyjs-webpack-plugin errorl

**Comment by raphaelLacerda** [comment] 2018-01-29 20:44
kikar's workaround worked for me

**Comment by carlospliego** [comment] 2018-01-29 20:44
Same issue

**Comment by carlospliego** [comment] 2018-01-29 20:52
Seeing a fix as of now.

**Comment by hansl** [comment] 2018-01-29 20:54
After escalation and investigation, the webpack-contrib team released a new version 1.1.8 with everything proper in it. I'm going to close this issue as fixed, but we'll look into fixing our dependency versions (and why it wasn't fixed inthe first place). Thanks for your patience.

**Closed by hansl** 2018-01-29 20:54 UTC

**Comment by jlozoya** [comment] 2018-01-29 20:57
What version you recommend to downgrade webpack, at this time?

**Comment by carlospliego** [comment] 2018-01-29 20:57
@jlozoya just run `ng new app_name` they downgraded their webpack. Works for me now.

**Comment by filipesilva** [comment] 2018-01-29 20:58
Hi all,

`uglifyjs-webpack-plugin` has release a `1.1.8` version that should fix this problem.

You can force your local install to use this version by following these steps:
```
npm install uglifyjs-webpack-plugin@1.1.8 --save
npm uninstall uglifyjs-webpack-plugin@1.1.8 --save
```

By installing and uninstalling a specific version you will update your local npm cache to resolve matching ranges to that version.

I'd like to remind everyone that **you only have reproducible installs if you use a lockfile**. Both [NPM v5+](https://docs.npmjs.com/files/package-locks) and [Yarn](https://yarnpkg.com/lang/en/docs/yarn-lock/) support lockfiles. If your CI works one day but not the next and you did not change your code or `package.json`, it is likely because one of your dependencies had a bad release and you did not have a lockfile.

**It is your responsibility as a library consumer to use lockfiles**. No one wants to do a release with bugs but it sometimes happens, and the best we can do is to fix it as fast as possible with a new release. When you have a couple of thousand total dependencies it is only a matter of time until one of them has a bad release.
