### ISSUE TITLE
Flags that specifies the folder of the generated application or libarary

### ISSUE THREAD

**Issue by junraemon** [angular/angular-cli#12858] opened 2018-11-03 04:32 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node: v9.11.1
NPM: v6.4.1
Angular CLI: 7.0.4

### Desired functionality

add a flag like --projectRoot=apps or --projectRoot=libs to specify which folder the generated apps or libaries to be added.

### Mention any other details that might be useful

By default, all the generated applications and libraries are added in the projects folder. It'll be great if we have a flag that can override this. I tried --projectRoot=apps, --newProjectRoot=apps but it will always adds the project to the default newProjectRoot.

**Comment by junraemon** [comment] 2018-11-03 04:37
this will be a great buddy for the ng new flag --createApplication=false

**Comment by alan-agius4** [comment] 2021-01-11 10:56
Duplicate of https://github.com/angular/angular-cli/issues/11101

**Closed by alan-agius4** 2021-01-11 10:56 UTC
Labels: comp: schematics/angular, type: feature
