### ISSUE TITLE
ng new - Cannot find module 'config-chain'

### ISSUE THREAD

**Issue by Rekeyea** [angular/angular-cli#1264] opened 2016-07-01 14:40 UTC
1. Windows 10

2. 
angular-cli: 0.1.0
node: 5.3.0
os: win32 x64

3. Reproduce with:
`ng new my-app`

4. 

Cannot find module 'config-chain'
Error: Cannot find module 'config-chain'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\emiliano.conti\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\lib\config\core.js:2:10)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

5. Installed config-chain globally with `npm install -g config-chain` but cannot find another module:

Cannot find module 'umask'
Error: Cannot find module 'umask'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\emiliano.conti\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\lib\utils\umask.js:1:75)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

**Comment by filipesilva** [comment] 2016-07-04 00:08
Dupe of https://github.com/angular/angular-cli/issues/1186

**Closed by filipesilva** 2016-07-04 00:08 UTC
