### ISSUE TITLE
Web-workers are not downleveled to es5 when using differential loading

### ISSUE THREAD

**Issue by nadavsinai** [angular/angular-cli#16329] opened 2019-12-01 15:29 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Sort of,  as far as I understand your code it exists since [bundle downleveling was introduced](https://github.com/angular/angular-cli/pull/15246/files)

### Description

I'm trying to convert our applications to Angular/CLI. I am responsible for the current custom webpack build of 20+ internal Philips-Algotec Angular applications.
We use web-workers extensively. My custom setup supported differential loading too but did it with two builds. I see this option exists in Angular 8.x but not in 9.x using the process.env.NG_BUILD_DIFFERENTIAL_FULL=1 flag so I'm reluctant to use it.
in the current mode - bundle downleveling the worker's chunks are:
1) not downleveled at all.
2) there is no change in the es5 main chunk new Worker construct which should change to use the es5 version of the worker (which unfortunately does not exist )

## 🔬 Minimal Reproduction

Simple steps to reproduce this bug.

 - generate a new angular application
 - add IE11 to browserlist to allow for differential loading
 - use `ng generate web-worker 'somename'` schematic to create a worker
 - use polyfills (in both the app & worker code)
 - but make sure the code in the worker uses new ES2015 language features that need transpilation rather than polyfilling - such as Array spread, string literals etc.
 - try to load site in IE11

I've created a repo with the above steps [here](https://github.com/Algotec/ie11-worker-repro)

## 🔥 Exception or Error
<pre><code>
Syntax error
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.19
Node: 10.15.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.14
@angular-devkit/build-angular      0.803.19
@angular-devkit/build-ng-packagr   0.803.19
@angular-devkit/build-optimizer    0.803.19
@angular-devkit/build-webpack      0.803.19
@angular-devkit/core               8.3.14
@angular-devkit/schematics         8.3.14
@angular/cdk                       8.2.3
@angular/cli                       8.3.19
@angular/elements                  8.1.2
@angular/flex-layout               8.0.0-beta.27
@ngtools/webpack                   8.3.19
@schematics/angular                8.3.14
@schematics/update                 0.803.19
ng-packagr                         5.7.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Anything else relevant?**
Browser specific to IE11 or any other non-ever green browser

**Comment by alan-agius4** [comment] 2019-12-02 05:08
Duplicate of https://github.com/angular/angular-cli/issues/16275

**Closed by alan-agius4** 2019-12-02 05:08 UTC
