### ISSUE TITLE
Custom SSL Cert with Subdomain

### ISSUE THREAD

**Issue by fabich** [angular/angular-cli#9635] opened 2018-02-15 16:03 UTC
### Versions
```
Angular CLI: 1.6.8
Node: 8.9.4
OS: darwin x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.2.1
@angular/cli: 1.6.8
@angular/material: 5.2.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.7.1
webpack: 3.10.0
```
macOS 10.13.3 (17D47)

### Repro steps

1. Create SSL Cert:
```
openssl req -x509 -sha256 -nodes -days 3650 \
-newkey rsa:2048 -keyout project.priv.key \
-out project.priv.crt -subj "/CN=*.project.dev" \
-reqexts SAN -extensions SAN -config <(cat /usr/local/etc/openssl/openssl.cnf \
<(printf '[SAN]\nsubjectAltName=DNS:*.project.dev'))ß
```
2. Add the cert to the keychain and set trust to always.

3. Run application
```
ng serve --ssl 1 --ssl-key "_dev\certs\ngDev2.key" --ssl-cert "_dev\certs\ngDev.crt" --port 5000 --env=dev-online --host 0.0.0.0 --disable-host-check
```

### Observed behavior
tenant.project.dev:5000 uses an invalid security certificate. The certificate is not trusted because it is self-signed. The certificate is only valid for the following names: localhost, localhost.localdomain, lvh.me, *.lvh.me, [::1], 127.0.0.1, 127.0.0.1 

### Desired behavior
I expect to see a cert that is valid for the domain *.project.dev
Why is it different and where is the cert in the browser coming from?

There seems to be no issue running the same setup, with the same cert, on Windows 10

**Comment by mgechev** [comment] 2019-08-19 20:24
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:24 UTC
Labels: comp: devkit/build-angular, freq1: low, severity3: broken, type: bug/fix
