### ISSUE TITLE
updating "prefix" via "ng set" doesn't update tslint.json

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#4377] opened 2017-02-02 23:05 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
MacOS 10.12.2

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
angular-cli: 1.0.0-beta.26
node: 6.9.1
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

- init new project with default options for "prefix",  then
- `ng set apps.0.prefix=new`
- create a directive that uses selector prefix "new"
- run lint (`yarn lint`?)

you'll see that the linter still complains about the "app" prefix, this is because the `tslint.json` is still using the old "app" prefix rather than the new "new" prefix.

```
    "directive-selector": [true, "attribute", "app", "camelCase"],
    "component-selector": [true, "element", "app", "kebab-case"],
```

**Comment by hansl** [comment] 2017-02-21 19:34
Multiple reasons this doesn't work as of now:

1. the angular config and tslint config are separated to let users run `tslint` themselves (as part of, say, a CI run)
2. would require a lot of extra logic in `ng set` or `ng lint` to update the lint configuration.
3. if you use multiple prefixes, you don't want us to override those.

We recommend that you change your `tslint.json` to handle your app. This should realistically be a one time thing, and it's already done right if you pass in `--prefix` to `ng new`.

Closing this as working as intended.

**Closed by hansl** 2017-02-21 19:34 UTC
