### ISSUE TITLE
Lazy load a ngModule that has been packaged via npm

### ISSUE THREAD

**Issue by miladchamo** [angular/angular-cli#6297] opened 2017-05-12 19:55 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions.

![image](https://cloud.githubusercontent.com/assets/6742750/26014484/c042a45e-372a-11e7-92a0-1378c49340ef.png)

### Repro steps.

1. Create an ngModule (feature Module) and publish it to npm.
2. Install the published module into an angular app that has been created via the angular-cli
3. try to lazy load the npm installed module/package,  This seems to not be supported, as the current syntax for lazy loading expects something like the below, however, the npm installed module is installed into the node_modules folder. 
**{path: 'admin', loadChildren:'app/admin/admin.module#AdminModule'},**  

### Desired functionality.

Should be able to lazy load a module/package that has been installed via npm, similar to how we are able to lazy load feature modules that live within our angular application.

### Mention any other details that might be useful.

Looks like a similar issue was reported and acknowledged back in October, 2016, but, I haven't seen traction on this issue.
[https://github.com/angular/angular-cli/issues/2601](https://github.com/angular/angular-cli/issues/2601)

**Comment by ciesielskico** [comment] 2017-05-15 08:31
>Looks like a similar issue was reported and acknowledged back in October, 2016, but, I haven't seen traction on this issue.

Then why duplicate the issue?

**Comment by alan-agius4** [comment] 2018-09-03 06:34
Thanks for reporting this issue. However, this issue is a duplicate of #2601. Please subscribe to that issue for future updates.

**Closed by alan-agius4** 2018-09-03 06:34 UTC
Labels: need: investigation
