### ISSUE TITLE
Please move to v7.X.X of autoprefixer to replace caniuse-db with caniuse-lite

### ISSUE THREAD

**Issue by fr0** [angular/angular-cli#7345] opened 2017-08-10 14:32 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.3.0
node: 6.10.2
os: darwin x64

### Mention any other details that might be useful.

Autoprefixer now uses `caniuse-lite` instead of `caniuse-db`.
`caniuse-db` is 7+ MB, and `caniuse-lite` is much smaller (in `node_modules`). Updating to the latest version of `autoprefixer` would save a lot of disk space.

Would also be good to get the latest `cssnano` and `postcss-merge-rules`, as the versions you're currently depending on also have `caniuse-db` in their dependency chain.

**Comment by devoto13** [comment] 2017-08-10 16:05
Dupe of https://github.com/angular/angular-cli/issues/7271.

**Comment by filipesilva** [comment] 2017-08-24 11:02
Closing as duplicate of #7271.

**Closed by filipesilva** 2017-08-24 11:02 UTC
