### ISSUE TITLE
[TSLint] member-ordering: variables-before-functions

### ISSUE THREAD

**Issue by Shyam-Chen** [angular/angular-cli#6022] opened 2017-04-20 12:52 UTC
tsling warning with `@ngrx/effects`!

```ts
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import { Actions, Effect } from '@ngrx/effects';
import { Observable } from 'rxjs/Observable';

@Injectable()
export class AuthEffects {
  constructor(private http: Http, private actions$: Actions) { }

  @Effect() login$ = this.actions$
      .ofType('LOGIN')
      .map(action => JSON.stringify(action.payload))
      .switchMap(payload => this.http.post('/auth', payload)
        .map(res => ({ type: 'LOGIN_SUCCESS', payload: res.json() }))
        .catch(() => Observable.of({ type: 'LOGIN_FAILED' }))
      );
}
```

**Comment by sumitarora** [comment] 2017-04-20 15:14
@Shyam-Chen You can always update `tslint.json` file created by the project to support use case you are using if needed. Is there any specific issue you are facing?

**Comment by Shyam-Chen** [comment] 2017-04-21 09:38
Before

![default](https://cloud.githubusercontent.com/assets/13535256/25272018/c78352d6-26b8-11e7-85f8-fdc32fd12ab2.png)

***

```diff
    "member-access": false,
    "member-ordering": [
      true,
     "static-before-instance",
-     "variables-before-functions"
    ],
    "no-arg": true,
```

***

After

![default](https://cloud.githubusercontent.com/assets/13535256/25272115/39ee1464-26b9-11e7-91ce-fd338a930687.png)

**Comment by delasteve** [comment] 2017-04-21 13:55
@Shyam-Chen, this is working as intended. `constructor` is a function and your `@Effect`s are variable assignments.

**Comment by sumitarora** [comment] 2017-04-21 15:11
Closing as above.

**Closed by sumitarora** 2017-04-21 15:11 UTC
