### ISSUE TITLE
Snowpack support

### ISSUE THREAD

**Issue by criskrzysiu** [angular/angular-cli#19265] opened 2020-10-30 18:45 UTC
Hi, there is there any chance to even make Snowpack build tool work with Angular in dev environment? There are already plugins for other frameworks like Vue, Svelte, Preact, and most important Webpack. As Angular is using Webpack maybe it would be possible to make Angular work with Snowpack? Such an upgrade in development speed would be great. 

This is only a question if this would be even possible? Any bright minds that have answers?

### Relevant Package
probably 
@angular-devkit/build-angular
@angular/language-service
@angular/compiler-cli

**Comment by JoostK** [comment] 2020-10-30 19:03
I've transferred this to the CLI repo as it concerns bundling, which isn't done by the framework itself.

**Comment by alan-agius4** [comment] 2020-10-30 19:09
Duplicate of https://github.com/angular/angular-cli/issues/18599

**Closed by alan-agius4** 2020-10-30 19:09 UTC

**Comment by criskrzysiu** [comment] 2020-10-30 19:12
@alan-agius4  thx, I was looking at open issues in that's why I didn't find it. Still, that's a shame

**Comment by FredKSchott** [comment] 2020-10-30 20:18
It feels like this was closed by mistake. #18599 is locked with the instructions "Please file a new issue if you are encountering a similar or related problem", which @criskrzysiu did here
