### ISSUE TITLE
esbuild doesn't watch for local library changes while running dev server

### ISSUE THREAD

**Issue by marcusho21** [angular/angular-cli#25359] opened 2023-06-11 15:26 UTC
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

When working with multiple projects in an Angular workspace, running `ng build --watch` on the library living in the same workspace as host app, which is running using `ng serve`, whenever changes are being made to the library, host app doesn't trigger update when using esbuild. However, the expected behavior where host app dev server would trigger change update whenever a library gets changed works on the stable builder.

### Minimal Reproduction

1. create a library and an application in the same workspace
2. update angular.json to use esbuild by update "builder": "...browser" to "builder": "...browser-esbuild"
3. run ng build --watch on the library
4. run ng serve on the host app
5. make a change to the library and save
6. host app doesn't react to the library change

### Your Environment

```text
Angular CLI: 16.0.5
Node: 18.16.0
Package Manager: npm 9.7.1
OS: darwin arm64

Angular: 16.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.5
@angular-devkit/build-angular   16.0.5
@angular-devkit/core            16.0.5
@angular-devkit/schematics      16.0.5
@angular/cdk                    16.0.4
@angular/material               16.0.4
@schematics/angular             16.0.5
ng-packagr                      16.0.1
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by alan-agius4** [comment] 2023-06-12 06:01
Duplicate of https://github.com/angular/angular-cli/issues/25011

**Closed by alan-agius4** 2023-06-12 06:01 UTC
