### ISSUE TITLE
Asset url's doesn't load in Angular 11 

### ISSUE THREAD

**Issue by sakshamsri7** [angular/angular-cli#23002] opened 2022-04-18 08:19 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2

### Description
I upgraded Angular 8.2 to 11.2.14, after that all the asset url's present in css files started giving 404. (Not found)
My output path in angular.json is set as ("outputPath": "../Bundles") and also I am passing --deploy-url Bundles/ in build command and also in angular.json, but deploy url is not prepended in asset url's after build.

I have tried giving relative urls for images, that works but in case of font urls relative urls also doesn't work.

## 🔥 Exception or Error

<pre><code>

After I run ng build --deploy-url ./Bundles/ --extract-css --vendor-chunk=false command for build:
In style.scss, asset url is written as: '/assets/images/logo.png'

My asset url's in network are as http://localhost:6140/assets/images/logo.png [This is giving 404 not found]
It should be like : http://localhost:6140/Bundles/assets/images/logo.png [since I included deploy-url flag]

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 11.2.19
Node: 16.14.2
OS: win32 x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1102.19
@angular-devkit/build-angular     0.1102.19
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/core              11.2.19
@angular-devkit/schematics        11.2.19
@angular/cli                      11.2.19
@angular/http                     7.2.16
@schematics/angular               11.2.19
@schematics/update                0.1102.19
rxjs                              6.6.0
typescript                        4.1.6

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2022-05-02 08:18
Duplicate of https://github.com/angular/angular-cli/issues/15520

**Closed by alan-agius4** 2022-05-02 08:18 UTC
