### ISSUE TITLE
angular-cli@webpack ng generate component in sub folder - BUG

### ISSUE THREAD

**Issue by joejordanbrown** [angular/angular-cli#1818] opened 2016-08-23 22:13 UTC
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2
node: 4.4.3
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
When trying to generate a component inside a sub folder using:
ng generate component sub-folder/test-component

It adds a backwards slash instead of forward slash on the import inside the app.modules.ts like below:
import { TestComponentComponent } from './sub-folder\test-component/test-component.component';

**Comment by filipesilva** [comment] 2016-08-24 02:03
Dupe of https://github.com/angular/angular-cli/issues/1719

**Closed by filipesilva** 2016-08-24 02:03 UTC
