### ISSUE TITLE
Disable generate *.spec.ts files 

### ISSUE THREAD

**Issue by xTaz1** [angular/angular-cli#6082] opened 2017-04-25 20:44 UTC
How to disable *.spec.ts files generation when i generate components/services from console, like this `ng g component page1`

I use Angular CLI 1.0.0

**Comment by dave11mj** [comment] 2017-04-25 22:33
Seems related to https://github.com/angular/angular-cli/pull/6064 and https://github.com/angular/angular-cli/issues/6054 .. I used to think `--skip-tests` would not generate any any `.spec.ts` files like on beta. However, based on the comments of https://github.com/angular/angular-cli/issues/6054, it seems on 1.0.0 the intended behavior for `--skip-tests` was only to not generate the initial test file generated with the app component.

**Comment by xTaz1** [comment] 2017-04-26 06:26
@dave11mj, But what should i do if i already have created a project ?

**Comment by xTaz1** [comment] 2017-04-26 06:35
`--skip-tests` - does't work

**Comment by grizzm0** [comment] 2017-04-26 07:53
You can disable file generation through your angular-cli.json.
See: [schema.json](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/lib/config/schema.json) and search for spec. Each generate command has it's own config.

**Comment by sumitarora** [comment] 2017-04-26 13:14
Closing as above.

**Closed by sumitarora** 2017-04-26 13:14 UTC

**Comment by xTaz1** [comment] 2017-06-05 12:51
@grizzm0 how i can do it in angular-cli.json ? (for example component)

**Comment by grizzm0** [comment] 2017-06-05 12:57
Just read the spec. Set defaults.component.spec to false.

**Comment by it-discovery** [comment] 2017-10-13 15:21
Hi, @grizzm0 

I tried to globally disable generation of spec and css file(in .angular-cli.json) when I generate new component. However it doesn't work, files are still created.
I use Angular CLI 1.4.2

Here's my .angular-cli.json:

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "angular5"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {
      "properties": {
        "spec": {
          "default": false
        },
        "inlineStyle": {
          "default": true
        }
      }
    }
  }
}

**Comment by zenking** [comment] 2017-10-18 09:08
@it-discovery  Besides, you do write this on command line  `ng g c component-name     --spec false`

**Comment by kylevdr** [comment] 2017-11-12 21:10
@it-discovery it should be like this
``` json
{
  "defaults": {
    "component": {
      "spec": false
    }
  }
}
```

**Comment by alfmoh** [comment] 2018-06-21 20:43
For Angular 6

`ng config schematics.@schematics/angular.component.spec false`

**Comment by Mathias54** [comment] 2018-11-24 02:11
@alfmoh it worked for me. 

But, for module and service I had to put this extra configuration on my angular.json:

```
  "schematics": {
    "@schematics/angular": {
      "component": {
        "spec": false
      },
      "module": {
        "spec": false
      },
      "service": {
        "spec": false
      }
    }
  }
```

**Comment by sammirzagharcheh** [comment] 2019-03-27 02:32
You can run this command to disable spec file generation for a specific type of file:

ng set defaults.spec.FILETYPE false

For example:

ng set defaults.spec.component false // Won't generate spec files for .component files

Alternately you can just disable all spec file generation from the angular.json file.
`{
  ...
  "defaults": {
    "spec": {
      "class": false,
      "component": false,
      "directive": false,
      "module": false,
      "pipe": false,
      "service": false
    }
  }
}
`

**Comment by sergey-morenets** [comment] 2019-03-27 08:39
@sammirzagharcheh Isn't ng set deprecated in favor of ng config?
