### ISSUE TITLE
ng build for production corrupts index.jsp

### ISSUE THREAD

**Issue by ChaosNemesis** [angular/angular-cli#22890] opened 2022-03-24 23:35 UTC
# 🐞 Bug report

### Command (mark with an `x`)

ng.cmd build --progress false --configuration production

### Is this a regression?

✍️ Yes, the previous version in which this bug was not present was:  10, 
migrated to 13 last month. Debug builds are fine. We've been using index.jsp without problem since Dec 2017 

### Description

Using index as JSP (index.jsp) is corrupted by ng build command. See angular.json start below.

index.JSP starts:
<%@ page contentType="text/html; charset=UTF-8" %>
<%@ page import="java.util.Date"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:url var="faviconUrl" value="/public/servlet/asset">
  <c:param name="locale" value="default" />
  <c:param name="family" value="images" />
  <c:param name="key" value="main_favicon" />
  <c:param name="isText" value="false" />
</c:url>

<!doctype html>
<html lang="en">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link
    rel="shortcut icon"
    href="${faviconUrl}" type="image/x-icon" />
...
</head>
<body>
...
</script>
</body>
</html>

In the dist folder this becomes:

<html lang="en"><head></head><body>&lt;%@ page contentType="text/html; charset=UTF-8" %&gt;
&lt;%@ page import="java.util.Date"%&gt;
&lt;%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %&gt;

<c:url var="faviconUrl" value="/public/servlet/asset" scope="request">
  <c:param name="locale" value="default">
  <c:param name="family" value="images">
  <c:param name="key" value="main_favicon">
  <c:param name="isText" value="false">
</c:param></c:param></c:param></c:param></c:url>

<jsp:include page="/WEB-INF/content/javascript/br_analytics.jsp">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="${faviconUrl}" type="image/x-icon">
...
</head>
<body>
...
</script>
</body>
</html>
###   ----------------------------------------------------------
Note the rewrite completely fails to hand the self closing tags as well as re-arranging the HTML tag

I failed to see any mention of this in the migration notes.  Can this "feature" be disabled?

ng.cmd --version

Angular CLI: 13.2.5
Node: 16.14.0
Package Manager: npm 8.5.2
OS: win32 x64

Angular: 13.2.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cli                    13.2.5
@schematics/angular             13.2.5
rxjs                            6.6.7
typescript                      4.5.5

===  Start of angular.json
{
	"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
	"version": 1,
	"newProjectRoot": "projects",
  "defaultProject": "angular",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "app",
      "style": "css"
    },
    "@schematics/angular:directive": {
      "prefix": "app"
    }
  },
	"projects": {
		"angular": {
			"root": "",
			"sourceRoot": "src",
			"projectType": "application",
			"architect": {
				"build": {
					"builder": "@angular-devkit/build-angular:browser",
					"options": {
						"outputPath": "dist",
						"index": "src/index.jsp",
						"main": "src/main.ts",
						"tsConfig": "src/tsconfig.app.json",
						"polyfills": "src/polyfills.ts",
						"assets": [
							"src/assets",
							"src/favicon.ico"
						],

### ---- Start of package.json
{
  "name": "angular",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "node patches/patch-cli"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^13.2.4",
    "@angular/cdk": "^13.2.4",
    "@angular/common": "^13.2.4",
    "@angular/compiler": "^13.2.4",
    "@angular/core": "^13.2.4",
    "@angular/forms": "^13.2.4",
    "@angular/localize": "^13.2.4",
    "@angular/material": "^13.2.4",
    "@angular/platform-browser": "^13.2.4",
    "@angular/platform-browser-dynamic": "^13.2.4",
    "@angular/platform-server": "^13.2.4",
    "@angular/router": "^13.2.4",

**Comment by alan-agius4** [comment] 2022-03-25 06:37
Duplicate of https://github.com/angular/angular-cli/issues/20276#issuecomment-800053465

**Closed by alan-agius4** 2022-03-25 06:37 UTC
