### ISSUE TITLE
adding my own env files not working

### ISSUE THREAD

**Issue by sree526** [angular/angular-cli#8654] opened 2017-11-28 05:52 UTC
I would like to have different api endpoints based on environment. So i have created qa environment file in src/environments/environment.qa.ts and added that name to environments object in angular cli.json like "qa":'environments/environment.qa.ts' and while doing ngserve --env=qa its still taking dev evniroment url. I have imported enviroment in my app.component.ts like import { environment } from './environments/enviroment' and tried to access that api end point from console. What am i doing wrong;

**Comment by filipesilva** [comment] 2017-11-28 10:42
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #7305. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-11-28 10:42 UTC

**Comment by nicholasserra** [comment] 2017-12-18 18:53
@sree526 did you ever find a fix? I'm stuck on this issue also.

**Comment by sree526** [comment] 2017-12-19 02:05
Well, actually the issue was with angular cli version. When I updated it to
newest version in my project folder by using command npm install
@angular/cli@latest --save . The env files started working :-).
