### ISSUE TITLE
Overnight, unable to use localhost 4200 on Dev Containers

### ISSUE THREAD

**Issue by jamesikanos** [angular/angular-cli#27569] opened 2024-05-01 10:07 UTC
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

I have a VSCode dev container running several angular projects (ESbuild and Webpack).

Last night, I was able to access localhost:4200 (tunneled through the VSCode Dev Container) but this morning, I need to set the --host 0.0.0.0 flag.

I have tried a very simple node express server (just simply serving the phrase hello world on localhost:4200 inside the container and it works fine.

### Minimal Reproduction

To reproduce:
- Create and open a NodeJS VS Code dev container
   - mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
- `npm install -g @angular/cli`
- ng new
- ng serve

Expect:
- Host PC should access localhost:4200

Actual:
- Connection hangs (timeout in curl and chrome)

Workaround:
- Set host to 0.0.0.0 on the dev server inside the container

### Exception or Error

```text
Web server times out
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.6
Node: 20.12.0
Package Manager: npm 10.5.0
OS: linux x64

Angular: 17.3.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.6
@angular-devkit/build-angular   17.3.6
@angular-devkit/core            17.3.6
@angular-devkit/schematics      17.3.6
@schematics/angular             17.3.6
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.5
```

**Comment by alan-agius4** [comment] 2024-05-01 10:22
Duplicate of https://github.com/angular/angular-cli/issues/27439

See: https://stackoverflow.com/questions/77110607/frontend-app-running-inside-docker-container-not-accessible-from-browser/77111001 and https://github.com/vitejs/vite/discussions/6146 for more info.

**Closed by alan-agius4** 2024-05-01 10:22 UTC

**Comment by jamesikanos** [comment] 2024-05-01 13:16
Thanks @alan-agius4. But this affects the webpack server also, or, are they related? I have projects that use both esbuild and webpack.

**Comment by alan-agius4** [comment] 2024-05-01 15:30
This effects both vite and webpack-dev-server.
