### ISSUE TITLE
Unexpected Identifier in IE11

### ISSUE THREAD

**Issue by greygatch** [angular/angular-cli#18271] opened 2020-07-16 16:40 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 No

### Description

Unable to get Angular app running in IE11. I have changed the browserslist + polyfills.ts files to handle the IE11 changes, and that is not working. I have tried other hacky solutions, but none have worked.

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/6654025/87698459-1f567d00-c759-11ea-8564-3d130192ef44.png)

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.11
Node: 12.18.1
OS: win32 x64

Angular: 9.1.11
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.11
@angular/localize                 10.0.3
@ngtools/webpack                  9.1.9
@schematics/angular               9.1.11
@schematics/update                0.901.11
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

IE11

**Comment by greygatch** [comment] 2020-07-16 16:44
`# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
# For additional information regarding the format and rule options, please see:
# https://github.com/browserslist/browserslist#queries

# You can see what browsers were selected by your queries by running:
#   npx browserslist

> 0.5%
last 2 versions
Firefox ESR
not dead
IE 9-11 # For IE 9-11 support, remove 'not'.`

**Comment by greygatch** [comment] 2020-07-16 16:45
```
/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/guide/browser-support
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
 import 'classlist.js';  // Run `npm install --save classlist.js`.

/**
 * Web Animations `@angular/platform-browser/animations`
 * Only required if AnimationBuilder is used within the application and using IE/Edge or Safari.
 * Standard animation support in Angular DOES NOT require any polyfills (as of Angular 6.0).
 */
 import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 * because those flags need to be set before `zone.js` being loaded, and webpack
 * will put import in the top of bundle, so user need to create a separate file
 * in this directory (for example: zone-flags.ts), and put the following flags
 * into that file, and then add the following code before importing zone.js.
 * import './zone-flags';
 *
 * The flags allowed in zone-flags.ts are listed here.
 *
 * The following flags will work for all browsers.
 *
 * (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
 * (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
 * (window as any).__zone_symbol__UNPATCHED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames
 *
 *  in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
 *  with the following flag, it will bypass `zone.js` patch for IE/Edge
 *
 *  (window as any).__Zone_enable_cross_context_check = true;
 *
 */

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.


/***************************************************************************************************
 * APPLICATION IMPORTS
 */

 /**
 * Angular localization polyfill
 */
import '@angular/localize/init'
```

**Comment by greygatch** [comment] 2020-07-16 16:46
According to [this comment](https://github.com/angular/angular-cli/issues/16372#issuecomment-562677449), I shouldn't have to do anything else to get this running.

**Comment by alan-agius4** [comment] 2020-07-16 17:54
Duplicate of #14455

**Comment by greygatch** [comment] 2020-07-17 19:23
@alan-agius4 The previous issue is locked, and your comment describing a workaround did not solve the issue:

https://github.com/angular/angular-cli/issues/14455#issuecomment-493739768

Unable to get this running in IE.

**Comment by alan-agius4** [comment] 2020-07-17 19:45
@greygatch, can you please provide a minimal
reproduction?
A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by greygatch** [comment] 2020-07-17 20:35
@alan-agius4 I have traced it back to the `import '@angular/localize/init'` line in polyfills.ts. For some reason, including this line results in the IE errors?

**Comment by alan-agius4** [comment] 2020-07-17 20:42
@greygatch, and this happens when you have target set to `es5` in your `tsconfig.json`?

**Comment by greygatch** [comment] 2020-07-17 20:46
Yes, the target is correct.

Looks like the issue was resolved by downgrading the @angular/localize npm package from 10.x to 9.x.

**Comment by alan-agius4** [comment] 2020-07-17 23:47
@greygatch, it’s not recommended to mix angular packages version as it can cause undefined and broken behaviour.

The problem you are experiencing is that in version 10 Angular packages no contain ES5 version of the bundles. This is causing the runtime error because the old browser doesn’t support ES2015 syntax. 

In Angular CLI 10, when an application syntax is targeted to ES5, all JS, including vendors packages will be downlevelled from ES2015 to ES5.

**Closed by alan-agius4** 2020-07-17 23:47 UTC
Labels: comp: devkit/build-angular, devkit/build-angular: browser
