### ISSUE TITLE
Tree shaking and performance not optimized as staked

### ISSUE THREAD

**Issue by vairamsvsjdo** [angular/angular-cli#3844] opened 2017-01-04 03:37 UTC
>Tree shaking and performance not optimized as staked:
> ---------------------------------------------------------------

### OS?
> Linux (CentOS 7)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: linux x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

### Repro steps.
> This was created using angular-cli. The source can be found here:
https://github.com/vairamsvsjdo/ng-cli-examples/ng-test-parsing/

The distribution output of Prod can be found here:
https://vairamsvsjdo.github.io/ng-test-parsing/index.html

### The error is in performance and bundling size.
No errors

### Mention any other details that might be useful.
How to minimize the tree shaking on angular when only what is needed is little out of angular.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gelliott181** [comment] 2017-01-09 03:07
Bear with me, but from my understanding you are asking how to stop tree shaking from being done?

**Comment by vairamsvsjdo** [comment] 2017-01-09 14:03
No, I am pointing the fact that tree shaking is not shaking the dependency libraries used: angular. Hence the vendor bundle is huge. Does tree shaking gets rid off unused angular code? If not how can one go about doing that?

**Comment by gelliott181** [comment] 2017-01-09 14:48
Tree shaking the angular framework libraries should be happening, but it's also not unlikely that somewhere down the abstraction layers your code is in fact using nearly all of the framework (Especially the base framework package) that has been imported. I checked your test page and not only are response times well within reason, the vendor bundle is very small compared to one which heavily relies on Angular's features. Are there specific libs that you're concerned about?

Another thing to watch will be the changes in the AOT compiler with the next few releases. Tree shaking is going to have its foundation rattled a little bit while the steps before it have the bugs knocked out.

**Comment by vairam-bcf** [comment] 2017-01-09 17:59
I was looking for a tree shaken angular that I can get to 50KB or less. I understand each product are trying to market what their strength is. I am trying to find a happy medium that angular 2 can present itself to be used as a powerful static web application, progressive web application JS library stack.

https://vuejs.org/v2/guide/comparison.html#Size-and-Performance
http://stefankrause.net/js-frameworks-benchmark4/webdriver-ts/table.html

**Comment by gelliott181** [comment] 2017-01-09 18:15
You're going to have to find a custom solution to handle cutting down the vendor bundle that much. If I'm not mistaken the current CLI base project's vendor bundle still comes in at a couple hundred kilobytes using the `--aot` and `--prod` flags.

**Comment by deebloo** [comment] 2017-01-09 18:29
A standard Hello World app using the CLI. So just a single app module and single app component using as few modules as possible will give you all app that is around 80kb. If you cut down on the polyfills you can get it to around 71k;

**Comment by PEsteves8** [comment] 2017-01-09 18:51
I have a project with a few tables, some of them (temporarily) end up with a lot of in memory data. This allows me to notice small delays on activating a dropdown when I click on it. If there is a lot of in memory data, the longer it'll take. 

I noticed that using ng build --prod, generates a version which is faster to load, but it takes noticeably longer to show a dropdown when I click. 

Navigating from one section to the other is also slower. **So the app actually ends up having worse performance**. I can't really imagine what could cause this. Is it a common problem?

**Comment by filipesilva** [comment] 2017-01-24 13:01
Dupe of https://github.com/angular/angular-cli/issues/2901. It's a webpack thing atm, tracked in webpack/webpack#2899.

**Closed by filipesilva** 2017-01-24 13:01 UTC
