### ISSUE TITLE
we need Angular Cli webpack to be configurable for build files.

### ISSUE THREAD

**Issue by samehmagdytawfik** [angular/angular-cli#3237] opened 2016-11-22 16:50 UTC
I need webpack to be configurable for build and dev... special;;y for dev it's not fair to work with dev env on webpack host I need for example to host that on IIS as i need to use the windows authentication while working on dev environment.. 

we need that fix asap, it's very important for angular cli users to have an opertunity to configure all their webpack option. we should be able to debug and use windows authentication in development mode.. 

regards,
Sameh

**Comment by grizzm0** [comment] 2016-11-22 17:19
If you heavily depend on custom configuration then angular-cli might not be for you and a custom webpack setup might be a better choice. 

An addon system is planned, but that's after v1.0 sometime next year.

**Comment by dherges** [comment] 2016-11-22 18:59
see also #2047

@samehmagdytawfik i propose a temporary solution to you: add a ``webpack.config.js`` to the root folder of your repo and try to ``require('angular-cli/packages/angular-cli/models/webpack-build-common.ts').getWebpackCommonConfig()`` and customize that. it's going to be a lot of work though and you need to add custom npm scripts llike to your ``package.json``. see https://github.com/angular/angular-cli/blob/master/packages/angular-cli/models/webpack-build-common.ts

**Comment by filipesilva** [comment] 2016-12-22 18:47
I know @grizzm0's answer wasn't what you were looking for, but it's the accurate one.

Also dupe of https://github.com/angular/angular-cli/issues/1656

**Closed by filipesilva** 2016-12-22 18:47 UTC
