### ISSUE TITLE
Page not reloading when changing *.scss or *.css anymore

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#946] opened 2016-05-28 08:33 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**Windows 10**

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
**angular-cli: 1.0.0-beta.5
node: 4.4.5
os: win32 x64**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
**Install NodeJS, Install Angular CLI, change a css file 'the one in the app folder' or change it to a scss file and change it. Nothing happends.**

4. The log given by the failure. Normally this include a stack trace and some
   more information.
**No errors.**

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**When I press F5 I can see the changes i did, like h1 { color: red; }
When I change a html or ts file, it does auto reload.**

**Comment by Splaktar** [comment] 2016-05-29 05:31
Can you confirm that it does not update the page with your styling change? Sometimes it can do this without a reload.

**Comment by masaanli** [comment] 2016-05-29 08:40
@Splaktar Yes what I can remmeber when I used the Angular CLI version from 4 weeks ago and I did styling changes it did a reload of the page. Now not anymore, tried several 'css and scss' files in muliple places. Never did a  reload now. (I must always do a F5 in the browser)

**Comment by AncaIO** [comment] 2016-05-30 14:07
I can confirm this issue. CSS changes alone will not trigger a livereload even though the css file does seem to be watched - I get the "file changed app/ms-cli-rc1.component.css" message in the terminal... 

Once a *.ts or *.html file is changed and saved, the livereload will work as expected.

**Comment by daco** [comment] 2016-05-31 07:21
I have the same issue. Moreover, in earlier builds the styles where changed without a page reload. Which is much nicer considering that a reload takes a long time with RC1

**Comment by fmoessle** [comment] 2016-06-01 12:35
Same over here

**Comment by gelidus** [comment] 2016-06-01 13:11
Guys you need to install node-sass for this locally:

`npm install node-sass --save`

**Comment by filipesilva** [comment] 2016-06-02 14:56
Closing as a duplicate of https://github.com/angular/angular-cli/issues/946, but resolution will continue there.

**Closed by filipesilva** 2016-06-02 14:56 UTC
Labels: command: serve, type: bug
