### ISSUE TITLE
Angular Move, Rename, Delete

### ISSUE THREAD

**Issue by NoahFlowa** [angular/angular-cli#14081] opened 2019-04-04 18:14 UTC
# 🚀 Feature request
Add 3 new commands to speed up and improve QOL for Angular projects and the Angular CLI by introducing ng move, ng rename and ng delete

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...
I believe that Angular should have a dedicated set of commands for Moving components, modules and services as well as Renaming and Deleting them right from the CLI.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
I propose the solutions to the three new commands should look like:

ng move [ng mv] currentPathofFolderFile newPathofFolderFile
ng rename [ng rn] oldFolderFileName newFolderFileName
ng delete [ng del] folderFileName

Doing these commands should update the path references for the components/modules/services and of course do the intended action.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
There are a couple VSCode extensions that sort of do this, the most popular being MoveTS but that doesnt update the file paths for angulars needs and ends up making the build fail as it uses the wrong path type.  

Also not everyone who works with Angular uses VSCode as their IDE so they dont have the option for MoveTS like extensions.

**Comment by alan-agius4** [comment] 2019-04-05 13:46
Duplicate of https://github.com/angular/angular-cli/issues/900

**Closed by alan-agius4** 2019-04-05 13:46 UTC
