### ISSUE TITLE
Cannot read property 'glob' of null

### ISSUE THREAD

**Issue by mkdebie** [angular/angular-cli#5231] opened 2017-03-05 01:37 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Ubuntu 16.04

### Versions.
@angular/cli: 1.0.0-rc.1
node: 7.6.0
os: linux x64

### Repro steps.
When I create an app in angular cli, every ng command results in a crash resulting in the output below. Since being stuck in the very early phase, none of the files created by angular/cli where touched I have no clue how to fix this.

### The log given by the failure.
Cannot read property 'glob' of null
TypeError: Cannot read property 'glob' of null
    at ObjectSchemaTreeNode._set (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:224:131)
    at new ObjectSchemaTreeNode (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:209:14)
    at OneOfSchemaTreeNode._createChildProperty (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:161:25)
    at Array.map (native)
    at OneOfSchemaTreeNode (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:160:48)
    at ArraySchemaTreeNode._createChildProperty (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)
    at ArraySchemaTreeNode._set (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:286:39)
    at new ArraySchemaTreeNode (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:267:14)
    at ObjectSchemaTreeNode._createChildProperty (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)
    at ObjectSchemaTreeNode._set (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:224:45)
    at new ObjectSchemaTreeNode (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:209:14)
    at ArraySchemaTreeNode._createChildProperty (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)
    at ArraySchemaTreeNode._set (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:286:39)
    at new ArraySchemaTreeNode (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:267:14)
    at RootSchemaTreeNode._createChildProperty (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)
    at RootSchemaTreeNode._set (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:224:45)
    at RootSchemaTreeNode.ObjectSchemaTreeNode (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:209:14)
    at RootSchemaTreeNode (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-tree.js:307:9)
    at GeneratedSchemaClass.SchemaClassBase (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-class-factory.js:53:29)
    at GeneratedSchemaClass (/home/mihaly/mroizo/node_modules/@ngtools/json-schema/src/schema-class-factory.js:144:13)
    at new CliConfig (/home/mihaly/mroizo/node_modules/@angular/cli/models/config/config.js:18:24)
    at Function.fromConfigPath (/home/mihaly/mroizo/node_modules/@angular/cli/models/config/config.js:81:16)
    at Function.fromProject (/home/mihaly/mroizo/node_modules/@angular/cli/models/config.js:90:46)
    at Object.<anonymous> (/home/mihaly/mroizo/node_modules/@angular/cli/commands/build.js:7:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (/home/mihaly/mroizo/node_modules/@angular/cli/addon/index.js:15:16)
    at /home/mihaly/mroizo/node_modules/@angular/cli/ember-cli/lib/models/project.js:287:61
    at Array.forEach (native)
    at Project.addonCommands (/home/mihaly/mroizo/node_modules/@angular/cli/ember-cli/lib/models/project.js:286:15)
    at Project.eachAddonCommand (/home/mihaly/mroizo/node_modules/@angular/cli/ember-cli/lib/models/project.js:321:30)
    at module.exports (/home/mihaly/mroizo/node_modules/@angular/cli/ember-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/home/mihaly/mroizo/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:46:26)
    at tryCatch (/home/mihaly/mroizo/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/mihaly/mroizo/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/mihaly/mroizo/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/mihaly/mroizo/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
.

### Mention any other details that might be useful.

**Comment by intellix** [comment] 2017-03-06 15:37
Duplicate of #4919

**Closed** 2017-03-06 15:37 UTC

**Comment by xe4me** [comment] 2017-03-07 05:51
Same here 
Works fine in my mac
not in ubunto

**Comment by balr404** [comment] 2017-05-09 23:02
I have tried the following option to resolve the issue
Steps to resolve the issue

$ pwd
it shows —> /Users/YourName /*** That is your Home path***/
Execute the below command to display the hidden files

$ defaults write com.apple.Finder AppleShowAllFiles true
$ killall Finder
After executing the above command you will see the hidden files.
if “.angular-cli.json” file exist under “/Users/yourname” (i.e Home Path) then remove “.angular-cli.json” file.

then navigate to your application path and try execute ‘ng’ command.

**Comment by balr404** [comment] 2017-05-09 23:03
I have tried the following option to resolve the issue
Steps to resolve the issue

$ pwd
it shows —> /Users/YourName /*** That is your Home path***/
Execute the below command to display the hidden files

$ defaults write com.apple.Finder AppleShowAllFiles true
$ killall Finder
After executing the above command you will see the hidden files.
if “.angular-cli.json” file exist under “/Users/yourname” (i.e Home Path) then remove “.angular-cli.json” file.

then navigate to your application path and try execute ‘ng’ command.

**Comment by balr404** [comment] 2017-05-09 23:03
I have tried the following option to resolve the issue
Steps to resolve the issue

$ pwd
it shows —> /Users/YourName /*** That is your Home path***/
Execute the below command to display the hidden files

$ defaults write com.apple.Finder AppleShowAllFiles true
$ killall Finder
After executing the above command you will see the hidden files.
if “.angular-cli.json” file exist under “/Users/yourname” (i.e Home Path) then remove “.angular-cli.json” file.

then navigate to your application path and try execute ‘ng’ command.

**Comment by manoz2000** [comment] 2017-06-12 09:18
In windows:
Delete "angular-cli.json" file
C:\Users\your name\angular-cli.json
then run ng serve again.

**Comment by kirillgroshkov** [comment] 2017-08-30 21:17
I don't have any extra .angular-cli.json files, but still get this error. Help!

**Comment by cisrakesh** [comment] 2017-10-09 09:07
Facing same error , there isn't any additional .angular-cli.json

**Comment by abhishek-nyllabs** [comment] 2017-11-05 01:58
It worked for me. Deleted hidden file angular-cli.json file in home directory.

**Comment by luizlucasi** [comment] 2017-11-23 01:11
On mac 

rm ~/.angular-cli.json

worked for me

**Comment by afzal00** [comment] 2018-01-24 05:19
It working for me in window  by deleting this '.angular-cli.json'file from the 'c:/Users/user-name/.angular-cli.json'

**Comment by coolrb** [comment] 2018-06-16 18:41
on CentOS7
rm ~/.angular-cli.json
worked for me as well
