### ISSUE TITLE
@angular/build:library builder?

### ISSUE THREAD

**Issue by pweyrich** [angular/angular-cli#27962] opened 2024-06-28 18:34 UTC
### Command

build

### Description

The new @angular/build package was a great little surprise included in the v18 release! 🚀 

As of today, the @angular/build package is offering workspaces that are only using the new application builder a great opportunity to strip down a lot of dependencies 👍 
Workspaces that include libraries however can unfortunately not yet benefit here as the package is currently missing a library builder - one is still required to install the @angular-devkit/build-angular package for that purpose.

That's why I was wondering whether there are any plans on providing a library builder with the new @angular/build package?

Also, will you give packaging libraries with esbuild another shot? (as https://github.com/ng-packagr/ng-packagr/commit/9c238273c9057108744c9f9ef8c7d9e62225c0f1 has been reverted as it seems)

### Describe the solution you'd like

Provide a library builder with the @angular/build package (which ideally would also be based on esbuild in order to keep the dependency footprint small)

### Describe alternatives you've considered

There are no alternatives. As mentioned above, one is still required to use the @angular-devkit/build-angular:ng-packagr builder in workspaces that include libraries.

**Comment by alan-agius4** [comment] 2024-06-28 18:40
Duplicate of https://github.com/angular/angular-cli/issues/27593

**Closed** 2024-06-28 18:39 UTC
