### ISSUE TITLE
Differential loading continues generating ES5 bundle when disabled

### ISSUE THREAD

**Issue by asalopez** [angular/angular-cli#22505] opened 2022-01-13 13:31 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Unsure but there are a lot of closed issues with no apparent solutions.

### Description

ES5 bundle is generated even with the correct browserlist and TS configs.

## 🔬 Minimal Reproduction

Change your _.browserslistrc_ file with:
<pre><code>
last 1 Chrome version
</code></pre>

Set up your _tsconfig.json_ with the option:

<pre><code>
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "typeRoots": ["node_modules/@types"],
    "types": ["jest", "node"],
    "lib": ["es2018", "dom", "es2020.string"],
    "skipLibCheck": true
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableIvy": true
  }
}
</code></pre>

## 🔥 Exception or Error

ES5 bundle is still generated:

![image](https://user-images.githubusercontent.com/33123192/149338185-c9d989d4-5b87-4b6f-9ab1-9653e3a9f387.png)

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.2.12
Node: 16.13.2 (Unsupported)
Package Manager: yarn 1.22.5
OS: win32 x64

Angular: 12.2.12
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.12
@angular-devkit/build-angular   12.2.12
@angular-devkit/core            12.2.12
@angular-devkit/schematics      12.2.12
@angular/flex-layout            12.0.0-beta.35
@schematics/angular             12.2.12
rxjs                            6.5.5
typescript                      4.3.5
webpack                         5.61.0

Warning: The current version of Node (16.13.2) is not supported by Angular.

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2022-01-13 17:44
I'm sorry, but we can't reproduce the problem following the instructions you provided. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `npx @angular/cli@12 new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2022-01-17 10:34
Closing since no reproduction was provided. 

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem. 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Closed by alan-agius4** 2022-01-17 10:34 UTC
Labels: need: repro steps
