### ISSUE TITLE
Creating a new project fails -  ng new PROJECT-NAME

### ISSUE THREAD

**Issue by fad250** [angular/angular-cli#12732] opened 2018-10-24 12:01 UTC
### Bug Report or Feature Request (mark with an `x`)

```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 7.0.2
Node: 8.11.1
OS: win32 x64

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3
```

### The log given by the failure

```
Schematic input does not validate against the Schema: {"name":"test"}
Errors:

  Data path "" should have required property 'version'.
```
### Desired functionality

A new project is created

**Comment by alan-agius4** [comment] 2018-10-24 12:51
Duplicate of #12733 12690

**Closed by alan-agius4** 2018-10-24 12:51 UTC

**Comment by rafaelzuckerberg** [comment] 2019-03-26 20:08
Run "npm update" and after run "ng new your-project --version=7.3.6"

**Comment by yogeshdotnet** [comment] 2019-04-29 02:59
HI,
This issue may be resolved by applying the following command in cmd.

**npm i @schematics/angular@latest --save-dev**

after applying this no need to write version after angular 7 project name just write
**ng new ang-project-name**

**Comment by Rajeshpeyala** [comment] 2019-07-23 09:52
> HI,
> This issue may be resolved by applying the following command in cmd.
> 
> **npm i @schematics/angular@latest --save-dev**
> 
> after applying this no need to write version after angular 7 project name just write
> **ng new ang-project-name**
> 
> For Online Angular Training please visit [https://www.yogeshdotnet.com](url)

It's solved my issue. Thank you so much Sir
