### ISSUE TITLE
add optional "input" and "output" paths to "index" in angular-cli.json

### ISSUE THREAD

**Issue by nekkon** [angular/angular-cli#7309] opened 2017-08-09 11:21 UTC
It would be great if "input" and "output" optional paths were added to "index" in angular-cli.json. There are scenarios that can not be covered with current implementation. (even using deployUrl)

With the current implementation the path of index.html after build is forced to be the same with the location during development. This is not always the case. An example is when folder structure in development is different than production. In such case the output path of the index.html can not be the same. 

For example in angular-cli.json:

{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "project": {
        "name": "orco-frontend"
    },
    "apps": [
        {
            "name": "dm",
            "root": "src",
            "outDir": "dist/dm",
            "assets": [
                { "glob": "**/*", "input": "dm/assets/", "output": "./assets/" },
                { "glob": "favicon.ico", "input": "dm/", "output": "./" },
                { "glob": "**/*", "input": "shared/assets", "output": "./assets/" }
            ],
            "index": "dm/index.html",
            "deployUrl": "./",

In this example there is an app (dm) in src folder. The index.html file after build ends up in dist/dm/dm/index.html while it needs to be in dist/dm/index.html. 

Even if you change outDir to the folder: "new location", index.html will still be built to the folder "new location"/dm/index.html. All the rest of the necessary files of the build will end up in the folder "new location" which is not the proper file/folder structure. This should not be forced to happen.

**Comment by intellix** [comment] 2017-08-09 12:02
I'm thinking that this is more of a bug really. I think the index.html should always be in the root directory and not copied across with it's directory structure, since JS is forced into the root as well

**Comment by out-of-memory** [comment] 2017-08-09 13:13
I have similar requirement, but with slight difference... I am not able to find any solutions and neither I was able to find any tickets around for that. If there is one then I am really sorry but please redirect me. 
My requirement is simple... 
I have multiple index.html files... 
like index.html, index.stage.html, index.prod.html 
now at the time of build I want "ng build" to pick index.stage.html and convert it to index.html,  
if  --env=stage. Is this possible.

**Comment by nekkon** [comment] 2017-08-09 13:38
@out-of-memory Maybe [this](https://github.com/angular/angular-cli/issues/4451#issuecomment-285026543) can help you? Also, you don't explain why you would like something like that to happen. I think what you request is different than this issue.

**Comment by intellix** [comment] 2017-08-09 14:27
Found the culprit: https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/models/webpack-configs/browser.ts#L67

If that's hardcoded to index.html then we get the solution that we're after:

```
filename: path.resolve(buildOptions.outputPath, 'index.html'),
```

**Comment by grizzm0** [comment] 2017-08-09 14:39
The reason you end up with dist/dm/dm/index.html is because you have dm in both index and outDir. Change index to index.html, src to src/dm and outDir to dist/dm.

See #7124 where I posted a more in depth response about this.

**Comment by nekkon** [comment] 2017-08-09 16:13
@grizzm0 Yes "dm" is both in index and outdir. I was forced to cause of an [issue](https://github.com/angular/angular-cli/issues/5986) which is not solved yet. Also, could you confirm if the solution you [suggest] (https://github.com/angular/angular-cli/issues/7124#issuecomment-317641320) works with lazy loaded modules?

 It would be great if "input" and "output" optional paths were added to "index". It does not harm anyone and index.html is not forced to have the same path (from root folder) in production and development.

**Comment by intellix** [comment] 2017-08-09 18:54
I feel like the index.html should always be at root, so it's on the same level as the scripts it needs to load which are always at root

**Comment by nekkon** [comment] 2017-08-09 19:05
@intellix In case you manage it 100%, also test your solution on the example I [have](https://github.com/nekkon/angular-cli-library) . If it works after you build the app with --prod flag (npm run app1:build) then everything should be fine.

**Comment by nekkon** [comment] 2017-08-09 20:01
@grizzm0 I have an example [here](https://github.com/nekkon/angular-cli-library) . You can edit the tsconfig based on your solution and try running ng build --app app1 --prod  to see if it can be built.

**Comment by intellix** [comment] 2017-08-09 22:37
I've added an example using a different root property amongst a few other things like SCSS Vars and Image replacement: https://github.com/intellix/angular-cli-library

Thanks to @nekkon and @grizzm0 it serves, builds and can be tested. IDE is reporting that `core/*` imports don't exist so it's not perfect. I'll see about perfecting it

**Comment by nekkon** [comment] 2017-08-10 06:46
@intellix Your example does not work with AOT. Also you do not lazy load the module which is a common scenario. Add --prod flag to your build commands and see what I am talking about.

**Comment by nekkon** [comment] 2017-08-10 08:02
@grizzm0 @intellix I have created a new [branch](https://github.com/nekkon/angular-cli-library/tree/intellix_grizzm0_suggestion) with an example of a lazy loaded module of the shared code. It follows your suggestions/solution. ng serve works, ng build works but ng build --prod **does not**. There are open issues with angular-cli that do not allow your suggestion/solution/examples to work. That is why I created the repo **angular-cli-library**. In that repo AOT works with/without lazy loaded modules, which is something important if you want your app to be built for production. The only problem is that index file ends up in "app-name/index.html" instead of the outDir folder. That is why I created this issue. Until then, if you copy/transfer index.html to the parent folder everything works properly. This is why I ask for the functionality @marcincichocki requested.

**Comment by filipesilva** [comment] 2017-08-10 10:50
`index` keeping the relative path inside `outDir` as it does inside `root` is not a bug, but intended. I don't have a PR on hand but this was requested some time ago and is now part of the feature set.

It's part of an overall philosophy we follow that relative paths should always be maintained.

**Comment by nekkon** [comment] 2017-08-10 11:46
@filipesilva The functionality I request [exists](https://github.com/angular/angular-cli/blob/809340a8f0ae1302cba2628bbb2889d943cc3a0c/docs/documentation/stories/asset-configuration.md) "input is relative to the project root (src/ default), while output is relative to outDir (dist default)." Relative paths are not maintained in assets, something I agree with and find it very helpful. I ask for the same to be applied to `index`.

**Comment by filipesilva** [comment] 2017-08-10 21:25
It does exist for assets, yes. Mostly to support copying stuff from node_modules though, which is necessarily outside the source directory.

Is there something that prevents you from moving `src/dm/dm/index.html` one directory up though? That would give you the output you're looking for.

**Comment by grizzm0** [comment] 2017-08-10 22:30
@filipesilva This whole issue is about multiple apps more or less. I've suggested to change the root to src/dm and keep index as index.html.

This is related to what you and @intellix discussed on slack earlier today with the AOT issue.

**Comment by nekkon** [comment] 2017-08-11 06:45
@filipesilva Yes I can not move one directory up. I can not use @grizzm0 's suggestion as AOT does not work with modules that are lazily loaded outside the project . I do understand that under normal conditions @grizzm0 's suggestion is the way to go, but there are open issues (ex [#5986](https://github.com/angular/angular-cli/issues/5986) ) that prevent his solution to work 100% at the moment. That's why I asked to add the optional paths.

**Comment by intellix** [comment] 2017-08-11 09:00
The PR I've created flattens the output location of index.html so that it always exists at the root of the application alongside the JS bundles. I still think this is correct as you can't request JS files like: `../vendor.js` unless you do some Node hackery. 

Basically an index.html in another folder upwards will never work out of the box without https://github.com/angular/angular-cli/pull/7314

**Comment by nekkon** [comment] 2017-08-11 09:24
@intellix "you can't request JS files like: ../vendor.js" -> deployUrl can be used to do that. Just telling you so you know. I did it by setting "deployUrl": "./". That's why index.html works properly in the root folder in "dist/dm" although it is built in "dist/dm/dm". If I had set it to "../" it would had done what you say it can't. 

@intellix Your PR does solve the problem we have, but it could create problems/issues to users that want it to work otherwise. I would support you if that might not happen. That's why I asked for the optional paths for index as that wouldn't cause any problem/issues to anyone, but give more options to developers. 

I believe things should be flexible for each developer to have enough options that cover all possible scenarios. If you make things too strict, absolute and you miss usage scenarios, you disappoint them and make them feel that this was built only for a few people/companies and not for everyone.

**Comment by filipesilva** [comment] 2017-08-21 10:25
If https://github.com/angular/angular-cli/issues/5986 is what prevents @grizzm0's approach from working, it should be fixed instead as it's supposed to work.

Bear in mind that sharing code directly between apps without a library is not an officially supported usecase... It might or might not work with paths.

**Comment by intellix** [comment] 2017-08-21 11:38
@nekkon I've changed my example repository to look closer to yours, as that's working better for us at the moment as well. One thing that's not supported there though still is `CoreModule` lazy loading it's own things. I think this is probably related to #5986 where another "package" can't lazy-load it's own things. It works to serve and without AOT though.

```
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve '/Sites/github/intellix/angular-cli-library/src/$$_gendir/core/modules/lazy/lazy.module.ngfactory.ts' in '/Sites/github/intellix/angular-cli-library/src/$$_gendir'
resolve '/Sites/github/intellix/angular-cli-library/src/$$_gendir/core/modules/lazy/lazy.module.ngfactory.ts' in '/Sites/github/intellix/angular-cli-library/src/$$_gendir'
  using description file: /Sites/github/intellix/angular-cli-library/package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Sites/github/intellix/angular-cli-library/package.json (relative path: ./src/$$_gendir)
    using description file: /Sites/github/intellix/angular-cli-library/package.json (relative path: ./src/$$_gendir/core/modules/lazy/lazy.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Sites/github/intellix/angular-cli-library/src/$$_gendir/core/modules/lazy/lazy.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Sites/github/intellix/angular-cli-library/src/$$_gendir/core/modules/lazy/lazy.module.ngfactory.ts.tsdoesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Sites/github/intellix/angular-cli-library/src/$$_gendir/core/modules/lazy/lazy.module.ngfactory.ts.jsdoesn't exist
      as directory
        /Sites/github/intellix/angular-cli-library/src/$$_gendir/core/modules/lazy/lazy.module.ngfactory.ts doesn't exist
[/Sites/github/intellix/angular-cli-library/src/$$_gendir/core/modules/lazy/lazy.module.ngfactory.ts]
[/Sites/github/intellix/angular-cli-library/src/$$_gendir/core/modules/lazy/lazy.module.ngfactory.ts.ts]
[/Sites/github/intellix/angular-cli-library/src/$$_gendir/core/modules/lazy/lazy.module.ngfactory.ts.js]
[/Sites/github/intellix/angular-cli-library/src/$$_gendir/core/modules/lazy/lazy.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/red/main.ts
 @ multi ./src/red/main.ts
```

**Comment by nekkon** [comment] 2017-08-21 17:13
@intellix CoreModule has no issues in being lazy loaded, as with any other module being loaded from inside the "src" directory/subdirectory. From the [error message](https://github.com/angular/angular-cli/issues/7309#issuecomment-323721665) above I think your problem is with not updating angular-cli to the latest version properly, for example [#7341](https://github.com/angular/angular-cli/issues/7341). Many users have had that issue cause they updated just by changing the version in package.json. There is a discussion generally about updating [here](https://github.com/angular/angular-cli/issues/7375).

**Comment by intellix** [comment] 2017-08-21 20:16
I don't believe your repository has solved the same thing:
`app1` lazy loads a component from `app1` that depends on something from `shared`

The problem I'm having is that I already have a huge application. I just need to change SCSS variables and Images depending on the app. That means I have this not working:

`shared` depends on a lazy-module from `shared`. `app1` imports `SharedModule`. It's essentially something outside of src not being able to lazy-load it's own stuff.

**Comment by nekkon** [comment] 2017-08-22 05:06
@intellix 'shared' depends on a lazy-module from 'shared'. 'app1' imports 'SharedModule'

You can also do that and it works. The only restriction is for all modules to be in the src folder (either in shared or in each app). If you want the files to be outside the src folder there is an issue open which does not allow you to.

**Comment by Lakston** [comment] 2017-11-22 13:20
Has something been done to manage this in the end ?

I have a multi app setup and my index output for (for example) "app2" is `build-app2/app/modules/app2/index.html` instead of `build-app2/index.html` because the path of my index in my dev folder is copied to the build folder : 

```
      "name": "app2",
      "root": "src",
      "outDir": "dist-app2",
      "index": "app/modules/app2/index.html",
```

**Comment by demilsson** [comment] 2017-12-07 10:48
@Lakston That's a nice idea, but the opposite problem will then occur with the assets. 

Say the folder structure is like this:

    [project]
        [src]
            main-app2.ts
            polyfills.ts
            (etc)
            [apps]
                [app2]
                    [styles]
                        styles.scss
                    app.module.ts
                    index.html
            [assets]
                image.png

And that the app config is 

    "name": "app2",
    "root": "src/apps/app2",
    "outDir": "dist/app2",
    "assets": ["../../assets"], <-- relative path to root
    "index": "index.html",
    "main": "../../main-app2.ts",
    "polyfills": "../../polyfills.ts",
    "tsconfig": "../../tsconfig.app.json",
    "testTsconfig": "../../tsconfig.spec.json",
    "styles": ["styles/styles.scss"],
    "scripts": [],
    "environmentSource": "../../environments/environment.ts",

The output of the build will then be:

    [project]
        [dist]
            [app2]
                index.html
                (etc)
        [assets] <-- asset folder is added to the project root folder
            image.png

Since the assets folder was accessed using a relative path, it is also seems to be copied using the same relative path, in this case two levels above the dist folder. 

We definitely need a flexible way to deal with this.

**Comment by Lakston** [comment] 2017-12-08 07:20
I have since found a batter way to handle my 4 apps, it required me to duplicate some files and folders (like my assets) but I am happy of how things are going now.

I've read some commits and found out about the `appRoot` option (I think it was introduced in [this commit](https://github.com/angular/angular-cli/commit/b6dfa8d52c7c7177c647760675bf2132838a03b0)) so now my `angular-cli.json` files looks like this : 

```
 {
      "name": "app",
      "root": "src/modules/app",
      "appRoot": ".",
      "outDir": "dist-app",
      "assets": ["assets"],
      "index": "index.html",
      "main": "main-export.ts",
      ... many params,
      "environmentSource": "../../environments/environment.ts",
      "environments": {
        "dev": "../../environments/environment.ts",
        "prod": "../../environments/environment.prod.ts"
      }
    },
    {
      "name": "app2",
      "root": "src/modules/"",
      "appRoot": ".",
      "outDir": "dist-"",
      "assets": ["assets"],
      "index": "index.html",
      "main": "main-app2.ts"
      }
    },
```

I have duplicated quite a few files but now the benefit of this is that I can generate things via the CLI, the proper paths will be respected and the right app module will get updated like so : 
`ng g c components/new-component --app app2`

It will create the components in the right place and update `app2.module.ts`

I am in the process of making typescript aliases so I can avoid some `../../../` paths for shared files and I'm sure I am not even touching on the potential of `appRoot`, hopefully some doc will come out or someone smarter than me will show us the 'proper way' !

But for now, this works !

**Comment by nekkon** [comment] 2017-12-08 08:02
@Lakston Hi, can you explain how appRoot is different than setting the root folder of the app? As I see from your example both apps have "." as the value. How does setting "." change things? Maybe this new parameter could solve the "index" issue. Thanks in advance and for pointing out this new parameter. Maybe @vsavkin can explain it to us or add it to the docs?

**Comment by Lakston** [comment] 2017-12-08 08:24
I am confused by this too, from what I can gather it allows me to use the `ng generate` which didn't work before I put it in, it still does not fix the index issue that's why I specified that I had to duplicate a lot of files, we definitely need some doc about this and examples !

**Comment by jpduckwo** [comment] 2018-03-05 04:12
I would definitely like to do something like this in the app definition with index.
```
index: { "input": "index.other.html", "output": "./index.html" },
```
I have have a second version of an app that requires a different index.html and at the moment the output keeps the alternative index name...
I have worked around it with an npm script to rename it after building - not ideal for sure.

**Comment by ahmadhsalim** [comment] 2018-03-12 05:41
@jpduckwo This is what I want too. I'm using Angular inside a PHP Laravel application and the front page will be served from the blade template `welcome.blade.php` so I want angular-cli to copy the index file to `resources/assets/views/welcome.blade.php` but all other files should be in the default `public/dist` folder.
For now what I'm doing is to copy the contents of the `public/dist/index.html` file into the `welcome.blade.php` file. Index file usually doesn't change so it works most of the time.

**Comment by marticrespi** [comment] 2018-03-13 09:31
Any news about it? I have multiple apps and I can't move to root dist folder for each app, because it is generated with relative paths inside index.html linking styles, main bundle..

**Comment by intellix** [comment] 2018-03-13 09:42
@marticrespi since encountering this, NX CLI came out which was made for multiple apps. I've personally moved to there and would recommend others to as it has some good tooling for multiple apps

**Comment by listepo-alterpost** [comment] 2018-03-16 19:45
@intellix we also using nrwl, but `"index": "../../../libs/common/index.html",`still not working for `aot`.

**Comment by bluebaroncanada** [comment] 2019-04-15 21:19
Still a "no"; eh?

**Comment by clydin** [comment] 2019-09-19 23:48
This is now supported in Angular CLI 8.2.0 or greater.

**Closed by clydin** 2019-09-19 23:48 UTC
Labels: type: RFC / discussion / question

**Comment by bluebaroncanada** [comment] 2019-09-20 02:09
Awesome.
