### ISSUE TITLE
[@ngtools/webpack]  Error: TypeScript compilation failed

### ISSUE THREAD

**Issue by cyr-x** [angular/angular-cli#8043] opened 2017-10-13 11:12 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

The `@ngtools/webpack` loader throws an error if I'm using a package which was symlinked via `yarn link` and the `resolve` attribute inside the webpack config is containing `'.ts'` as an extension.

### Versions.

ngtools/webpack 1.8.0-rc.0

### Repro steps.

1. Clone the basic example repository which is using **webpack** + **ngtools/webpack**:
https://github.com/cyr-x/ngtools-sample

2. Run `yarn` to install deps.

3. Clone a very simple "package" repository:
https://github.com/cyr-x/package-sample

4. Symlink the `package-sample` repository via `yarn link`.

5. Run `yarn build && yarn start:prod` (=> everything works fine)

6. Uncommend the `resolve` attribute inside the `webpack.config.js` and repeat step 5. An error is thrown during the build step.

### The log given by the failure.

```
ERROR in ../package-sample/index.ts
Module build failed: Error: TypeScript compilation failed.
    at plugin.done.then (/xxxx/xxxx/xxxx/ngtools-sample/node_modules/@ngtools/webpack/src/loader.js:479:27)
    at <anonymous>
 @ ./src/app.module.ts 5:0-38
 @ ./src/app.module.ngfactory.js
 @ ./src/main.ts
```
### Desired functionality.

The build should finish without an error.

**Comment by filipesilva** [comment] 2017-10-16 12:43
This issue is essentially a duplicate of https://github.com/angular/angular-cli/issues/6228. Please see https://github.com/angular/angular-cli/issues/6228#issuecomment-301024884 for a description of why this scenario is not supported.

**Closed by filipesilva** 2017-10-16 12:43 UTC
