### ISSUE TITLE
New "Solution Style" tsconfig.json file breaks the unused files in most Editors

### ISSUE THREAD

**Issue by destus90** [angular/angular-cli#18040] opened 2020-06-26 09:50 UTC
If we have an unused service, we will run into some Typescript errors in Editors since the unused file isn't really a part of any TypeScript compilation.
**VS code**
![image](https://user-images.githubusercontent.com/17944366/85844033-8963ae00-b7bb-11ea-8be1-68b98bb26262.png)
**Webstorm**
![image](https://user-images.githubusercontent.com/17944366/85844101-a13b3200-b7bb-11ea-9702-3be43650809e.png)

Shall we revert the changes for tsconfig.file?

**Comment by kyliau** [comment] 2020-06-27 16:40
Please make sure you are using the workspace version of Typescript. 
Solution-style tsconfig is not supported by typescript < v3.9.
In vscode, you can select typescript version like so:

<img width="781" alt="Screen Shot 2020-06-27 at 9 37 48 AM" src="https://user-images.githubusercontent.com/2941178/85927314-25dc8d80-b85a-11ea-80b4-ead4886fdc2f.png">

**Comment by destus90** [comment] 2020-06-28 04:55
@kyliau 
Thanks for your suggestion. However, my TypeScript version is set as a workspace version. The real problem here has been described by @alan-agius4 https://github.com/angular/angular/issues/37781#issuecomment-650573639. I have created a repo https://github.com/destus90/angular-v10-issues. It would be nice if you could investigate it (file src/app/foo.service.ts). I found out that adding unused files into tsconfig.app.json files array solves the issue, but it would pain us to manually put all unused files into it. Any further assistance would be appreciated. 
![ng10issue](https://user-images.githubusercontent.com/17944366/85938188-4a9d3780-b924-11ea-85b0-207f47f36ef9.png)

**Comment by alan-agius4** [comment] 2020-06-28 07:44
We are aware that “unused” files safe are effected as described above.

This is because we have a strict file Inclusion policy in our tsconfig, which results in un-referenced files not being part of correct program. 

We’ll be discussing this issue during our meeting this week.

**Comment by cyrilletuzi** [comment] 2020-07-06 11:50
Hi @alan-agius4, what is the status about this issue? I just discovered it while animating an Angular training and it's a real pain. Any time you create a service, as shown in the screenshot of the initial message, there is an error telling that `experimentalDecorators` should be set to `true`.

If it was solved by just using the service somewhere, that would be confusing but quite OK. But to use it, you need to inject the service in some constructor. Before, the service would be part of the IDE suggestions so the import is done automatically, but now the service is not suggested at all so you have to do the import manually, for each service you create.

**Comment by alan-agius4** [comment] 2020-07-06 12:05
@cyrilletuzi, we are still evaluating the best course of action to fix this.

I’ll update the issue when we have more details.

**Comment by LayZeeDK** [comment] 2020-07-06 14:14
>If it was solved by just using the service somewhere
Is this a problem in libraries where the exposed services are not *used anywhere*?

**Comment by jtsom** [comment] 2020-07-06 15:35
I also ran into this problem in VSCode:

In Angular 10, they introduced "solution-style" tsconfig files: https://angular.io/guide/migration-solution-style-tsconfig

This, however, seems to break auto importing of files and classes, and the quick-fixes for adding imports:

![image](https://user-images.githubusercontent.com/13488/86610867-e6a9ed00-bf7b-11ea-9f7a-0c775f8a5b15.png)

![image](https://user-images.githubusercontent.com/13488/86609224-a5b0d900-bf79-11ea-81ca-bbce8dd4c9a9.png)

Note that it's showing "no quick fixes available" .. that should be, and it used to be (something like) "... add import of Contact ...". Or ideally, it would have automatically added the import line as soon as I typed line 13.

In the tsconfig.app.json, a standard Angular 10 app has:

```
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

Once I changed the include like to be:
```
  "include": [
    "src/**/*.d.ts",
    "src/**/*.ts"
  ]
```

The quick fix now works, as well as the auto-import of the file:

![image](https://user-images.githubusercontent.com/13488/86609865-8a929900-bf7a-11ea-80a3-ac02762823c6.png)

This is with both the workspace version and VSCode packaged version of Typescript.

This used to work in Angular < 10

**Comment by cyrilletuzi** [comment] 2020-07-06 16:10
For info: as it is really painful for students during my training, as a workaround, I reverted back to pre-Angular 9 config, ie. copy all config from `tsconfig.base.json` to `tsconfig.json` and search/replace `tsconfig.base.json` by `tsconfig.json` (mainly for `extends` in other `tsconfig.xxx.json`).

But then it breaks other features like `ng g library` (which says `no tsconfig.base.json found`).

**Comment by ahasall** [comment] 2020-07-07 07:46
@cyrilletuzi:  try adding `"extends": "tsconfig.base.json"` to the root `tsconfig.json` file. It may help with editor support and won't break building your libraries.

**Comment by crfrolik** [comment] 2020-07-07 15:50
For WebStorm support of "solution style" tsconfig, please follow https://youtrack.jetbrains.com/issue/WEB-46368

**Comment by vdurante** [comment] 2020-07-07 16:55
Same issue here. VSCode not identifying tsconfig.json for new files.

**Comment by jtsom** [comment] 2020-07-07 17:00
Unhelpful comment, but given this https://angular.io/guide/migration-solution-style-tsconfig, do the maintainers even use VS Code or Webstorm? Or do they not bother with the intellisense / auto importing? How did this get out the door with it broken in the popular editors?

**Comment by alan-agius4** [comment] 2020-07-07 19:55
@jtsom, I am sorry by the inconvenience caused by this issue.

This feature was available for testing since beta version of CLI version 10 and both issues were not raised until after the final version of the CLI version 10 was released.

In many case auto import, is not effected if you use ‘ng generate` commands to generate new components, modules, etc.. this is because new files are always referenced.

Also it’s important to point that there are 2 separate issues here, one being auto imports not working and the other is un-referenced files have diagnostics errors. The first is being tracked #18170

**Comment by guilhermetod** [comment] 2020-07-11 17:03
I found another issue that might be related to this. I started a project and switched to ESLint from TSLint. However, both through ESLint CLI and in VSCode output:

> Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
> The file does not match your project config: src/client/environments/environment.prod.ts.
> The file must be included in at least one of the projects provided

I then switched to the following and stopped the error messages:

```
 "exclude": [
    "./src/**/*.spec.ts"
  ],
  "include": [
    "./src/**/*.ts",
  ],
```

**Comment by mhamri** [comment] 2020-07-14 05:05
+1

how I fixed it, I changed `tsconfig.json` to this

```
{
  "extends": "./tsconfig.base.json",
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    },
    {
      "path": "./e2e/tsconfig.json"
    }
  ],
  "include": ["**/*.ts", "**/*.js"]
}
```

and the in `tsconfig.base.json` I added the `composite: true`


````
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": ["es2018", "dom"],
    "composite": true
  }
}
````

**Comment by jtsom** [comment] 2020-07-15 16:31
Is there any movement on this issue? Using VS Code with Angular 10 is difficult at best until this is fixed.

**Comment by jtsom** [comment] 2020-07-15 20:02
I sure hope something happens here as two related issues on the typescript repo were just closed with no resolution.

**Comment by unboxedsolutions** [comment] 2020-07-15 20:27
None of the suggestions above are working for me either.

**Comment by then3rdman** [comment] 2020-07-18 06:23
Another bump on this one, rather annoying

**Comment by jtsom** [comment] 2020-07-19 21:50
> @jtsom, I am sorry by the inconvenience caused by this issue.
> 
> This feature was available for testing since beta version of CLI version 10 and both issues were not raised until after the final version of the CLI version 10 was released.
> 

Most users don't use beta versions of software, let alone frameworks used to build software. I have been burned by beta versions of Angular in the past, so steer clear. I'm sure I'm not the only one.

> In many case auto import, is not effected if you use `ng generate` commands to generate new components, modules, etc.. this is because new files are always referenced.
> 

I think the more common use case is as I outlined above - create a class and attempt to reference it in a component. Don't see how that was not noticed in development and testing of Angular 10 with this change to the tsconfig files.

> Also it’s important to point that there are 2 separate issues here, one being auto imports not working and the other is un-referenced files have diagnostics errors. The first is being tracked #18170

Hopefully something will be fixed soon. As I said, using VSCode now (and apparently Webstorm) is annoying at the least, and difficult at most.

**Comment by then3rdman** [comment] 2020-07-19 23:52
For the record, at least in Webstorm, i have no no issues with auto import, just the annoying TsLint error 1219. Its also super inconsistent...

**Comment by alan-agius4** [comment] 2020-07-20 13:30
We do understand that this is a big inconvenience and we are sorry for that. 

We didn't forget about this issue, in fact we have been working on it since it was first reported. We do have some solutions in mind, but these are none trivial fixes especially outside of a non major release as we'd require to create a migration to update all of the TypeScript configuration files. 

We needed to do a couple of in-depth investigations to understand the impact and various solutions a bit better especially considering the magnitude of what needs to be changed to fix issues introduced with the solutions style configuration.

We also reached out to the TypeScript team and filed an issue in their tracker which you can view here: https://github.com/microsoft/TypeScript/issues/39632.

**Comment by then3rdman** [comment] 2020-07-21 00:29
Thanks very much for the transparency! Its great to know we are being supported!

**Comment by biltongza** [comment] 2020-07-21 08:30
@alan-agius4 are there any fixes you could suggest as interim fixes that improve the situation?

**Comment by alan-agius4** [comment] 2020-07-21 09:51
@biltongza, if the issue you are experiencing is the one which is being tracked here, ie: Typescript errors in IDE's such as the experimental decorators. You can try to add the below reference in your `tsconfig.json`.

```json
   {
     "path": "./tsconfig.base.json"
   }
```

**IMPORTANT:** this has to be always last element in the references array. If you will generate/opt-in libraries, app-shell, universal, web-workers or new applications projects. You will need to manually keep moving this as the very last element in the array.

**Comment by anstarovoyt** [comment] 2020-07-21 22:48
Just a note, on the WebStorm side, we've implemented https://youtrack.jetbrains.com/issue/WEB-46324 as a hotfix but it works only for the upcoming WS2020.2.

**Closed** 2020-08-12 18:26 UTC
Labels: comp: schematics/angular, freq3: high, severity5: regression, type: bug/fix

**Comment by jimmykane** [comment] 2020-08-16 15:28
Is this released? Could we expect a version tag here with the fix? That would be great

**Comment by jtsom** [comment] 2020-08-16 16:13
It looks like it won't be out until they release 10.1 ... whenever that is.

**Comment by alan-agius4** [comment] 2020-08-16 16:16
10.1 is scheduled to be released as stable latest version end of this month.

**Comment by jimmykane** [comment] 2020-08-16 18:06
Thank you!

**Comment by kumaravnish** [comment] 2020-09-09 21:32
Looks like 10.1 is released, but when I upgrade from 10.0.x to 10.1.x I get the following error:

❯ Removing "Solution Style" TypeScript configuration file support.
✖ Migration failed: Could not read 'tsconfig.json'.
  See "/private/var/folders/lm/bljksptx3zz_ymcg2qv0t66w0000gn/T/ng-tF6sg8/angular-errors.log" for further details.

Looks like the script is trying to check for the existence of tsconfig.json, but it fails because it does not exist. Has anyone else experienced this?

**Comment by destus90** [comment] 2020-09-10 03:34
@kumaravnish I guess it is something like https://github.com/angular/angular-cli/issues/18744#issuecomment-689790320. I have updated my project to Angular 10.1 and the migration went well.

**Comment by kumaravnish** [comment] 2020-09-10 23:32
@destus90, yes I have similar issue as https://github.com/angular/angular-cli/issues/18744#issuecomment-689790320, but there is no solution there. 

For you, are you upgrading from angular 10.0.x to 10.1? Did you already have tsconfig.json file?

**Comment by destus90** [comment] 2020-09-11 03:31
@kumaravnish 
Yes, I migrated from 10.0.x to 10.1 and tsconfig.json was in my project.

**Comment by mhamri** [comment] 2020-09-14 16:45
today I update to 10.1.1 and it's already fixed. after getting a diff on folders noticed the tsconfig.base.json has been removed and path in any other tsconfig.*.json is updated. this is the only major change other than the typescript 4 support

**Comment by eranshmil** [comment] 2020-09-23 08:44
> @destus90, yes I have similar issue as [#18744 (comment)](https://github.com/angular/angular-cli/issues/18744#issuecomment-689790320), but there is no solution there.
> 
> For you, are you upgrading from angular 10.0.x to 10.1? Did you already have tsconfig.json file?

I had the same issue, so I opened a PR to fix that:
https://github.com/angular/angular-cli/pull/18851
