### ISSUE TITLE
SCSS "Module not found: Error: Can't resolve" for @font-face url with relative path

### ISSUE THREAD

**Issue by JSMike** [angular/angular-cli#5213] opened 2017-03-03 21:26 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Linux (Docker hub image: mhart/alpine-node:6.9.4) on OSX host

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
```
@angular/cli: 1.0.0-rc.1
node: 6.9.4
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Importing a font with sass using relative path:

```
@font-face {
  font-family: 'Gotham-Light';
  src: url('../fonts/Gotham-Light.eot?#iefix') format('embedded-opentype'),  
    url('../fonts/Gotham-Light.otf')  format('opentype'),
    url('../fonts/Gotham-Light.woff') format('woff'), 
    url('../fonts/Gotham-Light.ttf')  format('truetype'),
    url('../fonts/Gotham-Light.svg#Gotham-Light') format('svg');
  font-weight: normal;
  font-style: normal;
  line-height: 1.5;
}
```

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module not found: Error: Can't resolve '../fonts/Gotham-Light.eot' in '/code/src'
 @ ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:108-144
 @ ./src/styles.scss
 @ multi ./~/material-design-icons/iconfont/material-icons.css
```

### Mention any other details that might be useful.

Looks like this may be related to https://github.com/angular/angular-cli/issues/4778

From my understanding relatives paths in url() was fixed for `@import`, maybe something additional needs to be done for `@font-face`

Also, this error doesn't occur when using the absolute path starting from src/, the error only appears when using the relative path. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JSMike** [comment] 2017-03-06 14:40
I've created an example repository for this issue: https://github.com/JSMike/angular-cli-issue-5213

**Comment by filipesilva** [comment] 2017-03-07 16:32
Hm I'm looking at your example repo and as far as I can tell what's happening is that the font is always being resolved relative to the initial entry point (`styles.scss`).

So if I change it `url('app/lib/fonts/Gotham-Light.otf')` it works. 

This looks like a bug somewhere really.

**Comment by filipesilva** [comment] 2017-03-07 16:50
Searched around and apparently this is just how sass loader works: https://github.com/sass/sass/issues/1015

There's a suggestion for using https://github.com/bholloway/resolve-url-loader, but it does have the serious limitation of not working without sourcemaps. This is a big problem because component css doesn't support sourcemaps at all, and your project shouldn't die just because sourcemaps aren't there.

So I think the recommended approach here is to put these font files in the assets folder, and use absolute paths (starting with `/`) for urls in sass files that are imported by other sass files.

```
@font-face {
  font-family: 'Gotham-Light';
  src: url('/assets/fonts/Gotham-Light.otf') format('opentype');
  font-weight: normal;
  font-style: normal;
  line-height: 1.5;
}
```

If anyone has a better way I'm happy to hear it.

**Comment by JSMike** [comment] 2017-03-15 16:30
My solution for now was to create `css` instead of  `scss` files for importing fonts from relative paths.

**Comment by filipesilva** [comment] 2017-03-18 16:03
I'm closing it as 'working as intended' as per sass then.

**Closed by filipesilva** 2017-03-18 16:03 UTC
Labels: command: build, flag: help wanted

**Comment by pmchugh3** [comment] 2017-05-10 15:49
It seems to me this does not "work as intended". You need to provide a way for libraries with relative scss imports to work, given that webpack projects can do this. Otherwise we have to try hack a workaround, ditch the scss library or remove angular-cli.

**Comment by jigneshkhokhani** [comment] 2017-07-14 19:07
In fresh app when I ran `npm install` or `npm install --save` and then run `ng s` then it gives me error like below. I think because of package-lock.json file is not generated for me in fresh app after running npm install.

```
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:914:18)
    at Object.getInstalledBinaries (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:571:32)
 @ ./src/styles.scss 4:14-189
 @ multi ./src/styles.scss

ERROR in ./src/app/app.component.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:914:18)
    at Object.getInstalledBinaries (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jigneshkhokhani/sites/workspace/fitness/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:571:32)
 @ ./src/app/app.component.ts 18:17-48
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

```
But after that I switch finally to yarn and it working like charm :)
`yarn install` generate yarn.lock file and it resolved my issue.

**Comment by JSMike** [comment] 2017-07-17 14:36
@jigneshkhokhani your issue is unrelated to this item. Please look for a similar issue or create a new one.

**Comment by rtm** [comment] 2017-07-26 19:45
This is still not working for me. I serve my app from a subdirectory, as in `http://myserver.com/subdir`. I have set `outDir` and `<base>` correctly and the app runs fine. However, fonts referred to by URLs in `@font-face` directories, when specified as `/assets/fonts/...` do not load, because it tries to load them from `http://myserver.com/assets/fonts` instead of `http://myserver.com/subdir/assets/fonts`. If I specify the URL as `assets/fonts` or `./assets/fonts`, then I get a build error

```
Module not found: Error: Can't resolve './assets/fonts/tf-icon-font.eot' in '/home/rtm/repos/TNF/identity-ui/src'
```

So I am stuck. Am I going to have to move these `@font-face` directives into a CSS file and load that from the `styles` property in `.angular-cli.json`? By the way, in that case, will the URL be relative to the CSS file, or to the project root?

**Comment by JSMike** [comment] 2017-07-27 02:27
If you're using the CLI then webpack will take care of the font bundling, it doesn't need to be in assets. Your CSS file should just have the relative path to the font in your local file system, you can have a separate fonts folder outside of src if you want.

**Comment by ohcibi** [comment] 2017-08-11 12:49
@JSMike I tried that with `typeface-exo-2` and I get errors about the font files not being found.

```sh
> ng new font-test
> cd font-test
> npm install --save typeface-exo-2
# edit .angular-cli.json to contain "../node_modules/typeface-exo-2/index.css" in apps[0].styles
> ng serve
** NG Live Development Server is listening on localhost:4201, open your browser on http://localhost:4201 **
Hash: 88a9faab7a188279b24f
Time: 9484ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 178 kB {4} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.js.map (styles) 28.2 kB {4} [initial] [rendered]
chunk    {2} main.bundle.js, main.bundle.js.map (main) 5.28 kB {3} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.19 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/typeface-exo-2/index.css
Module not found: Error: Can't resolve './files/exo-2-latin-100.svg' in '/Users/ohcibi/test/font-test/node_modules/typeface-exo-2'
 @ ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/typeface-exo-2/index.css 6:566-604
 @ ./~/typeface-exo-2/index.css
 @ multi ./src/styles.css ./~/typeface-exo-2/index.css
...
```

**Comment by MrPardeep** [comment] 2017-08-30 08:42
@filipesilva you are right, but thing is while deploy code on server it is again showing "no module found"

so i have tried using `/assets` to `assets` but not working any idea ?

**Comment by thovo** [comment] 2017-12-07 15:28
I met the same problem but not on local anymore, it happened at server. In scss file, if I followed the same instructions as @filipesilva it worked normally on local. But when I used the `ng build` to have the production file, it kept the same path and cause an errors font not exist. @JSMike I think I will try with yours. Is there any other solution we can do here?

**Comment by JSMike** [comment] 2017-12-07 18:10
@thovo the file with the `@fontface` should be a `css` file, not a `scss` file. see if that helps. Then in your `scss` just import the `css` file. Webpack should take care of the rest.

**Comment by justgeek** [comment] 2018-01-06 12:24
Without Modifying Webpack Config, This work:
```

$mdi-font-path: '~mdi/fonts/';
@import '~mdi/scss/materialdesignicons';
```

**Comment by Jasius** [comment] 2018-01-09 22:47
@justgeek works great, thank you.

**Comment by ShawnMercado** [comment] 2018-02-01 17:54
Maybe I'm confused, but importing as raw css does not solve the problem for anyone who wants to import an external stylesheet as a sass file so that they can `@extend` or `@include` something in it, if that stylesheet contains relative urls.

**Comment by trsh** [comment] 2018-04-05 14:35
@ShawnMercado same here.

I bought one Theme, that is used as npm module, and has lots of xxx/xxx.png paths. All those give me errors, and CLI is useless. Copying something doesn't help, as I have rename all URL paths to absolutes. If I do that I will have problems with updating my theme. This is big problem.

**Comment by EugeneSnihovsky** [comment] 2018-05-04 13:35
I spent a day of painful researches and still has this issue. I tried every workaround in this topic and also read
https://github.com/sass/sass/issues/1015
https://github.com/angular/angular-cli/issues/9185
https://github.com/angular/angular-cli/issues/3757
https://github.com/angular/angular-cli/issues/2403

On local machine (OS X 10.13.3) all works fine, but on gitlab runner (ubuntu image) command `ng build --prod` fail with error
```
  102 | @font-face {
  103 |   font-family: "SFUIText-Bold";
> 104 |   src: url("../assets/fonts/SFUI/SFUIText-Bold.otf");
      |             ^
  105 |   font-style: normal;
  106 |   font-weight: normal;
```
also try
```
src: url("/assets/fonts/SFUI/SFUIText-Bold.otf");
```
and with this version app build without error, but when I launch it I see 404 for this font.

How can I solve this?

**Comment by idrislab** [comment] 2019-04-22 15:17
@EugeneSnihovsky  Same issue here.

**Comment by shuklaniraj** [comment] 2019-05-27 07:36
same issue...

**Comment by yansenlei** [comment] 2019-08-13 07:19
same issue

**Comment by hemregeris** [comment] 2019-09-02 11:14
Hi,

Just use  **url ('/assets/** instead of **url('/assets/**

Give a blank between url and (

**Comment by semiaddict** [comment] 2019-09-16 14:59
@hemregeris, I had the same issue in a non angular related project using webpack, and this seems to work.
Could you explain why we need a space between **url** and **(** ?
Thank you.
