### ISSUE TITLE
Export utils from @schematics/angular

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12134] opened 2018-09-04 23:23 UTC
_From @alan-agius4 on March 16, 2018 17:12_

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Area
```
- [] devkit
- [x] schematics
```

### Desired functionality
At the moment none of the `@schematics/angular` utils and actual schematics are exported available if one needs to create a custom schematic using an existing util, or build on top of an existing schematic. 

1) It would be nice that at least some utils are exported such as the `ast utils`, `find-module` etc.. While I understand that these might not make sense to be in `@angular-devkit/core`, I think it will be good to export them and make them available. Either in the schematics package itself or create another package such as `@angular-devkit/utils`, `@angular-devkit/ast-utils` etc...

Another option would be to export them directly from the `@schematics/angular` package, using the `main` and `typings` field in package.json

I'll happily do a PR if you let me know is the desired way.

_Copied from original issue: angular/devkit#514_

**Comment by denisoby** [comment] 2018-10-04 14:37
Would be glad to make PR too)

**Comment by Airblader** [comment] 2019-03-13 07:53
I would really love to see this, too. Schematics are such a strong and powerful tool with which we can significantly improve developer experience for users. However, the developer experience for those writing schematics is currently about as poor as it could get: the basic infrastructure is there, but no documentation or tooling exists for it.

Some of these utilities perform basic tasks that a vast majority of projects could need, and exporting (and documenting!) them would transform a currently extremely confusing and tedious task of  adding schematics support into something that's as easy to set up as a new CLI project.

**Comment by Airblader** [comment] 2019-03-13 07:54
Also for reference, somewhat related (but different): https://github.com/angular/angular/issues/29241 and https://github.com/angular/angular/pull/28343

**Comment by alan-agius4** [comment] 2021-01-14 16:39
Duplicate of https://github.com/angular/angular-cli/issues/15335

**Closed by alan-agius4** 2021-01-14 16:39 UTC
Labels: comp: schematics/angular, type: feature
