### ISSUE TITLE
Updating to angular@12.2.1 results in "No matching version found for postcss-minify-gradients@^5.0.2"

### ISSUE THREAD

**Issue by HristoP96** [angular/angular-cli#21600] opened 2021-08-18 14:35 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes

### Description

Running ng update from angular version 11.2.14 to latest(angular@12.2.1) throws error "No matching version found for postcss-minify-gradients@^5.0.2" during npm install .

## 🔬 Minimal Reproduction
Run ng update @ angular/cli @ angular/core

## 🔥 Exception or Error

<pre>Angular CLI: 11.2.14
Node: 14.17.1
OS: win32 x64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            11.2.14 (cli-only)
@angular-devkit/schematics      11.2.14 (cli-only)
@angular/cli                    11.2.14 (cli-only)
@schematics/angular             11.2.14 (cli-only)
@schematics/update              0.1102.14 (cli-only)
rxjs                            6.6.3 (cli-only)
typescript                      <error><code>
</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

The requested `postcss-minify-gradients` dependency is a dependency of cssnano, which is a dependency of  @angular-devkit/build-angular.

The requested version is available since 4 hours from now
![image](https://user-images.githubusercontent.com/25771040/129918319-310fc160-d794-4781-b62a-50c086e40f00.png)

**Comment by alan-agius4** [comment] 2021-08-18 15:05
Closing as this is not an Angular CLI issue. 

Likely it’s caused by out of sync NPM registry pop.

**Closed by alan-agius4** 2021-08-18 15:05 UTC
