### ISSUE TITLE
Is any way to extend or generate configuration for Angular CLI?

### ISSUE THREAD

**Issue by fetis** [angular/angular-cli#12635] opened 2018-10-18 13:51 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
Angular CLI: 6.2.5
Node: 8.9.4
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.5
@angular-devkit/build-angular     0.8.5
@angular-devkit/build-optimizer   0.8.5
@angular-devkit/build-webpack     0.8.5
@angular-devkit/core              0.8.5
@angular-devkit/schematics        0.8.5
@angular/cdk                      6.4.7
@angular/cli                      6.2.5
@angular/material                 6.4.7
@ngtools/webpack                  6.2.5
@schematics/angular               0.8.5
@schematics/update                0.8.5
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.20.2
```

### Desired functionality
Let's assume I have 5 language versions. [According Angular way](https://github.com/angular/angular-cli/wiki/stories-internationalization) I have to create 5 configs for every build. It's a lot of repetition and manual work. Is any way that we can extend configuration or maybe some external tool that can generate it. Will it be possible to do this with schematics?

Yes, it's possible to workaround it somehow with individual parameters for the builder, but this eliminates usefulness `angular.json` and it would be might clear to provide only configuration parameters. The only way to specify it for serve is via config, so it's very problematic to develop

**Comment by alan-agius4** [comment] 2018-10-18 15:02
Duplicate of https://github.com/angular/angular-cli/issues/11233

**Closed by alan-agius4** 2018-10-18 15:02 UTC

**Comment by fetis** [comment] 2019-06-21 13:50
https://github.com/angular/angular-cli/issues/10612
