### ISSUE TITLE
Component generation on module: Illegal operation on a directory, read

### ISSUE THREAD

**Issue by albandaft** [angular/angular-cli#5827] opened 2017-04-04 13:33 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### Versions.
@angular/cli: 1.0.0
node: 6.10.0
os: darwin x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

MACOS Sierra

### The log given by the failure.
```
Alban-MacBook-Pro:frontend-ng alban$ ng g c -m search search/search-form
installing component
  create src/app/search/search-form/search-form.component.scss
  create src/app/search/search-form/search-form.component.html
  create src/app/search/search-form/search-form.component.spec.ts
  create src/app/search/search-form/search-form.component.ts
EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at Class.afterInstall (/Users/alban/projects/daft-touch/frontend-ng/node_modules/@angular/cli/blueprints/component/index.js:209:34)
    at tryCatch (/Users/alban/projects/daft-touch/frontend-ng/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/alban/projects/daft-touch/frontend-ng/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/alban/projects/touch/frontend-ng/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/Users/alban/projects/touch/frontend-ng/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

### Repro steps.
- Create an simple app
- Create a new module
- Add a component to the app with the command `ng g c -m new_module new_module/new_component`

Although the generation worked correctly

**Comment by filipesilva** [comment] 2017-04-10 16:28
Dupe of https://github.com/angular/angular-cli/issues/5461, fixed in https://github.com/angular/angular-cli/pull/5467, and out on the next patch release.

**Closed by filipesilva** 2017-04-10 16:28 UTC
