### ISSUE TITLE
Bundle does not include 3rd party lib after ng-build --prod

### ISSUE THREAD

**Issue by lehno** [angular/angular-cli#11409] opened 2018-06-29 11:54 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report
- [ ] feature request
```

### Versions
```
Angular CLI: 6.0.8
@angular/compiler-cli: 6.0.7
@types/jasmine: 2.8.8
@types/jasminewd2: 2.0.3
@types/node: 10.5.1

Angular: 6.0.7
Node: 8.10.0
OS: Windows 10

Package                           Version
-----------------------------------------------------------
@angular-devkit/build-angular     0.6.7
@angular/cli                      6.0.7
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
1 - Created I lib in a different workspace from the main project. 
2- Published to a private npm.
3 - Installed the lib in the same workspace with a test project, ```npm install @org/my-lib```, ng serve works and ng-build works, (it has the lib code in the bundle file)
4 - Installed the lib in my main project (that will consume the lib), its in another workspace.
5- ng serve works, ng build --prod does not include the lib code into the bundle.

### Mention any other details that might be useful
The main project was upgraded from angular 5 to 6 one month ago using angular cli.
If I install the lib using the tgz file directly ```"my-lib": "file:../../my-project/dist/my-lib"```, ng-build --prod works and the code in included in the bundle.
If I install the lib using the tgz file from cloud ```"my-lib": "https://myserver/my-lib.0.0.1.tgz"```, it does not include the lib code into the bundle file
If I install the lib using ```"@org/my-lib":"0.0.1" ```, ng build --prod does'n include the lib code into the bundle

**Comment by clydin** [comment] 2018-06-29 13:28
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by lehno** [comment] 2018-07-02 16:32
I've setup a repo, but unfortunately, it works on the repo. So maybe is some configuration created when using the angular migration command that is different from when you start a fresh project.
I compared all files from the fresh and my main project, all the same. I deleted node_modules and installed everything again, no lucky

**Comment by lehno** [comment] 2018-07-02 18:07
Probably this is related: [#6195](https://github.com/angular/angular-cli/issues/6195)

**Comment by lehno** [comment] 2018-07-02 19:32
It is something with cache, I created one repro app and a repro-lib, did a few tests and it works, it updates the code normally. Is there any cache with angular-cli or webpack? I saw in some issues here about angular-cli relying on a symlink on dist folder. I have different folder names on my main project. Im not using src and dist folders. Do you think its related?

**Comment by lehno** [comment] 2018-07-02 20:19
When I delete my node_modules folder and all dist folder, npm instal and ng build --prod again, it brings the last lib code to the vendor file

**Comment by lehno** [comment] 2018-07-05 17:46
The only way I found to make my build to include updates on my lib is to 
`delete node_modules` folder
`npm cache clean --force`
`npm install`
Then, if I build, it includes the last code

**Comment by lehno** [comment] 2018-07-10 20:02
I posted this issue on webpack repo. No solution until now...

**Comment by alexmj212** [comment] 2018-11-15 19:35
I'm also having the same issue and running a `npm cache clean --force` worked for me as well.

I had also tried making changes to my `tsconfig.json` by adding the 3rd party path directly to the config, this did not work. Errors showed that it was looking directly at the installed module in node_modules but that it still couldn't find it. https://github.com/angular/angular-cli/issues/11835 also did not include the fix for this.

Just to clarify, I have 3 sub-packages that are getting built locally and I was using an `npm link` to point to them from the main project. Each sub-package had several 3rd party dependencies (angular, rxjs, etc).

After linking the other local sub-packages, I run `ng test` in the main package. This resulted in `Module not Found` errors for almost all the 3rd party dependencies because it could not resolve the sub-package 3rd party dependencies.

**Comment by filipesilva** [comment] 2019-01-29 14:47
There was a point at which we had some cache for prod builds (specifically for Build Optimizer) that had some edge cases where it didn't work. We've since removed it. I think that might have been the cause of the problem on our side.

Not sure what the problem might be with the npm cache proper, if at all. But this repo wouldn't be the right place to address it.

In regards to `npm link` please bear in mind that there are a lot of cases where it doesn't work properly. Especially with peer dependencies, which are common in Angular projects. I don't recommend using it.

**Closed by filipesilva** 2019-01-29 14:47 UTC
Labels: comp: devkit/build-angular, need: repro steps

**Comment by lehno** [comment] 2019-02-21 14:59
Using the latest version of everything mentioned above and it does not happen anymore.
