### ISSUE TITLE
angular/cli an error occurred while creating a new project

### ISSUE THREAD

**Issue by jackywang615** [angular/angular-cli#12704] opened 2018-10-23 00:25 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

os: windows 10
node: 10.11.0
npm: 6.4.1
Angular CLI: 7.0.2
Node: 10.11.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3

### Repro steps

![snipaste_2018-10-22_09-21-37](https://user-images.githubusercontent.com/9586655/47326768-f052ca80-d69c-11e8-8670-617e68577c20.png)

**Comment by alan-agius4** [comment] 2018-10-23 04:17
Duplicate of https://github.com/angular/angular-cli/issues/12670

**Closed by alan-agius4** 2018-10-23 04:17 UTC
