### ISSUE TITLE
Feat: add support for library development

### ISSUE THREAD

**Issue by msterba** [angular/angular-cli#2669] opened 2016-10-12 16:11 UTC
It would be nice to have support for developing component libraries.

Scaffolding could be done similar as for an app, having the app as playground for the library during development. `ng build` would then create tree-shakeable es6(es5) modules and an umd bundle. Of course without the app.

**Comment by loicsalou** [comment] 2016-10-13 11:08
it's quite difficult to find a standard way how to create an Angular2 library. I've been struggling for a while to be able to do this and so far I still can't create a component library which uses all Angular2 concepts (separated files for typescript, html templates, scss style files), and it's also quite hard to include in such a library images or stuff like that. 
This would really be great for all developpers in order to increase usage of Angular !

**Comment by BernhardRode** [comment] 2016-10-13 11:59
I think a basic peace would be to have a away to generate a "valid" npm package to be used in other projects.

**Comment by vinaysoni** [comment] 2016-10-13 13:58
What is the point of having reusable components and modules, if I can't use them in multiple projects? Unless, it is possible to make a reusable library out of a module, why would someone modularize.
 cli should allow generation of projects that are not root projects. There should also be a simple way to refer to non root modules in root module. This is a a feature (to specify dependencies) commonly provided in build systems like Maven and Gradle.

**Comment by filipesilva** [comment] 2016-10-14 22:50
Dupe of https://github.com/angular/angular-cli/issues/1692

**Closed by filipesilva** 2016-10-14 22:50 UTC
