### ISSUE TITLE
Failing to start Angular's live development server  - ERR_NO_ICU

### ISSUE THREAD

**Issue by avibu** [angular/angular-cli#20808] opened 2021-05-15 17:23 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

I'm facing some difficulties while trying to start Angular's live development server :

```
ubuntuserver]#> ng serve
internal/encoding.js:429
          throw new errors.TypeError('ERR_NO_ICU', '"fatal" option');
          ^

TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU
    at new TextDecoder (internal/encoding.js:429:17)
    at Object.<anonymous> (/service/src/main/resources/static/node_modules/@angular-devkit/schematics/src/rules/template.js:27:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/service/src/main/resources/static/node_modules/@angular-devkit/schematics/src/index.js:26:10)
```

Same issue is happening while I'm using "ng update" command.

## 🔬 Minimal Reproduction

My package.json:

```
{
  "name": "angular2-seed",
  "version": "0.3.1",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --port 4202",
    "build": "ng build",
    "buildProd": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.1.12",
    "@angular/cdk": "~9.1.2",
    "@angular/common": "^9.1.12",
    "@angular/compiler": "^9.1.12",
    "@angular/core": "^9.1.12",
    "@angular/forms": "^9.1.12",
    "@angular/localize": "^9.1.12",
    "@angular/material": "~9.1.2",
    "@angular/platform-browser": "^9.1.12",
    "@angular/platform-browser-dynamic": "^9.1.12",
    "@angular/router": "^9.1.12",
    "@auth0/angular-jwt": "~4.0.0",
    "@ng-bootstrap/ng-bootstrap": "~6.1.0",
    "@ngrx/effects": "^9.1.2",
    "@ngrx/entity": "^9.2.0",
    "@ngrx/schematics": "^10.0.1",
    "@ngrx/store": "^9.1.2",
    "@ngrx/store-devtools": "^9.1.2",
    "@popperjs/core": "^2.5.4",
    "ag-grid-angular": "^24.1.0",
    "ag-grid-community": "^24.1.0",
    "angular-2-local-storage": "^3.0.2",
    "bootstrap": "~4.4.1",
    "fibers": "^3.1.1",
    "font-awesome": "^4.7.0",
    "html-webpack-plugin": "^4.5.0",
    "jquery": "^3.5.1",
    "ngx-toastr": "^12.1.0",
    "node-sass": "^4.14.1",
    "popper.js": "^1.16.1",
    "reselect": "^4.0.0",
    "rxjs": "^6.6.3",
    "rxjs-compat": "^6.6.3",
    "tslib": "^1.14.1",
    "webpack": "^4.44.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.901.12",
    "@angular/cli": "^9.1.12",
    "@angular/compiler-cli": "^9.1.12",
    "@angular/language-service": "^9.1.12",
    "@types/jasmine": "^3.5.14",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.19.4",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "mimic": "^2.0.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "^5.20.1",
    "typescript": "~3.8.3"
  }
}
```

-->

## 🔥 Exception or Error

`TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU`

**Comment by alan-agius4** [comment] 2021-05-15 17:26
Can you please provide the output of `ng v`? Thanks

**Comment by avibu** [comment] 2021-05-15 17:29
> Can you please provide the output of `ng v`? Thanks

Same output for "ng v":

ubuntuserver]#>ng v
internal/encoding.js:429
          throw new errors.TypeError('ERR_NO_ICU', '"fatal" option');
          ^

TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU
    at new TextDecoder (internal/encoding.js:429:17)
    at Object.<anonymous> (/service/src/main/resources/static/node_modules/@angular-devkit/schematics/src/rules/template.js:27:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/service/src/main/resources/static/node_modules/@angular-devkit/schematics/src/index.js:26:10)

**Comment by alan-agius4** [comment] 2021-05-15 17:54
Might be helpful: https://stackoverflow.com/questions/64389736/typeerror-err-no-icu-when-using-the-angular-cli

**Comment by avibu** [comment] 2021-05-16 07:10
> Might be helpful: https://stackoverflow.com/questions/64389736/typeerror-err-no-icu-when-using-the-angular-cli

Didn't help unfortunately, please let me know if more information is needed.
Seems like all 'ng' commands producing the same output.

**Comment by alan-agius4** [comment] 2021-05-16 07:17
The error indicates that the Node.JS version you have installation compile without ICU supported.

Please try to re-install Node.js 10 or 12. A good way to install Node.js is via NVM, https://github.com/nvm-sh/nvm

**Comment by alan-agius4** [comment] 2021-05-16 07:17
Closing as this is not caused by Angular CLI.

**Closed by alan-agius4** 2021-05-16 07:17 UTC
Labels: need: more info
