### ISSUE TITLE
Really slow experience

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular-cli#2656] opened 2016-10-11 21:28 UTC
Is it normal that it takes about 16 seconds from saving a file to a browser refresh?
My cmd is running elevated and my vs code is not as vs code has some strange bugs when running elevated.

> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.17
node: 5.12.0
os: win32 x64

### Repro steps.
> Created with CLI, TS, SCSS or HTML file edited.

### Mention any other details that might be useful.
1052ms building modules
9ms sealing
3ms optimizing
1ms basic module optimization
323ms module optimization
2ms advanced module optimization
21ms basic chunk optimization
1ms chunk optimization
2ms advanced chunk optimization
20ms module and chunk tree optimization
170ms module reviving
2ms module order optimization
9ms module id optimization
9ms chunk reviving
5ms chunk order optimization
24ms chunk id optimization
130ms hashing
3ms module assets processing
172ms chunk assets processing
9ms additional chunk assets processing
2ms recording
2ms additional asset processing
4555ms chunk asset optimization
1581ms asset optimization
92ms emitting
Hash: b71ae8a4b329cf25339e
Version: webpack 2.1.0-beta.25
Time: 16361ms
                                 Asset     Size  Chunks             Chunk Names
 7500519de3d82e33d1587f8042e2afcb.woff  61.6 kB
  ecdd509cadbf1ea78b8d2e31ec52328c.eot    21 kB
  4d9f3f9e5195e7b074bb63ba4ce42208.eot  21.4 kB
  30799efa5bf74129468ad4e257551dc3.eot  21.3 kB
  dfe56a876d0282555d1e2458e278060f.eot  21.7 kB
  e31fcf1885e371e19f5786c2bdfeae1b.ttf   128 kB
 dc81817def276b4f21395f7ea5e88dcd.woff  62.9 kB
  46e48ce0628835f68a7369d0254e4283.ttf   127 kB
 3b813c2ae0d04909a33a18d792912ee7.woff  62.3 kB
  894a2ede85a483bf9bedefd4db45cdb9.ttf   127 kB
 fc78759e93a6cac50458610e3d9d63a0.woff    63 kB
  df7b648ce5356ea1ebce435b3459fd60.ttf   126 kB
 ba3dcd8903e3d0af5de7792777f8ae0d.woff  61.7 kB
  94998475f6aea65f558494802416c1cf.ttf   128 kB
  a990f611f2305dc12965f186c2ef2690.eot  20.9 kB
39b2c3031be6b4ea96e2e3e95d307814.woff2    50 kB
69f8a0617ac472f78e45841323a3df9e.woff2  49.4 kB
574fd0b50367f886d359e8264938fc37.woff2  50.2 kB
2751ee43015f9884c3642f103b7f70c9.woff2  49.2 kB
954bbdeb86483e4ffea00c4591530ece.woff2  48.5 kB
                        main.bundle.js  4.23 MB    0, 3  [emitted]  main
                      styles.bundle.js   177 kB    1, 3             styles
                     scripts.bundle.js   724 kB    2, 3             scripts
                             inline.js  5.53 kB       3             inline
                            styles.map   233 kB    1, 3             styles
                           scripts.map   874 kB    2, 3             scripts
                            inline.map  5.59 kB       3             inline
                              main.map   4.5 MB    0, 3  [emitted]  main
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  2.9 kB       0

**Comment by Naph** [comment] 2016-10-12 00:38
Normal for now. Separating the vendors (chunks) from the webpack watcher sync should ease the time. But there isn't anything written in the docs to do so.

**Comment by mbeckenbach** [comment] 2016-10-12 19:35
That sound like a good idea. Usually the vendor files dont change while developing.

**Comment by leon** [comment] 2016-10-13 13:30
Alot of time is spent creating source maps.
In the master branch there is a commit changing to use cheap-module-source-map instead of source-map which when I changed it locally dropped a few seconds of my devloop.

https://github.com/angular/angular-cli/pull/2619

Hopefully there will be a new beta out soon which incorporates this :)

**Comment by guiomie** [comment] 2016-10-13 15:54
Similar discussion going on here: #1980

**Comment by filipesilva** [comment] 2016-10-14 18:05
Dupe of #1980

**Closed by filipesilva** 2016-10-14 18:05 UTC
