### ISSUE TITLE
Migration Failed from v12.2.14 to v13.0.0

### ISSUE THREAD

**Issue by AmanSonii** [angular/angular-cli#24839] opened 2023-03-10 15:37 UTC
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

While trying to update the current angular version to 13, I am having the error **× Migration failed: Cannot convert undefined or null to object**

[error] TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at _buildPackageInfo (\AppData\Local\Temp\angular-cli-packages-GQiRwr\node_modules\@angular\cli\src\commands\update\schematic\index.js:435:52)
    at AppData\Local\Temp\angular-cli-packages-GQiRwr\node_modules\@angular\cli\src\commands\update\schematic\index.js:710:53
    at Map.forEach (<anonymous>)
    at \AppData\Local\Temp\angular-cli-packages-GQiRwr\node_modules\@angular\cli\src\commands\update\schematic\index.js:709:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async callRuleAsync (\AppData\Local\Temp\angular-cli-packages-GQiRwr\node_modules\@angular-devkit\schematics\src\rules\call.js:78:18)

### Minimal Reproduction

Run the following command from the root directory of the project.

**ng update**

### Your Environment

```text
Angular CLI: 13.0.0
Node: 18.12.0 (Unsupported)
Package Manager: npm 8.19.2
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.0
@angular-devkit/core         13.0.0
@angular-devkit/schematics   13.0.0
@angular/cli                 13.0.0
@schematics/angular          13.0.0
```

**Comment by alan-agius4** [comment] 2023-03-10 16:24
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2023-03-16 14:36
Closing due to the lack of a reproduction.

**Closed by alan-agius4** 2023-03-16 14:36 UTC
Labels: needs: repro steps
