### ISSUE TITLE
Build to exclude files from tree-shaking (prefer using regex expression)

### ISSUE THREAD

**Issue by n614cd** [angular/angular-cli#23061] opened 2022-04-30 10:54 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [x ] build

### Description

Short version: Skip the tree-shaking for select file(s) based on a regex expression.

Longer version: I have an application which uses a GraphQL based api. With a significant portion of the application dynamic and based upon data provided by the server. With GraphQL I believe this development pattern will become more common. 
The fundamental issue is the Angular CLI is too aggressive on tree-shaking the types from the generated GrapphQL schema. As a result, in a "production" build the application has errors in HTML templates processing directives (usually ngFor in my case).

I believe this is similar to a previous request, however I believe with growing popularity of GraphQL the issue will gain more significance and should be queued for a future release. https://github.com/angular/angular-cli/issues/20828

### Describe the solution you'd like

An ability to add a reg expression to specifically exclude file(s) from tree-shaking.

### Describe alternatives you've considered

1. Disable optimization
2. Create a dummy component which contains references to all items in the schema file, is included in the app component but is never displayed using an ngIf.

**Comment by alan-agius4** [comment] 2022-05-02 09:07
Hi @n614cd,

In order to understand the problem better, can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment] 2022-05-24 10:59
Closing since no reproduction was provided. Please feel free to open a new issue when you put together a minimal reproduction.

**Closed by alan-agius4** 2022-05-24 10:59 UTC
Labels: need: repro steps
