### ISSUE TITLE
Building angular2 libs with angular-cli

### ISSUE THREAD

**Issue by NCC1701M** [angular/angular-cli#5333] opened 2017-03-09 13:52 UTC
### Versions.
> node: 6.10.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

It should be possible to build libraries with angular-cli which you can use in other angular2 projects.

**Comment by Brocco** [comment] 2017-03-09 14:04
Duplicate of #1692

**Closed by Brocco** 2017-03-09 14:04 UTC
