### ISSUE TITLE
npm i -g angular-cli fails on windows 10 - on broccoli@1.0.beta.6 postinstall

### ISSUE THREAD

**Issue by HansS** [angular/angular-cli#389] opened 2016-04-02 09:33 UTC
Hans@HP-HANS C:\Users\Hans
$ npm i -g angular-cli
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
C:\Users\Hans\AppData\Roaming\npm\ng -> C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\bin\ng

> broccoli@1.0.0-beta.6 postinstall C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\node_modules\broccoli
> multidep test/multidep.json

broccoli-plugin 1.0.0: Installing
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\assetgraph-builder\node_modules\node-pre-gyp requires rc@'~1.1.0' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\assetgraph-builder\node_modules\rc, npm WARN unmet dependency which is version 0.5.5
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires glob@'~5.0.15' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\glob,
npm WARN unmet dependency which is version 4.0.6
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires node-gyp@'~3.0.3' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\node-gyp,
npm WARN unmet dependency which is version 3.1.0
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires osenv@'~0.1.3' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\osenv,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires request@'~2.65.0' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\request,
npm WARN unmet dependency which is version 2.47.0
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires semver@'~5.0.3' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\semver,
npm WARN unmet dependency which is version 4.3.6
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires tar@'~2.2.1' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\tar,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\phonegap\node_modules\localtunnel\node_modules\request requires form-data@'~0.0.3' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\phonegap\node_modules\form-data,
npm WARN unmet dependency which is version 0.1.4
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\phonegap\node_modules\phonegap-build-api\node_modules\request requires form-data@'~0.0.3' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\phonegap\node_modules\form-data,
npm WARN unmet dependency which is version 0.1.4
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hans\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\npm\\bin\\npm-cli.js" "install" "broccoli-plugin@1.0.0"
npm ERR! node v5.3.0
npm ERR! npm  v2.14.21
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package yo@1.6.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-element@1.1.0 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-fluxible@1.2.4 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-g@0.0.1 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-greenfield@1.6.1 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-ionic@0.8.0 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-jsmodule@0.2.0 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-module@0.0.2 wants yo@>=1.0.0-rc.1
npm ERR! peerinvalid Peer generator-n@0.0.6 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-node-mocha@0.1.0 wants yo@~1.1.2
npm ERR! peerinvalid Peer generator-refactoru-html@0.5.0 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-skeletor@0.6.0 wants yo@>=1.0.4

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\node_modules\broccoli\test\multidep\broccoli-plugin-1.0.0\npm-debug.log
Error: npm exited with exit code 1, signal null
    at ChildProcess.<anonymous> (C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\node_modules\multidep\index.js:90:28)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
C:\Users\Hans\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hans\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "angular-cli"
npm ERR! node v5.3.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE

npm ERR! broccoli@1.0.0-beta.6 postinstall: `multidep test/multidep.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the broccoli@1.0.0-beta.6 postinstall script 'multidep test/multidep.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the broccoli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     multidep test/multidep.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs broccoli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls broccoli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Hans\npm-debug.log
npm ERR! code 1

Hans@HP-HANS C:\Users\Hans
$ ng -version
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\bin\ng'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

Hans@HP-HANS C:\Users\Hans
$ npm -v
3.7.1

Hans@HP-HANS C:\Users\Hans
$ node -v
v5.3.0

**Comment by anode7** [comment] 2016-04-02 10:06
Try to run update npm `npm install -g npm` and `npm cache clean` to be sure to run the latest version (3.8.5 for me)

**Comment by HansS** [comment] 2016-04-02 12:23
Hi Gregory,
i did the install again and stopped the installation when "broccoli@1.0.beta.6 postinstall "by closing the terminal window.
As far as i can see "ng new todo" is working!
kind regardsHans

Date: Sat, 2 Apr 2016 03:06:10 -0700

**Comment by HansS** [comment] 2016-04-02 12:39
Hi Gregory,
this is the installation procedure after reinstall of angular-cli (see previous email)
Hans@HP-HANS C:\Users\Hans\Web\js\angular-cli\test> ng new todoinstalling ng2  create .clang-format  create angular-cli.json  create config\environment.js  create e2e\app.e2e.ts  create e2e\app.po.ts  create e2e\tsconfig.json  create e2e\typings.d.ts  create angular-cli-build.js  create .gitignore  create karma-test-shim.js  create karma.conf.js  create package.json  create protractor.conf.js  create public\.npmignore  create src\app\todo.html  create src\app\todo.spec.ts  create src\app\todo.ts  create src\app\route-config.ts  create src\app.ts  create src\favicon.ico  create src\index.html  create src\tsconfig.json  create src\typings.d.ts  create tslint.json  create typings.jsonSuccessfully initialized git.Installing packages for tooling via npmbroccoli-plugin 1.0.0: InstallingInstalling packages for tooling via npm...loadRequestedDeps         | |################----------------------
Installing packages for tooling via npmloadDep:underscore.string - |####################---------------------Installing packages for tooling via npmloadDep:glob -> afterAdd  \ |#######################------------------C:\Users\Hans\Web\js\angular-cli\test\todo\node_modules\angular-cli\node_modules\broccoli\test\multidep\broccoli-plugin-1.0.0ges for tooling via npm└─┬ broccoli-plugin@1.0.0  ├─┬ promise-map-series@0.2.2  │ └── rsvp@3.2.1  ├─┬ quick-temp@0.1.5mktemp@0.3.5Installing packages for tooling via npm  │ ├── rimraf@2.2.8  │ └── underscore.string@2.3.3  ├─┬ rimraf@2.5.2  │ └─┬ glob@7.0.3  │   ├─┬ inflight@1.0.4  │   │ └── wrappy@1.0.1  │   ├── inherits@2.0.1  │   ├─┬ minimatch@3.0.0  │   │ └─┬ brace-expansion@1.1.3  │   │   ├── balanced-match@0.3.0  │   │   └── concat-map@0.0.1  │   ├── once@1.3.3  │   └── path-is-absolute@1.0.0  └─┬ symlink-or-copy@1.0.1    └── copy-dereference@1.0.0
broccoli-plugin 1.1.0: InstallingC:\Users\Hans\Web\js\angular-cli\test\todo\node_modules\angular-cli\node_modules\broccoli\test\multidep\broccoli-plugin-1.1.0ges for tooling via npm..└─┬ broccoli-plugin@1.1.0  ├─┬ promise-map-series@0.2.2  │ └── rsvp@3.2.1  ├─┬ quick-temp@0.1.5  │ ├── mktemp@0.3.5  │ ├── rimraf@2.2.8  │ └── underscore.string@2.3.3  ├─┬ rimraf@2.5.2  │ └─┬ glob@7.0.3  │   ├─┬ inflight@1.0.4  │   │ └── wrappy@1.0.1  │   ├── inherits@2.0.1  │   ├─┬ minimatch@3.0.0  │   │ └─┬ brace-expansion@1.1.3  │   │   ├── balanced-match@0.3.0  │   │   └── concat-map@0.0.1  │   ├── once@1.3.3  │   └── path-is-absolute@1.0.0  └─┬ symlink-or-copy@1.0.1    └── copy-dereference@1.0.0
broccoli-plugin 1.2.0: InstallingC:\Users\Hans\Web\js\angular-cli\test\todo\node_modules\angular-cli\node_modules\broccoli\test\multidep\broccoli-plugin-1.2.0ges for tooling via npm..└─┬ broccoli-plugin@1.2.0  ├─┬ promise-map-series@0.2.2  │ └── rsvp@3.2.1  ├─┬ quick-temp@0.1.5  │ ├── mktemp@0.3.5  │ ├── rimraf@2.2.8  │ └── underscore.string@2.3.3  ├─┬ rimraf@2.5.2  │ └─┬ glob@7.0.3  │   ├─┬ inflight@1.0.4  │   │ └── wrappy@1.0.1  │   ├── inherits@2.0.1  │   ├─┬ minimatch@3.0.0  │   │ └─┬ brace-expansion@1.1.3  │   │   ├── balanced-match@0.3.0  │   │   └── concat-map@0.0.1  │   ├── once@1.3.3  │   └── path-is-absolute@1.0.0  └─┬ symlink-or-copy@1.0.1    └── copy-dereference@1.0.0
broccoli-source 1.1.0: InstallingC:\Users\Hans\Web\js\angular-cli\test\todo\node_modules\angular-cli\node_modules\broccoli\test\multidep\broccoli-source-1.1.0ges for tooling via npm...└── broccoli-source@1.1.0

├── es6-shim (ambient)├── angular-protractor (ambient dev)├── jasmine (ambient dev)└── selenium-webdriver (ambient dev)
Installed packages for tooling via npm.
Hans@HP-HANS C:\Users\Hans\Web\js\angular-cli\test



regardsHans





---------------------------------------------------------------------------------------------




From: hans.schenker@windowslive.com
To: reply@reply.github.com
Subject: RE: [angular/angular-cli] npm i -g angular-cli fails on windows 10 - on broccoli@1.0.beta.6 postinstall (#389)
Date: Sat, 2 Apr 2016 14:23:47 +0200




Hi Gregory,
i did the install again and stopped the installation when "broccoli@1.0.beta.6 postinstall "by closing the terminal window.
As far as i can see "ng new todo" is working!
kind regardsHans

Date: Sat, 2 Apr 2016 03:06:10 -0700

**Comment by anode7** [comment] 2016-04-02 12:58
@HansS The current stable version of node is v5.10.0, Trying to do a new **clean** install of nodejs and npm.
I am convinced that the problem is a npm conflict.

Regards

**Comment by HansS** [comment] 2016-04-02 14:00
I did the node install 5.10.0 (see results below)
Hans@HP-HANS C:\Users\Hans> node -vv5.10.0
Hans@HP-HANS C:\Users\Hans> npm -v3.7.1
Hans@HP-HANS C:\Users\Hans> npm i -g angular-clinpm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.C:\Users\Hans\AppData\Roaming\npm\ng -> C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\bin\ngC:\Users\Hans\AppData\Roaming\npm`-- angular-cli@0.0.29

kind regardsHans







Date: Sat, 2 Apr 2016 05:58:16 -0700

**Comment by anode7** [comment] 2016-04-02 14:48
So it works now ? great

**Comment by HansS** [comment] 2016-04-02 15:04
thank's a lot and have a nice weekend!

Date: Sat, 2 Apr 2016 07:48:22 -0700

**Comment by hansl** [comment] 2016-04-05 22:25
Closing this as Non-reproducible.

**Closed by hansl** 2016-04-05 22:25 UTC

**Comment by vapits** [comment] 2016-04-13 13:40
Have the same issue hre.
I can't install it, getting:

```bash
> broccoli@1.0.0-beta.6 postinstall /usr/local/lib/node_modules/angular-cli/node_modules/broccoli
> multidep test/multidep.json

broccoli-plugin 1.0.0: Installing
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/angular-cli/node_modules/.bin/npm" "install" "broccoli-plugin@1.0.0"
npm ERR! node v5.10.1
npm ERR! npm  v2.14.21
npm ERR! path /Users/vassilis/.npm/broccoli-plugin/1.0.0
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/Users/vassilis/.npm/broccoli-plugin/1.0.0'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/Users/vassilis/.npm/broccoli-plugin/1.0.0']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/vassilis/.npm/broccoli-plugin/1.0.0' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/angular-cli/node_modules/broccoli/test/multidep/broccoli-plugin-1.0.0/npm-debug.log
Error: npm exited with exit code 243, signal null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/multidep/index.js:90:28)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE

npm ERR! broccoli@1.0.0-beta.6 postinstall: `multidep test/multidep.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the broccoli@1.0.0-beta.6 postinstall script 'multidep test/multidep.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the broccoli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     multidep test/multidep.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs broccoli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls broccoli
npm ERR! There is likely additional logging output above.
```

**Comment by anode7** [comment] 2016-04-13 16:01
@vapits The solution is [here](https://github.com/angular/angular-cli/issues/345#issuecomment-201276673)

**Comment by vapits** [comment] 2016-04-14 07:25
The @anode7 you fix worked for me also!

Take care!

**Comment by reinos** [comment] 2016-04-22 12:47
same problem here, but the solution with the permissions doesn`t solve the problem

```
ReinosMac:~ reinos$ sudo npm install -g angular-cli
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/Users/reinos/.npm/bin/ng -> /Users/reinos/.npm/lib/node_modules/angular-cli/bin/ng

> broccoli@1.0.0-beta.6 postinstall /Users/reinos/.npm/lib/node_modules/angular-cli/node_modules/broccoli
> multidep test/multidep.json

broccoli-plugin 1.0.0: Installing
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/Users/reinos/.npm/lib/node_modules/angular-cli/node_modules/.bin/npm" "install" "broccoli-plugin@1.0.0"
npm ERR! node v5.11.0
npm ERR! npm  v2.14.21
npm ERR! path /Users/reinos/.npm/broccoli-plugin/1.0.0
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/Users/reinos/.npm/broccoli-plugin/1.0.0'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/Users/reinos/.npm/broccoli-plugin/1.0.0']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/reinos/.npm/broccoli-plugin/1.0.0' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/reinos/.npm/lib/node_modules/angular-cli/node_modules/broccoli/test/multidep/broccoli-plugin-1.0.0/npm-debug.log
Error: npm exited with exit code 243, signal null
    at ChildProcess.<anonymous> (/Users/reinos/.npm/lib/node_modules/angular-cli/node_modules/multidep/index.js:90:28)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
/Users/reinos/.npm/lib
└── (empty)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! broccoli@1.0.0-beta.6 postinstall: `multidep test/multidep.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the broccoli@1.0.0-beta.6 postinstall script 'multidep test/multidep.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the broccoli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     multidep test/multidep.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs broccoli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls broccoli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/reinos/npm-debug.log
npm ERR! code 1
```

**Comment by filipesilva** [comment] 2016-04-22 13:00
@reinos that still looks like the permissions issue. You probably fixed it initially, but since you now did `sudo npm install -g angular-cli` you get the problem again. 

You must not use sudo when installing npm packages, otherwise there will be `EACCES` errors.

More specifically, what happened is this: 
- you fixed permissions
- you ran `sudo npm install -g angular-cli`
- this sets admin permissions on some node module folders
- as part of the install, `multi-dep` installs more deps
- multidep installs are not made as sudo
- multidep gets `EACCES` errors due to permissions
- install fails

**Comment by reinos** [comment] 2016-04-22 13:33
@filipesilva thanks, that fixed the permission issue! I think i got used to the sudo command ;-)

**Comment by filipesilva** [comment] 2016-04-22 13:34
Glad to hear it helped :D

**Comment by williamhunter9094** [comment] 2017-03-24 20:48
I am using a fresh install of angular cli and on windows 10 it is not working. 

It is very tantalising as I am general public and would like to imagine I can enter a platform such as Angular, and the offer of Angular CLI to provide quick deployment and production alternatives is a big draw.  Then to discover, after falling into a rabbit hole of trial and error, that ng server/build etc all don't work on a fresh install; this is a bit of a con.  

Angular appears to need to come with a health warning to those who prefer not to get sucked into a developer's bug-fix 'collaborative project' vortex.
