### ISSUE TITLE
Port 4200 is already in use

### ISSUE THREAD

**Issue by malikasinger1** [angular/angular-cli#4201] opened 2017-01-24 13:21 UTC
**it should automatic shift on other port if a port is busy,**
**currently when i try to serve two projects at a time i always get error:**

``` Port 4200 is already in use ```

Thank You,
M.Inzamam Malik

**Comment by MTechDE** [comment] 2017-01-24 13:26
You can set your port with --port 1234

**Comment by malikasinger1** [comment] 2017-01-24 13:29
@MTechDE  i know but why not automatically, just like ionic-cli does
kindly let me know if there is any good reason behind this

**Comment by MTechDE** [comment] 2017-01-24 13:49
They have to implement something like this: https://www.npmjs.com/package/ember-cli-auto-port
Angular-CLI is based on the Ember CLI

**Comment by clydin** [comment] 2017-01-24 13:51
I would view the current deterministic behavior as an important trait of a development tool.  Scripted and test-related scenarios, for example, rely on a particular setup.  And if something is running on a port that is expected to be free, something is wrong.

**Comment by filipesilva** [comment] 2017-01-24 17:57
Dupe of https://github.com/angular/angular-cli/issues/4201

**Closed by filipesilva** 2017-01-24 17:57 UTC

**Comment by ashfaq22iit** [comment] 2017-07-31 18:47
lsof -t -i tcp:80 -s tcp:listen | sudo xargs kill

**Comment by mcakar1993** [comment] 2017-08-02 06:56
ng serve --port 4201

default port 4200 so already another project work in same port. So change it as 4201 or any other

**Comment by melhaer** [comment] 2017-10-06 13:02
For Windows: 

Open Command   Prompt and type:  **_netstat -a -o -n_** 
Find the PID of the process that you want to kill.
Type: **_taskkill /F   /PID 16876_** 
This one **16876** - is the PID for the process that I want to kill - in that case, the process is 4200 - check the attached file.

![capture](https://user-images.githubusercontent.com/16577124/31278899-94e2a77a-aaaf-11e7-8667-340639e49920.PNG)

**Comment by kaustubhtalathi** [comment] 2017-10-21 02:08
For Windows it would be:
**## taskkill -F -PID 16876**

**Comment by harmeshg5** [comment] 2018-01-04 06:57
You can also try with this to run your application in visual studio code -:

`ng serve --open --port 4201`

you can give any port number.

**Comment by melhaer** [comment] 2018-01-04 08:59
![capture](https://user-images.githubusercontent.com/16577124/34556239-402b1430-f13e-11e7-840a-c82b2f8161fb.PNG)

For Windows you can also kill the process (Node.js) through the Task Manager - this is the easiest way to do it:)

**Comment by enesyurtlu** [comment] 2018-03-16 20:09
`lsof -t -i tcp:80 -s tcp:listen | sudo xargs kill` this works !
But I want it in angular-cli. If specified port is in use, cli can automatically stop that.

**Comment by daliri72** [comment] 2018-04-22 10:33
`Port 4200 is already in use. Use '--port' to specify a different port`
This means that you already have another service running on port 4200. If this is the case
you can either . shut down the other service or. use the `--port` flag when running ng
serve like this:
`ng serve --port 9001`

**Comment by goneos** [comment] 2018-05-01 23:15
I'm a few weeks in with Angular and Visual Studio Code and it was working quite well, but now when I terminate the batch job it goes back to the cli, but then when I try to restart my app it gives the port error.  I then have to track it down using netstat and kill it directly.  

I know I can specify a new port, buy can anyone give me an idea of why my app is not releasing the port?

**Comment by agiletuan** [comment] 2018-05-07 03:26
[https://stackoverflow.com/a/48476963/5812106](url)
I usually use the ng set command to change the Angular CLI settings for project level.

ng set defaults.serve.port=4201
It changes change your .angular.cli.json and adds the port settings as it mentioned earlier.

After this change you can use simply ng serve and it going to use the prefered port without the need of specifying it every time.

**Comment by ahmedohadi** [comment] 2018-11-26 05:01
why should i keep 4200 listening and resort to another port?! it is a good practice not to have anything unnecessarily works on your machine, so kill it!

**Comment by Qasmi2** [comment] 2019-03-01 07:34
Ubuntu ( terminal command ) 
**kill -9 $(lsof -i tcp:4200 -t)**

**Comment by Dx** [comment] 2019-03-06 04:42
the command @Qasmi2 suggested, works on Mac OSX too 👍 

kill -9 $(lsof -i tcp:4200 -t)

**Comment by konidala** [comment] 2019-03-14 14:29
> For Windows:
> 
> Open Command Prompt and type: **_netstat -a -o -n_**
> Find the PID of the process that you want to kill.
> Type: **_taskkill /F /PID 16876_**
> This one **16876** - is the PID for the process that I want to kill - in that case, the process is 4200 - check the attached file.
> 
> ![capture](https://user-images.githubusercontent.com/16577124/31278899-94e2a77a-aaaf-11e7-8667-340639e49920.PNG)



> For Windows:
> 
> Open Command Prompt and type: **_netstat -a -o -n_**
> Find the PID of the process that you want to kill.
> Type: **_taskkill /F /PID 16876_**
> This one **16876** - is the PID for the process that I want to kill - in that case, the process is 4200 - check the attached file.
> 
> ![capture](https://user-images.githubusercontent.com/16577124/31278899-94e2a77a-aaaf-11e7-8667-340639e49920.PNG)

netstat -ano | findstr 4200
taskkill /F /PID <pid>

**Comment by alypakistan** [comment] 2019-06-08 20:48
> Just enter this below command line in your new app for simultaneously run two app at a time. 

`ng serve --port 4401`


**@ALYPAKISTAN**

**Comment by lokisanhitleson** [comment] 2019-08-18 12:59
I also faced this problem suddenly and solved it by deleting `node_modules` folder and `package-lock.json` and again doing `npm install`.

**Comment by hadideveloper** [comment] 2019-08-20 07:13
> I also faced this problem suddenly and solved it by deleting `node_modules` folder and `package-lock.json` and again doing `npm install`.
> 
> something changed in `package-lock.json` caused this problem to me

Yes, Finally it works. I wasted two days on it.

**Comment by bboyzplatform** [comment] 2019-08-20 10:39
I solved this problem with yarn. 
1. Delete package-lock.json & node_modules folder
2. Install yarn package manager
3. yarn install. 
4. ng serve - runs goooood.
