### ISSUE TITLE
Add option to disable es5 bundle generation in build on CI

### ISSUE THREAD

**Issue by neilhem** [angular/angular-cli#15759] opened 2019-10-04 07:47 UTC
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...
Add option to fully disable es5 generation in such scenarios like CI environment passing some option `ng build --disable-es5-bundle=true`

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

ref https://github.com/angular/angular-cli/issues/14679

**Comment by alan-agius4** [comment] 2021-01-11 11:04
Duplicate of https://github.com/angular/angular-cli/issues/14602

**Closed by alan-agius4** 2021-01-11 11:04 UTC
Labels: comp: devkit/build-angular, type: feature
