### ISSUE TITLE
"TypeError: path must be a string or Buffer" with installation.

### ISSUE THREAD

**Issue by minhoryang** [angular/angular-cli#2459] opened 2016-10-01 07:15 UTC
### OS?
> **Ubuntu 14.04.2 LTS**
```
$ uname -a
Linux spy 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### Versions.
> 
**angular-cli@1.0.0-beta.16**
```
$ node --version
v6.7.0
$ npm --version
3.10.8
$ pnpm --version
0.37.0
```

### Repro steps.
```
$ ndenv local v6.7.0
$ npm install -g pnpm
$ ndenv rehash
$ pnpm install angular-cli
$ ng --version
```

### The log given by the failure.
> 
```
$ ng --version
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Function.Version.fromProject (/home/minhoryang/NODE_PLAYGROUND/node_modules/angular-cli/upgrade/version.js:87:31)
    at Function.Version.isPreWebpack (/home/minhoryang/NODE_PLAYGROUND/node_modules/angular-cli/upgrade/version.js:111:31)
    at Function.Version.assertPostWebpackVersion (/home/minhoryang/NODE_PLAYGROUND/node_modules/angular-cli/upgrade/version.js:97:18)
    at /home/minhoryang/NODE_PLAYGROUND/node_modules/angular-cli/bin/ng:25:15
    at /home/minhoryang/NODE_PLAYGROUND/node_modules/angular-cli/node_modules/resolve/lib/async.js:44:21
    at ondir (/home/minhoryang/NODE_PLAYGROUND/node_modules/angular-cli/node_modules/resolve/lib/async.js:187:31)
    at /home/minhoryang/NODE_PLAYGROUND/node_modules/angular-cli/node_modules/resolve/lib/async.js:153:39
```

### Mention any other details that might be useful.
> When I searched this TypeError, I got these: #2324 #1941 #2135

**Comment by minhoryang** [comment] 2016-10-01 07:26
[configPath === null (@ packages/angular-cli/upgrade/version.ts#L78)](https://github.com/angular/angular-cli/blob/v1.0.0-beta.16/packages/angular-cli/upgrade/version.ts#L78)

**Comment by minhoryang** [comment] 2016-10-01 07:38
```
$ npm install angular-cli
```
also happened without `pnpm`

**Comment by minhoryang** [comment] 2016-10-01 08:32
```
$ npm install -g angular-cli
```
works... :(

**Comment by minhoryang** [comment] 2016-10-01 08:33
why?

**Comment by minhoryang** [comment] 2016-10-01 08:39
With global installed angular-cli won't call `Version.fromProject` which was raising TypeError.

**Comment by minhoryang** [comment] 2016-10-01 08:48
Oh! He already [knew this](https://github.com/angular/angular-cli/issues/1941#issuecomment-247946387)

**Comment by sonnenfeld269** [comment] 2016-10-02 01:08
@minhoryang did u find a solution?

**Comment by minhoryang** [comment] 2016-10-03 08:51
@sonnenfeld269 you can bypass this with globally installation (-g), but I can't find the root causes.

**Comment by vadost** [comment] 2016-10-03 12:03
I have the same problem with globally installation(

**Comment by vadost** [comment] 2016-10-05 07:31
I solved the problem this way:
Simplest workaround to continue working in your project is comment line 25 of node_modules/angular-cli/bin/ng : 
// Version.assertPostWebpackVersion(); 
Until it is fixed properly.​​

**Comment by filipesilva** [comment] 2016-10-06 16:49
Dupe of https://github.com/angular/angular-cli/issues/2135

**Closed by filipesilva** 2016-10-06 16:49 UTC
