### ISSUE TITLE
Cannot find module 'uglifyjs-webpack-plugin'

### ISSUE THREAD

**Issue by navalgandhi1989** [angular/angular-cli#9428] opened 2018-01-29 20:24 UTC
### Versions 1.6.6
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.6
Node: 6.11.2
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.6
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

* ng new sample
* cd sample
* ng serve

### Observed behavior
```
 ng serve
Cannot find module 'uglifyjs-webpack-plugin'
Error: Cannot find module 'uglifyjs-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\sample\node_modules\@angular\cli\models\webpack-configs\production.js:13:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\sample\node_modules\@angular\cli\models\webpack-configs\index.js:9:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

### Desired behavior
First, I expect this simple project to run.
Then I would expect to run ng build --prod on another project

**Comment by ashfaqch** [comment] 2018-01-29 20:27
I am also getting same error...

**Comment by raphaelLacerda** [comment] 2018-01-29 20:41
+1

**Comment by chadbr** [comment] 2018-01-29 20:44
same... :(

**Comment by seekheart** [comment] 2018-01-29 20:45
ditto :(

**Comment by goodmase** [comment] 2018-01-29 20:46
+1. https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/217

**Comment by admosity** [comment] 2018-01-29 20:47
Dupe #9427

**Comment by ianseyer** [comment] 2018-01-29 20:50
+1

**Comment by williamchristophercooley** [comment] 2018-01-29 20:51
+1

**Comment by Shukarity** [comment] 2018-01-29 20:54
Same here

**Comment by hansl** [comment] 2018-01-29 20:54
Duplicate of #9427

**Closed by hansl** 2018-01-29 20:54 UTC

**Comment by jringwood** [comment] 2018-01-29 21:03
I've been trying to figure this problem out for about an hour, now.
I have uninstalled angular and reinstalled it.
I wasn't having this issue earlier and have no idea what could have changed that would cause me to run into this now. Any help would be awesome.

**Comment by nombielabs** [comment] 2018-01-29 21:19
+1

Was not having this issue approx 4 or 5 hours ago.

**Comment by changhuixu** [comment] 2018-01-29 21:35
+1
Same. happened just now
for new project

**Comment by ehthind** [comment] 2018-01-29 21:46
Check the version of uglifyjs-webpack-plugin you are using in your package.json.
I was using `1.1.7` which broke my build a few hours ago, however, after installing the latest version via `npm install --save uglifyjs-webpack-plugin` It upgraded to `1.1.8` and now my build is fine...

**Comment by cfremgen** [comment] 2018-01-29 22:08
Seems it's once a week that CLI is breaking our builds, and I'm sure thousands of other developers. Please version lock all dependent libraries.

**Comment by jonasarcangel** [comment] 2018-07-08 09:52
I use 1.2.7 but I'm getting this error. I'm not creating a new one though. I tried removing node_modules and package-lock.json, to no avail. https://github.com/jonasarcangel/ModuleIssue/tree/master/ClientApp.

**Comment by shn923** [comment] 2019-05-06 09:29
yes is wright
