### ISSUE TITLE
Changing an Interface doesn't seem to live reload it in the dev server

### ISSUE THREAD

**Issue by KyleMcNutt** [angular/angular-cli#6438] opened 2017-05-24 12:14 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.4
node: 7.8.0
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.4
@angular/compiler-cli: 4.1.3
```

### Repro steps.
Have a an app running in the dev server, and be referencing a simple `interface` and some properties from it somewhere in code, for example if you have an interface `Person` and then are referencing property `id` which is of type `string`. If you change the interface, and for example change the type of `id` to be `number` then you will start to get errors in the CLI's dev server about how the property is still of style `string`. It seems that the CLI's dev server doesn't automatically pick up on interface changes like this and instead you need to restart the server.

### The log given by the failure.
N/A

### Desired functionality.
That the CLI's dev server automatically updates when you make type changes to the interface and they are correct reflected on the next live reload.

**Comment by natedsaint** [comment] 2017-05-24 12:15
+1

**Comment by filipesilva** [comment] 2017-05-25 08:29
Dupe of https://github.com/angular/angular-cli/issues/5634

**Closed by filipesilva** 2017-05-25 08:29 UTC
Labels: priority: 2 (required), severity1: confusing

**Comment by KyleMcNutt** [comment] 2017-05-25 10:26
Ahhh! Thanks @filipesilva for pointing out the dupe!
