### ISSUE TITLE
[Feature Request] Process/include inline CSS in index.html

### ISSUE THREAD

**Issue by christianliebel** [angular/angular-cli#12336] opened 2018-09-21 07:59 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

N/A

### Repro steps

N/A

### The log given by the failure

N/A

### Desired functionality

It’s a common practice to include “above the fold” CSS right in the `index.html`. It would be great if we had a feature that allows us to import CSS files right in the index.html, so the CSS does not have to be duplicated, e.g.:

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Demo</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <style>@import "header";</style>
</head>
<body>
  <app-root></app-root>
</body>
</html>
```

Which would, during build, process (= resolve imports, minify etc.) and/or inline the CSS in the HTML file. Alternatively, there could be an option in `angular.json` to specify files which (processed) file should later be inlined in the `index.html`.

### Mention any other details that might be useful

https://css-tricks.com/authoring-critical-fold-css/

**Comment by alan-agius4** [comment] 2018-09-21 08:02
Duplicate of https://github.com/angular/angular-cli/issues/11395

**Closed by alan-agius4** 2018-09-21 08:02 UTC
