### ISSUE TITLE
Upgrade to 9 breaks ng-universal application.

### ISSUE THREAD

**Issue by shane-arthur** [angular/angular-cli#16087] opened 2019-11-06 20:14 UTC
### Angular 9 Upgrade Issues

Our team recently tried to upgrade to Angular 9 RC following the migration guide https://update.angular.io/ upgrading from 8.0x to 9.

When trying to run our universal build we are met with the following errors.

*TypeError: Cannot Assign to read only property '_showWarnings' of object '#<Object>'*

![Screen Shot 2019-11-04 at 4 02 02 PM](https://user-images.githubusercontent.com/18357121/68334098-e8977580-00a7-11ea-9ae1-2276e5bbef7c.png)
![Screen Shot 2019-11-04 at 3 58 24 PM](https://user-images.githubusercontent.com/18357121/68334100-e8977580-00a7-11ea-80af-a5d3f563f99c.png)

**Comment by alan-agius4** [comment] 2019-11-07 07:17
Kindly provide the full output of `ng version` & also the output of the log file. Parts of it is truncated in the the screenshot.

Thanks.

**Comment by kapilpatel20** [comment] 2019-11-14 15:28
I am facing the same issue . Here below is my ng version 

![image](https://user-images.githubusercontent.com/12792291/68870817-82eb5f00-0721-11ea-98a3-488933e37eee.png)

**Comment by kapilpatel20** [comment] 2019-11-14 15:30
![image](https://user-images.githubusercontent.com/12792291/68870894-a31b1e00-0721-11ea-9503-5398859113b4.png)

![image](https://user-images.githubusercontent.com/12792291/68870915-a7dfd200-0721-11ea-9d9e-c7b5275c9b18.png)


I am using Angular 8 universal and facing the same problem.

**Comment by clydin** [comment] 2019-11-14 15:35
Can you provide the output of `npm ls webpack` from within the project?

**Comment by kapilpatel20** [comment] 2019-11-15 05:40
the output is 

```
└─┬ @angular-devkit/build-angular@0.803.19
  └── webpack@4.39.2

```

![image](https://user-images.githubusercontent.com/12792291/68919525-76561d80-0798-11ea-965d-383264de71ca.png)

**Comment by kaushikparmar** [comment] 2019-11-20 06:31
Hey @alan-agius4 

@shane-arthur Did you solve this one?

This is the output of the log file.

TypeError: Cannot assign to read only property '_showWarnings' of object '#<Object>'
   at TapSubscriber._visitJsonRecursive.pipe.operators_1.tap.x [as _tapNext] (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/schema/visitor.js:56:210)
    at TapSubscriber._next (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/operators/tap.js:59:27)
    at TapSubscriber.Subscriber.next (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
    at MergeMapSubscriber._next (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/observable/scalar.js:6:20)
    at Observable._trySubscribe (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:30:22)
    at MergeMapOperator.call (/home/fxqa/www/web/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:39:23)[fxqa@FX web]$

**Comment by kaushikparmar** [comment] 2019-11-20 10:13
@shane-arthur 

Me and @kapilpatel20  able to solve this issue.

The reason behind this is @angular-devkit/build-angular@0.803.19

It was @angular-devkit/build-angular@0.803.5 when we created the Angular Universal project then someone did npm install and it got updated due to ^ symbol.

We the version back to @angular-devkit/build-angular@0.803.5  and it started working properly.

**Comment by guiseek** [comment] 2019-11-21 10:13
i have the same problem... works but doesn't allow sequential or concurrent commands for practical builds

**Comment by guiseek** [comment] 2019-11-21 10:16
> @shane-arthur
> 
> Me and @kapilpatel20 able to solve this issue.
> 
> The reason behind this is @angular-devkit/build-angular@0.803.19
> 
> It was @angular-devkit/build-angular@0.803.5 when we created the Angular Universal project then someone did npm install and it got updated due to ^ symbol.
> 
> We the version back to @angular-devkit/build-angular@0.803.5 and it started working properly.

Great!!! thanks bro!

**Comment by eternalmatt** [comment] 2019-11-21 17:42
Replying "me too" except I am on angular@8.2.0 after installing a new app from Nx.  This only occurs when I build my universal server.  Downgrading to 0.803.5 works.

**Comment by mehrad-rafigh** [comment] 2019-12-05 14:06
We are experiencing the same issue in our team. Downgrading build-angular to 0.803.6 fixed our problem

**Comment by pakman198** [comment] 2020-01-02 23:19
> @shane-arthur
> 
> Me and @kapilpatel20 are able to solve this issue.
> 
> The reason behind this is @angular-devkit/build-angular@0.803.19
> 
> It was @angular-devkit/build-angular@0.803.5 when we created the Angular Universal project then someone did npm install and it got updated due to ^ symbol.
> 
> We reverted the version back to @angular-devkit/build-angular@0.803.5 and it started working properly.

Thanks !
The only downside is that still you get some deps warnings with that version of @angular-devkit

**Comment by alan-agius4** [comment] 2020-01-24 19:10
Is this still reproducible? If so, can we please get a reproduction?

**Comment by mohamedaboelmagd** [comment] 2020-01-28 13:41
> @shane-arthur
> 
> Me and @kapilpatel20 are able to solve this issue.
> 
> The reason behind this is @angular-devkit/build-angular@0.803.19
> 
> It was @angular-devkit/build-angular@0.803.5 when we created the Angular Universal project then someone did npm install and it got updated due to ^ symbol.
> 
> We reverted the version back to @angular-devkit/build-angular@0.803.5 and it started working properly.

I have issue which solved from 0.803.7
so I can't back to 0.803.5

**Comment by at-dongho** [comment] 2020-03-12 15:09
I change to `"@angular-devkit/build-angular": "~0.800.0",` and it work for me.

**Comment by alan-agius4** [comment] 2020-06-24 07:14
Hi all, is this still reproducible using Angular CLI latest version 9 or prerelease of 10?

**Comment by alan-agius4** [comment] 2020-07-13 21:50
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2020-07-13 21:50 UTC
Labels: comp: devkit/build-angular, devkit/build-angular: server, need: more info, triage #1
