### ISSUE TITLE
.angular cache folder grows unbounded

### ISSUE THREAD

**Issue by jeffschulzusc** [angular/angular-cli#25000] opened 2023-04-12 15:40 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

before cache was introduced

### Description

seems my .angular folder just keeps growing ... it was at 90GB before i deleted it

### Minimal Reproduction

angular 15, build and serve projects

### Your Environment

```text
Angular CLI: 15.0.4
Node: 16.16.0
Package Manager: npm 8.11.0
OS: darwin arm64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1500.4 (cli-only)
@angular-devkit/core         15.0.4 (cli-only)
@angular-devkit/schematics   15.0.4 (cli-only)
@schematics/angular          15.0.4 (cli-only)
```

### Anything else relevant?

https://github.com/angular/angular-cli/issues/22323

**Comment by alan-agius4** [comment] 2023-04-12 15:47
I suspect that this might be a webpack issue. But without a reproduction it’s hard to tell what is happening.

**Comment by jeffschulzusc** [comment] 2023-04-12 16:13
will be necessary to disable caching until it is fixed ... 
i mean, after just a few builds the size is at 4GB

**Comment by alan-agius4** [comment] 2023-04-12 16:18
Please setup a minimal repro please.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by jeffschulzusc** [comment] 2023-04-12 17:43
trying to reproduce in minimal project ... so far i see it stable, with one project, i see under cache/15.2.5/angular-webpack 
that a uuid folder is created seems for each of build/serve production/development (4 folders)

it may be either a nrwl/nx problem or a scale problem:
- i am in an nx workspace (no more angular.json)
- workspace has 40+ projects

thanks

**Comment by alan-agius4** [comment] 2023-04-12 17:55
> i see under cache/15.2.5/angular-webpack
that a uuid folder is created seems for each of build/serve production/development (4 folders)

This is expected since each of these commands have different options and compilation units. 

> workspace has 40+ projects

I would expect that in this case the cache would be rather large, but it should somewhat stable.

**Comment by alan-agius4** [comment] 2023-04-20 10:32
Closing as there does not appear to be an issue from our end here. If the problem persists please open a new issue with a reproduction.

**Closed by alan-agius4** 2023-04-20 10:32 UTC
Labels: needs: repro steps
