### ISSUE TITLE
angular-cli is not working

### ISSUE THREAD

**Issue by beingbing** [angular/angular-cli#8906] opened 2017-12-16 17:47 UTC
#### I'm opening this issue because:
  - [0] npm is doing something I don't understand.

#### What's going wrong?

(after migrating into desired folder)when i ran -
`ng new my-app`
this is what i got -
![screenshot from 2017-12-16 13 54 07](https://user-images.githubusercontent.com/26813160/34072924-ce18699c-e2b5-11e7-86ca-b957b69dd774.png)

even when i ran -
`ng --version`
i am getting te same error

### supporting information:

 - `npm -v` prints:  5.6.0
 - `node -v` prints: v8.9.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues: none

**Comment by hansl** [comment] 2017-12-16 18:23
It's loading babel for some reason, but we do not depend on Babel at all (see our dependencies here: https://unpkg.com/@angular/cli@1.6.1/package.json

I suggest you try to remove your global installation and reinstall the CLI globally:

```
npm uninstall -g @angular/cli
npm install -g @angular/cli
```

I'm going to close this issue as fixed or not caused by the CLI. We do not use babel nor core-js in the Angular CLI. If you experience the same error after the steps above, please look at your environment setup.

**Closed by hansl** 2017-12-16 18:23 UTC
