### ISSUE TITLE
ng test "Cannot find source file" for npm dependencies

### ISSUE THREAD

**Issue by JohannesRudolph** [angular/angular-cli#2364] opened 2016-09-27 08:25 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OS X El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
iDevBook01:context jr$ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.15
node: 6.3.0
os: darwin x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

 1. Create a demo project ``ng new demo`` 
 2. add any npm angular 2 library (e.g. ng2-slim-loading-bar)
 3. edit `app.component.spec.ts` to import from library (e.g. `import { SlimLoadingBarService } from 'ng2-slim-loading-bar';`)
 4. run `ng test`

4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
WARNING in ./~/ng2-slim-loading-bar/index.js
Cannot find source file 'index.ts': Error: Can't resolve './index.ts' in '/Users/jr/dev/new-horizon/meshstack-ui/node_modules/ng2-slim-loading-bar'
 @ ./src/app/app.component.ts 9:2511-2542
 @ ./src/app/app.component.spec.ts
 @ ./src \.spec\.ts
 @ ./src/test.ts

WARNING in ./~/ng2-slim-loading-bar/src/slim-loading-bar.component.js
Cannot find source file 'slim-loading-bar.component.ts': Error: Can't resolve './slim-loading-bar.component.ts' in '/Users/jr/dev/new-horizon/meshstack-ui/node_modules/ng2-slim-loading-bar/src'
 @ ./~/ng2-slim-loading-bar/index.js 19:35-78 21:9-52
 @ ./src/app/app.component.spec.ts
 @ ./src \.spec\.ts
 @ ./src/test.ts

WARNING in ./~/ng2-slim-loading-bar/src/slim-loading-bar.service.js
Cannot find source file 'slim-loading-bar.service.ts': Error: Can't resolve './slim-loading-bar.service.ts' in '/Users/jr/dev/new-horizon/meshstack-ui/node_modules/ng2-slim-loading-bar/src'
 @ ./~/ng2-slim-loading-bar/index.js 20:33-74 22:9-50
 @ ./src/app/app.component.spec.ts
 @ ./src \.spec\.ts
 @ ./src/test.ts

WARNING in ./~/ng2-slim-loading-bar/src/slim-loading-bar.utils.js
Cannot find source file 'slim-loading-bar.utils.ts': Error: Can't resolve './slim-loading-bar.utils.ts' in '/Users/jr/dev/new-horizon/meshstack-ui/node_modules/ng2-slim-loading-bar/src'
 @ ./~/ng2-slim-loading-bar/src/slim-loading-bar.component.js 16:31-66
 @ ./~/ng2-slim-loading-bar/index.js
 @ ./src/app/app.component.spec.ts
 @ ./src \.spec\.ts
 @ ./src/test.ts

WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
45:15 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
57:15 Critical dependency: the request of a dependency is an expression
```

5. Mention any other details that might be useful.
I assume this has something to do with the way test.ts loads libraries/sets up the karma environment. Not sure where to start looking for a fix though. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JohannesRudolph** [comment] 2016-09-27 08:27
Potentially a duplicate of https://github.com/angular/angular-cli/issues/2359

**Comment by dzonatan** [comment] 2016-09-27 10:06
Warnings about `ng2-slim-loading-bar` package are shown because that package is missing `*.ts` files from npm registry while source maps still refers to them. They are ignored [in this line](https://github.com/akserg/ng2-slim-loading-bar/blob/master/.npmignore#L13).

You should create an issue in [akserg/ng2-slim-loading-bar](https://github.com/akserg/ng2-slim-loading-bar) for request of  adding typescript files or improving source maps.

**Comment by JohannesRudolph** [comment] 2016-09-27 10:33
Thanks @dzonatan, I will try this!

**Comment by dzonatan** [comment] 2016-09-27 11:26
Good question. I think the answer is hiding somewhere in [webpack configuration](https://github.com/angular/angular-cli/tree/master/packages/angular-cli/models) since **test** and **serve/build** have different configs.

Anyway they're just warnings and your tests should pass.

**Comment by filipesilva** [comment] 2016-10-05 15:28
Dupe of https://github.com/angular/angular-cli/issues/2359. The cause for other warnings are as @dzonatan described.

**Closed by filipesilva** 2016-10-05 15:28 UTC
