### ISSUE TITLE
Add all possible flag values in the Wiki

### ISSUE THREAD

**Issue by trichetriche** [angular/angular-cli#11875] opened 2018-08-13 08:25 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Command (mark with an `x`)
```
- [X] new
- [X] build
- [X] serve
- [X] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

**Node** v8.11.3
**NPM** 5.6.0
**CLI** 6.0.8
### Repro steps

*None*

### The log given by the failure

*None*

### Desired functionality

In the Wiki, I would like to see all the possible flag values so that I can use them. Currently, I have to look online to find the possible values, and the 6th version not being so old, it's really difficult. 

(Otherwise, please explain to me how to find the flag values, as I'm only a beginner with the CLI and my firt reflex is to go on the Wiki)

**Comment by alexeagle** [comment] 2018-08-13 22:37
Thanks, I think we can make this a dupe of #11847

**Closed by alexeagle** 2018-08-13 22:37 UTC
