### ISSUE TITLE
Watching changed files not working

### ISSUE THREAD

**Issue by papaiatis** [angular/angular-cli#4283] opened 2017-01-30 09:01 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
System: Latest Gentoo Linux with Gnome 3.22
angular-cli: 1.0.0-beta.26
node: 7.3.0
os: linux x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

Calling `ng build --watch` only builds once at the beginning, it doesn't capture file change events.
Project is generated by angular-cli.

**Comment by grizzm0** [comment] 2017-01-30 11:27
I just tried and it works fine for me. What's the console output after you save a file?

**Comment by papaiatis** [comment] 2017-01-30 11:44
There is no console output.  I think it didn't even realize a file was changed.
How should I debug this? What is listening for file changes?

**Comment by filipesilva** [comment] 2017-01-30 12:20
Dupe of https://github.com/angular/angular-cli/issues/1610 (`ng serve` should use the same watching mechanism as `ng build --watch`).

I don't have a definite answer for you but there's a few people with similar issues and workarounds in that thread. Let us know there if they solve your scenario.

**Closed by filipesilva** 2017-01-30 12:20 UTC
