### ISSUE TITLE
NG HELP / ERROR

### ISSUE THREAD

**Issue by kamalkech** [angular/angular-cli#4794] opened 2017-02-17 17:03 UTC
### OS?
> Windows 10

### Versions.
node : v6.9.5
npm : 3.10.10

### Repro steps.
after run "ng help" i got this error : 
The specified command core-object is invalid. For available options, see `ng help`.

any idea ??

**Comment by filipesilva** [comment] 2017-02-17 17:04
Dupe of https://github.com/angular/angular-cli/issues/4776

**Closed by filipesilva** 2017-02-17 17:04 UTC

**Comment by kamalkech** [comment] 2017-02-17 17:10
@filipesilva : i uninstall and install again the last version but error not fixed

**Comment by kamalkech** [comment] 2017-02-17 17:21
@filipesilva : i update file "cli.js" : 

```
 if (args.length === 0) {
   args[0] = 'help';
 }
```

But after run any command line like "ng g c nameComponent" i get message help !! : 

```
 ng g c contact
ng build <options...>
  Builds your app and places it into the output path (dist/ by default).
  aliases: b
  --target (String) (Default: development)
    aliases: -t <value>, -dev (--target=development), -prod (--target=production), --target <value>
  --environment (String)
    aliases: -e <value>, --environment <value>
  --output-path (Path)
    aliases: -op <value>, --outputPath <value>
  --aot (Boolean)
    aliases: -aot
  --sourcemap (Boolean)
    aliases: -sm, --sourcemaps, --sourcemap
  --vendor-chunk (Boolean) (Default: true)
    aliases: -vc, --vendorChunk
  --base-href (String)
    aliases: -bh <value>, --baseHref <value>
  --deploy-url (String)
    aliases: -d <value>, --deployUrl <value>
  --verbose (Boolean) (Default: false)
    aliases: -v, --verbose
  --progress (Boolean) (Default: true)
    aliases: -pr, --progress
  --i18n-file (String)
    aliases: --i18nFile <value>
  --i18n-format (String)
    aliases: --i18nFormat <value>
  --locale (String)
    aliases: --locale <value>
  --extract-css (Boolean)
    aliases: -ec, --extractCss
```

**Comment by filipesilva** [comment] 2017-02-17 17:29
@kamalkech I don't recommend manually changing the package files unless you know what you're doing.

**Comment by kamalkech** [comment] 2017-02-17 17:39
@filipesilva i update to last version and same issue

**Comment by filipesilva** [comment] 2017-02-17 17:49
This issue isn't fixed yet. When it is fixed it will be released on the next version. Meanwhile you can use `ng help` instead of just `ng`.
