### ISSUE TITLE
--stats-json flag doesn't work on Windows

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular-cli#6131] opened 2017-04-29 17:19 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Output from: `ng --version`.
```
@angular/cli: 1.0.0
node: 6.10.1
os: win32 x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
```

### Repro steps.
On Windows:
1. `ng new demo`
2. `ng build --prod --stats-json`

### The log given by the failure.

```
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\George\Source\Repos\demo\dist\stats.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
```

### Desired functionality.

Stats to work properly on Windows

**Comment by filipesilva** [comment] 2017-05-05 21:41
Hm, I'm on windows and can't repro. Does this always happen for you?

**Comment by EugeneAzhogin** [comment] 2017-07-01 14:15
I have the same behaviour if any ts-file (for example) has an syntax error.

```
fs.js:641
      return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                     ^

    EXEC : error : ENOENT: no such file or directory, open 'D:\Projcts\Test\dist\stats.json'
        at Error (native)
        at Object.fs.openSync (fs.js:641:18)
        at Object.fs.writeFileSync (fs.js:1347:33)
        at callback (D:\Projcts\Test\node_modules\@angular\cli\tasks\build.js:40:24)
        at onCompiled (D:\Projcts\Test\node_modules\webpack\lib\Compiler.js:239:14)
        at D:\Projcts\Test\node_modules\webpack\lib\Compiler.js:494:13
        at next (D:\Projcts\Test\node_modules\tapable\lib\Tapable.js:138:11)
        at Compiler.<anonymous> (D:\Projcts\Test\node_modules\webpack\lib\CachePlugin.js:62:5)
        at Compiler.applyPluginsAsyncSeries (D:\Projcts\Test\node_modules\tapable\lib\Tapable.js:142:13)
        at D:\Projcts\Test\node_modules\webpack\lib\Compiler.js:491:10
        at Compilation.applyPluginsAsyncSeries (D:\Projcts\Test\node_modules\tapable\lib\Tapable.js:131:46)
        at self.applyPluginsAsync.err (D:\Projcts\Test\node_modules\webpack\lib\Compilation.js:645:19)
        at next (D:\Projcts\Test\node_modules\tapable\lib\Tapable.js:138:11)
        at Compilation.compilation.plugin (D:\Projcts\Test\node_modules\webpack\lib\ProgressPlugin.js:121:6)
        at Compilation.applyPluginsAsyncSeries (D:\Projcts\Test\node_modules\tapable\lib\Tapable.js:142:13)
        at self.applyPluginsAsync.err (D:\Projcts\Test\node_modules\webpack\lib\Compilation.js:636:11)
```

Besides, dist folder does not created.

**Comment by danizen** [comment] 2017-08-23 22:16
It works for me on Windows with Node 6.9.4 and npm 3.1.0.10, but the stats file is not generated alongside --watch.

So, the following works:
```
ng build --stats-json
```

The following does not:
```
ng build --watch --stats-json
```

I'm debating filing another issue, but will refrain until I can try this from Ubuntu at home.

**Comment by filipesilva** [comment] 2017-08-31 15:08
@EugeneAzhogin it's definitely mean to fail somehow when you have TS errors.

@danizen I can confirm that I don't get the stats json on watch mode either, but that's definitely another issue.

I'm closing this one as it seems to be working.

**Closed by filipesilva** 2017-08-31 15:08 UTC
Labels: need: repro steps
