### ISSUE TITLE
Angular CLI is giving error - Can't resolve '/assets/***sharedfonts/open-sans-v15-latin-300.woff2' after updated to Angular 10

### ISSUE THREAD

**Issue by ErVishalM** [angular/angular-cli#18043] opened 2020-06-26 14:27 UTC
Hi,

I just updated to `Angular 10` and before this i was using `Angular 9.1` and this was working fine in `Angular 9.1` now angular cli is throwing error that
`Can't resolve '/assets/***sharedfonts/open-sans-v15-latin-300.woff2'`
![image](https://user-images.githubusercontent.com/43669644/85866691-6948e480-b7e5-11ea-9818-c30617b25941.png)

If i remove the **~** then it is working fine on local server but it is not replacing relative path in **styles.d17173f9650483347d45.css** production css file.

So because of that i am getting error on production server if i remove **~**
![image](https://user-images.githubusercontent.com/43669644/85866794-95646580-b7e5-11ea-9029-e9e99e7041a6.png)

**Previous Angular 9.1 styles.css production file angular cli was automatically adding my href (MyProject) in path**
![image](https://user-images.githubusercontent.com/43669644/85867284-4a971d80-b7e6-11ea-8b59-7a96368d9068.png)
**Angular 10 styles.css production file angular cli not adding my href (MyProject) in path**
![image](https://user-images.githubusercontent.com/43669644/85867430-84682400-b7e6-11ea-913d-9aa35bb18642.png)

Adding this **~** before `/assets/` i got this answer from [here](https://github.com/angular/angular-cli/issues/6599)
Please help me what am i missing? Is there something i need to do?

**Comment by alan-agius4** [comment] 2020-06-26 14:57
Duplicate of https://github.com/angular/angular-cli/issues/18013

**Comment by alan-agius4** [comment] 2020-06-26 15:04
Duplicate of https://github.com/angular/angular-cli/issues/18041

**Closed by alan-agius4** 2020-06-26 15:04 UTC

**Comment by ErVishalM** [comment] 2020-06-26 16:13
Hi @alan-agius4  I am sorry i m disturbing you again but nothing solved my problem
I tried this in `angular.json`
`{ "glob": "**/*", "input": "src/assets/", "output": "./assets/" }`
in this time i was using URL as  
```
@font-face {
    font-family: 'Open Sans';
    font-style: normal;
    font-weight: 300;
    src: url('/assets/sharedfonts/open-sans-v15-latin-300.eot');}
```
So this **works on localhost** but not **on production mode**. But before **in Angular 9.1 i did nothing** and i was using **~** like this
```
@font-face {
    font-family: 'Open Sans';
    font-style: normal;
    font-weight: 300;
    src: url('~/assets/sharedfonts/open-sans-v15-latin-300.eot');}
```
and it was working. 
Can you please tell me what can i do to solve this

**Comment by alan-agius4** [comment] 2020-06-26 16:18
@ErVishalM, without a reproduction and the needed information it's hard to tell what's happening.

**Comment by ErVishalM** [comment] 2020-06-27 04:46
Hi @alan-agius4 ,
I'm sorry it took me time to create reproduction actually I never did it before so here is the repository [url](https://github.com/ErVishalM/Angular10Path.git) Now when you will check i am building in prod mode with command 
`ng build --prod --base-href=/MyAg/` So after build successfully this is the ss of file **styles.bc46f4802651edaf4c0b.css**

![image](https://user-images.githubusercontent.com/43669644/85914736-7524bd00-b85e-11ea-990b-6852deb6e3ca.png)

check url which i marked **(It is giving me error on production server)**

![image](https://user-images.githubusercontent.com/43669644/85914786-08f68900-b85f-11ea-9e22-40588e745c07.png)

url should be coming as (Expected Output) **as this was coming in before in Angular 9.****

![image](https://user-images.githubusercontent.com/43669644/85914771-dfd5f880-b85e-11ea-893d-d0addadc34b3.png)

**Comment by ErVishalM** [comment] 2020-06-27 12:43
Hi @alan-agius4 , have you checked this Can you please reopen this issue as you said it was a duplicate but in those issues also I'm getting the same error in Angular 10. May be anyone not used `--base-href` in production mode that's why they are not getting any error in production mode.
Thank you!

**Comment by alan-agius4** [comment] 2020-06-27 13:35
@ErVishalM, I’ll take a look on Monday.

**Comment by ErVishalM** [comment] 2020-06-29 04:56
Hi, @alan-agius4 according to upper mentioned issue best way to use relative path in css but because of this all the files are **copied to the root folder** which is very difficult for large application there can be so many files so all files will be copied to root folder like this 
![image](https://user-images.githubusercontent.com/43669644/85974163-6e2eb380-b9f2-11ea-8aa4-cb0f0d066437.png)

But before in Angular `9.* ` it was working correctly so this is breaking change in `Angular 10` or there is another way out to use the same as we were using in `Angular 9.*` in previous cli all files were coming where we mentioned ex  in upper case - **`root/assets/sharedfonts`**
Thanks.

**Comment by alan-agius4** [comment] 2020-06-29 13:35
Hi @ErVishalM, 

This is working as expected. When using root paths `/` together with `baseHref`. the base href value is not inlined as part of the resource path in the CSS files. This has also been the case for a number of previous versions. if you want the base href to be included you can opt-in the deprecated behaviour using the `rebaseRootRelativeCssUrls` option.

If you wish that processed assets are not placed in the root of `dist` folder you can use the `resourcesOutputPath` option.

More information about these options can be found: https://angular.io/cli/build

**Comment by ErVishalM** [comment] 2020-06-29 13:56
Hi @alan-agius4 , Thank for the reply. In my case assets are already coming in `assets/sharedfonts` folder so now what should i change in css to be pick all the related assets from this folder only. As in `Angular 9.*` as i already mentioned , I was using url like this 
```
@font-face {
    font-family: 'Open Sans';
    font-style: normal;
    font-weight: 300;
    src: url('~/assets/sharedfonts/open-sans-v15-latin-300.eot');}
```
which was working and all the assets were coming in `assets/sharedfonts` and css was picking all the assets from there see the path. The base href value is inlined as part of the resource path in the CSS files.
![image](https://user-images.githubusercontent.com/43669644/86014375-dfe01f00-ba3d-11ea-9ba6-c3bc52b98191.png)

now **why its not working in** `Angular 10` why **~** it is giving me error? Why i need to change in code if everything is working as expected? because now behavior is not the same as it was working in `Angular 9.*`. 
**Now i don't know what change i have to do to get the same behavior, as it was working before**

**Comment by alan-agius4** [comment] 2020-06-29 15:41
@ErVishalM, having the base href inlined in the bundle when using root level paths ie paths starting with a  `/` is non standard and is deprecated behaviour which will be removed in the future without a replacement. 

Since version 9, the base href value is not included in the final css file unless opting in the deprecated behaviour mentioned above. See: https://github.com/angular/angular-cli/issues/14587. The `rebaseRootRelativeCssUrls` option is there to allow users enough time to transition away from needing a base href inlined in their stylesheet. 

In most cases users should rely upon the build system to process and emit assets referenced in CSS.

Paths starting with `~/`, `^/` etc.. are Webpack specific features which we always encountered users not to rely upon as these are unsupported and might break in the future version without warning.

**Comment by ErVishalM** [comment] 2020-06-29 16:04
@alan-agius4 , with due respect as you can see there are so many people waiting for correct answer and as your are saying all we are using a non standard method and `rebaseRootRelativeCssUrls` this will be remove in future so can you please create a sample for us to teach what is the standard for this which standard we can use. Please give us a working example with this requirement so that our life will be easy.
Please do this favour for us.

**Comment by alan-agius4** [comment] 2020-06-29 16:32
@ErVishalM, the recommended approach is to use either **relative** paths were the assets will be processed out-of-the-box by the build system or use root paths if you want to load assets which are not relative to your base-href where you will need to copy the assets manually using `assets` option.

**Comment by ErVishalM** [comment] 2020-06-29 17:05
@alan-agius4 , Thanks for the information. 
I love seeing a sample but it's ok as I asked 3-4 times already.

Forget it. Thank you so much for helping me in a way. 👍😊
