### ISSUE TITLE
Debug cli-generated project with Visual Studio Code

### ISSUE THREAD

**Issue by daverupp** [angular/angular-cli#1223] opened 2016-06-27 14:52 UTC
Version:
Windows 10
angular-cli: 1.0.0-beta.8
node: 6.2.2
os: win32 x64

I changed nothing in the code, I am just trying to get it working with Visual Studio Code :-)

Here is my launch.json content:

`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch index.html with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "file": "${workspaceRoot}/src/index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}/dist/"
        },
        {
            "name": "Launch localhost with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:4200/index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}/dist/"
            
        },
        {
            "name": "Attach with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}/dist/"
        }
    ]
}
`

**Comment by guidorice** [comment] 2016-06-27 23:12
@daverupp - just an aside question- in genral, are you able to do angular2 development on Windows? I tried on windows10, but I ran into some npm module that was trying to create symlinks, which was failing on windows. I do not remember which module it was- it could have been part of the quickstart project.

**Comment by daverupp** [comment] 2016-06-28 06:55
So far everything is working. Honestly I just started with developing with Angular2. But the "Hero" quickstart works properly.

**Comment by guidorice** [comment] 2016-06-29 00:36
@daverupp sorry my bad- I must have been remembering some other node modules which fail on windows because of symlinking. Angular2 quickstart works great on Win10.

**Comment by code1line** [comment] 2016-09-17 11:12
@daverupp - this doesn't work for me. Do you start with "ng serve" and then run the debug-session?

**Comment by filipesilva** [comment] 2016-09-22 02:17
Can't answer this myself as I don't use the functionality you're trying to use, but will flag it for community help.

**Comment by daverupp** [comment] 2016-09-29 08:37
Yes I tried to run with ng serve. The angular app is running in localhost:4200.

Then I tried to attach to port 9222 via chrome (I attached this to the chrome launch:  --remote-debugging-port=9222)

when run visual studio code, in the console is written: "SW registered". So that seems to be promising.

But when I go to localhost:4200 and click on a button to hit the breakpoint, still nothing happens... 

Anyone can help?

**Comment by cjrosa** [comment] 2016-10-04 20:35
To too am unable to debug **angular-cli** created application in VC Code.  Seemingly no combination of launch.json setting will enable breakpoints being hit.  There is alot of chatter in the debug console related to "webpack" when the `"diagnosticLogging": true` is set, but no obvious indications. 

I added as tcs task to force the creation of the *.js and *.map files to be coresident with the *.ts files to no avail (this worked on an non-cli app served from iisExpress, not via tsserver).

Thanks!

**Comment by ufleisch** [comment] 2016-10-07 14:23
I can debug from Visual Studio Code after adding a `sourceMapPathOverrides` to `launch.json` (Linux, project created with current angular-cli):

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Chrome against localhost, with sourcemaps",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:4200",
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}",

      "sourceMapPathOverrides": {
        "webpack:///*": "/*"
        // "webpack:////absolute/path/to/workspaceRoot/*": "${webRoot}/*"
        // works too, but this will not work:
        // "webpack:///${workspaceRoot}/*": "${webRoot}/*"
      }
    },
    {
      // For this to work, start chrome using
      // google-chrome --remote-debugging-port=9222 http://localhost:4200
      // and do not use its developer tools simultaneously.
      "name": "Attach to Chrome, with sourcemaps",
      "type": "chrome",
      "request": "attach",
      "port": 9222,
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}",

      "sourceMapPathOverrides": {
        "webpack:///*": "/*"
      }
    }
  ]
}
```

See also Microsoft/vscode-chrome-debug#226 for a `sourceMapPathOverrides`with an absolute Windows path.

**Comment by cjrosa** [comment] 2016-10-08 20:23
@ufleisch Thanks!  I've confirmed that I too can debug given the launch.json you've provided.  Note I'm using windows and an absolute path was necessary.

**Comment by filipesilva** [comment] 2016-10-09 00:33
Closing in favor of https://github.com/angular/angular-cli/issues/2453 since there's more investigation and solutions there.

**Closed by filipesilva** 2016-10-09 00:33 UTC
Labels: flag: help wanted, type: question/support

**Comment by rafalkasa** [comment] 2017-01-07 11:00
If you are windows users try to change in your launch.json **sourceMapPathOverrides** from default: ``` "webpack:///*": "/*" ```
to:
```
"sourceMapPathOverrides": {
    "webpack:///C:*":"C:/*"
}
```
and Launch Chrome against localhost, with sourcemaps from VSCode

**Comment by amitvchaudhary** [comment] 2017-09-12 14:10
Hi All,

I am still facing the problem.

Below is the launch.json file:

{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Chrome against localhost, with sourcemaps",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:4200",
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}",

      "sourceMapPathOverrides": {
        "webpack:///C:*":"C:/*"
    }
    },
    {
 
      "name": "Attach to Chrome, with sourcemaps",
      "type": "chrome",
      "request": "attach",
      "port": 9222,
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}",

      "sourceMapPathOverrides": {
        "webpack:///C:*":"C:/*"
    }
    }
  ]
}

Please help me out.

**Comment by filipesilva** [comment] 2017-09-12 16:07
There's an official VSCode guide in https://github.com/Microsoft/vscode-recipes/tree/master/Angular-CLI as well.
