### ISSUE TITLE
New project is not created where I would expect

### ISSUE THREAD

**Issue by mikeerickson** [angular/angular-cli#3568] opened 2016-12-15 02:00 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

10.2.2 Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

 $ ng version
angular-cli: 1.0.0-beta.22-1
node: 6.8.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

```
$ ng new test
```

![image](https://cloud.githubusercontent.com/assets/183153/21209095/15ccb0b4-c227-11e6-9b6a-c0eb07da785b.png)

When `test` is actually created, it is located at

```
~/cli-test
```

![image](https://cloud.githubusercontent.com/assets/183153/21209118/3e4f3ac0-c227-11e6-9605-87d2ca66f12a.png)

**Comment by Nikki1993** [comment] 2016-12-15 11:54
Cannot reproduce it. I created a test folder in my Downloads folder (git-demo), cded into it and ran 

`ng new cli-test` and got back the file path for project `/Downloads/git-demo/cli-test`

```
angular-cli: 1.0.0-beta.22-1
node: 7.2.1
os: darwin x64
```

**Comment by mikeerickson** [comment] 2016-12-15 17:25
I doubt this is the issue, but only differences I see are

- I am using node 6.8, you are using 7.2.1
- I am creating at a deeper level 
   ~/documents/projects/angular 
- you are at
   ~/downloads

I will try again using the same as you

**Comment by Nikki1993** [comment] 2016-12-15 17:49
I am doing it a bit deeper, created a folder inside downloads. I could nest like 10 folders and try.

**Comment by hansl** [comment] 2016-12-15 18:32
You have a `node_modules` inside your home folder or somewhere above where you want to create your project. Some people create `node_modules` folders by running `npm install` (instead of installing something globally), it's a common mistake. The solution is to delete that rogue `node_modules` and try to run `ng new` again. The reason the CLI gets confused is because Ember CLI (which we're based on) uses the existence of a `node_modules` folder as the root of your project.

Closing this.

**Closed by hansl** 2016-12-15 18:32 UTC

**Comment by mikeerickson** [comment] 2016-12-15 18:42
@hansl ah yes indeed, I did have a rogue node_modules directory.  I removed the node_modules directory and all worked as expected
