### ISSUE TITLE
ng update @angular/cli --migrate-only --from=1.7.1 migrates assets incorrectly

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#10180] opened 2018-04-04 18:37 UTC
### Versions
```
Angular CLI 1.7.x project
Upgraded to Angular CLI 6.0.0-rc.0

```

### Repro steps
* ng new with 1.7
* locally update to @angular/cli@next
* run `ng update @angular/cli --migrate-only --from=1.7.1`

### Observed behavior
Asset don't get included as part of an `ng build` because the asset configuration is wrong

### Desired behavior
Correct asset configuration

**Comment by filipesilva** [comment] 2018-04-05 10:34
Duplicate of https://github.com/angular/angular-cli/issues/10146, fixed via https://github.com/angular/devkit/pull/620

**Closed by filipesilva** 2018-04-05 10:34 UTC
