### ISSUE TITLE
Angular cli dependency @angular-devkit/schematics not found on install

### ISSUE THREAD

**Issue by DrCalx** [angular/angular-cli#9703] opened 2018-02-20 16:00 UTC
### Versions
```
$ node --version
v8.9.4

$ npm --version
5.6.0
```

### Repro steps
* Step 1: `npm install @angular/cli -g`

### Observed behavior
```
npm ERR! code E404
npm ERR! 404 Not Found: @angular-devkit/schematics@0.3.1
```

### Desired behavior
I expect all dependencies to download and install

**Comment by hansl** [comment] 2018-02-20 20:35
Schematics 0.3.1 has been published last Wednesday; https://unpkg.com/@angular-devkit/schematics@0.3.1/

Closing this as we cannot reproduce. Are you behind a proxy or using a cache that would be missing this dependency?

**Closed by hansl** 2018-02-20 20:35 UTC
