### ISSUE TITLE
ng serve ignores includePaths in stylePreprocessorOptions

### ISSUE THREAD

**Issue by xXKeyleXx** [angular/angular-cli#15254] opened 2019-08-06 10:30 UTC
# 🐞 Bug report

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Works fine in 8.1.2

## 🔬 Minimal Reproduction
Add following code to the `build` architect in the angular.json
<pre><code>
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/scss"
              ]
            },
</code></pre>

Create `constants.scss` in the `src/scss` folder

Add `@import 'constants';` to any component stylesheet

Run `ng serve`

## 🔥 Exception or Error
<pre><code>
ERROR in ./src/app/modules/help/components/help-button/help-button.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import "constants";
       ^
      Can't find stylesheet to import.
  ?
1 ? @import "constants";
  ?         ^^^^^^^^^^^
  ?
  stdin 1:9  root stylesheet
      in /usr/src/src/app/modules/help/components/help-button/help-button.component.scss (line 1, column 9)
</code></pre>

## 🌍 Your Environment
<pre><code>
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@angular/cdk                      8.1.2
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.1.2
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**
It doesn't happen in `ng build`

**Comment by alan-agius4** [comment] 2019-08-06 20:43
I am thinking this might be related to: https://github.com/angular/angular-cli/issues/15126

Can you try to rename the scss partial files to something else?

**Comment by xXKeyleXx** [comment] 2019-08-07 07:38
You are correct. It seems to be the same problem. I renamed the file to `variables.scss` and it works fine now.

**Comment by alan-agius4** [comment] 2019-08-07 08:52
In that case Ill close this as it is not caused by the CLI, but rather caused by sass-loader which is being tracked here: https://github.com/webpack-contrib/sass-loader/issues/704

If you can provide further info in that issue, it would be awesome.

Thank you.

**Closed by alan-agius4** 2019-08-07 08:52 UTC
Labels: comp: devkit/build-angular, need: more info
