### ISSUE TITLE
Error Thrown Adding Lib After Upgraded to Angular 13

### ISSUE THREAD

**Issue by benedict-chng** [angular/angular-cli#22453] opened 2022-01-07 05:05 UTC
After upgrading to Angular 13, my application can be compiled and be served and hot-reload all works. Unfortunately when I try to add a new library to it, I got the following error:

> ng g lib features/test-admin
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID

I didn't get this error previously when I was working on Angular 10.

I've attached package.json and package-lock.json for your reference.

[package-json.zip](https://github.com/angular/angular-cli/files/7826591/package-json.zip)

The content of the error is:
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\core\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\core\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\core\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\core\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\core\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\core\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\core\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\core\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\core\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\core\node_modules\ajv\dist\compile\codegen\index.js:568:18)

**Comment by alan-agius4** [comment] 2022-01-07 09:31
Please provide the output of `ng v` and `npm ls @schematics/angular`?

Likely you are depending on an older incompatible version of `@schematics/angular`.

**Comment by benedict-chng** [comment] 2022-01-09 04:17
Hi @alan-agius4,

These are the information you're asking for:
C:\Workspace\Nova\Avatar>ng v

Angular CLI: 13.1.2
Node: 12.22.7
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.13.10
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.4.4

avatar@0.0.0 C:\Workspace\Nova\Avatar
+-- @angular/cli@13.1.2
| `-- @schematics/angular@13.1.2
+-- @nrwl/builders@7.8.7
| `-- @angular/cli@7.3.1
|   `-- @schematics/angular@7.3.1
`-- @nrwl/schematics@8.12.11
  `-- @nrwl/angular@8.12.11
    `-- @schematics/angular@8.3.23

**Comment by benedict-chng** [comment] 2022-01-09 04:41
Also inside the node_modules/@schematics/angular directory, the top part of the package.json file says:

{
  "_args": [
    [
      "@schematics/angular@13.1.2",
      "C:\\Workspace\\Nova\\Avatar"
    ]
  ],
  "_development": true,
  "_from": "@schematics/angular@13.1.2",
  "_id": "@schematics/angular@13.1.2",

**Comment by alan-agius4** [comment] 2022-01-09 10:30
The problem seems to be caused by `@nrwl/builders` and `@nrwl/schematics`. 

Please uninstall these packages and try again.

**Comment by benedict-chng** [comment] 2022-01-10 06:04
Thanks @alan-agius4, it is indeed a problem with the @nwrl package. Unfortuntely we used a legacy version of this. Seems like the only way is to upgrade it ...

Any other way to get pass this problem?

**Comment by alan-agius4** [comment] 2022-01-10 08:03
@benedict-chng, unfortunately, the only option is to remove the incompatible packages by either uninstalling or updating them. 

Closing since this is not actionable from our end.

**Closed by alan-agius4** 2022-01-10 08:03 UTC
Labels: need: more info
