### ISSUE TITLE
ng build --prod=true fails with global scripts in agular.json when opt-in to Webpack 5

### ISSUE THREAD

**Issue by nchangnon** [angular/angular-cli#19598] opened 2020-12-11 22:18 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

This works when not opting-in to Webpack 5.

### Description

 A clear and concise description of the problem... -->
If scripts are specified in the build options to be included globally, `ng build --prod=true` fails to build.

## 🔬 Minimal Reproduction

1. create a new angular project
2. opt-in to webpack 5 :
`"resolutions": { "webpack": "5.4.0" }`
3. add an external dependency such as jquery to package.json (using yarn)
`yarn add jquery`

4. update angular.json to include the new global dependency

<pre>
<code>
  "projects": {
    "wp5": {
      "projectType": "application",
      "schematics": {},
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/wp5",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": [
              "./node_modules/jquery/dist/jquery.min.js"
            ]
          }
     ...
   }
</code>
</pre>

5. run `ng build --prod=true`

## 🔥 Exception or Error
<pre><code>

wp5 % ng build --prod=true
✔ Browser application bundle generation complete.
An unhandled exception occurred: Chunk.modulesIterableThere was no ChunkGraph assigned to the Chunk for backward-compat (Use the new API)
See "/private/var/folders/km/qmp0wv016q9chrhmsr34qdp80000gn/T/ng-zRypdH/angular-errors.log" for further details.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.0.4
Node: 15.3.0
OS: darwin x64

Angular: 11.0.3
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.0-next.2
@angular-devkit/build-angular   0.1101.0-next.2
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@angular/cli                    11.0.4
@angular/compiler-cli           11.0.4
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-12-14 08:53
Duplicate of https://github.com/angular/angular-cli/issues/19550

Addressed in `~0.1101.0-next.2`, to try out the prerelease run `ng update @angular/cli --next`

**Comment by nchangnon** [comment] 2020-12-14 16:30
@alan-agius4 This bug is present in 0.1101.0-next.2

**Comment by alan-agius4** [comment] 2020-12-14 16:44
Hi @nchangnon,

Apologies, I didn't notice that you were already on `~0.1101.0-next.2`.

The error does appear to be a Webpack 5 bug which was fixed in a more recent version. Using `5.10.1` should solve the issue.

**Comment by alan-agius4** [comment] 2020-12-14 16:49
I actually managed to replicate it. For some reason I wasn't before when I used the latest version of Webpack.

**Comment by alan-agius4** [comment] 2020-12-14 16:51
I actually managed to replicate it. For some reason I wasn't before when I used the latest version of Webpack. It appears to be caused by the `license-webpack-plugin` plugin. Disabling license extraction doesn't cause an error.

```
ng build --prod --no-extract-licenses
```

**Comment by alan-agius4** [comment] 2021-01-04 11:18
Closing as it's currently fixed on master branch and will be part of the 11.1 release.

**Closed by alan-agius4** 2021-01-04 11:18 UTC
Labels: comp: devkit/build-angular, devkit/build-angular: browser, freq1: low, severity3: broken, state: blocked on upstream, type: bug/fix
