### ISSUE TITLE
`ng g universal` generate wrong path in tsconfig.server.json

### ISSUE THREAD

**Issue by thanatos915** [angular/angular-cli#10383] opened 2018-04-19 05:08 UTC
### Versions
```
Angular CLI: 6.0.0-rc.5
Node: 8.11.1
OS: darwin x64
Angular: 6.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.7
@angular-devkit/build-angular     0.5.7
@angular-devkit/build-optimizer   0.5.7
@angular-devkit/core              0.5.7
@angular-devkit/schematics        0.5.7
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.5
@schematics/angular               0.5.7
@schematics/update                0.5.7
rxjs                              6.0.0-uncanny-rc.7
typescript                        2.7.2
webpack                           4.5.0
```

### Repro steps
* Step 1
```
ng new my-app
```
* Step 2
```
ng g universal --client-project 
```

### Observed behavior
```
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/my-app-server",
            "main": "projects/my-app/src/main.server.ts",
            "tsConfig": "projects/my-app/tsconfig.server.json"
          }
```

### Desired behavior
```
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/my-app-server",
            "main": "src/main.server.ts",
            "tsConfig": "src//tsconfig.server.json"
          }
```

**Comment by alan-agius4** [comment] 2018-04-20 06:44
I observed the same thing

**Comment by RicardoVaranda** [comment] 2018-04-20 07:42
Hi @thanatos915 ,

Thanks for reporting this issue, seems it seems to be a duplicate of #10288.

**Comment by vikerman** [comment] 2018-04-25 01:13
Please follow #10288.

**Closed by vikerman** 2018-04-25 01:13 UTC
