### ISSUE TITLE
Custom form validator generation

### ISSUE THREAD

**Issue by ShinDarth** [angular/angular-cli#8709] opened 2017-12-01 12:29 UTC
It would be nice if we had something like:

`ng generate validator path/to/my-custom-validator`

which automatically generates skeletons for a custom form validator and its unit tests.

For example:

`my-custom.validator.ts`

```
import { AbstractControl, ValidationErrors, ValidatorFn } from '@angular/forms';

export function myCustomValidator(arg1: string, arg2: string): ValidatorFn {
  return (form: AbstractControl): ValidationErrors | null => {
    const error: ValidationErrors = { myCustomErrorName: true };

    // ...

    form.setErrors(null);
    return null;
  };
}
```

`my-custom.validator.spec.ts`

```
import { AbstractControl, FormControl, FormGroup, ValidationErrors, ValidatorFn } from '@angular/forms';
import Spy = jasmine.Spy;

import { myCustomValidator } from './my-custom-validator.ts';

describe('MyCustomValidator', () => {
  let form: FormGroup;
  let myCustomValidatorFn: ValidatorFn;

  const error: ValidationErrors = { myCustomErrorName: true };

  beforeEach(() => {
    form = new FormGroup({
      // ...
    });

    myCustomValidatorFn = myCustomValidator(...);

    spySetErrors = spyOn(form, 'setErrors').and.callThrough();
  });

  it('should correctly ...', () => {
    // ...

    expect(myCustomValidatorFn(form)).toEqual(...);

    // ...
  });
});
```

**Comment by clydin** [comment] 2017-12-01 15:58
Thanks for reporting this issue. However, this issue is appears to be a duplicate of an existing issue #8170. Please subscribe to that issue for future updates.

**Closed by clydin** 2017-12-01 15:58 UTC
