### ISSUE TITLE
Angular CLI: JavaScript heap out of memory

### ISSUE THREAD

**Issue by genemars** [angular/angular-cli#18070] opened 2020-06-29 13:55 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/cli

### Description

`ng serve` crashes during the compilation process when triggered by a file modification in `src` folder. This happen after a certain number of builds (let's say < 100).

## 🔬 Minimal Reproduction

https://github.com/genielabs/HomeGenie/tree/master/src/homegenie-ui-app

## 🔥 Exception or Error
<pre><code>
Date: 2020-06-29T13:19:51.270Z - Hash: 6712bb111bedcaf80f27
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 385 kB [initial] [rendered]
Time: 5292ms
: Compiled successfully.

Date: 2020-06-29T13:21:29.463Z - Hash: 6712bb111bedcaf80f27
5 unchanged chunks

Time: 3916ms
: Compiled successfully.

Date: 2020-06-29T13:33:02.243Z - Hash: 6712bb111bedcaf80f27
5 unchanged chunks

[... and after a dozen more succesfully compilations... ]

Time: 7809ms
: Compiled successfully.
50% building 0/3 modules 3 active ...Development/Repositories/github-genielabs/HomeGenie/src/homegenie-ui-app/src/app/splash-screen/splash-screen.component.ts
<--- Last few GCs --->

[281038:0x356da20]  2837154 ms: Mark-sweep 1359.5 (1447.4) -> 1347.0 (1448.4) MB, 1612.1 / 0.0 ms  (average mu = 0.347, current mu = 0.354) allocation failure scavenge might not succeed
[281038:0x356da20]  2839590 ms: Mark-sweep 1361.2 (1448.4) -> 1350.2 (1450.4) MB, 1635.7 / 0.0 ms  (average mu = 0.338, current mu = 0.328) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x2e91eb35be1d]
Security context: 0x07bceab9e6e9 <JSObject>
    1: checkExportsOnMergedDeclarations(aka checkExportsOnMergedDeclarations) [0x2675fa4df1b9] [/home/gene/Scrivania/Work/G-Labs/Development/Repositories/github-genielabs/HomeGenie/src/homegenie-ui-app/node_modules/typescript/lib/typescript.js:~62666] [pc=0x2e91ecd27cad](this=0x354b6c0826f1 <undefined>,node=0x1b080f15c169 <NodeObject map = 0x6de42c47a09>)
  ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa0c0 node::Abort() [ng serve]
 2: 0x8fa10c  [ng serve]
 3: 0xb0026e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [ng serve]
 4: 0xb004a4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [ng serve]
 5: 0xef49b2  [ng serve]
 6: 0xef4ab8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [ng serve]
 7: 0xf00b92 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [ng serve]
 8: 0xf014c4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [ng serve]
 9: 0xf04131 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [ng serve]
10: 0xecd5b4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [ng serve]
11: 0x116d73e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [ng serve]
12: 0x2e91eb35be1d 
Annullato (core dump creato)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.0
Node: 10.16.3
OS: linux x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cdk                      10.0.0
@angular/cli                      10.0.0
@angular/flex-layout              10.0.0-beta.32
@angular/material                 10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

This is occurring on `Ubuntu 20.04 LTS`
<pre><code>Linux mobi-dev 5.4.0-37-generic angular/angular#41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux</code></pre>

**Comment by alan-agius4** [comment] 2020-06-29 17:31
Duplicate of #18034

**Closed by alan-agius4** 2020-06-29 17:31 UTC
