### ISSUE TITLE
material-moment-adapter doesn't work in build-angular@0.901

### ISSUE THREAD

**Issue by eun-choi** [angular/angular-cli#17396] opened 2020-04-06 02:29 UTC
# 🐞 Bug report
Class with @angular/material-moment-adapter not opening in production build @angular-devkit/build-angular@0.901.0 version.
It worked without problems until version @angular-devkit/build-angular@0.900.7

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Class with @angular/material-moment-adapter not opening in production build @angular-devkit/build-angular@0.901.0 version.
It worked without problems until version @angular-devkit/build-angular@0.900.7

## 🔬 Minimal Reproduction
**1) Update build-angular@0.901 and material-moment-adapter**
npm i @angular-devkit/build-angular@0.901.0 @angular/material@9.2.0 @angular/material-moment-adapter@9.2.0

**2) Import material-moment-adapter into the page.**
import { MAT_MOMENT_DATE_FORMATS, MomentDateAdapter, MAT_MOMENT_DATE_ADAPTER_OPTIONS } from '@angular/material-moment-adapter';
import { DateAdapter, MAT_DATE_FORMATS, MAT_DATE_LOCALE } from '@angular/material/core';

**3) Add providers to the page.**
@Component({
  providers: [
    { provide: MAT_DATE_LOCALE, useValue: 'en-US' },
    { provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE, MAT_MOMENT_DATE_ADAPTER_OPTIONS] },
    { provide: MAT_DATE_FORMATS, useValue: MAT_MOMENT_DATE_FORMATS }
  ]
})

**4) Production build**
ng build --prod

**5) After running the app, Page does not open.**

**6) Downgrade build-angular@0.900.7**
npm i @angular-devkit/build-angular@0.900.7

**7) Production build**

**8) After running the app, It runs without problems.**

## 🔥 Exception or Error
<pre><code>
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.0
Node: 10.18.1
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.900.7
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.2.0
@angular/fire                      5.4.2
@angular/material                  9.2.0
@angular/material-moment-adapter   9.2.0
@angular/pwa                       0.901.0
@ngtools/webpack                   9.0.7
@schematics/angular                9.1.0
@schematics/update                 0.901.0
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.41.2

</code></pre>

**Comment by alan-agius4** [comment] 2020-04-06 07:30
Duplicate of #17320

**Closed by alan-agius4** 2020-04-06 07:30 UTC
