### ISSUE TITLE
Incompatibility of @ngtools/webpack@1.2.6 with angular-cli@1.0.0-beta.26

### ISSUE THREAD

**Issue by darkkean** [angular/angular-cli#4352] opened 2017-02-02 11:32 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.26
node: 7.4.0
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/compiler-cli: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/platform-server: 2.4.5
@angular/router: 3.4.5
@ngtools/json-schema: 1.0.1
@ngtools/webpack: 1.2.4

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Yes

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/frontend-ng2/node_modules/typescript/lib/typescript.js:14546:109)
    at parseSourceFileWorker (/frontend-ng2/node_modules/typescript/lib/typescript.js:14478:26)
    at Object.parseSourceFile (/frontend-ng2/node_modules/typescript/lib/typescript.js:14427:26)
    at Object.createSourceFile (/frontend-ng2/node_modules/typescript/lib/typescript.js:14282:29)
    at WebpackCompilerHost.getSourceFile (/frontend-ng2/node_modules/@ngtools/webpack/src/compiler_host.js:293:27)
    at findSourceFile (/frontend-ng2/node_modules/typescript/lib/typescript.js:63447:29)
    at processSourceFile (/frontend-ng2/node_modules/typescript/lib/typescript.js:63378:27)
    at /frontend-ng2/node_modules/typescript/lib/typescript.js:63488:17
    at Object.forEach (/frontend-ng2/node_modules/typescript/lib/typescript.js:1293:30)
    at processReferencedFiles (/frontend-ng2/node_modules/typescript/lib/typescript.js:63486:16)
    at findSourceFile (/frontend-ng2/node_modules/typescript/lib/typescript.js:63471:21)
    at processSourceFile (/frontend-ng2/node_modules/typescript/lib/typescript.js:63378:27)
    at processRootFile (/frontend-ng2/node_modules/typescript/lib/typescript.js:63265:13)
    at /frontend-ng2/node_modules/typescript/lib/typescript.js:62614:60
    at Object.forEach (/frontend-ng2/node_modules/typescript/lib/typescript.js:1293:30)
    at Object.createProgram (/frontend-ng2/node_modules/typescript/lib/typescript.js:62614:16)
    at AotPlugin._setupOptions (/frontend-ng2/node_modules/@ngtools/webpack/src/plugin.js:161:28)
    at new AotPlugin (/frontend-ng2/node_modules/@ngtools/webpack/src/plugin.js:21:14)
    at Object.exports.getWebpackNonAotConfigPartial (/frontend-ng2/node_modules/angular-cli/models/webpack-build-typescript.js:25:13)
    at new NgCliWebpackConfig (/frontend-ng2/node_modules/angular-cli/models/webpack-config.js:41:46)
    at Class.run (/frontend-ng2/node_modules/angular-cli/tasks/serve-webpack.js:23:22)
    at /frontend-ng2/node_modules/angular-cli/commands/serve.run.js:37:22
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Mention any other details that might be useful.

My `package.json`'s dependencies are:
```
"dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/compiler-cli": "^2.4.3",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/platform-server": "^2.4.3",
    "@angular/router": "~3.4.0",
    "@ng-idle/core": "^2.0.0-beta.4",
    "@ng-idle/keepalive": "^2.0.0-beta.4",
    "core-js": "^2.4.1",
    "moment": "^2.13.0",
    "ng2-bootstrap": "^1.0.22",
    "ng2-device-detector": "^0.1.0",
    "numeral": "^2.0.4",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "typescript": "^2.0.10",
    "zone.js": "^0.7.4"
  },
```

In order to run a successful `ng serve`, I would need to explicitly set which version of **@ngtools/webpack** to download. So I downgraded it back to: 1.2.4.

```
"@ngtools/webpack": "1.2.4",
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by RicardoVaranda** [comment] 2017-02-02 11:35
This is an issue with a recent change in @ngtools/webpack

I would recommend if possible to update angular cli to the latest version with the following commands:

```
npm uninstall -g angular-cli
npm clear cache
npm install -g @angular/cli
```

Navigate to your project directory and do the following command:

```
ng init
```

**Comment by ryan-morris** [comment] 2017-02-02 22:12
@RicardoVaranda , I tried your suggestion and now am getting the below with `ng serve`

```
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/json3/lib/json3.js
Module parse failed: project_dir\node_modules\json3\lib\json3.js Parenthesized pattern (89:12)
You may need an appropriate loader to handle this file type.
|           if (stringifySupported) {
|             // A test function object with a custom `toJSON` method.
|             (value = function () {
|               return 1;
|             }).toJSON = value;
 @ ./~/sockjs-client/lib/main.js 7:12-28
 @ ./~/sockjs-client/lib/entry.js
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://localhost:4200/
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/@angular/common/src/facade/errors.js
Module parse failed: project_dir\node_modules\@angular\common\src\facade\errors.js Parenthesized pattern (60:32)
You may need an appropriate loader to handle this file type.
|          * @return {?}
|          */
|         set: function (value) { ((this._nativeError)).stack = value; },
|         enumerable: true,
|         configurable: true
 @ ./~/@angular/common/src/pipes/invalid_pipe_argument_error.js 13:0-45
 @ ./~/@angular/common/src/pipes/async_pipe.js
 @ ./~/@angular/common/src/pipes/index.js
 @ ./~/@angular/common/src/common.js
 @ ./~/@angular/common/index.js
 @ ./~/@ng-bootstrap/ng-bootstrap/accordion/accordion.module.js
 @ ./~/@ng-bootstrap/ng-bootstrap/index.js
 @ ./src/app/dashboard/dashboard.component.ts
 @ ./src/app/dashboard/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
```

**Comment by dsoltesz** [comment] 2017-02-02 23:26
I am getting the same type of parse errors now as well after updating

angular-cli: 1.0.0-beta.28.3
node: 6.9.5
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
@angular/flex-layout: 2.0.0-beta.4

**Comment by beeman** [comment] 2017-02-03 00:20
It's probably related to this issue, and the fix: https://github.com/angular/angular-cli/issues/4378#issuecomment-277127588

**Comment by AbbTek** [comment] 2017-02-03 00:31
In my case, I solved the problem updating my project and keeping "rxjs": "5.0.1" rather than "rxjs": "^5.0.3". Now the project is working again :D

**Comment by darkkean** [comment] 2017-02-03 10:37
Tried suggestions from @RicardoVaranda @beeman, but unfortunately still not working and getting the same exact error:

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
```

1. Run `rm -rf node_modules dist
1. Installed **angular-cli 1.0.0-beta.28.3** both project local and global
1. Run `ng update`
1. Installed **acorn@4.0.7** on project local

However none fixed the issue.

**Comment by RicardoVaranda** [comment] 2017-02-03 10:40
@darkkean Can you post your angular-cli.json please.

**Comment by grimner** [comment] 2017-02-03 12:20
@darkkean Please note this line in the first post: "@ngtools/webpack": "1.2.4", it solved the problem for me.

**Comment by beeman** [comment] 2017-02-03 15:42
@darkkean can you please try with the latest `@angular/cli@1.0.0.beta.30`, then and remove `node_modules` and `npm install` ?

If that does not work, can you share you `package.json`?

**Comment by bkdotcom** [comment] 2017-02-28 17:29
I'm attempting to migrate from the tour-of-heroes/system.js way of doing things to angular-cli. and stuck on `ng serve` 'TypeError: Cannot read property 'length' of undefined'
No idea if the error is on my end or with tooling

`ng --version` :

```
@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8
```

**Comment by filipesilva** [comment] 2017-03-09 10:59
Dupe of #4378.

**Closed by filipesilva** 2017-03-09 10:59 UTC
