### ISSUE TITLE
build fail when inlineCritical is enabled

### ISSUE THREAD

**Issue by vlio20** [angular/angular-cli#25429] opened 2023-06-23 06:29 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15

### Description

After upgrading to angular 16.1 I am getting an error:
`An unhandled exception occurred: document.documentElement.setAttribute is not a function
`

When digging into the stacktrace I see that the error is coming from:
```
[error] TypeError: document.documentElement.setAttribute is not a function
    at createDocument (<MY_PATH>/webapp/node_modules/critters/dist/critters.js:519:30)
```

### Minimal Reproduction

the command that i am runnig is:
```
ng build --configuration production
```

angular.json:
`"optimization": true,`

### Exception or Error

```text
[error] TypeError: document.documentElement.setAttribute is not a function
    at createDocument (<MY_PATH>/webapp/node_modules/critters/dist/critters.js:519:30)
```
```


### Your Environment

```
mac/ci (github actions)
```


### Anything else relevant?

when turning off `inlineCritical`

This setup works:
```
              "optimization": {
                "scripts": true,
                "styles": {
                  "minify": true,
                  "inlineCritical": false
                },
                "fonts": true
              },
```

**Comment by alan-agius4** [comment] 2023-06-23 08:06
Duplicate of https://github.com/angular/angular-cli/issues/25419

**Closed by alan-agius4** 2023-06-23 08:06 UTC
