### ISSUE TITLE
Initializers are not allowed in ambient contexts

### ISSUE THREAD

**Issue by carlosfaria94** [angular/angular-cli#5693] opened 2017-03-27 15:15 UTC
```
- [x] bug report
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.0.0
node: 6.10.0
os: darwin x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
```

### Repro steps.

After [migrating to 1.0](https://github.com/angular/angular-cli/wiki/stories-1.0-update) and doing `ng serve` I obtain the error: `Initializers are not allowed in ambient contexts.`

### The log given by the failure.

```
ERROR in /*/node_modules/@angular/core/src/errors.d.ts (9,33): Initializers are not allowed in ambient contexts.
/*/node_modules/@angular/core/src/errors.d.ts (10,43): Initializers are not allowed in ambient contexts.
/*/node_modules/@angular/core/src/errors.d.ts (11,42): Initializers are not allowed in ambient contexts.
/*/node_modules/@angular/core/src/errors.d.ts (12,43): Initializers are not allowed in ambient contexts.
/*/node_modules/@angular/core/src/errors.d.ts (13,35): Initializers are not allowed in ambient contexts.

ERROR in /*/node_modules/@angular/core/src/animation/dsl.d.ts (34,33): Initializers are not allowed in ambient contexts.

ERROR in /*/node_modules/@angular/core/src/animation/animation_metadata_wrapped.d.ts (12,33): Initializers are not allowed in ambient contexts.

ERROR in /*/node_modules/@angular/http/src/backends/browser_jsonp.d.ts (1,33): Initializers are not allowed in ambient contexts.

ERROR in /*/node_modules/@angular/router/src/shared.d.ts (15,37): Initializers are not allowed in ambient contexts.

ERROR in /*/node_modules/@angular/common/src/platform_id.d.ts (8,42): Initializers are not allowed in ambient contexts.
/*/node_modules/@angular/common/src/platform_id.d.ts (9,41): Initializers are not allowed in ambient contexts.
/*/node_modules/@angular/common/src/platform_id.d.ts (10,45): Initializers are not allowed in ambient contexts.
/*/node_modules/@angular/common/src/platform_id.d.ts (11,44): Initializers are not allowed in ambient contexts.

ERROR in /*/node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts (14,41): Initializers are not allowed in ambient contexts.

ERROR in /*/node_modules/@angular/forms/src/model.d.ts (6,28): Initializers are not allowed in ambient contexts.
/*/node_modules/@angular/forms/src/model.d.ts (10,30): Initializers are not allowed in ambient contexts.
/*/node_modules/@angular/forms/src/model.d.ts (15,30): Initializers are not allowed in ambient contexts.
/*/node_modules/@angular/forms/src/model.d.ts (20,31): Initializers are not allowed in ambient contexts.

ERROR in /*/node_modules/@angular/compiler/src/util.d.ts (8,36): Initializers are not allowed in ambient contexts.

ERROR in AppModule is not an NgModule
```

**Comment by aluanhaddad** [comment] 2017-03-27 16:42
Your TypeScript version is out of date. This is not a bug. Install the latest and if you get other errors, downgrade by point release until you get a working build.

**Comment by aluanhaddad** [comment] 2017-03-27 16:45
It's a good idea to just destroy your node_modules folder and just do a clean install.

**Comment by carlosfaria94** [comment] 2017-03-27 16:55
@aluanhaddad thanks for the feedback. I had already updated to the recent version (2.2.1), but I think I forgot to do a clean install.

Problem solved. Thanks.

**Comment by aluanhaddad** [comment] 2017-03-28 11:44
They should but, [from what I have read on the Angular blog](http://angularjs.blogspot.com/2017/03/angular-400-now-available.html), certain Angular features didn't work correctly correctly with TypeScript@2.2.1. I have not encountered any issues, and I have been running against the latest TypeScript  available, updating all major dependencies, including Angular and TypeScript within 2 days of a release on a production app using a continuous delivery model, with no issues.

Perhaps it works that scenario because the app does not use AOT.
AOT is a break from all standards. It deviates from the TypeScript specification, via `ngc`, in such a way that it violates the ECMAScript spec, meaning you are no longer writing standard or future standard compliant programs, you are writing Angular specific programs where syntax (decorators) has been redefined by `ngc` to mean something they never will in JS or TS.

AOT is a bad thing and it needs to die.

**Comment by carlosfaria94** [comment] 2017-03-28 15:10
Thanks for the insight @aluanhaddad .

**Comment by AbdelMonnem** [comment] 2017-04-08 15:34
still have the same problem. i have TS 2.2.2.

**Comment by aluanhaddad** [comment] 2017-04-09 00:44
@AbdelMonnem can you post the line that's raising the error?
The error experienced by the OP was likely caused by something like:
**some-dependency.d.ts**
```ts
export declare const value = 5;
```
This is illegal in TypeScript 2.0 but became legal in TypeScript 2.1 with the introduction of literal type inference for const declarations.

**Comment by hbsts** [comment] 2017-04-10 15:53
I tried to add material to a current project. Because I got some errors and I am new to Angular I started with a clean installation. I am using TS 2.2.2, but still have the above issue. 

I used the following commands to create the project:
ng new material // using latest angular-cli version
cd material
npm install --save @angular/material
npm install --save @angular/animations

I then added the following line to app.module.ts: 
import { MdButtonModule, MdCheckboxModule } from '@angular/material';

Executing"ng serve" I get a lot of errors, starting with the following one:
--> ERROR in C:/Code/material/node_modules/@angular/material/typings/core/overlay/scroll/scroll-dispatcher.d.ts (9,42): Initializers are not allowed in ambient contexts.

According to your getting-started.md I additionally added the following line to app.module.ts:
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
-->  A directory named @angular/platform-browser/animations does not exist in my node_modules directory. Even class BrowserAnimationsModule does not exist in any of the files in node_modules directory.

Have I missed anyting?

Best regards
Christian

**Comment by hbsts** [comment] 2017-04-10 16:34
I had the same error and fixed it by typing: 
npm install --save typescript@latest
package.json now has the latest ts version and ts compiler is 2.2.2. 

By the way: I used angular-cli to install a new angular based project. The version in package.json was something like 2.0.3.

**Comment by aluanhaddad** [comment] 2017-04-11 02:29
That is why I don't think people should rely on scaffolders. They are handy but it is a must to know how to do things from first principles like @hbsts did.

**Comment by AneelaBrister** [comment] 2017-04-13 18:46
I get an 'unmet peer dependency' for @angular/common@2.4.10, @angular/core@2.4.10, and @angular/http@2.4.10   when I try to install typescript@latest....
However, when I look at package.json, all three of those are at ^2.4.10. 
Any ideas? 

PS: I saw the same initializers error as the OP in the exact same situation.

**Comment by filipesilva** [comment] 2017-05-03 11:10
Closing as this doesn't seem to be an Angular CLI bug, but rather expected behaviour based on TypeScript versions.

@AneelaBrister Angular version 2 does not support the latest TS versions, you must stay in 2.1.x.

**Closed by filipesilva** 2017-05-03 11:10 UTC

**Comment by aluanhaddad** [comment] 2017-05-03 15:43
@filipesilva I don't know about the CLI, but I've ran npm:@angular/*@^2 against TypeScript dev builds that were well into typescript 2.3. Again, I don't use the CLI but it certainly works with the framework itself.

**Comment by janki7** [comment] 2017-05-19 09:32
I had same issue, clearing and re installing node_modules helped.

**Comment by binary2quantum** [comment] 2017-05-29 12:10
while i'm using typescript:2.0.3, 
it produces initializers are not allowed in ambient contexts.

the after upgrading to 2.1.4 
it produces cannot read property 'exclude' of undefined typescript in main.ts

pls someone help to fix this

**Comment by aluanhaddad** [comment] 2017-05-29 12:37
Why not use the latest stable TypeScript version? 2.1.4 is a fairly arbitrary place to start and it has been out of date for a while.

**Comment by dman777** [comment] 2017-05-31 06:04
This is so much why using a pre-processor language for Angular 2 and greater was a bad idea. Native JavaScript is always best. 

The Angular io docs for webpack, [specifically the package.json](https://angular.io/docs/ts/latest/guide/webpack.html#!#common-configuration), needs to be updated.

**Comment by aluanhaddad** [comment] 2017-06-01 16:46
@dman777 You are complaining about transpilers when you have adopted a monolithic framework and a framework specific CLI on top of that. Transpilers do not restrict you.

Consider, that TypeScript is by default perfectly happy to emit code irrespective of _any_ TypeScript errors including this one. These are tooling level errors, more like warnings, and thus non-blocking unless other tools get in the way (ex: `ngc`)

**Comment by dman777** [comment] 2017-06-01 16:56
Right now, you have production documentation that is wrong with breakage. The package.json needs to be fixed.  Any newcomer, as myself, will do the walk through the docs and hit this error. That should be of greater importance than anything else.

**Comment by JimTheMan** [comment] 2017-06-08 02:12
What TypeScript version works? What's the command to change it?

**Comment by aluanhaddad** [comment] 2017-06-08 19:02
Just use the latest `2.3.4`

**Comment by rbinsztock** [comment] 2017-06-15 10:41
I updated typescript to 2.3.4 but I still have the error `Initializers are not allowed in ambient contexts.` here the gist : https://gist.github.com/rbinsztock/1da21750458133a29f7bfe114ff02417

**Comment by CindySLiu** [comment] 2017-07-19 16:58
I still have this problem. I have the latest typescript 2.4.1. I deleted node_modules and reinstalled all the packages, but I still have the same error - Initializers are not allowed in ambient contexts. 

Here is my package.json:
{
  "name": "webapplication2",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "@types/node": "7.0.7",
    "angular-in-memory-web-api": "~0.3.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "typescript": "^2.4.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {}
}

Here is my tsconfig.json:
{
  "compilerOptions": {
    "target": "es6",
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es7", "dom" ],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  }
}

**Comment by CindySLiu** [comment] 2017-07-20 18:44
I solved my problem. It turns out VS2015 project file using TS2.0. After changed it to 2.2, the errors are gone.

**Comment by aluanhaddad** [comment] 2017-07-23 02:01
Use the latest 2.4.2. VS tools version 2.4. You can download the latest tools from www.typescriptlang.org

**Comment by arpitansu** [comment] 2019-07-20 08:35
for version 2.1.6 it throws error project requires version above 2.7.2 and after install 2.7.2 I get error ERROR in node_modules/@angular/core/core.d.ts(214,21): error TS1039: Initializers are not allowed in ambient contexts.

Fix this.
