### ISSUE TITLE
Disable webpack in dev env during ng build

### ISSUE THREAD

**Issue by iamkarlson** [angular/angular-cli#7461] opened 2017-08-22 06:13 UTC
- [x] feature request

### Versions.
```
angular-cli: 1.0.0-beta.28.3
node: 8.2.1
os: win32 x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/platform-server: 4.3.5
@angular/router: 4.3.5
@angular/compiler-cli: 4.3.5
```
Windows 10

### Repro steps.

1. ng build --output-path ./www/;
1. cordova run browser
1. change ts and recompile them
2. ouput of ng build is bundled in webpack and can't be updated with typescript compiler

### Desired functionality.
During debugging it will be helpful to disable packaging and preserve js files as is. Especially with typescript compileOnSave option

**Comment by hansl** [comment] 2017-08-22 17:00
Hi @iamkarlson,

I'm sorry, but I'm really failing to see what kind of setup you have or want. I assume you want the JS files from typescript? In that case you might prefer to run `tsc` or `ngc` directly. The CLI is a bundler and we have no intention currently of giving direct access to the intermediate steps.

Note that we do not support beta versions of the CLI, you'll need to update (the latest version is 1.3.1). Also, please provide with repro steps that include a setup step that we can use; either give us an existing open source project or explain how to recreate your setup.

I'm going to wait a few days for your reply, and if we hear nothing I'll close this issue. Thanks!

**Comment by iamkarlson** [comment] 2017-08-23 06:30
Hi @hansl 

I'm newbie with angular cli and didn't see that I'm using "beta". what I am talking about is to let me have in output folders my compiled js files without changing folder structure. 

for example, what I expected to have after 
```
ng build --output-path ./www/
```
is:
```
-src
--app
---services
----myService.ts
---components
----myComponent.ts
-www
--services
---myService.js
--components
---myComponent.js
```

**Comment by alan-agius4** [comment] 2018-08-23 15:51
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2018-08-23 15:51 UTC
Labels: need: more info, need: repro steps
