### ISSUE TITLE
Angular 14 is fine & but Angular  15 build fails when importing css in source code from node modules.

### ISSUE THREAD

**Issue by Danonlylane** [angular/angular-cli#26682] opened 2023-12-15 11:00 UTC
### Command

build, run, serve

### Description

When I upgraded from Angular 13 to Angular 14, There's been a mistake.

![cec49dd2-b10e-4e65-b82c-02c6a6c5dc3f](https://github.com/angular/angular-cli/assets/53202530/51afbbd5-9932-43c2-9db0-51b358a967d2)

I solved it in the following way
```js
// angular.json > projects > {project_name} > architect > build > options
  "styles": [
    "src/index.less",
    "src/styles.css",
    "node_modules/@cloudscope/core/ui/mask/mask.css", // add
    "node_modules/@cloudscope/core/ui/message/tips.css", // add
    "node_modules/@cloudscope/core/ui/regionTree/regionTree.css" // add
  ],
```
But when I upgraded to Angular 15, the problem reappeared. The styles configuration of my angular.json remains unchanged.
![4f9fa368-69fc-4da8-bfe2-12817ade797b1111](https://github.com/angular/angular-cli/assets/53202530/bffb5541-802f-45ce-a283-8b41cc175af8)

I wonder why Angular 14 can configure styles to solve this problem, but Angular 15 can't.
I also want to know how to solve this problem in Angular 15.
I appreciate your support very much.

### 🌍 Your Environment

Angular 14
```
Angular CLI: 14.2.13
Node: 18.16.0 (Unsupported)
Package Manager: npm 9.5.1 
OS: win32 x64

Angular: 14.3.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.13
@angular-devkit/build-angular   14.2.13
@angular-devkit/core            14.2.13
@angular-devkit/schematics      14.2.13
@angular/cdk                    13.3.9
@angular/cli                    14.2.13
@schematics/angular             14.2.13
rxjs                            6.6.7
typescript                      4.6.4
```

Angular 15
```
Angular CLI: 15.2.10
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 15.2.10
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.10
@angular-devkit/build-angular   15.2.10
@angular-devkit/core            15.2.10
@angular-devkit/schematics      15.2.10
@angular/cdk                    13.3.9
@schematics/angular             15.2.10
rxjs                            6.6.7
typescript                      4.9.5
```

**Comment by alan-agius4** [comment] 2023-12-15 11:04
A lot has changed since version 15, please update to version 17 and if the problem persists please provide a minimal reproduction. 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Danonlylane** [comment] 2023-12-15 11:35
> A lot has changed since version 15, please update to version 17 and if the problem persists please provide a minimal reproduction.
> 
> You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
> 
> This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

 I'll try to upgrade to 17. I'll let you know when the result is there.
Thank you very much for your reply

**Comment by JoostK** [comment] 2023-12-15 12:33
This occurs when CSS stylesheets are loaded from ESM, which is non-standard and not supported by the CLI.

**Comment by alan-agius4** [comment] 2023-12-15 12:36
@JoostK is right here. If CSS is imported in ESM modules this will fail with the above error. 

Closing as it is working as intentended.

**Closed by alan-agius4** 2023-12-15 12:36 UTC
Labels: needs: repro steps

**Comment by Danonlylane** [comment] 2023-12-15 13:02
> This occurs when CSS stylesheets are loaded from ESM, which is non-standard and not supported by the CLI.

Yes, it is precisely because of the reasons you mentioned that when I was in Angular14, I put the css file that caused compilation errors in angular.json to solve this problem. But this solution seems to be invalid in Angular15. This is exactly what I can't understand
```
// Solution
// angular.json > projects > {project_name} > architect > build > options
  "styles": [
    "src/index.less",
    "src/styles.css",
    "node_modules/@cloudscope/core/ui/mask/mask.css", // add
    "node_modules/@cloudscope/core/ui/message/tips.css", // add
    "node_modules/@cloudscope/core/ui/regionTree/regionTree.css" // add
  ],
```

**Comment by Danonlylane** [comment] 2023-12-15 13:10
> @JoostK is right here. If CSS is imported in ESM modules this will fail with the above error.
> 
> Closing as it is working as intended.

I remember what you said about these https://github.com/angular/angular-cli/issues/23273#issuecomment-1145831043, So I used the above method to solve it in Angular14, but this problem occurred again in Angular15. Do you have any good suggestions for this?
