### ISSUE TITLE
Use CLI to provide JSPM-like functionality?

### ISSUE THREAD

**Issue by robwormald** [angular/angular-cli#182] opened 2016-02-09 19:25 UTC
One of the reasons SystemJS has a lot of boilerplate is that it's really designed for a case where the `jspm` CLI is managing your `config.js` file automatically for you. When somebody uses regular NPM, they don't get this automatic config and thus there's a lot of manual mapping that has to be done, eg:

```js
System.config({
  map: {
    'angular2': 'node_modules/angular2',
   'my-super-awesome-lib' : 'node_modules/my-super-awesome-lib'
  },
  packages: {
   'my-super-awesome-lib': {
     'main': 'index.js'
   }
  }
})

```

This gets unwieldy fast and is super complicated if you don't know the System config API very well. It seems like this could be handled with our CLI, especially given the stuff you're doing with adding providers and stuff.

Thoughts?

**Comment by hansl** [comment] 2016-02-12 18:18
I'm working on a design doc for `ng install` that will cover this. We will get a simpler `System.config` for the user (and he can still customize it).

**Comment by timkindberg** [comment] 2016-02-29 02:38
Yes I'd say this issue is strongly related (if not a duplicate of) #124 and I also highly agree this needs to be a thing. +1

**Comment by khanhhua** [comment] 2016-03-15 18:57
+1 This is super urgent. It's likely we abandon that CLI if I have to manually config for SystemJS for every node_module package.

**Comment by zackarychapple** [comment] 2016-03-15 19:29
Giant +1 here too.

**Comment by hansl** [comment] 2016-03-17 20:40
@khanhhua: the tool is not even in Alpha and you shouldn't use this for any serious projects (yet).

The proposal is under way and we'll configure SystemJS properly once we're done with it.

See the design doc here: https://github.com/angular/angular-cli/pull/255

Closing this as a duplicate.

**Closed by hansl** 2016-03-17 20:40 UTC
