### ISSUE TITLE
Angular 10 taking so long to build 

### ISSUE THREAD

**Issue by makuzaverite** [angular/angular-cli#18854] opened 2020-09-23 10:10 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Performance issues with Angular CLI
Hello, I have an angular 10 code base but angular CLI takes so long to build I have tried to search what is causing the issue but nothing to seem to work. My laptop speed is just fine and what wrong?

### Describe the solution you'd like
Make angular CLI builds even more faster

**Comment by alan-agius4** [comment] 2020-09-23 10:43
Hi @makuzaverite,

Unfortunately without more information, and a reproduction it's hard for us to investigate this issue and determine a root cause.

In the meantime I'd like to understand what you are experiencing better, can you please answer the below?
- Can you also elaborate on what do you mean by taking long to build, are we talking 2mins, 5mins, 15mins etc?
- Is it slow on the first cold build or all builds?
- Has the speed regressed from previous versions?
- Can you provide the output of `ng version`?

**Comment by makuzaverite** [comment] 2020-09-23 11:09
- The build time takes 10+ mins
- It is slow on the first build
- No this is my new laptop I have installed angular few month ago

![angulargear](https://user-images.githubusercontent.com/53856673/94005097-080dbe80-fd9e-11ea-85cd-84133fdfc201.PNG)

**Comment by alan-agius4** [comment] 2020-09-23 11:26
Try to update to the latest stable version, this should help reduce the the time spent by NGCC to transform the packages. More context: https://github.com/angular/angular/pull/38840

```
ng update @angular/cli @angular/core
```

**Comment by alan-agius4** [comment] 2020-09-29 07:02
Closing as no further info provided.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2020-09-29 07:02 UTC
Labels: need: more info
