### ISSUE TITLE
ng serve not working when install latest version of angular cli

### ISSUE THREAD

**Issue by tedrob** [angular/angular-cli#4895] opened 2017-02-22 01:03 UTC
> Please provide us with the following information:
windows 10 

angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.26]
node: 6.9.5
os: win32 x64
@angular/cli: 1.0.0-beta.32.3

nothing just upgraded to the new version and started having all these problems
also I get this error also
can't find  @angular/platform-browser-dynamic
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment] 2017-02-22 01:04
@tedrob can you please enter the information requested in the template? It looks like you posted just the template without entering the details. Thanks!

**Comment by beeman** [comment] 2017-02-22 01:14
@tedrob can you try to remove node_modules from you project and run `npm install` again?

**Comment by tedrob** [comment] 2017-02-22 01:29
I removed node-modules and still get the error can't find from '@angular/platform-browser-dynamic';

**Comment by tedrob** [comment] 2017-02-22 01:31
also when I run ng serve I can't find Tried to find bootstrap code, but could not

**Comment by bdelaney** [comment] 2017-02-22 01:49
I upgraded from a project using CLI beta.26 to 32.3, following directions here to upgrade the cli.
At first running NG Serve produced a request to modify the cli json file:
"To migrate angular-cli.json follow the example below:" as per the Breaking changes note.
Which I did. Then ran ng serve again. That seemed to start the server, but with an error:
"ERROR in AppModule is not an NgModule"
And browsing to the localhost:4200 gives me: "Cannot GET /"
I then manually renamed angular-cli.json to begin with . as mentioned per 'code refactoring'
same problem
ng version output:
@angular/cli: 1.0.0-beta.32.3
node: 6.9.5
os: win32 x64
Windows 10

Created new project with ng new and then ran ng serve.
Works!

just sayin'

**Comment by beeman** [comment] 2017-02-22 01:49
What is the output of this:

```
npm ls @angular/platform-browser-dynamic
```

**Comment by tedrob** [comment] 2017-02-22 02:32
-- @angular/platform-browser-dynamic@2.4.8

**Comment by tedrob** [comment] 2017-02-22 02:40
now I get this error
ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (C:\aaa-angular2\foundation\ag2-tubes\node_modules\typescript\lib\typescript.js:8062:20)
    at Object.createCompilerHost (C:\aaa-angular2\foundation\ag2-tubes\node_modules\typescript\lib\typescript.js:44978:26)
    at Object.ngcLoader (C:\aaa-angular2\foundation\ag2-tubes\node_modules\@ngtools\webpack\src\loader.js:350:33)
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

**Comment by tedrob** [comment] 2017-02-22 03:21
I tried that and still get the same problem, but when you say you renamed angular-cli.json to begin with a . do you mean 
.angular-cli.json

or angular.cli.json

Which is it?

**Comment by tedrob** [comment] 2017-02-22 05:45
OK I renamed angular-cli.json to .angular-cli.json but still get this error
ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (C:\aaa-angular2\foundation\ag2-tubes\node_modules\typescript\lib\typescript.js:8062:20)
    at Object.createCompilerHost (C:\aaa-angular2\foundation\ag2-tubes\node_modules\typescript\lib\typescript.js:44978:26)
    at Object.ngcLoader (C:\aaa-angular2\foundation\ag2-tubes\node_modules\@ngtools\webpack\src\loader.js:350:33)
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

**Comment by bdelaney** [comment] 2017-02-22 11:26
@tedrob - sorry my comment came in as exact same time as @beeman.
I did not have a solution or good troubleshooting. Just figured that in my case (.26 -> 32.3), the new version has so many breaking changes that I may as well give up on the old project and have ngCLI build a new one, then transfer module code etc into that new project.
I apologize for confusing this thread.

I guess we cannot expect upgrade stability until we get to RC stage at least.

**Comment by dxxvi** [comment] 2017-02-22 15:28
I have some weird issues with
```
@angular/cli: 1.0.0-beta.32.3
node: 7.3.0
os: win32 ia32
npm 3.10.10
```
A new project created with ng new project-name runs fine in Firefox 52.0b7, but doesn't run in IE 11.0.9600.18537 and Chrome 43.0.2357.134 m which both show an error message "Unable to get property 'apply' of undefined or null reference" for this function
```
function combine(options) {
    return (_a = ((Object))).assign.apply(_a, [{}].concat(options));
    var _a;
}
``` 
IE says it's in vendor.bundle.js, Chrome says it's in intl.js.

**Comment by rahulroxx** [comment] 2017-02-24 17:46
Same Problem
need help 
```
Environment configuration does not contain "environmentSource" entry.

A new environmentSource entry replaces the previous source entry inside environments.

To migrate angular-cli.json follow the example below:

Before:

"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}


After:

"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}

```

**Comment by rahulroxx** [comment] 2017-02-24 17:47
ng serve is not serving old angular2 projects.

**Comment by beeman** [comment] 2017-02-24 17:47
@rahulroxx the suggested fix is printed there.

**Comment by rahulroxx** [comment] 2017-02-24 17:50
I did the same but throws new error as posted by @tedrob 

```
Module build failed: TypeError: Cannot read property 'newLine' of undefined
at Object.getNewLineCharacter (C:\aaa-angular2\foundation\ag2-tubes\node_modules\typescript\lib\typescript.js:8062:20)
at Object.createCompilerHost (C:\aaa-angular2\foundation\ag2-tubes\node_modules\typescript\lib\typescript.js:44978:26)
at Object.ngcLoader (C:\aaa-angular2\foundation\ag2-tubes\node_modules@ngtools\webpack\src\loader.js:350:33)
@ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
```

**Comment by beeman** [comment] 2017-02-24 19:57
Try these steps please:

### Clean up
- remove node_modules from your project
- remove any `angular-cli` and `@angular/cli` references from package.json if it's there
- Uninstall `angular-cli` and `@angular/cli` globally: `npm uninstall -g angular-cli @angular/cli`

### Reinstall
- Install `@angular/cli` globally: `npm install -g @angular/cli`
- Install `@angular/cli` in your project: `npm install --save-dev @angular/cli`

**Comment by svcastaneda** [comment] 2017-02-27 19:10
If @beeman's steps don't work, check which version of node you're using.

### Steps:
- `node -v` should be v6.9.0 or higher. If not, keep reading.
- Run `nvm ls`. The output should look something like this:
```
$ nvm ls
         v5.0.0
->       v5.9.0
         v6.9.5
         system
default -> node (-> v6.9.5)
node -> stable (-> v6.9.5) (default)
stable -> 6.9 (-> v6.9.5) (default)
iojs -> N/A (default)
```
- If v6.9 isn't installed, run `nvm install v6.9`
- Run `node -v` and check if it's now using **v6.9._**. If not, run `nvm use 6.9`

**Comment by gnomeontherun** [comment] 2017-03-01 17:26
I'm facing this same problem after upgrading from beta24, and followed each breaking change step in the changelog.

I uninstalled everything as @beeman suggested, and see the `newLine` error. 

```
@angular/cli: 1.0.0-rc.0
node: 6.9.2
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/compiler-cli: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-rc.0
```

Error

```
ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/.../node_modules/typescript/lib/typescript.js:9426:20)
    at Object.createCompilerHost (/.../node_modules/typescript/lib/typescript.js:62475:26)
    at Object.ngcLoader (/.../node_modules/@ngtools/webpack/src/loader.js:341:33)
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.
```

**Comment by khizerrehands** [comment] 2017-03-01 18:15
@beeman Can you help regarding this error ?

I have updated my angular-cli from 1.0.0-beta.28 (2017-02-01)   to 1.0.0-rc.0 (2017-02-25)

ERRORS DISPLAYING:

Environment configuration does not contain "environmentSource" entry.

A new environmentSource entry replaces the previous source entry inside environments.

To migrate angular-cli.json follow the example below:

Before:

"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}


After:

"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}

**Comment by gnomeontherun** [comment] 2017-03-01 23:14
@khizerrehands You need to follow the environments portion of the angular-cli.json file just like it mentions in the error. Replace the `environments` property with these two.

```
"environmentSource": "environments/environment.ts",
"environments": {
"dev": "environments/environment.ts",
"prod": "environments/environment.prod.ts"
}
```

**Comment by EdgarsZagorskis** [comment] 2017-03-02 16:47
I got this same `Cannot read property 'newLine' of undefined` thing with latest angular-cli (rc0). noticed it uses yarn during `ng new`. So i tried `rm -rf node_modules && npm cache clean && npm install` and that worked. 
Perhaps yarn is locked to some broken setup which is resolved by npm's dependency management?

**Comment by montella1507** [comment] 2017-03-02 17:15
Can you paste your package.json dependencies, guys?

**Comment by EdgarsZagorskis** [comment] 2017-03-02 17:59
In my case the root cause was using `-lc` argument. package.json in both cases is same, but if i do
`ng new foo` then ng can be served, but when i do
`ng new -lc foo` then ng can be served, but when it fails and only way to fix it is to remove node_modules and install again with `npm i` or `yarn`

a bit about me (if it may help):
yarn: 0.21.3
node: 7.7.1
angular-cli: 1.0.0-rc.0

**Comment by zatelnet** [comment] 2017-03-04 19:42
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>
in index.html may help

**Comment by neosoko** [comment] 2017-03-07 12:23
Hi,

Found the solution. If you the error above still persist then try this:

open angular-cli.json
find-
"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}

and replace with:
"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}

**Comment by amartinelli6577** [comment] 2017-03-07 21:51
Not sure if this helps anyone else with this issue or not. I was experiencing it and turned here looking for ideas. As I was scrolling through, I double-checked my package.json and discovered that I had the beta and rc versions of the cli installed. I removed the pointer to the beta version (angular-cli), deleted my node_modules and reran npm install. Fixed my issue.

**Comment by neosoko** [comment] 2017-03-08 06:59
Yeah, but i have uninstall angularCLI package and deleted node_module files then i reinstalled the angularCLI thereafter i just modified angular-cli.json as shown above then it worked.

**Comment by dherges** [comment] 2017-03-08 07:04
On a Windows 7, 64bit

```bash
rm -rf node_modules
npm install
ng serve
```

solved it. :rocket:

**Comment by enerone** [comment] 2017-03-12 17:44
**The steps to solve this:**

1. Upgrade your npm version (to 3 or +) (this was the little devil)
2. Uninstall angular-cli, 
3. Clean npm cache (npm clean cache)
4. Install Angular-cli again

Some dependencies can´t be installed with older npm versions, and you only get a warning ;) but angular-cli installs anyway.... without the dependencies

**Comment by filipesilva** [comment] 2017-03-13 18:53
This really looks like upgrade problems. We have an upgrade story you can follow to ensure upgrading is done right: https://github.com/angular/angular-cli/wiki/stories-rc-update

**Closed by filipesilva** 2017-03-13 18:53 UTC

**Comment by SEAN-LANOUE** [comment] 2017-03-14 15:13
angular-cli.json

WHERE is this file?   I cannot seem to find it!

**Comment by mairis79** [comment] 2017-04-02 00:37
i have tried all the above but still problem persista please help.

C:\Users\Manirish>npm start

> untitled1@0.0.0 start C:\Users\Manirish
> ng serve

Environment configuration does not contain "environmentSource" entry.

A new environmentSource entry replaces the previous source entry inside environments.

To migrate angular-cli.json follow the example below:

Before:

"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}


After:

"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! untitled1@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the untitled1@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the untitled1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs untitled1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls untitled1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Manirish\AppData\Roaming\npm-cache\_logs\2017-04-02T00_36_57_183Z-debug.log

C:\Users\Manirish>

**Comment by mairis79** [comment] 2017-04-02 00:41
i have tried all the above solutions still the problem persisits...please help...
Manirish@Mairish MINGW64 ~
$ cd angular2

Manirish@Mairish MINGW64 ~/angular2 (master)
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

Manirish@Mairish MINGW64 ~/angular2 (master)
$ npm start

> angular-quickstart@1.0.0 prestart C:\Users\Manirish\angular2
> npm run build


> angular-quickstart@1.0.0 build C:\Users\Manirish\angular2
> tsc -p src/

src/app/app.component.ts(8,3): error TS2345: Argument of type '{ moduleId: string; selector: string; templateUrl: string; directives: typeof NavbarComponent[]; }' is not assignable to parameter of type 'Component'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'Component'.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Manirish\AppData\Roaming\npm-cache\_logs\2017-04-02T00_39_20_189Z-debug.log

**Comment by gnomeontherun** [comment] 2017-04-02 19:25
@mairis79 Your error tells you exactly what to do. What happened is you have an older version of the CLI used to set up your project, and you have to update the `angular-cli.json` file as it describes.

----

Environment configuration does not contain "environmentSource" entry.

A new environmentSource entry replaces the previous source entry inside environments.

To migrate angular-cli.json follow the example below:

Before:

"environments": {
"source": "environments/environment.ts",
"dev": "environments/environment.ts",
"prod": "environments/environment.prod.ts"
}

After:

"environmentSource": "environments/environment.ts",
"environments": {
"dev": "environments/environment.ts",
"prod": "environments/environment.prod.ts"
}

**Comment by paulmc** [comment] 2017-04-03 12:37
I am having the same problem. I Downgraded my Node via nvm from the current stable version, I removed the node_modules and cleared the cache. I also removed the global @angular/cli and installed it again.

My angular-cli.json already has the 'After:' text:
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }

bash-3.2$ nvm ls
->       v6.9.5
         v7.8.0
         system
default -> v6.9.5
node -> stable (-> v7.8.0) (default)
stable -> 7.8 (-> v7.8.0) (default)
iojs -> N/A (default)
bash-3.2$ ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.5
os: darwin x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/compiler-cli: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/platform-server: 4.0.1
@angular/router: 4.0.1
@angular/tsc-wrapped: 4.0.1
@angular/upgrade: 4.0.1
@angular/animations: 4.0.1
@angular/cli: 1.0.0

**Comment by beeman** [comment] 2017-04-03 13:57
@paulmc it might make sense to open a new issue for that :)

**Comment by armc0** [comment] 2017-04-23 17:26
Keep together work for me

      "environmentSource": "environments/environment.ts",
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
}

**Comment by bootsoon** [comment] 2017-05-16 09:16
@dherges  It works for me. But why can it solve this ?

**Comment by iamhaseebiqbal** [comment] 2017-08-07 10:39
@neosoko Worked perfectly. Thanks mate.

**Comment by anupam42** [comment] 2017-08-09 05:46
@neosoko Thanks mate ur solution worked for me :+1:

**Comment by Hadh** [comment] 2017-08-21 10:16
I had the same issue, changing the configuration in `angular-cli.json` solved it, as it said : 
To migrate angular-cli.json follow the example below:

```
Before:

"environments": {
"source": "environments/environment.ts",
"dev": "environments/environment.ts",
"prod": "environments/environment.prod.ts"
}

After:

"environmentSource": "environments/environment.ts",
"environments": {
"dev": "environments/environment.ts",
"prod": "environments/environment.prod.ts"
}
```

**Comment by tedrob** [comment] 2018-06-12 23:20
I don't think that's the problem my problem seems that the node server which is server.js is not responding to an event from angular, on angular I have a post-event that is being a triggered, OK, it works, the problem is that when in production on a Heroku environment the node server isn't aware, the app runs when opened, but it tries to connect to my local server.js. Better said if I run node server.js on my local it works.  If node server.js on my local isn't running. I get options http://llocalhost:8080coins/add 0 (), and ERROR Unknow Error, can anyone help...

**Comment by SudhirKaushik** [comment] 2018-12-08 17:36
The problem is totally different Angular CLI workspace configuration scheme.

 For angular-cli 1.7.2 I had `.angular-cli.json` but for latest version like angular-cli 7, it is `angular.json` which can be found here : https://github.com/angular/angular-cli/wiki/angular-workspace

My suggestion, create a new project with angular-cli 7, and copy its angular.json to your project and run `npm install` to get latest angular-cli
