### ISSUE TITLE
ng new my-app causes This command can not be run inside of a CLI project.

### ISSUE THREAD

**Issue by javadev** [angular/angular-cli#10594] opened 2018-05-02 08:17 UTC
### Versions
```
Node v8.11.1
NPM 5.6.0
Windows 10 64 bit
```

### Repro steps
* install next version of @angular/cli@next
* Create new project with ng new my_project
* See error message

### Observed behavior
```
This command can not be run inside of a CLI project.
```

### Desired behavior

New project should be created.

**Comment by njl07** [comment] 2018-05-02 08:33
hy @javadev your issue is duplicate of #10590 I've reported this morning too

**Comment by javadev** [comment] 2018-05-02 08:44
How it is possible to release a new version of angular-cli and not test new project generation?

Build system should be improved.

**Comment by avatsaev** [comment] 2018-05-02 14:01
Seems to be fixed on master

**Comment by joseorihuela** [comment] 2018-05-02 14:26
Same issue here.

**Comment by joseorihuela** [comment] 2018-05-02 17:28
Works now, thanks!

**Closed** 2018-05-02 19:49 UTC
Labels: priority: 2 (required)

**Comment by KunalOjha** [comment] 2018-05-08 05:35
In the folder you are targeting, if there is a angular-cli.json file, remove it. Worked for me.

**Comment by pankajparkar** [comment] 2018-05-11 13:51
Update `@angular/cli` to latest version 6.0.1 and it started working.

**Comment by lksnmnn** [comment] 2018-06-12 08:32
Maybe we can change the error message to enable users to remove their leftover files without having to google it first...

**Comment by TakeshiDaveau** [comment] 2018-07-09 14:15
Why is it not allowed to create multiple app inside the same CLI project ?

**Comment by tekpartner** [comment] 2018-08-04 19:32
I'm working on a Mac. I tried looking for the files `.angular*` on the following directories:

`/Users/XXXX'
`/`

I couldn't find the files there. Where else am I supposed to look?

**Comment by Rhadamez** [comment] 2018-08-25 19:09
Still happening to me. Have tried to uninstall -g and install the lastest version, but did't work.

<h2>Versions</h2>

Angular CLI: 6.1.5
Node: 10.0.0
NPM: 6.4.0
Win 10 x64

Where are theses .angular* files?

**Comment by daham81** [comment] 2018-09-09 05:06
I am having lot of trouble with his error message. No .angular* files located in my home/root directories. 

Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.8.1
@angular/cdk                      6.4.7
@angular/cli                      6.2.1
@angular/material                 6.4.7
@ngtools/webpack                  6.1.5
@schematics/angular               0.8.1
@schematics/update                0.8.1
rxjs                              6.3.2
typescript                        2.7.2
webpack                           4.9.2

This is very disheartening.. especially since I am learning angular at the same time.

**Comment by arif7503** [comment] 2018-09-19 17:56
Try to run cmd as Administrator

**Comment by ryrobbo** [comment] 2018-09-26 09:17
I got around this issue by removing a stray **angular-cli.json** file from the folder path where I was trying to install a new Angular app.

I was attempting to install a new app in the directory: **/home/vagrant/projects/angular-app**

However, inside the **/home/vagrant/projects** directory was an **angular-cli.json** file that I kept for a backup. I renamed the file and put a '1' in front of the file name and was able to install successfully after that.
