### ISSUE TITLE
PeerDependencies requirements failure on beta.15

### ISSUE THREAD

**Issue by igorzg** [angular/angular-cli#2304] opened 2016-09-23 09:05 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. Ubuntu 14.04 server

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: linux x64

```
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer string-replace-loader@1.0.5 wants webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.3 wants webpack@^2.1.0-beta
```

**Comment by ValeryVS** [comment] 2016-09-23 10:59
Are you trying to run 'ng init'?
It is looks like you have local node_modules/.bin in your path.
Duplicate of #2179

**Comment by nathan-j-brenner** [comment] 2016-09-23 22:10
I've got this error on circleCI.  Everything seems to be working fine working from it locally, haven't changed anything yet in the project.  The build just fails on the CI. On my computer:

```
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: darwin x64
```

**Comment by JohannesRudolph** [comment] 2016-09-27 07:24
@nathan-j-brenner try running `ng test --watch false`, by default it will watch for changes and thus won't exit ;-)

**Comment by filipesilva** [comment] 2016-10-05 15:21
Duplicate of #2179 as the source cause.

**Closed by filipesilva** 2016-10-05 15:21 UTC
