### ISSUE TITLE
"Browserslist: caniuse-lite is outdated"

### ISSUE THREAD

**Issue by RichardMisiak** [angular/angular-cli#16594] opened 2020-01-08 14:49 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes and no, a dependency has been updated and @angular-devkit/build-angular hasn't caught up

### Description
A warning is printed when running `ng serve` 
```
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
```

## 🔬 Minimal Reproduction
```
npm install -g @angular/cli@latest
ng new example --routing=false --style=csss
cd example
ng serve 
```

## 🔥 Exception or Error
N/A

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.21
Node: 12.14.1
OS: win32 x64
Angular: 8.2.14
</code></pre>

**Anything else relevant?**
Generated package.json
```
{
  "name": "example",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.21",
    "@angular/cli": "~8.3.21",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

```

**Comment by alan-agius4** [comment] 2020-01-08 14:52
Duplicate of https://github.com/angular/angular-cli/issues/16560

**Closed by alan-agius4** 2020-01-08 14:52 UTC

**Comment by RichardMisiak** [comment] 2020-01-08 14:54
Ah, the original was closed so I couldn't find it
