### ISSUE TITLE
Angular cli doesn't work only on IE9

### ISSUE THREAD

**Issue by oxygenstar** [angular/angular-cli#8923] opened 2017-12-18 10:26 UTC
### Versions
```
@angular/cli: 1.3.1
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.3.1
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
```

### Repro steps
IE9
polyfills.ts:
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es7/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es7/array';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';

tsconfig.json:
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

### Observed behavior
```
Blank page.
console error:
Unhandled Promise rejection:Object doesn't support property or method 'apply'; Zone:<root>; Task:Promise.then; Value:TypeError: Object doesn't support property or method 'apply'undefined
```

### Desired behavior
Properly working page.

**Comment by filipesilva** [comment] 2017-12-21 14:01
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #6110. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-12-21 14:01 UTC
