### ISSUE TITLE
Test source maps are not working

### ISSUE THREAD

**Issue by danielsuter** [angular/angular-cli#6737] opened 2017-06-19 17:35 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.2
node: 6.9.1
os: win32 x64

### Repro steps.
1. ng new source-maps
2. Make a test failing (e.g. app.component.spec.ts expect a wrong title)
3. npm test
 

### The log given by the failure.
```
Chrome 58.0.3029 (Windows 10 0.0.0) AppComponent should have as title 'app' FAILED
        Expected 'app' to equal 'app2'.
            at Object.<anonymous> (http://localhost:9876/_karma_webpack_/main.bundle.js:89:27)
            at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2800:26)
            at AsyncTestZoneSpec.webpackJsonp.../../../../zone.js/dist/async-test.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:2643:39)
            at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:3406:39)
Chrome 58.0.3029 (Windows 10 0.0.0): Executed 2 of 3 (1 FAILED) (0 secs / 0.154 secs)
Chrome 58.0.3029 (Windows 10 0.0.0) AppComponent should have as title 'app' FAILED
        Expected 'app' to equal 'app2'.
            at Object.<anonymous> (http://localhost:9876/_karma_webpack_/main.bundle.js:89:27)
            at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2800:26)
            at AsyncTestZoneSpec.webpackJsonp.../../../../zone.js/dist/async-test.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:2643:39)
            at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:987Chrome 58.0.3029 (Windows 10 0.0.0): Executed 3 of 3 (1 FAILED) (0.204 secs / 0.191 secs)
```

### Desired functionality.
The output should show the line number of the typescript file instead of the bundle.

**Comment by filipesilva** [comment] 2017-06-26 12:50
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/6623. Please subscribe to that issue for future updates.

**Comment by danielsuter** [comment] 2017-06-27 09:18
@filipesilva The other issue is closed and it's only stated that there's a problem when debugging through docker. 
Imho this is not a duplicate or the other issue should be adjusted and reopened.

**Comment by filipesilva** [comment] 2017-06-28 13:16
The issue I linked wasn't about docker, it's mentioned in the last comment by another user and nowhere else.

@clydin's comment (https://github.com/angular/angular-cli/issues/6623#issuecomment-308471592) indicates what the problem was and provides a fix in https://github.com/angular/angular-cli/pull/6682. It should be in the latest release.

When using the latest release do you still experience this problem?

**Comment by filipesilva** [comment] 2017-06-29 13:39
https://github.com/angular/angular-cli/issues/6824 also reported the same in 1.1.3, will investigate.

**Comment by filipesilva** [comment] 2017-07-02 14:27
I pushed a fix in https://github.com/angular/angular-cli/pull/6862 that addresses part of the issue, restoring source maps test runs in the sources window:

![image](https://user-images.githubusercontent.com/4172079/27770669-c35921da-5f3a-11e7-8af8-db4f0a4b12c4.png)

I'm not sure that the other part of it, the error shown by the Karma console, is fixable though. I don't think that error uses sourcemaps, since it's a zone error. I tried using the `@angular/cli@1.0.0` and it didn't seem to work there either. If you have a version of the CLI that correctly shows that error, please let me know.

**Comment by filipesilva** [comment] 2017-07-03 18:13
The console error is being tracked in https://github.com/angular/angular-cli/issues/6737.

**Closed by filipesilva** 2017-07-03 18:13 UTC
Labels: effort2: medium (days), freq2: medium, priority: 1 (urgent), severity4: regression, type: bug

**Comment by madnaelo** [comment] 2017-10-24 18:34
This issue is related to that issue. That issue is related to another that issue, and that another that issue is closed as not an issue. Wow!! Bravo!!
