### ISSUE TITLE
Assets loading from scss files

### ISSUE THREAD

**Issue by destus90** [angular/angular-cli#20916] opened 2021-05-24 05:57 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11.x

### Description
There is an issue with loading images from component's scss files. After running `ng serve` command it shows 404 error for those images in the browser's console.

## 🔬 Minimal Reproduction
1. git clone https://github.com/destus90/ng12-assets-issue
2. npm i 
3.  ng serve

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.1
Node: 14.15.0
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-05-24 06:03
Duplicate of https://github.com/angular/angular-cli/issues/20882

**Closed by alan-agius4** 2021-05-24 06:03 UTC
