### ISSUE TITLE
Compile inline styles to the identified style format (SCSS, LESS, etc)

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#8470] opened 2017-11-13 22:22 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Angular CLI: 1.5.0
Node: 8.9.1
OS: darwin x64
macOS Sierra 10.12.6

### Repro steps.

1. run `ng new foo --styles scss`
2. create a component with inline styles
3. add scss styles to it
4. run `ng serve -o`

### The log given by the failure.
The style compile as CSS, even though we set them to be SCSS in the cli json file

### Desired functionality.
I would like to see angular transpile inline styles and external files styles using the identified selection.

### Mention any other details that might be useful.
The workaround is to move styles for SCSS to their own file, using the `styleUrls` metadata.

**Comment by hansl** [comment] 2017-11-13 23:58
Hi @johnpapa,

Inline styles will not be rendered with a special renderer, unfortunately. It is impossible for us to know which styles you want your inline style to be, and even so we don't have control over how inline styles are compiled; we do not resolve them like we do with external styles.

This is a limitation of the angular compiler itself.

I'm going to close this as working as intended.

Cheers!

**Closed by hansl** 2017-11-13 23:58 UTC

**Comment by johnpapa** [comment] 2017-11-14 00:07
I do not understand ... if the CLI knows it is SASS (aka scss), then how do we not know what to tell the compiler?

How are external file templates different? Is it because SASS just hits those extensions by default and the webpack compiler for sass, less, etc are always there?

**Comment by filipesilva** [comment] 2017-11-14 09:36
FYI there was a PR to do this (https://github.com/angular/angular-cli/pull/8145).

**Comment by hansl** [comment] 2017-11-30 01:02
> if the CLI knows it is SASS (aka scss)

We do by the file extension. For inline styles we don't. The PR referred by Filipe is a hack that creates fake files and refactor the component.
