### ISSUE TITLE
Angular 16 - esbuild - 404 on routes inside proxy.conf.json

### ISSUE THREAD

**Issue by whyboris** [angular/angular-cli#25150] opened 2023-05-05 15:43 UTC
### Which @angular/* package(s) are the source of the bug?

common, core, Don't known / other

### Is this a regression?

Yes

### Description

When `angular.json` has `esbuild` enabled (in `architect.build.builder`):
```
"builder": "@angular-devkit/build-angular:browser-esbuild",
```
The app, running locally, shows `404` in the _Network_ tab of Chrome Developer Tools on API call that is set up in the `proxy.conf.json`

```json
{
  "/authapi/*": {
    "target": "https://stage-api.forbes.com",
    "changeOrigin": true,
    "secure": true
  }
}
```
Locally the app runs on `https://one.forbes.com:4200/`  and my `hosts` file has this entry `127.0.0.1 one.forbes.com`

When running the same code but changing the `builder`:

```
"builder": "@angular-devkit/build-angular:browser",
```

Everything works as it did before ✅ (no 404, API call is made)

### Please provide a link to a minimal reproduction of the bug

n/a

### Please provide the exception or error you saw

```true
`404 Not Found` in Chrome's _Network_ tab when clicking on the API call that was supposed to work.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0
Node: 18.12.1
Package Manager: npm 9.6.6
OS: darwin arm64

Angular: 16.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@angular/material               14.2.7
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      5.0.4
```

### Anything else?

I'm sorry I'm unsure if there is anything else that could be affecting the outcome I'm seeing. I'm happy to provide more information 🙇

**Comment by alan-agius4** [comment] 2023-05-05 16:12
Duplicate of https://github.com/angular/angular-cli/issues/25148

**Closed by alan-agius4** 2023-05-05 16:12 UTC

**Comment by whyboris** [comment] 2023-05-05 16:41
🙇  thank you for identifying the duplicate.

The response in the linked _Issue_ there is [a solution](https://github.com/angular/angular-cli/issues/25148#issuecomment-1536319136): removing the `*` at the end of the url in the `proxy.json` ✅
