### ISSUE TITLE
How to edit includePaths for saas with angular cli 1.0.0-beta.22-1?

### ISSUE THREAD

**Issue by sergamers** [angular/angular-cli#3667] opened 2016-12-21 06:59 UTC
For exapmle: I need include styles/_variable into app/header/header.component.scss and write 
@import '../../styles/variable ';
but i want write @import 'variable ';

**Comment by grizzm0** [comment] 2016-12-21 14:39
This is currently not supported. There is an open PR to fix this here #2747.

**Comment by filipesilva** [comment] 2016-12-30 16:27
Dupe of https://github.com/angular/angular-cli/issues/1791, being worked on in #2747 as @grizzm0 mentioned.

**Closed by filipesilva** 2016-12-30 16:27 UTC
