### ISSUE TITLE
ng serve can run and can see the page but just showing "Loading..."

### ISSUE THREAD

**Issue by Kilims** [angular/angular-cli#5267] opened 2017-03-07 08:53 UTC
> After running the command on your usage it can run smoothly and finnally shows 

<code>webpack: Compiled successfully</code>

>But when go to http://localhost:4200 it just shows "Loading..." and after press F12 on Firefox, it shows

<code>TypeError: (intermediate value).assign is undefined</code>
<code>	

return (_a = ((Object))).assign.apply(_a, [{}].concat(options));

vendor.bundle.js (line 43865)

</code>

### OS?
> Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-rc.1
node: 6.10.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Created using the CLI and havent changed a word

### The log given by the failure.
> Normally this include a stack trace and some more information.
The log didnt show failure info but just shows error on the page.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by RicardoVaranda** [comment] 2017-03-07 15:16
Hi @Kilims ,
Could you please provide us with repro steps for this issue as it will help us to make a better assumption of what the error might be. It looks like its an application error rather than a cli error.

**Comment by PriyankaKadam001** [comment] 2017-03-08 04:56
I am facing same challenge 
 webpack: Compiled successfully 
When I will go to -http://localhost:4200
it is showing error: **Uncaught TypeError: Cannot read property 'apply' of undefined**(Chrome)

OS?
Windows 7

Versions

@angular/cli: 1.0.0-rc.1
node: 7.7.1
os: win32 x64

App was created using ng new, compiling successfully and giving error on this address http://localhost:4200

**Comment by RicardoVaranda** [comment] 2017-03-08 09:18
@PriyankaKadam001 do you get this error on a fresh project without any changes to the code?

I.E using:
```
ng new testError
ng serve
```

**Comment by PriyankaKadam001** [comment] 2017-03-08 09:40
True, I am not making any changes, using fresh app and in IE, there is no error in console just giving "Loading..." message.

**Comment by RicardoVaranda** [comment] 2017-03-08 10:38
What version of IE are you using? You may have to add the polyfills for IE.

**Comment by PriyankaKadam001** [comment] 2017-03-09 04:31
Using IE11

**Comment by PriyankaKadam001** [comment] 2017-03-09 04:51
Yes after adding polyfills.js I am getting same error in IE. PFA
![capture](https://cloud.githubusercontent.com/assets/13555658/23736417/167af304-04b2-11e7-882b-89a576bfc309.PNG)

**Comment by lhoest** [comment] 2017-03-10 09:52
I have exactly the same issue as Kilims, and i have it even when creating a new app with @angular/cli from scratch . I found out that Internet Explorer and Firefox show exactly the same error in vendor.bundle.js (line 43865). Only Google Chrome does NOT show the error.

Reproduction steps (i have windows 7):
1. Complete Deinstallation of node, npm and npm packages exactly as recommended in http://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows
2. Installation of node, npm and ng exactly as recommended in https://angular.io/docs/ts/latest/cli-quickstart.html
3. Creating new project and starting testserver:
ng new my-app
cd my-app
ng serve --open

Chrome shows testpage correctly. IE and Firefox show only "Loading..." on blank page. Error consoles of both show javascript error in line 43865 of vendor.bundle.js.

Version information:
@angular/cli: 1.0.0-rc.1
node: 6.10.0
npm: 3.10.10
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1

What could be causing this?

**Comment by PriyankaKadam001** [comment] 2017-03-10 10:00
Got solution. 
Got to **src/polyfills.js** in your package and uncomment sections below-
 /** IE9, IE10 and IE11 requires all of the following polyfills. **/

**Comment by lhoest** [comment] 2017-03-10 11:24
@PriyankaKadam001 Thank you for sharing this. Unfortunately we have to support these elder browsers too.

I found out that it is **not** only a problem in development. Even when webapplication is created from scratch (as explained above) and built for production with tree shaking and uglification with
ng build --prod
same error shows for IE and FF, of course in different line (751). 

Our application needs full support for IE10-11 at least and for firefox. 

Since these Browsers are officially supported by Angular and regularly tested according to https://angular.io/docs/ts/latest/guide/browser-support.html, the problem should not occur.

Installation steps for node&npm and @angular/cli showed no errors or warnings.

**Comment by filipesilva** [comment] 2017-03-17 19:52
Closing as answered, thanks @PriyankaKadam001 !

**Closed by filipesilva** 2017-03-17 19:52 UTC

**Comment by JafferyTech** [comment] 2019-04-27 04:00
Am using firefox as my default browser . But when I run the*ng serve for Angular project its continuously loading the project .but can not seen any output on browser and not show console .its not allow me to right click and go to the console to see error..Help me to fix this issue.
