### ISSUE TITLE
hostReportError with 6.0.0-rc.4 when creating a new project

### ISSUE THREAD

**Issue by agoncal** [angular/angular-cli#10336] opened 2018-04-14 12:41 UTC
### Versions

I first installed Angular CLI 6.0.0-rc.4 with Yarn and got the following output mentionning errors
```
$ yarn global add @angular/cli@6.0.0-rc.4

$ ng --version
    
Angular CLI: 6.0.0-rc.4
Node: 9.11.1
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    <error>
@angular-devkit/core         <error>
@angular-devkit/schematics   <error>
@schematics/angular          <error>
@schematics/update           <error>
rxjs                         <error>
```

So I removed it (`yarn global remove @angular/cli`) and reinstalled Angular CLI 6.0.0-rc.4 with NPM and didn't get the errors

```
$ npm install -g @angular/cli@6.0.0-rc.4

$ ng --version

Angular CLI: 6.0.0-rc.4
Node: 9.11.1
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.5.6
@angular-devkit/core         0.5.6
@angular-devkit/schematics   0.5.6
@ngtools/json-schema         1.1.0
@schematics/angular          0.5.6
@schematics/update           0.5.6
rxjs                         6.0.0-uncanny-rc.7
typescript                   2.7.2
```

### Repro steps

But on both scenarios, when I create a new project (`ng new store`) I get a `hostReportError` (see below). I've also tried with 6.0.0-rc.2 and 6.0.0-rc.2 and got the same issue.

### Observed behavior

```
$ ng new store

CREATE store/README.md (1027 bytes)
CREATE store/angular.json (3846 bytes)
CREATE store/package.json (1394 bytes)
CREATE store/tsconfig.json (384 bytes)
CREATE store/tslint.json (2805 bytes)
CREATE store/.editorconfig (245 bytes)
CREATE store/.gitignore (503 bytes)
CREATE store/src/environments/environment.prod.ts (51 bytes)
CREATE store/src/environments/environment.ts (743 bytes)
CREATE store/src/favicon.ico (5430 bytes)
CREATE store/src/index.html (292 bytes)
CREATE store/src/main.ts (370 bytes)
CREATE store/src/polyfills.ts (3114 bytes)
CREATE store/src/test.ts (642 bytes)
CREATE store/src/assets/.gitkeep (0 bytes)
CREATE store/src/styles.css (80 bytes)
CREATE store/src/browserslist (51 bytes)
CREATE store/src/karma.conf.js (1011 bytes)
CREATE store/src/tsconfig.app.json (194 bytes)
CREATE store/src/tsconfig.spec.json (282 bytes)
CREATE store/src/tslint.json (314 bytes)
CREATE store/src/app/app.module.ts (314 bytes)
CREATE store/src/app/app.component.css (0 bytes)
CREATE store/src/app/app.component.html (1141 bytes)
CREATE store/src/app/app.component.spec.ts (986 bytes)
CREATE store/src/app/app.component.ts (207 bytes)
CREATE store/e2e/protractor.conf.js (752 bytes)
CREATE store/e2e/src/app.e2e-spec.ts (299 bytes)
CREATE store/e2e/src/app.po.ts (208 bytes)
CREATE store/e2e/tsconfig.e2e.json (213 bytes)
/Users/agoncal/.npm-packages/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/hostReportError.js:9
    setTimeout(function () { throw err; });
                             ^

TypeError: You provided 'function reduceOperatorFunction(source) {
        return pipe_1.pipe(scan_1.scan(function (acc, value, index) {
            return accumulator(acc, value, index + 1);
        }), takeLast_1.takeLast(1))(source);
    }' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.exports.subscribeTo (/Users/agoncal/.npm-packages/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:42:15)
    at Object.subscribeToResult (/Users/agoncal/.npm-packages/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:26)
    at MergeMapSubscriber._innerSub (/Users/agoncal/.npm-packages/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/Users/agoncal/.npm-packages/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/Users/agoncal/.npm-packages/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.notifyComplete (/Users/agoncal/.npm-packages/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:148:18)
    at InnerSubscriber._complete (/Users/agoncal/.npm-packages/lib/node_modules/@angular/cli/node_modules/rxjs/internal/InnerSubscriber.js:37:21)
    at InnerSubscriber.Subscriber.complete (/Users/agoncal/.npm-packages/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:128:18)
    at Observable.rxjs_1.concat.rxjs_1.concat.rxjs_1.Observable.obs [as _subscribe] (/Users/agoncal/.npm-packages/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/workflow/node-workflow.js:113:17)
    at Observable.subscribe (/Users/agoncal/.npm-packages/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:162:69)
```

### Mention any other details that might be useful (optional)

Don't know if this could be related to issue #10335 (different OS: Windows vs OSX). In this issue, when installing RC4 @KiraiChang got

```
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.5.6
@angular-devkit/build-angular   0.5.6
@angular-devkit/core            0.5.6 (cli-only)
@angular-devkit/schematics      0.5.6 (cli-only)
@angular/cli                    6.0.0-rc.4
@ngtools/json-schema            1.2.0
@schematics/angular             0.5.6 (cli-only)
@schematics/update              0.5.6
rxjs                            5.5.6
typescript                      2.5.3
```

While I have

```
Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.5.6
@angular-devkit/core         0.5.6
@angular-devkit/schematics   0.5.6
@ngtools/json-schema         1.1.0
@schematics/angular          0.5.6
@schematics/update           0.5.6
rxjs                         6.0.0-uncanny-rc.7
typescript                   2.7.2
```

Which is using `rxjs@5.5.6` and not `rxjs@6.0.0-uncanny-rc.7`

**Comment by HitomiTenshi** [comment] 2018-04-14 13:36
I got the same error when running `ng generate application <name>`.

- Windows 10 x64
- NodeJS 9.11.1
- npm 5.8.0
- angular-cli 6.0.0-rc.4

**Comment by daBishMan** [comment] 2018-04-14 18:51
I believe this is might be related to rxjs 6.0.0-uncanny-rc.7.

**Comment by avatsaev** [comment] 2018-04-14 22:26
Can confirm having the exact same error

**Comment by kyosho-** [comment] 2018-04-15 00:32
I got same error message too on `ng new xxx`.

- Windows 10 x64
- node v8.11.1
- npm 5.8.0
- angular-cli 6.0.0-rc.4

**Comment by sandangel** [comment] 2018-04-15 12:00
Got same error on `ng g universal`
macOS HS
node 8.11.1
cli 6 rc4
rxjs uncanny rc7

**Comment by filipesilva** [comment] 2018-04-16 09:30
Heya, because of the error (I think this `TypeError: You provided 'function reduceOperatorFunction`) and the timing (both 2 days ago) I think this is the exact same problem as #10335.

I'm closing this as duplicate of #10335, but will make a note of the findings in this issue.

**Closed by filipesilva** 2018-04-16 09:30 UTC
