### ISSUE TITLE
Regression: Cannot execute 'ng g library' with Angular CLI 10.1.0 : Cannot read property 'paths' of undefined

### ISSUE THREAD

**Issue by bjornharvold** [angular/angular-cli#18747] opened 2020-09-10 06:42 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [X] generate

### Is this a regression?
Yes. This works fine in my large mono repo with Angular CLI 10.0.8.

### Description
This error does NOT show up when creating a completely new project with ng new using the Angular CLI 10.1.0. I'm working with a 100+ module mono repo and it shows up there. We've never had this type of error. Would be great to know what's changed in the CLI since 10.0.8. I couldn't find anything in the change log. All our modules are upgraded to use the new way of tsconfig: tsconfig.base.json, tsconfig.app.json and tsconfig.json. 

## 🔬 Minimal Reproduction
Try to create a new library with
`ng g library`

## 🔥 Exception or Error
<pre><code>
Cannot read property 'paths' of undefined
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.0
Node: 12.18.3
OS: darwin x64

Angular: 10.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@angular/cli                      10.1.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.3
typescript                        4.0.2
webpack                           4.44.1
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-09-10 06:54
Duplicate of https://github.com/angular/angular-cli/issues/18709

**Closed by alan-agius4** 2020-09-10 06:54 UTC

**Comment by bjornharvold** [comment] 2020-09-10 09:03
Hi @alan-agius4 

I don't understand what I should do here. Both my project version and global version is 10.1.0. I don't understand what solution was provided in #18709

**Comment by bjornharvold** [comment] 2020-09-10 09:22
Nevermind. The trick is to run ng update @angular/cli and not do it manually. I can see tsconfig.base.json was removed and all projects are now extending tsconfig.json instead.

This was not mentioned in the release notes so figured a manual update was OK.
