### ISSUE TITLE
App built with ATO on CLI 22 are way heavier than those on CLI 21

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular-cli#3506] opened 2016-12-10 11:43 UTC
### Issue
> Built app size jump from 213 to 451kB after updating to angular-cli-22-1.
JS bundle now seems to be split in 2 files. 
![image](https://cloud.githubusercontent.com/assets/7990765/21073082/0b6236b6-bed6-11e6-8977-8759e3f78fb4.png)
Did I do something wrong ?

### OS?
> Windows 10

### Versions.
> 1.0.0-beta.22-1

### Repro steps.
> Build add with: ng build -p --aot

**Comment by ogix** [comment] 2016-12-10 12:00
Try to provide --no-vendor-chunk flag

**Comment by Ploppy3** [comment] 2016-12-10 12:23
@ogix this flag merges the main and vendor bundle without affecting the final size.

**Comment by filipesilva** [comment] 2016-12-12 14:46
Dupe of https://github.com/angular/angular-cli/issues/3368

**Closed by filipesilva** 2016-12-12 14:46 UTC
