### ISSUE TITLE
ng build --prod fail jszip

### ISSUE THREAD

**Issue by kodermax** [angular/angular-cli#9933] opened 2018-03-11 14:49 UTC
### Versions
```
Angular CLI: 6.0.0-beta.5
Node: 9.8.0
OS: win32 x64
Angular: 6.0.0-beta.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 6.0.0-beta.4
@angular/cli: 6.0.0-beta.5
@angular/material: 6.0.0-beta.4
@angular-devkit/build-optimizer: 0.4.5
@angular-devkit/core: 0.4.5
@angular-devkit/schematics: 0.4.5
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.5
@schematics/angular: 0.4.5
@schematics/package-update: 0.4.5
typescript: 2.6.2
webpack: 4.0.1
```

### Repro steps

* Step 1. ng build --prod
* Step 2. ng build
* Step 3

### Observed behavior
```
ng build --prod
 10% building modules 3/3 modules 0 active(node:5104) DeprecationWarning: Tapable.plugin is deprecated. Use neDate: 2018-03-11T14:43:37.285ZHash: 729e3e040a083551d150
Time: 26857ms
chunk {main} main.js, main.js.map (main) 132 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 224 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.09 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 20.8 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 645 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 17.2 MB [initial] [rendered]

ERROR in ./node_modules/jszip/lib/readable-stream-browser.js
Module not found: Error: Can't resolve 'stream' in 'C:\Projects\docs\ui\node_modules\jszip\lib'
```

### Mention any other details that might be useful (optional)
```json
{
  "name": "ui",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --port 4200n",
    "build": "ng build --prod && npm run build:after",
    "build:after": "node after-build.js",
    "test": "ng test",
    "test-ci": "ng test --single-run --watch=false",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "e2e-ci": "ng e2e --watch=false"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "6.0.0-beta.7",
    "@angular/cdk": "6.0.0-beta.4",
    "@angular/common": "6.0.0-beta.7",
    "@angular/compiler": "6.0.0-beta.7",
    "@angular/core": "6.0.0-beta.7",
    "@angular/forms": "6.0.0-beta.7",
    "@angular/http": "6.0.0-beta.7",
    "@angular/material": "6.0.0-beta.4",
    "@angular/platform-browser": "6.0.0-beta.7",
    "@angular/platform-browser-dynamic": "6.0.0-beta.7",
    "@angular/router": "6.0.0-beta.7",
    "@auth0/angular-jwt": "^1.0.0",
    "@types/hammerjs": "^2.0.35",
    "@types/jszip": "^3.1.3",
    "core-js": "^2.5.3",
    "devextreme": "^18.1.1-pre-18064",
    "devextreme-angular": "18.1.1-beta.2",
    "es6-shim": "^0.35.3",
    "file-saver": "^1.3.3",
    "hammerjs": "^2.0.8",
    "jszip": "3.1.3",
    "ng2-file-upload": "^1.3.0",
    "node-fetch": "^2.1.1",
    "nuxeo": "^3.6.0",
    "readable-stream": "^2.3.5",
    "rxjs": "^5.5.6",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "6.0.0-beta.5",
    "@angular/compiler-cli": "6.0.0-beta.7",
    "@angular/language-service": "6.0.0-beta.7",
    "@types/file-saver": "^1.3.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^9.4.6",
    "codelyzer": "^4.2.1",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.4.1",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "2.6.2"
  }
}

```

**Comment by Brocco** [comment] 2018-03-12 21:45
This is a known issue and will be resolved, see this [comment](https://github.com/angular/angular-cli/issues/9914#issuecomment-371894801).

Duplicate of #9914

**Closed by Brocco** 2018-03-12 21:45 UTC

**Comment by xfh** [comment] 2018-05-04 15:42
@Brocco I don't see how this is Related to #9914 

I think it is duplicated by #10625 though.
