### ISSUE TITLE
require html stopped working in upgrade to angular 9

### ISSUE THREAD

**Issue by dionisoros** [angular/angular-cli#16999] opened 2020-02-17 17:01 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.x

### Description

Hybrid application angular9 & angularJS 1.7. When trying to require an html file (in the angularJS app) using **@angular/cli 9** it fails, it works in angular 7.

## 🔥 Exception or Error
<pre><code>

ERROR in ./src/app/template.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to handle this file type.
</code></pre>

## 🌍 Your Environment
<pre><code>

    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.6
Node: 13.0.1
OS: linux x64
Angular: 9.0.0-next.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.6
@angular-devkit/build-angular     0.803.6
@angular-devkit/build-optimizer   0.803.6
@angular-devkit/build-webpack     0.803.6
@angular-devkit/core              8.3.6
@angular-devkit/schematics        8.3.6
@angular/cli                      8.3.6
@angular/localize                 9.0.0-next.5
@angular/upgrade                  8.2.14
@ngtools/webpack                  8.3.6
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

This is important for me because I want to upgrade an angularJS (1.7) app to angular 9 and my angularJS app is using the syntax like **require(file.html)**.

**Comment by alan-agius4** [comment] 2020-02-18 06:39
Duplicate of https://github.com/angular/angular-cli/issues/14855#issuecomment-510592634

**Closed by alan-agius4** 2020-02-18 06:39 UTC

**Comment by dionisoros** [comment] 2020-02-18 07:40
@alan-agius4 Can you please tell me which is the best way to fix this problem? Upgrading to angular 7 (instead of 9) OR using **html-loader** (or raw-loader) that worked for me....

**Comment by alan-agius4** [comment] 2020-02-18 09:13
@dionisoros, I recommend to update and extend the webpack configuration to include a loader that handles html.
