### ISSUE TITLE
Angular Cli 1.0.0-beta.11-webpack.8: ng build failed if route 'loadChildren'

### ISSUE THREAD

**Issue by cuiliang** [angular/angular-cli#1891] opened 2016-08-30 08:31 UTC
https://github.com/angular/angular-cli/blob/master/addon/ng2/models/find-lazy-modules.ts#L38

```
.map((node: ts.PropertyAssignment) => {
        return JSON.parse(node.initializer.getText(source)); // tslint:disable-line
      });
```

JSON.parse failed with ：
```
loadChildren:'app/+workspace/+settings/settings.module#SettingsModule'
```

**Comment by mjolk** [comment] 2016-08-30 13:47
"Unexpected token ' in JSON at position 0". :)

**Comment by LibertyBeta** [comment] 2016-08-30 15:18
Can confirm and reproduce. Moving to ` ` ` removes the error, but causes routing to fail.

**Comment by monojack** [comment] 2016-08-31 14:46
Do lazy modules work with a `system.js` build?

**Comment by cuiliang** [comment] 2016-08-31 14:48
@monojack yes, works before update to angular-cli@webpack

**Comment by shaun-mason** [comment] 2016-08-31 19:26
Same same.

> angular-cli: 1.0.0-beta.11-webpack.8
> node: 6.4.0
> os: win32 x64

**Comment by splintercode** [comment] 2016-09-01 20:25
I believe the latest webpack branch ( beta.11-webpack.8 ) does not currently support lazy loaded modules yet.

**Comment by shaun-mason** [comment] 2016-09-01 20:30
> I believe the latest webpack branch ( beta.11-webpack.8 ) does not currently support lazy loaded modules yet.

You are correct in a way.  RC5 apparently uses System.js to do the lazy loading, since the CLI moved to Webpack that method is unavailabled.   It looks like the RC2 router and RC6 resolve the issue.  Unfortunately for me, the Angular 2 Material team is a bit out of sync, so I can't upgrade to RC6 yet.  

I worked around it and implemented a basic async module loader for the time being.

**Closed** 2016-09-06 04:03 UTC
