### ISSUE TITLE
Library docs say to build lib --prod but it fails.

### ISSUE THREAD

**Issue by escalonn** [angular/angular-cli#12333] opened 2018-09-20 21:54 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [x] doc
```

### Versions
```
$ node --version
v8.11.2
```
```
npm --version
6.4.1
```
```
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.2.3
Node: 8.11.2
OS: win32 x64
Angular: 6.1.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.3
@angular-devkit/build-angular      0.8.3
@angular-devkit/build-ng-packagr   0.8.3
@angular-devkit/build-optimizer    0.8.3
@angular-devkit/build-webpack      0.8.3
@angular-devkit/core               0.8.3
@angular-devkit/schematics         0.8.3
@angular/cli                       6.2.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.3
@schematics/angular                0.8.3
@schematics/update                 0.8.3
ng-packagr                         4.2.0
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.19.1
```
Windows 10.

### Repro steps
1. `ng new my-app`
1. `cd my-app`
1. `ng generate library my-lib`
1. `ng build my-lib --prod`

### The log given by the failure
```
Configuration 'production' could not be found in project 'my-lib'.
Error: Configuration 'production' could not be found in project 'my-lib'.
    at Architect.getBuilderConfiguration (C:\code\my-app\node_modules\@angular-devkit\architect\src\architect.js:102:23)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (C:\code\my-app\node_modules\@angular\cli\models\architect-command.js:70:55)
    at MergeMapSubscriber._tryNext (C:\code\my-app\node_modules\rxjs\internal\operators\mergeMap.js:65:27)
    at MergeMapSubscriber._next (C:\code\my-app\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (C:\code\my-app\node_modules\rxjs\internal\Subscriber.js:64:18)
    at TapSubscriber._next (C:\code\my-app\node_modules\rxjs\internal\operators\tap.js:62:26)
    at TapSubscriber.Subscriber.next (C:\code\my-app\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (C:\code\my-app\node_modules\rxjs\internal\operators\mergeMap.js:84:26)
    at InnerSubscriber._next (C:\code\my-app\node_modules\rxjs\internal\InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (C:\code\my-app\node_modules\rxjs\internal\Subscriber.js:64:18)
```

### Desired functionality
According to [create library story](https://github.com/angular/angular-cli/wiki/stories-create-library) in wiki documentation, to publish my library I should run `ng build my-lib --prod`. ("The `--prod` flag should be used when building to publish because it will completely clean the build directory for the library beforehand, removing old code leftover code from previous versions.")

As far as I can tell, `generate library` has since been updated to not add a production configuration for the project, and to just make the regular build clear `dist/my-lib`.

So the documentation should be updated to reflect this.

But I am not an Angular expert and I would like to be sure whether when an application which includes the library is built with `--prod`, the typical benefits of it (AOT, etc.) are still provided to the library code and not just the application code.

### Mention any other details that might be useful
Possibly #10710 related.

**Comment by alan-agius4** [comment] 2018-09-21 07:28
Duplicate of 12290

**Closed by alan-agius4** 2018-09-21 07:28 UTC
