### ISSUE TITLE
A way to process the final CSS bundle(s)

### ISSUE THREAD

**Issue by ennovum** [angular/angular-cli#12603] opened 2018-10-15 23:52 UTC
### Bug Report or Feature Request
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality
I'd like to be able to run the final CSS bundle(s) content through a PostCSS pipe, to apply e. g. CSSO or such.

I use a lot of imports in my source SCSS code. Imported files often contain class definitions. `ng-cli` treats each component's stylesheet as a new SCSS entry, so I can't apply the import once loader approach, there is no common "context" for all these files. In result, I get a lot of duplicated code in my final bundle. I'd like to clean it using a tool like CSSO.

If there is a cleaner way of not introducing duplication, please let me know, I couldn't find anything myself.

**Comment by DaSchTour** [comment] 2018-10-25 10:12
I guess this is a duplicate of #8427

**Comment by ennovum** [comment] 2018-10-25 10:28
> I guess this is a duplicate of #8427

It is not. There is a way of defining custom PostCSS plugins to each component style entry. What I meant here is a possibility to define another custom pipeline for the final concatenated bundle if possible.

**Comment by clydin** [comment] 2018-10-25 10:34
There is no final concatenated bundle.  With AOT, the component styles are compiled into the components themselves.  Each component’s styles only affect and are present in the DOM when an instance of the component is present.

**Comment by alan-agius4** [comment] 2020-05-25 11:20
Closing as per above comment.

**Closed by alan-agius4** 2020-05-25 11:20 UTC
Labels: comp: devkit/build-angular, type: feature
