### ISSUE TITLE
Cannot "import as" with prod build

### ISSUE THREAD

**Issue by rhino5oh** [angular/angular-cli#13577] opened 2019-02-02 05:31 UTC
- [X] build

### Regression?   
I believe so, however, I do not recall the exact last version that it worked

### Description

In all of my routing modules, I have the following import:
`import { AuthGuardService as AuthGuard } from './../auth/auth-guard.service'`

And I use it like so:
```
const scatRoutes: Routes = [
  { path: 'scat', component: ScatComponent, canActivate: [AuthGuard]  }
];
```

When I do a prod build, such as:
`ng build --prod --source-map`

I get the following error when I attempt to access my application (served via Express.js):
```
ReferenceError: AuthGuard is not defined
```

### Also, removing the "as" part of the import, and simply importing the class name itself, does in fact work.  So it appears to be in issue with doing import "as". In other words, it works if I change the import to this:

`import { AuthGuardService } from './../auth/auth-guard.service'`

Here's my environment:
```
Angular CLI: 7.3.0
Node: 8.11.3
OS: win32 x64
Angular: 7.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.2
@angular-devkit/build-angular     0.10.2
@angular-devkit/build-optimizer   0.10.2
@angular-devkit/build-webpack     0.10.2
@angular-devkit/core              7.0.2
@angular-devkit/schematics        7.3.0
@angular/cdk                      7.3.0
@angular/cli                      7.3.0
@angular/material                 7.3.0
@ngtools/webpack                  7.0.2
@schematics/angular               7.3.0
@schematics/update                0.13.0
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.19.1

```

**Comment by alan-agius4** [comment] 2019-02-02 07:02
Hi, kindly update `@angular-devkit/build-angular` to the lastest version.

Duplicate of 
https://github.com/angular/angular-cli/issues/13212

**Closed by alan-agius4** 2019-02-02 07:02 UTC

**Comment by rhino5oh** [comment] 2019-02-02 17:56
Also, I updated @angular-devkit/build-angular, now I'm getting this build error:

```
ERROR in scripts.b0500e1e41820f3b46e0.js from Terser
TypeError: Cannot read property 'minify' of undefined
at minify (C:\Users\Ryan\asclepius\node_modules\terser-webpack-plugin\dist\minify.js:175:23)
    at module.exports (C:\<removed>\node_modules\terser-webpack-plugin\dist\worker.js:13:40)
    at handle (C:\<removed>\node_modules\worker-farm\lib\child\index.js:44:8)
    at process.<anonymous> (C:\<removed>\node_modules\worker-farm\lib\child\index.js:51:3)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by rhino5oh** [comment] 2019-02-02 19:21
Also, I updated @angular-devkit/build-angular, now I'm getting this build error:

```
ERROR in scripts.b0500e1e41820f3b46e0.js from Terser
TypeError: Cannot read property 'minify' of undefined
at minify (C:\<removed>\node_modules\terser-webpack-plugin\dist\minify.js:175:23)
    at module.exports (C:\<removed>\node_modules\terser-webpack-plugin\dist\worker.js:13:40)
    at handle (C:\<removed>\node_modules\worker-farm\lib\child\index.js:44:8)
    at process.<anonymous> (C:\<removed>\node_modules\worker-farm\lib\child\index.js:51:3)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Alyosha-Ruslanovich** [comment] 2019-02-12 02:13
I have this error also. How can I fix this issue?
