### ISSUE TITLE
Support glob expressions and placeholders in fileReplacements

### ISSUE THREAD

**Issue by michaeljota** [angular/angular-cli#12517] opened 2018-10-08 14:48 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: v8.12.0
npm: 6.4.1
ng: 
```
Angular CLI: 6.2.4
Node: 8.12.0
OS: win32 x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.4
@angular-devkit/build-angular     0.8.4
@angular-devkit/build-optimizer   0.8.4
@angular-devkit/build-webpack     0.8.4
@angular-devkit/core              0.8.4
@angular-devkit/schematics        0.8.4
@angular/cli                      6.2.4
@ngtools/webpack                  6.2.4
@schematics/angular               0.8.4
@schematics/update                0.8.4
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2
```

### Repro steps

Setup the `angular.json` file with a `fileReplacements` property in `option` from one of the configurations as
```
"fileReplacements": [
  {
    "replace": "src/app/**/{service-name}.service.ts",
    "with": "src/app/**/{service-name}.mock.service.ts"
  }
],
```

### Desired functionality

I would like a file in the folder matching the glob expression being replaced with the another file matching the placeholder. This would allow to replace a series of files according to the platform or other use case.

**Comment by alan-agius4** [comment] 2018-12-07 11:33
Duplicate of https://github.com/angular/angular-cli/issues/12354

**Closed by alan-agius4** 2018-12-07 11:33 UTC
Labels: comp: devkit/build-angular, type: feature
