### ISSUE TITLE
ng init does not create all required files or folders

### ISSUE THREAD

**Issue by jmls** [angular/angular-cli#4180] opened 2017-01-23 13:37 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Linux Ubuntu 16.10

### Versions.
angular-cli: 1.0.0-beta.26

### Repro steps.
ng init on existing folder structure

### The log given by the failure.
no failure ... but `ng test` does not work

### Mention any other details that might be useful.

when running `ng init` on an existing node project, the new files are created successfully and the project is "converted" into an angular-cli project

however, when running `ng test` the following errors are shown

```
 ng test

ENOENT: no such file or directory, lstat '/home/ubuntu/workspace/src/assets'
Error: ENOENT: no such file or directory, lstat '/home/ubuntu/workspace/src/assets'
    at Object.fs.lstatSync (fs.js:901:18)
```
this is fixed by manually creating an empty "assets" folder

then

```
> ng test

ENOENT: no such file or directory, lstat '/home/ubuntu/workspace/src/favicon.ico'
Error: ENOENT: no such file or directory, lstat '/home/ubuntu/workspace/src/favicon.ico'
    at Object.fs.lstatSync (fs.js:901:18)
```

there are obviously _some_ files which are missed out when using `ng init` instead of `ng new`

**Comment by filipesilva** [comment] 2017-01-23 20:54
Odd, will investigate. Thanks for the report!

**Comment by kaznovac** [comment] 2017-02-09 13:11
as mentioned here #2813 this, however unexpected, is intentional by design

**Comment by sumitarora** [comment] 2017-05-11 15:13
Closing is as obsolete `ng init` is no longer available command.

**Closed by sumitarora** 2017-05-11 15:13 UTC
Labels: need: investigation
