### ISSUE TITLE
ng g aliases do not honor .angular-cli.json defaults

### ISSUE THREAD

**Issue by saverett** [angular/angular-cli#7827] opened 2017-09-25 20:55 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.4.3 (also present in 1.4.2)
node: 6.9.1
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
typescript: 2.4.2
```

### Repro steps.
**Given the following `.angular-cli.json` configuration:**
```
"defaults": {
    "component": {
      "flat": true,
      "inlineStyle": true,
      "inlineTemplate": false,
      "spec": false
    },
    "service": {
      "spec": false
    }
    ...
}
```

**Using `ng g` aliases *do not* honor `.angular-cli.json` defaults:**
```
>ng g c test
  create src/app/test/test.component.html (23 bytes)
  create src/app/test/test.component.spec.ts (614 bytes)
  create src/app/test/test.component.ts (261 bytes)
  create src/app/test/test.component.css (0 bytes)
  update src/app/app.module.ts (12070 bytes)

>ng g s blah
  create src/app/blah.service.spec.ts (362 bytes)
  create src/app/blah.service.ts (110 bytes)

...(present in other element aliases as well)
```

**However `ng g` non-aliases *do* honor `.angular-cli.json` defaults:**
```
>ng g component test
  create src/app/test.component.html (23 bytes)
  create src/app/test.component.ts (236 bytes)
  update src/app/app.module.ts (11819 bytes)

>ng g service blah
  create src/app/blah.service.ts (110 bytes)

...(present in other elements as well)
```

### Desired functionality.
`ng g` aliases honor `.angular-cli.json` defaults

### Mention any other details that might be useful.
Likely related to https://github.com/angular/angular-cli/issues/7644 and https://github.com/angular/angular-cli/issues/7662, but those issues do not call out the problems specific to using `ng g` aliases with `.angular-cli.json` defaults

**Comment by hansl** [comment] 2018-09-28 15:30
Could not reproduce this with the latest workspace. This has been fixed with the way we handle aliases and schematics.

![image](https://user-images.githubusercontent.com/681969/46218129-e47c1e80-c311-11e8-968f-b92eeab13e86.png)

**Closed by hansl** 2018-09-28 15:30 UTC
Labels: priority: 1 (urgent), severity5: regression, type: bug/fix
