### ISSUE TITLE
ng serve, is not watching

### ISSUE THREAD

**Issue by gdavid42** [angular/angular-cli#6523] opened 2017-05-31 19:31 UTC
i just updated the angular cli a couple of days ago, and now when i use ng serve it does run the aplication but afterward it doesnt get upgraded, i have to cancel and run again to see the changes i made.

- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
<!--
Output from: `ng --version
@angular/cli: 1.0.6
node: 6.10.3
os: linux x64
Linux fedora 25
-->


### Repro steps.
<!--
Simple steps to reproduce this bug.
Please include: commands run, packages added, related code changes.
A link to a sample repo would help too.
-->


### The log given by the failure.
<!-- Normally this include a stack trace and some more information. -->


### Desired functionality.
<!--
What would like to see implemented?
What is the usecase?
-->


### Mention any other details that might be useful.
<!-- Please include a link to the repo if this is related to an OSS project. -->

**Comment by sumitarora** [comment] 2017-05-31 19:56
Dupe of https://github.com/angular/angular-cli/issues/1610

**Closed by sumitarora** 2017-05-31 19:56 UTC
