### ISSUE TITLE
Make `baseUrl` works in angular-cli

### ISSUE THREAD

**Issue by AlBlanc** [angular/angular-cli#1992] opened 2016-09-06 10:47 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
It doesn't matter

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```angular-cli: local (v1.0.0-beta.11-webpack.8, branch: master)
node: 6.2.1
os: darwin x64```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Just create an app. Set `baseUrl` to `"."` in `tsconfig.json`


4. The log given by the failure. Normally this include a stack trace and some
   more information.
It does not find the import

5. Mention any other details that might be useful.
Not sur i should post this improvement here but Typescript 2.0 introduces `baseUrl` options which allow absolute imports. 
It would be really appreciated to include it in angular-cli.


Update: [This PR](https://github.com/Microsoft/TypeScript/issues/5039#baseUrl) might help. And apparently, `baseUrl` was introduced in TS1.9

**Comment by serhiisol** [comment] 2016-09-08 13:38
https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#module-resolution-enhancements-baseurl-path-mapping-rootdirs-and-tracing

this is documentation about baseUrl.

It would be nice to have this option working instead of having something like: ```../../../../../shared``` if you need that

**Comment by rolandoldengarm** [comment] 2016-09-10 08:00
Already raised here: https://github.com/angular/angular-cli/issues/1465

**Comment by filipesilva** [comment] 2016-09-19 01:10
Dupe of https://github.com/angular/angular-cli/issues/1465

**Closed by filipesilva** 2016-09-19 01:10 UTC
