### ISSUE TITLE
Inconsistency between ng build and ng serve with differential loading

### ISSUE THREAD

**Issue by michaelwittwer** [angular/angular-cli#16069] opened 2019-11-05 16:46 UTC
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No, this behavior was not there in versions previous to angular 8.0

### Description
Differential loading is an awesome feature. Thanks for that!

I have some problems creating a nice developer workflow, with nice I mean serving es5 compliant code (also for testing). I know about the option creating a special tsconfig-es5.app.json for that purpose and then run with `ng serve --configuration es5`. But this does not solve my problem involving a library (also included in the git repo)

## 🔬 Minimal Reproduction
I created a GitHub repository, where the code for the following two approaches lives.

**First Approach**
checkout https://github.com/shiftcode/ng-issue-investigation/tree/%231-es2015-build-only

```
npm i
npx ng build
```

The typescript library delivers a single artifact with `tsconfig.target = es2015`. When running `npx ng build` everything works as expected. The es2015 class construct will be transpiled to function, so legacy (es5) browsers are supported (yes IE11, looking at you).

```
// vendor-es5.js
/***/ "./node_modules/@sample/ts-library/dist/_es2015/messenger.js":
/*!*******************************************************************!*\
  !*** ./node_modules/@sample/ts-library/dist/_es2015/messenger.js ***!
  \*******************************************************************/
/*! exports provided: Messenger */
/***/ (function (module, __webpack_exports__, __webpack_require__) {
  "use strict";
  __webpack_require__.r(__webpack_exports__);
  /* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "Messenger", function () { return Messenger; });
  var Messenger = /** @class */ (function () {
    function Messenger() {
    }
    Messenger.prototype.talk = function () {
      return 'i am just talking';
    };
    return Messenger;
  }());
  //# sourceMappingURL=messenger.js.map
  /***/
})
```

when running `ng serve --configuration es5` IE11 will fail with syntax error, because es2015 class is not transpiled by webpack.

``` 
// vendor.js
/***/ "./node_modules/@sample/ts-library/dist/_es2015/messenger.js":
/*!*******************************************************************!*\
  !*** ./node_modules/@sample/ts-library/dist/_es2015/messenger.js ***!
  \*******************************************************************/
/*! exports provided: Messenger */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "Messenger", function() { return Messenger; });
class Messenger {
    talk() {
        return 'i am just talking';
    }
}
//# sourceMappingURL=messenger.js.map
```

so this approach does not work.

**Second Approach**
checkout https://github.com/shiftcode/ng-issue-investigation/tree/%232-multi-platform-lib-build

Run the following in ng-client:
```
npm i 
npx ng serve --configuration es5
```

The library now provides different entry points, check [package.json](https://github.com/shiftcode/ng-issue-investigation/blob/%232-multi-platform-lib-build/ts-library/package.json) . This is actually the preferred approach, because then we could also use esNext features, because we have a separate build (`tsc --target es5`) transpiling unsupported features.

When running `npx ng serve --configuration es5` everything works as expected in IE11. In comparison running `npx ng build` will not load the correct file for es5 build, instead it loads from `ts-library/dist/_es2015`. (check vendor-es5.js and you will see the string _i am just talking es2015_ instead of _i am just talking es5_).

So for me the question remains about how differential loading supports IE11 with live reloading. Hopefully you can also shed some light in why the files are not loaded / or transpiled as expected.

Thanks in advance for any help!

## 🔥 Exception or Error
Please see the description above.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.17
Node: 12.12.0
OS: darwin x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.17
@angular-devkit/build-angular     0.803.17
@angular-devkit/build-optimizer   0.803.17
@angular-devkit/build-webpack     0.803.17
@angular-devkit/core              8.3.17
@angular-devkit/schematics        8.3.17
@angular/cli                      8.3.17
@ngtools/webpack                  8.3.17
@schematics/angular               8.3.17
@schematics/update                0.803.17
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by clydin** [comment] 2019-11-05 17:28
`ng serve` currently does not support differential loading.  This will change in the future once a comparable performance and usability level can be guaranteed.  `ng serve` is currently recommended for development use against modern browsers that provide built-in development tools.

As you have shown above, serve can be configured to change the TypeScript compilation to emit ES5 code.  But only TypeScript files are affected in such a configuration.  The differential loading processing is performed as a post application build (bundling) step.  This allows it to guarantee the entire application will be ES5 compliant.

**Comment by michaelwittwer** [comment] 2019-11-05 18:19
@clydin Thanks for the fast response, really appreciated. Alright, I guess i can live with that for now. But what i don't get is when following second approach, why does the compiler not pick up the correct version of the library (`ts-library/dist/_es5`). In comparison it works when I run `npx ng serve --configuration es5`. I expected the angular-cli to also set (under the hood) the tsconfig.target to es5 when doing differential loding, am i missing something?

**Comment by clydin** [comment] 2019-11-06 16:40
When differential loading is used, a full ES2015 application build is performed.  This is then post-processed to perform the conversion into an ES5 browser variant (code is down-leveled, necessary polyfills are included, etc.).  An index HTML file is then created that allows browsers to use the appropriate variant and then both variants are written to the output directory.  Finally, any common elements (global stylesheets, assets, etc.) are written/copied into the output directory.

**Comment by alan-agius4** [comment] 2020-10-21 15:14
Closing as working as intended.

Feel free to open a new issue if you feel otherwise.

Thanks.

**Closed by alan-agius4** 2020-10-21 15:14 UTC
Labels: comp: devkit/build-angular, type: feature
