### ISSUE TITLE
"ng build --prod" cause Javascript error in browsers

### ISSUE THREAD

**Issue by MiraYuan** [angular/angular-cli#14384] opened 2019-05-09 04:13 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 
1. commend to start server: ng serve --prod
2. configure angular.json to debug error: "sourceMap": true, "buildOptimizer": false,
3. error show browser console: TypeError: (void 0) is not a function[Learn More] observers.es5.js:38
4. error happen in: "webpacka:///node_modules/@angular/cdk/esm5/observers.es5.js"
var MutationObserverFactory = /** @class */ (function () {
  ...
    /** @nocollapse */ MutationObserverFactory.ngInjectableDef = ɵɵdefineInjectable({ factory: function MutationObserverFactory_Factory() { return new MutationObserverFactory(); }, token: MutationObserverFactory, providedIn: "root" });
    ..
}());

could you please help fix this problem as soon as possible? this is blocked our work.

## 🔬 Minimal Reproduction

when I open the page, error happen right now.

## 🔥 Exception or Error
<pre><code>

TypeError: (void 0) is not a function[Learn More] observers.es5.js:38
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.8
Node: 10.5.0
OS: darwin x64
Angular: 7.2.10
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.8
@angular/animations               8.0.0-beta.11
@angular/cdk                      8.0.0-beta.1-73c4bed
@angular/cli                      7.3.8
@angular/http                     7.2.11
@angular/material                 8.0.0-beta.1-73c4bed
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-05-09 09:06
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by MiraYuan** [comment] 2019-05-17 07:53
I found the root cause is that I deleted codes those had used MaterialModule which is created by myself, and import it in app.module. At last, this module is no need so I don't use it. It looks like it will go wrong if I just import it without using it.

Now I remove the import MaterialModule sentences and it work well of my project.

**Comment by alan-agius4** [comment] 2019-05-17 08:13
Closing as it seems that it's not a bug from the above comment. 

If the issue persists and you think it's a bug please open a new issue with a reproduction.

Thanks.

**Closed by alan-agius4** 2019-05-17 08:13 UTC
Labels: need: more info

**Comment by MiraYuan** [comment] 2019-05-20 06:52
I still think this is a bug, because it is not reasonable error happen when user not use a resource and only import it.
