### ISSUE TITLE
Make it possible to remove directories

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12130] opened 2018-09-04 23:22 UTC
_From @FrozenPandaz on March 26, 2018 14:59_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
All

### Repro steps
Currently there is no way to delete an existing directory.

Additionally, using `move()` with an existing directory will cause the old directory to remain as empty directories.

Try executing a move('src', 'new-src') on a new @angular/cli project for an example.

### The log given by the failure

No log, this is lack of a feature and some unintentional behavior

### Desired functionality
There should be a way to delete an existing directory. Maybe the following?

```ts
tree.delete(pathToDir, isDirectory)
```

Also, using `move()` should remove the old directory if one exists.

### Mention any other details that might be useful

https://github.com/FrozenPandaz/nx/blob/workspacesschematics/packages/schematics/src/collection/workspace/index.ts#L307

Also, this works fine for a tree being generated because the directories aren't on the file system yet. But if you are altering the existing file system, empty directories are left

_Copied from original issue: angular/devkit#563_

**Comment by alan-agius4** [comment] 2018-10-16 13:00
Duplicate of https://github.com/angular/angular-cli/issues/11460

**Closed by alan-agius4** 2018-10-16 13:00 UTC
