### ISSUE TITLE
Error: Local workspace file ('angular.json') could not be found.

### ISSUE THREAD

**Issue by hfakouri** [angular/angular-cli#11137] opened 2018-06-06 20:05 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

`Angular CLI: 6.0.8`
`Node: 8.11.2`
`OS: win32 x64`
`Angular: 6.0.3`
`... animations, common, compiler, compiler-cli, core, forms`
`... http, language-service, platform-browser`
`... platform-browser-dynamic, router`

`Package                           Version`
`-----------------------------------------------------------`
`@angular-devkit/architect         0.6.8`
`@angular-devkit/build-angular     0.6.8`
`@angular-devkit/build-optimizer   0.6.8`
`@angular-devkit/core              0.6.8`
`@angular-devkit/schematics        0.6.8`
`@angular/cli                      6.0.8`
`@ngtools/webpack                  6.0.8`
`@schematics/angular               0.6.8`
`@schematics/update                0.6.8`
`rxjs                              6.2.0`
`typescript                        2.7.2`
`webpack                           4.8.3`

Windows 7 x64

### Repro steps

In VS Code Integrated Terminal:
`ng new sample`

Then:
`npm install --save @ng-bootstrap/ng-bootstrap`

And then:
`ng serve --open`

### The log given by the failure

`Error: Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:180:32)
    at ServeCommand.<anonymous> (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:46:16)
    at Object.<anonymous> (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:87:23)`

### Desired functionality

It should open the browser and show the running angular app

**Comment by filipesilva** [comment] 2018-06-07 16:57
Hi, I can't see that behaviour when following your repro. Can you provide a repository where this happens please?

Just to confirm though, did you change directory into `sample` after `ng new`? Because if you didn't, you're still outside of the project and not serving anything.

**Comment by hansl** [comment] 2018-06-07 18:04
Dupe of https://github.com/angular/angular-cli/issues/10757

**Closed by hansl** 2018-06-07 18:04 UTC
Labels: need: repro steps

**Comment by hfakouri** [comment] 2018-06-07 18:11
It's not a duplicated issue. 
- This is about Angular CLI version 6.0.8 (not 6.0.0)
- Here the issue is on 'ng serve' not 'ng g component mynewcomponent'

**Comment by gargolillas** [comment] 2018-06-07 19:55
You have to run **ng serve --open** in the same folder that creates your project. In your case the folder **sample**

**Comment by hfakouri** [comment] 2018-06-07 20:43
@gargolillas I know, and I did that. That's why I'm saying it should be sth else

**Comment by hfakouri** [comment] 2018-06-07 20:44
@hansl Can you please re-open the issue?

**Comment by sathyaprakash94** [comment] 2018-06-13 11:44
The steps are all fine except you have to do one more step to run the angular application.
Pls change the directory `>cd sample`
and then run the command `>ng serve` 
Hope this will create the initial environment successfully.

**Comment by molcik** [comment] 2018-07-12 07:40
For people googling this error. It’s probably because your global **@angular/cli** version and **@angular/compiler-cli** are differentf  **[here is how to fix it](https://filipmolcik.com/error-local-workspace-file-angular-json-could-not-be-found/)**.

**Comment by attishrj** [comment] 2018-08-18 07:02
This is because you have install angular in some directory and trying to use ng serve without creating your new project set-up

**Comment by sameensg** [comment] 2018-09-12 05:27
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules\@angular\cli\models\workspace-loader.js:44:19)
    at WorkspaceLoader.loadWorkspace (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules\@angular\cli\models\workspace-loader.js:31:21)
    at ServeCommand._loadWorkspaceAndArchitect (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules\@angular\cli\models\architect-command.js:201:32)
    at ServeCommand.<anonymous> (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules\@angular\cli\models\architect-command.js:53:25)
    at Generator.next (<anonymous>)
    at F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules\@angular\cli\models\architect-command.js:52:16)
    at Object.<anonymous> (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules\@angular\cli\models\command-runner.js:127:23)

**Comment by josuepr2** [comment] 2019-04-23 15:46
> I am facing following error:
> 
> Local workspace file ('angular.json') could not be found.
> Error: Local workspace file ('angular.json') could not be found.
> at WorkspaceLoader._getProjectWorkspaceFilePath (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules@angular\cli\models\workspace-loader.js:44:19)
> at WorkspaceLoader.loadWorkspace (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules@angular\cli\models\workspace-loader.js:31:21)
> at ServeCommand._loadWorkspaceAndArchitect (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules@angular\cli\models\architect-command.js:201:32)
> at ServeCommand. (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules@angular\cli\models\architect-command.js:53:25)
> at Generator.next ()
> at F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules@angular\cli\models\architect-command.js:7:71
> at new Promise ()
> at __awaiter (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules@angular\cli\models\architect-command.js:3:12)
> at ServeCommand.initialize (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules@angular\cli\models\architect-command.js:52:16)
> at Object. (F:\Angular Projects\coreui-free-bootstrap-admin-template-master\node_modules@angular\cli\models\command-runner.js:127:23)

I'm having the same issue
