### ISSUE TITLE
ng test - Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by khocef** [angular/angular-cli#1478] opened 2016-07-28 15:39 UTC
**1. OS** -  Windows 7

**2. Versions:**
angular-cli: 1.0.0-beta.10
node: 4.4.5
os: win32 x64

3. Repro steps.  
```
npm install -g angular-cli
ng new ng-app
cd ng-app
ng serve (as admin)
ng test  (as admin)

```
4. The log: 
```
$ ng test
Built project successfully. Stored in "dist/".
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EMFILE: too many open files, open 'D:\workspaces\NodeJs\ng-app\tmp\broccoli_type_script_compiler-input_base_path-piXDQ7BG.tmp\0\src\tsconfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at BroccoliTypeScriptCompiler._loadTsConfig (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:128:34)
    at BroccoliTypeScriptCompiler._createServiceHost (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:163:25)
    at BroccoliTypeScriptCompiler.build (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:41:12)
    at D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\angular2-app.js:331:18)
    at Angular2App._buildTree (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (D:\workspaces\NodeJs\ng-app\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build-watch.js:17:16)
    at D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\addon\ng2\commands\test.js:69:46
    at lib$rsvp$$internal$$tryCatch (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)


The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EMFILE: too many open files, open 'D:\workspaces\NodeJs\ng-app\tmp\broccoli_type_script_compiler-input_base_path-piXDQ7BG.tmp\0\src\tsconfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at BroccoliTypeScriptCompiler._loadTsConfig (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:128:34)
    at BroccoliTypeScriptCompiler._createServiceHost (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:163:25)
    at BroccoliTypeScriptCompiler.build (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:41:12)
    at D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\angular2-app.js:331:18)
    at Angular2App._buildTree (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (D:\workspaces\NodeJs\ng-app\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build-watch.js:17:16)
    at D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\addon\ng2\commands\test.js:69:46
    at lib$rsvp$$internal$$tryCatch (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\workspaces\NodeJs\ng-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

Tanks

**Comment by filipesilva** [comment] 2016-07-28 16:04
Dupe of https://github.com/angular/angular-cli/issues/977, fixed in #1455.

**Closed by filipesilva** 2016-07-28 16:04 UTC
