### ISSUE TITLE
ng update performed code migrations for Angular 9

### ISSUE THREAD

**Issue by fr0** [angular/angular-cli#15523] opened 2019-09-04 20:20 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Unknown

### Description

```
> ng update
Using package manager: 'yarn'
Collecting installed dependencies...
Found 81 dependencies.
    We analyzed your package.json, there are some packages to update:
    
      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       8.3.1 -> 8.3.2           ng update @angular/cli
> ng update @angular/cli
Using package manager: 'yarn'
Collecting installed dependencies...
Found 81 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cli @ "8.3.2" (was "8.3.1")...
    Updating package.json with dependency @angular/language-service @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/compiler-cli @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/compiler @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular-devkit/build-ng-packagr @ "0.803.2" (was "0.803.1")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.803.2" (was "0.803.1")...
    Updating package.json with dependency @angular/animations @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/elements @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/common @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/core @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/forms @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/platform-browser @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/platform-server @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/router @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency zone.js @ "0.10.2" (was "0.9.1")...
UPDATE package.json (3908 bytes)
warning " > @angular-devkit/build-angular@0.803.2" has incorrect peer dependency "@angular/compiler-cli@^8.0.0-beta.0 || ^8.1.0-beta.0 || ^8.2.0-beta.0 || ^8.3.0-beta.0 || ^8.4.0-beta.0 || >=9.0.0-beta < 9".
warning "@angular-devkit/build-angular > @ngtools/webpack@8.3.2" has incorrect peer dependency "@angular/compiler-cli@^8.0.0-beta.0 || ^8.1.0-beta.0 || ^8.2.0-beta.0 || ^8.3.0-beta.0 || ^8.4.0-beta.0 || >=9.0.0-beta < 9".
warning " > codelyzer@5.1.0" has incorrect peer dependency "@angular/compiler@>=2.3.1 <9.0.0 || >8.0.0-beta <9.0.0 || >8.1.0-beta <9.0.0 || >8.2.0-beta <9.0.0".
warning " > codelyzer@5.1.0" has incorrect peer dependency "@angular/core@>=2.3.1 <9.0.0 || >8.0.0-beta <9.0.0 || >8.1.0-beta <9.0.0 || >8.2.0-beta <9.0.0".
warning " > ng-packagr@5.5.0" has incorrect peer dependency "@angular/compiler@^6.0.0 || ^7.0.0 || ^8.0.0-beta.0 || ^8.1.0-beta.0 || ^8.2.0-beta.0 || ^8.3.0-beta.0 || ^8.4.0-beta.0 || >=9.0.0-beta < 9".
warning " > ng-packagr@5.5.0" has incorrect peer dependency "@angular/compiler-cli@^6.0.0 || ^7.0.0 || ^8.0.0-beta.0 || ^8.1.0-beta.0 || ^8.2.0-beta.0 || ^8.3.0-beta.0 || ^8.4.0-beta.0 || >=9.0.0-beta < 9".
    ** Executing migrations for package '@angular/core' **
            ------ Renderer to Renderer2 Migration ------
            As of Angular 9, the Renderer class is no longer available.
            Renderer2 should be used instead.
            ------ Undecorated classes with decorated fields migration ------
            As of Angular 9, it is no longer supported to have Angular field decorators on a class that does not have an Angular decorator.
            ------ Undecorated classes with DI migration ------
            
            This migration uses the Angular compiler internally and therefore projects that no longer build successfully after the update cannot run the migration. Please ensure there are no AOT compilation errors and rerun the migration.. The following project failed: src/tsconfig.app.json
            
            TypeError: Cannot read property '_metadataResolver' of undefined
            
            Migration can be rerun with: "ng update @angular/core --from 8.0.0 --to 9.0.0 --migrate-only"
            Successfully migrated all found undecorated classes
            that use dependency injection.
            ----------------------------------------------

```

I am confused because I was going from Angular 8.3.1 to 8.3.2, so why does it say "As of Angular 9"?

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.1
Node: 12.6.0
OS: darwin x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.1
@angular-devkit/build-angular      0.803.1
@angular-devkit/build-ng-packagr   0.803.1
@angular-devkit/build-optimizer    0.803.1
@angular-devkit/core               8.3.1
@angular-devkit/schematics         8.3.1
@angular/cli                       8.3.1
@schematics/angular                8.3.1
@schematics/update                 0.803.1
ng-packagr                         5.5.0
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.3
</code></pre>

**Comment by alan-agius4** [comment] 2019-09-04 20:30
Duplicate of https://github.com/angular/angular-cli/issues/14980

**Closed by alan-agius4** 2019-09-04 20:30 UTC
