### ISSUE TITLE
@angular-devkit/schematics-cli doesn't support schematics prompt

### ISSUE THREAD

**Issue by noelmace** [angular/angular-cli#12800] opened 2018-10-29 23:23 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
@angular-devkit/schematics@v0.10.3
node v10.11.0
GNU/Linux Debian buster/sid
```

### Repro steps
1. create a new schematic: `schematics blank hello-world`
1. create a schema.json file in src/hello-world with the following content
```json
{
  "$schema": "http://json-schema.org/schema",
  "id": "SchematicsHelloWorld",
  "title": "Hello World Schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "name of the file to create",
      "x-prompt": "What name do you want to give to the generated file?"
    }
  },
  "required": []
}
```
1. run this schematic without the name option
`schematics .:hello-world`

See https://github.com/noelmace/angular-cli-deep-dive/tree/schematics-prompt

A npm script `schematics:run-cli` permit to reproduce this.
You'll find all the schematics files in the schematics/ folder.
You can also run the `schematics:run` npm script to see that the behavior isn't the same when using angular-cli generate.

### The log given by the failure
No prompt:
```
 ➜ npm run schematics:run-cli

> angular-cli-deep-dive@0.0.0 schematics:run-cli ./git/hub/noelmace/angular-cli-deep-dive
> cd ./schematics/hello-world && schematics .:hello-world

CREATE /hello (5 bytes)
```
### Desired functionality
In order to be consistent with @angular/cli, @angular-devkit/schematics-cli should support schematics prompt.

**Comment by alan-agius4** [comment] 2018-10-30 05:09
Duplicate of https://github.com/angular/angular-cli/issues/12688

**Closed by alan-agius4** 2018-10-30 05:09 UTC
