### ISSUE TITLE
Ability For Ngr Standard Library To Work Across Different Versions of Ng

### ISSUE THREAD

**Issue by chopswil15** [angular/angular-cli#25918] opened 2023-09-28 14:54 UTC
### Command

version

### Description

In the .Net world there is .Net Standard, and when you write a .Net Standrd DLL it can work across different versions of .Net without doing anything special and no complaints about version issues.

I would like to have an Ng Standrd so I can write common code library once and add the library to any Ng version project without it complaining about version issues.

### Describe the solution you'd like

see above

**Comment by chopswil15** [comment] 2023-09-28 14:57
Also with 3rd Party Libraries, if they could be Ng Standard compliant you wouldn't have to wait for them to update their code to a new version of Ng.

**Comment by alan-agius4** [comment] 2023-09-28 14:58
Duplicate of https://github.com/angular/angular/issues/46398

**Closed by alan-agius4** 2023-09-28 14:58 UTC
