### ISSUE TITLE
can i be able load module from node_modules (folder pointing to some repo) in loadChildren for routing using angular-cli  version 1.0.0

### ISSUE THREAD

**Issue by tkssharma** [angular/angular-cli#9041] opened 2017-12-30 16:18 UTC
can i be able load module from node_modules from some repo in loadChildren in routing 

### Versions
```
const routes: Routes = [
  { path: '', redirectTo: '/home', pathMatch: 'full' },
  { path: 'about', loadChildren: './about/about.module#AboutModule' }
];
```

**Comment by filipesilva** [comment] 2018-01-02 10:07
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/6373. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2018-01-02 10:07 UTC
