### ISSUE TITLE
--mobile flag has been disabled temporarily,..

### ISSUE THREAD

**Issue by webia1** [angular/angular-cli#3007] opened 2016-11-03 16:50 UTC
After a while I wanted test angular-cli again, in the hope, maybe there would be new features,.. 

Unfortunately the opposite was the case: existing features (routing, mobile,..) have been disabled and nothing has happened since then. I think, the idea with Angular-CLI is great but the development leaves something to be desired. I don't want to demotivate any participant but we would strongly need a CLI in a production environment for mobile devices.

Maybe you could give some detail information? Thank you very much,..

**Comment by webia1** [comment] 2016-11-03 17:57
> The --mobile flag has been disabled temporarily while we await an update of angular-universal for supporting NgModule. Sorry for the inconvenience.

I've got the information just now:

> Angular-Universal is supporting NgModule for a while now, you can download 2.1.0-rc.1,..

**Comment by filipesilva** [comment] 2016-11-04 17:27
Dupe of https://github.com/angular/angular-cli/issues/2228

**Closed by filipesilva** 2016-11-04 17:27 UTC
