### ISSUE TITLE
Expose code instrumentation as a a build option

### ISSUE THREAD

**Issue by Tallyb** [angular/angular-cli#25793] opened 2023-09-06 18:45 UTC
### Command

build, serve

### Description

Provide the ability to instrument the code using istanbul without the need to run jest or any other specific test runner. 
This could be an option in the angular.json (project.json for nx) to specify if code should be instrumented.

**Comment by alan-agius4** [comment] 2023-09-11 06:34
Duplicate of https://github.com/angular/angular-cli/issues/15333

**Closed** 2023-09-11 07:17 UTC
