### ISSUE TITLE
angular/cli not compatible with moment 2.19

### ISSUE THREAD

**Issue by mike-bresnahan** [angular/angular-cli#8010] opened 2017-10-11 15:53 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.5
node: 6.11.3
os: darwin x64
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4

After upgrading from moment 2.18 to 2.19, our angular/cli 1.4.5 application no longer builds with the AOT compiler. I have reproduced the problem by adding moment 2.19 to a vanilla application created with "ng new". The build fails with the following diagnostics.

WARNING in ./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/Users/a715139/ngnew/node_modules/moment/src/lib/locale'
resolve './locale' in '/Users/a715139/ngnew/node_modules/moment/src/lib/locale'
using description file: /Users/a715139/ngnew/node_modules/moment/package.json (relative path: ./src/lib/locale)
Field 'browser' doesn't contain a valid alias configuration
after using description file: /Users/a715139/ngnew/node_modules/moment/package.json (relative path: ./src/lib/locale)
using description file: /Users/a715139/ngnew/node_modules/moment/package.json (relative path: ./src/lib/locale/locale)
as directory
/Users/a715139/ngnew/node_modules/moment/src/lib/locale/locale doesn't exist
[/Users/a715139/ngnew/node_modules/moment/src/lib/locale/locale]
@ ./node_modules/moment/src/lib/locale/locales.js 65:16-60
@ ./node_modules/moment/src/lib/locale/locale.js
@ ./node_modules/moment/src/moment.js
@ ./src/app/app.component.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

The root cause appears to be the fact that webpack is confused by line 65 in src/lib/locale/locales.js into thinking that a file must exist at src/lib/locale/locale, but no such file exists. The solution is not clear to me.

```js
pretendingNotToRequireV2('./locale/' + name);
```

```js
function loadLocale(name) {
    var oldLocale = null;

    // TODO: Find a better way to register and load all the locales in Node
    if (!locales[name] && (typeof module !== 'undefined') &&
            module && module.exports) {
        oldLocale = globalLocale._abbr;
        try {
            // workaround for React Native 0.49+
            var pretendingNotToRequireV1 = require;
            pretendingNotToRequireV1('moment/locale/' + name);
        } catch (e) {
            // In the test environment, the external module 'moment'
            // can't be resolved because we're running inside it.
            // Fallback to using the old relative import
            try {
                var pretendingNotToRequireV2 = require;
                pretendingNotToRequireV2('./locale/' + name);
            } catch (e) { }
        }

        // because defineLocale currently also sets the global locale, we
        // want to undo that for lazy loaded locales
        getSetGlobalLocale(oldLocale);
    }
    return locales[name];
}
```

**Comment by hansl** [comment] 2017-10-11 17:58
This is an issue with the interaction with Moment.js and webpack, nothing we can do. The issue has been reported already on their repo (see https://github.com/moment/moment/issues/4216).

Closing this as duplicate of https://github.com/moment/moment/issues/4216.

**Comment by hansl** [comment] 2017-10-11 17:59
Addendum: The only fix known, for _any_ webpack projects using momentjs (not just the Angular CLI), is to rollback to using 2.18.1.

**Closed by hansl** 2017-10-11 17:58 UTC
