### ISSUE TITLE
Need Lazy Loaded routes from the .json file to be compiled and loaded dynamically

### ISSUE THREAD

**Issue by NaveenTula90** [angular/angular-cli#8029] opened 2017-10-12 15:56 UTC
This issue is same as the "https://github.com/angular/angular-cli/issues/4234"

I was trying to read the lazy routes from the json file. I know that loadchildren string should be compiled for the routes to be registered.

My question is: Is there any possibility to do the compile or build the lazy routes and  then read them from the Json File? or another approach is read them from the json file and compile and load them(https://github.com/mgechev/angular-seed/issues/1358#issuecomment-248890159) ?

Please post the suggestions. Thank you! #4234 #1358 @filipesilva

**Comment by ramasamykasiviswanathan** [comment] 2017-10-12 16:30
I thought of implementing the similar thing where by registering routes based on JSON file

StackOverFlow link: https://stackoverflow.com/questions/46707591/angular-4-dynamic-routing-json

Any help on this is much appreciated.

Thanks

**Comment by filipesilva** [comment] 2017-10-16 10:51
I'm sorry but I have to close this issue as a duplicate of #4234 and ask you to post your question there instead. 

Another relevant issue is https://github.com/angular/angular-cli/issues/4541.

**Closed by filipesilva** 2017-10-16 10:51 UTC
