### ISSUE TITLE
Routing to another page does not load external scripts

### ISSUE THREAD

**Issue by cactusjack66** [angular/angular-cli#12043] opened 2018-08-30 11:19 UTC
Bug Report or Feature Request (mark with an `x`)

- [x] bug report 
- [ ] feature request

Versions
Node: v10.7.0
npm 6.1.0
Angular CLI: 6.0.8
Angular: 6.1.6

Repro steps
https://github.com/cactusjack66/ScriptRouteTest.git

Desired functionality
The collapse button on the top right corner of the box collapses the box on page1 after the page has been loaded. After clicking the redirect button to page2 it does not work any longer. You have to reload the page to make it work again. I have added all neccessary scripts and styles to the angular.json file.

Mention any other details that might be useful
After checking out use npm install @angular-devkit/build-angular to get it work.

**Comment by alan-agius4** [comment] 2018-08-30 13:33
Thanks for reporting this issue. However, this issue is a duplicate of #11044. Please subscribe to that issue for future updates.

**Closed by alan-agius4** 2018-08-30 13:33 UTC
