### ISSUE TITLE
Cannot hit breakpoints in VS Code since 1.7.0

### ISSUE THREAD

**Issue by coffeymatt** [angular/angular-cli#9795] opened 2018-02-27 10:21 UTC
### Versions
```
The issue occurs with angular cli 1.7.0 onward:
I have rolled back to 1.6.8 and angular 5.1.1 to restore functionality.

```

### Repro steps

The after the upgrade to 1.7.1, if I put a break point in a component, it either doesn't get hit, or shows a 'readonly inline' version of the code breaking in a completely different place.

Apologies that these repro steps aren't specific, but it's a rather general issue, as per other users:

https://stackoverflow.com/questions/48892311/angular-cli-1-7-0-and-visual-studio-code-cant-set-breakpoints/49006195#49006195

### Observed behavior

Break point doesn't get hit or opens readonly inline file with break in wrong place:

https://stackoverflow.com/questions/48892311/angular-cli-1-7-0-and-visual-studio-code-cant-set-breakpoints/49006195#49006195

### Desired behavior

Restore previously working debugging from 1.6.8

**Comment by filipesilva** [comment] 2018-02-27 19:32
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/9729. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2018-02-27 19:32 UTC
