### ISSUE TITLE
Application/Vite builder does not work with linked libraries and cache enabled

### ISSUE THREAD

**Issue by Carlosamouco** [angular/angular-cli#26999] opened 2024-01-30 22:10 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When rebuilding a linked library, the `ng serve` does not pick the changes of that library when we have cache enabled.

I tried to include the linked library under the `paths` config in ` tsconfig.json` but it made the library chunk get imported twice during runtime. In the chrome dev-tools I can see the library generated chunk being imported from `.angular/cache/17.1.1/vite/deps` and another chunk from the same library at the `root`.

It is possible to make this work by any means? Not having the possibility to have cache enabled really hurts.

### Minimal Reproduction

1. Prepare the environment:
```bash
ng new my-workspace --create-application false
ng new my-app

cd ./my-workspace
ng generate library my-lib
ng build my-lib

cd ../my-app
npm link ../my-worksapce/dist/my-lib
```

2. Import and use the linked library in the `app.component.ts`:
```ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

import { MyLibComponent } from 'my-lib';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'my-app';

  constructor() {
    console.log(MyLibComponent);
  }
}
```

3. Run `ng serve` - The component class is printed in the browser console.
4. Change something in the linked library component `MyLibComponent` and rebuild it with `ng build my-lib --watch` - The change is not applied to the application.

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.1.1
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
ng-packagr                      17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by alan-agius4** [comment] 2024-01-30 22:18
Duplicate of https://github.com/angular/angular-cli/issues/26585

**Closed by alan-agius4** 2024-01-30 22:18 UTC

**Comment by Carlosamouco** [comment] 2024-01-30 22:28
@alan-agius4 

As stated in https://github.com/angular/angular-cli/issues/25753#issuecomment-1855377797, linked libraries work if we have cache disabled. That's the issue I am facing and the duplicate does not address that.
