### ISSUE TITLE
```AngularCompilerPlugin``` ignores config passed to it

### ISSUE THREAD

**Issue by pfrendo** [angular/angular-cli#8688] opened 2017-11-30 13:44 UTC
### Versions
```
ng- 5.0.3
```

### Repro steps
Configure the ```AngularCompilerPlugin``` with the following config:

```
new AngularCompilerPlugin({
	tsConfigPath: "./tsconfig.json",
	entryModule: path.join(__dirname, "ClientApp/app/app.module.server#AppModule"),
	platform: Platform.Server,
	compilerOptions: {
	noUnusedParameters: false,
	}
})```

Then build in NGC, it then gives out this exception

``` Module build failed: Error: @ngtools/webpack is being used as a loader but no `tsConfigPath` option nor AotPlugin was detected. You must provide at least one of these.
          at Object.ngcLoader```

**Comment by clydin** [comment] 2017-11-30 15:23
Thanks for reporting this issue. However, this issue is appears to be a duplicate of an existing issue #8430. Please subscribe to that issue for future updates.

**Closed by clydin** 2017-11-30 15:23 UTC
