### ISSUE TITLE
6.0.0-rc.7 update/generate commands fail if angular.json is in home folder

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#10508] opened 2018-04-28 05:05 UTC
If there is a `angular.json` or `.angular.json` file in the home folder and `6.0.0-rc.7` is used, `ng update` and `ng generate` commands will fail.

A workaround for now is to delete the `.angular.json`/`angular.json` in the home folder.

**Comment by hansl** [comment] 2018-04-30 22:30
Dupe of #10513 which is going to be fixed soon.

**Closed by hansl** 2018-04-30 22:30 UTC
Labels: priority: 2 (required)
