### ISSUE TITLE
Takes a very very long time to install

### ISSUE THREAD

**Issue by pflannery** [angular/angular-cli#3086] opened 2016-11-09 23:38 UTC
Windows 10, i7 2.3ghz quad core
50Mb connection
```
angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: win32 x64
```
I understand it's still beta but it took me 25 minutes to get the cli to install itself and generate the first app.
I noticed that this cli takes up 225 MB once installed. This seems a very extreme size for a cli app.
The generated app takes up 240MB which is also really extreme for a basic skeleton.

Would be great if the sizes and install times could be reduced because Installing from npm can suck even on a 50mb connection. 
It takes no more than 5mins to download the angular1.zip @ 9MB and then setup a basic app. 
I just hope this will eventually be the same for angular 2 :)

**Comment by jongunter** [comment] 2016-11-09 23:50
I'm suffering from long install times on Windows, too. Not 25 minutes, but at least 5 min, which is still pretty darn long!  I'm on a 100 Mb/s connection, so I don't think download speed is the issue.  Seems to be hanging at the part where it installs NPM packages.

**Comment by gelliott181** [comment] 2016-11-10 20:14
Let's clear something up: This is the Angular-CLI, not just Angular 2. The CLI will be large because in addition to the Angular 2 framework (https://github.com/angular/angular), it provides many other features like a live-reload dev server and build system (Webpack + plugins + loaders), testing systems for both Unit tests and E2E, and capabilities to boilerplate your Angular 2 code for you. The installs take a while because there is a long list of dependencies and we pull multiple large projects (Ember-CLI, Webpack, Karma, Protractor, most of lodash, PostCSS, Bluebird, RxJS, UglifyJS, etc.), something the team has stated they're trying to trim down on whenever possible. 

Open your local `node_modules` and you'll get a feeling for how many dependencies have to be pulled each time. A lot of these are minimally used, and many are likely being installed for something we depend on indirectly, or they were previously depended on and are now tech debt which means the removal requires extensive testing to ensure nothing was using them without documenting it (Broccoli is a great example.)

The good news? You really shouldn't need to install the entire project often. Yes, the CLI is a bit hefty, but the tools are well worth the extra weight in my opinion. The production output it provides is also very small in comparison. This has also been topic of concern as the builds can sometimes reach 2-3MB with larger projects, but after extensive AoT work, the sizes have been getting smaller and smaller each release.

**Comment by filipesilva** [comment] 2016-11-21 16:38
Dupe of https://github.com/angular/angular-cli/issues/1263, we are working on it though.

**Closed** 2016-11-21 16:38 UTC

**Comment by harishh486** [comment] 2017-11-02 01:22
It is taking more than 40 mins and its still running for me.

**Comment by OwLisCodes** [comment] 2018-01-01 22:08
same for me right now. I'm around 1h into installing right now.

**Comment by ashish051321** [comment] 2018-01-24 12:23
The install time for even simple angular projects that we clone from github or bitbucket, is taking way too much time.(>10 mins).
Is there a solution to it ?

**Comment by Max-Lev** [comment] 2018-01-25 23:17
It also makes my machine to laaag: macOS became unresponsive  - no browsers and all small programs could not be opened....

it ain't right....

**Comment by fivedesigns** [comment] 2018-02-13 13:28
nearly 30 minutes passed and it's still installing on Mac

**Comment by kemin711** [comment] 2018-03-17 20:19
It is very long time and getting an error even I am using root login!
is=0x17788a58c211 <JSGlobal Object>,err=0x177875d23ca9 <Error map = 0x177876104e59>,cre...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 5: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/usr/local/bin/node]
 6: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x1bbb0bf842fd
 8: 0x1bbb0c0c287c
EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/vendor'
+ @angular/cli@1.7.3
added 1045 packages in 2367.623s
