### ISSUE TITLE
Upgrade message is shown twice and includes error stack

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#10157] opened 2018-04-03 18:38 UTC
When running `ng build` using `6.0.0-rc.0` on a 1.7 project, the message to upgrade shows up twice and includes an unneeded error stack.

```
kamik@RED-X1C6 MINGW64 /d/sandbox/1.7-project (master)
$ ng build
An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
  npm i
Error: An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
  npm i
    at WorkspaceLoader._assertUpdatedWorkspace (D:\sandbox\1.7-project\node_modules\@angular\cli\models\workspace-loader.js:73:19)
    at WorkspaceLoader._getProjectWorkspaceFilePath (D:\sandbox\1.7-project\node_modules\@angular\cli\models\workspace-loader.js:29:14)
    at WorkspaceLoader.loadWorkspace (D:\sandbox\1.7-project\node_modules\@angular\cli\models\workspace-loader.js:25:21)
    at BuildCommand._loadWorkspaceAndArchitect (D:\sandbox\1.7-project\node_modules\@angular\cli\models\architect-command.js:151:32)
    at BuildCommand.<anonymous> (D:\sandbox\1.7-project\node_modules\@angular\cli\models\architect-command.js:45:25)
    at Generator.next (<anonymous>)
    at D:\sandbox\1.7-project\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\sandbox\1.7-project\node_modules\@angular\cli\models\architect-command.js:3:12)
    at BuildCommand.initialize (D:\sandbox\1.7-project\node_modules\@angular\cli\models\architect-command.js:44:16)
```

**Comment by dottodot** [comment] 2018-04-04 06:54
Seeing the same with ng serve after running `ng update @angular/cli --migrate-only --from=1.7.1` it successfully creates the `angular.json` file but I then get the same error as above and can't proceed

**Comment by pascallaprade-beslogic** [comment] 2018-04-04 14:17
I had the same problem also. I ended up searching globally on my whole computer for "angular-cli.json", and found ".angular-cli.json" in my home directory (I don't know how it got up there, but anyways - or is this what happens when we set global cli settings?).

Once I removed this file, I tried building again, and the update message didn't show up, and the build succeeded.

In my case, the warning message appeared after a checkout from someone else's branch, and that person already did the update. Typing in the suggested update command simply failed, because there was no configuration file to be found...

So if it's caused by global cli settings, you should be able to detect when the update needs to update that part only, and not fail when the update was already done on another computer. The update message should also be more specific: it's not the project I needed to update, but my global configuration (which I just deleted in this case).

If it was _not_ caused by global configuration, I would expect an ".angular-cli.json" file in my home directory to not interfere with a specific project.

**Comment by clydin** [comment] 2018-04-04 17:36
Fixed via https://github.com/angular/angular-cli/pull/10162

**Closed by clydin** 2018-04-04 17:36 UTC
Labels: 6.0.0-rc
