### ISSUE TITLE
compiler.js:2175 Uncaught Error: Can't resolve all parameters for TestComponent: (?, ?)

### ISSUE THREAD

**Issue by AnandkumarBShetty** [angular/angular-cli#15916] opened 2019-10-22 18:06 UTC
After update to latest cli (@angular/cli 8.3.12 last released one), compilation works fine however the page is not opening due to issue error message in console on the chrome inspect. Prior to the update(with angular cli version:    "@angular/cli": "~8.2.2", it used to work fine.

compiler.js:2175 Uncaught Error: Can't resolve all parameters for : (?, ?).
at syntaxError (compiler.js:2175)
at CompileMetadataResolver._getDependenciesMetadata (compiler.js:20399)
at CompileMetadataResolver._getTypeMetadata (compiler.js:20294)
at CompileMetadataResolver._getInjectableTypeMetadata (compiler.js:20512)
at CompileMetadataResolver.getProviderMetadata (compiler.js:20521)
at compiler.js:20459
at Array.forEach ()
at CompileMetadataResolver._getProvidersMetadata (compiler.js:20419)
at compiler.js:20421
at Array.forEach ()

Angular CLI: 8.3.12
Node: 10.16.0
OS: win32 x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package Version
@angular-devkit/architect 0.803.12
@angular-devkit/build-angular 0.803.12
@angular-devkit/build-optimizer 0.803.12
@angular-devkit/build-webpack 0.803.12
@angular-devkit/core 8.2.2
@angular-devkit/schematics 8.2.2
@angular/cli 8.3.12
@angular/http 7.2.15
@ngtools/webpack 8.3.12
@schematics/angular 8.3.12
@schematics/update 0.803.12
rxjs 6.5.3
typescript 3.5.3
webpack 4.39.2

**Comment by alan-agius4** [comment] 2019-10-22 19:15
Duplicate of https://github.com/angular/angular-cli/issues/15917

**Closed by alan-agius4** 2019-10-22 19:15 UTC
