### ISSUE TITLE
ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

### ISSUE THREAD

**Issue by PeterHdd** [angular/angular-cli#14592] opened 2019-05-30 16:06 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] serve
```

### Description

I'm trying to use my library:
https://github.com/PeterHdd/date-filtersjs 

in an ionic application that uses angular, but I keep getting the above error. I'm just executing `ionic serve` and then I get the error in the title.

This is my `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es5",                          
    "module": "commonjs",                    
    "lib": ["es6", "dom", "es2017"],  
    "strict": true,
    "outDir": "./dist",
  },
}
```

I also get the same error if I use the following `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es5",                          
    "module": "commonjs",                    
    "lib": ["es6", "dom", "es2017"],  
    "strict": true,
    "outDir": "./dist",
  },
   "files": [
    "src/dates.ts",
    "src/filter.ts",
     ],
  "include": [
    "src/**/*",
    "**/*.ts"
  ]
}
```
or 

```   
{
  "compilerOptions": {
    "target": "es5",                          
    "module": "commonjs",                    
    "lib": ["es6", "dom", "es2017"],  
    "strict": true,
"outDir": "./dist",
  },
   "files": [
    "src/dates.ts",
    "src/filter.ts",
     ],
  "include": [
    "src/**/*",
],
}
```

## 🔬 Minimal Reproduction
```
npm install https://github.com/PeterHdd/date-filtersjs
ionic serve
```

## 🔥 Exception or Error
```
\node_modules\date-filtersjs\src\filter.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
[ng] The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
[ng]     at AngularCompilerPlugin.getCompiledFile (D:\Peter\Invest Bank\Invest-Corporate\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
[ng]     at plugin.done.then (D:\Peter\Invest Bank\Invest-Corporate\node_modules\@ngtools\webpack\src\loader.js:41:31)
[ng]     at <anonymous>
[ng]     at process._tickCallback (internal/process/next_tick.js:188:7)
```

## 🌍 Your Environment
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 8.11.1
OS: win32 x64
Angular: 7.2.12
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.0
```

**Comment by alan-agius4** [comment] 2019-05-30 16:16
Duplicate of https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325

**Closed by alan-agius4** 2019-05-30 16:16 UTC
