### ISSUE TITLE
Building an application automatically watch for libraries changes

### ISSUE THREAD

**Issue by KrakenZ** [angular/angular-cli#18985] opened 2020-10-06 13:03 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [x] build
- [x] serve
### Description
Whe working in an Angular workspace,
you have to run `ng build [lib] --watch` on all libraries and then `ng build [app] --watch`
to detect the changes and rebuild the application with the latest libraries changes.

### Describe the solution you'd like
• A flag (`--watchLibraries=opts`?) to automatically build & watch libraries when running `ng build [app] --watch`
or
• An option in angular.json to make it dependent on the configuration.

`opts=true|false|noFirstBuild`:
true/false: activate / deactivate the functionnality.
noFirstBuild: to prevent having to compile lots of libraries each time you run the command, you can choose to only build them if they changed after the application has been built.

How to detect the libraries:
Using `angular.json#projects.[project].projectType` (= library)

### Describe alternatives you've considered
npm scripts, but each time you add a library you need to add it in the scripts.

**Comment by alan-agius4** [comment] 2020-10-07 07:27
Duplicate of https://github.com/angular/angular-cli/issues/11002

**Closed by alan-agius4** 2020-10-07 07:27 UTC
