### ISSUE TITLE
Building package with wrap-enums build optimizer gets stuck

### ISSUE THREAD

**Issue by eemeli** [angular/angular-cli#14505] opened 2019-05-23 10:29 UTC
# 🐞 Bug report

### Command (mark with an `x`)
```
- [x] build
```

### Is this a regression?

No idea.

### Description

Building a project with [messageformat](https://messageformat.github.io/messageformat/) 2.2.1 or later as a dependency, either directly or via [ngx-translate-messageformat-compiler](https://www.npmjs.com/package/ngx-translate-messageformat-compiler), gets stuck if `buildOptimizer` is true.

Hacking `node_modules/@angular-devkit/build-optimizer/src/build-optimizer/build-optimizer.js` (version 0.13.9) to comment out [line 110 (js) / 155 (ts)](https://github.com/angular/angular-cli/blob/f651a2bd30fe812954dee6cc1fb2cc2e385a1bfd/packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts#L155) allows for the build to succeed, and would suggest that the issue is caused by the wrap-enums transform.

## 🔬 Minimal Reproduction
```sh
git clone git@github.com:frankie567/messageformat-issue-239.git
cd messageformat-issue-239
npm install
npm run build -- --prod  # gets stuck
sed -ie '110d' node_modules/@angular-devkit/build-optimizer/src/build-optimizer/build-optimizer.js
npm run build -- --prod  # succeeds
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.9
Node: 11.9.0
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

Related issue: messageformat/messageformat#239

The change in the dependent package (messageformat) was moving the source from ES5 to
ES6 and adding a Webpack-generated `"browser"` build of the library.

**Comment by kzc** [comment] 2019-05-24 03:27
The typescript parser takes an inordinate amount of time to process the code from the minified bundle of `messageformat`. Removing the wrap-enums transform just causes `angular-cli` to bail early without parsing since there are no other applicable transforms for that particular input.

Repro of the slowness using only `typescript`:

```
npm install messageformat@2.2.1 typescript@3.2.4

# either takes a very long time to run or it never completes
node_modules/.bin/tsc node_modules/messageformat/messageformat.js --allowJs --out out.js
```

Specifically, the generated code for the [`pegjs` parser](https://github.com/messageformat/messageformat/blob/master/packages/parser/parser.pegjs) once minified will cause the typescript parser to get bogged down in type deduction in deeply mutually recursive inlined code.

Compare the time it takes typescript to process the unminified input:

```
$ cp node_modules/messageformat-parser/parser.js .

$ /usr/bin/time node_modules/.bin/tsc parser.js --allowJs --out out.js
        3.92 real         4.61 user         0.14 sys
```

to processing the minified input:

```
$ terser -V
terser 3.11.0

# minified and formatted
$ terser parser.js -bmc > parser.min.js 

# either takes a very long time to run or it never completes
$ /usr/bin/time node_modules/.bin/tsc parser.min.js --allowJs --out out.js
```

So while this is a `typescript` parser issue and probably should be reported to that project, the problem could be avoided if the `messageformat/messageformat.js` bundle were to be published in unminified form.

**Comment by kzc** [comment] 2019-05-24 17:01
This bug appears to be fixed in the latest dev version of `typescript`:

```
$ node_modules/.bin/tsc -v
Version 3.5.0-dev.20190524

$ /usr/bin/time node_modules/.bin/tsc --allowJs parser.js --out out.js
        2.34 real         3.02 user         0.13 sys

$ /usr/bin/time node_modules/.bin/tsc --allowJs parser.min.js --out out.min.js
        4.29 real         5.08 user         0.14 sys
```

**Comment by alan-agius4** [comment] 2019-05-28 07:05
Thanks @kzc for looking into this and for all the information provided. That is awesome :). Well done!

**Comment by artuska** [comment] 2019-07-03 21:45
Run into this issue — the problem is in `angular.json` config:

change

    "sourceMap": true,

to

    "sourceMap": false,

**Comment by vtolstov** [comment] 2019-07-25 09:32
how to dealt that anjular 8.x needs typescript < 3.5.0 ?

**Comment by maxime1992** [comment] 2019-11-10 16:56
I've got:

- sourcemap set to false
- typescript 3.5.3
- @angular-devkit/build-angular 0.803.18
- @angular/cli 8.3.18
- @angular/* 8.2.13

and I still encounter that issue. Any idea how to fix it even with a temporary/ugly fix for now?
I can't compile :(

**Comment by alan-agius4** [comment] 2020-05-25 08:07
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2020-05-25 08:07 UTC
Labels: comp: devkit/build-optimizer, freq1: low, severity3: broken, type: bug/fix
