### ISSUE TITLE
Remove regex file type check on fileReplacements

### ISSUE THREAD

**Issue by stanislavromanov** [angular/angular-cli#25599] opened 2023-07-28 03:05 UTC
### Command

build

### Description

Currently when we use `fileReplacements` it will check the files for this regex pattern: `\.(([cm]?j|t)sx?|json)$`. I found it out by trying to replace `robots.production.txt` into `robots.txt`.

This is the config that I am using that throws this error:

```json
{
  "replace": "src/robots.txt",
  "with": "src/robots.production.txt"
}
```

The question is: Why limit file types onto this setting? I don't see the benefit and only drawbacks as I have experienced currently.

### Describe the solution you'd like

I would like to remove regex filetype check on `fileReplacements` property.

### Describe alternatives you've considered

Only alternative is to run a custom shell script that would do it for me before running `npm run build:production`.

**Comment by alan-agius4** [comment] 2023-07-28 07:32
Duplicate of https://github.com/angular/angular-cli/issues/20147

**Closed by alan-agius4** 2023-07-28 07:32 UTC
