### ISSUE TITLE
Uncaught Error: Missing: SyncTestZoneSpec (using webpack)

### ISSUE THREAD

**Issue by fulltilt** [angular/angular-cli#2590] opened 2016-10-08 18:30 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.4.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I get this whenever I run 'ng test'.

### The log given by the failure.
> Normally this include a stack trace and some more information.
Uncaught Error: Missing: SyncTestZoneSpec
  at /Users/daviddoria/Documents/Trigger/new/csx_triggers/trigger-search/src/test.ts:48356 <- webpack:///Users/daviddoria/Documents/Trigger/new/csx_triggers/trigger-search/~/zone.js/dist/jasmine-patch.js:19:0

### Mention any other details that might be useful.
I was originally on angular-cli@1.0.0-beta.11-webpack.8 and upgraded to the newest version of the CLI. The app works but when I tried ng test, I'm getting the error. I downgraded back to beta.11 and still get the error.

I looked up older issues with this problem but the solutions dealt with SystemJS configurations.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-10-10 13:13
Dupe of https://github.com/angular/angular-cli/issues/2036, see updated `test.ts`: https://github.com/angular/angular-cli/blob/master/packages/angular-cli/blueprints/ng2/files/__path__/test.ts

**Closed by filipesilva** 2016-10-10 13:13 UTC
