### ISSUE TITLE
@angular/ssr - how to handle responsiveness

### ISSUE THREAD

**Issue by zygarios** [angular/angular-cli#26459] opened 2023-11-21 23:13 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

With the new version of Angular and its migration to @angular/ssr, using 'ng serve' is not based on an Express server. How can I locally work on a project, including hydration, when some components are displayed only for mobile devices and others only for desktop? Previously, I could do this by passing the user-agent to the ngx-device-detector library and obtaining information about the user's device. Unfortunately, currently on localhost I do not have the ability to check what device it is because the REQUEST and RESPONSE have a value of null. As a result, it is difficult to work on the project. How can I deal with this?

`<div class="app">
  @if (!isMobile) {
  <app-header></app-header>
  }
  @if (isMobile) {
  <app-bottom-navbar></app-bottom-navbar>
  }
</div>
`

Currently, on the server side, the isMobile variable will always assume a hardcoded value, e.g. true, until it receives the correct value on the browser side. This causes incompatibility, e.g. in hydration, because the DOM layout on the browser will be different from the server.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0
```

**Comment by alan-agius4** [comment] 2023-11-22 10:25
Duplicate of https://github.com/angular/angular-cli/issues/26323 

Worth mentioning that in some of cases relying on user-agent sniffing is a bad idea see:
-  https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Closed by alan-agius4** 2023-11-22 10:25 UTC

**Comment by zygarios** [comment] 2023-11-22 14:34
Ok, but i dont know any other solution to handle it on server...

**Comment by thatsyishak** [comment] 2023-11-22 14:57
🥰🥰
