### ISSUE TITLE
Error: Cannot find module 'exists-sync'

### ISSUE THREAD

**Issue by michaelpumo** [angular/angular-cli#1191] opened 2016-06-24 09:54 UTC
**1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)**

Mac OSX El Capitan

**2. Versions. Please run `ng --version`.**

angular-cli: 1.0.0-beta.8
node: 5.8.0

**3. Repro steps. Was this an app that wasn't created using the CLI? What change did you do on your code? etc.**
   
CLI only. From scratch.

**4. The log given by the failure. Normally this include a stack trace and some
   more information.**

```
ng generate component card
module.js:341
    throw err;
    ^

Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/raggededge/Desktop/moveable/moveable/node_modules/angular-cli/node_modules/ember-cli/lib/models/project.js:11:26)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
fatal: no upstream configured for branch 'master'
fatal: no upstream configured for branch 'master'
-bash: [: 55d540eba0a5efa18bdaad19112caf63a0e1a584: unary operator expected
-bash: [: 55d540eba0a5efa18bdaad19112caf63a0e1a584: unary operator expected
```

**5. Mention any other details that might be useful.**

Followed the guide here: https://github.com/angular/angular-cli
Successfully created the project and installed the dependencies.
Once complete, I tried running 'ng generate component card' and got the above errors. Think it might have something to do with Git? But the setup guide mentions nothing of Git.

**Comment by zhaoshengjun** [comment] 2016-06-24 10:39
I just fixed this issue by installing the missing module.

The issue is likely caused by ember-cli.

Should be easy to fix.

**Comment by MrCroft** [comment] 2016-06-24 12:14
#1186

**Comment by Splaktar** [comment] 2016-06-26 16:10
Duplicate of https://github.com/angular/angular-cli/issues/1186. This should be closed.

**Closed** 2016-06-30 12:18 UTC
