### ISSUE TITLE
Using Angular proxy is ignoring withCredentials:false flag

### ISSUE THREAD

**Issue by jarri-official** [angular/angular-cli#24509] opened 2023-01-10 11:24 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Using Angular Proxy and HttpClient while creating an HTTP request with `withCredentials` set to `false` (or left empty, with the default value of `false`) will attach cookies to the request like in the scenario when `withCredentials` flag is set to `true`. It is not possible to make an HTTP request with no `Cookie` param in headers by setting `withCredentials` to `false`. This bug is occurring only while using Angular Proxy. While using the development server without proxy or on production build, this bug will not occur.

### Please provide the exception or error you saw

```true
No exceptions or errors.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node : 18.12.0
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 14.6.4
   @nrwl/angular : 14.6.4
   @nrwl/cypress : 14.6.4
   @nrwl/devkit : 14.6.4
   @nrwl/eslint-plugin-nx : 14.6.4
   @nrwl/express : 15.0.0
   @nrwl/jest : 15.0.0
   @nrwl/js : 14.6.4
   @nrwl/linter : 14.6.4
   @nrwl/node : 15.0.0
   @nrwl/storybook : 14.6.4
   @nrwl/web : 14.6.4
   @nrwl/workspace : 14.6.4
   typescript : 4.7.4
```

**Comment by alan-agius4** [comment] 2023-01-10 14:13
Hi @jarri-official, can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2023-01-23 11:23
Closing due to the lack of a reproduction. None-the-less, if there is an issue this is likely in https://github.com/chimurai/http-proxy-middleware.

**Closed by alan-agius4** 2023-01-23 11:23 UTC
Labels: needs: repro steps
