### ISSUE TITLE
No any error output when used `ng serve --aot` in project which has errors

### ISSUE THREAD

**Issue by vadimzham** [angular/angular-cli#2667] opened 2016-10-12 13:05 UTC
> Please provide us with the following information:

No any error output when used `ng serve --aot` in project which has errors(compilation fails).
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux(Ubuntu 16.04)
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: local (v1.0.0-beta.17, branch: master)
node: 6.7.0
os: linux x64
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
### The log given by the failure.

> Normally this include a stack trace and some more information.

I getting this log with "infinite building":
`ng serve --aot
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
** NG Live Development Server is running on http://localhost:4200. **
 23% building modules 109/109 modules 0 active`
But nothing of errors. 
### Mention any other details that might be useful.

With normal `ng-serve` project successfully builds but has intentional error which appears in browser console - not imported "angular2-text-mask" package(but it's functionality used in template).

> Thanks! We'll be in touch soon.

**Comment by criticalpixel** [comment] 2016-10-13 09:33
Same issue here, running on OSX(El Capitan)

```
20% building modules 86/86 modules 0 activeoDataConfig
```

**Comment by filipesilva** [comment] 2016-10-14 18:24
Does it repeatedly rebuild as well, is that it?

**Comment by vadimzham** [comment] 2016-10-17 15:58
No, it's just keep in this state permanently. No any rebuild.

**Comment by Simon-Briggs** [comment] 2016-10-20 05:39
I faced this as well.

ng serve --aot simply hangs at 20%.

ng build --aot showed me the problem.

```
AppModule is not an NgModule
Error: AppModule is not an NgModule
```

**Comment by inska** [comment] 2016-10-25 06:25
same here

> AppModule is not an NgModule
> Error: AppModule is not an NgModule

**Comment by Meligy** [comment] 2016-10-31 11:58
Same here with beta.19-3.

Both outputs from `serve --aot` and `build --aot` happening to me.

For `serve --aot`, if I navigate to `http://localhost:4200` while it's waiting, it adds this new line to the terminal console (not the browser console, the browser just times out after a while):

```
webpack: wait until bundle finished: /
```

**Comment by Meligy** [comment] 2016-10-31 12:09
I have upgraded my test repo to beta.19-3 if this helps with testing:

https://github.com/meligy/routing-angular-cli

**Comment by erycson** [comment] 2016-11-01 13:27
same here

**Comment by masterfix** [comment] 2016-11-03 13:17
Same problem here. Not with the AppModule but with another module.

**Comment by montella1507** [comment] 2016-11-09 03:07
Same here.

**Comment by irvjc82** [comment] 2016-11-09 14:53
Same problem here 

<pre>10% building modules 2/2 modules 0 activeError: AppModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (C:\Users\Irvin\WebstormProjects\nexus4_angular_cli\node_modules\@ngtools\webpack\src\plugin.js:247:19)
    at AotPlugin._processNgModule (C:\Users\Irvin\WebstormProjects\nexus4_angular_cli\node_modules\@ngtools\webpack\src\plugin.js:230:42)
    at C:\Users\Irvin\WebstormProjects\nexus4_angular_cli\node_modules\@ngtools\webpack\src\plugin.js:206:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
AppModule is not an NgModule
Error: AppModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (C:\Users\Irvin\WebstormProjects\nexus4_angular_cli\node_modules\@ngtools\webpack\src\plugin.js:247:19)
    at AotPlugin._processNgModule (C:\Users\Irvin\WebstormProjects\nexus4_angular_cli\node_modules\@ngtools\webpack\src\plugin.js:230:42)
    at C:\Users\Irvin\WebstormProjects\nexus4_angular_cli\node_modules\@ngtools\webpack\src\plugin.js:206:23
    at process._tickCallback (internal/process/next_tick.js:103:7)</pre>

**Comment by unsafecode** [comment] 2016-11-10 09:46
+1 Have the same issue with `@ngtools/webpack` and a lazy route

**Comment by ajantsch** [comment] 2016-11-10 18:35
+1 what @unsafecode said, same problem with @ngtools/webpack and a lazy route.

**Comment by riparrag** [comment] 2016-11-10 19:09
same here
activeError: AppModule is not an NgModule

**Comment by Judahh** [comment] 2016-11-11 13:59
Same here

**Comment by mallim** [comment] 2016-11-13 02:23
angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: win32 x64

````
Error: LazyLoadedModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (root_folder\node_modules\@ngtools\webpack\src\plugin.js:247:19)
    at AotPlugin._processNgModule (root_folder\node_modules\@ngtools\webpack\src\plugin.js:230:42)
    at AotPlugin._processNgModule (root_folder\node_modules\@ngtools\webpack\src\plugin.js:239:33)
    at root_folder\node_modules\@ngtools\webpack\src\plugin.js:206:23
````

In app.routing.ts:

````
      {
        path: 'lazy_loaded',
        loadChildren: 'app/lazy_loaded/lazy_loaded.module#LazyLoadedModule'
      }
````

**Comment by indooorsman** [comment] 2016-11-16 03:55
+1 
```
getNgModuleMetadata of StaticSymbol {
  filePath: '/Users/indooorsman/workspace/projects/web/yingke/server/ykly-toc-web/src/main/webapp/spa_src/src/app/app.module.ts',
  name: 'AppModule',
  members: undefined }
get annotations: []
Error: AppModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (/Users/indooorsman/workspace/projects/web/yingke/server/ykly-toc-web/src/main/webapp/spa_src/node_modules/@ngtools/webpack/src/plugin.js:249:19)
    at AotPlugin._processNgModule (/Users/indooorsman/workspace/projects/web/yingke/server/ykly-toc-web/src/main/webapp/spa_src/node_modules/@ngtools/webpack/src/plugin.js:230:42)
```

**Comment by ovrmrw** [comment] 2016-11-19 07:06
same here `"angular-cli": "1.0.0-beta.19-3"`
```
** NG Live Development Server is running on http://localhost:4200. **
 10% building modules 2/2 modules 0 active(node:1276) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: AppModule is not an NgModule
 20% building modules 84/84 modules 0 active
```

**Comment by ctrl-brk** [comment] 2016-11-20 08:41
Still in beta.20-4

**Comment by dmittendorf** [comment] 2016-11-28 20:47
Same problem with 1.0.0-beta.21

**Comment by intergleam** [comment] 2016-12-06 13:20
same thing here, seems like caused by this [issue](https://github.com/oferh/ng2-completer/issues/60)

`ng serve` just freezes

**Comment by arlowhite** [comment] 2016-12-13 20:37
I have this problem with angular-cli: **1.0.0-beta.22-1**
I do have lazy-loaded modules in _app-routing.module.ts_

Same code worked fine with version 1.0.0-beta.19-3

**Comment by aaronleeucla** [comment] 2016-12-13 21:03
My ng serve hanging went away after I updated /src/tsconfig.json to the one generated by beta.22

**Comment by intergleam** [comment] 2016-12-14 08:15
the way i deal with it is I run `ng build` and see where is the error actually

**Comment by frank-mendez** [comment] 2016-12-14 08:21
+1 20% building modules 84/84 modules 0 activewebpack: wait until bundle finished:
What is the possible solution for this?

**Comment by arlowhite** [comment] 2016-12-14 19:31
From what I've seen here and on https://github.com/angular/angular-cli/issues/3157 and https://github.com/angular/angular-cli/issues/3426

Most problems seem to be caused by people jumping ahead to a newer version of Angular or TypeScript.

Double-check **package.json**
For an **angular-cli 1.0.0-beta.22-1** project, you should be on:

- Angular 2.2.3 (@angular/* packages)
 - Don't forget `"@angular/compiler-cli": "2.2.3"` (under devDependencies)
- @angular/router 3.2.3
- typescript 2.0.10  (default version is ~2.0.3)

You should use `ng init --skip-npm` to diff your package.json with the default. Or create a fresh project somewhere else `ng new --skip-npm fresh-ng-project` and use your favorite diff tool to compare your package.json with the default.

After you've double-checked your package.json, `npm install`

If that doesn't fix it, some people have said changes they made to **tsconfig.json** caused the problem. So review that diff as well.

Otherwise, review how your module is exported. In my project, one module was
`export default class MyModule {}`
**export default** no longer works.

Remove `default`, if this is a lazy-loaded module in the router, you will need to add `#MyModule`
 `loadChildren: 'app/path/to/my.module#MyModule'`

**Comment by meghadureja** [comment] 2017-01-28 13:13
getting below error while running **ng build** command.

**No errors
Error: No errors**
    at validate (/home/meghad/testingWorkspace/web/node_modules/extract-text-webpack-plugin/schema/validator.js:10:9)
    at Function.ExtractTextPlugin.extract (/home/meghad/testingWorkspace/web/node_modules/extract-text-webpack-plugin/index.js:188:3)
    at /home/meghad/testingWorkspace/web/node_modules/angular-cli/models/webpack-build-utils.js:72:77
    at Array.map (native)
    at Object.makeCssLoaders (/home/meghad/testingWorkspace/web/node_modules/angular-cli/models/webpack-build-utils.js:69:53)
    at Object.getWebpackCommonConfig (/home/meghad/testingWorkspace/web/node_modules/angular-cli/models/webpack-build-common.js:77:65)
    at new NgCliWebpackConfig (/home/meghad/testingWorkspace/web/node_modules/angular-cli/models/webpack-config.js:22:49)
    at Class.exports.default.Task.extend.run (/home/meghad/testingWorkspace/web/node_modules/angular-cli/tasks/build-webpack.js:18:22)
    at Class.Command.extend.run (/home/meghad/testingWorkspace/web/node_modules/angular-cli/commands/build.js:60:26)
    at Class.<anonymous> (/home/meghad/testingWorkspace/web/node_modules/angular-cli/ember-cli/lib/models/command.js:152:17)
    at tryCatch (/home/meghad/testingWorkspace/web/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/home/meghad/testingWorkspace/web/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at /home/meghad/testingWorkspace/web/node_modules/es6-promise/dist/es6-promise.js:172:16
    at flush (/home/meghad/testingWorkspace/web/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

**Comment by iamgmd** [comment] 2017-01-28 13:43
getting same as meghadureja on ng build or ng serve

**Comment by Equinox** [comment] 2017-01-28 14:12
@iamgmd 

Hi there, you're after https://github.com/angular/angular-cli/issues/4264 for the current issue, with a working workaround in that thread.

**Comment by iamgmd** [comment] 2017-01-28 14:22
@equinox

Thanks, just seen that after I posted. Thanks for redirect.

**Comment by hansl** [comment] 2017-02-03 20:21
Closing this as fixed.

**Closed by hansl** 2017-02-03 20:21 UTC
Labels: command: build, feature: aot, priority: 1 (urgent), type: bug
