### ISSUE TITLE
Can't customize path for lazy loaded module chunks

### ISSUE THREAD

**Issue by SamShekhovtsov** [angular/angular-cli#22418] opened 2021-12-22 15:37 UTC
# 🐞 Bug report
Provided that Angular files are served not from the application root, but custom folder, there is no way to customize path for loaded chunks.

### Is this a regression?
no

### Description

Let's say that there is a multi - modular Angular 13 application, where modules are loaded using lazy - loading. The problem happens when the generated Angular files like main.[hash].js, pollyfils.[hash].js and runtime.[hash].js are located NOT at the site root. The structure looks like following:

/index.html
  /mysitefolder/main.f29052602897eb02.js
  /mysitefolder/styles.755cfc65dad8627d.css
  /mysitefolder/polyfills.eca354b64e370005.js
  /mysitefolder/runtime.54752149a889ba60.js
  /mysitefolder/815.d3bd01384abd247c.js

When application runs, it tries to load the chunk file 815.d3bd01384abd247c.js from the application root, not from it's actual location, obviously chunk load fails. There is no configuration to customize chunk base path.

## 🔬 Minimal Reproduction

Create a simple Angular application, where files are located not at the server root but at the custom directory. The chunks are not loaded. For this example, let's say that the Angular.json file has following setting:

"outputPath": "../public/mysitefolder"

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.2
Node: 12.22.7
Package Manager: npm 8.1.0
OS: linux x64

Angular: 13.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@schematics/angular             13.0.2
rxjs                            7.4.0
typescript                      4.4.4

</code></pre>

**Anything else relevant?**

**Comment by eneajaho** [comment] 2021-12-23 10:23
Hello, 
you may want to take a look at: [Base Href](https://angular.io/guide/deployment#the-base-tag).

You can you try to change `baseHref` in `index.html` to "/mysitefolder/" and see if that works.

**Comment by SamShekhovtsov** [comment] 2021-12-24 23:30
Hi,
 Thanks for the suggestion, I've already investigated it and tried Base Ref, it doesn't solve the problem. If I specify the Base Ref chunks are still loaded from the site root. It has no effect at all. The chunk load fails.


> Hello, you may want to take a look at: [Base Href](https://angular.io/guide/deployment#the-base-tag).
> 
> You can you try to change `baseHref` in `index.html` to "/mysitefolder/" and see if that works.

**Comment by alan-agius4** [comment] 2022-01-10 08:48
Hi @SamShekhovtsov, 

Using the base href option should result in the desired outcome. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2022-01-17 10:34
Closing since no reproduction was provided. 

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem. 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Closed by alan-agius4** 2022-01-17 10:34 UTC
Labels: need: repro steps
