### ISSUE TITLE
Angular-cli@Webpack: error when creating a module

### ISSUE THREAD

**Issue by kassimorra** [angular/angular-cli#2022] opened 2016-09-08 12:51 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7 - 64bits

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
c:\Users\kborra\web\pp>ng --version                                                                                                                                                           
angular-cli: 1.0.0-beta.11-webpack.8                                                                                                                                                          
node: 5.4.0                                                                                                                                                                                   
os: win32 x64   

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Created the app with the CLI. I added bootstrap and jquery to angular-cli.json.
The error only happens when I tried ng g module report.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
c:\Users\kborra\web\pp>ng g module report                                                                                                                                                     
installing module                                                                                                                                                                             
  create src\app\report\report.module.ts                                                                                                                                                      
installing component                                                                                                                                                                          
  create src\app\report\report.component.css                                                                                                                                                  
  create src\app\report\report.component.html                                                                                                                                                 
  create src\app\report\report.component.spec.ts                                                                                                                                              
  create src\app\report\report.component.ts                                                                                                                                                   
Cannot apply a change to a different path.                                                                                                                                                    
Error: Cannot apply a change to a different path.                                                                                                                                             
    at MultiChange.appendChange (C:\Users\kborra\AppData\Roaming\npm\node_modules\angular-cli\packages\ast-tools\src\change.ts:41:19)                                                         
    at C:\Users\kborra\AppData\Roaming\npm\node_modules\angular-cli\packages\ast-tools\src\change.ts:32:86                                                                                    
    at Array.forEach (native)                                                                                                                                                                 
    at new MultiChange (C:\Users\kborra\AppData\Roaming\npm\node_modules\angular-cli\packages\ast-tools\src\change.ts:32:45)                                                                  
    at C:\Users\kborra\AppData\Roaming\npm\node_modules\angular-cli\packages\ast-tools\src\ast-utils.ts:227:16                                                                                
    at lib$es6$promise$$internal$$tryCatch (c:\Users\kborra\web\pp\node_modules\es6-promise\dist\es6-promise.js:362:16)                                                                       
    at lib$es6$promise$$internal$$invokeCallback (c:\Users\kborra\web\pp\node_modules\es6-promise\dist\es6-promise.js:374:17)                                                                 
    at lib$es6$promise$$internal$$publish (c:\Users\kborra\web\pp\node_modules\es6-promise\dist\es6-promise.js:345:11)                                                                        
    at lib$es6$promise$asap$$flush (c:\Users\kborra\web\pp\node_modules\es6-promise\dist\es6-promise.js:119:9)                                                                                
    at nextTickCallbackWith0Args (node.js:456:9)                                                                                                                                              
    at process._tickCallback (node.js:385:13)      

5. Mention any other details that might be useful.
I´m using RC6. I don´t know if its a real error ou just an error message with no impact.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by chozzz** [comment] 2016-09-08 14:54
I've also experienced the same error when executing `ng g c MyComponent`. I noticed that I had to remove `MyComponent` from `app.module.ts`  since it was previously created and the angular cli automatically generated the imports and added it to declaration.

**Comment by filipesilva** [comment] 2016-09-19 02:53
@Brocco can you have a look?

**Comment by Brocco** [comment] 2016-09-24 03:24
@kassimorra & @chozzz have you been able to reproduce this issue with the latest version of the CLI (currently beta15)?

There have been improvements surrounding adding new generations to modules since reported.

I am closing this for now, but if you're still experiencing an issue comment here and I can reopen the issue.

**Closed by Brocco** 2016-09-24 03:24 UTC
Labels: command: generate, priority: 1 (urgent), type: bug

**Comment by kassimorra** [comment] 2016-09-24 14:19
Hi @brocco. 

I'm using the currently version and it works nice. 

Thanks 

Kassim
