### ISSUE TITLE
Beta.11-webpack mobile mode generates incorrect app.component.ts

### ISSUE THREAD

**Issue by FraserKillip** [angular/angular-cli#1534] opened 2016-08-03 07:21 UTC
Hey all,

1. MacOS 10.12 Sierra Public Beta

2. Versions.
angular-cli: 1.0.0-beta.11-webpack
node: 5.7.1
os: darwin x64

3. After running the following command:
`
ng new foo2 --style=less --mobile
`
The file src/app/app.component.ts has a component definition that uses a `template` rather than using a `templateUrl` for the generated app.component.html

4. No error given, but uses wrong template.

5. Tested without using the --mobile flag and it works as expected (uses `templateUrl` for app.component.html)

**Comment by filipesilva** [comment] 2016-08-10 16:54
Dupe of https://github.com/angular/angular-cli/issues/1371

**Closed by filipesilva** 2016-08-10 16:54 UTC
