### ISSUE TITLE
Angular 12 and Node 16 error

### ISSUE THREAD

**Issue by sergey-morenets** [angular/angular-cli#20833] opened 2021-05-18 08:34 UTC
Hi

I tried to upgrade Angular 11.2.8 -> 12.0.0 using this command:

`ng update @angular/cli @angular/core @angular/material`

but received an error:

`Installing packages (yarn)...error @angular/animations@12.0.0: The engine "node" is incompatible with this module. Expected version "^12.14.1 || ^14.0.0". Got "16.1.0"`

**Comment by alan-agius4** [comment] 2021-05-18 08:51
Duplicate of https://github.com/angular/angular/issues/42076

**Closed by alan-agius4** 2021-05-18 08:51 UTC
