### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by mmonteiroc** [angular/angular-cli#21179] opened 2021-06-22 13:28 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 11

### Description

We just migrated to angular 12 and now when I'm serving the application (ng serve) it compiles properly... after a few minutes passed, the serve does a re-compile (like if I did a change in the codebase - which I don't) and when it's re-compiling it crashes with a heap out of memory

## 🔥 Exception or Error

<pre><code>
⠋ Generating browser application bundles...
>)
    2: addContextTimestamps [000002B782A1F6D9] [C:\DEV\FrontendService\Client\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\FileS...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7D807035F napi_wrap+119615
 2: 00007FF7D8017666 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NextTableOffset+38102
 3: 00007FF7D8018466 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NextTableOffset+41686
 4: 00007FF7D885451E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7D883C6C1 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF7D86EDE9C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7D86F90E0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF7D86F5BF4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF7D86EB3F3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF7D86EA7E4 v8::internal::Heap::CollectAllAvailableGarbage+196
11: 00007FF7D86E9AE4 v8::internal::Heap::AddRetainedMap+2628
12: 00007FF7D870AEEB v8::internal::Factory::NewFixedArrayWithFiller+107
13: 00007FF7D8703D77 v8::internal::Factory::InternalizeString<unsigned short>+471
14: 00007FF7D853DC2B v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::Allocate+123
15: 00007FF7D853FD7B v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::Rehash+59
16: 00007FF7D853ED0A v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::EnsureGrowable+9017: 00007FF7D8489DC2 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+114882
18: 00007FF7D8CA993D v8::internal::SetupIsolateDelegate::SetupHeap+546925
19: 00007FF7D8C6E59A v8::internal::SetupIsolateDelegate::SetupHeap+304330
20: 000002CF3BCD87DB
</code></pre>

## 🌍 Your Environment

<pre><code>
Your global Angular CLI version (12.0.5) is greater than your local version (12.0.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.4
Node: 12.19.0
Package Manager: npm 6.14.7
OS: win32 x64

Angular: 12.0.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.4
@angular-devkit/build-angular   12.0.4
@angular-devkit/core            12.0.4
@angular-devkit/schematics      12.0.4
@schematics/angular             12.0.4
rxjs                            7.1.0
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

**Comment by meriturva** [comment] 2021-06-22 14:12
Duplicate of https://github.com/angular/angular-cli/issues/20801

**Comment by zwjohn** [comment] 2021-06-22 22:49
Getting OOM error too with ng serve after a few changes, using 12.0.5.
                        "development": {
                            "buildOptimizer": false,
                            "optimization": false,
                            "vendorChunk": true,
                            "extractLicenses": false,
                            "sourceMap": true,
                            "namedChunks": true
                        }

Build at: 2021-06-22T22:38:36.527Z - Hash: a6f07c35cd6b1ca3f5bc - Time: 26795ms

√ Compiled successfully.
/ Generating browser application bundles (phase: building)...
<--- Last few GCs --->

[23276:000001B72A84CC00] 28646151 ms: Scavenge (reduce) 2029.3 (2051.4) -> 2028.6 (2052.7) MB, 4.5 / 0.0 ms  (average mu = 0.167, current mu = 0.085) allocation failure
[23276:000001B72A84CC00] 28646893 ms: Mark-sweep (reduce) 2029.4 (2054.7) -> 2027.9 (2054.8) MB, 741.3 / 0.1 ms  (average mu = 0.228, current mu = 0.288) allocation failure scavenge might
not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF761993E0F napi_wrap+108911
 2: 00007FF761937E16 v8::base::CPU::has_sse+61910
 3: 00007FF761938D16 node::OnFatalError+294
 4: 00007FF762210CEE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7621F5ACD v8::SharedArrayBuffer::Externalize+781
 6: 00007FF76209F95C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF7620AACEA v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
 8: 00007FF7620A7E99 v8::internal::Heap::PageFlagsAreConsistent+2457
 9: 00007FF76209CA71 v8::internal::Heap::CollectGarbage+2033
10: 00007FF76209AC95 v8::internal::Heap::AllocateExternalBackingStore+1349
11: 00007FF7620BAFEB v8::internal::Factory::NewFillerObject+203
12: 00007FF761DE9F81 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1409
13: 00007FF762299BAD v8::internal::SetupIsolateDelegate::SetupHeap+465229
14: 00000242DE2099AF

**Comment by alan-agius4** [comment] 2021-06-23 05:26
Duplicate of #20801.

@mmonteiroc please update to the latest version.

@zwjohn and @mmonteiroc if the issue persists with the latest patch release please provide a reproduction or heap snapshots. See https://github.com/angular/angular-cli/issues/20801#issuecomment-843977643

**Closed by alan-agius4** 2021-06-23 05:26 UTC
