### ISSUE TITLE
generator module flag not working

### ISSUE THREAD

**Issue by westlakem** [angular/angular-cli#10995] opened 2018-05-24 15:09 UTC
### Versions
```
Angular CLI: 6.0.3
Node: 8.9.4
OS: win32 x64
Angular: 6.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cdk                      6.1.0
@angular/material                 6.1.0
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
* Step 1: Generate a new angular project
* Step 2: run `ng generate service MyService --module="app.module"`

### Observed behavior

The service does not get included in app.module.ts

### Desired behavior
The service should be included in app.module.ts

**Comment by araad** [comment] 2018-06-03 04:59
I'm having the same issue when I generate a service or a guard

**Comment by hansl** [comment] 2018-06-07 17:55
With Tree-shakable providers, you no longer need to provide your service in a module. This is a new feature in Angular 6 that makes it easier to setup and use services, and tree shake them away when they're not needed.

Closing this as Working as Intended.

**Closed by hansl** 2018-06-07 17:55 UTC
Labels: comp: cli/generate
