### ISSUE TITLE
live reload doesnt work with long path to root folder

### ISSUE THREAD

**Issue by polyglotinc** [angular/angular-cli#6981] opened 2017-07-14 20:14 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.0
node: 6.11.0
os: darwin x64

### Repro steps.

cd ~/Desktop
ng new foo
cd foo
ng serve
> change a source file, and live reload works!
> but same thing in a deep base directory fails! e.g.....

cd /Users/rbw/Workspaces/Eclipse 4.6 Neon (from new mini 3.6-Kepler)/www.example.com/WebContent/_AngularCliTutorial/demoApp

> do identical actions and live reload never works

### Desired functionality.

obviously, live reload should work regardless of path

**Comment by polyglotinc** [comment] 2017-07-14 20:17
With that path, other possible candidates are:
- doesnt like spaces in path?
- doesnt like special characters in path?

**Comment by filipesilva** [comment] 2017-07-28 10:44
This issue is a duplicate of https://github.com/angular/angular-cli/issues/1610, where these and other limitations are known and being tracked.

**Closed by filipesilva** 2017-07-28 10:44 UTC
