### ISSUE TITLE
lint --files requires array, cannot lint single file

### ISSUE THREAD

**Issue by erika9star** [angular/angular-cli#13668] opened 2019-02-13 15:00 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 No

### Description

 Cannot lint a single file using ng lint's --files parameter

## 🔬 Minimal Reproduction
```
ng new test-app
cd ../test-app
ng lint --files "src/app/app.component.ts"
```

## 🔥 Exception or Error
<pre><code>
Schema validation failed with the following errors:
  Data path ".files" should be array.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 6.2.9
Node: 8.12.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4
</code></pre>

**Comment by cexbrayat** [comment] 2019-06-15 16:00
This is no longer an issue with CLI v8

```
ng lint --files src/app/app.component.ts 
Linting "test-project"...
All files pass linting.
```

This can probably be closed.

**Comment by alan-agius4** [comment] 2019-06-18 13:43
Thanks @cexbrayat for looking into this.

Closing as indeed this issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2019-06-18 13:43 UTC
Labels: comp: devkit/build-angular, freq1: low, severity3: broken, type: bug/fix
