### ISSUE TITLE
`ng new` New project error

### ISSUE THREAD

**Issue by psingl** [angular/angular-cli#7482] opened 2017-08-23 15:55 UTC
@angular/cli version 1.3.0
![image](https://user-images.githubusercontent.com/13885706/29625395-32fa6652-8849-11e7-9642-fb92d63f1966.png)

**Comment by quanterion** [comment] 2017-08-24 07:09
Can confirm with 1.4:

@angular/cli: 1.4.0-rc.0
node: 8.1.4
os: win32 x64

C:\>ng new myapp
Error: Path "myapp/src/" is invalid.
Path "myapp/src/" is invalid.

**Comment by AlainD-** [comment] 2017-08-24 21:39
seems like a duplicate of #7492

**Comment by Brocco** [comment] 2017-08-29 13:31
It does look like a duplicate, so I am closing this issue.

@psingl if you are still experiencing this issue, please create a new issue following the new issue template with additional information, including version numbers and steps to reproduce.

**Closed by Brocco** 2017-08-29 13:31 UTC

**Comment by psingl** [comment] 2017-08-29 14:01
Hey @Brocco I don't think this is the duplicate of any existing issue. The issue referred by @AlainD- in his comment above is something else which is experienced by user in @angular/cli version 1.4.0-rc.0 In version 1.3.2 there is no such error as referred to by @AlainD- The issue I'm talking about is for @angular/cli 1.3.2
