### ISSUE TITLE
SVG inlining with postcss-url not compatible with IE11

### ISSUE THREAD

**Issue by RoopeHakulinen** [angular/angular-cli#8937] opened 2017-12-19 12:43 UTC
### Versions
Possibly caused by [this commit](https://github.com/angular/angular-cli/commit/def8f6294a2a9af0468d8d0b2e1fff1774b2fcbb#diff-c9c80a591c7b05af6bb6a3ab25ca6a30) introduced in 1.6.0.

### Repro steps

Add an SVG image in CSS with `url('assets/pic.svg')`. This image needs to be small enough (less than 10kB) so that postcss-url does inline it as it is configured so.

### Observed behavior
Image is not shown.

### Desired behavior

Image should be shown.

### Mention any other details that might be useful (optional)
This is because the base64 encoding is not used and thus the image contains spaces in the produced inline SVG inside the `url('...')`. This again does not work in IE11 thus the images are not shown.

**Comment by clydin** [comment] 2017-12-21 15:13
Does this happen in both development and production build targets?

**Comment by RoopeHakulinen** [comment] 2017-12-22 11:11
Only for production as I analyzed it further and it is caused by [this commit](https://github.com/angular/angular-cli/commit/392a3935a757945be68dbde0c4bcc8d5b4aa7bd5) instead of the one I referenced initially. There on lines 80 to 87 is this:

**Comment by clydin** [comment] 2017-12-22 13:04
Those lines run in both production and development.  However, they appear to have exposed a defect in the css optimizer which is only run in production.  Master has some changes to css optimization.  As a result (and we'll run some tests to ensure), this should already be fixed in master and should be in the next minor version.

**Comment by filipesilva** [comment] 2018-01-02 17:01
I tested with `@angular/cli@1.6.3` using https://s.cdpn.io/3/kiwi.svg (3kb) and `body { background-image: url('./assets/kiwi.svg') }` in `src/styles.css`. Then I ran `npm run ng -- serve --prod` and opened the page in Internet Explorer 11. It seems to be fine now. 

@RoopeHakulinen let me know if you still see this with `1.6.3` and I will reopen.

**Comment by RoopeHakulinen** [comment] 2018-01-03 12:06
Nope still not working. I'll see if I can make a small project to reproduce.

Here's what happens
Original SVG:
```
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  <defs>
    <style>.cls-1{fill:#0051ba;}</style>
  </defs>
  <title>details-hover</title>
  <rect class="cls-1" x="11" y="11" width="2" height="5"/>
  <rect class="cls-1" x="11" y="8" width="2" height="2"/>
  <path class="cls-1"
        d="M12,20.8A8.8,8.8,0,1,1,20.8,12,8.81,8.81,0,0,1,12,20.8Zm0-16A7.2,7.2,0,1,0,19.2,12,7.21,7.21,0,0,0,12,4.8Z"/>
</svg>
```
CSS usage:
```
.icon-img {
  background-image: url('assets/icons/details-hover.svg');
}
```

Result in CSS:
```
background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg id='Layer_1' data-name='Layer 1' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cdefs%3E%3Cstyle%3E.cls-1{fill:%230051ba}%3C/style%3E%3C/defs%3E%3Ctitle%3Edetails-hover%3C/title%3E%3Cpath class='cls-1' d='M11 11h2v5h-2zM11 8h2v2h-2z'/%3E%3Cpath class='cls-1' d='M12 20.8a8.8 8.8 0 1 1 8.8-8.8 8.81 8.81 0 0 1-8.8 8.8zm0-16a7.2 7.2 0 1 0 7.2 7.2A7.21 7.21 0 0 0 12 4.8z'/%3E%3C/svg%3E")
```

which does not work in IE11.

**Comment by RoopeHakulinen** [comment] 2018-01-03 13:32
@filipesilva Here's reproducable project: https://github.com/RoopeHakulinen/angular-cli-svg-ie11

Just clone and run 
```
npm install
npm start -- --prod
```

and compare Chrome and IE11.

**Comment by filipesilva** [comment] 2018-01-04 13:52
@RoopeHakulinen I can confirm it still happens in your repro. I tried adding my image  https://s.cdpn.io/3/kiwi.svg) to it as well and that one loads well though. Unsure what the difference is.

I also tried to use it in global vs component css but did not see any difference in behaviour: the kiwi image loaded always correctly but `details-hover.svg` only worked in dev while in ie11.

Worth mentioning in ie11 dev will have some core-js exception, but global styles still work.

@clydin do you know why the behaviour might be different?

**Comment by filipesilva** [comment] 2018-01-04 14:01
Spoke with @clydin offline:
> Can you try with master, if you have some time?  Cssnano had a SVG optimizer pass that I think doesn’t work with IE, but it’s gone now.

I tried with CLI master and both images show. It should be released next week as `1.6.4`.

**Closed by filipesilva** 2018-01-04 14:01 UTC
Labels: priority: 1 (urgent), severity4: regression, type: bug

**Comment by RoopeHakulinen** [comment] 2018-01-04 14:10
Great, thanks for the info :)

**Comment by RoopeHakulinen** [comment] 2018-01-12 10:12
1.6.4 does *not* fix this but 1.7.0-beta.0 seems to do the trick for the example project I've shared.

**Comment by clydin** [comment] 2018-01-13 12:50
That is correct.  1.6.4 above was a typo.  1.7.0-beta.0 has an improved stylesheet optimization pipeline which also addresses this issue.

**Comment by AustinMatherne** [comment] 2018-02-09 05:42
I ran into this today, as well. I'm able to workaround the issue by inlining styles in my SVGs.
