### ISSUE TITLE
Could not resolve module error reported only when build for production

### ISSUE THREAD

**Issue by jusfeel** [angular/angular-cli#9898] opened 2018-03-08 10:54 UTC
{ path: 'tasks', loadChildren: '../some-module/some-module.module#SomeModuleModule'}

When the path is wrong( 1 dot instead of 2 dots),  below error message would show up when build production, not "ng build" or "ng serve"

"ERROR in Could not resolve module"

### Versions
```
Angular CLI: 1.7.3
Node: 9.5.0
OS: linux x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.7.3
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack-bundle-analyzer: 2.11.1
webpack: 3.11.0
```
```
npm: 5.6.0
```
```
ubuntu 16.04
```
### Repro steps

* Step 1
Change ".." to "." in the path string
* Step 2
ng b
* Step 3
ng b --prod

**Comment by psiva017** [comment] 2018-05-22 14:00
I too facing the same issue. 
Any fix for this ?

**Comment by filipesilva** [comment] 2019-01-28 16:54
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by filipesilva** 2019-01-28 16:54 UTC
Labels: comp: devkit/build-angular
