### ISSUE TITLE
"ng update" not responding to input (yndH)

### ISSUE THREAD

**Issue by csis0247** [angular/angular-cli#4649] opened 2017-02-13 06:32 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Ubuntu 16.10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: linux x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Followed the instructions on README.md to update from beta25.5 to beta31, until the last step "ng update":
>Global package:
```bash
npm uninstall -g angular-cli @angular/cli
npm cache clean
npm install -g @angular/cli@latest
```

>Local project package:
```bash
rm -rf node_modules dist # use rmdir on Windows
npm install --save-dev @angular/cli@latest
npm install
ng update
```
and nothing happened on input ynd. H is responding normally.

### The log given by the failure.
> Normally this include a stack trace and some more information.

No error message. "ng update" just ended right after typing command and pressing "Enter", and nothing happened.
```bash
~/tutorials/angular-cli-app$ ng update
installing ng2
? Overwrite README.md? Diff
~/tutorials/angular-cli-app$ ng update
installing ng2
? Overwrite README.md? No, skip
~/tutorials/angular-cli-app$ ng update
installing ng2
? Overwrite README.md? Yes, overwrite
~/tutorials/angular-cli-app$ ng update
installing ng2
? Overwrite README.md? Yes, overwrite
~/tutorials/angular-cli-app$
``` 

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by kgtkr** [comment] 2017-02-13 07:24
Me too

**Comment by grizzm0** [comment] 2017-02-13 07:29
Dupe of #4584

**Comment by csis0247** [comment] 2017-02-13 08:57
Thanks. Didn't expect to search for closed issues.

**Comment by grizzm0** [comment] 2017-02-13 09:01
@csis0247 Could you close this issue?

**Closed** 2017-02-13 09:13 UTC
