### ISSUE TITLE
Way to easily Use LESS/SASS Variables in component LESS/SASS Files

### ISSUE THREAD

**Issue by jongunter** [angular/angular-cli#3535] opened 2016-12-12 22:43 UTC
Apologies if I'm posting this question in the wrong place, but I'm using a global style sheet, written in LESS. I have angular-cli configured to use LESS style sheets for each component, rather than CSS.  Is there a way for the CLI to generate components with my `variables.less` auto imported so I don't have to import them manually every time I want to use variables in a component's styles? Same goes for SASS.

**Comment by fural** [comment] 2016-12-13 17:37
I am facing the same situation, and I think that's the only way.

In my case I have to generate multiple themes. What I'm doing now is a gulp task that replace my `color-variables.sass` and execute the the `ng build` for each theme I have.

**Comment by filipesilva** [comment] 2016-12-30 12:53
Dupe of https://github.com/angular/angular-cli/issues/1791. Work ongoing in https://github.com/angular/angular-cli/pull/2747

**Closed by filipesilva** 2016-12-30 12:53 UTC
