### ISSUE TITLE
Chunk file is not created if routing is more than 2 level deep

### ISSUE THREAD

**Issue by plunker4madhu** [angular/angular-cli#3836] opened 2017-01-03 16:02 UTC
### OS?
> Windows 7

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: win32 x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

### Repro steps.
Chunk file is not being created for 3rd level lazy routed module.

### The log given by the failure.
No error while build or serve, errors out to fetch the Module while route is navigated.

### Mention any other details that might be useful.
Here is the Plunker **http://plnkr.co/edit/n5BkE5HNCK6uhDNbaZEB?p=preview** which works.
But when try to build this with Angular CLI, no chunk file is created for the 3rd level lazy loaded route.

**Comment by slubowsky** [comment] 2017-01-04 00:14
Duplicate. See https://github.com/angular/angular-cli/issues/3663

**Comment by hansl** [comment] 2017-01-04 00:32
Closing this as duplicate of #3663.

**Closed by hansl** 2017-01-04 00:32 UTC
