### ISSUE TITLE
Show build errors in the browser and/or browser console

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular-cli#20710] opened 2021-05-06 12:28 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem or missing capability...
Build errors appear in the terminal but are not displayed properly in the browser's console.
The errors are actually forwarded to the browser by the webpack dev server but the logged error is not human readable.

### Describe the solution you'd like

 If you have a solution in mind, please describe it.
It would be even nicer if the build error could be displayed in the "Failed to compile" overlay.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

<img width="689" alt="browser" src="https://user-images.githubusercontent.com/2674658/117297848-f84b7200-ae76-11eb-8cf5-08f08b85784c.png">
<img width="1423" alt="terminal" src="https://user-images.githubusercontent.com/2674658/117297851-fa153580-ae76-11eb-8112-f56ae3917a24.png">

**Comment by alan-agius4** [comment] 2021-05-07 07:27
Hi, it appears that the problem is in the `webpack-dev-server` which currently doesn't fully support Webpack 5.

I can see that this has been fixed in the next major version fo webpack-dev-server https://github.com/webpack/webpack-dev-server/blob/199baec187376213f55d8d0542798f4945b8cce5/client-src/index.js#L173, that being said it's still in beta.

**Closed by alan-agius4** 2021-05-07 07:27 UTC

**Comment by yjaaidi** [comment] 2021-05-08 00:47
Oh ok! Makes sense. Sorry for the noise
