### ISSUE TITLE
Error: set the style to scss 

### ISSUE THREAD

**Issue by sh107** [angular/angular-cli#4092] opened 2017-01-18 15:18 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.25.5
node: 7.2.1
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

I tried to change the style from css to scss using the following command

ng set defaults.styleExt scss

This gives the following error by running "ng serve"
### The log given by the failure.
> Normally this include a stack trace and some more information.

Path must be a string. Received { source: 'environments/environment.ts',
  dev: 'environments/environment.ts',
  prod: 'environments/environment.prod.ts' }
TypeError: Path must be a string. Received { source: 'environments/environment.ts',
  dev: 'environments/environment.ts',
  prod: 'environments/environment.prod.ts' }
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.getWebpackCommonConfig (/Users/sijinhe/WebstormProjects/ng2-phenomenal-portal/node_modules/angular-cli/models/webpack-build-common.js:102:25)
    at new NgCliWebpackConfig (/Users/sijinhe/WebstormProjects/ng2-phenomenal-portal/node_modules/angular-cli/models/webpack-config.js:24:49)
    at Class.run (/Users/sijinhe/WebstormProjects/ng2-phenomenal-portal/node_modules/angular-cli/tasks/serve-webpack.js:23:22)
    at /Users/sijinhe/WebstormProjects/ng2-phenomenal-portal/node_modules/angular-cli/commands/serve.run.js:37:22
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Mention any other details that might be useful.

I changed the angular-cli.json back to its original setting.
It now comes back to work. There must be something wrong happening using the command "ng set defaults.styleExt scss"

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment] 2017-01-18 20:06
@sh107 issue confirmed.

To manually switch to using `scss` please update the value of `defaults.styleExt` to `scss` in `angular-cli.json`.

**Comment by filipesilva** [comment] 2017-01-18 20:17
Dupe of https://github.com/angular/angular-cli/issues/4044

**Closed by filipesilva** 2017-01-18 20:17 UTC
