### ISSUE TITLE
Broken link on https://cli.angular.io/

### ISSUE THREAD

**Issue by ethancane** [angular/angular-cli#10650] opened 2018-05-04 19:48 UTC
Broken link on the https://cli.angular.io/ website in the footer (left hand side) attempting to link to: 
https://wwww.angular.io/

Too many w's in the subdomain it appears.

Hope this helps!

**Comment by msterba** [comment] 2018-05-04 21:58
Dupe of https://github.com/angular/angular-cli/issues/9730

**Closed** 2018-05-08 00:46 UTC
