### ISSUE TITLE
tree.branch is not a function error on ng new with custom schematics

### ISSUE THREAD

**Issue by Neonox31** [angular/angular-cli#8513] opened 2017-11-16 13:18 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0
Node: 8.9.1
NPM: 5.5.1
OS: linux x64
```

### Repro steps.
I created a package whiches copy exactly orignal angular schematics and try to initiate a new application using collection of my custom package using `ng new -c my-custom-schematics myapp`

here is a docker command to reproduce the problem in a clean environment : `docker run --rm node:8 sh -c 'npm i --unsafe-perm -g @angular/cli && git clone https://github.com/Neonox31/custom-schematics-example.git && cd custom-schematics-example/dist && npm pack && npm i -g my-custom-schematics && ng new -c my-custom-schematics myapp'`

The code of my custom schematics package is located here : https://github.com/Neonox31/custom-schematics-example

### The log given by the failure.
```
Error: tree.branch is not a function
tree.branch is not a function
```

### Desired functionality.
Application should be scaffolded using custom schematics and not print error messages.

/cc @davinkevin

**Comment by hansl** [comment] 2017-11-22 18:28
This should have been fixed with the latest Schematics, but I'll file an error on the DevKit repo to make sure we look at it.

**Comment by hansl** [comment] 2017-11-22 18:28
Actually already reported, so dupe of https://github.com/angular/devkit/issues/271

**Closed by hansl** 2017-11-22 18:28 UTC
