### ISSUE TITLE
DirectoryWatcher crashes during ng-serve

### ISSUE THREAD

**Issue by stannynuytkens** [angular/angular-cli#6749] opened 2017-06-20 07:18 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.1
node: 6.9.4
OS: Windows 7 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3

### Repro steps.
N/A

### The log given by the failure.
```
[root]\node_modules\watchpack\lib\DirectoryWatcher.js:288
DirectoryWatcher.prototype.getTimes = function() {
                                              ^

RangeError: Maximum call stack size exceeded
    at DirectoryWatcher.getTimes ([root]\node_modules\watchpack\lib\DirectoryWatcher.js:288:47)
    at DirectoryWatcher.<anonymous> ([root]\node_modules\watchpack\lib\DirectoryWatcher.js:306:35)
    at Array.forEach (native)
    at DirectoryWatcher.getTimes ([root]\node_modules\watchpack\lib\DirectoryWatcher.js:304:33)
    at DirectoryWatcher.<anonymous> ([root]\node_modules\watchpack\lib\DirectoryWatcher.js:306:35)
    at Array.forEach (native)
    at DirectoryWatcher.getTimes ([root]\node_modules\watchpack\lib\DirectoryWatcher.js:304:33)
    at DirectoryWatcher.<anonymous> ([root]\node_modules\watchpack\lib\DirectoryWatcher.js:306:35)
    at Array.forEach (native)
    at DirectoryWatcher.getTimes ([root]\node_modules\watchpack\lib\DirectoryWatcher.js:304:33)
    at DirectoryWatcher.<anonymous> ([root]\node_modules\watchpack\lib\DirectoryWatcher.js:306:35)
    at Array.forEach (native)
    at DirectoryWatcher.getTimes ([root]\node_modules\watchpack\lib\DirectoryWatcher.js:304:33)
    at DirectoryWatcher.<anonymous> ([root]\node_modules\watchpack\lib\DirectoryWatcher.js:306:35)
    at Array.forEach (native)
    at DirectoryWatcher.getTimes ([root]\node_modules\watchpack\lib\DirectoryWatcher.js:304:33)
```

### Desired functionality.
No `ng-serve` crash.

### Mention any other details that might be useful.
Just reporting this error, got this while adding a an application feature (component, service, ...)
Root folder in stack is obfuscated.

**Comment by filipesilva** [comment] 2017-06-26 15:03
Duplicate of https://github.com/angular/angular-cli/issues/6309, related to https://github.com/angular/angular-cli/issues/6739.

**Closed by filipesilva** 2017-06-26 15:03 UTC
