### ISSUE TITLE
Remove Project Name ... is Invalid from CLI ng new 

### ISSUE THREAD

**Issue by netlander** [angular/angular-cli#17932] opened 2020-06-14 17:45 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Simply remove the pointless error message when naming projects as `www.abcd.com` or `xyz-01`, etc...

### Describe the solution you'd like

Allowing the above mentioned names for project would be real helpful

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment] 2020-06-15 06:53
Duplicate of https://github.com/angular/angular-cli/issues/11051

**Closed by alan-agius4** 2020-06-15 06:53 UTC
