### ISSUE TITLE
ng serve does not generate service worker files

### ISSUE THREAD

**Issue by koenig-dominik** [angular/angular-cli#18876] opened 2020-09-24 20:21 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...
The command `ng serve` currently does not generate service worker files.
It may be because in the past it was not possible to register service workers in non SSL sites.
There is now a exception to that, all `http://localhost` or `http://127.x.y.z` addresses do work (at least in Chrome)
This was already shortly discussed in https://github.com/angular/angular-cli/issues/16883#issuecomment-650178791 but only the generation for `ng build --watch` was implemented.
`ng serve` & serve-ssr do not generate these files.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Generate the needed service worker files in `@angular-devkit/build-angular:dev-server` & `@nguniversal/builders:ssr-dev-server`

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
Build the universal server & run that without serve-ssr, which is really cumbersome in development

**Comment by alan-agius4** [comment] 2020-12-01 10:47
Duplicate of https://github.com/angular/angular-cli/issues/9869

**Closed by alan-agius4** 2020-12-01 10:47 UTC
Labels: comp: devkit/build-angular, devkit/build-angular: dev-server, type: feature
