### ISSUE TITLE
Generating directive inserts wrong file name in the barrel

### ISSUE THREAD

**Issue by Gelio** [angular/angular-cli#1434] opened 2016-07-23 10:33 UTC
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions
angular-cli: 1.0.0-beta.10
node: 6.2.2
os: win32 x64

3. Repro steps

``` bash
ng generate directive AnimateOnScroll
```
This creates the directive with a filename `animate-on-scroll.directive.ts` along with its spec file.
``` bash
  create src\app\shared\animate-on-scroll.directive.spec.ts
  create src\app\shared\animate-on-scroll.directive.ts
```
*index.ts* now contains the following line:
``` typescript
export * from './AnimateOnScroll.directive';
```
Which results in an error, because no such file exists. It should instead be:
``` typescript
export * from './animate-on-scroll.directive';
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Not related.

5. Mention any other details that might be useful.
It seems like the name of the file created is changed from PascalCase to kebab-case, but the entry in the barrel is not. I haven't dug inside angular-cli's code, so I can't help to identify in which file the issue is present, otherwise I would have made a pull request already.

**Comment by aciccarello** [comment] 2016-07-27 13:01
Possibly a duplicate of #1305?

**Comment by filipesilva** [comment] 2016-07-27 14:28
Dupe of https://github.com/angular/angular-cli/issues/1418, made obsolete by #1455.

**Comment by filipesilva** [comment] 2016-07-27 14:29
Oh my bad, it's not related to #1418 at all! Reopening.

**Comment by filipesilva** [comment] 2016-07-27 14:30
Yes dupe of #1305, but this issue contains more details useful for the fix so I will keep this one open.

**Comment by filipesilva** [comment] 2016-09-22 01:39
We don't automatically add stuff to barrels anymore, so this issue is now obsolete.

**Closed by filipesilva** 2016-09-22 01:39 UTC
Labels: command: generate, effort: (1) easy, type: bug
