### ISSUE TITLE
Angular.json ability to define shared app build configuration

### ISSUE THREAD

**Issue by mcm-ham** [angular/angular-cli#11299] opened 2018-06-19 04:26 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Desired functionality
I have a number of sub-projects that I would like the same build configuration apart from paths. In angular.json it would be helpful to have the ability to setup default build configurations that can apply to all projects (or ability for one app to refer to another apps build config).

**Comment by MickL** [comment] 2018-06-22 12:55
Duplicate of: https://github.com/angular/angular-cli/issues/11233
Also there is: https://github.com/angular/angular-cli/issues/10612

**Comment by kyliau** [comment] 2020-05-27 00:25
This has already been and addressed and fixed in https://github.com/angular/angular-cli/issues/10612

**Closed by kyliau** 2020-05-27 00:25 UTC
Labels: triage #1, type: feature
