### ISSUE TITLE
give use back webpack.config.js ;-)

### ISSUE THREAD

**Issue by mindruptive** [angular/angular-cli#2473] opened 2016-10-02 19:37 UTC
Environment: win10, node 6.5.0, npm 3.10.8, cli 1.0.0-beta.16
The current CLI does not create a webpack.config.js. In case we want more control over the packaging process, does it make sense to create our own one? Will it be used by the build process? If not, could you make the CLI create the webpack.config.js again?
Thanks a lot

**Comment by grizzm0** [comment] 2016-10-02 20:30
Duplicate of #1656

**Comment by mindruptive** [comment] 2016-10-02 20:32
thanks @grizzm0 , missed #1556

**Comment by filipesilva** [comment] 2016-10-02 20:50
Closed as duplicate.

**Closed by filipesilva** 2016-10-02 20:50 UTC
