### ISSUE TITLE
Newly created project doesn't work with docker and debug in Chrome extension in VSCode - sourcemap problem

### ISSUE THREAD

**Issue by erlloyd** [angular/angular-cli#7076] opened 2017-07-21 01:33 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

  ```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.2
node: 6.10.3
os: linux x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.2
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1
```
### Repro steps.

NOTE: This workflow works perfectly fine using `@angular/cli` 1.1.0. It breaks when using 1.1.1 and remains broken in the current version.

I have a sample repo setup here: https://github.com/erlloyd/ng-cli-vscode-error-sample

1) Make sure you have docker installed
2) Clone the above repo
3) In the repo directory, run `docker-compose build`
4) Run `docker-compose up`
5) Make sure you have VSCode and the 'Debugger for Chrome' extension installed (https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome)
6) Open the project in VSCode. Set a breakpoint in VSCode. I use line 12 of `app.component.ts`
7) Launch the debugger config in VSCode. It should be called 'launch sample against localhost'

EXPECTED: the breakpoint becomes active (red) after the page loads (note that it isn't necessarily going to hit the breakpoint due to startup race conditions)

ACTUAL: From ng versions 1.1.1 onward, the breakpoint remains grey with the error: `Breakpoint ignored because generated code not found (source map problem?).`

### Mention any other details that might be useful.
Note that this only occurs if the project is run through Docker. If I run the project on the local machine the breakpoints are hit without an issue. Could something have changed about where/how the sourcemaps are generated and stored?

Please let me know if you want any additional information and / or testing.

**Comment by filipesilva** [comment] 2017-07-31 11:15
Duplicate of https://github.com/angular/angular-cli/issues/6583, should be fixed in newer versions.

**Closed by filipesilva** 2017-07-31 11:15 UTC
