### ISSUE TITLE
`ng test` frequently crashes with "Missing error handler on `socket`."

### ISSUE THREAD

**Issue by maxfurman** [angular/angular-cli#2781] opened 2016-10-19 15:21 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.17
node: 6.8.1
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

This app was created using the CLI. When I am editing a `.spec.ts` file while the `ng test` server is running, it will frequently crash with the error pasted below.

I'm using VSCode and I have it set to autosave changes every few seconds. The crashes seem to occur when the test file has a typo or syntax error at the moment it saves.

### The log given by the failure.
Missing error handler on `socket`.
TypeError: Cannot read property 'set' of null
    at KarmaRemapIstanbul.onBrowserComplete (/Users/Max/projects/meal-planner/node_modules/karma-remap-istanbul/index.js:28:16)
    at Server.<anonymous> (/Users/Max/projects/meal-planner/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:111:20)
    at Server.emit (events.js:191:7)
    at Browser.onComplete (/Users/Max/projects/meal-planner/node_modules/karma/lib/browser.js:143:13)
    at Socket.<anonymous> (/Users/Max/projects/meal-planner/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:111:20)
    at Socket.emit (events.js:191:7)
    at Socket.onevent (/Users/Max/projects/meal-planner/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/Users/Max/projects/meal-planner/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/Users/Max/projects/meal-planner/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/Max/projects/meal-planner/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/Users/Max/projects/meal-planner/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/Users/Max/projects/meal-planner/node_modules/socket.io/lib/client.js:175:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Socket.onPacket (/Users/Max/projects/meal-planner/node_modules/engine.io/lib/socket.js:101:14)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at WebSocket.Transport.onPacket (/Users/Max/projects/meal-planner/node_modules/engine.io/lib/transport.js:104:8)
    at WebSocket.Transport.onData (/Users/Max/projects/meal-planner/node_modules/engine.io/lib/transport.js:115:8)
    at WebSocket.onData (/Users/Max/projects/meal-planner/node_modules/engine.io/lib/transports/websocket.js:76:30)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/Max/projects/meal-planner/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:816:10)
    at /Users/Max/projects/meal-planner/node_modules/engine.io/node_modules/ws/lib/Receiver.js:477:18
    at /Users/Max/projects/meal-planner/node_modules/engine.io/node_modules/ws/lib/Receiver.js:361:7
    at /Users/Max/projects/meal-planner/node_modules/engine.io/node_modules/ws/lib/PerMessageDeflate.js:247:5
    at afterWrite (_stream_writable.js:387:3)
    at onwrite (_stream_writable.js:378:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:639:5)
Chrome 53.0.2785 (Mac OS X 10.11.6) ERROR
  Disconnectedundefined

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-10-23 17:49
Heya, this is roughly a duplicate of https://github.com/angular/angular-cli/issues/2640, which https://github.com/angular/angular-cli/pull/2785 together with https://github.com/angular/angular-cli/pull/2840 should fix.

**Closed by filipesilva** 2016-10-23 17:49 UTC
Labels: command: test, need: investigation, priority: 1 (urgent), type: bug
