### ISSUE TITLE
Cli won't serve projects from a directory with '%20' in name

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular-cli#6162] opened 2017-05-03 10:56 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.10.1
os: win32 x64

### Repro steps.

1. `ng new testproj`
2. `ng serve` - everything works nicely
3. change the name of the testproj directory to test%20proj
4. navigate to **http://localhost:4200/**
5. See error `Cannot GET /`

### The log given by the failure.
N/A

### Desired functionality.
This used to be supported and has broken at some point since `-beta.21`. Ideally this would work and serve as expected. 

Failing that, a sensible warning about an invalid directory name would be great.

### Mention any other details that might be useful.

All other functions work fine, e.g. test and build

**Comment by filipesilva** [comment] 2017-05-08 09:54
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/6119. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-05-08 09:54 UTC
