### ISSUE TITLE
tsconfig.json typeRoots path ignores --source-dir

### ISSUE THREAD

**Issue by mh-dev** [angular/angular-cli#2550] opened 2016-10-06 13:42 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.16
node: 6.6.0
os: win32 x64
global install via
git clone https://github.com/angular/angular-cli.git
cd angular-cli
npm link 

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
mkdir
ng init --source-dir src/main/web

### The log given by the failure.
> Normally this include a stack trace and some more information.
ERROR in [default] {path}\src\main\web\app\app.component.ts:5:12
Cannot find name 'require'.
ERROR in [default] {path}\src\main\web\app\app.component.ts:6:11
Cannot find name 'require'.

### Mention any other details that might be useful.
The generated typeRoots is '../node_modules/@types' but it should be '../../../node_modules/@types'
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bthharper** [comment] 2016-10-08 19:08
If you've added a `types` element into `tsconfig.json`, then all the types are not included automatically by tsc only those specified, so you can either:

a) explicitly add "node"
b) or just add: `declare var required: any;` to `typings.d.ts`.

**Comment by mh-dev** [comment] 2016-10-08 23:35
Its not that I don't know a way to resolve this problem. But the generated project is just incorrect and this should be fixed in some way. I personally will take look into the cli in a few weeks again. Right now I am running into to much problems.

**Comment by bthharper** [comment] 2016-10-09 07:51
Sorry, I see your issue now.  Good luck with submitting a PR - sounds like a good fix to make.

**Comment by filipesilva** [comment] 2016-10-10 13:47
Dupe of #2206

**Closed by filipesilva** 2016-10-10 13:47 UTC
