### ISSUE TITLE
@angular/compiler-cli Incompatible peer dependencies found

### ISSUE THREAD

**Issue by enddering** [angular/angular-cli#13126] opened 2018-12-04 06:53 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

7.1.1

### The log given by the failure

`ng update --all `
`Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=3.1.1 <3.2", would install "3.2.1").`
`Incompatible peer dependencies found. See above.`

### Desired functionality

compatible ts 3.2.1

**Comment by alan-agius4** [comment] 2018-12-04 07:20
Duplicate of https://github.com/angular/angular-cli/issues/13095

**Closed by alan-agius4** 2018-12-04 07:20 UTC
