### ISSUE TITLE
Uncaught Error: Template parse errors: 'component' is not a known element:

### ISSUE THREAD

**Issue by TheDoozyLulu** [angular/angular-cli#8828] opened 2017-12-11 11:14 UTC
I am facing the problem in angular 4.4 , In my app, I have hierarchical view. In which I have created a:= module 1 -> module 2 -> my component.I have declared everything correctly. , But still I'm getting error.Declared component.Imported it into other module.selector name is same.Exported component in module 2.Imported module 2 in module 1.

**What could be the catch? Component Code: Admin -> Configuration -> mycomponent //My component**

My Code:=>

Component Code:
**Admin -> Configuration -> mycomponent**
//My component
import { Component, OnInit, ViewChild, ChangeDetectorRef } from '@angular/core';
@Component({
  selector: 'test-mycomponent',
  templateUrl: './mycomponent.component.html',
  styleUrls: ['./mycomponent.component.scss']
})
export class MyComponentComponent implements OnInit {
  @ViewChild('myComponentTable')

  constructor() {
    }
  ngOnInit() {
//init functionality
}
}

// configure module code 
import { NgModule,Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { MyComponentComponent } from './mycomponent/mycomponent.component';
@NgModule({
  imports: [
    CommonModule,
    WidgetsModule,
    FormsModule,
    NgbModule
  ],
  declarations: [
    MyComponent
  ],
  providers: [
  ],
  exports: [
    MyComponent
  ]
})
export class ConfigurationModule { }

//Main module admin
import { NgModule, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ConfigurationModule } from './configuration/configuration.module';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { MyComponentComponent } from './configuration/mycomponent/mycomponent.component';
import { FormsModule } from '@angular/forms';
@NgModule({
  imports: [
    CommonModule,
    NgbModule,
    FormsModule,
    ConfigurationModule
  ],
  declarations: [
  ],
  exports: [
     ]
})
export class AdminModule { }

and I am calling that template in another file
//Test file html 
    <ng-template>
          <test-mycomponent></test-mycomponent>
      </ng-template>

**Comment by Brocco** [comment] 2017-12-11 18:24
This issue is a support issue and not a bug or issue with the CLI itself. I suggest submitting your question where you can can some support/assistance such as [StackOverflow](https://stackoverflow.com/questions/tagged/angular-cli).
Closing this issue.

**Closed by Brocco** 2017-12-11 18:24 UTC

**Comment by marcobarbero** [comment] 2018-01-10 07:12
I think that the problem is the missing of _MyComponent_ in the _imports_ struct.

@NgModule({
imports: [
CommonModule,
NgbModule,
FormsModule,
ConfigurationModule,
**MyComponent**
],

You can see a simple example at this post:
https://expertcodeblog.wordpress.com/2018/01/09/how-to-resolve-uncaught-error-template-parse-errors-mycomponent-selector-name-is-not-a-known-element-on-angular/
