### ISSUE TITLE
Generators putting a backward slash in import path on Windows

### ISSUE THREAD

**Issue by jschwarty** [angular/angular-cli#2181] opened 2016-09-16 19:33 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.14
node: 6.3.1
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Have a dir in the `<project>/src/app` named `profile`.
With the current directory as the top level dir of the project, in the command/terminal run
 `ng g c profile/profile-tray` 
to generate a new component named `ProfileTrayComponent` within a dir named `profile`.
Look in the `app.module.ts` file and see the resulting import statement of
`import { ProfileTrayComponent } from './profile\profile-tray/profile-tray.component';`

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gelliott181** [comment] 2016-09-16 19:40
Just reproduced this.
Windows 10 x64
Angular-CLI 1.0.0-beta.14
Node 6.3.0
NPM 3.10.6

As for the cause, I think we can pinpoint the generate command as the source. It will work fine if you enter `ng g c profile\profile-tray` (Note the forward slash), but entering `ng g c profile/profile-tray` will cause it to use the Unix style path instead of replacing the slash with a forward slash. This happens for any slashes contained in the `path/sub/name` string.

**Comment by filipesilva** [comment] 2016-09-22 02:01
Fixed in https://github.com/angular/angular-cli/issues/1719

**Closed by filipesilva** 2016-09-22 02:01 UTC
