### ISSUE TITLE
Warning: Condition always false

### ISSUE THREAD

**Issue by AlexZanel** [angular/angular-cli#15509] opened 2019-09-03 09:51 UTC
I use Angular library.
I have main tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowUnreachableCode":true,
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "core": [
        "dist/core"
      ],
      "core/*": [
        "dist/core/*"
      ],
      "@angular/*": [
        "node_modules/@angular/*"
      ],
      "rxjs": [
        "node_modules/rxjs"
      ],
      "rxjs/*": [
        "node_modules/rxjs/*"
      ]
    }
  }
}

```
and tsconfig.json for my lib

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    "declaration": true,
    "sourceMap": true,
    "inlineSources": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "types": [
      "jasmine"
    ],
    "lib": [
      "dom",
      "es2018"
    ]
  },
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableResourceInlining": true,
    "warnings": false,
  },
  "exclude": [
    "dist",
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
```
When I build Angular library I get many warnings. For example:
`WARNING: Condition always false`
I use 
`ng build --project my-lib 
`
I have many similar interfaces, for example: 
```
export interface IPagination {
  prevUrl?: string;
  selfUrl?: string;
  nextUrl?: string;
  number: number;
  size: number;
  totalElements: number;
  totalPages: number;
}
```
The following code is generated for this interface
```
 function IPagination() { }
    if (false) {
        /** @type {?|undefined} */
        IPagination.prototype.prevUrl;
        /** @type {?|undefined} */
        IPagination.prototype.selfUrl;
        /** @type {?|undefined} */
        IPagination.prototype.nextUrl;
        /** @type {?} */
        IPagination.prototype.number;
        /** @type {?} */
        IPagination.prototype.size;
        /** @type {?} */
        IPagination.prototype.totalElements;
        /** @type {?} */
        IPagination.prototype.totalPages;
    }
```
I get warnings for every such interface.
Why it turns into an impossible condition?
How can I disable this warning or fix this?

I also get such warnings:
WARNING: Dropping unreachable code [0:178,8]
WARNING: Dropping side-effect-free statement [0:55,8]
WARNING: Dropping unused function __exportStar [0:113,13]
WARNING: Dropping unused function __spread [0:145,13]
WARNING: Dropping unused function __spreadArrays [0:151,13]
WARNING: Dropping unused function __asyncGenerator [0:163,13]
WARNING: Dropping unused function __asyncDelegator [0:175,13]
WARNING: Dropping unused function __asyncValues [0:181,13]
WARNING: Dropping unused function __makeTemplateObject [0:189,13]
WARNING: Dropping unused function __importStar [0:194,13]
WARNING: Dropping unused function __importDefault [0:202,13]

How can I fix these warnings?

**Comment by alan-agius4** [comment] 2019-09-03 10:44
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1394

**Closed by alan-agius4** 2019-09-03 10:44 UTC
