### ISSUE TITLE
ng serve ignores outDir for assets in HTML

### ISSUE THREAD

**Issue by cortopy** [angular/angular-cli#6421] opened 2017-05-23 10:48 UTC
```
- [x ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.
@angular/cli: 1.0.3
node: 7.10.0
os: linux x64
@angular/cli: 1.0.3
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/compiler-cli: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2

### Repro steps.

Specify in the config file output directory like:

```
     "outDir": "dist/subfolder",
      "assets": [
        "assets",
        "favicon.ico"
      ],
```

### The log given by the failure.
404 for assets in HTML files

### Desired functionality.
With `outDir` configured this way, resources can be easily accessed on build using `/subfolder/assets/file.jpg` in templates.

However, they are not accessible like that when doing `ng serve`

### Mention any other details that might be useful.
I'm able to do a workaround by importing `environment`, using build only with `--prod` flag and dynamically setting url accordingly. I'm not sure if this is a bug or expected usage.

Having said that, would it not be possible for `ng serve` to detect output directory in order to make static resources available according to configuration?

**Comment by clydin** [comment] 2017-05-23 13:04
This is working as intended.  The `outDir` option is meant to specify the _root_ of the built output.

**Comment by cortopy** [comment] 2017-05-23 13:26
However `ng serve --help` still gives the option `--output-path (Path) Path where output will be placed`

Apart from that, I've not been able to find anything in the docs about output for static resources in development. When I used webpack dev server I configured it to allow for serving resources that way.

If build and serve output directories are different, then how could one differentiate those in the code?

**Comment by Brocco** [comment] 2017-05-23 16:04
You can read more about asset configuration [here](https://github.com/angular/angular-cli/wiki/stories-asset-configuration).

Closing this issue as you should be able to accomplish what you're trying to with the information in that link.

**Closed by Brocco** 2017-05-23 16:04 UTC

**Comment by cortopy** [comment] 2017-05-24 08:01
@Brocco that doesn't solve the issue. The problem occurs when an angular app has base_href and output directory configure like in my example. 

The configuration in the [doc](https://github.com/angular/angular-cli/wiki/stories-asset-configuration) page doesn't cover that use case.

That configuration applies both to `serve` and `build` and so the disparities between them remain.

Following my example:

```
     "outDir": "dist/subfolder",
      "assets": [
        { "glob": "**/*", "input": "./assets/", "output": "./subfolder/assets/" },
        { "glob": "favicon.ico", "input": "./", "output": "./subfolder/" }
      ],
```

will mean that static assets have to be accessed differently in `serve` and `build`.

In `serve` they are available at `/subfolder/assets` yet in `build` they're available at `subfolder/subfolder/assets`
