### ISSUE TITLE
Get error after update angular/cli version

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular-cli#8992] opened 2017-12-25 19:15 UTC
angular/cli: 1.5.0 - 1.6.0
angulat/core: 5.0.0

### Repro steps

1. Clone [app](https://github.com/dxvladislavvolkov/testapp)
2. npm i
3. ng build --prod
4. cd dist
5. run server

### Observed behavior
After update angular and angular/cli versions I get error "TypeError: Cannot read property 'pointers' of undefined".

### Desired behavior
If I use the 1.4.* version with angular 4, everything works fine

**Comment by filipesilva** [comment] 2017-12-26 12:47
Using your repro, I had to first remove  implements AfterViewInit` from `src/app.component.ts` because it was not implemented correctly.

Then while running `npm run ng -- serve --prod --sm` I was able to see this error:
```
mouse.js:24 Uncaught TypeError: Cannot set property 'pointerId' of undefined
```

Then I updated versions to latest ones (`"@angular/cli": "1.6.2"`, "devextreme": "17.2.4"` and `"devextreme-angular": "17.2.4"` and the error went away. I'm not sure where the problem was but latest versions seems to have fixed it.

**Comment by dxvladislavvolkov** [comment] 2017-12-26 16:21
@filipesilva it is not working on my side( Can you re-open the issue?

**Comment by filipesilva** [comment] 2017-12-26 16:35
Thanks for getting back to me, I'm reopening. I tried to reproduce with a newer version of `uglify-es` because it seems it's causing problems in `https://github.com/angular/angular-cli/issues/8997`. I now see `Uncaught TypeError: Cannot set property 'pointerId' of undefined` even with updated versions of other packages.

Can you please tell me what do you see on your machine when you run `npm ls uglify-es`?

**Comment by filipesilva** [comment] 2017-12-26 16:39
For now you can run this command to use an older version of `uglify-es` where the error does not occur:
```
npm i uglify-es@3.2.2 --save-exact && rm -rf package-lock.json node_modules && npm i && npm ls uglify-es
```

**Comment by dxvladislavvolkov** [comment] 2017-12-26 17:49
The result of the command execution:
-- @angular/cli@1.6.2
  -- uglifyjs-webpack-plugin@1.1.4
    -- uglify-es@3.3.2

Thanks for the workaround!

**Comment by filipesilva** [comment] 2017-12-26 21:15
Have been debugging this for a couple of hours and the best I can say is that the class inheritance mechanism that devextreme uses breaks down when passed through `uglify-es@3.3.2`.

**Comment by filipesilva** [comment] 2017-12-26 21:28
https://github.com/mishoo/UglifyJS2/issues/2663 might be related, I noticed some of that function inlining in the code I was investigating.

**Comment by filipesilva** [comment] 2017-12-27 15:01
The bug causing these problems is reported with repros at https://github.com/mishoo/UglifyJS2/issues/2663.

**Comment by filipesilva** [comment] 2017-12-27 15:02
I'm going to close this issue in favor of #8997 since the problem is the same.

**Closed by filipesilva** 2017-12-27 15:02 UTC
Labels: priority: 1 (urgent), type: bug
