### ISSUE TITLE
ng generate component not working properly

### ISSUE THREAD

**Issue by emiliogambone** [angular/angular-cli#12750] opened 2018-10-25 12:52 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 7.0.3
Node: 8.11.1
OS: darwin x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@ngtools/webpack                  6.0.8
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

```
ng generate component example --module app
```

### The log given by the failure

```
CREATE src/app/example/example.component.ts (259 bytes)
UPDATE src/app/app.module.ts (1341 bytes)
```

### Desired functionality

It creates only the .ts file and all the others component files are missing

### Mention any other details that might be useful

link to the minimal repro here:

https://github.com/emiliogambone/sampleAngular

**Comment by alan-agius4** [comment] 2018-10-25 13:10
Duplicate of https://github.com/angular/angular-cli/issues/12747

**Comment by alan-agius4** [comment] 2018-10-25 13:14
Hi, this is correct, as you are specifying that the files should be inlined. https://github.com/emiliogambone/sampleAngular/blob/a039259da3dfc8d338a048f0a2dc7f9e88f4d02a/angular-site-template-v1.0/angular.json#L132-L137

**Comment by emiliogambone** [comment] 2018-10-25 13:22
> Hi, this is correct, as you are specifying that the template and styles for components should be inlined and not to create spec files. https://github.com/emiliogambone/sampleAngular/blob/a039259da3dfc8d338a048f0a2dc7f9e88f4d02a/angular-site-template-v1.0/angular.json#L132-L137

thank, i understand now

**Closed** 2018-10-25 13:22 UTC
