### ISSUE TITLE
start project failed

### ISSUE THREAD

**Issue by kamalkech** [angular/angular-cli#4378] opened 2017-02-02 23:24 UTC
### OS
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.28.3
node: 6.9.4
os: win32 x64

### Repro steps.
ng serve

### The log given by the failure.
ERROR in ./~/@angular/core/src/util/decorators.js
Module parse failed: C:\Projets\Angular\formation\node_modules\@angular\core\src\util\decorators.js Parenthesized pattern (156:12)
You may need an appropriate loader to handle this file type.
|     if (clsDef.hasOwnProperty('extends')) {
|         if (typeof clsDef.extends === 'function') {
|             ((constructor)).prototype = proto =
|                 Object.create(((clsDef.extends)).prototype);
|         }
 @ ./~/@angular/core/src/util.js 9:0-42
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/@angular/core/src/di/forward_ref.js
Module parse failed: C:\Projets\Angular\formation\node_modules\@angular\core\src\di\forward_ref.js Parenthesized pattern (24:4)
You may need an appropriate loader to handle this file type.
|  */
| export function forwardRef(forwardRefFn) {
|     ((forwardRefFn)).__forward_ref__ = forwardRef;
|     ((forwardRefFn)).toString = function () { return stringify(this()); };
|     return (((forwardRefFn)));
 @ ./~/@angular/core/src/di.js 14:0-65
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/@angular/core/src/facade/errors.js
Module parse failed: C:\Projets\Angular\formation\node_modules\@angular\core\src\facade\errors.js Parenthesized pattern (60:32)
You may need an appropriate loader to handle this file type.
|          * @return {?}
|          */
|         set: function (value) { ((this._nativeError)).stack = value; },
|         enumerable: true,
|         configurable: true
 @ ./~/@angular/core/src/application_ref.js 15:0-53
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/@angular/compiler/src/aot/static_reflector.js
Module parse failed: C:\Projets\Angular\formation\node_modules\@angular\compiler\src\aot\static_reflector.js Parenthesized pattern (793:4)
You may need an appropriate loader to handle this file type.
| function positionalError(message, fileName, line, column) {
|     var /** @type {?} */ result = new Error(message);
|     ((result)).fileName = fileName;
|     ((result)).line = line;
|     ((result)).column = column;
 @ ./~/@angular/compiler/index.js 30:0-61
 @ ./~/@angular/platform-browser-dynamic/src/platform-browser-dynamic.js
 @ ./~/@angular/platform-browser-dynamic/index.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/@angular/compiler/src/jit/compiler.js
Module parse failed: C:\Projets\Angular\formation\node_modules\@angular\compiler\src\jit\compiler.js Parenthesized pattern (283:12)
You may need an appropriate loader to handle this file type.
|             assertComponent(compMeta);
|             var /** @type {?} */ HostClass = function HostClass() { };
|             ((HostClass)).overriddenName = identifierName(compMeta.type) + "_Host";
|             var /** @type {?} */ hostMeta = createHostComponentMeta(HostClass, compMeta);
|             compiledTemplate = new CompiledTemplate(true, compMeta.selector, compMeta.type, hostMeta, ngModule, [compMeta.type]);
 @ ./~/@angular/compiler/index.js 36:0-49
 @ ./~/@angular/platform-browser-dynamic/src/platform-browser-dynamic.js
 @ ./~/@angular/platform-browser-dynamic/index.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/@angular/platform-browser/src/browser/browser_adapter.js
Module parse failed: C:\Projets\Angular\formation\node_modules\@angular\platform-browser\src\browser\browser_adapter.js Parenthesized pattern (88:75)
You may need an appropriate loader to handle this file type.
|      * @return {?}
|      */
|     BrowserDomAdapter.prototype.setProperty = function (el, name, value) { ((el))[name] = value; };
|     /**
|      * @param {?} el
 @ ./~/@angular/platform-browser/src/browser.js 12:0-62
 @ ./~/@angular/platform-browser/src/platform-browser.js
 @ ./~/@angular/platform-browser/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/@angular/platform-browser/src/dom/dom_renderer.js
Module parse failed: C:\Projets\Angular\formation\node_modules\@angular\platform-browser\src\dom\dom_renderer.js Parenthesized pattern (321:8)
You may need an appropriate loader to handle this file type.
|      */
|     DomRenderer.prototype.setElementProperty = function (renderElement, propertyName, propertyValue) {
|         ((renderElement))[propertyName] = propertyValue;
|     };
|     /**
 @ ./~/@angular/platform-browser/src/browser.js 18:0-71
 @ ./~/@angular/platform-browser/src/platform-browser.js
 @ ./~/@angular/platform-browser/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/@angular/compiler/src/facade/errors.js
Module parse failed: C:\Projets\Angular\formation\node_modules\@angular\compiler\src\facade\errors.js Parenthesized pattern (60:32)
You may need an appropriate loader to handle this file type.
|          * @return {?}
|          */
|         set: function (value) { ((this._nativeError)).stack = value; },
|         enumerable: true,
|         configurable: true
 @ ./~/@angular/compiler/src/util.js 13:0-44
 @ ./~/@angular/compiler/index.js
 @ ./~/@angular/platform-browser-dynamic/src/platform-browser-dynamic.js
 @ ./~/@angular/platform-browser-dynamic/index.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/json3/lib/json3.js
Module parse failed: C:\Projets\Angular\formation\node_modules\json3\lib\json3.js Parenthesized pattern (89:12)

You may need an appropriate loader to handle this file type.
|           if (stringifySupported) {
|             // A test function object with a custom `toJSON` method.
|             (value = function () {
|               return 1;
|             }).toJSON = value;
 @ ./~/sockjs-client/lib/main.js 7:12-28
 @ ./~/sockjs-client/lib/entry.js
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://localhost:4200/
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/@angular/common/src/facade/errors.js
Module parse failed: C:\Projets\Angular\formation\node_modules\@angular\common\src\facade\errors.js Parenthesized pattern (60:32)
You may need an appropriate loader to handle this file type.
|          * @return {?}
|          */
|         set: function (value) { ((this._nativeError)).stack = value; },
|         enumerable: true,
|         configurable: true
 @ ./~/@angular/common/src/pipes/invalid_pipe_argument_error.js 13:0-45
 @ ./~/@angular/common/src/pipes/async_pipe.js
 @ ./~/@angular/common/src/pipes/index.js
 @ ./~/@angular/common/src/common.js
 @ ./~/@angular/common/index.js
 @ ./~/@angular/platform-browser/src/browser.js
 @ ./~/@angular/platform-browser/src/platform-browser.js
 @ ./~/@angular/platform-browser/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

any idea ?

**Comment by beeman** [comment] 2017-02-02 23:27
@kamalkech is this a new project or an existing one?

If it's an existing one, did you upgrade using these steps: https://github.com/angular/angular-cli#updating-angular-cli ?

**Comment by shcarrico** [comment] 2017-02-02 23:29
Same issue reported in #4368 by @denkomanceski. I have the same problem after upgrading to 28.3 from 26. I have all the newest package dependenies, command line tool, etc AFAIK, and even upgraded to node 6.9 to ensure that wasn't the issue..

**Comment by kamalkech** [comment] 2017-02-02 23:29
@yep it's a last version i guess : 

angular-cli: 1.0.0-beta.28.3
node: 6.9.4
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

**Comment by dsoltesz** [comment] 2017-02-02 23:29
I'm having the same issue with existing project and yes, i updated both global and local packages

angular-cli: 1.0.0-beta.28.3
node: 6.9.5
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
@angular/flex-layout: 2.0.0-beta.4

**Comment by StephanHartmann** [comment] 2017-02-02 23:33
same here with :
Windows 10 x64
Node 7.5.0
@angular/cli    ( => 1.0.0-beta.29 )

steps to reproduce :

ng new testproject
cd testproject 
ng serve

**Comment by depoulo** [comment] 2017-02-02 23:39
Having the same issue on a small playground project (no Angular at all, just babel and webpack) after upgrading webpack and webpack-dev-server.

**Comment by Toxicable** [comment] 2017-02-02 23:42
Am also getting this error.
```
ng new project
cd project
ng serve
```
```
angular-cli: 1.0.0-beta.28.3
node: 6.9.4
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

**Comment by EvgenyKravchenko** [comment] 2017-02-02 23:43
With latest @angular/cli same errors.

@angular/cli: 1.0.0-beta.29
node: 7.2.0
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/cli: 1.0.0-beta.29
@angular/compiler-cli: 2.4.5

**Comment by juanmcampos** [comment] 2017-02-02 23:45
Same issue,

I can confirm it happens on new project and when updating.

i tried @angular/cli  and angular-cli

**Comment by EvgenyKravchenko** [comment] 2017-02-02 23:45
Even rollback to old working version does not help

**Comment by Nodarii** [comment] 2017-02-02 23:46
I guess it's webpack issue...

**Comment by irsick** [comment] 2017-02-02 23:49
@EvgenyKravchenko 
I confirm. Rollback to 1.0.0-beta.26 didn't help. Looks like the regression came from one of CLI's unlocked dependencies.

**Comment by EvgenyKravchenko** [comment] 2017-02-02 23:54
Looks like latest versions work with projects, which were bootstrapped before regression

**Comment by victorblq** [comment] 2017-02-02 23:59
Same here,  rollback didn't solve too.

**Comment by shawnlan** [comment] 2017-02-03 00:00
Didn't update CLI. Newly created projects got these errors.

**Comment by RomainGoncalves** [comment] 2017-02-03 00:06
Same here on a brand new project

**Comment by mogafk** [comment] 2017-02-03 00:06
Guys, few minutes ago a throwed similar error, but i not used something from angular or angular cli. 
My error:
ERROR in ./~/json3/lib/json3.js
Module parse failed: /home/mogafk/web/task4/node_modules/json3/lib/json3.js Parenthesized pattern (89:12)
You may need an appropriate loader to handle this file type.
|           if (stringifySupported) {
|             // A test function object with a custom `toJSON` method.
|             (value = function () {
|               return 1;
|             }) .toJSON = value;
 @ ./~/sockjs-client/lib/main.js 7:12-28
 @ ./~/sockjs-client/lib/entry.js
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://localhost:8080
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app.js


I solved this problem downgrade webpack and webpack-dev-server to 2.2.0(from 2.2.1). I hope this information help you solved this problem.
ps: sorry, my english is suck

**Comment by AbbTek** [comment] 2017-02-03 00:08
Same problem, but in my case, the build server is still working with the following version:

angular-cli: 1.0.0-beta.28.3
node: 6.9.1
os: win32 ia32
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
@ngtools/webpack: 1.2.4

But after update the cache in the develop machines, the project is broken :(

**Comment by mack-cope** [comment] 2017-02-03 00:09
Was breaking on our build server got it working using the following:

    "@angular/common": "2.4.0",
    "@angular/compiler": "2.4.0",
    "@angular/core": "2.4.0",
    "@angular/forms": "2.4.0",
    "@angular/http": "2.4.0",
    "@angular/platform-browser": "2.4.0",
    "@angular/platform-browser-dynamic": "2.4.0",
    "@angular/router": "~3.4.0",
    "@types/moment-timezone": "^0.2.34",
    "angular-cli": "1.0.0-beta.24"

**Comment by shcarrico** [comment] 2017-02-03 00:10
I was able to get it to work by pinning Angular to 2.4.5 similar to @AbbTek above.

**Comment by EvgenyKravchenko** [comment] 2017-02-03 00:10
See related issue for acorn package
https://github.com/ternjs/acorn/issues/502

**Comment by arthrmlo** [comment] 2017-02-03 00:12
I've managed to get it running. 
Delete your node_modules folder after creating a project with `ng new proj-name` and modify the rxjs entry (line 24) on package.json removing the "^" before it. It should look like: `"rxjs": "5.0.1",`. Re-run `npm install` and `ng serve` should work fine.

**Comment by EvgenyKravchenko** [comment] 2017-02-03 00:15
As a temporary solution just update acorn package to 4.0.7

**Comment by RomainGoncalves** [comment] 2017-02-03 00:15
I managed to fix it with @AbbTek 's solution. Changed the version of devDependencies: ``` "@angular/compiler-cli": "2.4.5",```

**Comment by beeman** [comment] 2017-02-03 00:18
The problem was indeed in acorn, one of WebPack's dependencies and should be fixed by doing:

```
$ rm -rf node_modules
$ npm install
```

Or just:

```
$ npm install acorn@4.0.7
```

**Comment by hansl** [comment] 2017-02-03 00:18
Closing this as the fix above should work.

**Closed by hansl** 2017-02-03 00:18 UTC

**Comment by kamalkech** [comment] 2017-02-03 01:00
@beeman runing server of angular-cli work good now, but after update files ts webpack not compile them !!

**Comment by dsoltesz** [comment] 2017-02-03 02:03
added "acorn": "4.0.7" to package.json fixed this issue for me

**Comment by colintucker** [comment] 2017-02-03 05:08
Thank you so, SO much @beeman, all working now... was frustrating me for the past 4 hours.  :P <3

**Comment by denkomanceski** [comment] 2017-02-03 09:27
Short offtopic question before this issue dissapears forever: Did you guys notice the difference in speed in recompiling? That was the one and only reason I updated the cli hehe
