### ISSUE TITLE
Latest .28 build can't generate production build

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#4327] opened 2017-02-01 21:55 UTC
### OS
angular-cli: 1.0.0-beta.28.3
node: 6.9.5
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/language-service: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.2.1
@angular/compiler-cli: 2.4.5

### Repro steps.
Repo: https://github.com/born2net/studioweb

```
git clone https://github.com/born2net/studioweb.git
cd studioweb
npm install --no-optional
ng build --target=production --base-href ./ --aot true
```

### Error:

worked fine with previous build of .26

dump

```
root@DESKTOP-VEUHFOL /cygdrive/c/msweb/studioweb
$ npm run release_aot

> studioweb@0.1.94 release_aot C:\msweb\studioweb
> rm -r -f ./dist && npm run x_bump && npm run x_prod_aot && npm run x_sw && npm run x_rsync


> studioweb@0.1.94 x_bump C:\msweb\studioweb
> gulp x_bump

[13:54:01] Using gulpfile C:\msweb\studioweb\gulpfile.js
[13:54:01] Starting 'x_bump'...
[13:54:01] Finished 'x_bump' after 7.87 ms
[13:54:01] Bumped 0.1.94 to 0.1.95 with type: patch

> studioweb@0.1.95 x_prod_aot C:\msweb\studioweb
> ng build --target=production --base-href ./ --aot true

As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

Hash: 602058ee3363a6f815d2
Time: 76015ms
chunk    {0} 0.0cb116efbe3477609730.chunk.js 766 kB {1} {2} {3} {4} {5} {6} {7} [rendered]
chunk    {1} 1.167b3ce0de7984a2da69.chunk.js 65.7 kB {0} {2} {3} {4} {5} {6} {7} [rendered]
chunk    {2} 2.1bc6cc7bf67d3e5de3df.chunk.js 173 kB {0} {1} {3} {4} {5} {6} {7} [rendered]
chunk    {3} 3.08532ef528810c0c1231.chunk.js 72.5 kB {0} {1} {2} {4} {5} {6} {7} [rendered]
chunk    {4} 4.e609f12f3d59a017f9c6.chunk.js 173 kB {0} {1} {2} {3} {5} {6} {7} [rendered]
chunk    {5} 5.f6c8c71220b7cc76c1e1.chunk.js 25.1 kB {0} {1} {2} {3} {4} {6} {7} [rendered]
chunk    {6} 6.b6fb4534b8ac718334ca.chunk.js 26.8 kB {0} {1} {2} {3} {4} {5} {7} [rendered]
chunk    {7} main.88ec1f21a0a9e3c70b74.bundle.js (main) 738 kB {10} [initial] [rendered]
chunk    {8} scripts.84cb767c4a82d1b1ee75.bundle.js (scripts) 1.63 MB {11} [initial] [rendered]
chunk    {9} styles.8e33d6addfa8d4f9302a.bundle.css (styles) 334 bytes {11} [initial] [rendered]
chunk   {10} vendor.8f2abf8c51545a5ec54c.bundle.js (vendor) 5.62 MB [initial] [rendered]
chunk   {11} inline.c190dbe96e6cc81bc31c.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in ./src/services/StoreService.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:93:31
    at Array.map (native)
    at _addCtorParameters (C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:92:46)
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:114:17
    at Array.forEach (native)
    at _removeDecorators (C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:109:10)
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:280:48
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/locale/app/app-module.ngfactory.ts 85:0-56
 @ ./src/main.ts
 @ multi ./src/main.ts

ERROR in ./src/store/effects/appdb.effects.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:93:31
    at Array.map (native)
    at _addCtorParameters (C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:92:46)
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:114:17
    at Array.forEach (native)
    at _removeDecorators (C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:109:10)
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:280:48
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/locale/app/app-module.ngfactory.ts 65:0-62
 @ ./src/main.ts
 @ multi ./src/main.ts

ERROR in ./src/store/effects/msdb.effects.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:93:31
    at Array.map (native)
    at _addCtorParameters (C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:92:46)
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:114:17
    at Array.forEach (native)
    at _removeDecorators (C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:109:10)
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:280:48
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/locale/app/app-module.ngfactory.ts 66:0-61
 @ ./src/main.ts
 @ multi ./src/main.ts

ERROR in ./src/comps/sliderpanel/Sliderpanel.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:93:31
    at Array.map (native)
    at _addCtorParameters (C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:92:46)
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:114:17
    at Array.forEach (native)
    at _removeDecorators (C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:109:10)
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:280:48
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/modules/shared.module.ts 2:0-63
 @ ./src/locale/app/app-module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "x_prod_aot"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! studioweb@0.1.95 x_prod_aot: `ng build --target=production --base-href ./ --aot true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the studioweb@0.1.95 x_prod_aot script 'ng build --target=production --base-href ./ --aot true'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the studioweb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --target=production --base-href ./ --aot true
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs studioweb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls studioweb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\msweb\studioweb\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release_aot"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! studioweb@0.1.94 release_aot: `rm -r -f ./dist && npm run x_bump && npm run x_prod_aot && npm run x_sw && npm run x_rsync`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the studioweb@0.1.94 release_aot script 'rm -r -f ./dist && npm run x_bump && npm run x_prod_aot && npm run x_sw && npm run x_rsync'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the studioweb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -r -f ./dist && npm run x_bump && npm run x_prod_aot && npm run x_sw && npm run x_rsync
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs studioweb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls studioweb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\msweb\studioweb\npm-debug.log

root@DESKTOP-VEUHFOL /cygdrive/c/msweb/studioweb
```

**Comment by born2net** [comment] 2017-02-01 22:01
let me also add that non AOT **does** works
```ng build --target=production --base-href ./ --aot false```

**Comment by yarrgh** [comment] 2017-02-01 22:47
`ng build --prod` now defaults to use aot.

**Comment by maxime1992** [comment] 2017-02-02 08:20
@born2net take a look into #4343 :smile:
(spoiler alert : If you're using yarn you should be able to fix this)

**Comment by born2net** [comment] 2017-02-02 12:56
Thanks, checking now
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by maxime1992** [comment] 2017-02-02 13:47
@born2net better than the yarn thing, read that comment : https://github.com/angular/angular-cli/issues/4343#issuecomment-276918967

I was able to upgrade all my deps after that (so it would be working with npm too :+1: !!)

**Comment by born2net** [comment] 2017-02-02 14:38
TX!
will do

**Comment by dlimkin** [comment] 2017-02-02 21:17
Maybe this will help. I accidentally called `ng init` in Нome directory, after the launch of the `ng` in any other directory caused the error (even when call `ng --version`). After deleting ng files from the home directory. `ng` runs without errors

**Comment by born2net** [comment] 2017-02-04 02:23
I still have the same issue with .30 :(

**Comment by filipesilva** [comment] 2017-03-09 10:54
Dupe of #4343

**Closed by filipesilva** 2017-03-09 10:54 UTC

**Comment by AhmedBahet** [comment] 2017-06-28 11:39
Whether Aot is or is not implemented.

If Aot is implemented : bootstrapModuleFactory in main.ts

    ng build --prod

If Aot is not implemented : bootstrapModule in main.ts

    ng build --prod --aot=false
