### ISSUE TITLE
Unused down-levelled ES2015 classes are not tree shaken away

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular-cli#14997] opened 2019-07-04 12:33 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
```
## Description

I have created an angular application and checked main bundle whether tree-shaking is working or not using [bundle-analyzer](https://coryrylan.com/blog/analyzing-bundle-size-with-the-angular-cli-and-webpack).

But i found all **.js extension** files are included.

## 🔬 Minimal Reproduction

1. Download sample form below link - [click here](https://www.syncfusion.com/downloads/support/directtrac/general/ze/angular-treeshaking1305190968)

2. Run below commands :

> npm i

> npm run start  - **To generate build**

> npm run bundle-report - **To check bundle files in online**

## 🔥 Exception or Error
In below, i have not enabled pdf-export functionality in my application. In source level,i have done proper work for module injection but in below you can see pdfexport related js files are added.

**Note: But pdf-export module not get added in main.bunlde.js file**

marked files are not used but still getting added

![sdf](https://user-images.githubusercontent.com/36756050/60710321-0c974e80-9f30-11e9-9f03-bcbfaede1ab2.jpg)

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

 

Angular CLI: 8.0.1
Node: 10.16.0
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

 

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.1 (cli-only)
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

I thought, while tree-shaking it includes all imported files.

**Comment by kumaresan-subramani** [comment] 2019-07-04 14:41
I have tried this [https://github.com/mishoo/UglifyJS2/issues/2279#issuecomment-322591372](https://github.com/mishoo/UglifyJS2/issues/2279#issuecomment-322591372)

**Comment by FDIM** [comment] 2019-07-04 18:47
Someone can correct me if I am wrong, but I am fairly sure that you need to set module type to esnext/es2015 in ts config. In the zip you've linked, module is set to es5.

See: https://webpack.js.org/guides/tree-shaking/

**Comment by kumaresan-subramani** [comment] 2019-07-05 05:03
Hi @FDIM ,

I have set modules as es2015 but still i am facing same error which is my depedent packages are all get included even i have not used those.

**Comment by kumaresan-subramani** [comment] 2019-07-05 05:41
https://github.com/webpack/webpack/issues/2899

**Comment by kumaresan-subramani** [comment] 2019-07-05 08:48
HI Guys,

I am analyzing this since Wednesday still i am not able to find out cause of this issue.

Can anyone please provide any suggestions?

@alan-agius4 , Can you please see this?

**Comment by alan-agius4** [comment] 2019-07-05 10:13
Hi I had a look at this is being retained because of ES5 classes are not being wrapped in an IIFE which is making code non tree-shakable.

The issue seems to happen when downlevelling from ES2015 to ES5 which was being done in ng-packagr version 1.5 which you are using to build your libraries. Downlevelling was removed in version 4.

This most likely is also caused by the removal of the `class-fold` transformer from the build-optimizer pipeline.

**Comment by kumaresan-subramani** [comment] 2019-07-05 10:24
HI @alan-agius4 ,

Thanks for your Fast reply. i will wait for fix.

**Comment by kumaresan-subramani** [comment] 2019-07-11 13:22
HI @alan-agius4 ,

Can you please let me know tentative timeline for this to proceed further since tree shaking is considered as major break by most of the application developers.

**Comment by alan-agius4** [comment] 2019-07-19 11:46
At the moment, there is no ETA yet, though if someone want to land a PR they are more than welcome.

We work on issues based on how their categorised, and this one is classified as `low frequency` and `broken`. Others which have a higher priority or are regressions take priority over such issues.

The main reason for this classification is;
- Low Frequency - it's doesn't seems to be effected a lot of users since the pattern described above is not widely used, and if the library author update their library build tool chain the issue will be solved, as this only happens when down levelling ES2015 code to ES5 using TypeScript and as mentioned previously down-levelling of libraries is no longer happening with ng-packagr since version 4 .
- Broken because it doesn't seem to be a regressions (IE: was working and stop)

Thanks for your understanding.

**Comment by alan-agius4** [comment] 2020-11-05 11:09
I am going to close this, since this issue is caused when using an old version of ng-packagr which relied on TSC downlevelling, this version supported Angular 4 which is no longer supported.

Kindly be aware that Angular 8 is in LTS and it's support will end on the Nov 28, 2020.
More info: https://angular.io/guide/releases#support-policy-and-schedule

Please update to the most recent Angular CLI and ng-packagr version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2020-11-05 11:09 UTC
Labels: comp: devkit/build-optimizer, freq1: low, help wanted, severity3: broken, triage #1, type: bug/fix
