### ISSUE TITLE
Invalid SASS causes build error that's hard to track down

### ISSUE THREAD

**Issue by FiniteLooper** [angular/angular-cli#25193] opened 2023-05-11 21:54 UTC
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

My project uses SCSS and I had a selector like this:
```scss
#one {
  // styles here

  #two & {
    // styles here
  }
}
```

I decided to restructure it without thinking very hard apaprently and I un-nested that selector so that I had this:

```scss
#one {
  // styles here
}

#two & {
  // styles here
}
```

I didn't realize it was invalid at the time, but when I came back to my project to run `ng-build` or `ng serve` I got this extremely generic error

```
PS C:\Users\FiniteLooper\Projects\LyricConverter> ng serve
⠋ Generating browser application bundles (phase: building)...
node:internal/event_target:1010
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: Cannot read properties of undefined (reading 'column')
    at convertSourceSpan (C:\Users\FiniteLooper\Projects\LyricConverter\node_modules\@angular-devkit\build-angular\src\sass\worker.js:146:30)       
    at MessagePort.<anonymous> (C:\Users\FiniteLooper\Projects\LyricConverter\node_modules\@angular-devkit\build-angular\src\sass\worker.js:111:27) 
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at [kOnExit] (node:internal/worker:268:5)
    at Worker.<computed>.onexit (node:internal/worker:199:20)

Node.js v18.15.0
```

It took a look of guesswork, but eventually I narrowed it down and confirmed this was the cause.  It obviosly should throw an error for this, but apparently it has a problem reporting what/where this error is which makes it hard to track down,

### Minimal Reproduction

Include this invalid SCSS
```scss
#two & {
  // styles here
}
```

Then run `ng build` or `ng serve`

### Exception or Error

```text
PS C:\Users\FiniteLooper\Projects\LyricConverter> ng serve
⠋ Generating browser application bundles (phase: building)...
node:internal/event_target:1010
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: Cannot read properties of undefined (reading 'column')
    at convertSourceSpan (C:\Users\FiniteLooper\Projects\LyricConverter\node_modules\@angular-devkit\build-angular\src\sass\worker.js:146:30)       
    at MessagePort.<anonymous> (C:\Users\FiniteLooper\Projects\LyricConverter\node_modules\@angular-devkit\build-angular\src\sass\worker.js:111:27) 
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at [kOnExit] (node:internal/worker:268:5)
    at Worker.<computed>.onexit (node:internal/worker:199:20)

Node.js v18.15.0
```

### Your Environment

```text
Angular CLI: 16.0.1
Node: 18.15.0
Package Manager: npm 9.6.2
OS: win32 x64

Angular: 16.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@schematics/angular             16.0.1
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by alan-agius4** [comment] 2023-05-12 05:37
Duplicate of https://github.com/angular/angular-cli/issues/25134

**Closed by alan-agius4** 2023-05-12 05:37 UTC
