### ISSUE TITLE
Ng lint produces to multiple xml content in single file

### ISSUE THREAD

**Issue by harishankard** [angular/angular-cli#15608] opened 2019-09-16 16:00 UTC
# 🐞 Ng lint produces to Multiple XML content in single file

### 
```
- [ x] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression? Yes

Angular 5 Was not having this issue. Once we moved to Angular 7 we are facing this issue.
### Description
when we use ng lint for checkstyle it produces multiple xml content. This result in parsing failure of the xml.

## 🔬 Minimal Reproduction
when i run this 
ng lint --format checkstyle > result-checkstyle.xml;

the result file contains : 
```
<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"><file name="../shoppingcart-ang7/shoppingcart/src/app/app.component.ts"><error line="208" column="160" severity="error" message="trailing whitespace" source="failure.tslint.no-trailing-whitespace" /></file></checkstyle>
<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"></checkstyle>

```

This result in xml parsing error.

**Comment by alan-agius4** [comment] 2019-09-16 16:31
Duplicate of https://github.com/angular/angular-cli/issues/14659

**Closed by alan-agius4** 2019-09-16 16:31 UTC
