### ISSUE TITLE
Memory leak during build process after updating to Angular 15

### ISSUE THREAD

**Issue by ruizmarc** [angular/angular-cli#24523] opened 2023-01-11 17:29 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.8

### Description

Hi,

After upgrading from Angular 14 to Angular 15, our library project has dramatically increased the amount of RAM needed to build the project. It never surpassed 8GB of RAM on build time with Angular 14, but after upgrading to Angular 15.1, it needs up to 25GB of RAM... it doesn't seem like a normal change. Furthermore, it takes far more time. 

### Minimal Reproduction

We are executing: `ng build ng-ptp`

### Your Environment

```text
Angular CLI: 15.1.0
Node: 18.12.0
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.1.0
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1501.0
@angular-devkit/build-angular     15.1.0
@angular-devkit/core              15.1.0
@angular-devkit/schematics        15.1.0
@angular/cdk                      15.0.4
@angular/material                 15.0.4
@angular/material-luxon-adapter   15.0.4
@nguniversal/builders             15.0.0
@nguniversal/express-engine       15.0.0
@schematics/angular               15.1.0
ng-packagr                        15.1.0
rxjs                              7.8.0
typescript                        4.9.4
```

**Comment by alan-agius4** [comment] 2023-01-11 18:22
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/2530

**Closed by alan-agius4** 2023-01-11 18:22 UTC
