### ISSUE TITLE
loadChildren doesn't work in webpack (rc5 ngmodule)

### ISSUE THREAD

**Issue by reflog** [angular/angular-cli#1679] opened 2016-08-13 09:52 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
linux/windows

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Defined a new module 'about', referenced it in a route:
  { path: 'about', loadChildren: 'app/+about/about.module' },

Build passes, during runtime, exception is thrown

4. The log given by the failure. Normally this include a stack trace and some
   more information.

EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'import' of undefined
browser_adapter.js:84 EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'import' of undefinedBrowserDomAdapter.logError @ browser_adapter.js:84BrowserDomAdapter.logGroup @ browser_adapter.js:94ExceptionHandler.call @ exception_handler.js:65next @ application_ref.js:348schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:77onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233_loop_1 @ zone.js:487drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
browser_adapter.js:84 STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:67next @ application_ref.js:348schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:77onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233_loop_1 @ zone.js:487drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
browser_adapter.js:84 Error: Uncaught (in promise): TypeError: Cannot read property 'import' of undefined
    at resolvePromise (zone.js:538)
    at zone.js:515
    at ZoneDelegate.invoke (zone.js:323)
    at Object.onInvoke (ng_zone_impl.js:53)
    at ZoneDelegate.invoke (zone.js:322)
    at Zone.run (zone.js:216)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.onInvokeTask (ng_zone_impl.js:44)
    at ZoneDelegate.invokeTask (zone.js:355)BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:68next @ application_ref.js:348schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:77onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233_loop_1 @ zone.js:487drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:461 Unhandled Promise rejection: Cannot read property 'import' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'import' of undefined(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): TypeError: Cannot read property 'import' of undefined(…)consoleError @ zone.js:463_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by michalstepien** [comment] 2016-08-13 20:47
Pls look https://vsavkin.com/angular-router-declarative-lazy-loading-7071d1f203ee#.324d4zo1w or https://gist.github.com/brandonroberts/02cc07face25886fe142c4dbd8da1340

**Comment by reflog** [comment] 2016-08-14 06:00
@michalstepien , thanks, but Victor's blog talks about a SystemJS solution, not Webpack, and the Gist you reference is a custom loader, not something provided by angular-cli.

**Comment by choeller** [comment] 2016-08-14 09:14
There is currently a pull-request dealing with this: https://github.com/angular/angular-cli/pull/1632 According to @hansl the PR needs some changed introduced in RC.6 so you'll have to wait for the new RC to land - I'm also really looking forward to this :)

**Comment by reflog** [comment] 2016-08-14 09:26
cool, thanks. I'll keep an eye on it!

**Comment by filipesilva** [comment] 2016-08-19 02:37
Dupe of https://github.com/angular/angular-cli/issues/1636

**Closed by filipesilva** 2016-08-19 02:37 UTC
Labels: feature: webpack, priority: 1 (urgent), type: bug
