### ISSUE TITLE
Is it possible to integrate postcss?

### ISSUE THREAD

**Issue by willgm** [angular/angular-cli#2420] opened 2016-09-29 15:42 UTC
I would like to integrate postcss in order to use autoprefix and other plugins, but looks like it is not supported. So, two questions:

- Is it going to be supported in the future?

- Is there a easy way to integrate postcss in my current project with angular-cli?

Keep up the good work! =)

**Comment by shayan786** [comment] 2016-09-29 21:08
+1

**Comment by scottwio** [comment] 2016-10-04 16:22
See https://github.com/angular/angular-cli/issues/1656

**Comment by filipesilva** [comment] 2016-10-09 01:45
Dupe of https://github.com/angular/angular-cli/issues/1512

**Closed by filipesilva** 2016-10-09 01:45 UTC
