### ISSUE TITLE
Cant share code between libraries: rootDir is expected to contain all source files

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#19831] opened 2021-01-20 16:33 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/cli or @ng-packagr/ng-packagr

### Description
When developing libraries it seems to be impossible to share code between them. E.g. two libraries may use the same interfaces. But as soon as importing something from outside of the libraries root folder (./projects/*) the build fails with error:

> rootDir is expected to contain all source files

Example: 

```
ng new my-workspace --create-application=false
cd my-workspace
ng generate library my-lib
```

Create a file `./projects/shared.ts`:

```
export interface Hello {
 world: string;
}
```

Import this file somewhere in the library, e.g. in `./projects/my-lib/src/lib/my-lib.service.ts`.

What I tried:
- Setting `rootDir` or `rootDirs` in tsconfig.json does not have any effect.
- Setting `paths` in tsconfig.json does not change the error

### Describe the solution you'd like
Any solution importing a file from outside the library (e.g. I do share TypeScript interfaces with the Node.js backend) would be great! I searched for hours finding no solution.

**Comment by JoostK** [comment] 2021-01-20 16:39
Moving to the CLI repo as this doesn't concern FW behavior.

Libraries need to be self-contained as they are suppposed to be shipped as standlone packages to NPM. This is why it's forbidden to reference files that fall outside of the directory boundary of a package, as that would put them outside of the package. It is certainly possible to capture the shared interfaces in a library/entry-point of its own and reference that from other places, which I believe is the actual way to go here.

**Comment by alan-agius4** [comment] 2021-01-20 16:49
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1264

**Closed by alan-agius4** 2021-01-20 16:49 UTC

**Comment by MickL** [comment] 2021-01-20 17:02
A library can be self contained no matter if it imports from outside of its root folder. A common example is that is it allowed to import from node_modules. In my opinion if it is forbidden or not should be decided by the developer.

**Comment by MickL** [comment] 2021-01-20 17:06
I opened another issue ng-packagr/ng-packagr#1841 as ng-packagr/ng-packagr#1264 does not seem to describe the same.
