### ISSUE TITLE
CSS: "z-index: 902;" after build become "z-index:#902;"

### ISSUE THREAD

**Issue by cesco69** [angular/angular-cli#20970] opened 2021-05-27 14:50 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build

### Description

the source css of a component:

```css
#particles-js {
    z-index: 902;
}
```

after the build become (`901` become `#901`):

```css
#particles-js {
    z-index:#902;
}
```

## 🔬 Minimal Reproduction

**Step 1**: create a component

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `<div id="particles-js"></div>`,
  styles: [`
    #particles-js {
        z-index: 902;
    }
  `]
})
export class AppComponent {
  title = 'my-app';
}
```

**Step 2**: make a build with

```
ng build
```

output in `index.html`

```html
<style>
#particles-js[_ngcontent-fpy-c98]{z-index:#901;}
<style>
```

with `ng serve` it works:

```html
<style>
#particles-js[_ngcontent-reu-c11] {
  z-index: 902;
}
<style>
```

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.2
Node: 12.22.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 12.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@schematics/angular             12.0.2
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Comment by alan-agius4** [comment] 2021-05-27 15:03
Duplicate of https://github.com/angular/angular-cli/issues/20918

**Closed by alan-agius4** 2021-05-27 15:03 UTC

**Comment by cesco69** [comment] 2021-05-27 15:09
My build is make into docker container (gitlab-ci). Node modules are installed fresh every build.

**Comment by cesco69** [comment] 2021-05-27 15:17
My build is make into docker container (gitlab-ci). Node modules are installed fresh every build.

**Comment by alan-agius4** [comment] 2021-05-27 15:24
Doesn’t matter if you have a package-lock.json.

**Comment by cesco69** [comment] 2021-05-27 15:27
Yes, I have it... For fix, i need to delete `package-lock.json` make a clean `npm install` and rebuild?

**Comment by alan-agius4** [comment] 2021-05-27 15:28
Yes
