### ISSUE TITLE
Error ng new project

### ISSUE THREAD

**Issue by vonat** [angular/angular-cli#1582] opened 2016-08-06 18:28 UTC
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**Linux: ubuntu/trusty64**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
**angular-cli: 1.0.0-beta.10
node: 6.3.1
os: linux x64**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
**ng new project**

4. The log given by the failure. Normally this include a stack trace and some
   more information.
_(node:16202) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
installing ng2
  create .editorconfig
  create README.md
  create src/app/app.component.css
  create src/app/app.component.html
  create src/app/app.component.spec.ts
  create src/app/app.component.ts
  create src/app/environment.ts
  create src/app/index.ts
  create src/app/shared/index.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/system-config.ts
  create src/tsconfig.json
  create src/typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config/environment.dev.ts
  create config/environment.js
  create config/environment.prod.ts
  create config/karma-test-shim.js
  create config/karma.conf.js
  create config/protractor.conf.js
  create e2e/app.e2e-spec.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create e2e/typings.d.ts
  create .gitignore
  create package.json
  create public/.npmignore
  create tslint.json
  create typings.json
Successfully initialized git.
ENOENT: no such file or directory, chmod '/var/www/html/angular2/max-ang2/project/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-sign'
Error: ENOENT: no such file or directory, chmod '/var/www/html/angular2/max-ang2/project/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-sign'
    at Error (native)_

**Comment by hansl** [comment] 2016-08-08 02:04
Can you give us more information?

Are you using an NPM (or http) proxy?  Do you have admin access? Do you have ember-cli addons?

The path in the output seems utterly wrong. angular-cli does not depend on angular-cli. Furthermore, new projects don't depend on `npm`.

**Comment by vonat** [comment] 2016-08-08 14:39
Sure, I can.
This system is an 'ubuntu/trusty64' was newly installed on Vagrant.

**1, I use NVM - NodeVersionManager installed with these commands:**
"
  _cd ~
  sudo apt-get update
  sudo apt-get install -y build-essential libssl-dev
  curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh -o install_nvm.sh
  bash install_nvm.sh
  source ~/.profile
  nvm install 6.3.1_
"
Now I have this versions installed on the system:
vagrant@webc0001-msrv0002:~$ node -v
v6.3.1
vagrant@webc0001-msrv0002:~$ npm -v
3.10.3


**2, I use these commands to install Watchman:**
"
  _git clone https://github.com/facebook/watchman.git
  cd watchman/
  git checkout v4.5.0
  sudo apt-get install -y autoconf automake build-essential python-dev
  ./autogen.sh 
  ./configure 
  make
  sudo make install_
"
Now I have this version of Watchman:
vagrant@webc0001-msrv0002:~/watchman$ watchman -v
4.5.0


**3, I use this command to install Angular-cli globaly:**
_"npm install -g angular-cli"._

Then I like to make a new Angular2 project with cli:
_"ng new project"._
I got this error:

> (node:15677) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
> installing ng2
>   create .editorconfig
>   create README.md
>   create src/app/app.component.css
>   create src/app/app.component.html
>   create src/app/app.component.spec.ts
>   create src/app/app.component.ts
>   create src/app/environment.ts
>   create src/app/index.ts
>   create src/app/shared/index.ts
>   create src/favicon.ico
>   create src/index.html
>   create src/main.ts
>   create src/system-config.ts
>   create src/tsconfig.json
>   create src/typings.d.ts
>   create angular-cli-build.js
>   create angular-cli.json
>   create config/environment.dev.ts
>   create config/environment.js
>   create config/environment.prod.ts
>   create config/karma-test-shim.js
>   create config/karma.conf.js
>   create config/protractor.conf.js
>   create e2e/app.e2e-spec.ts
>   create e2e/app.po.ts
>   create e2e/tsconfig.json
>   create e2e/typings.d.ts
>   create .gitignore
>   create package.json
>   create public/.npmignore
>   create tslint.json
>   create typings.json
> Successfully initialized git.
> ENOENT: no such file or directory, chmod '/var/www/html/project/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-sign'
> Error: ENOENT: no such file or directory, chmod '/var/www/html/project/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-sign'
>     at Error (native)

What do I wrong?
Gonna do it differently?

- Are you using an NPM (or http) proxy?
  **I use NPM.**
- Do you have admin access?
  **Yes, I have admin rights with SUDO if needed.**
- Do you have ember-cli addons?
  **Ember-cli not installed. Should I?**

**Comment by filipesilva** [comment] 2016-08-15 02:18
I'll mark this as a dupe of https://github.com/angular/angular-cli/issues/1522. You shouldn't need to install `ember-cli` separately, no.

**Closed by filipesilva** 2016-08-15 02:18 UTC
