### ISSUE TITLE
production build including all js and multiple file , but in production build , it should have minimum file and minified files.  and also ng build -prod not working .. it very big issue with production ..  this should be first priority 

### ISSUE THREAD

**Issue by kamleshKumarVerma** [angular/angular-cli#926] opened 2016-05-26 08:46 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipeaguiar** [comment] 2016-05-28 02:51
You should consider changing the title to something shorter.

My sugestion:
> `ng build -prod` not working or generating unnecessary files

**Comment by filipesilva** [comment] 2016-06-01 01:50
@kamleshKumarVerma I'm not really sure what you mean. Currently prod mode will bundle and minify files, as of beta.5. Is that not what you are experiencing?

If it is not working for you, can you provide me with reproduction steps so I can try and debug the issue?

**Comment by thunderrun** [comment] 2016-06-02 12:34
in `package.json`
change dependency `systemjs` from 
```"systemjs": "0.19.26"```
to
```"systemjs": "0.19.29"```
and then `npm install`

Angular cli should release a new version and change the dependencies in `package.json` to the latest or just tell users to do this in `README.md` or more issues like this will pop up.

**Comment by filipesilva** [comment] 2016-06-02 15:00
@thunderrun what is that change meant to fix?

**Comment by hellsan631** [comment] 2016-06-02 19:14
having the same issue, and tried the fix as posted by @thunderrun, but unfortunately it didn't work.

Any time I add -prod to either ng build or ng serve, nothing loads in the app. There are no errors in console either. Here is a look at the network screen: https://gyazo.com/91eb02e1c84a9580fc8e1d0af8fc12e3

without the prod flag, everything works fine.

**Comment by thunderrun** [comment] 2016-06-03 04:36
@filipesilva 
`systemjs` in angular-cli beta.5 packages.json is still `0.19.26`
which cause production builds fail when i add 3rd part libs  #839
so i changed `systemjs` to the latest version and seems it just works for me...

**Comment by filipesilva** [comment] 2016-06-03 15:26
@thunderrun `systemjs-builder` has a dependency on a later version of `systemjs` so I don't think it changes much. I'll investigate though, maybe something got fixed there.

@hellsan631 see https://github.com/angular/angular-cli/issues/951 for that problem.

**Comment by filipesilva** [comment] 2016-06-04 15:25
Closing as I can't get an answer back from the original poster. @kamleshKumarVerma if you're still having trouble reply here so I can reopen the issue.

**Closed by filipesilva** 2016-06-04 15:25 UTC
Labels: need: more info, need: repro steps
