### ISSUE TITLE
Angular 11 to 12 upgrade Breaks Styling on Test

### ISSUE THREAD

**Issue by ThisThato** [angular/angular-cli#22542] opened 2022-01-21 12:47 UTC
I recently upgrade an angular application from version 11 to 12. It works locally but it breaks the styling on test and it shows the a CSP error. 
I attached screenshots of my angular.json and CSP values. 
The application also uses angular material

![image](https://user-images.githubusercontent.com/39223762/150529284-7723f40e-ba9c-4131-8463-10c5ef275509.png)
`<add name="Content-Security-Policy" value="default-src 'self'; style-src 'self' 'unsafe-inline' 'unsafe-hashes' 'unsafe-eval';  script-src 'self' 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline' 'unsafe-hashes' 'unsafe-eval';/>`

![image](https://user-images.githubusercontent.com/39223762/150529670-ee15e243-a0c0-4524-8dd5-ec5c7ddb95f1.png)

**Comment by alan-agius4** [comment] 2022-01-21 13:34
Duplicate of https://github.com/angular/angular-cli/issues/20864

**Closed by alan-agius4** 2022-01-21 13:34 UTC
