### ISSUE TITLE
`--help` must be run in a workspace.

### ISSUE THREAD

**Issue by dgp1130** [angular/angular-cli#16616] opened 2020-01-10 00:34 UTC
# 🐞 Bug report

### Command

- [X] help

### Is this a regression?

Don't know.

### Description

Running `ng generate --help` outside of an Angular project throws an error. Help should not need to be in a specific project to function.

## 🔬 Minimal Reproduction

```shell
cd some/random/location/outside/an/angular/project
ng generate --help
```

## 🔥 Exception or Error

```
An unhandled exception occurred: Unable to locate a workspace file for workspace path.
See "/usr/local/google/home/douglasparker/Temp/ng-0xcBR4/angular-errors.log" for further details.
```

## 🌍 Your Environment

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.21
Node: 10.15.3
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.21
@angular-devkit/core         8.3.21
@angular-devkit/schematics   8.3.21
@schematics/angular          8.3.21
@schematics/update           0.803.21
rxjs                         6.4.0
```

**Comment by alan-agius4** [comment] 2020-01-10 08:14
Duplicate of https://github.com/angular/angular-cli/issues/16241

**Closed by alan-agius4** 2020-01-10 08:14 UTC
Labels: comp: angular/cli, freq1: low, priority: 3 (nice to have), severity2: inconvenient, type: bug/fix
