### ISSUE TITLE
Pass an environment variable from heroku to angular cli

### ISSUE THREAD

**Issue by vincentrebelz** [angular/angular-cli#4914] opened 2017-02-22 11:09 UTC
Hi,
I wanted to know if it was possible possible to do so and how to do it.
For node.js it's "process.env.api" but this does not apply for angular.
I'm running angular cli on heroku.

**Comment by filipesilva** [comment] 2017-03-13 19:07
Dupe of https://github.com/angular/angular-cli/issues/4419

**Closed by filipesilva** 2017-03-13 19:07 UTC
