### ISSUE TITLE
"Module not found: Error: Can't resolve..." when consuming declarations

### ISSUE THREAD

**Issue by zuzusik** [angular/angular-cli#13658] opened 2019-02-12 15:36 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 

Not sure
### Description

`/src/app/components/buggy-component.ts`:
```ts
import {SomeClass} from '../../../declarations/package';
import {Component} from '@angular/core';

@Component({
  selector: 'buggy-component',
  template: '<div>test</div>'
})
export class BuggyComponent {
  constructor(private prop : SomeClass) {}
}
```
Error:
```
ERROR in ./src/app/components/buggy-component.ts
Module not found: Error: Can't resolve '../../../declarations/package' in '/Users/zuzusik/projects/typescript-bug/src/app/components'
```

`src/app/components/buggy-component-workaround.ts`

```ts
import {SomeClass} from '../../../declarations/package';
import {Component} from '@angular/core';

@Component({
  selector: 'buggy-component-workaround',
  template: '<div>test</div>'
})
export class BuggyComponentWorkaround {
  private prop : SomeClass;

  constructor(prop) {
    this.prop = prop;
  }
}
```
No errors

## 🔬 Minimal Reproduction

clone https://github.com/zuzusik/typescript-bug
run `npm install`
run `ng serve`

## 🔥 Exception or Error
<pre><code>
ERROR in ./src/app/components/buggy-component.ts
Module not found: Error: Can't resolve '../../../declarations/package' in '/Users/zuzusik/projects/typescript-bug/src/app/components'
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.1
Node: 8.12.0
OS: darwin x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.1
@angular-devkit/build-optimizer   0.13.1
@angular-devkit/build-webpack     0.13.1
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  7.3.1
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

I need such a construction to inject service from Angular.js and specify it's type from compiled .d.ts file.

**Comment by mgechev** [comment] 2019-02-12 18:19
I can see the inconsistency in the behavior but I don't think there's anything we can do on our side. Here's what happens:

- You declare that you want to use the type `SomeClass` as a DI token
- TypeScript emits metadata for the component because of the `@Component` decorator
- Later, webpack tries to resolve the symbol but it cannot find it, since it's stripped as part of the TypeScript compilation process

What you can do to workaround this issue is:

```ts
import {SomeClass} from '../../../declarations/package';
import {Component, Inject} from '@angular/core';

@Component({
  selector: 'buggy-component',
  template: '<div>test</div>'
})
export class BuggyComponent {
  constructor(@Inject(Token) private prop : SomeClass) {}
}
```

Make sure that the `Token` exists as a JavaScript symbol.

**Comment by alan-agius4** [comment] 2019-02-12 18:27
Closing as per @mgechev comment above.

**Closed by alan-agius4** 2019-02-12 18:27 UTC

**Comment by zuzusik** [comment] 2019-02-12 18:29
@mgechev I have similar code in my real project where I use `@Inject(Token)` - it has exactly the bug described above, my `Token` is a result of `new InjectionToken('ajsServiceName')`

@alan-agius4 could you please re-open it? I don't think it is solved yet...

**Comment by zuzusik** [comment] 2019-02-12 18:33
@mgechev I have implemented what you suggested here: https://github.com/zuzusik/typescript-bug/commit/b91a61ca99a4ff3e43b42e3f8fbb06e25844c9b9

still getting the same error:

```
ERROR in ./src/app/components/buggy-component.ts
Module not found: Error: Can't resolve '../../../declarations/package' in '/Users/zuzusik/projects/typescript-bug/src/app/components'
```

**Comment by alan-agius4** [comment] 2019-02-13 10:30
@zuzusik, the token needs to be registered as a DI provider. Also note, that since you are providing a `Class` and not an `Interface` these needs to have a corresponding Js symbol which is used for the `design:paramtypes`. An alternative would be to use an interface, since this will have a symbol of an object.

That said, this is working as intended. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
