### ISSUE TITLE
ng e2e --no-serve no longer works

### ISSUE THREAD

**Issue by raysuelzer** [angular/angular-cli#10761] opened 2018-05-09 18:45 UTC
### Versions: 6.0.0
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

*Step 1 `> ng serve`
*Step 2 `>  ng e2e --no-serve`

### Observed behavior
```
> ng "e2e" "--no-serve"
Port 4200 is already in use. Use '--port' to specify a different port.
```

### Desired behavior

What would like to see implemented? --no-serve option to be back
What is the usecase? Very nice to be able to run e2e tests without the compile step.
What did you expect to see? The same behavior as in previous CLI version.

### Mention any other details that might be useful (optional)

Has the --no-serve functionality been moved elsewhere? I haven't been able to find any documentation on this in the release notes (mostly googling).

**Comment by clydin** [comment] 2018-05-09 19:27
Duplicate of #10741

**Closed by clydin** 2018-05-09 19:27 UTC

**Comment by jai-rathore** [comment] 2018-07-06 21:02
In the angular.json file, in the subsection -> "projects" -> "projectName-e2e" -> "architect" ->"options" - remove the "devServerTarget" option,
While running the e2e scripts, use command `ng e2e --project=projectName-e2e`
