### ISSUE TITLE
"index.ts is missing from the TypeScript compilation" after update angular and cli verion

### ISSUE THREAD

**Issue by dyh333** [angular/angular-cli#9376] opened 2018-01-25 06:42 UTC
### Versions
```
Angular CLI: 1.6.5
Node: 6.12.0
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps
this is my repo: 
[core-module](https://github.com/sz-igeo/core-module)
[login-module](https://github.com/sz-igeo/login-module)
* login-module: install core-module from file path like "file:///F:\\Projects\\angular-framework\\core-module"
* login-module: npm start
* show 

### Observed behavior
![image](https://user-images.githubusercontent.com/1221313/35374323-580617da-01dd-11e8-98e7-a13a92e44aac.png)

### Desired behavior
run as nomal

### Mention any other details that might be useful (optional)
this bug appear after updating angular 4.x to 5.x, and cli update to 1.6.5 also.

@filipesilva ,  could you kindly help me? I had try to update [tsconfig.json or tsconfig.app.json](https://github.com/angular/angular-cli/issues/9142), but still failed 

thanks!

**Comment by Jmadih** [comment] 2018-01-25 10:00
Same here ! After adding a `dependencie.`
I got the warning : 

```
@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
```
and i got the error :
`ng2-breadcrumb.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.`

**Comment by filipesilva** [comment] 2018-01-25 10:09
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/8284. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2018-01-25 10:09 UTC

**Comment by babagay** [comment] 2018-01-25 16:08
The same sing but with lunching karma test. "Module build failed: Error: app\app.component.spec.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property."
`//tsconfig.app.json
...
 "include": [
    "../src/**/*"
  ],
...
`
