### ISSUE TITLE
@ngtools/webpack complainning about not an NgModule

### ISSUE THREAD

**Issue by princemaple** [angular/angular-cli#3157] opened 2016-11-16 11:35 UTC
using `@ngtools/webpack` 1.1.7
tried both `@angular/compiler-cli` 2.1.x and 2.2.0

```js
import { NgModule, Component } from '@angular/core';

@Component({
  selector: 'app',
  template: '<h1>hello world</h1>',
  styles: []
})
class AppComponent {}

@NgModule({
  declarations: [AppComponent],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

```
Error: AppModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (/var/build/node_modules/@ngtools/webpack/src/plugin.js:297:19)
    at AotPlugin._processNgModule (/var/build/node_modules/@ngtools/webpack/src/plugin.js:241:42)
    at /var/build/node_modules/@ngtools/webpack/src/plugin.js:217:39
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
Done in 7.29s.
```

**Comment by marinho** [comment] 2016-11-17 03:15
@princemaple can you paste your AotPlugin configuration, please?

**Comment by marinho** [comment] 2016-11-17 03:18
oops, I missed this is an angular-cli related. Without it (i.e. just using `@ngtools/webpack`), that error message would appear if `entryModule` points to the wrong path (i.e. `./src/app/app.module#AppModule` must be a valid path)

**Comment by princemaple** [comment] 2016-11-17 03:18
I had a very simple minimal AotPlugin config, something like

```js
new ngtools.AotPlugin({
  tsConfigPath: '/var/build/tsconfig.json',
  entryModule: '/var/build/src/app.module#AppModule'
})
```

**Comment by princemaple** [comment] 2016-11-17 03:21
Note I used absolute paths, because I saw some commits in this repo saying something about relative paths not working. I am pretty sure my path was valid.

**Comment by marinho** [comment] 2016-11-17 05:18
I see. In that case, I have no more to add.

**Comment by janwo** [comment] 2016-11-17 08:51
I have the same problem here. I also configured it like @princemaple.

**Comment by princemaple** [comment] 2016-11-17 08:57
@marinho thanks for taking a look still!

**Comment by janwo** [comment] 2016-11-17 14:52
```js
AotPlugin.prototype.getNgModuleMetadata = function (staticSymbol) {
    var ngModules = this._reflector.annotations(staticSymbol).filter(function (s) { 
        return s instanceof core_1.NgModule; 
    });
    if (ngModules.length === 0) {
        throw new Error(staticSymbol.name + " is not an NgModule");
    }
    return ngModules[0];
};
```

Whereas `staticSymbol` is... 
```js
{
  filePath: '/Users/***skipped***/client/app/app.module.ts',
  name: 'AppModule',
  members: undefined 
}
```

...and `this._reflector.annotations(staticSymbol)` is `[]`.

Seems like the annotations are not set correctly? The path is valid.

**Comment by marinho** [comment] 2016-11-18 07:42
@janwo did you try without ".ts" in `filePath`?

When enabling AoT, it didn't pass because I had some imports with `.ts` in the end. I just removed in all lines it found and it didn't complain anymore. Maybe it's the same case.

BTW, I still don't have my app successfully in AoT. I'm also learning in this topic at this very moment.

**Comment by janwo** [comment] 2016-11-18 12:00
@marinho Thanks for your response. Yes, its all without a suffix. Somehow it works now, I deleted my node_modules folder and installed all dependencies again. It's weird as I updated them before as well.

**Comment by dhardtke** [comment] 2016-11-18 18:09
I have the same problem, see https://github.com/angular/angular-cli/issues/2667

**Comment by mashhoodr** [comment] 2016-11-22 16:47
Im also getting the same. If I build a new project using `ng new` and run -aot on that, it works fine - but on my own project im getting  `Error: AppModule is not an NgModule`. I have removed everything from my AppModule and AppComponent.

**Comment by dhardtke** [comment] 2016-11-22 22:09
I have the problem with the AotPlugin for Webpack...

**Comment by jessezhang91** [comment] 2016-11-22 22:15
It seems like `typescript@2.1.1` is causing the issue. Downgrading to `2.0.10` seems to make it pick up the metadata correctly.

**Comment by zakdances** [comment] 2016-12-02 12:00
Strangely, this error shows up on `2.2.4` but not `2.2.3`.

**Comment by dhardtke** [comment] 2016-12-02 12:01
For me downgrading to `typescript@2.0.10` worked, just like jessezhang91 suggested.

**Comment by e-oz** [comment] 2016-12-02 12:02
@zakdances thanks for heads up. Will skip this update :) Previous dancing with this error is hard to forget.

**Comment by mashhoodr** [comment] 2016-12-02 12:11
Downgrading to 2.0.12 didnt work for me. :( When I run `ng server --aot` I still get this error. (double checked the installed version as well)

**Comment by dhardtke** [comment] 2016-12-02 12:12
`2.0.12` != `2.0.10`

**Comment by mashhoodr** [comment] 2016-12-02 12:14
Sorry, I meant to write 2.0.10.

**Comment by DutchKevv** [comment] 2016-12-02 23:33
@zakdances downgrading all packages to 2.2.3 didn't work for me..:( Which packages did you downgraded to 2.2.3 exactly?? Thanks

**Comment by jessezhang91** [comment] 2016-12-03 01:32
@DutchKevv make sure you downgrade router to 3.2.3 or so as well.

**Comment by DutchKevv** [comment] 2016-12-04 19:15
Thanks Jess, but didn't get it to work..

Using these packages ->

  "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/router": "3.2.3",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/store": "2.2.1",
    "@ngrx/store-devtools": "^3.2.1",
    "@ngrx/store-log-monitor": "^3.0.2",


Probably just wait until Typescript and Angular are friends again on final releases.. But can't build production now :(

**Comment by e-oz** [comment] 2016-12-04 19:19
@DutchKevv try to `rm -rf npm_modules && npm cache clean` before installation.

**Comment by Quramy** [comment] 2016-12-04 19:49
I think this issue is related to `typscript@2.1.x` and tsc-wrapped as dhardtke and jessezhang91 said.

In https://github.com/angular/angular/blob/2.2.x/tools/@angular/tsc-wrapped/src/collector.ts#L254 , which is collect metadata from `app.module.ts` , 

```typescript
        case ts.SyntaxKind.ClassDeclaration:
          const classDeclaration = <ts.ClassDeclaration>node;
          if (classDeclaration.name) {
            const className = classDeclaration.name.text;
            if (node.flags & ts.NodeFlags.Export) { // this is false always! 
              if (classDeclaration.decorators) {
                if (!metadata) metadata = {};
                metadata[className] = classMetadataOf(classDeclaration);
              }
            }
          }
``` 

it seems this code works only if `ts.NodeFlags.Export` is truthy. But in https://github.com/Microsoft/TypeScript/blob/v2.1.1/src/compiler/types.ts#L400 , there is no export enum named `Export`. (In typescript@2.0.10 `ts.NodeFlags` has the `Export` value. see https://github.com/Microsoft/TypeScript/blob/v2.0.10/src/compiler/types.ts#L395 )

**Comment by beeman** [comment] 2016-12-05 23:44
I'm getting the same error using TypeScript 2.0.10, trying to link modules from 1 app into another. Both are generated using angular-cli version 1.0.0-beta.22.

**Comment by tarlepp** [comment] 2016-12-06 12:29
Yep same problem here with `"typescript": "2.0.10"` and `"angular-cli": "1.0.0-beta.22-1"` any solutions ?

**Comment by antonybudianto** [comment] 2016-12-06 13:34
not working even with typescript 2.0.10, using @ngtools/webpack 1.1.9

**Comment by timosalm** [comment] 2016-12-06 15:46
@tarlepp @antonybudianto Workaround: Specify the precise dependency versions in the package.json.

**Comment by antonybudianto** [comment] 2016-12-06 15:53
@timosalm already did

**Comment by e-oz** [comment] 2016-12-06 16:18
Dear Angular team, maybe it's not obvious, but it's a very dangerous bug - when users can't build production build, it means development of their projects is stopped. And it's not so easy to explain to product owners why it's impossible (for now) to implement minor changes (even if task is just edit text).
And this bug is not even labeled.
Please, give some attention to this bug. I understand you have a lot of tasks, but it's really important bug.

**Comment by jessezhang91** [comment] 2016-12-06 17:21
Here're my dependencies. They seem to be working with no issues
```
@angular/common@2.2.4
@angular/compiler@2.2.4
@angular/compiler-cli@2.2.4
@angular/core@2.2.4
@angular/forms@2.2.4
@angular/http@2.2.4
@angular/platform-browser@2.2.4
@angular/platform-browser-dynamic@2.2.4
@angular/router@3.2.4
@ngtools/webpack@1.1.9
typescript@2.0.10
```

**Comment by tarlepp** [comment] 2016-12-06 17:33
@timosalm And what are those "precise dependency versions" I only updated `"angular-cli"` to latest and that broke all. Changes [here](https://github.com/tarlepp/angular2-firebase-material-demo/commit/ebbb982c2979b5046807f57d121c771a8b674a79)

**Comment by beeman** [comment] 2016-12-06 17:44
@tarlepp I've created a separate issue for this issue introduced by angular-cli version 1.0.0-beta.22 : #3426

**Comment by vascofernandes** [comment] 2016-12-06 19:02
same problem:
"@ngtools/webpack": "1.1.9",
"typescript": "^2.0.10",
"webpack": "^2.1.0-beta.27"

**Comment by jkuri** [comment] 2016-12-06 21:29
Please check https://github.com/angular/angular-cli/issues/3426#issuecomment-265277988 for a solution.

**Comment by dwightgunning** [comment] 2016-12-06 22:13
I've just today started to work with ngc and am hitting this same error.

I also stripped back my ``entryModule`` to the bare minimum.

```
import { NgModule, Component } from '@angular/core';

@Component({
  selector: 'app',
  template: '<h1>hello world</h1>',
  styles: []
})
class AppComponent {}

@NgModule({
  declarations: [AppComponent],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

All my @angular/ packages are aligned at version 2.2.4 and I've done my best to update all related webpack and typescript related plugins. There are other packages which may be out of date, but as none of them are imported via my AppModule, I can't see why'd they'd effect the compilers ability to load the AppModule (or at least report a meaningful error).

I've tried both relative and absolute paths for the entryModule.

**Comment by jessezhang91** [comment] 2016-12-06 22:37
@vascofernandes Instead of "^2.0.10" for typescript, try "2.0.10" exactly. I had it install 2.1.1 for me when I had `^` before.

**Comment by vascofernandes** [comment] 2016-12-07 07:37
Hi,
I just tried that and and no success, same error.

**Comment by alvipeo** [comment] 2016-12-07 20:34
shit, same here with cli "1.0.0-beta.22-1" :(

**Comment by avitiw** [comment] 2016-12-08 10:51
It works for me with 
 @angular/common@2.2.4
@angular/compiler@2.2.4
@angular/compiler-cli@2.2.4
@angular/core@2.2.4
@angular/forms@2.2.4
@angular/http@2.2.4
@angular/platform-browser@2.2.4
@angular/platform-browser-dynamic@2.2.4
@angular/router@3.2.4
@ngtools/webpack@1.1.9
typescript@2.0.10

**Comment by dwightgunning** [comment] 2016-12-08 10:54
Yes, when I downgraded from Typescript 2.1.4 to 2.0.10 it works. I wish I
could tell you why.

Regards,

Dwight

**Comment by hansl** [comment] 2016-12-08 22:22
Fixed a lot of issues with path resolution and having your tsconfig in a different path than your webpack config. Closing this as fixed.

**Closed by hansl** 2016-12-08 22:22 UTC

**Comment by arciisine** [comment] 2016-12-09 13:25
@hansl I'm experiencing this with an cli-built application that I upgraded from 1.0.0-beta.21 to 1.0.0-beta.22-1.
```
10% building modules 2/2 modules 0 active(node:39556) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: AppModule is not an NgModule
```
As far as I know the webpack config should be transparent to cli users, unless I'm missing something.

**Comment by brugsel** [comment] 2016-12-12 09:33
For me, fixing the versions in package.json fixed it:
- Angular 2.2.3
- Router on 3.2.3
- Typescript 2.0.10

**Comment by tinchou** [comment] 2016-12-14 03:50
I can confirm it breaks with TypeScript 2.1.4 and then works again after downgrading to 2.0.10.

@hansl please reopen this so someone can take a look, or at least point us to another issue where you're tracking this.

**Comment by beeman** [comment] 2016-12-14 04:05
> Fixed a lot of issues with path resolution and having your tsconfig in a different path than your webpack config. Closing this as fixed.

@hansl is this fixed in master?

**Comment by MortimerCat** [comment] 2016-12-15 15:06
As per @tinchou I am unable to compile 
Angular 2.2.3
Router on 3.2.3
Typescript 2.0.10

**Comment by rgiosa** [comment] 2016-12-22 14:24
My external modules only builds when:

Angular: 2.2.3
Router: 3.2.3
Typescript: 2.0.10
Angular-Cli: 1.0.0-beta.15

I've tried several combinations.

```
npm uninstall angular-cli -g
npm cache clean
npm install angular-cli@1.0.0-beta.15 -g
```

**Comment by misterwise** [comment] 2016-12-25 11:50
@hansl this is a legitimate issue and should be reopened, I also recently upgraded to Angular-Cli:1.0.0-beta.24 and encountered this breaking change, preventing work on a production site.  Downgrading to beta.22 and related packages resolved the issue.

**Comment by anderflash** [comment] 2016-12-25 16:45
It builds (dev and prod) even though the error is shown. I use latest versions:
- angular 2.4.1
- typescript 2.1.4 
- angular-cli 1.0.0-beta.24

**Comment by ichent** [comment] 2016-12-26 12:27
Hello.
I have this error today, after I will try to update angular to 2.4.1. 
Today I saw many errors, and "AppModule is not an NgModule", and "cannot read property codegen" and so on. Then I changed my package.json to previous state (worked state), and now I getinng an error "AppModule is not an NgModule". A current package.json is 
{
angular: 2.2.3,
router: 3.2.3,
"@ngtools/webpack": "1.1.9",
}

**Comment by greenginger** [comment] 2017-01-05 12:21
I had the "AppModule is not an NgModule" error plus various others. I've somehow now got Angular 2.4.1 working with Angular CLI 1.0.0-beta.24 and Typescript 2.0.10 !! :o) 

(But not with 2.1.4, that produced the AppModule is not an NgModule". Given [this](https://github.com/angular/angular/issues/13715) I suspect I need to wait a while for Angular to work with Typescript 2.1.4.)

I followed the steps here for [updating Angular-CLI](https://www.npmjs.com/package/angular-cli#updating-angular-cli) 

And here are my dependencies from package.json:
`
 "dependencies": {
    "@angular/common": "2.4.1",
    "@angular/compiler": "2.4.1",
    "@angular/core": "2.4.1",
    "@angular/forms": "2.4.1",
    "@angular/http": "2.4.1",
    "@angular/platform-browser": "2.4.1",
    "@angular/platform-browser-dynamic": "2.4.1",
    "@angular/platform-server": "2.4.1",
    "@angular/router": "3.4.1",
    "@angularclass/conventions-loader": "^1.0.2",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "core-js": "^2.4.1",
    "http-server": "^0.9.0",
    "ie-shim": "^0.1.0",
    "jasmine-core": "^2.5.2",
    "reflect-metadata": "^0.1.9",
    "rxjs": "~5.0.2",
    "zone.js": "~0.7.4",    
    "ts-helpers": "^1.1.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.4.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "2.0.10"
  }
`

**Comment by e-oz** [comment] 2017-01-05 18:29
@hansl I guess you closed this issue just because you assumed it should be somehow fixed, without checking it and asking affected users, right? Please reopen it and please let's find solution for this issue - it's pretty critical thing. Angular CLI is not usable at this moment because of this issue.

**Comment by JesterXL** [comment] 2017-01-06 01:30
I need(ed?) TypeScript 2.1.x for Generator support. Typescript 2.2.3, 2.1.4, and 2.1.3-insiders.20161130 didn't work (I couldn't find 2.1.3). Dropping to 2.0.10 like suggested fix it.

I should note an older project had `"angular-cli": "^1.0.0-beta.19-3",` and `"typescript": "v2.1.1"` and that worked for both `ng serve` and `ng test`. Whatever, it works and only took 1 🍺.

**Comment by ichent** [comment] 2017-01-09 13:15
Hello.
Today I removed @ngtools/webpack from my project and now I'm using webpack for AoT. I'm happy.

**Comment by princemaple** [comment] 2017-01-09 13:16
How is that done?

**Comment by arciisine** [comment] 2017-01-09 13:17
Angular 2.4.2 just landed which fixed TS 2.1 support.  I've successfully built 2.4.2 with typescript 2.1.4 and beta 24 of the cli.

**Comment by sbley** [comment] 2017-01-09 14:00
@arciisine Which Angular dependency has to be updated to 2.4.2? common, core?

**Comment by jkuri** [comment] 2017-01-09 14:02
@sbley `compiler-cli` at least, preferable all.

**Comment by sbley** [comment] 2017-01-09 14:03
Yeah, in the end these are peer dependencies. If you update one you gotta update all...

**Comment by ichent** [comment] 2017-01-09 15:34
@princemaple What do you mean?
Yesterday I founded an example here https://github.com/blacksonic/angular2-aot-webpack (big thanks to the author). But my roadmap is a little bit different
And now, I'm using webpack. Here is a part of my webpack.config.
.....
{
                    test: /\.ts$/,
                    loaders: env.aot ?
                        ['awesome-typescript-loader?tsconfig=./client-code/src/tsconfig.json', 'angular2-template-loader', 'angular2-router-loader?genDir=./client-code/src/aot-compiled/app&aot=true'] :
                        ['awesome-typescript-loader?tsconfig=./client-code/src/tsconfig.json', 'angular2-template-loader', 'angular2-router-loader']
                }
...

With 'angular2-router-loader' I can split my bundles.

**Comment by rgiosa** [comment] 2017-01-09 17:43
Yeap, this is now working with Typescript 2.1.4!

```
angular-cli: 1.0.0-beta.24
node: 4.4.7
os: win32 x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2
```

**Comment by princemaple** [comment] 2017-01-10 04:07
@ichent thanks for the information about the alternative!

**Comment by ichent** [comment] 2017-01-10 08:53
@princemaple You are welcome!

**Comment by MortimerCat** [comment] 2017-01-10 10:03
I can also confirm that this is now working on the latest release versions.....

Angular 2.4.2
Router on 3.4.2
Typescript 2.1.4

**Comment by larssin** [comment] 2017-01-14 14:41
**Look for unwanted node_modules folders...**

I experienced the problem with "AppModule is not an NgModule" after trying to run "./node_modules/.bin/ngc" to build a translated version (the build failed and the app wasn't translated). 
I tried to reinstall, change versions etc. but nothing worked. 
I finally realized that something had created an extra node_modules folder under the src folder. It only contains "@angular" and "rxjs" folders. When I delete this extra node_modules I can build again.
However I still can't figure out how to use i18n - but that is another problem.

**Comment by AckerApple** [comment] 2017-05-17 18:41
I had one time forgot to add "typings"="index.d.ts" key to my package.json file. Once I did, I stopped getting Please add @NgModule error

**Comment by Maloric** [comment] 2017-05-22 09:18
In case anyone stumbles across this, in my case it was misconfiguration.  I was getting a `null is not an NgModule` error, which was because my entryModule missed of the name of the module:

```
    new ngtools.AotPlugin({
        tsConfigPath: './tsconfig.json',
        entryModule: root('src/app/pager') 
    })
```

became


```
    new ngtools.AotPlugin({
        tsConfigPath: './tsconfig.json',
        entryModule: root('src/app/pager') **+ '#PagerComponentModule'**
    })
```

**Comment by pratiksha-chandel** [comment] 2017-06-13 11:43
ng build and ng serve is not working for me .gives error 

ERROR in /home/pratiksha/migration//app/shared/user.service.spec.ts (7,3): Cannot find name 'beforeEach'.

ERROR in /home/pratiksha/migration/app/shared/user.service.spec.ts (13,3): Cannot find name 'it'.

ERROR in /home/pratiksha/migration/app/shared/user.service.spec.ts (14,5): Cannot find name 'expect'.

ERROR in PopoverModule is not an NgModule

ERROR in multi ./src/styles.css ./src/css/main.css ./src/css/font-awesome.min.css ./src/css/daterangepicker.css ./src/css/style.css ./src/css/style-bootstrap.css ./src/css/style-default.css ./src/css/style-material.css
Module not found: Error: Can't resolve '/home/pratiksha/migration/src/css/main.css' in '/home/pratiksha/migration/node_modules/@angular/cli/models/webpack-configs'
 @ multi ./src/styles.css ./src/css/main.css ./src/css/font-awesome.min.css ./src/css/daterangepicker.css ./src/css/style.css ./src/css/style-bootstrap.css ./src/css/style-default.css ./src/css/style-material.css

try all but not working for me . 
angular cli is not working after upgrade -this is not supporting to .spec.ts file .
why this is happing ?
