### ISSUE TITLE
ERROR in node_modules/@angular/platform-browser-dynamic/src/compiler_factory.d.ts

### ISSUE THREAD

**Issue by vishalbedre** [angular/angular-cli#11618] opened 2018-07-20 21:58 UTC
Hi all 

Used typescript 2.7.2 but giving me following error

**ERROR in node_modules/@angular/platform-browser-dynamic/src/compiler_factory.d.ts(18,22): error TS2720: Class 'CompilerImpl' incorrectly implements class 'Compiler'. Did you mean to extend 'Compiler' and inherit its members as a subclass?
  Property 'getModuleId' is missing in type 'CompilerImpl'.
node_modules/@angular/platform-browser-dynamic/testing/src/compiler_factory.d.ts(12,22): error TS2720: Class 'TestingCompilerImpl' incorrectly implements class 'TestingCompiler'. Did you mean to extend 'TestingCompiler' and inherit its members as a subclass?
  Property 'getModuleId' is missing in type 'TestingCompilerImpl'**

**Comment by alan-agius4** [comment] 2018-07-21 16:07
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by adi290491** [comment] 2018-07-27 07:52
I managed to solve this by checking the libraries.
1. Type npm outdated to check the version of each library.
2. The angular-platform-dynamic library could be outdate so install it with `npm i @angular/platform-browser-dynamic`.
3. You will also require tslib. So also install that with `npm i tslib`.
4 Then try ng serve.

**Comment by alan-agius4** [comment] 2018-09-04 06:01
Closing as it looks like a solution was provided above.

**Closed by alan-agius4** 2018-09-04 06:01 UTC
Labels: need: repro steps
