### ISSUE TITLE
application builder doesn't build a package that includes optionally node packages (fabric)

### ISSUE THREAD

**Issue by jcompagner** [angular/angular-cli#27291] opened 2024-03-14 16:13 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

the "browser" builder in the same version

### Description

when using the 'fabric' npm package (https://www.npmjs.com/package/fabric) and use that in your package then with the new application builder this won't build anymore,
With the browser builder this builds fine that seems to just ignore the optional stuff (or stuff that is not really used?)

[fabric.zip](https://github.com/angular/angular-cli/files/14605058/fabric.zip)

unzip this package and run npm install and then npm run build
this will fail
if then the application builder is changed to browser (browser property to  main ) then it does build fine.

### Minimal Reproduction

unzip
npm install
npm run build

### Exception or Error

```text
✘ [ERROR] Could not resolve "path"

    (disabled):node_modules/jsdom/lib/api.js:3:21:
      3 │ const path = require("path");
        ╵                      ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

### Your Environment

```text
Angular CLI: 17.3.0
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.0
@angular-devkit/build-angular   17.3.0
@angular-devkit/core            17.3.0
@angular-devkit/schematics      17.3.0
@schematics/angular             17.3.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by jcompagner** [comment] 2024-03-14 16:38
why is it that if i just do:

rmdir .\node_modules\jsdom\

and then a build it works?

shoudn't there then be a require or something (in fabric code) that is trying to include jsdoc which is not found?

**Comment by JoostK** [comment] 2024-03-14 18:41
Duplicate of #26870.

Fabric 5 is bundled as hybrid browser/node package, where `jsdom` is included using `require`. `require`s can fail if the dep cannot be loaded, so `jsdom` not being present doesn't generate a build time error. If `jsdom` is present however then the bundler will also include its sources, and since `jsdom` references native Node modules you now do get a build error as the bundler is instructed to build for browser environments.

The Fabric 6 branch has revamped this entirely, with a switch to support `exports` conditions in the package.json file.

**Closed by JoostK** 2024-03-14 18:41 UTC
