### ISSUE TITLE
build-angular 12 regression: Updates to node_modules properly trigger rebuilds, but vendor.js chunk is not updated by rebuild

### ISSUE THREAD

**Issue by nbitouze** [angular/angular-cli#21195] opened 2021-06-24 13:48 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: @angular-devkit/build-angular version 0.1102.14.

### Description

When running `ng serve`, changes to `.js` files in `node_modules` are properly detected and trigger a rebuild. However, the rebuild itself does not notice the changes and leaves everything unchanged.

This is particularly problematic when using the recommended flow to work on an angular library (using `ng build --watch` in the library to automatically rebuild it on change, and using `npm link` to link the library inside the main project's `node_modules`). In this particular scenario, updates to the libary's code trigger the library's build in its own `ng build --watch`. The build outputs data in the library's directory that the projects `node_module` symlinks to. The project's `ng serve` detects the update and recompiles. *But `vendor.js` is not updated*.

Sample output (trimmed newlines):
```
✔ Browser application bundle generation complete.
5 unchanged chunks
Build at: 2021-06-24T09:52:46.822Z - Hash: 10397e9fbdac4352dd17 - Time: 791ms
✔ Compiled successfully.
```

Same exact flow with version 0.1102.14:
```
✔ Browser application bundle generation complete.
Initial Chunk Files | Names  |    Size
vendor.js           | vendor | 8.34 MB
4 unchanged chunks
Build at: 2021-06-24T10:25:52.854Z - Hash: a8c2d9813f0281ecfff6 - Time: 4176ms
✔ Compiled successfully.
```

## 🔬 Minimal Reproduction

In an angular project that uses `@angular-devkit/build-angular` version 12 (I tried `12.0.3`, `12.0.5` and `12.1.0-next.6`):

1. Install, for instance, momentjs: `npm install moment`
2. Run `ng serve`.
3. While `ng serve` is running, make a meaningless edit to `node_modules/moment/moment.js` (like adding a whitespace at the beginning of the file). Using `touch` won't work, there has to be a small edit.
4. Observe that `ng serve` triggered a compile step, but did not update `vendor.js`.
5. Repeat every step with an older `@angular-devkit/build-angular` version (like `0.1102.14`). Step 4 will now show an update to `vendor.js`.

## 🌍 Your Environment

`ng version` where the bug occurs:
<pre><code>
Angular CLI: 12.0.5
Node: 14.15.5
Package Manager: npm 6.14.11
OS: linux x64

Angular: 12.0.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.1.0-next.6
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            6.6.3
typescript                      4.2.4

</code></pre>

`ng version` where the bug does not occur (notice that this version of build-angular is not really supposed to be compatible with angular 12, but it still works, and it also works as expected within an angular 11 project):
<pre><code>
Angular CLI: 12.0.5
Node: 14.15.5
Package Manager: npm 6.14.11
OS: linux x64

Angular: 12.0.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            6.6.3
typescript                      4.2.4
</code></pre>

**Comment by alan-agius4** [comment] 2021-06-24 13:53
Duplicate of https://github.com/angular/angular-cli/issues/20962

**Closed by alan-agius4** 2021-06-24 13:53 UTC

**Comment by nbitouze** [comment] 2021-06-24 14:35
Indeed, my bad. Thank you for the quick answer.
