### ISSUE TITLE
ng g s: Add ability to generate non-singleton services

### ISSUE THREAD

**Issue by am-trinity** [angular/angular-cli#11908] opened 2018-08-16 09:51 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
$ node --version
v10.8.0
$ npm --version
6.3.0
$ ng --version
Angular CLI: 6.0.7
Node: 10.8.0
OS: linux x64
```

### Repro steps

```
ng g service example
```

### The log given by the failure

New service not included in parent module with: 
```
...
@Injectable({
  providedIn: 'root',
})
...
```

### Desired functionality

New service without `providedIn: 'root'` attribute and included in parent module.

**Comment by hansl** [comment] 2018-08-17 06:15
Hi @am-trinity ,

See discussion in https://github.com/angular/angular-cli/issues/10170 (and many other places). Essentially Services are 99% singletons, and making a special case is actually more confusing for most users. It's a small change for you once the service is generated, so we decided to remove the option.

Please note that we never configured a provider in the past. We always created singleton services. I'm going to close this as working as intended.

Cheers!

**Closed by hansl** 2018-08-17 06:15 UTC
Labels: comp: schematics/angular

**Comment by am-trinity** [comment] 2018-08-17 07:00
I got it, thank you. Declarations like `providedIn` look very non-familiar and non-transparent (for the first time).
