### ISSUE TITLE
on dev mode setting "serviceWorker": true, after rebuild makes a never ending cycle on browser refresh

### ISSUE THREAD

**Issue by fssrepository** [angular/angular-cli#26419] opened 2023-11-19 19:34 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

on dev mode setting "serviceWorker": true, after rebuild makes a never ending cycle on browser refresh

I don't care what is the excuse behind, it shouldn't blow up my machine.

The refresh is so fast that it's behaving like a virus, couldn't catch anything from the console.

ctrl + fn + f5 => hard refresh on browser solves the problem on ng serve (dev), but i don't want that to happen on production at all, if i upgrade, and might forget to change the version package.json or any tricky config!

### Minimal Reproduction

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "myscoutee": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "allowedCommonJsDependencies": ["lodash"],
            "outputPath": "dist/myscoutee",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "assets": ["src/assets", "src/manifest.json", "src/manifest.webmanifest"],
            "styles": [
              "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
              "src/_styles/styles.scss"
            ],
            "scripts": [
              "node_modules/html5-qrcode/dist/html5-qrcode.min.js",
              "node_modules/qrcode/build/qrcode.min.js"
            ],
            "vendorChunk": true,
            "extractLicenses": false,
            "buildOptimizer": false,
            "sourceMap": true,
            "optimization": false,
            "namedChunks": true,
            "serviceWorker": true,
            "ngswConfigPath": "ngsw-config.json"
          },
```

### Your Environment

```text
Angular: 
    "@angular/animations": "^16.2.0",
    "@angular/cdk": "^16.2.0",
    "@angular/common": "^16.2.0",
    "@angular/compiler": "^16.2.0",
    "@angular/core": "^16.2.0",
    "@angular/forms": "^16.2.0",
    "@angular/material": "^16.2.0",
    "@angular/platform-browser": "^16.2.0",
    "@angular/platform-browser-dynamic": "^16.2.0",
    "@angular/router": "^16.2.0",
    "@angular/service-worker": "^16.2.0",

Angular CLI: 16.2.8
Node: 16.20.2
Package Manager: npm 8.19.4
OS: linux x64
```

**Comment by alan-agius4** [comment] 2023-11-19 19:46
Duplicate of https://github.com/angular/angular/issues/47455

**Closed by alan-agius4** 2023-11-19 19:46 UTC
