### ISSUE TITLE
Feature Request: Change default environment target for build/serve.

### ISSUE THREAD

**Issue by HFTSOL** [angular/angular-cli#5256] opened 2017-03-06 21:20 UTC
**Feature Request**

I have been trying to find a way to change the default env target for ng serve/build from dev to anything else (ex:'local'), but I haven't found one.  

Our app environments are:
- Local - Developer computer
- Dev - Target for continuous integration on check-in
- Test - Pre-Prod validation server
- Prod - Production

I would like to be able to specify 'local' as the default environment so, when I run ng serve, it loads the environment file associated with the 'local' environment instead of 'dev'.  To be clear, I don't want to have to use any flags for that.  I would use the --dev, --test-, and --prod flags in our build scripts, or if I'm manually building for a target environment.

Did I miss something in the documentation?

Thanks in advance.

**Comment by sumitarora** [comment] 2017-03-06 21:24
Duplicate of : https://github.com/angular/angular-cli/issues/1923

**Closed by sumitarora** 2017-03-06 21:24 UTC

**Comment by HFTSOL** [comment] 2017-03-06 21:33
There is no solution presented there.  That's why this is a feature request.  Please reopen.

**Comment by delasteve** [comment] 2017-03-06 21:59
@HFTSOL there is no solution yet. Both of the issues are feature requests. That's why @sumitarora closed the issue.

That said, `rc` is feature frozen. The soonest it will happen is post `1.0.0` launch.
