### ISSUE TITLE
ng build

### ISSUE THREAD

**Issue by englishandy** [angular/angular-cli#3496] opened 2016-12-09 14:49 UTC
I installed a clean angular cli "hello world" project, local host works fine, but when i build it doesn't work in production.

Can you explain if i need to change anything out of the box to just get a working prod version that is able run (the prod server is not running nodejs..but i dont need it right?).

i tried ng build and copied the filed over to the server manually as i dont have environments setup.

**Comment by noelmace** [comment] 2016-12-09 15:32
Please reproduce #3495 to see if your issue is a duplicate of it or not.

**Comment by englishandy** [comment] 2016-12-09 15:43
OS?
    Windows 7

Versions.
    angular-cli: 2.1.0
    node: 6.9.1
    os: win32 x64

--
Where do i put the dev mode script?(sorry new to this)

if (isDevMode()) {
  console.log('devmode');
}
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    HttpModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by noelmace** [comment] 2016-12-09 15:49
My bad, I wanted to say "check", not reproduce ... if you didn't use isDevMode and didn't change anything about environment.prod.ts, this is not a duplicate. But we still need some infos ... Please follow the [Submission Guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submit)

**Comment by englishandy** [comment] 2016-12-09 16:06
OS?
Windows 7

Versions.
angular-cli: 2.1.0
node: 6.9.1
os: win32 x64

Repro steps.
Create an app using CLI
start the app in localhost  - ng serve (works fine)
build app - ng build (also tried ng build --prod) - produces the following files in "dist" folder..
favicon.ico
index.html
inline.bundle.js
inline.map
main.bundle.js
main.map
styles.bundle.js
styles.map
nothing else, so when i upload this to live server it display "loading..." only.

**Comment by englishandy** [comment] 2016-12-09 16:29
in the prod environment i see "loading", and error in the console

SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
http://mydomain.com/main.bundle.js
Line 45364

**Comment by noelmace** [comment] 2016-12-09 18:10
I don't think this is an issue with angular-cli. See http://stackoverflow.com/questions/24573061/uncaught-syntaxerror-in-strict-mode-code-functions-can-only-be-declared-at-top and check your code. If you still don't find anything, give use the lines of code around the error.

**Comment by hansl** [comment] 2016-12-09 18:46
Dupe of https://github.com/angular/angular/issues/13301

**Closed by hansl** 2016-12-09 18:46 UTC

**Comment by iTrout** [comment] 2016-12-14 05:53
I know this is after the fact, but I got it to work by putting the contents of the dist folder (excepting the index.html) into the root folder of the production site...it seems that's where angular is looking for them.  Is there a way to build so that the bundles do not have to be placed directly in the root?  This could get quick messy if running multiple angular apps on the same site.
