### ISSUE TITLE
High memory usage on serve

### ISSUE THREAD

**Issue by fknop** [angular/angular-cli#8254] opened 2017-10-30 21:23 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

I noticed a high memory usage using the last version of CLI when running`ng serve`. It starts with a normal amount of memory allocated. And then for every change made to the project files, it seems that the previous memory allocated for the build is not freed and the memory keeps growing until I have to stop the process and start again.

### Versions.
```
Angular CLI: 1.5.0-rc.6
Node: 7.6.0
OS: win32 x64
Angular: 5.0.0-rc.8
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0-rc.6
@angular/flex-layout: 2.0.0-beta.9
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.31
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.6
@schematics/angular: 0.0.48
typescript: 2.5.3
webpack: 3.8.1
```

### Repro steps.
I would need to try on a new generated project if it does the same thing.

### The log given by the failure.

Here is 2.6G of RAM allocated for the `serve` process.

![image](https://user-images.githubusercontent.com/6775689/32196312-808fcedc-bdc0-11e7-9258-246edb4d5f0b.png)

And 5 minutes after

![image](https://user-images.githubusercontent.com/6775689/32196769-0590deea-bdc2-11e7-9980-4326f5aa67d4.png)

**Comment by CaerusKaru** [comment] 2017-10-31 00:22
Duplicate of #5613

**Comment by clydin** [comment] 2017-10-31 14:44
With 1.5 and Angular 5 a new compiler is used so this may not be a dupe.

@fknop Can you try with the latest RC of 1.5?

**Comment by fknop** [comment] 2017-10-31 16:11
@clydin Is rc6 not already the latest rc ?

**Comment by fknop** [comment] 2017-10-31 20:38
@clydin High memory usage is still there but it seems to grow much slower.

**Comment by CaerusKaru** [comment] 2017-10-31 21:27
Also being tracked by #8259, reverting some behavior in next RC/final (keep an eye out for it, PR is #8267)

**Comment by hansl** [comment] 2017-10-31 21:39
I'm going to do another RC today for that PR and the sourcemaps ones.

**Comment by theunreal** [comment] 2017-11-01 12:34
I'm facing the same issue, annoying... latest angular & latest cli

**Comment by ar53n** [comment] 2017-11-02 13:34
Also have this problem and have problem when `ng build` `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

**Comment by shanehsu** [comment] 2017-11-15 08:28
I noticed that it eats a lot of memory even in the release build. Can anyone else reproduce that also?

**Comment by voznik** [comment] 2017-11-18 12:11
https://github.com/angular/angular-cli/issues/5613#issuecomment-345438148

**Comment by filipesilva** [comment] 2017-12-07 15:00
For discussion about the amount of memory used by `ng serve`, please use #5613 instead. For the memory usage in `ng build --prod` please use https://github.com/angular/angular-cli/issues/5618.

**Closed by filipesilva** 2017-12-07 15:00 UTC
Labels: need: investigation, priority: 2 (required), type: discussion
