### ISSUE TITLE
allow publish lib with prod mode

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular-cli#18307] opened 2020-07-20 15:18 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
angular cli stop publishing lib when the lib is built with prod flag

### Describe the solution you'd like

angular cli should support publishing lib when the lib is built with prod flag
`@angular/**` packages should built with prod too
and the ngcc should skip when all the lib is built with prod mode.

### Describe alternatives you've considered

ngcc will make the build process costing more time than the version before angular 9, especially in the continuous integration env

**Comment by alan-agius4** [comment] 2020-07-20 15:44
Duplicate of https://github.com/angular/angular/issues/37973

**Closed by alan-agius4** 2020-07-20 15:44 UTC
