### ISSUE TITLE
New project generated by angular cli not working

### ISSUE THREAD

**Issue by kokosakyi** [angular/angular-cli#7837] opened 2017-09-26 13:23 UTC
polyfills.bundle.js:3951 Uncaught SyntaxError: Invalid or unexpected token

vendor.bundle.js:3650 Uncaught SyntaxError: Unexpected token )

Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bootstrap 71577ea491509d5e258c:54)
    at Object.0 (main.bundle.js:181)
    at __webpack_require__ (bootstrap 71577ea491509d5e258c:54)
    at webpackJsonpCallback (bootstrap 71577ea491509d5e258c:25)
    at main.bundle.js:1

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.3
node: 8.5.0
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/compiler-cli: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/platform-server: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
typescript: 2.3.4

### Repro steps.

1. I run ng new testapp
2. the cd into testapp
3. Then ng serve
4. The browser for localhost:4200 shows blank with the afore-mentioned errors

### The log given by the failure.

polyfills.bundle.js:3951 Uncaught SyntaxError: Invalid or unexpected token

vendor.bundle.js:3650 Uncaught SyntaxError: Unexpected token )

Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bootstrap 71577ea491509d5e258c:54)
    at Object.0 (main.bundle.js:181)
    at __webpack_require__ (bootstrap 71577ea491509d5e258c:54)
    at webpackJsonpCallback (bootstrap 71577ea491509d5e258c:25)
    at main.bundle.js:1

**Comment by filipesilva** [comment] 2017-09-27 10:57
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/6196. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-09-27 10:57 UTC
