### ISSUE TITLE
Error: Class private methods are not enabled when using pdfjs-dist library 

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#24429] opened 2022-12-13 18:52 UTC
### Command

build, serve, test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Angular v15 CLI is not able to build and serve app if pdfjs-dist library is imported

### Minimal Reproduction

- `npx @angular/cli@15 new admin-console`
- `cd admin-console`
- `npm install pdfjs-dist`
- `npm ls pdfjs-dist` -> 3.1.81
- Edit `src/app/app.component.ts` and update the file with this code
```ts
import { Component } from '@angular/core';
import * as pdfjsLib from 'pdfjs-dist';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'admin-console';

  private initialize() {
    console.log(pdfjsLib.version);
  }
}
```
- `npm run build`
<img width="1357" alt="class_private_methods_angular_v15_cli" src="https://user-images.githubusercontent.com/13006107/207419964-f07cb84f-12ce-4f1e-940e-ebc8ac4cc2bd.png">

### Exception or Error

```text
./node_modules/pdfjs-dist/build/pdf.js - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
SyntaxError: /Users/prabh/dev/tmp/admin-console/node_modules/pdfjs-dist/build/pdf.js: Class private methods are not enabled. Please add `@babel/plugin-proposal-private-methods` to your configuration.
  2591 | class PDFObjects {
  2592 |   #objs = Object.create(null);
> 2593 |   #ensureObj(objId) {
```

### Your Environment

```text
Angular CLI: 15.0.3
Node: 18.12.1
Package Manager: npm 8.19.3
OS: darwin arm64

Angular: 15.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.3
@angular-devkit/build-angular   15.0.3
@angular-devkit/core            15.0.3
@angular-devkit/schematics      15.0.3
@schematics/angular             15.0.3
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by alan-agius4** [comment] 2022-12-13 19:38
Duplicate of https://github.com/angular/angular-cli/issues/24426

**Closed by alan-agius4** 2022-12-13 19:38 UTC
