### ISSUE TITLE
--env flag does not work with 'ng test'

### ISSUE THREAD

**Issue by steelheaddigital** [angular/angular-cli#1718] opened 2016-08-17 01:43 UTC
> ## Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
   OSX El Capitan 10.11.6
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:
   angular-cli: 1.0.0-beta.10
   node: 6.3.1
   os: darwin x64
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   a.) Add an environment.test.ts file to the project
   b.) Change a value inside the file.
   c.) run `ng build --env=test`
   d.) look at the environment.js file in dist/
   e.) notice that it has the value from the environment.test.ts file
   f.) run `ng test --env=test`
   g.) look in the dist folder again and notice that the values from the dev environment file are there instead of the test environment file.
4. The log given by the failure. Normally this include a stack trace and some
   more information.
   N/A
5. Mention any other details that might be useful.

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-08-23 02:22
Dupe of https://github.com/angular/angular-cli/issues/1419

**Comment by filipesilva** [comment] 2016-08-23 02:23
It might not seem a dupe at face value, but the underlying issue is the same: that `ng test` is not using the environments.

**Comment by rsheptolut** [comment] 2017-06-28 11:07
@filipesilva This issue wasn't a dupe. --env flag is still not available for 'ng test':
`The option '--env' is not registered with the test command. Run `ng test --help` for a list of supported options.`
I see you made a fix that defaults the environment to 'dev', but there's no way to actually specify any other environment for karma to use (without making a karma.conf.js from scratch, but that's missing the point of angular-cli). Should we reopen this issue or open another one just like it?

**Comment by filipesilva** [comment] 2017-06-28 13:52
Going through this issue again I see that I had misunderstood it. We don't have the `--env` flag for `ng test`, no. It's something we could add.

**Closed** 2017-06-29 13:28 UTC
Labels: command: test, community: help wanted, priority: 3 (nice to have), severity2: inconvenient, type: feature
