### ISSUE TITLE
angular cli 13 keeps recompiling... 

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#22427] opened 2021-12-25 08:39 UTC
Angular just keeps recompiling in infinite loop running the command:

```
node --max_old_space_size=16834 ./node_modules/@angular/cli/bin/ng serve --configuration=dev --proxy-config proxy.json
```

this is proxy.json

```
{
  "/api": {
    "target": "https://earth.xxxxe.me:8080",
    "secure": false,
    "pathRewrite": {
      "^/api": ""
    },
    "changeOrigin": true
  }
}

```

```
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@angular/flex-layout            13.0.0-beta.36
@angular/google-maps            9.2.4
@angular/pwa                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4

```

![image](https://user-images.githubusercontent.com/5090936/147381117-20f5ee43-f31f-458a-a445-f77463fc867b.png)

at first all is well, but after 10 minutes of development, things go nutz,
let me know what other info I can provide, anyone else seeing this?

regards

Sean.

**Comment by born2net** [comment] 2022-01-03 06:27
any news on this? anyone else is seeing?

**Comment by alan-agius4** [comment] 2022-01-10 09:02
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2022-01-17 10:34
Closing since no reproduction was provided. 

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem. 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Closed by alan-agius4** 2022-01-17 10:34 UTC
Labels: need: repro steps
