### ISSUE TITLE
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):

### ISSUE THREAD

**Issue by mayankdargan03** [angular/angular-cli#25144] opened 2023-05-05 08:27 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli, Don't known / other

### Is this a regression?

Yes

### Description

After running the local build, I am receiving the following error:
Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Transform failed with 1 error:
location of scss file. 
ERROR: Unterminated string token

The line mentioned for the scss file contains 
`height: calc(100vh - 132px);`

### Please provide the exception or error you saw

```true
After running the local build, I am receiving the following error:
Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Transform failed with 1 error:
location of scss file. 
ERROR: Unterminated string token

The line mentioned for the scss file contains 
`height: calc(100vh - 132px);`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
npm ls @ngtools/webpack


@angular-devkit/build-angular@14.2.11
  └── @ngtools/webpack@14.2.11 
```

ng version

```
Angular CLI: 14.2.11
Node: 14.16.1
Package Manager: npm 6.14.12 
OS: darwin x64

Angular: 14.3.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.11
@angular-devkit/build-angular   14.2.11
@angular-devkit/core            14.2.11
@angular-devkit/schematics      14.2.11
@angular/cdk                    13.3.9
@angular/cli                    14.2.11
@schematics/angular             14.2.11
rxjs                            6.6.7
typescript                      4.6.4


```
node -v
`14.15.0`
```


### Anything else?

_No response_

**Comment by alan-agius4** [comment] 2023-05-05 09:31
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by rogerg93** [comment] 2023-05-05 09:32
> This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?
> 
> A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

Please check my comment above. No code is needed to reproduce the issue. Just:

Run `ng new project-name --standalone`
Run `ng serve`

**Comment by mayankdargan03** [comment] 2023-05-05 09:43
@alan-agius4 - It will take make me some time to create one. As the code is production level code security concerns are there.

@rogerg93 - Is --standalone an option? When I tried it threw me an error.
`Error: Unknown argument: standalone`

**Comment by JeanMeche** [comment] 2023-05-05 09:45
@rogerg93 I could not reproduce your issue with a new project created with the v16 CLI + Scss files. 

Could you provide your sample project on a repo / a stackblitz ? thx !

**Comment by JeanMeche** [comment] 2023-05-05 09:45
> @rogerg93 - Is --standalone an option? When I tried it threw me an error. `Error: Unknown argument: standalone`

It's not available on v14.

**Comment by alan-agius4** [comment] 2023-05-16 09:20
Closing due to lack of a reproduction.

**Closed by alan-agius4** 2023-05-16 09:20 UTC
Labels: needs: repro steps
