### ISSUE TITLE
--deploy-url will have no effect on assets paths

### ISSUE THREAD

**Issue by DaveXCS** [angular/angular-cli#4517] opened 2017-02-08 10:01 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
`@angular/cli: 1.0.0-beta.30
node: 7.5.0
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6
`

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
- create app with the cli
- use `img src="assets/logo.png"` in a template
- ng build -d mysubfolder -bh mysubfolder
copy the content of the dist to "htdocs/mysubfolder" on any webserver or use 
`app.use('/mysubfolder', express.static(path.join(__dirname, angularDist)));` on a node server.
### The log given by the failure.
> Normally this include a stack trace and some more information.

404 on all assets because it will ignore base href or deploy url and just use GET /assets/logo.png

**Comment by merwok** [comment] 2017-02-08 22:26
I am deploying an app written by someone else.  Assets use hard-coded paths like /assets/img/etc (note the leading slash compared to the OP), the main files (*.bundle.js and sourcemaps) end up in the root of the dist directory.  This is okay for frontend development (using ng serve, /index.html can load /index.bundle.js and /assets/img/etc), but for the actual deployment I would ideally have everything under URLs looking like /static/app/ and /static/assets/ for example.

Note that I’m not familiar with webpack, so the one-line documentation for ng build options don’t let me have a clear picture of what they are supposed to do.  For now I’m experimenting with deploy-url (base-href gave undesirable changes in the browser address bar, and I have other ways to post-process the index.html file) to make sure the main js files have correct references, and I’ll live with the /assets/ URLs.

**Comment by es-lab** [comment] 2017-02-21 17:58
I had this problem too. All my resources are served on a subdomain. Using the deployUrl option solved the issue for the scripts/styles being loaded from the subdomain inside the index.html. This guaranteed me to not worry about base href so that my routing will work properly, it remains as default `/`. Regarding other resources like images, try loading them from your styles using the background-image property. As the styles loads from the subdomain, it loads the necessary resources from the subdomain too, including fonts, etc.
Now I have an issue with the favicon as it is an asset, the compiler does not put the deployUrl in the href attribute and I have to put it manually.

**Comment by victormejia** [comment] 2017-03-03 20:07
Facing the same issue here, I've got some CSS like this:

```css
label.custom-radio-default-label {
  margin: 0;
  clear: none;
  cursor: pointer;
  background: url(/assets/images/custom-radio-normal.svg) left center no-repeat;
  background-size: 20px;
  font-size: 16px;
  font-weight: normal;
}
```

and building with `ng build --deploy-url https://test.com` doesn't seem to have any effect on the output.

**Comment by filipesilva** [comment] 2017-03-09 12:13
Largely fixed by https://github.com/angular/angular-cli/pull/4803.

The `ng build --deploy-url https://test.com` (with `http`) scenario isn't catered for currently though.

**Comment by es-lab** [comment] 2017-03-09 14:38
@filipesilva #5254 Here is a related issue that I've posted 3 days ago. Hope you will fix this soon.

**Comment by merwok** [comment] 2017-03-09 17:00
@filipesilva Does #4803 rewrite paths for assets that are images or javascript files, or only CSS files?

**Comment by filipesilva** [comment] 2017-03-10 13:47
@es-lab thank you, I will track the `http` bug in your issue instead. I'm closing this one then.

@merwok it rewrite paths only for assets in `url()` inside CSS. Those are the only ones that need path rewriting afaik.

**Closed by filipesilva** 2017-03-10 13:47 UTC
Labels: command: build, priority: 1 (urgent), type: bug

**Comment by merwok** [comment] 2017-03-10 16:53
The example in the original message is an image.  The source code contains `img src="assets/logo.png"` (in my case, `src="/assets/logo.png"`) but the app files end up served from ``/static/assets/``.

**Comment by filipesilva** [comment] 2017-03-11 22:34
@merwok if you have `url('/assets/logo.png')` in your CSS, and use `--deploy-url=static/`, the CLI should build that path to `url('/static/assets/logo.png')`. Mind you that images under a certain size are just inlined.

Make sure you're using the latest RC though.

**Comment by merwok** [comment] 2017-03-12 00:13
Thank you for the reply!  I depend on webpack indirectly via angular-cli, so I’ll check the new behaviour when we’ll be able to upgrade.

**Comment by milankr** [comment] 2017-03-13 20:49
@filipesilva It affects urls stated in CSS files, but it doesn't those which are directly stated in markup like `<img src="assets/logo.png">`. So if I build using --deploy-url=static/ it won't be `<img src="/static/assets/logo.png">`

**Comment by filipesilva** [comment] 2017-03-13 21:40
@milankr we do not process HTML, so that is expected behaviour.

**Comment by merwok** [comment] 2017-03-14 03:02
Ah!  If only index.html is changed and not the other HTML files, I’ll have to keep my sed workaround.

Next project, we’ll get the paths right from day one!

**Comment by tomasklingen** [comment] 2017-04-13 13:23
@filipesilva can you tell me what the reasoning was to only process asset urls in css, and not in the html templates?

**Comment by macrivello** [comment] 2017-04-21 06:15
@filipesilva What is the strategy using <img> src paths with a project using --deploy-url? @merwok comment points out this issue:

"The example in the original message is an image. The source code contains img src="assets/logo.png" (in my case, src="/assets/logo.png") but the files will be served from /static/assets/."

The requests for the image source will 404.

**Comment by bergben** [comment] 2017-06-10 19:12
Is there any workaround to make this work for `<img src="[...]" />`?

**Comment by yordis** [comment] 2017-06-13 16:01
@bergben the only workaround that now reading the thread is to use Javascript binding so you configure the base path in your environment config files 👎

**Comment by yordis** [comment] 2017-06-13 16:02
@filipesilva any updates on this? I need HTML processing as well

**Comment by merwok** [comment] 2017-06-13 17:08
FWIW, I lived with renaming `assets` to `static/assets` and doing a mass search-and-replace.  Source paths now match deployed paths.

**Comment by naveedahmed1** [comment] 2017-09-01 16:39
I need to put Index.html in root directory i.e. /dist folder and all script files in dist/scripts directory, can anyone please guide how do I achieve this? So that when I deploy it on server my index file resides in root of my domain (mydomain/index.html) and all scripts in scripts directory (e.g. mydomain/scripts/****.js)

**Comment by filipesilva** [comment] 2017-09-04 14:01
@tomasklingen it was attempted a couple of times but at the time we couldn't find a safe approach for it, especially since you can compose urls in html using component variables. So any change there was very likely to break some projects, which is a breaking change and thus outside of 1.x.

**Comment by MaximeMorin** [comment] 2017-09-08 15:43
@filipesilva Can we get some sort of reserved string/variable/token that you can search in HTML and TS to replace all occurences?

**Comment by Nodarii** [comment] 2017-09-20 14:39
@filipesilva , 

For those of us who are not in production yet. Should we think about some workaround or we can expect some fix in next releases(even not in 1.x)?

**Comment by ajit-jain** [comment] 2017-09-29 08:19
@filipesilva i m deploying my app through 

>ng build --env=prod --prod --aot --build-optimizer --deploy-url //-distribution-.cloudfront.net/ --output-hashing none --nosourcemap

after build in dist/index.html
<script type="text/javascript" src="//-distribution-.cloudfront.net/polyfills.bundle.js"></script>**<script type="text/javascript" src="/-distribution-.cloudfront.net/scripts.bundle.js"></script>**<script type="text/javascript" src="//-distribution-.cloudfront.net/main.bundle.js"></script>

it only produces single '/' for scripts.bundle.js why???

**Comment by pagimaxx** [comment] 2017-10-07 18:36
When you deploy extract <base "/"> of the index.html, just this!

**Comment by merwok** [comment] 2017-10-09 15:02
I think there are two workarounds: either move your source files and do a mass search and replace so that the source paths match the deployed paths (what I mentioned in a previous comment), or use the [ng eject command](https://github.com/angular/angular-cli/wiki/eject) to get access to the raw webpack config and get out of ng cli.

**Comment by zsmorgan21** [comment] 2017-10-11 15:23
I have a work around in the mean time.

I put the deploy path in my environment.ts files.

Then in the components that I want to refer to files in the assets folder, I set href to "{{deploypath}}/assets/...". You will have to create a deploypath component variable and assign the environment.deployPath in the constructor of the component.

**Comment by MaximeMorin** [comment] 2017-10-11 15:41
@zsmorgan21 We do the same thing.  When we deploy, we have a script that updates our package version and replace the value in our environment file.  Itworks so far.

**Comment by zappan** [comment] 2018-01-23 19:39
I'll reference this StackOverflow post https://stackoverflow.com/questions/47885451

As I've ran into the same issue, `deployUrl` manages the path in the `index.html`, but not across the application's `assets/` files. The workaround is to have a CI/CD post-build script which pretty much does in-place replace in build files using `sed`.

The proper CDN support for any client-side apps framework is quite important; I'm not deep into Angular/CLI to know all the ins and outs to propose a solution, but it is something we're definitely running into when planning CDN deployments.

**Comment by clydin** [comment] 2018-01-23 19:55
Generally, setting the `base-href` is a cleaner option.  It not only handles initial scripts, but also lazy scripts, processed resources, and most importantly the application's assets.  The use of Angular's `APP_BASE_HREF` ([documentation](https://angular.io/api/common/APP_BASE_HREF)) in combination can provide a full solution for CDN use cases.

**Comment by sir-captainmorgan21** [comment] 2018-01-23 20:06
@clydin,

`base-ref` alone wont solve the issue with assets. However, I do think setting and referencing Angular's APP_BASE_HREF is the better option than using angular CLI's environment variables. You can set it like @clydin mentioned above. You can reference it like so...

https://stackoverflow.com/questions/39287444/angular2-how-to-get-app-base-href-programatically

**Comment by clydin** [comment] 2018-01-23 20:19
Could you elaborate on why using the `--base-href` option will not solve the asset issue?

All relative fetches made by the browser will be prefixed by the provided base href.  This would include all relative asset URLs within the application.  This is also why it is generally a cleaner solution as opposed to the `--deploy-url` option which requires the supplied URL to be embedded throughout the application to function.  The `APP_BASE_HREF` token (which is used as the Angular router base path) would generally be set `/` in this scenario; as the default value is actually the base href of `index.html`.

**Comment by sir-captainmorgan21** [comment] 2018-01-23 20:23
When you refer to `base-href`, are you referring to the command line
parameter or the base tag and href attribute? I think there is some
confusion there. Your initial post was missing the "--" from `base-href`.

Zachary S. Morgan
Hampden-Sydney College
Class of '14

**Comment by zappan** [comment] 2018-01-23 21:08
Reading all this, and it still doesn't explain how to have assets mapped to a CDN, even with using this `APP_BASE_HREF`

This is the build command, which maps `base-href` to `/subpath/` and `deployUrl` to CDN:

    ng build --prod --aot --base-href "/subpath/" --deployUrl="//cdn.example.com/subpath/"

So, the app is served off of a webserver host's subpath (so, Angular routing must work with this subpath, as the [link I shared explains](https://stackoverflow.com/questions/47885451)), but angular files are stored on the CDN. With the above build command, built JS/CSS files are referenced from CDN in the `index.html`, but then, inside the app, all the assets should be referenced from the CDN as well. 

What is needed is the way to `--deployUrl` be applied to all the `/assets/` during the build. With this `APP_BASE_URL` they'd be referenced with the value of the `--base-href` parameter, if I understand it correctly (correct me if I'm wrong; but that was the conclusion in the comments of the [StackOverflow question](https://stackoverflow.com/questions/47885451) - not supported).

Thank you

**Comment by clydin** [comment] 2018-01-23 23:17
The purpose of the `--base-href` option is to set the value of the `base` element's `href` attribute within `index.html`.  So either would be relevant to the discussion.

@zappan Something similar to the following command:
```
ng build --prod --base-href="//cdn.example.com/subpath/"
```
with `APP_BASE_HREF` set to `/subpath/` in the entry module should work.  Relative URL usage within the app is critical as the browser will only apply the HTML base href to relative URLs.
As an aside, `--aot` is enabled by default with `--prod`.

**Comment by rajjaiswalsaumya** [comment] 2018-04-14 01:26
Can some one throw light on this, how to achieve context path other than / for my application. I had been reading whole night for this issue but could not find a way

**Comment by ga-kumar** [comment] 2018-09-10 04:06
@zappan did it ever work for you? I tried without any luck and am stuck with it. Could you please assist?

**Comment by ga-kumar** [comment] 2018-09-11 17:55
thanks @zappan , I also ended up doing same.. Clydin's suggestion didn't work for me either or not sure if I understood correctly.. anyway.. thanks again..

**Comment by albanx** [comment] 2018-11-04 20:08
Having the same issue.
My first attempt was to use the --base-href but this will affect also the angular router so it is not a solution.

For now I am going to place a deployUrl to every src of html images.

**Comment by clydin** [comment] 2018-11-05 19:32
@albanx Use `--base-href` for the applications assets and the [`APP_BASE_HREF`](https://angular.io/api/common/APP_BASE_HREF) token to control the Angular router.

**Comment by brantxiong** [comment] 2018-12-12 14:12
Hi, @clydin I have encountered the similar problem, Please help.
angular-cli version:
```bash
Angular CLI: 6.2.5
Node: 8.12.0
OS: darwin x64
```
#### My deploy situation:
My site have to be deployed on server A because of domain, so I put index.html ( generated file in 
the dist folder) on server A. And I want to deploy all the static files on another CDN server B, and I put all the dist folder on Server B as a folder named like 111. I tried build my site with following ways:

#### way 1:  Failed with some assets link in html did not converted to CDN path, so assets link in html breaks
```bash
ng build --prod --base-href /111/ --deploy-url https://B.com/111/  
```
#### way 2: all the Angular router and http api both breaks, since all api and router are added with the base-href
```bash 
ng build --prod --base-href https://B.com/111/
```

I have already set the `APP_BASE_HREF` token in `src/app/app.module.ts`:

```ts
@NgModule({
 ...
  bootstrap: [AppComponent],
  providers: [
    {provide: APP_BASE_HREF, useValue: '/'}
  ]
})
```

Please help and let me know if you want more information. Thanks!

**Comment by rijine** [comment] 2019-03-19 16:34
Assets in ts file is has no impact on deployUrl. I was trying dynamic configuration https://christianlydemann.com/implementing-dynamic-environments-in-angular-for-avoiding-one-build-per-environment/

```
public init() {
    return from(
        fetch('assets/app-config.json').then(function(response) {
          return response.json();
        })
      ).pipe(
        map((config) => {
        window.config = config;
        return 
      })).toPromise();
  }
```

![image](https://user-images.githubusercontent.com/1145401/54624138-183c3380-4a6d-11e9-81f8-44ed2dd9f231.png)

Can anyone help me how baseUrl can be used to update references ts file?

**Comment by pravesh364** [comment] 2019-03-26 06:53
Still we don't have any solution for the same issue. Don't know why this ticket is closed.

I am building my application on cnd server and serving my index.html file from other domain which is my public domain.

The build command for same is like `ng build --prod --aot --output-hashing none --deploy-url=https://ng.xyzcdn.in/`. If I am running my application on `https://ng.xyzcdn.in/`, static content are are coming from same cdn domain are fine. But when I am using my main/public domain to serve application, the static content path is relative to my main/public domain.

My requirement will be fixed only when static content would served via deploy url.

Note: All the chucks file are serving correctly via deploy url path on main/public domain. Only facing issue with static contents which are deployed inside "svg" and "assets" folders.

Application is not working fine when I am trying to hard code cdn path of "assets" in `angular.json` file.
