### ISSUE TITLE
Feature request: Support service worker in development mode

### ISSUE THREAD

**Issue by ronzeidman** [angular/angular-cli#10483] opened 2018-04-27 13:26 UTC
I have a pretty complex logic in creating push notifications with multiple users + multiple sub apps + fallback logic and debugging production mode is hard. If support service workers under development mode was under a flag I'd have a much easier time debugging.
Thanks!

**Comment by oberoivarun** [comment] 2018-08-02 09:12
Could the angular team just allow service workers in `ng serve --prod` ??

**Comment by dgp1130** [comment] 2020-06-26 15:56
Duplicate of #16883

**Closed by dgp1130** 2020-06-26 15:56 UTC
Labels: comp: angular/pwa, need: further discussion, triage #1, type: feature
