### ISSUE TITLE
Support for Windows line endings

### ISSUE THREAD

**Issue by kremerd** [angular/angular-cli#6487] opened 2017-05-27 15:15 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

```
$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.6
node: 6.10.2
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.6
@angular/compiler-cli: 4.1.3
```
Running on Windows 10.

### Repro steps.

```
$ ng new demo
$ cd demo
$ ng generate component DemoComponent
$ git add .
warning: LF will be replaced by CRLF in src/app/app.module.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/demo-component/demo-component.component.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/demo-component/demo-component.component.spec.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/demo-component/demo-component.component.ts.
The file will have its original line endings in your working directory.
```

### The log given by the failure.

None.

### Desired functionality.

I'd like a setting to make `ng generate` create files with Windows line endings (CRLF) instead of the currently used Unix line endings (LF). This would increase users flexibility on Windows environments, where it's still common to use Windows line endings as a default.

The setting *could* look like `ng set --global end_of_line=crlf`.

### Mention any other details that might be useful.

None.

**Comment by clydin** [comment] 2017-05-28 00:39
You can use this tslint rule (https://palantir.github.io/tslint/rules/linebreak-style/) and either use `ng lint --fix`; or in the upcoming version 1.1, use the `--lint-fix` option on the `generate` command or add it as a default in `.angular-cli.json`.

**Comment by kremerd** [comment] 2017-05-28 18:06
Thanks for the hint! Using the linter is a great help already. Version 1.1 (or at least [tslint 5.0.0](https://github.com/palantir/tslint/blob/5.0.0/src/rules/linebreakStyleRule.ts)) is required in any case, because the rule is not auto-fixable in older versions.

Handling linebreaks separately might still be advantegeous, though. For one `tslint` only updates TypeScript files, leaving other files like html templates untouched. More importantly, if the repository is shared between different environments, it might not be an option to hard-code the preferred linebreak style in a shared config like `tslint.json`.

Aside from introducing a new setting, I could also imagine to rely on the NodeJS environment variable `os.EOL`. From what I've seen it's already used to format console output, but so far not to copy blueprints.

**Comment by hansl** [comment] 2017-05-30 22:19
The Schematics (custom templates) project hopes to help fix this issue by having special rules to make changing files depending on external factors (like platform) easier. I'm going to close this as working as intended for now.

**Closed by hansl** 2017-05-30 22:19 UTC
Labels: type: feature

**Comment by kremerd** [comment] 2017-05-31 07:04
Sure. Is there a page for the Schematics project or some other resource where one can get updates about these special rules?

**Comment by sdurnov** [comment] 2018-10-18 13:57
@hansl please reopen this again, as this is still an issue.
