### ISSUE TITLE
AOT does not catch errors in an *ngIf 

### ISSUE THREAD

**Issue by cenkentimist** [angular/angular-cli#5764] opened 2017-03-30 15:15 UTC
note: the title and content of this post have been changed since its creation. Originally I found this issue at the same time as two others and did not realize they where separate. most of the content has been moved out of this post.
The other two issues for the curious are
[needing to save twice in a row to compile against the new version](https://github.com/angular/angular-cli/issues/4252#issuecomment-290591224)
[zone js can silence some errors](https://github.com/angular/zone.js/issues/706)
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.5.0
os: darwin x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.
ng new mincase
cd mincase
npm start -- --aot

at this point I opened it up in chrome

opened up app.componenet.html in atom and changed text to
```
<h1 *ngIf="'x'">
  x {{title2.foo}}
</h1>
```

save twice to get around a bug (once wont update it)
this compiled without error chrome shows x and errors to the console

next I changed the text in app.componenet.html to 
```
{{title2.foo}}
<h1 *ngIf="'x'">
  x {{title2.foo}}
</h1>
```
save twice to get around a bug. (once wont update it)
compile fails and chrome switches to showing an error screen

### Desired functionality.
If would be cool if the aot was able to identify the error ahead of time inside the *ngIf

**Comment by leocaseiro** [comment] 2017-04-03 05:11
I confirm this issue, but I believe it's not related to `*ngIf`.

In my case, any time I run with `--aot` enabled, the `.html` only updates on second save. However, if you make changes on a `.ts` file, the changes are updated in the same time.

I wrote about it here: https://github.com/angular/angular-cli/issues/4252#issuecomment-290591224

**Comment by cenkentimist** [comment] 2017-04-03 11:02
Probably. I need to update this when I get to a proper computer (this is
from my phone) the silenced errors came from zonejs. The 2nd save issue is
likely as you state. I think the *ngIf is preventing aot from catching the
issue but that might not be fixable/right

**Comment by mgechev** [comment] 2019-08-19 20:17
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:17 UTC
Labels: effort2: medium (days), freq1: low, priority: 2 (required), severity2: inconvenient
