### ISSUE TITLE
error while running build (npm start/ng test)  - JavaScript heap out of memory exception (intermittent )

### ISSUE THREAD

**Issue by amitagt007** [angular/angular-cli#20822] opened 2021-05-17 14:15 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [x ] serve
- [ x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 updated from angular 10 to 12 version. after that while running ng serve . ng test getting below error-

 'FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory'

## 🔬 Minimal Reproduction

run npm start / ng test, getting the exception and build not successful.  modified node config, still intermittently its coming

package config -
"scripts": {
    "ng": "ng",
    "start": "node --max_old_space_size=3000000 ./node_modules/@angular/cli/bin/ng serve --host 0.0.0.0  --disable-host-check",
    "build": "node --max_old_space_size=3000000 ./node_modules/@angular/cli/bin/ng build",
    "test": "node --max_old_space_size=3000000 ./node_modules/@angular/cli/bin/ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "prettier-check": "npx prettier --check ."
  },

## 🔥 Exception or Error

<pre><code>
⠋ Generating browser application bundles (phase: sealing)...
<--- Last few GCs --->

[39208:0081C0A0]   200939 ms: Scavenge (reduce) 1004.7 (1021.9) -> 1003.9 (1022.9) MB, 2.9 / 0.0 ms  (average mu = 0.256, current mu = 0.179) allocation failure 
[39208:0081C0A0]   200979 ms: Scavenge (reduce) 1006.3 (1026.4) -> 1005.6 (1026.4) MB, 18.9 / 0.0 ms  (average mu = 0.256, current mu = 0.179) allocation failure 
[39208:0081C0A0]   201011 ms: Scavenge (reduce) 1008.1 (1025.1) -> 1007.5 (1026.1) MB, 9.5 / 0.0 ms  (average mu = 0.256, current mu = 0.179) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 01268689 v8::internal::Heap::PageFlagsAreConsistent+2169
 2: 0125E701 v8::internal::Heap::CollectGarbage+1985
 3: 0125CDB3 v8::internal::Heap::AllocateExternalBackingStore+1171

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular - 12.0.0
Node -  v14.17.0
npm - 7.13.0

</code></pre>
![image](https://user-images.githubusercontent.com/23057846/118503541-56fece80-b748-11eb-8625-a665f19de9c3.png)

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2021-05-17 14:25
Duplicate of https://github.com/angular/angular-cli/issues/20801

**Closed by alan-agius4** 2021-05-17 14:25 UTC
