### ISSUE TITLE
Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=3.1.1 <3.3", would install "3.4.5").

### ISSUE THREAD

**Issue by jtsom** [angular/angular-cli#14561] opened 2019-05-29 12:02 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Yes

 Yes, the previous version in which this bug was not present was: ....

### Description

Having this issue trying to do an ng update on a pretty stock angular 7 application to angular 8:

```
ng update @angular/cli
Your global Angular CLI version (8.0.0) is greater than your local
version (7.3.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=3.1.1 <3.3", would install "3.4.5").
Incompatible peer dependencies found. See above.
```

package.json:
```
{
  "name": "sample-player",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "videogular2": "^6.4.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.8",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}

```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Comment by jtsom** [comment] 2019-05-29 12:17
Also, do we have to do a git commit after every update operation??

```
ng update @angular/core
Repository is not clean.  Please commit or stash any changes before updating.
```

**Comment by alan-agius4** [comment] 2019-05-29 12:30
Also related to https://github.com/angular/angular-cli/issues/13095

**Comment by jtsom** [comment] 2019-05-29 12:32
I did see #13095 but wanted to specifically target the new 8.0 (where it says it supports Typescript 3.4 - except where it doesn't....)

**Comment by jtsom** [comment] 2019-05-29 12:52
I was able to get the update to run using the --force flag, but it looks like the operations that are run after the update (updating tsconfig.json, tslint.json, etc) were not run. How do I re-run those schematics to get everything up to date?

**Comment by alan-agius4** [comment] 2019-05-29 13:01
You can run `ng update @angular/cli--from 7 --to 8 --migrate-only`

**Comment by jtsom** [comment] 2019-05-29 13:44
Except:
```
ng update @angular/cli --from 7 --to 8 --migrate-only
Using package manager: 'npm'
Collecting installed dependencies...
Found 32 dependencies.
Invalid Version: 7
```

**Comment by alan-agius4** [comment] 2019-05-29 15:30
@jtsom, yeah there is another issue with command, kindly see https://github.com/angular/angular-cli/issues/14559#issuecomment-496933988

**Comment by mswilson4040** [comment] 2019-05-29 21:39
Ran into this as well. The only way I could get angular to upgrade 8 (from 7) was to use `npm install @angular/cli@8.0.0 --save-dev` (opposed to `ng update @angular/cli`

once I did this, I ran into the issue @jtsom called out:

> Repository is not clean.  Please commit or stash any changes before updating.

Once I committed the changes and ran `ng update --all`, I get more warnings of the similar type.

**Comment by tc9011** [comment] 2019-05-30 03:27
@mswilson4040 same problem, Finally I use npm to update angular, like this:

```bash
npm install @angular/cli@latest @angular-devkit/build-angular@latest  --save-dev

npm install @angular/{common,compiler,compiler-cli,core,forms,platform-browser,platform-browser-dynamic,platform-server,router,animations}@latest typescript@3.4 --save
``` 

After update, you should manually add parameter to `ViewChild` or `ContentChild`

**Comment by alan-agius4** [comment] 2019-05-30 05:45
Hi, are you running `ng update @angular/cli @angular/core`?

**Comment by tc9011** [comment] 2019-05-30 05:53
@alan-agius4 yes, I run `ng update @angular/cli` at first, and it worked well, but after I run `ng update @angular/core` , it said `Repository is not clean.  Please commit or stash any changes before updating`
![image](https://user-images.githubusercontent.com/18380140/58611574-2ebf0080-82e2-11e9-8737-19c590fa6e2b.png)

**Comment by kswarthout** [comment] 2019-05-30 08:55
I encountered the same issues. The warning is related to your git repo. Committing my recent changes fixed the problem, and I was able to run the ng update commands (i.e. ng update @angular/cli @angular/core)

**Comment by TomySmit** [comment] 2019-05-30 12:31
run this command `git status --porcelain` and add files and directories to ignore file or commit

**Comment by mswilson4040** [comment] 2019-05-30 15:34
IMO I think it's a horrible development experience to have to commit the updated change for each individual update. I have yet to see `ng update --all` actually work and always have to update cli, then core, then whatever, then material/cdk. It'd be nice if this was more streamlined.

**Comment by RogierdeRuijter** [comment] 2019-05-30 16:17
> run this command `git status --porcelain` and add files and directories to ignore file or commit

Fixing my git ignore worked for me.

**Comment by huyinghuan** [comment] 2019-05-31 02:24
```
npm install -g @angluar/cli
ng update --all --force
ng add @angular/http 
```

it work fine for `ng server` and `ng build`

**Comment by damingerdai** [comment] 2019-05-31 02:34
i also meet this error. 
first,i run 
```
ng update @angular/core
```
and them
```
ng update @angular/cil
```
i don't run
```
ng update rxjs
```
now i have upgraded to angular8 and every thing sees ok.
i hope it is helpful

**Comment by KylerJohnson26** [comment] 2019-05-31 17:33
I had the same errors. Here's what worked for me:
`ng update --all --force`

**Comment by tc9011** [comment] 2019-06-01 03:19
> run this command `git status --porcelain` and add files and directories to ignore file or commit

Before you use `ng update`, you should commit or stash all files

**Comment by Laurens-makel** [comment] 2019-06-01 09:54
> i also meet this error.
> first,i run
> 
> ```
> ng update @angular/core
> ```
> 
> and them
> 
> ```
> ng update @angular/cil
> ```
> 
> i don't run
> 
> ```
> ng update rxjs
> ```
> 
> now i have upgraded to angular8 and every thing sees ok.
> i hope it is helpful

Thanks, seems to be working!
Btw, you made a little spelling mistake in your `ng update @angular/cil` command, it should be `ng update @angular/cli`

**Comment by matheo** [comment] 2019-06-01 20:30
On a side note, I had to run `ng update @angular/material --from 7 --to 8 --migrate-only` many times because it was throwing `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` after editing my import paths on tons of components.

Thanks for the great work tho!

**Comment by damingerdai** [comment] 2019-06-02 13:48
> > i also meet this error.
> > first,i run
> > ```
> > ng update @angular/core
> > ```
> > 
> > 
> > and them
> > ```
> > ng update @angular/cil
> > ```
> > 
> > 
> > i don't run
> > ```
> > ng update rxjs
> > ```
> > 
> > 
> > now i have upgraded to angular8 and every thing sees ok.
> > i hope it is helpful
> 
> Thanks, seems to be working!
> Btw, you made a little spelling mistake in your `ng update @angular/cil` command, it should be `ng update @angular/cli`

Thanks

**Comment by jtsom** [comment] 2019-06-02 15:17
Just tried to update another project and got:
```
ng update @angular/cli @angular/core @angular/cdk @angular/material
Your global Angular CLI version (8.0.1) is greater than your local
version (7.1.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
                  Package "@ncstate/sat-popover" has an incompatible peer dependency to "@angular/cdk" (requires "^7.0.0", would install "8.0.0").
Incompatible peer dependencies found. See above.
```

getting worse...

**Comment by fr0** [comment] 2019-06-04 19:06
What's the solution for this? Running `ng update -all` gives a bunch of errors.

```
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires ">=3.1 < 3.5", would install "3.5.1")
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=3.4 <3.5", would install "3.5.1")
                  Package "ng-packagr" has an incompatible peer dependency to "typescript" (requires ">=2.7 < 3.5", would install "3.5.1")
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires ">=3.1 < 3.5", would install "3.5.1").
Incompatible peer dependencies found. See above.
```

**Comment by mswilson4040** [comment] 2019-06-04 19:46
I've never actually seen `ng update --all` work. I was able to get things working by doing `ng update @angular/core @angular/cli`

**Comment by fr0** [comment] 2019-06-04 19:49
If `ng update --all` doesn't work, then it should be removed.

Or at the very least, this message should be changed:

```
 We analyzed your package.json, there are some packages to update:
    
      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       7.3.9 -> 8.0.1           ng update @angular/cli
      @angular/core                      7.2.15 -> 8.0.0          ng update @angular/core
    
    
    There might be additional packages that are outdated.
    Run "ng update --all" to try to update all at the same time.

```

**Comment by mswilson4040** [comment] 2019-06-04 19:52
Yea, it's immediately suspicious when it reads `Run "ng update --all" to _try_ to update all at the same time.

**Comment by Invertisment** [comment] 2019-06-06 10:23
This issue also appears on my update from 6.0.8 to 7 (using this guide: https://update.angular.io/#6.0:7.0)
I'm not even trying to target anything over version 7. I only wanted to be able to run version 7 at all.
This is an almost unchanged application from angular example but it still doesn't work.

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
```
$ ng update @angular/cli @angular/core
Your global Angular CLI version (8.0.1) is greater than your local
version (6.0.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
                  Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires ">=7.0.0-rc.0 <8.0.0||>=2.3.1 <7.0.0||>6.0.0-beta <7.0.0", would install "8.0.0").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/common" (requires ">=7.0.0-rc.0 <8.0.0||>=2.3.1 <7.0.0||>6.0.0-beta <7.0.0", would install "8.0.0").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/core" (requires ">=7.0.0-rc.0 <8.0.0||>=2.3.1 <7.0.0||>6.0.0-beta <7.0.0", would install "8.0.0").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires ">=7.0.0-rc.0 <8.0.0||>=2.3.1 <7.0.0||>6.0.0-beta <7.0.0", would install "8.0.0").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/platform-browser" (requires ">=7.0.0-rc.0 <8.0.0||>=2.3.1 <7.0.0||>6.0.0-beta <7.0.0", would install "8.0.0").
Incompatible peer dependencies found. See above.
```

`package.json`
```
{
  "name": "angular-tour-of-heroes",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.6",
    "@angular/cdk": "^6.2.1",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/flex-layout": "^6.0.0-beta.15",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.2.1",
    "@angular/material-moment-adapter": "^6.3.1",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "core-js": "^2.5.4",
    "material-design-icons": "^3.0.1",
    "moment": "^2.22.2",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.3",
    "@angular-devkit/build-angular": "~0.6.8",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.8",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }
}```

**Comment by astronaute77** [comment] 2019-06-09 15:08
Also having the same issue when running `ng update --all`:

`Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=3.4 <3.5", would install "3.5.1").`

**Comment by Random90** [comment] 2019-06-10 19:00
Same here, `ng update --all` throws typescript dependency error, but `ng update @angular/core @angular/cli` worked.

**Comment by kishore0207** [comment] 2019-06-11 08:50
I am also getting the same error like 
Repository is not clean.  Please commit or stash any changes before updating.

I run this command ng update @angular/material, then i got the below error.
![repo-error](https://user-images.githubusercontent.com/37035639/59257629-eeea0880-8c53-11e9-99ce-8ed41e88d583.png)




`Repository is not clean.  Please commit or stash any changes before updating.`

**Comment by kishore0207** [comment] 2019-06-11 09:18
Am updating the angular 7 to 8, after updating the `ng update @angular/cli @angular/core` command updated successfully,
but after updating the material through `ng update @angular/material` entered, then i got the error.
`Repository is not clean. Please commit or stash any changes before updating.`

**Comment by deeja** [comment] 2019-06-11 22:50
> `Repository is not clean. Please commit or stash any changes before updating.`

Commit the changed files into your git repository and the message will disappear.
Likely an enforced checkpoint

**Comment by Kolahzary** [comment] 2019-06-13 10:17
It also happened to me, solved it by these steps

1. remove node_modules and package-lock.json
2. ng update @angular/core
3. ng update @angular/cli

**Comment by madalinignisca** [comment] 2019-06-21 19:04
`yarn add -D typescript@~3.4.0` sorted the problem.

For the moment, typescript will be updated to latest patch on 3.4.x versions. When Angular will allow latest stable typescript, I will update again it using the same command for the new supported minor version.

**Comment by alan-agius4** [comment] 2019-07-04 11:30
Duplicate of https://github.com/angular/angular-cli/issues/13095

**Closed by alan-agius4** 2019-07-04 11:30 UTC
Labels: comp: schematics/update, freq3: high, severity3: broken

**Comment by Sirjiskit** [comment] 2019-08-22 17:08
I once face the same issue was www.allovermyhead.com tried almost every thing getting one error of the other then i tried ng update --all --force;
Done evering was alright.

**Comment by mswilson4040** [comment] 2019-08-22 17:16
Seems like `ng update` is just getting more finicky and fragile with every release.
