### ISSUE TITLE
ng update tries to install 9.0.0-next.4

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#15536] opened 2019-08-31 09:38 UTC
I am having existing angular application based on 7 adn I just run 

`ng update @angular/cli@8 @angular/core@8 --force` and all seems to be now updated. But when I try to update material with 
`ng update @angular/material@8  or ng update @angular/material`  it tries to update existing angular packages I just updated to version angular/components#8 to version 9

```
ng update @angular/material@8
Using package manager: 'npm'
Collecting installed dependencies...
Found 62 dependencies.
Fetching dependency metadata from registry...
        Updating package.json with dependency @angular/material @ "8.1.4" (was "7.3.7")...
    Updating package.json with dependency @angular/compiler-cli @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/language-service @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/animations @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/compiler @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/core @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/common @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/cdk @ "8.1.4" (was "7.3.7")...
    Updating package.json with dependency @angular/platform-browser @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/router @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency @angular/forms @ "9.0.0-next.4" (was "8.2.4")...
    Updating package.json with dependency zone.js @ "0.10.2" (was "0.9.1")...

```

#### Expected Behavior

What behavior were you expecting to see?
I expect that it will only tries to update to version 8 and dont touch existing angular packages. 

#### Actual Behavior

What behavior did you actually see?

see above the output

#### Environment

```
Angular CLI: 8.3.2
Node: 11.0.0
OS: darwin x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.2
@angular-devkit/build-angular      0.803.2
@angular-devkit/build-ng-packagr   0.803.2
@angular-devkit/build-optimizer    0.803.2
@angular-devkit/build-webpack      0.803.2
@angular-devkit/core               8.3.2
@angular-devkit/schematics         8.3.2
@angular/cdk                       7.3.7
@angular/cli                       8.3.2
@angular/material                  7.3.7
@ngtools/webpack                   8.3.2
@schematics/angular                8.3.2
@schematics/update                 0.803.2
ng-packagr                         5.5.0
rxjs                               6.5.2
typescript                         3.5.3
webpack                            4.39.2
```

**Comment by alan-agius4** [comment] 2019-09-06 04:26
Duplicate of https://github.com/angular/angular-cli/issues/14980

**Closed by alan-agius4** 2019-09-06 04:26 UTC

**Comment by ernie58** [comment] 2019-09-10 08:18
@alan-agius4 Any ETA on #14980 ?

It's been 2 months since the bug was reported, and it prevents us from updating our code base.
We don't want to update the dependencies manually, since we're afraid to break something if we skip the upgrade process with the schematics.

Since the other ticket is locked, we have no idea when there will be a solution, or if anyone is actively working on this.
