### ISSUE TITLE
ng new create project in different path in OSX

### ISSUE THREAD

**Issue by tmleeek** [angular/angular-cli#2120] opened 2016-09-14 22:55 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 0.0.39
node: 5.1.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

hello , ng new dont generate in the same folder in same folder its generate it on my home user directory 

so i am in this path : 

/Users/alawialbaiti/projects/

and type : ng new myapp 

i found the project generated in this place : 

/Users/alawialbaiti/myapp 

4. The log given by the failure. Normally this include a stack trace and some
   more information.
none

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jasonhodges** [comment] 2016-09-15 02:55
@tmleeek perhaps you could try once more creating a new project under the /Users/alawialbaiti/projects/ directory. I just tried to reproduce the issue you've described and was unsuccessful. I must mention that I ran `npm install -g angular-cli` first to get a fresh install. 
My versions are listed here: 
angular-cli: 1.0.0-beta.12-1
node: 4.4.5
os: darwin x64

**Comment by tmleeek** [comment] 2016-09-15 04:16
I have done install -g with SUDO , i have try now to recreate the project but the problem still exist even that i am in other folder

Alawis-MacBook-Pro:Desktop alawialbiti$ cd demo
Alawis-MacBook-Pro:demo alawialbiti$ ls
1.mp4	2.mp4	3.mp4
Alawis-MacBook-Pro:demo alawialbiti$ ng new HelloWorld
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Directory 'HelloWorld' already exists.
Alawis-MacBook-Pro:demo alawialbiti$ mkdir hope
Alawis-MacBook-Pro:demo alawialbiti$ ls
1.mp4	2.mp4	3.mp4	hope
Alawis-MacBook-Pro:demo alawialbiti$ 
![screen shot 2016-09-15 at 7 15 46 am](https://cloud.githubusercontent.com/assets/1878832/18538221/43fdb762-7b14-11e6-9f3c-a15156673738.png)

**Comment by jasonhodges** [comment] 2016-09-15 04:48
Can you run `ls` on your Desktop and paste the results here? I've been working with the latest build all evening and have not had any directory issues.

**Comment by tmleeek** [comment] 2016-09-15 05:02
sure

Alawis-MacBook-Pro:Desktop alawialbiti$ ls

56923 Yoga.pdf alawi test demo ionic-1.3.1
Alawis-MacBook-Pro:Desktop alawialbiti$

**Comment by jasonhodges** [comment] 2016-09-15 05:21
Try running `npm install -g angular-cli` without using `sudo`
After that is complete, if you don't receive errors during the install, paste your versions here once more. 
Also, what version of OSX are you running?

**Comment by tmleeek** [comment] 2016-09-15 05:32
i tried without sudo but its full of errors

i use OSX 10.11.6 (15G1004)

**Comment by tmleeek** [comment] 2016-09-15 17:20
i forget to attach image of installing without sudo with npm log

![screen shot 2016-09-15 at 8 29 54 am](https://cloud.githubusercontent.com/assets/1878832/18559839/c8246c58-7b81-11e6-97c9-b7b92905074b.png)
[npm-debug.txt](https://github.com/angular/angular-cli/files/475216/npm-debug.txt)

**Comment by tmleeek** [comment] 2016-09-17 16:03
i want just to inform me that i have installed the lateset angular-cli and
angular 2 and still keep getting the same problem ..

**Comment by filipesilva** [comment] 2016-09-22 02:48
I think your issue is a dupe of https://github.com/angular/angular-cli/issues/1133, can you check that solution?

**Closed by filipesilva** 2016-09-22 02:48 UTC

**Comment by tmleeek** [comment] 2016-09-22 08:38
wow thats really was the solution thanks @filipesilva 
i was not know this could happen from package.json file .
