### ISSUE TITLE
about the ng build js&css path

### ISSUE THREAD

**Issue by nikejaycn** [angular/angular-cli#2740] opened 2016-10-17 10:12 UTC
we know `ng build` can inject created js & css path in the `index.html` file.

link this: 
```html
<script type="text/javascript" src="inline.js"></script>
<script type="text/javascript" src="styles.b52d2076048963e7cbfd.bundle.js"></script>
<script type="text/javascript" src="main.a9bd8f0a1785b67f561a.bundle.js"></script>
```

but we don't  use file physical path, we use the virtual path.
we want this: 
```html
<script type="text/javascript" src="/static/files/path/inline.js"></script>
<script type="text/javascript" src="/static/files/path/styles.b52d2076048963e7cbfd.bundle.js"></script>
<script type="text/javascript" src="/static/files/path/main.a9bd8f0a1785b67f561a.bundle.js"></script>
```

we don't find any configuration options in the `angular-cli` doc.
so the `angular-cli` can do that? how?

**Comment by filipesilva** [comment] 2016-10-17 22:35
Dupe of https://github.com/angular/angular-cli/issues/2276

**Closed by filipesilva** 2016-10-17 22:35 UTC

**Comment by jane-** [comment] 2017-03-29 06:45
use this  ng build  -prod   --base-href /path --deploy '/static/files/path/'
