### ISSUE TITLE
ng build --prod output size bigger than ng build

### ISSUE THREAD

**Issue by vikasediga** [angular/angular-cli#5832] opened 2017-04-04 22:57 UTC
```
1. Created a new app with cli.
2. With no other changes ran ng build which creates following bundles

chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 4.03 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.77 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.39 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

3. Then ran ng build --prod which by default enables aot, tree shaking, rollup etc creates bundles that are bigger than ng build (esp main.js bundle)

chunk    {0} polyfills.f52c146b4f7d1751829e.bundle.js (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.e088c8ce83e51568eb21.bundle.js (main) 26.8 kB {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.4fcbac8c60aff59a60f5.bundle.js (vendor) 1.16 MB [initial] [rendered]
chunk    {4} inline.d72284a6a83444350a39.bundle.js (inline) 0 bytes [entry] [rendered]

I would expect ng build --prod output to be smaller than ng build. Is this behavior expected? 

```

**Comment by ctrl-brk** [comment] 2017-04-04 23:57
Here's a good explanation:
https://github.com/angular/angular-cli/issues/4896#issuecomment-281984124

**Comment by filipesilva** [comment] 2017-04-10 16:33
Dupe of #4896 like @ctrl-brk said (cheers!). I'd like to add that with Angular v4.0 and up the main bundle might be bigger, but the vendor bundle is *much* smaller.

**Closed by filipesilva** 2017-04-10 16:33 UTC
