### ISSUE TITLE
Performing ng init to upgrade application

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#1188] opened 2016-06-24 01:38 UTC
When performing an upgrade per the documentation the `ng init` function does not respect the currently configured prefix, therefore everything generates with `app` adding to more manual inspection of files than necessary.

**Comment by filipesilva** [comment] 2016-07-04 01:43
Dupe of https://github.com/angular/angular-cli/issues/1170

**Closed by filipesilva** 2016-07-04 01:43 UTC
Labels: priority: 2 (required), type: bug
