### ISSUE TITLE
Unable to upgrade to 14.0.0-rc.1 with Yarn 3

### ISSUE THREAD

**Issue by Lonli-Lokli** [angular/angular-cli#23186] opened 2022-05-20 09:39 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes

### Description

Unable to execute npx ng update @angular/cli --next with yarn as package manager

## 🔬 Minimal Reproduction

Create angular 13 app with yarn 3 as package
Run npx ng update @angular/cli --next 

## 🔥 Exception or Error

<pre><code>
> Update Angular packages 'dependencies' and 'devDependencies' version prefix to '^' instead of '~'.
⠸ Installing packages (yarn)...Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn cache clean [--mirror] [--all]
  1. yarn cache clean [--mirror] [--all]
  2. yarn config get [--json] [--no-redacted] <name>
  3. yarn config set [--json] [-H,--home] <name> <value>
  4. yarn config unset [-H,--home] <name>
  5. yarn set resolution [-s,--save] <descriptor> <resolution>
  6. yarn set version from sources [--path #0] [--repository #0] [--branch #0] [--plugin #0] [--no-minify] [-f,--force] [--skip-plugins]
  7. yarn set version [--only-if-needed] <version>
  8. yarn workspaces list [--since] [-R,--recursive] [-v,--verbose] [--json]
  9. yarn --clipanion=definitions
 10. yarn help
 11. yarn help
 12. yarn help
 13. yarn <leadingArgument> ...
 14. yarn -v
 15. yarn -v
 16. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
 17. yarn bin [-v,--verbose] [--json] [name]
 18. yarn config [-v,--verbose] [--why] [--json]
 19. yarn dedupe [-s,--strategy #0] [-c,--check] [--json] [--mode #0] ...
 20. yarn exec <commandName> ...
 21. yarn explain peer-requirements [hash]
 22. yarn explain [--json] [code]
 23. yarn info [-A,--all] [-R,--recursive] [-X,--extra #0] [--cache] [--dependents] [--manifest] [--name-only] [--virtuals] [--json] ...
 24. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
 25. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
 26. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
 27. yarn link [-A,--all] [-p,--private] [-r,--relative] <destination>
 28. yarn unlink [-A,--all] ...
 29. yarn node ...
 30. yarn plugin import from sources [--path #0] [--repository #0] [--branch #0] [--no-minify] [-f,--force] <name>
 31. yarn plugin import <name>
 32. yarn plugin remove <name>
 33. yarn plugin list [--json]
 34. yarn plugin runtime [--json]
 35. yarn rebuild ...
 36. yarn remove [-A,--all] [--mode #0] ...
 37. yarn run
 38. yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
 39. yarn up [-i,--interactive] [-E,--exact] [-T,--tilde] [-C,--caret] [-R,--recursive] [--mode #0] ...
 40. yarn why [-R,--recursive] [--json] [--peers] <package>
 41. yarn workspace <workspaceName> <commandName> ...
 42. yarn create [-p,--package #0] [-q,--quiet] <command> ...
 43. yarn dlx [-p,--package #0] [-q,--quiet] <command> ...
 44. yarn init [-p,--private] [-w,--workspace] [-i,--install]
 45. yarn npm audit [-A,--all] [-R,--recursive] [--environment #0] [--json] [--severity #0]
 46. yarn npm info [-f,--fields #0] [--json] ...
 47. yarn npm login [-s,--scope #0] [--publish]
 48. yarn npm logout [-s,--scope #0] [--publish] [-A,--all]
 49. yarn npm publish [--access #0] [--tag #0] [--tolerate-republish] [--otp #0]
 50. yarn npm tag add <package> <tag>
 51. yarn npm tag list [--json] [package]
 52. yarn npm tag remove <package> <tag>
 53. yarn npm whoami [-s,--scope #0] [--publish]
 54. yarn pack [--install-if-needed] [-n,--dry-run] [--json] [-o,--out #0]
 55. yarn patch-commit [-s,--save] <patchFolder>
 56. yarn patch [--json] <package>
 57. yarn unplug [-A,--all] [-R,--recursive] [--json] ...
 58. yarn search
 59. yarn upgrade-interactive

While running --silent --ignore-scripts
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 14.0.0-rc.1
Node: 14.18.2
Package Manager: yarn 3.2.0
OS: win32 x64

Angular: 14.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0-rc.1
@angular-devkit/build-angular   14.0.0-rc.1
@angular-devkit/core            14.0.0-rc.1
@angular-devkit/schematics      14.0.0-rc.1
@schematics/angular             14.0.0-rc.1
rxjs                            7.5.5
typescript                      4.6.4
</code></pre>

**Comment by alan-agius4** [comment] 2022-05-20 09:52
Duplicate of #22048

**Closed by alan-agius4** 2022-05-20 09:52 UTC
