### ISSUE TITLE
Improving flag --save-dev for add package in devDependecies

### ISSUE THREAD

**Issue by kyusupov33** [angular/angular-cli#13237] opened 2018-12-20 06:32 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

In our @ngxs/schematics package we need to add it in devDependencies, but by default in angular-cli flag `--save-dev` will be `true`. You can make sure on it in this file: https://github.com/angular/angular-cli/blob/master/packages/angular/cli/tasks/npm-install.ts.

We can send PR and add ability to add package with `ng add` command in devDependencies.

**Comment by eranshmil** [comment] 2018-12-20 08:36
https://github.com/angular/angular-cli/blob/master/packages/angular/cli/commands/add-impl.ts#L46
I think the save default should be false, because of this comment.

**Comment by eranshmil** [comment] 2018-12-26 09:35
@hansl implemented the autosave in https://github.com/angular/angular-cli/commit/729d407fa1877d60d1e44efa3d657dc3ab4279e1
Also, this is a duplicate of https://github.com/angular/angular-cli/issues/12003

**Closed** 2019-10-14 20:40 UTC
Labels: comp: angular/cli, type: feature
