### ISSUE TITLE
Support "target": "es6" in tsconfig.json

### ISSUE THREAD

**Issue by hotforfeature** [angular/angular-cli#6370] opened 2017-05-18 15:08 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.0.3
node: 6.9.5
os: darwin x64

### Repro steps.
Change `tsconfig.json` "target" to "ES6" and run `ng build --prod`. UglifyJS will cause an error and the build will fail.

### The log given by the failure.
```
ERROR in main.87940961b85a05fb6d79.bundle.js from UglifyJs
Unexpected token: name (CoreModule) [main.87940961b85a05fb6d79.bundle.js:29,6]
```

### Desired functionality.
Either the CLI should replace the UglifyJS plugin with an ES6-compatible plugin (such as [Babili](https://github.com/babel/babili)) or the CLI should disable minifying when the target is ES6.

Another option would be to expose a flag to developers to disable minifying.

### Mention any other details that might be useful.
#5730 #5352 #4554 and #3191 are all issues that have been closed because the CLI does not support an ES6 target.

There is no open issue to track ES6 support, and with over 1 billion devices supporting ES6 with Chrome and Safari, it does not make sense to limit developers to ES5 compiled code when the workaround is as easy as opting out of minifying.

**Comment by aldo-roman** [comment] 2017-05-23 16:23
Check #2907, seems duplicated.

Also ES6 has been renamed to ES2015, let's better use the standard name.

**Comment by hotforfeature** [comment] 2017-05-23 16:45
To be clear, it has not been renamed, [the official name](http://www.ecma-international.org/ecma-262/6.0/) is "ECMAScript 2015", the 6th edition of ECMAScript. It has been abbreviated by the community as ES2015 or ES6. Neither of those abbreviations are standard from Ecma International.

It does look like I missed #2907 in my search for related issues. @sumitarora you're assigned to that issue, but there's no severity or effort labels attached to it. That ticket was made back in October of 2016, has it fallen through the cracks?

**Comment by merhawifissehaye** [comment] 2017-05-24 07:08
https://stackoverflow.com/a/43506162/4688650

**Comment by imcotton** [comment] 2017-05-31 17:33
I don't think this need to be configurable at all, simply overwritten to `target: es5` during production build internally, and that's it.

**Comment by hotforfeature** [comment] 2017-05-31 17:40
@imcotton I disagree. I want to build the app compiled to ES6. This is possible using webpack or other build tools. There's no reason to force the developer to use ES5 when using the cli

**Comment by imcotton** [comment] 2017-05-31 17:51
@hotforfeature I meant without ejecting from cli, if however you decide to crafting without cli's help, you can do anything you like by `ng eject` already, right?

**Comment by jimmykane** [comment] 2017-07-14 20:38
Any updates on this?

**Comment by filipesilva** [comment] 2017-07-28 13:42
Heya, I'm consolidating all the ES2015 support requests on the same issue, so it can be better actioned on.

Duplicate of https://github.com/angular/angular-cli/issues/2907.

**Closed by filipesilva** 2017-07-28 13:42 UTC
Labels: effort2: medium (days), priority: 3 (nice to have), severity2: inconvenient
