### ISSUE TITLE
"styles" attribute in .anglar-cli.json seems not recognize local npm packages

### ISSUE THREAD

**Issue by bwiercinski** [angular/angular-cli#9385] opened 2018-01-25 16:03 UTC
### Versions
```
Angular CLI: 1.6.5
Node: 8.9.3
OS: win32 x64 (windows 10)
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0

```

### Repro steps

* Step 1
create local npm package `my-package` with my.css file
* Step 2
install it via
`npm install /path/to/my-package`
* Step 3
add to .angular-cli.json in styles:
`"../node_modules/my-package/my.css"`
* Step 4
inspect webbrowser... there are no <style> in <head> DOM

### Observed behavior
```
there are no <style> in <head> DOM
```

### Desired behavior
add support or print warn

oh i forgot to add that when i'm installing package via local reference its create symbolic link in node_modules

**Comment by filipesilva** [comment] 2018-01-26 10:18
I think it's probably related to the symlink. How are you building btw? `ng serve` you'll get a JS bundle with the CSS code for speed, but on `ng build --prod` you will have CSS files. You can also try the build option `--preserve-symlinks` which usually helps with symlink related issues.

**Comment by mgechev** [comment] 2019-08-19 20:23
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:23 UTC
Labels: comp: devkit/build-angular, freq1: low, severity2: inconvenient, type: bug/fix
