### ISSUE TITLE
ngtools npm link

### ISSUE THREAD

**Issue by patrikx3** [angular/angular-cli#5723] opened 2017-03-28 19:45 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```bash
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /home/patrikx3/Projects/patrikx3/corifeus/corifeus-app-web-pages/node_modules/corifeus-web/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /home/patrikx3/Projects/patrikx3/corifeus/corifeus-app-web-pages/node_modules/corifeus-web/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /home/patrikx3/Projects/patrikx3/corifeus/corifeus-app-web-pages/node_modules/corifeus-web/node_modules/@angular/core/core.d.ts

```

### Repro steps.

Any npm link failures.

### The log given by the failure.

Given already.

### Desired functionality.

Works.

### Mention any other details that might be useful.

Simple, just broken.

**Comment by tabvn** [comment] 2017-03-31 04:03
same issue!

**Comment by tabvn** [comment] 2017-03-31 04:03
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/toan/Sites/loopcms/backend/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /Users/toan/Sites/loopcms/backend/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /Users/toan/Sites/loopcms/backend/node_modules/@angular/core/core.d.ts

**Comment by gingters** [comment] 2017-04-04 11:43
The issue is that the `npm link`ed packages contain their own copy of the `node_modules` folder, with their own copies of referenced packages (i.e. @angular/core etc.).

This is perhaps mainly an issue with the typescript compiler itself, and not so much @angular/cli or @angular/compiler. See also: https://github.com/Microsoft/TypeScript/issues/6496

A workaround is, to put this in the `tsconfig.json` `compilerOptions` element:
```
    "paths": {
      "@angular/common": [
        "../node_modules/@angular/common"
      ],
      "@angular/compiler": [
        "../node_modules/@angular/compiler"
      ],
      "@angular/core": [
        "../node_modules/@angular/core"
      ],
      "@angular/forms": [
        "../node_modules/@angular/forms"
      ],
      "@angular/platform-browser": [
        "../node_modules/@angular/platform-browser"
      ],
      "@angular/platform-browser-dynamic": [
        "../node_modules/@angular/platform-browser-dynamic"
      ],
      "@angular/router": [
        "../node_modules/@angular/router"
      ],
      "@angular/http": [
        "../node_modules/@angular/http"
      ]
    },
```

This will tell the compiler to use the main projects copy of these packages and not the nested ones.
However, this requires a change in the projects config that is not necessary when you don't link a package, so this is just a workaround.

It would be best, if the ngc / tsc would ignore nested node_modules when there is an explicit installed module on the top level for that.

**Comment by kylecordes** [comment] 2017-04-07 20:34
@gingters and others - I have had good results working around all this. Lots of details in this repo:

https://github.com/OasisDigital/many-to-many-angular

Example of applying the technique you mentioned:

https://github.com/OasisDigital/many-to-many-angular/blob/master/application/admin/tsconfig.json#L11

**Comment by sebelga** [comment] 2017-04-11 12:44
@kylecordes thanks for sharing this, looks great!

**Comment by filipesilva** [comment] 2017-05-03 11:30
Duplicate of https://github.com/angular/angular-cli/issues/3854, the answer there is very similar to @gingters's one.

**Closed by filipesilva** 2017-05-03 11:30 UTC
