### ISSUE TITLE
App created by `ng new` is created in wrong place

### ISSUE THREAD

**Issue by apinnecke** [angular/angular-cli#1079] opened 2016-06-14 13:55 UTC
Tried to use `ng new project-name`. The project get's created, but the path is wrong. My source code is located in a my `/src/apinnecke` directory. When I execute the `ng new project-name` inside of `/src/apinnecke` the project get's created at `/src/project-name`. Steps to reproduce are as follows:

``` bash
$ mkdir -p /src/apinnecke
$ cd /src/apinnecke/
$ ng new project-name
$ ls -a
. ..
$ ls -a ..
. .. project-name
```

Am i missing a configuration step or am I having a strange setup here? Totally confused. Took me about 10 minutes to find out where the project got created.

Host machine is an OSX El Capitan:

```
[apinnecke:~] 4s $ uname -a
Darwin minas-tirith 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
```

``` bash
[apinnecke:~] $ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.5
node: 5.11.1
os: darwin x64
[apinnecke:~] $
```

**Comment by Trendy** [comment] 2016-06-14 15:55
I'm unable to reproduce this on OS X Yosemite (10.10.5), following the same steps.

**Comment by Christopotamus** [comment] 2016-06-16 04:31
Can you post an ls -a of your /src directory? I know some yeoman generators will create things in the wrong directory based on some hidden files ,so maybe that's what's going on there?

**Comment by apinnecke** [comment] 2016-06-16 09:30
OH! Got it. try to add a `package.json` in `/src/package.json`, that will reproduce the issue. Removed that one after testing the project-name stuff because it was a backup of something older, so I abandoned it.

Can you please check now if you're able to reproduce?

**Comment by filipesilva** [comment] 2016-06-18 03:18
Possibly related: https://github.com/angular/angular-cli/issues/1045

**Comment by adamduren** [comment] 2016-06-22 13:12
I can reproduce the issue with @apinnecke method. Removing the package.json in my home folder resolves the issue.

**Comment by hansl** [comment] 2016-12-05 21:38
Closing this as `package.json` indicates where the project is.

**Closed by hansl** 2016-12-05 21:38 UTC
Labels: priority: 2 (required), type: bug

**Comment by filipesilva** [comment] 2017-02-26 15:26
This issue shouldn't happen anymore even with `package.json` in parent directories, due to the fix in https://github.com/angular/angular-cli/pull/4901.

**Comment by alexispolak** [comment] 2017-03-29 16:30
Same to me, Ubuntu 16.10,  Nodejs v6.10.1, npm 4.2.0 when i make "ng new Project-name" the folder is created in the root directory rather in the directory i am in. #5483
