### ISSUE TITLE
CSS minification issue with v12.0.1 and ngx-toaster

### ISSUE THREAD

**Issue by mohamed-badaoui** [angular/angular-cli#20895] opened 2021-05-21 20:18 UTC
# 🐞 Bug report

### Command (mark with an `x`)
- [x] build

### Is this a regression?
yes

Yes, the previous version in which this bug was not present was: 12.0.0

### Description
I upgraded @angular/cli / @angular-devkit/build-angular from v12.0.0 to v12.0.1, and used with package ngx-toaster (https://github.com/scttcper/ngx-toastr) 

But one of css rule of this toaster is 
``` 
.toast-container{z-index:999999}
```
and it is minified wrongly to:  
```
.toast-container{ z-index:#999 }
```
No issue with @angular/cli / @angular-devkit/build-angular **v12.0.0**

**Comment by alan-agius4** [comment] 2021-05-21 20:21
Duplicate of https://github.com/angular/angular-cli/issues/20870

**Closed by alan-agius4** 2021-05-21 20:21 UTC
