### ISSUE TITLE
Proposal: report-issue command

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#13] opened 2015-07-14 21:04 UTC
When a user mails us (or someone else) for help, it would be useful to gather information about their local environment, for example what version of node, npm, angular, libs they are using, log files, etc. This helps us reproduce their problem, and avoids a lot of back-and-forth communication to gather info ourselves.

We need more design thought, but my rough idea is a command for angular-cli that behaves a lot like the Send Feedback link in google properties. A wizard appears prompting user to explain their problem, gathers up the local repro info, and presents them with everything that will be sent off their machine (so they have a chance to prevent secrets being leaked).

**Comment by alexeagle** [comment] 2018-07-31 18:28
Thinking about this again in the context of the volume of issue reports we get that are inactionable. Maybe we should route most users to file issues using a feedback command in the CLI rather than type them into github

**Comment by SanderElias** [comment] 2018-07-31 18:50
You mean create a tool that wraps the output from `ng version` and adds the list of packages, and put that automatically in a GitHub issue,  including a couple of placeholders for the problems?

**Comment by alexeagle** [comment] 2018-08-01 13:30
Yeah and it could gather much more. In theory we should try to grab a
reproducible snapshot of the users code, but in practice that would involve
slurping their whole repo and their code is typically
proprietary/confidential - but whatever we could possibly gather to help us
diagnose and reproduce the problem.
It could also be an interactive wizard, trying to get more users down the
path of reading doc/faq, getting help from other channels, etc.

**Comment by filipesilva** [comment] 2018-08-22 10:49
I don't think we ever want user code unless it's already a repro app. Both because of the proprietary bit, but also because it's usually confounded by a lot of project specific logic. It's hard for us to unravel the real problem inside a real project.

Perhaps we could have a wizard for making repros. Something like:

```
> ng repro --create
Creating reproduction app
Reproduction created in repro-1234asdf
Please add a commit with the minimum code to reproduce the issue and run 'ng repro --submit`
# user adds repro
> ng repro --submit
Please open https://github.com/new in your browser and follow the instructions there to upload your reproduction.

Then fill in a new issue at https://github.com/angular/angular-cli/issues/new with the link to your repro. Thanks!

**Comment by filipesilva** [comment] 2018-08-22 10:59
I also remember some years ago that Ionic had a fantastic wizard to submit issues online, that also looked up issues with similar names and guided you through the process. 

It doesn't seem to be working right now though: https://ionicframework.com/submit-issue/

We could have such a support website with the wizard and a knowledge base of the error codes.

**Comment by mgechev** [comment] 2018-12-17 18:59
Can we achieve this with the telemetry? If we can, do we need to keep this issue open?

**Comment by alan-agius4** [comment] 2022-03-03 15:36
Closing as this is currently note in the CLI roadmap.
Let's reconsider this in the future.

**Closed by alan-agius4** 2022-03-03 15:36 UTC
Labels: feature, comp: angular/cli, insufficient votes
