### ISSUE TITLE
AOT compilation: property decorators are missing

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#3412] opened 2016-12-05 20:24 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?

Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
````
$ ng --version
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64
````

### Repro steps.
I've created a new app with the CLI. I've created a decorator function, and added that to properties in a Person class:
````
export function deserialize(target : any, keyName : string) : any {}

class Person {
    @deserialize
    firstName: string;
    @deserialize
    lastName: string;
}
````

In JIT, the generated JavaScript has these decorators:
````
var Person = (function () {
    function Person() {
    }
    __decorate([
        deserialize, 
        __metadata('design:type', String)
    ], Person.prototype, "firstName", void 0);
    __decorate([
        deserialize, 
        __metadata('design:type', String)
    ], Person.prototype, "lastName", void 0);
    return Person;
}());
````
However, in the AOT generated JavaScript, these are gone:
````
var Person = (function () {
    function Person() {
    }
    return Person;
}());
````

*Expected behavior*
The decorator information is available in AOT.

**Comment by rolandoldengarm** [comment] 2016-12-05 21:31
I think I know why this is happening.

The default webpack config is [here](https://github.com/angular/angular-cli/blob/f9a7c01602546dea6c92adb165a5c437689c41b4/packages/angular-cli/models/webpack-build-typescript.ts).

In the webpack loader, at [this line](https://github.com/angular/angular-cli/blob/f9a7c01602546dea6c92adb165a5c437689c41b4/packages/webpack/src/loader.ts#L160), for AOT (skipCodeGeneration === false in that case) it will call _removeDecorators()

Is there any reason why this is happening?

**Comment by hansl** [comment] 2016-12-05 21:33
Yes, we remove all decorators blindly. We're working towards a more smart solution where we properly convert those decorators to static properties, only for Angular annotations.

**Comment by hansl** [comment] 2016-12-05 21:34
Duplicate of https://github.com/angular/angular-cli/issues/2799

**Closed by hansl** 2016-12-05 21:34 UTC

**Comment by jarzimichal** [comment] 2016-12-05 21:57
Do you have any ETA for that functionality? as I have experienced the same problem and it would great to have that done.

> Yes, we remove all decorators blindly. We're working towards a more smart solution where we properly convert those decorators to static properties, only for Angular annotations.
