### ISSUE TITLE
while preloading modules view will be struck

### ISSUE THREAD

**Issue by adityarw** [angular/angular-cli#11993] opened 2018-08-24 05:56 UTC
i have around 10 modules each module contains atleast of 25-30 components, while preloading all the modules the login view will be struck m unable to fill the login credentials until it load all the module..

please add this feature..

please preload the modules background so that we can do our work on current view..

**Comment by alan-agius4** [comment] 2018-08-24 06:34
We are closed as a support request because this is both not a CLI specific issue and is already supported by the Angular framework. Assistance with using documented existing features is considered a support request. 

For additional information on preloading please see here [check](https://angular.io/guide/router#preloading-background-loading-of-feature-areas). 

Duplicate of #11344, #11985

**Closed by alan-agius4** 2018-08-24 06:34 UTC
