### ISSUE TITLE
Maximum call stack size exceeded during install

### ISSUE THREAD

**Issue by rodricifuentes1** [angular/angular-cli#253] opened 2016-02-25 19:43 UTC
Hello, I'm getting this error while trying to install angular-cli in my machine.

![angular-cli](https://cloud.githubusercontent.com/assets/5632896/13332017/05a3b34e-dbce-11e5-93fd-08f80029ea3a.png)

What do you suggest?

Thank you all!

**Comment by jkuri** [comment] 2016-02-25 19:48
Try removing `node_modules` and retry installing. Its not the best solution but I think it will work.

**Comment by filipesilva** [comment] 2016-02-26 12:15
I couldn't reproduce on my machine, but found a similar report on another repo and they recommended using an older node version.

Mine is a windows machine with versions as follows:
```
node v4.2.1
npm  v2.14.7
```

Our tests run in linux and osx machines with the following node versions:
```
node v4.3.1 (npm v2.14.12)
```
and
```
node v5.7.0 (npm v3.6.0)
```

That last one is exactly yours... Can you maybe try node 4?

**Comment by hansl** [comment] 2016-03-18 17:33
I'll close this as non reproducible. If you still see this happening, feel free to reopen and we'll try to work with you :)

**Closed by hansl** 2016-03-18 17:33 UTC

**Comment by balasivagnanam** [comment] 2016-06-04 13:09
occurs after update of node as well :( 

![image](https://cloud.githubusercontent.com/assets/4233785/15799737/8b4428d0-2a98-11e6-8a71-75ed6cdb0870.png)

**Comment by balasivagnanam** [comment] 2016-06-04 14:31
i had to run npm postintall to get rid of this error and get the project working..

**Comment by Nuttdguy** [comment] 2016-06-22 19:29
I had a similar issue. However, it seemed my was caused by having a second terminal window open. Possible cause of maximum call stack error? After closing second terminal window, install returned with no warnings or error - using windows 7.

**Comment by nhhockeyplayer** [comment] 2017-02-21 04:50
I reproduced it

**Comment by Benyaminrmb** [comment] 2018-01-25 18:23
yes -- its right thanks @nuttdguy  - using windows 10.
