### ISSUE TITLE
Hot reload freezes if mistake in template file is corrected

### ISSUE THREAD

**Issue by radekjakubowski** [angular/angular-cli#26334] opened 2023-11-11 10:50 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

While playing with Angular in dev mode I get stuck frequently at 
![image](https://github.com/angular/angular/assets/83402116/532755d7-c122-447f-a72b-101f79fa404e)

Rerunning app with 'ng serve' resolves but it's annoying.

### Please provide the exception or error you saw

```true
Application bundle generation complete. [0.074 seconds]
Reloading client(s)...
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0
Node: v18.13.0
```

**Comment by JoostK** [comment] 2023-11-11 11:03
Could you provide some additional information about your setup:
- What operation system is being used?
- Which CLI builder is being used? `@angular-devkit/build-angular:browser-esbuild` or `@angular-devkit/build-angular:application`

Some more general questions: how often does this occur? Could you identify which changes result in this behavior, or is it seemingly at random?

Other than that, some things you could try:
1. set the `NG_BUILD_DEBUG_PERF=1` environment variable to log profiling data, which may reveal where things get stuck.
2. set the `NG_BUILD_PARALLEL_TS=0` environment variable to disable parallelization in certain areas.

**Comment by radekjakubowski** [comment] 2023-11-11 11:21
I am using Windows 11 Home 22H2 and "builder": "@angular-devkit/build-angular:application".
I'd say it's pretty frequent - once every 5-6 file saves and mainly I've been fiddling with html files.

NG_BUILD_DEBUG_PERF=1 doesn't log as it gets stuck totally and only "Reloading client(s)" is there.
Will try disabling parallelization later.

**Comment by kimanderssonm3cs** [comment] 2023-11-13 16:17
Hi! I can confirm the same behaviour when getting html error, then fixing it, then getting stuck in reloading.

**Comment by Alecto** [comment] 2023-11-13 19:41
The same for me

**Comment by ChrisPienta1137** [comment] 2023-11-15 16:05
I also experienced this. 
Windows 11
Angular CLI 17.0.0
Node 20.9.0

**Comment by Ameerusa86** [comment] 2023-11-16 01:58
Same for me, I have to keep stopping and re run the projects, is there any fix, ty

**Comment by reduckted** [comment] 2023-11-16 04:27
This might be related to #26325 which has just been fixed and released (haven't tried it yet).

**Comment by radekjakubowski** [comment] 2023-11-16 09:15
I tried it out for dependencies listed below:
![image](https://github.com/angular/angular-cli/assets/83402116/26a77a63-35ee-484f-be00-11ecc91e7f65)

And it doesn't work sadly... I'd bump my node to current version to see if it resolves issue (currently v18.13.0)

**Comment by iqmeta** [comment] 2023-11-16 09:23
Same here, happens random after 2 - 7 reloads: 

![image](https://github.com/angular/angular-cli/assets/7533842/5c3496ec-d1d9-4219-8c27-c9cd05a97506)

"builder": "@angular-devkit/build-angular:application",

Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 10.2.3
OS: win32 x64 W11 22H2
Chrome 119

![image](https://github.com/angular/angular-cli/assets/7533842/5d9c58cc-0602-448f-a8b1-9bee6680051e)

**Comment by kimanderssonm3cs** [comment] 2023-11-16 09:36
> This might be related to #26325 which has just been fixed and released (haven't tried it yet).

I can confirm that it is now working correctly in 17.0.1

**Comment by radekjakubowski** [comment] 2023-11-16 10:16
Dunno why it got closed when me and @iqmeta still have same issue on 17.0.1...

**Comment by dgp1130** [comment] 2023-11-17 01:06
I did some investigation and was able to reproduce consistently with the following steps:

1. `npm init @angular@17.0.1 ng-new && cd ng-new`
1. `ng serve`
1. Introduce a syntax error into `app.component.html`.
    * I added `<div>Hello, world!</div` (no `>`).
1. App rebuilds automatically and issues a syntax error.
1. Fix the syntax error by adding `>`.
1. App automatically rebuilds and reloads the page successfully.
1. The CLI is now hung, any further edits to `app.component.html` no longer trigger a rebuild.

A few more notes:

* This seems specific to component _templates_. I was not able to reproduce this by introducing TypeScript typing errors as opposed to template syntax errors.
* I was not able to reproduce this behavior by editing `index.html` (although it doesn't seem to be watched at all which is likely a separate bug).
* You can edit the template in step 3. as much as you want and it will rebuild correctly. If you change the syntax error, it will correctly update the error message. However, once the template is fixed, the CLI is hung and no changes will trigger a rebuild.
* Weirdly, fixing the syntax error does trigger a successful rebuild (6.), only changes after that rebuild are ignored.

Digging down this looks like a Windows pathing issue. After every build we check if any files were added or removed from the compilation and update the file watcher to match. To do this we compare the files we were watching before a build with the files we found during the build ([relevant code](https://github.com/angular/angular-cli/blob/3b93df42daf9eda9215ea65d8ed0efd1ef203a09/packages/angular_devkit/build_angular/src/builders/application/build-action.ts#L152-L173)). Inspecting this state I found:

| Time | Path |
| ----- | ----- |
| Watched | `C:\\Users\\Doug\\Source\\ng-new\\src\\app\\app.component.html` |
| Built | `C:/Users/Doug/Source/ng-new/src/app/app.component.html` |

Due to the different separators, the CLI thinks we stopped watching `app.component.html` and removes it from the watched file set. Seems like we just need to make sure our paths are normalized so they are added/removed from the watched set correctly. The bad paths are likely coming from some of the tools we're invoking (TypeScript, esbuild, etc.). So we'll want to normalize those to a consistent structure when we receive them.

**Comment by kimanderssonm3cs** [comment] 2023-11-17 11:33
Yeah sorry, it seems to be working when .ts files are fixed, but as you say above, html files and other files are still breaking.
the global styles.scss does emit changes until it receives an error, after that it stops being watched.

**Comment by ssougnez** [comment] 2023-11-17 12:17
I think I have the same issue. 

In my case, I'm not using `ng serve` but `ng build --watch` and I often have the case that fixing an issue in a template does not trigger the incremental build:

For example, here, I updated a regular variable into a signal but the compiler does not see it:

```
⠦ Changes detected. Rebuilding...X [ERROR] NG7: This comparison appears to be unintentional because the types 'WritableSignal<boolean>' and 'boolean' have no overlap. [plugin angular-compiler]

    src/app/branch/components/branch-homepage-update-form/branch-homepage-update-form.component.html:28:21:
      28 │           [loading]="updating === true"
         ╵                      ~~~~~~~~~~~~~~~~~

  Error occurs in the template of component BranchHomepageUpdateFormComponent.

    src/app/branch/components/branch-homepage-update-form/branch-homepage-update-form.component.ts:23:15:
      23 │   templateUrl: './branch-homepage-update-form.component.html',
```

If I stop the build and launch it again it works.
I'm using node 20.9.0, the CLI 17.0.1 and the application builder.

**Comment by dgp1130** [comment] 2023-11-18 00:08
@clydin landed a potential fix in https://github.com/angular/angular-cli/pull/26393. I wasn't able to reproduce the issue in my testing.

It's unfortunately pretty late on a Friday right now, but I can follow up with a patch release Monday morning. This should be in the `17.0.2` release.

**Comment by radekjakubowski** [comment] 2023-11-18 08:09
@dgp1130 great news! Amazing work with v17 so far <3

**Comment by alan-agius4** [comment] 2023-11-20 06:28
Duplicate of https://github.com/angular/angular-cli/issues/26334

**Closed** 2023-11-20 19:04 UTC
Labels: type: bug/fix, needs: more info, area: devkit/build-angular, devkit/build-angular:application

**Comment by radekjakubowski** [comment] 2023-11-21 08:16
@dgp1130 
Hey Douglas, can confirm it's fixed :)

**Comment by ssougnez** [comment] 2023-11-21 10:54
So far, so good for me as well/

**Comment by geosh2000** [comment] 2023-11-23 03:54
still happening:

<img width="588" alt="Captura de pantalla 2023-11-22 a la(s) 10 43 18 p m" src="https://github.com/angular/angular-cli/assets/31418457/a27a2669-606d-434a-ac53-6b52c77876e2">

<img width="649" alt="image" src="https://github.com/angular/angular-cli/assets/31418457/9b715ec5-252f-4de1-9cc4-f798dd9d67a4">

package.json:

{
  "name": "gg-erp17",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.4",
    "@angular/cdk": "^17.0.1",
    "@angular/common": "^17.0.4",
    "@angular/compiler": "^17.0.4",
    "@angular/core": "^17.0.4",
    "@angular/forms": "^17.0.4",
    "@angular/material": "^17.0.1",
    "@angular/platform-browser": "^17.0.4",
    "@angular/platform-browser-dynamic": "^17.0.4",
    "@angular/router": "^17.0.4",
    "rxjs": "~7.8.0",
    "tslib": "^2.6.2",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.3",
    "@angular/cli": "^17.0.3",
    "@angular/compiler-cli": "^17.0.4",
    "@types/jasmine": "~5.1.0",
    "autoprefixer": "^10.4.16",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "postcss": "^8.4.31",
    "tailwindcss": "^3.3.5",
    "typescript": "~5.2.2"
  }
}

**Comment by ManciDRaffy** [comment] 2023-11-23 12:37
Same here, bug still occurs, but for me, it's every time I change something in HTML, so not only on fixing a bug

**Comment by alan-agius4** [comment] 2023-11-23 13:38
For those users who are still reporting file changes not triggering rebuilds, can you check if applying the changes in https://github.com/angular/angular-cli/pull/26468 fixes the issue? 

Steps to apply the update:
- Update the file contents of `node_modules/@angular-devkit/build-angular/src/tools/esbuild/watcher.js` with https://gist.github.com/alan-agius4/f9a9c0a52f1b6b53895d3617e515dd97
- Update the file contents of `node_modules/@angular-devkit/build-angular/src/utils/environment-options.js` with https://gist.github.com/alan-agius4/200fe02b59519a1bb0f5338fb8bcc225

**Comment by HCenggel** [comment] 2023-11-24 08:53
I have the default configuration. After using ng serve to start the project, this problem will also occur.

**Comment by muhamedkarajic** [comment] 2023-11-25 16:42
To me it seems like its cause I was using something instead of app-root. Another thing which I had quit a few issues was that I was using direct import ... from 'src/app/...' which seems now not anymore to work, so you have to use '../../..' etc.

**Comment by tarzasai** [comment] 2023-11-30 00:42
> Same here, bug still occurs, but for me, it's every time I change something in HTML, so not only on fixing a bug

Me too and while it was only happening only on html errors in 17.0.0, with 17.0.2 I have to re-serve after every change, even if the html is correct.

**Comment by GuillaumeChata** [comment] 2023-12-18 16:14
Same errors occurs with the 17.0.6 version of CLI.
