### ISSUE TITLE
Module creation fails

### ISSUE THREAD

**Issue by JohnCashmore** [angular/angular-cli#2668] opened 2016-10-12 15:09 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.17
node: 4.6.0
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

When creating a new module the name is auto changed for the create but it appears not for the rest.

### The log given by the failure.
> Normally this include a stack trace and some more information.

➜  my-app git:(master) ✗ ng g module rulesManagement
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing module
  create src/app/rules-management/rules-management.module.ts
installing component
Invalid path: "/home/developer/Projects/my-app/src/app/rulesManagement"" is not a valid path.
➜  my-app git:(master) ✗

**Comment by filipesilva** [comment] 2016-10-14 17:52
@Brocco can you have a look?

**Comment by Brocco** [comment] 2016-10-18 02:24
This will be resolved by PR #2756 and is a dupe of issue #2724, this issue can be tracked there

**Closed by Brocco** 2016-10-18 02:24 UTC
Labels: command: generate, priority: 1 (urgent), type: bug
