### ISSUE TITLE
Set NODE_ENV to production when building a prod build

### ISSUE THREAD

**Issue by Pajn** [angular/angular-cli#2737] opened 2016-10-17 06:48 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux, Ubuntu 16.04

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
❯ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.16
node: 6.5.0
os: linux x64
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Yes, run ng new in another dir and manually merge the setup with the repo.

### The log given by the failure.
> Normally this include a stack trace and some more information.

In production, this is logged:
>You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

### Mention any other details that might be useful.

When running a production build NODE_ENV should be set to production so that development code is stripped out by uglify. Redux as well as many other libraries depends on this behavior.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-10-17 22:09
Dupe of https://github.com/angular/angular-cli/issues/2110

**Closed by filipesilva** 2016-10-17 22:09 UTC
