### ISSUE TITLE
ng serve - assets folder with large video files causing heap out of memory, unable to compile

### ISSUE THREAD

**Issue by appsteams** [angular/angular-cli#14821] opened 2019-06-18 09:35 UTC
ng serve - assets folder with large video files causing heap out of memory, unable to compile

**Comment by alan-agius4** [comment] 2019-06-19 07:30
The most probable root cause is that during `serve` files are stored in memory.

There are two options here as workaround:
1) Increase the memory limit of the process using `--max_old_space_size`
2) Avoid copying these large files during serve.

**Comment by alan-agius4** [comment] 2020-12-01 07:46
Duplicate of https://github.com/angular/angular-cli/issues/9629

**Closed by alan-agius4** 2020-12-01 07:46 UTC
Labels: comp: devkit/build-angular, freq1: low, severity3: broken, type: bug/fix
