### ISSUE TITLE
Can't test ng update with beta versions

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#9517] opened 2018-02-05 18:44 UTC
### Versions
```
Angular CLI: 1.7.0-beta.3
Node: 8.4.0
OS: linux x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cdk: 5.0.4
@angular/cli: 1.7.0-beta.3
@angular/material: 5.0.4
@angular-devkit/build-optimizer: 0.2.0
@angular-devkit/core: 0.2.0
@angular-devkit/schematics: 0.2.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.0-beta.3
@schematics/angular: 0.2.0
@schematics/package-update: 0.2.0
typescript: 2.6.2
webpack: 3.10.0

```

### Repro steps
Run `ng update` with the @next version of Angular CLI.

### Observed behavior
```
Error: Cannot downgrade package "@angular/cli" from version "^1.7.0-beta.3" to "1.6.7".
Cannot downgrade package "@angular/cli" from version "^1.7.0-beta.3" to "1.6.7".

```

### Desired behavior
I would like to be able to override this error, or get my project into a state where I'm running the latest version of Angular, and the @next version of the CLI.

**Comment by clydin** [comment] 2018-02-06 20:19
Closing as a duplicate of #9507.

**Closed by clydin** 2018-02-06 20:19 UTC
Labels: comp: cli/update
