### ISSUE TITLE
Error on creation new project 

### ISSUE THREAD

**Issue by rachlenko** [angular/angular-cli#1138] opened 2016-06-19 15:42 UTC
How can I fix it ? 

Error: @angular/router@3.0.0-alpha.3 postinstall: `typings install`
spawn ENOENT
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/npm/lib/utils/spawn.js:17:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by filipesilva** [comment] 2016-06-19 15:53
Duplicate of https://github.com/angular/angular-cli/issues/1092. There is a temporary solution in there, and a permanent solution in the next release.

**Closed by filipesilva** 2016-06-19 15:53 UTC
