### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by ishara** [angular/angular-cli#3099] opened 2016-11-10 12:57 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10.

### Versions.
> 
angular-cli: 1.0.0-beta.19
node: 6.6.0
os: win32 x64

### Repro steps.
>
This is big project 

### The log given by the failure.
> 

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### .

How can I set Heap size in ng
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gelliott181** [comment] 2016-11-10 19:28
For others also seeking help with this, the issue is known to plague the CLI (#1652, #2974) when projects grow beyond what many of us consider small-medium sized codebases. As you mentioned, the fix it to set Node's heap size. This is done with `node --max_old_space_size=[Space in MB]` followed by whatever call you wanted to make

**Comment by naveedahmed1** [comment] 2016-11-17 20:48
This should help https://github.com/angular/angular-cli/issues/1652#issuecomment-261269197

**Comment by filipesilva** [comment] 2016-12-12 16:17
Closing as dupe of https://github.com/angular/angular-cli/issues/1652

**Closed by filipesilva** 2016-12-12 16:17 UTC
