### ISSUE TITLE
Could not determine version for package...

### ISSUE THREAD

**Issue by juristr** [angular/angular-cli#16162] opened 2019-11-12 11:32 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

The `ng update` command fails when a package uses the `git+ssh://` or `https` reference rather than a version number (as you usually have).  While this is definitely not best practice, it happens from now and then inside enterprise environments.

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Add a package referenced via `git+ssh`, for instance:

"@biesbjerg/ngx-translate-extract": "git+ssh://git@bitbucket.org:r3_gis_dev/ngx-translate-extract.git#3.0.5-r3patch.01",

```
...
"dependencies": {
    ...
    "mypackage": "git+ssh://git@...mypackage.git#3.0.5",
}
```

Having this in the `package.json` run `ng update @angular/core@next @angular/cli@next`.

As a concrete example of an external package, this one should also fail:

```
...
"dependencies": {
    ...
    "material-icon-font": "https://github.com/petergng/materialIconFont.git",
}
```

## 🔥 Exception or Error
<pre><code>

An unexpected error happened; could not determine version for package ...
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.18
Node: 11.6.0
OS: darwin x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.18
@angular-devkit/build-angular      0.803.18
@angular-devkit/build-optimizer    0.803.18
@angular-devkit/build-webpack      0.803.18
@angular-devkit/core               8.3.18
@angular-devkit/schematics         8.1.2
@angular/cdk                       8.0.2
@angular/cdk-experimental          8.0.2
@angular/cli                       8.3.18
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.0.2
@angular/material-moment-adapter   8.0.2
@ngtools/webpack                   8.3.18
@schematics/angular                7.3.9
@schematics/update                 0.803.18
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

//cc @filipesilva

**Comment by filipesilva** [comment] 2019-11-12 11:35
I *think* this is a regression, I remember deps we couldn't identify properly were supposed to be ignored. @clydin might know more.

**Comment by alan-agius4** [comment] 2019-11-12 11:40
Duplicate of https://github.com/angular/angular-cli/issues/13059

**Comment by filipesilva** [comment] 2019-11-12 18:33
Closing in favor of #13059,

**Closed by filipesilva** 2019-11-12 18:33 UTC
Labels: comp: schematics/update, freq1: low, severity5: regression, type: bug/fix
