### ISSUE TITLE
Migrating to ESBuild breaks SASS imports with "~" (tilde)

### ISSUE THREAD

**Issue by pfeileon** [angular/angular-cli#27872] opened 2024-06-18 08:53 UTC
### Command

build, test

### Is this a regression?

Unknown

### Description

When migrating to the new build system, "\~" (tilde) is no longer supported, which is fine, I guess.
But when you remove the "\~" the test build fails: https://github.com/fontsource/fontsource/issues/798#issuecomment-2166824082

### Minimal Reproduction

s. OP in linked issue for reproduction
[EDIT] or simply set up an Angular 17 project and migrate it to 18 with the new build option selected. Then install `npm i @fontsource/roboto` and include the SASS mixin in your project.

### Exception or Error

```text
./src/styles.scss - Error: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
/home/pfeileon/git/my-app/node_modules/@fontsource/roboto/scss/mixins.scss:189:6: Can't resolve '../node_modules/@fontsource/roboto/scss/@fontsource/roboto/files/roboto-cyrillic-ext-300-normal.woff' in '/home/pfeileon/git/my-app/src'
```

### Your Environment

```text
Angular CLI: 18.0.4
Node: 20.12.2
Package Manager: npm 10.5.0
OS: linux x64

Angular: 18.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.4
@angular-devkit/build-angular   18.0.4
@angular-devkit/core            18.0.4
@angular-devkit/schematics      18.0.4
@angular/cli                    18.0.4
@schematics/angular             18.0.4
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by alan-agius4** [comment] 2024-06-18 09:16
Duplicate of https://github.com/angular/angular-cli/issues/26718

**Closed by alan-agius4** 2024-06-18 09:16 UTC
