### ISSUE TITLE
Build error - The Broccoli Plugin: [Funnel] failed with: ng serve on windows10 

### ISSUE THREAD

**Issue by Alshahranimohammed** [angular/angular-cli#1768] opened 2016-08-19 21:41 UTC
looking for help. I installed angular CLI and use **ng new** it works fine i think. Because i got files have been created. but after dive in folder for **ng serve** i got the following error. 

I tried it on node 4.5.0 and not working too

Now I have this version and it is not working too :)  
angular-cli: 1.0.0-beta.10
node: 6.3.1
npm :3.10.6
os: win32 ia32

anyone could help :) waiting for expert :+1: 

// start of error 
(node:6500) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
The Broccoli Plugin: [Funnel] failed with:
Error: EISDIR: illegal operation on a directory, symlink 'D:\training\angularjs2\helloworld\src' -> 'D:\training\angularjs2\helloworld\tmp\funnel-input_base_path-185X28Ag.tmp\0'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at symlinkWindows (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\symlink-or-copy\index.js:101:16)
    at symlinkOrCopySync (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\symlink-or-copy\index.js:53:5)
    at D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\broccoli-plugin\read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at Funnel.Plugin (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at new Funnel (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\broccoli-funnel\index.js:44:10)
    at Angular2App._buildInputTree (D:\training\angularjs2\helloworld\node_modules\angular-cli\lib\broccoli\angular2-app.js:92:7)
    at new Angular2App (D:\training\angularjs2\helloworld\node_modules\angular-cli\lib\broccoli\angular2-app.js:51:41)
    at module.exports (D:\training\angularjs2\helloworld\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\ember-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\training\angularjs2\helloworld\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

and when i checked the version ng -v i got another error 
"(node:6116) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
"

**Comment by Alshahranimohammed** [comment] 2016-08-19 22:05
one more thing to add. 
I am running CMD as administrator. and when I use ng new it takes a long time to create the project **about 15 minutes**. I just created a project to test the time and I got the following message which I don't know what does it mean ? 

// start of message 
 Installing packages for tooling via npm
├── es6-shim (global)
├── angular-protractor (global dev)
├── jasmine (global dev)
└── selenium-webdriver (global dev)
// end of message

**Comment by Ardenexal** [comment] 2016-08-22 03:20
i'm getting the same issue as well, I've tried using the new Ubuntu integrated bash console for windows 10 as well the normal CMD as administrator  and get the same error

**Comment by filipesilva** [comment] 2016-08-23 14:49
@Alshahranimohammed if you are using BashOnWindows then this is a dupe of https://github.com/angular/angular-cli/issues/1555, see the closing comment.

Otherwise, you seem to be having some symlink permissions issue. The webpack preview version does not use symlink so you might consider upgrading to that: https://github.com/angular/angular-cli#webpack-preview-release-update

**Closed by filipesilva** 2016-08-23 14:49 UTC

**Comment by Alshahranimohammed** [comment] 2016-08-23 21:26
@filipesilva thanks for the help. it works fine now no more build error. could you please help with the time ? i just create a project with ng new and **it takes 20 minutes to finish !**

any idea what is going on ?

**Comment by filipesilva** [comment] 2016-08-23 21:59
`ng new` also does `npm install`, which locally installs `angular-cli` and it currently is a big package. See https://github.com/angular/angular-cli/issues/1263 for more information.

It shouldn't take 20 minutes though.... On my computer it takes some 2-3 minutes. The only think that comes to mind is internet speed.
