### ISSUE TITLE
Can't build AOT if project have unused @Pipe class

### ISSUE THREAD

**Issue by visat09** [angular/angular-cli#9380] opened 2018-01-25 09:09 UTC
## when i try to build AOT i got this error message

> ERROR in ./src/main.ts
Module not found: Error: Can't resolve './app/app.module.ngfactory' in '/Users/name/workspace/co/xxx/xxx/src'
resolve './app/app.module.ngfactory' in '/Users/name/workspace/co/xxx/xxx/src'
  using description file: /Users/name/workspace/co/xxx/xxx/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/name/workspace/co/xxx/xxx/package.json (relative path: ./src)
    using description file: /Users/name/workspace/co/xxx/xxx/package.json (relative path: ./src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/name/workspace/co/xxx/xxx/src/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/name/workspace/co/xxx/xxx/src/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/name/workspace/co/xxx/xxx/src/app/app.module.ngfactory.js doesn't exist
      as directory
        /Users/name/workspace/co/xxx/xxx/src/app/app.module.ngfactory doesn't exist
[/Users/name/workspace/co/xxx/xxx/src/app/app.module.ngfactory]
[/Users/name/workspace/co/xxx/xxx/src/app/app.module.ngfactory.ts]
[/Users/name/workspace/co/xxx/xxx/src/app/app.module.ngfactory.js]
[/Users/name/workspace/co/xxx/xxx/src/app/app.module.ngfactory]
 @ ./src/main.ts 3:0-66
 @ multi ./src/main.ts

## i alredy fix that by remove Pipe Class and i can build aot (work fine)

this is my Pipe Class

![screen shot 2561-01-25 at 16 05 33](https://user-images.githubusercontent.com/6519797/35379718-93ee6778-01e9-11e8-9b53-8a8ad6cb0d5c.png)

## my package.json
> {
  "name": "xxx",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --disable-host-check",
    "build": "ng build",
    "build-prod-aot": "ng build --env=prod --aot",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "bootstrap": "4.0.0-beta.2",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "ng-sidebar": "^6.0.4",
    "npm": "^5.6.0",
    "primeng": "^5.0.2",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.5",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "angular-ide": "^0.9.38",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

**Comment by mgechev** [comment] 2019-08-19 20:23
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:23 UTC
Labels: comp: devkit/build-angular, freq1: low, severity1: confusing, type: bug/fix
