### ISSUE TITLE
$ ng update

### ISSUE THREAD

**Issue by Richardo86** [angular/angular-cli#18896] opened 2020-09-26 03:33 UTC
$ ng update
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
internal/modules/cjs/loader.js:1083
  throw err;
  ^

Error: Cannot find module 'C:\Users\Firstname'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

_Originally posted by @Richardo86 in https://github.com/angular/angular-cli/issues/18891#issuecomment-699310568_

**Comment by alan-agius4** [comment] 2020-09-26 04:11
Duplicate of https://github.com/angular/angular-cli/issues/18891

**Closed by alan-agius4** 2020-09-26 04:11 UTC
