### ISSUE TITLE
why the types node,jasmine  in tsconfig.spec.json?

### ISSUE THREAD

**Issue by stefanaerts** [angular/angular-cli#5106] opened 2017-02-28 13:38 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

mac osx

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
![image](https://cloud.githubusercontent.com/assets/3684599/23407262/6bc9284e-fdc3-11e6-977a-478e1ca7a8fd.png)

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

when i remove the types jasmin,node from the tsconfig.spec.json file,
npm run test and npm run e2e still work fine for my empty project
I wonder why?

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Brocco** [comment] 2017-03-01 04:31
When you say "removed from my project" what did that entail?

**Comment by stefanaerts** [comment] 2017-03-01 08:43
Sry i was not clear, i removed it from types in tsconfig.spec.json.
And run the test and e2e after that,both worked fine

**Comment by filipesilva** [comment] 2017-03-02 08:46
`tsconfig.spec.json` is used for unit tests only with `ng test`, and not having them there should give you a couple of errors like what happens when you remove them (and leave an empty array) from `tsconfig.e2e.json`:

```
e2e\app.e2e-spec.ts (2,23): Cannot find name 'exports'. (2304)
e2e\app.e2e-spec.ts (3,18): Cannot find name 'require'. (2304)
e2e\app.e2e-spec.ts (4,1): Cannot find name 'describe'. (2304)
e2e\app.e2e-spec.ts (6,5): Cannot find name 'beforeEach'. (2304)
e2e\app.e2e-spec.ts (9,5): Cannot find name 'it'. (2304)
e2e\app.e2e-spec.ts (11,9): Cannot find name 'expect'. (2304)
```

I tested it right now and it's as you say `ng test` does not show errors after removing them. This makes me think there's something broken somewhere. Thanks for bringing this up!

**Comment by splintercode** [comment] 2017-03-09 18:04
I think this might be related https://github.com/angular/angular-cli/issues/5322
To get `require` to be recognized I added the following in my tsconfig.app.json and now with RC its like it is ignoring the types array. 

```
"types": [
      "node"
    ]
```

**Comment by filipesilva** [comment] 2017-03-19 22:00
Dupe of #5322

**Closed by filipesilva** 2017-03-19 22:00 UTC
Labels: type: bug
