### ISSUE TITLE
CLI exit code is 0 when quitting for unknown options

### ISSUE THREAD

**Issue by delego-wlritchi** [angular/angular-cli#10759] opened 2018-05-09 18:10 UTC
### Versions
```
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.0
Node: 10.0.0
OS: linux x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/flex-layout              5.0.0-beta.14
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
Run an Angular CLI command with an unknown option, e.g. `--foo`
```
$ ng build --foo
Unknown option: '--foo'
```
### Observed behavior
The CLI exits (as expected), but with exit code 0 (indicating no error).
```
$ echo $?
0
```

### Desired behavior
The CLI should exit with a nonzero exit code to indicate that the command did not complete successfully. This is particularly important for scripts that call the CLI, especially if these scripts run on a CI server and do not have their output closely monitored. For example, if a CI server is misconfigured and passes an unknown option to `ng test`, the tests will not run at all, but the CI server would incorrectly label the build as passing all tests.

**Comment by megfault** [comment] 2018-07-20 08:10
When is this fix expected to be merged? This is a rather serious issue for people using CI tools.

I am sorry if this is perceived as impolite. I have no idea of what your time plans are, but I see a fix that is two months old by now, and it's silently letting broken code being deployed in god knows how many repositories of unsuspecting users.

**Comment by compeek** [comment] 2018-10-12 21:07
This appears to be fixed in newer versions, although I'm not sure which one it was fixed in. I'm on @angular/cli 6.2.3 and am getting a 1 exit code for unknown options.

**Comment by alan-agius4** [comment] 2018-12-07 11:49
_
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior._

**Closed by alan-agius4** 2018-12-07 11:49 UTC
Labels: comp: devkit/build-angular
