### ISSUE TITLE
provide blueprint for component library as a feature

### ISSUE THREAD

**Issue by yeiniel** [angular/angular-cli#1284] opened 2016-07-05 17:05 UTC
Using angular-cli improve development but something i was missing is a blueprint to create component libraries. Right now i have developed a library of services to be consumed by more than one application and i have to resort to use a yeoman generator. The generator was fine (except for the lack of testing infrastructure) but i prefer a consistent coding style and the best practices that can bring to the table the angular-cli. Any idea if this feature will be included in the roadmap? May be implementing the **App Creation Using Template** story is the way to achieve this.

**Comment by filipesilva** [comment] 2016-07-28 02:41
This feature is on roadmap but I have no set date for it.

**Comment by kartzum** [comment] 2016-08-09 19:28
Ok, but may be have you any advice how to create components/services libraries for angular2 or some manual steps for creating these ones through angular cli?

I tried to create simple library through angular cli (https://github.com/kartzum/color-generators) but got some problems. There are some:

- 'app' name can not be changed
- after 'npm publish'  package does not contain 'dist' folder without manual steps

**Comment by berwyn** [comment] 2016-08-09 19:59
I'd like to throw in support for this issue. I have feature teams working vertical slices of the app and it would be great if I could pull those out into separate projects and still use the cli tool!

**Comment by filipesilva** [comment] 2016-09-22 04:03
Marking as dupe of https://github.com/angular/angular-cli/issues/1284 to keep discussion in a single place.

**Closed by filipesilva** 2016-09-22 04:03 UTC
Labels: priority: 2 (required), type: feature

**Comment by kartzum** [comment] 2016-09-22 06:53
Could you please write link to new discussion?

**Comment by yeiniel** [comment] 2016-09-22 14:05
Hey @filipesilva i think you make a mistake marking this as a dupe of #1284 because this is the issue #1284. Is the issue number wrong?

**Comment by filipesilva** [comment] 2016-10-03 17:58
@kartzum @yeiniel sorry, my bad! The right link is https://github.com/angular/angular-cli/issues/1692
