### ISSUE TITLE
Problem install on node 6

### ISSUE THREAD

**Issue by jvbianchi** [angular/angular-cli#568] opened 2016-04-29 23:45 UTC
Problem tring to install on node 6
1. Mac OSX El Capitan: v10.11.4
2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        
        nvm: v0.31.0
        node --version: v6.0.0
        npm --version: v3.8.7
        npm info angular-cli: v0.0.34 

3. Repro steps. Tell us exactly what you did and how you came to the failure. 
   If you can give us steps from the moment you created an empty application,
   even better! Please try to be as descriptive as you can; this will avoid
   unnecessary back and forth. Was this an app that wasn't created using the
   CLI? What change did you do on your code? etc.
           
         npm i -g angular-cli

4. The log given by the failure. Normally this include a stack trace and some
   more information.

`npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible.
/Users/developer/.nvm/versions/node/v6.0.0/lib
└── (empty)

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/developer/.nvm/versions/node/v6.0.0/bin/node" "/Users/developer/.nvm/versions/node/v6.0.0/bin/npm" "i" "-g" "angular-cli"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.7
npm ERR! path /Users/developer/.nvm/versions/node/v6.0.0/lib/node_modules/.staging/abbrev-4e3f7ee8
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/developer/.nvm/versions/node/v6.0.0/lib/node_modules/.staging/abbrev-4e3f7ee8' -> '/Users/developer/.nvm/versions/node/v6.0.0/lib/node_modules/angular-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/developer/.nvm/versions/node/v6.0.0/lib/node_modules/.staging/abbrev-4e3f7ee8' -> '/Users/developer/.nvm/versions/node/v6.0.0/lib/node_modules/angular-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by filipesilva** [comment] 2016-04-29 23:49
Seems like a dupe of https://github.com/angular/angular-cli/issues/548. Can you check if the solution there works?

**Comment by jvbianchi** [comment] 2016-04-29 23:52
I alredy using nvm 0.31.0

**Comment by filipesilva** [comment] 2016-04-30 00:09
Hm.... can you perhaps do `npm cache clean` and retry?

**Comment by jvbianchi** [comment] 2016-04-30 00:15
I managed to solve it. 

I had angular-cli v0.0.33 installed, I uninstalled it and ran npm cache clean again. The error disappeared.

Thanks and sorry to bother you.

**Comment by filipesilva** [comment] 2016-04-30 00:18
No bother at all, other users might have the same issue!

**Closed by filipesilva** 2016-04-30 00:18 UTC
