### ISSUE TITLE
creating lazy loaded route --route flag adds route after wild card route

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular-cli#15550] opened 2019-09-07 06:57 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
NA

### Description

 A clear and concise description of the problem...
with CLI 8.3.0 we can generate the lazy loaded module, and it works great.
ng g module testmodule --routing true --route test --module app

The only problem is it is standard practice to add wild card routes in app module in, currently the lazy-loaded config is added as the last config. The command should find wild card route and add this lazy loaded route before wild card route

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.3
Node: 10.14.2
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.2
@angular-devkit/build-angular      0.800.2
@angular-devkit/build-ng-packagr   0.800.6
@angular-devkit/build-optimizer    0.800.2
@angular-devkit/build-webpack      0.800.2
@angular-devkit/core               8.0.2
@angular-devkit/schematics         8.3.3
@angular/cdk                       8.0.2
@angular/cli                       8.3.3
@angular/material                  8.0.2
@ngtools/webpack                   8.0.2
@schematics/angular                8.3.3
@schematics/update                 0.803.3
ng-packagr                         5.5.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-09-07 07:32
Duplicate of https://github.com/angular/angular-cli/issues/15255

**Closed by alan-agius4** 2019-09-07 07:32 UTC

**Comment by santoshyadav198613** [comment] 2019-09-07 07:38
Oops my bad , should have verified this, thanks @alan-agius4
