### ISSUE TITLE
Error: Cannot locate bin for temporary package: @angular/cli.

### ISSUE THREAD

**Issue by sergey-morenets** [angular/angular-cli#21011] opened 2021-06-01 12:02 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ x] update

### Is this a regression?

Yes

### Description

We tried to upgrade one of our Angular 11 projects to v12.0.2 but received an error.
That's strange because we've never seen this error during upgrade before. And we could upgrade another Angular 11 project to v 12.0.0 a week ago.

## 🔬 Minimal Reproduction

`ng update @angular/cli @angular/core @angular/material`

## 🔥 Exception or Error

<pre><code>
[error] Error: Cannot locate bin for temporary package: @angular/cli.
    at Object.runTempPackageBin (C:\Users\test\AppData\Roaming\npm\node_modules\@angular\cli\utilities\install-package.js:116:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UpdateCommand.validateAndRun (C:\Users\test\AppData\Roaming\npm\node_modules\@angular\cli\models\command.js:136:22)
    at async Object.runCommand (C:\Users\test\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:205:24)
    at async default_1 (C:\Users\test\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js:70:31)

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.0 (cli-only)
@angular-devkit/core         12.0.0 (cli-only)
@angular-devkit/schematics   12.0.0 (cli-only)
@schematics/angular          12.0.0 (cli-only)

</code></pre>

OS: Windows 10 Pro

**Comment by alan-agius4** [comment] 2021-06-01 12:04
Duplicate of https://github.com/angular/angular-cli/issues/20907

**Closed by alan-agius4** 2021-06-01 12:04 UTC
