### ISSUE TITLE
Error on ng version build and serve

### ISSUE THREAD

**Issue by elioth010** [angular/angular-cli#5555] opened 2017-03-21 23:58 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
`ng --version

                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.28.3
node: 6.9.5
os: linux x64 debian 8 
`
### Repro steps.
`ng build` or `ng serve`

### The log given by the failure.

`Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "undefined".
Error: Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "undefined".
    at Object.<anonymous> (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/@ngtools/webpack/src/index.js:27:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/angular-cli/models/webpack-build-typescript.js:5:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/angular-cli/models/webpack-config.js:2:34)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/angular-cli/tasks/build-webpack.js:6:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/angular-cli/commands/build.js:3:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/angular-cli/addon/index.js:21:16)
    at /home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/angular-cli/angular-cli/lib/models/project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/angular-cli/angular-cli/lib/models/project.js:391:15)
    at Project.eachAddonCommand (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/angular-cli/angular-cli/lib/models/project.js:426:30)
    at module.exports (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/angular-cli/angular-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/angular-cli/angular-cli/lib/cli/cli.js:34:26)
    at tryCatch (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/home/elioth010/Development/Workspaces/ByteWorkspace/ACE/ace/backoffice-ace/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

### Desired functionality.

Start my app and compile the sources.

**Comment by avegpatekar** [comment] 2017-03-22 15:21
Facing same issue...

**Comment by elioth010** [comment] 2017-03-22 15:28
a dirty solution is install as dev depdenency "@ngtools/webpack": "1.2.13", because the latest need the angular-compiler-cli : 2.3.1

**Comment by smiper** [comment] 2017-03-23 13:07
I wonder how to get the cli to use that separate @ngtools/webpack instead? For me it still says it's "undefined" after installing it!

**Comment by filipesilva** [comment] 2017-03-23 21:56
Dupe of https://github.com/angular/angular-cli/issues/5558

**Closed by filipesilva** 2017-03-23 21:56 UTC
