### ISSUE TITLE
After upgrading to latest version of Angular ng build doesn't work 

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#8754] opened 2017-12-06 12:42 UTC
### Versions
```
Angular CLI: 1.6.0-rc.2
Node: 8.9.1
OS: win32 x64
Angular: 5.1.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.0-rc.3
@angular/cli: 1.6.0-rc.2
@angular/flex-layout: 2.0.0-beta.11-b01c2d7
@angular/material: 5.0.0-rc.3
@ngtools/json-schema: 1.1.0
typescript: 2.4.2
webpack: error
```

After upgrading to latest version of Angular ng build doesn't work  and throw below error:

`Cannot find module 'webpack/lib/node/NodeTemplatePlugin'`

**Comment by clydin** [comment] 2017-12-06 13:37
This appears to be a duplicate of https://github.com/angular/angular-cli/issues/8741 and is most likely due to multiple or incorrect webpack versions being installed. Please follow the instructions present in the comments of the linked issue.

**Closed by clydin** 2017-12-06 13:37 UTC
