### ISSUE TITLE
Issue with build optimization

### ISSUE THREAD

**Issue by gs377209** [angular/angular-cli#24537] opened 2023-01-12 17:09 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.0.4

### Description

The build claims to pass, but the optimization step is failing which causes CI/CD pipelines to fail.

```sh
✔ Browser application bundle generation complete.

Error: Optimization error [main.cca9583a96881fb5.js]: SyntaxError: Unexpected token: punc (()
```

### Minimal Reproduction

`ng build` is the only command needed

No new packages were added; only updated angular and TS

Commit with changes that broke the build can be found here:
https://github.com/gs377209/angular-tour-of-heroes-example/commit/3a1de0d74ab8a659c543a7afdb4e5782d078bbd8

### Exception or Error

```text
Error: Optimization error [main.cca9583a96881fb5.js]: SyntaxError: Unexpected token: punc (()
```

### Your Environment

```text
> ng version


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.1.0
Node: 18.12.0
Package Manager: npm 8.19.2
OS: darwin x64

Angular: 15.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.0
@angular-devkit/build-angular   15.1.0
@angular-devkit/core            15.1.0
@angular-devkit/schematics      15.1.0
@angular/fire                   7.5.0
@schematics/angular             15.1.0
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by clydin** [comment] 2023-01-12 17:11
Duplicate of #24526
Fixed in 15.1.1

**Closed by clydin** 2023-01-12 17:11 UTC
