### ISSUE TITLE
1.6.4 SCSS/CSS source maps not working

### ISSUE THREAD

**Issue by smlombardi** [angular/angular-cli#9235] opened 2018-01-16 14:39 UTC
### Versions
```
Angular CLI: 1.6.4
Node: 6.11.2
OS: darwin x64
Angular: undefined
... 
@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.37
@angular-devkit/core: 0.0.24
@angular-devkit/schematics: 0.0.45
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.12
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps
Run project with `ng serve --sourcemaps --extract-css -o --hmr -e=hmr --proxy-config proxy.config.json`

### Observed behavior
Inspecting HTML in DevTools shows all the css is in `styles.bundle.scss`, where it used to display the scss source of the rule. So I can no longer determine where the css rule I am inspecting comes from.

### Desired behavior
This used to work before we updated to 1.6.4 and Angular 5.1.3

**Comment by Stephane-Peyroutet** [comment] 2018-01-16 16:58
I don't know if this is related to your problem but some stuff has been broken regarding scss/css in the 1.6.4 release (see #9185).

**Comment by smlombardi** [comment] 2018-01-16 17:10
I rolled back to 1.6.3, same issue.

**Comment by pdecembre** [comment] 2018-01-16 20:57
I tried to remove the tilda from every @import but that didn't fix the issue.  
@import '~@angular/material/prebuilt-themes/indigo-pink.css'; is breaking with or without the "~". So far the only thing that seem to fix the problem is to rollback, both local devDependencies AND global installation To 1.6.1,  I don't know about others, but rolling back local devDependencies to 1.6.2 or 1.6.3 didn't fix it for me.

**Comment by smlombardi** [comment] 2018-01-17 13:54
Rolled back to 1.6.1 and I *still* am not getting source maps.

**Comment by michael-letcher** [comment] 2018-01-17 15:43
Also related (#9099)

**Comment by hansl** [comment] 2018-01-23 21:32
Closing as duplicate.

**Closed by hansl** 2018-01-23 21:32 UTC
