### ISSUE TITLE
created project folder tree too deep for windows

### ISSUE THREAD

**Issue by aggro80** [angular/angular-cli#1298] opened 2016-07-07 13:19 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 0.1.0
node: 5.4.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Issue is almost the same as it was in #1090, but I'm using node 5, instead of node 3, so the solution provided in that issue does not help. Also you need to have a base path of about 50 characters for the problem to occur.
1. Go to directory: C:\myproject\myproject\subproject\src\main\resources\web
2. Create project: ng new --skip-git myproject
3. Try to delete it and see how it fails

Here is one of the problematic paths:
C:\MYPROJ~1\MYPROJ~1\SUBPRO~1\src\main\web\NODE_M~1\ANGULA~1\NODE_M~1\EMBER-~1\NODE_M~1\BROCCO~1\NODE_M~1\BABEL-~1\NODE_M~1\REGENE~1\NODE_M~1\defs\NODE_M~1\yargs\NODE_M~1\cliui\NODE_M~1\CENTER~1\NODE_M~1\ALIGN-~1\NODE_M~1\kind-of\node_modules\is-buffer

- Problems seem to occur only under node_modules\angular-cli. 
- angular-cli paths are about 200 characters, so your base path needs to be about 50 characters for you to see the problem. If you create the project directly to the C-root, you won't see the problem.
- While the path in this example if invented just for this purpose, this problem happened in real life project (I admit that the project could be structured better, but this is just what real life provides). 

If you can't do anything about the 200 character long path, you could at least warn about this when creating a project or at least mention it in the documentation. But preferred solution would be not to create so long paths.

**Comment by nitro52** [comment] 2016-07-08 06:59
we had this problem with node before. i thought they had fixed it it in node 5, seems like they haven't completely fixed it

http://stackoverflow.com/questions/26155135/node-npm-windows-file-paths-are-too-long-to-install-packages

There are a couple of workarounds for this.I think using the rmdir command is the easiest

> rmdir /S /Q <dir>

**Comment by jkuri** [comment] 2016-07-08 22:17
Thanks @nitro52. @aggro80 did this solves your issue?

**Comment by alexpaluzzi** [comment] 2016-07-11 23:00
I have `rimraf` installed globally for this reason on my Windows boxes. It works great.

`npm i rimraf -g`
`rimraf directory/`

Be careful, of course.

**Comment by aggro80** [comment] 2016-07-13 07:38
Solution 1: Every user does tricks to get around the angular-cli problems.
Solution 2: Users just don't use angular-cli as it is too hard
Solution 3: angular-cli is fixed so that it is easy to use

I have not seen any other package installed by npm to create paths this deep, so I have to assume the problem is somehow related either to angular-cli or the packages it uses. 

I don't have the skills nor time to provide a fix for this issue (to angular-cli), so the best I could do is to bring the issue into your attention. I hope that you can provide a real fix to the angular-cli so that it doesn't create paths so deep.

**Comment by alexpaluzzi** [comment] 2016-07-13 07:42
> I have not seen any other package installed by npm to create paths this deep, so I have to assume the problem is somehow related either to angular-cli or the packages it uses.

This is not an `angular-cli` problem. It's an `npm` and `Windows` problems. Specifically with some of the third-party dependencies.

This problem is not unique to this project in any way. Almost every Yeoman scaffold and seed project I use has `npm` dependencies that break the Windows limit.

**Comment by aggro80** [comment] 2016-07-15 15:45
OK, but even if this problem is not unique to angular-cli, it still exists in angular-cli. If it is caused by a bug in npm, it is OK for me to link this ticket to npm ticket and wait for a fix and once the npm is fixed, this ticket can be closed. 

That being said, this issue should have been fixed already in npm3:
https://docs.npmjs.com/how-npm-works/npm3

It could be that there are still bugs in npm and their planned system does not work(?), but it looks to me, that if angular-cli and all its dependencies would use the same versions of every package, everything should be flat. So simply upgrading some packages that give deepest paths, might give at least some help for this issue.

**Comment by filipesilva** [comment] 2016-07-28 02:32
This issue was caused by a bug in the CLI that caused an older version of npm to be used. It was fixed in https://github.com/angular/angular-cli/pull/1250.

**Closed by filipesilva** 2016-07-28 02:32 UTC
Labels: priority: 2 (required), type: bug
