### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by watzon** [angular/angular-cli#9589] opened 2018-02-10 00:40 UTC
### Versions
```
Angular CLI: 1.6.8
Node: 9.4.0
OS: linux x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
* run `ng help generate`

### Observed behavior
```
➜ ng help generate
Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at Class.getCollectionName (/home/watzon/Projects/Personal/story-time/node_modules/@angular/cli/commands/generate.js:57:36)
    at Class.printDetailedHelp (/home/watzon/Projects/Personal/story-time/node_modules/@angular/cli/commands/generate.js:179:37)
    at commandFiles.forEach.cmd (/home/watzon/Projects/Personal/story-time/node_modules/@angular/cli/commands/help.js:57:38)
    at Array.forEach (<anonymous>)
    at Class.run (/home/watzon/Projects/Personal/story-time/node_modules/@angular/cli/commands/help.js:36:22)
    at resolve (/home/watzon/Projects/Personal/story-time/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (/home/watzon/Projects/Personal/story-time/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/home/watzon/Projects/Personal/story-time/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)
    at <anonymous>

```

### Desired behavior
It should list the command specific help for generate

### Mention any other details that might be useful (optional)
I tracked down the issue to [here](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/commands/generate.ts#L67).

**Comment by Brocco** [comment] 2018-02-12 16:25
Duplicate of #9412

Closing.

**Closed by Brocco** 2018-02-12 16:25 UTC
