### ISSUE TITLE
Please update build-angular's dependency of webpack-dev-server to 3.2.0

### ISSUE THREAD

**Issue by patrickhrastnik** [angular/angular-cli#13723] opened 2019-02-20 15:52 UTC
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...

webpack-dev-server@3.2.0 (indirectly) supports AIX systems (because its dependencies support AIX systems after some changes).
@angular-devkit/build-angular strictly requires webpack-dev-server@3.1.14 - That's why the changes of v3.2.0 are not pulled when installing an angular project via npm.
So I'm not able to install the angular dependencies on the AIX system.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Could you please update the dependency of webpack-dev-server to 3.2.0 so I can use angular on AIX? (or maybe to ^3.2.0 or ~3.2.0?)
It's in `packages/angular_devkit/build-angular/package.json` 
There shouldn't be a problem with build-webpack because this package.json has its dependency to ^3.1.4

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment] 2019-02-21 06:37
Hi, thanks for reporting this.

The reason being why direct dependencies are pinned, is because when a new package is released it might cause regressions and breaks existing users. As a matter of fact `webpack-dev-server` version `3.2.0` has such regression and breaks users that use the ssl option.

See: https://github.com/angular/angular-cli/pull/13728

**Comment by patrickhrastnik** [comment] 2019-02-21 06:56
Hello,
thanks for checking that out.
So, what's the next step (for me to do)?

The reason I'm asking is, I'm currently working on a prototype to evaluate if we can use Angular and/or React on our AIX system. I'd like to know what to tell my boss...

**Comment by alan-agius4** [comment] 2019-02-21 07:34
Blocked by https://github.com/webpack/webpack-dev-server/issues/1674

**Comment by patrickhrastnik** [comment] 2019-02-21 08:48
ok, thanks

**Comment by alan-agius4** [comment] 2019-02-26 16:36
Closed via https://github.com/angular/angular-cli/commit/f2827971976f3317086d5981c33cc6cb9247224e

**Closed by alan-agius4** 2019-02-26 16:36 UTC
Labels: comp: devkit/build-angular, type: feature
