### ISSUE TITLE
angular-cli warning: critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by zhouweiming** [angular/angular-cli#7874] opened 2017-09-29 02:19 UTC
os: win10
node: 8.4

`ng --version`:

![image](https://user-images.githubusercontent.com/4847735/30998097-d36fb72c-a491-11e7-8aac-ac9107462887.png)

use `ng serve` ，get warnings:

![image](https://user-images.githubusercontent.com/4847735/30998126-feab93c0-a491-11e7-9da3-fc2e973867f7.png)

I run same project on mac, get same warning, but when i remove node_modules and reinstall, run project success, please help me.

**Comment by filipesilva** [comment] 2017-10-02 10:43
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/7689. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-10-02 10:43 UTC
Labels: priority: 3 (nice to have), severity2: inconvenient
