### ISSUE TITLE
Non normaly working IE9

### ISSUE THREAD

**Issue by micaz** [angular/angular-cli#5457] opened 2017-03-16 15:24 UTC
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
Output from: `ng --version`.
@angular/cli: 1.0.0-rc.0
node: 6.9.5
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.9

Windows (7)
Browser IE9

### Repro steps.
ng new micaztest
cd micaztest

edit polifills.ts
un comment lines
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

ng serve

### The log given by the failure.
None

### Desired functionality.
Please anyone help me!!

### Mention any other details that might be useful.

This case Happend Only IE9!!

1. Show Just Loading Text
![image](https://cloud.githubusercontent.com/assets/11342456/24002311/bf80ba00-0aa3-11e7-9754-0b5f868d4182.png)

2. What happened Then Turn on The Development mode(F12)
![image](https://cloud.githubusercontent.com/assets/11342456/24002688/b2c20e30-0aa4-11e7-87d8-de403616778a.png)

3. Press F5(Refrish) and WorkFine??
ManyTimes Test And Check
normal mode is not work
Turn on The DevelopMode is work fine 
And It also works when Turn off DevelopMode
![image](https://cloud.githubusercontent.com/assets/11342456/24003969/56caf8c2-0aa8-11e7-8c47-7ca708b3c5f2.png)

Sorry My Bad English
Anyone help me please!!

**Comment by mattdistefano** [comment] 2017-03-16 16:19
IE9 doesn't work properly with `ng serve`. See https://github.com/angular/angular-cli/issues/4772

**Comment by hansl** [comment] 2017-03-16 19:53
Please enable the polyfills for IE9. See the `polyfills.ts` file and read the comments.

**Comment by micaz** [comment] 2017-03-17 01:53
clearly I edited polyfills.ts
lock my First Comment

I know of an error that is caused by a websocket error
The original environment is firebase hosting

Why Turn on Development mode(F12) And Prees F5(Refrish) Work Fine?

**Comment by Meligy** [comment] 2017-03-17 02:27
I'm seeing in a few places that livereload has issues with IE9.

This might be your problem.

Try:

```
ng serve --live-reload=false
```

**Comment by Meligy** [comment] 2017-03-17 02:31
If this is the problem (livereload), there's not much that can be done in the CLI itself.

You can try this extension for IE that seems to make livereload work:
https://github.com/dvdotsenko/livereload_ie_extension

Maybe also start a new issue for adding `liveReload` to the defaults in `.angular-cli.json`.
Even without doing that, if you want livereload always disabled, you can modify the npm `start` script, or add another script that calls the command above.

**Comment by micaz** [comment] 2017-03-17 04:05
**My problem is not livereload**

please check https://test.micaz.net (Firebase hosting)

First Call in IE9
Just "Loading...." Display
And Then PressF5(Refrish) PressF5(Refrish) PressF5(Refrish) same Loading Display

Fianly PressF12(Develoment Mode)
And Then PressF5(Refrish) Text Chagne "app work!"

Why is that happening?

**Comment by filipesilva** [comment] 2017-03-18 15:06
Dupe of https://github.com/angular/angular-cli/issues/4772, tracking it there.

I think it's the same problem because both issues report the error `SCRIPT445` in the screenshot.

**Closed by filipesilva** 2017-03-18 15:06 UTC
