### ISSUE TITLE
Top-level await is not available in the configured target environment ("chrome129.0", "edge129.0", "firefox115.0", "ios17.0", "node22.0.0", "safari17.0" + 5 overrides)

### ISSUE THREAD

**Issue by Gouvernathor** [angular/angular-cli#28896] opened 2024-11-19 18:07 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

This perfectly valid TS syntax does not work, purportedly because of browser-compatibility reasons (according to the error message), despite my project having no browser compatibility requirements.
I have seen the closed issues about this, which are closed for comments. I think they deserve to be reopened (at least one of them).
**_Even aside that_**, I spent a day trying to find where my configuration required browser compatibility constraints ; if that is not the problem, then the error message must be changed to reflect what the actual problem is, so devs can know whether looking into browser constraints is useful or not.

### Minimal Reproduction

```ts
import languageIds from '../assets/langages.json';
export {languageIds};
const translations: Readonly<Record<string, Readonly<Record<string, string>>>> = Object.fromEntries(await Promise.all(
    languageIds.map(async (languageId) => (
        [languageId, await import(`../assets/languages/${languageId}.json`)]
))));
```
With the required JSON files, followed by `ng serve` or `ng build`.

### Exception or Error

```text
X [ERROR] Top-level await is not available in the configured target environment ("chrome129.0", "edge129.0", "firefox115.0", "ios17.0", "node22.0.0", "safari17.0" + 5 overrides)

    src/configuration.ts:5:40:
      5 │ ...slations = Object.fromEntries(await Promise.all(languageIds.map(...
        ╵                                  ~~~~~
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.2.12
Node: 20.18.0
Package Manager: npm 10.9.0
OS: win32 x64

Angular: 18.2.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   18.2.12
@angular-devkit/core            18.2.12
@angular-devkit/schematics      18.2.12
@schematics/angular             18.2.12
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by JeanMeche** [comment] 2024-11-19 18:13
Top level async is only available for zoneless apps.

**Comment by alan-agius4** [comment] 2024-11-19 18:35
Closing as this is working as intended as mentioned above.

**Closed by alan-agius4** 2024-11-19 18:35 UTC

**Comment by JeanMeche** [comment] 2024-11-19 19:01
Zone.js is not compatible with having top-level await.

**Comment by Gouvernathor** [comment] 2024-11-19 19:40
@JeanMeche I understood that. Why is it considered to be an intended feature, as @alan-agius4 said, is my question.
In addition to the error message being incorrect, that is.
