### ISSUE TITLE
Multiple `--configuration` doesn't work on `ng serve`

### ISSUE THREAD

**Issue by dianjuar** [angular/angular-cli#22424] opened 2021-12-23 22:06 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't know

### Description

I want to use the feature of multiple configurations using the `--configuration` on [build](https://angular.io/guide/workspace-config#alternate-build-configurations) and [serve](https://angular.io/cli/serve#ng-serve).

In `ng serve` is not working properly.

## 🔬 Minimal Reproduction

Repo https://github.com/dianjuar/example-serve-multipli-config-bug-ngcli

```json
"build": {
  "configurations": {
    "development": {
      "buildOptimizer": false,
      "optimization": false,
      "vendorChunk": true,
      "extractLicenses": false,
      "sourceMap": true,
      "namedChunks": true
    },
    "local-against-dev": {
      "fileReplacements": [
        {
          "replace": "src/environments/environment.ts",
          "with": "src/environments/environment.local-against-dev.ts"
        }
      ]
    }
  }
},
"serve": {
  "configurations": {
    "development": {
      "browserTarget": "example-serve-multipli-config-bug:build:development"
    },
    "local-against-dev": {
      "browserTarget": "example-serve-multipli-config-bug:build:local-against-dev"
    }
  },
  "defaultConfiguration": "development"
}
```

I tried to serve the application using the _development_ settings defined in my `development` configuration but also I want to apply the configuration of my `local-against-dev` environment. So the command to make this happen would be:

`ng serve --configuration development,local-againts-dev`

The parameter `development` is not being taken into account, is not applying all the configurations that I placed there on the `development` configuration. A way to prove my statement is because no source maps are generated, you can not access the `app.component.ts` file using the chrome dev tools.

## 🔥 Exception or Error

No error is shown

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.2.14
Node: 16.13.1 (Unsupported)
Package Manager: npm 8.1.2
OS: darwin x64

Angular: 12.2.15
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.14
@angular-devkit/build-angular   12.2.14
@angular-devkit/core            12.2.14
@angular-devkit/schematics      12.2.14
@angular/cli                    12.2.14
@schematics/angular             12.2.14
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by dianjuar** [comment] 2022-01-03 18:59
On the [implementation commit](https://github.com/filipesilva/angular-cli/commit/55c169976ca30c53ba6556fc509f3a71efd630bb) I could find another way of accomplishing it using target strings.

```json
"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
  "options": {
    "browserTarget": "latest-project:build:one,two"
  },
  "configurations": {
  "production": {
      "browserTarget": "latest-project:build:production,one,two"
  }
}
```

**Comment by artaommahe** [comment] 2022-01-03 19:44
@dianjuar ng server with comma separated configurations does not actually merge this configs, it just takes values from the last one in the list. We have same issue and have to copy-paste dev config in whole to each custom one to have it work properly

**Comment by dianjuar** [comment] 2022-01-03 22:23
@artaommahe as a workarround you can use target strings on your `ng serve` configuration trough the `browserTarget` property. I found this other way on the [commit message](https://github.com/filipesilva/angular-cli/commit/55c169976ca30c53ba6556fc509f3a71efd630bb) where multiple configuration feature was implemented

This is a good option if your configurations possibilities are static. If they are some how dynamic, it won't work, you would still need to have this bug to be fixed.

I took this workaround, I prefer having a single source of truth rather than having all the configuration repeated across all the possible configurations. That last practice is very error prone in my opinion.

> It's now possible to use multiple configurations by separating them with a comma:
> ```
> ng build --configuration=one,two,three
> ```
> 
> You can also use it in target strings:
> ```
>         "serve": {
>           "builder": "@angular-devkit/build-angular:dev-server",
>           "options": {
>             "browserTarget": "latest-project:build:one,two"
>           },
>           "configurations": {
>             "production": {
>               "browserTarget": "latest-project:build:production,one,two"
>             }
>           }
> ```

**Comment by alan-agius4** [comment] 2022-01-10 09:01
@dianjuar, this is working as intended as configurations are merged from left to right. In the original post you were overriding the `browserTarget` option value to `example-serve-multipli-config-bug:build:local-against-dev`.

Instead of creating additional configurations you can also set `browserTarget` via the command line. 

Example: 
```
 ng build --browser-target latest-project:build:production,one,two
```

Closing as this is working as intended.

**Closed by alan-agius4** 2022-01-10 09:01 UTC
