### ISSUE TITLE
There is an error in browser/schema.d.ts in the @angular-devkit/build-angular@0.7.5 distribution.

### ISSUE THREAD

**Issue by iwe7** [angular/angular-cli#12020] opened 2018-08-28 11:26 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```
@angular-devkit/build-angular/src/browser/schema.d.ts
```ts
 fileReplacements: FileReplacements[];
```
### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

**Comment by alan-agius4** [comment] 2018-08-28 11:37
Thanks for reporting this issue. However, this issue is a duplicate of #11992. Please subscribe to that issue for future updates.

**Comment by alan-agius4** [comment] 2018-08-28 11:38
Please fill in the template with more details. Thanks

**Closed by alan-agius4** 2018-08-28 11:37 UTC

**Comment by iwe7** [comment] 2018-08-28 12:00
fileReplacements: FileReplacements[]; // i think should is FileReplacement[]
