### ISSUE TITLE
Problem with @angular/cli and yarn package manager

### ISSUE THREAD

**Issue by darkoandreev** [angular/angular-cli#18136] opened 2020-07-03 08:36 UTC
Hello everyone,

**Description**
I’m facing with a problem in my Angular lib project and it’s related with the update of `@angular/cli`. I’m trying to upgrade from Angular 9.1 to Angular 10 and I’m using **yarn package manager v1.16.0.**. The update of @angular/core, @angular/cdk 
was successful and the problem appeared when I tried to update the `@angular/cli`.

**Issue**
I got the following error:
![image](https://user-images.githubusercontent.com/20442015/86449372-c8948080-bd20-11ea-929d-557f501bacd2.png)

I just want to mention, that the problem appeared only with the yarn package manager and with the npm I didn't have such kind of a problem. 

The dependencies were updated in the package.json, but they were not installed as you can see in the following screenshot:
![image](https://user-images.githubusercontent.com/20442015/86449605-18734780-bd21-11ea-8d5c-1eaf3a9dcb57.png)

When I try to do `yarn install`, I get the same error:
`error Couldn't find package "acorn@^6.4.1" required by "webpack@4.43.0" on the "npm" registry.`

It will be very nice if you have any suggestions and it will be very helpful. Thanks in advance!

**Comment by alan-agius4** [comment] 2020-07-03 10:14
@darkoandreev, `acorn@^6.4.1` is available on the public npm registry https://www.npmjs.com/package/acorn/v/6.4.1

So this might be something related to your environment. If you are behind an NPM proxy make sure that it's synced with the public NPM registry, you might also be blocked by a firewall or, do have a different registry set for any of your `.yarnrc` or `.npmrc` files.

Using  `yarn install--verbose`, should give you more information.

Closing as it's not caused by the Angular CLI.

**Closed by alan-agius4** 2020-07-03 10:14 UTC
