### ISSUE TITLE
ng g component in folder where currently residing creates component in root

### ISSUE THREAD

**Issue by NilsHolger** [angular/angular-cli#3570] opened 2016-12-15 07:46 UTC
when create a component in currently residing folder, my component is created in root structure:
![ngcli1](https://cloud.githubusercontent.com/assets/7613203/21215609/823f8606-c2a2-11e6-92ac-4fadba08f5f7.PNG)

/c/dev/ng2clienttracker/src/app/clients/components 
ng g component new-cmp
installing component
  create src\app\new-cmp\new-cmp.component.css
  create src\app\new-cmp\new-cmp.component.html
  create src\app\new-cmp\new-cmp.component.spec.ts
  create src\app\new-cmp\new-cmp.component.ts

**Comment by Nikki1993** [comment] 2016-12-15 11:50
Could you fill out issues template to show what kind of version of the CLI you are using etc?

FYI, I am not having this issue on 1.0.0Beta-21 on macOS 10.12.2 with node 7.2.1 npm 4.0.3

**Comment by samiurrahman** [comment] 2016-12-15 13:47
Hello I facing the Same issue while creating new component in specific folder. it only generate in root (app) folder. can any one help.>

**Comment by baruchvlz** [comment] 2016-12-15 17:25
As @Nikki1993 said, please follow the questionnaire provided when opening a new issue. I tried this on MacOSX Sierra and cli 1.0.0.beta.22-1 and it works properly.

<img width="386" alt="screen shot 2016-12-15 at 12 22 12 pm" src="https://cloud.githubusercontent.com/assets/14321495/21234642/77766d60-c2c1-11e6-8201-76fc95ca2e69.png">

**Comment by filipesilva** [comment] 2016-12-30 15:11
This seems windows specific.

**Comment by vtolstov** [comment] 2017-01-01 13:44
No, this is not windows specific. I'm use angular-cli 1.0.0-beta24 and component not created in another component folder, but in root.

**Comment by omahm** [comment] 2017-01-05 21:33
I have this issue in Ubuntu 16.04 and CLI version 1.0.0-beta.24

**Comment by martinstark** [comment] 2017-01-09 15:09
I have this issue on Windows 10, since beta version .23. I'm currently on 1.0.0-beta.24

**Comment by samiurrahman** [comment] 2017-01-12 04:18
@NilsHolger  Here is the Answer.

Consider your project is recipe-book.
first navigate to app folder by

1. cd src
2. cd app

then if you wants to create folder in app then simply type
ng g c test

it will create in app folder
now you wants to create component inside of test then type
ng g c test/test2
it will create new component in test folder. see below pic


![newcoponent](https://cloud.githubusercontent.com/assets/7039896/21876764/f19905bc-d8ab-11e6-93c7-ca223d1ea9fa.png)

**Comment by Brocco** [comment] 2017-01-15 03:27
I have just tried to recreate this issue unsuccessfully, closing this issue as it cannot be reproduced, if you're still having the issue, please comment and we will re-evaluate.

Here is a screen-grab of my attempt to recreate. (with version 1.0.0-beta.25.5)

![image](https://cloud.githubusercontent.com/assets/1565117/21960034/540e109a-daa8-11e6-85d7-96eed38acb83.png)

**Closed by Brocco** 2017-01-15 03:27 UTC
Labels: command: generate, priority: 2 (required), type: bug

**Comment by tchelidze** [comment] 2018-01-17 07:32
- Navigate at root of your project (`test-app` in this case)
- issue command `ng g c parentfolder/componentname` (`ng g c form-test/form-test-child` in this case)

![image](https://user-images.githubusercontent.com/10682707/35030786-33dea9c2-fb15-11e7-80e7-f38c3a002079.png)

Result 

![image](https://user-images.githubusercontent.com/10682707/35030870-7f7d0158-fb15-11e7-89d7-841bca8f2e1b.png)

**Comment by sipolyashhivangi** [comment] 2018-11-06 20:11
I do not want app folder, I want if I run ng g c test then test folder will generate in src
 
ex:
ng g c test
it will generate in "src/app/test"
I do not want app folder here I want test folder is in src.

please suggest

**Comment by thescientist13** [comment] 2018-12-12 23:40
I think maybe lost in this thread was a question about how to specific the output directory of the `generate` command.

For example, right now it will always prefix the path with _app/_.
```
$ ./node_modules/.bin/ng generate component component/navigation
CREATE src/app/component/navigation/navigation.component.scss (0 bytes)
CREATE src/app/component/navigation/navigation.component.html (29 bytes)
CREATE src/app/component/navigation/navigation.component.spec.ts (656 bytes)
CREATE src/app/component/navigation/navigation.component.ts (346 bytes)
```

Would be great to get the result, but without _app/_.

Is this possible through _angular.json_ or CLI?
