### ISSUE TITLE
RangeError: Maximum call stack size exceeded when build library

### ISSUE THREAD

**Issue by kukubadze** [angular/angular-cli#14774] opened 2019-06-14 09:07 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
no proplem in 7.2.0

### Description

error on bulding library with export class with static property

## 🔬 Minimal Reproduction

- ng new tst

- ng generate library my-lib

- insert in MyLibModule new class:
<pre><code>
export class Constants {
  public static ItemType='Item'.toLowerCase();
}
</code></pre>
- ng build my-lib
## 🔥 Exception or Error
<pre><code>
ng build my-lib
Building Angular Package
Building entry point 'my-lib'
Compiling TypeScript sources through ngc

BUILD ERROR
Maximum call stack size exceeded
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at isPrimitive (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:610:25)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:406:17)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)
    at MetadataBundler.convertValue (D:\Net\Pag.Mes.Io\src\Pag.Mes.Io\tst\tst\node_modules\@angular\compiler-cli\src\metadata\bundler.js:422:36)

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.0.2
Node: 11.8.0
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.2
@angular-devkit/build-angular      0.800.2
@angular-devkit/build-ng-packagr   0.800.2
@angular-devkit/build-optimizer    0.800.2
@angular-devkit/build-webpack      0.800.2
@angular-devkit/core               8.0.2
@angular-devkit/schematics         8.0.2
@angular/cli                       8.0.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.2
@schematics/angular                8.0.2
@schematics/update                 0.800.2
ng-packagr                         5.3.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-06-14 10:50
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1093

**Closed by alan-agius4** 2019-06-14 10:50 UTC

**Comment by florian-kittel** [comment] 2019-06-19 12:08
@kukubadze I had the same problem with ng-packagr > 5 -> I moved back to version 4.7.1.

**Comment by florian-kittel** [comment] 2019-06-19 12:53
@alan-agius4 Seem ng-update updatest ng-packager since cli version > 8.0.1 to version 5.3.0.

**Comment by niceilm** [comment] 2019-07-30 11:52
I have same issue. cli version 8.1.3 version 5.4.3
