### ISSUE TITLE
in angular-cli V 6.1  where is the webpack.config.js

### ISSUE THREAD

**Issue by fuzitu** [angular/angular-cli#10864] opened 2018-05-15 08:04 UTC
![_20180515160134](https://user-images.githubusercontent.com/25705181/40044237-635c16de-5859-11e8-9fd4-9c4e56532cdb.png)
![_20180515160157](https://user-images.githubusercontent.com/25705181/40044238-63b3a1ce-5859-11e8-90f3-fc43a59d274a.png)
I try ng eject it not work,how can i let it recognition *.ttf ,
thanks!!

**Comment by phl3x0r** [comment] 2018-05-15 14:45
Do you mean 6.0.1?
In any case, ng eject has been temporarily disabled in ~6.0.0
https://github.com/angular/angular-cli/issues/10618

**Comment by Brocco** [comment] 2018-05-15 17:12
Closing...
Duplicate of #10618

**Closed by Brocco** 2018-05-15 17:12 UTC

**Comment by fuzitu** [comment] 2018-05-24 10:15
how can i use .ttf.woff
