### ISSUE TITLE
npm run build don't generate production build by default

### ISSUE THREAD

**Issue by sinedied** [angular/angular-cli#17651] opened 2020-05-06 13:51 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No

### Description

 A clear and concise description of the problem...
I'm surprised nobody already reported that, but I could not find a similar issue searching through history.

By default, apps generated with `ng new` have an `npm run build` script that translates to `ng build`, so it's not building a production-ready version a one would expect.

Why not make the default build script use the `--prod` option, so we get production-ready build by default? For instance, React, Vue and Svelte all create a production build with their default `npm run build` command.

I would gladly propose a PR to fix that, but that seems so obvious that surely you may had some reasons for not doing so all this time?

Thanks for considering that 🙂 

## 🔬 Minimal Reproduction

1. `ng new` 😄 

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.1
Node: 12.13.0
OS: darwin x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment] 2020-05-06 13:58
Duplicate of #14471

**Closed by clydin** 2020-05-06 13:58 UTC

**Comment by sinedied** [comment] 2020-05-06 15:51
@clydin while it's related, I don't see it as duplicate issue. The one you linked ask about making `ng build` do production builds by default, which has breaking changes implications, while it's not what I am suggesting here.

Here I am merely suggesting changing the default template generated by `ng new`, so it would not involve breaking changes as only new projects would be affected.

**Comment by clydin** [comment] 2020-05-06 17:50
The suggested change is actually mentioned in the first comment of the referenced issue (https://github.com/angular/angular-cli/issues/14471#issuecomment-493870955).  It was previously made and then reverted.

The change also has farther reaching effects into areas such as online tutorials (including video) and both online and offline teaching material.  This is a change that the team is definitely interested in making, however, there is a large amount of coordination that needs to be planned to ensure a smooth transition for all stakeholders.

**Comment by sinedied** [comment] 2020-05-07 07:51
Oops my bad, missed that one!
Thanks for giving some context. Still sad that the change made it but was reverted because of single complaint (on GH at least), though I understand the rationale here.
I hope it can find its way to v10, keep up the good job 👍
