### ISSUE TITLE
Improved Reporting File Grouping (E5 and ES2015)

### ISSUE THREAD

**Issue by apiweb** [angular/angular-cli#19344] opened 2020-11-12 01:39 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
I think it would be interesting if the output of Angular, displayed the total size of the files grouped in three categories: ES5, ES2015 and Total.
That way we could get an idea of how the file size for each category ES5 and ES2015 was.

### Describe the solution you'd like
![image](https://user-images.githubusercontent.com/5881027/98884413-b238c700-246e-11eb-89e8-de72098a12ca.png)

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment] 2020-11-12 06:35
Duplicate of https://github.com/angular/angular-cli/issues/19330

**Closed by alan-agius4** 2020-11-12 06:35 UTC
