### ISSUE TITLE
Error when serving angular-cli beta 15 project.

### ISSUE THREAD

**Issue by Xamlware** [angular/angular-cli#2335] opened 2016-09-24 22:56 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10, Visual STudio code.

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I originally created the app with angular-cli beta 10 and have now been trying to upgrade to latest for a week.  I have install angular-cli globally and locally, and cleared the cache.  I npm installed everything and installed typings.  I ng build an everything builds fine.  I ng serve and all is well until it tries to load the app.  I'm getting:

 "SCRIPT438: Object doesn't support property or method 'match'"
main.bundle.js (19707,5)
which is this method:

/**
 * Splits a URI into its component parts.
 *
 * Each component can be accessed via the component indices; for example:
 * <pre>
 * goog.uri.utils.split(someStr)[goog.uri.utils.CompontentIndex.QUERY_DATA];
 * </pre>
 *
 * @param uri The URI string to examine.
 * @return Each component still URI-encoded.
 *     Each component that is present will contain the encoded value, whereas
 *     components that are not present will be undefined or empty, depending
 *     on the browser's regular expression implementation.  Never null, since
 *     arbitrary strings may still look like path names.
 */
function _split(uri) {
    return uri.match(_splitRe);
}

I set a breakpoint and the uri is 381.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
no log is generated that I can find.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-10-05 14:30
Dupe of https://github.com/angular/angular-cli/issues/1910

**Closed by filipesilva** 2016-10-05 14:30 UTC
