### ISSUE TITLE
There is no a command that can set detection strategy to OnPush by default with `ng new`

### ISSUE THREAD

**Issue by RayKimEX** [angular/angular-cli#15447] opened 2019-08-27 02:13 UTC
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
There is no a command that can set detection strategy to OnPush by default with `ng new`

### Describe the solution you'd like
Add a additional parameters like --style=scss that can set detection strategy to OnPush by default with 'ng new' in CLI

### Describe alternatives you've considered
There is Alternatives.
ng config schematics.@schematics/angular.component.changeDetection OnPush

But I want to set detection strategy with `ng new` like --style=scss
I think this is worthy

Thank you for reading

**Comment by alan-agius4** [comment] 2019-08-27 04:33
Duplicate of https://github.com/angular/angular-cli/issues/13327

**Closed by alan-agius4** 2019-08-27 04:33 UTC

**Comment by RayKimEX** [comment] 2019-08-27 05:39
> Duplicate of #13327

You said in #13327 that `ng new` creates only single component, and it would be trivial to change the change detection for the root compoenent

But what i want is including `ng config` feature.

When you create with `ng new` with --style=scss
then it sets

```
        "@schematics/angular:component": {
          "styleext": "scss",

          // this is what i want feature with 'ng new' command and parameter
          "changeDetection" : "OnPush"
        },
```

Could you explain for me why `ng new` with--style=scss is accepted,
but `ng new` with like changeDetection='OnPush' can not be accepted?

this would not be trivial. 
Because when you create `ng generate`. it sets by default

**Comment by alan-agius4** [comment] 2019-08-27 09:59
The `style` option controls more than just a single component style. The option is used to generate the global style sheet extension and configures the styles option under the browser and test builder.

`ng new` only exposes a subset of options from the component schematic. Ex `viewEncapsulation`, `selector`, `skipSelector` and other as not exposed.

If you want to use `ng generate component` and always set the `changeDetection`  to `OnPush`  you will need to run the above mentioned command after `ng new`. (Note: it won't update existing components)
