### ISSUE TITLE
webpack config node miss

### ISSUE THREAD

**Issue by BennieMeng** [angular/angular-cli#11458] opened 2018-07-05 10:45 UTC
Module not found: Error: Can't resolve 'fs' in '/home/mengqingyun/iserver/src/frontend/node_modules/yamljs/lib'.
when i run my product on dev model, i find this issue.
so we add this to your config:
node: {
      fs: "empty"
}.
but with  lastest version of angular-cli@6.0.7. i can't find entry to add this config.
under is part of my angular.json:
"serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "frontend:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "frontend:build:production"
            }
          }
        }

so i try to read resource fo  @angular-devkit/build-angular .
[browser](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts), find node is  false.

if change to fs: “empty”. problem is solved.
alse i find other config file all set node like [webpack.config.common.js](https://github.com/angular/angular-cli/blob/44086c60ff1d6c26d30850bef125120f6c498ac1/tests/%40angular_devkit/build_optimizer/webpack/simple-app/webpack.config.common.js)
node: {
    fs: 'empty',
    global: true,
    crypto: 'empty',
    tls: 'empty',
    net: 'empty',
    process: true,
    module: false,
    clearImmediate: false,
    setImmediate: false
  }

**Comment by Plysepter** [comment] 2018-07-05 21:02
I am experiencing this issue as well and I hope it can be resolved but I also believe that this might be a duplicate of this issue here: https://github.com/angular/angular-cli/issues/10681

**Comment by filipesilva** [comment] 2018-07-19 13:10
I'm sorry to say but this is expected behaviour. You can read more about why we disabled these imports in https://github.com/angular/angular-cli/issues/9827.

**Closed by filipesilva** 2018-07-19 13:10 UTC

**Comment by BennieMeng** [comment] 2018-07-25 12:06
@filipesilva  i get it because of  environment . but i'd like to find an entry to write config like setting node config. i not find it in scema.json page. can you help me where override webpack config. thank you~

**Comment by liuxh0** [comment] 2018-08-14 07:50
Hi @filipesilva , I can understand why node modules are disabled. But most of npm packages those import or require nodejs modules don't work any more. Do you have a workaround?

**Comment by Plysepter** [comment] 2018-08-15 16:32
@liuxh0 while not an official solution you can try this package (not mine) https://github.com/meltedspark/angular-cli-builders. It allows you to extend the angular cli webpack config. You take the risk of future updates being incompatible but gain the ability to obtain the flexibility you are looking for. The Angular CLI team has been fantastic about making the cli modular and this package takes advantage of this.

**Comment by liuxh0** [comment] 2018-08-16 07:57
@Plysepter Thanks for your advice. I've solved by problem by adding `browser` field in `package.json`. But I still hope Angular lets user modify webpack config, just like `tsconfig.json` and `tslint.json`.
