### ISSUE TITLE
Remove unused CSS via with PurgeCSS

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#24851] opened 2023-03-14 18:31 UTC
### Command

build

### Description

It would be nice if Angular had the ability to remove unused CSS with something like [PurgeCSS](https://purgecss.com/).  

This way when designing a themed app we can include all the component theme styles with `mat.all-component-themes`, and possibly add other styles (Bootstrap, Materialize, etc.) and whatever the application does not use angular can strip out.

### Describe the solution you'd like

I believe the CLI already integrates with PostCSS, so there may be other options.

There's an article discussing the approach here:
https://dev.to/dylanvdmerwe/reduce-angular-style-size-using-purgecss-to-remove-unused-styles-3b2k

The only thing is that Angular will add classes dynamically to component elements as the application state changes, and tools like PurgeCSS will strip the styles for classes that are added at runtime and not declared at design time.

So if Angular does integrate tooling for this it would need to create a **white-list** for classes that should not be stripped.

### Describe alternatives you've considered

There are "Manual" approaches to stripping unused CSS, but all of them are quite tedious and error prone ...

**Comment by alan-agius4** [comment] 2023-03-14 19:06
Duplicate of https://github.com/angular/angular-cli/issues/22809

**Closed by alan-agius4** 2023-03-14 19:06 UTC
