### ISSUE TITLE
Ng serve fails with Angular CLI version 9.1.4 and Angular version 9.1.5

### ISSUE THREAD

**Issue by lamim50** [angular/angular-cli#17674] opened 2020-05-08 15:37 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular CLI version 9.1.4 and Angular version 9.1.4

### Description

I recently installed node version 12.16.3 LTS, then Angular CLI using the command `npm install -g @angular/cli`. Then I created a new project with the command `ng new myProject`.
These steps installed CLI version 9.1.4 and Angular version 9.1.5. After the installation, I tried to launche the project wih the command `ng serve` and get the error bellow.

## 🔥 Exception or Error
<pre><code>

> test@0.0.0 start C:\Users\Public\workspace\test
> ng serve

Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/animations/browser/testing : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 676 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 12.7 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2020-05-08T15:28:59.528Z - Hash: ce7b123bfb39e55c84dd - Time: 6563ms

ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:65165:24)
    at C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (C:\Users\Public\workspace\test\node_modules\typescript\lib\typescript.js:98688:20)
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.4
Node: 12.16.3
OS: win32 x64

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by EatonZ** [comment] 2020-05-08 15:40
+1 getting this too.
I assume because the CLI is stuck in [build-limbo again](https://github.com/angular/angular-cli/issues/17495).

**Comment by petebacondarwin** [comment] 2020-05-08 15:54
> I assume because the CLI is stuck in build-limbo again.

Not correct. There is a regression in the Framework that we are working on resolving. See https://github.com/angular/angular/issues/36992#issuecomment-625856812

**Comment by petebacondarwin** [comment] 2020-05-08 15:54
Please follow along at that issue.

**Closed by petebacondarwin** 2020-05-08 15:54 UTC
