### ISSUE TITLE
Cli 8.0.0-beta.5 cannot do a production build if enableIvy is set

### ISSUE THREAD

**Issue by jmesa-sistel** [angular/angular-cli#13849] opened 2019-03-07 12:50 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

 
I get  the error:
> ERROR in Unable to write a reference to AppComponent in ....

When I run ng build in a enableIvy project

## 🔥 Exception or Error
<pre>ERROR in Unable to write a reference to AppComponent in D:/web/testangular8/src/app/app.component.ts from D:/web/testangular8/src/app/app.module.ts<code>

</code></pre>
ng new testangular8Ivy --enableIvy
cd testangular8Ivy
ng build

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.0.0-beta.5
Node: 10.11.0
OS: win32 x64
Angular: 8.0.0-beta.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.14.0-beta.5
@angular-devkit/build-angular     0.14.0-beta.5
@angular-devkit/build-optimizer   0.14.0-beta.5
@angular-devkit/build-webpack     0.14.0-beta.5
@angular-devkit/core              8.0.0-beta.5
@angular-devkit/schematics        8.0.0-beta.5
@angular/cli                      8.0.0-beta.5
@ngtools/webpack                  8.0.0-beta.5
@schematics/angular               8.0.0-beta.5
@schematics/update                0.14.0-beta.5
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.6
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-03-07 13:46
Duplicate of https://github.com/angular/angular/issues/29140 and being addressed in https://github.com/angular/angular-cli/pull/13848 and https://github.com/angular/angular/pull/29151

**Closed** 2019-03-08 00:02 UTC
Labels: comp: core & compiler, comp: ngtools/webpack, freq2: medium, severity5: regression, type: bug/fix
