### ISSUE TITLE
node_modules\ngx-http-rest\index.ts is not part of the compilation output. Please check the other error messages for details.

### ISSUE THREAD

**Issue by thatisuday** [angular/angular-cli#8406] opened 2017-11-08 17:04 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```sh
Angular CLI: 1.5.0
Node: 7.10.0
OS: win32 x64
Angular: 5.0.0

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.
1. npm install ngx-http-rest
2. add `import { HttpRestModule } from 'ngx-http-rest';` to module.ts
3. import `HttpRestModule` in `imports` section of module class

### The log given by the failure.
```
ERROR in ./node_modules/ngx-http-rest/index.ts
Module build failed: Error: C:\Users\Uday\git-repos\thatisuday.github.io\ngx-ig-demo\node_modules\ngx-http-rest\index.ts is not part of the compilation outp
ut. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Uday\git-repos\thatisuday.github.io\ngx-ig-demo\node_modules\@ngtools\webpack\src\angular_compiler_pl
ugin.js:629:23)
    at plugin.done.then (C:\Users\Uday\git-repos\thatisuday.github.io\ngx-ig-demo\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/app.module.ts 11:0-47
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

### Desired functionality.
Normally, angular app should compile. 

### Mention any other details that might be useful.
This is problem doesn't occur with `ngx-http-rest` package but all packages made for Angular 4. For example, `ngx-image-gallery` package made by me have exact same problem.

**Comment by JulioWar** [comment] 2017-11-09 01:42
Check the issue #8284. This issue is related to that.

**Comment by himajaM** [comment] 2017-11-17 11:54
ERROR in ./node_modules/ngx-uploader/src/classes/index.ts
Module build failed: Error: D:\demo\node_modules\ngx-uploader\src\classes\index.ts is not part of the compilation output. Please check the other error messages for details.
at AngularCompilerPlugin.getCompiledFile (D:\rndtc\rndtc\node_modules@ngtools\webpack\src\angular_compiler_plugin.js:624:23)
at plugin.done.then (D:\rndtc\rndtc\node_modules@ngtools\webpack\src\loader.js:467:39)
at process._tickCallback (internal/process/next_tick.js:103:7)
@ ./node_modules/ngx-uploader/ngx-uploader.js 6:0-86
@ ./src/app/modules/consult/consult-job/consult-job.module.ts
@ ./src/$$_lazy_route_resource lazy
@ ./node_modules//esm5/core.js
@ ./src/main.ts
@ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

Solution for my above error pls !!!!!!!

**Angular CLI: 1.5.2
Node: 7.4.0
OS: win32 x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

: 1.5.2
: 2.0.0-5d0e199
: 0.0.33
: 0.0.20
: 0.0.36
: 1.1.0
: 1.8.2
: 0.1.5
typescript: 2.4.2
webpack: 3.8.1**

**Comment by thatisuday** [comment] 2017-11-17 11:58
This error is related to Angular CLI 1.5. Please check issues on Angular 5
and Angular CLI projects on GitHub.

**Comment by himajaM** [comment] 2017-11-17 11:59
Thank you.. Il check it.

**Comment by filipesilva** [comment] 2017-12-07 14:57
This issue is a duplicate of https://github.com/angular/angular-cli/issues/8284. Please read the comments on that issue to better understand what is happening. https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325 is a specially relevant comment.

**Closed by filipesilva** 2017-12-07 14:57 UTC
