### ISSUE TITLE
ERR_IPC_CHANNEL_CLOSED error in version 1.5.0

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular-cli#8349] opened 2017-11-04 18:47 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0
Node: 8.9.0
OS: win32 ia32
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1

```

### Repro steps.

ng serve
after few watch the error throws

### The log given by the failure.
```
ERROR in Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at AngularCompilerPlugin._updateForkedTypeChecker (C:\Users\Sheik Althaf\Documents\angular\butterfly\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:370:34)
    at Promise.resolve.then (C:\Users\Sheik Althaf\Documents\angular\butterfly\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:208:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Desired functionality.
Ruined the develpment. fix the bug asap

### Mention any other details that might be useful.
this bug makes unable to work. I tried uninstall and reinstall node and cli but still problem exist.
I think cli have error with node version 8+.

**Comment by CramericaIndustries** [comment] 2017-11-04 19:08
Duplicate of #8331

**Comment by Brocco** [comment] 2017-11-13 18:33
Closing as a Duplicate of #8331

**Closed by Brocco** 2017-11-13 18:33 UTC
