### ISSUE TITLE
browser-esbuild can't resolve secondary entry point from library

### ISSUE THREAD

**Issue by LeonEck** [angular/angular-cli#24434] opened 2022-12-14 12:06 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I wanted to try the new esbuild based browser builder in a project that contains a library. That library is split into secondary entry points (similar to the [ng-packagr secondary sample](https://github.com/ng-packagr/ng-packagr/tree/main/integration/samples/secondary)). When I try to run `ng build` it produces an error saying it can not resolve the secondary entry points.

### Minimal Reproduction

I created a reproduction here: https://github.com/LeonEck/esbuild-library-secondary
The project contains a newly generated angular project. Afterwards (second commit) I generated a new library. In the third commit I added a secondary entry point to the library. Finally I switched the builder to "browser-esbuild".

### Exception or Error

When you run `ng build my-lib` followed by `ng build` it produces the following error:

```text

✘ [ERROR] Could not resolve "my-lib/secondary"

    src/main.ts:3:29:
      3 │ import { logSomething } from "my-lib/secondary";
        ╵                              ~~~~~~~~~~~~~~~~~~

  You can mark the path "my-lib/secondary" as external to exclude it from the bundle, which will remove this error.
```

### Your Environment

```text
Angular CLI: 15.0.3
Node: 18.12.1
Package Manager: npm 9.1.2
OS: darwin x64

Angular: 15.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.3
@angular-devkit/build-angular   15.0.3
@angular-devkit/core            15.0.3
@angular-devkit/schematics      15.0.3
@schematics/angular             15.0.3
ng-packagr                      15.0.3
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by gmfun** [comment] 2023-05-12 08:17
The issue is there in v16.0.1 as well.

**Comment by atsjo** [comment] 2023-09-26 13:46
Ran into the same problem with nx and incremental builds, didn't know incremental builds was supported using just angular cli... Apparently this is still present in 16.2.6, but I could work around it by just using esbuild without incremental builds in nx...

**Comment by neodescis** [comment] 2023-10-13 17:23
Just ran into this myself. Any chance this will be fixed in Angular 17? Otherwise the move to esbuild seems like a non-starter.

**Closed** 2023-10-26 11:02 UTC
Labels: type: bug/fix, freq1: low, severity3: broken, area: devkit/build-angular, devkit/build-angular:application
