### ISSUE TITLE
Cannot find module 'shared' when building a nested project that imports a shared library

### ISSUE THREAD

**Issue by christofferfleat** [angular/angular-cli#14208] opened 2019-04-18 11:41 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Not sure.

### Description
I'm trying to implement Universal with a project structure like:

```
workspace
  projects
    foo
    shared
      lib
       shared.service.ts
      public_api.ts <!-- this exports the shared.service.ts
  src
  ...
```

I ran `ng add @nguniversal/express-engine --clientProject foo` standing in workspace and it added all the files it should. Here's where I stumbled upon two issues:

1. Running `npm run build:ssr && npm run serve:ssr` directly after the previous command results in it building the workspace project instead of `projects/foo` which was specified as the `--clientProject`.

I changed the following line:

```
"build:client-and-server-bundles": "ng build --prod && ng run foo:server:production"
```

To:

```
"build:client-and-server-bundles": "ng build foo --prod && ng run foo:server:production"
```

And it builds the correct project, **this should be default behaviour shouldn't it?**

2. In the `foo` project I'm importing things from `shared`, but these imports doesn't work when I run `npm run build:ssr && npm run serve:ssr`. All I get is:

```
projects/foo/src/app/app.component.ts(3,34): error TS2307: Cannot find module 'shared'.
```

This is strange to me since the library works great when just serving the `foo` project normally.

## 🔬 Minimal Reproduction

Repo found here: https://github.com/chrillewoodz/universal-library-repro

```
$ ng new workspace
$ cd workspace
$ ng generate application foo
$ ng add @nguniversal/express-engine --clientProject foo
$ ng generate library shared
$ ng build shared
```

Add `import {SharedService} from 'shared';` to `projects/foo/src/app/app.component.ts`.

Change `package.json` line 14 to:

`"build:client-and-server-bundles": "ng build foo --prod && ng run foo:server:production"`

Run `npm run build:ssr && npm run serve:ssr`.

## 🔥 Exception or Error
<pre><code>
ERROR in projects/foo/src/app/app.component.ts(3,29): error TS2307: Cannot find module 'shared'.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.0.7
Node: 8.12.0
OS: darwin x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.7
@angular-devkit/build-angular      0.10.7
@angular-devkit/build-ng-packagr   0.10.7
@angular-devkit/build-optimizer    0.10.7
@angular-devkit/build-webpack      0.10.7
@angular-devkit/core               7.0.7
@angular-devkit/schematics         7.0.7
@angular/cli                       7.0.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.7
@schematics/angular                7.0.7
@schematics/update                 0.10.7
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.19.1
</code></pre>

**Comment by alan-agius4** [comment] 2019-04-18 16:19
Duplicate of https://github.com/angular/angular-cli/issues/13935

You need to remove the `baseUrl` from the server tsconfig
https://github.com/chrillewoodz/universal-library-repro/blob/master/projects/foo/tsconfig.server.json#L5

**Closed by alan-agius4** 2019-04-18 16:19 UTC
