### ISSUE TITLE
ng serve --watch is not watching for code changes

### ISSUE THREAD

**Issue by davidrdz93** [angular/angular-cli#8313] opened 2017-11-02 19:32 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.9
node: 8.9.0
os: linux x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
typescript: 2.3.4

### Repro steps.

ng serve --port 8080 --watch

### The log given by the failure.

The development server is not reloading when changes are made on the code.. 
It only compiles and serves the project.

I don't know what other information can I supply in order to explain better myself!

**Comment by deebloo** [comment] 2017-11-02 19:38
@davidrdz93 can you provide a sample project with this issue? also ```ng serve``` should do livereload without the --watch flag. can you try with that flag?

**Comment by davidrdz93** [comment] 2017-11-02 19:50
I am trying without the --watch flag but it is not working.. Last night I tried reinstalling webpack and It worked for a while! I don't know how to provide a sample project, however let me know if there are another ways to give you more info! Thanks!

**Comment by davidrdz93** [comment] 2017-11-02 19:52
I don't know if there is something in my environment because in my other PC it is livereloading nice!

**Comment by davidrdz93** [comment] 2017-11-06 18:33
I am just realizing that using ng serve with sudo is making it work properly

**Comment by scottasmith** [comment] 2018-02-02 22:38
Hi all,
This may help if it is the same problem I had.
Trying to use `ng serve` and `ng build --watch` sometimes worked but mostly they were not watching for code changes and I thought it was something to do with `ng`.

Then I remembered a problem I had a while back with
[inotify watches](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers)

I ran this on my Ubuntu machine and it seems to have kicked in and watching code changes:
```
echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/40-max-user-watches.conf && sudo sysctl --system
```

Hope it helps

**Comment by ilovett** [comment] 2018-02-06 21:45
Thanks @scottasmith increasing max watches on ubuntu worked for me

**Comment by Paulskit** [comment] 2018-02-08 18:11
@davidrdz93 try this: https://github.com/angular/angular-cli/issues/9275#issuecomment-360186355
Helped my solve the same issue.

**Comment by tommueller** [comment] 2018-02-27 15:25
For me this also changed from one day to the other, also running the the `ng serve` as root fixes the problem for me ... I ran an `apt upgrade` on my Debian 9 maschine today, that updated this packages:

```
Start-Date: 2018-02-27  09:03:50
Upgrade: libsystemd0:amd64 (236-3~bpo9+1, 237-3~bpo9+1), geoip-database:amd64 (20171107-1~bpo9+1, 20180215-1~bpo9+1), google-chrome-stable:amd64 (64.0.3282.140-1, 64.0.3282.186-1), udev:amd64 (236-3~bpo9+1, 237$
End-Date: 2018-02-27  09:04:10
```

Maybe that is of any help?!

**Comment by quirogamauricio** [comment] 2018-07-24 15:10
@scottasmith 's solution worked for me as well. Thank you.

**Comment by udbhav1995** [comment] 2018-08-14 12:51
@scottasmith 's solution worked for me as well for angular angular  1.6.3

**Comment by mmohammad-pk** [comment] 2018-09-20 12:18
@scottasmith Thanks. It worked for me as well.

**Comment by nikhilbhalwankar** [comment] 2019-03-31 18:38
> Hi all,
> This may help if it is the same problem I had.
> Trying to use `ng serve` and `ng build --watch` sometimes worked but mostly they were not watching for code changes and I thought it was something to do with `ng`.
> 
> Then I remembered a problem I had a while back with
> [inotify watches](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers)
> 
> I ran this on my Ubuntu machine and it seems to have kicked in and watching code changes:
> 
> ```
> echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/40-max-user-watches.conf && sudo sysctl --system
> ```
> Hope it helps

Thanks a ton. This worked for me like a charm on Ubuntu 18.04 LTS !

**Comment by oranjos9** [comment] 2019-08-19 16:48
watch is not watching for code changes i am using windows

**Comment by mgechev** [comment] 2019-08-19 19:54
@oranjos9 what's your Angular CLI version?

**Comment by perceptron007** [comment] 2019-08-22 06:44
@mgechev It's not working for me, I haven't installed it globally but only at Project Level

Angular CLI Version: 8.1.1
OS: Windows
I also tried adding a poll option to angular.json configuration and it also doesn't seem to work.

**Comment by bmsekni** [comment] 2019-08-22 12:55
same here
I tried with Angular CLI Version: 8.0.2 & 8.2.2
OS: Windows

**Comment by mgechev** [comment] 2019-08-22 17:54
Not sure if that's a problem in the CLI. Happy to see that there's a workaround for linux, but this also makes me thing that the issue is related to permissions or other OS-level configuration.

With the limited information we have here, I don't think there's anything more we can do. I'm closing for now, please comment or open a new issue if you have more insights or you're able to consistently reproduce the problem.

**Closed by mgechev** 2019-08-22 17:54 UTC
Labels: need: more info
