### ISSUE TITLE
Inconsistency between ng serve and ng build when using Node.js built-ins

### ISSUE THREAD

**Issue by Deku-nattsu** [angular/angular-cli#29077] opened 2024-12-06 18:44 UTC
### Command

serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

19.0.2

### Description

After updating the angular cli to 19.0.4, i can no longer serve my project, the issue comes from the usage of pdfjs-dist that includes usage of nodejs build-ins. however i am able to build successfully which contradicts with the goal fc41f50

My expecation is a workaround this build blocking error (probably through the compiler configuration) and the consistency of errors between serving and build.

### Minimal Reproduction

1. create a new angular project
2. install any library that uses nodejs build-ins in my case pdfjs-dist@4.6.82
3. try to serve/build

here's the repo to reproduce it: https://github.com/Deku-nattsu/nodejs-build-ins-error
stackblitz: https://stackblitz.com/~/github.com/Deku-nattsu/nodejs-build-ins-error

### Exception or Error

```text
when serving:

 [ERROR] The package "url" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]

    node_modules/pdfjs-dist/build/pdf.mjs:5666:48:
      5666 │       url = await import(/*webpackIgnore: true*/"url");
           ╵                                                 ~~~~~

✘ [ERROR] The package "fs" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]

    node_modules/pdfjs-dist/build/pdf.mjs:5663:51:
      5663 │     const fs = await import(/*webpackIgnore: true*/"fs"),
           ╵                                                    ~~~~

✘ [ERROR] The package "http" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]

    node_modules/pdfjs-dist/build/pdf.mjs:5664:49:
      5664 │       http = await import(/*webpackIgnore: true*/"http"),
           ╵                                                  ~~~~~~

✘ [ERROR] The package "https" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]

    node_modules/pdfjs-dist/build/pdf.mjs:5665:50:
      5665 │       https = await import(/*webpackIgnore: true*/"https"),
           ╵                                                   ~~~~~~~
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 19.0.4
Node: 20.15.1
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 19.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.4
@angular-devkit/build-angular   19.0.4
@angular-devkit/core            19.0.4
@angular-devkit/schematics      19.0.4
@angular/cli                    19.0.4
@schematics/angular             19.0.4
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by pumano** [comment] 2024-12-06 19:46
got same problems with `falso` library after [commit](https://github.com/angular/angular-cli/commit/fc41f50b53bbffead017b420105eed5bd8573ac1) landed to 19.0.4. I create issue: https://github.com/ngneat/falso/issues/386

Looks like `seedrandom` library under the hood properly handle what to use, for nodejs uses `require('crypto')` while in browser use window global for crypto get randomBytes.

**Comment by isoroka-plana** [comment] 2024-12-08 10:07
I also started getting this issue after updating to `19.0.4` from Angular 18.
```
X [ERROR]
The package "util" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]
    node_modules/idmission-web-sdk/dist/sdk2.esm.js:6447:24:
      6447 │     this.util = require('util');
           ╵                         ~~~~~~
X [ERROR] The package "fs" wasn't found on the file system but is built into node.
[plugin angular-browser-node-built-in]
    node_modules/@tensorflow/tfjs-data/dist/sources/file_data_source.js:43:25:
      43 │       const fs = require('fs');
         ╵                          ~~~~
X [ERROR] The package "string_decoder" wasn't found on the file system but is built into node.
[plugin angular-browser-node-built-in]
    node_modules/@tensorflow/tfjs-data/dist/util/deep_map.js:217:16:
      217 │     } = require('string_decoder');
          ╵                 ~~~~~~~~~~~~~~~~
X [ERROR] The package "crypto" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]
    node_modules/seedrandom/seedrandom.js:265:27:
      265 │       nodecrypto = require('crypto');
```

It used to work without any issues before and I inspected the code of these packages they all check what environment they are running in before running those `require` calls so the build shouldn't try to attempt to bundle them for the browser.
I am using `@angular-devkit/build-angular:browser-esbuild`. 
I can confirm this issue is gone when downgrading to `19.0.3`.

**Comment by eoussama** [comment] 2024-12-08 21:13
bump

**Comment by ngadceser** [comment] 2024-12-09 06:13
"only 19.0.4 --- I'm currently just observing since the same error occurred with `nodecrypto = require('crypto');` above."

**Closed** 2024-12-09 16:11 UTC
Labels: type: bug/fix, freq1: low, severity5: regression, devkit/build-angular:dev-server, area: @angular/build

**Comment by Deku-nattsu** [comment] 2024-12-09 16:22
@alan-agius4 Thanks :)

**Comment by x-etienne** [comment] 2024-12-12 05:59
bump
