### ISSUE TITLE
ng g c with non-default flags throws error

### ISSUE THREAD

**Issue by goelinsights** [angular/angular-cli#11797] opened 2018-08-07 05:28 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
"@angular/cli": "6.1.1",
    "@ngrx/schematics": "5.2.0",
    "@nrwl/schematics": "6.1.1",

### Repro steps
ng g c -is -it component-name
(trying to generate component without InlineStyle or inlineTemplate). In Angular.json, these are set as default: true, which may be causing the problem (in which case is there a better way to set the defaults that allow them to be overriden?)

Can generate component without flags (ng g c component-name)

Schematics default setting at end of angular.json 

```
"schematics": {
    "@nrwl/schematics:component": {
      "styleext": "scss",
      "spec": true,
      "flat": true,
      "changeDetection": "OnPush"
    }
  }
```

Is this a nx issue vs a cli issue?

### The log given by the failure
Schematic input does not validate against the Schema: {"inlineStyle":true,"inlineTemplate":true,"i":[true,true],"path":"/apps/admin/src/app/corporate/containers","styleext":"scss","spec":true,"flat":true,"changeDetection":"OnPush","skipImport":false,"export":false,"entryComponent":false}
Errors:

  Data path "" should NOT have additional properties(i).

### Desired functionality
should be able to generate a component different than the default setting using flags like -it and -is

**Comment by hansl** [comment] 2018-09-27 14:09
This seems to be a bug with Nrwl. I was not able to reproduce it using our schematics. Are they using 

Please note that `-it` and `-is` are not the proper flags anymore. You seem to want `-t` and `-s`, respectively. We changed the semantics of a single dash back in 6.0, and changed the aliases that weren't correct. Now there's no single dash double letter shortcuts, they're all single letters.

Closing this as working as intended.

Cheers!

**Closed by hansl** 2018-09-27 14:09 UTC
Labels: comp: schematics/angular
