### ISSUE TITLE
When install angular cli stuck

### ISSUE THREAD

**Issue by lyminster** [angular/angular-cli#1214] opened 2016-06-26 15:38 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**windows 10**

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
**node version v6.2.2**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

when i try to install angular cli in my computer i keep stuck on 

> loadRequestedDeps ->netw  | #######---------------------------------

and not going any where,
i'm running the command prompt in  administrator already

and i'm already try this step
```
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest
```

**Comment by filipesilva** [comment] 2016-07-04 01:07
Is this still happening? It sounds like an npm issue.

**Comment by lyminster** [comment] 2016-07-04 09:12
thanks @fillipesilva for your response,

now it can but i must wait like 6 or more hours to install,
and when im going for ng new "my project name"
i cant install from from package.json

**Comment by burhan** [comment] 2016-07-05 11:28
This sounds like a problem with your network connection / Internet.

**Comment by robertwalsh0** [comment] 2016-07-05 13:15
After upgrading to the latest version `angular-cli: 1.0.0-beta.9` I'm having the same problem when running `npm install`

![](https://www.evernote.com/l/AA6beoIkAx1KFrbUjjKbiYKh2R-kiueshrQB/image.png)

**Comment by samuba** [comment] 2016-07-05 13:48
same problem here after upgrading to beta.9

**Comment by robertwalsh0** [comment] 2016-07-05 14:04
Update: I ran the install again 3 times and the third time my npm install went through.

**Comment by jshamley** [comment] 2016-07-07 14:33
I am having the same problems. This has been happening for the last 2 days now. No local network issues, everything else is working fine including other npm installs. My install sticks at the same place as @robertwalsh0 `loadRequestedDeps → netwo` and it just hangs for hours.

**Comment by lyminster** [comment] 2016-07-08 07:38
@burhan i think so, but after i check it , i still can install npm from another package

just angular cli i can't install,

any idea?

**Comment by jshamley** [comment] 2016-07-08 13:52
According to this issue, the Angular CLI requires Node v6 https://github.com/angular/angular-cli/issues/1046 - after updating to v6 I was able to install the CLI. There is some discussion if the CLI should in fact require Node v6, but this fixed the problem for me.

**Comment by zhhb** [comment] 2016-07-15 09:12
I has the same problem. Just I solve it as using git clone this project to local , and run npm install && npm link

**Comment by filipesilva** [comment] 2016-07-28 02:13
Really weird... we test on clean copies of node5 and node6, and I've never seen it have any problems like this. I don't have an answer for you but am leaving the issue open in case some one does.

**Comment by trickpattyFH20** [comment] 2016-07-31 03:03
I'm getting the same issue. I'm on an AWS linux env. node 6.3, npm install just hangs on the `extract:` steps, sometimes it stays hung there and sometimes it exits without completing and without any error messages.

**Comment by xmas** [comment] 2016-08-24 18:41
I had the same issue (node version 5.7 on OS X, installed via homebrew). Uninstalled the homebrew version, installed node 6.x. Angular CLI installed in seconds. Maybe something with the homebrew node build?

**Comment by rspenc29** [comment] 2016-08-30 18:56
I'm having the same issue. I'm on arch linux so it's not homebrew related.

**Comment by xmas** [comment] 2016-08-30 19:12
@rspenc29 Reading lots of different threads leads me to believe this is simply an issue of not using the approved Node(6+)/npm(3+) versions.

**Comment by rspenc29** [comment] 2016-08-30 19:15
```
➜  ~ node --version
v6.5.0
➜  ~ npm --version
3.10.6
```

**Comment by bargepole** [comment] 2016-09-16 08:16
this works on arch-linux using node 6.3.1, node 6.4.0, 6.5.0, 6.6.0 error out: 

λ cd angular.dalawa/                                                            node
λ node -v                                                             angular.dalawa
v6.6.0
λ nvm use 6.3.1                                                       angular.dalawa
Now using node v6.3.1 (npm v3.10.3)
λ git clone --quiet https://github.com/angular/angular-cli            angular.dalawa
λ cd angular-cli/                                                     angular.dalawa
λ touch .install.log.vim                                          master angular-cli
λ sudo npm install --save --loglevel=silent > /dev/null 2> .install.log.vim &
Job 3, “sudo npm install --save --logle…” has ended
λ touch .install.logLink.vim                                      master angular-cli
λ sudo npm link --loglevel=silent > /dev/null 2> .install.logLink.vim &

**Comment by albertodominguezs** [comment] 2016-10-18 14:56
Angular-CLI does nothing when it is called. I tried several times to reinstall the cli and even other node modules - also tried a clean installation. None of the NG commands work (not even --version)

I found that "SUDO" command makes it work, but I does not sound good to me.

Output when running ng command with sudo:

angular-cli: 1.0.0-beta.15
node: 6.8.1
os: darwin x64

**Comment by filipesilva** [comment] 2016-10-23 14:06
Closing as old and because original poster never came back to the issue. There are other problems in this thread, but if you're still having them please open new issues.

@albertodominguezs see https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Closed by filipesilva** 2016-10-23 14:06 UTC
Labels: flag: help wanted, type: question/support

**Comment by albertodominguezs** [comment] 2016-10-23 14:24
Silva, 

1. I do have **Node** installed **Homebrew**.
2. I change the permissions based on the instructions you shared - didn't work.

Is there any way I can get debug level log or something to identify the problem? It is clear it is a permissions issue, but not sure where the problem is.

**Comment by karnavkumar** [comment] 2017-05-29 09:17
$ npm install -g @angular/cli
C:\Users\Kv\AppData\Roaming\npm\ng -> C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng

> node-sass@4.5.3 install C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-51_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-51_binding.node":

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.3 postinstall C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\vendor\win32-x64-51\binding.node
Testing binary
Binary has a problem: Error: %1 is not a valid Win32 application.
\\?\C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\vendor\win32-x64-51\binding.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
Building the binary locally
Building: C:\Program Files\nodejs\node.exe C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Kv\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.1
gyp info using node@7.7.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:114:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:114:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:114:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:114:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kv\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass
gyp ERR! node -v v7.7.4
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules\@angular\cli\node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! path C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\globule\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir

npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\globule\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\Users\Kv\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\globule\node_modules'
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\Users\\Kv\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\globule\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Kv\Desktop\npm-debug.log

**Comment by vamshi9666** [comment] 2018-02-27 16:48
i used yarn . then it shows everything is up to date . but there is still an issue in modules
