### ISSUE TITLE
Inline SCSS styles truncated

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#3542] opened 2016-12-13 15:24 UTC
### OS:
OSX

### Versions:
angular-cli: 1.0.0-beta.22-1
node: 6.3.1
os: darwin x64

### Repro steps:
1. Convert repo to scss
1. Import bootstrap into styles.scss with `@import "../node_modules/bootstrap/scss/bootstrap-flex";`
1. Button styles get applied but column styles are not being applied.  Looking at the inline import it appears cutoff. Maybe there is a line limit on the imported styles?

### Note: 
When importing the `.scss` file in the `angular-cli.json` file via the styles attribute the issue still persists. However switching to the compiled css file in `../node_modules/bootstrap/css/bootstrap-flex.min.css` "fixes it" 

Here is the demo repo: https://github.com/zackarychapple/bootstrap-ng2

**Comment by zackarychapple** [comment] 2016-12-13 15:36
Looks to be the same / similar issue as #3500

**Comment by hansl** [comment] 2016-12-15 20:10
Dupe of #3500

**Closed by hansl** 2016-12-15 20:10 UTC

**Comment by zackarychapple** [comment] 2016-12-16 09:33
@hansl while this is similar it is broken behavior, can we possibly bump the priority for https://github.com/angular/angular-cli/issues/3500 to not be `nice to have`
