### ISSUE TITLE
6.0.0-rc.2 cannot create new project

### ISSUE THREAD

**Issue by vamsivarikuti** [angular/angular-cli#10237] opened 2018-04-09 06:42 UTC
### Versions
Angular CLI: 6.0.0-rc.2
Node: 8.10.0
OS: darwin x64
Angular:

macOS (High Sierra)

### Repro steps

```ng new ng-hnpwa --routing -sw -sc --hmr --style=scss -p=hn```

### Observed behavior
```
name.split is not a function
TypeError: name.split is not a function
    at NodeModulesEngineHost._resolveCollectionPath (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:55:18)
    at NodeModulesEngineHost.createCollectionDescription (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:106:27)
    at SchematicEngine._createCollectionDescription (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:78:40)
    at SchematicEngine.createCollection (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:71:43)
    at Object.getCollection (/usr/local/lib/node_modules/@angular/cli/utilities/schematics.js:28:31)
    at NewCommand.getOptions (/usr/local/lib/node_modules/@angular/cli/models/schematic-command.js:173:41)
    at NewCommand.initialize (/usr/local/lib/node_modules/@angular/cli/commands/new.js:48:21)
    at /usr/local/lib/node_modules/@angular/cli/models/command-runner.js:57:23
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@angular/cli/models/command-runner.js:4:58)

```

### Desired behavior

Expect to generate new project as it does using version 1.7.4

**Comment by lambidu** [comment] 2018-04-09 08:33
Same error here.
It looks like it's caused by GIT repository initialization

@vamsivarikuti you can add `-sg` or `--skip-git` until fix come.
worked for me :)

**Comment by filipesilva** [comment] 2018-04-09 13:09
This issue is a duplicate of https://github.com/angular/angular-cli/issues/10206. We have it fixed on master for the next release and there is also a workaround in that issue.

**Closed by filipesilva** 2018-04-09 13:09 UTC
