### ISSUE TITLE
Multiple Module warnings with latest Angular-CLI

### ISSUE THREAD

**Issue by jtsom** [angular/angular-cli#2070] opened 2016-09-12 15:02 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10
Powershell and cmd.exe command lines

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

```
angular-cli: local (v1.0.0-beta.11-webpack.8, branch: master)                                               
node: 6.5.0                                                                                                 
os: win32 x64 
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Using the latest Master version of A-Cli, create a new test project:

`ng new a2testing --link-cli`

Start the project, making no code changes:
`ng serve`

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Webpack warnings in the terminal window and also the browser debugger console:

```
WARNING in (webpack)/buildin/module.js                                                                      
There are multiple modules with names that only differ in casing.                                           
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.               
Use equal casing. Compare these module identifiers:                                                         
* C:\Code\angular-cli\node_modules\webpack\buildin\module.js                                                
    Used by 1 module(s), i. e.                                                                              
    C:\Code\ng2testing\node_modules\rxjs\util\root.js                                                       
* C:\code\angular-cli\node_modules\webpack\buildin\module.js                                                
    Used by 2 module(s), i. e.                                                                              
    C:\code\angular-cli\node_modules\punycode\punycode.js
```

5. Mention any other details that might be useful.

**Comment by filipesilva** [comment] 2016-09-20 02:26
Dupe of https://github.com/angular/angular-cli/issues/1702

**Closed by filipesilva** 2016-09-20 02:26 UTC
