### ISSUE TITLE
Locale is not added to `--deployUrl` flag when using `--localize`

### ISSUE THREAD

**Issue by marcinowski** [angular/angular-cli#17737] opened 2020-05-15 16:08 UTC
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No

### Description
I'm implementing the `--localize` flag in our application build. We are serving our assets from a CDN, and so far we were building separate applications with `--locale=..` which was working fine, because we knew the locale and we could just specify `--deployUrl=https://cdn.com/assets/${locale}`.
However now moving to `--localize` flag I can't do that anymore, because there's a single build for all locales.

#### Actual problem
Since `locale` is actually added to the `--baseHref=/assets/` forming
```html
<href base="/assets/${locale}">
```  
then I would almost expect the same thing to happen with `--deployUrl` because I don't know that suffix a priori. 

#### Alternative solution
Another solution is constructing that path like
```
deployUrl + baseHref + locale + asset/path
```
And in that case running 
```sh
$ ng build --baseHref=/assets/ --deployUrl=https://cdn.com/ --localize
```
would return the proper localized asset path with the cdn

#### What I'm running
So currently my `ng build` looks like
```sh
$ ng build --baseHref=/assets/ --deployUrl=https://cdn.com/assets/ --localize
```
and while `baseHref` works fine, the `deployUrl` points at (for example) https://cdn.com/assets/main.js instead of https://cdn.com/assets/${locale}/main.js which ends up as HTTP 404.
For the record in `app.module.ts` I have
```ts
{ provide: APP_BASE_HREF, useValue: '/' }
```

#### Similar issues
I was reading some other issues and probably the closest one was https://github.com/angular/angular-cli/issues/16625
but we can't grep/replace the assets because of our PWA configuration and hash checking the assets.
So is my approach wrong here? or is it actually a bug?

## 🔬 Minimal Reproduction
https://github.com/marcinowski/ng-build-localize-issue
`$ yarn build --baseHref=/assets/ --deployUrl=https://cdn.com/assets/ --localize`

## 🔥 Exception or Error
```
$ ng build --baseHref=/assets/ --deployUrl=https://cdn.com/assets/ --localize
$ head -6 assets/en/index.html 
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <base href="/assets/en/">

$ tail -2 assets/en/index.html
<script src="https://www.cdn.com/assets/runtime.f95efe4dfa0fd0cf523c.js" defer>
```

## 🌍 Your Environment
<pre><code>

$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.5
Node: 12.16.0
OS: linux x64

Angular: 9.1.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.1.1
@angular/cli                      9.0.5
@angular/material                 9.1.1
@ngtools/webpack                  9.0.3
@nguniversal/builders             9.1.0
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
    
Done in 0.45s.
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-05-18 11:31
Duplicate of https://github.com/angular/angular-cli/issues/16558

**Closed by alan-agius4** 2020-05-18 11:31 UTC
Labels: comp: devkit/build-angular

**Comment by marcinowski** [comment] 2020-05-18 12:08
> Duplicate of #16558

Hold on, I don't want to configure different `deployUrls` per locale, I think that's what angular should be doing by default really, that's why I think it's a bug, not a feature request.
I can't really toggle the parameters there, as explained in the issue you've linked, setting `baseHref` to `https://cdn.com` causes all the urls end to up as `https://myapp.com/https://cdn.com/assets/main.js`.

Also in that project I've attached as a minimal reproduction you can check how is the `deployUrl` actually used in the `dist/` directory it appears that it's only
```
$ ag 'localhost' --js
fr/runtime-es5.js
140:/******/ 	__webpack_require__.p = "http://localhost:4200/assets/";

en/runtime-es5.js
140:/******/ 	__webpack_require__.p = "http://localhost:4200/assets/";

fr/runtime-es2015.js
140:/******/ 	__webpack_require__.p = "http://localhost:4200/assets/";

en/runtime-es2015.js
140:/******/ 	__webpack_require__.p = "http://localhost:4200/assets/";

```

and in index.html
```
$ ag -c 'localhost' --html
fr/index.html:10
en/index.html:10
```
so is it really that deeply embedded?

And of course, if there's no solution to it then at least the documentation should clearly state that
it's not possible to use `--deployUrl` with `--localize` flag. There seems to be quite a lot of confusion online with regards to `baseHref`/`deployUrl`/`APP_BASE_HREF` and I can see why.

**Comment by marcinowski** [comment] 2020-05-20 11:26
> Duplicate of #16558

Bump @alan-agius4 can you please let me know what you think about the comment above

**Comment by laurentgoudet** [comment] 2020-05-25 14:56
> Also in that project I've attached as a minimal reproduction you can check how is the `deployUrl` actually used in the `dist/` directory it appears that it's only
> 
> ```
> $ ag 'localhost' --js
> fr/runtime-es5.js
> 140:/******/ 	__webpack_require__.p = "http://localhost:4200/assets/";
> 
> en/runtime-es5.js
> 140:/******/ 	__webpack_require__.p = "http://localhost:4200/assets/";
> 
> fr/runtime-es2015.js
> 140:/******/ 	__webpack_require__.p = "http://localhost:4200/assets/";
> 
> en/runtime-es2015.js
> 140:/******/ 	__webpack_require__.p = "http://localhost:4200/assets/";
> ```
> 
> and in index.html
> 
> ```
> $ ag -c 'localhost' --html
> fr/index.html:10
> en/index.html:10
> ```
> 
> so is it really that deeply embedded?

AFAIK in addition of being used to set Webpack's [publicPath](https://webpack.js.org/guides/public-path/) as above, `deployUrl` is also used by the `PostcssCliResources` plugin which rewrites the CSS assets (`background` images), i.e. it's going to be embedded into each & every lazy-loaded chunks (which has a template with a `background` image).

However, this is arguably not much far worst as `$localize()` itself, which is already embedded everywhere, yet still being replaced as part of the new `--localize` logic. While this isn't exactly the same as the component styles are strings (no AST), so processing them would be a bit hacky, IMO there's nothing strictly preventing `--localize` to work with `--deployUrl`.

Interestingly (I think?) the Angular CLI itself does not support for the localization of assets (images..) yet, so in theory `--deployUrl` could work with `--localize` just by rewriting Webpack's `publicPath` when post processing the bundles (and not override the existing `baseHref` in that case) - assuming the same thing can be done with Bazel.

I do agree that using `--baseHref` is cleaner/nicer, but it also has limitations that many real-life projects unfortunately have to deal with (assets served from a cookie-less domain, legacy AngularJS code on the page relying on a specific `baseHref`..), hence why it would be great `--localize` & `--deployUrl` could play nice together.

**Comment by alan-agius4** [comment] 2020-05-26 09:51
Hi, sorry for my late reply.

>Hold on, I don't want to configure different deployUrls per locale,

Essentially that's what you want to do, you one a different deploy url for each locale in the format. `http://cdn.com/<local-id>`. Unlike the base HREF, which is only present in a static `index.html`, deploy URL, is deeply emended in JS bundles, stylesheets, source-maps etc.. 

This making it impractical to change the deploy URL for each locale without another build. So, if you need to have a different deploy url for each locale an individual build per locale is required.

Thus, where possible it is recommended to use the base HREF instead of the deploy URL. See: https://github.com/angular/angular-cli/blob/master/docs/design/deployurl-basehref.md

With regards to using CDNs, I would recommend a different strategy, were you front the entire application with a CDN and not solely used to serve the assets. In your case this would also a remove the need of configuring the deploy URL.

**Comment by laurentgoudet** [comment] 2020-05-26 12:13
> Unlike the base HREF, which is only present in a static `index.html`, deploy URL, is deeply emended in JS bundles, stylesheets, source-maps etc..
> 
> This making it impractical to change the deploy URL for each locale without another build. So, if you need to have a different deploy url for each locale an individual build per locale is required.

Swapping the `deployUrl` post build is still fairly similar as swapping the `$localize()` calls though, as in those are embedded everywhere as well (right?), yet the CLI still handles them without requiring individual builds per locale (anymore).

> With regards to using CDNs, I would recommend a different strategy, were you front the entire application with a CDN and not solely used to serve the assets. In your case this would also a remove the need of configuring the deploy URL.

While this is true, oftentimes real-life projects have to deal with other constrains, e.g.:
- Fronting the entire app could have a non-negligible cost depending on the traffic, especially when the Angular app is only a portion of the content served from the domain
- Legacy (pre HTTP/2) architectures with cookie-less domains & domain sharding
- ccTLDs support with a shared static domain, as otherwise changing domain cache-bust all the assets

For instance browsing popular names on www.madewithangular.com, Delta airlines uses content.delta.com, and I think a couple of Google's properties are still using www.gstatic.com.

> Thus, where possible it is recommended to use the base HREF instead of the deploy URL.

A major issue with setting the base HREF is that it impacts things outside the app itself, which is problematic in hybrid stacks where the Angular SPA has to coexist alongside other technologies. For instance if our case we inject pieces of the app into legacy PHP pages, themselves already running lots of frontend code, so changing the base HREF of the document is not feasible.

AFAIK setting a base HREF also impacts anchor links (`<a href="#anchor">`) which can oftentimes be problematic depending on the site complexity, e.g. dynamically injected markup, server-side generated templates...

**Comment by alan-agius4** [comment] 2020-05-26 13:26
> Swapping the deployUrl post build is still fairly similar as swapping the $localize() calls though, as in those are embedded everywhere as well (right?), yet the CLI still handles them without requiring individual builds per locale (anymore).

Since, localize is only present in JS, while deployUrl is spread among different type of files, the former it simpler. That said, replacing `$localize()` is far from trivial and there is a special package that does this which is `@angular/localize`.

> While this is true, oftentimes real-life projects have to deal with other constrains... For instance browsing popular names on www.madewithangular.com, Delta airlines uses content.delta.com, and I think a couple of Google's properties are still using www.gstatic.com.


That is true indeed, but to begin with deployUrl, wasn't intended to be used for CDNs. It just happens to work. From the info I have this option was introduced because of `ngUpgrade` story where old AngularJS apps may not work with different baseHrefs.

> AFAIK setting a base HREF also impacts anchor links which can oftentimes be problematic depending on the site complexity, e.g. dynamically injected markup, server-side generated templates...

This is indeed correct, base href does effect anchors.

So to sum everything it;
- If you want to use a CDN only for your resources you can use deployUrl.
- if you also want to use localization + CDN for resources, you need to build the application once for every locale.
- If you want to use localization and build your application once, you need to go with a different CDN approach.
