### ISSUE TITLE
Resolve typescript paths when compiling libraries

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#16383] opened 2019-12-07 08:28 UTC
If we setup the typescript `paths` option for libraries the libraries get compiled without resolving the paths.  For example if we declared a path like this:

```
      "@app/*": ["projects/my-lib/src/lib/*"] 

```

And build.  The compiled fesm2015 will look like this:

```
import { Test } from '@app/test';

```
I have been using typescript transform paths for this in the past, but I was hoping Angular Library support would have it baked in.  

https://www.npmjs.com/package/typescript-transform-paths

**Comment by alan-agius4** [comment] 2019-12-07 08:47
Duplicate of https://github.com/angular/angular-cli/issues/16367

**Closed by alan-agius4** 2019-12-07 08:47 UTC
