### ISSUE TITLE
'ng new project_name' always creates project in ~/ directory, regardless of where the command is run

### ISSUE THREAD

**Issue by xingped** [angular/angular-cli#1375] opened 2016-07-18 22:54 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OS X 10.11.5 (El Capitan)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

node: 6.2.0
angular-cli: 1.0.0-beta.9

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

run 'ng new project_name' in any directory and the project is always created in ~/

4. The log given by the failure. Normally this include a stack trace and some
   more information.

No failure message other than the following:

(node:2520) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-07-28 03:29
Dupe of https://github.com/angular/angular-cli/issues/1079

**Closed by filipesilva** 2016-07-28 03:29 UTC

**Comment by amazingandyyy** [comment] 2016-08-01 04:00
I have issue!!!!
how to fix this? 

@filipesilva 
Close this means what? in 1079 i didn't see a solution...

**Comment by filipesilva** [comment] 2016-08-10 16:30
@amazingandyyy see https://github.com/angular/angular-cli/issues/1045#issuecomment-225319582
