### ISSUE TITLE
Generate component as SCAM

### ISSUE THREAD

**Issue by wizardnet972** [angular/angular-cli#21574] opened 2021-08-14 06:48 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem or missing capability...
It would be nice to create a component as Single (CPD) Angular Module (SCAM) using the cli as built-in functionality.

### Describe the solution you'd like

 If you have a solution in mind, please describe it.
I think about passing a flag to create a component like `--scam` and the cli will generate as [ngneat/scam library](https://github.com/ngneat/scam) does.

[Angular Revisited: Tree-shakable Components and Optional NgModules by Lars Gyrup Brink Nielsen](https://www.youtube.com/watch?v=DA3efofhpq4)

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment] 2021-08-14 07:16
Duplicate of https://github.com/angular/angular-cli/issues/21053

**Closed by alan-agius4** 2021-08-14 07:16 UTC
