### ISSUE TITLE
Update from 6 to 7, the 'dist' root directory got bloated after 'ng build --prod'

### ISSUE THREAD

**Issue by Teamop** [angular/angular-cli#12731] opened 2018-10-24 11:27 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

angular-cli 7.0.2

### Repro steps

I'm using `ag-grid` and `ag-grid-angular` with `angular-cli`, and I also need to do some customization for the theme so I need to do that with scss file provided by the `ag-grid`.
With CLI v6, the dist folder like this:
![image](https://user-images.githubusercontent.com/8519685/47423833-a6f79d80-d7b8-11e8-86cc-9ea15a083a46.png)
After I updated to v7, like this(just part):
![image](https://user-images.githubusercontent.com/8519685/47423878-ca224d00-d7b8-11e8-8106-9abe4a261119.png)

Here, we can see the SVG files are all in the root directory. 
Then I did some research, there SVG files are required in the ag-grid style, but before in the v6, they are all got inlined. But with v7, they are all just individual files. I believe this change is #12267. And based on this change, **these files now are in the right place**. But compared with the 6 version, seems a little messy.
 

### Desired functionality

These SVG files should be in a sub folder, like 'dist/images/xx'

### Mention any other details that might be useful

Maybe related to #6315

**Comment by alan-agius4** [comment] 2018-10-24 11:38
Indeed this is by design that SVG are no longer inlined.

I am going to close this in favor of #6315 to move assets into sub-directories.

**Closed by alan-agius4** 2018-10-24 11:38 UTC

**Comment by bampakoa** [comment] 2018-11-12 11:05
I have experienced the same issue but with PNG files that are referenced inside vendor CSS files such as 

`background-image: url("../img/remove-icon-small.png")`

In my case, I do not use any of these so the **dist** directory is bloated with unnecessary files. I understand that this is by design but are you planning to provide a workaround or should I stick to remove them using a custom automation?
