### ISSUE TITLE
An error occurred during installation

### ISSUE THREAD

**Issue by 283397898** [angular/angular-cli#23840] opened 2022-09-01 07:22 UTC
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### After I entered the installation command on my terminal, the following error occurred
```
$ npm install -g @angular/cli                   ok | base py | 16.17.0 node | 14:44:44 
```
###  The following error occurred
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/architect@0.1402.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Minimal Reproduction

npm install -g @angular/cli

### Exception or Error

```text
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/architect@0.1402.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Your Environment

```text
The default version
```

### Anything else relevant?

macOS
node 16.17.0

**Comment by alan-agius4** [comment] 2022-09-01 07:56
Hi, 

`@angular-devkit/architect@0.1402.1` is available on the public NPM registry. 

See: https://unpkg.com/browse/@angular-devkit/architect@0.1402.1/ and https://www.npmjs.com/package/@angular-devkit/architect

If you are behind a corporate NPM proxy make sure that it's synced correctly.  

Closing as this issue not an issue caused by the Angular CLI.

**Closed by alan-agius4** 2022-09-01 07:56 UTC
