### ISSUE TITLE
feature request: generators can generate where we want them to

### ISSUE THREAD

**Issue by wbhob** [angular/angular-cli#6105] opened 2017-04-27 15:19 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

```
@angular/cli: 1.0.0
node: 6.9.4
os: darwin x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/platform-server: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2
```

### Desired functionality.

Ionic has great generators that generate into a directory that is relevant to what you are generating. For example, 'pages' go into the pages directory, pipes go into their own directory, and providers go into their own directory. The Angular CLI currently puts everything into the app directory, which can be extremely disorganized for larger projects. Please consider a generation tree like this one:
```
src
    - app
        - app.module.ts
        - app.component.ts
        - app.component.html
        - app.component.(s)css
    - components
        - comp-name
            - comp-name.component.ts
            - comp-name.component.html
            - comp-name.component.(s)css
    - pipes
        - pipes.module.ts
        - pipe-name
            - pipe-name.pipe.ts
            - pipe-name.pipe.spec.ts
    - providers
        - providers.module.ts
        - provider-name
            - provider-name.provider.ts
            - provider-name.provider.spec.ts

```

### Mention any other details that might be useful.

https://www.github.com/driftyco/ionic-cli

**Comment by clydin** [comment] 2017-04-27 15:28
The CLI follows the [style guide](https://angular.io/styleguide) which emphasizes a directory hierarchy based on features.  This lends itself directly to the [Angular module concept](https://angular.io/docs/ts/latest/guide/ngmodule.html) wherein an application is a hierarchy of reusable (and potentially lazy loaded) modules.

**Comment by delasteve** [comment] 2017-04-27 15:41
Also, this is essentially a dupe of https://github.com/angular/angular-cli/issues/5995

**Comment by sumitarora** [comment] 2017-04-27 15:45
Closing as above being track on https://github.com/angular/angular-cli/issues/5995

**Closed by sumitarora** 2017-04-27 15:45 UTC
