### ISSUE TITLE
Facing a Problem in ng serve for a my new admin template

### ISSUE THREAD

**Issue by sagargithubuser** [angular/angular-cli#24178] opened 2022-11-03 10:31 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have purchased angular admin template but during setup of template I am getting following error:

./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i5.BsDropdownModule to symbol

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i5.BsDropdownModule to symbol

:heavy_multiplication_x: Failed to compile.

### Minimal Reproduction

ng serve

### Exception or Error

```text
./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i5.BsDropdownModule to symbol

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i5.BsDropdownModule to symbol
```

### Your Environment

```text
My versions are:
Angular CLI: 14.2.7
Node: 14.20.1
Package Manager: npm 8.19.2
OS: linux x64
```

### Anything else relevant?

./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i5.BsDropdownModule to symbol

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i5.BsDropdownModule to symbol

:heavy_multiplication_x: Failed to compile.

**Comment by alan-agius4** [comment] 2022-11-03 10:38
Hi @sagargithubuser, 

This looks like an issue with the purchased templated. Likely you have some missing dependency installed.  I suggest you contact the author of your purchased template to assist you. 

Closing as this is not caused by Angular.

**Closed by alan-agius4** 2022-11-03 10:38 UTC

**Comment by sagargithubuser** [comment] 2022-11-03 10:56
> 

Thanks @alan-agius4

What could be the depndency missing ?

OR

Is there any setting to ignore the error and complete the ng serve ?

**Comment by alan-agius4** [comment] 2022-11-03 11:07
> What could be the depndency missing ?
`BsDropdownModule` seems to be ng-bootstrap related.

OR

> Is there any setting to ignore the error and complete the ng serve ?
No this is not possible.
