### ISSUE TITLE
Cannot find module '@angular-cli/ast-tools'

### ISSUE THREAD

**Issue by kevinaud** [angular/angular-cli#2941] opened 2016-10-28 20:06 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Linux, Fedora 23
> Node 6.6.0
> npm 3.10.3

### Versions.
> Version 1.0.0-beta.18

### Repro steps.
> mkdir test
> cd test
> npm install angular-cli@1.0.0-beta.18
> ng new test-app

### The log given by the failure.

Cannot find module '@angular-cli/ast-tools'
Error: Cannot find module '@angular-cli/ast-tools'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kevinaud/bin/test/node_modules/angular-cli/utilities/ast-utils.js:4:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kevinaud/bin/test/node_modules/angular-cli/models/find-lazy-modules.js:7:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kevinaud/bin/test/node_modules/angular-cli/models/webpack-build-typescript.js:4:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kevinaud/bin/test/node_modules/angular-cli/models/webpack-config.js:2:34)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kevinaud/bin/test/node_modules/angular-cli/tasks/build-webpack.js:6:24)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kevinaud/bin/test/node_modules/angular-cli/commands/build.js:3:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (/home/kevinaud/bin/test/node_modules/angular-cli/addon/index.js:21:16)
    at /home/kevinaud/bin/test/node_modules/angular-cli/lib/models/project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (/home/kevinaud/bin/test/node_modules/angular-cli/lib/models/project.js:391:15)
    at Project.eachAddonCommand (/home/kevinaud/bin/test/node_modules/angular-cli/lib/models/project.js:426:30)
    at module.exports (/home/kevinaud/bin/test/node_modules/angular-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/home/kevinaud/bin/test/node_modules/angular-cli/lib/cli/cli.js:34:26)
    at tryCatch (/home/kevinaud/bin/test/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/kevinaud/bin/test/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/kevinaud/bin/test/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/kevinaud/bin/test/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

### Mention any other details that might be useful.
Was working fine yesterday. Today I tried to deploy the app I've been working on with my travis CI build and that's when I first encountered this error. When I tried to reproduce it at the most basic level on my own machine it gave me the same error. I'm not sure what could've changed since I had to version locked in to 1.0.0-beta.18. I have the angular cli globally installed on my machine at version 18 as well and it is working fine. It's only when I try to install it locally to a directory that I am running in to this.

**Comment by nukuuk** [comment] 2016-10-28 20:15
me too, except i am trying to use beta.19

**Comment by karbica** [comment] 2016-10-28 20:18
+1

**Comment by fcrocce** [comment] 2016-10-28 20:21
same problem with both beta.18 and beta.19 (ubuntu 16.04)

**Comment by nukuuk** [comment] 2016-10-28 20:21
Am getting the following while doing **npm install angular-cli -g**

> > execSync@1.0.2 install C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ Error: spawn node-gyp ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.

> node-zopfli@2.0.1 install C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

**Comment by Blah2014** [comment] 2016-10-28 20:23
+1 v1.0.0-beta.19

**Comment by alexverdaguer** [comment] 2016-10-28 20:27
Same here ...

**Comment by sgybas** [comment] 2016-10-28 20:30
Duplicate of #2940

**Comment by filipemoraisjorge** [comment] 2016-10-28 20:48
maybe the same as this https://github.com/angular/angular-cli/issues/1882#issuecomment-243326099

**Comment by baschte** [comment] 2016-10-28 20:59
+1 v1.0.0-beta.19

**Comment by agalazis** [comment] 2016-10-28 21:00
+1 angular-cli@1.0.0-beta.19-2

**Comment by siouxfallsit** [comment] 2016-10-28 21:01
Same problem setting up project on a fresh dev machine.

**Comment by wenzelwebdesign** [comment] 2016-10-28 21:11
Same here using latest:

Cannot find module '@angular-cli/ast-tools'
Error: Cannot find module '@angular-cli/ast-tools'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)

**Comment by ryantrevisol** [comment] 2016-10-28 21:17
For me it has messed up every version since beta 16. Beta 15 gives me a different error, but betas 16, 17, 18, and 19-2 give me the ast-tools issue

**Comment by roelver** [comment] 2016-10-28 21:31
New version 1.0.0-beta.19-3 did not fix it.
( node 7.0.0 / npm 4.0.1 / macOS Sierra v.10.12.1 )

```
Error: Cannot find module '@angular-cli/ast-tools'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/utilities/ast-utils.js:4:19)

```

**Comment by SamD** [comment] 2016-10-28 21:33
Seeing the same
Ubuntu 16.04, 

node v6.9.1
npm 3.10.8

**Comment by adumesny** [comment] 2016-10-28 21:47
worked for me at 10am this morning (PST) on new project, but broke this afternoon (2PM) when I deleted node_modules/ folder and re-ran npm install again (app that uses angular-cli, which is globally installed).

**Comment by leofachetti** [comment] 2016-10-28 21:55
Run again `npm install -g angular-cli` it's now working

**Comment by filipesilva** [comment] 2016-10-28 22:03
Dupe of https://github.com/angular/angular-cli/issues/2941, there's more information there.

**Closed by filipesilva** 2016-10-28 22:03 UTC

**Comment by azjkjensen** [comment] 2016-10-30 06:13
I had the same issue, turns out I had accidentally also installed angular-cli locally, and it wasn't using the global install.

**Comment by Supamiu** [comment] 2016-11-02 13:57
@filipesilva You closed as dupe but you marked the issue as dupe of itself.

**Comment by filipesilva** [comment] 2016-11-03 17:33
My bad! Wanted to close it as a dupe of https://github.com/angular/angular-cli/issues/2940
