### ISSUE TITLE
--stats-json doesn't work with --watch

### ISSUE THREAD

**Issue by mark-buer** [angular/angular-cli#9739] opened 2018-02-23 04:52 UTC
### Repro steps
* Compare result of running `ng --watch --stats-json`
* to the result of running `ng --stats-json`

### Observed behavior
`ng --stats-json` produces a `stats.json` file.
`ng --watch --stats-json` does not produce a `stats.json` file.

### Desired behavior
It should be possible to watch _and_ to produce the `stats.json` file.

If this is not possible, and these two flag settings are mutually exclusive, it'd be nice if `--help` or wiki mentioned it.

Usecase:

I'm developing a custom build system for an electron application which is comprised of many angular apps. `ng --watch` speeds up our development cycle, but the initial hit of building many apps at application startup is a killer. I plan to use the output of prior `--watch --stats-json` builds to fingerprint the filesystem, and thus only perform a build if the modified time of any of the modules of an angular app have changed.

Thus, I'd like `stats.json` to be emitted every time that the webpack compiler callback is invoked.

### Mention any other details that might be useful

I can't think of a good reason why `stats.json` isn't emitted during `--watch` builds.
Relevant code location https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/tasks/build.ts#L61

**Comment by mark-buer** [comment] 2018-02-23 04:55
This problem was briefly mentioned here: https://github.com/angular/angular-cli/issues/6131#issuecomment-326325703

**Comment by filipesilva** [comment] 2018-02-27 20:11
It's a bug for sure, just a rather low prio one. Instead of writing the stats there we should be using something like https://www.npmjs.com/package/stats-webpack-plugin.

**Comment by mgechev** [comment] 2019-08-19 20:25
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:25 UTC
Labels: comp: devkit/build-angular, freq1: low, severity2: inconvenient, type: bug/fix
