### ISSUE TITLE
New project created in wrong way

### ISSUE THREAD

**Issue by bay007** [angular/angular-cli#4999] opened 2017-02-25 07:14 UTC
>I want to create my app called "pr2" (ng new pr2) in the folder c:\Users\DELL\Documents\angular2 the process for creation stars and ends Successfully, but when try to navigate to forder pr2 the folder is missing. ![image](https://cloud.githubusercontent.com/assets/8164038/23329075/de7ec4a0-faf5-11e6-9ec9-c33ff043092d.png)

If run the command **ng new pr2** again I get the error _Directory 'pr2' already exists._

![image](https://cloud.githubusercontent.com/assets/8164038/23329091/1ff33772-faf6-11e6-89ff-9db3cdb4bd41.png)

Searching where is my project pr2, I found it in the path "c:\Users\DELL", 2 folders up.

> ---------------------------------------------------------------

### OS?
Microsoft Windows 7 Professional
6.1.7601 Service Pack 1 Compilación 7601

### Versions.
> @angular/cli: 1.0.0-beta.32.3
node: 7.3.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

### Mention any other details that might be useful.
I unnistalled angular-cli with the commands
**npm uninstall -g angular-cli
npm cache clear**

Installed again with the command 
**npm install -g @angular/cli**
the behaviour is the same.

I cut and paste the folder c:\Users\DELL\pr2 to c:\Users\DELL\Documents\angular2\ 
I am in the path c:\Users\DELL\Documents\angular2\pr2 and ran the command
**ng serve --host 0.0.0.0 --port 4201 --live-reload-port 49153**
and the app works until now.

![image](https://cloud.githubusercontent.com/assets/8164038/23329165/a43e7a90-faf7-11e6-810a-beee77747391.png)

**Comment by filipesilva** [comment] 2017-02-26 15:25
That happened because you had a `node_modules` or `package.json` up in `c:\Users\DELL`, which caused the CLI to identify that folder as the project root.

Dupe of https://github.com/angular/angular-cli/issues/1079, fixed in https://github.com/angular/angular-cli/pull/4901, released in rc.0.

**Closed by filipesilva** 2017-02-26 15:25 UTC
