### ISSUE TITLE
Cant use webpack bundle analyzer. the stats.json generated by ng build is missing the assets property

### ISSUE THREAD

**Issue by windmillcode0** [angular/angular-cli#27190] opened 2024-03-04 06:19 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.1.0

### Description

From moving from the old architect to the new architect stats.json assets property is missing. webpack-bundle analyzer fails because the assets property is missing and you are not able to view the dependencies in your code

### Minimal Reproduction

npm install -s @angular/cli
npx ng new my-app
cd .\my-app\
npm install -D webpack-bundle-analyzer
npx ng build  --stats-json; npx webpack-bundle-analyzer --port 9000 dist/my-app/stats.json

### Exception or Error

```text
Could't analyze webpack bundle:
TypeError: Cannot read properties of undefined (reading 'filter')
```

### Your Environment

```text
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.2
@angular-devkit/build-angular   17.2.2
@angular-devkit/core            17.2.2
@angular-devkit/schematics      17.2.2
@angular/cli                    17.2.2
@angular/ssr                    17.2.2
@schematics/angular             17.2.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

### Anything else relevant?

Here is the github repo https://github.com/windmillcode0/angular-webpack-bundle-analyzer-fails 
all you have to do is npm install 
then npm run analyze

**Comment by JoostK** [comment] 2024-03-04 06:54
This appears to be https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/490.

**Comment by alan-agius4** [comment] 2024-03-04 07:15
Closing as this is not caused by the Angular CLI.

**Closed by alan-agius4** 2024-03-04 07:15 UTC

**Comment by windmillcode0** [comment] 2024-03-04 13:00
Greetings at least can we get documentation on this command?

**Comment by windmillcode0** [comment] 2024-03-04 13:21
I've gone and found this package https://www.npmjs.com/package/vite-bundle-analyzer
and for  anyone needding to know how to use it
```ts
ng build -c production  && cd  [PROJECT PATH NAME HERE NO BRACKETS]/[browser or server IF YOU USED SSR NO BRACKETS] &&  vite-bundle-visualizer    --open
```
