### ISSUE TITLE
Installation fails with error code -4058

### ISSUE THREAD

**Issue by MrBananaGuard** [angular/angular-cli#2290] opened 2016-09-22 09:42 UTC
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**Windows 10**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

**Output:**
C:\CDATA\Angular CLI>node --version
v6.6.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

 This is an installation error...

4. The log given by the failure. Normally this include a stack trace and some
   more information.

**Error stack trace from the log file:**

**113513** warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\angular-cli\node_modules\chokidar\node_modules\fsevents):
**113514** warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
**113515** verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
**113515** verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
**113515** verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
**113515** verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
**113516** verbose stack Error: ENOENT: no such file or directory, rename 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\.staging\abbrev-0bb3b844' -> 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
**113516** verbose stack     at destStatted (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:25:7)
**113516** verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
**113516** verbose stack
**113516** verbose stack Error: ENOENT: no such file or directory, rename 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\.staging\abbrev-0bb3b844' -> 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
**113516** verbose stack     at Error (native)
**113517** verbose cwd C:\CDATA\Angular CLI
**113518** error Windows_NT 10.0.14393
**113519** error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USERNAME\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
**113520** error node v6.6.0
**113521** error npm  v3.10.8
**113522** error path C:\Users\USERNAME\AppData\Roaming\npm\node_modules\.staging\abbrev-0bb3b844
**113523** error code ENOENT
**113524** error errno -4058
**113525** error syscall rename
**113526** error enoent ENOENT: no such file or directory, rename 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\.staging\abbrev-0bb3b844' -> 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
**113527** error enoent ENOENT: no such file or directory, rename 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\.staging\abbrev-0bb3b844' -> 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
**113527** error enoent This is most likely not a problem with npm itself
**113527** error enoent and is related to npm not being able to find a file.
**113528** verbose exit [ -4058, true ]

5. Mention any other details that might be useful.

I am also using the latest NPM

**Output:**
C:\CDATA\Angular CLI>npm --version
3.10.8

**Comment by filipesilva** [comment] 2016-10-03 17:38
Dupe of https://github.com/angular/angular-cli/issues/1190

**Closed by filipesilva** 2016-10-03 17:38 UTC
