### ISSUE TITLE
ng new creates project in parent folder in OS X Terminal

### ISSUE THREAD

**Issue by gotofritz** [angular/angular-cli#4198] opened 2017-01-24 11:19 UTC
### OS?
OS X 10.10.5

### Versions.
angular-cli: 1.0.0-beta.26
node: 6.9.1
os: darwin x64

### Repro steps.
cd ~/work/angular
npm i -g angular-cli
ng new my_project

EXPECTED: folder ~/work/angular/my_project
ACTUAL: folder ~/work/my_project

### The log given by the failure.
None

**Comment by Meligy** [comment] 2017-01-24 11:23
You probably have a `package.json` file in upper folder? This is used by the CLI to indicate the root of a project.

**Comment by filipesilva** [comment] 2017-01-24 11:47
Dupe of https://github.com/angular/angular-cli/issues/1079

**Closed by filipesilva** 2017-01-24 11:47 UTC
