### ISSUE TITLE
Allow setting noEmitOnError 

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular-cli#21492] opened 2021-08-04 06:44 UTC
Every typescript error causes the compiler to fail. This is very annoying when working in dev mode, because we don't want to spend time fixing these errors now.  For example:

> Property 'foo' is declared but its value is never read.

It will be really helpful to add a new configuration in angular.json that can disable this behavior based on environment.

**Comment by alan-agius4** [comment] 2021-08-04 06:47
Duplicate of https://github.com/angular/angular-cli/issues/19948

**Closed by alan-agius4** 2021-08-04 06:47 UTC
