### ISSUE TITLE
ng update takes from registry.npmjs.com rather than github

### ISSUE THREAD

**Issue by SamuelMarks** [angular/angular-cli#10642] opened 2018-05-04 15:13 UTC
### Versions
```
Angular CLI: 6.0.0
Node: 8.11.1
OS: darwin x64
Angular: 6.0.0
```

### Repro steps

* Add a github package to your package.json, `team/repo-name` should work, or with tarball: `https://api.github.com/repos/team/repo-name/tarball`.
* Run `ng update`

### Observed behavior
```
$ ng update @angular/cli
Registry returned 404 for GET on https://registry.npmjs.org/repo-name
```

### Desired behavior
It shouldn't look to registry.npmjs when a github version is referred.

**Comment by scottleedavis** [comment] 2018-05-05 19:10
from #10614 , to temporarily get past this 
@james-tonicanalytics

> The temporary solution that stopped the error occurring was to delete the local dependency from the package.json file and then run ng update @angular/cli. Once the .angular-cli.json was migrated to angular.json, I added the local dependency back in.

**Comment by beeing** [comment] 2018-06-25 08:31
Not sure if this helps, I'm using a private npm registry and uses `npm login --registry=url`.
Angular CLI should read from ~/.npmrc instead?

**Comment by xcash** [comment] 2018-11-15 09:58
Commenting out the dependency in `package.json` resolves it but it would be great even a simple and lazy solution as preventing the update from stopping. 
Please Google fix this :)

**Comment by JayceeZ** [comment] 2018-12-04 10:00
Any news about this issue? We tried migrating to Angular 7, but ng update failed with 404 due to calls to the wrong registry...

**Comment by Steven-Harris** [comment] 2018-12-27 18:42
I am also having an issue with this. I have a private registry set in my global npmrc (and yarnrc) and the cli seems to be playing by it's own rules rather than respecting the global config. I also tried setting a local npmrc file and had the same issue.
`404 Not Found - GET https://registry.npmjs.org/mypackage- Not found`

**Comment by balteo** [comment] 2020-05-29 13:51
Any update on this issue? 
When will it be possible to configure the npm registry used by ng update/ng cli?
Please kindly reply...

**Comment by clydin** [comment] 2020-05-29 16:03
The Angular CLI will honor the configuration found in .npmrc files.  If you are encountering issues in this regard please open a separate issue detailing the problem.
This issue pertains to the use of non-registry sourced dependencies (file, git, directory, etc.).  Analyzing such dependencies is not currently supported via ng update but as of 9.1 they will no longer cause an error.

**Comment by balteo** [comment] 2020-05-29 16:09
@clydin Thanks for the reply and sorry for the misunderstanding. I will open a separate issue.

**Comment by andrewpolemeni** [comment] 2022-07-11 19:53
This issue should not just be from github but for private repo manager URL. The ng update command should be smart enough to see that there is an .npmrc file and then update based on that.

**Comment by alan-agius4** [comment] 2022-11-14 10:32
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Closed by alan-agius4** 2022-11-14 10:32 UTC
Labels: type: bug/fix, freq2: medium, severity3: broken, area: angular/cli
