### ISSUE TITLE
Hide app setting variable (like firebase details )  

### ISSUE THREAD

**Issue by nirav4273** [angular/angular-cli#9581] opened 2018-02-09 15:35 UTC
I want to hide my firebase details.
after make build all environment.ts file data visible inside main.ts file.
I want to hide from there.

can anyone suggest how to hide?
Is it possible in angular or any way for hiding details?

**Comment by wvanderdeijl** [comment] 2018-02-09 22:27
All angular code is shipped to the client. How would you envision to keeping things secret in JavaScript that ships to the browser client?

**Comment by ddimaria** [comment] 2018-02-11 08:19
@nirav4273 you would handle this with a proxy or on a server where you authenticate (token).

**Comment by Brocco** [comment] 2018-02-12 15:43
Duplicate of #4419

**Closed by Brocco** 2018-02-12 15:43 UTC
