### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular-cli#24605] opened 2023-01-25 15:00 UTC
### Description

When will angular finally have vite support? I just don't see this topic dicussed eneugh. We want vite support.

### Proposed solution

/

### Alternatives considered

/

**Comment by alan-agius4** [comment] 2023-01-25 15:54
Duplicate of https://github.com/angular/angular-cli/issues/23771

**Closed by alan-agius4** 2023-01-25 15:54 UTC
