### ISSUE TITLE
webpack-bundle-analyzer --> polyfills-es5-es2015.js

### ISSUE THREAD

**Issue by pacocom** [angular/angular-cli#16819] opened 2020-02-03 10:07 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

I need to use tsconfig.json **target: es2015**
```
{
  "compileOnSave": false,
  "compilerOptions": {
    ...
    "target": "es2015",
    ...
}
```

Script package.json
```
...
"build:stats": "ng build client --prod --statsJson",
"build:analyze": "webpack-bundle-analyzer dist/apps/client/stats-es2015.json",
...
```

Terminal
```
$ npm run build:stats && npm run build:analyze

> ng build client --prod --statsJson

Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {5} polyfills-es2015.js, polyfills-es2015.js.map (polyfills) 185 kB [initial] [rendered]
chunk {6} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 272 kB [initial] [rendered]
chunk {3} 3-es2015.js, 3-es2015.js.map () 19.4 kB  [rendered]
chunk {3} 3-es5.js, 3-es5.js.map () 20.1 kB  [rendered]
chunk {1} common-es2015.js, common-es2015.js.map (common) 8.92 kB  [rendered]
chunk {1} common-es5.js, common-es5.js.map (common) 9.59 kB  [rendered]
chunk {0} runtime-es2015.js, runtime-es2015.js.map (runtime) 2.25 kB [entry] [rendered]
chunk {0} runtime-es5.js, runtime-es5.js.map (runtime) 2.25 kB [entry] [rendered]
chunk {2} 2-es2015.js, 2-es2015.js.map () 115 kB  [rendered]
chunk {2} 2-es5.js, 2-es5.js.map () 116 kB  [rendered]
chunk {9} 9-es2015.js, 9-es2015.js.map () 14.3 kB  [rendered]
chunk {9} 9-es5.js, 9-es5.js.map () 14.8 kB  [rendered]
chunk {4} main-es2015.js, main-es2015.js.map (main) 2.07 MB [initial] [rendered]
chunk {4} main-es5.js, main-es5.js.map (main) 2.19 MB [initial] [rendered]
chunk {8} 8-es2015.js, 8-es2015.js.map () 64.3 kB  [rendered]
chunk {8} 8-es5.js, 8-es5.js.map () 65.5 kB  [rendered]
chunk {10} 10-es2015.js, 10-es2015.js.map () 147 kB  [rendered]
chunk {10} 10-es5.js, 10-es5.js.map () 150 kB  [rendered]
chunk {11} 11-es2015.js, 11-es2015.js.map () 95.1 kB  [rendered]
chunk {11} 11-es5.js, 11-es5.js.map () 97.2 kB  [rendered]
chunk {7} styles.css, styles.css.map (styles) 336 kB [initial] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 3.15 kB [entry] [rendered]
Date: 2020-02-03T09:56:05.827Z - Hash: ef66f1bf1f025acfeb65 - Time: 119800ms

WARNING in budgets, maximum exceeded for initial. Budget 2 MB was exceeded by 1.8 MB.

> @telefonica/atc@0.0.0 build:analyze C:\Users\Francisco\Documents\project
> webpack-bundle-analyzer dist/apps/client/stats-es2015.json

Error parsing bundle asset "C:\Users\Francisco\Documents\project\dist\apps\client\polyfills-es5-es2015.js": no such file
Webpack Bundle Analyzer is started at http://127.0.0.1:8888
Use Ctrl+C to close it
```
![image](https://user-images.githubusercontent.com/7735329/73644195-2b4ff600-4675-11ea-8a07-bb7eeefd6cae.png)

**File polyfills-es5-es2015.js** doesn't exist. **The correct file name is polyfills-es5.js**

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.15
Node: 12.3.1
OS: win32 x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.3
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.3
@angular-devkit/schematics        8.3.3
@angular/cdk                      8.2.3
@angular/cli                      8.3.15
@angular/material                 8.2.3
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.3
@schematics/update                0.803.15
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-02-03 15:51
This should be fixed in version 9 as per https://github.com/angular/angular-cli/pull/16181

**Comment by alan-agius4** [comment] 2020-02-03 15:55
Duplicate of https://github.com/angular/angular-cli/issues/15915

**Closed by alan-agius4** 2020-02-03 15:55 UTC
