### ISSUE TITLE
Missing declaration types NormalizedSourceMaps, CurrentFileReplacement, AssetPatternObject

### ISSUE THREAD

**Issue by code2nguyen** [angular/angular-cli#13388] opened 2019-01-09 15:31 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```
### Area
```
- [X] devkit
- [ ] schematics
```
### Versions
ng --version v7.2.0

### Repro steps
```
import { BrowserBuilder, } from '@angular-devkit/build-angular';
```

### The log given by the failure
```
../../node_modules/@angular-devkit/build-angular/src/browser/schema.d.ts:417:14 - error TS2304: Cannot find name 'NormalizedSourceMaps'.

417   sourceMap: NormalizedSourceMaps;
                 ~~~~~~~~~~~~~~~~~~~~

../../node_modules/@angular-devkit/build-angular/src/browser/schema.d.ts:420:17 - error TS2304: Cannot find name 'NormalizedOptimization'.

420   optimization: NormalizedOptimization;
                    ~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/@angular-devkit/build-angular/src/karma/schema.d.ts:61:11 - error TS2304: Cannot find name 'AssetPatternObject'.

61   assets: AssetPatternObject[];
             ~~~~~~~~~~~~~~~~~~

../../node_modules/@angular-devkit/build-angular/src/karma/schema.d.ts:62:21 - error TS2304: Cannot find name 'CurrentFileReplacement'.

62   fileReplacements: CurrentFileReplacement[];
                       ~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/@angular-devkit/build-angular/src/karma/schema.d.ts:63:14 - error TS2304: Cannot find name 'NormalizedSourceMaps'.

63   sourceMap: NormalizedSourceMaps;
                ~~~~~~~~~~~~~~~~~~~~

../../node_modules/@angular-devkit/build-angular/src/server/schema.d.ts:181:21 - error TS2304: Cannot find name 'CurrentFileReplacement'.

181   fileReplacements: CurrentFileReplacement[];
                        ~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/@angular-devkit/build-angular/src/server/schema.d.ts:182:14 - error TS2304: Cannot find name 'NormalizedSourceMaps'.

182   sourceMap: NormalizedSourceMaps;
                 ~~~~~~~~~~~~~~~~~~~~

../../node_modules/@angular-devkit/build-angular/src/server/schema.d.ts:183:17 - error TS2304: Cannot find name 'NormalizedOptimization'.3:17 - error TS2304: Cannot find name 'NormalizedOptimization'.

183   optimization: NormalizedOptimization;
                    ~~~~~~~~~~~~~~~~~~~~~~

```

### Desired functionality

Compile w/o error when importing from @angular-devkit/build-angular.

**Comment by hansl** [comment] 2019-01-10 00:40
Not sure why this is marked as a regression. It never worked as we don't guarantee to publish typings for those. The `build-angular` package is currently experimental.

The good news is we'll start publishing those most likely around the v8 timeframe as we stabilize the Architect API.

Closing this as working as intended.

**Closed by hansl** 2019-01-10 00:40 UTC
Labels: comp: devkit/build-angular, freq1: low, severity5: regression, type: bug/fix

**Comment by AlanObject** [comment] 2019-01-11 03:51
I ran into this as well.  To fix it so I could build my angular project I had to downgrade @angular/build-angular to 0.11.4 because anything later than that wouldn't build.   

Could someone explain why this ticket was closed because "build-angular is experimental" so we don't care if it works or not?   Can you do ng serve without it?
