### ISSUE TITLE
ng serve, browser serve wrong path for material fonts (self hosted), in dev server

### ISSUE THREAD

**Issue by djleonskennedy** [angular/angular-cli#10412] opened 2018-04-20 11:48 UTC
### Versions
```
Angular CLI: 6.0.0-rc.5
Node: 8.9.4
OS: win32 x64
Angular: 6.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.7
@angular-devkit/build-angular     0.5.7
@angular-devkit/build-optimizer   0.5.7
@angular-devkit/core              0.5.7
@angular-devkit/schematics        0.5.7
@angular/cdk                      6.0.0-rc.12
@angular/material                 6.0.0-rc.12
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.5
@schematics/angular               0.5.7
@schematics/update                0.5.7
rxjs                              6.0.0-uncanny-rc.7
typescript                        2.7.2
webpack                           4.5.0
```

### Repro steps
1) install app **ng new app**
2) install material icons (as self hosting)
![image](https://user-images.githubusercontent.com/8366455/39049200-32014c44-44a9-11e8-954c-94954219fc65.png)

3) set up lazy routes someLazyRoute -> someLazyRoute2 (both lazy)
4) open them by full path localhost:4200/someLazyRoute/someLazyRoute2
5) add some icon in `someLazyRoute` for example;
6) check console

### Observed behavior
I've setup project with lazy loading;

have structure **localhost:4200/account/home** (all routes are lazy loaded)
if i open app from root like **localhost:4200** icons serves well
if i serve from path localhost:4200/account/home

i have next a result:
![image](https://user-images.githubusercontent.com/8366455/39049106-b87266b0-44a8-11e8-89e3-c167849794d9.png)

this is Frames screen from chrome
![image](https://user-images.githubusercontent.com/8366455/39049151-ebdf2a6a-44a8-11e8-8bda-e022c5b54c89.png)

### Desired behavior
icons loaded as expected

### Mention any other details that might be useful (optional)
seems like this problem with dev server;
i've tried serve this via `http server` with `spa` mode and all works fine also in IE11 all works fine too even in ng serve

**Comment by cyrilletuzi** [comment] 2018-04-20 12:33
Duplicate of #10378

**Closed** 2018-04-20 13:27 UTC
