### ISSUE TITLE
Failing to build libraries as of ng-packagr v16.1.0

### ISSUE THREAD

**Issue by Blunderchips** [angular/angular-cli#25421] opened 2023-06-22 08:40 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

As of a recent update my libraries are not building. Of course, the only change I made to the libraries was to update the version of Angular we use. We first noticed the issue when our CI/CD pipelines started failing on new merge requests but the main branch was still succeeding. If there is a version of the library built/cached in the `dist` folder the build does succeed, I am assuming this has something to do with how things are cached. Builds only seem to fail when they are done cold/with nothing in the cache.

Looking through our build logs the issue seems to have been introduced around `ng-packagr v16.1.0`. No changes have been made to the failing library for a couple of weeks now code-wise.

I will attach the error message below. I would love to give more info in the future, maybe we should also look at improving those log messages :)

### Please provide the exception or error you saw

```true
No provider for InjectionToken ng.v5.defaultTsConfig! (InjectionToken ng.v5.packageTransform -> InjectionToken ng.v5.initTsConfigTransform -> InjectionToken ng.v5.defaultTsConfig)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.0       
Node: 18.16.0
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 16.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@angular/cli                    16.1.0
@angular/fire                   7.6.1
@angular/flex-layout            15.0.0-beta.42
@schematics/angular             16.1.0
ng-packagr                      16.1.0
rxjs                            7.8.1
typescript                      5.0.4
```

### Anything else?

I have seen [this issue](https://stackoverflow.com/q/74346913/3833743). Though it seems to be similar it is not a duplicate and this answer is not a solution.

Our project consists of a workspace with two applications sharing components from a shared library.

**Comment by JoostK** [comment] 2023-06-22 09:27
Transferring to the CLI although this seems like it could be an ng-packagr thing (which has its own repository: https://github.com/ng-packagr/ng-packagr),

We'd need a reproduction to tell what is going on here. I suspect some issues with dependencies, but I couldn't tell for certain without a repro.

**Comment by Blunderchips** [comment] 2023-06-22 09:36
> Transferring to the CLI although this seems like it could be an ng-packagr thing (which has its own repository: https://github.com/ng-packagr/ng-packagr),
> 
> We'd need a reproduction to tell what is going on here. I suspect some issues with dependencies, but I couldn't tell for certain without a repro.

Hi @JoostK how do you suggest I provide steps to replicate? We can't of course open source our entire project of course and we can't tell for certain where the issue even is when Angular just stops working.

**Comment by JoostK** [comment] 2023-06-22 10:38
Using a Github repo that contains a minimum reproduction. The code is unlikely to be relevant, but all configuration and dependencies most likely are. If you create a new application and then align configuration to correspond with your real app you might find what is needed to cause it to break, at which point you can share the minimum setup that reproduces the issue.

**Comment by Blunderchips** [comment] 2023-06-26 08:09
Hello @JoostK I don't you are understanding what I am saying. Of course, we would upload a new application to GitHub. We are unable to reproduce the error given the vague error message. From my perspective, I am looking at a `500 server error` with no trace or any debug info whatsoever.

Could you please advise us on how to get any debug information or add some in?

**Comment by JoostK** [comment] 2023-06-26 09:30
It seems like the ng-packagr builder requires a `tsconfig` option. When omitted it could result in this error.

**Comment by Blunderchips** [comment] 2023-06-26 10:36
> It seems like the ng-packagr builder requires a `tsconfig` option. When omitted it could result in this error.

Ok @JoostK what option? Our `tsconfig` has not changed for quite some time now and we have cross-referenced against it a newly created angular project. That is both our root `tsconfig` and the `tsconfig` of our library.

Could you please advise us on how to get any debug information or add some in?

**Comment by JoostK** [comment] 2023-06-26 11:44
I suspect that this condition:

https://github.com/angular/angular-cli/blob/c05c83be7c6c8bcdad4be8686a6e0701a55304cc/packages/angular_devkit/build_angular/src/builders/ng-packagr/index.ts#L33

is false, causing no tsconfig to be configured which then results in the error that the tsconfig configuration is missing. That condition corresponds with the value of the `tsconfig` option of the ng-packagr builder, as configured in your `angular.json` file.
 I don't otherwise have additional debugging suggestions.

**Comment by Blunderchips** [comment] 2023-06-29 10:57
> I suspect that this condition:
> 
> https://github.com/angular/angular-cli/blob/c05c83be7c6c8bcdad4be8686a6e0701a55304cc/packages/angular_devkit/build_angular/src/builders/ng-packagr/index.ts#L33
> 
> is false, causing no tsconfig to be configured which then results in the error that the tsconfig configuration is missing. That condition corresponds with the value of the `tsconfig` option of the ng-packagr builder, as configured in your `angular.json` file. I don't otherwise have additional debugging suggestions.

@JoostK I am assuming these are the `angular.json` options you are referring to? They are all defined and all the files exists. 

![image](https://github.com/angular/angular-cli/assets/7081037/bcf90554-a665-4eb5-b35b-e892e6918214)

As for that condition, I added in some logging, and `tsconfig` is undefined on `options`. I am assuming that is the bug that is causing our issues?

![image](https://github.com/angular/angular-cli/assets/7081037/7b685de0-d63b-42e2-a006-def654809953)

![image](https://github.com/angular/angular-cli/assets/7081037/425fd72e-cce9-4471-b245-4dadb832b621)

**Comment by alan-agius4** [comment] 2023-06-29 12:37
@Blunderchips, it looks like you don't have a `defaultConfiguration` parallel to the configuration object in your `angular.json`.

**Comment by JoostK** [comment] 2023-06-29 12:51
You're only specifying a `tsconfig` option in the various configurations, so if there is no default configuration and if you're not building a particular configuration then you'll get the error.

There is a bug where `tsconfig` being optional results in ng-packgr just failing, whereas `tsconfig` is in fact declared as optional by the ng-packagr builder. I would classify that as CLI bug.

**Comment by alan-agius4** [comment] 2023-06-29 12:53
The tsconfig is technically optional, which would cause ng-packagr to use it's built in config, so it's more of an ng-packagr issue.

**Comment by Blunderchips** [comment] 2023-06-29 13:19
> @Blunderchips, it looks like you don't have a `defaultConfiguration` parallel to the configuration object in your `angular.json`, which causes the tsConfig to be undefined.

Hi @alan-agius4 we have not added or removed configs since the library was first generated and even then we used the default that the CLI generated at the time. If an option is missing it can be added if you let me know which one? Then if we are introducing break changes with either ng-packagr or the CLI would it not be done with a major?

Either way, I think it is important for you guys to please update your error messages so we have a better idea of what is going on here.

**Closed** 2023-06-29 13:21 UTC
Labels: needs: repro steps
