### ISSUE TITLE
Use Node.js dependencies in server-only code

### ISSUE THREAD

**Issue by Mehdi-MST** [angular/angular-cli#28087] opened 2024-07-19 15:38 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Packages like swagger-dist that uses path gives error on build. Using ssr or without ssr. 

node_modules/swagger-ui-dist/absolute-path.js:9:19:

const getAbsoluteFSPath = function () {
// detect whether we are running in a browser or nodejs
if (typeof module !== "undefined" && module.exports) {
return require("path").resolve(__dirname)
}
throw new Error('getAbsoluteFSPath can only be called within a Nodejs environment');
}

export default getAbsoluteFSPath

by removing the line return require("path").resolve(__dirname) it solve the issue . any other possible fix for that please?

### Minimal Reproduction

Swagger-dist

### Exception or Error

```text
require("path").resolve(__dirname) it solve the issue . any other possible fix for that please?
```

### Your Environment

```text
18.0.1
```

**Comment by dgp1130** [comment] 2024-07-19 17:56
What exactly is the build error you're seeing? Is it that esbuild is refusing to bundle Node packages for a browser build?

> The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

`ng serve` seems to treat such packages as external. It runs them for SSR but throws an error for CSR. Weirdly, depending on how you import the symbol you get different errors:

```typescript
import {join} from 'path';

join('foo', 'bar');
```

> Error: Module "path" has been externalized for browser compatibility. Cannot access "path.join" in client code.  See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

This one makes sense and correctly identifies the core issue.

```typescript
import * as path from 'path';

path.join('foo', 'bar');
```

>  path.join is not a function

This one just imports `path` as an empty `Proxy`, which isn't terribly helpful. It would be nice for the `ng serve` implementation with Vite to give a consistent error.

Normally I would suggest `isPlatformBrowser()` to avoid running server-only code on the client, but `swagger-dist` is already basically doing that and it doesn't help here since the issue happens at bundle time.

I tried to see if esbuild is smart enough to tree shake unused modules and avoid this error, and that's possible, but a bit constrained. I initially tried:

```typescript
import * as path from 'path';

declare global {
  const usePath: boolean;
}

if (usePath) {
  console.log(path.join('foo', 'bar'));
}
```

And then set `defines: { usePath: "false" }` in `angular.json`, esbuild still emits the same error.

However this does work if we gate a dynamic `import()` behind a `define`:

```typescript
if (usePath) {
  const path = await import('path');
  console.log(path.join('foo', 'bar'));
}
```

That seems closer to the right solution here, however I don't think `defines` currently supports different options for client vs. server bundles, so there's no easy way to tree shake from the client bundle but still use it in the server bundle (maybe it should be). Also we've discussed a tree shakable version of `isPlatformBrowser()` which might be more appropriate here.

I think the action items here are:
1. `ng serve` should give a consistent error when importing Node.js modules (not sure if that's a Vite bug or not).
2. esbuild should tree shake unused static imports prior to checking platform so you don't need a dynamic import here.
3. Consider a tree-shakable `isPlatformBrowser`.
4. Consider setting different `defines` between client and server builds.

**Comment by alan-agius4** [comment] 2024-07-19 18:42
This seems like a duplicate of https://github.com/angular/angular-cli/issues/27425

**Comment by alan-agius4** [comment] 2024-07-26 09:08
In this situation, because the issue lies within a library, options 2 to 4 are not feasible. Instead, it is recommended to configure `path` as an external dependency.

Here's how you can modify your configuration:

```json
"architect": {
  "build": {
    "builder": "@angular-devkit/build-angular:application",
    "options": {
      "index": "src/index.html",
      "main": "src/main.ts",
      "externalDependencies": ["path"]
    }
  }
}
```

Regarding the different behavior observed during `ng serve`, this issue is being tracked at https://github.com/angular/angular-cli/issues/27425.

**Closed by alan-agius4** 2024-07-26 09:08 UTC
Labels: needs: discussion, area: @angular/ssr, area: angular/build
