### ISSUE TITLE
Random sass errors after angular migration (14 to 16)

### ISSUE THREAD

**Issue by JoranLive** [angular/angular-cli#26389] opened 2023-11-17 08:12 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Exactly the same issue as described here:
https://github.com/angular/angular-cli/issues/25018

### Minimal Reproduction

Not easy to find a way to reproduce as it is random and noticed on CICD.

### Your Environment

```text
Angular CLI: 16.2.10
Node: 16.18.1
Package Manager: npm 8.19.2
OS: linux x64

Angular: 16.2.12
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.5
@angular-devkit/build-angular   16.2.10
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.2.10
@angular/cli                    16.2.10
@angular/flex-layout            15.0.0-beta.42
@schematics/angular             16.2.10
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.3
```

**Comment by alan-agius4** [comment] 2023-11-17 10:24
Unfortunately, without a reproduction it's not possible for us to investigate the issue.

**Comment by alan-agius4** [comment] 2023-11-23 15:06
Closing as no reproduction was provided. 

If the problem persists please open a new issue together with a minimal reproduction.

**Closed by alan-agius4** 2023-11-23 15:06 UTC
Labels: needs: repro steps

**Comment by amakhrov** [comment] 2023-12-22 20:41
I'm seeing similar errors when compiling the app in CI (Github Actions). It only started happening once we've stopped compiling inside docker (as a part of `docker build`) and started compiling directly in the Github Action runner.
We're on Angular 16.2 - I'll still have to see if the issue persists after upgrading to 17 though.

In addition to the errors similar to posted in https://github.com/angular/angular-cli/issues/25018 ("Undefined variable", "Undefined mixin", "Module loop"), there are also warnings like this
> [WARNING] Comments in CSS use "/* ... */" instead of "//" [js-comment-in-css]

After googling for this warning message, looks like it comes from `esbuild` - which is extremely strange, because we didn't opt into esbuild in our Angular 16 app:
```
    "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
```
