### ISSUE TITLE
Issue with the tree shaking

### ISSUE THREAD

**Issue by stephanecot** [angular/angular-cli#6233] opened 2017-05-09 09:56 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.0.2

### Repro steps.
I create a simple projet with angular/cli
I added two libs:
`
"@angular/animations": "^4.0.0"
"primeng": "4.0.0"
`
In app.module.ts, I had:
`
import { SharedModule as PrimeNgSharedModule } from 'primeng/primeng';
`
When I import  **PrimeNgSharedModule** in @NgModule.imports, my bundle grows from 2.29mb to 3.19mb ! (this module is very small...)

Whatever module, I had, the size will be always the same, all the content of primeng/primeng is added, there is not tree shaking here....

**Comment by filipesilva** [comment] 2017-05-09 10:03
Mostly dupe of https://github.com/angular/angular-cli/issues/2901.

The amount of tree shaking that happens depends on how `primeng` is setup as well. Webpack supports limited tree shaking (depends on your definition), not as much as rollup. We currently used Webpack and are thus limited by their support.

**Closed by filipesilva** 2017-05-09 10:03 UTC

**Comment by ysfjwd** [comment] 2017-05-12 17:46
hi @filipesilva, mind if i ask, does angular team has any plans of moving to rollup?

**Comment by filipesilva** [comment] 2017-05-12 20:03
No, that is not part of our plans currently. It would require a massive rework of the build system.
