### ISSUE TITLE
ng update return error for private package

### ISSUE THREAD

**Issue by tiaguinho** [angular/angular-cli#10729] opened 2018-05-08 13:20 UTC
### Version

```brash
Angular CLI: 6.0.0
Node: 8.9.4
OS: darwin x64 (Sierra)
```

### Repro steps

```bash
ng update @angular/cli
```

I have an Angular CLI project with a few private packages using YARN workpaces.
I'm receiving the error ```Not found: PACKAGE_NAME``` when I try to use ```ng update```.

**Comment by clydin** [comment] 2018-05-08 14:06
Duplicate of #10614

**Closed by clydin** 2018-05-08 14:06 UTC
