### ISSUE TITLE
Decorator stripping for app code no longer working in 1.5.0-rc.0

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#8050] opened 2017-10-13 22:47 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
Angular CLI: 1.5.0-rc.0
Node: 6.9.5
OS: darwin x64
Angular: 5.0.0-rc.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0-rc.0
@angular/material: 2.0.0-beta.12
@angular/service-worker: 1.0.0-beta.16
@angular-devkit/build-optimizer: 0.0.27
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.33
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.0
@schematics/angular: 0.0.45
typescript: 2.5.3
webpack: 3.7.1
```

I tested this also with Typescript 2.4.2 and got the same result.

### Repro steps.
```
ng new foo
cd foo
ng build --prod --build-optimizer
```

### The log given by the failure.

no error, the app builds, but the bundle contains decorators coming from the app code.

Example:

```
AppComponent = tslib_es6.b([ Object(core.h)({
                selector: "aio-shell",
                templateUrl: "./app.component.html"
            }), tslib_es6.d("design:paramtypes", [ deployment_service_Deployment, document_service_DocumentService, core.j, location_service_LocationService, navigation_service_NavigationService, scroll_service_ScrollService, search_service_SearchService, toc_service_TocService ]) ], AppComponent);
```

### Desired functionality.
All decorators in the app code should have been stripped.

### Mention any other details that might be useful.
This used to work in the past.

**Comment by sarunint** [comment] 2017-10-14 18:15
May be duplicate of #8027? Because the CLI automatically uses `AngularCompilerPlugin` when Angular's `major` is >= 5.

**Closed** 2017-10-18 18:49 UTC
Labels: priority: 1 (urgent), type: bug
