### ISSUE TITLE
browser-esbuild use 100% CPU

### ISSUE THREAD

**Issue by Hagay-Reinman** [angular/angular-cli#24626] opened 2023-01-29 17:42 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 14

### Description

According to the blug, I changed 
"builder": "@angular-devkit/build-angular:browser"
To 
"builder": "@angular-devkit/build-angular:browser-esbuild"

Every time I am compiling, the process uses all my CPU (32 GB) and swap, and the computer gets stuck for a few minutes. 
I am working on 5.15.0-58-generic #64-Ubuntu

### Minimal Reproduction

 nx serve dashboard

### Exception or Error

```text
Change to :browser-esbuild, and compile
```

### Your Environment

```text
I am running under nx, and ng version is not working.
node version is v19.5.0
npm version is 9.3.1
This is the package.json:
"devDependencies": {
    "@angular-devkit/build-angular": "15.1.3",
    "@angular-eslint/eslint-plugin": "15.0.0",
    "@angular-eslint/eslint-plugin-template": "15.0.0",
    "@angular-eslint/template-parser": "15.0.0",
    "@angular/cli": "~14.1.0",
    "@angular/compiler-cli": "15.1.2",
    "@angular/language-service": "^15.1.2",
    "@nrwl/cli": "15.6.3",
    "@nrwl/cypress": "15.6.3",
    "@nrwl/eslint-plugin-nx": "15.6.3",
```

### Anything else relevant?

When the compilation is done, everything work fine, but until then the computer is "dead"

**Comment by clydin** [comment] 2023-01-30 16:57
From the issue report, it appears that `nx` is being used.  Can this issue be replicated in an Angular project that is not using `nx`?
The Angular CLI itself does not currently contain dev-server support for the experimental esbuild-based builder. The issue may be caused by an interaction with the `nx serve` builder.

**Comment by alan-agius4** [comment] 2023-02-06 08:02
Closing due to the lack of communication. Please feel free to open a new issue if the problem persists.

**Closed by alan-agius4** 2023-02-06 08:02 UTC
Labels: needs: more info
