### ISSUE TITLE
[CSS] BUG css-loader strip background extra property start from 1.7.0-rc0

### ISSUE THREAD

**Issue by WandererInVoids** [angular/angular-cli#9687] opened 2018-02-19 15:17 UTC
### Versions
```
Angular CLI: 1.7.0
Node: 9.5.0
OS: win32 x64
Angular: 5.2.5
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.7.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.7.2
webpack-bundle-analyzer: 2.9.1
webpack: 3.11.0
```

### Repro steps

write css like:
`.image: {background: #FFF url("../imgs/login/user.png") no-repeat scroll 0% 0% / contain;}`
run `ng build prod`
after css transform to
`{background:url(user.cabb1ada47bc3414c794.png) #fff`

### Observed behavior
PostCSS strip `no-repeat scroll 0% 0% / contain` property from background if image is to large for encode to base64

### Desired behavior
not strip extra property
### Workaround 
use property like this:
```
 background-attachment: scroll;
  background-repeat: no-repeat;
  background-size: contain;
  background-color: #FFF;
```

**Comment by clydin** [comment] 2018-02-19 15:25
Duplicate of #9642; fixed via #9660; and will be in the next patch release.

**Closed by clydin** 2018-02-19 15:25 UTC
