### ISSUE TITLE
Identical chunk hash names, different file contents

### ISSUE THREAD

**Issue by monfa-red** [angular/angular-cli#3341] opened 2016-12-01 14:24 UTC
### OS?
Kubuntu 16.04

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: linux x64

### Repro steps.
`ng build --prod --aot`

### The log given by the failure.
It doesn't fail!

### Mention any other details that might be useful.
**The generated hashed chunks have the same filenames compare to the previous build when the contents of the files are different!!**

Let say I build the app using `ng build --prod --aot` and one of the chunk names is `16.25b41a1d87472f09d7df.chunk.js` , then I change/update code and build it again, now the main chunk gets a different hash name but some of the chunks keep the same previous name although they have a slightly different content, this causes problem since the old chunk gets cached in our users browsers.

It usually happens when I add a new component to the app and run the AoT build

**Comment by pavel-mxsf** [comment] 2016-12-01 14:38
check https://github.com/Poky85/webpack-chunkhash-demo ?

**Comment by monfa-red** [comment] 2016-12-01 15:46
@pavel-mxsf  seems like it reflects the same hashing issue, any solution to fix it for angular-cli?

**Comment by grizzm0** [comment] 2016-12-01 17:17
Already being discussed in #3311

**Comment by hansl** [comment] 2016-12-16 22:26
Dupe of #3311

**Closed by hansl** 2016-12-16 22:26 UTC
