### ISSUE TITLE
Angular 12.2 ng build fails with NOENT esbuild.exe error

### ISSUE THREAD

**Issue by bbarry** [angular/angular-cli#21702] opened 2021-09-03 14:12 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, 12.1.1 worked fine

 Yes, the previous version in which this bug was not present was: ....

### Description

I had a working application running angular 12.1.1 and just updated angular to 12.2.4 and received a NOENT error attempting to delete an angular architect .DELETE file (this happens almost every time I try to run ng update and I think it is some sort of problem with the language service and vscode on windows interacting badly with a process that my IT makes us run to scan for PII written to disk). Anyway I continued with `npm install` and added the new `webpack` peer dependency and `@babel/core` peer and `ng serve` works and my upgraded application seems good.

Then I run `ng build` and get this:

```


      throw er; // Unhandled 'error' event
      ^

 

Error: spawn C:\[working dir]\node_modules\esbuild\esbuild.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    [... lines matching original stack trace ...]
    at processImmediate (internal/timers.js:434:9) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\[working dir]\\node_modules\\esbuild\\esbuild.exe',
  path: 'C:\\[working dir]\\node_modules\\esbuild\\esbuild.exe',
  spawnargs: [ '--service=0.12.24', '--ping' ]
}

```

A bit of googling later I found this: https://github.com/vitejs/vite/issues/1361

It seems like I never got esbuild install.js to run...

## 🔬 Minimal Reproduction

1. get an angular 12.2.4 project working without having esbuild install.js having run
2. `ng build --aot -c production`

I fixed it with `npm install esbuild --save-dev`

## 🔥 Exception or Error

```


      throw er; // Unhandled 'error' event
      ^

 

Error: spawn C:\[working dir]\node_modules\esbuild\esbuild.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    [... lines matching original stack trace ...]
    at processImmediate (internal/timers.js:434:9) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\[working dir]\\node_modules\\esbuild\\esbuild.exe',
  path: 'C:\\[working dir]\\node_modules\\esbuild\\esbuild.exe',
  spawnargs: [ '--service=0.12.24', '--ping' ]
}

```

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.4
Node: 14.15.0
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 12.2.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.4
@angular-devkit/build-angular   12.2.4
@angular-devkit/core            12.2.4
@angular-devkit/schematics      12.2.4
@schematics/angular             12.2.4
rxjs                            7.3.0
typescript                      4.4.2
webpack                         5.51.2
</code></pre>

**Anything else relevant?**

**Comment by bbarry** [comment] 2021-09-03 14:14
Why would esbuild's install.js script not run when it is installed as a transitive dependency via `@angular-devkit/build-angular` but does run when installed directly as a dev dependency?

Would it be better as a peer?

**Comment by alan-agius4** [comment] 2021-09-03 14:59
Have you tried to removing `node_modules` and `package-lock.json`?

Webpack, babel and esbuild should not be installed in the project when using `@angular-devkit/build-angular` and adding there as dependencies in your project is highly discouraged.

The fact that the Angular CLI uses these packages is an implementation detail.

For the reason why the post install script is not running. It seems to be more of an environment issue which we the Angular team cannot action. 

I suggest you to try to use a different package manager such as Yarn, maybe it interacts better with the software that your IT team has installed. If the problem persists after that, and you still suspect it’s caused by the software installed by your IT team, I suggest to take it up with them and investigate the issue together.

**Comment by alan-agius4** [comment] 2021-09-04 10:51
Closing as per above.

**Closed by alan-agius4** 2021-09-04 10:51 UTC
