### ISSUE TITLE
git add after ng generate command

### ISSUE THREAD

**Issue by robert-king** [angular/angular-cli#10346] opened 2018-04-16 01:32 UTC
it would be cool if

`ng -g component foobar --git-add`

added the component to git

although this is probably overkill / unnecessary :)

**Comment by jainanuj0812** [comment] 2018-04-18 13:16
I think it will be unnecessary probably. Most of the git related stuff are handled by editor itself.

Anyways after creating the component, the user is going to change the component according to his/her needs which will ultimately throw back the files which are generated and added by this command in **not staged** changes.

**Comment by alan-agius4** [comment] 2019-02-05 11:18
Duplicate of https://github.com/angular/angular-cli/issues/7948

**Closed by alan-agius4** 2019-02-05 11:18 UTC
