### ISSUE TITLE
"ERROR in" (without any description!)

### ISSUE THREAD

**Issue by maiasmith** [angular/angular-cli#7152] opened 2017-07-26 22:00 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.3
node: 7.2.1
os: darwin x64
@angular/animations: 4.3.0
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.1.3
@angular/compiler-cli: 4.3.0
@angular/language-service: 4.3.0

### Repro steps.
`npm test` (which runs ng test) will not produce the error when "`npm test`" is newly run, but rather after the following sequence of circumstances:

1. a legit error occurs (producing a full error message)
2. test code is updated to fix the error
3. test code is saved 
4. tests are automatically rebuilt.

### The log given by the failure.
ERROR in

A more detailed example here:
```

Chrome 59.0.3071 (Mac OS X 10.12.1): Executed 37 of 37 (2 FAILED) (0.993 secs / 0.947 secs)

ERROR in
25 07 2017 11:18:59.338:INFO [karma]: Delaying execution, these browsers are not ready: Chrome 59.0.3071 (Mac OS X 10.12.1)

ERROR in
^CMac-mini:presentation-template-ng2 maiasmith$ npm test

> presentation-template-ng2@0.0.0 test /Users/maiasmith/git_repos/presentation-template-ng2
> ng test

 10% building modules 1/1 modules 0 active25 07 2017 11:19:46.712:WARN [karma]: No captured browser, open http://localhost:9876/
25 07 2017 11:19:46.721:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
25 07 2017 11:19:46.721:INFO [launcher]: Launching browser Chrome with unlimited concurrency
25 07 2017 11:19:46.733:INFO [launcher]: Starting browser Chrome
25 07 2017 11:20:00.040:WARN [karma]: No captured browser, open http://localhost:9876/
25 07 2017 11:20:00.278:INFO [Chrome 59.0.3071 (Mac OS X 10.12.1)]: Connected on socket RWEtd4dKrVY_6B8xAAAA with id 69718589
Chrome 59.0.3071 (Mac OS X 10.12.1): Executed 1 of 37 (skipped 36) SUCCESS (0.23 secs / 0.097 secs)
```

### Desired functionality.
No error at all, since tests pass once I restart the test runner (command-C, then "npm test").

**Comment by filipesilva** [comment] 2017-07-31 10:49
Not sure what's causing this but it is unintended.

**Comment by jongunter** [comment] 2017-09-06 17:00
I'm experiencing this too. 

Building on what @maiasmith said, its not a super reproducible pattern, but it seems I usually experience the error after adding a new spec file, or after fixing an an error in a spec.  Even more interesting, the console seems frozen/laggy when it reaches this state (there's often a few second wait (in Win8) between pressing `ctrl` + `c`  and getting the `Terminate batch job (Y/N)?` prompt). 

My versions:
```
@angular/cli: 1.3.2
node: 6.11.0
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
```

**Comment by drewloomer** [comment] 2017-09-13 14:34
Is anyone else who is experiencing this problem running their tests out of a different directory than their application? I am writing a plugin that has a `docs` directory where the main app lives, and then a `lib` directory where most of the source code is. When I point `.angular-cli.json` to find the tests outside of the app directory I start to see this error.

**Comment by TrevorBroderick1** [comment] 2017-09-13 16:55
@drewloomer Same scenario as me. The project is a shared code library, so the main app is in a different folder than the shared code and tests.

**Comment by clydin** [comment] 2018-09-25 17:58
Closing as version `1.1.3`/`1.3.2` is no longer supported. If the problem persists within the latest stable version (currently 6.2.3), please open a new issue detailing the problem.

**Closed by clydin** 2018-09-25 17:58 UTC
Labels: comp: devkit/build-angular, freq2: medium, severity5: regression, type: bug/fix
