### ISSUE TITLE
Angular outputs the same bundle hash for different localized app (using the same baseHref)

### ISSUE THREAD

**Issue by nhanpdnguyen** [angular/angular-cli#20623] opened 2021-04-25 15:44 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 No

### Description

In my other app, I need to serve 2 localized SSR version under single endpoint ("/").
What I did was based on the `lang` cookie, require the correspondent `dist` folder of the localized angular app and handle the request.
However, Angular build process produces the same bundle hash for both localized apps which result to the browser cache the these files and the localization breaks.

## 🔬 Minimal Reproduction

1. Pull and install the app from this repo: https://github.com/nhanpdnguyen/angular-i18n-bug
2. Run `npm run build -- --configuration=production`
3. View the `dist` folder. 

**Expected result:**
The bundle file name in `dist/en` folder (ex: `main-es5.2837a5083c11ef5082e3.js`) should be different from the file in `dist/fr`

**Actual result:**
The bundle file name in `dist/en` folder (ex: `main-es5.2837a5083c11ef5082e3.js`) is the same with the file in `dist/fr`

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.2.10
Node: 14.16.0
OS: darwin x64

Angular: 11.2.11
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.10
@angular-devkit/build-angular   0.1102.10
@angular-devkit/core            11.2.10
@angular-devkit/schematics      11.2.10
@angular/cli                    11.2.10
@schematics/angular             11.2.10
@schematics/update              0.1102.10
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Anything else relevant?**
The content of `main-es5.2837a5083c11ef5082e3.js` in this example is different in `dist/en` and `dist/fr` (see the first line of this file) but its name was being produced with the same bundle hash.

**Comment by alan-agius4** [comment] 2021-04-25 15:50
Duplicate of https://github.com/angular/angular-cli/issues/17416

**Closed by alan-agius4** 2021-04-25 15:50 UTC
