### ISSUE TITLE
Typescript compile angular.json 'scripts': ['core.ts']

### ISSUE THREAD

**Issue by DutchKevv** [angular/angular-cli#17913] opened 2020-06-11 19:29 UTC
# 🚀 Feature request

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Describe the solution you'd like
Compile typescript bundle, output bundle.js standalone

### Describe alternatives you've considered

- Setting up custom webpack (to easy for getting corrupted)
- add some script to package.json after build (but does not work when serving)

Lets say:
I have the front-end in Angular (duh)
I have a seperate Cordova / Ionic etc code base
I have a seperate 'external' page
I have a special way of 'bootstrapping'

But I want all of them, to 'bootstrap' a bundle.js **_before_** Angular, written in Typescript.
How do we do it?

Could be i'm missing something, but looked all over google, so... 

How do we 'bundle' a script ->

`"scripts": [
              {
                "input": "src/external/index.ts",
                "lazy": true,
                "bundleName": "core"
              }
            ],`

so that it compiles to core.js? 
Using the same tsconfig, etc as the Angular app. So we can --watch and load (<script src="core.js"></script>)?

Thanks

**Comment by alan-agius4** [comment] 2020-06-11 19:44
Duplicate of https://github.com/angular/angular-cli/issues/17125

**Closed by alan-agius4** 2020-06-11 19:44 UTC

**Comment by DutchKevv** [comment] 2020-06-11 19:58
@alan-agius4 

Thanks for the quick response, but that timeline doesn;t give an answer ... 
It shows how to make an npm script that compiles a file, its 0% angular way.

can you re-open please?

**Comment by DutchKevv** [comment] 2020-06-11 20:41
So anyway, fixed!

Follow this path to create a custom webpack.config.ts ->
https://www.digitalocean.com/community/tutorials/angular-custom-webpack-config

In the config, add an entry ->
` entry: {
    core: join(__dirname, 'src/external/index.ts'),
  },`

In your index.html, add a script ->
`  <script src="core.js"></script>`

And there you go, a build of a separate package, with a watcher on it from Angular. So you can bootstrap external code and still build it following the Angular build :)
