### ISSUE TITLE
Stats file generated by ng build --stats-json cannot be parsed by analyzers

### ISSUE THREAD

**Issue by beeman** [angular/angular-cli#10589] opened 2018-05-02 04:06 UTC
### Versions
```
Angular CLI: 6.0.0-rc.9
Node: 9.5.0
OS: darwin x64
Angular: 6.0.0-rc.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.12
@angular-devkit/build-angular     0.5.12
@angular-devkit/build-optimizer   0.5.12
@angular-devkit/core              0.5.12
@angular-devkit/schematics        0.5.12
@angular/cli                      6.0.0-rc.9
@ngtools/webpack                  6.0.0-rc.10
@schematics/angular               0.5.12
@schematics/update                0.5.12
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps

* `ng new test-app`
* `cd test-app`
* `ng build --stats-json`
* `npx webpack-bundle-analyzer ./dist/test-app/stats.json`

### Observed behavior

![image](https://user-images.githubusercontent.com/36491/39504809-d91b69ea-4d93-11e8-974c-5b55b90f8d42.png)

### Desired behavior

File should be parsed by the analyzer.

### Mention any other details that might be useful (optional)

Another place where it's broken:

- Upload the file `dist/test-app/stats.json` to https://webpack.github.io/analyse/

- The file does not get parsed by https://webpack.github.io/analyse/
- An error appears in the console:

```
Uncaught TypeError: Cannot read property 'sort' of undefined
    at r (web.js:1)
    at Object.e.load (web.js:1)
    at FileReader.e.onload (8.568a26e05565c8025a86.js:1)
```

**Comment by flamingbug** [comment] 2018-05-04 12:17
Same in full release.

**Comment by pumano** [comment] 2018-05-06 19:32
I confirm. Same problem. Webpack bundle analyzer not working in Angular 6

**Comment by visurel** [comment] 2018-05-07 14:53
Not working, tried various combinations of --build-optimizer=false and named chunks, vendor bundles, nothing works, the result is always the same as above.

**Comment by tmakin** [comment] 2018-05-12 17:48
This is now working fine with Webpack Bundle Analyzer 2.11.2
https://www.npmjs.com/package/webpack-bundle-analyzer

**Comment by beeman** [comment] 2018-05-12 19:34
Thanks @tmakin - confirmed it works:

```
npx webpack-bundle-analyzer@latest ./dist/test-app/stats.json
```

Or just install the latest version globally: 

```
npm i -g webpack-bundle-analyzer@latest
```

![image](https://user-images.githubusercontent.com/36491/39960912-00ac456e-55f1-11e8-9372-b86c5b7e37f3.png)


Probably good to keep the issue open until [webpack.github.io/analyse](https://webpack.github.io/analyse/) works too.

**Comment by beeman** [comment] 2018-05-12 21:43
Looks like https://webpack.github.io/analyse is broken because of [this issue](https://github.com/webpack/analyse/issues/30)...

**Comment by santonica** [comment] 2018-06-26 01:17
--stats-json supplied to an Angular library build emits an unknown option message. Is this applicable only for an application build?

**Comment by alan-agius4** [comment] 2018-07-30 12:39
Will be fixed by: https://github.com/webpack/analyse/pull/37

**Comment by JohannesHoppe** [comment] 2018-10-23 12:12
The PR is still open, but I sucessfully tested this against angular 6.0.4. / @angular/cli 6.0.8
The issue might be obsolete?

**Comment by muradm** [comment] 2018-11-01 04:50
Same here with `7.0.2`, fresh new project.

**Comment by LosD** [comment] 2018-11-05 09:11
@JohannesHoppe Are you using lazy-loaded modules? I don't think it's an issue otherwise, looking at the fix from @alan-agius4

**Comment by shinigamiCZ** [comment] 2018-11-05 09:56
Some hardcore workaround:
If you intent to use https://webpack.github.io/analyse:
1) add breakpoint before file parsing fails (use the devtools to navigate to error source)
2) save `t` or whatever that should contain `.modules` to global variables via devtools
3) paste 
```javascript
temp1.modules = [];
for(const chunk of temp1.chunks) {
    temp1.modules.push(... chunk.modules);
}
```
4) ??? 
5) profit 

You can even see reasons why something was included - which was the main reason i attempted to use that tool

**Comment by romulocintra** [comment] 2018-11-08 12:31
Just works perfect with : 

Angular CLI: 7.0.4
Node: 10.1.0
OS: darwin x64
Angular: 7.0.2

**Comment by intellix** [comment] 2018-11-22 10:09
@alan-agius4 PR was submitted in July and has yet to be looked at let alone merged. The last commit to Webpack Analyser was 2 years ago. I'm thinking it's time to remove the reference to the abandonware in the help text:

```
  --stats-json
    Generates a 'stats.json' file which can be analyzed using tools such as: #webpack-bundle-analyzer' or https: //webpack.github.io/analyse
```

**Comment by alan-agius4** [comment] 2019-02-12 08:24
Hi, I'm sorry, but this issue is not caused by Angular CLI. 

As @intellix correctly mentioned in his comment above https://github.com/angular/angular-cli/issues/10589#issuecomment-440979327 there are other alternatives that work such as [source-map-explorer](https://www.npmjs.com/package/source-map-explorer). 

Unfortunately  https://github.com/webpack/analyse seems to be unmaintained, sometime ago I did create a PR to fix this however it was never looked at https://github.com/webpack/analyse/pull/37. Also, this same issue is being tracked in their issue tracker here: https://github.com/webpack/analyse/issues/30.

**Comment by alan-agius4** [comment] 2019-02-12 08:37
@juarezpaf, webpack-bundle-analyzer` seems to be working.

**Closed** 2019-02-13 15:53 UTC
