### ISSUE TITLE
ng build --prod   error  occur  !!  no such file or directory, open 'schema/loader.json'

### ISSUE THREAD

**Issue by Christian-Yang** [angular/angular-cli#6761] opened 2017-06-21 06:38 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.1.1
node: 6.9.0
os: linux x64
@angular/animations: 4.2.3
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/core: 4.2.3
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.3
@angular/language-service: 4.2.3

```

### Repro steps.

ng  build --prod  

### The log given by the failure.

```
[root@localhost ngportal]# ng build --prod
ENOENT: no such file or directory, open '/media/B/CodeForNgPortal/ngportal/ngportal/schema/loader.json'
Error: ENOENT: no such file or directory, open '/media/B/CodeForNgPortal/ngportal/ngportal/schema/loader.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at validateOptions (/media/B/CodeForNgPortal/ngportal/ngportal/node_modules/schema-utils/dist/validateOptions.js:35:27)
    at Function.ExtractTextPlugin.extract (/media/B/CodeForNgPortal/ngportal/ngportal/node_modules/extract-text-webpack-plugin/index.js:206:3)
    at rules.push.baseRules.map (/media/B/CodeForNgPortal/ngportal/ngportal/node_modules/@angular/cli/models/webpack-configs/styles.js:172:66)
    at Array.map (native)
    at Object.getStylesConfig (/media/B/CodeForNgPortal/ngportal/ngportal/node_modules/@angular/cli/models/webpack-configs/styles.js:160:33)
    at NgCliWebpackConfig.buildConfig (/media/B/CodeForNgPortal/ngportal/ngportal/node_modules/@angular/cli/models/webpack-config.js:21:31)
    at Class.run (/media/B/CodeForNgPortal/ngportal/ngportal/node_modules/@angular/cli/tasks/build.js:27:92)
    at Class.run (/media/B/CodeForNgPortal/ngportal/ngportal/node_modules/@angular/cli/commands/build.js:149:26)
    at Class.Command.validateAndRun (/media/B/CodeForNgPortal/ngportal/ngportal/node_modules/@angular/cli/ember-cli/lib/models/command.js:128:15)
    at /media/B/CodeForNgPortal/ngportal/ngportal/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:92:22
    at tryCatch (/media/B/CodeForNgPortal/ngportal/ngportal/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/media/B/CodeForNgPortal/ngportal/ngportal/node_modules/rsvp/dist/rsvp.js:554:13)
    at /media/B/CodeForNgPortal/ngportal/ngportal/node_modules/rsvp/dist/rsvp.js:629:16
[root@localhost ngportal]# 
```

### Desired functionality.

nothing

### Mention any other details that might be useful.

ng build  work  normal  

ng build --dev work  normal  

ng build --prod work  occur  errors 

Looking forward to your help! thank!

**Comment by jiverson** [comment] 2017-06-22 00:10
I just tried and couldn't reproduce. Maybe a local issue or need more info, possibly update ng?

**Comment by Christian-Yang** [comment] 2017-06-22 04:12
@jiverson   
in node_modules , i  can  see ：
```
# Change Log

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

<a name="2.1.1"></a>
## [2.1.1](https://github.com/webpack-contrib/extract-text-webpack-plugin/compare/v2.1.0...v2.1.1) (2017-06-08)


```
is it a bug of  extract-text-webpack-plugin ???
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/534

**Comment by Christian-Yang** [comment] 2017-06-26 02:59
update   extract-text-webpack-plugin in node_modules  to  version is 2.1.2   solve  my problem !!!

**Comment by filipesilva** [comment] 2017-06-26 16:22
Closing as it seems sorted.

**Closed by filipesilva** 2017-06-26 16:22 UTC
