### ISSUE TITLE
Generate CanDeactivate guard

### ISSUE THREAD

**Issue by vishnu-dev** [angular/angular-cli#16057] opened 2019-11-04 07:37 UTC
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
_**Generate guard needs to also have CanDeactivate as option.**_

Currently has only 3 options:
![Currently has only 3 options](https://user-images.githubusercontent.com/21088161/68105193-c664f280-ff03-11e9-99d8-844e391ae80b.png)

### Describe the solution you'd like
 Add CanDeactivate option while generating guards

### Describe alternatives you've considered
 I need to create a file and add CanDeactivate class myself.

**Comment by alan-agius4** [comment] 2019-11-04 09:49
Duplicate of https://github.com/angular/angular-cli/issues/15668

**Closed by alan-agius4** 2019-11-04 09:49 UTC
Labels: comp: schematics/angular, help wanted, type: feature
