### ISSUE TITLE
Lot of TypeScript and other errors with webpack.8 version

### ISSUE THREAD

**Issue by rajkgoel** [angular/angular-cli#1935] opened 2016-09-01 12:26 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
- Installed new version of Node 6.5.
- Installed latest version of Angular CLI Webpack 8, after uninstalling the last installed CLI that uses Broccoli.
- Generated the new project using "ng generate ..."
- ng server

4. The log given by the failure. Normally this include a stack trace and some
   more information.
`ar\platform-browser\src\facade\lang.d.ts:15:17
Cannot find name 'JSON'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:19:27
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:20:32
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:21:31
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:22:26
Cannot find name 'Array'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:23:16
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:24:18
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:25:17
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:26:19
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:27:15
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:29:46
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:40:25
Cannot find name 'FunctionConstructor'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:41:30
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:47:9
A rest parameter must be of an array type.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:51:25
Cannot find name 'DateConstructor'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:56:51
Cannot find name 'String'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:59:54
Cannot find name 'Object'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:63:49
Cannot find name 'Date'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:67:58
Cannot find name 'Map'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:72:36
Cannot find name 'RegExp'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:77:39
Cannot find name 'RegExp'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:79:45
Cannot find name 'RegExp'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:89:46
Cannot find name 'Error'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:106:27
Cannot find name 'RegExpConstructor'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:108:21
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:109:20
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:109:43
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:113:44
Cannot find name 'Object'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:116:35
Cannot find name 'Error'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:116:43
Cannot find name 'Object'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:117:34
Cannot find name 'Error'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:117:42
Cannot find name 'Object'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:119:29
Cannot find name 'Object'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:120:27
Cannot find name 'Object'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:123:137
Cannot find name 'Date'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:124:39
Cannot find name 'Date'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:125:35
Cannot find name 'Date'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:126:26
Cannot find name 'Date'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:127:18
Cannot find name 'Date'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:128:24
Cannot find name 'Date'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\facade\lang.d.ts:136:46
Cannot find name 'Object'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\web_workers\shared\client_message_broker.d.ts:32:64
Cannot find name 'Promise'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\web_workers\shared\client_message_broker.d.ts:40:55
Cannot find name 'Promise'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\web_workers\shared\serializer.d.ts:10:36
Cannot find name 'Object'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\web_workers\shared\service_message_broker.d.ts:27:75
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\web_workers\shared\service_message_broker.d.ts:35:67
A rest parameter must be of an array type.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\web_workers\shared\service_message_broker.d.ts:35:83
Cannot find name 'Promise'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\web_workers\worker\location_providers.d.ts:21:85
Cannot find name 'Promise'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\worker_app.d.ts:6:52
Cannot find name 'Array'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\worker_app.d.ts:13:55
Cannot find name 'Array'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\worker_render.d.ts:35:52
Cannot find name 'Array'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\worker_render.d.ts:40:51
Cannot find name 'Array'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\@angul
ar\platform-browser\src\worker_render.d.ts:44:54
Cannot find name 'Array'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\rxjs\O
bservable.d.ts:10:65
Cannot find name 'Promise'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\rxjs\O
bservable.d.ts:11:68
Cannot find name 'ArrayLike'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\rxjs\O
bservable.d.ts:38:19
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\rxjs\O
bservable.d.ts:66:59
Cannot find name 'Promise'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\rxjs\O
bservable.d.ts:66:69
Cannot find name 'Promise'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\rxjs\S
ubject.d.ts:23:19
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\rxjs\S
ubscription.d.ts:4:60
Cannot find name 'Function'.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\typesc
ript\lib\lib.es2015.d.ts:17:0
File 'C:/Projects/Angular2/TestProject/node_modules/typescript/lib/lib.
es2015.core.d.ts' not found.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\typesc
ript\lib\lib.es2015.d.ts:18:0
File 'C:/Projects/Angular2/TestProject/node_modules/typescript/lib/lib.
es2015.collection.d.ts' not found.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\typesc
ript\lib\lib.es2015.d.ts:19:0
File 'C:/Projects/Angular2/TestProject/node_modules/typescript/lib/lib.
es2015.generator.d.ts' not found.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\typesc
ript\lib\lib.es2015.d.ts:20:0
File 'C:/Projects/Angular2/TestProject/node_modules/typescript/lib/lib.
es2015.iterable.d.ts' not found.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\typesc
ript\lib\lib.es2015.d.ts:21:0
File 'C:/Projects/Angular2/TestProject/node_modules/typescript/lib/lib.
es2015.promise.d.ts' not found.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\typesc
ript\lib\lib.es2015.d.ts:22:0
File 'C:/Projects/Angular2/TestProject/node_modules/typescript/lib/lib.
es2015.proxy.d.ts' not found.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\typesc
ript\lib\lib.es2015.d.ts:23:0
File 'C:/Projects/Angular2/TestProject/node_modules/typescript/lib/lib.
es2015.reflect.d.ts' not found.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\typesc
ript\lib\lib.es2015.d.ts:24:0
File 'C:/Projects/Angular2/TestProject/node_modules/typescript/lib/lib.
es2015.symbol.d.ts' not found.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\typesc
ript\lib\lib.es2015.d.ts:25:0
File 'C:/Projects/Angular2/TestProject/node_modules/typescript/lib/lib.
es2015.symbol.wellknown.d.ts' not found.

ERROR in [default] C:\Projects\Angular2\TestProject\node_modules\typesc
ript\lib\lib.es2015.d.ts:26:0
File 'C:/Projects/Angular2/TestProject/node_modules/typescript/lib/lib.
es5.d.ts' not found.
`

5. Mention any other details that might be useful.
Same errors appear after I upgraded to typescript@2.0.2
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wjke** [comment] 2016-09-01 12:56
lock typescript version to 2.0.0

**Comment by rakibler** [comment] 2016-09-01 13:05
@rajkgoel see https://github.com/angular/angular-cli/issues/1901#issuecomment-243679698

**Comment by filipesilva** [comment] 2016-09-21 01:33
Dupe of https://github.com/angular/angular-cli/issues/1901

**Closed by filipesilva** 2016-09-21 01:33 UTC
