### ISSUE TITLE
File / class deleted during tree shake despite the fact it's being used

### ISSUE THREAD

**Issue by ssmartin** [angular/angular-cli#16246] opened 2019-11-21 09:44 UTC
### Is this a regression?

 Yes, the previous version in which this bug was not present was: .Angular 7

### Description

I have a service / configuration  that we provide dynamically based on decorator. 

Looks like this: 
```
@Injectable()
@Configuration({ deps: [] })
export class VehiclePickerConfiguration extends NewPickerConfiguration {

    constructor() {
        super(VEHICLE_CONFIG);
    }
}

```

Basically we register (add to a static map) this configuration / service metadata (and many others) by using our custom annotation / decorator. Later on, this configuration / service is provided on the fly using the following code: 

```
 injectorProviders = injectorProviders.concat({ provide: metaData.constructor, useClass: metaData.constructor, deps: metaData.deps });
        this.createInjector(injectorProviders);
```

Then this VehicleConfigurationis is requested / used in two other different files / classes like this: 

`let configuration: VehiclePickerConfiguration = this.getPickerConfiguration<VehiclePickerConfiguration>(FieldContainers.RentContract.RentContract_booking_vehiclePriceList_vehicle); 
`

Long story short, we have some generic code to provide these services / configurations on the fly and this worked very well until Angular 8. 
But since Angular 8 the whole file (_vehicle.configuration_) where this configuration is written is basically tree shake (deleted) during compile time and this gives us extra headaches and causing bus in our application. 

IF i provide this _VehicleConfiguration_ manually anywhere in the app then the file is not deleted anymore, but this in our case defeats the purpose of providing and creating the instances of these services ONLY when they are needed.  

## 🔥 Exception or Error
The file is deleted most probably during the tree shake process even if it's used (imported and referenced in two other files / classess) and due to this we will have unexpected results (the vehicle configuration is not created and we get and undefined exception)

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.17
Node: 10.15.3
OS: win32 x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.17
@angular-devkit/build-angular     0.803.17
@angular-devkit/build-optimizer   0.803.17
@angular-devkit/build-webpack     0.803.17
@angular-devkit/core              8.3.17
@angular-devkit/schematics        8.3.17
@angular/cli                      8.3.17
@ngtools/webpack                  8.3.17
@schematics/angular               8.3.17
@schematics/update                0.803.17
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.41.2

</code></pre>

Thank you.

**Comment by alan-agius4** [comment] 2019-11-21 10:37
This seems to be caused because previously you leveraged on a bug which caused classes that had custom decorators not being tree-shaken away.

This bug was fixes in version 8 and now unused classes with custom decorators are also tree-shaken away.

> The file is deleted most probably during the tree shake process even if it's used (imported and referenced in two other files / classess) 

Are you referring to the below?
```ts
let configuration: VehiclePickerConfiguration = 
this.getPickerConfiguration<VehiclePickerConfiguration>(FieldContainers.RentContract.RentContract_booking_vehiclePriceList_vehicle);
```

The above are type references only which will cause the `VehiclePickerConfiguration` to be tree shaken away unless it is referenced such as injected via DI.

**Comment by ssmartin** [comment] 2019-11-21 11:11
> ```ts
> ```ts
> 
> ```
> 
> 
> The above are type references only which will cause the VehiclePickerConfiguration to be tree shaken away unless it is referenced such as injected via DI.
> ```

I understand and also noticed this ( that if I provide it manually or inject it then is not tree shake ), but this is not ok from mu point of view. Basically with this limitation the dynamic providing and injecting is not possible anymore. This for us is a major downgrade. 
We also face similar issuues with Components that are created dynamically using the ComponentResolver and which is also not working fine anymore event thought the component is declared in the entryComponents section of its module. This  also worked just fine until we upgraded to Angular 8.  But for that I will open a different ticket. 

Back to this topic, we don’t want to statically inject these services, we want to provide them when needed only and seems that currently this is not possible anymore?

**Comment by alan-agius4** [comment] 2019-11-21 11:32
@ssmartin did you mean to share some code?

**Comment by alan-agius4** [comment] 2019-11-21 11:51
Indeed, it is not possible to retain a piece of code which is not statically referenced. 

A workaround would be to mark this used something along;

```ts
window.retain = [
  VehicleConfiguration 
]
```

Or add to `VehicleConfiguration ` to the list of `providers` in your module.

The `@inject` without a reference is designed to tree-shake unused service. This was introduced in Angular version 6 under the name Tree Shakeable Providers. Tree Shakeable Providers are a way to define services and other things to be used by Angular’s dependency injection system that will be tree-shaken unless used.

https://angular.io/guide/dependency-injection-providers#tree-shakable-providers

**Comment by ssmartin** [comment] 2019-11-21 12:03
Hi @alan-agius4  

Sorry for the typo before - just wanted to highlight some part of your first response. 

I am aware of these workarounds (I see them really as workarounds and not as a solution to my problem), but I still think that is really bad to delete the whole file when that type is imported and referenced in other parts of the applications, parts which is not dead code at all.

I'm not even sure if I should open the other ticket (which I mentioned above) because probably I'll get the same reply as here, to use the window.retain which for me is really an ugly workaround...

**Comment by alan-agius4** [comment] 2019-11-21 12:13
> but I still think that is really bad to delete the whole file when that type is imported and referenced in other parts of the applications, parts which is not dead code at all.

A type doesn't have any JS representation and is used for type-checking:

For example;
```ts
class Foo {}
let foo: Foo|undefined;
console.log(foo)
```

Will produce 
```ts
class Foo { }
let foo;
console.log(foo);

```

Notice that In the above example class `Foo` in used.

Now when passing the above to a minifier like terser. It will produce the below;
```js
console.log(void 0);
```

**Comment by ssmartin** [comment] 2019-11-21 12:18
Hi @alan-agius4 

I understand that, but I hope you can also understand that something that was supposed to help us (the tree shake) is now causing some ugly side effects when you want to do more advanced stuff like providing dynamically some services ONLY when they are needed.

**Comment by dgp1130** [comment] 2019-11-21 18:10
Since decorators are assumed to not have side effects, this isn't really supported behavior within Angular.

**Comment by ssmartin** [comment] 2019-11-21 20:35
Hi @dgp1130 

OK, that's fine, but this is not really about decorators - it's about providing a way to dynamically provide some services via StaticInjectors and then later being able to use / create instances of them by requesting them from the injector. This was working very well for us, and now it's not working anymore ...and not because Angular would not support this, but because the file is tree shake during the build process. For us this is at least weird and kind of defeats the whole purpose of the tree shaking concept.

**Comment by ssmartin** [comment] 2019-11-21 20:50
I will provide here a second scenario when the tree shake is causing us problem, after upgrading to ANgular 8. IF you then say I should create a different ticket, I will do it. 

We have basically some components that we create dynamically using the ComponentResolver but first we need to get the type based on the name of the component (this we have from some metamodel information). 

We use this code to get the type: 

 // application angular component are kept into a factories map
    ```
    const factsMap: Map<any, any> = (<any>this._componentFactoryResolver)._factories;
        const iterator: IterableIterator<any> = factsMap.entries();

 let result: Type<any>;
        let currentEntry: any;
        let currentValue: any;
        // iterate through the component factories map
        do {
            currentValue = undefined;
            currentEntry = iterator.next();

            // unwrap current value and check if the name of the component (class) matches the one that is search for
            if (currentEntry && currentEntry.value) {
                currentValue = currentEntry.value;
            }

            if (currentValue && currentValue[0].name === compName) { 
                // if component with search name was found, store its type(a.k.a class) and break the loop
                result = currentValue[0];
                break;
            }
        } while (currentValue);
...
```

These code was working fine and we were getting the type of the components that we will then create dynamically. Now this code is failing even though our component is declared in the _entryComponents_ section of the right module.
What I noticed is that if our component (that we want to find the way described above) extends an abstract class, then the code above still works, but otherwise not anymore.
This happens only in production mode (running ng build...). 

Any ideas on this one? SHould I create a different ticket for this? 

Thank you in advance.

**Comment by alan-agius4** [comment] 2019-11-22 08:30
Hi again @ssmartin,

> For us this is at least weird and kind of defeats the whole purpose of the tree shaking concept.

Tree-shaking will remove unused side-effect free code. In Angular custom decorators on classes are treated to be side effect free meaning that classes with a custom decorators that are unused will be removed by design.

> This was working very well for us, and now it's not working anymore ...and not because Angular would not support it, 

Previously this used to work because of a bug in `@angular-devkit/build-optimizer` which caused classes with custom decorators not to be marked as pure and thus always retained in the final bundle.  This bug used to cause custom decorators on the classes to allow side-effects at a global level, which in your cases were leveraging.  

The current behaviour in Angular is that custom decorators are treated as side-effect free.

**Comment by ssmartin** [comment] 2019-11-22 08:51
Hi @alan-agius4  and thank you for the reply and patience. 

I understand all this, but would be nice if you would provide a special decorator or annotation that would prevent tree shaking to remove that class. The window.retain is an ugly hack / workaround, from my point of view. 

Best regards,
Sergiu

**Comment by vikerman** [comment] 2019-12-05 18:13
We are not supporting decorators with global side-effects. This issue provides a workaround for this(referencing from the window).

**Closed by vikerman** 2019-12-05 18:13 UTC
Labels: comp: devkit/build-optimizer, need: further discussion
