### ISSUE TITLE
TSLint is deprecated

### ISSUE THREAD

**Issue by nainardev** [angular/angular-cli#17378] opened 2020-04-03 02:40 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
:+1: 

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

In [release post](https://blog.angular.io/version-9-1-of-angular-now-available-typescript-3-8-faster-builds-and-more-eb292f989428) of angular v9.1

> #### TSLint 6.1 by default
> Newly created projects will now use TSLint 6.1 by default. If you want to migrate to the latest version, make sure you are on version 9.1 first, then you can opt-in via:
> ```sh
> ng update @angular/cli --migrate-only tslint-version-6
> ```

TSLint is deprecated and migration to ESLint is advised according to its docs

**Comment by devoto13** [comment] 2020-04-03 07:08
This is duplicate of https://github.com/angular/angular-cli/issues/13732.

Here is the official answer: https://github.com/angular/angular-cli/issues/13732#issuecomment-575796158

**Comment by alan-agius4** [comment] 2020-04-03 07:41
Closing as per above comment

**Closed by alan-agius4** 2020-04-03 07:41 UTC
