### ISSUE TITLE
TypeScript skipLibCheck flag is not respected in templates

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular-cli#13050] opened 2018-11-26 13:00 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

**node**: v10.13.0
**npm**: 6.4.1
**Angular CLI**:
```
Angular CLI: 7.0.6
Node: 10.13.0
OS: darwin x64
Angular: 7.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
```

### Repro steps
Execute the following command:

```
git clone git@github.com:klemenoslaj/ngx-formly-aot-bug-report.git && cd ngx-formly-aot-bug-report && yarn && ng build --aot
```

Notice `ng build` is triggered with `--aot` command. With JIT compiler it works fine.

### The log given by the failure

```
ERROR in node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(7,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(6,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(5,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(10,18): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(10,18): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(16,23): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(16,23): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(16,23): : Element implicitly has an 'any' type because type 'FormlyFieldConfig' has no index signature.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(20,23): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(20,23): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(20,23): : Element implicitly has an 'any' type because type 'FormlyFieldConfig' has no index signature.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(28,17): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/textarea/ngx-formly-material-textarea.d.ts.FormlyFieldTextArea.html(9,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/textarea/ngx-formly-material-textarea.d.ts.FormlyFieldTextArea.html(4,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/textarea/ngx-formly-material-textarea.d.ts.FormlyFieldTextArea.html(7,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/textarea/ngx-formly-material-textarea.d.ts.FormlyFieldTextArea.html(8,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/radio/ngx-formly-material-radio.d.ts.FormlyFieldRadio.html(3,25): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/checkbox/ngx-formly-material-checkbox.d.ts.FormlyFieldCheckbox.html(8,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/checkbox/ngx-formly-material-checkbox.d.ts.FormlyFieldCheckbox.html(9,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/checkbox/ngx-formly-material-checkbox.d.ts.FormlyFieldCheckbox.html(9,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/checkbox/ngx-formly-material-checkbox.d.ts.FormlyFieldCheckbox.html(7,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/checkbox/ngx-formly-material-checkbox.d.ts.FormlyFieldCheckbox.html(7,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/checkbox/ngx-formly-material-checkbox.d.ts.FormlyFieldCheckbox.html(9,54): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/checkbox/ngx-formly-material-checkbox.d.ts.FormlyFieldCheckbox.html(11,13): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/checkbox/ngx-formly-material-checkbox.d.ts.FormlyFieldCheckbox.html(11,13): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/multicheckbox/ngx-formly-material-multicheckbox.d.ts.FormlyFieldMultiCheckbox.html(2,19): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/select/ngx-formly-material-select.d.ts.FormlyFieldSelect.html(5,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/select/ngx-formly-material-select.d.ts.FormlyFieldSelect.html(7,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/select/ngx-formly-material-select.d.ts.FormlyFieldSelect.html(6,7): : Object is possibly 'undefined'.
node_modules/@ngx-formly/material/select/ngx-formly-material-select.d.ts.FormlyFieldSelect.html(12,21): : Object is possibly 'undefined'.
```

### Desired functionality

If a skipLibCheck flag is provided in TypeScript configuration, the compiler should not fail with the errors from node_modules.
This makes impossible to use certain libraries in projects with a strict mode of TypeScript.

**Comment by alan-agius4** [comment] 2018-11-26 13:15
Duplicate of https://github.com/angular/angular/issues/21353

**Closed by alan-agius4** 2018-11-26 13:15 UTC
