### ISSUE TITLE
'ng update @angular/cli' failed when we use npm package which is use git repo url directly!

### ISSUE THREAD

**Issue by liwonder** [angular/angular-cli#11146] opened 2018-06-07 05:26 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

node version: v8.11.2
npm version: 6.1.0
macOS (High Sierra 10.13.4 (17E202))

### Repro steps
we have a package.json file with a dependency using git repo url directly like below:
`
"dependencies": {
        "someRepo": "https://github.com/company/someRepo.git",
}
`

I was update our Angular 5.0 project to Angular 6.0, and according to the guideline in 'https://update.angular.io/'

`npm install -g @angular/cli`
`npm install @angular/cli`
`ng update @angular/cli`

### The log given by the failure
It will log 'someRepo' not found, and also the angular.json file is not found.

### Mention any other details that might be useful
when I remove this line, the update would be success.
` someRepo": "https://github.com/company/someRepo.git`

**Comment by alan-agius4** [comment] 2018-10-11 14:48
Duplicate of https://github.com/angular/angular-cli/issues/10642

**Closed by alan-agius4** 2018-10-11 14:48 UTC
Labels: type: bug/fix
