### ISSUE TITLE
service names in barrels use upper camel case instead of kebab case

### ISSUE THREAD

**Issue by timstoddard** [angular/angular-cli#1305] opened 2016-07-08 16:54 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

    Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

    angular-cli: 1.0.0-beta.8
    node: 6.1.0
    os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

    I used the command `ng g s SampleTest`.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

    The index.ts file created to export the service contained the following:
    `export * from './SampleTest.service';`

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

    The file should have contained `export * from './sample-test.service';` since SampleTest.service.ts   does not currently exist.

**Comment by timstoddard** [comment] 2016-07-08 17:14
just played around with cli some more, this is happening for pipes as well

**Comment by filipesilva** [comment] 2016-07-27 14:30
Dupe of https://github.com/angular/angular-cli/issues/1434. Yours was open first but the other one contains more information needed to fix the issue, so I'll track it there.

**Closed by filipesilva** 2016-07-27 14:30 UTC
