### ISSUE TITLE
ngc doesn't work

### ISSUE THREAD

**Issue by fplini** [angular/angular-cli#3601] opened 2016-12-16 16:53 UTC
### OS
Windows 7

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 6.9.1
os: win32 x64

### Repro steps.
Created with angular-cli

### The log given by the failure.
C:\dev\repo\new\easy-frontend>ngc
can't resolve module C:/dev/repo/new/easy-frontend/node_modules/@angular/core/src/di/reflective_key.d.ts from C:/dev/repo/new/easy-frontend/node_modules/@angular/core/src/di/reflective_key.d.ts
Error: can't find symbol KeyRegistry exported from module C:/dev/repo/new/easy-frontend/node_modules/@angular/core/src/di/reflective_key.d.ts
    at ReflectorHost.findDeclaration (C:\dev\repo\new\easy-app\node_modules\@angular\compiler-cli\src\reflector_host.js:173:23)
    at C:\dev\repo\new\easy-app\node_modules\@angular\compiler-cli\src\codegen.js:137:46
    at Array.forEach (native)
    at extractProgramSymbols (C:\dev\repo\new\easy-app\node_modules\@angular\compiler-cli\src\codegen.js:120:10)
    at CodeGenerator.codegen (C:\dev\repo\new\easy-app\node_modules\@angular\compiler-cli\src\codegen.js:57:29)
    at codegen (C:\dev\repo\new\easy-app\node_modules\@angular\compiler-cli\src\main.js:7:81)
    at Object.main (C:\dev\repo\new\easy-app\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (C:\dev\repo\new\easy-app\node_modules\@angular\compiler-cli\src\main.js:16:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
Compilation failed

Simply running "ngc"

**Comment by tobymurray** [comment] 2016-12-18 20:15
What is `ngc` intended to do? `ng help` doesn't reference that command, and in general commands take the form `ng <command>` with a space between the two.

**Comment by fplini** [comment] 2016-12-19 09:13
ngc is a command under node_modules/.bin
I use this also to run aot compiler (node_modules/.bin/ngc -p tsconfig-aot.json)
Till some weeks ago it worked fine. I'm new with NG2, so I want to build and compile the app project to make it more light and run in pre-prod env

**Comment by gelliott181** [comment] 2016-12-19 13:34
You want `ng build --aot` or `ng serve --aot` for lightweight code with develepment mode enabled ("pre-prod env").

**Comment by fplini** [comment] 2016-12-19 14:40
So if I run ng build --aot I receive this error
"10% building modules 3/3 modules 0 activeUnexpected value 'CustomFormsModule' imported by the module 'AppModule'
Error: Unexpected value 'CustomFormsModule' imported by the module 'AppModule'"

But is not bind to this module, if I remove "CustomFormModule" I receive the error again on other modules.
Suppose that I want deploy the app on prod env. I'd like to compile and compress all to reduce the app size. This is what I'm trying to do :)

**Comment by gelliott181** [comment] 2016-12-19 15:58
You're now building it properly, but your app's codebase is no longer compliant with the Angular 2 spec as the compiler defines and expects it. You should start looking at errors within your modules that prevent them from being analyzed and compiled properly.

For reference the commands to build (should be from heaviest to lightest) are
`ng b`
`ng b --aot`
`ng b --prod`
ng b --prod --aot`

Adding `--prod` runs produces minified code, but it's not particularly human readable so development isn't fun with it on.

**Comment by fplini** [comment] 2016-12-20 08:59
Thanks for you attention @gelliott181, so if I run "ng b" and "ng b --prod" all works fine. The problem seems to be when I run "ng b --aot" (that shows the error ahead). 
Maybe I can avoid the aot compilation. 
Do you know if "ng b --prod" is the right way to deploy on prod env?

**Comment by hansl** [comment] 2016-12-30 01:28
You should build with `ng build --aot --prod` to deploy to prod environment.

It seems like you have a problem with your app, which is hard to investigate. Please share a repo we can look at to reproduce your error. Also, try updating to the latest beta (24) which has a lot of fixes (as usual).

Running `ngc` should work from the command line but it might need a special `tsconfig.json` (the default one doesn't have angular compiler options). You do not need to run it though, the `--aot` flag does that same thing but in memory.

I'm going to close this, but if you have a project we can look at and your problem isn't resolved, please file a new issue.

**Closed by hansl** 2016-12-30 01:28 UTC
