### ISSUE TITLE
Serving but not building with lazyloading : ERROR in ./src/$$_gendir lazy

### ISSUE THREAD

**Issue by stefdelec** [angular/angular-cli#8733] opened 2017-12-04 08:41 UTC
### Versions
```
@angular/cli: 1.4.4
node: 8.9.1
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4
```

### Repro steps
ng serve => is working
ng build => not working

### Observed behavior
```
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\endpoints\file-reader\file-reader.module.ngfac
tory.ts' in 'C:\Users\mynameofuser\git\my-project-contracts\src\$$_gendir'
resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\endpoints\file-reader\file-reader.module.ngfactory.ts' in 'C:\Users\delecroix
s\git\my-project-contracts\src\$$_gendir'
  using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/node_modules/@my-project/my-project-core/src/app/endpoints/file-reader/file-
reader.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\endpoints\file-reader\file-reader.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\endpoints\file-reader\file-reader.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\endpoints\file-reader\file-reader.module.ngfactory.ts.js doesn't exist
      as directory
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\endpoints\file-reader\file-reader.module.ngfactory.ts doesn't exist
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\endpoints\file-reader\file-reader.module.ngfactory.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\endpoints\file-reader\file-reader.module.ngfactory.ts.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\endpoints\file-reader\file-reader.module.ngfactory.ts.js]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\endpoints\file-reader\file-reader.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\account-completion-form\account-compl
etion-form.module.ngfactory.ts' in 'C:\Users\mynameofuser\git\my-project-contracts\src\$$_gendir'
resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\account-completion-form\account-completion-form.module.ngfactory.ts'
 in 'C:\Users\mynameofuser\git\my-project-contracts\src\$$_gendir'
  using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/node_modules/@my-project/my-project-core/src/app/features/account-completion
-form/account-completion-form.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\account-completion-form\account-completion-form.module.ngfactory.ts d
oesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\account-completion-form\account-completion-form.module.ngfactory.ts.t
s doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\account-completion-form\account-completion-form.module.ngfactory.ts.j
s doesn't exist
      as directory
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\account-completion-form\account-completion-form.module.ngfactory.ts d
oesn't exist
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\account-completion-form\account-completion-form.module.ngfactory.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\account-completion-form\account-completion-form.module.ngfactory.ts.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\account-completion-form\account-completion-form.module.ngfactory.ts.js]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\account-completion-form\account-completion-form.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\faq-module\faq-module.module.ngfactor
y.ts' in 'C:\Users\mynameofuser\git\my-project-contracts\src\$$_gendir'
resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\faq-module\faq-module.module.ngfactory.ts' in 'C:\Users\mynameofuser\g
it\my-project-contracts\src\$$_gendir'
  using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/node_modules/@my-project/my-project-core/src/app/features/faq-module/faq-mod
ule.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\faq-module\faq-module.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\faq-module\faq-module.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\faq-module\faq-module.module.ngfactory.ts.js doesn't exist
      as directory
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\faq-module\faq-module.module.ngfactory.ts doesn't exist
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\faq-module\faq-module.module.ngfactory.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\faq-module\faq-module.module.ngfactory.ts.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\faq-module\faq-module.module.ngfactory.ts.js]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\faq-module\faq-module.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\newscast\newscast.module.ngfactory.ts
' in 'C:\Users\mynameofuser\git\my-project-contracts\src\$$_gendir'
resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\newscast\newscast.module.ngfactory.ts' in 'C:\Users\mynameofuser\git\v
ls-web-contracts\src\$$_gendir'
  using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/node_modules/@my-project/my-project-core/src/app/features/newscast/newscast.
module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\newscast\newscast.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\newscast\newscast.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\newscast\newscast.module.ngfactory.ts.js doesn't exist
      as directory
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\newscast\newscast.module.ngfactory.ts doesn't exist
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\newscast\newscast.module.ngfactory.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\newscast\newscast.module.ngfactory.ts.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\newscast\newscast.module.ngfactory.ts.js]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\newscast\newscast.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offer-configuration-module\offer-conf
iguration.module.ngfactory.ts' in 'C:\Users\mynameofuser\git\my-project-contracts\src\$$_gendir'
resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offer-configuration-module\offer-configuration.module.ngfactory.ts'
in 'C:\Users\mynameofuser\git\my-project-contracts\src\$$_gendir'
  using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/node_modules/@my-project/my-project-core/src/app/features/offer-configuratio
n-module/offer-configuration.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offer-configuration-module\offer-configuration.module.ngfactory.ts do
esn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offer-configuration-module\offer-configuration.module.ngfactory.ts.ts
 doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offer-configuration-module\offer-configuration.module.ngfactory.ts.js
 doesn't exist
      as directory
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offer-configuration-module\offer-configuration.module.ngfactory.ts do
esn't exist
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offer-configuration-module\offer-configuration.module.ngfactory.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offer-configuration-module\offer-configuration.module.ngfactory.ts.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offer-configuration-module\offer-configuration.module.ngfactory.ts.js]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offer-configuration-module\offer-configuration.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offers\offers.module.ngfactory.ts' in
 'C:\Users\mynameofuser\git\my-project-contracts\src\$$_gendir'
resolve 'C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offers\offers.module.ngfactory.ts' in 'C:\Users\mynameofuser\git\vls-w
eb-contracts\src\$$_gendir'
  using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/$$_gendir)
    using description file: C:\Users\mynameofuser\git\my-project-contracts\package.json (relative path: ./src/node_modules/@my-project/my-project-core/src/app/features/offers/offers.modu
le.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offers\offers.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offers\offers.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offers\offers.module.ngfactory.ts.js doesn't exist
      as directory
        C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offers\offers.module.ngfactory.ts doesn't exist
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offers\offers.module.ngfactory.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offers\offers.module.ngfactory.ts.ts]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offers\offers.module.ngfactory.ts.js]
[C:\Users\mynameofuser\git\my-project-contracts\src\node_modules\@my-project\my-project-core\src\app\features\offers\offers.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```

I've tried many options suggested in other issues, I am still getting the error.

Already tried solution:
1/ rm node_modules, npm cache clean npm i
2/ npm i -D webpack

**Comment by clydin** [comment] 2017-12-04 15:45
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?  Upgrading to the latest stable version (1.5.5) of the CLI may also be helpful.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by clydin** [comment] 2017-12-04 16:37
Does the project attempting to a load lazy route directly from a node module/package?  If so, this is not supported by the CLI.

**Comment by stefdelec** [comment] 2017-12-04 16:44
Yes it does. Any workaround?

**Comment by clydin** [comment] 2017-12-04 16:51
There's an open issue regarding the problem with a discussion and several potential suggestions and links to some others. The issue is here: https://github.com/angular/angular-cli/issues/6373

I'm going to close this as a duplicate but if you find that this is not the actual problem, feel free to re-open this.

**Closed by clydin** 2017-12-04 16:51 UTC
Labels: command: build, need: repro steps

**Comment by stefdelec** [comment] 2017-12-04 16:56
Thanks for the links.
