### ISSUE TITLE
Running ng e2e throws cannot find definition files 

### ISSUE THREAD

**Issue by woppa684** [angular/angular-cli#7198] opened 2017-07-29 10:35 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.6
node: 6.10.3
os: win32 x64
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.2

### Repro steps.
ng new test-app -si
update package.json so that it uses angular 4.3.2, angular cli 1.2.6 and typescript ^2.4.0
npm install
ng e2e

### The log given by the failure.
```
[12:12:39] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'jasmine'. (2688)
Cannot find type definition file for 'node'. (2688)
Cannot find type definition file for 'q'. (2688)
Cannot find type definition file for 'selenium-webdriver'. (2688)
e2e\app.e2e-spec.ts (1,35): Cannot find module './app.po'. (2307)
e2e\app.e2e-spec.ts (3,1): Cannot find name 'describe'. (2304)
e2e\app.e2e-spec.ts (6,3): Cannot find name 'beforeEach'. (2304)
e2e\app.e2e-spec.ts (10,3): Cannot find name 'it'. (2304)
e2e\app.e2e-spec.ts (12,5): Cannot find name 'expect'. (2304)
    at getOutput (D:\Sources\feat115\uipstn\ColorFeedback\node_modules\ts-node\src\index.ts:312:17)
    at D:\Sources\feat115\uipstn\ColorFeedback\node_modules\ts-node\src\index.ts:343:18
    at Object.compile (D:\Sources\feat115\uipstn\ColorFeedback\node_modules\ts-node\src\index.ts:476:19)
    at Module.m._compile (D:\Sources\feat115\uipstn\ColorFeedback\node_modules\ts-node\src\index.ts:406:44)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\Sources\feat115\uipstn\ColorFeedback\node_modules\ts-node\src\index.ts:409:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at D:\Sources\feat115\uipstn\ColorFeedback\node_modules\jasmine\lib\jasmine.js:93:5
    at Array.forEach (native)
    at Jasmine.loadSpecs (D:\Sources\feat115\uipstn\ColorFeedback\node_modules\jasmine\lib\jasmine.js:92:18)
    at Jasmine.execute (D:\Sources\feat115\uipstn\ColorFeedback\node_modules\jasmine\lib\jasmine.js:197:8)
    at D:\Sources\feat115\uipstn\ColorFeedback\node_modules\protractor\built\frameworks\jasmine.js:132:15
[12:12:39] E/launcher - Process exited with error code 100
```

### Desired functionality.
Working E2E tests

### Mention any other details that might be useful.
Looks like the same issue as https://github.com/angular/angular-cli/issues/5082 but that was fixed a while ago ...

**Comment by philmtd** [comment] 2017-07-30 15:10
I can confirm this, have the same issue. Moving back to typescript 2.2.1 works.

**Comment by woppa684** [comment] 2017-07-30 15:16
Upgrading ts-node to ~3.3.0 also seems to fix this by the way.

**Comment by filipesilva** [comment] 2017-07-31 12:43
Duplicate of https://github.com/angular/angular-cli/issues/7050, it's `ts-node` as you mentioned.

**Closed by filipesilva** 2017-07-31 12:43 UTC
