### ISSUE TITLE
Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "8.2.14". 

### ISSUE THREAD

**Issue by Shubham819** [angular/angular-cli#17809] opened 2020-05-28 07:07 UTC
Hi,
 I am using angular 8.2.14 with node 8.11. 
I am able to run the project.
I am using aot webpack 3.11 to build. 
So while building I m facing error. 
Version of @angular/compiler-cli needs to be greater than 2.3.1 current version is 8.2.14.
So below things I tried
Deleting node modules and pkg. Json and npm install no solution

**Comment by alan-agius4** [comment] 2020-05-28 07:09
Duplicate of #5558

**Closed by alan-agius4** 2020-05-28 07:09 UTC

**Comment by Shubham819** [comment] 2020-05-28 07:12
I did not get any solution out of that, hence created this

**Comment by alan-agius4** [comment] 2020-05-28 09:42
https://github.com/angular/angular-cli/issues/5558#issuecomment-288270864 should solve your issue.

if the issue persists, please file another issue and follow the issue template.
