### ISSUE TITLE
How to integrate a scss file (custom one)

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#1521] opened 2016-08-02 17:53 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
Beta 10 (webpack / master branch)

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
-

4. The log given by the failure. Normally this include a stack trace and some
   more information.
-

5. Mention any other details that might be useful.
-
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

I've just created a main.scss inside the public folder, and then included in my index.html the scss file but nothing happens, also this is a strange approach. Because I want a css file with a map file to the scss right?

**Comment by deebloo** [comment] 2016-08-02 19:01
as far as I know files in the public folder aren't compiled with sass. only files in your src directory

**Comment by deebloo** [comment] 2016-08-02 19:01
public should just be for static assets like fonts, standard stylesheets, etc

**Comment by sirajc** [comment] 2016-08-02 19:13
Duplicate of #1459

**Comment by masaanli** [comment] 2016-08-03 04:37
@deebloo If it's for static assets, how can i link to them then? Because when you run the application it can only access files inside the src folder.

**Comment by deebloo** [comment] 2016-08-03 15:20
@masaanli you don't. It it for things like images where you use the file path or css files that you include with <link>. things of that nature

**Comment by deebloo** [comment] 2016-08-03 15:22
if you have custom scss files they should be in src/

**Comment by masaanli** [comment] 2016-08-04 05:11
@deebloo Ok, so I'm making an folder called `assets/scss` inside the `src` folder. and put my `main.scss` file there.

**What approach?**
I reference to that scss file from my `index.html` or `as TemplateStyleUrl` inside the main app component?

**How is this working, referencing to a file in node_modules?**
If I install `bootstrap-sass` and import the reference in  `main.scss`.
So you will get inside the `main.scss` : import `node_modules\bootstrap-sass\bootstrap.scss`?

**Comment by filipesilva** [comment] 2016-08-10 18:37
Duplicate of https://github.com/angular/angular-cli/issues/1459, please comment there instead.

**Closed by filipesilva** 2016-08-10 18:37 UTC
