### ISSUE TITLE
Babel error during localized bundle generation v9.0.0-rc.10

### ISSUE THREAD

**Issue by thekip** [angular/angular-cli#16781] opened 2020-01-28 12:44 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, this is a kind of regression. I'm not sure about the root cause, it worked well in one of my previous setups with earlier RC versions. This might be as regression in AngularCli itself or because of different babel versions which I might install. 

### Description

An error:
```
Localized bundle generation failed: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
`
babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
`
See https://babeljs.io/docs/en/options#filename for more information.
An error occurred inlining file "main.bd935ccfc875481a7ad2.js"
```

The error came from `packages/angular_devkit/build_angular/src/utils/process-bundle.ts:614`

```ts
try {
    ast = parseSync(options.code, { // <--- Error here
      babelrc: false,
      sourceType: 'script',
    });
  } catch (error) {
    if (error.message) {
     ...
    }
  }
```

And obviously caused by lacking `filename` param.

![image](https://user-images.githubusercontent.com/1586852/73264449-1ede2000-41d3-11ea-8da3-22eddd8bc0d8.png)

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
To reproduce just add locales into `angular.json` `i18n.locales` and turn on `localize` in project options

(simplified angular.json)
```
  {
  "projects": {
    "timescenery": {
      "i18n": {
        "locales": {
          "ru": "src/translates/messages.ru.xlf",
          "de": "src/translates/messages.de.xlf",
          "es": "src/translates/messages.es.xlf",
          "pt": "src/translates/messages.pt.xlf"
        },
        "sourceLocale": "en"
      },
      "architect": {
        "build": {
          "options": {
            "localize": true,
            "aot": true,
          },
        },
      }
    }
  }
}

```

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.10
Node: 12.13.1
OS: darwin x64

Angular: 9.0.0-rc.11
... common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.10
@angular-devkit/build-angular     0.900.0-rc.10
@angular-devkit/build-optimizer   0.900.0-rc.10
@angular-devkit/core              9.0.0-rc.10
@angular-devkit/schematics        9.0.0-rc.10
@angular/cdk                      9.0.0-rc.8
@angular/cli                      9.0.0-rc.10
@schematics/angular               9.0.0-rc.10
@schematics/update                0.900.0-rc.10
rxjs                              6.5.3
typescript                        3.7.2
webpack                           4.41.5

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment] 2020-01-28 12:52
This might be caused by `@angular/localize` not pinning the Babel version?

**Comment by petebacondarwin** [comment] 2020-01-28 12:53
Can you show what version of each of the `@babel/....` packages are installed?

**Comment by thekip** [comment] 2020-01-28 13:21
quote from `yarn.lock`

Localize is pinning `@babel/core" "^7.5.5`

![image](https://user-images.githubusercontent.com/1586852/73267360-2f919480-41d9-11ea-8f2f-1803ad1017c1.png)


All  `@babel/core` versions deduped to 7.8.3

![image](https://user-images.githubusercontent.com/1586852/73267405-4cc66300-41d9-11ea-91ce-2d6ed06a17ea.png)

**Comment by thekip** [comment] 2020-01-28 14:14
Well, downgrading `@babel/core` and rest of babel packages to `7.7.2` fixes the problem, but requires some hard work to downgrade 2nd level dependencies. 

I think the issue is still actual as constatint in `@angular/localize` ^7.5.5 allows any `7.*.*` versions including `7.8.*` which is causing a crash.

**Comment by petebacondarwin** [comment] 2020-01-28 14:58
This might well be fixed by https://github.com/angular/angular/pull/34974, which is currently on master and should come out in the next RC.

**Comment by petebacondarwin** [comment] 2020-01-28 15:06
This might help too https://github.com/angular/angular/pull/35008

**Comment by thekip** [comment] 2020-01-28 15:14
What about adding a `filename` into `parseSync` call? Looks like bumping dependency for `localize` to `7.8.3` will just make this error constant for everyone, or am I wrong?

**Comment by petebacondarwin** [comment] 2020-01-28 15:16
Ah that will be a bug in `@angular/devkit` rather than `@angular/localize`. We need to fix that bug in this repo...

**Comment by petebacondarwin** [comment] 2020-01-28 15:20
Interestingly the version in `build_angular` is already at 7.8.3: https://github.com/angular/angular-cli/blob/ca7973e5e04983a3c708dd98f9818fc7862ad9ff/packages/angular_devkit/build_angular/package.json#L14

**Comment by petebacondarwin** [comment] 2020-01-28 15:26
See #16782

**Comment by thekip** [comment] 2020-01-28 15:30
Looks like i brought clutter to this issue. 
I continued investigation with debugger and what if found. 

This error is triggered from `@babel/core` only in case if `options.test || options.include || options.exclude` is not empty. 

I checked them, and `test` wasn't empty. There was an
![image](https://user-images.githubusercontent.com/1586852/73277738-e0545f80-41ea-11ea-85fb-1b70e3860e6c.png)

That was quite suspiciously, so i went further and found that: 

![image](https://user-images.githubusercontent.com/1586852/73277929-1e518380-41eb-11ea-9a7e-63786c7aa575.png)

Despite the fact `babelrc: false,` is set the babel still reads my `babel.config.js` placed in the root, and take presets from there, and on of the presets are require filename to be set. 

So I think problem here not only in `filename` property.

**Comment by thekip** [comment] 2020-01-28 15:31
I need this babel.config for my subpakages in mono-repo which use jest for testing, so this config has absolutely nothing in common with angular-cli

**Comment by thekip** [comment] 2020-01-28 15:41
So yes, deleting `babel.config.js` from root fixing the problem and proving theory that babel doesn't work in full isolation even `babelrc: false` is set.  

It also proves that problem not related to the version of bable.

**Comment by thekip** [comment] 2020-01-28 15:52
```ts
    ast = parseSync(options.code, { 
      babelrc: false,
      sourceType: 'script',
      configFile: false,
    });
```
Adding `configFile: false` ensures that babel will not use any kind of configs defined in a project

**Closed** 2020-01-28 18:22 UTC
Labels: comp: devkit/build-angular, freq1: low, severity3: broken, type: bug/fix
