### ISSUE TITLE
1.0.0-beta.31 ng update not updating angular-cli.json and packages.json

### ISSUE THREAD

**Issue by reaction1989** [angular/angular-cli#4580] opened 2017-02-10 08:45 UTC
Running ng -update just tries to update .editorconfig All other files are untouched

**Comment by anderaus** [comment] 2017-02-10 08:52
I believe I'm seeing the same issue. On Windows, running "ng update" after installing beta.31 prompts to override the first file only, then exits.

**Comment by g-mack** [comment] 2017-02-10 09:20
Same for me on Windows after updating to beta.31.

ng update starts and asks for Overwriting README.md.
If I type "d" and press enter on the "Diff" command, the process exits without error.

@angular/cli: 1.0.0-beta.31
node: 7.5.0
os: win32 x64
@angular/common: 2.2.1
@angular/compiler: 2.2.1
@angular/core: 2.2.1
@angular/forms: 2.2.1
@angular/http: 2.2.1
@angular/platform-browser: 2.2.1
@angular/platform-browser-dynamic: 2.2.1
@angular/router: 3.2.1
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.2.1

**Comment by ByJC** [comment] 2017-02-10 09:28
Hi everyone, 
I just updated the cli to the beta.31 version and when i run ng update, I got the following error

```
Unexpected token =
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/JC/Workspace/perso/ng-blog-posts/node_modules/@angular/cli/models/config.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/JC/Workspace/perso/ng-blog-posts/node_modules/@angular/cli/addon/index.js:4:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Function.Addon.lookup (/Users/JC/Workspace/perso/ng-blog-posts/node_modules/@angular/cli/ember-cli/lib/models/addon.js:218:19)
    at Project.initializeAddons (/Users/JC/Workspace/perso/ng-blog-posts/node_modules/@angular/cli/ember-cli/lib/models/project.js:305:29)
    at Project.eachAddonCommand (/Users/JC/Workspace/perso/ng-blog-posts/node_modules/@angular/cli/ember-cli/lib/models/project.js:359:10)
    at module.exports (/Users/JC/Workspace/perso/ng-blog-posts/node_modules/@angular/cli/ember-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/Users/JC/Workspace/perso/ng-blog-posts/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:42:26)
    at tryCatch (/Users/JC/Workspace/perso/ng-blog-posts/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/JC/Workspace/perso/ng-blog-posts/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/JC/Workspace/perso/ng-blog-posts/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/JC/Workspace/perso/ng-blog-posts/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by ptsydzik** [comment] 2017-02-10 09:50
@ByJC, You need to update typescript and ts-node modules

**Comment by ByJC** [comment] 2017-02-10 09:57
Thanks for the answer and sorry if it was not the place for asking this.

**Comment by filipesilva** [comment] 2017-02-10 10:35
Marking as dupe of https://github.com/angular/angular-cli/issues/4584 since that one has more detail.

**Closed by filipesilva** 2017-02-10 10:35 UTC
