### ISSUE TITLE
Angular complains about missing `index.ts` when it is there

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#16386] opened 2019-12-08 03:30 UTC
When running `ng serve -o` on a project that includes `@fireflysemantics/slice` I get the following error:

```
ERROR in ./node_modules/@fireflysemantics/slice/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /home/ole/Temp/sph/node_modules/@fireflysemantics/slice/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/ole/Temp/sph/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:900:23)
    at /home/ole/Temp/sph/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

I don't get this error in Stackblitz projects.  For example here's one with the most recent version of `@fireflysemantics/slice`:

https://stackblitz.com/edit/angular-slice-ngrx-scratch-demo-final-version9

Do we need do include the `index.ts` manually in the `files` or `include` property?

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes it has worked in all previous versions.

Simple steps to reproduce this bug.

```
ole@mkt:~/Temp$ ng new fstest
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss   
npm i -S @fireflysemantics/slice
```

Create this `app.component.ts`:

```
import { Component } from '@angular/core'
import { EStore} from '@fireflysemantics/slice'
class Todo {}
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  constructor() {
    const eStore:EStore<Todo> = new EStore()
    console.log(eStore)
  }
  title = 'fstest';
}
```
Now run `ng serve -o`

You should get the error.

## 🔥 Exception or Error
<pre><code>

ERROR in ./node_modules/@fireflysemantics/slice/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /home/ole/Temp/sph/node_modules/@fireflysemantics/slice/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/ole/Temp/sph/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:900:23)
    at /home/ole/Temp/sph/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
</code></pre>

## 🌍 Your Environment
<pre><code>
ole@mkt:~/Temp/fstest$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.5
Node: 12.6.0
OS: linux x64

Angular: 9.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.5
@angular-devkit/build-angular     0.900.0-rc.5
@angular-devkit/build-optimizer   0.900.0-rc.5
@angular-devkit/build-webpack     0.900.0-rc.5
@angular-devkit/core              9.0.0-rc.5
@angular-devkit/schematics        9.0.0-rc.5
@ngtools/webpack                  9.0.0-rc.5
@schematics/angular               9.0.0-rc.5
@schematics/update                0.900.0-rc.5
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Comment by EdricChan03** [comment] 2019-12-08 07:59
Based on the error log that you've pasted, I can pinpoint that it's caused by this issue

> The missing file seems to be part of a third-party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

As such, I looked at the [Unpkg CDN for the library you've specified](https://unpkg.com/browse/@fireflysemantics/slice@9.0.4/) and have discovered that a recent version of the library has unintentionally included an `index.ts` file in the package. This is the reason why your compilation didn't work.

For now, the resolution would be to revert back to a former version of the library that does not contain the `index.ts`. (In this case, it would be `v9.0.1`, which also has a [completely different format (the Angular Package Format!)](https://unpkg.com/browse/@fireflysemantics/slice@9.0.1/) from older versions of the same library - strange)

Hope this helps!

**Comment by Plochie** [comment] 2019-12-08 08:01
It's mistake by developer of @fireflysemantics/slice, as developer is including ts files in the library, this is not standard understandable by Angualr hence the error

Error: C:\Users\demo\Documents\angular\demong\node_modules@fireflysemantics\slice\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property. The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library.

Until the developer makes the changes in the library, you need to remove index.ts file from node_modules\@fireflysemantics\slice.

After removing index.ts, angular will use valid index.js from same directory.

After removing the index.ts file, ng serve again, it should work.

Also until developer fixes it, you can add following in package.json to start your application by npm start. It'll take care of the file.

"start": "rm node_modules/@fireflysemantics/sliceng/index.ts && ng serve",

Please close this, as this is not angular issue.

**Comment by EdricChan03** [comment] 2019-12-08 08:13
@Plochie Have you realised that the author of this issue is the library author? Strange why the library author would post an issue here?

**Comment by Plochie** [comment] 2019-12-08 08:19
@EdricChan03, realized after your comment. I think there is no point discussing this further. :) As this is clearly not angular-cli issue.

**Comment by alan-agius4** [comment] 2019-12-08 10:41
Closing as per the above comments.

**Closed by alan-agius4** 2019-12-08 10:41 UTC
