### ISSUE TITLE
ng lint is ignoring linterOptions property of the tslint config file

### ISSUE THREAD

**Issue by michaeljota** [angular/angular-cli#11951] opened 2018-08-20 14:51 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting (search: `linterOptions`)
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: v8.11.2
npm: 6.0.1
ng:
```
Angular CLI: 1.6.3
Node: 8.11.2
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

Add a `linterOptions` property in the `tslint.json` config file, and configure a `exclude` list of files globs to be ignored. 

```json
{
  "linterOptions": {
    "exclude": [
      "/**/*.spec.ts"
    ]
  },
}
```

### The log given by the failure

spec files are linting anyway.

### Desired functionality

spec files should not be checked.

**Comment by alan-agius4** [comment] 2018-08-21 08:56
Duplicate of #11773

**Comment by michaeljota** [comment] 2018-08-21 14:46
Will try. Thanks!

**Closed** 2018-08-21 18:17 UTC
Labels: comp: devkit/build-angular
