### ISSUE TITLE
Cant find sock.js on safari

### ISSUE THREAD

**Issue by lakinmohapatra** [angular/angular-cli#8481] opened 2017-11-14 11:08 UTC
Its showing "Cant find sock.js on safari" .
Seems like a webpack issue .

Also its showing reference issue . ReferenceError: Can't find variable: overlayDiv

Please help

**Comment by bryjohns** [comment] 2017-11-14 20:29
Duplicate of #8400

**Comment by Brocco** [comment] 2017-11-15 16:48
Closing as a duplicate.

**Closed by Brocco** 2017-11-15 16:48 UTC
