### ISSUE TITLE
Optimize index.html

### ISSUE THREAD

**Issue by jelbourn** [angular/angular-cli#22559] opened 2022-01-24 18:27 UTC
While working on angular.io, I noticed that the site includes a number of both HTML and inline JS comments. That led me to note that the HTML and inline JS includes whitespace. In the grand scheme of things this is pretty minor, but it would be nice if the CLI could apply a few basic, safe optimizations for `index.html`:

- Remove comments (probably configurable for HTML comments which can theoretically be load-bearing)
- Remove non-significant whitespace (e.g. any whitespace outside of `<body>`)
- Optimize inline JS (needs some due diligence to make sure this is safe) and CSS (much safer)

**Comment by alan-agius4** [comment] 2022-01-24 18:31
Duplicate of https://github.com/angular/angular-cli/issues/11360

**Closed by alan-agius4** 2022-01-24 18:31 UTC
