### ISSUE TITLE
The update schematic for version 9 should remove entryComponents.

### ISSUE THREAD

**Issue by sfabriece** [angular/angular-cli#16913] opened 2020-02-10 12:10 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...

According to update instructions, entryComponents are no longer needed for IVY.
### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Add a schematic to remove entryComponents in existing codebases.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Doing it manually

**Comment by elvisbegovic** [comment] 2020-02-10 12:30
Hi, this should be opened on angular/angular (as it concern angular schematics migration).
But it is duplicate of https://github.com/angular/angular/issues/34399

**Comment by elvisbegovic** [comment] 2020-02-10 12:32
Hi, good idea ! (this should be opened on angular/angular as it concern angular schematics migration).
But it is duplicate of https://github.com/angular/angular/issues/34399

**Comment by alan-agius4** [comment] 2020-02-10 13:13
Closing as duplicate of #34399

**Closed by alan-agius4** 2020-02-10 13:13 UTC
