### ISSUE TITLE
ng new [PROJECT NAME], eslint is not added by default. (Angular CLI: 12.2.4)

### ISSUE THREAD

**Issue by qyjs** [angular/angular-cli#21717] opened 2021-09-07 07:22 UTC
### Description

Angular CLI: 12.2.4

ng new [PROJECT NAME]

After this command is executed, eslint is not added by default

### Proposed solution

Add eslint by default

### Alternatives considered

eslint

**Comment by alan-agius4** [comment] 2021-09-07 11:49
Closing as this is indeed by design

**Closed by alan-agius4** 2021-09-07 11:49 UTC

**Comment by alan-agius4** [comment] 2021-09-07 11:51
Duplicate of https://github.com/angular/angular-cli/issues/20769
