### ISSUE TITLE
Allow comments in .angular-cli.json

### ISSUE THREAD

**Issue by mxii** [angular/angular-cli#5610] opened 2017-03-24 07:43 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Versions.
v1.0.0

### Repro steps.
ng s

### The log given by the failure.
InvalidConfigError: Parsing .angular-cli.json failed. Please make sure your .angular-cli.json is valid JSON. Error:
SyntaxError: Unexpected token / in JSON at position 533

### Desired functionality.
Would be really great to be able to put comments to that file. :)

**Comment by aslan92** [comment] 2017-03-24 09:34
JSON file can not contain comments!

**Comment by yarrgh** [comment] 2017-03-24 12:31
JSON format doesn't allow comments. This is not a limitation with the CLI. It's a limitation of JSON itself.

**Comment by filipesilva** [comment] 2017-03-24 14:48
Closing as the community already answered this, thanks guys!

**Comment by filipesilva** [comment] 2017-03-24 14:55
Actually, let's keep this open... I misread it as a bug report, but it's a very reasonable feature request.

**Comment by bekos** [comment] 2017-08-28 17:18
Sorry if you have answered it elsewhere, but can this file actually be a `.js` file instead of `.json`.
It will be much more flexible and easier to work with.

**Comment by filipesilva** [comment] 2017-08-31 15:38
@bekos no, that is not supported.

**Comment by bekos** [comment] 2017-08-31 16:26
@filipesilva This would help if we actually needed a bit different setup for production and development setups in angular-cli. Does this make sense for a new feature request?

**Comment by filipesilva** [comment] 2017-08-31 17:06
@bekos I'm curious on the particulars of your scenario. Can you open a new issue to discuss your request?

**Comment by manuel-di-iorio** [comment] 2017-09-15 13:23
Would be nice to use https://www.npmjs.com/package/strip-json-comments

```js
const json = '{/*rainbows*/"unicorn":"cake"}';
 
JSON.parse(stripJsonComments(json));
//=> {unicorn: 'cake'} 
```

**Comment by listepo** [comment] 2017-12-26 20:53
I think `strip-json-comments` this is a very good solution. @filipesilva what do you think?

**Comment by aristotll** [comment] 2018-02-09 08:58
I think this is a great feature and the `tsconfig.json` also allows comments, https://github.com/Microsoft/TypeScript/issues/4987.

The config files need comments for clarification and future reading.

**Comment by thorn0** [comment] 2018-02-13 10:59
We can probably borrow this "JSON with comments" parser from VS Code:
https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/json.ts

**Comment by alan-agius4** [comment] 2018-10-30 13:59
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2018-10-30 13:59 UTC
Labels: effort1: easy (hours), priority: 3 (nice to have), type: feature
