### ISSUE TITLE
Object shorthand syntax can't be used in module decorator

### ISSUE THREAD

**Issue by briansokol** [angular/angular-cli#5210] opened 2017-03-03 17:50 UTC
If you use object property shorthand syntax in a decorator and run a build, you will get an error that seems to indicate that the property is not read at all.

### OS
macOS Sierra 10.12.3

### Versions
@angular/cli: 1.0.0-rc.0
node: 7.5.0
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.9

### Repro steps
Run `ng new ShortHandBug --routing`

Update **app.module.ts** so that the imports are in a separate array and then add it to the decorator:

```TypeScript
const imports = [
  BrowserModule,
  FormsModule,
  HttpModule,
  AppRoutingModule
];

@NgModule({
  declarations: [
    AppComponent
  ],
  imports,
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Run `ng build` or `ng build --aot`

### The log given by the failure
If you run `ng build`:

```shell
ERROR in (moduleMetadata.imports || []).filter is not a function
```

If you run `ng build --aot`:

```shell
ERROR in Template parse errors:
'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
  {{title}}
</h1>
[ERROR ->]<router-outlet></router-outlet>
"): AppComponent@3:0

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/[...]/ShortHandBug/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

### Mention any other details that might be useful
There is no issue when running `ng serve`.

Changing it to `{imports: imports}` also fixes the issue.

**Comment by Brocco** [comment] 2017-03-06 14:37
I have just tested this with rc.1 and was not able to reproduce. Can you please re-test with the latest version of the CLI?

**Comment by briansokol** [comment] 2017-03-06 15:17
Thanks for testing it. Unfortunately, I'm still seeing the issue with the latest version. I tried with Node 7.5 and then upgraded to 7.7.1 and tried again. Just in case it mattered, I also tried installing dependencies with both Yarn and NPM, same result.

If no one else is able to reproduce this, I'm willing to accept that it's just something weird with my machine.

**Comment by beeman** [comment] 2017-03-07 20:45
Can reproduce on Ubuntu 16.04.2 LTS

```
@angular/cli: 1.0.0-rc.1
node: 7.7.1
os: linux x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9
```

```
root@beeman:~/ShortHandBug# ng build
Hash: 6a94d2e8206e3118acbe
Time: 12951ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 153 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 5.44 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.77 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.69 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in (moduleMetadata.imports || []).filter is not a function
root@beeman:~/ShortHandBug# cat src/app/app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

const imports = [
    BrowserModule,
    FormsModule,
    HttpModule,
    AppRoutingModule
]

@NgModule({
  declarations: [
    AppComponent
  ],
  imports,
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```


I tend to use object destructuring for this use case, but `imports: imports` works too and is shorter: 

```
  imports: [
    ...imports,
  ],
```

**Comment by filipesilva** [comment] 2018-02-01 21:05
Hello, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

Angular CLI always runs *some* statical analysis, even on JIT mode, in order to discover lazy-loaded routes.
This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

Below are good resources on how to to debug these errors:
- https://angular.io/guide/metadata
- https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60
- https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts

If your problem still persists, it might be a bug with the Angular Compiler itself.
In that case, please open an issue in https://github.com/angular/angular.

**Closed by filipesilva** 2018-02-01 21:05 UTC
Labels: comp: cli/build, freq1: low, priority: 2 (required), type: bug
