### ISSUE TITLE
Server does not restart automatically when there was a change

### ISSUE THREAD

**Issue by nyoman** [angular/angular-cli#3026] opened 2016-11-05 01:43 UTC
> I am starting a new project using Angular 2 CLI (angular-cli: 1.0.0-beta.16). But when I made a change, I have to restart the server manually because it does not react to the change or changes as it should be.

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-11-05 15:58
Dupe of https://github.com/angular/angular-cli/issues/2833

**Closed by filipesilva** 2016-11-05 15:58 UTC

**Comment by nyoman** [comment] 2016-11-07 15:59
Now it works. Thanks. 

    On Saturday, November 5, 2016 10:58 PM, Filipe Silva <notifications@github.com> wrote:
 

 Dupe of #2833—

**Comment by JJkip** [comment] 2016-11-08 08:34
How was this resolved? I uninstalled cli then updated npm to version 3.10.8, then  installed cli but still the server does not refresh. Even when i clear my browser cache and refresh it no update is made. I have to _ng serve_ to update the code changes. Please help.

**Comment by nyoman** [comment] 2016-11-08 11:12
I have the same problem. I had another file of the same version of CLI (beta 19), but It works with no problem. But when I created another new app, I have to restart (ng serve) every time after making a change.
 

    On Tuesday, November 8, 2016 3:34 PM, JayJay <notifications@github.com> wrote:
 

 How was this resolved? I uninstalled cli then updated npm to version 3.10.8, then installed cli but still the server does not refresh. Even when i clear my browser cache and refresh it no update is made. I have to ng serve to update the code changes. Please help.—

**Comment by JJkip** [comment] 2016-11-08 11:31
@filipesilva this issue seems not be resolved. The old angular 2.0.0 with cli 1.0.0-beta.15 doesn't have this issue but with this latest cli 1.0.0-beta.19 release it's chaos.

**Comment by JJkip** [comment] 2016-11-08 12:03
I am using OSX Elcapitan version 10.11.6

**Comment by sayedrakib** [comment] 2016-11-16 16:20
I have the same problem, but in my case if AppComponent is changed and saved, it reload and detect the chages. but changes made in child component does not reload. I have
angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: linux x64
