### ISSUE TITLE
ng new app fails to fully initialize an angular project

### ISSUE THREAD

**Issue by pcnate** [angular/angular-cli#22452] opened 2022-01-06 13:28 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
I did not experience this issue the last time I created an Angular project which would have been ~10.x

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

```shell
pcnate@newvm:~/$ npm install --global @angular/cli
pcnate@newvm:~/$ ng --version

Angular CLI: 13.1.2
Node: 16.13.1
Package Manager: npm 8.1.2
OS: linux x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.2
@angular-devkit/core         13.1.2
@angular-devkit/schematics   13.1.2
@angular/cli                 13.1.2
@schematics/angular          13.1.2

pcnate@newvm:~/$ mkdir newProject && cd newProject
pcnate@newvm:~/newProject$ git init
Initialized empty Git repository in /home/pcnate/newProject/.git/
pcnate@newvm:~/newProject$ ng new my-app
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss                ]
CREATE my-app/README.md (1051 bytes)
CREATE my-app/.editorconfig (274 bytes)
CREATE my-app/.gitignore (620 bytes)
CREATE my-app/angular.json (3207 bytes)
CREATE my-app/package.json (1070 bytes)
CREATE my-app/tsconfig.json (863 bytes)
CREATE my-app/.browserslistrc (600 bytes)
CREATE my-app/karma.conf.js (1423 bytes)
CREATE my-app/tsconfig.app.json (287 bytes)
CREATE my-app/tsconfig.spec.json (333 bytes)
CREATE my-app/.vscode/extensions.json (130 bytes)
CREATE my-app/.vscode/launch.json (474 bytes)
CREATE my-app/.vscode/tasks.json (938 bytes)
CREATE my-app/src/favicon.ico (948 bytes)
CREATE my-app/src/index.html (291 bytes)
CREATE my-app/src/main.ts (372 bytes)
CREATE my-app/src/polyfills.ts (2338 bytes)
CREATE my-app/src/styles.scss (80 bytes)
CREATE my-app/src/test.ts (745 bytes)
CREATE my-app/src/assets/.gitkeep (0 bytes)
CREATE my-app/src/environments/environment.prod.ts (51 bytes)
CREATE my-app/src/environments/environment.ts (658 bytes)
CREATE my-app/src/app/app-routing.module.ts (245 bytes)
CREATE my-app/src/app/app.module.ts (393 bytes)
CREATE my-app/src/app/app.component.scss (0 bytes)
CREATE my-app/src/app/app.component.html (23364 bytes)
CREATE my-app/src/app/app.component.spec.ts (1073 bytes)
CREATE my-app/src/app/app.component.ts (211 bytes)
✔ Packages installed successfully.
    Directory is already under version control. Skipping initialization of git.
pcnate@newvm:~/newProject$ ls -lah
total 16K
drwxr-xr-x 4 pcnate pcnate   4.0K Jan  6 13:22 .
drwxrwxr-x 7 pcnate www-data 4.0K Jan  6 13:20 ..
drwxr-xr-x 7 pcnate pcnate   4.0K Jan  6 13:20 .git
drwxr-xr-x 5 pcnate pcnate   4.0K Jan  6 13:23 my-app
pcnate@newvm:~/newProject$ ng serve
The serve command requires to be run in an Angular project, but a project definition could not be found.
pcnate@newvm:~/newProject$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

## 🔥 Exception or Error

1. angular.json is not created
2. package.json is not updated with dependencies

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 13.1.2
Node: 16.13.1
Package Manager: npm 8.1.2
OS: linux x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.2
@angular-devkit/core         13.1.2
@angular-devkit/schematics   13.1.2
@angular/cli                 13.1.2
@schematics/angular          13.1.2</code></pre>

**Anything else relevant?**

<pre><code>
pcnate@newvm:~/newProject$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
</code></pre>

**Comment by JoostK** [comment] 2022-01-06 13:52
The project is being created in its own directory; after `ng new` you'd have to `cd` into that directory before you can run `ng serve`.

**Comment by pcnate** [comment] 2022-01-08 21:24
ok. That makes sense now and I feel dumb for not noticing that bit. Is it possible to have it point to a root folder and amend the package.json file as it is created?

**Comment by JoostK** [comment] 2022-01-08 23:00
I don't think that is possible, no.

**Comment by alan-agius4** [comment] 2022-01-09 10:33
Closing as this is working as intended.

**Closed by alan-agius4** 2022-01-09 10:33 UTC
