### ISSUE TITLE
TSLint is deprecated

### ISSUE THREAD

**Issue by fr0** [angular/angular-cli#16695] opened 2020-01-17 19:29 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description.

`ng lint` should no longer use `tslint`, but instead should use https://github.com/typescript-eslint/typescript-eslint.

**Comment by alan-agius4** [comment] 2020-01-17 19:32
Duplicate of https://github.com/angular/angular-cli/issues/13732

**Closed by alan-agius4** 2020-01-17 19:32 UTC
