### ISSUE TITLE
es-build is failing on non relative scss imports 

### ISSUE THREAD

**Issue by vlio20** [angular/angular-cli#25427] opened 2023-06-22 20:37 UTC
### Command

ng build --configuration production --verbose

### Is this a regression?

No

### The previous version in which this bug was not present was

No

### Description

When building my application with esbuild (angular.json):
```
"builder": "@angular-devkit/build-angular:browser-esbuild",
```

I am getting the error: `Can't find stylesheet to import.`

### Minimal Reproduction

I am running:
```
ng build --configuration production --verbose
```

### Exception or Error

```text
⠧ Building...✘ [ERROR] Can't find stylesheet to import.
  ╷
1 │ @import 'src/app/common/styles/mixins';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/app/sections/competition-group/pages/competition-groups-list/competition-group-list.component.scss 1:9  root stylesheet [plugin angular-sass]
```
```


### Your Environment

```text
mac / ci (github actions)
```

### Anything else relevant?

No

**Comment by alan-agius4** [comment] 2023-06-23 05:59
Duplicate of https://github.com/angular/angular-cli/issues/23698

**Closed by alan-agius4** 2023-06-23 05:59 UTC
