### ISSUE TITLE
error while using ng new

### ISSUE THREAD

**Issue by eshwarmore1993** [angular/angular-cli#1268] opened 2016-07-02 07:09 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 8.1

Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Krishna\AppData\Roaming\npm\node_modules\ang
ular-cli\node_modules\ember-cli\lib\models\project.js:11:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by JoshWilliams92** [comment] 2016-07-02 11:34
Navigate to the folder where you have globally installed angular-cli and run npm install. Also, navigate to angular-cli in node modules where you have created a new project and npm install again.

**Comment by CoderAjay** [comment] 2016-07-02 17:34
Angular-cli is looking locally for modules( angular-cli deps ), where as it should look for globally.

**Comment by filipesilva** [comment] 2016-07-03 22:15
Dupe of https://github.com/angular/angular-cli/issues/1186.

**Closed by filipesilva** 2016-07-03 22:15 UTC

**Comment by eshwarmore1993** [comment] 2016-07-04 07:19
thank you. it helped
