### ISSUE TITLE
`ng` no longer supports source in an npm package

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular-cli#8963] opened 2017-12-21 18:44 UTC
### Versions
```
Angular CLI: 1.6.1
Node: 8.9.3
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

From https://github.com/angular/angular/issues/20091#issuecomment-352976046

```sh
$ git clone git@github.com:chuckjaz/repro-20091.git
$ cd repro-20091
$ yarn install
$ ng build
```

### Observed behavior
```
ERROR in ./node_modules/angular-bootstrap-md/index.ts
Module build failed: Error: ./node_modules/angular-bootstrap-md/index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (./node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:649:23)
    at plugin.done.then (./node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 9:0-58
 @ ./src/main.ts
 @ multi ./src/main.ts
```

### Desired behavior

No error message.

### Mention any other details that might be useful (optional)

This works with Angular 4.4.2 which can be demonstrated by:

1. `git checkout adac6d359dbc1efa1ca70ef290f90359794b0ee1`
2. `yarn install`
3. `ng build`

`ng --version`
```
Angular CLI: 1.6.1
Node: 8.9.3
OS: darwin x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.3.4
webpack: 3.10.0
```

**Comment by filipesilva** [comment] 2017-12-21 19:25
This issue is a duplicate of https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325.

In that issue an in-depth explanation of what changed is included. The short version is that files that are meant to be compiled by TypeScript must be listed in `src/tsconfig.app.json`. There is currently a bug with AOT compilation where this isn't required (https://github.com/angular/angular/issues/20115), but that should be fixed in the future.

**Closed by filipesilva** 2017-12-21 19:25 UTC
