### ISSUE TITLE
bug cli@6.0.0-beta5: ng build --prod include all compiler in final bundle

### ISSUE THREAD

**Issue by sandangel** [angular/angular-cli#9914] opened 2018-03-09 08:06 UTC
### Versions
```bash
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
$ ng version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 6.0.0-beta.5
Node: 8.10.0
OS: win32 x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.2.4
@angular/cli: 6.0.0-beta.5
@angular/flex-layout: 5.0.0-beta.13
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.4.5
@angular-devkit/core: 0.4.5
@angular-devkit/schematics: 0.4.5
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.5
@schematics/angular: 0.4.5
@schematics/package-update: 0.4.5
typescript: 2.6.2
webpack-bundle-analyzer: 2.11.1
webpack: 4.0.1
```

Windows 10, yarn 1.5.1, npm 5.7.1, node 8.10.0

### Repro steps

I can only provide the stats.json file generated by this command: 

`ng build --prod --sm --output-hashing=false --stats-json`

angular 1.7.3:
[stats.txt](https://github.com/angular/angular-cli/files/1796028/stats.txt)

angular 6.0.0-beta5:
https://ufile.io/0p2ke

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```
angular/cli 1.7.3
![image](https://user-images.githubusercontent.com/22189661/37197047-7aabbf14-23bc-11e8-89b6-0da36e66201e.png)

angular/cli 6.0.0-beta5
![image](https://user-images.githubusercontent.com/22189661/37196945-1719e0f2-23bc-11e8-8967-915d90ad4615.png)

### Desired behavior

No compiler in final bundle when build with --prod

**Comment by omahjoub** [comment] 2018-03-09 11:09
Hi, I'm seeing the same issue.

> Angular CLI: 6.0.0-beta.5
> Node: 9.5.0
> OS: darwin x64
> Angular: 6.0.0-beta.7
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> angular/cli: 6.0.0-beta.5
> angular-devkit/build-optimizer: 0.4.5
> angular-devkit/core: 0.4.5
> angular-devkit/schematics: 0.4.5
> ngtools/json-schema: 1.2.0
> ngtools/webpack: 6.0.0-beta.5
> schematics/angular: 0.4.5
> schematics/package-update: 0.4.5
> typescript: 2.6.2
> webpack: 4.0.1

`ng build --prod`

> chunk {main} main.js, main.js.map (main) 778 kB [initial] [rendered]
> chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 224 kB [initial] [rendered]
> chunk {runtime} runtime.js, runtime.js.map (runtime) 5.09 kB [entry] [rendered]
> chunk {scripts} scripts.js, scripts.js.map (scripts) 293 kB  [rendered]
> chunk {styles} styles.js, styles.js.map (styles) 424 kB [initial] [rendered]
> chunk {vendor} vendor.js, vendor.js.map (vendor) **5.27 MB** [initial] [rendered]

But Running `ng build --target=production` seems to be good :

> chunk {scripts} scripts.7919ccceb3b0018336c0.js (scripts) 288 kB  [rendered]
> chunk {0} runtime.5f9d33fb31487f0fdbf1.js (runtime) 1.05 kB [entry] [rendered]
> chunk {1} styles.3b9328888a1ada1ada41.css (styles) 313 kB [initial] [rendered]
> chunk {2} polyfills.f0578259d90544bd90ad.js (polyfills) 59.1 kB [initial] [rendered]
> chunk {3} main.37c0d0a04c33ab0e7152.js (main) **1.9** MB [initial] [rendered]

**Comment by hansl** [comment] 2018-03-09 18:03
Yes.  In our refactoring of flags we removed the old parsing code and thus `--prod` was removed (as it was a weird alias case), and we forgot to put it back as a special flag. This will be addressed in the next beta.

For now you can use the long form `--target=production`.

**Comment by code2nguyen** [comment] 2018-04-23 21:57
It **does not** work for me
```
 #ng build --target=production
Project 'production' could not be found in workspace.
Error: Project 'production' could not be found in workspace.
```

**Comment by alan-agius4** [comment] 2019-02-05 12:02
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2019-02-05 12:02 UTC
