### ISSUE TITLE
webpackJsonp is not defined 

### ISSUE THREAD

**Issue by fabienbranchel** [angular/angular-cli#8026] opened 2017-10-12 15:08 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report 
- [ ] feature request
```

### Versions.
Output from: `ng --version`.
@angular/cli: 1.4.6
node: 6.11.3
os: darwin x64
@angular/animations: 4.4.4
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.6
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
@angular/service-worker: 1.0.0-beta.16
typescript: 2.3.4
macOS  Sierra 10.12.6

Android Devices : 
- Samsung Galaxy S7 Edge, Android 7.0, Chrome 61.0.3163.98 
- Motorola Moto E4, Android 7.1.1, Chrome 61.0.3163.98 
- Pixel C, Android 8.0,  Chrome 61.0.3163.98

### Repro steps.
I have a webapp with a SW (generate by CLI), I build it with the "ng build --prod" command.
- Open the webapp in Chrome on Android Device
- Close Chrome 
- Repeat open (the webapp opened previously reload)/close Chrome few times, and the error happen

**Important** : I can't reproduce it without a registered SW.

OR

- Install app on Android Device
- Repeat open/close the app few times, and the error happen

I can't reproduce the error on my Mac.

### The log given by the failure.
```
 Uncaught ReferenceError: webpackJsonp is not defined at sw-register.cddb6ecf3e30717910a9.bundle.js:1 
```

### Desired functionality.
Webapp launch & display OK.

### Mention any other details that might be useful.
I've already find this similar issue : https://github.com/angular/angular-cli/issues/4998
But my uglify version is 3.

**Comment by filipesilva** [comment] 2017-10-16 10:48
`webpackJsonp is not defined` usually mean you are not loading the javascript bundles in the right order. They must be loaded in the order present in the `index.html` that the CLI generates.

Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by flyher** [comment] 2017-10-24 02:41
@filipesilva 
I meet the same issue after add `jquery` and `bootstrap` in webpack.config.js ,
you can see the code [here](https://github.com/flyher/totoro/blob/dev_0.3/webpack.config.js)

thank you!

![1111](https://user-images.githubusercontent.com/5570324/31922498-d297c748-b8a7-11e7-97dd-25359cbc661d.png)

**Comment by natcohen** [comment] 2017-10-25 15:49
Having the same issue here... building with -aot (dev) works fine. Prod compiles without complaint but when loading the app on the browser, it returns the following errors:


```
polyfills.900aaf0d520c2ec873a7.bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at polyfills.900aaf0d520c2ec873a7.bundle.js:1
(anonymous) @ polyfills.900aaf0d520c2ec873a7.bundle.js:1
vendor.b3b1073e85b443c9b6c3.bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at vendor.b3b1073e85b443c9b6c3.bundle.js:1
(anonymous) @ vendor.b3b1073e85b443c9b6c3.bundle.js:1
main.dfb485d3367f26ac4251.bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at main.dfb485d3367f26ac4251.bundle.js:1
(anonymous) @ main.dfb485d3367f26ac4251.bundle.js:1
```

**Comment by alapasset** [comment] 2017-11-08 10:47
I have same issue only on IE 11

**Comment by oshingc** [comment] 2017-11-17 20:33
Same issue here.

**Comment by yadoble** [comment] 2017-12-06 20:13
Same issue here, `ng serve` works fine, but `ng build` to deploy the app in bluemix is not working properly

**Comment by royjulien** [comment] 2017-12-10 04:32
Same issue. Local build works fine loading both the `localhost:4200` and `localhost:4200/[viewcomponent]`. As soon as I push it live, the base url is working but not loading any other page returns ```Uncaught SyntaxError: Unexpected token <
polyfills.900aaf0d520c2ec873a7.bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at polyfills.900aaf0d520c2ec873a7.bundle.js:1
(anonymous) @ polyfills.900aaf0d520c2ec873a7.bundle.js:1
vendor.945e35d73f0e55b0c5f4.bundle.js:1 Uncaught SyntaxError: Unexpected token <
main.bd9155fd1f2baada6b7b.bundle.js:1 Uncaught SyntaxError: Unexpected token <```

**Comment by fabienbranchel** [comment] 2017-12-14 10:30
@filipesilva :

Time pass, I was using Workbox in production and then I try again with the release of Angular 5.
I now use Angular 5.1, with Angular CI 1.6 and Angular Service Worker 5.0. 
The issue seems to be fix with my use case.

I proceed to a lot of tests in the same conditions than before with previouses versions, and all is working as expected.

**Comment by luizptm** [comment] 2018-02-07 16:11
@fabienbranchel :

Could you send me a example of your package.json file, please?

Thanks a lot.

**Comment by fabienbranchel** [comment] 2018-02-08 09:42
@luizptm : 
`{
  "name": "test",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "start": "npm run branchel-modernizr && ng serve --aot",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc": "./node_modules/.bin/compodoc -p tsconfig.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.0.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.0.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ngx-translate/core": "^8.0.0",
    "@ngx-translate/http-loader": "^2.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@angular/service-worker": "^5.2.0",
    "@compodoc/compodoc": "^1.0.5",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "^2.6"
  }
}
`

**Comment by luizptm** [comment] 2018-02-08 14:09
Thanks, @fabienbranchel.
I am still having this issue. I changed the angular dependencies to version 5 as above and it not worked.
Could someone help me, please?

**Comment by fabienbranchel** [comment] 2018-02-08 14:22
@luizptm : have you tried with the exact same versions of all depencies as above ?

**Comment by luizptm** [comment] 2018-02-08 15:06
Yes, I tried it and nothing happen. It shows the same error.

**Comment by Len0re** [comment] 2018-02-09 17:20
I had the same problem a while ago, turned out it was a problem with my browser (chrome). I cleaned the cache and then it worked great.

**Comment by luizptm** [comment] 2018-02-09 17:47
Hi Len0re,

I was using another browser (Maxthon) and I tried now on Chrome for the first time and I received the same error.
The first generated file that was showed was style.ac1cb6d1ddd09746eac0.js.

Thanks for your help.

**Comment by adrienlamotte** [comment] 2018-02-17 12:07
I had the same kind of error in production only, on a NodeJS server...
Turns out I just forgot to restart the server !

**Comment by luizptm** [comment] 2018-02-17 13:32
Could you be more specific? How ca I do this?

Thanks for helping.

**Comment by goelinsights** [comment] 2018-02-17 22:00
I'm getting the same problem showing up when I put a CDN in front of express...goes away when I invalidate the cache.  Any reason this would pop up with the way a CDN stores/ distributes the files?

**Comment by thenninger** [comment] 2018-05-03 12:44
Getting the same problem only sometimes though when loading production build in browser.

**Comment by oztek22** [comment] 2018-05-27 20:00
![image](https://user-images.githubusercontent.com/14314089/40590077-6b6f5f90-6216-11e8-96e7-b1cf76694c8e.png)

looks like this is the same issue. It happens after I bundled my Angular app using browsserify and embedded it on page where webpackJsonp was already added.

Is there any way I can conditionally remove it from execution?

**Comment by alan-agius4** [comment] 2018-09-03 15:33
Closing as no reproduction was provided.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Closed by alan-agius4** 2018-09-03 15:33 UTC
Labels: need: repro steps

**Comment by gauravbhavsar** [comment] 2018-11-20 08:41
@filipesilva

I am also getting this error in **Prerenderer.RenderToString**
>new JavaScriptModuleExport(
request.HttpContext.RequestServices.GetRequiredService<IHostingEnvironment>().ContentRootPath + "/ClientApp/dist/main.bundle")

and getting error **`NodeInvocationException: Prerendering failed because of error: ReferenceError: webpackJsonp is not defined`** in main.bundle.js file
