### ISSUE TITLE
Provide option to disable linting when running ng test

### ISSUE THREAD

**Issue by matsura** [angular/angular-cli#2777] opened 2016-10-19 12:00 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.17
node: 5.7.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.
No failure.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

We should be able to turn off linting when running test. When developing, tests running is really slow with lint on.

https://github.com/angular/angular-cli/issues/2551

**Comment by filipesilva** [comment] 2016-10-23 16:06
Dupe of https://github.com/angular/angular-cli/issues/1980, addressed by https://github.com/angular/angular-cli/pull/2840.

**Closed by filipesilva** 2016-10-23 16:06 UTC
