### ISSUE TITLE
Bug: Module cannot be initialized with router

### ISSUE THREAD

**Issue by Karasuni** [angular/angular-cli#7655] opened 2017-09-11 14:15 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.1
node: 7.1.0
os: win32 x64

### Repro steps.
```
ng g m home --router
```

### The log given by the failure.
```
The option '--router' is not registered with the generate command. Run `ng generate --help` for a list of supported options.
  create src/app/home/home.module.spec.ts (259 bytes)
  create src/app/home/home.module.ts (188 bytes)
```

### Desired functionality.
As described in the [documentation](https://github.com/angular/angular-cli/wiki/stories-routing) I expect the routing module to be initialized and created.

```
  create src/app/home/home.module.spec.ts (259 bytes)
  create src/app/home/home.module.ts (188 bytes)
  create src/app/home/home-routing.module.ts (xxx bytes)
```

**Comment by hansl** [comment] 2017-09-11 17:22
Hi @Karasuni ,

The argument is actually `--routing`, not `--router`. I don't think we ever had the `--router` argument.

Closing this as working as intended. Cheers!

**Closed by hansl** 2017-09-11 17:22 UTC
