### ISSUE TITLE
Multi lib support build in Angular 6

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#11473] opened 2018-07-05 20:19 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [X] feature request
```
### Area
```
- [X ] devkit
- [x] schematics
```

### Versions
Angular CLI: 6.0.8
Node: 8.9.1
OS: darwin x64
Angular: 6.0.7

### Repro steps

I am not even sure if this is a bug or more it should be a feature or I am missing something. 
I have multi lib project created with libraries called: A, B. B library imports some modules from A. 

When I run `ng build B`  it fails as it is missing dependencies that exists inside A. So I need to run manually A and then B to make all works. 

And I am not sure how to configure existing project to trigger build for  project A first and then B. Are there a way how to specify this dependency?

### Desired functionality
Option to specify library depedency so when I build project B it will automatically build project A or some kind of option to specify `ng build A,B`

**Comment by filipesilva** [comment] 2018-07-19 17:25
There isn't a way currently to recursively build projects, but this is something we want to add.

**Comment by intellix** [comment] 2018-08-02 09:51
Maybe possible using TS 3.0 Project references? https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/#project-references

**Comment by filipesilva** [comment] 2018-08-02 10:43
@intellix it helps, but is not enough by itself. Building a library is not just a matter of running typescript. Other things, like css preprocessors and ngc also need to run.

**Comment by alan-agius4** [comment] 2018-10-29 13:04
Relates to #11023

**Comment by alan-agius4** [comment] 2019-01-04 13:21
Duplicate of https://github.com/angular/angular-cli/issues/11002

**Closed by alan-agius4** 2019-01-04 13:21 UTC
Labels: comp: angular/cli, type: feature
