### ISSUE TITLE
"ng build -prod" - component's template not showing

### ISSUE THREAD

**Issue by MrCroft** [angular/angular-cli#1792] opened 2016-08-21 20:43 UTC
I don't know how to best describe this in the title, maybe if someone has a suggestion.
The content (template) of the components I have in the `declarations` array in my `app.module.ts`, that are used within other components, don't show up at all when building with the "-prod" flag.

Steps to reproduce:

1. `ng new my-app --directory ng.app` (I don't know why, but this sets "app" as prefix if you check `angular-cli.json`, I would have expected the prefix to be "my-app")
2. `cd ng.app`
3. `mkdir src/app/layout`
4. `ng generate component layout/header`
5. go into "app.module.ts" and correct the path from where the newly HeaderComponent is imported (this is a bug #1714)
6. go into `app.component.html` and add `<app-header></app-header>`.
7. run `ng serve` and access `http://localhost:4200`. You see "**app works!**" and "**header works!**"
8. run `ng serve -prod` and access `http://localhost:4200`. Now you **only** see "**app works!**". The HeaderComponent template is not rendered anymore. If you inspect the dom, you can see the `<app-header></app-header>` tag there. But it's empty.

No errors on build and no errors in the browser console.

```
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.4.0
os: win32 x64
```

**Comment by nampdn** [comment] 2016-08-23 01:51
Hi, I meet the same problem here when build for production, but the weird thing are `styles`, it render the template but not the css of its component

**Comment by filipesilva** [comment] 2016-08-23 15:06
Dupe of https://github.com/angular/angular-cli/issues/1644. There's a fix in master that'll be in the next release.

**Closed by filipesilva** 2016-08-23 15:06 UTC

**Comment by antonyRoberts** [comment] 2016-08-24 17:40
@filipesilva I'm using the master build and still have issues with the prod version only
angular-cli: local (v1.0.0-beta.11-webpack.2, branch: master)
node: 6.3.1
os: win32 x64

**Comment by filipesilva** [comment] 2016-08-28 16:14
Ok, reopening to investigate.
