### ISSUE TITLE
[BUG] Font import urls not being prepended with base-href

### ISSUE THREAD

**Issue by michael-letcher** [angular/angular-cli#14825] opened 2019-06-19 02:06 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Yes, the previous version in which this bug was not present was: v7.x.x

### Description
If you have a `@font-face` in your styles and serve/build with a base-href your urls will be incorrect.

Tested with both SCSS and LESS both fail in v8. Testing in v7 LESS passes.

## 🔬 Minimal Reproduction
**Angular 7**
`ng new angular7Test` with LESS
`ng serve --prod --base-href=/app/`

Add this too app.component.less
```
// Set antialiasing as default
html {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale; // Fix for Mozilla
  font-family: sans-serif;
}

// Mixin to simplify inclusion of local web fonts
.AddFontFace(@FontFileName, @FontFriendlyName, @FontLocation, @FontWeight, @FontStyle) {
  font-family: @FontFriendlyName;
  src: url("@{FontLocation}@{FontFileName}.eot");
  src: url("@{FontLocation}@{FontFileName}.eot?#iefix")
      format("embedded-opentype"),
    url("@{FontLocation}@{FontFileName}.woff") format("woff"),
    //url('@{FontLocation}@{FontFileName}.woff2') format('woff2'),
      url("@{FontLocation}@{FontFileName}.ttf") format("truetype"),
    url("@{FontLocation}@{FontFileName}.svg#@{FontFriendlyName}") format("svg");
  font-weight: @FontWeight;
  font-style: @FontStyle;
}

// Location of all fonts
@font-files-location: "/assets/shared/fonts/";

// Univers Regular (Used as Bold)
@font-face {
  .AddFontFace(
    "universbq-regular-webfont",
    "UniversBQ",
    "@{font-files-location}",
    bold,
    normal
  );
}

* {
  font-family: "UniversBQ";
}
```

You will see the fonts import with `/app/` prepended.

**Angular 8**
`ng new angular8Test` with LESS
`ng serve --prod --base-href=/app/`

Same steps above but the fonts will fail with 404 as they are looking for `/assets/...` and not `/app/assets/...`

## 🔥 Exception or Error
NA

## 🌍 Your Environment
**v7**
<pre><code>
Angular CLI: 7.3.9
Node: 10.15.1
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**v8**
<pre><code>
Angular CLI: 8.0.3
Node: 10.15.1
OS: darwin x64
Angular: 8.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2019-06-19 05:44
Duplicate of https://github.com/angular/angular-cli/issues/14587

**Closed by alan-agius4** 2019-06-19 05:44 UTC
