### ISSUE TITLE
Broken module file when generate module --routing

### ISSUE THREAD

**Issue by DaSchTour** [angular/angular-cli#9796] opened 2018-02-27 13:18 UTC
### Versions
```
Angular CLI: 1.7.1
Node: 8.9.1
OS: darwin x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/.DS_Store: error
@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.4.2
@angular-devkit/schematics: 0.4.2
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps

* ng generate module test --routing

### Observed behavior
```
  create src/app/test/test-routing.module.ts (247 bytes)
  create __path__/__name@dasherize@if-flat__/__name@dasherize__.module.ts (271 bytes)
```

### Desired behavior
```
  create src/app/test/test-routing.module.ts (247 bytes)
  create src/app/test/test.module.ts (271 bytes)
```

**Comment by Brocco** [comment] 2018-02-27 20:13
Duplicate of #9480

**Closed by Brocco** 2018-02-27 20:13 UTC
Labels: comp: schematics/angular, severity5: regression
