### ISSUE TITLE
Npm install not working

### ISSUE THREAD

**Issue by HNeukermans** [angular/angular-cli#2111] opened 2016-09-14 14:44 UTC
NPM installing -g angular-cli doesn' work anymore. It remains hanging.
Tried it more then ones. 

Is it me? Or does it have something to do with the package?

OS: Windows 7
Node : v4.3.1
Npm : 3.8.1

![image](https://cloud.githubusercontent.com/assets/2285199/18516720/51d0d448-7a9a-11e6-9b18-da444a80b370.png)

**Comment by eaustin** [comment] 2016-09-14 15:00
Same here.

**Comment by alex-oleshkevich** [comment] 2016-09-14 15:09
Same here.

Arch Linux. 
node: v6.5.0
npm: 3.10.7

```bash sudo npm install -g angular-cli``` hangs on ```extract:angular-cli: sill doParallel extract 902```

![image](https://cloud.githubusercontent.com/assets/635848/18517772/2115328e-7aa6-11e6-84a4-1934e4976ded.png)

**Comment by kylecordes** [comment] 2016-09-14 15:10
```npm install -g angular-cli``` has been unfortunately obsolete for many weeks, as most or all of the development attention (and much of the CLI user community) is working with the webpack version.  I suggest retrying with the webpack variant, and report whether you have the same difficulties there, there are instructions on the README, also linked below, in that direction.

https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md

(The CLI team has also mentioned that the webpack version will become the main version soon, at that point the simple install command will again become the correct thing to do to get the current CLI.)

**Comment by alex-oleshkevich** [comment] 2016-09-14 15:20
@kylecordes, thanks for reply, but it still does not work:

```sudo npm -ddd install angular-cli@webpack``` continues hanging. Last log lines:

```
npm verb unbuild lib/node_modules/.staging/clap-eb63a9c5
npm verb unbuild lib/node_modules/.staging/marked-terminal-67a99fa6
npm verb unbuild lib/node_modules/.staging/cli-usage-c6642290
npm verb unbuild lib/node_modules/.staging/ora-2a28b3f9
npm verb unbuild lib/node_modules/.staging/sum-up-8b3a8a70
```

I tried it with older versions of npm and node, it worked but I had other issues. I think that smth related to npm itself. Who knows..

**Comment by kylecordes** [comment] 2016-09-14 15:28
It is good (for those having this trouble) that it hangs on the current webpack variant, That means that this is a current problem that the team will probably need to investigate, not a leftover thing from the months-old mainline code that could be ignored.

Here's a data point, in case it helps: on my Mac I just successfully uninstalled and then installed CLI. Then I upgraded to the current Node (6.5.0) and did it again, also successfully.  I don't have my Windows machine and the at the moment, but I will also try it on Linux to help narrow down where this failure might be occurring and if it is widespread.

**Comment by kylecordes** [comment] 2016-09-14 15:46
I also just tested in Linux - install works there (for me) also. I suspect @alex-oleshkevich problem is something local wrong with Node. I don't know about the earlier reported Windows problem.

**Comment by alex-oleshkevich** [comment] 2016-09-14 15:48
@kylecordes what npm version do you use? It fails on 2 machines for me (common thing - they are both based on Arch Linux)

**Comment by filipesilva** [comment] 2016-09-14 15:48
Just tried myself and didn't have any issues.

Windows 10
node 6.5.0
npm 3.10.3

I ran these commands to make sure my environment wasn't using any leftover setup from my dev work:

```
npm uninstall -g angular-cli
npm cache clean
```

Then did `npm install -g angular-cli@webpack` and it ran fine.

**Comment by kylecordes** [comment] 2016-09-14 15:51
NPM: tried 6.3 and 6.5. OK. Linux:

```
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
```

I suggest deleting your entire pile of globally installed Node modules. I have found NPM to be surprisingly prone to trouble. I don't recall the command offhand, but a search should reveal it.

**Comment by alex-oleshkevich** [comment] 2016-09-14 15:52
Seems the problem is in NPM: https://github.com/npm/npm/issues/13782

**Comment by kylecordes** [comment] 2016-09-14 15:54
Relevant comment from that Node thread:

"... I’d recommend you download and use the official binaries from https://nodejs.org/ too. The fix is in V8 now, so it probably won’t be too long until you can use Arch’s own executables again."

**Comment by alex-oleshkevich** [comment] 2016-09-14 15:55
well, I downgraded nodejs to 6.4 and it worked. I have successfully installed ```angular-cli```.

**Comment by suryashekhawat** [comment] 2016-09-14 15:58
i think you just need to update node to latest version and then give a try

**Comment by filipesilva** [comment] 2016-09-14 16:40
Closing as the problem is in NPM. Great job tracking it down guys!

**Closed by filipesilva** 2016-09-14 16:40 UTC
Labels: flag: help wanted
