### ISSUE TITLE
Angular 5 installation error  "npm install -g angular/cli@1.5.0 npm ERR! code ENOLOCAL npm ERR! Could not install from when i run npm install angular\cli@1.5.0       "angular\cli@1.5.0" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by sandeepmulukala** [angular/angular-cli#11588] opened 2018-07-18 20:41 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

**Comment by hansl** [comment] 2018-07-18 21:34
Dupe of https://github.com/angular/angular-cli/issues/11589

**Closed by hansl** 2018-07-18 21:34 UTC
