### ISSUE TITLE
Environment variables on index.html

### ISSUE THREAD

**Issue by aldo-roman** [angular/angular-cli#6778] opened 2017-06-22 21:50 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
1.1.0

### Repro steps.
1. go to `index.html`
2. include this code:
```
<script>
console.log(environment.production);
</script>
```

### Desired functionality.
I would like to access environment files in inline javascript code, ie `<script>...</script>`

### Mention any other details that might be useful.
**Motivation** we need to setup some tracking IDs (think Google Analytics) and do not know how to replace them at compile time while doing production release.

**Comment by jgodi** [comment] 2017-06-24 02:53
Answered in https://github.com/angular/angular-cli/issues/4451. Hope that helps!

**Comment by filipesilva** [comment] 2017-06-26 16:44
Closing as a (sort of) duplicate of #4451, answered in https://github.com/angular/angular-cli/issues/4451#issuecomment-285329985.

**Closed by filipesilva** 2017-06-26 16:44 UTC

**Comment by toby5box** [comment] 2019-07-02 15:32
Better answer at https://github.com/angular/angular-cli/issues/4451#issuecomment-399888807
