### ISSUE TITLE
"export * as ns" not working in angular-cli@9.1.1

### ISSUE THREAD

**Issue by himanshugarg574** [angular/angular-cli#17509] opened 2020-04-20 10:50 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 This feature is introduced in typescript 3.8 and hence in angular-cli  9.1.1.

### Description

 A clear and concise description of the problem...
I tried to use typescript 3.8 feature, `export * as namespace`. But angular cli threw an error w

## 🔥 Exception or Error
<pre><code>

ERROR in ./src/app/features/state/internal.ts 13:9
Module parse failed: Unexpected token (13:9)
File was processed with these loaders:
 * ./node_modules/@ngtools/webpack/src/index.js
You may need an additional loader to handle the result of these loaders.
> export * as addRecordState from './add-record';
| export * as auditState from './audit-log';
| export * as forwardState from './forward';
 @ ./src/app/features/actions/actions.module.ts 26:0-51 47:35-50 47:66-81 76:43-58 76:74-89
 @ ./src/app/admin/admin.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.1
Node: 12.3.1
OS: win32 x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@angular/cdk                       9.2.1
@angular/cli                       9.1.1
@angular/material                  9.2.1
@angular/material-moment-adapter   9.2.1
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-04-20 12:25
Duplicate of https://github.com/angular/angular-cli/issues/17231

**Closed by alan-agius4** 2020-04-20 12:25 UTC
