### ISSUE TITLE
Create module with routing places routing module in wrong place

### ISSUE THREAD

**Issue by smlombardi** [angular/angular-cli#9804] opened 2018-02-27 16:37 UTC
### Versions
```
Angular CLI: 1.7.1
Node: 6.11.2
OS: darwin x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.4.2
@angular-devkit/schematics: 0.4.2
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps

Tried to create a module "errorpages" with routing inside an existing directory "demo":
```
US-ST016LO-MLT:client st016lo$ ng g m /demo/errorpages --spec=false --module app --routing -d
```

### Observed behavior

The module is created as expected, inside `/src/app/demo/errorpages`.  But the routing module is created at ` app/demo/errorpages/errorpages-routing.module.ts`, which creates a whole new folder hierarchy.  Also, the resulting  `errorpages.module.ts` has an error since it's looking for the routing module where it _should_ be, at `./`
```
  create app/demo/errorpages/errorpages-routing.module.ts (278 bytes)
  create src/app/demo/errorpages/errorpages.module.ts (295 bytes)
  update src/app/app.module.ts (5901 bytes)
```
Also, the resulting routing module is full of garbage:
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [];

@NgModule({
  imports: [RouterModule.for<%= routingScope %>(routes)],
  exports: [RouterModule]
})
export class <%= classify(name) %>RoutingModule { }
```

**Comment by Brocco** [comment] 2018-02-27 20:16
Duplicate of #9480

**Closed by Brocco** 2018-02-27 20:16 UTC
Labels: comp: cli/generate
