### ISSUE TITLE
Upgrading from v9 to v11 ng build/serve are very slow #20227

### ISSUE THREAD

**Issue by MathewBerg** [angular/angular-cli#20763] opened 2021-05-13 13:30 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Maybe? Hard to tell if we just aren't doing something right currently.
### Description

We were unable to upgrade from angular 9 to 11 last year. After doing the migration the builds are taking around an hour and ng serve is taking around 10minutes to start and then a few minutes to recompile.

## 🔬 Minimal Reproduction

The project is quite large. After the discussion here: https://github.com/angular/angular-cli/issues/20227 we had lot of failures of generating the .json files with NG_BUILD_PROFILING set to 1. Eventually one of our developers was able too after cutting out a large portion of our code base, but it just mimics how we're building stuff elsewhere.

## 🔥 Exception or Error

(copied from the last bug) I saw this issue raised: #17557 that was able to spit out the webpack timings but I tried the same command and didn't get anything. Here are some logs from that command though:

Hash: 10062e72e655a942dd34
Version: webpack 4.44.2
Time: 708716ms
Built at: 03/09/2021 10:15:12 AM

LOG from webpack.buildChunkGraph.visitModules
prepare: 157.7756ms
visiting: 11.9087ms
calculating available modules: 0.9064ms
merging available modules: 0.1087ms
visiting: 47.7026ms
calculating available modules: 1.9921ms
merging available modules: 0.023ms
visiting: 1.39ms

Initial Chunk Files | Names | Size
main-es5.3ac0413d5fda208dcf49.js | main | 3.60 MB
main-es2015.3ac0413d5fda208dcf49.js | main | 3.32 MB
polyfills-es5.1577f06bbd7cd498d2aa.js | polyfills-es5 | 131.77 kB
styles.088de8f15a462993e614.css | styles | 108.92 kB
polyfills-es2015.603bb5ba1ae3ee6b7388.js | polyfills | 45.98 kB
runtime-es2015.12e587ff0e65ab518ba8.js | runtime | 3.40 kB
runtime-es5.12e587ff0e65ab518ba8.js | runtime | 3.40 kB

## 🌍 Your Environment

<pre><code>

Angular CLI: 11.2.3
Node: 14.16.0
OS: win32 x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3 (cli-only)
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3 (cli-only)
@angular-devkit/schematics      11.2.3
@angular/cdk                    11.2.3
@angular/cli                    11.2.3
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
ng-packagr                      11.2.4
rxjs                            6.5.5
typescript                      4.0.7
</pre>

**Anything else relevant?**

Here's the speed-measure-plugin.json:

```
{
  "misc": {
    "compileTime": 485627
  },
  "plugins": {
    "AngularCompilerPlugin": 253168,
    "BuildOptimizerWebpackPlugin": 61121,
    "ContextReplacementPlugin": 79,
    "CopyPlugin": 67,
    "MiniCssExtractPlugin": 29,
    "ProfilingPlugin": 70949,
    "ProgressPlugin": 11394,
    "CircularDependencyPlugin": 6080,
    "LicenseWebpackPlugin": 9014,
    "AnyComponentStyleBudgetChecker": 241,
    "SuppressExtractedTextChunksWebpackPlugin": 125,
    "NgBuildAnalyticsPlugin": 5058,
    "HashedModuleIdsPlugin": 631,
    "OptimizeCssWebpackPlugin": 5030,
    "TerserPlugin": 44879,
    "BundleBudgetPlugin": 970
  },
  "loaders": {
    "build": [
      {
        "averages": {
          "dataPoints": 1,
          "median": 202470,
          "mean": 202470,
          "range": {
            "start": 202470,
            "end": 202470
          }
        },
        "activeTime": 202470,
        "loaders": [
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\mini-css-extract-plugin\\dist\\loader.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\css-loader\\dist\\cjs.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\postcss-loader\\src\\index.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\sass-loader\\dist\\cjs.js"
        ],
        "subLoadersTime": {}
      },
      {
        "averages": {
          "dataPoints": 1,
          "median": 194400,
          "mean": 194400,
          "range": {
            "start": 194400,
            "end": 194400
          }
        },
        "activeTime": 194400,
        "loaders": [
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\css-loader\\dist\\cjs.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\postcss-loader\\src\\index.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\sass-loader\\dist\\cjs.js"
        ],
        "subLoadersTime": {}
      },
      {
        "averages": {
          "dataPoints": 405,
          "median": 4328,
          "mean": 5250,
          "range": {
            "start": 363,
            "end": 13806
          },
          "variance": 12656309
        },
        "activeTime": 13806,
        "loaders": [
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\raw-loader\\dist\\cjs.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\postcss-loader\\src\\index.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\sass-loader\\dist\\cjs.js"
        ],
        "subLoadersTime": {}
      },
      {
        "averages": {
          "dataPoints": 1212,
          "median": 5,
          "mean": 26,
          "range": {
            "start": 2,
            "end": 6484
          },
          "variance": 39836
        },
        "activeTime": 32036,
        "loaders": [
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\@angular-devkit\\build-optimizer\\src\\build-optimizer\\webpack-loader.js"
        ],
        "subLoadersTime": {}
      },
      {
        "averages": {
          "dataPoints": 1304,
          "median": 31,
          "mean": 17,
          "range": {
            "start": 3,
            "end": 644
          },
          "variance": 639
        },
        "activeTime": 22403,
        "loaders": [
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\@angular-devkit\\build-optimizer\\src\\build-optimizer\\webpack-loader.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\@ngtools\\webpack\\src\\index.js"
        ],
        "subLoadersTime": {}
      },
      {
        "averages": {
          "dataPoints": 3,
          "median": 7,
          "mean": 15,
          "range": {
            "start": 7,
            "end": 29
          },
          "variance": 148
        },
        "activeTime": 45,
        "loaders": [
          "modules with no loaders"
        ],
        "subLoadersTime": {}
      },
      {
        "averages": {
          "dataPoints": 73,
          "median": 8,
          "mean": 10,
          "range": {
            "start": 7,
            "end": 68
          },
          "variance": 51
        },
        "activeTime": 718,
        "loaders": [
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\svg-inline-loader\\index.js"
        ],
        "subLoadersTime": {}
      }
    ]
  }
}

```

**Comment by clydin** [comment] 2021-05-13 13:58
Is a third-party builder being used within the project?

The version output also may indicate that incorrect/outdated versions are present:
```
@angular-devkit/architect       0.1102.3 (cli-only)
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3 (cli-only)
```
A third-party builder may be inadvertently injecting older versions of dependencies into the build pipeline.

It also appears that the build is a production build due to the presence of `BuildOptimizerWebpackPlugin`.  Is that correct?

**Comment by MathewBerg** [comment] 2021-05-13 14:01
@clydin yes, this was a production build. We're running this:

`node --max_old_space_size=8096 ./node_modules/@angular/cli/bin/ng "build" "--prod"`

chrome-profiler-events.json is 600MB

**Comment by MathewBerg** [comment] 2021-05-13 14:12
Seeing that node-sass seems to take awhile, I'm going to try converting as much of the scss we have to css with some scripts.

**Comment by clydin** [comment] 2021-05-13 14:42
If you are able to update to v12, the next patch release of 12.0.1 will contain several improvements that should greatly benefit the build performance of applications that use large amounts of Sass stylesheets.

As to the overall build performance, can you also run the following commands (or the yarn variant if using it instead of npm):
`npm ls @angular-devkit/build-angular`
`npm ls @ngtools/webpack`
`npm ls @angular/compiler-cli`

**Comment by MathewBerg** [comment] 2021-05-13 15:00
I'm running this on my computer which has just a slight different version, but I experience the same problem.

Here is the output:

```
`-- @angular-devkit/build-angular@0.1102.10

`-- @angular-devkit/build-angular@0.1102.10
  `-- @ngtools/webpack@11.2.10

`-- @angular/compiler-cli@11.2.11
```

We have roughly ~1700 components

**Comment by kemsky** [comment] 2021-05-14 11:26
Initially, I thought that slowdown was caused by v12, but it is not, looks like some third-party dependencies were updated in v11.

This is v11.0.12 with yarn install --freeze (perhaps some deps are old):
```
$ ng build --prod
√ Browser application bundle generation complete.
√ Copying assets complete.
√ Index html generation complete.

Initial Chunk Files                   | Names         |      Size
main.1bbe17e891e0e81a6bae.js          | main          |   3.20 MB
scripts.5b3322e07a3cdcf6af69.js       | scripts       |   1.48 MB
styles.19406af932cc90ae2667.css       | styles        | 152.44 kB
polyfills-es5.2cb7395a5fd592fe7443.js | polyfills-es5 |  85.88 kB
runtime.23c71f07ba7ec5c3766a.js       | runtime       |   1.51 kB

                                      | Initial Total |   4.92 MB

Build at: 2021-05-14T11:00:10.476Z - Hash: 034e3176df64cbc0b60a - Time: 88357ms
```
Verbose log (logging itself causes slowdown, unfortunately...): 
[angular11.txt](https://github.com/angular/angular-cli/files/6478398/angular11.txt)

This is v12 with yarn.lock  and node_modules removed and reinstalled:
```
$ ng build --configuration production
Warning: Support was requested for IE 11 in the project's browserslist configuration. IE 11 support is deprecated since Angular v12.
For more information, see https://angular.io/guide/browser-support
√ Browser application bundle generation complete.
√ Copying assets complete.
√ Index html generation complete.

Initial Chunk Files                   | Names         |      Size
main.25755cb56d908f1ffa0c.js          | main          |   3.19 MB
scripts.5b3322e07a3cdcf6af69.js       | scripts       |   1.48 MB
styles.51baf6c2a9fbe6837aa1.css       | styles        | 154.28 kB
polyfills-es5.b787b17c5e8d81a4b18e.js | polyfills-es5 |  90.75 kB
runtime.bf3db8034d6e10a74a56.js       | runtime       |   1.20 kB

                                      | Initial Total |   4.92 MB

Build at: 2021-05-14T11:18:16.175Z - Hash: 8806f0a3a3b1271495e0 - Time: 157125ms
```
Verbose log (logging itself causes slowdown, unfortunately...): 
[angular12.txt](https://github.com/angular/angular-cli/files/6478420/angular12.txt)

We have a single small *.scss file (overriding some material colors) and it was updated by migration. The application has only one module.

On average it is 50% slower.

**Comment by MathewBerg** [comment] 2021-05-14 13:54
Converting from scss to css resulted in a negligible speed difference.

**Comment by alan-agius4** [comment] 2021-05-17 11:03
@MathewBerg, that is strange because based on the above timings the most of the time appears to be spent in `sass-loader`.

```
      {
        "averages": {
          "dataPoints": 1,
          "median": 202470,
          "mean": 202470,
          "range": {
            "start": 202470,
            "end": 202470
          }
        },
        "activeTime": 202470,
        "loaders": [
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\mini-css-extract-plugin\\dist\\loader.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\css-loader\\dist\\cjs.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\postcss-loader\\src\\index.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\sass-loader\\dist\\cjs.js"
        ],
        "subLoadersTime": {}
      },
      {
        "averages": {
          "dataPoints": 1,
          "median": 194400,
          "mean": 194400,
          "range": {
            "start": 194400,
            "end": 194400
          }
        },
        "activeTime": 194400,
        "loaders": [
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\css-loader\\dist\\cjs.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\postcss-loader\\src\\index.js",
          "C:\\git\\bpi\\ng\\BPI.UI\\node_modules\\sass-loader\\dist\\cjs.js"
        ],
        "subLoadersTime": {}
      },
```

Is there a way to share the project privately or CPU profiles? Without neither it's hard to find the root cause.

**Comment by MathewBerg** [comment] 2021-05-17 12:01
@alan-agius4 I have chrome-profiler-events.json, but it's about 600MB. Is there a preferred location you'd like me to upload it too?

**Comment by SirJosh1987** [comment] 2021-05-17 12:33
I think I've figured this out

**Comment by alan-agius4** [comment] 2021-05-17 12:40
> @alan-agius4 I have chrome-profiler-events.json, but it's about 600MB. Is there a preferred location you'd like me to upload it too?

Not really as long as I can download them :)

**Comment by MathewBerg** [comment] 2021-05-17 12:55
@alan-agius4 I added you to a private repo with the events in a .7z archive. I appreciate the help!

**Comment by alan-agius4** [comment] 2021-05-17 13:14
> @alan-agius4 I added you to a private repo with the events in a .7z archive. I appreciate the help!

Mind sharing the then uncompressed or in zip format? I don’t use 7zip.

**Comment by MathewBerg** [comment] 2021-05-17 13:52
@alan-agius4 Done.

**Comment by alan-agius4** [comment] 2021-05-18 05:50
Hi, 

I've been trying to load the CPU profiles in Chrome but to no available. 

Can you try to generate the profiles using the below method

1. `node --inspect-brk node_modules/@angular/cli/lib/init.js build --configuration=production`
2. Open Chrome and type `chrome://inspect` -> `Open dedicated DevTools for Node` -> `Profiler tab` ->`Record` (this will resume from the halted debugger in profiling mode). Wait until the process is finished and then stop recording and save the profile.

Thanks.

**Comment by MathewBerg** [comment] 2021-05-18 10:54
@alan-agius4 thanks, and will do! It'll take me a few days to do this as the employee I was working with who was able to generate the profiler is off.

**Comment by MathewBerg** [comment] 2021-05-18 15:25
@alan-agius4 ok, just gave that a try on my computer. 

1. Opened cmd line and ran `node --inspect-brk node_modules/@angular/cli/lib/init.js build --configuration=production`
2. Opened dedicated DevTools for Node in chrome://inspect and went to profiler and hit record
3. In cmd It gave the ie11 warning, then exited. 

`
C:\Development\PROJECT_NAME>node --inspect-brk node_modules/@angular/cli/lib/init.js build --configuration=production
Debugger listening on ws://127.0.0.1:9229/1ceba245-77ba-45eb-b7d0-251ee3a53e3b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Warning: Support was requested for IE 11 in the project's browserslist configuration. IE 11 support is deprecated since Angular v12.
For more information, see https://angular.io/guide/browser-support

C:\Development\PROJECT_NAME>
`

**Comment by MathewBerg** [comment] 2021-05-18 16:05
@alan-agius4 same result with 11, exists almost immediately.

**Comment by jamesnben** [comment] 2021-05-18 17:50
I'm working on the same project as Mat. I've run the following command:
`node --inspect-brk node_modules/@angular/cli/lib/init.js build --configuration=production`

The build succeeds with angular cli 9.1.0, however the profiler gets stuck recording.

I can open the profiler and click "Start" to kick off the build.

After the build completes, the console window states that it is "Waiting for the debugger to disconnect..." 

At this point, I click "Stop" in the profiler and wait.

Eventually chrome crashes.

Should I try doing anything differently?

![image](https://user-images.githubusercontent.com/22961542/118699074-1bfbaa00-b7df-11eb-9a22-8851ce51d87a.png)

**Comment by alan-agius4** [comment] 2021-05-19 08:33
Hi @jamesnben & @MathewBerg,  

Not sure why you are experiencing that issue but probably memory related. 

Couple of things to verify
- Update to the latest Chrome version
- Try to close all other Chrome windows

**Comment by kemsky** [comment] 2021-05-19 11:07
I guess you are using node 14 on windows? It does not work for me as well, I had to downgrade node to version 12 and use `NG_BUILD_PROFILING=1` instead.

**Comment by SirJosh1987** [comment] 2021-05-29 07:46
Ok yes?

**Comment by alan-agius4** [comment] 2021-05-31 13:00
Hi @jamesnben & @MathewBerg,

Since you are using Node.JS 14+ you can also use `--cpu-prof`.

```
node --cpu-prof node_modules/@angular/cli/lib/init.js build --configuration=production
```

**Comment by MathewBerg** [comment] 2021-05-31 13:45
@alan-agius4 thanks, we will try that.

**Comment by MathewBerg** [comment] 2021-06-01 15:33
After a bit of finagling of the code here is the output:

![image](https://user-images.githubusercontent.com/1194365/120350641-2af95680-c2cd-11eb-9a99-5a3259eb8bec.png)

Is that what you would need @alan-agius4 ?

**Comment by alan-agius4** [comment] 2021-06-01 15:38
Yes

**Comment by MathewBerg** [comment] 2021-06-02 21:37
@alan-agius4 I can't share the cpu profiles with you (security reasons). I'll have to wait awhile before reaching out again. As before I appreciate the responses.

**Comment by alan-agius4** [comment] 2021-06-03 06:34
@MathewBerg, in that case let’s close this issue for the time being.

Feel free to open a new issue when you are able to share the CPU profiles.

**Closed by alan-agius4** 2021-06-03 06:34 UTC
Labels: need: more info, severity4: memory/performance
