### ISSUE TITLE
ng new FAIL

### ISSUE THREAD

**Issue by ddagone** [angular/angular-cli#1273] opened 2016-07-03 15:46 UTC
When I'm trying to type `ng new tutorial` I get this message error right here : 

```
module.js:327
    throw err;
    ^
Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/lib/models/project.js:11:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

I don't know what or why it shows up, help would be great 👍

**Comment by filipesilva** [comment] 2016-07-03 21:37
Dupe of https://github.com/angular/angular-cli/issues/1186.

**Closed by filipesilva** 2016-07-03 21:37 UTC
