### ISSUE TITLE
[AOT] webpack DefinePlugin not working with @ngtools/webpack

### ISSUE THREAD

**Issue by JounQin** [angular/angular-cli#9874] opened 2018-03-06 07:15 UTC
### Versions
```
`@ngtools/webpack`: 6.0.0-beta.4
```

### Repro steps

// route module
https://github.com/JounQin/ng-rubick/blob/master/src/views/app.routing.module.ts#L24
// webpack config
https://github.com/JounQin/ng-rubick/blob/master/build/config.ts#L14
// Travis env config
https://github.com/JounQin/ng-rubick/blob/master/.travis.yml#L7

### Observed behavior
When I define a global variable `HASH_MODE=true` via webpack.DefinePlugin and set it to RouterModule `useHash`, it not works,

### Desired behavior

When `HASH_MODE=true` is set, Router should be in hash mode.

### Mention any other details that might be useful (optional)
Webpack: 4.1.0

**Comment by filipesilva** [comment] 2019-01-28 16:51
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by filipesilva** [comment] 2019-02-04 09:53
I think this happens because of AOT compilation overall. When the decorators are compiled down to javascript, something must change that stops DefinePlugin from working properly. I'm not sure what the right way to address it is at this point.

**Comment by guilhermevrs** [comment] 2019-06-20 13:28
Not sure if you are still facing the issue, but I use DefinePlugin and it works just fine on AOT as well

**Comment by JounQin** [comment] 2019-06-26 02:40
@guilhermevrs I've tried to upgrade all (dev)dependencies, but it still does not work.

**Comment by alan-agius4** [comment] 2021-05-26 12:01
@JounQin, is this still a problem with Angular 12?

**Comment by vtulin** [comment] 2021-05-26 12:08
> @JounQin, is this still a problem with Angular 12?

Angular 11 works fine:
"webpack": "^4.44.2",
"@angular/compiler": "^11.2.14",
"@ngtools/webpack": "^10.2.2",

**Comment by alan-agius4** [comment] 2021-05-26 12:20
Closing as per above.

**Closed by alan-agius4** 2021-05-26 12:20 UTC
Labels: comp: ngtools/webpack, freq1: low, help wanted, need: more info, severity3: broken, type: bug/fix
