### ISSUE TITLE
remove Option "deployUrl" is deprecated warning

### ISSUE THREAD

**Issue by alvipeo** [angular/angular-cli#23763] opened 2022-08-18 07:13 UTC
I use the following command to build my angular app and publish it with a back-end made using .NET:
```
ng build --base-href /%folder% --deploy-url /%folder%/ --configuration=production
```

And it's a bit annoying to see this warning:

> Option "deployUrl" is deprecated: Use "baseHref" option, "APP_BASE_HREF" DI token or a combination of both instead. For more information, see https://angular.io/guide/deployment#the-deploy-url.

There's no way `deployUrl` is deprecated. Please remove this warning.

OS: Windows 11

**Comment by alan-agius4** [comment] 2022-08-18 07:59
deployUrl is indeed deprecated. Closing as working as intended.

**Closed by alan-agius4** 2022-08-18 07:59 UTC

**Comment by alvipeo** [comment] 2022-08-18 08:15
and how are we supposed to work without it? https://stackoverflow.com/q/71548735/2896495
