### ISSUE TITLE
If .spec changes, ng serve re-compiles and reload the app

### ISSUE THREAD

**Issue by maxime1992** [angular/angular-cli#6962] opened 2017-07-13 13:29 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.0
node: 8.0.0
os: linux x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.2.0
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

### Repro steps.
```
ng new some-repo
cd some-repo
ng serve
```

Open a unit test file with `.spec`, change something in it.
You should see the `ng serve` re-compiling the app and the browser reloading it.

But nothing changed in the app.

### Desired functionality.
**If a `.spec` changes, do not re-compile the app nor reload app in the browser.**

**Comment by filipesilva** [comment] 2017-07-28 10:26
This is a duplicate of #6238.

**Closed by filipesilva** 2017-07-28 10:26 UTC
