### ISSUE TITLE
ng build --prod produces FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by tshowers** [angular/angular-cli#9157] opened 2018-01-10 18:54 UTC
@angular/cli: 1.3.2
node: 6.10.1
os: darwin x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.3.2
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
ng build --prod
 92% chunk asset optimization
<--- Last few GCs --->

  144159 ms: Mark-sweep 1303.7 (1437.4) -> 1303.7 (1437.4) MB, 1239.6 / 0.0 ms [allocation failure] [GC in old space requested].
  145388 ms: Mark-sweep 1303.7 (1437.4) -> 1303.7 (1437.4) MB, 1229.3 / 0.0 ms [allocation failure] [GC in old space requested].
  146635 ms: Mark-sweep 1303.7 (1437.4) -> 1306.6 (1419.4) MB, 1246.2 / 0.0 ms [last resort gc].
  147891 ms: Mark-sweep 1306.6 (1419.4) -> 1309.8 (1419.4) MB, 1256.2 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x17cc28dcfb39 <JS Object>

    1: token(aka token) [0x17cc28d04381 <undefined>:1729] [pc=0x1a8123da60ed] (this=0x17cc28d04381 <undefined>,type=0x28ac7a55e891 <String[4]: punc>,value=0x281b7740e119 <String[1]: (>,is_comment=0x17cc28d04381 <undefined>)
    2: arguments adaptor frame: 2->3
    3: input(aka next_token) [0x17cc28d04381 <undefined>:~1982] [pc=0x1a8123f81432] (this=0x1cb5f14cedc9 <an Object with map 0x2396662a0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewTransitionArray(int) [/usr/local/bin/node]
 5: v8::internal::TransitionArray::Insert(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Map>, v8::internal::SimpleTransitionFlag) [/usr/local/bin/node]
 6: v8::internal::Map::ShareDescriptor(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Descriptor*) [/usr/local/bin/node]
 7: v8::internal::Map::CopyWithField(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::Representation, v8::internal::Trans
itionFlag) [/usr/local/bin/node]
 8: v8::internal::Map::TransitionToDataProperty(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/u
sr/local/bin/node]
 9: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/usr/local/bin/node]
10: v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/local/bin/node]
11: v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/local/bin/node]
12: v8::internal::StoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/local/bin/node]
13: v8::internal::Runtime_StoreIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x1a81169092a7
15: 0x1a8123da60ed
16: 0x1a8116909895
Abort trap: 6

### Repro steps
<!--
Simple steps to reproduce this bug.
Please include: commands run, packages added, related code changes.
A link to a sample repo would help too.
-->
My first ever attempt to build and to publish in the cloud produces the above error.

ng serve (works fine) 
* ng build --prod

**Comment by clydin** [comment] 2018-01-10 19:38
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #5618. Please subscribe to that issue for future updates.

**Closed by clydin** 2018-01-10 19:38 UTC
