### ISSUE TITLE
Production build fails after upgrade to version 12

### ISSUE THREAD

**Issue by 4nderss** [angular/angular-cli#20884] opened 2021-05-21 06:00 UTC
# 🐞 Bug report

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 10.1.1

### Description

After updating from 10.1.1 to latest version. We can no longer build our applications with the optimization flag set to true. 

## 🔬 Minimal Reproduction

run ng build with optimization set to true

works when its set to false

## 🔥 Exception or Error

<pre>
<code>

2021-05-21 07:49:47: webpack 5.36.2 compiled in 84034 ms (5e690d36f371e40bd6f2)
✔ ES5 bundle generation complete.
✔ Copying assets complete.
✖ Index html generation failed.
undefined:1:3650594: property missing ':'
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.1
Node: 14.15.0
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
ng-packagr                      12.0.0
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

Tracing back the update steps I see that bulding works fine in 11.2.

**Comment by alan-agius4** [comment] 2021-05-21 07:24
Duplicate of https://github.com/angular/angular-cli/issues/20760

**Closed by alan-agius4** 2021-05-21 07:24 UTC
