### ISSUE TITLE
[Feature request] add a schematic to generate resolvers

### ISSUE THREAD

**Issue by geromegrignon** [angular/angular-cli#18758] opened 2020-09-11 09:21 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
As Angular CLI provides a riche schematic ecosystem, there is no one to generate a resolver.

### Describe the solution you'd like

add a dedicated schematic.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by geromegrignon** [comment] 2020-09-11 09:22
I can submit a PR if the request is approved.

**Comment by alan-agius4** [comment] 2020-09-11 10:18
Duplicate of https://github.com/angular/angular-cli/issues/17569

**Closed by alan-agius4** 2020-09-11 10:18 UTC
