### ISSUE TITLE
[BUILD] Missing dependencies on build project with library - 6.0.0-rc.2

### ISSUE THREAD

**Issue by choucry13** [angular/angular-cli#10264] opened 2018-04-10 12:40 UTC
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 6.0.0-rc.2
Node: 9.6.1
OS: darwin x64
Angular: 6.0.0-rc.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 6.0.0-rc.2
@angular-devkit/architect: 0.5.4
@angular-devkit/build-angular: 0.5.4
@angular-devkit/build-ng-packagr: 0.5.4
@angular-devkit/build-optimizer: 0.5.4
@angular-devkit/core: 0.5.4
@angular-devkit/schematics: 0.5.4
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-rc.2.4
@schematics/angular: 0.5.4
@schematics/update: 0.5.4
typescript: 2.7.2
webpack: 4.5.0
```

### Repro steps
* Step 1
   ng new philou
* Step 2
   ng g library tim
* Step 3
  ng build --prod

### Observed behavior
```
Two devDepencies are not present : 
 - @angular-devkit/build-ng-packagr
 - ng-packagr
```

### Desired behavior
add this packages solved the issue.

**Comment by yarrgh** [comment] 2018-04-10 14:08
Duplicate of #10216

**Comment by filipesilva** [comment] 2018-04-10 14:32
Closing as duplicate, thanks @yarrgh !

**Closed by filipesilva** 2018-04-10 14:32 UTC

**Comment by choucry13** [comment] 2018-04-10 17:30
Sorry guys. I don’t see that already reported 😅.
