### ISSUE TITLE
Ability to disable AoT compilation

### ISSUE THREAD

**Issue by mp3por** [angular/angular-cli#3450] opened 2016-12-07 11:10 UTC
How to disable AoT compilation ? Please add a setting or explain to me how to do it ?

### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 6.9.1
os: win32 x64

### Mention any other details that might be useful.
I don't need the AoT compilation and my project was working before updating to 22-1. Now there are tons of changes needed to make it compile AoT.  It also takes 3 times more time to compile and is thus  harder to test.

**Comment by rolandoldengarm** [comment] 2016-12-07 19:42
Duplicate: https://github.com/angular/angular-cli/issues/3368

Just revert back to 1.0.0-beta.21

**Comment by hansl** [comment] 2016-12-07 22:07
Dupe of #3368.

**Closed by hansl** 2016-12-07 22:07 UTC
