### ISSUE TITLE
Allow disabled ViewEncapsulation for global styles

### ISSUE THREAD

**Issue by montella1507** [angular/angular-cli#2742] opened 2016-10-17 10:47 UTC
Hi, 

is it possible to support global styles without view encapsulation?

I have .scss style as a global style (in app[0].styles[] array) it works correctly, but i am not able to debug the styles, because they are included in <style> tag without mapping to concrete files.. I think it should be possible to have not encapsulated (or with map files.) global files in developer environment

**Comment by montella1507** [comment] 2016-10-17 10:56
I think the problem is the same:

#2020  it shouold be possible to enable source maps...

**Comment by filipesilva** [comment] 2016-10-17 22:44
Yes I think it's a dupe of https://github.com/angular/angular-cli/issues/2020. We're waiting for a contributor to get back to that issue atm.

**Closed by filipesilva** 2016-10-17 22:44 UTC
