### ISSUE TITLE
serverless offline with angular cli application

### ISSUE THREAD

**Issue by edvenkat** [angular/angular-cli#27097] opened 2024-02-14 07:08 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

it is working fine in angular 16

### Description

I am attempting to utilize the application builder instead of webpack as per the instructions provided in the link - https://angular.io/guide/esbuild. However, we encountered the following error while running the application in serverless offline.

undefined ERROR Uncaught Exception {
"errorType": "Runtime.ImportModuleError",
"errorMessage": "Error: Cannot find module './dist/server/server'\nRequire stack:\n- /var/task/lambda.js\n- /var/runtime/index.mjs",
"stack": [
"Runtime.ImportModuleError: Error: Cannot find module './dist/server/server",
"Require stack:",
"- /var/task/lambda.js",
"- /var/runtime/index.mjs",
" at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
" at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
" at async start (file:///var/runtime/index.mjs:1282:23)",
" at async file:///var/runtime/index.mjs:1288:1"
]
}

Please help on this.

### Minimal Reproduction

1. create a new angular project with version 17 and use application-builder
2. include the serverless configuration into the project 
3. try to run in local using serverless offline

### Exception or Error

```text
undefined ERROR Uncaught Exception {
"errorType": "Runtime.ImportModuleError",
"errorMessage": "Error: Cannot find module './dist/server/server'\nRequire stack:\n- /var/task/lambda.js\n- /var/runtime/index.mjs",
"stack": [
"Runtime.ImportModuleError: Error: Cannot find module './dist/server/server",
"Require stack:",
"- /var/task/lambda.js",
"- /var/runtime/index.mjs",
" at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
" at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
" at async start (file:///var/runtime/index.mjs:1282:23)",
" at async file:///var/runtime/index.mjs:1288:1"
]
}
```

### Your Environment

```text
Angular CLI: 17.1.1
Node: 21.6.1 (Unsupported)
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@angular/cdk                    16.2.13
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
webpack                         5.88.2
zone.js                         0.14.3

Warning: The current version of Node (21.6.1) is not supported by Angular.
```

**Comment by alan-agius4** [comment] 2024-02-14 09:10
@edvenkat, please provide a minimal runnable reproduction. 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by edvenkat** [comment] 2024-02-14 17:21
Hey @alan-agius4 

i have uploaded the code in below github.

Build : npm run build:dev
Run : serverless offline

https://github.com/edvenkat/issue-angular

**Comment by alan-agius4** [comment] 2024-02-15 10:19
There are a couple of problems that I can observe here. In https://github.com/edvenkat/issue-angular/blob/2b29d26f48fdabb206796a21b8fa79db8eb6d9bf/lambda.js#L3C46-L4C66 the Angular application is being imported as as CJS module using require instead of import, in addition the file being imported does not exist as it should be `./dist/server/server.mjs`. 

Closing as this is not a bug in Angular. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Closed by alan-agius4** 2024-02-15 10:19 UTC
Labels: needs: repro steps

**Comment by edvenkat** [comment] 2024-02-15 13:41
Hi @alan-agius4 thanks I tried your suggestion, but I encountered the following error:

{"errorMessage":"Error while loading api","errorType":"Error","stackTrace":["Error [ERR_REQUIRE_ESM]: require() of ES Module C:\\Users\\venkatesh.ganesan\\Downloads\\events-dynamic-form 2\\dist\\server\\server.mjs not supported.","Instead change the require of C:\\Users\\venkatesh.ganesan\\Downloads\\events-dynamic-form 2\\dist\\server\\server.mjs to a dynamic import() which is available in all CommonJS modules.","at Object.<anonymous> (C:\\Users\\venkatesh.ganesan\\Downloads\\events-dynamic-form 2\\lambda.js:3:16)","at Object.createHandler (C:\\Users\\venkatesh.ganesan\\Downloads\\events-dynamic-form 2\\node_modules\\serverless-offline\\src\\functionHelper.js:215:15)","at handler (C:\\Users\\venkatesh.ganesan\\Downloads\\events-dynamic-form 2\\node_modules\\serverless-offline\\src\\ApiGateway.js:485:40)","at module.exports.internals.Manager.execute (C:\\Users\\venkatesh.ganesan\\Downloads\\events-dynamic-form 2\\node_modules\\@hapi\\hapi\\lib\\toolkit.js:41:33)","at internals.handler (C:\\Users\\venkatesh.ganesan\\Downloads\\events-dynamic-form 2\\node_modules\\@hapi\\hapi\\lib\\handler.js:46:48)","at exports.execute (C:\\Users\\venkatesh.ganesan\\Downloads\\events-dynamic-form 2\\node_modules\\@hapi\\hapi\\lib\\handler.js:31:36)","at Request._lifecycle (C:\\Users\\venkatesh.ganesan\\Downloads\\events-dynamic-form 2\\node_modules\\@hapi\\hapi\\lib\\request.js:312:68)"],"offlineInfo":"If you believe this is an issue with serverless-offline please submit it, thanks. https://github.com/dherault/serverless-offline/issues"}
