### ISSUE TITLE
ng build ignores tsconfig described in .angular-cli.json

### ISSUE THREAD

**Issue by NagarajMadyastha** [angular/angular-cli#10185] opened 2018-04-05 03:17 UTC
Angular CLI: 1.7.3
Node: 8.9.4
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

We are doing lazy loading for external bundle module in our application, the external bundle is created using ng-packagr.

**Source link:** 

External module: [lazy-module](https://github.com/NagarajMadyastha/lazy-module)
Application: [app-consume](https://github.com/NagarajMadyastha/app-consume
)
Steps to reproduce the issue.

1.  Bundle the external module "lazy-module" using "npm run cd"
2.  include the bundle in "app-consume" application using “npm install  dist.tgz”
3.  When we run or build app-consume application, using  “ng serve “ or “ng build” it fails

[Note: Issue won't reproduce in "ng serve -aot" and "ng build -aot",  command]


If we serve the application using development server using "ng serve" command, it fails with below error message.
Error: is logged bundle.d.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property
 

ERROR in ./node_modules/bundle/bundle.d.ts
Module build failed: Error: D:\consume\node_modules\bundle\bundle.d.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\consume\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (D:\\consume\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)


Able to run and build the app, using with help of "ng serve" and "ng build"

# comp: cli/build  #comp: cli/serve  #need: repro steps

**Comment by maciejtreder** [comment] 2018-04-06 08:46
It seems that `ng server` & `ng build` ignores tscofnig file specified by uesr.

I have an exactly same issue in my application. To reproduce:

```
git clone -b externalLibrary https://github.com/maciejtreder/angular-universal-pwa.git
cd angular-universal-pwa/application/
npm install
npm start (calls ng serve under the hood)
```

If you will run production build on this repo:
```
npm run build:prod
```
which calls ```ng build``` with --prod flag it works correctly (proper tsconfig files are used).

**Comment by maciejtreder** [comment] 2018-04-06 09:37
After a little bit more investigation. I found out that tsconfig described in .angular-cli.json is taken by ```ng serve```. I think that ```files``` section is ignored/overwritten somewhere...

**Comment by alan-agius4** [comment] 2019-02-05 12:57
Duplicate of https://github.com/angular/angular-cli/issues/6373

**Closed by alan-agius4** 2019-02-05 12:57 UTC
