### ISSUE TITLE
Add different css files conditionally

### ISSUE THREAD

**Issue by mousavidev** [angular/angular-cli#9301] opened 2018-01-19 19:08 UTC
My app uses different languages and some of them are right-to-left. I have two separate css files; one for LTR and the other for RTL.

how can i conditionally add a css file on component?

**Comment by jburtondev** [comment] 2018-01-19 22:07
@mousavidev Great question.This issue looks related: https://github.com/angular/angular-cli/issues/4685

**Comment by filipesilva** [comment] 2018-01-25 10:43
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/4685. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2018-01-25 10:43 UTC

**Comment by mousavidev** [comment] 2018-01-26 19:31
@filipesilva thanks.
