### ISSUE TITLE
Feature request: plugable hooks

### ISSUE THREAD

**Issue by no-more** [angular/angular-cli#13071] opened 2018-11-28 08:17 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
node -v
v10.13.0

yarn -v
1.12.3

npm -v
6.4.0

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.1.0
Node: 10.13.0
OS: win32 x64
Angular: 7.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.0
@angular-devkit/build-angular      0.11.0
@angular-devkit/build-ng-packagr   0.11.0
@angular-devkit/build-optimizer    0.11.0
@angular-devkit/build-webpack      0.11.0
@angular-devkit/core               7.1.0
@angular-devkit/schematics         7.1.0
@angular/flex-layout               7.0.0-beta.19
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.0
@schematics/angular                7.1.0
@schematics/update                 0.11.0
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1

```

### Repro steps

Not a bug

### The log given by the failure

NA

### Desired functionality

It was already asked previously but closed as out of scope prior version 1.
Could we now have an update about pluggable hooks. I'm not talking about npm pre and post script but rather something that could work with `--watch`.
My main use case is currently to be able to trigger a notification or an action at the end of the re-build in watch mode. Currently I have to keep an eye on the compilation box to check when the rebuild is over and then manually trigger the actions I want. This would be really usefull.

Thanks a lot

**Comment by alan-agius4** [comment] 2019-11-28 10:02
Duplicate of https://github.com/angular/angular-cli/issues/11787

**Closed by alan-agius4** 2019-11-28 10:02 UTC
Labels: type: feature
