### ISSUE TITLE
ng build/serve fails with "Error: No errors" message

### ISSUE THREAD

**Issue by duard** [angular/angular-cli#4264] opened 2017-01-28 11:53 UTC
### OS?
`Ubuntu 16.10 
`
### Versions.
 ```
 __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.26
node: 7.4.0
os: linux x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

### Repro steps.
New app created using => 
`ng new PROJECT
`
### The log given by the failure.
 ng serve

```
No errors
Error: No errors
    at validate (/home/carlos/empresa.com.br/PROJECT/node_modules/extract-text-webpack-plugin/schema/validator.js:10:9)
    at Function.ExtractTextPlugin.extract (/home/carlos/empresa.com.br/PROJECT/node_modules/extract-text-webpack-plugin/index.js:188:3)
    at /home/carlos/empresa.com.br/PROJECT/node_modules/angular-cli/models/webpack-build-styles.js:79:83
    at Array.map (native)
    at Object.getWebpackStylesConfig (/home/carlos/empresa.com.br/PROJECT/node_modules/angular-cli/models/webpack-build-styles.js:76:43)
    at new NgCliWebpackConfig (/home/carlos/empresa.com.br/PROJECT/node_modules/angular-cli/models/webpack-config.js:44:51)
    at Class.run (/home/carlos/empresa.com.br/PROJECT/node_modules/angular-cli/tasks/serve-webpack.js:23:22)
    at /home/carlos/empresa.com.br/PROJECT/node_modules/angular-cli/commands/serve.run.js:37:22
    at process._tickCallback (internal/process/next_tick.js:103:7)

```

This is just a new ubuntu and a new node npm and angular-cli install 

`carlos@carlos-Z97M-D3H:~/empresa.com.br/PROJECT(master○) » npm start                                                             1 ↵

> project@0.0.0 start /home/carlos/empresa.com.br/PROJECT
> ng serve

```
No errors
Error: No errors
    at validate (/home/carlos/empresa.com.br/PROJECT/node_modules/extract-text-webpack-plugin/schema/validator.js:10:9)
    at Function.ExtractTextPlugin.extract (/home/carlos/empresa.com.br/PROJECT/node_modules/extract-text-webpack-plugin/index.js:188:3)
    at /home/carlos/empresa.com.br/PROJECT/node_modules/angular-cli/models/webpack-build-styles.js:79:83
    at Array.map (native)
    at Object.getWebpackStylesConfig (/home/carlos/empresa.com.br/PROJECT/node_modules/angular-cli/models/webpack-build-styles.js:76:43)
    at new NgCliWebpackConfig (/home/carlos/empresa.com.br/PROJECT/node_modules/angular-cli/models/webpack-config.js:44:51)
    at Class.run (/home/carlos/empresa.com.br/PROJECT/node_modules/angular-cli/tasks/serve-webpack.js:23:22)
    at /home/carlos/empresa.com.br/PROJECT/node_modules/angular-cli/commands/serve.run.js:37:22
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Linux 4.8.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! project@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/carlos/empresa/PROJECT/npm-debug.log
```
`

**Comment by intellix** [comment] 2017-01-28 12:10
What version of `extract-text-webpack-plugin` are you running? I see that they released a new version just an hour ago: `2.0.0-rc.1` which is also giving me the above error. I'll try with the previous version.

**Comment by duard** [comment] 2017-01-28 12:14
How can I get the version of this `extract-text-webpack-plugin` ?

**Comment by filipesilva** [comment] 2017-01-28 12:15
@duard `npm ls extract-text-webpack-plugin` in your project.

**Comment by duard** [comment] 2017-01-28 12:22
```
carlos@carlos-Z97M-D3H:~/empresa.com.br/PROJECT(master⚡) » npm ls extract-text-webpack-plugin
project@0.0.0 /home/carlos/empresa.com.br/PROJECT
└── (empty)

npm ERR! code 1

```

**Comment by filipesilva** [comment] 2017-01-28 12:23
That's very odd... did you remove your node-modules? 

You should get something like this:
```
$ npm ls extract-text-webpack-plugin
master-project@0.0.0 D:\sandbox\master-project
`-- extract-text-webpack-plugin@2.0.0-rc.1
```

**Comment by jhuntoo** [comment] 2017-01-28 12:24
I'm also experiencing this just now - does angular-cli pin package version numbers under the hood ?

**Comment by Drakenfly** [comment] 2017-01-28 12:24
I can confirm that the problem does not occur anymore after installing the plugin at version 2.0.0-rc.0
(npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev)

**Comment by filipesilva** [comment] 2017-01-28 12:24
This problem arises from a recent update in a external dependency and it's not fixable without a CLI release right now. 

The workaround by @drakenly is the only option right now:
```
npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev
```

**Comment by duard** [comment] 2017-01-28 12:26
Yes, I did `rm -rf /usr/local/lib/node_modules ` after try everything ... now I will install angular-cli again
```
npm cache clean
npm uninstall -g angular-cli
npm install -g -f angular-cli
```
npm install is very slow here, I hope this work.

**Comment by netmikey** [comment] 2017-01-28 12:27
Same issue here since half an hour or so:

$ npm ls extract-text-webpack-plugin
rm5-frontend@0.0.0 /PROJECTS/myProject
├─┬ angular-cli@1.0.0-beta.24
│ ├── extract-text-webpack-plugin@**2.0.0-rc.1**

This was driving me nuts... can we PLEASE pin versions and stop using bleeding edge chaos unless some library explicitly asks for it? (e.g. like java/maven is doing it since like forever)?! 😡

**Comment by duard** [comment] 2017-01-28 12:54
Thanks @Drakenfly

**Comment by filipesilva** [comment] 2017-01-28 12:55
I'm going to leave this open since a lot of people are going to be searching for it. Will also change the title to something more obvious.

**Comment by Lopierdis** [comment] 2017-01-28 13:18
The new version uses ExtractTextWebpack 2.0.0.-rc.1 which contains the bug, it's still not fixed

**Comment by TomGeiger** [comment] 2017-01-28 13:33
I'm experiencing the same issue, 'no error' is displayed when I run ng serve.

└─┬ angular-cli@1.0.0-beta.26
  └── extract-text-webpack-plugin@2.0.0-rc.1

**Comment by laumair** [comment] 2017-01-28 13:33
@Drakenfly Thanks.  That did the trick.

` npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev` @Lopierdis

**Comment by gastikirs** [comment] 2017-01-28 13:33
Thanks @Drakenfly !

**Comment by TomGeiger** [comment] 2017-01-28 13:35
Thanks - that fixed me too!!

**Comment by hendryrenald1** [comment] 2017-01-28 13:35
Just today I started learning angular-cli. About 4 hrs it was working fine and started error an hour ago replacing the extract-text-webpackage solved the issue. Thanks filipesilva. 
This error drives me crazy, I just re-installed everything, without knowing the change in the repo. Is there any way we can identify the time or date the  repo is planning to upgrade in future.

**Comment by Lopierdis** [comment] 2017-01-28 13:43
@laumair this fix works for me, but it's only a hacky fix, and it prevents me from deploying to Heroku..

**Comment by meghadureja** [comment] 2017-01-28 13:47
Thanks @Drakenfly ! fixed now by running "npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev"

**Comment by wutthisakj** [comment] 2017-01-28 13:57
npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev also works for me. Thanks.

**Comment by stanleytakamatsu** [comment] 2017-01-28 14:02
`npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev` did not work for me.

If I remove the `node_modules` folder and then re-install` npm install`, it installs `2.0.0-rc.1`, even though it is saved in` package.json`:

```
{
  "DevDependencies": {
...
  "extract-text-webpack-plugin": "^ 2.0.0-rc.0",
...
}
}
```

any suggestion?

Thanks

**Comment by Drakenfly** [comment] 2017-01-28 14:09
You could try to clean your npm cache by running `npm cache clean`!

**Comment by stanleytakamatsu** [comment] 2017-01-28 14:12
I tried, but it does not work anyway.

The error happens in a clean installation inside a `container` of ` docker`.

**Comment by philipgeorgiev123** [comment] 2017-01-28 14:13
Seriously disappointed trying to learn angular ...

(node:1950) DeprecationWarning: `DEBUG_FD` is deprecated. Override `debug.log` if you want to use a different log function (https://git.io/vMUyr)
No errors
Error: No errors
    at validate (/Users/philipgg/IdeaProjects/AngularCLI/node_modules/extract-text-webpack-plugin/schema/validator.js:10:9)
    at Function.ExtractTextPlugin.extract (/Users/philipgg/IdeaProjects/AngularCLI/node_modules/extract-text-webpack-plugin/index.js:188:3)
    at /Users/philipgg/IdeaProjects/AngularCLI/node_modules/angular-cli/models/webpack-build-styles.js:79:83
    at Array.map (native)
    at Object.getWebpackStylesConfig (/Users/philipgg/IdeaProjects/AngularCLI/node_modules/angular-cli/models/webpack-build-styles.js:76:43)
    at new NgCliWebpackConfig (/Users/philipgg/IdeaProjects/AngularCLI/node_modules/angular-cli/models/webpack-config.js:44:51)
    at Class.run (/Users/philipgg/IdeaProjects/AngularCLI/node_modules/angular-cli/tasks/serve-webpack.js:23:22)
    at /Users/philipgg/IdeaProjects/AngularCLI/node_modules/angular-cli/commands/serve.run.js:37:22
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "start"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-cli@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-cli@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/philipgg/IdeaProjects/AngularCLI/npm-debug.log

**Comment by ssthil** [comment] 2017-01-28 14:16
Thanks @Drakenfly `npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev` its worked for me.

**Comment by philesc** [comment] 2017-01-28 14:21
`npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev works` for me too, thanks @Drakenfly

**Comment by DaniyarJakupov** [comment] 2017-01-28 14:24
Can confirm, `npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev` fixed the issue

**Comment by luAr26** [comment] 2017-01-28 14:41
Worked for me too `npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev`

**Comment by jimmy07** [comment] 2017-01-28 15:22
Yeah, That works !

**Comment by latentstops** [comment] 2017-01-28 15:27
Works for me too!

**Comment by KlausEichinger** [comment] 2017-01-28 15:43
Thanks @Drakenfly 
`npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev`
works fine

**Comment by wagneripjr** [comment] 2017-01-28 15:56
Thanks @Drakenfly

**Comment by philipgeorgiev123** [comment] 2017-01-28 15:58
npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev ok worked but what the heck is wrong :(

i am trying to learn angular 2

**Comment by spnv** [comment] 2017-01-28 15:58
Thanks @Drakenfly ! fixed now by running "npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev"

**Comment by TarekAlQaddy** [comment] 2017-01-28 16:03
Thanks @Drakenfly "npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev" 
fixed this issue 
Did you report about this problem or something?

**Comment by storymessinger** [comment] 2017-01-28 16:08
Does not work for me.

I had another error prior to this, which told me that I am lacking a module called ajv

I installed it but the error goes on....

`Error: No errors
    at validate (/Users/Jun/Udemy/Angular2/first-try/node_modules/angular-cli/node_modules/extract-text-webpack-plugin/schema/validator.js:10:9)
    at Function.ExtractTextPlugin.extract (/Users/Jun/Udemy/Angular2/first-try/node_modules/angular-cli/node_modules/extract-text-webpack-plugin/index.js:188:3)
    at /Users/Jun/Udemy/Angular2/first-try/node_modules/angular-cli/models/webpack-build-styles.js:79:83
    at Array.map (native)
    at Object.getWebpackStylesConfig (/Users/Jun/Udemy/Angular2/first-try/node_modules/angular-cli/models/webpack-build-styles.js:76:43)
    at new NgCliWebpackConfig (/Users/Jun/Udemy/Angular2/first-try/node_modules/angular-cli/models/webpack-config.js:44:51)
    at Class.exports.default.Task.extend.run (/Users/Jun/Udemy/Angular2/first-try/node_modules/angular-cli/tasks/build-webpack.js:18:22)
    at Class.buildRun (/Users/Jun/Udemy/Angular2/first-try/node_modules/angular-cli/commands/build.run.js:39:22)
    at Class.Command.extend.run (/Users/Jun/Udemy/Angular2/first-try/node_modules/angular-cli/commands/build.js:38:47)
    at Class.<anonymous> (/Users/Jun/Udemy/Angular2/first-try/node_modules/angular-cli/ember-cli/lib/models/command.js:147:17)
    at process._tickCallback (node.js:369:9)`

**Comment by UpperApps** [comment] 2017-01-28 16:09
@laumair , you saved my life. My hero. hahaha
Thank you!

**Comment by CAtoDC** [comment] 2017-01-28 16:17
npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev

This did the trick on a Win10 (64-bit) box as well.  Thanks!

**Comment by clement-jacquet** [comment] 2017-01-28 16:19
@duard exact same error just now on Windows x64 using yarn to load / download dependencies

**Comment by netmikey** [comment] 2017-01-28 16:42
@stanleytakamatsu It looks like the entry in your `package.json` is wrong: if you prefix the version with `^`, npm will still use the latest available version of the package, and **not** the one explicitly specified: the version is unpinned.

If you remove the `^` like this, it might work:

    "extract-text-webpack-plugin": "2.0.0-rc.0"

**Comment by Drakenfly** [comment] 2017-01-28 16:43
@stanleytakamatsu look at your package.json - what is the exact version that is saved to your package file?

I think you need to remove the caret at the start - so the line looks like: `"extract-text-webpack-plugin": "2.0.0-rc.0"`

**Comment by avatsaev** [comment] 2017-01-28 16:47
Guys this is insane, use fucking yarn, and pin your shit!

**Comment by sagikazarmark** [comment] 2017-01-28 16:49
Maybe this discussion should be locked with the solution as the last comment. There is nothing more that can be added here.

**Closed** 2017-02-03 20:16 UTC
Labels: priority: 0 (critical)
