### ISSUE TITLE
Bun support for Angular

### ISSUE THREAD

**Issue by jastraberg** [angular/angular-cli#24490] opened 2022-12-28 19:42 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

[Bun](https://bun.sh/) is a new JavaScript runtime. Currently, the Bun team only have plans to support React apps. However, the angular community could do with a runtime like Bun, seeing as the rendering speeds for React far exceed Node and Deno.

### Proposed solution

The Angular team reaches out to the Bun team to offer their friendly support/help to get things going.

### Alternatives considered

N/A

**Comment by dgp1130** [comment] 2023-01-05 19:38
Transferring to the CLI repository, since this is mostly a tooling feature.

I imagine most of the motivation here is for SSR and Universal with the hope of improved performance. We don't have any existing metrics to know if there are compelling performance wins here. Not sure if there's much interest in running the CLI on Bun or if it makes much difference, but it might be coupled in some ways.

We're keeping an eye on alternative JavaScript runtimes like Deno and Bun, but we don't have any active efforts to support or evaluate them right now. It would be great if Angular tooling worked with them, just not a major priority right now.

**Comment by alan-agius4** [comment] 2023-01-06 12:53
This is a duplicate of https://github.com/angular/angular/issues/46719

**Comment by alan-agius4** [comment] 2023-01-09 10:37
Closing as per above.

**Closed by alan-agius4** 2023-01-09 10:37 UTC
Labels: needs: clarification

**Comment by Halfist** [comment] 2023-01-21 19:18
> I get the impression that support for Angular is not being prioritized to the same extent as React.

That's true for majority of modern front-end projects. Unfortunately, since Angular is more closed than React, and because the latter is more opened for integrations, developers find it no-brainer to support React / React-like / React-based projects first. This feels very frustrating to me, mostly because I don't like JSX, unopinionated guidelines, Redux, Tailwind and some other things praised by that community.
