### ISSUE TITLE
import { AppModule } from './app/app.module';

### ISSUE THREAD

**Issue by oleksiipotiekhin** [angular/angular-cli#13888] opened 2019-03-12 19:00 UTC
# 🐞 Bug report
### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```
### Is this a regression?
No
### Description
By changing **AppModule** import url in **main.ts** `ng add @angular/pwa` or `ng add @angular/material` stop working because `getAppModulePath` from `ng-ast-utils.ts` combine `${mainDir}` from **angular.json** and `${moduleRelativePath}` from **main.ts**

![image](https://user-images.githubusercontent.com/30025319/54227180-af4e3c00-44ff-11e9-9cf8-fbd8ac5f6529.png)

## 🔬 Minimal Reproduction
Edit **tsconfig.json**

![image](https://user-images.githubusercontent.com/30025319/54226579-6d70c600-44fe-11e9-8077-dfc99b2abe9e.png)

Change the **AppModule** import url

![image](https://user-images.githubusercontent.com/30025319/54225932-fe46a200-44fc-11e9-8188-763855bbce88.png)

Run `ng add @angular/pwa` or `ng add @angular/material`
## 🔥 Exception or Error
<pre><code>Could not read file (/src/@app/app.module.ts).
</code></pre>
## 🌍 Your Environment
<pre><code>Angular CLI: 7.3.5
Node: 10.15.1
OS: win32 x64
Angular: 7.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.5
@angular-devkit/build-angular     0.13.5
@angular-devkit/build-optimizer   0.13.5
@angular-devkit/build-webpack     0.13.5
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cdk                      7.3.3
@angular/cli                      7.3.5
@angular/fire                     5.1.1
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.3.3
@angular/pwa                      0.12.4
@ngtools/webpack                  7.3.5
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>
## 🔬Resolution
`isRelativePath` function should be added to determine whether the path to **AppModule** from **main.ts** is relative or not

**Comment by alan-agius4** [comment] 2019-03-12 19:58
Duplicate of https://github.com/angular/angular-cli/issues/12740

**Closed by alan-agius4** 2019-03-12 19:58 UTC
