### ISSUE TITLE
Provide way to replace environment config after build

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular-cli#17088] opened 2020-02-26 05:22 UTC
Imagine that in our company we have Java, Python, NodeJS, web, etc. applications. We build them, next - deploy. On build stage we create artifacts which consists of compiled files. On deploy stage we apply environment settings to our artifacts (change configs or replace placeholders). Next we run application which read config and stands up.

This is common situation for any projects because of their artifacts contains separate config files (or files in archive which we can simply repack). For any except web. Web-artifact is a bunch of compiled html/js files which also include config. This is not simple to find and replace it.

What are possible solutions?
1. Store src in the artifact and build them any deploy. This contradicts the concept of an artifact.
2. Store config as separate js-chunk. This is possible but the issue shouldn't define structure of our bundles
4. Store config as asset and load it asynchronously. This makes our application more difficult
3. Find and replace config into the compiled js-files. This is possible, but it is too hard to find place of config correctly.

Well, we can combine 2 and 4 ways to simplify work with configs. E.g.
Angular-cli can make separate chunk for file which contains special `/* angular-cli:chunk-name:config */` directive on the top of file and stay this comment in the main chunk. So, we can process our config chunk and replace the comment on our processed config or any other config.
Or it can be settings in angular.json.

Maybe there are other ways. Think please about this issue.

**Comment by clydin** [comment] 2020-02-26 14:59
This is essentially a duplicate of https://github.com/angular/angular-cli/issues/7506.  That issue provides several options for runtime configuration.  Option 3 described above is actually quite achievable using an Angular service and the `APP_INITIALIZER` token.  The use of a service to provide application-wide configuration can be beneficial outside of the need for runtime configuration as well.

A search for `APP_INITIALIZER angular runtime configuration` should also provide a variety of articles describing potential implementations.

**Closed by clydin** 2020-02-26 14:59 UTC

**Comment by tamtakoe** [comment] 2020-02-27 17:07
@clydin It is too difficult and inefficiently.

The first solution proposed there
```
<script>
    APP_CONFIG = {};
</script>
...
export const config = (window as any).APP_CONFIG;
```
looks much better and understandable. More of this APP_INITIALIZER supposes that you should load config as separate file (by separate request). It is not good idea. And it is much easier to find and replace `APP_CONFIG = {}` on server side then our APP_INITIALIZER code.

On other side, who said that config is just collection of urls? What about translation strings?

In AngularJS time I was loaded configs and translation strings the same way (by $http) but on deploy stage I added my environment values to $http.defaults.cache (at the end of my artifact). It worked good... But why we need special middleware for config and thousands binding in our teplates for translation strings? It is not what we need in realtime. If user change locale or some base settings the best way is to reload page.

So, the next my approach was to find `$translate(...)` and `$config(...)` occurrences in my artifact and replace it to environment values (It needed to use `mangle:true`, in uglify config to keep variable names). This way allows us make application faster and easy for developers who don't need to think about environment stuff. Now in our React-applications we use ast-parser for post-processing our artifacts.

That is why it will be good to have some anchors in our compiled files for post-processing. Maybe it is not task for Angula-cli team, maybe - for Uglify community (or what you are using), who knows?

P.S. Of course we can use SSR, but we don't need it for many cases.

**Comment by tamtakoe** [comment] 2020-03-17 15:44
So. I tried several ways and I'm using this:
1. Build
a. Run special command before build which replaces content of config file to `export default ['unique_config_placeholder'] as any;`
b. Build with my fake config.
2. Deploy
a. Replace my production config file according environment.
3. Start server.
a. Find built js-artifact in the `dist` folder.
b. Replace `['unique_config_placeholder']` to production config.
c. Add middleware which returns the artifact (generally main-...js) with production config instead of original with fake config.
d. Run server.

This works nice and clear for developers without overhead in the angular code
