### ISSUE TITLE
chain() RuleFactory doesn't respect order when calling externalSchematic

### ISSUE THREAD

**Issue by thonythony** [angular/angular-cli#11736] opened 2018-08-01 13:54 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report
- [ ] feature request
```

### Command (mark with an `x`)
```
- [X] devkit/Schematics
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 6.1.1
Node: 8.11.3
Npm: v6.2.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.1
@angular-devkit/core         0.7.1
@angular-devkit/schematics   0.7.1
@schematics/angular          0.7.1
@schematics/update           0.7.1
rxjs                         6.2.2
typescript                   2.7.2

### Repro steps

Given this code : 

```typescript
import {
  Tree,
  Rule,
  externalSchematic,
  chain,
  SchematicContext
} from "@angular-devkit/schematics";

export function ngNew(options: any): Rule {
  const createAngularApp = externalSchematic(
    "@schematics/angular",
    "ng-new",
    options
  );
  return chain([
    (tree: Tree, context: SchematicContext) => {
      context.logger.info("Before ng-new");
      return tree;
    },
    createAngularApp,
    (tree: Tree, context: SchematicContext) => {
      context.logger.info("After ng-new");
      return tree;
    }
  ]);
}

```

### The log given by the failure

When I test this schematics, it seems to not respect order of chain call. The console output result :
``` 
Before ng-new
After ng -new
CREATE [...]
```

### Desired functionality
If chain respected, it shall output like that : 
```
Before ng-new
CREATE [...]
After ng-new
```

### Mention any other details that might be useful
This issue was original posted inside this archived repo : 
https://github.com/angular/devkit/issues/475

**Comment by clydin** [comment] 2018-08-01 14:30
Tree operations are always reported at the end of the execution.  Whereas log messages are shown to the user at the point of execution.  The rules themselves are actually executed in order.

**Comment by hansl** [comment] 2018-08-01 17:54
Hi @thonythony,

To add to what @clydin is saying, `Tree`s are only recording operations. When those operations are actually done to the filesystem, the tool report them.

If we were to report them as they happen, it would show up a lot of CREATE and UPDATEs, and would become too much noise (even for relatively small schematics like the angular ones). The log would likely look like:

```
Before ng-new
CREATE [...]
UPDATE [...]
UPDATE [...]
UPDATE [...]
After ng-new
```

Closing this as it's working as intended.

**Closed by hansl** 2018-08-01 17:54 UTC
