### ISSUE TITLE
Angular generates css instead of scss in library

### ISSUE THREAD

**Issue by PascalMainzer** [angular/angular-cli#22458] opened 2022-01-10 12:39 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was:  Angular Version 11

### Description

 Even though the scss schematic is present in the angular.json of the environment, new components generated in a library only have a css file. Generated components in the default app are created with a scss file. A similar issue seems to have happened in 2017, but the version of Angular I am running is v13.

## 🔬 Minimal Reproduction

`ng new repro`
Angular routing: No
Stylesheet format: SCSS
```
cd repro
ng g library ngx-repro --prefix=repro
ng g module components/rcomponent --project=ngx-repro
ng g component components/rcomponent --project=ngx-repro
```

## 🔥 Exception or Error

<pre><code>

CREATE projects/ngx-repro/src/lib/components/rcomponent/rcomponent.component.spec.ts (654 bytes)
CREATE projects/ngx-repro/src/lib/components/rcomponent/rcomponent.component.ts (297 bytes)
CREATE projects/ngx-repro/src/lib/components/rcomponent/rcomponent.component.css (0 bytes)
UPDATE projects/ngx-repro/src/lib/components/rcomponent/rcomponent.module.ts (285 bytes)

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.1.2
Node: 14.16.1
Package Manager: npm 8.3.0
OS: win32 x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
ng-packagr                      13.1.2
rxjs                            7.4.0
typescript                      4.5.4

</code></pre>

**Current workaround**
using `--style=scss` in the generate command will create a scss file in the component. Still needs to be tested for issues.

**Comment by alan-agius4** [comment] 2022-01-10 13:16
The configured stylesheet format via the prompt only applies to the default application. 

You change set the preferred stylesheet format workspace wide by using running the below:

```
 ng config schematics.@schematics/angular:component.style scss
```

Or, you can also apply this setting to a specific project:
```
 ng config projects.ngx-repro.schematics.@schematics/angular:component.style scss
```

**Comment by PascalMainzer** [comment] 2022-01-10 23:32
> The configured stylesheet format via the prompt only applies to the default application.
> 
> You change set the preferred stylesheet format workspace wide by using running the below:
> 
> ```
>  ng config schematics.@schematics/angular:component.style scss
> ```
> 
> Or, you can also apply this setting to a specific project:
> 
> ```
>  ng config projects.ngx-repro.schematics.@schematics/angular:component.style scss
> ```

For library-component generation in v.11, the library also used the configured stylesheet format in the default application though.

**Comment by alan-agius4** [comment] 2022-01-11 07:27
> For library-component generation in v.11, the library also used the configured stylesheet format from the default application though.

This seems to have been unindented behaviour that was fixed. Projects settings in this case the default application shouldn't effect other projects.

**Comment by alan-agius4** [comment] 2022-01-12 07:05
Closing since this is working as intended.

**Closed by alan-agius4** 2022-01-12 07:05 UTC
