### ISSUE TITLE
"ng test" does not bail on type definition errors

### ISSUE THREAD

**Issue by huyph** [angular/angular-cli#3424] opened 2016-12-06 03:29 UTC
### OS
Mac OSX - EL Capitan

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 6.4.0
os: darwin x64

### Repro steps.
- Have a default angular-cli setup in place (by running "ng new <project_name>")
- Then there should be `AppComponent` and its spec file created by default.
- Add a new method in `app.component.ts`:
```javascript
public static returnAorB(character: 'A' | 'B') {
  return character;
}
```

And add following line anywhere in `app.component.spec.ts`:
```javascript
expect(AppComponent.returnAorB('C')).toEqual('C');
```
- Run "ng test --watch=false"

It will generate an error complaining `Argument of type '"C"' is not assignable to parameter of type '"A" | "B"'.` But the command did not exit. 

### The log given by the failure.
```javascript
....
ERROR in [default] <path>/src/app/app.component.spec.ts:16:35 
Argument of type '"C"' is not assignable to parameter of type '"A" | "B"'.
.....
(Completes and Exits with successful code)
```

**Comment by hansl** [comment] 2016-12-06 18:45
Right, we don't check for build errors on test. That's a bug, thanks! Will fix.

**Comment by JohannesRudolph** [comment] 2016-12-08 06:30
I think this is a duplicate of https://github.com/angular/angular-cli/issues/2778 , which is incorrectly flagged as "need: repro steps" right now as @huyph here and @fabian-dev in the linked issue have produced a repro sample.

**Closed** 2017-03-20 16:10 UTC
Labels: effort1: easy (hours), priority: 2 (required), type: bug
