### ISSUE TITLE
addSymbolToNgModule fails when a token provider is present in the providers array of the NgModule

### ISSUE THREAD

**Issue by mlakhara** [angular/angular-cli#13103] opened 2018-11-30 17:10 UTC
https://github.com/angular/angular-cli/blob/508d4df48231d4db11b690c55d51a57094a9e3ff/packages/schematics/angular/utility/ast-utils.ts#L446

The code block is same as the section where NgModule Decorator metadata does not have the provided metaDataField, however this needs to be changed as in this particular case, the last element in the providers array is an ObjectLiteral and we have to append the Symbol inside ObjectLiteral's parent (ArrayLiteral) rather than the ObjectLiteral itself.

**Comment by alan-agius4** [comment] 2018-11-30 18:03
Duplicate of https://github.com/angular/angular-cli/issues/13080

Side note for next time, kindly follow the issue template when opening an issue.

**Closed by alan-agius4** 2018-11-30 18:03 UTC
