### ISSUE TITLE
ng update v7 core functionality broken

### ISSUE THREAD

**Issue by celesteking** [angular/angular-cli#19159] opened 2020-10-21 12:26 UTC
# 🐞 Bug report

### Command (mark with an `x`)
- [x] update

### Description

Really, guys, what's up with `ng update` again, it seems you've switched devs or something... Because it used to work brilliantly. And now it just riddled with bugs. I'm trying to follow your upgrade guide 6 -> 7 LTS.

I  managed to update `ng update @angular/cli@7 @angular/core@7` just fine, but next is Material update.
I installed all deps manuallly and properly (swimlane charts , etc).

Now I'm running material update and it **PULLS** angular **10**. Really?!

```
$ ng update  @angular/material@7
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/common" (requires "7.x" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/animations" (requires "7.x" (extended), would install "10.1.6").
                  Package "@angular/http" has an incompatible peer dependency to "@angular/core" (requires "7.2.15" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-datatable" has an incompatible peer dependency to "@angular/compiler" (requires "<8.0.0" (extended), would install "10.1.6").
                  Package "@angular/http" has an incompatible peer dependency to "@angular/platform-browser" (requires "7.2.15" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "zone.js" (requires "^0.8.26", would install "0.10.3").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/forms" (requires "7.x" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires "7.x" (extended), would install "10.1.6").
Incompatible peer dependencies found. See above.


$ ng update --force  --packages  @angular/material@7 
                  Package "@swimlane/ngx-datatable" has an incompatible peer dependency to "@angular/common" (requires "<8.0.0" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/animations" (requires "7.x" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-datatable" has an incompatible peer dependency to "@angular/compiler" (requires "<8.0.0" (extended), would install "10.1.6").
                  Package "@angular/http" has an incompatible peer dependency to "@angular/core" (requires "7.2.15" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-datatable" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires "<8.0.0" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/forms" (requires "7.x" (extended), would install "10.1.6").
                  Package "@angular/http" has an incompatible peer dependency to "@angular/platform-browser" (requires "7.2.15" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "zone.js" (requires "^0.8.26", would install "0.10.3").
    Updating package.json with dependency @angular/compiler-cli @ "10.1.6" (was "7.2.15")...
    Updating package.json with dependency @angular/language-service @ "10.1.6" (was "7.2.15")...
    Updating package.json with dependency @angular/common @ "10.1.6" (was "7.2.15")...
    Updating package.json with dependency @angular/animations @ "10.1.6" (was "7.2.15")...
    Updating package.json with dependency @angular/compiler @ "10.1.6" (was "7.2.15")...
    Updating package.json with dependency @angular/material @ "7.3.7" (was "6.4.7")...
    Updating package.json with dependency @angular/core @ "10.1.6" (was "7.2.15")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "10.1.6" (was "7.2.15")...
    Updating package.json with dependency @angular/forms @ "10.1.6" (was "7.2.15")...
    Updating package.json with dependency @angular/router @ "10.1.6" (was "7.2.15")...
    Updating package.json with dependency @angular/platform-browser @ "10.1.6" (was "7.2.15")...
    Updating package.json with dependency zone.js @ "0.10.3" (was "0.8.29")...
    Updating package.json with dependency typescript @ "4.0.3" (was "3.2.4")...
UPDATE package.json (1398 bytes)
^C             ....] - prepare:frontend: info lifecycle fraudmarc-ce@1.0.1~prepare: fraudmarc-ce@1.0.1
^C
```
I had to abort it. Why on Earth would you pull 10? Did I ask for that? No. I clearly specified **7**. 

Would you stop bringing students onto your projects and get real devs actually do the coding? This should've been caught by CI/CD tools and testing. Do you actually have testing? If yes, why wasn't it caught? It's right in your update guide, you should've caught it.

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.10
Node: 10.19.0
OS: linux x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.10
@angular-devkit/build-angular     0.13.10
@angular-devkit/build-optimizer   0.13.10
@angular-devkit/build-webpack     0.13.10
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cdk                      7.3.7
@angular/cli                      7.3.10
@angular/flex-layout              7.0.0-beta.24
@angular/material                 6.4.7
@ngtools/webpack                  7.3.10
@schematics/angular               7.3.10
@schematics/update                0.13.10
rxjs                              6.6.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Comment by celesteking** [comment] 2020-10-21 12:27
And for someone telling me v7 is EOL. I KNOW that, that's why I'm trying to update this legacy app. And it seems I can't just jump major versions , I have to do it iteratively.

**Comment by alan-agius4** [comment] 2020-10-21 12:41
Also, you are kindly maintain a professional behaviour as per our [code of conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md).

**Comment by alan-agius4** [comment] 2020-10-21 12:41
Looks like a duplicate of https://github.com/angular/angular-cli/issues/17143

Also, you are kindly maintain a professional behaviour as per our [code of conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md).

**Comment by alan-agius4** [comment] 2020-10-21 12:54
Closing as a duplicate of #17143

**Closed by alan-agius4** 2020-10-21 12:54 UTC

**Comment by celesteking** [comment] 2020-10-21 13:03
In that issue, they state `We did not have issues while lagging behind 6/7/8 releases.` . And I'm reporting against v7.
