### ISSUE TITLE
webpack-merge approach to 'eject'

### ISSUE THREAD

**Issue by bmayen** [angular/angular-cli#7814] opened 2017-09-24 21:56 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

Latest

### Desired functionality.

Currently the webpack eject approach dumps the entirety of the internal webpack configs into editable files. This completely detaches the configs from the CLI and any subsequent updates to the lib are not reflected in these configs.

I suggest a better approach would be to eject config stubs which leverage webpack-merge to allow us to selectively merge in different functionality. This would allow us to continue getting the latest and greatest CLI updates but still give us some flexibility to support custom use-cases.

### Mention any other details that might be useful.

Related to https://github.com/angular/angular-cli/issues/6731

**Comment by filipesilva** [comment] 2017-09-25 10:32
Heya, I'm sorry to say but this is essentially a duplicate of https://github.com/angular/angular-cli/issues/1656, with the official answer for now being there. I'll bring it up internally again to see if something changed though.

**Closed by filipesilva** 2017-09-25 10:32 UTC

**Comment by bmayen** [comment] 2017-09-25 11:22
Sorry, missed that one

**Comment by michaeljota** [comment] 2018-01-28 02:56
With something like this, resolving issues like #9107 would be trivial. I don't even would like something like the entire file to be merge, but better just to be able to override some of the default configuration. 
So, maybe something that would fit in Angular-CLI and also, would allow the users to customize is to allow to override certain webpack configurations through `.angular-cli.json` file.

**Comment by ruipimentel** [comment] 2018-01-28 18:49
Definitely agree with @michaeljota, a simple override in Webpack's `"target"` setting would solve my issue quite satisfactorily, eliminating the need for ejecting my app and keeping @angular/cli's commands functional as always.

**Comment by joaocc** [comment] 2018-01-29 19:50
I would also love to be able to override or define webpack's target setting... Currently we have to use an external and as of now unsupported package to work around that, and we dislike ejection for the reasons pointed above.
