### ISSUE TITLE
Error during template compile of 'Input'   Function calls are not supported in decorators but 'makePropDecorator' was called.

### ISSUE THREAD

**Issue by Gajendrasinh** [angular/angular-cli#14759] opened 2019-06-13 10:18 UTC
$ ng build --prod

Date: 2019-06-13T09:55:52.743Z
Hash: 226874ac2f15daa34818
Time: 40920ms
chunk {0} runtime-es5.9c308a63d02029c20228.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es5.4af9b61479361f268d39.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills-es5.374878e7def8b1ff61fc.js (polyfills) 68 kB [initial] [rendered]
chunk {3} styles.e1c712c6ca6213c9a477.css (styles) 144 kB [initial] [rendered]
chunk {scripts} scripts.613511dc7eb70f096b79.js (scripts) 424 kB [entry] [rendered]

ERROR in Error during template compile of 'Input'
  Function calls are not supported in decorators but 'makePropDecorator' was called.
Error during template compile of 'Input'
  Function calls are not supported in decorators but 'makePropDecorator' was called.
Error during template compile of 'Input'
  Function calls are not supported in decorators but 'makePropDecorator' was called.
Error during template compile of 'Input'
  Function calls are not supported in decorators but 'makePropDecorator' was called.
Error during template compile of 'Input'
  Function calls are not supported in decorators but 'makePropDecorator' was called.
Error during template compile of 'Input'
  Function calls are not supported in decorators but 'makePropDecorator' was called.
Error during template compile of 'Input'
  Function calls are not supported in decorators but 'makePropDecorator' was called.
Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'makeDecorator' was called.

**Comment by alan-agius4** [comment] 2019-06-13 10:44
Duplicate of https://github.com/angular/angular/issues/30988

**Closed by alan-agius4** 2019-06-13 10:44 UTC

**Comment by Gajendrasinh** [comment] 2019-06-13 11:01
In that no solution, can you please provide some information, 

Why this happened
