### ISSUE TITLE
ng build accepts any argument list and silently ignores them

### ISSUE THREAD

**Issue by PYL666** [angular/angular-cli#5935] opened 2017-04-12 15:11 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.5
os: darwin x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

```
### Repro steps.

Just type the command below:
```
$ ng build accepts any argument list and silently ignores them 
```
You then get the result:
```
$ ng build accepts any argument list and silently ignores them 
Hash: 7293d841f09f4d666afe                                                                 
Time: 32858ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 2.05 MB {3} [initial] [rendered]
chunk    {1} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 132 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.06 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
$ 
```

### The log given by the failure.

No log: the command line seems to succeed, letting you believe it did what you expect.

In the above case, it is obvious that the parameters are ignored.

Unfortunately you can end up with a weird result when you are unlucky enough to type (actually paste it from a web page...) commands like:

```
ng build ——prod ——aot true
```

 ⚡️ You are toasted. ⚡️ 

Indeed there is a mistake in this command line: the use of '—' instead of '-' but depending on the font of your terminal chances are you will not notice it.

And `ng build` gently finishes you up by silently misleading you. :smiling_imp:

### Desired functionality.

At least a warning, perhaps an error, telling that you have supplied parameters that are ignored.

In any case, it is not correct for a command to encounter superfluous parameters and not report them as ignored.

**Comment by filipesilva** [comment] 2017-05-05 10:10
@hansl is working on this in https://github.com/angular/angular-cli/pull/3893

**Comment by shairez** [comment] 2017-07-18 17:33
@Brocco I see that #3893 is closed, is it still relevant?

**Comment by filipesilva** [comment] 2017-07-19 08:49
Sorry, closed by mistake. This is not yet addressed. @hansl only closed the PR, but it wasn't merged.

**Comment by alan-agius4** [comment] 2018-10-25 08:14
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2018-10-25 08:14 UTC
Labels: effort1: easy (hours), freq2: medium, priority: 2 (required), severity1: confusing
