### ISSUE TITLE
co-mingle Static HTML site with Angular2 app for separate area

### ISSUE THREAD

**Issue by jpmyob** [angular/angular-cli#9545] opened 2018-02-08 06:55 UTC
My app is ONLY the members area of a very large static HTML site. so I want http://example.com/ to serve the STATIC html, and http://example.com/members to be the entry point to the Angular app.

'dist' is set to my static file dir in express, so when webpack does a build it deletes & creates dist - so I cant put my html in dist to start.

All the references I read on static html in an angular app are about adding things to the assets folder, or specifying a separate folder in the angular-cli.json assets object.

However - these solutions assume you are ENTERING the app, by default; so http://example.com/ puts you in your app-root, and I'd have to go to http://example.com/assets/ or http://example.com/static/ go get to my html

this obviously 'breaks' the existing url experience

I have tried setting base href="/members - but this only redirects the whole site to /members

I just tried setting the "outDir": "../dist/members", - which ALMOST works. As my HTML sitting in dist, works, and clicking a link to "/members" I get the "loading..." screen of my app; but it never loads.

I have tried setting the angular-cli.json "index": "members.html", and renaming the index file in my src folder to members.html - and that gets me 95% there, the app loads the main module but no sub components...

How does one default to HTML site, and have the angular app as a sub-directory?

my express has

app.get('*', (req,res) => {
    res.sendFile(path.join(__dirname,'dist/index.html'));
})

but I have also tried to have express default route to /static/ by using

res.sendFile(path.join(__dirname,'dist/static/index.html'));

but no luck - seems the 'index.html' defined in the angular-cli.json superceeds all.

How can I serve my regular HTML by default, and have my angular app avail on a specific 'route' like /members?

Cheers

**Comment by Brocco** [comment] 2018-02-08 19:55
This issue is a support issue and not a bug or issue with the CLI itself. I suggest submitting your question where you can can some support/assistance such as [StackOverflow](https://stackoverflow.com/questions/tagged/angular-cli).
Closing this issue.

You find some information in the [documentation](https://github.com/angular/angular-cli/wiki).

**Closed by Brocco** 2018-02-08 19:55 UTC
