### ISSUE TITLE
Environment as external chunk

### ISSUE THREAD

**Issue by michal-kroliczek** [angular/angular-cli#2929] opened 2016-10-28 07:43 UTC
Hi, 

this is feature proposition. I know already how environments should be use and it is quite ok. What would be nice is to put final environment.js as external chunk so it is loaded from  environment.js located somewhere next to index.html.

Motivation: 
I use docker for deployment. I found it really nice option to configure some properties (like backendUrl) at deployment time and not build time.  

Having environemnt in external file it would be easy to override them when docker starts by providing env variables.

**Comment by intellix** [comment] 2016-10-28 07:49
I guess you're thinking of doing something like a `sed` replace on the environment chunk before deployment to a particular environment.

I wonder if this sort of functionality should wait until we have Universal merged because at that point, we can actually use environment variables and inline the configuration inside index.html upon serve. Your Docker container would be a node service at that point.

**Comment by michal-kroliczek** [comment] 2016-10-28 09:03
Yep using 'sed' is the way I thought of. Could you please give more details about using env variables? How  will it work?

**Comment by intellix** [comment] 2016-10-28 13:25
well ideally if you had an actual node app (NG Universal delivering index.html), we could inline the config inside index.html. Maybe we would need to replace the original environment.ts values on runtime of the server like:

```ts
import { environment } from 'environments/environment';
environment.apiEndpoint = process.env.API_ENDPOINT;

// And then some middleware the inlines environment into index.html
```

**Comment by filipesilva** [comment] 2016-11-03 00:28
Dupe of https://github.com/angular/angular-cli/issues/2508

**Closed by filipesilva** 2016-11-03 00:28 UTC
