### ISSUE TITLE
Since 1.6.4 Angular Material CSS import does not work anymore (breaking change)

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular-cli#9185] opened 2018-01-12 13:23 UTC
### Versions
```
Angular CLI: 1.6.4
Node: 9.4.0
OS: linux x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.4
@angular/cli: 1.6.4
@angular/material: 5.0.4
@angular-devkit/build-optimizer: 0.0.37
@angular-devkit/core: 0.0.24
@angular-devkit/schematics: 0.0.45
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.12
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps
A new Angular CLI and Angular Material project like mentioned here:
https://material.angular.io/guide/getting-started

### Observed behavior
The import `@import "~@angular/material/prebuilt-themes/indigo-pink.css";` in the `styles.css` fails:
```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./src/styles.css
Module build failed: Error: Can't resolve '~@angular/material/prebuilt-themes/indigo-pink.css' in '/.../src'
    at onError (/.../node_modules/enhanced-resolve/lib/Resolver.js:61:15)
    at loggingCallbackWrapper (/.../node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/.../node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/.../node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/.../node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/.../node_modules/tapable/lib/Tapable.js:252:11)
    at /.../node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/.../node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/.../node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/.../node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/.../node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/.../node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/.../node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/.../node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/.../node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/.../node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
 @ ./src/styles.css 4:14-138
 @ multi ./src/styles.css
```

### Desired behavior
No error or update Angular Material Getting started section.

### Mention any other details that might be useful (optional)
Worked until 1.6.3 :)

**Comment by jolafrite** [comment] 2018-01-12 13:43
Same problem here
The postcss-url callbacks are never invoked

**Comment by clydin** [comment] 2018-01-12 14:04
This is indeed a defect and will be corrected in the next patch release.  The tilde can actually be removed to retain existing behavior.

**Comment by pferretti** [comment] 2018-01-12 14:05
Same problem here

ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./src/styles.css
Module build failed: Error: Can't resolve '~@angular/material/prebuilt-themes/indigo-pink.css'

**Comment by pferretti** [comment] 2018-01-12 14:13
Thanks @clydin ! removing the tilde correct the behaviour for Angular Material theme import.
In my project I also have an import for

`@import "~material-design-icons/iconfont/material-icons.css";`

and removing the tilde actually give the error
```

ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./src/styles.css
Module not found: Error: Can't resolve './MaterialIcons-Regular.woff2'
```

It worked until angular cli version 1.6.3 :-)

**Comment by clydin** [comment] 2018-01-12 14:31
@pferretti I provided further details over here on that particular problem: https://github.com/angular/angular-cli/issues/9166#issuecomment-357249253

Also, unless the application does not have access to the internet or has restrictions thereof, adding this to index.html should typically provide a performance benefit:
```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

**Comment by pferretti** [comment] 2018-01-12 14:53
Thank you @clydin , but unfortunately my app has restrictions and I have to rely on font self-hosting.

For reference, I temporarily copied Material Icon fonts in my assets folder and added to style.css the styles specified at https://google.github.io/material-design-icons/#setup-method-2-self-hosting

Probably not elegant, but it's a temporary solution that works :-)

**Comment by LosD** [comment] 2018-01-12 14:56
@pferretti You can also add the file to the `.angular-cli.json` styles array. That should copy it to the source and make a style link to it in head (just like it does for `src/styles.css`).

**Comment by clydin** [comment] 2018-01-12 15:06
@aarongranade it's not related and that should be working.  If it is, not ensure that the project's version of the CLI is updated (not just the global) and if the problem persists check which versions of autoprefixer are installed via `npm ls autoprefixer` and please respond in this issue: https://github.com/angular/angular-cli/issues/9029

**Comment by jolafrite** [comment] 2018-01-12 17:20
the solution I do to fix this issue is to change the part in https://github.com/angular/angular-cli/blob/1.6.x/packages/%40angular/cli/models/webpack-configs/styles.ts#L70 to

```js
postcssImports({
        resolve: (url: string, context: string) => {
          return new Promise<string>((resolve, reject) => {
            if(url.startsWith('~')) {
              url = url.substr(1);
            }
            loader.resolve(context, url, (err: Error, result: string) => {
              if (err) {
                reject(err);
                return;
              }

              resolve(result);
            });
          });
        },
```

**Comment by simeyla** [comment] 2018-01-12 22:41
Regarding the [release notes for Angular 5.2 ](https://blog.angular.io/angular-5-2-now-available-312d1099bd81)

I'm frankly getting sick of reading things like 'This is a minor release that is a drop-in replacement for 5.1 containing many bugfixes.' and then having to spend 2 hours getting it to work until i stumble upon the right issue after having gone round and round in circles.

I just cannot fathom how nobody involved in releasing 5.2 would stop to think 'hmm perhaps this update of our main project might cause a conflict with the latest version of our other main project'.

It just wastes probably literally millions of hours and all you need is to add a note. I'm sorry but it's pathetic.

**Comment by ravishivt** [comment] 2018-01-13 01:54
I moved the `@imports` from my `css` styles to my `scss` styles and they worked again.  Note that I was only having the issue for --prod builds so not sure if its a different issue.

In SCSS:
`@import url('https://fonts.googleapis.com/css?family=Material+Icons');`

**Comment by skalpin** [comment] 2018-01-13 02:38
I am also having this issue. Is there an easy way to roll back to angular-cli 1.6.0?

**Comment by zahmee** [comment] 2018-01-13 08:51
I am also having this issue.

**Comment by sniederb** [comment] 2018-01-13 09:50
Had the same issue, but for now I just downgraded CLI back to 1.6.3 (exact), and everything is fine.

**Comment by zahmee** [comment] 2018-01-13 10:34
> @sniederb 
not work with me   :(

**Comment by cyrilletuzi** [comment] 2018-01-13 10:41
It's [fixed](https://github.com/angular/angular-cli/commit/aaca7d832e867e2345aa00d07c476e60dbd8b6f6), we just have to wait for a new release.

**Comment by seffyfisher** [comment] 2018-01-13 12:22
anyone know how to downgrade i've tried :(after uninstall the leatest and clean cache verifed)
npm install -g @angular/cli@1.6.3
but it installed 1.6.4..

**Comment by sniederb** [comment] 2018-01-13 12:34
I did exactly what @seffyfischer posted, plus put the exact 1.6.3 version in packages. json. Worked for me

**Comment by seffyfisher** [comment] 2018-01-13 12:43
@sniederb i changed the "@angular/cli": "1.6.3" in the package.json still no good .
im still getting 
"ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./src/styles.css
Module build failed: Error: Can't resolve '~@angular/material/prebuilt-themes/indigo-pink.css' in 'C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\src'
    at onError (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\Resolver.js:61:15)
    at loggingCallbackWrapper (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\tapable\lib\Tapable.js:252:11)
    at C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\tapable\lib\Tapable.js:252:11)
    at innerCallback (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\Resolver.js:144:11)
    at loggingCallbackWrapper (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\tapable\lib\Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (C:\Users\ma\Desktop\CODING\angular\metrial\usingMetrial\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:44:6)
 @ ./src/styles.css 4:14-138
 @ multi ./src/styles.css"

after putting 
@import "~@angular/material/prebuilt-themes/indigo-pink.css";
inside style.css

//
if you enter in the terminal ng -v what do you get ? (im still getting 1.6.4)

**Comment by sniederb** [comment] 2018-01-13 14:24
@seffyfisher here's my output. 

```
>ng -v
Angular CLI: 1.6.3
Node: 6.11.1
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.0.4
@angular/cli: 1.6.3
@angular/flex-layout: 2.0.0-beta.10
....
```

I'm not sure what you did differently

**Comment by simeyla** [comment] 2018-01-13 19:17
Forget all this reverting to 1.6.3 stuff. 

##Just remove the tilde (`~`) from the path.

@import "@angular/material/prebuilt-themes/indigo-pink.css";

This works for me with Angular 5.2 with CLI 1.6.4

**Comment by seffyfisher** [comment] 2018-01-13 19:27
@simeyla thank you so much!

**Comment by aymanaladdin** [comment] 2018-01-13 21:53
actually removing telda '~' ,solved the problem for me either, i'm using:
angular-cli@1.6.4
npm@5.6.0
windows 8.1-64 bit.

**Comment by joswalt** [comment] 2018-01-14 05:38
I encountered this error with my projects as well. I spent a few hours trying to figure out why my builds were all of sudden failing. I don't believe changing how you process css imports through the CLI should be changed in patch release that could break projects.

I was able to get passed the issue by reverting back to CLI v1.6.2. I will update to a new version when the fix for this issue is released.

**Comment by realharry** [comment] 2018-01-14 06:16
This is indeed a serious problem. I have multiple angular apps built with angular material, and they are hosted on different services via CI (mostly, with the build running in a docker container). All these apps (which had code commits for the last couple of day) are now failing because the ci script installs the recent version of ng cli during the build/deployment process.

I'd appreciate it if the Angular team could share the ETA for the fix.

**Comment by Stephane-Peyroutet** [comment] 2018-01-16 16:55
I have the same problem with 1.6.4 with import related paths to icon font files that still work in 1.6.3.
So this is not an issue specific to Material CSS import (maybe a change of title ?).
I also noticed this new issue #9235 which is also related to another broken behavior (source maps) in relation with scss/css in the 1.6.4 release.
So it seems a bunch of the SCSS/CSS treatment has to be fixed before the next release and use 1.6.3 for now.

**Comment by smlombardi** [comment] 2018-01-16 17:08
I reported https://github.com/angular/angular-cli/issues/9235 and rolling back to 1.6.3 does not help my issue.

**Comment by fourctv** [comment] 2018-01-16 18:05
Yeah, the problem seems to be the tilda not being recognized by 1.6.4 as a reference to `node_modules`. I have the same issue with bootstrap and material, references on `styles.scss`. Removing the tilda did not fix it. For now, rolling back to 1.6.3 seems to be the only solution.

**Comment by agborkowski** [comment] 2018-01-17 09:44
downgrade is worked, package.json

```
   "@angular/cli": "^1.6.3",
```

then

```
 npm i -S -d -D @angular/cli
```

**Comment by jamsheer-thottathil** [comment] 2018-01-17 09:48
Downgrade worked to me  :)

**Comment by drullo** [comment] 2018-01-17 15:00
I was able to simply remove the tilde from the import statement in my styles.css that was for the Angular Material theme.  That worked.  However... that approach did not work for other imported styles (font-awesome, etc.).  So, I simply went back to the .angular-cli.json file to add my style imports there and that works fine with 1.6.4.

It is odd that the Angular team has let this seemingly simple bug out in the wild for so many days.  I would have expected this to be fixed the same day that 1.6.4 was released or the next day.

**Comment by michael-letcher** [comment] 2018-01-17 16:15
Also related (#9099)

**Comment by manimayan** [comment] 2018-01-18 10:28
This is the eay way to get rid of  "ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!."
Run the below:
npm install --save-dev @angular/cli@1.6.3

**Comment by CisSasGot** [comment] 2018-01-18 12:58
I had the same problem but adding 3 lines of code it seems that the problem has disappeared, I will see if everything works and let my know.

I added 
```JavaScript
if (url.startsWith("~")) {
              url = url.substr(1);
 }
```
 to the 
**`node_modules\@angular\cli\models\webpack-configs\styles.js`**
 file.

**Comment by Taha-Di-Nero** [comment] 2018-01-19 08:31
@CisSasGot Already merged see 5d346c1423f5d7297b1084d14de1665216450798

**Comment by clydin** [comment] 2018-01-22 15:32
Resolved in 1.6.5 & 1.7.0-beta.1.  If this problem still persists for anyone, please open a new issue detailing the circumstances of the problem.

**Closed by clydin** 2018-01-22 15:32 UTC
Labels: priority: 1 (urgent), type: bug

**Comment by GoodJeans** [comment] 2018-02-02 15:38
@CisSasGot hi my bug is similar to this however the angular version I am using is "@angular/cli": "1.6.1", they do not have postcssImports how do I fix it? Below is the code


"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const path = require("path");
const suppress_entry_chunks_webpack_plugin_1 = require("../../plugins/suppress-entry-chunks-webpack-plugin");
const utils_1 = require("./utils");
const eject_1 = require("../../tasks/eject");
const cssnano = require('cssnano');
const postcssUrl = require('postcss-url');
const autoprefixer = require('autoprefixer');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const customProperties = require('postcss-custom-properties');
/**
 * Enumerate loaders and their dependencies from this file to let the dependency validator
 * know they are used.
 *
 * require('exports-loader')
 * require('style-loader')
 * require('postcss-loader')
 * require('css-loader')
 * require('stylus')
 * require('stylus-loader')
 * require('less')
 * require('less-loader')
 * require('node-sass')
 * require('sass-loader')
 */
function getStylesConfig(wco) {
    const { projectRoot, buildOptions, appConfig } = wco;
    const appRoot = path.resolve(projectRoot, appConfig.root);
    const entryPoints = {};
    const globalStylePaths = [];
    const extraPlugins = [];
    // style-loader does not support sourcemaps without absolute publicPath, so it's
    // better to disable them when not extracting css
    // https://github.com/webpack-contrib/style-loader#recommended-configuration
    const cssSourceMap = buildOptions.extractCss && buildOptions.sourcemaps;
    // Minify/optimize css in production.
    const minimizeCss = buildOptions.target === 'production';
    // Convert absolute resource URLs to account for base-href and deploy-url.
    const baseHref = wco.buildOptions.baseHref || '';
    const deployUrl = wco.buildOptions.deployUrl || '';
    const postcssPluginCreator = function () {
        // safe settings based on: https://github.com/ben-eb/cssnano/issues/358#issuecomment-283696193
        const importantCommentRe = /@preserve|@licen[cs]e|[@#]\s*source(?:Mapping)?URL|^!/i;
        const minimizeOptions = {
            autoprefixer: false,
            safe: true,
            mergeLonghand: false,
            discardComments: { remove: (comment) => !importantCommentRe.test(comment) }
        };
        return [
            postcssUrl([
                {
                    // Only convert root relative URLs, which CSS-Loader won't process into require().
                    filter: ({ url }) => url.startsWith('/') && !url.startsWith('//'),
                    url: ({ url }) => {
                        if (deployUrl.match(/:\/\//) || deployUrl.startsWith('/')) {
                            // If deployUrl is absolute or root relative, ignore baseHref & use deployUrl as is.
                            return `${deployUrl.replace(/\/$/, '')}${url}`;
                        }
                        else if (baseHref.match(/:\/\//)) {
                            // If baseHref contains a scheme, include it as is.
                            return baseHref.replace(/\/$/, '') +
                                `/${deployUrl}/${url}`.replace(/\/\/+/g, '/');
                        }
                        else {
                            // Join together base-href, deploy-url and the original URL.
                            // Also dedupe multiple slashes into single ones.
                            return `/${baseHref}/${deployUrl}/${url}`.replace(/\/\/+/g, '/');
                        }
                    }
                },
                {
                    // TODO: inline .cur if not supporting IE (use browserslist to check)
                    filter: (asset) => !asset.hash && !asset.absolutePath.endsWith('.cur'),
                    url: 'inline',
                    // NOTE: maxSize is in KB
                    maxSize: 10
                }
            ]),
            autoprefixer(),
            customProperties({ preserve: true })
        ].concat(minimizeCss ? [cssnano(minimizeOptions)] : []);
    };
    postcssPluginCreator[eject_1.postcssArgs] = {
        variableImports: {
            'autoprefixer': 'autoprefixer',
            'postcss-url': 'postcssUrl',
            'cssnano': 'cssnano',
            'postcss-custom-properties': 'customProperties'
        },
        variables: { minimizeCss, baseHref, deployUrl }
    };
    // determine hashing format
    const hashFormat = utils_1.getOutputHashFormat(buildOptions.outputHashing);
    // use includePaths from appConfig
    const includePaths = [];
    let lessPathOptions;
    if (appConfig.stylePreprocessorOptions
        && appConfig.stylePreprocessorOptions.includePaths
        && appConfig.stylePreprocessorOptions.includePaths.length > 0) {
        appConfig.stylePreprocessorOptions.includePaths.forEach((includePath) => includePaths.push(path.resolve(appRoot, includePath)));
        lessPathOptions = {
            paths: includePaths,
        };
    }
    // process global styles
    if (appConfig.styles.length > 0) {
        const globalStyles = utils_1.extraEntryParser(appConfig.styles, appRoot, 'styles');
        // add style entry points
        globalStyles.forEach(style => entryPoints[style.entry]
            ? entryPoints[style.entry].push(style.path)
            : entryPoints[style.entry] = [style.path]);
        // add global css paths
        globalStylePaths.push(...globalStyles.map((style) => style.path));
    }
    // set base rules to derive final rules from
    const baseRules = [
        { test: /\.css$/, use: [] },
        { test: /\.scss$|\.sass$/, use: [{
                    loader: 'sass-loader',
                    options: {
                        sourceMap: cssSourceMap,
                        // bootstrap-sass requires a minimum precision of 8
                        precision: 8,
                        includePaths
                    }
                }]
        },
        { test: /\.less$/, use: [{
                    loader: 'less-loader',
                    options: Object.assign({ sourceMap: cssSourceMap }, lessPathOptions)
                }]
        },
        {
            test: /\.styl$/, use: [{
                    loader: 'stylus-loader',
                    options: {
                        sourceMap: cssSourceMap,
                        paths: includePaths
                    }
                }]
        }
    ];
    const commonLoaders = [
        {
            loader: 'css-loader',
            options: {
                sourceMap: cssSourceMap,
                importLoaders: 1,
            }
        },
        {
            loader: 'postcss-loader',
            options: {
                // A non-function property is required to workaround a webpack option handling bug
                ident: 'postcss',
                plugins: postcssPluginCreator,
                sourceMap: cssSourceMap
            }
        }
    ];
    // load component css as raw strings
    const rules = baseRules.map(({ test, use }) => ({
        exclude: globalStylePaths, test, use: [
            'exports-loader?module.exports.toString()',
            ...commonLoaders,
            ...use
        ]
    }));
    // load global css as css files
    if (globalStylePaths.length > 0) {
        rules.push(...baseRules.map(({ test, use }) => {
            const extractTextPlugin = {
                use: [
                    ...commonLoaders,
                    ...use
                ],
                // publicPath needed as a workaround https://github.com/angular/angular-cli/issues/4035
                publicPath: ''
            };
            const ret = {
                include: globalStylePaths,
                test,
                use: buildOptions.extractCss ? ExtractTextPlugin.extract(extractTextPlugin)
                    : ['style-loader', ...extractTextPlugin.use]
            };
            // Save the original options as arguments for eject.
            if (buildOptions.extractCss) {
                ret[eject_1.pluginArgs] = extractTextPlugin;
            }
            return ret;
        }));
    }
    if (buildOptions.extractCss) {
        // extract global css from js files into own css file
        extraPlugins.push(new ExtractTextPlugin({ filename: `[name]${hashFormat.extract}.bundle.css` }));
        // suppress empty .js files in css only entry points
        extraPlugins.push(new suppress_entry_chunks_webpack_plugin_1.SuppressExtractedTextChunksWebpackPlugin());
    }
    return {
        entry: entryPoints,
        module: { rules },
        plugins: [].concat(extraPlugins)
    };
}
exports.getStylesConfig = getStylesConfig;
//# sourceMappingURL=/users/hansl/sources/hansl/angular-cli/models/webpack-configs/styles.js.map

**Comment by germs12** [comment] 2018-02-12 13:40
I resolved the issue by upgrading `@angular/cli` to version `1.6.5` via my `package.json`

`"@angular/cli": "^1.6.5",`

**Comment by moorthi07** [comment] 2018-04-06 21:29
@clydin Its  still not working with ng build --prod with below config.
Hope you guys added an unit test for this feature. 

devDependencies": {
    "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "^5.2.9",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "^2.6.2"
  }

**Comment by clydin** [comment] 2018-04-06 21:41
Yes, there are [tests](https://github.com/angular/angular-cli/blob/1.7.x/tests/e2e/tests/build/styles/material-import.ts) for multiple forms in both global and component styles in all of the following: CSS, SCSS, LESS, and stylus.

Please open a new issue with a minimal reproduction so that the problem can be fully examined.

**Comment by moorthi07** [comment] 2018-04-07 19:37
@clydin would't it be a duplicate?

**Comment by xAvarice** [comment] 2018-09-27 07:49
Beyond ridiculous. If I have to spend another set of hours having to hunt down such stupid issues... a tilde that used to work... really? I'm just going to switch to a different framework it is getting impossible to work with.
