### ISSUE TITLE
Schematic workflow failed

### ISSUE THREAD

**Issue by HiIamAnil** [angular/angular-cli#11366] opened 2018-06-25 13:40 UTC
While creating new using ng 

I got below error 

"Package install failed, see above."

then I uninstalled node_modules in my local folder and I again ran 
ng new ..
I got below error
"Schematic workflow failed "

Can anybody guide what went wrong in this case. Thanks in advance. 
@patrickoliveras @angular-cli

**Comment by ryanmccormick** [comment] 2018-06-29 16:30
I am not sure if this will work for you, but it might be worth a try:
1. Open a new terminal window and verify your current node version: `node -v`. is compatible `Node 8.9 or higher, together with NPM 5.5.1 or higher`
2. Delete your node_modules/ folder
3. Delete your package-lock.json file
4. run `npm cache verify`
5. run `npm install` again

**Comment by ryanmccormick** [comment] 2018-06-29 17:22
I removed my previous solution as I somehow got hung up on the `uninstalled node_modules` part and presented a solution that probably wouldn't have been relevant. Here is an alternate solution that might work for you...

1. Open a new terminal and run `node -v` and then `npm -v` to make sure you are running compatible versions: "Node 8.9 or higher, together with NPM 5.5.1 or higher"
2. Uninstall your current Global Angular cli `npm uninstall -g @angular/cli`
3. Run `npm cache verify`
4. Re-Install Angular CLI `npm install -g @angular/cli@latest`
5. Close your terminal window (just because).
6. Open a new terminal window, browse to where you want your new project and try the 'ng new` command again.

**Comment by Brocco** [comment] 2018-07-26 17:48
I agree with @ryanmccormick that something seems off with your installation. Please follow up with the results... close this issue if you're successful and if not, please try to provide some additional information.

Thanks!

**Comment by alan-agius4** [comment] 2018-09-04 16:14
Closing as no feedback was provided.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2018-09-04 16:14 UTC
Labels: comp: schematics/angular, freq1: low, need: more info, severity3: broken

**Comment by dimassp** [comment] 2019-08-18 03:57
thank you @ryanmccormick
