### ISSUE TITLE
[Feature Request] A hook file to customize webpack config.

### ISSUE THREAD

**Issue by larssn** [angular/angular-cli#10954] opened 2018-05-22 13:44 UTC
**Intro**
We dearly need a lightweight way to customize the internal webpack config file, so advanced users can tweak it, and still use the CLI, without having to eject. The current approach of having to eject causes a huge amount of overhead (also for the CLI team it seems). In NG5, we personally had 4 different fully complete webpack config files, to satisfy our dev environment, which was getting out of hand.

Since you can't eject in NG6, you currently have people rewriting `node_modules` files, to do some simple customizations. See https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d

**Proposal**
Doing an `ng serve/whatever` calls a hook file, where you can customize the webpack config related to the current `ng` command.

```
function webpackHook(config) {
   config.node = {
       crypto: true,
   }

   const args = require('yargs').argv;
   if (args.stats) {
    try {
         console.log('Adding Stats Plugin');
         const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
         config.plugins.push(new BundleAnalyzerPlugin());
      } catch (e) {
         console.error('webpack-bundle-analyzer not installed - `npm i webpack-bundle-analyzer --save-dev`');
      }
   }

   return config;
}
```

A hook file like this would probably remove the need to eject in the first place.

_Was originally posted here, where it seemed to gather support_: https://github.com/angular/angular-cli/issues/1548#issuecomment-387136761

**Comment by vincentjames501** [comment] 2018-05-22 13:51
Thumbs up and upvote! Would probably eliminate most peoples need to eject at all as I know it would us.

**Comment by filipesilva** [comment] 2018-05-22 14:20
I'm really sorry that I have to close this issue but this is still a duplicate of https://github.com/angular/angular-cli/issues/1656, and our stance on this topic still has not changed. If it changes, we will announce it on that issue.

**Closed by filipesilva** 2018-05-22 14:20 UTC

**Comment by vincentjames501** [comment] 2018-05-22 14:39
@filipesilva Any word on the "addon" system that's been in the works for 2 years?

```
Sorry but we will not expose the webpack confit for various reasons. An addon system is being designed that would allow such a thing but for the time being we won't expose it.
```

**Comment by filipesilva** [comment] 2018-05-22 14:43
The new workspace is part of that addon system. It provides extension points from where you can change what running `ng` commands do.

The upcoming eject (https://github.com/angular/angular-cli/pull/10946) leverages that. The plan is that doing `ng eject` will give you a hand-written webpack config, and that then doing `ng run project-name:build-webpack` runs that config.

If you replace the ejected target name (this is the keys inside the `architect` entry in your `angular.json` file) from `build-webpack` to just `build`, then `ng build` will run your webpack config instead.

**Comment by michael-letcher** [comment] 2018-05-22 22:58
Disappointing to see the Angular team rejecting collaboration and would rather close tickets and lock them than keep an open ticket on the subject allowing for discussion...

**Comment by RyRy79261** [comment] 2018-05-30 10:53
How is this issue still going on. 

I've spent 2 days reading through post starting in 2016 relating to this issue. There needs to be a better way than simply running a post install patch directly into the node module to allow for minor webpack tweaking.

**Comment by JonnyBGod** [comment] 2018-06-02 17:36
I understand the amount of maintenance problems that would come from exposing the full webpack.config. But I also think that it is totally nonsense to need to ```ng eject``` and then have to maintain it myself just to be able to add and extra webpack loader.

Why not compromise a bit and expose some parts of the webpack.config with a simple plugin/hook system?

Also you could easily do this while throwing a "At your own risk!" warning.

**Comment by darkguy2008** [comment] 2018-06-07 20:32
I can't believe that we're in 2018 and this issue is still alive. I'm finding myself in the need to use google-fonts-webpack-plugin and without ejecting I can't do it.

I fail to see why it's **so complicated** to use webpack-merge and merge it with whatever file the user can specify through the CLI and get it done. 2 years on this? come on... I used to do this almost daily in all my projects, and they were easily overridable, however, I'm being forced to use the CLI and I can't find a way to override just a specific portion of the config (adding a plugin).

Come on, this is basic stuff, give the user a choice or the possibility to do so.

**Comment by urish** [comment] 2018-06-20 22:42
Check out [angular-cli-customizer](https://github.com/nfriend/angular-cli-customizer) - did the trick for me

**Comment by darkguy2008** [comment] 2018-06-20 23:09
@urish Awesome!! Exactly what I was looking for! Someone give these men a beer and include this as a core functionality in the CLI. I can't believe someone had to hack it... still, great.

**Comment by sublimator** [comment] 2018-06-25 08:07
Yes, what a pita, I just upgraded an old app, which suddenly stopped working due to `node: false` being added, then I realized I have to... 

Ugh

**Comment by pawelkondraciukinstapage** [comment] 2018-06-28 08:22
It would be so great to have an option to customize angular-cli config with `webpack.config.js` file, just like `webpackMerge`

**Comment by pawelkondraciuk** [comment] 2018-06-28 08:22
It would be so great to have an option to customize angular-cli config with webpack.config.js file, just like webpackMerge

**Comment by 001123** [comment] 2018-08-15 03:30
Please add soon!
VUE, REACT can easy add webpack config.

**Comment by Pringels** [comment] 2018-11-01 07:50
+1

The recent upgrade to angular 7 completely broke coverage reporting in our monorepo setup. The response from the Angular team was that it was "by design". All I need to do to fix this is to disable a single line in the `@angular-dekit/build-angular` test webpack config. 

I'm seriously starting to consider switching my team over to `Vue.js` for future projects. I've encountered many requests like this one where the default response always seems to be "Deal with it. Issue closed." 

There has to be some middle ground here :(

**Comment by keaukraine** [comment] 2019-04-16 13:04
I used [angular-builders](https://github.com/meltedspark/angular-builders) to patch Angular 7 configs.

**Comment by klemenoslaj** [comment] 2019-04-16 18:04
> I used [angular-builders](https://github.com/meltedspark/angular-builders) to patch Angular 7 configs.

This works pretty nice, but only for the applications. If you have multiple libraries in your repo consumed by the application, then custom webpack builder will not help.

Referenced custom webpack builder hooks only into `@angular-devkit/build-angular` builder, which is used to build applications.
Libraries use `@angular-devkit/build-ng-packagr` builder, which I think is rollup undedr the hood even.

So yea, in a bit more advanced situation we have no workaround at all.
