### ISSUE TITLE
Autoprefixer "browsers" option is deprecated in v9, produces warnings

### ISSUE THREAD

**Issue by bjornharvold** [angular/angular-cli#14674] opened 2019-06-05 10:43 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ x] build
```

### Description
Cleaned my node_modules today and did a full rebuild. When building my libraries, I am getting this warning:

## 🔬 Minimal Reproduction
- Grab the latest version of Angular CLI and type

```
ng new myproject
ng g library mylib
ng build --project mylib
```
## 🔥 Exception or Error
<pre><code>
Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.1
Node: 12.3.1
OS: darwin x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.1
@angular-devkit/build-angular      0.800.1
@angular-devkit/build-ng-packagr   0.800.1
@angular-devkit/build-optimizer    0.800.1
@angular-devkit/build-webpack      0.800.1
@angular-devkit/core               8.0.1
@angular-devkit/schematics         8.0.1
@angular/cli                       8.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.1
@schematics/angular                8.0.1
@schematics/update                 0.800.1
ng-packagr                         5.2.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**
Gatsbyjs had the same issue yesterday:
https://github.com/gatsbyjs/gatsby/issues/14530

**Comment by alan-agius4** [comment] 2019-06-05 10:55
Angular CLI uses ng-packagr under the hood to build libraries.

Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1310

**Closed by alan-agius4** 2019-06-05 10:55 UTC
