### ISSUE TITLE
Angular CLI fails after updating to v13

### ISSUE THREAD

**Issue by plamenNachevICB** [angular/angular-cli#22202] opened 2021-11-19 15:49 UTC
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes

### Description

After updating to Angular 13 and updating most packages the angular CLI fails when trying to create a component

## 🔬 Minimal Reproduction

ng generate component test-component

## 🔥 Exception or Error

<pre><code>
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (D:\View\MyProject\node_modules\@angular\cli\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (D:\View\MyProject\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at D:\View\MyProject\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (D:\View\MyProject\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (D:\View\MyProject\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (D:\View\MyProject\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (D:\View\MyProject\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at D:\View\MyProject\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (D:\View\MyProject\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (D:\View\MyProject\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:568:18)
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.3
Node: 14.17.4
Package Manager: npm 6.14.14
OS: win32 x64

Angular: 13.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            8.3.29
@angular-devkit/schematics      8.3.29
@angular/cli                    13.0.3
@nguniversal/builders           13.0.1
@nguniversal/express-engine     13.0.1
@schematics/angular             8.3.29
rxjs                            6.6.7
typescript                      4.4.4
</code></pre>

**Anything else relevant?**

"devDependencies": {
    "@angular-devkit/build-angular": "^13.0.3",
    "@angular-eslint/builder": "^13.0.1",
    "@angular-eslint/eslint-plugin": "^13.0.1",
    "@angular-eslint/eslint-plugin-template": "^13.0.1",
    "@angular-eslint/schematics": "^13.0.1",
    "@angular-eslint/template-parser": "^13.0.1",
    "@angular/cli": "^13.0.3",
    "@angular/compiler-cli": "^13.0.2",
    "@bahmutov/cy-api": "^1.6.1",
    "@briebug/cypress-schematic": "^4.4.0",
    "@cypress/code-coverage": "^3.9.11",
    "@cypress/webpack-preprocessor": "5.7.0",
    "@datorama/akita-ng-router-store": "^6.0.2",
    "@datorama/akita-ngdevtools": "^6.0.1",
    "@istanbuljs/nyc-config-typescript": "^1.0.1",
    "@nguniversal/builders": "^13.0.1",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/leaflet": "^1.7.6",
    "@types/node": "^12.20.37",
    "@typescript-eslint/eslint-plugin": "5.3.0",
    "@typescript-eslint/parser": "5.3.0",
    "codelyzer": "^6.0.0",
    "cypress": "^7.1.0",
    "cypress-multi-reporters": "^1.2.4",
    "eslint": "^8.2.0",
    "istanbul-instrumenter-loader": "^3.0.1",
    "istanbul-lib-coverage": "^3.2.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "^6.3.9",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "local-web-server": "^4.2.1",
    "mocha": "~8.2.1",
    "mocha-junit-reporter": "^1.23.3",
    "ngx-build-plus": "^13.0.1",
    "nyc": "^15.1.0",
    "prettier": "2.1.2",
    "sonar-scanner": "^3.1.0",
    "source-map-support": "^0.5.21",
    "start-server-and-test": "^1.14.0",
    "ts-node": "^8.10.2",
    "tslint": "~6.1.0",
    "typescript": "~4.4.4"
  }

There was a similar issue caused by old version of @angular-eslint, but the issue persists after updating to the latest version so I'm not sure if it's still a problem of @angular-eslint.

**Comment by alan-agius4** [comment] 2021-11-19 16:21
It’s seems that you are using an older version of `@schematics/angular`. If you have it listed in your dependencies please remove it.

**Comment by plamenNachevICB** [comment] 2021-11-22 07:53
I noticed that the `@schematics/angular` version seems older, it should be 13 I suppose. I can't figure out how to update it though. I though upgrading the angular cli to 13 should update the schematics as well.

This is the result of `npm ls @schematics/angular`:
`estata-customer-portal@0.0.0 D:\View\MyProject
+-- @angular/cli@13.0.3
| `-- @schematics/angular@13.0.3 
+-- @briebug/cypress-schematic@4.4.0
| `-- @schematics/angular@10.2.3
+-- @datorama/akita@6.2.4
| `-- schematics-utilities@2.0.3
|   `-- @schematics/angular@8.3.29
`-- ngx-build-plus@13.0.1
  `-- @schematics/angular@13.0.3`

Any idea how I can update the `@schematics/angular` to the latest version?

**Comment by alan-agius4** [comment] 2021-11-22 08:06
`@datorama/akita` and `@briebug/cypress-schematic` are pulling old versions of `@schematics/angular` which is not compatible with the latest version fo the Angular CLI. Please remove the mention dependencies.

Closing since this issue is not caused by the Angular CLI.

**Closed by alan-agius4** 2021-11-22 08:06 UTC
Labels: need: more info
