### ISSUE TITLE
path mapping "node_modules/core-js/proposals/reflect-metadata" does not exist in the file-system

### ISSUE THREAD

**Issue by Toso82** [angular/angular-cli#17428] opened 2020-04-09 08:44 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes this is a regression

### Description

 A clear and concise description of the problem...
WARNING in The basePath "C:/Users/Giacomo/Documents/Progetti/Angular/forMca/node_modules/core-js/proposals/reflect-metadata" computed from baseUrl "C:/Users/Giacomo/Documents/Progetti/Angular/forMca" and path mapping "node_modules/core-js/proposals/reflect-metadata" does not exist in the file-system.
It will not be scanned for entry-points.

## 🔬 Minimal Reproduction

ng serve

## 🔥 Exception or Error
<pre><code>
Warning: The basePath "C:/Users/Giacomo/Documents/Progetti/Angular/forMca/node_modules/core-js/proposals/reflect-metadata" computed from baseUrl "C:/Users/Giacomo/Documents/Progetti/Angular/forMca" and path mapping "node_modules/core-js/proposals/reflect-metadata" does not exist in the file-system.
It will not be scanned for entry-points.

chunk {main} main.js, main.js.map (main) 877 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 291 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 622 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 2.44 MB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.28 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 14.9 MB [initial] [rendered]
Date: 2020-04-09T08:23:25.475Z - Hash: 5ea679a50e78eb6c3623 - Time: 25592ms

WARNING in The basePath "C:/Users/Giacomo/Documents/Progetti/Angular/forMca/node_modules/core-js/proposals/reflect-metadata" computed from baseUrl "C:/Users/Giacomo/Documents/Progetti/Angular/forMca" and path mapping "node_modules/core-js/proposals/reflect-metadata" does not exist in the file-system.
It will not be scanned for entry-points.

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
  

Angular CLI: 9.1.1
Node: 13.9.0
OS: win32 x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@angular/cdk                       9.2.0
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.0
@angular/material-moment-adapter   9.2.0
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-04-09 09:15
Duplicate of https://github.com/angular/angular/issues/36518

**Closed by alan-agius4** 2020-04-09 09:15 UTC
