### ISSUE TITLE
Strange compiling bug

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#5469] opened 2017-03-17 08:06 UTC
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report

When you change a interface the TSLinter and the Angular CLI are not throwing errors anymore? It happens with different things too. When i run ng serve again for example it works again or it throws errors. But while changing files it seems to remember old stuff..

When you have a file with interfaces and have imported them somewhere else, and then start the project by ng serve it works correctly.
But when already running and reference to a exported interface it stops working.

### Versions.
CLI RC2
Node 7.8
YARN/NPM

### Repro steps.
Make a interface, couple it to a function

### Desired functionality.
Working again, so it needs to throw and error.

### Mention any other details that might be useful.
-

**Comment by masaanli** [comment] 2017-03-17 08:17
Another simple example when it happens:

I had:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { CoreModule } from './core/core.module';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AppRoutingModule,
    CoreModule.forRoot(),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

I changed it to:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { CoreModule } from './core/core.module';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    ReactiveFormsModule,
    AppRoutingModule,
    CoreModule.forRoot(),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Then I save it and cli is auto seeing the changes and gives this error...
Then im getting the error `ERROR in /repos/vreugd-online/src/app/app.module.ts (18,5): Cannot find name 'ReactiveFormsModule'.)`?

When stop the cli and run ng serve again then it works again.

**Comment by filipesilva** [comment] 2017-03-18 15:10
Dupe of https://github.com/angular/angular-cli/issues/5404, fixed in https://github.com/angular/angular-cli/pull/5489

**Closed by filipesilva** 2017-03-18 15:10 UTC
