### ISSUE TITLE
Respect .editorconfig indent_size and indent_type when generating code

### ISSUE THREAD

**Issue by atheros** [angular/angular-cli#23658] opened 2022-07-29 21:12 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

It would be more than awesome for Angular generated files to use indent size and type that is specified for the project it is used in.

It is annoying to have to open each file and reformat it after being generated (either by `ng new` or `ng g`).

What ends up happening is commits often have just reformatting of files, which is pretty pointless and seems to be not so difficult to address.

Similar issues or requests are / were being discussed in #10777 and #9953

### Describe the solution you'd like

Use .editorconfig indent_size and indent_type property from appropriate section (file type wildcard) when generating files.

This looks to be the best solution since Angular is providing by itself this file. So using those properties makes sense.

Initial `ng new` could also accept properties that set those, but it's like a stretch goal :)

### Describe alternatives you've considered

Alternative solution would be to run a formatter that would fix the intendation automatically.

**Comment by alan-agius4** [comment] 2022-07-29 21:31
Thanks for this issue.

Let’s continue tracking this in https://github.com/angular/angular-cli/issues/10777 as that is the desired resolution.

Also duplicate of https://github.com/angular/angular-cli/issues/16684

**Closed by alan-agius4** 2022-07-29 21:31 UTC
