### ISSUE TITLE
Assets in templates like (svg stack)

### ISSUE THREAD

**Issue by tamascsaba** [angular/angular-cli#6386] opened 2017-05-19 11:53 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Use icon stack in angular template like:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" [ngClass]="{'use-current-color ': useCurrentColor}">
  <use attr.xlink:href="assets/images/stack.svg#{{name}}"></use>
</svg>
```
Generated output will be the same.

### Desired functionality.
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" [ngClass]="{'use-current-color ': useCurrentColor}">
  <use attr.xlink:href="stack.509859ebb28ab1f45c2e.svg#{{name}}"></use>
</svg>
```
Webpack parse the template generate a same hashed file, which i use in styles too.

**Comment by clydin** [comment] 2018-01-05 19:56
This appears to be a duplicate of https://github.com/angular/angular-cli/issues/3415.  Please follow that issue for any updates.

**Closed by clydin** 2018-01-05 19:56 UTC
Labels: priority: 3 (nice to have), severity3: broken
