### ISSUE TITLE
Bootstrap styles not loading

### ISSUE THREAD

**Issue by Harsangeet** [angular/angular-cli#3411] opened 2016-12-05 19:56 UTC
Hi,

I followed the steps for Global Library Installation  [https://github.com/angular/angular-cli#global-library-installation](https://github.com/angular/angular-cli#global-library-installation) 

1. Installed bootstrap@3.3.7 
    npm install bootstrap --save

2. Then added the needed script files to to apps[0].scripts in angular-cli.json file:

```
 "scripts": [
    "../node_modules/bootstrap/dist/js/bootstrap.js"
    ],
```

and  the Bootstrap CSS to the apps[0].styles array:

```
"styles": [
    "styles.css",
    "../node_modules/bootstrap/dist/css/bootstrap.css"
    ],
```

3. Restarted ng serve

But the bootstrap styles are not loading
 

OS- Windows 7 Enterprise

angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64

**Comment by hansl** [comment] 2016-12-05 21:36
@filipesilva Any idea?

**Comment by rolandoldengarm** [comment] 2016-12-06 09:43
I'm using Bootstrap v4 with exactly this approach in beta.21 without any issue...

**Comment by vfedoriv** [comment] 2016-12-11 17:05
I too. And when downgrade to bootstrap 3.3.7 - still work.
(node 7.2.0)

**Comment by yanxiaodi** [comment] 2016-12-31 14:09
I have the same problem with bootstrap v3.3.7.  I use the same config like you and it doesn't work now.

**Comment by lukas-kloeppel** [comment] 2017-01-09 08:09
I'm facing the same problem with angular-cli: 1.0.0-beta.21, node 7.2.1 and 4.0.0-alpha.6.

Bootstrap content is included in the generated styles.bundles.css file, but not available in the page

**Comment by Dinistro** [comment] 2017-02-27 14:40
I can confirm this behavior in 1.0.0-rc.0. I will try to create a reproduction and add it here, if I'm done.

**Comment by Dinistro** [comment] 2017-02-28 06:54
I found the problem in my case:

If you try to use a bundle from a linked npm package it breaks, because webpack works with the absolute path of the files and so, the exclude options of webpack aren't working anymore. I'm not sure if this is an issue of webpack or not. 

There are more problems with linked projects, e.g.  #5049, where this could be the reason of the failure.

**Comment by maxguzeng** [comment] 2017-03-15 11:05
me also. the style is applied is i import bootstrap.css in styles.css. but i can not get it working in angular-cli.json > styles array.

**Comment by filipesilva** [comment] 2017-05-22 14:43
Closing as outdated. If this still happens, please let me know.

**Closed by filipesilva** 2017-05-22 14:43 UTC
Labels: need: investigation, type: bug

**Comment by Zhuinden** [comment] 2017-08-10 13:30
I'm trying to follow a tutorial and I added the following to my `.angular-cli.json`

      "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/bootstrap/dist/js/bootstrap.min.js"
      ],

But bootstrap does not show on the page.

Changing my index.html into this ugly mess works, but I'm pretty sure this webpack magic should handle it.

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>MyApp</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<app-root>Loading...</app-root>
<script src="//code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>
```

I also have `"bootstrap": "3.3.7"` in my package.json. Not sure if that did anything. I'm new to this thing.

**Comment by filipesilva** [comment] 2017-08-21 10:14
@Zhuinden the example in https://github.com/angular/angular-cli/wiki/stories-global-lib is for Bootstrap 4, but you are using Bootstrap 3.

**Comment by alextait1** [comment] 2017-12-06 16:31
I had this issue, then a good old exit and re-run of ng serve was all I needed to do.

**Comment by faizy6641** [comment] 2018-02-19 23:33
@filipesilva ,Could u pls check my issue #9690?i am also facing similar type of issue.
I am stuck in this issue from past 2 weeks,pls help me out.Thanks

**Comment by manojsgh** [comment] 2018-02-23 04:28
I had the same problem with bootstrap 4. I uninstall and installed version 3 and it worked
npm -install bootstrap@3 --save
.angular-cli.json
"styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.css" 
      ],

**Comment by shireefkhatab** [comment] 2018-03-14 03:44
All you need to do is: 1- Go to .angular-cli.json under thr root directory of your angular app.

2- Modify the styles array to include bootstrap before styles.css

"styles": [
    "../node_modules/bootstrap/dist/css/bootstrap.min.css",
    "styles.css"
  ],
Note: the path to bootstrap is relative to /src/index.html that's why you need "../" before node_modules.

3- Exit the current session of ng serve and start it again.

Here is an Awesome tutoral
[https://www.youtube.com/watch?v=JYPyy-hvjYc&list=PL6n9fhu94yhXwcl3a6rIfAI7QmGYIkfK5&index=1#t=05m18s](url)

**Comment by VerticalWorks** [comment] 2018-03-16 15:56
For me, I just added the following to my Angular-cli.json file, and it worked...  remember, WebPack needs to know "where and what to include :)  Be sure to restart "ng serve"
"styles": [
"../node_modules/bootstrap/dist/css/bootstrap.min.css",
"styles.css"
],

**Comment by ManojSonowal** [comment] 2018-04-07 11:37
Solution of manojsgh worked for me too.

**Comment by mutantkeyboard** [comment] 2018-04-13 08:59
I have resolved this by reading the link provided by @filipesilva

**Comment by nadyscoolcodes** [comment] 2018-04-27 10:56
Thanks @alextait1 !! Your method worked for me.......

**Comment by irfanakbar47** [comment] 2018-05-01 20:35
Restart npm server

**Comment by nadyscoolcodes** [comment] 2018-05-02 02:39
Okay

**Comment by STEPHINRACHEL** [comment] 2018-05-08 09:44
restart the application using   ng serve

**Comment by Yi98** [comment] 2018-06-18 05:37
@alextait1 Works like a charm. Thank you so much :)

**Comment by Rakeshmgowda** [comment] 2018-06-18 10:47
### ****

**Comment by Bridgeway** [comment] 2018-07-08 12:39
I have no bootstrap folder in my node_modules after installing bootstrap 4.1.1.tgz

**Comment by juandrn** [comment] 2018-07-28 21:22
manojsgh solution works for me, I was trying the  filipesilva solution but wihout results.

**Comment by francesfang** [comment] 2018-08-03 18:56
I ran into the same issue,Bootstrap was not loading with Angular 6, no matter how I tried to import , finally solved by downgrading bootstrap 4 to 3

**Comment by alalicon577** [comment] 2018-09-08 20:39
add to styles.css
@import "~bootstrap/dist/css/bootstrap.min.css";

**Comment by yawningphantom** [comment] 2018-09-09 07:09
I can confirm that this issue is because of bootstrap 4. I am using angular 6 and was trying to include bootstrap v4 it wasn't showing up and then I downgraded to bootstrap v3 and it works like a charm. Simply use the command 
npm install bootstrap@3 --save
to downgrade to bootstrap v3

**Comment by echosanjeet** [comment] 2018-09-10 11:00
try removing single dot (.). See below.
"./node_modules/bootstrap/dist/css/bootstrap.min.css"

**Comment by navgag33** [comment] 2018-10-14 17:42
Ran into the same issue and had to downgrade to version 3 of bootstrap and it worked.

**Comment by dotNetAthlete** [comment] 2018-10-22 18:10
I also have the same issue, however I am using version 4.1.3 as I want to be up to date. (The instructor is still using 3.3.7)  I am following a Udemy tutorial.

In my angular.json, I have this:
"styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "src/styles.less"
            ],

because at some point I would like the flexibility of .less.

**Comment by dotNetAthlete** [comment] 2018-10-22 18:21
Downgrading to version 3 isn't a solution and is absurd.
Imaging if as a professional developer you got told: "Oh our API won't work with .net core, so you'll have to re-write that app that you've just spent the last 6 months building to perfection in .net 4.5 !"   :(

**Comment by dotNetAthlete** [comment] 2018-10-23 07:28
The only way I can get to use the version 4 + styles is to use a CDN link at the top of app\src\styles.css:

`@import 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css';`

That's great when on occasions the bootstrapcdn server is down and all my users see an unstyled app - very professional.

Could someone PLEASE explain why 4 + can't be used the same as 3.3.7 upwards, WHAT is broke and WHY ?

**Comment by dotNetAthlete** [comment] 2018-10-23 08:47
https://www.techiediaries.com/angular-bootstrap/

That link should clear up a lot of confusion.

**Comment by navgag33** [comment] 2018-10-28 09:32
Thank You so Much @dotNetAthlete, So cut to the chase, The only thing we need to do is to use the latest Bootstrap:
Add **@import "~bootstrap/dist/css/bootstrap.css"** to your **styles.css** in the src folder and you are good to go.

**Comment by vantive** [comment] 2018-11-15 11:35
I checked all the options and tried each suggested here in the post. But only working option is by uninstalling 4.* version by (npm uninstall bootstrap --save) and next by installing bootstrap 3.3.7 (npm install bootstrap@3.3.7 --save).. 

**

> it worked like charm.

**

for other advanced members/users who dont want to disturb their existing version they have to deal with some intricacies of how to deal with such issues (for e.g. popper.js, jquery.js versions etc) and also know how to map these with the current bootstrap version.. then it might work!

but for me the priority to was to make my learning curve smooth and dont get mingled in these intricacies for now.

all the best!

happy coding.

**Comment by NdiBrithaLea** [comment] 2018-12-17 06:06
Had thesame problem. But just restartes my server (ng-serve)

**Comment by rahuls360** [comment] 2018-12-25 06:35
I had the same issue yesterday. I found a solution to it.
I was importing the styles and script files in the wrong place in angular.json file
It must be under **build** and not **test** object

I found the solution here https://stackoverflow.com/questions/51998505/styles-not-picking-from-angular-json-styles-array-angular-6-but-working-fine-wi

**Comment by Houuse** [comment] 2019-01-07 16:17
don't work until downgrade , 
best solution Uninstall angular -> install react -> enjoy

**Comment by arif7503** [comment] 2019-05-14 22:06
Just put

"scripts": [
    "./node_modules/bootstrap/dist/js/bootstrap.js"
    ],


"styles": [
    "styles.css",
    "./node_modules/bootstrap/dist/css/bootstrap.css"
    ],

Hope that it would work :)

**Comment by bhavinshiroya1994** [comment] 2019-06-11 07:15
same issue please let know if any one getting solution.

**Comment by lwensveen** [comment] 2019-06-12 15:38
Still an issue sadly

**Comment by nenadbulatovic** [comment] 2019-07-17 20:15
It happen to me today. 
Firstly I resolved it by adding `@import "~bootstrap/dist/css/bootstrap.min.css";` into styles.css but then I decided to look more into it and I compare angular.json file one from the previous projects where Bootstrap 3 was loading without issues. It is only that "Meld" (compare tool) reveled to me that in a hurry erroneously  I added path to the bootstrap `           "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "src/styles.css"
            ],`
under the **"test"** section instead under "architect" section.
Once moved to ""architect" section, bootstrap started loading.

**Comment by Anatoly03** [comment] 2019-08-11 11:43
I'm inputting all 3 scripts and the bootstrap styling inside the index.html, same error.

**Comment by MohamedAbdeljelil** [comment] 2019-08-19 09:40
> It happen to me today. Ubuntu, Angular 8, Bootstrap 3.
> Firstly I resolved it by adding `@import "~bootstrap/dist/css/bootstrap.min.css";` into styles.css but then I decided to look more into it and I compare angular.json file one from the previous projects where Bootstrap 3 was loading without issues. It is only that "Meld" (compare tool) reveled to me that in a hurry erroneously I added path to the bootstrap ` "styles": [ "node_modules/bootstrap/dist/css/bootstrap.min.css", "src/styles.css" ],`
> under the **"test"** section instead under "architect" section.
> Once moved to ""architect" section, bootstrap started loading.

Thanks i have the same problem and it's work now

**Comment by mac10046** [comment] 2019-08-26 14:48
I am using angular 8 and installed bootstrap 4 + jquery using npm - and it does not work. I tried putting it inside index.html (download via CDN) and it still did not worked. The strange thing noticed by me is that although the bootstrap file are loaded but they are always the .scss extension files from the node_modules folder even if you provide the files in index.html and remove it from angular-cli.json completely
This seems to be a default behaviour somehow and I could not understand how and why is it happening. I don't want downgrade to bootstrap 3 because I want to use the flexbox css

Any help is appreciated.

**Comment by manikanthvanka** [comment] 2019-09-07 08:25
> > It happen to me today. Ubuntu, Angular 8, Bootstrap 3.
> > Firstly I resolved it by adding `@import "~bootstrap/dist/css/bootstrap.min.css";` into styles.css but then I decided to look more into it and I compare angular.json file one from the previous projects where Bootstrap 3 was loading without issues. It is only that "Meld" (compare tool) reveled to me that in a hurry erroneously I added path to the bootstrap ` "styles": [ "node_modules/bootstrap/dist/css/bootstrap.min.css", "src/styles.css" ],`
> > under the **"test"** section instead under "architect" section.
> > Once moved to ""architect" section, bootstrap started loading.
> 
> Thanks i have the same problem and it's work now
