### ISSUE TITLE
including modernizr causes white screen

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#6546] opened 2017-06-02 03:31 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.2
os: win32 x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
@angular/platform-server: 4.0.1
```

### Repro steps.
1. Generated modernizr.js:
```
.\node_modules\.bin\modernizr -c .\node_modules\modernizr\lib\config-all.json
```
2. Moved to src\js folder (src is the root of my app)
3. Added `"js/modernizr.js"` to .angular-cli.json
4. Running ng serve shows a blank screen in the browser. No errors. 

### The log given by the failure.
None

### Desired functionality.
The site should keep working.

**Comment by filipesilva** [comment] 2017-06-06 12:50
That's odd. @Brocco can you investigate?

**Comment by narainsagar** [comment] 2017-07-14 23:14
@filipesilva Can I give it a try?

**Comment by narainsagar** [comment] 2017-07-15 08:42
@rolandoldengarm @filipesilva fyi. On the latest release `1.2.1` i.e.,
```
@angular/cli: 1.2.1
node: 7.9.0
os: darwin x64
```
@rolandoldengarm I have tried your repro steps and it seems working fine (no log errors, etc) and modernizr is also available on the dom.
![screen shot 2017-07-15 at 1 41 57 pm](https://user-images.githubusercontent.com/13800762/28237981-6ddf95bc-6963-11e7-9666-7f08ac23cae9.png)

**Comment by filipesilva** [comment] 2017-07-17 10:20
@narainsagar thanks for the repro, closing as working as intended 👍

**Closed by filipesilva** 2017-07-17 10:20 UTC
Labels: community: help wanted, effort1: easy (hours), priority: 2 (required), severity3: broken, type: bug

**Comment by Ismaestro** [comment] 2017-08-30 09:54
@rolandoldengarm said that it was a balck screen. Modernizr works, but the page is in blank as well for me too. No errors.

```
   _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.2
node: 7.1.0
os: darwin x64
```

**Comment by Ismaestro** [comment] 2017-08-31 12:41
I solved not including all modernizr tests. Just a few, and download modernizr-custom.js and include this file in .angular-cli.json
