### ISSUE TITLE
(Feature Request) - ng generate test

### ISSUE THREAD

**Issue by AlanCrevon** [angular/angular-cli#6584] opened 2017-06-06 08:05 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.1.0
node: 7.7.0
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6-6aaddbf
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3

OSX Sierra

### Desired functionality.

Could ng generate a test after a component was written ? 
Something like `ng g test to-test.component.ts` could (over)write test, maybe even including required dependencies analyzing the component.

Thanks.
alan

**Comment by tkstang** [comment] 2018-01-12 00:26
Just curious if this is something the team has plans to implement? Or more specifically if so where this is on the roadmap?

**Comment by BirgitPohl** [comment] 2018-02-15 12:49
I was specifically looking for a generate command that inserts dependencies, because it is just very inconvenient searching for all dependencies in a bigger project. I am sure a proper tool can do that automatically, because it is all about pointers.
One generated test with dependencies included that has the test "should create", so that I know the component instance is created without any problems and I can start create tests for the specific functions.

**Comment by alan-agius4** [comment] 2020-01-11 16:14
Duplicate of https://github.com/angular/angular-cli/issues/7727

**Closed by alan-agius4** 2020-01-11 16:14 UTC
Labels: comp: schematics/angular, type: feature
