### ISSUE TITLE
reload does not work

### ISSUE THREAD

**Issue by aercanunal** [angular/angular-cli#3273] opened 2016-11-24 21:10 UTC
angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: linux x64 (ubuntu 16.04)

Hello,
I create angular2 project with angular cli and when i changed a file (css, html or ts files) and go to the browser and refresh the pages to see change but live reload does not work.

i restart with ng serve to see changes

**Comment by NextLevelNoob** [comment] 2016-11-27 03:30
The same for me. I simply installed angular-cli, generated a new project, ran ng serve, changed some html, and live reload did not work. The debugging console does not show any errors, says "Angular 2 is running in development mode..."

angular-cli 1.0.0.-beta21
node: 7.2.0. (but before tried with node 6.9 - same result)
os: windows 10 x64

It seems like the system does not recognize any file-changes.

**Comment by NextLevelNoob** [comment] 2016-11-30 01:20
Just saw that there is another issue about that, so mentioning it here for others
https://github.com/angular/angular-cli/issues/1610

**Comment by NextLevelNoob** [comment] 2016-11-30 01:58
And another update (for others facing the same problem): the following solved the problem for me: reinstalling angular-cli with @latest:

1. npm uninstall -g angular-cli
2. npm cache clean
3. npm install -g angular-cli@latest

**Comment by filipesilva** [comment] 2016-12-29 20:39
Dupe of #1610, yes.

**Closed by filipesilva** 2016-12-29 20:39 UTC

**Comment by ManuelQuiroz** [comment] 2017-08-03 22:18
Increasing the amount of inotify watchers


**The technical details**

Listen uses inotify by default on Linux to monitor directories for changes. It's not uncommon to encounter a system limit on the number of files you can monitor. For example, Ubuntu Lucid's (64bit) inotify limit is set to 8192.

You can get your current inotify file watch limit by executing:

    $ cat /proc/sys/fs/inotify/max_user_watches

When this limit is not enough to monitor all files inside a directory, the limit must be increased for Listen to work properly.

You can set a new limit temporary with:

    $ sudo sysctl fs.inotify.max_user_watches=524288
    $ sudo sysctl -p

If you like to make your limit permanent, use:

    $ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
    $ sudo sysctl -p

You may also need to pay attention to the values of *max_queued_events* and *max_user_instances* if Listen keeps on complaining.


[more info here][1]


  [1]: https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
