### ISSUE TITLE
Auto-commit when executing ng generate

### ISSUE THREAD

**Issue by Thomas1664** [angular/angular-cli#18152] opened 2020-07-04 21:22 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] version
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] doc

### Description
The Angular CLI initialises a git-repo after creating a new app and performs an initial commit. Additionally, the update-command offers a similar option.
I would find it helpful if there was an option when generating a new component, service, etc. to auto-commit the generation with a message like:
Generate <TYPE> <NAME>

### Describe alternatives you've considered
Normally, I commit the generation of new components or services by myself.

**Comment by clydin** [comment] 2020-07-06 20:44
Duplicate of #7948

**Closed by clydin** 2020-07-06 20:44 UTC
