### ISSUE TITLE
Warning "*.worker.ts is part of the TypeScript compilation but it's unused." displayed for any web worker you have.

### ISSUE THREAD

**Issue by MaKCbIMKo** [angular/angular-cli#20415] opened 2021-03-31 09:35 UTC
# 🐞 Bug report

### Command
- [ x] build

### Is this a regression?

I have updated from Angular 9 to Angular 11. In Angular 9 I had now such warnings...
So, it might be a regression, or this is just another check and rules need to be adjusted.

### Description

Something weird happens using web-workers within Angular 11 application. It starts to display warnings for any worker you have:

```
Warning: /**/*.worker.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

But it behaves very strange. If you have only one worker - it gets built without any warnings. If then you add second worker - it will display 2 warnings. Third worker will make it to 6 warnings displayed.

Also, good to mention: if you also have 'js' worker (e.g. `new Worker('./some.worker.js')`) - it will print warning for any other 'ts' worker you have (any 'ts' worker that has been discovered by 'tsconfig.worker.json').

From what I found - it's somehow related to each `new Worker('...')` call in your code.

## 🔬 Minimal Reproduction

So, I made the following steps:
1. generate new application: `ng new web-worker-app`
2. add web-worker: `ng generate web-worker first`
3. add using of this worker in app.component, something like:
```
  const firstWorker = new Worker('./first.worker', { type: 'module' });
  firstWorker.postMessage('hello');
```
4. calling `npm run build` -> will show no warnings
5. add another web-worker: `ng generate web-worker second`
6. add using of this worker in app.component, so it will be:
```
  const firstWorker = new Worker('./first.worker', { type: 'module' });
  firstWorker.postMessage('hello');
  const secondWorker = new Worker('./second.worker', { type: 'module' });
  secondWorker.postMessage('hello');
```
7. calling `npm run build` -> will show 2 warnings (one for each worker)

8. We can go further and add 'js' worker to our app and add it to app.component
```
  // other TS workers instantiation here

  const jsWorker = new Worker('./my.worker.js');
  jsWorker.postMessage('hello);
```
9. calling `npm run build` -> will show 4 warnings

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.5
Node: 14.16.0
OS: win32 x64

Angular: 11.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.5
@angular-devkit/build-angular   0.1102.5
@angular-devkit/core            11.2.5
@angular-devkit/schematics      11.2.5
@angular/cli                    11.2.5
@schematics/angular             11.2.5
@schematics/update              0.1102.5
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Anything else relevant?**
In my specific case, I have to use only 'js' worker. But in order to make it automatically bundled, I need to have at least one 'dummy' typescript worker file that will be discovered by `tsconfig.worker.json`. I haven't found any other work-around here...

**Comment by MaKCbIMKo** [comment] 2021-03-31 09:38
Initially I started with this issue: https://github.com/angular/angular-cli/issues/19372 as it has the same warnings that I do.

But what I found is that it's not related to 'exclude' settings for `tsconfig.app.json`.

**Comment by alan-agius4** [comment] 2021-03-31 09:41
Duplicate of https://github.com/angular/angular-cli/issues/19938

**Closed by alan-agius4** 2021-03-31 09:41 UTC
