### ISSUE TITLE
ng test command failing with a disconnect after waiting to connect to Chrome

### ISSUE THREAD

**Issue by betxaburu** [angular/angular-cli#9584] opened 2018-02-09 16:32 UTC
**_ng test_** command failing with a disconnect after waiting to connect to Chrome after updating Chrome to 64.0.3282.144 version.

### Versions

@angular/cli: 1.4.9
node: 6.12.0
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.6.2

Chome version 64.0.3282.144

### Repro steps
* update Chrome to 64.0.3282.144 (in case you have an older version)
* execute ng test

### Observed behavior
After executing the command the tests are compiled correctly, but after waiting for a time fails cause it can't connect. I add the log:

09 02 2018 16:24:15.208:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
09 02 2018 16:24:15.211:INFO [launcher]: Launching browser Chrome with unlimited concurrency
09 02 2018 16:24:15.221:INFO [launcher]: Starting browser Chrome                                                                                                 09 02 2018 16:24:36.497:INFO [Chrome 64.0.3282 (Windows 10 0.0.0)]: Connected on socket W19XRVI7U_LPERL1AAAA with id 66563804
Chrome 64.0.3282 (Windows 10 0.0.0): Executed 0 of 102 SUCCESS (0 secs / 0 secs)
09 02 2018 16:29:41.163:WARN [Chrome 64.0.3282 (Windows 10 0.0.0)]: Disconnected (1 times)
Chrome 64.0.3282 (Windows 10 0.0.0) ERROR
Chrome 64.0.3282 (Windows 10 0.0.0) ERROR
  Disconnectedundefined
Chrome 64.0.3282 (Windows 10 0.0.0): Executed 0 of 102 DISCONNECTED (4 mins 54.998 secs / 0 secs)
Chrome 64.0.3282 (Windows 10 0.0.0) ERROR
  Disconnectedundefined
Chrome 64.0.3282 (Windows 10 0.0.0) ERROR
  Disconnectedundefined
Chrome 64.0.3282 (Windows 10 0.0.0): Executed 0 of 102 DISCONNECTED (4 mins 54.998 secs / 0 secs)

### Desired behavior
It is desired that the tests are run correctly like they where with previous versions.

**Comment by mgechev** [comment] 2019-08-19 20:24
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:24 UTC
Labels: comp: devkit/build-angular, freq1: low, severity3: broken, type: bug/fix
