### ISSUE TITLE
The order of trans-unit elements changes randomly

### ISSUE THREAD

**Issue by yuki-0710** [angular/angular-cli#19248] opened 2020-10-29 01:30 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] extract-i18n

### Is this a regression?

No

### Description

`ng xi18n` command with the ivy option will randomly change the order of trans-units in the generated messages.xlf.

## 🔬 Minimal Reproduction

There is no certain reproducibility, but it seemed to me that it was easy to reproduce when there were a lot of files to be extracted.

## 🌍 Your Environment
<pre>
<code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.2.0
Node: 14.11.0
OS: darwin x64

Angular: 10.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1002.0
@angular-devkit/build-angular      0.1002.0
@angular-devkit/core               10.2.0
@angular-devkit/schematics         10.2.0
@angular/cdk                       10.2.5
@angular/flex-layout               10.0.0-beta.32
@angular/material                  10.2.5
@angular/material-moment-adapter   10.2.5
@schematics/angular                10.2.0
@schematics/update                 0.1002.0
rxjs                               6.6.3
typescript                         3.9.7
</code></pre>

**Anything else relevant?**

No

**Comment by alan-agius4** [comment] 2020-10-29 07:23
Duplicate of https://github.com/angular/angular/issues/39262

**Closed by alan-agius4** 2020-10-29 07:23 UTC
