### ISSUE TITLE
ng new is failing

### ISSUE THREAD

**Issue by indcoder** [angular/angular-cli#1272] opened 2016-07-03 15:23 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 Pro

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
v6.2.2

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng new create

4. The log given by the failure. Normally this include a stack trace and some
   more information.

unzip error C:\Users\indcoder\AppData\Local\Temp\npm-10796-b2a49a97\registry.npmjs.org\esprima-fb\-\esprima-fb-15001.1001.0-dev-harmony-fb.tgz
 unzip error C:\Users\incoder\AppData\Local\Temp\npm-10796-b2a49a97\registry.npmjs.org\iconv-lite\-\iconv-lite-0.4.13.tgz
unexpected end of file
Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)

5. Mention any other details that might be useful.

Also i think some files, during install, are nested so deep that it is exceeding Windows maximum file name limitation
C:\Users\INCODE~1\DOWNLO~1\GitHub\DOCKER~2\NODE_M~1\ANGULA~1\NODE_M~1\EMBER-~2\NODE_M~1\BRA421~1\NODE_M~1\BABEL-~1\NODE_M~1\REGENE~1\NODE_M~1\defs\NODE_M~1\yargs\NODE_M~1\cliui\NODE_M~1\CENTER~1\NODE_M~1\ALIGN-~1\NODE_M~1\kind-of\NODE_M~1\is-buffer\test

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-07-03 21:38
Dupe of https://github.com/angular/angular-cli/issues/1186.

**Closed by filipesilva** 2016-07-03 21:38 UTC

**Comment by filipesilva** [comment] 2016-07-03 21:39
@indcoder I know it doesn't sound like the same issue, but it stems from the same root and https://github.com/angular/angular-cli/pull/1250 fixes it.
