### ISSUE TITLE
@angular-devkit/build-angular:server with optimization: true fails in 16.1.4. 16.1.1 works well

### ISSUE THREAD

**Issue by juanmaldonadodev** [angular/angular-cli#25529] opened 2023-07-12 08:49 UTC
### Command

run

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.1.1

### Description

Exception appears on run main.js with node 16 after build with optimization using @angular-devkit/build-angular@16.1.4 with @angular-devkit/build-angular@16.1.1 works well

### Minimal Reproduction

1 buid the project: ng build --configuration=production && ng run app:server:production 
Works correctly
2 Run the main.js present exception
node dist/app/server/main.js

```
TypeError: Right-hand side of 'instanceof' is not an object
    at insertElement (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:490276)
    at insertHTMLElement (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:489998)
    at before_head_mode (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:527950)
    at HTMLParser.htmlparser.insertToken (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:489022)
    at emitSimpleTag (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:494203)
    at data_state (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:494241)
    at scanChars (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:485784)
    at Object.parse (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:483851)
    at Object.exports2.createDocument (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:721803)
    at Object.exports2.createWindow (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:722306)
```

The problem disappears if in angular.json
optimization is set to false --> Not a real fix
or if downgrade to  "@angular-devkit/build-angular": "^16.1.1",

Final configuration:
`Angular CLI: 16.1.4
Node: 16.20.0
Package Manager: npm 8.19.4
OS: darwin x64

Angular: 16.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@nguniversal/builders           16.1.1
@nguniversal/express-engine     16.1.1
@schematics/angular             16.1.4
rxjs                            7.8.1
typescript                      5.1.6`

### Exception or Error

```text
TypeError: Right-hand side of 'instanceof' is not an object
    at insertElement (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:490276)
    at insertHTMLElement (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:489998)
    at before_head_mode (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:527950)
    at HTMLParser.htmlparser.insertToken (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:489022)
    at emitSimpleTag (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:494203)
    at data_state (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:494241)
    at scanChars (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:485784)
    at Object.parse (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:483851)
    at Object.exports2.createDocument (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:721803)
    at Object.exports2.createWindow (/Users/juanmaldonado/dev/ekilu-web-16/dist/app/server/main.js:1:722306)
```

### Your Environment

```text
`Angular CLI: 16.1.4
Node: 16.20.0
Package Manager: npm 8.19.4
OS: darwin x64

Angular: 16.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@nguniversal/builders           16.1.1
@nguniversal/express-engine     16.1.1
@schematics/angular             16.1.4
rxjs                            7.8.1
typescript                      5.1.6`
```

**Comment by juanico18** [comment] 2023-07-12 08:52
More users affected in this link: https://stackoverflow.com/questions/76611780/angular-ssr-error-right-hand-side-of-instanceof-is-not-an-object/76668748#76668748

**Comment by JeanMeche** [comment] 2023-07-12 09:09
It's this line that is throwing : https://github.com/angular/domino/blob/aa8de3486307f57a518b4b0d9e5e16d9fbd998d1/lib/HTMLParser.js#L2645C59-L2645C60

**Comment by juanico18** [comment] 2023-07-13 06:23
> It's this line that is throwing : https://github.com/angular/domino/blob/aa8de3486307f57a518b4b0d9e5e16d9fbd998d1/lib/HTMLParser.js#L2645C59-L2645C60

Do you think that the problem is in domino library and not in the build?

**Comment by Routhinator** [comment] 2023-07-15 19:17
Hmm, I've been banging my head against this for a couple of days, and @juanico18 's comment made me try removing domino from my server.ts, and now my SSR server starts without this exception.

..my app fails overall of course because I need to provide window for some things in my app, but that does seem to be the right track for this issue.

**Comment by Routhinator** [comment] 2023-07-15 20:20
As a workaround for anyone stuck with this, I dropped in `ssr-window` instead of `domino` and things seem to be working now. It's an alternative to downgrading devkit for now.

Example: 

```typescript
import { getWindow, getDocument } from 'ssr-window';
;(global as any).window = getWindow()
;(global as any).document = getDocument()
;(global as any).navigator = {
  language: 'en',
}
```

I'm a little concerned about this as a long-term workaround as the ssr-window project has been idle longer than domino, but I note that domino itself has also been lacking updates for 2 years now. 

Ultimately I should probably get on with doing platform checks to gate loading anything dependent on window/document/navigator and remove the need for this.

**Comment by Routhinator** [comment] 2023-07-15 23:21
Eh, I take it back. `domino` is hard to replace. It's implementation of `DOMParser` is more functionally complete than anything else.

**Comment by ahmadallw** [comment] 2023-07-20 12:06
any new updated on this issue?

**Comment by deni-rhn** [comment] 2023-07-27 09:15
@Routhinator have you resolved this problem? I have been stuck for a couple of days thinking to resolve this.

**Comment by Routhinator** [comment] 2023-07-27 12:25
My resolution was to rewrite any components that were using non angular safe methods of using document or window etc. 

IE: use Document from angular/core, or if you're looking to get an element use ViewChild and a setter, etc.

I've ripped out libs that don't do this or if they are user-only contexts, wrapped the loading of the module in a platform check.

**Comment by chakrachi** [comment] 2023-08-06 21:21
I'm experiencing the same issue with post versions @angular-devkit/build-angular v16.1.1,
hoping for a fix after the new 16.2.0 RCs?

**Comment by hiepxanh** [comment] 2023-08-10 08:22
have the same issue with 16.2.0 official version on production build :(

**Comment by alan-agius4** [comment] 2023-08-10 09:50
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by hiepxanh** [comment] 2023-08-10 10:18
aw sorry sir, I though that one provided it. Let me do that. I'm so sorry

**Comment by Wycza** [comment] 2023-08-10 11:48
It's because of the `domino` package. To reproduce it:

1. Create a new project
2. Add `ng add @nguniversal/express-engine`
3. `npm install domino --save`
4. Add this to `server.ts`:

```
 const distFolder = join(process.cwd(), 'dist/YOUR_PROJECT_NAME/browser');
```
```
  const window = domino.createWindow(template);
  global['window'] = window;
  global['document'] = window.document;
```

This is how it should look like:

```
// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/bug-repro/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html'))
    ? 'index.original.html'
    : 'index';

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/main/modules/express-engine)
  server.engine(
    'html',
    ngExpressEngine({
      bootstrap: AppServerModule,
    })
  );

  const template = fs
  .readFileSync(path.join(join(process.cwd(), 'dist/bug-repro/browser'), 'index.html'))
  .toString();

  server.set('view engine', 'html');
  server.set('views', distFolder);

  // This cause the bug
  const window = domino.createWindow(template);
  global['window'] = window;
  global['document'] = window.document;

  [...]
```

**Comment by alan-agius4** [comment] 2023-08-10 12:10
@Wycza, thanks I managed to replicate it.

**Comment by chakrachi** [comment] 2023-08-12 23:52
allowing for SSR hydration exacerbates the problem,
perhaps you can find a link with these issues

**Comment by djgovani** [comment] 2023-08-16 12:12
Today converted the app (v16.2.0) to SSR and then try to build and serve and got the same error. As @Wycza said in [comment](https://github.com/angular/angular-cli/issues/25529#issuecomment-1673070594) I'm also using `domino`. I did Google and found this issue. Hope this will fix soon.

**Comment by krivanek06** [comment] 2023-08-18 08:08
+1 on this

**Comment by vc-hitesh** [comment] 2023-08-25 09:44
+1 on this

**Comment by amorgaWebel** [comment] 2023-09-05 12:43
+1 on this

**Comment by REPTILEHAUS** [comment] 2023-09-05 18:16
Hitting this also v16.2.1

**Comment by ahmadallw** [comment] 2023-09-11 14:05
@D-Biela you not facing the same issue?

**Comment by D-Biela** [comment] 2023-09-11 14:10
@ahmadallw Im facing the same issue with  @angular-devkit/build-angular v16.2.1, but as mentioned in this thread, downgrading to @angular-devkit/build-angular 16.1.1 solves the problem.

**Comment by alucardu** [comment] 2023-09-13 20:20
Just upgraded Angular to version 16.2.4 and also running into this error.

**Comment by manduriomane** [comment] 2023-09-28 14:07
Hi to all.
Are there updates?

**Comment by ahmadallw** [comment] 2023-10-11 11:53
Hi all - Any new updates?

**Comment by igordanilovski** [comment] 2023-10-29 19:28
Same issue for me.

**Comment by geferon** [comment] 2023-11-15 14:35
For anyone that runs into this issue but still needs to use Domino, Angular has a forked Domino repository which works with v17s SSR:
https://github.com/angular/domino
It's not on NPM though, so you will have to install it through git.

**Comment by dchicurel** [comment] 2023-11-15 23:08
+1 facing this issue.

Can the forked domino be used with Angular 16 ? could this be released as a standalone Angular-domino package?

**Comment by dchicurel** [comment] 2023-11-15 23:19
> could this be released as a standalone Angular-domino package?
I guess this answers the question: https://github.com/angular/angular/blob/ec2d6e7b9c2b386247d1320ee89f8e3ac5e5a0dd/package.json#L118C5-L118C96

Tried that with Angular 16.2 and seems to be working fine!
`"domino": "https://github.com/angular/domino.git#9e7881d2ac1e5977cefbc557f935931ec23f6658",`

**Comment by JeanMeche** [comment] 2023-11-15 23:19
Angular has been using its own fork of domino since v16, [cf this commit](https://github.com/angular/angular/commit/76731ae5c8bf2bb6e230995009c2a3ac0da1aac0)

**Comment by ndr** [comment] 2023-12-17 01:05
> It's this line that is throwing : https://github.com/angular/domino/blob/aa8de3486307f57a518b4b0d9e5e16d9fbd998d1/lib/HTMLParser.js#L2645C59-L2645C60

I made a domino fork, made a workaround to fix this line throwing an error and linked my "domino" to the commit with fix in my package.json:

"domino": "https://github.com/ndr/domino.git#87c3ef9d60965ded1e713893c3b7c32a421958b1"

For me it worked (tried with angular 17)

**Comment by D-Biela** [comment] 2023-12-29 17:05
> > It's this line that is throwing : https://github.com/angular/domino/blob/aa8de3486307f57a518b4b0d9e5e16d9fbd998d1/lib/HTMLParser.js#L2645C59-L2645C60
> 
> I made a domino fork, made a workaround to fix this line throwing an error and linked my "domino" to the commit with fix in my package.json:
> 
> "domino": "https://github.com/ndr/domino.git#87c3ef9d60965ded1e713893c3b7c32a421958b1"
> 
> For me it worked (tried with angular 17)

Ive tried your solution, but now Im getting "Error: NotYetImplemented" instead of "Right-hand side of 'instanceof' is not an object"

**Comment by misha98857** [comment] 2024-05-14 21:59
> For anyone that runs into this issue but still needs to use Domino, Angular has a forked Domino repository which works with v17s SSR:
> https://github.com/angular/domino
> It's not on NPM though, so you will have to install it through git.

I think publishing the fork to npm would be a good idea. Right now, I need to specify the GitHub repository to receive the fixed version. It is not secure and doesn't follow best practices.

Why isn't that a fork published on npm?

**Comment by alan-agius4** [comment] 2024-12-04 14:15
We are gradually moving away from DOM emulation in server-side rendering (SSR). The Domino library, which was previously used for this purpose, has significant limitations. It is incompatible with the new build system because it relies on a loosely defined JavaScript implementation that does not support ECMAScript Modules (ESM). Additionally, the public version Domino cannot be used with the application builder, making it increasingly obsolete in modern Angular workflows.

Directly using `document` and `window` in SSR contexts is considered a bad practice. These operations can break hydration, which is the process of reusing server-rendered HTML on the client side. Direct DOM manipulation introduces discrepancies between the server-rendered and client-rendered content, leading to hydration mismatches and potential errors. 

Instead, such tasks are better handled through Angular's dedicated lifecycle hooks, such as [afterNextRender](https://angular.dev/api/core/afterNextRender)  or [afterRender](https://angular.dev/api/core/afterRender). These hooks offer a structured approach to executing tasks after rendering, ensuring better compatibility, stability, and maintainability in SSR applications.

This shift to a more modern and structured approach results in more robust, future-proof solutions that align with current development practices while avoiding pitfalls like broken hydration.

**Closed by alan-agius4** 2024-12-04 14:15 UTC
Labels: type: bug/fix, freq1: low, severity5: regression, area: @angular-devkit/build-angular, devkit/build-angular:server
