### ISSUE TITLE
Allow copying of random files on the root to dist

### ISSUE THREAD

**Issue by Lightw3ight** [angular/angular-cli#2374] opened 2016-09-27 19:23 UTC
I am using Angular 2 and the cli to make a chrome extension

chrome extensions require a manifest.json file in the root of the site to function

As far as I am aware, the only way to copy random files to the dist folder on build is via the "assets" folder and that doesn't allow for files on the root.

One possible solution could be to turn the "assets" configuration field on angular-cli.json to be an array of files/folders that are copied?

**Comment by calebkiage** [comment] 2016-09-30 02:25
There's a discussion on this going on at #1942.

**Comment by filipesilva** [comment] 2016-10-03 17:45
Closed as dupe of #1942.

**Closed by filipesilva** 2016-10-03 17:45 UTC
