### ISSUE TITLE
ng serve prepends baseHref to absolute URLs in HTML

### ISSUE THREAD

**Issue by taoyouh** [angular/angular-cli#29139] opened 2024-12-16 04:25 UTC
### Command

serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.3.6

### Description

baseHref is supposed to apply on relative URLs only. However, if I manually add a `<link ... href="/some-path/some-file">` in the `index.html`, `ng serve` will prepend the `baseHref` arg before the `/some-path`. This behavior is not observed in the built artifact.

### Minimal Reproduction

1. Use ng-new to create a new project (with ssr enabled)
2. Change the `<link rel="icon"` line in `index.html` to `<link rel="icon" type="image/x-icon" href="/my-app/favicon.ico">`
3. Add `"baseHref": "/my-app/"` in `angular.json` at `architect/build/options`.
4. Run `ng serve` and visit `http://localhost:4200/my-app/`

You could see the served webpage shows `<link rel="icon" type="image/x-icon" href="/my-app/my-app/favicon.ico">` (double `my-app` here), and the favicon doesn't show.

If you use `ng build` and `node .\dist\{project-name}\server\server.mjs`, and visit `http://localhost:4000/my-app`, the served page will show the correct unchanged URL `href="/my-app/favicon.ico`. (We need also add the base href to the "express" server to make it able to fetch the ico file, but this is irrelevant to the issue here.)

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 18.2.12
Node: 20.12.2
Package Manager: npm 10.2.5
OS: win32 x64

Angular: 18.2.13
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   18.2.12
@angular-devkit/core            18.2.12
@angular-devkit/schematics      18.2.12
@angular/cli                    18.2.12
@angular/ssr                    18.2.12
@schematics/angular             18.2.12
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else relevant?

The behavior change here may also be relevent with changing from `browser` builder to `application` builder.

**Comment by alan-agius4** [comment] 2024-12-16 08:25
Duplicate of #27576

**Closed by alan-agius4** 2024-12-16 08:25 UTC

**Comment by taoyouh** [comment] 2024-12-16 14:54
This is not a duplicate. The case of #27576 is they want to adjust the links in the file without touching the served path. The case here is the dev server is adjusting the hrefs in the header which should not be adjusted. In other words, the issue here is:

- My app will be served at http://host/app in production, so I set baseHref in the builder config.
- The dev server is serving at http://localhost/app which is expected
- However I have some manual items in the `<head>` section of `index.html` like favicons set as `/app/favicon.ico`, but the dev server changed these tags to `/app/app/favicon.ico` because of the baseHref config.

**Comment by alan-agius4** [comment] 2024-12-16 14:58
@taoyouh, this is the same root cause.
