### ISSUE TITLE
Webpack's sass-loader `~` deprecation affect

### ISSUE THREAD

**Issue by sahilbabbar** [angular/angular-cli#22765] opened 2022-02-24 07:10 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Since Webpack has deprecated use of `~` for style imports, this has stopped working in Angular v13 apps as well. 

`@import '~@my-lib/styles/index';`   **<-- Deprecated**

From Webpack's documentation:
> Using ~ is deprecated and can be removed from your code (we recommend it), but we still support it for historical reasons. Why can you remove it? The loader will first try to resolve @import as a relative path. If it cannot be resolved, then the loader will try to resolve @import inside [node_modules](https://webpack.js.org/configuration/resolve/#resolvemodules).

Now, when I try to change the import paths according to the above documentation, then Angular CLI throws an error that it cannot resolve the path i.e. the following doesn't work:

`@import '@my-lib/styles';`   **<-- Doesn't work**

**Query 1:** Why it doesn't work in an Angular app?

But, the following works:

`@import 'node_modules/@my-lib/styles';`   **<-- Works**

**Query 2:** Why does it work with `node_modules/...`?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.3
Node: 14.15.1
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 13.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.3
@angular-devkit/build-angular   13.2.3
@angular-devkit/core            13.2.3
@angular-devkit/schematics      13.2.3
@angular/cli                    13.2.3
@schematics/angular             13.2.3
rxjs                            6.6.3
typescript                      4.4.4
```

**Comment by alan-agius4** [comment] 2022-02-24 10:24
Hi @sahilbabbar, 
I am unable to replicate this issue with the steps provided above. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by sahilbabbar** [comment] 2022-02-24 15:03
Same issue can be seen for the repository at https://github.com/sahilbabbar/ng-playground/tree/master/thirteen/v1322.

**Comment by sahilbabbar** [comment] 2022-02-25 07:52
While digging into the cause of this issue and going over few similar issues faced by others, it appears that the issue is somewhere in the `package.json` of the library that is being used in an application. If it is deleted, then module build passes.

My hunch is that there is some issue with export of library's stylesheet.

My library's `package.json` after build looks like:
```
{
  "_from": "@mylib/package@1.2.3",
  "_id": "@mylib/package@1.2.3",
  "_inBundle": false,
  "_integrity": "",
  "_location": "/@mylib/package",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "@mylib/package@1.2.3",
    "name": "@mylib/package",
    "escapedName": "@mylib%2fpackage",
    "scope": "@mylib",
    "rawSpec": "1.2.3",
    "saveSpec": null,
    "fetchSpec": "1.2.3"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://internal-artefactory-url.com/@mylib/package-1.2.3.tgz",
  "_shasum": "",
  "_spec": "@mylib/package@1.2.3",
  "_where": "C:\.......",
  "bundleDependencies": false,
  "dependencies": {
    "tslib": "2.3.1"
  },
  "deprecated": false,
  "es2020": "fesm2020/mylib-package.mjs",
  "esm2020": "esm2020/mylib-package.mjs",
  "exports": {
    "./package.json": {
      "default": "./package.json"
    },
    ".": {
      "types": "./mylib-package.d.ts",
      "esm2020": "./esm2020/mylib-package.mjs",
      "es2020": "./fesm2020/mylib-package.mjs",
      "es2015": "./fesm2015/mylib-package.mjs",
      "node": "./fesm2015/mylib-package.mjs",
      "default": "./fesm2020/mylib-package.mjs"
    }
  },
  "fesm2015": "fesm2015/mylib-package.mjs",
  "fesm2020": "fesm2020/mylib-package.mjs",
  "module": "fesm2015/mylib-package.mjs",
  "name": "@mylib/package",
  "peerDependencies": {
    "@angular/common": "13.2.2",
    "@angular/core": "13.2.2",
    "d3": "5.16.0"
  },
  "sideEffects": false,
  "typings": "mylib-package.d.ts",
  "version": "1.2.3"
}

```

### Error
```
./src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[5].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[5].rules[1].use[1]!./src/styles.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
3 │ @import "@mylib/package/library/assets/styles/index";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\styles.scss 3:9  root stylesheet
 at tryRunOrWebpackError (C:\angular-app\node_modules\webpack\lib\HookWebpackError.js:88:9)
    at __webpack_require_module__ (C:\angular-app\node_modules\webpack\lib\Compilation.js:5023:12)
    at __webpack_require__ (C:\angular-app\node_modules\webpack\lib\Compilation.js:4980:18)
    at C:\angular-app\node_modules\webpack\lib\Compilation.js:5051:20
    at symbolIterator (C:\angular-app\node_modules\neo-async\async.js:3485:9)
    at done (C:\angular-app\node_modules\neo-async\async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (C:\angular-app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\angular-app\node_modules\tapable\lib\Hook.js:18:14)
    at C:\angular-app\node_modules\webpack\lib\Compilation.js:4958:43
    at symbolIterator (C:\angular-app\node_modules\neo-async\async.js:3482:9)
-- inner error --
```



**Some similar issues:** https://github.com/ng-packagr/ng-packagr/issues/2142, https://github.com/angular/components/issues/23896, https://stackoverflow.com/questions/67652012/sasserror-cant-find-stylesheet-to-import-use-angular-material-as-mat, https://stackoverflow.com/questions/70669126/angular-upgrade-own-library-from-12-to-13-scss-error-sasserror-cant-find-styl)

**Comment by alan-agius4** [comment] 2022-02-25 09:00
It appears that you have not configured the package exports for the styles.

See https://angular.io/guide/creating-libraries#managing-assets-in-a-library for more information.

**Comment by sahilbabbar** [comment] 2022-02-25 17:11
Thanks for the solution. It would be helpful if there is more clear and detailed documentation to export stylesheet(s) from a library project.

**Comment by alan-agius4** [comment] 2022-02-25 18:43
@sahilbabbar, what do you think we should be included in the docs that is not covered in https://angular.io/guide/creating-libraries#managing-assets-in-a-library?

**Comment by alan-agius4** [comment] 2022-03-02 09:20
@sahilbabbar, please provide a minimal reproduction.

**Comment by sahilbabbar** [comment] 2022-03-03 06:25
> @sahilbabbar, what do you think we should be included in the docs that is not covered in https://angular.io/guide/creating-libraries#managing-assets-in-a-library?

Well it seems that the missing part was the package exports documentation that is at https://nodejs.org/api/packages.html#subpath-exports and the example(comprising both `exports` and `@import`) that you have provided just above.

**Comment by alan-agius4** [comment] 2022-03-03 06:44
There is a similar comparison in our docs as well: https://angular.io/guide/angular-package-format#exports

**Comment by alan-agius4** [comment] 2022-03-04 15:18
Closing as this seems to be a misconfiguration issue which is explained in our docs.

**Closed by alan-agius4** 2022-03-04 15:18 UTC
Labels: need: more info
