### ISSUE TITLE
FF Console/Firebug conflicts with ng serve

### ISSUE THREAD

**Issue by peterankelein** [angular/angular-cli#1524] opened 2016-08-02 21:31 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS: Mac OSX El Capitain 10.11.6

2. Versions. Please run `ng --version`. 
```
(node:15665) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.10
node: 6.3.1
os: darwin x64
```

3. app was created via cli:
```
ng new my-project
cd my-project
ng serve
```
No errors thrown in the cli or in Chrome. However, in FF with Firebug open, output is stuck on "loading..." and firebug throws the following error (see 4 below) instead of the console msg "Angular 2 is running in the development mode...." Refreshing with firebug closed, the page loads correctly.

Also tried with native FF console. Everything's as it should be (if you open console after page is loaded)...page shows correctly and console msg shows. However, if you open the console and re-load the page, you get the same errors shown in 4 below. 

4. The log given by the failure:

```
Error: @http://localhost:4200/system-config.js:34:5
	Call@http://localhost:4200/vendor/es6-shim/es6-shim.js:289:14
	forEach@http://localhost:4200/vendor/es6-shim/es6-shim.js:1295:14
	@http://localhost:4200/system-config.js:33:1
	Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:4200/vendor/zone.js/dist/zone.js:323:20
	Zone</Zone</Zone.prototype.run@http://localhost:4200/vendor/zone.js/dist/zone.js:216:25
	scheduleResolveOrReject/<@http://localhost:4200/vendor/zone.js/dist/zone.js:571:53
	Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:4200/vendor/zone.js/dist/zone.js:356:24
	Zone</Zone</Zone.prototype.runTask@http://localhost:4200/vendor/zone.js/dist/zone.js:256:29
	drainMicroTaskQueue@http://localhost:4200/vendor/zone.js/dist/zone.js:474:26
	ZoneTask/this.invoke@http://localhost:4200/vendor/zone.js/dist/zone.js:426:22
	
	Evaluating http://localhost:4200/system-config.js
	Error loading http://localhost:4200/system-config.js
addToError()system.src.js (line 121)
linkSetFailed()system.src.js (line 716)
doLink/<()system.src.js (line 651)
doDynamicExecute()system.src.js (line 799)
link()system.src.js (line 998)
doLink()system.src.js (line 650)
updateLinkSetOnLoad()system.src.js (line 698)
proceedToTranslate/</<()system.src.js (line 510)
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke()zone.js (line 323)
Zone</Zone</Zone.prototype.run()zone.js (line 216)
scheduleResolveOrReject/<()zone.js (line 571)
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask()zone.js (line 356)
Zone</Zone</Zone.prototype.runTask()zone.js (line 256)
drainMicroTaskQueue()zone.js (line 474)
ZoneTask/this.invoke()zone.js (line 426)
	

var newErr = new Error(newMsg, err.fileName, err.lineNumber);
```
5. Additional info:
I'm guessing there is some sort of conflict with FF's consoles as there are no errors or conflicts when reloading the page with the console open in Chrome (expected, I suppose since it's all Google).

**Comment by mikeybyker** [comment] 2016-08-08 09:41
Same error too - with FF (48.0) and Firebug open (2.0.17) - on  Windows 10 64, node 4.4
```
angular-cli: 1.0.0-beta.10
node:  4.4.5
os: win32 x64
```

**Comment by dmeneses** [comment] 2016-08-10 23:20
Same error too - FF 48.0 and Firebug open (2.0.17) - Linux ubuntu 14.04

angular-cli: 1.0.0-beta.10
node: 5.0.0
os: linux x64

**Comment by AntonTrapp** [comment] 2016-08-13 07:32
Exact same config as @peterankelein - except that it ran on my config for exact the first time calling `ng serve`. After the second `ng serve` I got the same error.

**Comment by filipesilva** [comment] 2016-08-19 01:48
Dupe of https://github.com/angular/angular-cli/issues/1417

**Closed by filipesilva** 2016-08-19 01:48 UTC
