### ISSUE TITLE
In latest angular-cli: 1.0.0-beta.22 getting exceptions....

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#3384] opened 2016-12-04 06:17 UTC
In latest angular-cli: 1.0.0-beta.22 getting exceptions....

```
$ ng serve
** NG Live Development Server is running on http://localhost:4200. **
  0% compilingError encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 41:36 in the original .ts file), resolving symbol providing in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 41:36 in the original .ts file), resolving symbol providing in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts
    at positionalError (C:\msweb\msbarcode\node_modules\@angular\compiler-cli\src\static_reflector.js:595:18)
    at simplifyInContext (C:\msweb\msbarcode\node_modules\@angular\compiler-cli\src\static_reflector.js:473:27)
    at StaticReflector.simplify (C:\msweb\msbarcode\node_modules\@angular\compiler-cli\src\static_reflector.js:478:22)
    at StaticReflector.annotations (C:\msweb\msbarcode\node_modules\@angular\compiler-cli\src\static_reflector.js:60:36)
    at NgModuleResolver.resolve (C:\msweb\msbarcode\node_modules\@angular\compiler\bundles\compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (C:\msweb\msbarcode\node_modules\@angular\compiler\bundles\compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (C:\msweb\msbarcode\node_modules\@angular\compiler\bundles\compiler.umd.js:14636:23)
    at addNgModule (C:\msweb\msbarcode\node_modules\@angular\compiler\bundles\compiler.umd.js:12944:43)
    at C:\msweb\msbarcode\node_modules\@angular\compiler\bundles\compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (C:\msweb\msbarcode\node_modules\@angular\compiler\bundles\compiler.umd.js:12956:28)
    at analyzeNgModules (C:\msweb\msbarcode\node_modules\@angular\compiler\bundles\compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (C:\msweb\msbarcode\node_modules\@angular\compiler\bundles\compiler.umd.js:12704:20)
    at OfflineCompiler.compileModules (C:\msweb\msbarcode\node_modules\@angular\compiler\bundles\compiler.umd.js:12775:20)
    at CodeGenerator.codegen (C:\msweb\msbarcode\node_modules\@angular\compiler-cli\src\codegen.js:58:30)
    at AotPlugin._make (C:\msweb\msbarcode\node_modules\@ngtools\webpack\src\plugin.js:193:43)
    at Compiler.<anonymous> (C:\msweb\msbarcode\node_modules\@ngtools\webpack\src\plugin.js:157:75)
    at Compiler.applyPluginsParallel (C:\msweb\msbarcode\node_modules\tapable\lib\Tapable.js:156:14)
    at Compiler.<anonymous> (C:\msweb\msbarcode\node_modules\webpack\lib\Compiler.js:463:8)
    at Compiler.applyPluginsAsync (C:\msweb\msbarcode\node_modules\tapable\lib\Tapable.js:73:70)
    at Compiler.compile (C:\msweb\msbarcode\node_modules\webpack\lib\Compiler.js:456:7)
    at Watching.<anonymous> (C:\msweb\msbarcode\node_modules\webpack\lib\Compiler.js:46:17)
    at next (C:\msweb\msbarcode\node_modules\tapable\lib\Tapable.js:81:11)
    at Compiler.invalidAsyncPlugin (C:\msweb\msbarcode\node_modules\webpack-dev-middleware\middleware.js:119:3)
    at next (C:\msweb\msbarcode\node_modules\tapable\lib\Tapable.js:83:14)
    at Compiler.<anonymous> (C:\msweb\msbarcode\node_modules\webpack\lib\CachePlugin.js:31:4)
    at Compiler.applyPluginsAsync (C:\msweb\msbarcode\node_modules\tapable\lib\Tapable.js:85:13)
    at Watching._go (C:\msweb\msbarcode\node_modules\webpack\lib\Compiler.js:44:16)
    at Watching.<anonymous> (C:\msweb\msbarcode\node_modules\webpack\lib\Compiler.js:36:8)
    at Compiler.readRecords (C:\msweb\msbarcode\node_modules\webpack\lib\Compiler.js:367:10)
    at new Watching (C:\msweb\msbarcode\node_modules\webpack\lib\Compiler.js:33:16)
    at Compiler.watch (C:\msweb\msbarcode\node_modules\webpack\lib\Compiler.js:204:17)
    at module.exports (C:\msweb\msbarcode\node_modules\webpack-dev-middleware\middleware.js:146:27)
    at new Server (C:\msweb\msbarcode\node_modules\webpack-dev-server\lib\Server.js:43:20)
    at Class.run (C:\msweb\msbarcode\node_modules\angular-cli\tasks\serve-webpack.js:85:22)
    at C:\msweb\msbarcode\node_modules\angular-cli\commands\serve.js:102:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

As you can see I have a simple providing array which causes the problem (works fine in ng cli beta .21)

```
export var providing = [{
    provide: AppStore, useFactory: (ngRedux: NgRedux<any>, devTools: DevToolsExtension) => {
        const reducers = combineReducers({notify, sample_reducer});
        const middlewareEnhancer = applyMiddleware(<any>thunkMiddleware);
        const applyDevTools = () => devTools.isEnabled() ? devTools.enhancer : f => f;
        const enhancers: any = compose(middlewareEnhancer, applyDevTools);
        const store = createStore(reducers, enhancers);
        ngRedux.provideStore(store);
        return new AppStore(store);
    }, deps: [NgRedux, DevToolsExtension]
}, {
    provide: "OFFLINE_ENV",
    useValue: false
}, {
    provide: SampleActions,
    useClass: SampleActions
}];

@NgModule({
    declarations: [
        AppComponent,
        // MyComp
    ],
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        // MsLibModule.forRoot(),
        // NgReduxModule.forRoot(), //toggle
        MaterialModule.forRoot()
    ],
    providers: [providing],
    bootstrap: [AppComponent]
})
```

so ng cli is not happy about the fact I am running a factory with functions (which is the proper way of setting up Redux). If I remove the entire providing function, .22 passes the ng serve, but again, have to do it in order to bootstrap Redux.

You can take a look at the very small project at:
https://github.com/born2net/msbarcode/tree/hmr

will be happy to help test as I'd like to get hmr running which requires .22.

regards,

Sean

**Comment by slubowsky** [comment] 2016-12-04 15:08
Almost certainly due to AOT. See https://github.com/angular/angular-cli/issues/3354

**Comment by clydin** [comment] 2016-12-04 15:29
Try extracting the lambda into a separate function for the provider factory.

**Comment by born2net** [comment] 2016-12-04 16:08
tried this with same results:

```
var fac = (ngRedux: NgRedux<any>, devTools: DevToolsExtension) => {
    const reducers = combineReducers({notify, sample_reducer});
    const middlewareEnhancer = applyMiddleware(<any>thunkMiddleware);
    const applyDevTools = () => devTools.isEnabled() ? devTools.enhancer : f => f;
    const enhancers: any = compose(middlewareEnhancer, applyDevTools);
    const store = createStore(reducers, enhancers);
    ngRedux.provideStore(store);
    return new AppStore(store);
}

export var providing = [{
    provide: AppStore, useFactory: fac, deps: [NgRedux, DevToolsExtension]
}, {
    provide: "OFFLINE_ENV",
    useValue: false
}, {
    provide: SampleActions,
    useClass: SampleActions
}];
```

anyway to disable AOT for now so I can focus on hrm testing?

**Comment by born2net** [comment] 2016-12-04 16:10
this is the error:

```
root@DESKTOP-VEUHFOL /cygdrive/c/msweb/msbarcode
$ ng serve
** NG Live Development Server is running on http://localhost:4200. **
  0% compilingError encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 40:18 in the original .ts file), resolving symbol fac in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol providing in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 40:18 in the original .ts file), resolving symbol fac in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol providing in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts
    at positionalError (C:\msweb\msbarcode\node_modules\@angular\compiler-cli\src\static_reflector.js:595:18)
    at simplifyInContext (C:\msweb\msbarcode\node_modules\@angular\compiler-cli\src\static_reflector.js:473:27)
    at StaticReflector.simplify (C:\msweb\msbarcode\node_modules\@angular\compiler-cli\src\static_reflector.js:478:22)
    at StaticReflector.annotations (C:\msweb\msbarcode\node_modules\@angular\compiler-cli\src\static_reflector.js:60:36)
```

**Comment by beeman** [comment] 2016-12-05 07:34
@born2net ran into the same issue trying to get @ngrx working.

This fixed it for me: https://github.com/ngrx/store/issues/190#issuecomment-244406151

**Comment by ruggedy** [comment] 2016-12-05 14:08
@beeman Is there a way to make  dev tools and store log monitor work with AOT?

Thanks

**Comment by born2net** [comment] 2016-12-05 14:28
I tried to modify my code as follows with no luck:

```
var fac = (ngRedux: NgRedux<any>, devTools: DevToolsExtension) => {
    const reducers = combineReducers({notify, sample_reducer});
    const middlewareEnhancer = applyMiddleware(<any>thunkMiddleware);
    const applyDevTools = () => devTools.isEnabled() ? devTools.enhancer : f => f;
    const enhancers: any = compose(middlewareEnhancer, applyDevTools);
    const store = createStore(reducers, enhancers);
    ngRedux.provideStore(store);
    return new AppStore(store);
}

export var providing = [{
    provide: AppStore, useFactory: fac, deps: [NgRedux, DevToolsExtension]
}, {
    provide: "OFFLINE_ENV",
    useValue: false
}, {
    provide: SampleActions,
    useClass: SampleActions
}];
```

any ideas?

regards

Sean

**Comment by ruggedy** [comment] 2016-12-05 14:33
@born2net have you tried making the var "fac" into an untyped funciont rathar than a var .... eg 

```
function fac (ngRedux, devTools) {
.....
...........
....
}
```

that might work

**Comment by born2net** [comment] 2016-12-05 14:34
I haven't gotten that far to trying and getting the dev tools work...  
regards

**Comment by born2net** [comment] 2016-12-05 14:35
ya same error:

```
function fac (ngRedux, devTools) {
    const reducers = combineReducers({notify, sample_reducer});
    const middlewareEnhancer = applyMiddleware(<any>thunkMiddleware);
    const applyDevTools = () => devTools.isEnabled() ? devTools.enhancer : f => f;
    const enhancers: any = compose(middlewareEnhancer, applyDevTools);
    const store = createStore(reducers, enhancers);
    ngRedux.provideStore(store);
    return new AppStore(store);
}

export var providing = [{
    provide: AppStore, useFactory: fac, deps: [NgRedux, DevToolsExtension]
}, {
    provide: "OFFLINE_ENV",
    useValue: false
}, {
    provide: SampleActions,
    useClass: SampleActions
}];
```

**Comment by born2net** [comment] 2016-12-05 14:36
actually that fixed it!!!! tx!!!!!!!!!!

```
export function fac (ngRedux, devTools) {
    const reducers = combineReducers({notify, sample_reducer});
    const middlewareEnhancer = applyMiddleware(thunkMiddleware);
    const applyDevTools = () => devTools.isEnabled() ? devTools.enhancer : f => f;
    const enhancers: any = compose(middlewareEnhancer, applyDevTools);
    const store = createStore(reducers, enhancers);
    ngRedux.provideStore(store);
    return new AppStore(store);
}

export var providing = [{
    provide: AppStore, useFactory: fac, deps: [NgRedux, DevToolsExtension]
}, {
    provide: "OFFLINE_ENV",
    useValue: false
}, {
    provide: SampleActions,
    useClass: SampleActions
}];
```

**Comment by born2net** [comment] 2016-12-05 14:43
and no, dev tools is not working :(
seems like AOT is still in very early stages...

**Comment by born2net** [comment] 2016-12-05 14:49
the issue seems to be that while it is compiling now, it's running my fac function

```
export function fac (ngRedux, devTools) {
    alert('111')
    const reducers = combineReducers({notify, sample_reducer});
    const middlewareEnhancer = applyMiddleware(thunkMiddleware);
    const applyDevTools = () => devTools.isEnabled() ? devTools.enhancer : f => f;
    const enhancers: any = compose(middlewareEnhancer, applyDevTools);
    const store = createStore(reducers, enhancers);
    ngRedux.provideStore(store);
    return new AppStore(store);
}

export var providing = [{
    provide: AppStore, useFactory: fac, deps: [NgRedux, DevToolsExtension]
}, {
    provide: "OFFLINE_ENV",
    useValue: false
}, {
    provide: SampleActions,
    useClass: SampleActions
}];
```

**Comment by born2net** [comment] 2016-12-05 15:15
@beeman 
 Do you know of any way to run ng cli experiential in JIT mode instead of AOT?

**Comment by ruggedy** [comment] 2016-12-05 15:39
maybe try changing useFactory: fac => useFactory: fac()


just a thought as you are not actually running the function.

**Comment by born2net** [comment] 2016-12-05 15:41
Anyway of just running Beta 22 in JIT mode?

**Comment by born2net** [comment] 2016-12-05 17:26
so I did that with no luck.
I actually disabled aot mode in ng serve so I get no errors, but it still doesn't actually run the fac, it's odd.

**Comment by beeman** [comment] 2016-12-05 20:05
> @beeman
> Do you know of any way to run ng cli experiential in JIT mode instead of AOT?
@born2net nope, haven't played around with that yet...

**Comment by born2net** [comment] 2016-12-05 20:11
I figured that one out, --aot false
but at this time I think .22 is in pretty bad shape from what I can see as a ton of stuff is causing the error of:
```
** NG Live Development Server is running on http://localhost:4200. **
  0% compilingError encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 40:18 in the original .ts file), resolving symbol fac in C:/msweb/msbarcode/src/ap
````

**Comment by hansl** [comment] 2016-12-06 00:28
If you aren't specifying `--aot` on the command line, it's going to build using JIT.

_BUT_, we are still using the AotPlugin to figure out the lazy loaded routes from your app. The problem is that (it seems) `NgReduxModule` `forRoot()` function is not statically analyzable. If the functions are simple, we understand them.

Look for a `metadata.json` file next to the one that actually declares the `forRoot()` method. Since we cannot statically analyze ES5 code, we need that metadata file to understand what NgReduxModule is declaring. It can actually declare lazy loaded routes, for example, and without the metadata file we wouldn't know. Since we cannot know, we throw an error.

I'm going to investigate this further and come back to you.

**Comment by born2net** [comment] 2016-12-06 00:44
great tx for the feedback...

**Comment by born2net** [comment] 2016-12-06 00:50
so some more updates, I went ahead and updated all the libs again and latest cli .22 again.
now it seems to work if I don't include my lib module via:
```
MsLibModule.forRoot(),
```
but if I do include it, ng-cli will hang on compilation:
```
$ ng serve --aot false
** NG Live Development Server is running on http://localhost:4200. **
 20% building modules 85/85 modules 0 active
```
When I switch back to ng-cli .21, all is well, so I have somewhat confidence something broke in .22
the project can be easily tested against if you have time:  
https://github.com/born2net/msbarcode/tree/hmr
(not it's the hmr branch)

regards

Sean.

**Comment by hansl** [comment] 2016-12-06 00:59
Okay I cloned your repo and checked out the `hmr` branch.

Putting back the `MsLibModule` in your app results in `Error encountered resolving symbol values statically.`. I checked the `MsLibModule` and it doesn't have a `metadata.json` file, so it's not compatible with the CLI. We will contact them and have them try to deploy the proper files on npm.

Closing this as working as intended.

**Closed by hansl** 2016-12-06 00:59 UTC

**Comment by born2net** [comment] 2016-12-06 01:01
ok but let just make sure we are on the same page.
```MsLibModule``` is my module and ```NgReduxModule ``` is Redux.
Redux now seems fine for me on .22 (not sure what changed but now it works.
My own  ```MsLibModule``` gets the cli to hang (but odd that in .21 all is well)...

**Comment by hansl** [comment] 2016-12-06 01:07
We don't use static analysis in .21 to get your lazy routes, and because of that we were missing some routes. Both options have pros and cons, but we will not move back to reading your TS. External dependencies can define lazy routes and we were missing those.

I just checked and didn't know it was your library. In order to build `metadata` files you need to install `@angular/tsc-wrapped` and run `./node_modules/.bin/ngc` with the same arguments you would your typescript compiler.

If you need further help, let us know.

**Comment by hansl** [comment] 2016-12-06 01:07
BTW, it doesn't hang locally. You might have something wrong in your node_modules.

**Comment by born2net** [comment] 2016-12-06 01:11
ok but I don't use lazy loading...
so if I understand correctly there is a major change between .21 and .22 that is causing this?
if you can provide me more info (or command to run since you my project now) I would greatly appreciate it. Also, once all is working I will share this with the community as I am working with @beeman to get the docs corrected for proper --hmr

so to recap, I want to be able to use .22 and uncomment the line of: ```MsLibModule.forRoot(),``` in ```app.modules``` and have it work with .22 just as it is in .21.

tx again,

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by born2net** [comment] 2016-12-06 01:13
and you mean to run ```tsc-wrapped and run ./node_modules/.bin/ngc``` in my npm project MsLibModule?
MsLibModule is my external npm lib project (module) which I import in.

**Comment by hansl** [comment] 2016-12-06 02:07
Sorry, more info here (it's actually `compiler-cli`): https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

That should cover questions you have about the process. Cheers!

**Comment by hansl** [comment] 2016-12-06 02:07
And yes, I mean you need to generate `metadata` files in your MsLibModule.

**Comment by hansl** [comment] 2016-12-06 02:08
It's our best practices and our recommended way to publish Angular component libraries to also publish `metadata.json` files along `js` and `d.ts` files.

**Comment by born2net** [comment] 2016-12-06 02:19
perfect tx

**Comment by born2net** [comment] 2016-12-06 06:34
didn't have much luck with ngc.

```
$ ../node_modules/.bin/ngc
Error: Error at C:/msweb/ng-mslib/node_modules/typescript/lib/lib.d.ts:18770:11: Duplicate identifier 'ActiveXObject'.
Error at C:/msweb/ng-mslib/node_modules/typescript/lib/lib.d.ts:18773:13: Duplicate identifier 'ActiveXObject'.
Error at C:/msweb/ng-mslib/typings/app.d.ts:172:16: Duplicate identifier 'ActiveXObject'.
Error at C:/msweb/ng-mslib/src/ng-mslib.ts:3:25: Cannot find module 'immutable'.
Error at C:/msweb/ng-mslib/src/ng-mslib.ts:5:20: Cannot find module 'lodash'.
Error at C:/msweb/ng-mslib/src/ng-mslib.ts:6:26: Cannot find module 'moment'.
Error at C:/msweb/ng-mslib/src/ng-mslib.ts:7:28: Cannot find module 'immutable'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/di/reflective_provider.d.ts:88:123: Cannot find name 'Map'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/di/reflective_provider.d.ts:88:165: Cannot find name 'Map'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/facade/lang.d.ts:12:17: Cannot find name 'Map'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/facade/lang.d.ts:13:17: Cannot find name 'Set'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:24:15: Cannot find name 'Map'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:28:16: Cannot find name 'Map'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/application_init.d.ts:16:18: Cannot find name 'Promise'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/linker/compiler.d.ts:53:49: Cannot find name 'Promise'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/linker/compiler.d.ts:61:65: Cannot find name 'Promise'.
Error at C:/msweb/ng-mslib/node_modules/rxjs/Observable.d.ts:10:66: Cannot find name 'Promise'.
Error at C:/msweb/ng-mslib/node_modules/rxjs/Observable.d.ts:66:60: Cannot find name 'Promise'.
Error at C:/msweb/ng-mslib/node_modules/rxjs/Observable.d.ts:66:70: Cannot find name 'Promise'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/application_ref.d.ts:106:67: Cannot find name 'Promise'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/application_ref.d.ts:122:101: Cannot find name 'Promise'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/application_ref.d.ts:148:67: Cannot find name 'Promise'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/application_ref.d.ts:150:101: Cannot find name 'Promise'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/linker/ng_module_factory_loader.d.ts:14:34: Cannot find name 'Promise'.
Error at C:/msweb/ng-mslib/node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.d.ts:28:25: Cannot find name 'Pro
```

and still same issue with latest .22-1

hangs at 20%

root@DESKTOP-VEUHFOL /cygdrive/c/msweb/msbarcode
$ ng serve
** NG Live Development Server is running on http://localhost:4200. **
 20% building modules 85/85 modules 0 active

**Comment by davyvanlaere** [comment] 2017-01-02 08:28
Problem seems to have disappeared in beta 24 ...
