### ISSUE TITLE
Ng serve fails with Yarn and the -ng4 flag

### ISSUE THREAD

**Issue by Ionaru** [angular/angular-cli#4787] opened 2017-02-17 13:23 UTC
### OS?
Lubuntu 16.10

### Versions.
@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: linux x64

### Repro steps. (On a clean VM)
`sudo yarn global add @angular/cli`
`ng set --global packageManager=yarn`
`ng new MyYarnApp -ng4`
`cd MyYarnApp`
`ng serve` or `ng build`

or

`sudo yarn global add @angular/cli`
`ng new MyYarnApp -ng4 --skip-install`
`cd MyYarnApp`
`yarn`
`ng serve` or `ng build`

### The log given by the failure.
```
** NG Live Development Server is running on http://localhost:4200. **
Hash: 431dce9b2028dcad96e7                                                               
Time: 7586ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 155 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 3.72 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 10.1 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.76 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Could not resolve module @angular/core/src/di/opaque_token
webpack: Failed to compile.
```

### Mention any other details that might be useful.
This seems to be a combination of installing packages with Yarn, and using Angular 4

**Comment by Meligy** [comment] 2017-02-17 13:29
This is a duplicate of https://github.com/angular/angular-cli/issues/4611

Look at https://github.com/angular/angular-cli/issues/4611#issuecomment-279125728 or https://github.com/angular/angular-cli/pull/4781 for a workaround.

**Comment by Ionaru** [comment] 2017-02-17 13:41
I can confirm that changing the Angular versions in the package.json works.

**Comment by Meligy** [comment] 2017-02-17 14:54
Run `ng version` to be sure again.
It turned out it actually installed ng2 not ng4 :(

**Comment by Meligy** [comment] 2017-02-17 14:54
But then again maybe following https://github.com/angular/angular-cli/issues/4611#issuecomment-279125728 literally works. I'll be trying this later.

**Comment by jwuliger** [comment] 2017-02-17 22:42
@Ionaru Brilliant! This worked for me. Thanks so much!

**Comment by jwuliger** [comment] 2017-02-17 22:46
Well I spoke to soon. Meh. @Meligy you are correct. The above change to package.json results in a NG2 install.

**Comment by Ionaru** [comment] 2017-02-18 14:37
@Meligy you are correct, it does use Angular 2 with that change. My bad.

![](http://image.prntscr.com/image/ceff644242d841c5972532fa8230254c.png)

**Comment by victornoel** [comment] 2017-02-23 09:24
For those interested, I posted a clean workaround for this problem in https://github.com/angular/angular-cli/issues/4611#issuecomment-279125728.

**Comment by filipesilva** [comment] 2017-03-13 17:21
Dupe of https://github.com/angular/angular-cli/issues/4611

**Closed by filipesilva** 2017-03-13 17:21 UTC
