### ISSUE TITLE
Failed to load url /some/url/path (resolve id:  /some/url/path). Does the file exist?

### ISSUE THREAD

**Issue by AmitRDesai** [angular/angular-cli#26394] opened 2023-11-17 13:35 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Environment: Angular v17 with vite

When using `"proxyConfig": "src/proxy.conf.json"` option in `angular.json` and adding some proxy path URL to load the `js` script in `index.html` while loading the application it shows the following error message in terminal

```
Failed to load url /some/url/path (resolve id:  /some/url/path). Does the file exist?
```

proxy.conf.json
```
{
  "/some": {
    "target": "https://example.com/some",
    "pathRewrite": {
      "^/some": ""
    },
    "secure": false,
    "changeOrigin": true
  }
}
```

index.html
```
<script
      async
      src="/some/test.bundle.min.js"
      type="text/javascript"
    ></script>
```

It does not stop the dev server. it works as expected and all files are loaded correctly.

*Note*: It does not show such an error message for CSS files!

### Minimal Reproduction

It is reproducible in new projects and also

- Create new angular v17 apps
- Add proxy config
- Add proxied URL to load `js` script in `index.html`
- Run `ng serve`
- Load the app in the browser

### Exception or Error

```text
It should consider proxy config for index.html and not print this error message
```

### Your Environment

```text
Angular CLI: 17.0.0
Node: 18.18.2
Package Manager: npm 9.8.1
OS: linux x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.0 (cli-only)
@angular-devkit/core         17.0.0 (cli-only)
@angular-devkit/schematics   17.0.0 (cli-only)
@schematics/angular          17.0.0 (cli-only)
```

**Comment by alan-agius4** [comment] 2023-11-17 13:39
`/some` does not match `/some/test.bundle.min.js` as such the 404 is legit in this case and the fact that worked under webpack-dev-server seems to be incorrect.

Solution is to update `"/some"` to `"/some/**/*"`

**Comment by AmitRDesai** [comment] 2023-11-18 03:18
It is not throwing any 404 error in the browser. it is working fine but in terminal it shows the `Failed to load url` error message
![image](https://github.com/angular/angular-cli/assets/17644428/757588d0-447c-475e-99a1-93582d02f0ed)
![image](https://github.com/angular/angular-cli/assets/17644428/dc2842f7-632e-4250-a5b6-fc941dd64660)

**Comment by alan-agius4** [comment] 2023-11-18 07:20
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by AmitRDesai** [comment] 2023-11-19 05:57
Minimal repo: https://github.com/AmitRDesai/ng-proxy-config-issue

**Comment by giuseppebrb** [comment] 2024-01-09 12:09
the same is happening to after upgrading from Angular 16 to Angular 17.
It seems that with Angular 17, the paths aliases specified within `tsconfig.json` are not considered/resolved by the `application` builder.
Giving a similar error https://github.com/angular/angular-cli/issues/26394#issuecomment-1817346465

Example of `tsconfig.json`
```
{
  ...
  "compilerOptions": {
    "paths": {
      "@common/*": ["app/common/*"],
      "@components": ["app/components/*"]
    }
  ...
  }
}
```

**Closed** 2024-06-20 12:35 UTC
Labels: type: bug/fix, freq1: low, severity2: inconvenient, area: angular/build, angular/build:dev-server
