### ISSUE TITLE
Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by shouvikme** [angular/angular-cli#4440] opened 2017-02-05 18:25 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?

Mac OSX (El Capitan)

### Versions.

@angular/cli: 1.0.0-beta.30
node: 7.0.0
os: darwin x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6

### Repro steps.

Added a simple Opaque Token and NG-BUILD failed as the PROVIDER
```
import { OpaqueToken } from '@angular/core';

export const SUMMARRY = new OpaqueToken('summary');
const dictionary = { };

// providers
export const SUMMARY_PROVIDER = 
[
    { provide: SUMMARY, useValue: dictionary },
];
```

### The log given by the failure.

ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'dictionary'. Consider exporting the symbol (position 14:7 in the original .ts file), resolving symbol SUMMARY_PROVIDERS

### Any other information

To workaround this:

1. I put the dictionary inside a single quotes
2. Ran `ng-build `and then `ng-serve`
3. The code failed as it is now a string 
4. Went back to code and removed the single quotes
5. **Webpack did not complain** and the code works fine

**Comment by deebloo** [comment] 2017-02-05 18:33
Export dictionary and the error should go away

**Comment by shouvikme** [comment] 2017-02-06 03:40
I did try that before posting. It gives another error

Error encountered resolving symbol values statically. Expression form not supported

**Comment by deebloo** [comment] 2017-02-07 13:19
@shouvikme can you post the log from that error?

**Comment by TheDocX** [comment] 2017-02-07 14:17
@deebloo Hello. We encountered basically the same issue and the only error we get is:

```
ERROR in Error encountered resolving symbol values statically. Only initialized variables
and constants can be referenced because the value of this variable is needed by the template
compiler (position 16:22 in the original .ts file), resolving symbol WINDOW_PROVIDERS in …
```

Referenced line 16 is the one w/ exporting abstract class WindowRef in the code below:
```ts
import {OpaqueToken} from "@angular/core";

function _window ():any {
	return window;
}

export const WINDOW:OpaqueToken = new OpaqueToken('WindowToken');

export abstract class WindowRef {
	get nativeWindow ():any {
		return {};
	}
}

export class BrowserWindowRef extends WindowRef {
	constructor () {
		super();
	}

	get nativeWindow ():any {
		return _window();
	}
}

export const WINDOW_PROVIDERS = [
	{provide: WindowRef, useClass: BrowserWindowRef},
	{provide: WINDOW, useFactory: _window, deps: []},
];
```

Hope this helps; thank you in advance for your time.

**Comment by deebloo** [comment] 2017-02-07 14:22
@TheDocX can you try exporting _window and see what happens?

```TS
export  function _window(): any {
    return window;
}
```

**Comment by TheDocX** [comment] 2017-02-07 14:32
Same error, reference line moved from 16:22 to 17:22

**Comment by deebloo** [comment] 2017-02-07 14:36
Hmmm can you create a small repo to reproduce the error?

**Comment by TheDocX** [comment] 2017-02-07 14:37
I’ll try

**Comment by TheDocX** [comment] 2017-02-09 12:43
@deebloo Is there anything else I can provide to help?

**Comment by deebloo** [comment] 2017-02-09 13:00
@TheDocX nope sorry just getting around to looking at issues again. taking a look at the repo now

**Comment by deebloo** [comment] 2017-02-09 13:05
Like you said it is working with the local code but failing with the repote repo. still digging a bit

**Comment by TheDocX** [comment] 2017-02-09 20:29
@deebloo Okay, thank you so far and please let me know if I can help any further

**Comment by filipesilva** [comment] 2017-03-09 11:28
Any error regarding `Error encountered resolving symbol values statically.` is due to problems in static analysis.

The CLI requires code to be statically analyzable even when not doing AOT builds. We didn't in older versions of the CLI but this has been the case for a while now. My best tip to upgrade is to have a look at https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts.

**Closed by filipesilva** 2017-03-09 11:28 UTC

**Comment by TheDocX** [comment] 2017-03-12 14:22
Yeah, it was an issue w/ tsconfig.json

**Comment by HamzaJridi** [comment] 2017-04-12 11:54
@TheDocX  I'm getting the same issue as yours, can you please tell me how did you resolve it.thanks

**Comment by TheDocX** [comment] 2017-04-12 15:28
@HamzaJridi Well, I can’t really tell exactly, but here is our current tsconfig.json:

```json
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "mapRoot": "./",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types",
      "./typings"
    ]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

So try to fiddle around with it, hope it helps

**Comment by HamzaJridi** [comment] 2017-04-12 15:35
@TheDocX thanks, it seems to be the same as mine but I found the solution in here:
http://stackoverflow.com/questions/41932998/angular-2-error-encountered-resolving-symbol-values-statically

**Comment by TheDocX** [comment] 2017-04-12 16:39
I’m glad you solved it

**Comment by msterba** [comment] 2017-04-19 08:02
I got the same `Error encountered resolving symbol values statically`.
```
MyService {
  constructor(@Inject(ConfigToken) config: {[key: string]: string}) {}
}

// Which was provided as static value in the same module:
{ provide: ConfigToken, useValue: { 'a': 'b' } }
```

The error disappeared when I removed the type information:
```
MyService {
  constructor(@Inject(ConfigToken) config: any) {}
}
```

**Comment by omarsourour** [comment] 2017-06-13 12:48
I have the same issue, where if the Opaque Token is define in another package then this error is thrown. Any ideas how to solve that issue?

**Comment by dmayerdesign** [comment] 2017-10-10 19:31
The solution my team found was to translate our `const` into a `class`.

We had an app consuming a package (built by us, installed by the consumer app via a private npm package). The package exported an object like this:
```
export const constants = {
    SOME_CONST: "foo",
    SOME_OTHER_CONST: "bar"
}
```
Our app imported that like `import { constants } from '@our-company/common-package'`
Running `ng serve` produced the error
`ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template comp
iler, resolving symbol constants`

The solution was to instead export the following:
```
export class Constants {
    public static SOME_CONST = "foo";
    public static SOME_OTHER_CONST = "bar";
}
```
For some reason, the compiler can't statically analyze an exported const, but has no problem with an exported class.

Hope this helps!
