### ISSUE TITLE
Google Speed Insights (and other tools) warns about your JS code is not minified

### ISSUE THREAD

**Issue by rafa-as** [angular/angular-cli#18042] opened 2020-06-26 12:54 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.2.14 (We don't have tested with version 10 yet)

### Description

Before Angular 9 upgrade never we have seen this warning about JS minification using Angular CLI, but since we update our projects this warning appears. Advise us that main-es2015 file is not minified.

No compilation errors or warnings, the files seem minified and uglified but this warning is still shown. We have not made any changes to the build parameters for production when we have made the migration to Angular 9 and never we have seen this "error" with production builds and we have our website developed with Angular since Angular 2.

![](https://user-images.githubusercontent.com/594574/81392226-a286a180-911e-11ea-80e6-ee85a4e4e2a8.png)

The following code is our production tsconfig files and angular.json

<details>
 <summary>angular.json - build section</summary>

```json
{
  "build": {
    "builder": "@angular-devkit/build-angular:browser",
    "options": {
      "outputPath": "dist/apps/client/browser",
      "index": "apps/client/src/index-dev.html",
      "main": "apps/client/src/main.ts",
      "polyfills": "apps/client/src/polyfills.ts",
      "tsConfig": "apps/client/tsconfig.app.json",
      "aot": true,
      "assets": [
        "apps/client/src/assets",
        {
          "glob": "**/*",
          "input": "../../node_modules/@cnv/ui/components/form/input-phone/src/assets/flags",
          "output": "assets/flags"
        },
        {
          "glob": "**/*",
          "input": "../../node_modules/@cnv/ui/components/form/dropdown/src/assets/icons",
          "output": "assets/icons"
        }
      ],
      "styles": [
        "../../node_modules/normalize.css/normalize.css",
        "apps/client/src/styles.scss"
      ],
      "scripts": [],
      "stylePreprocessorOptions": {
        "includePaths": [
          "apps/client/src/styles"
        ]
      }
    },
    "configurations": {
      "production": {
        "fileReplacements": [
          {
            "replace": "apps/client/src/environments/environment.ts",
            "with": "apps/client/src/environments/environment.prod.ts"
          },
          {
            "replace": "apps/client/src/build-specifics/index.ts",
            "with": "apps/client/src/build-specifics/index.prod.ts"
          }
        ],
        "index": "apps/client/src/index.html",
        "optimization": true,
        "outputHashing": "all",
        "sourceMap": false,
        "extractCss": true,
        "namedChunks": false,
        "extractLicenses": true,
        "vendorChunk": false,
        "buildOptimizer": true,
        "budgets": [
          {
            "type": "initial",
            "maximumWarning": "2mb",
            "maximumError": "5mb"
          },
          {
            "type": "anyComponentStyle",
            "maximumWarning": "6kb",
            "maximumError": "10kb"
          }
        ],
        "tsConfig": "apps/client/tsconfig.app.prod.json"
      },
      "hmr": {
        "budgets": [
          {
            "type": "anyComponentStyle",
            "maximumWarning": "6kb"
          }
        ],
        "fileReplacements": [
          {
            "replace": "apps/client/src/environments/environment.ts",
            "with": "apps/client/src/environments/environment.hmr.ts"
          }
        ],
        "vendorSourceMap": true
      },
      "es5": {
        "budgets": [
          {
            "type": "anyComponentStyle",
            "maximumWarning": "6kb"
          }
        ],
        "tsConfig": "apps/client/tsconfig-es5.app.json"
      },
      "es5-production": {
        "budgets": [
          {
            "type": "anyComponentStyle",
            "maximumWarning": "6kb"
          }
        ],
        "tsConfig": "apps/client/tsconfig-es5.app.prod.json"
      }
    }
  }
}
```
</details>

<details>
 <summary>workspace tsconfig.json</summary>

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```
</details>

<details>
 <summary>base tsconfig.json</summary>

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "./"
  },
  "include": [
    "src/**/*.ts"
  ]
}
```
</details>

</details>

<details>
 <summary>tsconfig.app.json</summary>

```typescript
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc/apps/client",
    "types": [
      "node"
    ],
    "paths": {
      "@app/*": [
        "src/app/*"
      ],
      "@common/*": [
        "src/app/common/*"
      ],
      "@core/*": [
        "src/app/core/*"
      ],
      "@env/*": [
        "src/environments/*"
      ],
      "@build-specifics": [
        "src/build-specifics"
      ],
      "@cnv/*": [
        "../../libs/*/src/index.ts"
      ]
    }
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```
</details>

<details>
 <summary>tsconfig.app.prod.json</summary>

```typescript
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "paths": {
      "@app/*": [
        "src/app/*"
      ],
      "@common/*": [
        "src/app/common/*"
      ],
      "@core/*": [
        "src/app/core/*"
      ],
      "@env/*": [
        "src/environments/*"
      ],
      "@build-specifics": [
        "src/build-specifics"
      ]
    }
  }
}
```
</details>

## 🔬 Minimal Reproduction

We are not sure how to reproduce it because we don't perform any action except the Angular 9 update.

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.7
Node: 12.17.0
OS: darwin x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-ng-packagr   0.901.7
@angular-devkit/build-optimizer    0.901.7
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cdk                       9.2.4
@angular/cli                       9.1.7
@ngtools/webpack                   9.1.7
@nguniversal/builders              9.1.1
@nguniversal/common                9.1.1
@nguniversal/express-engine        9.1.1
@schematics/angular                9.1.7
@schematics/update                 0.901.7
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Anything else relevant?**

We use several third party libraries like ngrx but we also used them before the migration.

Some background about this issue can be found here #17550 

You can check it at [carnovo.com](https://carnovo.com) or [SpeedInisghts](https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fcarnovo.com%2Fes)

We can't give you more information about this bug but If you need some more specific information we are available for it.

**Comment by tspicer** [comment] 2020-07-01 19:41
@rafa-as I have seen the same issue at Pagespeed and https://gtmetrix.com/. 
GT Metrix will even generate the minified version to highlight the fact no modification is occurring.

**Comment by wibimaster** [comment] 2020-07-03 16:12
Got it too, with a fresh install of default project with angular-cli

**Comment by tspicer** [comment] 2020-07-07 15:10
@wibimaster i did not use gtmetrix other than a cross-check to see if the code was minimized (vs being valid). Running the JS through a manual modification process highlights minification is not properly occurring.

**Comment by dgp1130** [comment] 2020-07-09 18:18
@clydin did some investigation here and it seems that even an `ng new` project running either Ivy or View Engine will trigger this notice. We'll reach out to Page Speed Insights to understand a bit more about how this check is computed and see what we can do to get more actionable analysis.

**Comment by tspicer** [comment] 2020-07-09 18:23
@dgp1130 thank you. PageSpeed is embedded into Google Search Console, Google Ads, Google Analytics...so it is widely used as a benchmark of performance. I get warnings in GSC and Ads about similar PageSpeed alerts which means my SEO can take a hit or ads will not show. The good news? Solving it once will solve it everywhere. :)

**Comment by blasco** [comment] 2020-07-18 18:56
Same here, using angular 10 and getting minification required warnings in lighthouse...

**Comment by blasco** [comment] 2020-07-19 19:49
Seems that if I run the minification manually with terser and add the `--mangle-props` then lighthouse doesn't complaint, but this sames to break the code as the app stops working...

**Comment by oky1** [comment] 2020-07-29 07:43
Same problem. Any progress here?

**Comment by cybercussion** [comment] 2020-07-29 18:15
Am I right in looking at this it is just \n that its not taking out of the main*.js file?

**Comment by geetika-kathuria** [comment] 2020-07-30 03:27
Team, any update on this issue?

**Comment by cbernth** [comment] 2020-07-30 21:20
Same problem for me, looking forward to guidance.

**Comment by djouf007** [comment] 2020-08-02 00:07
I have the same problem

**Comment by e20bhn** [comment] 2020-08-04 00:07
yes, the same issue for me as well.  we have set the  "optimization": true. But in lighhouse the warning comes that "Remove unused javascripts". Can you please help in this as early as possible. 

Angular CLI: 8.1.2
Node: 14.5.0
OS: darwin x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.2
@angular-devkit/build-angular      0.801.2
@angular-devkit/build-optimizer    0.801.2
@angular-devkit/build-webpack      0.801.2
@angular-devkit/core               8.1.2
@angular-devkit/schematics         8.1.2
@angular/cdk                       8.1.1
@angular/fire                      5.2.1
@angular/flex-layout               8.0.0-beta.26
@angular/http                      7.2.15
@angular/material                  8.1.1
@angular/material-moment-adapter   8.1.1
@ngtools/webpack                   8.1.2
@schematics/angular                8.1.2
@schematics/update                 0.801.2
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2

                    "configurations": {
                        "production": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.prod.ts"
                                }
                            ],
                            "optimization": true,
                            "outputHashing": "all",
                            "sourceMap": false,
                            "extractCss": true,
                            "namedChunks": true,
                            "aot": true,
                            "extractLicenses": true,
                            "vendorChunk": false,
                            "buildOptimizer": true,
                            "budgets": [
                                {
                                    "type": "initial",
                                    "maximumWarning": "4mb",
                                    "maximumError": "6mb"
                                }
                            ]
                        },
                        "ec": {
                            "sourceMap": true,
                            "extractCss": true
                        },
                        "hmr": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.hmr.ts"
                                }
                            ]
                        }
                    }

**Comment by wibimaster** [comment] 2020-08-04 05:19
> yes, the same issue for me as well. we have set the "optimization": true. But in lighhouse the warning comes that "Remove unused javascripts". Can you please help in this as early as possible.

@e20bhn It's not the same thing ; this issue is mainly about code minification, and not code used/not used

**Comment by rafa-as** [comment] 2020-08-04 09:26
The used/not used is another issue. We should open another issue to track it separated.

**Comment by charlatan154** [comment] 2020-08-09 15:30
I have the same issue.

**Comment by ishan123456789** [comment] 2020-08-10 18:03
Any update? Hack? it shows about 70% reduction in the main.js file if minified so it's a huge chunk and considering with every new version of Angular says reduced bundle size I won't expect this.

**Comment by ishan123456789** [comment] 2020-08-20 11:48
I used gzip compression and the bundle size was reduced from some MB to 400 something KB in case anyone wants to do the same you can configure Nginx or use a nodeJS server to throw the Bundle when requesting a URL for me I was using SSR so just had to add compression middleware to the express.

**Comment by tspicer** [comment] 2020-08-20 12:52
@ishan123456789, while compression will certainly reduce the size, the error in this issue is specific to minification. Most servers or CDNs should be configured to use compression. For example, we use CloudFront to serve everything, which will gzip compress the assets, including JS.

**Comment by matreaus** [comment] 2020-08-21 07:49
I just found a cause, at least in my project! :) 
It seems that what @webimaster mentioned is crucial. The suggested by Google PageSpeed minified code is not valid and ends with: 
`this.peekStartsWith("/")&&!this.peekStartsWith("`

But what is even more important is that the next two characters in the correct/original files are // (!) and further code looks like this:
`this.peekStartsWith("/")&&!this.peekStartsWith(**"//"**` 

So my best guess is that Google Pagespeed is recognizing // as a comment sign and is treating everything after this as not used code! 

Could someone confirm? And if this is true, then I guess Google should implement change in Pagespeed.

(this is my first contribution, so sorry if I wrote something wrong)

**Comment by cbernth** [comment] 2020-08-27 06:52
Team, any updates?

**Comment by djouf007** [comment] 2020-08-27 09:53
I waiting for update also

**Comment by clydin** [comment] 2020-08-28 00:27
After an initial investigation, the issue appears to be caused by a false positive when processing ES2015 code.  An issue report has been opened with the Lighthouse project and is currently undergoing additional investigation.  For further updates, please monitor this issue: https://github.com/GoogleChrome/lighthouse/issues/11295

**Comment by djouf007** [comment] 2020-09-20 00:25
Is it fixed ?

**Comment by wibimaster** [comment] 2020-09-20 12:06
No more problem with master branch of lighthouse-cli

![image](https://user-images.githubusercontent.com/626666/93710908-5cb8fb80-fb4a-11ea-8e7c-8e6148fc7fab.png)

Fix is merged on master but not tagged nor deployed actually

**Comment by juanpablorojas** [comment] 2020-10-04 14:29
I have the same problem with minification

**Comment by clydin** [comment] 2020-10-04 15:18
The Lighthouse project has published a release ([v6.4.0](https://github.com/GoogleChrome/lighthouse/releases/tag/v6.4.0)) with a [fix](https://github.com/GoogleChrome/lighthouse/pull/11395) to the audit.
As to when this will be available on PageSpeed Insights, the release notes provide the following information:
> We expect this release to ship in the DevTools of Chrome 88, and to PageSpeed Insights within 2 weeks.

**Closed by clydin** 2020-10-04 15:18 UTC
Labels: blocked on upstream, need: investigation, severity4: memory/performance

**Comment by jsvanilla** [comment] 2020-10-19 22:46
I have the same problem, any updates ?

**Comment by hhsissi** [comment] 2020-10-20 16:55
+1

**Comment by cybercussion** [comment] 2020-10-20 17:08
> I have the same problem, any updates ?

I haven't had the issue after updating.  I want to say this was 10.1.5 corrected.  I'm on 10.1.7 now.

**Comment by clydin** [comment] 2020-10-20 17:10
This was caused by a defect within Lighthouse itself and not Angular.  Please see my comment above: https://github.com/angular/angular-cli/issues/18042#issuecomment-703270606
