### ISSUE TITLE
Error in generated files for production using jointjs in IE11.

### ISSUE THREAD

**Issue by jmesa-sistel** [angular/angular-cli#15233] opened 2019-08-02 10:26 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No

### Description

Not very sure if it is related to angular cli.
I am using [jointjs ](https://github.com/clientIO/joint) version 3.0.3 in a angular app and we have a problem when we try to execute the app in Internet Explorer.
Jointjs is using .mjs extension as module. In angular 8.2.0 we use differential loading for old browsers, the problem is the generated es5*.js (relative to jointjs) file, IE11 give me an error telling js is malformed (invalid character).

## 🔬 Minimal Reproduction

Create a angular app (testjointjs for example)
`ng new testjointjs`
Add `jointjs` package:
`npm install jointjs`
`npm install --save-dev @types/backbone`

In `app.component.ts` add:
`import * as joint from 'jointjs';`
And add in the class (to avoid to remove jointjs from build because it's not used):
`x = joint.V('path');`

Build app for production (`ng build --prod`).
Install `http-server` to serve angular app
`npm install -g http-server`
Run `http-server`: `http-server .\dist\testjointjs`
Now try to load in IE11 with url `http://127.0.0.1:8080/index.html`
In console log you will see an error processing a js file (invalid character). It is related to jointjs.

A simple test to be sure it is related to how angular cli compile jointjs is edit 
`node_modules/jointjs/package.json` and remove line:
`"module": "./joint.mjs",`
Notice the .mjs extension, I think it is related.
If you build the app again everything works fine.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.2.0
Node: 12.7.0
OS: win32 x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**

**Comment by LucaVassalli** [comment] 2019-08-02 12:34
Hi,
same error but in development.
I setup polyfills but the error is regarding vendor.js at this point

![image](https://user-images.githubusercontent.com/44664760/62370379-38f3ba00-b532-11e9-8bf0-5990235dcb24.png)

my versions are
![image](https://user-images.githubusercontent.com/44664760/62370444-6a6c8580-b532-11e9-891e-9ce8b3fd08aa.png)

I am struggling in vain

**Comment by jmesa-sistel** [comment] 2019-08-02 12:37
@LucaVassalli My ugly hack to get it working 
Add in `package.json` the next script in scripts section:
`"postinstall": "sed -i 's/\"module\":/\"module1\":/g' ./node_modules/jointjs/package.json"`
Then execute `npm install` to hack `jointjs`
Now it should work

**Comment by LucaVassalli** [comment] 2019-08-02 12:57
Thank you for reply.
Yes on other browser it works correctly.

I am trying to run your script in visual studio ... sed is a replace right?

**Comment by jmesa-sistel** [comment] 2019-08-02 13:05
@LucaVassalli 
Yes sed is a replce text.
The script change `module` to `module1` in `./node_modules/jointjs/package.json` so the lib is managed as .js (main entry) and not as .mjs (module)

**Comment by LucaVassalli** [comment] 2019-08-02 13:34
Your fix works, thank you very much!
Hope that IE burns in hell.
:D

**Comment by clydin** [comment] 2019-08-02 14:09
The root cause here is that third party code is not currently down-leveled for the ES5 bundles.  The module field is also poorly defined.  In many cases for browser libraries it references ES5 code with ES modules but for node libraries it may contain code that uses ES2015+ features.

**Comment by clydin** [comment] 2019-08-02 14:18
I’m going to close this issue as the CLI is currently working as intended.  However, in the future more comprehensive down-leveling support may be included that will allow the avoidance for the package manipulation detailed above.

**Closed by clydin** 2019-08-02 14:18 UTC
