### ISSUE TITLE
ng new with 1.5.0-beta.2 

### ISSUE THREAD

**Issue by matt328** [angular/angular-cli#7892] opened 2017-09-30 14:25 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

cli: 1.5.0-beta.2
node: 6.9.5
npm: 5.4.2

### Repro steps.

```bash
npm install @angular/cli@1.5.0-beta.2
ng --version
```

### The log given by the failure.

```
ng --version     // or ng <anything>                       
/Users/matt/.nvm/versions/node/v6.9.5/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:14
    throw new Error('The "@angular/compiler-cli" package was not properly installed. Error: ' + e);
    ^

Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.<anonymous> (/Users/matt/.nvm/versions/node/v6.9.5/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/matt/.nvm/versions/node/v6.9.5/lib/node_modules/@angular/cli/commands/build.js:6:19)
    at Module._compile (module.js:570:32)
```

### Desired functionality.

ng new should create a new project

### Mention any other details that might be useful.

I'd like to be able to use 1.5.0 because it supports --preserve-symlinks with ng test.  As a workaround for now, you can create a new project using 1.4.x and after a project is created, upgrade to 1.5.0-beta.2.  Once a project has been created, 1.5.0-beta.2 is able to find the dependencies it needs in the project's node_modules folder, so it's like a chicken and the egg thing.

**Comment by wulfsberg** [comment] 2017-10-01 21:03
Duplicate of #7694
AFAIK, another workaround is to install the @angular/cli explicitly after installing the CLI.

**Comment by filipesilva** [comment] 2017-10-02 15:09
Closing as duplicate of https://github.com/angular/angular-cli/issues/7694

**Closed by filipesilva** 2017-10-02 15:09 UTC
