### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by jwhite1802** [angular/angular-cli#1700] opened 2016-08-15 14:47 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.10
node: 5.10.1
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
This is an app that was created using the CLI

4. The log given by the failure. Normally this include a stack trace and some
   more information.

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EMFILE: too many open files, open 'D:\workspace\ng-test\node_modules\@angular\core\src\change_detection\differs\keyvalue_differs.d.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at CustomLanguageServiceHost.getScriptSnapshot (D:\workspace\ng-test\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:418:44)
    at HostCache.createEntry (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:48033:44)
    at HostCache.getOrCreateEntry (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:48056:25)
    at Object.getOrCreateSourceFile [as getSourceFile] (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:48956:53)
    at findSourceFile (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40307:29)
    at processImportedModules (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40352:17)
    at processImportedModules (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40352:17)
    at processImportedModules (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40352:17)
    at processImportedModules (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40352:17)
    at processImportedModules (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40352:17)
    at processImportedModules (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40352:17)
    at processSourceFile (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40251:27)
    at processRootFile (D:\workspace\ng-test\node_modules\angular-cli\node_modules\typescript\lib\typescript.js:40161:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (D:\workspace\ng-test\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (D:\workspace\ng-test\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (D:\workspace\ng-test\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:26:49)
    at Angular2App._getTsTree (D:\workspace\ng-test\node_modules\angular-cli\lib\broccoli\angular2-app.js:331:18)
    at Angular2App._buildTree (D:\workspace\ng-test\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (D:\workspace\ng-test\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (D:\workspace\ng-test\angular-cli-build.js:10:10)    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\workspace\ng-test\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\workspace\ng-test\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)    at new Class (D:\workspace\ng-test\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\workspace\ng-test\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build-watch.js:17:16)    at D:\workspace\ng-test\node_modules\angular-cli\addon\ng2\commands\test.js:69:46
    at lib$rsvp$$internal$$tryCatch (D:\workspace\ng-test\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\workspace\ng-test\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\workspace\ng-test\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\workspace\ng-test\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

5. Mention any other details that might be useful.
I get this error when runing the ng test command in terminals running as administrator and normal privileges.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by artigat1** [comment] 2016-08-22 13:40
I've had this. I just created a new project with angular-cli:

```
angular-cli: 1.0.0-beta.10
node: 5.0.0
os: win32 x64
```
After creating the project and making no changes, I did `ng test` and got the following error:

```
Built project successfully. Stored in "dist/".
\ BuildingThe Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EMFILE: too many open files, open 'C:\git\unit-tester\tmp\broccoli_type_script_compiler-input_base_path-ml3sdsIv.tmp\0\src\tsconfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at BroccoliTypeScriptCompiler._loadTsConfig (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:128:34)
    at BroccoliTypeScriptCompiler._createServiceHost (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:163:25)
    at BroccoliTypeScriptCompiler.build (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:41:12)
    at C:\git\unit-tester\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\git\unit-tester\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\git\unit-tester\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:26:49)
    at Angular2App._getTsTree (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\angular2-app.js:331:18)
    at Angular2App._buildTree (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\git\unit-tester\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\git\unit-tester\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\git\unit-tester\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\git\unit-tester\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\git\unit-tester\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build-watch.js:17:16)
    at C:\git\unit-tester\node_modules\angular-cli\addon\ng2\commands\test.js:69:46
    at lib$rsvp$$internal$$tryCatch (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)


The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EMFILE: too many open files, open 'C:\git\unit-tester\tmp\broccoli_type_script_compiler-input_base_path-ml3sdsIv.tmp\0\src\tsconfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at BroccoliTypeScriptCompiler._loadTsConfig (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:128:34)
    at BroccoliTypeScriptCompiler._createServiceHost (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:163:25)
    at BroccoliTypeScriptCompiler.build (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:41:12)
    at C:\git\unit-tester\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\git\unit-tester\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\git\unit-tester\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:26:49)
    at Angular2App._getTsTree (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\angular2-app.js:331:18)
    at Angular2App._buildTree (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (C:\git\unit-tester\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\git\unit-tester\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\git\unit-tester\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\git\unit-tester\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\git\unit-tester\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\git\unit-tester\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build-watch.js:17:16)
    at C:\git\unit-tester\node_modules\angular-cli\addon\ng2\commands\test.js:69:46
    at lib$rsvp$$internal$$tryCatch (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\git\unit-tester\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

**Comment by alexkates** [comment] 2016-08-22 19:58
+1 Having the same issue.

**Comment by filipesilva** [comment] 2016-08-23 18:41
Dupe of https://github.com/angular/angular-cli/issues/977, made obsolete by #1455. You can try the webpack preview by following these instructions: https://github.com/angular/angular-cli#webpack-preview-release-update

**Closed by filipesilva** 2016-08-23 18:41 UTC
