### ISSUE TITLE
on running cli command ng serve i can not detect changes on browser

### ISSUE THREAD

**Issue by hardy12994** [angular/angular-cli#8774] opened 2017-12-07 07:10 UTC
On running cli command `ng serve` i can not detect changes on browser

NPM - 4.2.0
NODE - v7.10.1

By this **ng -v** i get -

Your global Angular CLI version (1.6.0) is greater than your local
version (1.5.4). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
```sh
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.4
Node: 7.10.1
OS: linux x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0
@angular/cli: 1.5.4
@angular/material: 5.0.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.8.1

```

**Comment by filipesilva** [comment] 2017-12-07 17:25
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/1610. Please subscribe to that issue for future updates.

This can be caused by several things. Please have a look at that issue to find some solutions.

**Closed by filipesilva** 2017-12-07 17:25 UTC
Labels: need: repro steps, priority: 2 (required), severity3: broken
