### ISSUE TITLE
Angular 12.1 & Storybook 6.3 - Storybook build process never complete

### ISSUE THREAD

**Issue by ld210** [angular/angular-cli#21261] opened 2021-07-02 06:11 UTC
# 🐞 Bug report

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes, was working fine until @angular/cli@12.0.3

### Description

We have an Angular project (v12.1), and we are using Storybook for our design system (v6.3). When building Storybook, the process produce an output, but never close, breaking our CI.

## 🔬 Minimal Reproduction

- ng new testProject (with angular cli v12) (choosing SCSS)
- npx sb@next init
- build-storybook

## 🔥 Exception or Error

There's no errors

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.1.0
Node: 14.15.4
Package Manager: npm 7.19.0
OS: darwin x64

Angular: 12.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@schematics/angular             12.1.0
rxjs                            6.6.7
typescript                      4.3.4
</code></pre>

**Anything else relevant?**

There is an open issue in Storybook repo : [#15227](https://github.com/storybookjs/storybook/issues/15227) where someone put up a reproduction repo : [Storybook timeout repro](https://github.com/hoffination/storybook-timeout-repro)
Investigations appears to leads to a change in this PR : [21045](https://github.com/angular/angular-cli/pull/21045)
There is a workaround, a bit dirty though.

**Comment by toamitc** [comment] 2021-07-02 06:13
We are facing same issue

**Comment by alan-agius4** [comment] 2021-07-02 08:32
I did look into this briefly, it appears that when using Storybook the Webpack compiler is not shutting down properly and the shutdown event hook is never called, which causes the workers not to terminate. At the point, I think Storybook team are in a better position to investigate and determine why this is happening, since they are more familiar of how they are configuring the build and all the plugins/loaders being used.

It's important to mentioned that Storybook is also using private APIs to get and alter the Webpack configuration, these APIs are not meant to be used externally.

**Comment by ld210** [comment] 2021-07-02 08:54
"At the point, I think Storybook team are in a better position to investigate" 
well... They said the exact same thing, the other way around. I fear it is going in full circle...

**Comment by alan-agius4** [comment] 2021-07-02 09:10
The fact that the build never completes, is a side-effect of Webpack not not triggering the shutdown event/cycle, while we can do a workaround for this, it is far from ideal as not shutting down Webpack properly might have other undefined behaviour. 

herefore, the best action here is for the Storybook team to determine why Webpack is not shutting down properly.

**Comment by shilman** [comment] 2021-07-02 09:11
@alan-agius4 we'll look into this and see if there's something missing on the storybook side

**Comment by ld210** [comment] 2021-07-02 12:03
Thanks guys !

**Comment by clydin** [comment] 2021-07-06 23:37
From an initial review of the storybook code, it appears that the storybook Webpack 5 integration [code](https://github.com/storybookjs/storybook/blob/52064d9da88ecc8af72eddc85091e0ee745b70d0/lib/builder-webpack5/src/index.ts#L132) does not call the Webpack 5 compiler's `close` method (https://webpack.js.org/api/node/#run).  This is most likely the cause of the `shutdown` hook not running. This also has the potential lead to Webpack cache corruption (assuming Webpack 5 file caching is enabled) as the cache may not be shutdown properly.

**Comment by alan-agius4** [comment] 2021-07-07 07:56
Closing this is not actionable by the Angular team.

**Closed by alan-agius4** 2021-07-07 07:56 UTC
