### ISSUE TITLE
Error: Module not found 'crypto' while building with Angular 6

### ISSUE THREAD

**Issue by munukutla** [angular/angular-cli#12212] opened 2018-09-08 10:26 UTC
### Bug Report or Feature Request
```
- [x] bug report
```

### Command 
```
- [x] build
- [x] serve
```

### Versions
```
Angular CLI: 6.2.1
Node: 8.11.2
OS: darwin x64 macOS High Sierra
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.1
@angular-devkit/build-angular     0.8.1
@angular-devkit/build-optimizer   0.8.1
@angular-devkit/build-webpack     0.8.1
@angular-devkit/core              0.8.1
@angular-devkit/schematics        0.8.1
@angular/cli                      6.2.1
@ngtools/webpack                  6.2.1
@schematics/angular               0.8.1
@schematics/update                0.8.1
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.17.2
```

### Repro steps
```
ng new my-app
```
Add a dependency, which uses `tls`, `net` or `crypto`, such as [ts-nats](https://github.com/nats-io/ts-nats) and run `npm install`
```
ng build
```

### The log given by the failure
```
ERROR in ./node_modules/nuid/lib/nuid.js
Module not found: Error: Can't resolve 'crypto' in '/Users/cm/learning/angular/nats-sample/node_modules/nuid/lib'
ERROR in ./node_modules/ts-nats/lib/tcptransport.js
Module not found: Error: Can't resolve 'net' in '/Users/cm/learning/angular/nats-sample/node_modules/ts-nats/lib'
ERROR in ./node_modules/ts-nats/lib/tcptransport.js
Module not found: Error: Can't resolve 'tls' in '/Users/cm/learning/angular/nats-sample/node_modules/ts-nats/lib'
```
### Desired functionality
Project should build properly

### Mention any other details that might be useful
Investigated in several other issues and found that Angular 6 no more supports `net`, `fs`, `tls`, `crypto` and the like.

@filipesilva - there are many npm dependencies which include the above packages. Is there no workaround or ETA for resolution on this?

**Comment by munukutla** [comment] 2018-09-08 10:27
Also referenced in #1548

**Comment by alan-agius4** [comment] 2018-09-08 15:17
This is a duplicate of this issue: https://github.com/angular/angular-cli/issues/1548.  For details on why this is not configured, please see this comment: https://github.com/angular/angular-cli/issues/1548#issuecomment-286151056.

**Closed by alan-agius4** 2018-09-08 15:17 UTC

**Comment by Juanperezc** [comment] 2018-11-23 00:00
Hello, someone else has worked to implement ipfs on ionic, I'm trying but I'm having an error
