### ISSUE TITLE
getting error with ng serve --prod 

### ISSUE THREAD

**Issue by KushagraGitter** [angular/angular-cli#937] opened 2016-05-27 06:01 UTC
![61ccbec0-21cb-11e6-9562-f04a4d89b580](https://cloud.githubusercontent.com/assets/13452634/15599129/91a42446-23fe-11e6-97c5-3c1bebc6acb5.png)

**Comment by antonmoiseev** [comment] 2016-05-27 13:28
The same error for a newly generated mobile app. Steps to reproduce:

```
ng new my-app --mobile
cd my-app
ng build -prod 
```

CLI version:

```
$ ng --version
angular-cli: 1.0.0-beta.5
node: 6.2.0
os: darwin x64
```

**Comment by stretchgz** [comment] 2016-05-27 14:21
See https://github.com/angular/angular-cli/issues/847#issuecomment-221285753

**Comment by filipesilva** [comment] 2016-06-01 01:22
Duplicate of https://github.com/angular/angular-cli/issues/847.

The recommendation @stretchgz gave is the correct solution, and https://github.com/angular/angular-cli/pull/972 should solve it for future projects.

**Closed by filipesilva** 2016-06-01 01:22 UTC
