### ISSUE TITLE
ng command : module.js : 471

### ISSUE THREAD

**Issue by zakir-hussain** [angular/angular-cli#5108] opened 2017-02-28 14:53 UTC
while installing the angular-cli or @angular/cli, it is not getting install completely and this error message:
its asking for some VCBuild.exe , .Net framework 2.0 SDK and Visual Studio 2015.....
Not understand Why?
After this run "ng" :getting Error 
 module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\...\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by anantgoldie** [comment] 2017-02-28 20:44
I had similar issues, because i was behind a firewall and angular binaries were note able to download and install.

**Comment by sumitarora** [comment] 2017-03-06 20:10
@zakir-hussain Are you still getting the issue with the fix mentioned above?

**Comment by filipesilva** [comment] 2017-03-14 13:03
Dupe of https://github.com/angular/angular-cli/issues/4429 (it's the same cause, node-sass).

**Closed by filipesilva** 2017-03-14 13:03 UTC
