### ISSUE TITLE
error upgrading from 11.2.3 to 11.2.10

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular-cli#20630] opened 2021-04-27 00:12 UTC
I wish I no longer have to see these error and manually fix them with my hand, in this case I am at a lost what has failed.

$ ng update @angular/cli @angular/core
Using package manager: 'npm'
Collecting installed dependencies...
Found 33 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1102.10" (was "0.1102.3")...
    Updating package.json with dependency @angular/cli @ "11.2.10" (was "11.2.3")...
    Updating package.json with dependency @angular/compiler-cli @ "11.2.11" (was "11.2.4")...
    Updating package.json with dependency @angular/animations @ "11.2.11" (was "11.2.4")...
    Updating package.json with dependency @angular/common @ "11.2.11" (was "11.2.4")...
    Updating package.json with dependency @angular/compiler @ "11.2.11" (was "11.2.4")...
    Updating package.json with dependency @angular/core @ "11.2.11" (was "11.2.4")...
    Updating package.json with dependency @angular/forms @ "11.2.11" (was "11.2.4")...
    Updating package.json with dependency @angular/platform-browser @ "11.2.11" (was "11.2.4")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "11.2.11" (was "11.2.4")...
    Updating package.json with dependency @angular/router @ "11.2.11" (was "11.2.4")...
  UPDATE package.json (1365 bytes)
⠸ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @angular-devkit/build-angular@0.1102.3
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1102.10" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~0.1102.10" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/localize@11.2.11
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.10
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1102.10" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/yadav/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yadav/.npm/_logs/2021-04-27T00_06_41_340Z-debug.log
✖ Package install failed, see above.
✖ Migration failed. See above for further details.

**Comment by alan-agius4** [comment] 2021-04-27 04:59
Duplicate of https://github.com/angular/angular-cli/issues/20375

Unfortunately, this is a defect in NPM 7.

**Closed by alan-agius4** 2021-04-27 04:59 UTC
