### ISSUE TITLE
Allow excluding specific source maps

### ISSUE THREAD

**Issue by AbeerSul** [angular/angular-cli#13881] opened 2019-03-12 05:35 UTC
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
Angular CLI: 7.3.5
Angular: 7.2.7

When I configure build or serve commands to produce source maps in angular.json:
`        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "hasib-apps:build",
            "sourceMap": {
              "scripts": true,
              "styles": false,
              "hidden": false,
              "vendor": true
            }            
          },
          "configurations": {
            "production": {
              "browserTarget": "hasib-apps:build:production"
            }
          }
        },`

I get the warnings for vendors that do not have map files like below:

WARNING in ./node_modules/@devexpress/analytics-core/dx-analytics-core.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'dx-designer-core.js.map': Error: Can't resolve './dx-designer-core.js.map' in 'C:\Users\Abeer.Sulaiman\source\Workspaces\Workspace2017\ERP\Sources\Hasib.SSM\Hasib.SSM.Web\node_modules\@devexpress\analytics-core'
.
WARNING in ./node_modules/devexpress-reporting/dx-reportdesigner.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'dx-reportdesigner.js.map': Error: Can't resolve './dx-reportdesigner.js.map' in 'C:\Users\Abeer.Sulaiman\source\Workspaces\Workspace2017\ERP\Sources\Hasib.SSM\Hasib.SSM.Web\node_modules\devexpress-reporting'
.
.
And I wish I can disable these warnings as I cannot force installed package 'devexpress-reporting' to have source maps.

### Describe the solution you'd like

Allow developers to exclude specific vendor source maps. For example, exclude property can be useful here:
`        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "hasib-apps:build",
            "sourceMap": {
              "scripts": true,
              "styles": false,
              "hidden": false,
              "vendor": true,
              "exclude": [
                "node_modules/devexpress-reporting"
                ]
            }            
          },
          "configurations": {
            "production": {
              "browserTarget": "hasib-apps:build:production"
            }
          }
        },`

### Describe alternatives you've considered

1) Attempted to use "ng eject" to extract webpack.config.json and configure it to exclude  "node_modules/devexpress-reporting" but got the error:

`The 'eject' command has been disabled and will be removed completely in 8.0.
The new configuration format provides increased flexibility to modify the
configuration of your workspace without ejecting.

There are several projects that can be used in conjuction with the new
configuration format that provide the benefits of ejecting without the maintenance
overhead.  One such project is ngx-build-plus found here:
https://github.com/manfredsteyer/ngx-build-plus`

2) Disabled vendor source maps when I don't necessarily need them, to avoid seeing this warning for this vendor.

**Comment by alan-agius4** [comment] 2019-03-12 06:14
Duplicate of https://github.com/angular/angular-cli/issues/11305

**Closed by alan-agius4** 2019-03-12 06:14 UTC
