### ISSUE TITLE
Generated main.ts showing errors in intelliJ

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#673] opened 2016-05-07 04:38 UTC
The generated main.ts shows errors when using `beta.0`  The imports for `AppComponent` and `environment` both had issues in IntelliJ on OSX.

Non working:
```import { AppComponent, environment } from './app/';```
Working: 
```import { AppComponent, environment } from './app';```

**Comment by filipesilva** [comment] 2016-05-07 04:46
I tested in Atom and Visual Studio Code and they seemed to be ok with `import { AppComponent, environment } from './app/';`

**Comment by hawlik** [comment] 2016-05-07 07:38
Same in webstorm. I had to remove trailing slash.

**Comment by Codenator81** [comment] 2016-05-08 09:21
I just reopen webstorm and error from IDE gone

**Comment by hansl** [comment] 2016-05-09 18:59
Considering WebStorm is IntelliJ with a different theming, it's not surprising. I think we should fix this.

**Comment by filipesilva** [comment] 2016-05-09 19:44
Not sure we can fix it, perhaps by changing something in `tsconfig.json`? 

Removing the slash isn't the solution since we can have the `app.ts` file and the `app/` folder, which would both be resolved to the same using `import {} from 'app'`.

**Comment by filipesilva** [comment] 2016-05-09 19:49
To be clear though, the slash should be there, the issue is with webstorm recognizing barrels.

**Comment by hansl** [comment] 2016-05-09 20:21
I talked to JetBrains, and they seem to be moving towards using the TypeScript compiler which will probably resolve this. In any case I agree with Filipe.

**Comment by Brocco** [comment] 2016-05-11 14:37
There appears to be a consensus that this does not need fixed and we will be relying on JetBrains to resolve the issue in IntelliJ & WebStorm; therefore, closing this issue.

**Closed by Brocco** 2016-05-11 14:37 UTC
Labels: command: new, effort: (1) easy, priority: 2 (required), type: bug
