### ISSUE TITLE
Get rid of `node-zopfli` dependency

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#3709] opened 2016-12-22 18:08 UTC
We currently depend on `node-zopfli` but don't really use it and, even though it's optional, it will always try be rebuild itself.

This at best slows down installs and at worst can result in hard to debug failed installs on some systems. This seems to be due to the system actually being able to compile the package natively, but failing somewhere and leaving the `npm install` with missing packages.

**Comment by hansl** [comment] 2016-12-22 18:17
Dupe of https://github.com/angular/angular-cli/issues/3199

**Comment by hansl** [comment] 2016-12-22 18:17
Fixed by https://github.com/angular/angular-cli/pull/3414

**Closed** 2016-12-22 18:17 UTC
Labels: priority: 1 (urgent)
