### ISSUE TITLE
Service worker doesn't store manifest from remote cdn

### ISSUE THREAD

**Issue by jdahl-va** [angular/angular-cli#9609] opened 2018-02-12 21:27 UTC
The service worker won't store a remotely hosted manifest.json, event though the request to the manifest results in a 200, and you can read the response in the dev console.

### Versions
```
@angular/cdk: 5.2.0
@angular/cli: 1.6.8
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.2.0
@angular/service-worker: 5.2.4
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.7.1
webpack-bundle-analyzer: 2.10.0
webpack: 3.10.0
```

### Repro steps
Set the manifests href in your index.html to a CDN instead of something local.  Run the app and you'll see in the network tab of the chrome dev console that your service worker is installed, the request to the manifest succeeds, but the manifest isn't stored.

### Observed behavior

![customer_list](https://user-images.githubusercontent.com/12401997/36120396-a8e8b0b6-1008-11e8-8aea-f984af3d3dc6.png)

The applications tab just says "no manifest detected"

### Desired behavior
If I have a manifest's href pointing to `/manifest.json` (local to the app), the service worker picks it up and works as expected.

### Why am I doing this?
This might seem like an unusual case, but we need remote manifests due to our customers needing some things customized (ie, icons), so we'll need different manifests depending on which customer is using our app.  

My issue may be related to this: https://github.com/angular/angular/issues/20405.

**Comment by jdahl-va** [comment] 2018-02-13 17:13
I think this may be the issue.  When registering the service worker with the service worker module, it doesn't take angular-cli's deployUrl into account:

https://github.com/angular/angular/blob/master/packages/service-worker/src/module.ts#L76-L97

And the generated service worker looks for a manifest local to where it (the service worker) is:
https://github.com/angular/angular/blob/master/packages/service-worker/worker/src/driver.ts#L613

**Comment by jdahl-va** [comment] 2018-07-10 14:41
Just in case anyone stumbles upon this, it's looking like a duplicate of:

https://github.com/angular/angular-cli/issues/9753

**Comment by alan-agius4** [comment] 2018-10-08 13:48
Duplicate of https://github.com/angular/angular-cli/issues/12322.

**Closed by alan-agius4** 2018-10-08 13:48 UTC
Labels: comp: devkit/build-angular, freq1: low, severity3: broken, type: bug/fix
