### ISSUE TITLE
command start is invalid, see `ember help`

### ISSUE THREAD

**Issue by gaurish** [angular/angular-cli#3803] opened 2016-12-31 09:48 UTC
### OS?
Mac 10.12.1

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.7.0
os: darwin x64

### Repro steps.
> ng new app
> ng start

### The log given by the failure.
> The specified command start is invalid. For available options, see `ember help`.

### Mention any other details that might be useful.
I know the command name is wrong byt why its telling me to see `ember help` which doesn't exist & leads to `zsh: command not found: ember` error.

If this is a valid issue, would love to submit a patch for it.

Please provide guidance on next steps.

**Comment by Equinox** [comment] 2016-12-31 10:05
Related [comment](https://github.com/angular/angular-cli/issues/3731#issuecomment-269414546).

**Comment by baruchvlz** [comment] 2017-01-02 01:16
As hansl said here https://github.com/angular/angular-cli/issues/3731#issuecomment-269414546 , this is already fixed and waiting for the next version to change the npm package.

**Comment by Splaktar** [comment] 2017-01-02 04:48
Indeed, this is a duplicate and should be closed.

**Comment by filipesilva** [comment] 2017-01-09 15:23
Closing as dupe of https://github.com/angular/angular-cli/issues/3731

**Closed by filipesilva** 2017-01-09 15:23 UTC
