### ISSUE TITLE
ng serve compiling again and again without any changes

### ISSUE THREAD

**Issue by rahulcse1** [angular/angular-cli#16227] opened 2019-11-19 11:21 UTC
I know it's a repeat of https://github.com/angular/angular-cli/issues/13099
and i have tried all the options mentioned in above thread. Nothing worked for me.
Below is the versions . i am using latest version.
 ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.19
Node: 10.16.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cdk                      8.2.3
@angular/cli                      8.3.19
@angular/http                     7.2.15
@angular/material                 8.2.3
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

**Comment by rahulcse1** [comment] 2019-11-19 12:02
ng serve
10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 30 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 290 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 180 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.98 MB [initial] [rendered]
Date: 2019-11-19T11:31:51.206Z - Hash: 03e05c621ab120affcd0 - Time: 150990ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-11-19T12:00:43.340Z - Hash: 03e05c621ab120affcd0
5 unchanged chunks

Time: 10273ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /runtime.js
i ｢wdm｣: wait until bundle finished: /polyfills.js
i ｢wdm｣: wait until bundle finished: /styles.js
95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /vendor.js
i ｢wdm｣: wait until bundle finished: /main.js

Date: 2019-11-19T12:00:52.716Z - Hash: 03e05c621ab120affcd0
5 unchanged chunks

Time: 8826ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-11-19T12:01:00.459Z - Hash: 03e05c621ab120affcd0
5 unchanged chunks

Time: 7302ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /favicon.ico

Date: 2019-11-19T12:01:05.946Z - Hash: 03e05c621ab120affcd0
5 unchanged chunks

Time: 5126ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-11-19T12:01:26.215Z - Hash: 03e05c621ab120affcd0
5 unchanged chunks

Time: 7585ms
i ｢wdm｣: Compiled successfully.

**Comment by filipesilva** [comment] 2019-11-19 12:27
I don't know of anything that can cause repeat rebuilds without files changing. I imagine there's something in your system changing some of the files in the app folder...

**Comment by filipesilva** [comment] 2019-11-19 12:30
You can try locally altering this file in your node_modules to see what files are triggering the watcher:

https://github.com/angular/angular-cli/blob/7e0d0ff39471f427b34019d9d164e9feee80e885/packages/ngtools/webpack/src/virtual_file_system_decorator.ts#L147-L154

**Comment by rahulcse1** [comment] 2019-11-19 13:21
I am not changing anything in app folder. I'll try to modify above file.

**Comment by filipesilva** [comment] 2019-11-19 14:16
You might not be changing anything yourself, but there might be a background process (e.g. spawned by your editor) that is.

**Comment by rahulcse1** [comment] 2019-11-20 05:28
In order to check that. I just opened terminal and created helloworld app and then 
ng serve
Still got the same problem. It's only happening after upgrading to the latest cli. previously i was using  0.803.5. once i updated to latest. Problem starts occurring.

**Comment by filipesilva** [comment] 2019-11-20 10:25
I'm sorry, but I cannot reproduce that on my windows machine. The most likely reason is that you have some process that is altering in some way the files on disk. 

If you can find what files are triggering the watcher maybe you can use the tools described in https://superuser.com/questions/521476/detect-what-process-is-changing-a-file-on-windows to discover what process is changing it.

**Comment by alan-agius4** [comment] 2020-01-24 18:44
Closing as this in actionable from our end as we cannot reproduce it.

If the problem persists please open a new issue. Thanks.

**Closed by alan-agius4** 2020-01-24 18:44 UTC
Labels: need: repro steps

**Comment by ngochiep30051998** [comment] 2020-02-04 09:50
I am also having the same problem, sometime.
I didn't change my code, but it compiled itself constantly.

`[INFO] ... and 94 additional chunks
[ng] ℹ ｢wdm｣: Compiled successfully.
[ng] ℹ ｢wdm｣: Compiling...
[ng] Date: 2020-02-04T09:44:22.144Z - Hash: a24d6bc12a1e418cb268 - Time: 4610ms
[ng] 149 unchanged chunks
[ng] ℹ ｢wdm｣: Compiled successfully.
[ng] ℹ ｢wdm｣: Compiling...
[ng] Date: 2020-02-04T09:45:07.502Z - Hash: a24d6bc12a1e418cb268 - Time: 2412ms
[ng] 149 unchanged chunks
[ng] ℹ ｢wdm｣: Compiled successfully.
[ng] ℹ ｢wdm｣: Compiling...
[ng] Date: 2020-02-04T09:46:59.372Z - Hash: a24d6bc12a1e418cb268 - Time: 2689ms
[ng] 149 unchanged chunks
[ng] ℹ ｢wdm｣: Compiled successfully.
[ng] ℹ ｢wdm｣: Compiling...
[ng] Date: 2020-02-04T09:48:05.631Z - Hash: a24d6bc12a1e418cb268 - Time: 2333ms
[ng] 149 unchanged chunks
[ng] ℹ ｢wdm｣: Compiled successfully.
[ng] ℹ ｢wdm｣: Compiling...
[ng] Date: 2020-02-04T09:48:25.501Z - Hash: a24d6bc12a1e418cb268 - Time: 1918ms
[ng] 149 unchanged chunks
[ng] ℹ ｢wdm｣: Compiled successfully.
[ng] ℹ ｢wdm｣: Compiling...
[ng] Date: 2020-02-04T09:49:00.456Z - Hash: a24d6bc12a1e418cb268 - Time: 1979ms
[ng] 149 unchanged chunks
[ng] ℹ ｢wdm｣: Compiled successfully.`


my ionic info
`Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.8
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-webview 2.5.3, (and 30 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v12.13.1 (/usr/local/bin/node)
   npm     : 6.12.1
   OS      : macOS Catalina
   Xcode   : Xcode 11.3 Build version 11C29`.


help me, please!!!
