### ISSUE TITLE
ng init questions terminates ng

### ISSUE THREAD

**Issue by bregnvig** [angular/angular-cli#4589] opened 2017-02-10 11:02 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Mac OSX El Capitan

### Versions.
```
                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
@angular/cli: 1.0.0-beta.31
node: 7.3.0
os: darwin x64
```
### Repro steps.

`ng new hello-world`
`cd hello-world`
Make a change to the  README.md
`ng init`
Which gives this:
```
installing ng2
? Overwrite README.md? (yndeH)
```

Answering anything but `h` will make `ng` terminate

### The log given by the failure.

No stacktrace, it just terminates

### Mention any other details that might be useful.

The version `@angular/cli: 1.0.0-beta.31`is not yet on the release page, but it still installed when I did:

```
  npm uninstall -g angular-cli
  npm cache clean
  npm install -g @angular/cli
```

**Comment by filipesilva** [comment] 2017-02-10 11:06
Dupe of https://github.com/angular/angular-cli/issues/4584

**Closed by filipesilva** 2017-02-10 11:06 UTC
