### ISSUE TITLE
ng new project --style=scss is not generating yarn.lock consistently

### ISSUE THREAD

**Issue by lobo-tuerto** [angular/angular-cli#5388] opened 2017-03-11 22:27 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Ubuntu 16.04

### Versions.
> @angular/cli: 1.0.0-rc.1
node: 7.7.2
os: linux x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

### Repro steps.
> ng new a1 --style=scss
Then try to install anything else or run `npm ls`.

### The log given by the failure.
> $ npm install --save @angular/material
a1@0.0.0 /home/x/desarrollo/proyectos/angular2/a1
├── @angular/material@2.0.0-beta.2 
└── UNMET PEER DEPENDENCY typescript@2.0.10
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/tsc-wrapped@4.0.0-rc.2 requires a peer of typescript@^2.1.5 but none was installed.
npm WARN tsickle@0.21.5 requires a peer of typescript@^2.1.0 but none was installed.

### Mention any other details that might be useful.
Sometimes it creates a project without dependencies problems, sometimes not.

I have a sample for each (one working, one not working), created with the same `ng-cli` version.

It looks like the problem is in the generate `yarn.lock` file. Specifically here:

![ng-cli-issue-1](https://cloud.githubusercontent.com/assets/5730/23827345/4e06663e-0677-11e7-98e5-2ca0952c39f9.png)

The one on the left is the working one. The one on the right introduced the unmet dependency problem.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2017-03-18 00:47
Dupe of https://github.com/angular/angular-cli/issues/5085 I believe.

**Closed by filipesilva** 2017-03-18 00:47 UTC
