### ISSUE TITLE
angular-cli 1.0.0-beta.14  developing my  package

### ISSUE THREAD

**Issue by jjlgjkkl** [angular/angular-cli#2214] opened 2016-09-19 08:16 UTC
i'm developing my angular2 package and will publish to our private npm warehouse
in angular-cli 1.0.0-beta.14 , when building  my source code,there are three problems:

1)how to copy files to dist dir? that can be done in    angular-cli 1.0.0-beta.10
2)how to keep the   js and .d.ts files in the dist dir?  that  also can be done in    angular-cli 1.0.0-beta.10
3) webpack does not build the not used files
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jbeckton** [comment] 2016-09-19 19:42
We are building reusable angular 2 libraries that have modules that wrap common functionality, I could be wrong but most likely the CLI Webpack is not going to be the right tool for the job. You would not want to bundle all your scripts inside your library package, Webpack is going to do that anyways when your library is a dependency of your web app. 

I use Gulp to manage my build tasks for my library packages. The CLI Webpack is appropriate for web application code.

**Comment by filipesilva** [comment] 2016-09-22 04:04
Dupe of https://github.com/angular/angular-cli/issues/1692

For now the CLI is mostly focused on apps instead of libs, but we want to do libs in the feature.

**Closed by filipesilva** 2016-09-22 04:04 UTC
