### ISSUE TITLE
New build system -esbuild can't find an ng-select import in styles.scss

### ISSUE THREAD

**Issue by raclettedesavoie** [angular/angular-cli#26447] opened 2023-11-21 17:16 UTC
### Command

version

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.0.1

### Description

I just added -esbuild to test the new build system and the build is no longer working and i get this error :

The Error :
![Sans titre](https://github.com/angular/angular-cli/assets/78375181/26228d7b-0bff-462c-a1d9-b4da2368b0fb)
Adding -esbuild:
![Sans titrde](https://github.com/angular/angular-cli/assets/78375181/fb1ef541-b6e0-49a1-96f6-a5ae2d0e7e49)
I'm using nx on the project.
It's working if I build without -esbuild.

### Minimal Reproduction

Use new -esbuild build

import
``` 
 @import '~@ng-select/ng-select/themes/default.theme.css'; 
 ``` 
 into style.scss

Try build : 
``` 
npx nx run NameOfYourApp:serve 
```

### Your Environment

```text
_                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.2       
Node: 18.18.0
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.2
@angular-devkit/build-angular   17.0.2
@angular-devkit/core            17.0.2
@angular-devkit/schematics      17.0.2
@angular/cdk                    17.0.1
@angular/cli                    17.0.2
@angular/google-maps            17.0.1
@angular/material               17.0.1
@schematics/angular             17.0.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by alan-agius4** [comment] 2023-11-21 17:23
Duplicate of https://github.com/angular/angular-cli/issues/24387

**Closed by alan-agius4** 2023-11-21 17:23 UTC
