### ISSUE TITLE
Failed to Compile Angular App After editing typescript files 

### ISSUE THREAD

**Issue by jarvis7373** [angular/angular-cli#8438] opened 2017-11-10 13:30 UTC
ERROR in Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at AngularCompilerPlugin._updateForkedTypeChecker (/home/webteam/Documents/Angular/WebApp/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:370:34)
    at Promise.resolve.then (/home/webteam/Documents/Angular/WebApp/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:208:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

webpack: Failed to compile.

plz help to resolve this error

**Comment by jarvis7373** [comment] 2017-11-10 13:34
above error displays after saving app.component.ts file .
using ctrl+c i close server then i use ng serve the app works fine

**Comment by Brocco** [comment] 2017-11-14 19:46
This issue has been reported and the progress can be tracked via #8331

Duplicate of #8331

**Closed by Brocco** 2017-11-14 19:46 UTC
