### ISSUE TITLE
pre-render an application with angular-cli universal

### ISSUE THREAD

**Issue by WPietrzak** [angular/angular-cli#5624] opened 2017-03-24 12:38 UTC
### Bug Report or Feature Request (mark with an `x`)
- [x ] feature request

### Versions.
universal-cli: 1.0.0-alpha.universal.3
angular-cli: 1.0.0-beta.23
node: 6.10.0
os: win32 x64

### Desired functionality.
According to Angular Universal documentation there are two different approaches you can use for server rendering. The first option is to pre-render your application which means that you would use one of the Universal build tools (i.e. gulp, grunt, broccoli, webpack, etc.) to generate static HTML for all your routes at build time. Then you could deploy that static HTML to a CDN. The advantage of this approach is that it is highly scalable and performant. The disadvantage is that it is not quite as flexible as the second approach.

My question is if it's possible to use the above approach with angular universal cli?

Thank You
Wojtek

**Comment by RicardoVaranda** [comment] 2017-03-24 14:18
Hi @WPietrzak ,

This topic is currently being discussed at : https://github.com/angular/angular-cli/issues/1050 .
While this currently is not in the scope it's already being worked on and hopefully integrated soon as mentioned by @MarkPieszak here: https://github.com/angular/angular-cli/issues/1050#issuecomment-283680139 

Meanwhile you can take a look at the progress here:
https://github.com/devCrossNet/universal-cli

Thanks! 👍

**Comment by esistgut** [comment] 2017-03-24 14:34
Looks like universal-cli should be avoided: https://github.com/devCrossNet/universal-cli/issues/101#issuecomment-288464913

**Comment by filipesilva** [comment] 2017-03-24 14:52
I'm closing it as dupe of #1050 because it's better to keep discussion centralized there.

**Closed by filipesilva** 2017-03-24 14:52 UTC
