### ISSUE TITLE
npm install failed with rimraf messages

### ISSUE THREAD

**Issue by alanpurple** [angular/angular-cli#25110] opened 2023-05-02 01:09 UTC
### Command

other

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.2.6

### Description

npm install error because of rimraf

### Minimal Reproduction

npm install -g @angular/cli

### Exception or Error

```text
PS C:\Users\alanp> npm install -g @angular/cli
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\alanp\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\alanp\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\observable'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\alanp\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\rxjs\\observable'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\alanp\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\alanp\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-gyp'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\alanp\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-gyp'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\alanp\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\alanp\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@schematics\angular\third_party\github.com\Microsoft'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\alanp\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\@schematics\\angular\\third_party\\github.com\\Microsoft'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\alanp\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\inquirer',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\alanp\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\inquirer'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\alanp\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\inquirer'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\alanp\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\alanp\AppData\Local\npm-cache\_cacache\tmp\git-cloneUtQpFv
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run compile
npm ERR! npm ERR! > cliui@8.0.1 precompile
npm ERR! npm ERR! > rimraf build
npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! 'rimraf' is not recognized as an internal or external command,
npm ERR! npm ERR! operable program or batch file.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\alanp\AppData\Local\npm-cache\_logs\2023-05-02T01_07_45_852Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alanp\AppData\Local\npm-cache\_logs\2023-05-02T01_07_37_955Z-debug-0.log
```
```


### Your Environment

```text
Windows 11 22h2 x64
node.js 18.16.0 and 20.0.0   both same error
```

**Comment by zf-rb** [comment] 2023-05-02 02:00
Also getting the same issue. 
Locally:
- Windows 11 (Node 16)

Azure DevOps:
- Ubuntu
- Windows

---

Have tried installing earlier versions of the `@angular/cli` package (v15) with no success, until I tried v14 (Maybe a workaround for some, however not good that v14 targeting v15).

**Comment by souponaroom** [comment] 2023-05-02 02:04
Same issue:

Arch Linux (Node 18.6.0 through NVM). Could not update without getting a weird "npm: command not found" error halfway through "npm update -g" being ran, and then tried to just delete node environment and reinstall. Now I get the same error as the original poster.

**Comment by kerryj89** [comment] 2023-05-02 03:08
Not exactly the same error message but a bit coincidental I ran into this a few hours ago also and it's stopping my CI run.

```
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm ERR! code 2
npm ERR! git dep preparation failed
npm ERR! command /opt/hostedtoolcache/node/16.20.0/x64/bin/node /opt/hostedtoolcache/node/16.20.0/x64/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/runner/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 2
npm ERR! npm ERR! path /home/runner/.npm/_cacache/tmp/git-cloneFGUdnT
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c -- npm run compile
npm ERR! npm ERR! > cliui@8.0.1 compile
npm ERR! npm ERR! > tsc
npm ERR! npm ERR! 
npm ERR! npm ERR! error TS50[83](https://github.com/redacted/redacted/actions/runs/123456/jobs/123456#step:8:85): Cannot read file '/home/runner/.npm/_cacache/tmp/git-cloneFGUdnT/node_modules/gts/tsconfig-google.json'.
Error: npm ERR! npm ERR! lib/index.ts(214,54): error TS2550: Property 'trimEnd' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2019' or later.
Error: npm ERR! npm ERR! lib/index.ts(233,19): error TS2550: Property 'trimEnd' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2019' or later.
Error: npm ERR! npm ERR! lib/index.ts(233,88): error TS2550: Property 'trimStart' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2019' or later.
[...]
```

**Comment by zf-rb** [comment] 2023-05-02 03:13
I was able to reproduce the same error as @kerryj89  when I had manually installed `typescript` and `rimraf` globally.

```
npm i -g rimraf@3.0.2
npm i -g typescript
```

After removing these packages manually, I was back to the same error as the original poster.

```
npm uninstall -g rimraf
npm uninstall -g typescript
```

**Comment by kerryj89** [comment] 2023-05-02 03:23
Actually, the project I am looking at with this issue doesn't use Angular like I thought (got mixed up) - I landed here after searching Google since it's a fresh issue for many of us. When I did `yarn why @npmcli/move-file` it mentioned `gulp-iconfont#gulp-ttf2woff2#ttf2woff2#node-gyp#make-fetch-happen#cacache` and it seems `[cacache](https://www.npmjs.com/package/cacache)` lib was updated 8 hours ago... maybe a coincidence?  Anyhow, sorry that my findings aren't directly related to Angular as I once thought but maybe we can find some common root.

**Comment by BenTaylorPublic** [comment] 2023-05-02 04:04
It's now working locally and in my pipelines for me.

**Comment by zf-rb** [comment] 2023-05-02 04:06
I'm able to install locally too. Will assume my pipelines are working and advise if not.

**Comment by alan-agius4** [comment] 2023-05-02 09:08
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Closed by alan-agius4** 2023-05-02 09:08 UTC
