### ISSUE TITLE
weird LCOV file generated after unit tests run

### ISSUE THREAD

**Issue by bootrider** [angular/angular-cli#2297] opened 2016-09-22 19:30 UTC
1. OS?  
   Windows7
2. Versions. 
   angular-cli: 1.0.0-beta.14
   node: 6.3.1
   os: win32 x64
3. Repro steps. Was this an app that wasn't created using the CLI? 
   I created an app using the ng, then I run ng test, everything goes fine.

Read the LCOV file generated and it states that the file are:
`SF:C:/T/YYYYY/Main/XXX/XXX.YYYYY/node_modules\angular2-template-loader\index.js!C:\T\YYYYY\Main\XXX\XXX.YYYYY\node_modules\tslint-loader\index.js!C:\T\YYYYY\Main\XXX\XXX.YYYYY\src\test.ts`

`SF:C:/T/YYYYY/Main/XXX/XXX.YYYYY/node_modules\angular2-template-loader\index.js!C:\T\YYYYY\Main\XXX\XXX.YYYYY\node_modules\tslint-loader\index.js!C:\T\YYYYY\Main\XXX\XXX.YYYYY\src\polyfills.ts`

`SF:C:/T/YYYYY/Main/XXX/XXX.YYYYY/node_modules\angular2-template-loader\index.js!C:\T\YYYYY\Main\XXX\XXX.YYYYY\node_modules\tslint-loader\index.js!C:\T\YYYYY\Main\XXX\XXX.YYYYY\src\app\app.component.ts`

the same behavior happens if the reporter is changed to any of this formats:

```
remapIstanbulReporter: {

      reports: {
        html: 'coverage',
        lcovonly: './coverage/coverage.lcov',
        json: './coverage/json-report.json',
        cobertura:'coverage/coverage.xml'
      }
    }

```

More over, the in the JSON report the code appear as an array of lines of strings.

In other projects of JavaScript using TypeScript as language, Jasmine as a Unit test framework ,Karma
as runner and Remap-Istanbul, the report always define the name of the file as relative path (not the combination of three different paths), in the JSON report the code appear as a single line, not as an Array.

Why this happen? is there any configuration file that states that behaviors? 
It is possible to get a report that states only the involved file in the test (relative or absolute)?

**Comment by brunobastosg** [comment] 2016-09-23 17:53
I have the same problem, but I created the app using the CLI.

Here's part of the generated lcov file:

```
SF:/home/myusername/.jenkins/workspace/exemplo-angular2-sonar-typescript/node_modules/angular2-template-loader/index.js!/home/myusername/.jenkins/workspace/exemplo-angular2-sonar-typescript/node_modules/tslint-loader/index.js!/home/myusername/.jenkins/workspace/exemplo-angular2-sonar-typescript/src/test.ts

SF:/home/myusername/.jenkins/workspace/exemplo-angular2-sonar-typescript/node_modules/angular2-template-loader/index.js!/home/myusername/.jenkins/workspace/exemplo-angular2-sonar-typescript/node_modules/tslint-loader/index.js!/home/myusername/.jenkins/workspace/exemplo-angular2-sonar-typescript/src/polyfills.ts

SF:/home/myusername/.jenkins/workspace/exemplo-angular2-sonar-typescript/node_modules/angular2-template-loader/index.js!/home/myusername/.jenkins/workspace/exemplo-angular2-sonar-typescript/node_modules/tslint-loader/index.js!/home/myusername/.jenkins/workspace/exemplo-angular2-sonar-typescript/src/app/app.component.ts
```

Because of that, Sonar can't read coverage information and shows 0%.

**Comment by bootrider** [comment] 2016-09-23 20:06
@brunobastosg Which plugin are you using in Sonar?

**Comment by bootrider** [comment] 2016-09-23 20:42
I modified the code of the plugin that I am using, so it will load this weird LCOV file

**Comment by brunobastosg** [comment] 2016-09-23 20:48
@bootrider I'm using [SonarTsPlugin](https://github.com/Pablissimo/SonarTsPlugin)

I thought of modifying it but there's no urgency, so I'll wait to see what's the deal with this weird LCOV file.

**Comment by leandronunes** [comment] 2016-09-27 12:01
Hi guys,
I have the same problem using SonarTsPlugin

**Comment by adriancarriger** [comment] 2016-10-19 15:43
I have the same issue using Angular CLI 1.0.0-beta.17, macOS Sierra, and Node 6.5.0.

As a temporary workaround I added a [simple script](https://github.com/adriancarriger/clean-to-the-core/blob/master/scripts/fix_coverage.js#L19-L32) to run after tests that removes the unnecessary text from the LCOV file.

I'd be great to fix the real issue though!

**Comment by adriancarriger** [comment] 2016-12-24 17:54
This appears to be fixed using the latest version of the CLI (1.0.0-beta.24). Is anyone still experiencing the issue?

**Comment by brunobastosg** [comment] 2016-12-26 12:06
I can confirm that version 1.0.0-beta.24 fixed the issue.

**Comment by Brocco** [comment] 2017-01-09 04:23
With two people verifying the fix, closing the issue. If someone still experiences this, please comment and/or open a new issue.

**Closed by Brocco** 2017-01-09 04:23 UTC
Labels: command: test, need: investigation, priority: 2 (required)
