### ISSUE TITLE
ng new FAIL

### ISSUE THREAD

**Issue by ddagone** [angular/angular-cli#1274] opened 2016-07-03 15:47 UTC
When I'm trying to type `ng new tutorial` I get this message error right here : 

OS  ? OS X El Capitan
```
module.js:327
    throw err;
    ^
Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/lib/models/project.js:11:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

I don't know what or why it shows up, help would be great 👍

**Comment by suv0** [comment] 2016-07-03 20:02
`npm install` should have fix the issue. 

make sure your npm version is : 3.10.2

**Comment by moloch--** [comment] 2016-07-03 20:59
You have to go into the `/node_modules/angular-cli` and then run `npm install`, not sure why this is ... but it's the default behavior right now, the only documented fixes are in other GitHub issues.

**Comment by ddagone** [comment] 2016-07-03 21:06
Could you tell me where I can find this, is it in /usr/bin ?


2016-07-03 22:59 GMT+02:00 Joe <notifications@github.com>:

**Comment by ddagone** [comment] 2016-07-03 21:09
Nop, sorry but still nothing

ng new ang_project
/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/configstore/index.js:54
throw err;
^

Error: EACCES: permission denied, open
'/Users/redsun/.config/configstore/ember-cli.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.create.all.get
(/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/configstore/index.js:35:26)
    at Object.Configstore
(/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/configstore/index.js:28:44)
    at clientId
(/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/lib/cli/index.js:22:21)
    at module.exports
(/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/lib/cli/index.js:65:19)
    at module.exports
(/usr/local/lib/node_modules/angular-cli/lib/cli/index.js:106:10)
    at /usr/local/lib/node_modules/angular-cli/bin/ng:31:5
    at
/usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:46:14
➜  ~ npm -v
2.15.8

2016-07-03 23:06 GMT+02:00 Djamal Dag. <dagirovdjamal@gmail.com>:

**Comment by ddagone** [comment] 2016-07-03 21:16
Ok, I just understood the problem, Now It creates the necessary files but
when I do ``ng serve`` this Shows up :

ng serve
module.js:327
    throw err;
    ^

Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous>
(/Users/redsun/pro/node_modules/angular-cli/node_modules/ember-cli/lib/models/project.js:11:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

2016-07-03 23:09 GMT+02:00 Djamal Dag. <dagirovdjamal@gmail.com>:

**Comment by filipesilva** [comment] 2016-07-03 21:30
Duplicate of https://github.com/angular/angular-cli/issues/1186, solved in https://github.com/angular/angular-cli/pull/1250. Will be in the next release.

**Closed by filipesilva** 2016-07-03 21:30 UTC
