### ISSUE TITLE
Beta 22 build fails when using dependencies that don't support AoT

### ISSUE THREAD

**Issue by bonnici** [angular/angular-cli#3418] opened 2016-12-06 00:31 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 4.6.0
os: win32 x64

### Repro steps.
Ran ng build on a beta.22 app that imports an AoT-incompatible library (https://github.com/pleerock/ng2-rating) - see https://github.com/pleerock/ng2-rating/issues/6

### The log given by the failure.
```
$ ng build                                                                                                                              10% building modules 3/3 modules 0 activeRatingModule is not an NgModule
Error: RatingModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (C:\src\max-web\node_modules\@ngtools\webpack\src\plugin.js:332:19)
    at C:\src\max-web\node_modules\@ngtools\webpack\src\plugin.js:345:51
    at Array.map (native)
    at AotPlugin.extractLoadChildren (C:\src\max-web\node_modules\@ngtools\webpack\src\plugin.js:343:14)
    at C:\src\max-web\node_modules\@ngtools\webpack\src\plugin.js:346:30
    at Array.map (native)
    at AotPlugin.extractLoadChildren (C:\src\max-web\node_modules\@ngtools\webpack\src\plugin.js:343:14)
    at AotPlugin._processNgModule (C:\src\max-web\node_modules\@ngtools\webpack\src\plugin.js:272:38)
    at C:\src\max-web\node_modules\@ngtools\webpack\src\plugin.js:242:39
    at tryCatch (C:\src\max-web\node_modules\es6-promise\dist\es6-promise.js:410:12)
    at invokeCallback (C:\src\max-web\node_modules\es6-promise\dist\es6-promise.js:425:13)
    at publish (C:\src\max-web\node_modules\es6-promise\dist\es6-promise.js:393:7)
    at flush (C:\src\max-web\node_modules\es6-promise\dist\es6-promise.js:121:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

### Mention any other details that might be useful.
It would be great if there was a way to completely disable AoT, I'm sure there are many dependencies that are not yet AoT-ready and not being able to upgrade angular-cli until third parties decide to do the upgrade is pretty painful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment] 2016-12-06 02:02
If you use `ng build`, we don't use AoT at all. The `AoTPlugin` you see is used for compiling TypeScript. It supports both JIT and AOT compilations, so probably should be named something else now to avoid confusion.

In any case, I'm cloning your library to see if I can figure out what's going on.

**Comment by hansl** [comment] 2016-12-06 02:05
So unfortunately, we need all `@NgModule`s to be statically analyzable to see if they support routes and lazy routes, etc. Because they don't support AoT, the CLI won't be able to use their library either. We'll work with them to precipitate this. Cheers.

This is working as intended, so closing the issue.

**Closed by hansl** 2016-12-06 02:05 UTC

**Comment by born2net** [comment] 2016-12-06 04:21
Are there more docs that can be provided on how to fix this as I'm also having a problem with libraries with release 22. I was not able to create the Emitt declaration filed so far...

 I have a feeling there's going to be a lot of noise on issues due to release 22 
regards

Sean
