### ISSUE TITLE
Errors while compiling. Reload prevented. (beta-25)

### ISSUE THREAD

**Issue by s-f-a-g** [angular/angular-cli#4075] opened 2017-01-17 21:00 UTC
Live reload doesn't work anymore. With beta 24, I had errors but it worked, now it just doesn't reload at all.

### OS?
> Mac OSX (El Capitan)

### Versions.
angular-cli: 1.0.0-beta.25.5
node: 7.4.0
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3
socktjs : 0.3.18

### Repro steps.
The app is a full fresh app. I just run ng serve. I have a message telling in intelliJ

> ERROR in Could not resolve "/Users/me/" from "/Users/me/".

 With the beta 24, I had the message but I could used livereload, now live-reload doesn't work and I have the following message in chrome console : 

> Errors while compiling. Reload prevented.

### The log given by the failure.
> errors                                                       @ client?93b6:101
> sock.onmessage                                     @ socket.js:37
> EventTarget.dispatchEvent                    @ eventtarget.js:51
> (anonymous)                                           @ main.js:274
> SockJS._transportMessage                   @ main.js:272
> EventEmitter.emit                                   @ emitter.js:50
> WebSocketTransport.ws.onmessage    @ websocket.js:35
> wrapFn                                                    @ zone.js:962
> ZoneDelegate.invokeTask                      @ zone.js:275
> Zone.runTask                                          @ zone.js:151
> ZoneTask.invoke                                     @ zone.js:345

**Comment by filipesilva** [comment] 2017-01-17 22:51
Dupe of https://github.com/angular/angular-cli/issues/4069 I think.

**Closed by filipesilva** 2017-01-17 22:51 UTC
