### ISSUE TITLE
Incorrect declaration files

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12094] opened 2018-09-04 23:00 UTC
_From @mdasberg on May 23, 2018 13:1_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
All

### Repro steps
Any typescript linter will show the error.

### The log given by the failure
...packages/angular_devkit/build_angular/src/browser/schema.d.ts
Unresolved type FIleReplacements 
52 |     fileReplacements: FileReplacements[];

...packages/angular_devkit/build_angular/src/server/schema.d.ts
Unresolved type FIleReplacements 
75 |     fileReplacements: FileReplacements[];

### Desired functionality
Fix the declaration files see: [PR](https://github.com/angular/devkit/pull/958)

### Mention any other details that might be useful

_Copied from original issue: angular/devkit#963_

**Comment by alexeagle** [comment] 2018-09-04 23:00
_From @filipesilva on May 24, 2018 16:45_

I'm not sure how you're running this though. We run linting on your repro and the error does not come up. 

How exactly are you getting this error? Can you provide repro steps?

**Comment by alexeagle** [comment] 2018-09-04 23:00
_From @mdasberg on May 24, 2018 18:20_

When trying to extend the BrowserBuilder for example, I get errors when trying to compile.
Also if you open those files in your IDE, you will see the errors.

FileReplaceMents is not an interface or class. FileReplacement is.

**Comment by alexeagle** [comment] 2018-09-04 23:00
_From @mdasberg on May 24, 2018 18:50_

For example:

```typescript
import {BrowserBuilder, NormalizedBrowserBuilderSchema} from '@angular-devkit/build-angular';
import {Path, virtualFs} from '@angular-devkit/core';

import * as fs from 'fs-extra';

export class MyBrowserBuilder extends BrowserBuilder {
    /** {@inheritDoc}. */
    buildWebpackConfig(root: Path, projectRoot: Path, host: virtualFs.Host<fs.Stats>, options: NormalizedBrowserBuilderSchema): any {
        return super.buildWebpackConfig(root, projectRoot, host, options);
    }
}

export default MyBrowserBuilder;
```

will result in the following errors:

```
> tsc -p tsconfig.json

node_modules/@angular-devkit/build-angular/src/browser/schema.d.ts(52,21): error TS2304: Cannot find name 'FileReplacements'.
node_modules/@angular-devkit/build-angular/src/server/schema.d.ts(75,21): error TS2304: Cannot find name 'FileReplacements'.
```

Also notable is that when you change for instance the schema.d.ts file with
```
fileReplacements: abcde[];
```

It also passes.

**Comment by alexeagle** [comment] 2018-09-04 23:00
_From @dwieeb on May 30, 2018 17:44_

Also getting this. Not quite sure how this compiles:

notice the additional `s` at the end

https://github.com/angular/devkit/blob/4fb409d7c1c04d8f0c3d515ba515e470c91bb9da/packages/angular_devkit/build_angular/src/browser/schema.d.ts#L52

https://github.com/angular/devkit/blob/4fb409d7c1c04d8f0c3d515ba515e470c91bb9da/packages/angular_devkit/build_angular/src/browser/schema.d.ts#L265

**Comment by alan-agius4** [comment] 2018-09-05 05:55
Duplicate of https://github.com/angular/angular-cli/issues/11294

**Closed by alan-agius4** 2018-09-05 05:55 UTC
Labels: need: more info
