### ISSUE TITLE
suggestion: generate document automatically?

### ISSUE THREAD

**Issue by eriyu** [angular/angular-cli#2017] opened 2016-09-08 02:44 UTC
I found I can use [typedoc](https://github.com/TypeStrong/typedoc) to generate 'JSDOC style comment' into document .

![](https://i.imgur.com/FW4uH0Q.png)

If I can use `ng doc` to generate document automatically.

I think it must be better!

**Comment by dtesta** [comment] 2016-10-18 18:48
Related #102

**Comment by filipesilva** [comment] 2016-10-23 14:08
@dtesta is right, this one is a dupe of https://github.com/angular/angular-cli/issues/102.

**Closed by filipesilva** 2016-10-23 14:08 UTC
Labels: command: generate, priority: 3 (nice to have), type: enhancement
