### ISSUE TITLE
Delete Component

### ISSUE THREAD

**Issue by gabrielw007** [angular/angular-cli#24703] opened 2023-02-12 11:44 UTC
### Command

build, generate

### Description

required a new command to delete component and its references from the app
also to display all its references in the app

### Describe the solution you'd like

ng del c myComponent

### Describe alternatives you've considered

currently you have to do everything manually...

**Comment by alan-agius4** [comment] 2023-02-12 15:03
Duplicate of https://github.com/angular/angular-cli/issues/900

**Closed by alan-agius4** 2023-02-12 15:03 UTC
