### ISSUE TITLE
[ERROR] Could not resolve "../assets/fonts/my-font.woff"

### ISSUE THREAD

**Issue by ThomasDevGif** [angular/angular-cli#27165] opened 2024-02-27 10:27 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

Hello,

Previously I opened an issue because I could't build my angular design system library after upgrading it fom v16 to v17.1.0 .
I had an error when importing my font when using absolute path : [ERROR] Could not resolve "/assets/fonts/my-font.woff".

I changed the ng-packagr version from v17.1.0 to 17.2.0 and my scss import using absolute path is now working.
But if I want to use relative path "../../assets/" it still does not compile.

Is there a reason to not allow relative path in scss import ?

I use my lib in several angular applications with different base href so the absolute path does not working.

### Minimal repro

I created 2 workspaces and generated a library in each. I added a custom font in their assets folder et I import this font in their styles folder.

One workspace is generated with @angular/cli@16 and the other one with @angular/cli@17.

If i run the "npm run build" command in each
- the angular 16 build successfully
- the angular 17 throws
```
Build failed with 2 errors:
<stdin>:3:7: ERROR: Could not resolve "../assets/my-font.woff2"
<stdin>:3:53: ERROR: Could not resolve "../assets/my-font.woff"
```

Thanks in advance,

### Minimal Reproduction

-     Create an angular 17 workspace
-     Generate a design-system library
-     Add some fonts in assets folder
-     Create a styles folder :
projects / design-system /
-assets / fonts /...
-src / ...
-styles / fonts.scss

- Add the following code in the fonts.scss file
```scss
@font-face {
  font-family: "MyFont";
  src: url("../assets/fonts/my-font.woff2") format("woff2"),
  url("../assets/fonts/my-font.woff") format("woff");
}
```

- Try to run the ng build command

### Exception or Error

```text
[ERROR] Could not resolve "../assets/fonts/my-font.woff" [plugin angular-css-resource]
```

### Your Environment

```text
17.1.0 et 17.2.0
```

**Comment by ThomasDevGif** [comment] 2024-03-04 10:47
Hello Alan,
I created the 2 workspaces but I forgot to add the links..

https://github.com/ThomasDevGif/workspace17

https://github.com/ThomasDevGif/workspace16

So, one workspace is generated with @angular/cli@16 and the other one with @angular/cli@17.

If i run the "npm run build" command in each

    the angular 16 build successfully
    the angular 17 throws

Build failed with 2 errors:
<stdin>:3:7: ERROR: Could not resolve "../assets/my-font.woff2"
<stdin>:3:53: ERROR: Could not resolve "../assets/my-font.woff"

**Comment by alan-agius4** [comment] 2024-03-04 11:02
Thanks, based on the reproduction I can state that this is a duplicate of https://github.com/angular/angular-cli/issues/27007

**Closed by alan-agius4** 2024-03-04 11:02 UTC
Labels: needs: repro steps
