### ISSUE TITLE
Duplicate css entry in angular-cli.json produces cryptic webpack error

### ISSUE THREAD

**Issue by hisham** [angular/angular-cli#2671] opened 2016-10-12 18:03 UTC
Ideally `ng serve` should still work with a duplicate entry under styles but give a warning instead of an error. 
### OS?

Mac OSX El Capitan
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

`angular-cli: 1.0.0-beta.17
node: 6.4.0
os: darwin x64`
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

In the angular-cli.json created by ng init, add a duplicate entry to apps[styles] - e.g.:

`"styles": [
        "styles.css",
        "styles.css"
      ],`
### The log given by the failure.

> Normally this include a stack trace and some more information.

Running `ng serve` gives this error: 

`Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration.entry['styles'] should be one of these:
  string | [string]
  The entry point for one output file.
- configuration.entry should be one of these:
  object { <key>: string | [string] } | string | [string]
  The entry point(s) of the compilation.`

**Comment by catull** [comment] 2017-02-09 18:55
A couple of nits:

`ng serve` allows multiple entries in angluar-cli.json, AS LONG as they are different.

I can reproduce the error if `"styles": [ "styles.css", "styles.css" ],`

If the configuration becomes `"styles": [ "styles.css", "styles2.css" ],`

`ng serve` builds the dist, but complains:

```
ERROR in multi ./src/styles.css ./src/styles2.css
Module not found: Error: Can't resolve '/private/tmp/cool-app/src/styles2.css' in '/private/tmp/cool-app'
 @ multi ./src/styles.css ./src/styles2.css
```
After adding an empty src/styles2.css, everybody wins.

In short, the implementation works as expected, you got to feed it the correct config/data.

**Comment by hansl** [comment] 2017-02-23 18:54
Closing this as working as intended after @catull comment.

**Closed by hansl** 2017-02-23 18:54 UTC
Labels: command: build, priority: 2 (required), type: bug
