### ISSUE TITLE
"ng update" can install @next packages without the --next flag (Get compileFactoryFromMetadata is not a function after upgrading to angular 8)

### ISSUE THREAD

**Issue by zeinali0** [angular/angular-cli#15808] opened 2019-10-04 17:14 UTC
Hi i can't run my project after updating it from angular 7 to angular 8 by running `ng update @angular/cli @angular/core`

## 🔥 Exception or Error
<pre><code>
chunk {main} main.js, main.js.map (main) 2.02 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 149 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 147 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.63 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2019-10-04T16:50:24.470Z - Hash: 65f8616cbfb2cdc52e74 - Time: 6122ms

ERROR in compiler_1.compileFactoryFromMetadata is not a function
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.8
Node: 10.16.3
OS: win32 x64
Angular: 8.2.9
... animations, common, compiler, core, forms, language-service
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.8
@angular-devkit/build-angular     0.803.8
@angular-devkit/build-optimizer   0.803.8
@angular-devkit/build-webpack     0.803.8
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cdk                      8.0.0
@angular/cli                      8.3.8
@angular/compiler-cli             9.0.0-next.9
@angular/material                 8.0.0
@angular/pwa                      0.12.4
@ngtools/webpack                  8.3.8
@schematics/angular               7.2.4
@schematics/update                0.803.8
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by clydin** [comment] 2019-10-10 23:45
Duplicate of #14980

**Closed by clydin** 2019-10-10 23:45 UTC
