### ISSUE TITLE
Function in route generation causes lazy module to be unreachable

### ISSUE THREAD

**Issue by j3ddesign** [angular/angular-cli#2546] opened 2016-10-06 10:11 UTC
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.16
node: 6.4.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
**Current behavior**
When using a function to tidy route generation, eg:
```
const LazyRoute = (path: string, moduleName: string, dir?: string) => ({
  path: path,
  loadChildren: `app/core/+${dir ? dir : path}/${dir ? dir : path}.module#${moduleName}`
});
const LAZY_ROUTES = [
  LazyRoute('moderators', 'ModeratorModule'),
  LazyRoute('settings', 'SettingsModule'),
  LazyRoute('blog', 'BlogModule'),
  LazyRoute('help', 'HelpModule'),
  LazyRoute('wishlist', 'WishlistModule'),
  LazyRoute(':name', 'DashboardModule', 'dashboard')
];
```
The above setup logs out correctly, and should be functional, however routing to the module causes 'module cannot be found' errors (while giving the correct path in the error log)

I have copied the outputs from these functions and used them directly in the route configs, instead of abstracting to functions, and the app successfully loads and runs perfectly.

### The log given by the failure.
> Normally this include a stack trace and some more information.
In browser (Chrome 55.0.2880.4 canary) console: 
When navigating to `/settings/account` for example:
`Error: Cannot find module 'app/core/+settings/settings.module'.`

**Comment by filipesilva** [comment] 2016-10-09 20:51
Dupe of https://github.com/angular/angular-cli/issues/2485

**Closed by filipesilva** 2016-10-09 20:51 UTC
