### ISSUE TITLE
ERROR in <module> is not an NgModule

### ISSUE THREAD

**Issue by RickyGeek** [angular/angular-cli#4050] opened 2017-01-16 15:17 UTC
### OS
Mac OS El Capitan 

### Versions.
angular-cli: 1.0.0-beta.25.5
node: 6.2.2
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/compiler-cli: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.2.4

### Repro steps.
ng serve

### The log given by the failure.
ERROR in myModule is not an NgModule

**Comment by beeman** [comment] 2017-01-16 15:46
@RickyGeek most likely a duplicate of #3426 

If it's your own module, see [this comment](https://github.com/angular/angular-cli/issues/3426#issuecomment-269673735) on how to structure/publish them.

**Comment by filipesilva** [comment] 2017-01-16 15:52
Closing as dupe, thanks @beeman!

**Closed by filipesilva** 2017-01-16 15:52 UTC
