### ISSUE TITLE
ctrl + z do not close ng process

### ISSUE THREAD

**Issue by utain** [angular/angular-cli#8920] opened 2017-12-18 08:44 UTC
### Versions
```
Your global Angular CLI version (1.6.1) is greater than your local
version (1.6.0). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
_                      _                 ____ _     ___
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
/ △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
|___/

Angular CLI: 1.6.0
Node: 8.6.0
OS: darwin x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0

```

### Repro steps

* Step 1: Run command ``yarn start`` => ``ng serve``.
* Step 2: Focus on Terminal and ``ctrl + z``.
* Step 3: Run command ``yarn start``=>``ng serve`` again.

### Observed behavior
```
Output Step 1:
yarn run v1.3.2
$ ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-12-18T08:34:32.119Z
Hash: d35c5613a39d31085c98
Time: 6469ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 31.1 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 552 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 33.9 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 7.94 MB [initial] [rendered]

webpack: Compiled successfully.
========================
Output Step 3:
yarn run v1.3.2
$ ng serve
Port 4200 is already in use. Use '--port' to specify a different port.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Desired behavior
Should be don't allow to use ``ctrl + z`` or close ``ng`` process.

**Comment by hansl** [comment] 2017-12-18 21:56
`ctrl + z` put the process in the background. You're looking for `ctrl + c`, which kills the process.

Closing this as working as intended.

**Closed by hansl** 2017-12-18 21:56 UTC
