### ISSUE TITLE
Creating libraries: issue with destination path and unit tests

### ISSUE THREAD

**Issue by ramandeep-singh-1983** [angular/angular-cli#11374] opened 2018-06-26 09:56 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x ] devkit
- [ ] schematics
```

### Versions
> node --version
v8.11.1
> npm --version
6.0.0

OS: Windows 10

### Repro steps
1) Create a new library: `ng generate library my-lib`
2) Build the library in development (ng build my-lib) and production (ng build --prod my-lib) mode. Both builds will work fine.
3) In the library source, there are 2 ng-package.json files:
projects/my-lib/src/ng-package.json: dev
projects/my-lib/src/ng-package.prod.json: production.

The "dest" path variable is different in both files:

> ng-package.json: "dest": "../../dist/**my-lib**",
> ng-package.prod.json: "dest": "../../dist/**lib**"

So, the library is copied to different destination folders based on the build type: dev/prod
4) tsconfig.json contents:
```
"paths": {
      "my-lib": ["dist/my-lib"]
 }
```

5) Run the unit tests
`ng test --watch=false --code-coverage --browsers=ChromeHeadless my-app`

**Succeeds** if 'my-lib' was built in development mode (ng build my-lib) as the built library is copied to dist/my-lib and tsconfig.json 'paths' variable points to this location.

**Fails** if 'my-lib' was built in production mode (ng build --prod my-lib) as the built library is copied to dist/lib and tsconfig.json 'paths' variable points to this dist/my-lib.
 
### The log given by the failure
Module not found: Error: Can't resolve 'my-lib' in 'D:\Work\git_repos\my-app\src\app\modules\reporting' 
@ ./src/app/modules/reporting/reporting.module.ts 1:7377-7399
 @ ./src/app/shared/unit-tests/unit-tests.module.ts
 @ ./src/app/app.component.spec.ts
 @ ./src sync \.spec\.ts$
 @ ./src/test.ts

### Desired functionality
One of the following functionalities is desired:
1) 'ng generate library my-lib' generates same "dest" path for development and production builds. Maybe:
"dest": "../../dist/my-lib" as "dist/lib" can contain multiple libraries.
2) tsconfig.ts: possible to add more than 1 search path, the official tsconfig documentation (https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) says it's possible but it doesn't work in this case for me:

```
"paths": {
      "my-lib": ["dist/my-lib", "dist/lib"]
 }
```

For now, i have followed the 1st solution i.e. manually specified same "dest" path in both files.

**Comment by alan-agius4** [comment] 2018-06-26 15:18
Duplicate of: https://github.com/angular/angular-cli/issues/11251?

**Comment by Brocco** [comment] 2018-06-26 15:40
Confirmed...

Duplicate of #11251 

closing

**Closed by Brocco** 2018-06-26 15:40 UTC
