### ISSUE TITLE
AOT template error only displayed on initial build

### ISSUE THREAD

**Issue by bmayen** [angular/angular-cli#8283] opened 2017-11-02 02:40 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

1.5.0

### Repro steps.

1) Create a component with a template which attempts to call a private method
2) `ng serve --aot`
3) Note that an error is thrown, like "Property 'formSubmit' is private and only accessible within class 'FormComponent'"
4) Kill the build task
5) Fix error by making method public and run `ng serve --aot` again
6) After successful build, reintroduce the error by making the method private again and save to trigger incremental build
7) Note that no error is thrown

### Desired functionality.

Should throw errors for templates in incremental AOT builds

**Comment by filipesilva** [comment] 2017-11-02 13:59
Sounds like a bug alright. Thanks for the report, will investigate 👍

**Comment by smasala** [comment] 2018-10-15 12:19
Yes, I can confirm this. The initial build fails to compile due to errors but then a simple `save` causes a rebuild with successful compilation and no more errors to be thrown. I seem to be unable to reproduce this in a separate project so far.

**Comment by smasala** [comment] 2018-10-15 13:39
@filipesilva in our application it was the result of an explicit include in the `tsconfig`.

```json
include:["**/*.ts", "libs/mysuperlib/index.ts"]
```

Change to:

```json
include:["**/*.ts", "libs/mysuperlib/*"]
```

**Comment by mgechev** [comment] 2018-12-22 02:40
@filipesilva do we want to look at this or it behaves as expected?

**Comment by filipesilva** [comment] 2018-12-22 11:07
From the description it's not behaving as expected, but I haven't had time to investigate further. I get the impression it's not a frequent problem though.

**Comment by smasala** [comment] 2018-12-22 11:10
It seems to be quite heavily dependent on project complexity although I've struggled to reproduce the problem to a single source

**Comment by mgechev** [comment] 2019-08-19 20:21
Looks like a problem with old version of the CLI. Let us close the issue for now. If it's still relevant, please open a new ticket with steps to reproduce and a minimal demo. Thanks!

**Closed by mgechev** 2019-08-19 20:21 UTC
Labels: comp: ngtools/webpack, freq1: low, severity2: inconvenient, type: bug/fix
