### ISSUE TITLE
updating 10.0.8 to 10.1.3

### ISSUE THREAD

**Issue by DuncanFaulkner** [angular/angular-cli#18877] opened 2020-09-24 21:21 UTC
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I think this is a new issue, as the tsconfig.base.json didn't exist prior.

### Description

 A clear and concise description of the problem...
updating from 10.0.8 to 10.1.3 the tsconfig.base.json is removed. this file is present in 10.0.8 after creating a new project. 
as the upgrade process completes the following is output:
▸ Removing "Solution Style" TypeScript configuration file support.
DELETE tsconfig.base.json // this is now removed - either this has been dropped in 10.1.3 or deletion is an error.
UPDATE tsconfig.json (458 bytes)
UPDATE tsconfig.app.json (287 bytes)
UPDATE tsconfig.spec.json (333 bytes)
UPDATE e2e/tsconfig.json (294 bytes)
  Migration completed.

## 🔬 Minimal Reproduction

this is after upgrade
Angular CLI: 10.1.3
Node: 14.5.0
OS: linux x64

Angular: 10.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.3
@angular-devkit/build-angular   0.1001.3
@angular-devkit/core            10.1.3
@angular-devkit/schematics      10.1.3
@schematics/angular             10.1.3
@schematics/update              0.1001.3
rxjs                            6.5.5
typescript                      3.9.7

</code></pre>

**Comment by alan-agius4** [comment] 2020-09-24 21:26
Duplicate of https://github.com/angular/angular-cli/issues/18859

**Closed by alan-agius4** 2020-09-24 21:26 UTC
