### ISSUE TITLE
How to install angular-cli locally from a fork on github?

### ISSUE THREAD

**Issue by tsm91** [angular/angular-cli#3840] opened 2017-01-03 20:48 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Linux (ubuntu 1604)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.24
node: 6.9.2
os: linux x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1
@ngtools/webpack: 1.2.1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

The command i am trying to run is: `./node_modules/.bin/ng build --prod`

using a fork: https://github.com/TechTeamer/angular-cli  which is up to date with master and got these small modifications: https://github.com/angular/angular-cli/compare/master...TechTeamer:master

The project originally was created with angular-cli: 1.0.0-beta.24 installed globally. 

This fork functions correct if i do `npm link` steps as stated in the [readme](https://github.com/angular/angular-cli#development-hints-for-hacking-on-angular-cli). The problem is, i am not allowed to install a global package to the production server. That is why i cannot do `npm link`.

What i did is:
  * replaced the npm dependecy like this: `"angular-cli": "github:techteamer/angular-cli",`
  * then also installed `@ngtools/webpack` and `@angular-cli/base-href-webpack` because those dependecies were somehow resolved internally but not in my case and i got errors that these 2 modules are missing
  * then i got an error that led me to this https://github.com/webpack/webpack/issues/3641 issue
  * then i realized https://www.npmjs.com/package/@ngtools/webpack was published 2weeks ago and still uses `"webpack": "^2.1.0-beta.25"` (also saw the unmet dependency during installion)
  * then i updated the project's package.json to reference:
```
"@angular-cli/base-href-webpack": "file:./packages/@angular-cli/base-href-webpack",
"@ngtools/webpack": "file:./packages/@ngtools/webpack"
```
and generated those files with the [build npm script](https://github.com/TechTeamer/angular-cli/blob/master/package.json#L12)
  * this is where i am atm, with the `ERROR in AppModule is not an NgModule` error

### The log given by the failure.
> Normally this include a stack trace and some more information.
```
> ./node_modules/.bin/ng build --prod

Hash: 96a1809b453efc9987ea
Time: 7080ms
chunk    {0} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 246 kB {2} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.map (main) 527 bytes [initial] [rendered]
chunk    {2} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in AppModule is not an NgModule

ERROR in ./frontend/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/workspace/telenet-partner/node_modules/angular-cli/node_modules/typescript/lib/typescript.js:8062:20)

    at Object.createCompilerHost (/workspace/telenet-partner/node_modules/angular-cli/node_modules/typescript/lib/typescript.js:44978:26)

    at Object.ngcLoader (/workspace/telenet-partner/node_modules/angular-cli/packages/@ngtools/webpack/src/loader.ts:192:31)
 @ multi main
```

ping @hansl

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment] 2017-01-03 22:00
ng serve is not intended for production use.  It's strongly advised to use a security hardened server for production scenarios.

**Comment by tsm91** [comment] 2017-01-03 22:05
we are planning to use the build step, updated the command to make it less misleading

get the same error with the build command too

my guess is, some metadata is not being emitted to the compiler

**Comment by clydin** [comment] 2017-01-03 22:24
Generally, if you're using a fork, you're kind of on your own in terms of troubleshooting.
The error you're receiving is usually caused by a mismatch of angular versions.

**Comment by tsm91** [comment] 2017-01-03 22:50
@clydin maybe you are right, but if u check https://github.com/angular/angular-cli/issues/3781 this guy has a very similar error

**Comment by hansl** [comment] 2017-01-04 00:04
Don't install the CLI from a GitHub branch; it wasn't built that way. Instead, clone it locally and link it (`npm link`, then `npm link blah` from your project). Bootstrapping does not work properly if it's inside a `node_modules` itself. Since the file structure for developing is very different than the one on npm, that's to be expected and we use require hacks to make it work properly. Closing this as solved (just follow instructions in the developing guide).

**Closed by hansl** 2017-01-04 00:04 UTC

**Comment by tsm91** [comment] 2017-01-04 08:24
@hansl i am not allowed to install an npm package globally

it is in the issue: "The problem is, i am not allowed to install a global package to the production server. That is why i cannot do npm link."I cannot do https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory either.

where can i see the require hacks?

**Comment by izoomi** [comment] 2017-03-08 17:31
Any update on this?

**Comment by e-hein** [comment] 2017-05-19 19:45
Had exactly the same problem - solved it. What I did:
1. checkout angular cli in one directory and did a npm install
2. checkout my project (which uses the forked cli) in another directory and did npm install
resulting in a structure like this:
buildfolder
|- customized-angular-cli
\- my-project
3. cd into the my-project folder and launch the build process like this: "../customized-angular-cli/bin/ng build --prod -bh "/my-base-href/"

worked without any npm link :-)
