### ISSUE TITLE
ng build fails when using an absolute path in --output-path

### ISSUE THREAD

**Issue by paulflo150** [angular/angular-cli#26935] opened 2024-01-23 18:14 UTC
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

<17

### Description

Using an absolute path with ng build in --output-path throws an error, the build command appears to append the source folder to the folder provided in the --output-path. Using a relative path on the other hand works.

### Minimal Reproduction

ng build --configuration production --output-path="D:\builds\myapp"

### Exception or Error

```text
An unhandled exception occurred: ENOENT: no such file or directory, mkdir 'D:\Source.App\D:\builds\myapp\browser'
```

### Your Environment

```text
Angular CLI: 17.1.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.1.0
@angular/cdk                    17.0.1
@angular/cli                    17.1.0
@angular/fire                   17.0.0
@angular/material               17.0.1
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by clydin** [comment] 2024-01-23 21:09
Duplicate of #26900

**Comment by paulflo150** [comment] 2024-01-26 13:37
@clydin, this does not appear to be the same issue because I am using 17.1.1 and the problem persists.

`Angular CLI: 17.1.1
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@angular/cdk                    17.1.0
@angular/fire                   17.0.1
@angular/material               17.1.0
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2

PS D:\_E.Learning.Dev.APP> ng build --configuration production --output-path="D:\builds\app"`

`An unhandled exception occurred: ENOENT: no such file or directory, mkdir 'D:\_Source.APP\D:\builds\.app\browser'`

**Closed** 2024-01-26 14:39 UTC
Labels: type: bug/fix, freq1: low, severity3: broken, area: devkit/build-angular, devkit/build-angular:application
