### ISSUE TITLE
Regression: project is not working anymore from 6.0.8 -> 6.1.0 (in lerna monorepos)

### ISSUE THREAD

**Issue by ctaepper** [angular/angular-cli#11685] opened 2018-07-27 08:28 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] all
```

### Repro steps
Our angular/cli project ist located as one package of a larger lerna monorepo. We also make use of yarn workspaces, so all (or most) dependencies are hoisted within one single root node_modules folder. The resulting structure is something like
```
- node_modules <-- angular dependencies installed here
  - @angular
    - cli
    - core
    - ...
- packages
  - angular-app
    - package.json <-- angular dependencies defined here
    - src
    - ....
- package.json <-- no angular dependencies defined here
```

[this line](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/upgrade/version.ts#L48) now (as of 6.1.0) prevents the project from working (at all) because `relativePotential.startsWith('..') === true` because in our structure `relativePotential = ../../node_modules/@angular/core/package.json`

**everything was working fine with 6.0.8**

### The log given by the failure
You seem to not be depending on "@angular/core" and/or "rxjs". This is an error.

### Desired functionality
I can work on my angular project with latest versions of everything

**Comment by hunhavoc** [comment] 2018-07-27 08:56
Same issue here. Working on a workaround, I'll let you know if it's working.

**Comment by jSchez** [comment] 2018-07-27 11:13
Same here. We have tried both Lerna and Rush.js, same result.

**Comment by ctaepper** [comment] 2018-07-30 13:31
maybe there is the need for a setting in `angular.json` to make clear what is considered to "be within the project"

**Comment by cormacrelf** [comment] 2018-08-01 10:32
angular/angular-cli has this issue with links to PRs https://github.com/angular/angular-cli/issues/3864

**Comment by ctaepper** [comment] 2018-08-02 08:01
still broken in `6.1.2`

**Comment by ctaepper** [comment] 2018-08-10 07:15
`6.1.3` 🤷‍♂️

**Comment by alexeagle** [comment] 2018-08-10 16:37
Added to the top of our backlog

**Comment by appsolutegeek** [comment] 2018-08-27 11:57
In the meantime, not ideal, but a quick fix on the lerna.json file to NOT hoist certain dependencies..

```
    "bootstrap": {
      "nohoist": [
        "@angular/*",
        "@angular-devkit/build-angular",
        "rxjs",
        "@ngtools/*"
      ]
    }
```

**Comment by appsolutegeek** [comment] 2018-08-27 13:00
Actually, even this fix above is a nightmare as anything that is used by the UI needs to be set as a NOHOIST ......  So its a lot of packages. Anybody find an alternative fix ?

**Comment by appsolutegeek** [comment] 2018-08-27 13:02
I am using 6.1.5 (installed today).

**Comment by jSchez** [comment] 2018-08-27 13:11
@appsolutegeek try to add your dependencies in the root package.json. Then you will be able to hoist the dependencies within your packages.

**Comment by gombosg** [comment] 2018-08-29 11:01
I'm having the same issue, with only using Yarn workspaces.

**Comment by appsolutegeek** [comment] 2018-08-29 13:36
@gombosg no problem, hopefully, we can update the cli soon, so I can remove the NO HOIST packages.

**Comment by ctaepper** [comment] 2018-09-03 11:14
sadly, the nohoist option is only available for `private` packages
also sadly
>  Added to the top of our backlog

does not seem to mean "this is the very next issue that gets fixed"

**Comment by ctaepper** [comment] 2018-09-07 05:59
`6.2.0`, `7.0.0` 😔

**Comment by fabianbru** [comment] 2018-09-11 07:16
Is there any update when the issue will be fixed?

**Closed** 2018-09-26 12:53 UTC
Labels: comp: schematics/update, freq2: medium, jira-sync, severity3: broken, type: bug/fix

**Comment by ctaepper** [comment] 2018-09-26 13:56
@hansl 👍

**Comment by ctaepper** [comment] 2018-10-02 11:19
wait a minute, why did this not land in `6.2.4` ???

**Comment by ptitjes** [comment] 2018-10-06 14:05
@ctaepper It seems that it went in `7.0.0-rc`. Updating only `@angular/cli` worked for me.

**Comment by ptitjes** [comment] 2018-10-11 10:15
@alexeagle, @hansl, could we also have the fix on `6.2.x` please? Moving to `7.0.0-rc*` creates other problems with dependencies that are not ready for `7.0`...

**Comment by johanchouquet** [comment] 2019-07-16 08:49
Hi there, anyone tested monorepo approach with Firebase Cloud Functions ?

The idea: multiple apps for multiple Firebase targets, hosted via Firebase hosting. Each target would be a subdomain. I manage to do that.

But I'm struggling with Firebase Cloud Functions setup to be OK in the monorepo. It just doesn't work for now. Do you have best practices to share ?

**Comment by thefliik** [comment] 2019-07-16 08:58
@johanchouquet I have an angular monorepo with multiple firebase projects in it, including a firebase functions project. I can confirm it works fine.

**Comment by johanchouquet** [comment] 2019-07-16 09:48
@thefliik , I'm so glad to hear that it can work.

Then, i have this structure. I created 3 apps with the CLI. So my project structure is:
```
| projects
  | admin
  | app
  | website
package.json
| node_modules
| functions
  | packages.json
  | node_modules
.firebaserc
firebase.json
```
Everything is standard there. When I do `firebase deploy --only functions`, it fails when executing the `tsc` task.
I've this stacktrace:
```
node_modules/@google-cloud/common/node_modules/gaxios/build/src/index.d.ts(14,66): error TS1005: '>' expected.
node_modules/@google-cloud/common/node_modules/gaxios/build/src/index.d.ts(14,103): error TS1109: Expression expected.
node_modules/firebase-functions/lib/function-builder.d.ts(58,93): error TS1005: ';' expected.
node_modules/firebase-functions/lib/function-builder.d.ts(58,94): error TS1003: Identifier expected.
node_modules/firebase-functions/lib/function-builder.d.ts(58,114): error TS1005: ';' expected.
node_modules/firebase-functions/lib/function-builder.d.ts(63,88): error TS1005: ';' expected.
node_modules/firebase-functions/lib/function-builder.d.ts(63,89): error TS1003: Identifier expected.
node_modules/firebase-functions/lib/function-builder.d.ts(63,109): error TS1005: ';' expected.
node_modules/firebase-functions/lib/function-builder.d.ts(63,110): error TS1131: Property or signature expected.
node_modules/firebase-functions/lib/function-builder.d.ts(63,127): error TS1005: ';' expected.
node_modules/firebase-functions/lib/function-builder.d.ts(63,184): error TS1109: Expression expected.
node_modules/firebase-functions/lib/function-builder.d.ts(63,229): error TS1005: '(' expected.
node_modules/firebase-functions/lib/function-builder.d.ts(64,5): error TS1128: Declaration or statement expected.
node_modules/firebase-functions/lib/function-builder.d.ts(65,5): error TS1128: Declaration or statement expected.
node_modules/firebase-functions/lib/function-builder.d.ts(99,5): error TS1128: Declaration or statement expected.
node_modules/firebase-functions/lib/function-builder.d.ts(117,5): error TS1128: Declaration or statement expected.
node_modules/firebase-functions/lib/function-builder.d.ts(124,5): error TS1128: Declaration or statement expected.
node_modules/firebase-functions/lib/function-builder.d.ts(131,5): error TS1128: Declaration or statement expected.
node_modules/firebase-functions/lib/function-builder.d.ts(138,146): error TS1005: '(' expected.
node_modules/firebase-functions/lib/function-builder.d.ts(140,5): error TS1128: Declaration or statement expected.
node_modules/firebase-functions/lib/function-builder.d.ts(153,5): error TS1128: Declaration or statement expected.
node_modules/firebase-functions/lib/function-builder.d.ts(162,5): error TS1128: Declaration or statement expected.
node_modules/firebase-functions/lib/function-builder.d.ts(168,1): error TS1128: Declaration or statement expected.
node_modules/firebase-functions/lib/function-configuration.d.ts(4,64): error TS1005: ']' expected.
node_modules/firebase-functions/lib/function-configuration.d.ts(4,66): error TS1134: Variable declaration expected.
node_modules/firebase-functions/lib/function-configuration.d.ts(4,153): error TS1005: ';' expected.
node_modules/firebase-functions/lib/function-configuration.d.ts(16,61): error TS1005: ']' expected.
node_modules/firebase-functions/lib/function-configuration.d.ts(16,63): error TS1134: Variable declaration expected.
node_modules/firebase-functions/lib/function-configuration.d.ts(16,93): error TS1005: ';' expected.
```

I'm not sure if i don't something wrong or anything. I'm using the latest dependencies in the `functions/package.json`, as follow:
```
"dependencies": {
    "firebase-admin": "~8.2.0",
    "firebase-functions": "^3.1.0"
  }
```

So, did you configure something to make Firebase Cloud Functions work fine in the monorepo ?

**Comment by thefliik** [comment] 2019-07-16 12:55
@johanchouquet it's been a while since I set it up, so I can't remember if I encountered any issues in the beginning.

My folder structure is like so

```
> apps
  > app_one_name
    > app
    > e2e
    package.json
  > functions
    > src
    > tasks
    package.json
    tsconfig.json
    // ...
  > // ...
> libs
  > lib_one
  > lib_two
  > // ...
.firebaserc
angular.json
firebase.json
package.json
tsconfig.json
// ...
```

It's set up using yarn with [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/). The workspace's `package.json` includes:

```json
{
  "workspaces": {
    "packages": [
      "apps/*",
      "libs/*"
    ]
  }
}
```

The only other thing of note is that the `firebase.json` file needs to specify the location of the functions source directory:

```json
{
  "functions": {
    "source": "apps/functions"
  }
}
```

This all being said, your error message looks like it's coming from a syntax error in a typings file. Have you examined the file causing the error? Looks like it could be caused by an incorrect typescript version? Or perhaps the typings for dependencies are clashing in some way.
 
_🤔 💭 It's times like these I wish github had some sort of direct messaging system, to avoid cluttering issues._

**Comment by johanchouquet** [comment] 2019-07-16 13:06
Thanks @thefliik.

> 🤔 💭 It's times like these I wish github had some sort of direct messaging system, to avoid cluttering issues.
So true ^^!

> This all being said, your error message looks like it's coming from a syntax error in a typings file. Have you examined the file causing the error? Looks like it could be caused by an incorrect typescript version. Or perhaps the typings for dependencies are clashing in some way.
I'm looking into this right now.

I've created my workspace using Angular Console. So I didn't expect that there would be issues in typescript versions or else. Maybe this is not related, but just saying. BTW, AngularConsole is really amazing.

I'll look into yarn workspaces. Seems to be simpler to deal with Cloud Functions.

**Comment by thefliik** [comment] 2019-07-16 14:10
@johanchouquet sometimes typescript version errors can be hidden by vscode. VSCode, so long as it is kept updated, seems to always use the latest typescript version for intellisense. If your project has an older version of typescript installed, this means that vscode may not show you errors if you accidentally use a typescript feature that is newer than the typescript version your project is using (or if you depend on a library which, in turn, depends on a newer typescript version than you are using).

For example, a firebase functions project of mine was using typescript ~3.2. But I accidentally pulled in a library which made use of the new `readonly Array<T>` and `as const` syntax introduced in typescript 3.4. The error showed up as a strange syntax error at compile time. VSCode understood the syntax (because it was using typescript 3.5 to power intellisense), but the version of typescript using during compilation did not. The version of typescript used during compilation didn't even know how to define the error really. It said something like "variable declaration expected" or "unexpected `[`".

**Comment by johanchouquet** [comment] 2019-07-16 14:51
@thefliik , indeed, my tsc version was 3.1.6 in VS Code terminal ! I managed to change it to the same version used in my projects (v3.4.5). But nothing changed: i still have those errors... Very strange behavior.
