### ISSUE TITLE
@angular-devkit/build-angular 0.801.0 script import problems

### ISSUE THREAD

**Issue by julianpoemp** [angular/angular-cli#14981] opened 2019-07-03 08:50 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, because it works with 

- @angular/cli 8.0.6 and @angular-devkit/build-angular@0.800.6
- @angular/cli@8.1.0 and @angular-devkit/build-angular@0.800.6

### Description

After upgrade to @angular/cli@8.1.0 I noticed, that the version of @angular-devkit/build-angular is still 0.800.6 instead of 0.801.0 like in new projects created with ``ng new``. That's why I updated it manually and did an ``ng serve``. The command itself didn't fail but in the browser I get a message about various scripts failing like popper.js, bootstrap-material-design.js and ajv.js. It has definitively nothing to do with that scripts because it has worked before.

## 🔬 Minimal Reproduction

1. Create a new project using ``ng new`` with default settings  (angular/cli@8.1.0 must be globally installed).
2. Install popper.js and jquery: `` npm install --save popper.js`` and ``npm install --save jquery``
3. Include jquery and popper.js to the list of scrips in angular.json: 

       "node_modules⁩/jquery⁩/jquery.min.js⁩",
       "node_modules/popper.js/dist/umd/popper.js"
4. Run ``npm start``
5. Open ``http://localhost:4200`` and the web console.

## 🔥 Exception or Error

Web console:
<pre><code>popper.js:28 Uncaught TypeError: Cannot set property 'Popper' of undefined
    at popper.js:28
    at popper.js:29
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.1.0
Node: 12.5.0
OS: darwin x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**

It works with @angular-devkit/build-angular@8.00.6

**Comment by alan-agius4** [comment] 2019-07-03 09:21
Related and can be consider as a duplicate of https://github.com/angular/angular-cli/issues/14952

**Closed by alan-agius4** 2019-07-03 09:21 UTC

**Comment by sysmat** [comment] 2019-07-09 13:05
Again angular 8.1 broke app with bootstrap with  "@angular-devkit/build-angular": "~0.801.0",

**Comment by viethoanganh79** [comment] 2019-07-30 02:30
how to fix it!?

**Comment by julianpoemp** [comment] 2019-07-30 09:53
> how to fix it!?

I updated angular-devkit/build angular to 0.801.2 and it seems fixed:

    npm install --save-dev @angular-devkit/build-angular@0.801.2
