### ISSUE TITLE
Installation Fail (Failed at the node-sass@4.5.0 install script 'node scripts/install.js'.)

### ISSUE THREAD

**Issue by RuSTer1241** [angular/angular-cli#4445] opened 2017-02-06 06:20 UTC
**Installation Fail (Failed at the node-sass@4.5.0 install script 'node scripts/install.js'.)**
**Attach:**
[npm-debug.log.tar.gz](https://github.com/angular/angular-cli/files/753757/npm-debug.log.tar.gz)

**Info**
istributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
npm ERR! node v6.9.1
npm ERR! npm v3.10.9

**Ubuntu terminal log:**
developer@image-4963-l:~/Projects/angular-quickstart/angular_tutor/codelyzer_demo$ sudo npm install -g @angular/cli
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng

node-sass@4.5.0 install /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass
node scripts/install.js
module.js:471
throw err;
^

Error: Cannot find module '/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:509:3
/usr/local/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@angular/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.
npm ERR! Linux 3.13.0-88-generic
npm ERR! argv "/opt/node/bin/node" "/usr/local/bin/npm" "install" "-g" "@angular/cli"
npm ERR! node v6.9.1
npm ERR! npm v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.0 install: node scripts/install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/developer/Projects/angular-quickstart/angular_tutor/codelyzer_demo/npm-debug.log
npm ERR! code 1
developer@image-4963-l:~/Projects/angular-quickstart/angular_tutor/codelyzer_demo$ ll
total 704
drwxrwx--- 3 developer developer 4096 лют 3 19:07 ./
drwxrwx--- 7 developer developer 4096 лют 3 18:00 ../
drwxrwx--- 9 developer developer 4096 лют 3 18:38 angular-seed/
-rw-r----- 1 root root 705557 лют 3 19:07 npm-debug.log

**Comment by catull** [comment] 2017-02-06 21:37
This is a duplicate of #4429.

**Comment by M-Abozaid** [comment] 2017-02-06 23:43
same here
I tried `npm rebuild node-sass` but it didn't  fix it

**Comment by imjustd** [comment] 2017-02-08 11:22
Same with me on Linux after I updated node to version 6.9.5 with `nvm` node version manager.

**Comment by oolongtea** [comment] 2017-02-25 22:06
Same error. `npm rebuild node-sass` didn't fix for me either.

```
node: v6.9.5
npm:  v3.10.10

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
$ uname -a
Linux machine 4.9.0-040900-generic #201612111631 SMP Sun Dec 11 21:33:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by filipesilva** [comment] 2017-03-09 11:34
Dupe of https://github.com/angular/angular-cli/issues/4429

**Closed by filipesilva** 2017-03-09 11:34 UTC
