### ISSUE TITLE
Vendor sourcemaps are not available in build-angular@0.12.1

### ISSUE THREAD

**Issue by Tallyb** [angular/angular-cli#13449] opened 2019-01-16 17:06 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ X ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node v10.14.1
npm 6.5.0

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.1
@angular-devkit/build-angular      0.12.1
@angular-devkit/build-ng-packagr   0.12.1
@angular-devkit/build-optimizer    0.12.1
@angular-devkit/build-webpack      0.12.1
@angular-devkit/core               7.2.1
@angular-devkit/schematics         7.2.1
@angular/cli                       7.2.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.2.1
@schematics/angular                7.2.1
@schematics/update                 0.12.1
ng-packagr                         4.5.0
rxjs                               6.3.3
typescript                         3.2.2
webpack                            4.23.1

### Repro steps

Desired functionality: have sourcemaps...

**Comment by alan-agius4** [comment] 2019-01-16 17:43
Duplicate of https://github.com/angular/angular-cli/issues/13414

Will be solved in the next patch version

**Closed by alan-agius4** 2019-01-16 17:43 UTC
