### ISSUE TITLE
In mac, `ng new project-name` creates project in root directory rather in the directory I am in.

### ISSUE THREAD

**Issue by aniruddhadas9** [angular/angular-cli#5483] opened 2017-03-17 18:35 UTC
### Bug Report or Feature Request (mark with an `x`)

- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.

@angular/cli: 1.0.0-rc.2
node: 6.9.1
os: darwin x64

### Repro steps.

I am in /xyx/abc folder and run ng new appname, cli should create a folder named /xyz/abc/appname and put all the code in ther but it created a folder in root directory and put all code there

* below are the command I ran*
```
CDE34RDHGY23FFG:ng2cli user23$ pwd
/Users/user23/aniruddh/develop/ng2cli
CDE34RDHGY23FFG:ng2cli user23$ ng new mar18 --ng4 --style scss --routing true
installing ng
create .editorconfig
...

CDE34RDHGY23FFG:ng2cli user23$ pwd
/Users/user23/aniruddh/develop/ng2cli
CDE34RDHGY23FFG:ng2cli user23$ ls
feb19                   feb24                   feb25                   feb26                   feb3                    jan30                   mar3ng4withrouter       mar7
CDE34RDHGY23FFG:ng2cli user23$
02NM7DYG3QD:ng2cli user23$ pwd
/Users/user23/aniruddh/develop/ng2cli
CDE34RDHGY23FFG:ng2cli user23$ ls
feb19                   feb24                   feb25                   feb26                   feb3                    jan30                   mar3ng4withrouter       mar7
CDE34RDHGY23FFG:ng2cli user23$ cd ../..
CDE34RDHGY23FFG:aniruddh user23$ ls
backup                  gitexp                  installed-software      mar18                   package.json            run.sh                  test
develop                 helpers                 mar17                   npm-debug.log           run.bat                 sauce-config
CDE34RDHGY23FFG:aniruddh user23$

```

### The log given by the failure.

It did not failed but the folder is created in different folder expected

### Desired functionality.

The new project folder should created in the same folder

**Comment by filipesilva** [comment] 2017-03-18 15:26
Dupe of https://github.com/angular/angular-cli/issues/1079, that should have been fixed by https://github.com/angular/angular-cli/pull/4901.

@aniruddhadas9 are you *absolutely sure* you're using a globally installed rc.2? Can you reinstall to make sure?

**Comment by aniruddhadas9** [comment] 2017-03-18 19:21
@filipesilva Yes. I tried with both @angular/cli rc.1 and rc.2 and both have same result. I posted command here.

**Comment by filipesilva** [comment] 2017-03-18 19:40
Ok, then please check the solutions in #1079 (checking your root dir for a `node_modules` or `package.json` and removing them). Those should help.

**Comment by aniruddhadas9** [comment] 2017-03-18 21:13
Sure, Let me check that.

**Comment by aniruddhadas9** [comment] 2017-03-21 17:52
removing package.json file from the root folder worked for me. would I close this issue or there is a permanent fix coming?

**Comment by filipesilva** [comment] 2017-03-24 17:52
Let's keep it open. This should have been fixed but it seems the fix might not work.

**Comment by saviocamacam** [comment] 2018-01-28 00:37
On windows, the same thing happens.

**Comment by mgechev** [comment] 2018-12-17 19:20
@aniruddhadas9 are you still able to reproduce with the latest Angular CLI?

**Comment by mgechev** [comment] 2018-12-21 22:01
Closing the issue due to inactivity. If the problem still exists in the latest version of the CLI, please open a new issue following the template and providing a minimal demo where we can reproduce it. Thanks! :-)

**Closed by mgechev** 2018-12-21 22:01 UTC
Labels: comp: angular/cli
