### ISSUE TITLE
Angular 5, CLI, not generate source maps (script.bundle.js.map is disappeared)

### ISSUE THREAD

**Issue by Windman** [angular/angular-cli#8662] opened 2017-11-28 14:40 UTC
Angular CLI: 1.5.4
Node: 8.9.1
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.1
@angular/cli: 1.5.4
@angular/material: 5.0.0-rc.1
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1
Windows 10

**package.json:**
` 
{
  "name": "app",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve -dev",
    "start:aot": "ng serve --aot",
    "build": "ng build --env=prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~5.0.0",
    "@angular/cdk": "5.0.0-rc.1",
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/material": "5.0.0-rc.1",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/router": "~5.0.0",
    "angular2-datatable": "^0.6.0",
    "angular2-virtual-scroll": "^0.3.1",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "ngx-infinite-scroll": "^0.5.2",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "~1.5.0",
    "@angular/compiler-cli": "~5.0.0",
    "@types/jasmine": "^2.5.38",
    "@types/node": "~6.0.45",
    "css-loader": "^0.28.7",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lodash": "^4.17.4",
    "node-sass": "^4.7.2",
    "postcss-loader": "^2.0.9",
    "protractor": "~5.1.0",
    "source-map-loader": "^0.2.3",
    "ts-node": "^3.3.0",
    "typescript": "2.4.2"
  }
} 
`

**tsconfig.json**
`{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "exclude": [
    "node_modules"
  ]
}`

Steps to reproduce:
npm install
npm start

### Observed behavior
'npm start' produced:
Date: 2017-11-28T14:35:30.853Z
Hash: c78ef87868bb5f2ceff2
Time: 18443ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.52 MB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 605 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 176 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 21.3 MB [initial] [rendered]

5 files total instead of 6 files

### Desired behavior
There is no script.bundle.js.map file. So it is impossible to debug *.ts files.

**Comment by lidoma** [comment] 2017-11-28 16:30
Same issue here.

**Comment by filipesilva** [comment] 2017-11-30 10:32
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #8524. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-11-30 10:32 UTC

**Comment by kodaliasha** [comment] 2018-03-08 01:00
try following command to generate source maps 

`ng build --prod --sm
`

`Angular CLI: 1.7.2
Node: 9.7.1
OS: darwin x64
Angular: 5.2.7`


To get list of available compiler arguments run following command
ng help build
