### ISSUE TITLE
Run cli on browser (define a cutom Host and not NodeJsSyncHost)

### ISSUE THREAD

**Issue by GrandSchtroumpf** [angular/angular-cli#11549] opened 2018-07-13 20:08 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [*] feature request
```
Being able to run a "NewCommand" script from the browser with a custom virtual FS.

### Area
```
- [*] devkit
- [*] schematics
```

### Versions
`node v8.9.0`
`node 6.1.0`
Windows10

### Repro steps
In an Angular project 
```
import NewCommand from '@angular/cli/commands/new';
...
const cmd = new NewCommand({
   project: {
     root: '.'
   }
}, createConsoleLogger());
```
Then run `ng serve`

### The log given by the failure
```
Module not found: Error: Can't resolve 'child_process' in ...
Module not found: Error: Can't resolve 'fs' in ...
Module not found: Error: Can't resolve 'http' in ...
Module not found: Error: Can't resolve 'os' in ...
Module not found: Error: Can't resolve 'path' in ...
Module not found: Error: Can't resolve 'stream' in ...
....
```

### Desired functionality
I would like to be able to run `@angular/cli` commands from an Angular app to build a visual dashboard in order to create and manage angular app from the browser.

### Mention any other details that might be useful
I think the problem comes from this [line ](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/models/schematic-command.ts#L50).
Maybe we should be able to specify a custom virtualFS.Host instead ?

I also tried to change the webpack config for node of course, but it didn't help much.
Thanks for your amazing work !

**Comment by ajspera** [comment] 2018-07-13 21:10
ng-cli has many dependencies that are not compatible with browsers, and never will be due to the nature of web security concerns. The way to accomplish this would not be putting that in an angular project, but putting them on a node webserver with an http api that the browser can interact with.

**Comment by GrandSchtroumpf** [comment] 2018-07-13 21:23
Hmmm, it doesn't seems right to me. Much of the CLI project doesn't rely on modules incompatible with the browser. We can build custom Host and Workspace with VirtualFS and the loggerApi doesn't use node. 
Actually I don't see why the `NodeJsSyncHost` is hardcoded in the `SchematicCommand`... It could be replace by a custom VirtualFS based Host.

**Comment by ajspera** [comment] 2018-07-13 22:05
All of the missing modules in your log are not browser compatible, they are specific to node. They are also widely used by the cli's dependancies and not just the cli itself. To illustrate my point, run in an angular project.
``` bash
grep -r "require('fs')" node_modules/
```
Repeat for the rest of those missing modules. I wouldn't be surprised if there are over 1000 instances of usage between those packages within dependencies in an ng new project.

You would be better off trying to shim in a virtual node environment to the browser or taking my first suggestion depending on your specific use case. An interesting problem, but I doubt any of that is within the scope of the angular-cli project considering it is a cli written for node and not a gui written for a browser.

**Comment by GrandSchtroumpf** [comment] 2018-07-13 22:30
I understand your point, and I saw how much `fs` was used in the cli. But the only process of running commands and building schematics doesn't need much of non-browser modules. Actually I find only one class that needs node. This is `NodeJsSyncHost` and it can totally be replace with a browser compatible version of it. I think it should be a parameter of type `virtualFs.Host` and not hardcoded in the `SchematicCommand` class.
I don't say we should make the whole cli browser based. But for many services such as stackblitz, codesandbox, GUI, ... making the process of running schematics browser-friendly would be a boost.

I tried to shim a virtual node environment to the browser but could make it works either. Still I'll try to work with a server, but it means a lot more security than only dealing locally with the browser.
Thank for the idea.

**Comment by hansl** [comment] 2018-07-17 14:24
Hi @GrandSchtroumpf ,

The CLI was never meant to be used in a browser environment, by design. Instead, we're suggesting people who, like you, want to run CLI-like interface inside a different environment, to simply reuse the DevKit parts.

There was a plan a few months ago to implement all the missing part for running Schematics in a browser. This was never finished but shouldn't be much work; you need to implement your own Schematic EngineHost and you probably want to implement a BrowserWorkflow (that's not necessary but it limits the Schematics you can run who might require a workflow).

If you want to collaborate that'd be great. Otherwise this will happen eventually (hopefully before 7) as Schematics-in-a-browser is something I want for another project.

I'll keep this issue open for the discussion, but this is never going to be fixed as is (running CLI itself in the browser).

**Comment by GrandSchtroumpf** [comment] 2018-07-17 16:46
Hi @hansl , sure I would love to contribute ! Please tell me how =)

**Comment by GrandSchtroumpf** [comment] 2018-07-22 17:43
Hi @hansl, do you have a repo or something for Schematics-in-a-browser, so I can help with that?

**Comment by alan-agius4** [comment] 2021-07-28 11:29
Closing since running the CLI in the browser is no longer in scope.

**Closed by alan-agius4** 2021-07-28 11:29 UTC
Labels: comp: angular/cli, type: RFC / discussion / question
