### ISSUE TITLE
ng build --prod results in that the running app report "TypeError: Assignment to constant variable" with target:es2015

### ISSUE THREAD

**Issue by zijianhuang** [angular/angular-cli#9495] opened 2018-02-02 23:17 UTC
### Versions
```
Angular CLI: 1.6.7
Node: 8.9.4
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0
```

The tsconfig.json defined `target:es2015`

package.json:

```
  "dependencies": {
    "@angular/animations": "^5.2.2",
    "@angular/common": "^5.2.2",
    "@angular/compiler": "^5.2.2",
    "@angular/core": "^5.2.2",
    "@angular/forms": "^5.2.2",
    "@angular/platform-browser": "^5.2.2",
    "@angular/platform-browser-dynamic": "^5.2.2",
    "@angular/router": "^5.2.2",
    "concurrently": "^3.5.1",
    "core-js": "^2.5.3",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.7",
    "@angular/compiler-cli": "^5.2.2",
    "@angular/language-service": "^5.2.2",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.85",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "uglifyjs-webpack-plugin": "^1.1.8",
    "typescript": "^2.6.2"
  }
```

### Repro steps

* Step 1

Find the simple heros demo app at https://github.com/zijianhuang/webapiclientgen, and locate DemoNGCli

or the demo app downloadable in https://angular.io/tutorial/toh-pt6

* Step 2

Go to respective source folder and run ng build --prod

* Step 3

Run the app with IIS, or you may try Apache or other Web server. And use Chrom or alike browse the app.

### Observed behavior

The app will misbehave, with the following console traces when making the first HttpClient call.
`
ERROR TypeError: Assignment to constant variable. at r (main.14d23ee13c3a14c67d46.bundle.js:1) at XMLHttpRequest.a (main.14d23ee13c3a14c67d46.bundle.js:1) at e.invokeTask (polyfills.8e8e9e6cb9f95b7ba9ab.bundle.js:1) at Object.onInvokeTask (main.14d23ee13c3a14c67d46.bundle.js:1) at e.invokeTask (polyfills.8e8e9e6cb9f95b7ba9ab.bundle.js:1) at t.runTask (polyfills.8e8e9e6cb9f95b7ba9ab.bundle.js:1) at t.invokeTask [as invoke] (polyfills.8e8e9e6cb9f95b7ba9ab.bundle.js:1) at _ (polyfills.8e8e9e6cb9f95b7ba9ab.bundle.js:1) at XMLHttpRequest.k (polyfills.8e8e9e6cb9f95b7ba9ab.bundle.js:1)
`

The HttpClient call is actually successful with status 200 returned.

### Desired behavior

Heros display.

### Mention any other details that might be useful (optional)

`ng build --prod --no-aot` will result in similar errors:

`
Uncaught TypeError: Assignment to constant variable. at ih._compileModule (vendor.defd7bfff770299239f9.bundle.js:1) at j.then (vendor.defd7bfff770299239f9.bundle.js:1) at Object.then (vendor.defd7bfff770299239f9.bundle.js:1) at ih._compileModuleAndComponents (vendor.defd7bfff770299239f9.bundle.js:1) at ih.compileModuleAsync (vendor.defd7bfff770299239f9.bundle.js:1) at useClass.compileModuleAsync (vendor.defd7bfff770299239f9.bundle.js:1) at ls.bootstrapModule (vendor.defd7bfff770299239f9.bundle.js:1) at Object.cDNt (main.98d929d5770520d2cd22.bundle.js:1) at o (inline.66056c9a0e270b3547d6.bundle.js:1) at Object.0 (main.98d929d5770520d2cd22.bundle.js:1)
`

`ng build --aot` is fine.

`ng build` is fine.

When the tsconfig.json defined `target:es5`, `ng build --prod` results in correct behavior in runtime.

**Comment by umarov** [comment] 2018-02-03 17:44
I have the same issue. Only way is targeting ES5. I haven't gotten a chance to create a demo client to reproduce this issue. Thanks for making it.

**Comment by snajperek130** [comment] 2018-02-04 10:36
I have the same problem.

**Comment by softsaravanacse** [comment] 2018-02-05 10:03
I too have the same issue.

**Comment by deyung** [comment] 2018-02-06 01:36
Same here.

**Comment by krag-123** [comment] 2018-02-06 05:13
I have the same problem.

**Comment by johan--** [comment] 2018-02-15 07:29
Same issue here, resolved by using es5 as target.

**Comment by rujorgensen** [comment] 2018-02-16 13:28
Same.

**Comment by coryrylan** [comment] 2018-02-18 03:35
Same issue here with https://github.com/coryrylan/ng-pokedex

**Comment by jameskentTX** [comment] 2018-02-18 13:36
I have the same problem, when target is ES2015. But app compiles and works with:

1. "target": "es5" - in tsconfig.json
2. "typescript": "~2.5.3" - in package.json

**Comment by dnemoga** [comment] 2018-02-19 15:06
Same issue :(

**Comment by kennyrulez** [comment] 2018-02-19 16:28
Same Issue
CLI: 1.7.0
Typescript: 2.5.3, 2.6.2, 2.7.1

**Comment by dldavis** [comment] 2018-02-19 16:40
Same Issue

**Comment by citizentim** [comment] 2018-02-20 20:41
Ditto.  Same error after upgrading CLI to 1.7.0.  Switching from es6 to es5 target appears to fix the problem.

**Comment by ouq77** [comment] 2018-02-20 20:53
This is happening with CLI 1.6.8 also, so not sure that it is limited to 1.7.0.

**Comment by zijianhuang** [comment] 2018-02-20 21:32
This issue is stopping es2015 from becoming popular. Currently I have 2 NG2+ projects: project A needs to support IE which dose not support es2015, and project B is LOB which has no need to support IE. The 2nd one should had enjoyed es2015 without polyfill. Project B used to be working well with es2015 with SystemJS. Now with NG Cli I had to reverse back to es5.

**Comment by Vishnu407** [comment] 2018-02-21 10:25
Facing the same issue. This became a showstopper for me. Please suggest a fix for this issue ASAP.

**Comment by Vishnu407** [comment] 2018-02-21 11:00
For me targeting es5 in tsconfig.json rather than es6 solved the issue.
 "target": "es5", in tsconfig.json

**Comment by zijianhuang** [comment] 2018-02-22 07:45
As of CLI 1.7.1 and the Angular 5.2.6, the problem still persists.

**Comment by Marabyte** [comment] 2018-02-26 14:25
I'm seeing this issue with the `HttpClientJsonpModule` when compiling to es2015 with CLI 1.7 and 5.2

**Comment by kdcro101** [comment] 2018-02-27 17:37
Same here: 
`ERROR TypeError: Assignment to constant variable.`

Workaround in my case is was reverting from `HttpClientModule` back to `HttpModule`.
Build succeeds using cli 1.7.1 and `es2015`  target.

I think problem is in `HttpCLientModule`

**Comment by DutchKevv** [comment] 2018-02-27 17:49
Same here, anyone knowns a workaround? thanks

**Comment by citizentim** [comment] 2018-02-28 23:28
Just updated to the newly-released CLI 1.7.2 and Angular 5.2.7.  The problem persists.

**Comment by DutchKevv** [comment] 2018-03-01 23:06
Update to Angular 6.0.0-beta.6 and same problem still there. 

Only solution is to set tsconfig.json -> target: "es5".

Any news on this from @Angular ?? It makes the new httpClientModule a bit useless :(

**Comment by zijianhuang** [comment] 2018-03-02 05:47
According to https://github.com/mishoo/UglifyJS2/issues/2949, the cause is in UglifyJS2 which has a switch to workaround, however, NG CLI is not exposing this switch, while it is using UtlifyJS2. According to the comment by kzc, NG CLI may just provide a switch to fix the problem, or simply use that switch by default for target es2015.

**Comment by zijianhuang** [comment] 2018-03-02 20:22
In https://github.com/angular/angular/issues/21948, Cito had suggested: "Same problem here with Angular-CLI 1.7.2. When I set conditionals: false to const uglifyCompressOptions = { ... } in node_modules/@angular/cli/models/webpack-configs/production.js, as suggested by @trotyl, the problem disappears."

Hopefully Angular CLI team will provide a solution soon.

**Comment by ninjaonsafari** [comment] 2018-03-06 10:22
Can someone of the cli team tell us what the plan is?
If you plan to release a hotfix or if it's on the map for the next release.

> According to mishoo/UglifyJS2#2949, the cause is in UglifyJS2 which has a switch to workaround, however, NG CLI is not exposing this switch, while it is using UtlifyJS2

This would be a quick fix, but would work for me.
The issue is breaking my production site and I cannot change back to `es5` nor switch back to `HttpModule`.

Just mentioning @filipesilva :smirk:

**Comment by citizentim** [comment] 2018-03-06 19:11
As a workaround, I've added this to my build job, after I run **npm install**:

`sed -i'' 's/typeofs: false/typeofs: false, inline: 1/' node_modules/@angular/cli/models/webpack-configs/production.js`

**Comment by tatsujb** [comment] 2018-03-09 15:41
can confirm clydin's merge (and subsequent angular cli v. 1.7.3) fixed it. ...at least for me.

**Comment by clydin** [comment] 2018-03-09 17:24
Closing this as resolved.  If anyone is still encountering issues while using 1.7.3 within a project, please open a new issue detailing the problem.

**Closed by clydin** 2018-03-09 17:24 UTC
Labels: comp: cli/build, freq3: high, severity3: broken, type: bug

**Comment by inamvar** [comment] 2018-03-10 12:32
The problem not resolved yet and still here. This is my environment:

```
Angular CLI: 1.7.3
Node: 8.9.4
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

And this is my `tsconfig.json` file: 
```{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```
