### ISSUE TITLE
Angular 12 ng serve does not update libraries

### ISSUE THREAD

**Issue by arobinson** [angular/angular-cli#21122] opened 2021-06-11 20:16 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, Angular 11.0.5 correctly responded to updates in a symlinked shared library

### Description

 When using `ng serve` and having a shared library symlinked to the application, updates to that application are not brought in and the serve must be quit and restarted for each change. Due to really slow builds with large projects, this is a show stopping bug for us in Angular 12

## 🔬 Minimal Reproduction

In tab/console 1:
```
git clone https://github.com/arobinson/AngularLibraryUpdateIssue
cd AngularLibraryUpdateIssue/ExampleLibraries
npm i
ng b --watch
```

In tab/console 2:
```
cd AngularLibraryUpdateIssue/AngularLibraryUpdateIssue/
npm i
ng s -o
```

Open http://localhost:4200/ in a browser 
Verify page rendered as:
```
Example library:
Library component version 1
```

Open `ExampleLibraries/projects/example-library/src/lib/example-library.component.ts`
Change `versionNumber` from `1` to `2`:
```
export class ExampleLibraryComponent implements OnInit {
  versionNumber = 2
```

See that the library is rebuilt
See that `ng serve` refreshes the page
But the version number is still 1, the new changes were not included in the updated Javascript

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.0.3
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.3 (cli-only)
@angular-devkit/core         12.0.3 (cli-only)
@angular-devkit/schematics   12.0.3 (cli-only)
@schematics/angular          12.0.3 (cli-only)

</code></pre>

**Anything else relevant?**

**Comment by blitzionian** [comment] 2021-06-13 09:00
Have considered the same problem. My temporary workaround is to set env variable 'export NG_BUILD_CACHE=false'.
In #20962 is already a discussion about this topic, which seems to be the same problem.

**Comment by alan-agius4** [comment] 2021-06-14 08:06
This is expected because `node_modules` are considered immutable in Webpack 5 unless the "version" property changes. If you want to opt-out from this behaviour you need to use `NG_BUILD_CACHE=false` environment variable.

**Comment by alan-agius4** [comment] 2021-06-14 08:06
Duplicate of #20962

**Closed by alan-agius4** 2021-06-14 08:06 UTC
