### ISSUE TITLE
Angular Renders Default Buttons Differently on 6.0.0-RC.4 (Not desired result)

### ISSUE THREAD

**Issue by garysui** [angular/angular-cli#10331] opened 2018-04-14 05:46 UTC
### 6.0.0-RC4
```
Freshly create a new projects: one with 6.0.0-RC4 and another 1.7.4.


Output from: `ng --version`.

Angular CLI: 6.0.0-rc.4
Node: 8.10.0
OS: win32 x64
Angular: 6.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.6
@angular-devkit/build-angular     0.5.6
@angular-devkit/build-optimizer   0.5.6
@angular-devkit/core              0.5.6
@angular-devkit/schematics        0.5.6
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.4
@schematics/angular               0.5.6
@schematics/update                0.5.6
rxjs                              6.0.0-uncanny-rc.7
typescript                        2.7.2
webpack                           4.5.0


  Windows 10

```

### Repro steps

* Freshly create a new 6.0.0-RC4 project
* In index.html:

```
  <app-root></app-root>
  Buttons: Outside Angular 6.0.0-RC.4
  <div>
    <button>Button1</button>
    <button>Butotn2</button>
  </div>
```

* In app.component.html:

```
Buttons: Inside Angular 6.0.0-rc.4
<div>
  <button>Button1</button>
  <button>Butotn2</button>
</div>
```
* ng serve

* Use exactly the same index.html and app.component.html for 1.7.4 CLI.

### Observed behavior
```
On 6.0.0-RC.4, gap between buttons rendered differently
```

### Desired behavior
Render should be the same (without unexpected removal of gap between buttons) regardless of inside or outside of Angular scope. 1.7.4's behavior is desired. Attached both version for comparision.
![bootstrap-button-on-174](https://user-images.githubusercontent.com/8386050/38764918-336ae842-3f86-11e8-8715-93615fadc8b4.png)
![bootstrap-button-on-600rc4](https://user-images.githubusercontent.com/8386050/38764919-3376ec3c-3f86-11e8-9b43-7bd5f307527c.png)

**Comment by cexbrayat** [comment] 2018-04-14 16:53
@garysui This is not related to the CLI but to Angular itself: Angular 6 now have the `preserveWhitespaces` option set to to false by default, and that can break your layout. You can read [here what I written to explain it](http://blog.ninja-squad.com/2017/09/18/what-is-new-angular-4.4/)  when it was introduced on Angular 4.4.

As Angular CLI 6 generates a new project with Angular 6, you have run into this problem, but this is not a CLI issue.

You can set the option to `true` if you want, or you'll need to add a margin in CSS or a simple `&nbsp;` between the buttons.

**Comment by garysui** [comment] 2018-04-14 21:47
Apparently 1.7.4 uses Angular 5.2.0 and it didn't have this behavior. 
I confirm that this option did the trick for Angular 6 @cexbrayat . I wish the team kept this flag unchanged through the course.

**Comment by hansl** [comment] 2018-04-15 03:25
It’s hard to move forward while keeping backward compatibility forever. The Angulat team documented this feature when angular 5 came around, with the intent to have it by default in angular 6. We’ve been pretty transparent about this decision. 

I’m  going to close this issue as working as intended. And I’ll make sure there is a note in the blog post. Thanks!

**Closed by hansl** 2018-04-15 03:25 UTC
