### ISSUE TITLE
Project setup is not starting after Routing and Stylesheet selection

### ISSUE THREAD

**Issue by Arkamit** [angular/angular-cli#22514] opened 2022-01-17 05:48 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Nothing is happening after I've selected the routing as "No" and stylesheet as "CSS". No error is shown in the terminal and even after waiting for more than30 minutes nothing is happening. (Screenshot attached
![Angular Project Setup Error](https://user-images.githubusercontent.com/18526842/149714309-617b48e5-8a2b-4de3-8aae-af67c8e5f906.png)
)

I'm following the steps mentioned in: https://angular.io/guide/setup-local

### Please provide the exception or error you saw

```true
No exception shown on the screen
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.3
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.3 (cli-only)
@angular-devkit/core         13.1.3 (cli-only)
@angular-devkit/schematics   13.1.3 (cli-only)
@schematics/angular          13.1.3 (cli-only)
```

### Anything else?

Please find the Node and NPM versions below.

Node version: v16.13.2

NPM version: 8.1.2

Operating system : Windows 11 Home Single Language
Operating system version : 22000.434

**Comment by alan-agius4** [comment] 2022-01-17 11:37
I am unable to replicate this. 

Can you please share a CPU profile maybe it will help us understand what is happening.

**Comment by Arkamit** [comment] 2022-01-17 17:40
> I am unable to replicate this.
> 
> Can you please share a CPU profile maybe it will help us understand what is happening.

I'm not aware of CPU profiling. If we can have a call, it might be very helpful for me to show you all the steps. Please let me know if it is possible.

**Comment by alan-agius4** [comment] 2022-01-17 18:19
You can use Node.js `—-cpu-proof` to generate a CLU profile.


```
node --cpu-proof node_modules/@angular/cli/lib/init.js new
```

**Comment by Arkamit** [comment] 2022-01-17 19:11
Sorry I'm new to Angular. I tried running the command and I got the below result

node: bad option: --cpu-proof

I might be doing something wrong. It would be great if we can have a call.

**Comment by Arkamit** [comment] 2022-01-18 05:46
@alan-agius4 I'm from India and my email id is arkamitdutta@gmail.com. Please set a call if possible. I think we can resolve it faster in this way. Thanks.

**Comment by alan-agius4** [comment] 2022-01-20 09:24
Reached out via email.

**Comment by alan-agius4** [comment] 2022-01-24 15:08
@Arkamit, I haven't heard back from you.

**Comment by Arkamit** [comment] 2022-01-24 16:35
Hi Alan,

I'm very sorry I couldn't respond to your message as I'm on holiday with
very limited internet connection. Will it be ok with you if we have the
discord meet on Wednesday?

Please let me know your thoughts?

Thanks & Regards,
Arkamit Dutta

**Comment by alan-agius4** [comment] 2022-02-01 07:54
Hi @Arkamit, I’ve tried to reach out on discord a couple of times, but didn’t get a response from you. 

Closing since we are unable to reproduce this issue. 

if you are still experiencing the issue please feel free to open a new issue together with a CPU profile https://github.com/angular/angular-cli/blob/master/packages/angular/cli/README.md

**Closed by alan-agius4** 2022-02-01 07:54 UTC
Labels: need: more info
