### ISSUE TITLE
esbuild builder fails building material scss in 16.2.0 with pnpm

### ISSUE THREAD

**Issue by atsjo** [angular/angular-cli#25662] opened 2023-08-10 08:27 UTC
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.1.8

### Description

esbuild builder fails building material scss in 16.2.0 with pnpm

### Minimal Reproduction

- create minimal project with cli 16.2.0 and esbuild builder using pnpm as package manager
- add @angular/material
- add "@use '@angular/material';" to styles.scss
- build or serve

### Exception or Error

```text
@use "__NG_PACKAGE__;C:/Users/atles/source/repos/teve-no/task4s/node_modules/.pnpm/@angular+material@16.2.0_@angular+animations@16.2.0_@angular+cdk@16.2.0_@angular+common@16.2._bfcglieljnxvxwne53xl6murb4/node_modules/@angular/material/core/typography;@material/typography" as mdc-typography;
  node_modules\.pnpm\@angular+material@16.2.0_@angular+animations@16.2.0_@angular+cdk@16.2.0_@angular+common@16.2._bfcglieljnxvxwne53xl6murb4\node_modules\@angular\material\core\typography\_typography.scss 6:6  @forward
  @angular\_index.scss 12:1                                                                                                                                                                     
                   @use
  apps\devtest\src\styles.scss 4:1                                                                                                                                                              
                   root stylesheet [plugin angular-sass]
```

### Your Environment

```text
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : win32-x64
   pnpm   : 8.6.12

   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/angular        : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/esbuild        : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/webpack        : 16.6.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   angular-calendar : 0.31.0
   ---------------------------------------
   Local workspace plugins:
         @teve/integration
         @teve/firebase
         @teve/angular
         @teve/common
         @teve/task4s-all
         @teve/task4s-web
```

**Comment by JeanMeche** [comment] 2023-08-10 08:28
Dupe of #25662

**Closed by JeanMeche** 2023-08-10 08:28 UTC
