### ISSUE TITLE
Chunks are not getting generated with @ngtools/webpack

### ISSUE THREAD

**Issue by krischandra** [angular/angular-cli#8563] opened 2017-11-21 01:13 UTC
### Versions
```
Angular CLI: 1.5.0
Node: 6.10.1
Angular 5
@ngtools/webpack version: 1.8.2
```
Webpack.common.js
module: { 
rules: [{
    loader: '@ngtools/webpack',
        options: {
          configFileName: 'tsconfig.webpack.json',
        }
}],
plugins: [{
      new AngularCompilerPlugin({
            "sourceMap": true,
            "tsConfigPath":  helpers.root('tsconfig.webpack.json'),
            "skipCodeGeneration": true,
            "compilerOptions": {}
        }),
}]
}
Actual result: Chunks is not getting generated for lazy loaded modules
Expected Result: Should generate chunks

**Comment by KrakenTyP-co** [comment] 2017-11-21 07:33
pls post tsconfig.webpack.json
maybe there is problem

**Comment by krischandra** [comment] 2017-11-21 07:37
{
  "compilerOptions": {
    "outDir": "./compiled",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "baseUrl": ".",
    "paths": {

      "@test/*": [
        "src/test/*"
      ],
      "@styles/*": [
        "src/style-sheets/*"
      ]
    },
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2015",
      "dom"
    ]
  },
  "exclude": [
    "node_modules",
  ],
  "angularCompilerOptions": {
    "genDir": "./compiled",
    "skipMetadataEmit": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}

Do i need to use @angularclass/hmr-loader, ng-router-loader, angular2-template-loader while using @ngtools/webpack. If so what should be the order ?

**Comment by KrakenTyP-co** [comment] 2017-11-21 21:44
tsconfig looks good.
Extra routing template is no needed for new ngtools.

Maybe you have wrong defined routers.

**Comment by EmaGht** [comment] 2017-11-22 15:25
Actually having the same problem here...

webpack configuration:
`var webpack = require("webpack");
var path = require("path");
var clone = require("js.clone");
var merge = require("webpack-merge");
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var ContextReplacementPlugin = require("webpack/lib/ContextReplacementPlugin");
var TsConfigPathsPlugin = require("awesome-typescript-loader").TsConfigPathsPlugin;
var CheckerPlugin = require("awesome-typescript-loader").CheckerPlugin;
var DefinePlugin = require("webpack/lib/DefinePlugin");
var CopyWebpackPlugin = require("copy-webpack-plugin");
var isDevBuild = process.env.ASPNETCORE_ENVIRONMENT === "Production" ? false : true;
var isAotBuild = false;
var AngularCompilerPlugin = require('@ngtools/webpack').AngularCompilerPlugin;

module.exports = (env) => {

  if (env && env.prod)
    isDevBuild = false;

  if (env && env.aot) {
    isAotBuild = true;
    console.log("********************EXPERIMENTAL AOT CONFIGURATION IS ENABLED********************");
  }

  console.log("Webpack entrypoint Main_client Env Development: " + isDevBuild);
  var distDirectory = "./wwwroot/dist";
  var defaultLoaders = ["awesome-typescript-loader?silent=true", "angular2-template-loader", "angular-router-loader"];

  var sharedConfig = {
    resolve: {
      extensions: [".js", ".ts", ".css", ".scss", ".json"]
    },

    stats: { modules: false },
    context: __dirname,

    output: {
      filename: "[name].js",
      publicPath: "/dist/"
    },

    // Here we tell Webpack how to handle Modules
    module: {
      loaders: [
        { test: /\.ts$/, use: isDevBuild ? defaultLoaders : isAotBuild ? '@ngtools/webpack' : defaultLoaders },
        { test: /\.html$/, use: "raw-loader" },
        { test: /\.css/, use: "raw-loader" },
        { test: /\.scss$/, use: ["raw-loader", "sass-loader"] },
        { test: /initial\.scss$/, use: ExtractTextPlugin.extract({ fallback: "style-loader", use: "css-loader!sass-loader?sourceMap" }) },
        { test: /\.json$/, use: "json-loader" },
        { test: /\.woff(2)?(\?v=.+)?$/, use: "url-loader?limit=10000&mimetype=application/font-woff&name=fonts/[name].[ext]" },
        { test: /\.(ttf|eot|svg)(\?v=.+)?$/, use: "file-loader?&name=fonts/[name].[ext]" },
        { test: /bootstrap\/dist\/js\/umd\//, use: "imports?jQuery=jquery" },
        { test: /\.(png|jpg|gif)$/, use: "file-loader?limit=8192&name=assets/img/[name].[ext]" }
      ]
    },

    // Plugins are middleware we can use during webpacks processing cycles to handle other things we want to do
    plugins: [
      new CheckerPlugin(),
      new ExtractTextPlugin({ filename: "initial.css", allChunks: true }),

      new webpack.ProvidePlugin({
        jQuery: "jquery",
        $: "jquery",
        jquery: "jquery",
        'window.jQuery': "jquery",
        Skycons: "skycons/skycons",
        Dropzone: "dropzone",
        moment: "moment"
      }),

      new CopyWebpackPlugin([{
        from: "Client/assets",
        to: "assets"
      }])
    ]
  };

  var clientConfig = setTypeScriptAlias(require("./tsconfig.json"), {

    entry: {
      'main-client': "./Client/bootstrap-client.ts"
    },

    output: {
      path: path.join(__dirname, distDirectory),
      filename: "[name].js",
      publicPath: "/dist/"
    },

    plugins: [
      new DefinePlugin({ 'process.env': { 'development': true } }),
      new ContextReplacementPlugin(
        // The (\\|\/) piece accounts for path separators in *nix and Windows
        /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
        root("./Client")
      ),
      new TsConfigPathsPlugin({ tsconfig: "tsconfig.json" }),
      new webpack.DllReferencePlugin({
        context: __dirname,
        manifest: require("./wwwroot/dist/vendor-manifest.json")
      })

    ].concat(isDevBuild ?
      [
        new webpack.SourceMapDevToolPlugin({ filename: "[file].map", moduleFilenameTemplate: path.relative(distDirectory, "[resourcePath]") })
      ] :
      [
        new webpack.optimize.UglifyJsPlugin()
      ]
      ).concat(isAotBuild ?
        [
          new AngularCompilerPlugin({
            tsConfigPath: './tsconfig.json',
            entryModule: path.join(__dirname, 'Client/app/platform-modules/app.browser.module#AppBrowserModule'),
            exclude: ['./**/*.server.ts']
          })
        ] :
        [])
  });

  // Merge with Shared
  var mergedClientConfig = merge(sharedConfig, clientConfig);

  return [mergedClientConfig];
};

function setTypeScriptAlias(tsConfig, config) {
  var newConfig = clone(config);
  newConfig = newConfig || {};
  newConfig.resolve = newConfig.resolve || {};
  newConfig.resolve.alias = newConfig.resolve.alias || {};
  var tsPaths = tsConfig.compilerOptions.paths;
  for (var prop in tsPaths) {
    newConfig.resolve.alias[prop] = root(tsPaths[prop][0]);
  }
  return newConfig;
}

function root(args) {
  args = Array.prototype.slice.call(arguments, 0);
  return path.join.apply(path, [__dirname].concat(args));
}
`

scripts i use to compile:
` "scripts": {
    "build:dev": "webpack --config webpack.config.vendor.js --progress && webpack --config webpack.config.js --progress",
    "build:prod": "webpack --config webpack.config.vendor.js --progress --env.prod && webpack --config webpack.config.js --env.prod --progress",
    "build:prod:aot": "webpack --config webpack.config.vendor.js --progress --env.prod && webpack --config webpack.config.js --env.prod --env.aot --progress"
  },`

results for :dev are
![builddev](https://user-images.githubusercontent.com/12494403/33134959-66a0b85e-cfa1-11e7-9d86-32ff703bbb3d.PNG)

results for :prod are:
![buildprod](https://user-images.githubusercontent.com/12494403/33134974-740fa1da-cfa1-11e7-865f-ab9854fdc25a.PNG)

results for prod:aot are... 
![buildaot](https://user-images.githubusercontent.com/12494403/33134984-7d04e62e-cfa1-11e7-8fe0-08c77bd3ffc9.PNG)

As you can see it's not generating the modules.
Strange thing is AOT compilation throws no error whatsoever...

**Comment by filipesilva** [comment] 2017-11-24 10:52
There was a similar issue (https://github.com/angular/angular-cli/issues/8597) where the problem was `ContextReplacementPlugin`. If that's not the problem in your case, could you set up a repro that I can clone to see the problem please?

**Comment by EmaGht** [comment] 2017-11-24 12:27
Actually i was following the thread you linked aswell.
In my case, tho, the problem was this:

` new webpack.DllReferencePlugin({
        context: __dirname,
        manifest: require("./wwwroot/dist/vendor-manifest.json")
      })`

I'm not really sure about what it does... i just took it from another template a couple months ago, but that was my deal-breaker.
Thanks for your interest!!

**Comment by filipesilva** [comment] 2017-11-24 12:40
@EmaGht the `@ngtools/webpack` plugin is unfortunately not compatible with the DLLPlugin: https://github.com/angular/angular-cli/issues/4565

**Comment by sjumble** [comment] 2018-02-23 13:05
Hey @EmaGht have you resolved this issue, if Yes then can you please let us know the solutions.

**Comment by EmaGht** [comment] 2018-02-24 00:05
@sjumble I just excluded the DllReference plugin from the plugin chain during aot build, you can see my webpack configuration in my rant about the current state of node's package manager here: https://github.com/yarnpkg/yarn/issues/2088

**Comment by alan-agius4** [comment] 2018-09-18 16:50
Closing as no re-production was provided.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2018-09-18 16:50 UTC
Labels: need: repro steps
