### ISSUE TITLE
Cannot find module './applySourceMap' on ng serve or ng build

### ISSUE THREAD

**Issue by blakeghowe** [angular/angular-cli#16493] opened 2019-12-23 18:06 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Unsure

### Description

If I use ng serve or ng build, I get the following error message:
`An unhandled exception occurred: Cannot find module './applySourceMap'
See "C:\Users\[USER]\AppData\Local\Temp\ng-aEMkei\angular-errors.log" for further details.`

## 🔥 Exception or Error
<pre><code>

[error] Error: Cannot find module './applySourceMap'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\[USER]\source\repos\[PROJECT]\Angular_nstt\node_modules\webpack-sources\lib\SourceMapSource.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
</code></pre>

## 🌍 Your Environment
<pre><code>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@angular/animations               8.1.3
@angular/cdk                      8.1.1
@angular/http                     2.3.0
@angular/material                 8.1.2
@angular/platform-browser         8.1.3
@angular/tsc-wrapped              0.4.2
@ngtools/webpack                  8.3.21
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by sacgrover** [comment] 2019-12-24 15:02
Seems like. You didn't import applySourceMap module into App Module

**Comment by alan-agius4** [comment] 2019-12-27 08:41
Hi @blakeghowe, this might be caused by a package manger hosting issue. I am seeing also a number of package versions which are not aligned. 

Can you update your `@angular/cli` version to `^8.3.21` and try again?

**Comment by philoj** [comment] 2019-12-31 04:51
@alan-agius4  Having same issue here. I updated the cli to 8.3.21, still having the issue
@blakeghowe did you find a solution?

**Comment by alan-agius4** [comment] 2019-12-31 15:15
Can you run `npm ls webpack-sources`?

**Comment by frontend-stunntech** [comment] 2020-01-01 04:46
> Can you run `npm ls webpack-sources`?

Hi @alan-agius4 ,
I get the following
└─┬ @angular-devkit/build-angular@0.803.21
  ├─┬ @angular-devkit/build-optimizer@0.803.21
  │ └── webpack-sources@1.4.3  deduped
  ├─┬ @ngtools/webpack@8.3.21
  │ └── webpack-sources@1.4.3  deduped
  ├─┬ license-webpack-plugin@2.1.2
  │ └── webpack-sources@1.4.3  deduped
  ├─┬ mini-css-extract-plugin@0.8.0
  │ └── webpack-sources@1.4.3  deduped
  ├─┬ terser-webpack-plugin@1.4.3
  │ └── webpack-sources@1.4.3  deduped
  ├─┬ webpack@4.39.2
  │ └── webpack-sources@1.4.3  deduped
  └── webpack-sources@1.4.3

**Comment by clydin** [comment] 2020-01-03 00:43
You may have a corrupted install.  The JavaScript file in question (`applySourceMap.js`) should be located adjacent to the `SourceMapSource.js` mentioned in the stack trace. ([package contents](https://unpkg.com/browse/webpack-sources@1.4.3/lib/))

Can you check whether the file `applySourceMap.js` is present in the `node_modules\webpack-sources\lib\` directory?
Also it may be useful to try deleting the `node_modules` directory and lock file and then re-installing.  If the problem persists, removing the local npm cache prior to the re-install may help (`npm cache clean --force`).

**Comment by frontend-stunntech** [comment] 2020-01-03 04:41
> You may have a corrupted install. The JavaScript file in question (`applySourceMap.js`) should be located adjacent to the `SourceMapSource.js` mentioned in the stack trace. ([package contents](https://unpkg.com/browse/webpack-sources@1.4.3/lib/))
> 
> Can you check whether the file `applySourceMap.js` is present in the `node_modules\webpack-sources\lib\` directory?
> Also it may be useful to try deleting the `node_modules` directory and lock file and then re-installing. If the problem persists, removing the local npm cache prior to the re-install may help (`npm cache clean --force`).

Thanks, @clydin,
 `applySourceMap.js` was missing in the directory `node_modules\webpack-sources\lib\`.
Now its working fine when deleting `node-modules' and lock file and then reinstalling

**Comment by filipesilva** [comment] 2020-01-03 10:43
Glad to hear it's sorted, I'll close the issue then.

**Closed by filipesilva** 2020-01-03 10:43 UTC
Labels: need: more info
