### ISSUE TITLE
ng generate should generate code directly in the sourceRoot

### ISSUE THREAD

**Issue by SchnWalter** [angular/angular-cli#17598] opened 2020-05-01 17:11 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Currently the `ng generate` command doesn't generate the code directly in the `sourceRoot` of the project. Depending on the project type, the code is generated under an `app` or `lib` sub-directory. Because of this, when you want to generate code in the sourceRoot, you need to prefix the name for the schematic with `../`.

For example, if you want to add a `core` sub-package to a library project and expose it under `@example/library/core`, you need to use this command:
```
ng generate module ../core/example-library-core --flat
```
Instead of:
```
ng generate module core/example-library-core --flat
```
which will generate the new `ExampleLibraryCoreModule` under `@example/library/lib/core`, instead of just `@example/library/core`.

The same applies to application projects, where all code is generated under the `app` sub-directory of the sourceRoot and this happens because the generate command uses [`buildDefaultPath()`](https://github.com/angular/angular-cli/blob/v9.1.4/packages/schematics/angular/utility/workspace.ts#L71-L80) to and always adds this extra `projectDirName` directory .

I know that removing the extra directory will break existing example commands, but generating code directly in the `sourceRoot` directory feels more intuitive then generating code in these "arbitrary" directories.

**NOTE:** If your library doesn't use the `lib` directory at all in order to have nice sub-package imports, you still have to provide the `../` prefix for all generate commands.

### Describe the solution you'd like

Remove the extra sub-directories added by `buildDefaultPath()`, but find a way to keep old example commands working, so that in old projects, a command like `ng g m extras` would generate the module in the same location. Maybe a new "defaultDirectory" schematics configuration could be introduced in `angular.json` in order to avoid introducing regressions in existing codebases.

### Describe alternatives you've considered

You can always use `../` to prefix the names of generated code (modules/components/etc...).

---

P.S. Currently there are 2 `buildDefaultPath()` functions that have the same role, one of them is unused, see PR https://github.com/angular/angular-cli/pull/17597 and commit https://github.com/angular/components/commit/d509ff7f26875e0208d4dcbe284846acd713da6e

**Comment by kyliau** [comment] 2020-05-29 22:04
This is a duplicate of https://github.com/angular/angular-cli/issues/16080, please continue the discussion there.

**Closed by kyliau** 2020-05-29 22:04 UTC
Labels: comp: schematics/angular, freq1: low, severity3: broken, triage #1, type: bug/fix
