### ISSUE TITLE
angular-cli@1.0.0-beta.22-1 generates erroneous "Function calls not supported" error. 

### ISSUE THREAD

**Issue by Cogitaria** [angular/angular-cli#3445] opened 2016-12-07 00:56 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Breaks on any and all. 

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

This question exposes the underlying problem.  You don't really know what version you are running.  If you run `ng --version` in the project folder it seeks out the node_modules folder looking for `ng` in the .bin directory, and reports that version. I get the idea but that's a big surprise.  If you run `ng --version` outside the project folder it will report the globally installed `ng` version.  

In my case I had **1.0.0-beta.20-4** globally and **1.0.0-beta-22.1** locally.  Moreover, my package.json asked for **^1.0.0-beta.19-2** (and the ^ is going to result in the latest beta).   

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Yes.  Added some packages that mysteriously started failing to compile on various machines. 

### The log given by the failure.
> Normally this include a stack trace and some more information.

So, the 22-1 angular-cli compile suddenly fails with this error.  Works fine with 20-4. Here is the error (some AOT compile error with one of the 50 odd modules we have). 

**Error** encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a... more noise...
 
### Mention any other details that might be useful.

Main issue is compilation breaking in 22-4 beta with this obscure "Function calls are not supported" (on code that's been working up to now and hasn't changed) but also really not being able to determine quickly what actual version of angular-cli you are running.  

My fix was to remove the ^ from package.json for angular-cli and pin it to a known-good version, until such times as the compiler or the package is fixed. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment] 2016-12-07 01:02
Dupe of https://github.com/angular/angular-cli/issues/3368. See https://github.com/angular/angular-cli/issues/3368#issuecomment-265232700

**Closed by hansl** 2016-12-07 01:02 UTC
