### ISSUE TITLE
Feature Request: load scripts in angular-cli.json conditionally?

### ISSUE THREAD

**Issue by Ismaestro** [angular/angular-cli#4288] opened 2017-01-30 14:26 UTC
As I mention in [this stackoverflow question](http://stackoverflow.com/questions/41741457/angular2-load-script-conditionally-using-angular-cli), I think It would be awesome if we could load scripts depending on the environment.

So In production I want to load a script while in develop not.

The syntax's in angular-cli.json could be:
`{ "input": "script-only-for-dev.js", "environment": "dev" }`

BR

**Comment by LeonLiber** [comment] 2017-02-05 12:02
I'm now loading a "sandbox" script using the "scripts" section in angular-cli.json.
This "sandbox" script must be removed from the production build, any suggestion how to do so in the meantime?

**Comment by galta** [comment] 2017-02-05 12:51
Following... 
having the same problem...  :-(

**Comment by LeonLiber** [comment] 2017-02-05 14:55
Suggested workaround:
You can edit your "scripts" section under package.json file to have that:

`"start": "cp angular-cli-dev.json angular-cli.json && ng serve",
    "build": "cp angular-cli-prod.json angular-cli.json && ng build"`

Then you should rename your `angular-cli.json` file to ` angular-cli-dev.json` and `angular-cli-prod.json`
Each should have different configuration - in my case, different scripts in "secripts" section.

Hope that helps while we wait for an official solution

**Comment by hansl** [comment] 2017-04-07 22:13
What's wrong with having `import 'my-prod-only-script'` inside your `environment.prod.ts`?

**Comment by Ismaestro** [comment] 2017-04-08 07:02
@hansl It's not an import. It's a script that should be in included and minified with the others scripts of the application. So I think the right place to do that is in the .angular-cli.json file.

**Comment by LanderBeeuwsaert** [comment] 2017-04-29 08:51
A practical use case about this:

If I want to add my google analytics tracker code only when I go to production, how do I go about to do this?
I've tried to add it to environment.prod.ts ,
I've even tried https://github.com/angulartics/angulartics2 only to try to solve this.
Up until now, I have not succeeded to find a satisfying solution. Any ideas?

**Comment by fcalderon** [comment] 2017-05-03 11:50
@LanderBeeuwsaert I have a very similar use case as yours. I may have found a workaround that might make things more maintainable and be a better design than having to separate scripts. 

So the way I would do it with the service: 

* Edit `environment.prod.ts` and add a variable, e.g. `enableAnalytics`, you could also simply use the existing `enableProduction`
* Go to your analytics service, and check whether this flag is true in order to send the analytic event. 

e.g:

```typescript
    public pageChange(pageName) {
        if (!!ga && !!environment.enableProduction) {
                ga('send', 'pageView', pageName);
        }
    }
```
If you have more than one analytics script, you can use the code of the script and store that in the environment. Then you could load `ga` with the appropriate code in the service constructor.

e.g.

```typescript
// ... other imports ...
import {environment} from "../../environments/environment";

// ... other code ...

    constructor(logger:Logger){
        ga('create', environment.analyticsCode, 'auto');
    }

// ... other code ...
```

**Comment by LanderBeeuwsaert** [comment] 2017-05-09 18:21
Hello @fcalderon ,

yes, I actually solved it approximately the same way you did.
In my app.component.ts file I wrote:

    if (environment.production) {
      ga("create", gaCode, "auto");
      ga("send", "pageview", "index.html");
    }

kind regards

**Comment by roopkt** [comment] 2017-06-06 18:57
I created duplicate commands with prod suffix in the script and used those commands when needed.
like "test": " ng test", I created "test-prod": "ng test --browsers PhantomJS" , "build-prod" : "ng build -prodng build --prod --output-hashing false"  and so on. Now in my Continuous integration I use test-prod and build-prod scripts.

**Comment by garysui** [comment] 2017-08-02 14:58
@LeonLiber I like your solution. The nature of the problem is more **build** related.

**Comment by ohcibi** [comment] 2017-08-14 16:23
Why does this have a "nice to have" priority? This is a must have feature for a build tool.

**Comment by ohcibi** [comment] 2017-08-14 17:06
I'd like to share another solution that leaves only little boilerplate code in `main.ts` using [dynamic import](https://github.com/tc39/proposal-dynamic-import) which I borrowed from [here](https://github.com/Microsoft/TypeScript/issues/12364#issuecomment-288087153) (simplyfied code for umd module):

main.ts
```typescript
//...
import { environment } from './environments/environment';

declare global {
  interface System {
    import (request: string): Promise<any>;
  }

  const System: System;
}

if (!environment.production) {
  System.import('library').then(library => ).catch(error => );
}
//...
```

which only leaves something like

```javascript
if (!__WEBPACK_IMPORTED_MODULE_3__environments_environment__["a" /* environment */].production) {
  __webpack_require__.e/* import() */(6).then(__webpack_require__.bind(null, "library")).then(function (library) {
    }).catch(function (e) {
    });
}
```

in the production build.

**Comment by val-samonte** [comment] 2017-08-31 21:47
any updates on this? my use case is, I want to be able to include external scripts from the CDN, (which will be easily done by adding this on the script section) but of course, I want to specifically include the dev script from when in dev environment.

**Comment by richh94** [comment] 2017-09-15 12:48
Same question for me, are there any updates on this?

For now I fixed it this way https://github.com/angular/angular-cli/issues/4451#issuecomment-285026543 (thanks!) but that is REALLY ugly if you want to do that for Google Analytics, Hotjar AND Application Insights in 3 different environments.

**Comment by alan-agius4** [comment] 2018-02-15 09:00
Kinda need this badly as well.

**Comment by Ismaestro** [comment] 2018-02-15 09:56
Check [this](https://juristr.com/blog/2018/01/ng-app-runtime-config/?utm_campaign=NG-Newsletter&utm_medium=email&utm_source=NG-Newsletter_237).

**Comment by MadMango** [comment] 2018-03-20 11:28
For anyone still looking for a solution, in your `main.ts`, you could do:

```
import { environment } from './environments/environment';

const src = environment.your.cdn.url;
document.write(`<script src=${src}></script>`);
```

It's just a workaround but gets the job done for me.

**Comment by rwibawa** [comment] 2018-03-28 09:58
The `.angular-cli.json` supports [configuration for multiple apps](https://github.com/angular/angular-cli/wiki/stories-multiple-apps). Therefore we can put completely different configuration with different scripts/styles for the same app.
```json
"apps": [
    {
      "styles": [
        "styles.css"
      ],
      "scripts": [ ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts",
        "local": "environments/environment.local.ts"
      }
    },
    {
      "styles": [
        "styles.css",
        "../node_modules/select2/dist/css/select2.min.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/select2/dist/js/select2.full.min.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts",
        "local": "environments/environment.local.ts"
      }
    }
```
To serve the default app:
```sh
$ ng serve --app=0 

or 

$ ng serve --app 0
```

To serve the app with local environment:
```sh
$ ng serve --app=1 --env=local --port=8091
```

**Comment by clydin** [comment] 2018-12-06 18:58
Closing as Angular CLI 6.0+ supports a far reach configuration file format that allows for the customizations described above.

**Closed by clydin** 2018-12-06 18:58 UTC
Labels: priority: 3 (nice to have), type: feature
