### ISSUE TITLE
8.1.3 output fails to load after upgrading from 8.0.0

### ISSUE THREAD

**Issue by chadbr** [angular/angular-cli#15215] opened 2019-07-31 13:45 UTC
This is a continuation of #14909 -- I won't paste all the output from the other - it's the same.

### Is this a regression?

yes, worked fine in 8.0.0

### Description

Upgraded application from 8.0.0 to 8.1.3 -- and build output fails to load.

The source of the issue is loading of a 3rd party library that is not a `strict` script.

I've repo'd this by:
-creating a new cli project
-adding one external library to package.json
-import the package in app.module.ts.

```typescript
import '@somelib/toolkit.core';
```

@somelib/toolkit.core is a node module that includes:

index.d.ts
index.js
index.js.map

the index.js tries to reassign max_integer and it causes this...

<pre><code>
index.js.pre-build-optimizer.js:1 Uncaught TypeError: Cannot assign to read only property 'MAX_SAFE_INTEGER' of function 'function Number() { [native code] }'
    at index.js.pre-build-optimizer.js:1
</code></pre>

## 🔬 Minimal Reproduction

the library is in a private repo... I can upload the project with node_modules to github for someone to look at if it helps.

**Comment by clydin** [comment] 2019-07-31 14:16
Is the project using differential loading?
Module scripts are strict by definition as defined by the standard and implemented within the browser itself.  The behavior cannot be altered.

If the library in question cannot be corrected then an option is to disable differential loading.

**Comment by chadbr** [comment] 2019-07-31 14:40
@clydin I understand the browser restriction -- I don't understand how this changed between 8.0.0 and > 8.0.0?

I don't know how to tell if a project is using differential loading - my understanding is the > 8.0.0 cli does it by default.

Is there some way to turn it off?

Is there some way to tell angular to put the scripts in question into another bundle?

**Comment by clydin** [comment] 2019-07-31 16:12
Good point.  The underlying cause is not exactly obvious.  The issue is that for `ng serve` or `ng build --watch` only the module scripts are created since performing a full differential build is time consuming and for development this is generally not useful since a developer would typically be developing with a modern browser that provides dev tools.  For 8.0.0, even though the scripts were module scripts, the `type="module"` attribute was not being added in these cases.  The attribute was then added in later versions to better reflect both the nature of the scripts and to synchronize behavior with a production build (otherwise scripts could work in development but fail in production).  Module scripts are also deferred by default which is another behavioral difference.

In regards to disabling differential loading, there are several options:
* If ES5 only bundles are acceptable, then the ES target can be changed in the application's `tsconfig.json`.  Also enable the build option `es5BrowserSupport` to ensure polyfills are included for older browsers.
* If older browsers that do not support module scripts (ES2015+ features) are not required for the application, the `browserslist` file can be altered to only include newer browsers.  A setup similar to the following would work:
```
last 2 Chrome versions
last 2 Safari versions
last 2 Firefox versions
```

Note that the `browserslist` configuration is also used to process stylesheets.  Listing the full set of browsers that would be required for the application to support is the recommended best practice.

**Comment by alan-agius4** [comment] 2019-08-05 11:58
Closing as per answer above.

**Closed by alan-agius4** 2019-08-05 11:58 UTC
