### ISSUE TITLE
Configuration. Setting styleExt fails.

### ISSUE THREAD

**Issue by MRokas** [angular/angular-cli#2192] opened 2016-09-17 15:18 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

1\. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16.0.4 64bit

2\. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.14                                                 
node: 6.6.0                                                                
os: linux x64 
```

3\. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
```ng new NAME && cd NAME && ng set defaults.styleExt scss```

4\. The log given by the failure. Normally this include a stack trace and some
   more information.
```
    at RootSchemaTreeNode.ObjectSchemaTreeNode.serialize (/home/rokas/dev/a
ngular2/lol/node_modules/angular-cli/models/json-schema/schema-tree.js:227:
20)                                                                        
    at GeneratedSchemaClass.SchemaClassBase.$$serialize (/home/rokas/dev/an
gular2/lol/node_modules/angular-cli/models/json-schema/schema-class-factory
.js:141:25)                                                                
    at CliConfig.serialize (/home/rokas/dev/angular2/lol/node_modules/angul
ar-cli/models/config/config.js:37:29)                                      
    at CliConfig.save (/home/rokas/dev/angular2/lol/node_modules/angular-cl
i/models/config/config.js:33:44)                                           
    at /home/rokas/dev/angular2/lol/node_modules/angular-cli/commands/set.j
s:49:20                                                                    
    at Class.run (/home/rokas/dev/angular2/lol/node_modules/angular-cli/com
mands/set.js:31:16)                                                        
    at Class.<anonymous> (/home/rokas/dev/angular2/lol/node_modules/angular
-cli/lib/models/command.js:152:17)                                         
    at tryCatch (/home/rokas/dev/angular2/lol/node_modules/rsvp/dist/lib/rs
vp/-internal.js:215:12)                                                    
    at invokeCallback (/home/rokas/dev/angular2/lol/node_modules/rsvp/dist/
lib/rsvp/-internal.js:230:13)                                              
    at publish (/home/rokas/dev/angular2/lol/node_modules/rsvp/dist/lib/rsv
p/-internal.js:198:7)                                                      
    at flush (/home/rokas/dev/angular2/lol/node_modules/rsvp/dist/lib/rsvp/
asap.js:82:5)                                                              
    at _combinedTickCallback (internal/process/next_tick.js:67:7)          
    at process._tickCallback (internal/process/next_tick.js:98:9) 
```

5\. Mention any other details that might be useful.
While installing `angular-cli` I had these errors:

```
node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@6.6.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/rokas/.node-gyp/6.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/angular-cli/node_modules/fsevents/.node-gyp"
make: Entering directory '/usr/lib/node_modules/angular-cli/node_modules/fsevents/build'
make: *** No rule to make target '../.node-gyp/6.6.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/angular-cli/node_modules/fsevents/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/angular-cli/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-36-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/angular-cli/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64/fse.node" "--module_name=fse" "--module_path=/usr/lib/node_modules/angular-cli/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/angular-cli/node_modules/fsevents
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/angular-cli/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64/fse.node --module_name=fse --module_path=/usr/lib/node_modules/angular-cli/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/angular-cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-36-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/angular-cli/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/angular-cli/node_modules/fsevents
node-pre-gyp ERR! node -v v6.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/angular-cli/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64/fse.node --module_name=fse --module_path=/usr/lib/node_modules/angular-cli/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64' (1)

> execSync@1.0.2 install /usr/lib/node_modules/angular-cli/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> node-zopfli@1.4.0 install /usr/lib/node_modules/angular-cli/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.6.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/rokas/.node-gyp/6.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/.node-gyp"
make: Entering directory '/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
make: *** No rule to make target '../.node-gyp/6.6.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/angular-cli/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-36-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/angular-cli/node_modules/node-zopfli
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/angular-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-36-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/angular-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/angular-cli/node_modules/node-zopfli
node-pre-gyp ERR! node -v v6.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64' (1)
```
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-09-22 02:27
Dupe of https://github.com/angular/angular-cli/issues/1900

**Closed by filipesilva** 2016-09-22 02:27 UTC
