### ISSUE TITLE
new command returns error and fails to automatically install dependencies or setup git in Windows 10

### ISSUE THREAD

**Issue by duluca** [angular/angular-cli#10227] opened 2018-04-07 19:32 UTC
### Versions
```
ng 6.0.0-rc.2
Windows 10 Pro, version 1709
Node v8.11.0
npm v5.8.0
```

### Repro steps
* Execute `npx @angular/cli@6.0.0-rc.2 new ng6rc2`

### Observed behavior
Observe that:
- The command returns
```
npx: installed 1 in 3.081s
command not found: prefix
npx: installed 99 in 19.581s
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
- A folder named `ng6rc2` is created, but `node_modules` is not. If you execute `npm install` and then run `npm start` within the folder, then the Angular application still works.
- Note that also the git repository is not configured.

### Desired behavior
When running the `new` command on Windows 10, CLI should:
  - install dependencies without error
  - configure the git repository
as it does so in macOS.

**Comment by yarrgh** [comment] 2018-04-07 20:16
Duplicate of #10206

**Closed** 2018-04-07 21:02 UTC
