### ISSUE TITLE
"ng build" fails with TypeError when NODE_ENV is set to "development"

### ISSUE THREAD

**Issue by artu-ole** [angular/angular-cli#20502] opened 2021-04-12 12:48 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not sure.

### Description

I have encountered same issue as https://github.com/angular/angular-cli/issues/19677 with an exception that it happens no matter whether its a production build or not.
It seems to be related to the fact that NODE_ENV 'development' toggles some additional typescript assertions

```ts
Debug.setAssertionLevel(/^development$/i.test(sys.getEnvironmentVariable("NODE_ENV"))
            ? AssertionLevel.Normal
            : AssertionLevel.None);
```
https://github.com/microsoft/TypeScript/blob/38da7c600c83e7b31193a62495239a0fe478cb67/src/compiler/sys.ts#L1893-L1895
which in turn choke on angular component with combined import statement:

```ts
import tippy, { Instance } from 'tippy.js';
```
https://github.com/artu-ole/angular-cli-repro-app/blob/ba6bd91eeae2c92d429b7c388e51f879afd7b3e7/src/app/app.component.ts#L2

and if those are split into two statements then build goes through
```ts
// WORKS
// import tippy from 'tippy.js';
// import { Instance } from 'tippy.js';
```

## 🔬 Minimal Reproduction
1. Clone https://github.com/artu-ole/angular-cli-repro-app
2. `$env:NODE_ENV='development'`
3. `ng build`

## 🔥 Exception or Error

```console
Error: ./src/app/app.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: Cannot read property 'kind' of undefined
    at C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:2580:166
    at assert (C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:2501:127)
    at Object.assertNode (C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:2580:17)
    at visitNode (C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:80343:18)       
    at Object.visitEachChild (C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:80749:124)
    at visitor (C:\Users\artuo\git\repro-app\node_modules\@ngtools\webpack\src\transformers\make_transform.js:60:31)
    at visitNode (C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:80329:23)
    at Object.visitEachChild (C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:80747:172)
    at visitor (C:\Users\artuo\git\repro-app\node_modules\@ngtools\webpack\src\transformers\make_transform.js:60:31)
    at visitNodes (C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:80382:48)
    at visitLexicalEnvironment (C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:80422:22)
    at Object.visitEachChild (C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:80809:55)
    at visitor (C:\Users\artuo\git\repro-app\node_modules\@ngtools\webpack\src\transformers\make_transform.js:60:31)
    at Object.visitNode (C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:80329:23)
    at transformer (C:\Users\artuo\git\repro-app\node_modules\@ngtools\webpack\src\transformers\make_transform.js:67:31)
    at transformSourceFileOrBundle (C:\Users\artuo\git\repro-app\node_modules\typescript\lib\typescript.js:81488:57)
 @ ./src/app/app.module.ts 2:0-47 7:68-80 11:116-128
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.8
Node: 14.16.0
OS: win32 x64

Angular: 11.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8
@angular-devkit/build-angular   0.1102.8
@angular-devkit/core            11.2.8
@angular-devkit/schematics      11.2.8
@angular/cli                    11.2.8
@schematics/angular             11.2.8
@schematics/update              0.1102.8
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Comment by clydin** [comment] 2021-04-12 13:56
The `NODE_ENV` environment variable in this capacity is intended to facilitate debugging node applications and is recommended to be avoided outside of that context.  As a result, `NODE_ENV` is not used or required by the Angular CLI.  The issue demonstrated above, as mentioned, is caused by Typescript's internal behavior when TypeScript is placed in a debug/development mode by the aforementioned environment variable and is not generally intended to be used except when developing TypeScript itself as it may not function as expected otherwise.

**Comment by artu-ole** [comment] 2021-04-12 14:44
Our `NODE_ENV` usage is facilitated by the fact that angular project is served by express bundled into single docker container where node project takes care of miscellaneous features and assumes a role of backend for frontend. Therefore we specify `NODE_ENV` depending on the deployment target and whether its a development or production environment.

**Comment by clydin** [comment] 2021-04-12 14:48
A production ready application is not recommended to be built using build tools in a debug/development configuration.  Behavior in this scenario is undefined and the built application may not be functional.

**Comment by artu-ole** [comment] 2021-04-12 14:57
I would argue that building a docker container(and using `development` flag) does not imply that it's a production build. 
From my point of view there's a bug in the produced ast in this case as that assert should not fail otherwise.

**Comment by clydin** [comment] 2021-04-12 15:04
A production build of the application is not the key element but rather the stability of the build tool in use.  The purpose and meaning of `NODE_ENV` is drastically different between `express` and a command line tool such a TypeScript.  `express` uses the environment variable to signify whether the application is a production application.  Whereas with TypeScript, the options in the Typescript configuration file determine that.  The environment variable in the Typescript case, rather, changes the internals of the compiler to support development of the compiler itself (not the application) and in a way that may or may not generate a validate output.

**Comment by artu-ole** [comment] 2021-04-12 15:17
> changes the internals of the compiler to support development of the compiler itself (not the application) and in a way that may or may not generate a valid output.

Do you imply there's a bug in typescript in this case as we are using it on the serverside as well with the aforementioned `express` backend and have not encountered same bug with combined default and interface imports there running with `development` flag.

**Comment by clydin** [comment] 2021-04-12 16:31
Global use of `NODE_ENV` can lead to unexpected and/or unintended outcomes.  The behavior of `NODE_ENV` is unfortunately not standardized and can vary from package to package.

In this particular case, there appears to be two defects within TypeScript that lead to the crash demonstrated above. The first is that the assert function (`assertNode`) first asserts that the value is defined but if the assertion fails it then tries to access the `kind` property on the undefined value ([code](https://github.com/microsoft/TypeScript/blob/0487b38d06593b06fa30555c3dcf888063ad7369/src/compiler/debug.ts#L221)).  The second is the location of the call to the assert function.  At the location of the assertion call, the value can legitimately be undefined due to the empty array case.  An undefined value is also a valid value to return from the containing function ([code](https://github.com/microsoft/TypeScript/blob/0487b38d06593b06fa30555c3dcf888063ad7369/src/compiler/visitorPublic.ts#L43)).

**Comment by artu-ole** [comment] 2021-04-13 09:17
@clydin 
Nonetheless of course, that is not the root cause of there being an empty array.

In the `@ngtools/webpack/src/transformers/elide_imports.js` that `Instance` import from my example is removed from ast and the cause seems to be lying there as comments clearly indicate that that syntax is not being supported although it is valid AFAIK:
![Code_xHBq9ZChDn](https://user-images.githubusercontent.com/15938416/114528415-acc7ee80-9c51-11eb-8b92-32b7fb916647.png)

![Code_odKbXWniA9](https://user-images.githubusercontent.com/15938416/114528524-c5d09f80-9c51-11eb-88fa-ce720bffac57.png)

**Comment by clydin** [comment] 2021-04-13 10:32
An empty array is valid, supported, and generates the correct output AST.  The defect is purely on the TypeScript side.  There have been similar issues within the TypeScript code related to empty array handling which have been corrected over time.  Running TypeScript in its debug mode is more likely to surface some of these defects as this mode is not fully validated from both a TypeScript test suite perspective as it is not intended to be used outside of development of TypeScript itself.

**Comment by alan-agius4** [comment] 2021-04-15 08:41
Closing as this is not a bug caused by the Angular CLI.

**Closed by alan-agius4** 2021-04-15 08:41 UTC
