### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically WITH functions exported.

### ISSUE THREAD

**Issue by laPlacek** [angular/angular-cli#3967] opened 2017-01-12 13:29 UTC
### OS?
W10

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.4
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/platform-server: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Repro steps.
Consider following module:
```
export function angularHttpFactory(backend: XHRBackend, defaultOptions: RequestOptions): Http {
  return new Http(backend, defaultOptions);
}

export function authHttpFactory(auth: Auth, backend: XHRBackend, defaultOptions: RequestOptions): AuthHttp {
  return new AuthHttp(auth, backend, defaultOptions);
}

@NgModule({
  declarations: [LoginLoaderComponent],
  imports: [CommonModule, HttpModule, Ng2Webstorage],
  exports: [LoginLoaderComponent]
})
export class AuthModule {
  static forRoot(authConfig: AuthConfig): ModuleWithProviders {
    return {
      ngModule: AuthModule,
      providers: [
        { provide: AUTH_CONFIG, useValue: authConfig },
        { provide: ANGULAR_HTTP, useFactory: angularHttpFactory, deps: [XHRBackend, RequestOptions] },
        Auth,
        { provide: Http, useFactory: authHttpFactory , deps: [Auth, XHRBackend, RequestOptions] },
        AuthUser
      ]
    };
  }

  static forChild(): ModuleWithProviders {
    return {
      ngModule: AuthModule
    };
  }
}
```

### The log given by the failure.
> ERROR in Error encountered resolving symbol values statically. Calling function 'AuthModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/Users/jacek_dauth3h/Documents/dev/action-center-web-app/src/app/app.module.ts, resolving symbol AppModule in C:/Users/jacek_dauth3h/Documents/dev/action-center-web-app/src/app/app.module.ts

**Comment by serhiisol** [comment] 2017-01-12 21:03
Same problem here, if provide third party providers or modules, e.g.:
```
useFactory: isProduction => new LogService(isProduction)
```
```
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 42:19 in the original .ts file), resolving symbol AppModule in /Users/serhiisol/Development/admin-app/src/app/app.module.ts
```
log points on beginning of arrow function, e.g. on ```isProduction```.

**Comment by deebloo** [comment] 2017-01-13 03:06
@laPlacek hmmm nothing you have shown looks incorrect. would be be possible for you to do reproduce in a minimal repo and share?

@serhiisol your specific issue is that you need to you change your code from what you currently have to:

```TS
export function logServiceFactory(isProduction) {
    return new LogService(isProduction)
}
```

and then
```
useFactory: logServiceFactory
```

**Comment by serhiisol** [comment] 2017-01-13 09:00
@deebloo that's one of the examples, basically the problem is in AOT and Angular analyzer. It analyzes code in all cases whether you wanted to have aot or not.

**Comment by deebloo** [comment] 2017-01-13 12:20
@serhiisol correct even if you don't use AOT your code needs to be statically analyzable

**Comment by serhiisol** [comment] 2017-01-13 12:22
that's bad, it should be optional, should have some flag not to use this aot and analysis, IMHO, a lot of libraries, projects do not support AoT, what they should do in that case? rewrite application entirely ?

**Comment by deebloo** [comment] 2017-01-13 12:26
There are other discussions going on about that particular issue, eventually AOT will be the default way angular apps are built. AOT does not require entire rewrites, it just requires the code in your decorators be statically analyzable

**Comment by serhiisol** [comment] 2017-01-13 12:29
What about 3rd parties, which component/module will import? Will the analyzer analyze them ?

**Comment by deebloo** [comment] 2017-01-13 12:31
@serhiisol only angular libraries. Jquery/moment and other 3rd part libs don't need to do anything special

**Comment by serhiisol** [comment] 2017-01-13 12:47
@deebloo so if library won't support AOT you stuck

**Comment by deebloo** [comment] 2017-01-13 13:26
@serhiisol at least as of now yes. Is there a certain library you are having trouble with?

**Comment by serhiisol** [comment] 2017-01-13 13:27
only angular :) this AOT stuff just do not work correctly, always throws errors even if I exactly doing everything from the manual it still throws errors

**Comment by deebloo** [comment] 2017-01-13 13:28
can you post some reproducible examples? The only problem with what you posted before was using inline functions for your factories

**Comment by serhiisol** [comment] 2017-01-13 13:29
currently it throws error 
```
ERROR in SVGIconModule is not an NgModule
```

and the module itself looks like:
```
import { NgModule } from '@angular/core';

import { SVGComponent } from './svg-icon.component';

@NgModule({
  declarations: [
    SVGComponent
  ],
  imports: [

  ],
  exports: [SVGComponent],
})
export class SVGIconModule { }

```

**Comment by deebloo** [comment] 2017-01-13 13:31
@serhiisol can you provide more context? How and where SVGIconModule is used? is that module in the same project as the main app?

**Comment by serhiisol** [comment] 2017-01-13 13:33
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SVGIconModule, SVGService } from 'ng-components/svg-icon';

import { AppComponent } from './app.component';
import { routing } from './app.routing';

@NgModule({
  imports: [
    BrowserModule,
    CommonModule,
    SVGIconModule,
    routing
  ],
  providers: [
    SVGService
  ],
  declarations: [ AppComponent ],
  bootstrap: [ AppComponent ]
})
export class AppModule {
  constructor(svgService: SVGService) {
    svgService.path = './assets/svg';
  }
}

```

**Comment by deebloo** [comment] 2017-01-13 13:41
Is your library published somewhere or are you using a linked library

**Comment by serhiisol** [comment] 2017-01-13 13:54
I have another folder and npm installs this package from the folder. And yes, I'm linking them together. But issue appears also without linking.

**Comment by deebloo** [comment] 2017-01-13 13:56
I don't think that will work. Your issue isn't tied to AOT I think there is an active bug using external libraries not standardly installed

**Comment by serhiisol** [comment] 2017-01-13 13:58
that's not correct, at the end, ng-components just a normal package inside node_modules, with one folder, e.g. in this case svg-icon, and then import it normally like normal package

**Comment by mkollers** [comment] 2017-01-13 14:03
I've got the same issue after updating dependencies two hours ago, with the npm package "angular-oauth2-oidc"...

**Comment by deebloo** [comment] 2017-01-13 14:23
@serhiisol the error of "ERROR in SVGIconModule is not an NgModule" is not tied to the problem stated in this issue. Id suggest looking through the other issues and if you can't find it create a new one

**Comment by serhiisol** [comment] 2017-01-13 14:26
it's actually produced by the same code analyzer

**Comment by laPlacek** [comment] 2017-01-13 16:09
@serhiisol it is, but the subject of this issues says explicitly what it is about. it is not about all problems related to code analyzer, but about the specific problem: **resolving symbol** values statically **WITH functions exported**.

@deebloo it turns out, the same issue occurs when using aot compiler without angular CLI. saying that i'm going to continue the discussion on https://github.com/angular/angular/issues/13892

Thanks for help, i cannot make the repo or the used packages public since they are property of the client.

**Comment by serhiisol** [comment] 2017-01-13 17:21
@laPlacek these errors produced by analyzer, look at the code of aot compiler in @angular/compiler

**Comment by filipesilva** [comment] 2017-01-24 16:04
Closing as the (original) issue seems to be a static analysis one as per https://github.com/angular/angular-cli/issues/3967#issuecomment-272480733.

**Closed by filipesilva** 2017-01-24 16:04 UTC

**Comment by serhiisol** [comment] 2017-01-24 16:08
@filipesilva could you explain how to disable static analysis without AOT? My App code is not ready for AOT and CLI fails to compile it despite the fact that I didn't turn on AOT

**Comment by filipesilva** [comment] 2017-01-24 16:10
@serhiisol there is no way to disable it currently. Static analysis is always performed on the code.

**Comment by serhiisol** [comment] 2017-01-24 16:12
@filipesilva In angular team, did you even planned to give that option? just for curiosity

**Comment by filipesilva** [comment] 2017-01-24 16:14
There's no plans to add that option in the CLI that I know of. @hansl can you weigh in?

**Comment by Cogitaria** [comment] 2017-03-23 02:23
The Angular documentation still actively promotes the use of static methods in decorators, so no surprise it's so widely used.  Is there a (simple) work-around to import ModuleWithProviders into application modules (or modules in general)?

https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-for-root

**Comment by filipesilva** [comment] 2017-03-26 20:23
@Cogitaria you're right. If that approach has problems with AOT we shouldn't be promoting it in the docs.
