### ISSUE TITLE
Add support for *.html via the raw-loader to the webpack.config generated by @angular-devkit/build-angular:karma

### ISSUE THREAD

**Issue by skoblenick** [angular/angular-cli#16746] opened 2020-01-23 22:42 UTC
# 🚀 Feature Request: Add support for *.html via the raw-loader to the webpack.config generated by @angular-devkit/build-angular:karma

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

#### Background
I am working on a legacy AngularJS application. Migrating the entire code base to Angular is not technically viable at this point in time. As a solution I have dual bootstrap the AngularJS application with the Angular ngUpgrade module so the application can be migrated over time. 

At this initial stage of the project I am using the existing webpack.config to build the app. My webpack.config handles the transpilation of the Typescript and Angular by way of the ts-loader. Everything compiles and loads and I can proceed with Angular while maintaining existing AngularJS code.

At present I do not get the full benefit of the Angular CLI, but will in future as more legacy code is migrated and the CLI is used to it's full capability. At present thou it should be possible for me to use the lint and test commands against all new Angular code even thou it isn't being built or served by the Angular CLI.

#### The actual feature request

The issue comes into play when I attempt to use `ng test` to test new Angular components. `ng test`, or more specifically the angular-devkit/build-angular:karma plugin. Out of the box it doesn't support native ES6 imports for html files within Angular components. Running `ng test` on files written like:

```
import {Component} from '@angular/core';

import template from './my-component.component.html';

@Component({
    selector: 'my-component',
    template
})
public class MyComponent {
```

results in:

```
ERROR in ./src/app/my-component/my-component.component.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

I cannot use the Angular CLI to build at this time, so using templateUrl is out as it results distribution  making requests to the server for the templates. I assume this is because I don't have a full AOT configuration provided natively by the Angular CLI.

### Describe the solution you'd like

I would like the `\.html$` files to be handled by the webpack config generated by @angular-devkit/build-angular/plugins/karma`. This can be achieved simply by adding (or something similar):

```
webpackConfig.module.rules.push({
    test: /\.html$/,
    use: [{loader: 'raw-loader'}]
});
```

I was thinking `raw-loader` only because you already have it as a dependency; otherwise `html-loader` would also work with the additional configuration option for `caseSensitive: true`. It's a little insane that the plugin supports imports of every other typical file type but not html:

```
[
  {
    test: /\.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)$/,
    loader: 'file-loader',
    options: { name: '[name].[ext]' }
  },
  {
    test: /[\/\\]@angular[\/\\]core[\/\\].+\.js$/,
    parser: { system: true }
  },
  { test: /[\/\\]hot[\/\\]emitter\.js$/, parser: { node: [Object] } },
  {
    test: /[\/\\]webpack-dev-server[\/\\]client[\/\\]utils[\/\\]createSocketUrl\.js$/,
    parser: { node: [Object] }
  },
  { test: /\.js$/, exclude: /(ngfactory|ngstyle)\.js$/ },
  {
    test: /\.js$/,
    exclude: /(ngfactory|ngstyle)\.js$/,
    enforce: 'pre'
  },
  { exclude: [], test: /\.css$/, use: [ [Object], [Object] ] },
  {
    exclude: [],
    test: /\.scss$|\.sass$/,
    use: [ [Object], [Object], [Object] ]
  },
  {
    exclude: [],
    test: /\.less$/,
    use: [ [Object], [Object], [Object] ]
  },
  {
    exclude: [],
    test: /\.styl$/,
    use: [ [Object], [Object], [Object] ]
  },
  {
    test: /\.tsx?$/,
    loader: '/<omitted>/node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/index.js'
  },
  {
    test: /\.(jsx?|tsx?)$/,
    loader: '/<omitted>/node_modules/coverage-istanbul-loader/lib/index.js',
    options: { esModules: true },
    enforce: 'post',
    exclude: [ /\.(e2e|spec)\.ts$/, /node_modules/ ],
    include: '<omitted>'
  }
]
```

This shouldn't impact the usage of Angular's template or templateUrls because they aren't native requires or imports; just strings and webpack will ignore them.

### Describe alternatives you've considered

I have tried several work arounds including attempting to preprocess the files like in AngularJS and replace templateUrl with the embedded html string. Looked into other angular tooling that will build angular in my existing webpack config; but all these solutions feel dirty.

My least offensive workaround for my issue is to publish my own hacked version of the angular-devkit/build-angular library that applies the above mentioned patch so I can process test files in a way I expect until which time I can move to a world strictly with the angular-cli.

**Comment by alan-agius4** [comment] 2020-01-24 06:26
Hi @skoblenick, this is a duplicate of this issue https://github.com/angular/angular-cli/issues/14855#issuecomment-510592634

**Closed by alan-agius4** 2020-01-24 06:26 UTC

**Comment by skoblenick** [comment] 2020-01-24 15:40
@alan-agius4 ty. I accept this as a better solution to the issue.
