### ISSUE TITLE
ng update @angular/core: This request requires auth credentials

### ISSUE THREAD

**Issue by alvaro450** [angular/angular-cli#12835] opened 2018-11-01 15:03 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node: 10.13.0
npm: 6.4.1
ng 7.0.3

### Repro steps

ng update @angular/core 

### The log given by the failure

This request requires auth credentials. Run `npm login` and repeat request.

### Desired functionality

Updates angular libraries successfully

### Mention any other details that might be useful

The code in @schematics/update/update/npm.ts, the function to read npmrc file only checks LOCALAPPDATA on windows machines, most of our computers have the npmrc at the user level (C://Users/<user>/.npmrc). When it tries to get the npm configuration it is not able to find anything. 
When RegistryClient issues the GET request to get the package.json file from our repository, it obviously not passing the _auth token, hence the message above.

**Comment by alvaro450** [comment] 2018-11-01 15:04
@filipesilva I can submit a PR if you guys want me to.

**Comment by alan-agius4** [comment] 2018-11-01 16:53
Duplicate of #12664

**Closed by alan-agius4** 2018-11-01 16:53 UTC
