### ISSUE TITLE
Creating new component shows error:TypeError: core_1.PriorityQueue is not a constructor

### ISSUE THREAD

**Issue by praveenojha33** [angular/angular-cli#9374] opened 2018-01-25 04:48 UTC
### Versions
```
Angular CLI: 1.6.4
Node: 8.9.4
OS: linux x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

```

### Repro steps

* Running command `ng g c component`

### Observed behavior
```
core_1.PriorityQueue is not a constructor
TypeError: core_1.PriorityQueue is not a constructor
    at new TaskScheduler (/home/praveen/academeics/node_modules/@angular-devkit/schematics/src/engine/task.js:20:23)
    at SchematicEngine.createContext (/home/praveen/academeics/node_modules/@angular-devkit/schematics/src/engine/engine.js:81:31)
    at SchematicImpl.call (/home/praveen/academeics/node_modules/@angular-devkit/schematics/src/engine/schematic.js:35:38)
    at Promise (/home/praveen/academeics/node_modules/@angular/cli/tasks/schematic-run.js:73:23)
    at new Promise (<anonymous>)
    at Class.run (/home/praveen/academeics/node_modules/@angular/cli/tasks/schematic-run.js:72:16)
    at Class.run (/home/praveen/academeics/node_modules/@angular/cli/commands/generate.js:161:33)
    at resolve (/home/praveen/academeics/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (/home/praveen/academeics/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
```

### Desired behavior
Component should be created

###Deleting node_modules allowed creation of component and installing it again produces the above bug.
![error](https://user-images.githubusercontent.com/25537606/35371254-f8e431c0-01b8-11e8-8bbc-ccea6b97c3a5.png)

**Comment by nilseckert** [comment] 2018-01-25 09:17
I had the same issue and solved it by adding devkit-core in version 0.0.29 to my devDependencies

```
"devDependencies": {
    "@angular-devkit/core": "0.0.29",
   ...
}
```

or using with `npm i -D @angular-devkit/core@0.0.29`

**Comment by BreadBomb** [comment] 2018-01-25 12:25
This works for me:

I downgraded my globally installed angular cli to 1.5.0.

Just
```
npm remove -g @angular/cli
npm install -g @angular/cli@1.5.0
```

I think this only works if your project is running on Angular 4

**Comment by Oakerin** [comment] 2018-01-25 15:24
The same issue.

`
"devDependencies": {
    "@angular/cli": "1.6.3"
}
`

**Comment by buchmiller** [comment] 2018-01-25 20:33
I was able to resolve this same error by updating angular-cli to the latest version
```
npm remove -g @angular/cli
npm install -g @angular/cli@latest
```
and ensuring that the @angular/cli version in my package.json is fairly recent too.
Then I completely removed the node_modules folder and did a fresh install.

**Comment by Brocco** [comment] 2018-01-25 22:10
Can someone provide a reproduction repository? I have not been able to reproduce this issue. Also, please update to the latest version fo the CLI which is currently 1.6.6 which has a fix for some of the generate issues which were reported.

**Comment by tigredonorte** [comment] 2018-01-26 19:17
Same here

**Comment by gautamkrishnar** [comment] 2018-01-27 08:33
Same here... Fixed it by adding `  "@angular-devkit/core": "0.0.29"` to package.json for angular 5 using `npm i -D @angular-devkit/core@0.0.29` command

**Comment by olakara** [comment] 2018-01-28 16:57
@gautamkrishnar & @nickroberts Thanks! I was able to get around the issue by following your solution.

**Comment by Oakerin** [comment] 2018-01-30 11:40
@gautamkrishnar  Really thanks! It works!

**Comment by filipesilva** [comment] 2018-02-01 09:41
@gautamkrishnar and @buchmiller's comments seem to indicate this is fixed by updating. I think it's the same root cause as https://github.com/angular/angular-cli/issues/9194, which is fixed in 1.6.6 as detailed in https://github.com/angular/angular-cli/issues/9194#issuecomment-360615868.

**Closed by filipesilva** 2018-02-01 09:41 UTC
Labels: comp: cli/generate, need: more info

**Comment by omganesh** [comment] 2018-02-08 04:57
thanks  it works 
updated the package.json  followed by npm install

**Comment by fahedalh** [comment] 2018-03-16 11:48
install this :+1: 
 npm i -D @angular-devkit/core@0.0.29

it will solve the problem

**Comment by fahedalh** [comment] 2018-03-16 14:35
install this :+1: 
$ npm i -D @angular-devkit/core@0.0.29

it will solve the problem

**Comment by pugillum** [comment] 2018-07-16 07:33
In my case, I solved using: npm install @angular-devkit/core@0.3.2 --save-dev.  I am using angular CLI 1.7.4
