### ISSUE TITLE
Maximum call stack size exceeded when build --prod at StaticSymbolResolver.resolveSymbol

### ISSUE THREAD

**Issue by HeDo88TH** [angular/angular-cli#9383] opened 2018-01-25 13:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I have 1 module 3 components and 1 directive. There are no circular dependencies between them. I'm using angular material. 

When I run ng build --prod this is the error that pops out (using --verbose)

<pre><code>
ng build --prod --verbose

6451ms building modules
0ms sealing
0ms optimizing
0ms basic module optimization
0ms module optimization
0ms advanced module optimization
15ms basic chunk optimization
0ms chunk optimization
0ms advanced chunk optimization
1075ms building modules
4ms module and chunk tree optimization
0ms chunk modules optimization
0ms advanced chunk modules optimization
0ms module reviving
5ms module order optimization
0ms module id optimization
0ms chunk reviving
4ms chunk order optimization
0ms chunk id optimization
4ms hashing
0ms module assets processing
8ms chunk assets processing
16ms additional chunk assets processing
0ms additional asset processing
309ms chunk asset optimization
0ms asset optimization
Hash: 1b29ef7f5e3a9970305f
Version: webpack 3.10.0
Time: 7940ms
                                   Asset      Size  Chunks  Chunk Names
polyfills.3bc34265385d52184eab.bundle.js  86 bytes       1  polyfills
     main.e402deade8b026b7d50e.bundle.js  84 bytes       2  main
   inline.92ef6709b02058cd9af2.bundle.js   1.45 kB       3  inline
  styles.9bf67ccb2b89c7f441c0.bundle.css   49.3 kB       0  styles
chunk    {0} styles.9bf67ccb2b89c7f441c0.bundle.css (styles) 122 bytes {3} [initial] [rendered]
chunk    {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 28 bytes {3} [initial] [rendered]
chunk    {2} main.e402deade8b026b7d50e.bundle.js (main) 28 bytes {3} [initial] [rendered]
chunk    {3} inline.92ef6709b02058cd9af2.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveSymbol (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:29106:14)
    at resolveReferenceValue (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32053:75)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32216:65)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  3.33 kB       0
    chunk    {0} index.html 813 bytes [entry] [rendered]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--8-1!node_modules/postcss-loader/lib/index.js??postcss!src/style.css:
    chunk    {0} extract-text-webpack-plugin-output-filename 2.68 kB [entry] [rendered]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--9-1!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--9-3!src/orange-indigo.scss:
    chunk    {0} extract-text-webpack-plugin-output-filename 51.5 kB [entry] [rendered]

ERROR in RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveSymbol (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:29106:14)
    at resolveReferenceValue (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32053:75)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32216:65)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
</pre></code>

Using --dev or removing --aot It works. The command serve works like a charm.

here it is my angular-cli.json

<pre><code>{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "product-registration-client"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "style.css",
        "orange-indigo.scss"
      ],
      "scripts": [        
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "staging": "environments/environment.staging.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
</code></pre>

package.json

<pre><code>
{
  "name": "product-registration-client",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.2",
    "@angular/animations": "^5.2.1",
    "@angular/cdk": "^5.1.0",
    "@angular/common": "^5.2.1",
    "@angular/compiler": "^5.2.1",
    "@angular/core": "^5.2.1",
    "@angular/forms": "^5.2.1",
    "@angular/http": "^5.2.1",
    "@angular/material": "^5.1.0",
    "@angular/platform-browser": "^5.2.1",
    "@angular/platform-browser-dynamic": "^5.2.1",
    "@angular/router": "^5.2.1",
    "angular-google-place": "0.0.3",
    "core-js": "^2.4.1",
    "ng2-file-upload": "^1.3.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.5",
    "@angular/compiler-cli": "^5.2.1",
    "@angular/language-service": "^5.2.1",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.1.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
</code></pre>

## Environment

This is my environment:

<pre><code>
Angular CLI: 1.6.4
Node: 9.4.0
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.4
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.46
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0

</code></pre>

I can provide the source code if needed to solve this issue, thanks

**Comment by filipesilva** [comment] 2018-01-26 10:12
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by HeDo88TH** [comment] 2018-01-26 14:56
Here it is the repro https://github.com/HeDo88TH/repro-cli-max-stack
<pre><code>
git clone https://github.com/HeDo88TH/repro-cli-max-stack.git
cd repro-cli-max-stack
npm install
ng build --prod
<code>
<pre>

Then the error

<pre><code>
Date: 2018-01-26T14:53:26.710Z
Hash: be0055d9d2e9b07f86c9
Time: 1931ms
chunk {0} styles.9c0ad738f18adc3d19ed.bundle.css (styles) 79 bytes [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.22b7623ed7c5ac6f9a35.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveSymbol (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:29112:14)
    at resolveReferenceValue (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32059:75)
    at simplify (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32222:65)
    at simplifyInContext (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32427:20)
    at simplifyNested (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32084:28)
    at simplify (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32224:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32427:20)
    at simplifyNested (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32084:28)
    at simplify (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32224:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32427:20)
    at simplifyNested (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32084:28)
    at simplify (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32224:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32427:20)
    at simplifyNested (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32084:28)
    at simplify (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32224:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\repro-cli-max-stack\node_modules\@angular\compiler\bundles\compiler.umd.js:32427:20)
</code></pre>

**Comment by alexzuza** [comment] 2018-01-26 19:45
I can confirm this issue. It is connected with `angular-google-place` library.

I investigated a bit this problem and here is what I've discovered https://github.com/psykolm22/angular-google-place/issues/29

**Comment by filipesilva** [comment] 2018-01-31 10:12
Going through @alexzuza excellend investigation in https://github.com/psykolm22/angular-google-place/issues/29#issuecomment-360884843, this seems to be a duplicate of https://github.com/angular/angular/issues/19219. That issue is closed but I'll post there that this still happens with some libraries to see if it needs more attention.

**Closed by filipesilva** 2018-01-31 10:12 UTC
Labels: need: repro steps
