### ISSUE TITLE
--source-dir not working as expected when creating a new project

### ISSUE THREAD

**Issue by harilal** [angular/angular-cli#8461] opened 2017-11-13 05:20 UTC
### Bug Report or Feature Request (mark with an `x`)
```
When a new project is created using --source-dir it creates both src folder and the custom folder. The tsconfig files located inside src folder. But in angular-cli.json it's pointed to src.
```

### Versions.
Angular CLI: 1.5.0
Node: 8.6.0
OS: win32 x64
Angular:
...

### Repro steps.
ng new testdir1 --skip-install --source-dir client

Will create both _src_ _and_ client folder.

**Comment by esagawe** [comment] 2017-11-17 15:32
I have this problem, too (Windows 10, 64 bit, NodeJS 6.10.0, Angular 5, Angular CLI 1.5.0 / 1.5.2). When I try to generate a component CLI trys to use a wrong directory (`src/client/src/client` instead of `src/client`).

```
ng g c foobar --skip-import -d
create src/client/src/client/app/foobar/foobar.component.html (25 bytes)
create src/client/src/client/app/foobar/foobar.component.spec.ts (628 bytes)
create src/client/src/client/app/foobar/foobar.component.ts (269 bytes)
create src/client/src/client/app/foobar/foobar.component.css (0 bytes)
```

In my project I have the directories `src/api` and `src/client` (client contains tsconfig.app.json, main.ts etc)  and with Angular CLI 1.4.0 and Angular 4 everything was fine, but since the upgrade I can't use the generate commands.

**Comment by michelmontejuado** [comment] 2017-12-05 08:21
I have the same problem as @esagawe on Windows 10 64bit, Node 9.2.0, Angular 5.0.0, Angular CLI 1.5.5.

I am building an Electron application with Angular. I had some trouble creating the application properly, but managed to get it to function properly after reading the doc : I have put the Angular app in ```src/renderer/application```. I defined it properly inside the 'apps' array in the .angular-cli.json (the root being defined as ```src/renderer/application```). An ng build or serve works as expected, but when using the generate command, the cli generates the new module or component (or whatever else) inside ```src/renderer/application/src/renderer/application/app```.

I generated the new module first. If I move it manually and try to generate a component for that module but the CLI cannot find the module (```Error: Specified module does not exist```). Then I left the module as is, and generated the component properly, but in the wrong folder (```src/renderer/application/src/renderer/application/app/module```). Additionnally, the CLI generated an empty folder with the module name at the correct location.

```
> ng g m shared
  create src/renderer/application/src/renderer/application/app/shared/shared.module.ts (190 bytes)
```

Move the folder manually to src/renderer/application/app/ then :

```
> ng g c shared/window -m shared/shared.module.ts
Error: Specified module does not exist
Specified module does not exist
```

 Delete everything then :

```
> ng g m shared
  create src/renderer/application/src/renderer/application/app/shared/shared.module.ts (190 bytes)
> ng g c shared/window -m shared/shared.module.ts
  create src/renderer/application/src/renderer/application/app/shared/window/window.component.html (25 bytes)
  create src/renderer/application/src/renderer/application/app/shared/window/window.component.spec.ts (628 bytes)
  create src/renderer/application/src/renderer/application/app/shared/window/window.component.ts (269 bytes)
  create src/renderer/application/src/renderer/application/app/shared/window/window.component.scss (0 bytes)
  update src/renderer/application/src/renderer/application/app/shared/shared.module.ts (266 bytes)
```

**Comment by Brocco** [comment] 2017-12-05 14:43
Closing...
Duplicate of #8417

**Closed by Brocco** 2017-12-05 14:43 UTC
Labels: priority: 1 (urgent), severity3: broken

**Comment by dipaktelangre** [comment] 2019-03-06 05:38
I too had problem but it working fine now as ```ng new foobar --prefix foo --style scss --routing true --skip-git true --source-dir=web --dry-run```
