### ISSUE TITLE
consider generate webpack.config.[env].js?

### ISSUE THREAD

**Issue by jzlxiaohei** [angular/angular-cli#2169] opened 2016-09-16 13:14 UTC
`webpack` is powerful and has many `options` , `plugins ` ,`loaders`... I think It is very hard to cover all situations just  by limited options in cli.

for example:
1.  i want to  use `externals` config for cdn
2. i  use `webpack-dev-middleware` not `webpack-dev-server`
3. i dont want to use `html-webpack-plugin`, i use template engine(like pug/jade) to generate html.

generated files (`webpack.config.[env].js `) and some npm scripts might be better

**Comment by JanStureNielsen** [comment] 2016-09-16 15:31
Can you describe your feature proposal in detail, @jzlxiaohei? Can you produce a PR?

**Comment by Igonato** [comment] 2016-09-16 16:01
See #1656

**Comment by filipesilva** [comment] 2016-09-22 01:06
Dupe of https://github.com/angular/angular-cli/issues/1656

**Closed by filipesilva** 2016-09-22 01:06 UTC
