### ISSUE TITLE
ng downloads latest stable cli version from npm instead of using same version which is globally installed

### ISSUE THREAD

**Issue by myemuk** [angular/angular-cli#18227] opened 2020-07-11 17:06 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No, it was happening before.

### Description
Command running: `ng update`. Local ng version was 10.0.1; and version 10.0.2 was installed globally. And global version was latest stable release.

So first, ng chooses local version, because global is newer.
Second: ng decides to download latest stable version from npm to the temporary folder and run it instead of using global version.

As the result it takes much longer time to run this command. Moreover I usually use `ng update` and than `ng update @angular/cli @angular/core` if there is an update. So it downloads same version twice instead of using global version.

## 🔬 Minimal Reproduction
1. Install latest stable version globally.
2. Run `ng update` in any project what needs to be updated.

## 🔥 Exception or Error

<pre><code>
[user@mnjr driver]$ ng update
Your global Angular CLI version (10.0.2) is greater than your local
version (10.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 50 dependencies.
    We analyzed your package.json, there are some packages to update:
    
      Name                                Version                  Command to update
     ---------------------------------------------------------------------------------
      @angular/cli                        10.0.1 -> 10.0.2         ng update @angular/cli
      @angular/core                       10.0.2 -> 10.0.3         ng update @angular/core
[user@mnjr driver]$ ng update @angular/cli @angular/core
Your global Angular CLI version (10.0.2) is greater than your local
version (10.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.

</code></pre>

## 🌍 Your Environment
<pre><code>
Your global Angular CLI version (10.0.2) is greater than your local
version (10.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.1
Node: 14.5.0
OS: linux x64

Angular: 10.0.2
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              9.1.10
@angular-devkit/schematics        9.1.10
@angular/cli                      10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               9.1.10
@schematics/update                0.1000.1
rxjs                              6.6.0
typescript                        3.9.6
webpack                           4.43.0

</code></pre>

**Comment by alan-agius4** [comment] 2020-07-13 10:53
Hi @myemuk, 

This is currently working as intended. However, I do agree we should do better by maybe reusing the temporary version. However this will be part of a bigger overhaul of the `ng update` experience and also reducing the footprint of the global Angular CLI installation.

The global Angular CLI, is used to enable `ng` in path and acts as a proxy to the local CLI. It is not used for anything else other than `ng new`.

It's important that `ng update` always downloads and uses the latest stable version to take advantage of bug fixes and features which effect the update experience.

My recommendation to avoid unnecessary temporary installations for the time being would be to run `ng update @angular/cli` prior of running `ng update`.

**Comment by grosch** [comment] 2020-09-25 23:42
Definitely needs to cache this somewhere. It's super painful doing this from home, over VPN, through the company's firewall.  Takes forever :(

**Closed** 2020-10-21 15:10 UTC
Labels: ng update DX
