### ISSUE TITLE
Sass Modules - ng build&lint error when @use and @include mixins with namespaces

### ISSUE THREAD

**Issue by tomanovy** [angular/angular-cli#16354] opened 2019-12-05 01:25 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not sure, probably no.

### Description

Angular lint and build is impossible when using SASS namespaces.

1. (ng lint) how to allow "@use" if "at-rule-no-unknown" is not supported
2. (ng build) how to allow SASS Modules namespaces?

## 🔬 Minimal Reproduction
1. ng new app --style=scss
2. modify tslint.json
```json
    {
      "extends": "tslint:recommended",
      "rulesDirectory": [
        "codelyzer"
      ],
  "rules": {
    "at-rule-no-unknown": [true, {
      "ignoreAtRules": ["mixin"]
    }],
  // ...
```
3. run ng lint - result:
```
Could not find implementations for the following rules specified in the configuration:
    at-rule-no-unknown
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
```
4. create new file /src/app/styles/mix.scss
```scss
@mixin size($fontsize) {
  font-size: $fontsize;
}  
```
5. modify app.component.scss and add (with new line)
```scss
@use "styles/mix" as mi; 
button {
    @include mi.size('10px');
}
```
6. run ng build
```
ERROR: Invalid CSS after "...clude normalize": expected "}", was ".button-reset; // 1"
An unhandled exception occurred: Invalid CSS after "...clude normalize": expected "}", was     ".button-reset; // 1"
See "/tmp/ng-OkZ01p/angular-errors.log" for further details.
```
## 🔥 Exception or Error
Issue 1:
<pre><code>
Could not find implementations for the following rules specified in the configuration:
    at-rule-no-unknown
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
</code></pre>
Issue 2:
<pre><code>
ERROR: Invalid CSS after "...clude normalize": expected "}", was ".button-reset; // 1"
An unhandled exception occurred: Invalid CSS after "...clude normalize": expected "}", was     ".button-reset; // 1"
See "/tmp/ng-OkZ01p/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.3
Node: 10.15.2
OS: linux x64
Angular: 9.0.0-rc.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.3
@angular-devkit/build-angular      0.900.0-rc.3
@angular-devkit/build-ng-packagr   0.900.0-rc.3
@angular-devkit/build-optimizer    0.900.0-rc.3
@angular-devkit/build-webpack      0.900.0-rc.3
@angular-devkit/core               9.0.0-rc.3
@angular-devkit/schematics         9.0.0-rc.3
@ngtools/webpack                   9.0.0-rc.3
@schematics/angular                9.0.0-rc.3
@schematics/update                 0.900.0-rc.3
ng-packagr                         9.0.0-rc.2
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Anything else relevant?**
ng serve is working correctly - Shold not be reported as problem, as it follows specs:
https://sass-lang.com/documentation/at-rules/use

**Comment by alan-agius4** [comment] 2019-12-05 08:24
Hi @tomanovy, 

1.  The `at-rule-no-unknown` is not a valid tslint rule. In fact this is provided by stylelint https://stylelint.io/user-guide/rules/at-rule-no-unknown thus the first error is genuine. 

1. I am unable to replicate the second error, In the error message attached above, I am seeing classes where were not provided in the example above. Maybe it's related to those.

![image](https://user-images.githubusercontent.com/17563226/70217214-01478980-1741-11ea-8dda-c0d06af149d2.png)

**Comment by tomanovy** [comment] 2019-12-06 19:34
Thanks for feedback, first isue - i get it..., I'll try to create small demo. with ng serve I'ts ok, but with `ng build my-library` I'm still getting that error:

ERROR: Invalid CSS after "    @include mi": expected "}", was ".button-size("
An unhandled exception occurred: Invalid CSS after "    @include mi": expected "}", was ".button-size("
See "/tmp/ng-9lRoDM/angular-errors.log" for further details.

**Comment by ahnpnl** [comment] 2019-12-09 10:24
Hi,

I ran into the issue with using scss `@use` too. This is my [repo](https://github.com/ahnpnl/receiver-multiple-decorators/tree/angular-v9). The error when I run `ng serve` is
```
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/dist/cjs.js??ref-
-15-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
  ╷
5 │   @include square(10px);
  │   ^^^^^^^^^^^^^^^^^^^^^
  ╵
  C:\Users\apham3\test-project\src\styles.scss 5:3  root stylesheet

```
I did add `stylePreprocessorOptions` in `angular.json` as well as define a test mixin called `square` in `_mixins.scss`.

Switch back to `@import` works.

**Comment by protyliss** [comment] 2019-12-17 05:54
It's seems to be required custom-webpack config for now.
Many additional packages and angular.json modifications were required.
I think should wait for official update.
Because webpack is hard to set up.

**Comment by alan-agius4** [comment] 2019-12-30 07:44
@ahnpnl, the failure you are seeing is expected.

To use members you need to use it via a namespace example
```scss
@use "mixins";

.test {
  @include mixins.square(10px);
}
```

More info about the `@use` can be found here: https://sass-lang.com/documentation/at-rules/use

@tomanovy, please provide a reproduction. Thanks.

**Comment by johncrim** [comment] 2019-12-30 18:34
FWIW, I'm using a mix of `@use` and `@import` in my SCSS right now, plus stylelint, and builds are working fine using @angular/cli 9.0.0-rc.7.

RE the stylelint issue (if that's still an issue), take a look at [stylelint-config-recommended-scss](https://github.com/kristerkari/stylelint-config-recommended-scss/blob/master/index.js) - it looks like you should disable `at-rule-no-unknown` and enable `scss/at-rule-no-unknown` when linting scss files.

Or, you can just use the config from `stylelint-config-recommended-scss` by:

```bash
yarn add stylelint-config-recommended-scss --dev
```

And then make sure that your stylelint.config extends `stylelint-config-recommended-scss`. 

Here's the contents of my `stylelint.config.js` file:

```js
module.exports = {
  extends: 'stylelint-config-recommended-scss',
  rules: {
    // Angular elements are not known selectors, disable rule
    'selector-type-no-unknown': null,
    // We use scss so we can organize selectors in a meaningful way, including duplicates.
    'no-duplicate-selectors': null,
    // Allow empty SCSS files, for now
    'no-empty-source': null
  }
};
```

**Comment by alan-agius4** [comment] 2020-01-06 17:03
Closing as we are unable to replicate the issue.

If the problem persists please open a new issue with a reproduction.

Thanks

**Closed by alan-agius4** 2020-01-06 17:03 UTC
Labels: need: repro steps
