### ISSUE TITLE
npm i -g angular-cli fails on windows 10

### ISSUE THREAD

**Issue by HansS** [angular/angular-cli#385] opened 2016-04-01 09:44 UTC
```
> npm i -g angular-cli
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
C:\Users\Hans\AppData\Roaming\npm\ng -> C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\bin\ng

> broccoli@1.0.0-beta.6 postinstall C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\node_modules\broccoli
> multidep test/multidep.json

broccoli-plugin 1.0.0: Installing
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\assetgraph-builder\node_modules\node-pre-gyp requires rc@'~1.1.0' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\assetgraph-builder\node_modules\rc,
npm WARN unmet dependency which is version 0.5.5
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires glob@'~5.0.15' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\glob,
npm WARN unmet dependency which is version 4.0.6
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires node-gyp@'~3.0.3' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\node-gyp,
npm WARN unmet dependency which is version 3.1.0
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires osenv@'~0.1.3' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\osenv,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires request@'~2.65.0' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\request,
npm WARN unmet dependency which is version 2.47.0
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires semver@'~5.0.3' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\semver,
npm WARN unmet dependency which is version 4.3.6
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm requires tar@'~2.2.1' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\tar,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\phonegap\node_modules\localtunnel\node_modules\request requires form-data@'~0.0.3' but will load npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\phonegap\node_modules\form-data,
npm WARN unmet dependency which is version 0.1.4
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\phonegap\node_modules\phonegap-build-api\node_modules\request requires form-data@'~0.0.3' but will load
npm WARN unmet dependency C:\Users\Hans\AppData\Roaming\npm\node_modules\phonegap\node_modules\form-data,
npm WARN unmet dependency which is version 0.1.4
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hans\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\npm\\bin\\npm-cli.js" "install" "broccoli-plugin@1.0.0"
npm ERR! node v5.3.0
npm ERR! npm  v2.14.21
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package yo@1.6.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-element@1.1.0 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-fluxible@1.2.4 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-g@0.0.1 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-greenfield@1.6.1 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-ionic@0.8.0 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-jsmodule@0.2.0 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-module@0.0.2 wants yo@>=1.0.0-rc.1
npm ERR! peerinvalid Peer generator-n@0.0.6 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-node-mocha@0.1.0 wants yo@~1.1.2
npm ERR! peerinvalid Peer generator-refactoru-html@0.5.0 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-skeletor@0.6.0 wants yo@>=1.0.4

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\node_modules\broccoli\test\multidep\broccoli-plugin-1.0.0\npm-debug.log
Error: npm exited with exit code 1, signal null
    at ChildProcess.<anonymous> (C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\node_modules\multidep\index.js:90:28)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
C:\Users\Hans\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hans\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "angular-cli"
npm ERR! node v5.3.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE

npm ERR! broccoli@1.0.0-beta.6 postinstall: `multidep test/multidep.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the broccoli@1.0.0-beta.6 postinstall script 'multidep test/multidep.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the broccoli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     multidep test/multidep.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs broccoli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls broccoli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Hans\npm-debug.log
npm ERR! code 1

Hans@HP-HANS C:\Users\Hans
> node -v
v5.3.0

Hans@HP-HANS C:\Users\Hans
> npm -v
3.7.1

Hans@HP-HANS C:\Users\Hans
>
Hans@HP-HANS C:\Users\Hans
>
Hans@HP-HANS C:\Users\Hans
> ng --version
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\bin\ng'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

Hans@HP-HANS C:\Users\Hans
> npm info angular-cli

{ name: 'angular-cli',
  time:
   { modified: '2016-03-30T18:10:47.060Z',
     created: '2014-10-07T04:34:38.078Z',
     '1.0.0': '2014-10-07T04:34:38.078Z',
     '0.0.0': '2014-10-11T11:38:24.914Z',
     '0.0.1': '2015-08-03T17:12:04.553Z',
     '0.0.2': '2015-10-18T17:46:40.146Z',
     '0.0.3': '2015-10-18T21:42:52.445Z',
     '0.0.4': '2015-10-19T01:14:13.216Z',
     '0.0.5': '2015-10-19T09:14:01.712Z',
     '0.0.6': '2015-10-19T09:36:51.644Z',
     '0.0.7': '2015-10-19T11:48:24.233Z',
     '0.0.8': '2015-10-19T11:51:59.318Z',
     '0.0.9': '2015-10-19T21:18:13.725Z',
     '0.0.10': '2015-10-19T22:18:13.091Z',
     '0.0.11': '2015-11-03T05:03:06.345Z',
     '0.0.12': '2015-11-15T10:10:48.551Z',
     '0.0.13': '2015-12-04T17:16:43.662Z',
     '0.0.14': '2015-12-05T01:40:39.377Z',
     '0.0.15': '2015-12-05T05:50:59.226Z',
     '0.0.16': '2015-12-10T12:23:28.722Z',
     '0.0.17': '2015-12-14T19:37:08.400Z',
     '0.0.18': '2015-12-15T12:51:47.990Z',
     '0.0.19': '2015-12-15T18:23:33.077Z',
     '0.0.20': '2015-12-15T20:39:55.357Z',
     '0.0.22': '2016-02-20T00:36:56.908Z',
     '0.0.23': '2016-02-20T01:44:13.897Z',
     '0.0.24': '2016-02-25T17:41:20.619Z',
     '0.0.25': '2016-03-10T02:10:05.410Z',
     '0.0.26': '2016-03-23T00:39:46.402Z',
     '0.0.27': '2016-03-23T22:05:56.538Z',
     '0.0.28': '2016-03-28T22:39:45.766Z',
     '0.0.29': '2016-03-30T18:10:47.060Z' },
  maintainers:
   [ 'angularcore <angular-core+npm@google.com>',
     'rodyhaddad <npm@rodyhaddad.com>' ],
  description: 'CLI tool for Angular2',
  versions:
   [ '0.0.0',
     '0.0.1',
     '0.0.2',
     '0.0.3',
     '0.0.4',
     '0.0.5',
     '0.0.6',
     '0.0.7',
     '0.0.8',
     '0.0.9',
     '0.0.10',
     '0.0.11',
     '0.0.12',
     '0.0.13',
     '0.0.14',
     '0.0.15',
     '0.0.16',
     '0.0.17',
     '0.0.18',
     '0.0.19',
     '0.0.20',
     '0.0.22',
     '0.0.23',
     '0.0.24',
     '0.0.25',
     '0.0.26',
     '0.0.27',
     '0.0.28',
     '0.0.29' ],
  'dist-tags': { latest: '0.0.29' },
  readmeFilename: 'README.md',
  homepage: 'https://github.com/angular/angular-cli',
  keywords: [],
  repository:
   { type: 'git',
     url: 'git+https://github.com/angular/angular-cli.git' },
  author: 'Angular Authors',
  bugs: { url: 'https://github.com/angular/angular-cli/issues' },
  license: 'MIT',
  contributors:
   [ 'Rody Haddad <npm@rodyhaddad.com> (http://rodyhaddad.com/)',
     'Igor Minar <igor@angularjs.org>' ],
  version: '0.0.29',
  main: 'lib/cli/index.js',
  trackingCode: 'UA-8594346-19',
  bin: { ng: './bin/ng' },
  scripts:
   { test: 'node tests/runner',
     lint: 'eslint -c eslint.json \'./**/*.js\' ' },
  engines: { node: '>= 4.1.0' },
  dependencies:
   { broccoli: '^1.0.0-beta.6',
     'broccoli-caching-writer': '^2.2.1',
     'broccoli-concat': '^2.2.0',
     'broccoli-funnel': '^1.0.1',
     'broccoli-merge-trees': '^1.1.1',
     'broccoli-writer': '^0.1.1',
     chalk: '^1.1.1',
     'ember-cli': '2.4.2',
     exit: '^0.1.2',
     'fs-extra': '^0.26.6',
     leek: '0.0.21',
     lodash: '^4.6.1',
     multidep: '^2.0.0',
     resolve: '^1.1.7',
     shelljs: '^0.6.0',
     'silent-error': '^1.0.0',
     'symlink-or-copy': '^1.0.1',
     typescript: '^1.8.7',
     typings: '^0.7.9' },
  'ember-addon': { paths: [ './addon/ng2/' ] },
  devDependencies:
   { chai: '^3.5.0',
     'clang-format': '^1.0.37',
     eslint: '^2.4.0',
     'exists-sync': '0.0.3',
     glob: '^7.0.3',
     minimatch: '^3.0.0',
     mocha: '^2.4.5',
     rewire: '^2.5.1',
     through: '^2.3.8',
     tslint: '^3.6.0',
     'walk-sync': '^0.2.6' },
  gitHead: 'c3c1612d534d0a975afeee167ea685c9617f940c',
  dist:
   { shasum: '4c79ae7dd5faf61ee0732f35a68dc45786d1c3ed',
     tarball: 'https://registry.npmjs.org/angular-cli/-/angular-cli-0.0.29.tgz' },
  directories: {} }
```

**Comment by hansl** [comment] 2016-04-05 22:24
Dupe of #389

**Closed by hansl** 2016-04-05 22:24 UTC

**Comment by sfjadi2010** [comment] 2016-11-13 23:03
Experiencing same issue #389.
