### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule

### ISSUE THREAD

**Issue by domdeger** [angular/angular-cli#6207] opened 2017-05-06 16:17 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.2
node: 7.9.0
os: win32 x64
@angular/animations: 4.1.1
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/compiler-cli: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/platform-server: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2

### Repro steps.

I have an Angular4 project with 2 libs for outsourcing common stuff of my project. The second lib depends on the first. while the Angular4 project depends on both. 
For development i use npm link to make the dependencies available. My problem is that i cant compile then, because i get the error message `
"ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in C:/git/eds/eds-frontend/no
de_modules/ui-common/node_modules/@angular/core/core.d.ts, resolving symbol CommonUiLibModule in C:/git/eds/eds-frontend/node_modules/ui-common/src/CommonUiLibModule.ts, resolving symbol CommonUiLibModule in C:/git/eds/eds-frontend/node_modules/ui-common/src/CommonUiLibM
odule.ts"
`

I if i delete the node_modules folder of the linked projects, i can compile without issues. But i need the node_modules for my active development. Do you have any idea how i can resolve this issue. I did quiet a lot of reasearch on this topic but could not find a solution myself.

My ts config looks similar in alle projects like this: 

`{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "outDir": "../dist",
    "declaration": true,
    "sourceMap": true,
    "rootDir": "."
  },
  "lib": ["es6"],
  "angularCompilerOptions": {
    "genDir": "../dist",
    "entryModule": "VulnDbServiceLibModule#VulnDbServiceLibModule",
    "skipMetadataEmit" : false
  },
  "include": [
    "**/*.ts",
    "*.ts"
  ],
  "paths": { "@angular/*": ["../node_modules/@angular/*"] },
  "exclude": [
    "../node_modules",
    "**/node_modules/*"
  ]
}`

**Comment by filipesilva** [comment] 2017-05-08 10:57
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/3854. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-05-08 10:57 UTC
