### ISSUE TITLE
Error when generating app-shell

### ISSUE THREAD

**Issue by tdesvenain** [angular/angular-cli#8825] opened 2017-12-11 09:48 UTC
### Versions
```
Angular CLI: 1.6.0
Node: 6.11.5
OS: linux x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0

yarn 1.3.2 (same with npm 3.10.10)
```

### Repro steps

* ng new testshell
* set angular 5.1.0 and add @angular/router
* npm install
* ng generate component home
* add router-outlet
* setup routes like that:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { RouterModule, Routes } from '@angular/router';

import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';

const appRoutes: Routes = [
  { path: '', component: HomeComponent },
]

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent
  ],
  imports: [
    BrowserModule, RouterModule.forRoot(appRoutes)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### Observed behavior
```
[~/projects/testshell]$ ng generate app-shell --route shell                                                                                       *[master] 
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at Class.run (/home/tde/projects/testshell/node_modules/@angular/cli/commands/generate.js:110:63)
    at resolve (/home/tde/projects/testshell/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at Class.validateAndRun (/home/tde/projects/testshell/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/home/tde/projects/testshell/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)

```

**Comment by Shiroh1ge** [comment] 2017-12-11 12:36
I was getting the same error, but I figured out I was entering the wrong command.
What you need to do is either:

```
ng generate app-shell my-loading-shell   --universal-app=universal-app --route=app-shell-path 
```
or
```
ng generate app-shell [ --universal-app <universal-app-name>] [ --route <route>] // notice the brackets
```

**Comment by Brocco** [comment] 2017-12-11 16:36
Closing...
Duplicate of #8793

**Closed by Brocco** 2017-12-11 16:36 UTC
