### ISSUE TITLE
Bug in AOT mode with Angular 5:  Cannot determine the module for class

### ISSUE THREAD

**Issue by quanterion** [angular/angular-cli#8047] opened 2017-10-13 17:40 UTC
### Steps to reproduce:
1) ng new myapp
2) change angular version to 5.0.0-rc.2 in package.json, npm install
3) ng serve --aot
4) change title value in app.component.ts
5) In console appears error: ERROR in Error: Cannot determine the module for class AppComponent in C:/myapp/src/app/app.component.ts! Add AppComponent to the NgModule to fix it.

PS: ng serve without aot works perfectly, downgrading Angular to 4.x also works ok.

Angular CLI: 1.5.0-rc.0
Node: 8.7.0
OS: win32 x64
Angular: 5.0.0-rc.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cli: 1.5.0-rc.0
angular-devkit/build-optimizer: 0.0.27
angular-devkit/core: 0.0.20
angular-devkit/schematics: 0.0.33
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.0-rc.0
schematics/angular: 0.0.45
typescript: 2.5.3
webpack: 3.7.1

**Comment by hiepxanh** [comment] 2017-10-13 23:26
can you show your app-module.ts ?

**Comment by quanterion** [comment] 2017-10-14 05:50
It's generated with ng new, without changes! And it always successfully compiles the first time. The error appears after first rebuild.

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

**Comment by hiepxanh** [comment] 2017-10-14 09:51
you said `change title in app.component.ts` what actually did you do ? can you update to 1.5.0.RC-0 ? maybe it can resolve your problem

**Comment by quanterion** [comment] 2017-10-15 19:35
hiepxanh, please look carefully to the first issue message, it has the information that the project generated and served with 1.5.0-rc.0

**Comment by ocombe** [comment] 2017-10-16 09:05
Hello, closing this as it is a duplicate of https://github.com/angular/angular-cli/issues/7986

**Closed by ocombe** 2017-10-16 09:05 UTC
