### ISSUE TITLE
Accessing root address is not redirecting to base href url

### ISSUE THREAD

**Issue by npnm** [angular/angular-cli#16077] opened 2019-11-06 09:58 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.3.9

### Description

 

With @angular/cli v8.3.17, if you create a basic angular application and set the base href (e.g. "/test/")  then when you access http://localhost:4200 instead of http://localhost:4200/test/, it will not redirect to http://localhost:4200/test/. It will just show a white page containing below message:
```
Cannot GET /
```
It was working in Angular 7. "@angular/cli": "7.3.9"
Even if we access http://localhost:4200, it used to redirect to http://localhost:4200/test/ automatically and shows the website.

## 🔬 Minimal Reproduction

**Working example**
using *"@angular/cli": "7.3.9"*
```
ng new AngHost7
cd AngHost7
ng serve --baseHref=/test/
```
Open browser and access http://localhost:4200.  It will redirect to http://localhost:4200/test/ and shows the website

**Not working example (Issue)**
using *"@angular/cli": "8.3.17" or "8.0.6"*
```
ng new AngHost8
cd AngHost8 
ng serve --baseHref=/test/
```
Open browser and access http://localhost:4200.  It will not redirect to http://localhost:4200/test/. It will just show a white page with "Cannot get GET /" message

_Setting "baseHref": "/test/"  property in **angular.json** file also will give same result._

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.17
Node: 10.15.3
OS: win32 x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.17
@angular-devkit/build-angular     0.803.17
@angular-devkit/build-optimizer   0.803.17
@angular-devkit/build-webpack     0.803.17
@angular-devkit/core              8.3.17
@angular-devkit/schematics        8.3.17
@angular/cli                      8.3.17
@ngtools/webpack                  8.3.17
@schematics/angular               8.3.17
@schematics/update                0.803.17
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by alan-agius4** [comment] 2019-11-06 10:39
Duplicate of #14925

**Closed by alan-agius4** 2019-11-06 10:39 UTC
