### ISSUE TITLE
Cannot find module '@angular/core' after new update

### ISSUE THREAD

**Issue by keithmichelson** [angular/angular-cli#2823] opened 2016-10-21 23:56 UTC
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --
version` and paste the result here:

Can't run any ng commands all same error

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Updated the cli from beta 14 to beta 18 using all 6 steps.
ng init and all other ng commands give me "Cannot find module '@angular/core'"

### The log given by the failure.
> Normally this include a stack trace and some more information.

Error: Cannot find module '@angular/core'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> 
....

**Comment by shicechi** [comment] 2016-10-22 01:29
Just encountered this issue as well.
To fix: run `npm install` and try again.

**Comment by keithmichelson** [comment] 2016-10-22 03:38
@shicechi Thanks for the reply. I just did that after deleting the node_modules. It does work now but I never ran the ng init command. Did you do that, hopefully it doesn't cause future problems?

**Comment by shicechi** [comment] 2016-10-22 03:44
@keithmichelson I did run the `ng init` command though. But instead of skipping all the file checks, inspect each by typing in <kbd>d</kbd> to see the difference and modify the files accordingly. Some config files do actually need a override for this update. I so far haven't encountered any other problems but I could be wrong.

**Comment by keithmichelson** [comment] 2016-10-22 08:14
@shicechi Thanks, I just went through and did the same just to make sure, luckily that command worked after the npm install.

**Comment by filipesilva** [comment] 2016-10-27 16:05
Dupe of https://github.com/angular/angular-cli/issues/2410, fixed by https://github.com/angular/angular-cli/pull/2870

**Closed by filipesilva** 2016-10-27 16:05 UTC
