### ISSUE TITLE
Possibility to add global styles in karma tests

### ISSUE THREAD

**Issue by andreasrueedlinger** [angular/angular-cli#6769] opened 2017-06-22 08:52 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions.
@angular/cli: 1.1.2
node: 6.9.1
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.2
@angular/compiler-cli: 4.2.4

### Repro steps.
For a normal build all the styles from app.styles are preprocessed and included in the styles bundle. How can this bundle be generated and included also in tests (karma)?
Motivation to use styles in test: angular material requires a theme setup to work correctly/not outputting tons of warnings.

**Comment by filipesilva** [comment] 2017-06-26 16:38
I understand the motivation for this feature, but it might be harder than it sounds like due to the way builds are done for tests. I'll look into it if I have the time.

**Comment by andreasrueedlinger** [comment] 2017-11-03 14:37
any update on this?

**Comment by dhilt** [comment] 2018-02-10 19:51
Maybe I missed something, but the following works in my case.

**karma.conf.js**

```
module.exports = function (config) {
  config.set({
    ...
    files: [
      './tests/misc/styles.css'
    ],
    ...
  });
};
```

Also, it could be a path similar to './node_modules/.../bootstrap.css'

**Comment by alan-agius4** [comment] 2018-10-30 09:09
Duplicate of https://github.com/angular/angular-cli/issues/11072 and solved by https://github.com/angular/angular-cli/pull/12371

**Closed by alan-agius4** 2018-10-30 09:09 UTC
