### ISSUE TITLE
ng serve does not reload on changes in beta.28.3

### ISSUE THREAD

**Issue by emazv72** [angular/angular-cli#4355] opened 2017-02-02 14:30 UTC
### OS?
Windows 10

### Versions.

angular-cli: 1.0.0-beta.28.3
node: 6.9.5
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

Chrome 56.0.2924.87

### Repro steps.

- ng new test-app
- cd test-app & npm install & ng serve
- add a console.log line to app.component.ts

### The log given by the failure.

- node console shows

webpack: compiled successfully

- browser console shows 

App updated. Recompiling... Nothing changed.

### Mention any other details that might be useful.

Hash shown on node console never changes.

It works with v1.0.0-beta.26.

**Comment by Brocco** [comment] 2017-02-02 14:45
Duplicate of #4338

**Closed by Brocco** 2017-02-02 14:45 UTC
