### ISSUE TITLE
HTML minification

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular-cli#3459] opened 2016-12-08 04:52 UTC
Trying to track down some build size issues and at first glance it seems like there's no HTML minification being performed even in a prod build. I'm guessing this was either never in place or was lost with the removal of html-loader. What's the roadmap here? Is the AOT compiler supposed to handle this somehow? If not, can we add a loader that at least does the minification? 

### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 6.9.1
os: win32 x64

**Comment by mattdistefano** [comment] 2016-12-08 17:16
Benchmarked this on my own project.

With AOT - my main bundle was around 606kb without html minification and 602kb with. 
Without AOT - my main bundle was around 263kb without html minification and 255kb with.

Numbers are for the pre-gzip prod files. I imagine the gzip reduces the difference further.

**Comment by hansl** [comment] 2016-12-08 19:23
We are discussing using `html-loader` again, but there are other issues that arise when using it.

Closing this as a dupe of #3415

**Closed by hansl** 2016-12-08 19:23 UTC

**Comment by mattdistefano** [comment] 2016-12-08 19:28
@hansl Personally I'd like to see this left open unless you want to change #3415 to a general "Fix what we lost by removing html-loader" ticket. Yeah, html-loader does both html minification and image fingerprinting, but otherwise there's no relation between the two feature requests - you can have html minification with fingerprinting and fingerprinting without minification.

**Comment by hansl** [comment] 2016-12-08 21:45
We will not do html minification unless we implement html-loader, so they're related.

**Comment by mattdistefano** [comment] 2016-12-08 21:53
What's the reasoning for that? It shouldn't be difficult to create a loader that _only_ does html minification if you decide html-loader has too much other baggage to deal with.
