### ISSUE TITLE
It takes 50sec to build the empty app

### ISSUE THREAD

**Issue by simonech** [angular/angular-cli#3613] opened 2016-12-17 17:17 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

### Versions.

```
C:\Projects\angular-test\angular2_hello_world>ng -v
angular-cli: 1.0.0-beta.22-1
node: 6.9.1
os: win32 x64
```

### Repro steps.

```
ng new sampleapp
cd sampleapp
ng serve
** NG Live Development Server is running on http://localhost:4200. **
Hash: 93f32c205847c2238406
Time: 48413ms
chunk    {0} main.bundle.js, main.bundle.map (main) 4.83 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 9.99 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.22 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: bundle is now VALID.
```

### Mention any other details that might be useful.

Event `ng -v` takes forever

**Comment by baruchvlz** [comment] 2016-12-18 05:29
See #891.

**Comment by simonech** [comment] 2016-12-18 08:46
By going through the various issues listed it looks like the non-admin issues was fixed in beta6.
But I'll try running as admin and see what happens

**Comment by simonech** [comment] 2016-12-18 11:45
Even running as admin it takes 30sec just to output the `ng help`

**Comment by filipesilva** [comment] 2016-12-30 14:50
Dupe of https://github.com/angular/angular-cli/issues/1980.

**Comment by filipesilva** [comment] 2016-12-30 14:50
Well, sorta dupe. It's just that it's contained in the other one.

**Closed by filipesilva** 2016-12-30 14:50 UTC
