### ISSUE TITLE
vendor.bundle.js syntax error on IE10 Windows 7

### ISSUE THREAD

**Issue by CedN** [angular/angular-cli#8844] opened 2017-12-12 10:44 UTC
### Versions
```
Angular CLI: 1.5.4
Node: 8.6.0
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.8.1
```
Internet Explorer version 10.0.9200.17609

### Repro steps

* Step 1: install angular cli 1.5.4
* Step 2: create new app with ```ng new sample```
* Step 3: install and uncomment everything in the polyfill.ts file except ```web-animation.js```
* Step 4: ng serve
* Step 5: open app on IE 10 with console

### Observed behavior
The IE console displays this message:
```
SCRIPT1002: Syntax Error
vendor.bundle.js, Line 446 Character 1
```
The source line starts with:
```
eval("/* WEBPACK VAR INJECTION */(function(__resourceQuery) {\n\n/* global __resourceQuery ...
```
![dev mode console screenshot](https://user-images.githubusercontent.com/4160253/33880316-90b830a0-df31-11e7-9b96-b77d20204b55.png)

### Desired behavior
What should I do to make it work?

### Mention any other details that might be useful (optional)
I try to serve the application in production mode with ```ng serve --prod```. The IE console displays a similar message:
```
SCRIPT1002: Syntax Error
main.6452b0e0d49fae94852f.bundle.js, Line 1 Character 9106
```
The source fragment starts with: 
```
const r=n("VtmP"), ...
```
the keyword const are not supported by IE 10!

![prod mode console screenshot](https://user-images.githubusercontent.com/4160253/33880317-90d188fc-df31-11e7-9ee2-17c911e75279.png)

**Comment by fwchen** [comment] 2017-12-12 13:32
+1,but build work well

**Comment by CedN** [comment] 2017-12-12 13:46
@clydin says in issue #8596 the live reload feature of the webpack-dev-server require ES2015 but IE10 doesn't support it. 

Using ```--no-live-reload``` solves the error. 

But i don't understand why an error occurs in prod mode?

**Comment by clydin** [comment] 2017-12-14 14:12
`ng serve` uses live reload by default in all cases as it's the defining characteristic of the command (i.e., a development server without live reload is of fairly minimal utility).
The reason the error originates from the main bundle instead of vendor in production is because the vendor bundle is combined and optimized with the main bundle.  This allows for more comprehensive size reductions in the final output.

**Comment by clydin** [comment] 2017-12-14 16:10
Closing as things appear to be working as intended.  Please re-open if you feel this is in error.

**Closed by clydin** 2017-12-14 16:10 UTC
Labels: priority: 2 (required), severity3: broken

**Comment by CedN** [comment] 2017-12-18 13:17
The prod build error was due to the URL class usage. So actually there is no more error :)

**Comment by eassymo** [comment] 2017-12-30 01:45
Error persists:

> eval("/* unused harmony export VERSION */\n/* unused harmony export JitC...

Angular CLI: 1.6.3
Node: 9.2.0
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
typescript: 2.5.3
webpack-dev-server: 2.9.2

After applying solutions listed here, we have additional error "SecurityError"

![image](https://user-images.githubusercontent.com/34582073/34450515-a031cecc-ecd0-11e7-872d-760f937a17a6.png)
