### ISSUE TITLE
iOS 9.3 simulator throws "ReferenceError: Can't find variable: SockJS" error for "ng serve -o"

### ISSUE THREAD

**Issue by remisture** [angular/angular-cli#8400] opened 2017-11-08 14:38 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0
Node: 8.5.0
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.5.0
@angular/tsc-wrapped: error
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.
- ng serve -o
- Fire up a simulator device with iOS 9.3
- Access your app at localhost:xxxx

### The log given by the failure.
`ReferenceError: Can't find variable: SockJS`

### Desired functionality.
Local webserver should work in iOS 9.3

**Comment by meiordac** [comment] 2017-11-08 15:28
same for Safari 10.1.2

**Comment by G-Nantel** [comment] 2017-11-09 17:17
same here for safari 10.1.1

**Comment by Tyler-V** [comment] 2017-11-10 15:28
This is an issue with iOS 10.3.3

**Comment by kayode-anthony** [comment] 2017-11-10 20:01
Same on Safari 10.0.2 on Sierra 10.12.2

**Comment by dttung-mario** [comment] 2017-11-13 04:54
Same issue with cli 1.5 here, safari, ios...(not sure the version)

**Comment by FilipeQ** [comment] 2017-11-13 16:52
Same problem with ng serve on Safari

**Comment by lakinmohapatra** [comment] 2017-11-14 11:27
when its going to be fixed ?

**Comment by huhuixin** [comment] 2017-11-15 01:42
Same on Safari 10.1

**Comment by Timmaex** [comment] 2017-11-15 09:21
Should this not be fixed soon? It is preventing us from updating cli, because we want our projects to work on Safari...

**Comment by danielcrisp** [comment] 2017-11-15 11:13
I've found that disabling sourcemaps is a workaround:

```
$ ng serve --aot --no-sourcemap
```

**Comment by clydin** [comment] 2018-01-05 21:19
Built applications (`ng build`) will work on safari.
This issue is caused by `webpack-dev-server` the server used with `ng serve` to perform live-reloading.  It requires basic ES2015 browser support.  Also, due to a bug that was fixed in Safari 11, enabling (the default) source map support causes the issue as well on version less than 11.  Unfortunately without changes to `webpack-dev-server`, this will be an ongoing limitation.

**Closed by clydin** 2018-01-05 21:19 UTC

**Comment by RichardYL** [comment] 2018-02-11 13:36
This bug blocks developing Angular-5 mobile apps on macbook where Safari developer tool is a big plus

**Comment by jenhogan** [comment] 2018-06-20 14:58
Any update on this?
