### ISSUE TITLE
can't consume generated lib when using configured ts paths for imports

### ISSUE THREAD

**Issue by admir86** [angular/angular-cli#11375] opened 2018-06-26 12:15 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit (not sure)
- [ ] schematics
```

### Versions
node: v8.11.1
npm: 6.1.0
Angular CLI: 6.1.0-rc.0
OS: Win10

### Repro steps
- create new ng project with an ng library
- create some components -> see sample [demo-lib-app](https://github.com/admir86/demo-lib-app)
- use `BarService` in `FooComponent`
- import `BarService` in `FooComponent` by using the namespace `@dl/l` (defined in paths area in tsconfig) `"@dl/l/*": ["projects/demo-lib/src/*"]` -> see sample [demo-lib-app](https://github.com/admir86/demo-lib-app)
- build and publish the library (I used [verdaccio](https://github.com/verdaccio/verdaccio) to publish and consume my library)

##### consume library
- create new project that consumes the new library -> see sample [demo-lib-consumer](https://github.com/admir86/demo-lib-consumer)
- install demo-lib-app
- use `BarService` in a consumer component
- try to build it -> ERROR in ./node_modules/@dl/l/fesm5/dl-l.js...

### The log given by the failure
```
ERROR in ./node_modules/@dl/l/fesm5/dl-l.js
Module not found: Error: Can't resolve '@dl/l/lib/deep/bar/bar.service' in 'C:\Source\Repos\demo-lib-consumer\node_modules\@dl\l\fesm5'
```

### Desired functionality
it should be possible to make imports using the defined paths in tsconfig.
consuming lib in the [demo-lib-app](https://github.com/admir86/demo-lib-app) test project via `"demo-lib/*": ["dist/demo-lib/*"]` works fine. but not if the lib is installed in a different project.

**Comment by alan-agius4** [comment] 2018-06-26 15:49
Which version of ng-packagr are you using?

**Comment by alan-agius4** [comment] 2018-06-26 15:54
I think I know what is happening here.

You are naming your deep import path the same as your libaray ‘@dl/l’ this is causing a conflict m. Because internally in ng-packagr we add paths in order for secondary entry to resolve to the primary entry ‘.d.ts’

**Comment by alan-agius4** [comment] 2018-06-26 16:47
This is actually coming from typescript and is by design.

> The compiler does not rewrite module names. module names are considered resource identifiers, and are mapped to the output as they appear in the source

The module names you write are not going to change in the output. the "paths" and "baseURL" are there to tell the compiler where they are going to be at runtime.

Check the comment here https://github.com/Microsoft/TypeScript/issues/9910#issuecomment-234729007 and https://github.com/Microsoft/TypeScript/issues/10866

**Comment by alan-agius4** [comment] 2018-06-27 08:36
Yes correct.

On how to implement and use secondary entry points check
https://github.com/dherges/ng-packagr/blob/master/docs/secondary-entrypoints.md

**Comment by filipesilva** [comment] 2018-08-02 17:38
Closing as answered by @alan-agius4, thanks!

**Closed by filipesilva** 2018-08-02 17:38 UTC
Labels: comp: devkit/build-ng-packagr
