### ISSUE TITLE
`ng test` doesn't watch when first compilation fails

### ISSUE THREAD

**Issue by mrkvon** [angular/angular-cli#7976] opened 2017-10-09 05:41 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.5
node: 8.4.0
os: linux x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4

### Repro steps.

- `ng new testproject`
- introduce a syntax error to `./src/app/app.component.ts`
- run `ng test` and see the error message
- fix the syntax error and save
- doesn't recompile, tests are not rerun

### Desired functionality.

The `watch` should work independently of success/failure of the first compilation.

### Mention any other details that might be useful.

- happened after update 1.3.2 > 1.4.5
- the issue happens only when the first compilation fails. i.e. when the first compilation passes and the next one fails, the further behavior is as expected (still watching and recompiling)

**Comment by hansl** [comment] 2017-10-12 00:31
@mrkvon,

I could reproduce and see the error, but I cannot find the reason. Assigning @filipesilva as he was the one working on the karma plugin last.

**Comment by m-henderson** [comment] 2017-10-12 23:12
@filipesilva will you please reply here with the PR when you fix this issue. I would like to know how you fixed it. Thanks much.

**Comment by filipesilva** [comment] 2017-10-20 10:06
I checked now with the latest version `1.4.9` and it seems to be fixed. 

@m-henderson I believe it was fixed in https://github.com/angular/angular-cli/pull/7933, by forcing TS to always emit even with errors on the first build. This allows webpack to follow the dependency tree and  correctly watch those files for rebuilds.

**Closed by filipesilva** 2017-10-20 10:06 UTC
Labels: command: test, effort2: medium (days), freq3: high, priority: 2 (required), severity3: broken, workaround2: non-obvious
