### ISSUE TITLE
ng g c CLI command is stuck

### ISSUE THREAD

**Issue by sahossai** [angular/angular-cli#8813] opened 2017-12-09 05:33 UTC
Hi,
Whenever i am trying to generate component using CLI command "ng generate component xxx/yyy/zzz --spec false"  is stuck.

Note: I am able to create new project and others command  by CLI command.

I am using 
Angular CLI: 1.5.4
Node: 6.9.4
OS: darwin x64

And My operating system is 
macOS High Sierra
version: 10.13

Thanks in advance.

**Comment by baruchvlz** [comment] 2017-12-10 10:58
You should try upgrading to the latest version of the CLI and verifying if this still happens. To upgrade run:

```shell
npm uninstall --global @angular/cli
npm install --global @angular/cli
```

**Comment by Brocco** [comment] 2017-12-11 16:42
Closing...
Duplicate of #8782

**Closed by Brocco** 2017-12-11 16:42 UTC
