### ISSUE TITLE
github-pages:deploy, baseHref should be case-sensitive

### ISSUE THREAD

**Issue by icepeng** [angular/angular-cli#3773] opened 2016-12-29 00:51 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10, Ubuntu 16.04.1 LTS

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: linux x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/comdpiler-cli: 2.4.1

### Repro steps.
ng new SWPenguin
(Work on project)
ng github-pages:deploy

### The log given by the failure.

> https://icepeng.github.io/swpenguin/main.4e5996aaa2ffa03b9c5b.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
> https://icepeng.github.io/swpenguin/styles.a6c71221f2dfc2c6c594.bundle.css Failed to load resource: the server responded with a status of 404 (Not Found)
> https://icepeng.github.io/swpenguin/inline.8030da0a7ffa279deb05.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
> https://icepeng.github.io/swpenguin/main.4e5996aaa2ffa03b9c5b.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
> https://icepeng.github.io/swpenguin/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
> https://icepeng.github.io/swpenguin/styles.a6c71221f2dfc2c6c594.bundle.css Failed to load resource: the server responded with a status of 404 (Not Found

)

### Mention any other details that might be useful.
https://github.com/angular/angular-cli/blob/290c6e779b799f36f02ae68d51b0c8792b42ea25/packages/angular-cli/commands/github-pages-deploy.ts#L97
I found that this line has a problem. package.json generated by ng new command would be lowercase. But if project name has uppercase letters, a problem occurs.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2017-01-10 11:28
Dupe of https://github.com/angular/angular-cli/issues/3146

**Closed by filipesilva** 2017-01-10 11:28 UTC
Labels: need: investigation, priority: 2 (required)
