### ISSUE TITLE
Basic getting started fails - ENOENT typings

### ISSUE THREAD

**Issue by colemickens** [angular/angular-cli#1030] opened 2016-06-07 06:35 UTC
This is inside a docker container: `FROM docker.io/ubuntu:16.04`

```
root@1263841e0ab1:/opt/polykube/www/project# ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.5
node: 4.2.6
os: linux x64
```

Repro steps:

```
ng new project
cd project
ng build
```

Failure (full log):

```
root@1263841e0ab1:/opt/polykube/www# ng new project
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing ng2
  create .clang-format
  create .editorconfig
  create src/app/project.component.css
  create src/app/project.component.html
  create src/app/project.component.spec.ts
  create src/app/project.component.ts
  create src/app/environment.ts
  create src/app/index.ts
  create src/app/shared/index.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/system-config.ts
  create src/tsconfig.json
  create src/typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config/environment.dev.ts
  create config/environment.js
  create config/environment.prod.ts
  create config/karma-test-shim.js
  create config/karma.conf.js
  create config/protractor.conf.js
  create e2e/app.e2e.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create e2e/typings.d.ts
  create .gitignore
  create package.json
  create public/.npmignore
  create tslint.json
  create typings.json
Installed packages for tooling via npm.

root@1263841e0ab1:/opt/polykube/www# cd project

root@1263841e0ab1:/opt/polykube/www/project# ng build
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Build failed.
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, lstat 'typings'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at symlink (/opt/polykube/www/project/node_modules/angular-cli/node_modules/symlink-or-copy/index.js:60:26)
    at symlinkOrCopySync (/opt/polykube/www/project/node_modules/angular-cli/node_modules/symlink-or-copy/index.js:55:5)
    at /opt/polykube/www/project/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (/opt/polykube/www/project/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/opt/polykube/www/project/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/opt/polykube/www/project/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/opt/polykube/www/project/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (/opt/polykube/www/project/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/opt/polykube/www/project/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (/opt/polykube/www/project/node_modules/angular-cli/lib/broccoli/angular2-app.js:85:7)
    at new Angular2App (/opt/polykube/www/project/node_modules/angular-cli/lib/broccoli/angular2-app.js:51:41)
    at module.exports (/opt/polykube/www/project/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/opt/polykube/www/project/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/opt/polykube/www/project/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/opt/polykube/www/project/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/opt/polykube/www/project/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/build.js:15:19)
    at /opt/polykube/www/project/node_modules/angular-cli/node_modules/angular-cli/lib/commands/build.js:32:24
    at lib$rsvp$$internal$$tryCatch (/opt/polykube/www/project/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/opt/polykube/www/project/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /opt/polykube/www/project/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/opt/polykube/www/project/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

**Comment by filipesilva** [comment] 2016-06-07 15:20
Duplicate of https://github.com/angular/angular-cli/issues/901. See https://github.com/angular/angular-cli/issues/901#issuecomment-223327101 for the recommended solution.

**Closed by filipesilva** 2016-06-07 15:20 UTC
