### ISSUE TITLE
What's error and how to fix. Before 5 days, I still install success but today, i install new project then display error

### ISSUE THREAD

**Issue by Englbach** [angular/angular-cli#7683] opened 2017-09-13 14:55 UTC
![1dfs](https://user-images.githubusercontent.com/11801842/30384224-f01da64c-98cd-11e7-8c87-d7eb3d607420.png)

![untitled](https://user-images.githubusercontent.com/11801842/30384169-cada480e-98cd-11e7-804a-0a595af31319.png)

What's error and how to fix. Before 5 days, I still install success but today, i install new project then display error

**Comment by tramel-woodard** [comment] 2017-09-13 15:04
This looks like a duplicate of [Unsupported platform for fsevents](https://github.com/angular/angular/issues/13935). The most popular solution seems to be running `npm i -f`. 

Hope that works for you.

**Comment by Englbach** [comment] 2017-09-13 15:08
npm i -f
after npm install -g @angular/cli

**Comment by Englbach** [comment] 2017-09-13 15:11
![2321](https://user-images.githubusercontent.com/11801842/30385159-7c31d25a-98d0-11e7-9ad4-a1b682f148dd.png)

**Comment by tramel-woodard** [comment] 2017-09-13 15:48
According to @lacolaco, your **fsevents** issue was due to the following:

**`This is exactly Angular's issue. Current package.json requires fsevent as not optionalDependencies but devDependencies. This may be a problem for non-OSX users.`**

Also, I noticed that you were installing into a directory called **\Angular\SampleWebsite**. Does this directory already contain an Angular installation, a **node_modules** folder or a **package.json** file?

If so, this may be a case of **installation intrusion**, when files that are already in existence from a previous install are causing issues with a new install.

Can you **mkdir** a fresh folder outside of this structure and then try your installation in that one?

For example, create the following directory structure: **`C:\Users\lethi\Documents\AngularNew\`**

Then, **cd** to the **AngularNew** directory and run the following command: **`ng new SampleWebsite`**

This should work, based on your current environment.

Please inform us of your progress.

**Comment by SanderElias** [comment] 2017-09-14 06:32
@Englbach You have a rights issue in your users folder.  This has nothing to do with angular angular-cli or even node or npm.  You can fix this by resetting the owner and the user-permissions on the folder. 

You can safely ignore the warnings about fsEvents, that is a lower level dependency that is only needed on OSx systems, and tells you that you don't have that, so it does nothing.

**Comment by Brocco** [comment] 2017-09-22 15:17
Thanks @SanderElias for explaining... closing.

**Closed by Brocco** 2017-09-22 15:17 UTC
