### ISSUE TITLE
`ng` silently exit and do nothing, when run on Linux and `which` is not installed

### ISSUE THREAD

**Issue by KnairWang** [angular/angular-cli#24831] opened 2023-03-09 03:15 UTC
### Command

build, serve, version

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.0

### Description

on Linux, the `ng` command just exit with code `0` and output nothing when the command `which` is not available.
below is code from `@angular/cli/utilities/completion.js`
```javascript
/**
 * Returns whether the user has a global CLI install or `undefined` if this can't be determined.
 * Execution from `npx` is *not* considered a global CLI install.
 *
 * This does *not* mean the current execution is from a global CLI install, only that a global
 * install exists on the system.
 */
async function hasGlobalCliInstall() {
	var _a;
	// List all binaries with the `ng` name on the user's `$PATH`.
	const proc = (0, child_process_1.execFile)('which', ['-a', 'ng']);
	let stdout = '';
	(_a = proc.stdout) === null || _a === void 0 ? void 0 : _a.addListener('data', (content) => {
		stdout += content;
	});
////.... hide other codes
}
```

### Minimal Reproduction

1. on a Linux, uninstall command `which`
2. run `ng version`

### Exception or Error

```text
if the `hasGlobalCliInstall()` is very necessary to `ng` then it should fail obviously: with error message, with non-zero exit code.
else it should go on and process the command like no global installation appears.
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.2.0
Node: 18.14.2 (Unsupported)
Package Manager: npm 9.5.0
OS: linux x64

Angular: 14.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.0
@angular-devkit/schematics      14.2.0
@schematics/angular             14.2.0
ng-packagr                      14.2.2
rxjs                            7.8.0
typescript                      4.7.4
webpack                         5.75.0

Warning: The current version of Node (18.14.2) is not supported by Angular.
```
```


### Anything else relevant?

_No response_

**Comment by alan-agius4** [comment] 2023-03-09 06:19
Please update to a more recent version of the Angular CLI.

Duplicate of https://github.com/angular/angular-cli/issues/23997

**Closed by alan-agius4** 2023-03-09 06:19 UTC
