### ISSUE TITLE
Feature Request : comment tags configuration

### ISSUE THREAD

**Issue by noelmace** [angular/angular-cli#3562] opened 2016-12-14 18:01 UTC
### Versions
angular-cli: local (v1.0.0-beta.22-1, branch: 3452-module-prefix)
node: 6.9.1
os: win32 x64

### Why ?

See https://github.com/angular/angular-cli/issues/3452#issuecomment-267077132

Even if #3452 was proposed (see #3561) with the simplest solution possible (https://github.com/angular/angular-cli/issues/3452#issuecomment-266922450), this lead to some discussions about the possibility to allow this kind of configuration via comments instead of exported string constants.

However, this solution could be far more complexe (and fundamental) than the first one.

### Use case

See #3452 

### Option 1

Something like `/* angular-cli:param-id:value */`

Example : `/* angular-cli:module-prefix:hero */`

**Comment by hansl** [comment] 2016-12-14 22:29
Duplicate of #3452. Let's keep the discussion over there.

**Closed by hansl** 2016-12-14 22:29 UTC
