### ISSUE TITLE
ERROR in Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by adamdport** [angular/angular-cli#17109] opened 2020-02-27 21:10 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Yes, I didn't see this issue before trying to upgrade to Angular 9

### Description

 A clear and concise description of the problem...
When I run `ng serve`, I get a red error, `ERROR in Cannot read property 'push' of undefined`. There is no stack trace.

## 🔥 Exception or Error
<pre><code>
$ ng serve
0% compiling
Compiling @ngx-translate/http-loader : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 679 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 526 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2020-02-27T20:58:39.458Z - Hash: a28c43a5df921416a87c - Time: 8915ms

ERROR in Cannot read property 'push' of undefined
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.3
Node: 10.15.1
OS: win32 x64

Angular: 9.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.900.3
@angular-devkit/build-optimizer    0.900.3
@angular-devkit/build-webpack      0.900.3
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.0.3
@angular/cdk                       9.1.0
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.1.0
@angular/material-moment-adapter   9.1.0
@ngtools/webpack                   9.0.3
@schematics/angular                9.0.3
@schematics/update                 0.900.3
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**
I have 2 projects and a library. Both projects depend on the library. The first project and the library work fine and I have successfully upgraded to Angular 9. The second project gives me this error. I am not sure how to go about debugging this. `--verbose=true` did not give me any helpful output. 

One note is that sometimes it starts spitting out errors about tests after giving me that error? `Cannot find name 'beforeEach'`, `Cannot find name 'it'`, `Cannot find name 'describe'`, `Cannot find name 'expect'`, etc. I didn't run tests, and the printing of these errors is not consistent.

If there is another flag I can pass in to increase the log level I'd be happy to try it to provide more info.

**Comment by petebacondarwin** [comment] 2020-02-27 21:17
Duplicate of https://github.com/angular/angular/issues/35709 - should be fixed by https://github.com/angular/angular/pull/35718.

**Closed by petebacondarwin** 2020-02-27 21:17 UTC
