### ISSUE TITLE
Change the defult path to ng build command

### ISSUE THREAD

**Issue by bootrider** [angular/angular-cli#2223] opened 2016-09-19 14:47 UTC
using the `ng build` command, the result of the process is located at dist/.
if I want to generate the artifacts in other folder I use `ng build -o c:\temp\`
I want to change that folder with out having to explicit specified it in the command line. 

where should I perform changes to achieve my goal?

**Comment by ranst91** [comment] 2016-09-19 15:03
It's my first time using that CLI, Yet it seems that  `"outDir": "dist",`
inside:
`"apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": "assets",
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],`
in the angular-cli.json file is the logical choice.
Try to change the outDir and see if it solves your problem

**Comment by Meligy** [comment] 2016-09-19 20:42
`outDir` doesn't work at the moment. I just opened an issue for it #2230.

It'd be cool to be able to pass the folder to `ng build` directly as well, although it's less important if `outDir` works.

**Comment by bootrider** [comment] 2016-09-19 21:26
@Meligy  it is possible to pass the folder to the command `ng build`, using the -o parameter

**Comment by Meligy** [comment] 2016-09-20 04:42
Oh. In that case, the `outDir` should be the permanent way then, which is now broken as tracked by #2230.

A temporary workaround would be adding the whole command to npm `scripts` in `package.json`.

**Comment by filipesilva** [comment] 2016-09-22 04:26
Dupe of https://github.com/angular/angular-cli/issues/2006

**Closed by filipesilva** 2016-09-22 04:26 UTC
