### ISSUE TITLE
ng new fails with latest version of @angular/cli 

### ISSUE THREAD

**Issue by ea-augustin** [angular/angular-cli#20724] opened 2021-05-08 15:23 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes

When ever i try to install a new angular project. Using the ng new  projectname.

## 🔬 Minimal Reproduction
Run the following command:

ng new app

## 🔥 Exception or Error

<pre><code>

PS D:\Angular> ng new app
? Do you want to enforce stricter type checking and stricter bundle budgets in the workspace?
  This setting helps improve maintainability and catch bugs ahead of time.
  For more information, see https://angular.io/strict Yes
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss
 ]
CREATE app/.editorconfig (274 bytes)
CREATE app/.gitignore (631 bytes)
CREATE app/angular.json (3681 bytes)
CREATE app/package.json (1204 bytes)
CREATE app/README.md (1013 bytes)
CREATE app/tsconfig.json (783 bytes)
CREATE app/tslint.json (3185 bytes)
CREATE app/.browserslistrc (703 bytes)
CREATE app/karma.conf.js (1420 bytes)
CREATE app/tsconfig.app.json (287 bytes)
CREATE app/tsconfig.spec.json (333 bytes)
CREATE app/src/favicon.ico (948 bytes)
CREATE app/src/index.html (289 bytes)
CREATE app/src/main.ts (372 bytes)
CREATE app/src/polyfills.ts (2830 bytes)
CREATE app/src/styles.scss (80 bytes)
CREATE app/src/test.ts (753 bytes)
CREATE app/src/assets/.gitkeep (0 bytes)
CREATE app/src/environments/environment.prod.ts (51 bytes)
CREATE app/src/environments/environment.ts (662 bytes)
CREATE app/src/app/app-routing.module.ts (245 bytes)
CREATE app/src/app/app.module.ts (393 bytes)
CREATE app/src/app/app.component.scss (0 bytes)
CREATE app/src/app/app.component.html (24955 bytes)
CREATE app/src/app/app.component.spec.ts (1048 bytes)
CREATE app/src/app/app.component.ts (208 bytes)
CREATE app/e2e/protractor.conf.js (904 bytes)
CREATE app/e2e/tsconfig.json (274 bytes)
CREATE app/e2e/src/app.e2e-spec.ts (654 bytes)
CREATE app/e2e/src/app.po.ts (274 bytes)
⠼ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: app@0.0.0
npm ERR! Found: jasmine-core@3.6.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\elite\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\elite\AppData\Local\npm-cache\_logs\2021-05-08T15_21_35_632Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.
</code></pre>

## 🌍 Your Environment
🌍 Your Environment
Angular CLI: 11.2.12
Node: 16.1.0
Npm: 7.12.0

**Comment by clydin** [comment] 2021-05-08 15:29
Duplicate of #20719

**Closed by clydin** 2021-05-08 15:29 UTC
