### ISSUE TITLE
Proposal: detect the absence of the `node_modules` folder while running `ng build` or `ng serve`

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular-cli#18393] opened 2020-07-28 21:01 UTC
# 🚀 Feature request

### Command

- [x] build
- [x] serve

### Description
Running `ng build` or `ng serve` in a folder without `node_modules` present results in the following error thrown in terminal:

```
$ ng serve
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
... stacktrace ...
See "/private/var/folders/7d/r6b3nrdj7bn9t_w_dclm6y9r00kg80/T/ng-PRpMHw/angular-errors.log" for further details.
```

This can happen for example after downloading an example app from angular.io website. Example link:

https://angular.io/generated/zips/form-validation/form-validation.zip

### Describe the solution you'd like
The proposal is to handle the case when `node_modules` folder is not present and output a user-friendly error message that would suggest to run `npm install` or `yarn install`.

**Comment by sahilpurav** [comment] 2020-08-16 09:07
Instead of showing a message, how if we automatically do `npm install` or `yarn install`

**Comment by codebriefcase** [comment] 2020-09-11 12:03
Such errors seems to be mind-boggling when I was very new to Angular.
These needs to be exact and clear to the end user.

**Comment by elvisbegovic** [comment] 2020-09-11 13:46
Same with `ng new ap --skip-install && cd ap && ng version`

This is somehow related to https://github.com/angular/angular-cli/issues/10474

**Comment by alan-agius4** [comment] 2021-06-24 11:41
Duplicate of https://github.com/angular/angular-cli/issues/10536

**Closed by alan-agius4** 2021-06-24 11:41 UTC
Labels: comp: angular/cli, freq1: low, severity2: inconvenient, type: bug/fix
