### ISSUE TITLE
ngIf keeps adding element

### ISSUE THREAD

**Issue by christiankadjo** [angular/angular-cli#7260] opened 2017-08-03 15:44 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.6
node: 8.1.3
os: win32 x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic
@angular/router: 4.3.3
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

Windows 7 
### Repro steps.

Hello guys!
I'm having a problem hiding and showing an element depending of a boolean variable in Angular 2.
this is the code for the div to show and hide:

<alert type="danger" *ngIf="showAlert">{{alertMessage}}</alert>
<a href="#" class="btn btn-primary btn-md" type="submit" (click)="showError()">ShowError</a>
              <a href="#" class="btn btn-primary btn-md" type="submit" (click)="hideError()">HideError</a>

And the code of the component :

`import { Component, OnInit, Output, Input, EventEmitter, SecurityContext } from '@angular/core';
import { UserService } from '../user.service';
 
import { User } from '../user'
import { DomSanitizer } from '@angular/platform-browser';
import { FormControl } from '@angular/forms';
@Component({
  selector: 'app-register-form',
  templateUrl: './register-form.component.html',
  styleUrls: ['./register-form.component.css']
})
export class RegisterFormComponent implements OnInit {
  public email: string;
  public nom: string;
  public prenom: string;
  public alerts: any = [];
  constructor(private userService: UserService, sanitizer: DomSanitizer) {
    this.alerts = this.alerts.map((alert: any) => ({
      type: alert.type,
      msg: sanitizer.sanitize(SecurityContext.HTML, alert.msg)
    }));
  }
 
  @Output() onFormClosed = new EventEmitter<boolean>();
  @Output() onError = new EventEmitter<string>();
  showAlert: boolean = false;
  @Input() alertMessage: string;
  showSuccess: boolean = false;
  showInput: boolean = true;
  @Input() successMessage: string;
 
  closeForm() {
    console.log("EVENT FIRED");
    this.showAlert= false;
    this.showSuccess = false;
    this.onFormClosed.emit(true);
  }
 
  updateEmail(event: any) {
    this.email = event.target.value;
  }
 
  updateNom(event: any) {
    this.nom = event.target.value;
 
  }
 
  updatePrenom(event: any) {
    this.prenom = event.target.value;
  }
 
  showError()
  {
    this.showAlert = true;
    this.alertMessage = "Voici mon erreur"
  }
 
  hideError()
  {
    this.showAlert = false;
  }
 
  ngOnInit() {
  }
 
}`

Instead of hiding my element, ngIf directive keeps adding it in my div as shown in this [picture](https://user.oc-static.com/upload/2017/08/03/15017684302497_Sans%20titre.png)

Can you help me on this guys? I started to code with Angular since one month.

Thank you!

**Comment by yogeshgadge** [comment] 2017-08-03 17:31
You may want to post over at stackoverflow to get a response. This is about ngIf or about your code. What makes this issue related to `angular-cli`

**Comment by xtoff** [comment] 2017-08-04 06:33
I have the same issue.. I have worked with Angular 2 since december 2016 and never had this problem before

**Comment by Brocco** [comment] 2017-08-17 15:06
@yogeshgadge is correct, this is a support/coding question, not a bug report for the CLI. Thanks and good luck resolving your issue.

**Closed by Brocco** 2017-08-17 15:06 UTC
