### ISSUE TITLE
ng update fails when there is an npm dependency on a git repo

### ISSUE THREAD

**Issue by ronzeidman** [angular/angular-cli#10775] opened 2018-05-10 08:30 UTC
### Versions
```
Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/cdk                      5.2.5
@angular/cli                      6.0.0
@angular/flex-layout              5.0.0-beta.14
@angular/material                 5.2.5
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              5.5.10
typescript                        2.6.2
webpack                           4.6.0
```

### Repro steps
* Step 1
have a dependency on a git library (from bitbucket in my case)
* Step 2
try to use `ng update @angular/cli`
* Step 3
Registry returned 404 for GET on https://registry.npmjs.org/my-shared-lib

### Observed behavior
```
Registry returned 404 for GET on https://registry.npmjs.org/my-shared-lib
```

### Desired behavior
everything to work

**Comment by intellix** [comment] 2018-05-10 08:46
Just came here to post the same thing. In our case it's a git repository. We're not publishing packages to npm and instead depend on the `prepare` step that was added in npm 5:

```
"ionic-split-pane": "github:xcaliber-tech/ionic-split-pane",
```

Same error as above

**Comment by danletecky** [comment] 2018-05-13 09:57
The same error appears for gzipped tarball (tgz) locations:

`"my-package": "https://mypackagesourceserver.com/my-package.tgz"`

**Comment by Maryna-Yelakova** [comment] 2018-05-14 18:45
I have the same issue. I have performed an upgrade angular packages to v6
================================================================================
The Angular CLI configuration format has been changed, and your existing configuration can
be updated automatically by running the following command:

  ng update @angular/cli
================================================================================ 
I get this error every time I run this command
$ ng update @angular/cli
Registry returned 404 for GET on https://registry.npmjs.org/typescript@

**Comment by louisgv** [comment] 2018-05-21 23:38
Also having the same issue as @Maryna-Yelakova

**Comment by joelebeau1** [comment] 2018-05-23 18:47
Also having this issue trying to run `ng update @angular/cli` with multiple npm dependencies on git repos

**Comment by ashanan** [comment] 2018-05-23 18:51
This looks like the same issue: https://github.com/angular/angular-cli/issues/10167

It's not clear to me why that issue was closed, since it appears to still be broken.  There is a workaround there, though.

Workaround: (haven't tried it yet, so YMMV) remove your private repo dependencies, upgrade, re-add your depenedencies

**Comment by clydin** [comment] 2018-06-07 18:04
Duplicate of #10642

**Closed by clydin** 2018-06-07 18:04 UTC
Labels: comp: cli/update, freq2: medium, severity3: broken, type: bug
