### ISSUE TITLE
v15: Generate angular workspace/application with change detection set to onPush

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#24254] opened 2022-11-16 22:18 UTC
### Command

new

### Description

As a developer, I should be able to generate all my angular applications and their components with changeDetection strategy set to `onPush` by default.

```sh
- npx @angular/cli@15 new control-center --create-application false --strict true --package-manager yarn
- cd control-center
- yarn ng config schematics.@schematics/angular:component.changeDetection OnPush
- yarn ng generate application admin-panel --routing true --style scss
- yarn ng add @angular-eslint/schematics@latest
- ng generate application support-panel --routing true --style scss
```

Neither `projects/admin-panel/src/app/app.component.ts` nor `projects/support-panel/src/app/app.component.ts` contain any change detection strategy

<img width="845" alt="v15_angular_change_detection_onpush" src="https://user-images.githubusercontent.com/13006107/202305789-8c5e04c5-2bdb-4e0f-8878-0babd1a51bf5.png">

### Describe the solution you'd like

Angular CLI should provide a new argument to set change detection globally for all applications/libraries in a workspace
- `npx @angular/cli@15 new control-center --create-application false --strict true --change-detection onPush`

### Describe alternatives you've considered

[Previously](https://github.com/angular/angular-cli/issues/21353#issuecomment-882246989), it was suggested to configure angular cli by executing this command,

- `ng config schematics.@schematics/angular:component.changeDetection OnPush`

however this statement does not behave as expected in comparison to the previous releases (v14 and lower)

**Comment by alan-agius4** [comment] 2022-11-16 22:35
Duplicate of https://github.com/angular/angular-cli/issues/21523

**Closed by alan-agius4** 2022-11-16 22:35 UTC

**Comment by prabh-62** [comment] 2022-11-16 22:50
@alan-agius4 The workaround you mentioned here
- https://github.com/angular/angular-cli/issues/21353#issuecomment-882246989

no longer works for Angular CLI v15. The original issue was closed citing the reason that there is a configuration option available.
- `ng config schematics.@schematics/angular:component.changeDetection OnPush`

However, with v15, this option no longer does anything. At this point, there is no way to generate onPush components by default in angular CLI project.  
Why has this issue been closed without a proper resolution?
