### ISSUE TITLE
One library can't import another library

### ISSUE THREAD

**Issue by lsa-shanghai** [angular/angular-cli#10665] opened 2018-05-05 15:57 UTC
### Versions
```
Angular CLI: 6.0.0
Node: 10.0.0
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.0
@angular-devkit/build-angular      0.6.0
@angular-devkit/build-ng-packagr   0.6.0
@angular-devkit/build-optimizer    0.6.0
@angular-devkit/core               0.6.0
@angular-devkit/schematics         0.6.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.0
@schematics/angular                0.6.0
@schematics/update                 0.6.0
ng-packagr                         3.0.0-rc.2
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.6.0
```

### Repro steps

* Step 1
ng generate library model-lib
ng generate library ui-lib
ng generate application portal
* Step 2
ng build model-lib
* Step 3
import { ModelLibModule } from 'model-lib' in portal module
ng build portal
* Step 4
import { ModelLibModule } from 'model-lib' in ui-lib module
ng build ui-lib

### Observed behavior
```
BUILD ERROR
projects/ui-lib/src/lib/ui-lib.module.ts(3,29): error TS2307: Cannot find module 'model-lib'.
```

### Desired behavior
Library should import other library same as application.

**Comment by hwangzhiming** [comment] 2018-05-07 09:17
Have same issue, even added two libs to tsconfig.json file

**Comment by Etchelon** [comment] 2018-05-08 11:30
Same, it's a pretty critical issue imho. I tried playing with the compiler options "baseUrl" and "path", but the error is always the same during the compilation step with ngc.
Note that the IDE's (VS Code) intellisense works in resolving an import from library 1 written inside a file of library 2, but then the compilation of library 2 fails.

**Comment by aitboudad** [comment] 2018-05-08 11:36
solved that issue by defining `libs` in `paths` see https://github.com/formly-js/ngx-formly/blob/master/tsconfig.json#L20-L22 and for building libs I used a [patch](https://github.com/formly-js/ngx-formly/blob/master/.config/ng-packagr.patch) in ng-packgr to make it work

**Comment by aitboudad** [comment] 2018-05-08 13:29
@Etchelon it's just a temporary fix :) https://github.com/formly-js/ngx-formly/blob/master/package.json#L13

**Comment by aitboudad** [comment] 2018-05-08 18:16
@Etchelon another easy way is to add `paths` in [tsconfig.lib.json](https://github.com/formly-js/ngx-formly/blob/master/src/bootstrap/tsconfig.lib.json)

**Comment by stephanecot** [comment] 2018-05-13 14:46
same here

**Comment by smile2014** [comment] 2018-05-16 15:15
The specified command ("build:lib") is invalid. For a list of available options,
run "ng help".

Did you mean "build"?

**Comment by clydin** [comment] 2018-05-17 15:29
With a library generated with 6.0.2+ this should no longer be an issue.  Support for secondary entry points will be corrected via https://github.com/angular/devkit/pull/933

For an existing library exhibiting the issue, ensure the library that contains the import has its own `tsconfig` and that it has a paths section as described in the previous responses.

**Closed** 2018-05-17 20:48 UTC
Labels: comp: cli/build, comp: cli/generate, freq3: high, severity3: broken

**Comment by allanbond** [comment] 2018-06-04 15:42
> With a library generated with 6.0.2+ this should no longer be an issue.

Can you elaborate on this?

If lib-b depends on lib-a (both created w/6.0.0):

Which library do I need to regenerate for this issue to go away?

What manual change can I make so that both libs function as if they were created w/6.0.2+?

btw, adding paths to lib-b as describe above works---but if this is not the 'official cli' way, I'd rather not use it.

**Comment by eastjie** [comment] 2018-07-17 15:10
It works for me after I have corrected the "paths" of library in "tsconfig.lib.json". I have Angular CLI 6.0.9.

**Comment by maxime1992** [comment] 2018-10-19 09:31
Ok so I've been digging into that issue and found out what was wrong.

For some reason, `/src/tsconfig.app.json` had into `compilerOptions` the following prop:

`"baseUrl": "./",`

Removed that and now everything seems to be working.

**Comment by p1p3** [comment] 2018-11-23 08:02
@maxime1992  Thanks a lot!! I was debugging this for a couple of hours and it was driving me crazy. Thanks a lot.

It happens when you migrate an application from 5.x to latest angular version, in my case it was 7.x. So old tsconfig.app contained that property and was messing the imports from the libraries.

**Comment by maxime1992** [comment] 2019-06-11 11:00
Trying to migrate to v8... this trick doesn't work anymore and `baseUrl` is now required...

I've been stuck on that for 2 hours now :(

**Comment by maxime1992** [comment] 2019-06-11 11:10
Ok, after trying plenty of different things I finally managed to get it to work.

```diff
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -1,16 +1,16 @@
 {
   "compileOnSave": false,
   "compilerOptions": {
-    "baseUrl": ".",
+    "baseUrl": "./",
     "outDir": "./dist/out-tsc",
     "sourceMap": true,
     "declaration": false,
-    "module": "es2015",
+    "module": "esnext",
     "moduleResolution": "node",
     "emitDecoratorMetadata": true,
     "experimentalDecorators": true,
     "importHelpers": true,
-    "target": "es5",
+    "target": "es2015",
     "typeRoots": ["node_modules/@types"],
     "lib": ["es2018", "dom"],
     "paths": {
```

```diff
--- a/tsconfig.app.json
+++ b/tsconfig.app.json
@@ -2,11 +2,7 @@
   "extends": "./tsconfig.json",
   "compilerOptions": {
     "outDir": "./out-tsc/app",
-    "types": [],
-    "paths": {
-      "ngx-hover-opacity": ["projects/ngx-hover-opacity/src/public_api"],
-      "ngx-hover-opacity/*": ["projects/ngx-hover-opacity/src/public_api"]
-    }
+    "types": []
   },
   "include": ["src/**/*.ts"],
```

Might eventually help someone out here :man_shrugging:

**Comment by kcrossman** [comment] 2019-07-25 22:28
Specifically, just adding those two lines to your lib's tsconfig:
`"baseUrl": "./",`
`"module": "esnext",`

**Comment by Saky94** [comment] 2019-07-26 13:29
> Specifically, just adding those two lines to your lib's tsconfig:
> `"baseUrl": "./",`
> `"module": "esnext",`

I just added this in my tsconfig.lib.json, but now my first library can not see components from another library (shared-lib). Do u have any solution for that?

**Comment by kcrossman** [comment] 2019-07-31 16:34
> > Specifically, just adding those two lines to your lib's tsconfig:
> > `"baseUrl": "./",`
> > `"module": "esnext",`
> 
> Hello @kcrossman. I just added this in my tsconfig.lib.json, but now my first library can not see components from another library (shared-lib). Do u have any solution for that?

This is a project I made to test making a library and whatnot, for your reference. It's possibly your tsconfig.json, where you need to specify the path as such:
```
...
    "paths": {
      "shared-lib": [
        "dist/shared-lib"
      ],
      "shared-lib/*": [
        "dist/shared-lib/*"
      ]
    }
```

After which, you have to run `ng build` or `ng build shared-lib` to publish your library to that dist folder. Your code may show red lines but it will work at that point if you just run `ng serve`.

**Comment by fjoalland** [comment] 2019-08-01 21:09
I have the same issue with angular 8, I made a repo to reproduce my error here: https://github.com/fjoalland/multiple-angular-lib/

You just need to follow the steps and you will have the same error as me
`[error] Error: : Unexpected value 'Lib1Module in D:/Documents/multiple-angular-lib/lib1/dist/libs/lib1/libs-lib1.d.ts' imported by the module 'Lib2Module in D:/Documents/multiple-angular-lib/lib2/projects/libs/lib2/src/lib/lib2.module.ts'. Please add a @NgModule annotation.

    at Object.<anonymous> (D:\Documents\multiple-angular-lib\lib2\node_modules\ng-packagr\lib\ngc\compile-source-files.js:73:19)`

DId you manage to find a solution?

**Comment by kcrossman** [comment] 2019-08-01 22:00
> @kcrossman I have the same issue with angular 8, I made a repo to reproduce my error here: https://github.com/fjoalland/multiple-angular-lib/
> 
> You just need to follow the steps and you will have the same error as me
> `[error] Error: : Unexpected value 'Lib1Module in D:/Documents/multiple-angular-lib/lib1/dist/libs/lib1/libs-lib1.d.ts' imported by the module 'Lib2Module in D:/Documents/multiple-angular-lib/lib2/projects/libs/lib2/src/lib/lib2.module.ts'. Please add a @NgModule annotation. at Object.<anonymous> (D:\Documents\multiple-angular-lib\lib2\node_modules\ng-packagr\lib\ngc\compile-source-files.js:73:19)`
> 
> DId you manage to find a solution?

I'll look at your repo and see if I can find something. If you really need this, you could create 3 separate libraries for now and just host them and npm install them independently.

**Comment by kcrossman** [comment] 2019-08-01 22:13
@fjoalland Your repository is not configured correctly to use the normal import rule. You will have to host each library and npm install them to use them. I will copy some commands so that you can re-create your libraries to work...

1. `ng new ng-libs-ws --style=scss --createApplication=false --skip-git --skip-install`
2. cd ng-libs-ws
3. `ng g library ng-lib1 --skip-install`
4. `ng g library ng-lib2 --skip-install`
5. `ng g library ng-lib3 --skip-install`
6. (optional) `ng g application ng-libs-demo --style=scss --routing --minimal --skip-install`
7. `npm i`

At this point, you should be able to import your ng-lib1 where you want to use it. Though, I haven't done this myself. I've only verified the commands work and the initial config looks right...

**Comment by fjoalland** [comment] 2019-08-02 06:29
Merci pour ta réponse.

Cependant, j'ai bien testé et ca ne fonctionne pas. Peut être que j'ai mal expliqué ce que je rechairchais à faire.

Je souhaites pouvoir importer une librairie dans une autre librairie (et non une application angular). Je sais comment importer une librairie dans une application angular, ca fonctionne sans problème. Cependant, j'obtiens une erreur lorsque j'importe une librairie dans une autre librairie avec la commande 'npm link'. Par contre (et c'est la le plus surprenant!), si je déploie ma librairie sur un repository privé (example: nexus), et que je l'importe dans une autre librairie, cela va fonctionner.

J'ai recreer un repository ici!https://

**Comment by fjoalland** [comment] 2019-08-02 06:36
@kcrossman Thank you for your answer.

However, I have tested well and it does not work. Maybe I did not explain what I was trying to do.

I wish I could import a library into another library (and not an angular application). I know how to import a library into an angular application, it works without problems. However, I get an error when I import a library into another library with the 'npm link' command. By cons (and this is the most surprising!), If I deploy my library on a private repository (example: nexus), and I import it into another library, it will work.

I recreated a github reproduisnat my error here with the steps you made: https://github.com/fjoalland/import-lib-angular-in-other-angular-lib

There are two librairies:

- ng-lib1 in ng-libs-ws-bis directory
- ng-lib2 in ng-libs-ws directory

The ng-libs-ws-bis library imports the ng-libs-ws library module
```
import { NgModule } from '@angular/core';
import { NgLib2Component } from './ng-lib2.component';
import {NgLib1Module} from 'ng-lib1';

@NgModule({
  declarations: [NgLib2Component],
  imports: [
    NgLib1Module
  ],
  exports: [NgLib2Component]
})
export class NgLib2Module { }
```

Bellow, the error I got
```

ERROR: : Unexpected value 'NgLib1Module in /home/user/Documents/Test/libs/ng-libs-ws/dist/ng-lib1/ng-lib1.d.ts' imported by the module 'NgLib2Module in /home/user/Documents/Test/libs/ng-libs-ws-bis/projects/ng-lib2/src/lib/ng-lib2.module.ts'. Please add a @NgModule annotation.

An unhandled exception occurred: : Unexpected value 'NgLib1Module in /home/user/Documents/Test/libs/ng-libs-ws/dist/ng-lib1/ng-lib1.d.ts' imported by the module 'NgLib2Module in /home/user/Documents/Test/libs/ng-libs-ws-bis/projects/ng-lib2/src/lib/ng-lib2.module.ts'. Please add a @NgModule annotation.

See "/tmp/ng-cOPw65/angular-errors.log" for further details.
```

On the other hand, if I publish the library ng-libs-ws on my private repository nexus, and install it with the command 'npm install ng-lib2' on ng-libs-ws-bis, it will work.

**Comment by kcrossman** [comment] 2019-08-02 16:34
@fjoalland If they are separate Angular projects, you cannot share them without hosting them in some way and npm installing them. You don't necessarily have to use Nexus, something like [Verdaccio](https://verdaccio.org/) may work better for you.

**Comment by fjoalland** [comment] 2019-08-03 05:35
@krossman thanks a lot I didn't know Verdaccio! It's a great solution to resolve my problem.  
I will try that and tell you if it's working. But I hope that one day, npm link will work with angular library. It's much comfortable to use ng build --watch in a symlink to debug your library in real time.
