### ISSUE TITLE
Barrel for a component should export any shared child folder's barrels

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#586] opened 2016-05-01 22:58 UTC
![image](https://cloud.githubusercontent.com/assets/1202528/14944852/8d5f9a58-0fce-11e6-83dc-5cb90676bbb8.png)

cc @Brocco

**Comment by filipesilva** [comment] 2016-06-04 14:24
Duplicate of https://github.com/angular/angular-cli/issues/585, but correct me if I'm wrong.

**Closed by filipesilva** 2016-06-04 14:24 UTC
Labels: effort: (2) medium, priority: 2 (required)
