### ISSUE TITLE
ng get causes InvalidJsonPath error

### ISSUE THREAD

**Issue by fmorriso** [angular/angular-cli#5886] opened 2017-04-08 12:33 UTC
### Versions.
ps>ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 7.7.2
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.

1. Navigate to an existing directory that was created via ng new, such as ng new angular-hello.
2. Open a prompt at the location of the project directory.   Example c:\projects\angular-hello
3. ng get

### The log given by the failure.
ps>ng get --verbose 
The option '--verbose' is not registered with the get command. Run `ng get --help` for a list of supported options.
InvalidJsonPath
Error: InvalidJsonPath
    at _parseJsonPath (C:\projects\angular-hello\node_modules\@ngtools\json-schema\src\schema-class-factory.js:29:19)
    at _getSchemaNodeForPath (C:\projects\angular-hello\node_modules\@ngtools\json-schema\src\schema-class-factory.js:41
:21)
    at GeneratedSchemaClass.$$get (C:\projects\angular-hello\node_modules\@ngtools\json-schema\src\schema-class-factory.
js:84:22)
    at CliConfig.get (C:\projects\angular-hello\node_modules\@angular\cli\models\config\config.js:31:29)
    at resolve (C:\projects\angular-hello\node_modules\@angular\cli\commands\get.js:25:34)
    at Class.run (C:\projects\angular-hello\node_modules\@angular\cli\commands\get.js:19:16)
    at Class.<anonymous> (C:\projects\angular-hello\node_modules\@angular\cli\ember-cli\lib\models\command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)

### Desired functionality.
Eliminate the InvalidJsonPath error

### Mention any other details that might be useful.

1. ng build of the project works.
2. ng serve of the project works.

**Comment by fmorriso** [comment] 2017-04-08 12:39
[.angular-cli.json.txt](https://github.com/angular/angular-cli/files/907447/default.angular-cli.json.txt)
[package.json.txt](https://github.com/angular/angular-cli/files/907448/package.json.txt)
[build.txt](https://github.com/angular/angular-cli/files/907450/build.txt)

**Comment by fmorriso** [comment] 2017-04-08 12:40
accidentally close issue when I only meant to close the file upload.

**Comment by prestonvanloon** [comment] 2017-04-08 13:26
This is being thrown from [_parseJsonPath](https://github.com/angular/angular-cli/blob/c9d82438fec28080119bc4cbb9d66ab7aae858d3/packages/%40ngtools/json-schema/src/schema-class-factory.ts#L25). 

According to the function comment: `For example, a path of "a[3].foo.bar[2]" would give you a fragment array of ["a", 3, "foo", "bar", 2].` 

Do you get this same error when you specify a path such as `a[3].foo.bar[2]` (i.e. `ng get a[3].foo.bar[2]`)?

**Comment by prestonvanloon** [comment] 2017-04-08 13:50
@sumitarora I can submit a fix for this in a few minutes.

**Comment by sumitarora** [comment] 2017-04-08 13:52
@prestonvanloon sure 👍

**Comment by fmorriso** [comment] 2017-04-08 17:32
Thanks for the quick attention.  I visited the docs section of the repository looking for ng get but was unable to find what the valid built-in keys are or how determine which keys are available to "get" or "set".

Suggestion: 
1. create Get.md and Set.md.  

2. Then add them to the repository at the following location:
https://github.com/angular/angular-cli/tree/master/docs/documentation

**Comment by prestonvanloon** [comment] 2017-04-09 21:51
@fmorriso the related documentation is under the configuration doc. I do see your point of not knowing the built in keys. Originally, I proposed throwing a reasonable error when no key is provided. However, I think a better implementation would be to return the whole config object for display when no specific key provided. 

I'll update #5887 to return the proper config object.

**Comment by fmorriso** [comment] 2017-04-10 01:31
Putting what should be inside Get.md and Set.md in something non-obvious like Config.md seems curious at best.   When I want information about ng build I look in Build.md, so why not put ng get and ng set into Get.md and Set.md respectively?

**Comment by prestonvanloon** [comment] 2017-04-10 23:29
@fmorriso I agree, it's not intuitive to have get/set commands live under config.md. 

@filipesilva can you weigh in?

**Comment by alan-agius4** [comment] 2018-10-30 14:50
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2018-10-30 14:50 UTC
Labels: type: bug/fix
