### ISSUE TITLE
extract-i18n error since @angular-devkit/build-angular@18.2.0-next.2

### ISSUE THREAD

**Issue by bastienmoulia** [angular/angular-cli#28249] opened 2024-08-21 09:17 UTC
### Command

extract-i18n

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18.2.0-next.1

### Description

When I run the command, the bundle generation complete, then I have an error message:
```
Application bundle generation complete. [14.980 seconds]        

NX   Unknown file requested: scripts.js
```

### Minimal Reproduction

Don't know exactly how to reproduce it, will try to create a new project soon.

### Your Environment

```text
Angular CLI: 18.1.4
Node: 20.13.1
Package Manager: npm 10.5.2
OS: win32 x64

Angular: 18.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker, ssr

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1800.6
@angular-devkit/build-angular   18.2.0-next.2
@angular-devkit/core            18.1.0
@angular-devkit/schematics      18.1.0
@angular/cli                    18.1.4
@schematics/angular             18.1.0
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.8
```

### Anything else relevant?

For testing i have only update @angular-devkit/build-angular.
I'm using NX.

**Comment by alan-agius4** [comment] 2024-08-21 09:49
Duplicate of https://github.com/angular/angular-cli/issues/28236

**Closed by alan-agius4** 2024-08-21 09:49 UTC

**Comment by bastienmoulia** [comment] 2024-08-21 10:01
Sorry for the duplicate
