### ISSUE TITLE
Angular --prod build as development when optimization: false and custom webpack config

### ISSUE THREAD

**Issue by popec** [angular/angular-cli#19665] opened 2020-12-22 08:57 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package angular-builders/custom-webpack: 10.0.1 
When using custom webpack config (customWebpackConfig in angular.json architect->build->options) and setting optimization: false (in angular.json architect->build->configurations->production), config.mode available in customWebpack JS file during ng build --prod is being set to development instead of production.

### Is this a regression?

 
It was the same with version 9.x

**Comment by alan-agius4** [comment] 2020-12-22 12:38
This is expected as `—prod` Is just an alias for the production configuration. 

See: https://angular.io/cli/build

In the Angular CLI Webpack’s mode setting is controlled via the optimization option.

Closing as this is working as intended. Please note that custom Webpack configurations are not supported by Angular tooling team and the use of Webpack in the CLI is in implementation detail.

**Closed by alan-agius4** 2020-12-22 12:38 UTC
