### ISSUE TITLE
ng serve - 3rdpartylicenses.txt not found

### ISSUE THREAD

**Issue by stodastrabag** [angular/angular-cli#28375] opened 2024-09-09 09:50 UTC
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

2020

### Description

Using `ng serve` upon visting http://localhost:4200/3rdpartylicenses.txt I get `Cannot GET /3rdpartylicenses.txt`. As mentioned in https://github.com/angular/angular-cli/issues/17965 I do have `"extractLicenses": true` in my `build` config of `angular.json`.

### Minimal Reproduction

1. `ng serve`
2. go to http://localhost:4200/3rdpartylicenses.txt

### Exception or Error

```text
404 Not Found
```

### Your Environment

```text
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.8
Node: 20.16.0
Package Manager: npm 10.8.1
OS: linux x64

Angular: 17.3.10
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@schematics/angular             17.3.8
rxjs                            6.6.7
typescript                      5.3.3
webpack                         5.91.0
zone.js                         0.14.6
```

**Comment by alan-agius4** [comment] 2024-09-09 17:52
Could you elaborate on your specific use case and explain why you need access to third-party licenses during your development workflows?

**Comment by stodastrabag** [comment] 2024-09-10 07:22
No. It's a product of build schematic and I expect it to be served.

**Comment by alan-agius4** [comment] 2024-09-10 07:44
With the application builder files emitted outside the "browser" directory, like 3rdpartylicenses.txt and stats.json, are classified as non-servable. 

Closing as it is functioning as intended.

**Closed by alan-agius4** 2024-09-10 07:44 UTC
Labels: needs: more info

**Comment by stodastrabag** [comment] 2024-09-10 08:01
thanks for quick answer @alan-agius4 too bad nothing can be done here.
