### ISSUE TITLE
Feature Request: Support to platform-webworker

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12105] opened 2018-09-04 23:14 UTC
_From @lacolaco on May 10, 2018 7:57_

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [x] schematics
```

### Desired functionality

Currently, build_angular and schematics/angular don't support to build the `platform-webworker` application.

Interface ideas:

Generate webworker app

```
$ ng generate webworker # generate each UI/Worker entrypoint file
```

Build webworker app

```
$ ng run myapp:webworker # build app for webworker
```

```
...
        "server": {
          "builder": "@angular-devkit/build-angular:webworker",
          "options": {
            "appMain": "src/main.app.ts",
            "workerMain": "src/main.worker.ts",
            "tsConfig": "src/tsconfig.app.json"
          },
          "configurations": {
            ...
          }
        }
...
```

### Mention any other details that might be useful

_Copied from original issue: angular/devkit#882_

**Comment by Serginho** [comment] 2018-12-05 12:36
When do you plan do this?

**Comment by alan-agius4** [comment] 2019-02-05 13:32
Duplicate of https://github.com/angular/angular-cli/issues/2305

**Closed by alan-agius4** 2019-02-05 13:32 UTC
Labels: type: feature
