### ISSUE TITLE
1.5.0 Beta: Error for es2015, while working for es5

### ISSUE THREAD

**Issue by AmitMY** [angular/angular-cli#7831] opened 2017-09-26 05:14 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.5.0-beta.1
node: 8.4.0
os: win32 x64
@angular/animations: 4.4.2
@angular/common: 4.4.2
@angular/compiler: 4.4.2
@angular/core: 4.4.2
@angular/forms: 4.4.2
@angular/http: 4.4.2
@angular/platform-browser: 4.4.2
@angular/platform-browser-dynamic: 4.4.2
@angular/router: 4.4.2
@angular/cli: 1.5.0-beta.1
@angular/compiler-cli: 4.4.2
@angular/language-service: 4.4.2
typescript: 2.5.2
```

### Repro steps.
Running an app compiled to es5 works, but es2015 gives a zone error.
The app compiles I mean, but it doesn't run.

### The log given by the failure.
```
Unhandled Promise rejection: Cannot convert undefined or null to object ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at getParentCtor (core.js:1729)
    at ReflectionCapabilities.parameters (core.js:1542)
    at JitReflector.parameters (compiler.js:26622)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:15324)
    at CompileMetadataResolver._getFactoryMetadata (compiler.js:15263)
    at CompileMetadataResolver.getProviderMetadata (compiler.js:15533)
    at JitCompiler._compileModule (compiler.js:26063)
    at SyncAsync.then (compiler.js:26013)
    at Object.then (compiler.js:1633) TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at getParentCtor (http://localhost:4200/vendor.bundle.js:213913:49)
    at ReflectionCapabilities.parameters (http://localhost:4200/vendor.bundle.js:213726:45)
    at JitReflector.parameters (http://localhost:4200/vendor.bundle.js:211735:44)
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:200437:73)
    at CompileMetadataResolver._getFactoryMetadata (http://localhost:4200/vendor.bundle.js:200376:51)
    at CompileMetadataResolver.getProviderMetadata (http://localhost:4200/vendor.bundle.js:200646:43)
    at JitCompiler._compileModule (http://localhost:4200/vendor.bundle.js:211176:77)
    at SyncAsync.then (http://localhost:4200/vendor.bundle.js:211126:25)
    at Object.then (http://localhost:4200/vendor.bundle.js:186746:137)
```

### Desired functionality.
If es2015 code compiles well to es5, and runs well, it should be abled to compile to es2015 and run well.

### Mention any other details that might be useful.
I am using Chrome Canary.
This is my branch of an OSS project: https://github.com/AnSyn/ansyn/tree/chrome-44
`npm run start:backwards` works.
`npm run start` does not.

Even if I use the same configuration for both, and only change the target, I still get the error.

**Comment by AmitMY** [comment] 2017-09-26 09:17
Note!
If I use `@angular/cli@1.4.3` it works fine.

**Comment by filipesilva** [comment] 2017-09-27 10:48
Duplicate of https://github.com/angular/angular-cli/issues/7797.

**Closed by filipesilva** 2017-09-27 10:48 UTC
