### ISSUE TITLE
Error when build prod angular2

### ISSUE THREAD

**Issue by pekubu** [angular/angular-cli#6923] opened 2017-07-08 08:15 UTC
### Versions. 1.1.3

My code 
![code](https://user-images.githubusercontent.com/26251116/27983808-da576bc6-63ef-11e7-952b-159991123b29.PNG)

When debug
![captur4e](https://user-images.githubusercontent.com/26251116/27983828-39598ef6-63f0-11e7-9409-5500a5760a60.PNG)

When use 'ng build --prod'
![build](https://user-images.githubusercontent.com/26251116/27983814-23453d22-63f0-11e7-826d-4fb5c79b48e0.PNG)

how to fix it, plz help me :(

**Comment by Kapulara** [comment] 2017-07-08 10:37
What exactly is the issue?

The constructor name changes because of the webpack minify.

**Comment by sebastiangseijo** [comment] 2017-07-20 14:21
I have faced this problem with --prod and --aot and the solution i have found was this:
i modified production.js so constructor.name can give you the correct name and not a simple letter.

node_modules//models/webpack-configs/production.js

...
new webpack.optimize.UglifyJsPlugin({
...
mangle: { screw_ie8: true, keep_fnames: true }, /* added keep_fnames: true so SomeClass.constructor.name works */
...
})

**Comment by filipesilva** [comment] 2017-07-20 18:14
This issue is a duplicate of https://github.com/angular/angular-cli/issues/6454. Please see my comment https://github.com/angular/angular-cli/issues/6454#issuecomment-315431370 for an explanation of what is happening.

**Closed by filipesilva** 2017-07-20 18:14 UTC
