### ISSUE TITLE
mime type issue when providing buildUrl parameter during ng build --production

### ISSUE THREAD

**Issue by riteshmaurya** [angular/angular-cli#15633] opened 2019-09-19 09:26 UTC
mime type issue when providing buildUrl parameter during ng build --production

complete build command:
ARG configuration=production
RUN npm run build -- --output-path=./dist/out --deployUrl=/spa-demo --configuration $configuration

package.json:
{
  "name": "spa-demo",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.0.1",
    "@angular/common": "~8.0.1",
    "@angular/compiler": "~8.0.1",
    "@angular/core": "~8.0.1",
    "@angular/forms": "~8.0.1",
    "@angular/platform-browser": "~8.0.1",
    "@angular/platform-browser-dynamic": "~8.0.1",
    "@angular/router": "~8.0.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.3",
    "@angular/compiler-cli": "~8.0.1",
    "@angular/language-service": "~8.0.1",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}

Error in browser:
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8080/spa-demo/styles.3ff695c00d717f2d2a11.css".
main-es2015.fd34a56fb966daa0dd6c.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
runtime-es2015.1bfcc339d095abd71226.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
polyfills-es2015.5728f680576ca47e99fe.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by alan-agius4** [comment] 2019-09-19 10:15
Hi, which browser are you using?

Can you try https://github.com/angular/angular-cli/issues/15621?

**Comment by clydin** [comment] 2019-09-19 13:28
This also appears to be a server configuration error.  MIME types are configured and sent by the server.

**Comment by riteshmaurya** [comment] 2019-09-25 19:57
this was not server configuration issue. I found the workaround solution that is it will work only if you provide both deployUrl and baseHref as an argument to ng build. Also both argumaent values should be in this format /mypath/. this is now working for me on nginx. BTW I had tried checking and setting mime things on nginx side but that didnt worked.

**Comment by riteshmaurya** [comment] 2019-09-25 19:58
> Hi, which browser are you using?
> 
> Can you try #15621?

On any browser...i treid it in mozzila, chrome, IE..

**Comment by alan-agius4** [comment] 2019-09-28 08:19
Closing as it seems that you found the root cause.

Most likely you were hitting a 404 and your server is configured to send an HTML error page which is causing the mimetype issues.

**Closed by alan-agius4** 2019-09-28 08:19 UTC
Labels: need: more info
