### ISSUE TITLE
ng Command Hangs

### ISSUE THREAD

**Issue by smithad15** [angular/angular-cli#2702] opened 2016-10-14 15:43 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

macOS Sierra 10.12

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

ng --version does not run, Beta 17 installed. Node v6.8.0 installed via nvm

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Install angular-cli and try to run any command, `ng --help`, `ng --version`, etc. The terminal just hangs and requires a `Ctrl+C` to abort.

### The log given by the failure.
> Normally this include a stack trace and some more information.

No logs or output

### Mention any other details that might be useful.

Have tried installing via npm and yarn, no luck.
Have tried uninstall + cache clear, no luck.
Have tried rolling back to Beta 16, no luck.
Have had the cli working on this machine recently (within the last couple of weeks)
My terminal header (OS X Terminal) reports the following when hung on `ng --version`
"ng -- version - ng - watchman < angular-cli TMPDIR=/var/folders/fg/14mxvwgd2yngvk72m603rp4h0000gn/T/ TERM_PROGRAM_VERSION=377"
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment] 2016-10-14 18:16
Dupe of #2649

**Closed by filipesilva** 2016-10-14 18:16 UTC

**Comment by smithad15** [comment] 2016-10-14 19:49
A dupe indeed. The temp fix documented in that issue worked. Thanks

**Comment by hani647** [comment] 2018-09-07 09:36
I also experienced this issue when upgrading from Angular 5 to Angular 6. On my internet connection i.e. 2 MB/s it took half an hour but no result and then I increased my internet speed to 50 - 60 (MB/s) at this speed it took hardly 5 - 10 mins to run update command. Overall ng update is working but it seems that nothings happening so wait and let NG do its work. Hope it help you 👍
