### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by djflex68** [angular/angular-cli#21807] opened 2021-09-23 13:53 UTC
Related to #21041 that has been closed.
Issue is still present, but goes away as soon as sourceMaps is set to false inside angular.json.

**Comment by alan-agius4** [comment] 2021-09-23 14:09
Duplicate of https://github.com/angular/angular-cli/issues/21779

**Closed by alan-agius4** 2021-09-23 14:09 UTC
