### ISSUE TITLE
After error in code even if code is corrected, it is showing error.

### ISSUE THREAD

**Issue by inceptionolan** [angular/angular-cli#19539] opened 2020-12-03 06:42 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression? 
I am newbie. I don't know. 

### Description

On ng serve, code complies fine. Once I do coding mistake, I get error. Now if I correct that error then also I keep getting errors. If I terminate batch job and do ng serve it compiles fine. And cycle repeat itself. 

## 🔬 Minimal Reproduction

Ng serve
Edit code. Make some mistakes. 
Now correct the code. 
Still sees same/ different error. Sometimes you get the desired outcome. 
Terminate batch job on terminal. 
Ng serve
Hola! Code run without errors. 
Cycle repeat itself. 

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Cli : 11.0.2
Node: 10.16.3
Os: win32 x64
</code></pre>

**Anything else relevant?**
Most of the people in my organization getting same error. 
Cannot copy paste error or code. Against organization policy. Sorry.

**Comment by alan-agius4** [comment] 2020-12-03 07:15
What type of syntax error are you doing? Is it a template error?

If so this looks like a duplicate of https://github.com/angular/angular/issues/39147

**Comment by alan-agius4** [comment] 2020-12-05 11:11
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Closed by alan-agius4** 2020-12-05 11:11 UTC
Labels: need: more info
