### ISSUE TITLE
Node.js 9 - Unsupported engine for karma@1.7.1

### ISSUE THREAD

**Issue by andrei-tofan** [angular/angular-cli#10986] opened 2018-05-24 08:46 UTC
While trying to create a new project with `ng new my-app` and got this error:
```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for karma@1.7.1: wanted: {"node":"0.10 || 0.12 || 4 || 5 || 6 || 7 || 8"} (current: {"node":"9.6.1","npm":"5.8.0"})
npm ERR! notsup Not compatible with your version of node/npm: karma@1.7.1
npm ERR! notsup Not compatible with your version of node/npm: karma@1.7.1
npm ERR! notsup Required: {"node":"0.10 || 0.12 || 4 || 5 || 6 || 7 || 8"}
npm ERR! notsup Actual:   {"npm":"5.8.0","node":"9.6.1"}

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Work\AppData\Roaming\npm-cache\_logs\2018-05-24T06_34_06_471Z-debug.log
Package install failed, see above.
```

### Versions
```
Angular CLI: 6.0.3
Node: 9.6.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.3
@angular-devkit/core         0.6.3
@angular-devkit/schematics   0.6.3
@schematics/angular          0.6.3
@schematics/update           0.6.3
rxjs                         6.2.0
typescript                   2.7.2

Windows 10
```

### Repro steps
1. Install Angular CLI `npm install -g @angular/cli`
2. Create a new project with `ng new my-app`

### Observed behavior
Got an error while the setup was being done:
```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for karma@1.7.1: wanted: {"node":"0.10 || 0.12 || 4 || 5 || 6 || 7 || 8"} (current: {"node":"9.6.1","npm":"5.8.0"}) 
```
### Desired behavior
Setup of the new project to be successful

**Comment by filipesilva** [comment] 2018-05-24 22:02
@clydin this might be a problem in regards to https://github.com/angular/angular-cli/issues/10963

**Comment by clydin** [comment] 2018-05-25 10:14
The karma version does not support Node 9. The version can be upgraded manually to 2.0.2.  This will be addressed in the next CLI minor version.

**Comment by alan-agius4** [comment] 2018-11-20 10:52
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2018-11-20 10:52 UTC
Labels: comp: etc/misc
