### ISSUE TITLE
fix: ng generate on default project

### ISSUE THREAD

**Issue by klauskpm** [angular/angular-cli#12931] opened 2018-11-11 17:10 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
Angular CLI: 7.0.1
Node: 10.10.0
OS: darwin x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.1
@angular-devkit/build-angular      0.10.1
@angular-devkit/build-ng-packagr   0.10.1
@angular-devkit/build-optimizer    0.10.1
@angular-devkit/build-webpack      0.10.1
@angular-devkit/core               7.0.1
@angular-devkit/schematics         7.0.1
@angular/cli                       7.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.1
@schematics/angular                7.0.1
@schematics/update                 0.10.1
ng-packagr                         4.3.1
rxjs                               6.3.3
typescript                         3.1.3
webpack                            4.19.1
```

### Repro steps
1) Create a workspace, generate a library and set it as the default project. Now generate a component without supplying a project. It will generate the component at `src/app`.

2) Create a workspace without an application (`--create-application false`), generate a library and an application, and set the library as the default project. Now generate a component without supplying a project. It will generate the component at `projects/my-lib`.

### Desired functionality
I think it would be better if it always used the default project.

**Comment by alan-agius4** [comment] 2018-11-11 17:16
Duplicate of: https://github.com/angular/angular-cli/issues/11111

**Closed by alan-agius4** 2018-11-11 17:16 UTC
