### ISSUE TITLE
[dev-server] Unable to pass custom providers for SSR in Angular v17+

### ISSUE THREAD

**Issue by leo6104** [angular/angular-cli#28535] opened 2024-10-01 07:32 UTC
### Command

serve

### Description

In Angular versions prior to v17, it was possible to pass request/response objects to the server-side rendering (SSR) process through the providers argument of CommonEngine.render in server.ts. This allowed for custom control during SSR scenarios.
However, as per the Angular documentation:

> Note: In Angular v17 and later, server.ts is no longer used by ng serve. The dev server will use main.server.ts directly to perform server-side rendering.

This change has introduced a regression where it's no longer possible to pass these objects to the SSR process when using the development server.

Here is the example our project used. 

### tokens.ts 
```
const CUSTOM_INJECTION_TOKEN = new InjectionToken<AppContext>('EXAMPLE_TOKEN');

export class BrowserContext extends AppContext { ... } 
export class ExpressContext extends AppContext { ... } 
```

### server.ts 
```
import { CUSTOM_INJECTION_TOKEN } from './tokens';
import bootstrap from './src/main.server';

function app() {
     const server = express();
     const engine = new CommonEngine();
     ...
     server.get('*', (req, res) => {
        const expressContext = new ExpressContext(req, res);

        engine.render({
            bootstrap,
            providers: [
                 { provide: CUSTOM_INJECTION_TOKEN, useValue: expressContext }
            ],
        });
     });
}
```

When using ng serve in Angular v17+, the Vite dev server only looks at main.server.ts. As a result, even if we inject providers into server.ts, there's no way to pass the request/response objects to the SSR process.

### Describe the solution you'd like

We should have a way to pass request/response objects to the SSR process when using the development server, similar to how it was possible in versions prior to Angular v17.

**Comment by alan-agius4** [comment] 2024-10-01 07:36
Duplicate of https://github.com/angular/angular-cli/issues/26323

**Closed by alan-agius4** 2024-10-01 07:36 UTC
