### ISSUE TITLE
After upgrading to Angular 8 , compile time increased 3 times.

### ISSUE THREAD

**Issue by alialtun14** [angular/angular-cli#14604] opened 2019-05-31 02:40 UTC
I upgraded my project to Angular 8 version. While upgrading process, I haven't met any error. But the compile time increased 3 times without any error. 

    Last Compile Before Angular 8  (with Angular 7.2)
    Time: 1382.536ms -> main.cf29a89468d732f3f363.js (main) 12.4 MB 
    
    First Compile After Upgrading to Angular 8
    Time: 6379.317ms -> main.da4147c72278bc767ee4.js (main) 12.3 MB 

    Second Compile After Upgrading to Angular 8 and After restart PC 
    Time: 3147.254ms -> main.da4147c72278bc767ee4.js (main) 12.3 MB

tsconfig.json 
```
{
 "compileOnSave": false,
 "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "mapRoot": "./",
    "moduleResolution": "node",
    "outDir": "../__dist_cli",
    "sourceMap": true, 
    "target": "es5 ", 
    "module": "es2015",
    "lib": [
        "es2016",
        "dom"
    ],
    "typeRoots": [
        "node_modules/@types",
        "typings/custom"
    ]
}
```

package.josn
```
   ....
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "^8.0.0",
    "@angular/material": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "intl": "^1.2.5",
    "rxjs": "^6.5.2",
    "tar": "^4.4.8",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.0",
    "@angular-devkit/build-optimizer": "^0.800.0",
    "@angular/cli": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/compiler-cli": "^8.0.0",
    "@types/angular": "^1.6.54",
    "@types/angular-route": "^1.3.5",
    "@types/quill": "^2.0.2",
    "hammerjs": "^2.0.8",
    "quill": "^1.3.6",
    "typescript": "^3.4.5"
  }
}
```
```
Angular CLI: 8.0.0
Node: 12.3.1
OS: win32 x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@angular/flex-layout              8.0.0-beta.26
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
```

**Comment by trotyl** [comment] 2019-05-31 07:52
Duplicate of https://github.com/angular/angular-cli/issues/14554?

**Comment by alan-agius4** [comment] 2019-05-31 10:15
@trotyl, not really

**Comment by alan-agius4** [comment] 2019-05-31 10:17
@alialtun14, can you provide some more info, such as which command are you using is it a `ng serve` or `ng build`?

Would you be able to provide a reproduction please?

**Comment by alialtun14** [comment] 2019-05-31 11:40
"ngs":  "node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng"

 ./ngs build --prod --aot

**Comment by alan-agius4** [comment] 2019-05-31 13:07
Do you use `sass` as your style pre-processor? If yes, can you try a couple of things please:

```cmd
npm i  fibers --save-dev
```
Run the build and report the timings

```cmd
npm i node-sass -save-dev
```

Thanks

Run the build and report the timings.

**Comment by alialtun14** [comment] 2019-06-01 05:33
@alan-agius4  Thank you for your attention and effort.

I have compiled again after doing the operations you said. The result has not changed. The compile process is  waiting for about half an hour while 25%.   The same project takes less than 40 seconds to compile with ng serve instead of ng build --prod --aot.  

I have been working on upgrading to angular 8 for two days. The project actually does not have too much dependency, which may be likely to be the problem. There are only hammerjs and quill. I think I'll use angular 7.2 for a temporary solution.

I would like to share the link of project codes with the idea that maybe it works.
https://drive.google.com/file/d/11ChUK3k4sKMqmLS9nv0VFmac3bjXpZzF/view?usp=sharing

**Comment by alialtun14** [comment] 2019-06-01 18:31
After convert to angular 7.2.15, I compile the project with node 12 environment . 
The compile time is ****5527.777 ms (6 times more than normal)**

Then I installed the node 10.16.0 for angular 7.2.15 and the compile time is **901.372ms  (normal)**

# **Node: 12.3.1 + Angular: 7.2.15**   
Angular CLI: 7.3.9  OS: win32 x64    webpack: 4.29.0  TS: 3.2.4
````
Date: 2019-06-01T17:57:21.347Z
Hash: 003a017db26b2761ba40
Time: 5527.777ms
chunk {0} runtime.26209474bfa8dc87a77c.js      (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.d422ca0dc6cf56ee2633.js            (main) 12.2 MB [initial] [rendered]
chunk {2} polyfills.918ead405a6828219c02.js  (polyfills) 42.9 kB [initial] [rendered]
chunk {3} styles.a9ca052bcbe1e2ca9a8a.css       (styles)  104 kB [initial] [rendered]
chunk {4} vendor.bd9fcb891d7c323ba04b.js        (vendor)  927 kB [initial] [rendered]
chunk {scripts} scripts.c05cd6675c6d364a689d.js (scripts) 228 kB [entry] [rendered]
````
# **Node: 10.16.0 + Angular: 7.2.15**  
(Angular CLI: 7.3.9  OS: win32 x64    webpack: 4.29.0  TS: 3.2.4
````
Date: 2019-06-01T18:29:19.549Z
Hash: 003a017db26b2761ba40
Time: 901.372ms
chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.d422ca0dc6cf56ee2633.js (main) 12.2 MB [initial] [rendered]
chunk {2} polyfills.918ead405a6828219c02.js (polyfills) 42.9 kB [initial] [rendered]
chunk {3} styles.a9ca052bcbe1e2ca9a8a.css (styles) 104 kB [initial] [rendered]
chunk {4} vendor.bd9fcb891d7c323ba04b.js (vendor) 927 kB [initial] [rendered]
chunk {scripts} scripts.c05cd6675c6d364a689d.js (scripts) 228 kB [entry] [rendered]````

**Comment by alan-agius4** [comment] 2019-06-03 08:58
Hi @alialtun14, from what you provided above, it's seems that it is slower on Node 12 irrispective of the Angular CLI version, if anything version 8 is much faster than version 7 on Node 12.  `3147.254ms` versus `5527.777ms`.

This will require some digging to determine why the build is faster on Node 10 compared to Node 12.

 I couldn't help but notice that for version 7 the compilation takes less than 1 second which doesn't seem to be right.

Would you be able to share your application please?

**Comment by alialtun14** [comment] 2019-06-03 20:11
angular 7.2.15 project code without any error..
https://drive.google.com/open?id=133bT_I99l-sRM3FHP9_-BnyQh1QZc94W

to convert the project to angular 8,  the is only two term in the project.
```
2  lines ->   @ContentChild(...
579 lines -> @ViewChild(...
```

**Comment by alialtun14** [comment] 2019-06-03 21:03
angular 7.2.15 project code without any error.

https://drive.google.com/open?id=12PHtyX8P507mTsBU202wudngrRZQR9Hn

to convert the project to angular 8, the is only two term in the project.
```
2  lines:   @ContentChild(... 
579 lines: -> @ViewChild(...
```

**Comment by alan-agius4** [comment] 2019-06-05 05:45
Hi @alialtun14,

Thanks for the reproduction, we'll try to take a close look soon.

In the meantime I am going to close this issue in favor of https://github.com/angular/angular-cli/issues/13734 so that we have this issue tracked in a single tread.

Thanks for understanding.

**Closed by alan-agius4** 2019-06-05 05:45 UTC
Labels: need: more info

**Comment by adripanico** [comment] 2019-06-12 09:04
I'm upgrading an application from Angular 7 to 8 and I'm also. facing a huge impact in the compilation time, but I don't think it is related to #13734 (I don't see any error messages and everything works fine). The application is relatively complex (51 chunks total).

The compilation process percentage raises to 100% and then it starts again from 0%, 

I'm not using --aot, just ng build --prod --base-href /

Time to build:

- real	9m14,118s
- user	15m22,745s
- sys	0m15,490s

I've then revert to Angular 7.2 and I get this values:

- real	4m43,201s
- user	8m29,736s
- sys	0m7,659s

**Comment by micobarac** [comment] 2019-06-18 08:44
Same problem here too...

**Comment by kemsky** [comment] 2019-06-18 09:59
Overall angular-cli is two times slower and consumes more memory than custom script with rollup or closure and even webpack. CI times are much worse.

**Comment by adripanico** [comment] 2019-06-18 10:43
It seems it has been improved in @angular/cli 8.0.3 according to https://github.com/angular/angular-cli/issues/14746.

**Comment by Alcidauk** [comment] 2019-06-18 16:10
Hi all,

I faced the same problem too, even in the 8.0.3 version.

In my case, going back to native Sass (explained here https://update.angular.io/#7.0:8.0) fix the problem (I now have the same compilation time than with Angular 7).

**Comment by adripanico** [comment] 2019-06-25 12:57
Upgrading to cli 8.0.4:

```
real	7m50,181s
user	15m3,919s
sys	0m12,322s
```

Upgrading to cli 8.0.4 and using node-sass:

```
real	8m8,383s
user	15m0,839s
sys	0m13,394s
```

**Comment by j-nord** [comment] 2019-07-23 14:58
Sorry but:
So no one can seriously work with the new compiler for angular 8. It hardly goes slower anymore. An impertinence for every developer! We must wait 20 minutes to get an error message! And then we get an error message that doesn't say anything! 

The issue is open and not closed !

**Comment by adripanico** [comment] 2019-07-23 15:04
> Sorry but:
> So no one can seriously work with the new compiler for angular 8. It hardly goes slower anymore. An impertinence for every developer! We must wait 20 minutes to get an error message! And then we get an error message that doesn't say anything!
> 
> **The issue is open and not closed !**

I'm seriously working with the new compiler. I assume your "doesn't-say-anything" error is something miss-configured or any kind of issue during the upgrading on your side.

I don't think this error belongs to this issue: we are talking about compilation time here.

**Comment by j-nord** [comment] 2019-07-23 15:06
Yes and the compilation time in angular 8 is toooooooo slow!

**Comment by adripanico** [comment] 2019-07-23 15:11
It is actually faster than in Angular 7. The difference is that Angular 8 provides Differential Loading out-of-the-box. In my case, it was compiling two different versions, one for es5 and other one for es2015, doubling the compilation process.

**Comment by alialtun14** [comment] 2019-08-13 22:38
I would like to thank everyone who helped solve the problem. Today we have launched the application compiled with angular 8.

**Comment by metallidevils** [comment] 2019-08-19 20:41
> It is actually faster than in Angular 7. The difference is that Angular 8 provides Differential Loading out-of-the-box. In my case, it was compiling two different versions, one for es5 and other one for es2015, doubling the compilation process.

How do you disable this?

**Comment by adripanico** [comment] 2019-08-20 07:12
> > It is actually faster than in Angular 7. The difference is that Angular 8 provides Differential Loading out-of-the-box. In my case, it was compiling two different versions, one for es5 and other one for es2015, doubling the compilation process.
> 
> How do you disable this?

You have two choices:

- To keep the differential loading feature and configure the ```browserlist``` file so your output target is only es5.
- To completely disable differential loading.

Complete guide is provided by official Angular docs: https://angular.io/guide/deployment#configuring-differential-loading

Hope this help.

**Comment by yuezhizizhang** [comment] 2019-08-29 02:17
to support differential loading, Angular 8 would build two bundles of JavaScript files, one set to support modern browers, the other set to support legacy browsers. Hence, it takes at least twice the build time as before.

In Angular 7, there used to have a setting in angular.json file, which specifies whether support es5 browsers or not.

angular.json
```
"build": {
    "es5BrowserSupport":  false
}
```
However, in Angular 8 this setting is deprecated. Instead, you have to configure browserslist file to tell Angular build which browsers are supported. By default, browserslist looks like below:

browserslist
```
0.5%              # It says: I want to support all browsers that have at least .05% of the global browser usage.
                  # So this will include some really old browsers.
last 2 versions   # It says: the last 2 versions for each browser, even mobile browsers. But our app is not targeting at mobile devices.
Firefox ESR       # the latest [Firefox ESR] version.
not dead          # Don't support outdated browsers
not IE 9-11       # Don't support IE 9 - 11
```

If you only care about Edge, Firefox and Chrome, drop 0.5% and last 2 versions, one will include very old browsers, the other will include all of the mobile browsers.
