### ISSUE TITLE
AoTPlugin fails with @Input() public someVar;

### ISSUE THREAD

**Issue by MikaAK** [angular/angular-cli#3021] opened 2016-11-04 20:16 UTC
### OS?
OSX El Capitan

### Versions.
6.8.1

### Repro steps.
App wasn't created using CLI. I was trying to add AOT to [my seed](https://github.com/MikaAK/angular2-seed)

If you use `@Input() public someName: type` it will end up compiling to `this.someName = public`.

My test was using [a tab component](https://github.com/MikaAK/angular2-seed/blob/master/src/shared/components/tabs/tab/tab.component.ts#L8-L10) where I changed these to public and error messages happened as a result.

##### The following works fine with ts-loader 
```typescript
import {Component, Input} from '@angular/core'

@Component({
  selector: 'tab',
  templateUrl: './tab.pug'
})
export class Tab {
  @Input() public active: boolean
  @Input() public disabled: boolean
  @Input() public title: string
}
```
##### Results with AOT Plugin
```javascript
function Tab() {
  this.active = public
  this.disabled = public
  this.title = public
}
```

### The log given by the failure.

```error
ERROR in ./src/shared/components/tabs/tab/tab.component.ts
Module parse failed: /{path}/angular2-seed/node_modules/@ngtools/webpack/src/index.js!/{path}/angular2-seed/src/shared/components/tabs/tab/tab.component.ts The keyword 'public' is reserved (3:22)
You may need an appropriate loader to handle this file type.
| export var Tab = (function () {
|     function Tab() {
|         this.active = public;
|         this.disabled = public;
|     }
 @ ./src/app/home/home.component.ngfactory.ts 14:0-75
 @ ./src/app/home/home.module.ngfactory.ts
 @ . async
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/main.aot.ts
```

### Removing `public` from the declaration fixes this issue

**Comment by filipesilva** [comment] 2016-11-05 14:21
Dupe of https://github.com/angular/angular-cli/issues/2890

**Closed by filipesilva** 2016-11-05 14:21 UTC

**Comment by MikaAK** [comment] 2016-11-05 17:17
Ah my bad @filipesilva I couldn't find that issue.  Thanks!
