### ISSUE TITLE
Global install of angular-cli@latest on Windows 10 is failing

### ISSUE THREAD

**Issue by chumtoadafuq** [angular/angular-cli#2193] opened 2016-09-17 15:18 UTC
Windows 10.
node v6.2.1.
npm v3.9.3.

All commands are being run using Windows Powershell as Administrator.

1. Followed the instructions [here](https://github.com/angular/angular-cli#updating-angular-cli) to do global uninstall and clean cache. This worked fine.

2. Ran the command to install the latest version globally.
`npm install -g angular-cli@latest`

3. The result is many warnings and errors per attached textfile.
[terminal-log.txt](https://github.com/angular/angular-cli/files/478208/terminal-log.txt)

Is this a known issue?

**Comment by kalvarez2** [comment] 2016-09-17 17:45
I got the same issue, not windows 10, I have windows 7. also tried:

 npm install -g angular-cli@1.0.0-beta.11-webpack.9-4

and --no-optional flag...

the node-zopfli download fails, tried going to the amazon folder where the file is, get access denied.

Should I install CS express to compile from source? does anybody knows if that would make it work??

thanks!

**Comment by sarunint** [comment] 2016-09-19 00:14
I've also got the same issue before.  Despite the error, `angular-cli` should work without no problems.

If you really want to get rid of the error, follow [this instruction](https://github.com/nodejs/node-gyp/blob/master/README.md). *(Warning: It is downloading REALLY big files, be patient!)*

**Comment by filipesilva** [comment] 2016-09-22 03:12
Dupe of https://github.com/angular/angular-cli/issues/1991

**Closed by filipesilva** 2016-09-22 03:12 UTC
