### ISSUE TITLE
Relative url reference in CSS file not working in 1.7.1

### ISSUE THREAD

**Issue by pfeigl** [angular/angular-cli#9797] opened 2018-02-27 14:30 UTC
### Versions
```
Angular CLI: 1.7.1
Node: 8.4.0
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.3
@angular/cli: 1.7.1
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps
Create new project, add devextreme and devextreme-angular and add those two lines to the styles inside of angular-cli.json file

```
                "../node_modules/devextreme/dist/css/dx.common.css",
                "../node_modules/devextreme/dist/css/dx.android5.light.css"
``` 
Now just start / build the project.

### Observed behavior
```
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/devextreme/dist/css/dx.android5.light.css
(Emitted value instead of an instance of Error) CssSyntaxError: path_to_project\node_modules\devextreme\dist\css\dx.android5.light.css:3228:12: Can't resolve 'icons/dxicons.woff)%20format(%27woff%27),%20url(icons/dxicons.ttf)%20format(%27truetype%27' in 'path_to_project\node_modules\devextreme\dist\css'

  3226 | @font-face {
  3227 |   font-family: 'DXIcons';
 3228 |   src: url(icons/dxicons.woff) format('woff'), url(icons/dxicons.ttf) format('truetype');
       |            ^
  3229 |   font-weight: normal;
  3230 |   font-style: normal;
```

I'm not sure whether the relative path or whether the fact that there is two url's defined is the actual problem. But somehow this broke somewhere between 1.6.7 and 1.7.1

### Desired behavior
The project should be able to compile

### Mention any other details that might be useful (optional)
Was working as expected in 1.6.7, started failing after 1.7.1 and started working again after a downgrade. 

Here is the actual CSS class which fails:
```css
@font-face {
  font-family: 'DXIcons';
  src: url(icons/dxicons.woff) format('woff'), url(icons/dxicons.ttf) format('truetype');
  font-weight: normal;
  font-style: normal;
}
```

The icons font file and the folder both exist. The folder is at the same location as the css file is.

**Comment by clydin** [comment] 2018-02-27 14:35
Duplicate of #9726; fixed in master and will be in the next patch release (1.7.2).

**Closed by clydin** 2018-02-27 14:35 UTC
