### ISSUE TITLE
ng new - wont allow dashes as the first param

### ISSUE THREAD

**Issue by Adam-Kernig** [angular/angular-cli#14137] opened 2019-04-11 14:08 UTC
# 🐞 Bug report
```
- [ X ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No

### Description
Running ng new followed by a dash cased string will cause an error

## 🔬 Minimal Reproduction
ng new april-2019

## 🔥 Exception or Error
<pre><code>
adamkernig$ ng new april-2019
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
Schematic input does not validate against the Schema: {"name":"april-2019","version":"7.3.8","routing":true,"style":"css"}
Errors:

  Data path ".name" should match format "html-selector".<code>

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.8
Node: 10.15.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.8
@angular-devkit/core         7.3.8
@angular-devkit/schematics   7.3.8
@schematics/angular          7.3.8
@schematics/update           0.13.8
rxjs                         6.3.3
typescript                   3.2.4
</code></pre>

**Comment by alan-agius4** [comment] 2019-04-11 15:31
Duplicate of https://github.com/angular/angular-cli/issues/13885

**Closed by alan-agius4** 2019-04-11 15:31 UTC

**Comment by clydin** [comment] 2019-04-11 16:08
Just a quick note that the dash itself is not the problem but rather the presence of a number immediately following the dash.
