### ISSUE TITLE
Is there any way to customize generated files (with ng g)

### ISSUE THREAD

**Issue by emreavsar** [angular/angular-cli#4302] opened 2017-01-31 07:47 UTC
I was wondering whether it is possible to **customize** the templates used to generate the files when using the angular-cli command `ng generate component` etc.

Idea behind is: many companies try to add a more or less static fileheader with some copyright stuff into their classes. In IDEs this is not a problem, but since the files are generated via cli this does not work.

Maybe there is already something around, and I couldn't find it? 

Customizing with variables (author, date of creation aka `@since`) is highly desirable.

**Comment by grizzm0** [comment] 2017-01-31 08:09
No, there's currently no support for something like that.

What you could do is fork the repo and edit [these files](https://github.com/angular/angular-cli/tree/master/packages/angular-cli/blueprints) yourself. Then rebase every now and then to keep up to date with the upstream.

Here's a [guide](https://github.com/angular/angular-cli#working-with-master) on how to use your own repo.

**Comment by filipesilva** [comment] 2017-02-03 16:07
Dupe of https://github.com/angular/angular-cli/issues/3549

**Closed by filipesilva** 2017-02-03 16:07 UTC
