### ISSUE TITLE
Generating a module with --route doesn't respect app styles extension

### ISSUE THREAD

**Issue by AhsanAyaz** [angular/angular-cli#15015] opened 2019-07-08 17:28 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I don't think so. The `--route` was potentially not there before.

### Description

 
When generating a module with `--route`, the style extension for the component files being generated is not picked from the angular.json of the project. 

## 🔬 Minimal Reproduction

```
ng new my-app --routing --style scss
```

```
ng g module abc --route abc --module app.module.ts
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.1.0
Node: 10.14.2
OS: darwin x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**

-

**Comment by alan-agius4** [comment] 2019-07-08 17:53
Duplicate of https://github.com/angular/angular-cli/issues/14986

**Comment by mgechev** [comment] 2019-07-08 17:53
Duplicate of https://github.com/angular/angular-cli/issues/14986.

https://github.com/mgechev/angular-cli/commit/6595613221cd4db7fc5727372189d49e82247187

**Closed by alan-agius4** 2019-07-08 17:53 UTC
