### ISSUE TITLE
no such file or directory, 

### ISSUE THREAD

**Issue by Amit18april86** [angular/angular-cli#11936] opened 2018-08-17 18:40 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ x] new
- [ x] build
- [ x] serve
- [ x] test
- [ x ] e2e
- [ x ] generate
- [ x] add
- [ x] update
- [ x] lint
- [ x] xi18n
- [ x] run
- [ x] config
- [ x] help
- [ x] version
- [ x] doc
```

### Versions

node: v8.11.3
npm: 5.6.0
ng --version: @angular/cli@6.2.0-beta.3

### Repro steps

after updating using npm install -g @angular/cli@next . It downloaded version @angular/cli@6.2.0-beta.3. After which I started getting an error for every ng command. Path calculated using core libs consist of "c" drive twice, that failing it to find the exact path of installation.

### The log given by the failure

Error: ENOENT: no such file or directory, open 'C:\C\Users\XYZ\node_modules\@angular\cli\commands\version.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at findCommand (C:\Users\XYZ\node_modules\@angular\cli\models\command-runner.js:302:31)
    at Object.<anonymous> (C:\Users\XYZ\node_modules\@angular\cli\models\command-runner.js:80:31)
    at Generator.next (<anonymous>)
    at C:\Users\XYZ\node_modules\@angular\cli\models\command-runner.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\XYZ\node_modules\@angular\cli\models\command-runner.js:10:12)
    at Object.runCommand (C:\Users\XYZ\node_modules\@angular\cli\models\command-runner.js:51:12)
    at C:\Users\XYZ\node_modules\@angular\cli\lib\cli\index.js:38:58

### Desired functionality

All ng command should work

### Mention any other details that might be useful

Issue lies with @angular-devkit module , i.e. file 
C:\Users\XYS\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\virtual-fs\path.js

Line number 179: inside normalize function. for below code:
        path = '\\' + path[0] + '\\' + path.substr(3);
if I change it to 
        path = '\\' + path.substr(3);
Command started working. I verified on Windows 7 and 10, not sure if the solution works for Linux and Unix machine.

**Comment by Amit18april86** [comment] 2018-08-17 18:53
![capture](https://user-images.githubusercontent.com/6071194/44283744-f8495500-a27c-11e8-81d0-85e23cc13738.PNG)

**Comment by alan-agius4** [comment] 2018-08-18 07:37
Duplicate of https://github.com/angular/angular-cli/issues/11928

**Closed** 2018-08-20 17:43 UTC
