### ISSUE TITLE
Specify new option to control output file name in ng generate

### ISSUE THREAD

**Issue by hanct** [angular/angular-cli#17931] opened 2020-06-14 16:47 UTC
Hi,

I was executing **ng generate class todoItem**, and observe that a file named **todo-item.ts** was created. I would like to suggest an option to allow us to control the file name so that we can output **todoItem.ts** instead.  Likewise, the spec generated should also follow the specified file name as well (i.e **todoItem.spec.ts**).

Also, will be great if we can control the class name as well, perhaps **TodoItem** instead of the default **ToDoItem**.  

I am aware that we can manually change the file names, but why do that if we can specify it via the command

**Comment by alan-agius4** [comment] 2020-06-15 06:52
Duplicate of https://github.com/angular/angular-cli/issues/6705

**Closed by alan-agius4** 2020-06-15 06:52 UTC
