### ISSUE TITLE
Styles don't included when node_module folder is a symbolic link

### ISSUE THREAD

**Issue by a-legrand** [angular/angular-cli#16559] opened 2020-01-06 11:58 UTC
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

The exact same bug as in https://github.com/angular/angular-cli/issues/5515

My node_modules folder is a symlink
I can't include styles from that location. But I can include scripts. Very strange

## 🔬 Minimal Reproduction
```json
"styles": [
  "src/sass/app.scss",
  "node_modules/quill/dist/quill.core.css",
],
```

## 🔥 Exception or Error
No error, but styles aren't added to the final stylesheet.

## Environment
Angular CLI: 8.3.21
Node: 10.16.3
OS: linux x64
Angular: 8.2.14

**Comment by alan-agius4** [comment] 2020-05-28 17:38
Duplicate of https://github.com/angular/angular-cli/issues/3500

**Closed by alan-agius4** 2020-05-28 17:38 UTC
Labels: comp: devkit/build-angular, freq1: low, severity3: broken, triage #1, type: bug/fix
