### ISSUE TITLE
mat-fab, mat-mini-fab have no mat-accent class in production

### ISSUE THREAD

**Issue by PeS82** [angular/angular-cli#9253] opened 2018-01-17 16:53 UTC
### Versions
```
Angular CLI: 1.6.3
Node: 8.9.0
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cdk: 5.0.4
@angular/cli: 1.6.3
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.0.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.11
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
Source 
```html
<button [routerLink]="['/new']" mat-mini-fab class="ml" matTooltip="Add new customer"><mat-icon>add</mat-icon></button>
```
With `ng serve`, `ng serve --aot`, `ng build --aot` this produces:
```html
<button class="ml mat-mini-fab mat-accent" mat-mini-fab="" mattooltip="Add new customer" tabindex="0" ng-reflect-router-link="/new" aria-describedby="cdk-describedby-message-3" cdk-describedby-host="" ng-reflect-message="Add new customer"><span class="mat-button-wrapper"><mat-icon class="mat-icon material-icons" role="img" aria-hidden="true">add</mat-icon></span><div class="mat-button-ripple mat-ripple mat-button-ripple-round" matripple="" ng-reflect-centered="false" ng-reflect-disabled="false" ng-reflect-trigger="[object HTMLButtonElement]"></div><div class="mat-button-focus-overlay"></div></button>
```

When in production, after running `ng build --prod`, html is:
```html
<button class="ml mat-mini-fab" mat-mini-fab="" mattooltip="Add new customer" tabindex="0" aria-describedby="cdk-describedby-message-3" cdk-describedby-host=""><span class="mat-button-wrapper"><mat-icon class="mat-icon material-icons" role="img" aria-hidden="true">add</mat-icon></span><div class="mat-button-ripple mat-ripple mat-button-ripple-round" matripple=""></div><div class="mat-button-focus-overlay"></div></button>
```

### Observed behavior
There is no `mat-accent` class in production build.

### Desired behavior
There should be `mat-accent` class in production build.

### Mention any other details that might be useful (optional)
There might be other troubles, this one was easy to spot as all fab buttons lost the background. It should be accent by default per angular/material2 docs (and it was so until recently).

It might be trouble with Material itself however filing here as it does work with other than production builds.

**Comment by Taha-Di-Nero** [comment] 2018-01-18 10:24
https://github.com/angular/angular-cli/issues/9221

**Comment by alexjlockwood** [comment] 2018-01-21 07:09
Could anyone recommend a workaround for this issue?

**Comment by hansl** [comment] 2018-01-24 18:39
Closing as dupe of 9221.

**Closed by hansl** 2018-01-24 18:39 UTC
