### ISSUE TITLE
Compilatioin fails with latest Node 9.2 / npm 5.5

### ISSUE THREAD

**Issue by repinvv** [angular/angular-cli#8687] opened 2017-11-30 13:44 UTC
### Versions
ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.5
Node: 9.2.0
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser-dynamic, router, tsc-wrapped

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.5
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript-reexport-generator: 1.1.2
typescript: 2.6.2
webpack: 3.8.1

### Repro steps
* Step 1
 clone       git@github.com:repinvv/angular2test.git
* Step 2
npm i -g @angular/cli typescript
* Step 3
ng b

### Observed behavior
ng b

@angular/compiler-cli@4.4.6 requires typescript@'>=2.1.0 <2.4.0' but 2.6.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.
Please run the following command to install a compatible version of TypeScript.
    npm install typescript@'>=2.1.0 <2.4.0'
To disable this warning run "ng set warnings.typescriptMismatch=false".

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (c:\projects\nielsen\test\node_modules\typescript\lib\typescript.js:13411:110)
    at parseSourceFileWorker (c:\projects\nielsen\test\node_modules\typescript\lib\typescript.js:13343:26)
    at Object.parseSourceFile (c:\projects\nielsen\test\node_modules\typescript\lib\typescript.js:13269:26)
    at Object.createSourceFile (c:\projects\nielsen\test\node_modules\typescript\lib\typescript.js:13110:29)

### Desired behavior
typescript should attempt to build the code

**Comment by clydin** [comment] 2017-11-30 15:17
Thanks for reporting this issue. However, this issue is appears to be a duplicate of an existing issue #5053.  Please subscribe to that issue for future updates.

**Closed by clydin** 2017-11-30 15:17 UTC
