### ISSUE TITLE
Will include HardSourcePlugin into CLI webpack?

### ISSUE THREAD

**Issue by Dok11** [angular/angular-cli#8496] opened 2017-11-15 10:43 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Mention any other details that might be useful.

In many project that bigger than 'hello world' time of compilation is very large, but I found existed decision for webpack. For example from this impressive article https://medium.com/ottofellercom/0-100-in-two-seconds-speed-up-webpack-465de691ed4a
Is possible include them into CLI webpack, for prevent ejecting webpack config?

**Comment by filipesilva** [comment] 2017-11-21 20:43
Heya, this is discussed and tracked in https://github.com/angular/angular-cli/issues/7467. I'm taking another look at. I did try using it again btw (I try it every 3 months or so) and it broke in a weird way that I reported in https://github.com/mzgoddard/hard-source-webpack-plugin/issues/198.

I'm going to close as a duplicate of https://github.com/angular/angular-cli/issues/7467.

**Closed by filipesilva** 2017-11-21 20:43 UTC
