### ISSUE TITLE
ng build --prod ignores js files in bower_component folder

### ISSUE THREAD

**Issue by misoucouma** [angular/angular-cli#1339] opened 2016-07-13 17:50 UTC
Hi 
I added some bower components to my app and when I build in dev mode every thing works fine.
However, when I build in prod mode, every js file is ignored.

**Comment by Splaktar** [comment] 2016-07-14 04:27
What's the output of `ng --version`?

**Comment by misoucouma** [comment] 2016-07-14 06:01
v1.0.0-beta.8

**Comment by Splaktar** [comment] 2016-07-14 20:27
Assuming you added them to `public/` then [this issue](https://github.com/angular/angular-cli/issues/540) was [just fixed in master](https://github.com/angular/angular-cli/commit/00e111af2b256a762fad33f2cfb0571d4757f6a1), it's not in beta.8 or beta.9 builds.

**Comment by BenevidesLecontes** [comment] 2016-07-16 17:04
@Splaktar there's a way to install this master?

**Comment by Splaktar** [comment] 2016-07-16 18:03
@BenevidesLecontes sure, there are multiple ways. Here is one that should work:

`npm i angular-cli@https://github.com/angular/angular-cli.git`

I haven't tested it though since I'm still using my forked version here: `npm i angular-cli@https://github.com/DevIntent/angular-cli.git`

**Comment by BenevidesLecontes** [comment] 2016-07-18 19:44
@Splaktar this master only copy js files when I do ng serve or ng build, but when I do ng serve with ---prod it doesn't work. And if do ng serve and after that ng serve --prod it throw this error
<img width="738" alt="screen shot 2016-07-18 at 16 43 44" src="https://cloud.githubusercontent.com/assets/1839361/16928015/d67918d4-4d06-11e6-9cfb-1c34388333fb.png">

**Comment by Splaktar** [comment] 2016-07-18 20:20
@BenevidesLecontes Yes, I see those directory not empty errors as well. I usually have to run `ng build --prod` or `ng serve --prod` about 3-4 times for it to succeed. I believe that's a separate issue though.

After running the command multiple times and getting it to succeed, the files `.js` are indeed copied.

**Comment by BenevidesLecontes** [comment] 2016-07-18 20:27
@Splaktar can you paste here how you setup jquery or boostrap in your angular-cli-build and system-config?

**Comment by Splaktar** [comment] 2016-07-18 21:18
I'm not using either of those fortunately, but I can point you to [how to setup angular2-polymer w/ the angular-cli](https://vaadin.com/docs/-/part/elements/angular2-polymer/ng-cli.html) which is putting the files in `public/bower_components`.

Take note of the `.bowerrc` file containing:
```
{
  "directory" : "public/bower_components"
}
```

**Comment by filipesilva** [comment] 2016-07-28 03:03
Closed as issue was made obsolete by #1455.

There was an issue with how we copied our vendor files before, but it should be fixed now and the approach that @Splaktar shows should work well.

**Closed by filipesilva** 2016-07-28 03:03 UTC
Labels: type: question/support

**Comment by osolano** [comment] 2016-07-29 05:38
I am also running into a similar issue but have setup my files like @Splaktar but still run into issues. When I try
`ng build --prod
ng serve --prod`

As soon as the application loads I have this issue:
![image](https://cloud.githubusercontent.com/assets/280426/17238703/c49bb50e-5512-11e6-8a0b-69739380772b.png)

I've setup an elements.html file with all my bower_component imports and added webcomponentsjs to the index.html file. Also placed all bower_components in public/bower_components.

This isn't an issue at all with dev, just with prod.

The issue with webcomponentsjs is probably due to the bundling of the js files, but I'm not sure what the best way to handle that is for bower_components.

I also narrowed down the missing web-animations-next-lite.min.js to these to import in my elements.html file. Commenting them out will avoid the error message
`<link rel="import" href="bower_components/paper-menu-button/paper-menu-button.html">
<link rel="import" href="bower_components/neon-animation/neon-animation.html">`

**Comment by Splaktar** [comment] 2016-07-29 07:18
Confirmed that this is working in `beta.10` unless, like me, you are using some custom build steps to support SCSS.

I had to do the following to get that working properly:

Change:
```
new Funnel('public', {
      include: ['**/*.html', '**/*.css', '**/*.js', '**/*.svg', '**/*.png'],
      destDir: 'src'
    })
```

To:
```
new Funnel('public', {
      include: ['**/*.html', '**/*.css', '**/*.js', '**/*.svg', '**/*.png'],
      destDir: 'public'
    })
```

Hopefully I'll have time to make a blog post next month on my full angular-cli SCSS config. Of course I imagine that by then, it'll all be irrelevant due to the webpack breaking changes.

**Comment by osolano** [comment] 2016-07-29 19:19
@Splaktar Thanks for the reply. The issue seemed to go away after updating to beta10 and starting from scratch on my app, reinstalling node modules and bower componets and then doing a production build. thanks!

**Comment by Splaktar** [comment] 2016-07-29 22:31
Yes, if you have a mix of beta.9 and beta.10 installed, sometimes it won't work. Following the angular-cli upgrade procedure tries to help avoid this kind of thing.

**Comment by vabhik** [comment] 2016-09-19 11:34
I am using beta 10 and this issue is still there. I am using jquery and bootstrap and while running ng build --prod or ng serve --prod it ignores .js files. Please tell me what else needs to be done to make it work ?
