### ISSUE TITLE
hmr not working

### ISSUE THREAD

**Issue by ninja-liu** [angular/angular-cli#27932] opened 2024-06-26 09:11 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

running project with cli "ng serve --hmr=true"  is not working as expected where change content in html should not trigger the reloading of whole page.

### Minimal Reproduction

1. create one project following angular 17 official doc`s start up.
2. run the project with "ng serve --hmr=true"
3. change the inner content of some div tag in app.component.html
4. there you can realize reloading of the whole page is triggered

### Exception or Error

```text
patch the page instead of reloading it
```

### Your Environment

```text
Angular CLI: 17.3.8
Node: 18.16.0
Package Manager: pnpm 8.13.1
OS: win32 x64

Angular: 17.3.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8 (cli-only)
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8 (cli-only)
@angular-devkit/schematics      17.3.8 (cli-only)
@angular/cli                    17.3.8
@schematics/angular             17.3.8 (cli-only)
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.6
```

**Comment by alan-agius4** [comment] 2024-06-26 09:36
Duplicate of https://github.com/angular/angular/issues/39367

**Closed by alan-agius4** 2024-06-26 09:36 UTC
