### ISSUE TITLE
environment.ts not being replaced when using --prod in ng build or serve

### ISSUE THREAD

**Issue by skate056** [angular/angular-cli#7653] opened 2017-09-11 12:07 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
ng --version
@angular/cli: 1.3.1
node: 8.4.0
os: darwin x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5

### Repro steps.
- Create a new angular project using `ng new ng-env-test`
- Modify app.component files to show the environment flags (isProduction)
- Run `ng serve --prod`. isProduction is false on the UI
- Run `ng serve --prod --aot=false`. isProduction is still false on the UI

### The log given by the failure.
`isProduction = false` is displayed on the UI

### Desired functionality.
`isProduction = true` is displayed on the UI when `ng serve --prod` is used.

### Mention any other details that might be useful.
Created a sample project which exhibits the behaviour https://github.com/skate056/ng-env-test

**Comment by hansl** [comment] 2017-09-11 18:15
Hi @skate056 

Your example is flawed and does not work; you are importing a file (`src/app/environment.ts`) that does not get overwritten by the environment flag. You need to import the file that's referred by `environmentSource` in your configuration in order to do this. By default, this is `src/environment.ts`.

Basically, changing [this line](https://github.com/skate056/ng-env-test/commit/395c74baa0c6d2469c660ea21f04eb16fcc90fab#diff-5c26d2c8f8838f32ace87fdecd6344eaR2) to this:

```typescript
import { environment } from '../environments/environment';
```

Fixes this issue.

Closing this as working as intended. Cheers!

**Closed by hansl** 2017-09-11 18:15 UTC

**Comment by skate056** [comment] 2017-09-12 15:37
I was hoping it was something as simple as that. Thanks for your help!

**Comment by JT-Bruch** [comment] 2019-02-20 21:34
Damn auto import got me too :(
