### ISSUE TITLE
--prod build compresses css values wrong

### ISSUE THREAD

**Issue by niklas-dahl** [angular/angular-cli#6310] opened 2017-05-14 18:40 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 7.5.0
os: win32 x64

### Repro steps.

In a components css file write the following:
```
.animatedBar {
  transform-origin: 50% 0%;
}
```

### The log given by the failure.

Running `ng serve` works fine, but when runnning `ng build --prod` the css rule gets compressed to the following wrong output:
```
.animatedBar {
  transform-origin: 50% 0;
}
```

### Desired functionality.

It should **not** remove the %.

### Mention any other details that might be useful.

This happens in .scss and .css files.

Thanks.

**Comment by niklas-dahl** [comment] 2017-05-14 19:15
so I did a bit of research myself and found out that the cli is unsing cssnano to compress the css. https://github.com/ben-eb/cssnano

Using their cli I located the problem:
`npm install cssnano-cli --global`

with a file `loader.component.css` containing:
```
.animatedBar {
  transform-origin: 50% 0%;
}
```

running ` cssnano loader.component.css`
outputs `.animatedBar{transform-origin:50% 0}`

**Comment by niklas-dahl** [comment] 2017-05-14 19:20
I found an issue on their repository regarding this https://github.com/ben-eb/cssnano/issues/219

**Comment by clydin** [comment] 2017-05-14 19:47
Per the cssnano issue and the spec,  this is intended behavior as the two values are equivalent.

**Comment by sumitarora** [comment] 2017-05-15 01:19
Closing as above.

**Closed by sumitarora** 2017-05-15 01:19 UTC
