### ISSUE TITLE
ng serve often caches old component code

### ISSUE THREAD

**Issue by tsupryk** [angular/angular-cli#24916] opened 2023-03-27 14:47 UTC
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.1.2

### Description

After number of auto-recompilations when running "ng serve" face an issue with cached component - new changes made in IDE doesn't reflect in browser. Component gets cached and even re-run "ng serve" doesn't help. 
Only removing folder ".angular/cache" and then re-run "ng serve" helps. 
In version 14.1.2 didn't see such an issue very often.
In browser I'm using "Disable cache" option always.

Using Angular CLI version: 15.0.5
Angular version: 15.0.4

### Minimal Reproduction

1. Run "ng serve".
2. Change component code.
3. Wait till re-compilation finish.
4. Verify results.
5. If works, repeat steps 2-4 multiple times. After some point component won't get refreshed (will use previous code).

### Your Environment

```text
Angular CLI: 15.0.5
Node: 16.18.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.0.4
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect     0.1500.5 (cli-only)
@angular-devkit/build-angular 15.0.5 (cli-only)
@angular-devkit/core          15.0.5 (cli-only)
@angular-devkit/schematics    15.0.5 (cli-only)
@schematics/angular           15.0.5 (cli-only)
typescript                    4.8.4
```

**Comment by alan-agius4** [comment] 2023-03-28 08:44
I'm sorry, but we can't reproduce the problem following the instructions you provided. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2023-04-20 10:31
Closing due to the lack of a reproduction.

**Closed by alan-agius4** 2023-04-20 10:31 UTC
Labels: needs: repro steps
