### ISSUE TITLE
`ng build` chokes on processing Angular source maps

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#5476] opened 2017-03-17 15:25 UTC
### Bug Report or Feature Request (mark with an `x`)
- [X] bug report -> please search issues before submitting

### Versions.
```
@angular/cli: 1.0.0-rc.2
node: 6.9.5
os: darwin x64
@angular/animations: 4.0.0-rc.4
@angular/common: 4.0.0-rc.4
@angular/compiler: 4.0.0-rc.4
@angular/core: 4.0.0-rc.4
@angular/forms: 4.0.0-rc.4
@angular/http: 4.0.0-rc.4
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0-rc.4
@angular/platform-browser-dynamic: 4.0.0-rc.4
@angular/platform-server: 4.0.0-rc.4
@angular/router: 4.0.0-rc.4
@angular/service-worker: 1.0.0-beta.7
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 4.0.0-rc.2
```

### Repro steps.
1. upgrade a project to angular 4.0.0-rc.4
2. modify `node_modules/@angular/cli//models/webpack-configs/common.js
` to no exclude `node_modules` from the `source-map-loader`
3. build the project with `ng build` or `ng build --prod --sm`

### The log given by the failure.
```
$ ng build --prod --sm
 92% chunk asset optimization/Users/iminar/Dev/angular/aio/node_modules/source-map/lib/source-node.js:95
          var code = nextLine.substr(0, mapping.generatedColumn -
                             ^

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (/Users/iminar/Dev/angular/aio/node_modules/source-map/lib/source-node.js:95:30)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/iminar/Dev/angular/aio/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/Users/iminar/Dev/angular/aio/node_modules/source-map/lib/source-node.js:80:24)
    at SourceMapSource.node (/Users/iminar/Dev/angular/aio/node_modules/webpack-sources/lib/SourceMapSource.js:42:20)
    at ReplaceSource.node (/Users/iminar/Dev/angular/aio/node_modules/webpack-sources/lib/ReplaceSource.js:69:29)
    at CachedSource.node (/Users/iminar/Dev/angular/aio/node_modules/webpack-sources/lib/CachedSource.js:12:23)
    at /Users/iminar/Dev/angular/aio/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Users/iminar/Dev/angular/aio/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /Users/iminar/Dev/angular/aio/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Users/iminar/Dev/angular/aio/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /Users/iminar/Dev/angular/aio/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Users/iminar/Dev/angular/aio/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
```

### Desired functionality.
should build 😄

**Comment by Brocco** [comment] 2017-03-17 19:30
This was related to an issue in the angular repo angular/angular/pull/15226 and is resolved with the newly released rc5. It will work with the CLI once #5480 is resolved.

**Comment by IgorMinar** [comment] 2017-03-20 15:42
Unfortunately, I can still reproduce the issue with @angular/core@4.0.0-rc.5 and zone.js@0.8.4.

```
$ ng build
 92% chunk asset optimization/Users/iminar/Dev/angular/aio/node_modules/source-map/lib/source-node.js:95
          var code = nextLine.substr(0, mapping.generatedColumn -
                             ^

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (/Users/iminar/Dev/angular/aio/node_modules/source-map/lib/source-node.js:95:30)
```

**Comment by hansl** [comment] 2017-03-20 19:38
I can't repro locally with just enabling the node modules source maps. It builds (but takes twice the amount of time):

```
$ npm ls @angular/core
test-decorators@0.0.0 /Users/hansl/Sources/_Temp/test-decorators
├─┬ @angular/cli@1.0.0-rc.2 -> /Users/hansl/Sources/angular-cli
│ ├── @angular/core@4.0.0-rc.5  extraneous
│ └── UNMET PEER DEPENDENCY zone.js@0.7.8
```

**Comment by IgorMinar** [comment] 2017-03-20 23:39
@hansl looked into it more and said that it's due to incorrect source maps coming from `@angular/material@2.0.0-beta.2`

If I remove all material source maps using:
```
for i in `find node_modules/\@angular/material/ -name "*.js.map"`; do echo $i; rm $i; done
```
the error goes away.

**Comment by hansl** [comment] 2017-03-21 02:18
Apparently it's a known error in source-map: https://github.com/mozilla/source-map/issues/247 and related in ionic: https://github.com/driftyco/ionic-app-scripts/issues/796

As long as that issue is not fixed, we cannot really enable source maps in node_modules. Let's chat tomorrow @IgorMinar

**Comment by IgorMinar** [comment] 2017-03-21 05:57
@hansl we could fork the project with this patch: https://github.com/mozilla/source-map/pull/257#issuecomment-287984444. I verified that it works.

**Comment by hansl** [comment] 2017-03-21 16:48
That would work (but the mapping might be invalid), I'm not sure if that's what we want. Let's talk during the weekly.

**Comment by hansl** [comment] 2017-03-21 22:18
Removing this from 1.0 BLOCKING. The plan is to get Mozilla to fix their `source-map` library (see issues pointed above). If that cannot be done in a timely fashion we will fork it locally in the CLI and use it for a custom loader instead.

**Comment by zackarychapple** [comment] 2017-05-16 17:33
This happens without modifying the CLI as well. We have been fighting this today.
```
@angular/cli: 1.0.3
node: 7.5.0
os: darwin x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.3
@angular/compiler-cli: 4.0.1
@angular/language-service: 4.0.1
```

**Comment by Brocco** [comment] 2017-07-14 21:07
I was not able to reproduce this issue...

get latest CLI locally
comment out [this line](https://github.com/angular/angular-cli/blob/962b028e7c30150df49dc1a15cdc6f573e1768f5/packages/%40angular/cli/models/webpack-configs/common.ts#L70)

1. ng new src-map --link-cli
1. npm install --save @angular/cdk
1. npm install --save @angular/material2
1. import `MdButtonModule` in app.module.ts
1. update app.component.html to use `md-button`
1. run `ng build --prod --sm` which builds successfully

**Closed** 2017-07-14 21:13 UTC
Labels: command: build, priority: 1 (urgent), type: bug
