### ISSUE TITLE
core-js 

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular-cli#14310] opened 2019-04-30 09:52 UTC
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

no

### Description

using `ng update core-js` will success but when trying to build/serve the application it will fail

## 🔬 Minimal Reproduction

```
ng new project-name
cd project-name
ng update core-js
ng s
```

## 🔥 Exception or Error
<pre><code>
ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
Module not found: Error: Can't resolve 'core-js/es6/array' in 'C:\Users\rober\ng7\core-js\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'

</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 11.11.0
OS: win32 x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**
no

**Comment by clydin** [comment] 2019-04-30 13:58
Duplicate of #13954

Please see this comment specifically for more details: https://github.com/angular/angular-cli/issues/13954#issuecomment-485822832

**Closed by clydin** 2019-04-30 13:58 UTC

**Comment by robertIsaac** [comment] 2019-04-30 15:31
> Duplicate of #13954
> 
> Please see this comment specifically for more details: [#13954 (comment)](https://github.com/angular/angular-cli/issues/13954#issuecomment-485822832)

you misunderstand me

for example when  you try to update typescript it shows
```
$ ng update typescript
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=3.1.1 <3.3", would install "3.4.5").
Incompatible peer dependencies found. See above.
```

and it doesn't update it, i'm not reporting that angular doesn't support core-js, but that ng update allow updating core-js normally

this issue is very tricky when you want to update an old project

maybe it's something wrong with how i do it, so here is my steps
1. run `ng update --all` and copy the warnings to external file
2. run `ng update --all --force` 
3. downgrade the Incompatible dependencies in step 1 manually inside `package.json` 
4. run `npm i`
