### ISSUE TITLE
TypeError: Cannot read property 'glob' of null

### ISSUE THREAD

**Issue by erolyapici** [angular/angular-cli#6234] opened 2017-05-09 10:59 UTC
I got error when I run ng serve;
```

@angular/cli: 1.0.2
node: 7.4.0
npm 4.0.5
os: darwin x64
```

I installed
`  npm install -g @angular/cli
`then commang this its ok.

` ng --version
`result:```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.2
node: 7.4.0
os: darwin x64

```
Create new project my-app that's ok.
` ng new my-app
`

When I go my-app directory and run ng serve i got this error```

Cannot read property 'glob' of null
TypeError: Cannot read property 'glob' of null
    at ObjectSchemaTreeNode._set (projects/tmp/myApp/node_modules/@ngtools/json-schema/src/schema-tree.js:224:131)
    at new ObjectSchemaTreeNode (projects/tmp/myApp/node_modules/@ngtools/json-schema/src/schema-tree.js:209:14)
    at OneOfSchemaTreeNode._createChildProperty (projects/tmp/myApp/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (projects/tmp/myApp/node_modules/@ngtools/json-schema/src/schema-tree.js:161:25)
    at Array.map (native)
    at OneOfSchemaTreeNode (projects/tmp/myApp/node_modules/@ngtools/json-schema/src/schema-tree.js:160:48)
    at ArraySchemaTreeNode._createChildProperty (/projects/tmp/myApp/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)
    at ArraySchemaTreeNode._set (/projects/tmp/myApp/node_modules/@ngtools/json-schema/src/schema-tree.js:286:39)
    at new ArraySchemaTreeNode projects/tmp/myApp/node_modules/@ngtools/json-schema/src/schema-tree.js:267:14)
    at ObjectSchemaTreeNode._createChildProperty (/projects/tmp/myApp/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)

```

**Comment by balr404** [comment] 2017-05-09 22:56
I have tried the following option to resolve 
Steps to resolve the issue
1.  $ pwd  
   it shows  —> /Users/YourName  /*** That is your Home path***/

Execute the below command to display the hidden files

2. $ defaults write com.apple.Finder AppleShowAllFiles true
3.  $ killall Finder

After executing the above command you will see the hidden files.
if “.angular-cli.json” file exist under “/Users/yourname” (i.e Home Path) then remove “.angular-cli.json” file.

then navigate to your application path and try execute ‘ng’ command.

**Comment by filipesilva** [comment] 2017-05-10 11:57
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/4207. Please subscribe to that issue for future updates.

**Closed by filipesilva** 2017-05-10 11:57 UTC

**Comment by kiranpalkathait** [comment] 2017-06-09 21:39
Thank you so much @balr404

**Comment by kurmivivek295** [comment] 2018-08-08 06:10
I got the same issue, I ran npm install @angular/cli command on visual studio code terminal, and it's working. I am using Windows OS. Thanks.
